### ISSUE TITLE
LuckPerms PermissionsEx Migration Error (Something to do with prefixes?)

### ISSUE THREAD

**Issue by stormtrooper28** [lucko/LuckPerms#1]
When attempting to migrate from permissionsEx via the console (specifically "lp migration permissionsex") I run into the following _prefix-is-not-a-uuid_ error:

http://pastebin.com/zGNmzZ7F

I just downloaded the latest version of LuckPerms (2.5.5) and PermissionsEx (1.23.4) prior to attempting this.

Plugins (21): CoreProtect, AsyncWorldEditInjector, dynmap, MultiWorld, WorldEdit, ImageMaps, AsyncWorldEdit, CPCameraStudio, PermissionsEx, SWROTR_Utility(Custom Plugin), AlwaysOnline, CrackShot, Chairs, Ships, Vault, notnt, Cannons, LuckPerms, Essentials, CraftBook, EnjinMinecraftPlugin

**Comment by lucko** [comment]
Weird... 

The "identifier" of a user in your PEX setup is just "prefix". I can only assume that was a command mistake in the past sometime, that has corrupted your dataset.

Hopefully 692bf30cf59a84d7449ce8f3dcb0387b1290b54c will fix it?? I've added a few extra methods to try and find uuids. Unfortunately, there's no native method to just get a UUID from an internal user. I know PEX has uuid support, but not to much of an extent, unless I'm overlooking something. 😞 

https://ci.lucko.me/job/LuckPerms/52/
Grab a download from above and let me know if it works. Worst case scenario now is that it will just skip the user if it can't get their UUID. It will notify you of that in the console though.

If it still doesn't work, would you mind linking your permissions.yml file, or whatever it's called. 😃

**Comment by stormtrooper28** [comment]
Thank you! This new version has fixed it!

**Comment by lucko** [comment]
🎉🎉🎉
