### ISSUE TITLE
Reload support

### ISSUE THREAD

**Issue by lucko** [lucko/LuckPerms#100]
^

via PlugMan o.e. and a command.

**Comment by M9GLiquid** [comment]
Very usefull to be able to fast reload the server when developing, your plugin currently don't shutdown properly on reload (Bukkit/Spigot)

**Comment by lucko** [comment]
Reload support isn't as easy as I thought. Switching storage types, etc, whilst the server is still running is going to be difficult and buggy.

I've fixed the plugin cleanup issue, so at least now you can use Bukkit's /reload or PlugMan to reload the entire plugin without too many issues.

**Comment by Bjornskjald** [comment]
On the latest version (v4.2.75) it still bugs out on reload, hangs the whole server and doesn't let the players join
