### ISSUE TITLE
Vault throwing CME on startup 

### ISSUE THREAD

**Issue by JamieSinn** [lucko/LuckPerms#1001]
https://github.com/MilkBowl/Vault/issues/719

**Comment by JamieSinn** [comment]
@andrewkm would be best to ask for that. 
Sleaker thinks it's related to papermc.

**Comment by andrewkm** [comment]
Issue seems to have disappeared. Super confused.

**Comment by andrewkm** [comment]
It was on server start.
We never use reloads.

**Comment by lucko** [comment]
Yeah, guessing another plugin then, unfortunately the CME only tells you about one of the processes modifying

Not an LP issue though, so gonna close this
