### ISSUE TITLE
Can't unset a permission.

### ISSUE THREAD

**Issue by Aerocet** [lucko/LuckPerms#1009]
I uninstalled a plugin (ChatControl Pro) and want to remove a permission, so here's the details:

`>lp group administrator permission info`
`[14:14:19 INFO]: [LP] administrator's Permissions:  (page 1 of 1 - 6 entries)`
`[14:14:19 INFO]: > chatcontrol.groups.* (false)`
`[14:14:19 INFO]: > griefprevention.* (false)`
`[14:14:19 INFO]: > '*' (true)`
`[14:14:19 INFO]: > griefprevention.admin (true)`
`[14:14:19 INFO]: > vanish.joinvanished (false)`
`[14:14:19 INFO]: > vanish.silentjoin (false)`
`>lp group administrator permission unset chatcontrol.groups.*`
`[14:14:40 INFO]: [LP] Unset chatcontrol.groups.* for administrator in context global.`
`[14:14:40 INFO]: [LP] [Sql Messaging] Sending log with id: [big-ass number]`
`[14:14:43 INFO]: [LP] [Sql Messaging] Sending ping with id: [big-ass number]`
`>lp group administrator permission info`
`[14:14:46 INFO]: [LP] administrator's Permissions:  (page 1 of 1 - 6 entries)`
`[14:14:46 INFO]: > chatcontrol.groups.* (false)`
`[14:14:46 INFO]: > griefprevention.* (false)`
`[14:14:46 INFO]: > '*' (true)`
`[14:14:46 INFO]: > griefprevention.admin (true)`
`[14:14:46 INFO]: > vanish.joinvanished (false)`
`[14:14:46 INFO]: > vanish.silentjoin (false)`

The permission still remains after the unset command appeared to succeed.

**Comment by Aerocet** [comment]
What do you mean by clear the context completely? (For what it's worth, unset worked on every other group.)

**Comment by lucko** [comment]
Which version of LP?

Looks like a bug, but I can't reproduce it using the latest version
