### ISSUE TITLE
Permissions not applying immediately - LP v4.2.12

### ISSUE THREAD

**Issue by RussianRonin** [lucko/LuckPerms#1010]
So, I noticed when editing permissions on my server, they are not applying immediately. I have to disconnect and reconnect my Member (default) account for the permission to take effect.

Example:
Default inherits mem_essentials. mem_essentials has essentials.help set to true. Member has access to help. Owner runs /lp group mem_essentials permission unset essentials.help. Member still has access to essentials /help command. Both players are on the same server. Bungeecord is setup properly. Messaging goes through with no errors. Member loses access to essentials /help when they reconnect.

Also, both clients are running on the same computer... not sure is this will be an issue but worth mentioning.

**Comment by StiegeRobin** [comment]
Same problem here on Spigot 1.12.2. You cannot sync the permissions with /lp sync.
You need to reload/restart the whole server to apply permissions.

**Comment by lucko** [comment]
Thanks for reporting, should be fixed in the latest version
