### ISSUE TITLE
Error when having enabled-op false

### ISSUE THREAD

**Issue by JoeSGT** [lucko/LuckPerms#1016]
https://pastebin.com/raw/tMwaw83Z when you have enabled op set to false and then attempt to `op` in console you get the error and also a way to bypass this in console you can do `minecraft:op` i have my reason why i want this op thing fully disabled so you can please patch this also the version i am running on is LuckPerms v4.2.7

**Comment by lucko** [comment]
Did you install/update LP by reloading your server?

**Comment by JoeSGT** [comment]
no i restarted the server

**Comment by lucko** [comment]
Please can you try:

* Completely stopping your server
* Replacing the LP jar you have currently with the one available here: https://luckperms.github.io/
* Starting your server

and then trying to reproduce the issue again.

**Comment by JoeSGT** [comment]
https://pastebin.com/gtSTrQGb

same and also i am using Thermos i do have the special source update it one and also use the latest LuckPerms-Bukkit-Legacy on https://luckperms.github.io/

**Comment by lucko** [comment]
Error is being thrown on this line

https://github.com/lucko/LuckPerms/blob/b7de0e6901cb1b800b6f13ae7f577b5c8c49c38b/bukkit/src/main/java/me/lucko/luckperms/bukkit/listeners/BukkitPlatformListener.java#L83

Most likely a Thermos issue, not LuckPerms.

I suggest reporting the error to the Thermos issue tracker.
