### ISSUE TITLE
New config option! (an idea)

### ISSUE THREAD

**Issue by AeSix** [lucko/LuckPerms#1018]
This isn't the grandest of ideas, but *shrug*

Have a config option which allows owners to deny all nodes from minecraft and bukkit built-in permissions.  There are a set of permissions which are usable by default.  This would bring these permissions in-line with plugin permissions, which are all denied by default (Maybe a few plugin-defined exceptions?)

This would require owners firstly to enable this option in the config, but then once enabled force them to explicitly give these permissions to their groups.  These permissions would still be naturally allowed if this config option is disabled. 

In my opinion as a systems admin, two things which when implemented that should block everything until a specific hole is created are firewalls and permission management systems.  Bukkit and Minecraft permissions seem to be ignored, or purposefully allowed, which honestly just drives me batty.  There should be similar for Bungee, Sponge, etc as well, where needed, if needed.

Anyways, I said it wasn't a great idea, but it is an idea :P

**Comment by RussianRonin** [comment]
Already exists.

https://github.com/lucko/LuckPerms/wiki/Configuration#apply-bukkit-default-permissions

**Comment by AeSix** [comment]
Indeed this does exactly what I was requesting. 

The wording in both the wiki and the plugin help suggest this is referring to bukkit /plugins/ 
Clarification could be added to the wiki:
"Setting this to false disables all of bukkit's built-in commands and permission-backed functions" Or something. 

Thank You for the quick response Russian! :)
