### ISSUE TITLE
SubjectProxy getPermissionValue performance

### ISSUE THREAD

**Issue by bloodmc** [lucko/LuckPerms#1020]
I managed to capture a perf issue with getPermissionValue using LP 4.2.14

[<img src="https://i.imgur.com/dGDEExt.png">](https://i.imgur.com/dGDEExt.png)

Any room for improvement?

**Comment by lucko** [comment]
Yes looks like there is. :)

What steps did you take to reproduce this? Is it something I'd be able to easily do on my own server locally?

**Comment by bloodmc** [comment]
1. Setup server with SpongeForge, Worldedit, GP, SF, LP
2. Equip wooden axe
3. Select 2 points (the more blocks between the better)
4. Execute command '//set water'
5. Execute command '//undo'

Repeat steps 4 and 5 to reproduce lag.
