### ISSUE TITLE
I can be owner without op  even though i am admin

### ISSUE THREAD

**Issue by DiamondTheo** [lucko/LuckPerms#1027]
i am admin but i can do [/lp user DiamondTheo parent set Owner] and it works with pex you can't go to a group higher than you are, you can't promote yourself

**Comment by Wqrld** [comment]
well, don't give people that you don't fully trust luckperms access.

**Comment by DiamondTheo** [comment]
help

**Comment by lucko** [comment]
If you want to prevent people in lower groups from promoting themselves, you need to setup argument based permissions for LP commands.

More information on that can be found here.
https://github.com/lucko/LuckPerms/wiki/Argument-based-command-permissions
