### ISSUE TITLE
/lp import uses wrong path on SpongeForge

### ISSUE THREAD

**Issue by md678685** [lucko/LuckPerms#1028]
When running `/lp import permsexport`, I get the following output:
```
[LP] Error: File /home/server/ms3/4.1.1/./luckperms/permsexport does not exist.
```

It appears LP determines the path from the server root to the config directory is `./luckperms/`, not `config/luckperms/`.

SpongeAPI: 7.1.0-SNAPSHOT-43d8496
SpongeForge: 1.12.2-2705-7.1.0-BETA-3136
Forge: 14.23.4.2705
LuckPerms: 4.2.19

**Comment by lucko** [comment]
Bit confused

https://github.com/lucko/LuckPerms/blob/8cf0f7da5fc9382669d66ce65544eb41457aca52/sponge/src/main/java/me/lucko/luckperms/sponge/LPSpongeBootstrap.java#L244

**Comment by lucko** [comment]
(it's meant to target `/luckperms/`, but not `./luckperms/` as in the error you posted

**Comment by md678685** [comment]
Does Sponge's `@Inject @ConfigDir(sharedRoot = false)` on a field work correctly? I don't know how that internally determines the right directory, but it seems to point to `config/<plugin>/` from my experience.

**Comment by lucko** [comment]
Yes it does, but LP data isn't stored there.

**Comment by md678685** [comment]
That's a misunderstanding on my part, then, though I agree the `./` doesn't make sense.

**Comment by lucko** [comment]
Just got a chance to look a bit deeper into this issue.

Seems to be a SpongeForge bug - can't reproduce this on SV - so will submit a fix there.
