### ISSUE TITLE
Default Minecraft Commands

### ISSUE THREAD

**Issue by XarthDev** [lucko/LuckPerms#1030]
Can't figure out a way to remove all default minecraft commands (/plugins, /kill, etc.) Yes I know NCP and even Essentials gives a way to remove them yet when I add them to the deny list they still run regardless.

**Comment by RussianRonin** [comment]
You can only set LuckPerms to use explicit permissions with this config option. This means that ONLY permissions you apply in LuckPerms will be used.

https://github.com/lucko/LuckPerms/wiki/Configuration#apply-bukkit-default-permissions

**Comment by lucko** [comment]
In addition to what's been suggested above:

`/lp group default permission set minecraft.* false` will negate all permissions starting with `minecraft.`
