### ISSUE TITLE
Error Mysql

### ISSUE THREAD

**Issue by xGlenor** [lucko/LuckPerms#1033]
Hello
I have 2 servers connected with the mysql database
that's it ss
https://prnt.sc/jqd7f8

Please help

**Comment by BrainStone** [comment]
That’s a warning, not an error.

The plugin should operate as normal.

**Comment by lucko** [comment]
Indeed, should be fine to ignore, although it might suggest that your server is lagging a bit.

**Comment by lucko** [comment]
The above change will fix the warning message from appearing.

However, it won't fix the underlying issue, which is that your MySQL server is taking a long time to respond.
