### ISSUE TITLE
OP Not working and Perms not working properly 1.12.2

### ISSUE THREAD

**Issue by LeeRy30** [lucko/LuckPerms#1034]
I was wondering if anybody could help me please... We've just migrated from PEX however our ops don't have the ability to do everything as they used to, it is set in the config to allow them to, tried using the autoop and the perm but that doesn't work either, tried * that doesn't work, adding new perms for players and groups works sometimes, however we cannot unset or set them to false, they just remain there.

Any help would be hugely appreciated.
Tried the Discord and they couldn't help so sent us here.

Thanks

**Comment by LeeRy30** [comment]
To add to it, this is a bungee setup using MySQL which is set in all configs, bungee jar is installed and setup and messaging-service is set to sql

**Comment by lucko** [comment]
I need specific info to be able to help.

Specifically which permissions? Which commands did you run?
Outputs of `info` and `permission info` commands after setting the permissions?
Verbose reports showing which nodes are being checked, and what the results of each check are?

https://github.com/lucko/LuckPerms/wiki/Verbose
https://github.com/lucko/LuckPerms/wiki/Command-Usage:-User#lp-user-user-info
https://github.com/lucko/LuckPerms/wiki/Command-Usage:-Permission#lp-usergroup-usergroup-permission-info
https://github.com/lucko/LuckPerms/wiki/Command-Usage:-Parent#lp-usergroup-usergroup-parent-info

If I had to guess, I'd say double check that you have IP forwarding setup correctly.
https://github.com/lucko/LuckPerms/wiki/Network-Installation#pre-setup

**Comment by LeeRy30** [comment]
Managed to fix the permissions issue with the help of Discord but ops are still being limited by the permissions even though they are set to bypass in the config...
Verbose shows correct perms being checked 
If a perm is negated on default, ops can't use that command although the all commands allowed config option is set to true.

**Comment by XakepSDK** [comment]
What do you mean by saying `op`?

**Comment by XakepSDK** [comment]
What server software do you use? Bukkit-based or sponge-based?

**Comment by LeeRy30** [comment]
Bukkit based - Spigot - 1.12.2

**Comment by lucko** [comment]
Some commands are set with non-op defaults, in which case just setting `/op` won't work.

You could try setting a `*` permission, or disabling bukkit default permissions in the LP config.

**Comment by LeeRy30** [comment]
The * permissiondid not work - this was also tested.

**Comment by lucko** [comment]
Can you send a verbose recording link, and also an output for `/lp editor` please :)

**Comment by LeeRy30** [comment]
This is an example where essentials.balance was negated or unset (but negated in the default group) however I had the * permission (including essentials.* as a separate one) but I still got insufficient permission so had to add the permission separately!
Verbose: https://luckperms.github.io/verbose/?pb5EEPQ8ql
Editor: https://luckperms.github.io/editor/?vqWptDSdKf

Thanks for getting back to me again! =)

**Comment by lucko** [comment]
Oh right, yeah, that's intended behaviour.

Standard permissions will override wildcard assignments, even if the wildcard is assigned at a higher priority within the inheritance tree

**Comment by LeeRy30** [comment]
So there is no way to allow ops to use all commands without having to add the permission to them or their group? Not even * in the group works.

**Comment by lucko** [comment]
Just make sure they don't inherit from groups that negate permissions

**Comment by LeeRy30** [comment]
Okay, thank you for your help!

Hope you have a great day! =)
