### ISSUE TITLE
server Context with bungeecord

### ISSUE THREAD

**Issue by Hanarion** [lucko/LuckPerms#1038]
Hi, i don't know if it's a bug or a feature that doesn't exist but i have this problem :

I want to use different prefixes according to the server the player is connected to, for the chat i use gchat (your plugin) in order to connect all my servers chat but the luckperm prefix used by the chat plugin is the prefix of the bungee side so when i define the prefix with the server set to one of my servers the prefix doesn't shows cause the prefix isn't set for the bungee
So i tried with the context "server=" but when i set the server propertie to global to be sure it will work and the context "server=lobby" the prefix not showing up at all (it does the same with the server propertie set to bungee)

I think when the server is behind bungeecord the "server" context is always define with the bungee...

Thank you for helping me

**Comment by Brianetta** [comment]
In Bungee, the server name can be found in the world context. You'd want `world=lobby` as your context there.

**Comment by Hanarion** [comment]
Thank's you it works
