### ISSUE TITLE
Warning during startup (mediocre screenshot included)

### ISSUE THREAD

**Issue by Aerodog** [lucko/LuckPerms#1040]
Spigot has a message for you, good sir.

https://imgur.com/KgVCkes

**Comment by BrainStone** [comment]
Just use Java 8. There is currently no way to avoid this message on Java 9 and 10

**Comment by lucko** [comment]
Yeah uh, the message is printed by the Java runtime, not Spigot.

Currently no way around it, I'm kinda just waiting for a new way of achieving the same functionality to be added to the language.

**Comment by lucko** [comment]
(you can safely ignore the warning for now)
