### ISSUE TITLE
[API Problem] Setting someones rank!

### ISSUE THREAD

**Issue by GoNotCougsWA** [lucko/LuckPerms#1043]
Hey, I have been trying to set someone to a group using the API and I cannot get it to set. Well, I kinda don't know how.. I looked at the Developer API wiki and I cannot find how to set a player's group in there so I tried myself to look through everything and the only thing I was able to find the User setPrimaryGroup method and It's not working. Is there a different way I can set the group? 

Here is what i am using if this is a issue: https://pastebin.com/raw/9az9YkS8

**Comment by lucko** [comment]
You do it by setting a "group node" - explained here: https://github.com/lucko/LuckPerms/wiki/Developer-API:-Usage#the-basics-of-node

**Comment by GoNotCougsWA** [comment]
Ok! Thanks!
