### ISSUE TITLE
Issue with NukkitX preventing plugin from working

### ISSUE THREAD

**Issue by PhanaticD** [lucko/LuckPerms#1046]
https://i.gyazo.com/5b54dfb54ef1a38a200e706b09704a37.png

plugin doesnt appear to be working, only other plugin on the server is https://github.com/funniray/EssentialsNK which should format the chat. (error occurs even without essentialsnk)

according to dev of nukkitx you are trying to inject into a final field (or something like that)

**Comment by lucko** [comment]
Issue was because Nukkit uses a Set, not a list :)

Thanks for reporting
