### ISSUE TITLE
Web Editor Session doesn't appear in the Console

### ISSUE THREAD

**Issue by FoxMcloud5655** [lucko/LuckPerms#1047]
I am not 100% sure if this is a LuckPerms problem or a McMyAdmin problem, but when I attempt to get an editor session from console (ex. /lp editor), the line that contains the link never shows up.

I believe it is because data that is provided as a clickable link to the player is not supported by the console, therefore it doesn't show.  On my own plugins, I've had to check whether or not the current caller is a console or not, and display using the default method if it is, otherwise display the fancy clickable link.

**Comment by haoteng10** [comment]
I think you have to do /lp {user} editor or /lp {group} editor.

**Comment by electronicboy** [comment]
Platform? lp editor works fine here, but I don't use a control panel; Control panels are kinda known for mangling stuff like URLs shown in the console; I know Spigot lets you send clickable text to the console, just the clickable stuff will be stripped as it's converted to a legacy string automatically

**Comment by FoxMcloud5655** [comment]
It must be a problem with McMyAdmin then, as the line containing said text never appears.  It's not too hard to convert it within the plugin before sending it into the console, so if you'd like to be just that much more compatible, I think I could propose a change and send in a pull request (after testing it, of course).

**Comment by lucko** [comment]
It already gets converted

https://github.com/lucko/LuckPerms/blob/8b181b877bfb87b66e49927b8c6e10c3a84d741e/bukkit/src/main/java/me/lucko/luckperms/bukkit/BukkitSenderFactory.java#L86-L104

line 103


So yea, this is definitely an issue with your panel

**Comment by FoxMcloud5655** [comment]
Whoops.  Forgot to mention that it's the Sponge version that I'm using on the server.  And yes, it is up-to-date.  Also, thank you very much for replying very quickly.  I love LuckPerms over every other permission plugin I've used.

**Comment by lucko** [comment]
Ah okay, in which case the conversion will be handled by Sponge / the Minecraft server.

**Comment by FoxMcloud5655** [comment]
Knowing nothing of how your plugin works, would changing this:
```
    @Override
    protected void sendMessage(CommandSource source, Component message) {
        source.sendMessage(TextSerializers.JSON.deserialize(ComponentSerializers.JSON.serialize(message)));
    }
```
to this:
```
    @Override
    protected void sendMessage(CommandSource source, Component message) {
        if (source instanceof Player) {
        	source.sendMessage(TextSerializers.JSON.deserialize(ComponentSerializers.JSON.serialize(message)));
        }
        else {
            source.sendMessage(TextSerializers.LEGACY_FORMATTING_CODE.deserialize(ComponentSerializers.JSON.serialize(message)));
        }
    }
```
be something that could provide a temporary fix until the McMyAdmin instance supports displaying the format or Sponge properly converts the fancy string, whatever the problem is?

**Comment by FoxMcloud5655** [comment]
Understood.  Thank you for your time.
