### ISSUE TITLE
Permissions applied until a player leaves the server

### ISSUE THREAD

**Issue by Leomixer17** [lucko/LuckPerms#1049]
An useful feature would be setting permissions/groups/prefixes/suffixes until a player leaves the server

**Comment by RussianRonin** [comment]
I WOULD say that this is already just default functionality because if they are not on the server, they do not have permissions. BUT, what I think you mean is that you have permissions based on your current session. When you disconnect, you lose whatever session perms you were given. Interesting idea.

**Comment by lucko** [comment]
Possible usecase?

**Comment by Leomixer17** [comment]
@lucko I was thinking, if someone wants to give players the possibility to join with a custom client or something like that, you could identify the players who use it

**Comment by lucko** [comment]
This can already be achieved via the Bukkit API :)

https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/permissions/PermissionAttachment.html

**Comment by Leomixer17** [comment]
Yes, but this would be an useful feature

**Comment by lucko** [comment]
Yes, but I don't see when you'd ever need to assign "transient" permissions via a command call - and therefore don't think it makes sense for a whole new set of commands in LP for it

**Comment by Leomixer17** [comment]
it may be useful to integrate this feature with plugins that do not directly support this feature but can execute commands

**Comment by lucko** [comment]
I'm not so sure, I think it would make more sense for it to be written into a separate plugin.

Thanks for the suggestion, but I don't think it's appropriate for LP
