### ISSUE TITLE
[FEATURE] Server Groups

### ISSUE THREAD

**Issue by ConflictKingdoms** [lucko/LuckPerms#1051]
__**Feature Request**__

so /lp ServerName Editor

so show off the ranks in that server group only.

so you have 1 big database with 10+ ranks for 2 servers.

/lp editor 
u can see every rank etc.

you get a cmd called 

/lp create **ServerName**

/lp Add Group **ServerName**

when you do

/lp **ServerName** Editor u see all ranks on that server u have added

idk if LP has this kind of feature already but i think it would be useful in my opinion when u can edit 1 server at a time with ranks etc.

let me know what you guys think

this would be awesome to have 

**PS** this is just example

**Comment by lucko** [comment]
Yes, you can use the server context to do this.

https://github.com/lucko/LuckPerms/wiki/Context
