### ISSUE TITLE
Will LuckPerms prevent autocompleting of commands if they don't have permission for it?

### ISSUE THREAD

**Issue by MorphGamer** [lucko/LuckPerms#1053]
I was wondering if LuckPerms preventing autocompleting of commands they don't have permission to. I was wondering because I would like the players to be able to only auto tab complete commands that they have permission to. I think it would make it easier for the players experience.
So when a player does /+tab it would give a list of commands.
But I want when a player does /+tab to give only a list of commands they have access to.

**Comment by BrainStone** [comment]
LuckPerms does nothing with the tab complete. However I know for sure Sponge only lists commands the player has permissions to. And I think Spigot behaves the same.

**Comment by lucko** [comment]
^

This is a Spigot level thing - not much LP can do about it :)
