### ISSUE TITLE
LuckPermsBungeeCord v 4.2.3.1

### ISSUE THREAD

**Issue by tmoflash** [lucko/LuckPerms#1054]
I could not get luckperms to load into bungeecord. BungeeCord would not crash but not configs were created.
Here is the log file. I used an older version and everything seems to be working fine, but I wanted to bring this to you all's attention. I was using the latest version of bungeecord and I also tried waterfall, both provided same outcome.

Logfile: https://hastebin.com/pinevafexi.md

**Comment by Turbotailz** [comment]
Further information:

LuckPerms would not load correctly on BungeeCord with version 4.2.31 (errors in hastebin link above).
I suggested to try an older version that I know works on BungeeCord (4.2.22) and it seems to work fine. Not sure which version in between that has broken compatibility with Bungee.
tmoflash said they are running the latest version of BungeeCord.

**Comment by Turbotailz** [comment]
Possibly 4.2.30 that breaks it
https://i.imgur.com/d0sSzQN.png

**Comment by BrainStone** [comment]
4.2.30 also broke Sponge. Test your stuff mate :P

**Comment by lucko** [comment]
> Test your stuff mate :P

testing is overrated

**Comment by lucko** [comment]
Thanks for reporting, should be fixed in the latest release :)
