### ISSUE TITLE
Feature: Add Groups of worlds or "world sets"

### ISSUE THREAD

**Issue by K1ish** [lucko/LuckPerms#1055]
Hello,
I'd like to request that you add groups of worlds.
When I am trying to have a permission apply on a specific set of worlds (Not globally) I have to duplicate the permission node in the editor 4 times for each world. 
Can you add it so you can (in config.yml) set multiple "sets" of worlds. You would be able to have a permission's world as the name of a "world set" you have configured and the set would refer to multiple other worlds it would then take only one permission node to apply to multiple worlds. 

Thanks.

**Comment by Andre601** [comment]
Just create a group and apply the permissions to it.
Then you can add or set the group to the user in a specific world using `/lp user <user> parent add/set <group> world=<world>`

**Comment by K1ish** [comment]
Please read what I wrote, that isn't what I'm talking about.

**Comment by lucko** [comment]
You can use the world rewrite settings to achieve a similar outcome

https://github.com/lucko/LuckPerms/blob/957a918bd6aa315b5cda8a9df7f7124aa3124aee/bukkit/src/main/resources/config.yml#L425-L431
