### ISSUE TITLE
Error whilst pushing changes to other servers.

### ISSUE THREAD

**Issue by RealMrRedNeck** [lucko/LuckPerms#1056]
How do i fix this?

**Comment by BrainStone** [comment]
Uhh. I’m sorry my crystal ball broke. I’m afraid we’ll need more info to help you solve your issue.

Things like server platform (like Bukkit), versions (of LP at minimum) and error logs.

**Comment by RealMrRedNeck** [comment]
I'm Using BungeeCord And All Servers are Spigot

**Comment by RealMrRedNeck** [comment]
I don't see anything in the error logs?

**Comment by BrainStone** [comment]
You must be seeing an error somewhere. What’s said error? Where does it appear, what’s the error message? What did you do that triggered that error.

**Comment by RealMrRedNeck** [comment]
/lp networksync How do you setup the messaging service?
![screenshot_1](https://user-images.githubusercontent.com/34854953/41517569-d755982c-7289-11e8-9611-bc7303f3d2b1.png)

**Comment by BrainStone** [comment]
Click the big fat wiki button on the top of this page and then click “Network Installation” on the right. There’s your tutorial.
