### ISSUE TITLE
SQL error

### ISSUE THREAD

**Issue by MithrandirCraft** [lucko/LuckPerms#1057]
LP v. 4.2.22
Spigot: 1.12.2

`[16:26:58 WARN]: luckperms - Failed to validate connection me.lucko.luckperms.lib.mariadb.MariaDbConnection@100cc072 (Connection.setNetworkTimeout cannot be called on a closed connection)
`

This error spams continuously on console, any clues on how to solve it? >_<

**Comment by BrainStone** [comment]
https://github.com/lucko/LuckPerms/wiki/Storage-system-errors#mysql-no-operations-allowed-after-connection-closed-error
