### ISSUE TITLE
Vault Suffix retrieval inconsistency

### ISSUE THREAD

**Issue by BiGUNMAN** [lucko/LuckPerms#106]
PlaceholderAPI suffixes do not work. My current highest priority suffix is the number "2": http://i.imgur.com/MljAUya.png output of /lp user (user) info

But my suffix is "1" which is a lower priority suffix.

Output of /papi parse %luckperms_suffix% is "1", which is a suffix I do have, but is lower priority.

**Comment by M9GLiquid** [comment]
I believe the ranks for suffix and prefixes and so on goes from low to high meaning rank 1100 is owner and 1 is default...

**Comment by lucko** [comment]
@BiGUNMAN Use the Vault placeholders instead.

**Comment by BiGUNMAN** [comment]
Vault placeholders also display "1" instead of "2".

**Comment by lucko** [comment]
Screenshot the output of:

```
/lp user <you> meta info
/lp info
```

**Comment by BiGUNMAN** [comment]
Here's output of /lp user (user) meta info: http://i.imgur.com/onB6mE7.png
Here's /lp info: http://i.imgur.com/rZ3sxm5.png

**Comment by lucko** [comment]
Yeah - very strange. I assume re-logging doesn't help? There's no reason why that data would be applying if you don't even have it.

**Comment by BiGUNMAN** [comment]
I do have it, but it's priority is lower. Priority of suffix "1" is 1,
priority of suffix 2 is 2.

**Comment by BiGUNMAN** [comment]
@lucko Hi, this is still an issue, could you reopen it? I can try and provide more information, idk what else you'd like to know. Take note, the suffix is in a non-primary group the user has. There are no suffixes overriding it, the priorities are set properly (with a lower number being a lower priority). It seems the meta isn't displaying the correct data but /lp user (user) info does.

**Comment by lucko** [comment]
There absolutely *must* be a reason why the other is taking priority.

Can you try setting the `vault-server` config option to the same as `server`. (make it "survival")

**Comment by BiGUNMAN** [comment]
Alright, that seems to have fixed it.

**Comment by lucko** [comment]
Ok, great. :)
