### ISSUE TITLE
Verbose details not displayed

### ISSUE THREAD

**Issue by SlimeDog** [lucko/LuckPerms#1060]
Spigot 1.12.2 latest
LuckPerms 4.2.36

I just noticed that verbose mode details are not displayed in the console/log. All I see is
VB > _playerName_

The details were displayed until recently, certainly end of May). I don't see a relevant configuration change since 4.2.2. Did I miss something?

**Comment by lucko** [comment]
Are you using a locale file?

**Comment by SlimeDog** [comment]
Yes, I am. But I edited only the prefix.

```
# diff plugins/LuckPerms/lang.yml plugins/LuckPerms/releases/4.2.36/locale/en_US.yml
5c5
< prefix: "[LP] "
---
> prefix: "&7&l[&b&lL&3&lP&7&l] "
```

**Comment by SlimeDog** [comment]
Well, that worked. But hardly the expected result. As an test, I tried
```
# LuckPerms Language File
# Locale: en_US (English)
# Author: Luck

prefix: "[LP] "
verbose-log: "VB > {0}"
```
(copied from the locale file, and again removing only the formatting codes). It displayed only
VB > _playerName_

In order to get the equivalent of the default verbose-log display (minus some of the formatting), I had to supply
```
verbose-log: "VB > {0} - {1} -{2} {3}"
```

**Comment by lucko** [comment]
Yes, the locale file is out-of-date at the moment.

The correct replacement is here:
https://github.com/lucko/LuckPerms/blob/6f96d9c7d161502d8abe09607b90ba4d1890ba62/common/src/main/java/me/lucko/luckperms/common/locale/message/Message.java#L70

**Comment by SlimeDog** [comment]
Thanks.

**Comment by SlimeDog** [comment]
I was leaving this open until the localization files were updated. Do you want me to open a separate ticket?

**Comment by lucko** [comment]
The locale files are generally updated once builds are pushed to Spigot/Ore as "stable". These changes aren't backwards compatible.

**Comment by SlimeDog** [comment]
Thanks.
