### ISSUE TITLE
Random permissions will be removed when it's synced via MariaDB

### ISSUE THREAD

**Issue by Muijf** [lucko/LuckPerms#1063]
First server:
PaperSpigot Version: https://gyazo.com/d2bdeceb61ad47684ff4ce86ece14e57
LuckPerms Version: v4.1.25

Second Server:
https://gyazo.com/b132ad19f462382ebd2477d824bf25ff
LuckPerms Version: v4.2.17

Third server:
https://gyazo.com/c1804f3a46f5870be1ef80b4a9b4498c
LuckPerms Version: v4.2.6

MariaDB version: Latest

**Comment by Andre601** [comment]
May I ask, why **you're using different LP-versions on different servers?!**

**Comment by lucko** [comment]
You've given absolutely no information about the issue - how to reproduce, when it happens, how often, etc etc


I have nothing to work with here. Please feel free to re-open when you have some more detailed information to give.
