### ISSUE TITLE
[QUESTION] is it possible to inherit all permission besides one permisson?

### ISSUE THREAD

**Issue by doron1803** [lucko/LuckPerms#1064]
Hey.
I have a ranking system, and I've made a custom plugin to show the prefixes and suffixes in the tab and chat. So I've added permission of:
chatandtab.none and chatandtab.vip and etc. I want VIP to inherit every single permission that none has, but not inherit the chatandtab.none. 

Is this possible?

Doron

**Comment by Andre601** [comment]
If another group has the required permissions, do
`/lp group <group that should get the perms> parent add <group that has the perms>`
and then deny the permission you don't want for the group with
`/lp group <group> permission set <permission> false`

**Comment by lucko** [comment]
```
/lp group vip permission set chatandtab.* true
/lp group vip permission set chatandtab.none false
```

Although, I'd suggest that you change your custom tab plugin to simply infer `.none` if they don't have any of the other permissions set
