### ISSUE TITLE
How do I add permissions for bukkit's custom commands?

### ISSUE THREAD

**Issue by POcketCraftServerNew** [lucko/LuckPerms#1066]
I know this isn't an issue, but I did not know where to ask this.  How do I add permissions for players to use bukkit's custom commands? For example, if I want them /warp lobby to execute when the do /lobby I know that all I have to do is give them permissions to do /warp lobby.  But what if I want /spreadplayers X Y Z to execute, or something like that?

**Comment by BrainStone** [comment]
The custom commands don't have permissions. The players need the permissions for running them.

And the Discord would've been a much better place to ask.

**Comment by lucko** [comment]
The permissions for Bukkit & Minecraft commands are listed here

https://bukkit.gamepedia.com/CraftBukkit_Commands#Bukkit_Commands_and_Permissions
