### ISSUE TITLE
Animatednames sometime don't use correct prefix

### ISSUE THREAD

**Issue by GuerreroCraft61** [lucko/LuckPerms#1068]
I have rank VIP, and it is a parent of defeault rank, is possible unparent buy only the rank prefix?

**Comment by lucko** [comment]
You've not really given me much info to work with.

Which placeholders are you using?
Which commands are you using to set the prefix?
Screenshots of the `info` and `meta info` commands for the users with incorrect prefixes?


Please re-open this issue after providing the above details.
