### ISSUE TITLE
Rank promotions options. Suggestion.

### ISSUE THREAD

**Issue by Carbonawk** [lucko/LuckPerms#1069]
Feature request. If I am in any way unclear please do say so.
Maybe this is already possible and I am not aware. Ignorance is bliss :p

Right now a lot of servers have multiple "groups" we call tracks, Within these tracks, we can promote.
A lot of communities have Groups like but not limited to "junior mod, mod, senior mod, discord mod, website mod, admin, owner"

Due to promoting someone from all the way from junior mod to admin would take a while, would be possible to have a promote command give an option of where to promote to and call that a side road? so we can't promote any further? But make promoting faster for other rank paths.

Skillful Illustration below  :cool:

![image](https://user-images.githubusercontent.com/25295327/41935623-9ae0db60-798a-11e8-99fd-38d048169514.png)

**Comment by Andre601** [comment]
Either make a seperate track with those groups or directly set/add the group to the user with
`/lp user <user> parent add/set <group>`

That would be my suggestion

**Comment by Carbonawk** [comment]
I am _not_ asking this because I can't do it differently. But, because I want to do it differently. I am asking it as this makes a lot more sense, especially from a career ladder view. 


See it like this.

All moderators/mods would have the same group, yet they would have a different function within this group. This is the same as saying all programmers are capable of doing the exact same work, which is not true. But they are all programmers. Therefore you would still be part of a group called programmers. (track)

However, you wouldn't per se value one programmer over another. They typically are all on the same floor. So promoting 20 times to reach a certain rank wouldn't make sense, and it's not easy to remember all ranks either.

This is a way of working a lot of businesses use because it works well. Not because it can't be done otherwise.

Adding more tracks wouldn't help as this does not deal with the point I am making. That would just make more tracks and split up the ranks, even more, meaning you still have to manually type the full name of a group every time. This would also make promoting useless as you can just set a new group.

Example B.

![image](https://user-images.githubusercontent.com/25295327/41937628-1abf8844-7991-11e8-8156-4e3072404c6a.png)

**Comment by lucko** [comment]
Perhaps tracks are what you're looking for? :wink:

https://github.com/lucko/LuckPerms/wiki/Tracks

**Comment by Carbonawk** [comment]
Actually, I already use tracks. I just reread it to be sure I didn't miss anything. But no.

![image](https://user-images.githubusercontent.com/25295327/41943020-25401f70-79a2-11e8-96a0-bd94b4ec32f9.png)

I plan on expanding these group heavily, however. If I have to promote many multiple times to achieve something that I can do with 1 command it would defeat the purpose of promoting for me.

The image below might be a bit small, but it is all I got to work with on the road lol. I will edit later if required.

![image](https://user-images.githubusercontent.com/25295327/41943620-687e9bf2-79a4-11e8-81a3-ef87cdd0d8dc.png)

**Comment by lucko** [comment]
Assuming you created track `mods`: consisting of "mod" up to "towny mod" as in the screenshot above

then:

`/lp user your-username parent settrack mods 6`

would promote the user to position 6, (towny mod)

https://github.com/lucko/LuckPerms/wiki/Command-Usage:-Parent#lp-usergroup-usergroup-parent-settrack

**Comment by Carbonawk** [comment]
aah I see, yes that would work. Now I just have to remember all groupnames 👍 

That is also why I gave the example of inputting option by number when a promote command is used. That way I wouldn't have to remember it all. :P Just a suggestion for the old folks. 

![image](https://user-images.githubusercontent.com/25295327/41946037-9d6c5ae6-79b0-11e8-9711-1d6d331c5e30.png)

**Comment by lucko** [comment]
Yep, you can use the number with the settrack command. :)
