### ISSUE TITLE
error while trying to use the luckyperm editor

### ISSUE THREAD

**Issue by douwe265** [lucko/LuckPerms#1072]
hi!

I've been trying to use the editor, but it keeps getting stuck at loading

> [16:46:46 INFO]: RainbowGodDouwe issued server command: /lp group default editor
> [16:46:52 WARN]: java.lang.RuntimeException: java.net.UnknownHostException: bytebin.lucko.me: Try again
> [16:46:52 WARN]: at me.lucko.luckperms.common.web.StandardPastebin.post(StandardPastebin.java:156)
> [16:46:52 WARN]: at me.lucko.luckperms.common.web.StandardPastebin.postJson(StandardPastebin.java:123)
> [16:46:52 WARN]: at me.lucko.luckperms.common.commands.generic.other.HolderEditor.execute(HolderEditor.java:72)
> [16:46:52 WARN]: at me.lucko.luckperms.common.commands.generic.other.HolderEditor.execute(HolderEditor.java:54)
> [16:46:52 WARN]: at me.lucko.luckperms.common.command.abstraction.MainCommand.execute(MainCommand.java:103)
> [16:46:52 WARN]: at me.lucko.luckperms.common.command.abstraction.MainCommand.execute(MainCommand.java:46)
> [16:46:52 WARN]: at me.lucko.luckperms.common.command.CommandManager.execute(CommandManager.java:202)
> [16:46:52 WARN]: at me.lucko.luckperms.common.command.CommandManager.lambda$onCommand$0(CommandManager.java:147)
> [16:46:52 WARN]: at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
> [16:46:52 WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> [16:46:52 WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> [16:46:52 WARN]: at java.lang.Thread.run(Thread.java:748)
> [16:46:52 WARN]: Caused by: java.net.UnknownHostException: bytebin.lucko.me: Try again
> [16:46:52 WARN]: at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
> [16:46:52 WARN]: at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
> [16:46:52 WARN]: at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
> [16:46:52 WARN]: at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
> [16:46:52 WARN]: at java.net.InetAddress.getAllByName(InetAddress.java:1192)
> [16:46:52 WARN]: at java.net.InetAddress.getAllByName(InetAddress.java:1126)
> [16:46:52 WARN]: at me.lucko.luckperms.lib.okhttp3.Dns$1.lookup(Dns.java:40)
> [16:46:52 WARN]: at me.lucko.luckperms.lib.okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:185)
> [16:46:52 WARN]: at me.lucko.luckperms.lib.okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:149)
> [16:46:52 WARN]: at me.lucko.luckperms.lib.okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:84)
> [16:46:52 WARN]: at me.lucko.luckperms.lib.okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:214)
> [16:46:52 WARN]: at me.lucko.luckperms.lib.okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
> [16:46:52 WARN]: at me.lucko.luckperms.lib.okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
> [16:46:52 WARN]: at me.lucko.luckperms.lib.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
> [16:46:52 WARN]: at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
> [16:46:52 WARN]: at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
> [16:46:52 WARN]: at me.lucko.luckperms.lib.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
> [16:46:52 WARN]: at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
> [16:46:52 WARN]: at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
> [16:46:52 WARN]: at me.lucko.luckperms.lib.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
> [16:46:52 WARN]: at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
> [16:46:52 WARN]: at me.lucko.luckperms.lib.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
> [16:46:52 WARN]: at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
> [16:46:52 WARN]: at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
> [16:46:52 WARN]: at me.lucko.luckperms.common.web.HttpClient$LuckPermsUserAgentInterceptor.intercept(HttpClient.java:87)
> [16:46:52 WARN]: at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
> [16:46:52 WARN]: at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
> [16:46:52 WARN]: at me.lucko.luckperms.lib.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
> [16:46:52 WARN]: at me.lucko.luckperms.lib.okhttp3.RealCall.execute(RealCall.java:77)
> [16:46:52 WARN]: at me.lucko.luckperms.common.web.HttpClient.makeCall(HttpClient.java:60)
> [16:46:52 WARN]: at me.lucko.luckperms.common.web.StandardPastebin.post(StandardPastebin.java:141)
> [16:46:52 WARN]: ... 11 more

help would be appreciated!

Douwe

**Comment by lucko** [comment]
Seems like Cloudflare is having DNS issues at the moment - nothing I can do about it, we've just got to wait for it to be resolved. :(

**Comment by lucko** [comment]
Resolved now afaik
