### ISSUE TITLE
Paid auto-rank feature?

### ISSUE THREAD

**Issue by itsjusttriz** [lucko/LuckPerms#1073]
Is it possible to set it to where, if someone was to pay for a rank on a custom made website, that it could send the info over to LuckPerms on the server, to basically "autorank" said player? 
e.g.

If i setup a purchase-able rank on BuyCraft or Enjin or something. And someone was to buy said rank.
then Enjin or Buycraft would automatically be able to send a command to the server like /lp user <name> promote <group>

**Comment by BrainStone** [comment]
You can already do promote. The wiki page for that is called “Tracks”.

Otherwise `/lp user <user> parent set <group>` or `/lp user <user> parent add <group>` are an option too

**Comment by DatNubTriz** [comment]
@BrainStone But how would the website know which ingame player had bought the rank?

**Comment by BrainStone** [comment]
Any Minecraft-Shop system requires you to enter your username. And that information is sent to the server.
