### ISSUE TITLE
Transfer players with rank to new rank

### ISSUE THREAD

**Issue by Max604** [lucko/LuckPerms#1074]
Hello, I couldn't manage to find a way to move all players part of group 1 to group 2.
Could someone please direct me in the right direction?

Thanks.

**Comment by BrainStone** [comment]
https://github.com/lucko/LuckPerms/wiki/Bulk-Editing

**Comment by Max604** [comment]
I've read the article and I cannot identify a way to update people's primary group to something else.

**Comment by BrainStone** [comment]
The primary group will update automatically (assuming you haven’t changed the settings regarding the primary group calculation)

**Comment by Max604** [comment]
Is it possible for me to change the identifier for each group and ensure that all members who were part of the group remain in that group?

**Comment by BrainStone** [comment]
Renaming the group won’t move all players with it.

**Comment by Max604** [comment]
What's your suggested method that I should try?

**Comment by BrainStone** [comment]
Bulkedit
