### ISSUE TITLE
applyedits command doesn't apply anything and do nothing

### ISSUE THREAD

**Issue by maxlehot1234** [lucko/LuckPerms#1076]
Hey Luck,

I have an issue with applyedits command after editing permissions with the webeditor? Command simply wont run in the server chat :(

Really bad thing since I need it to work to edit everything I have to edits in my groups

I try this command: /lp applyedits 5ctXXXXXX in the chat and the server console and same issue, it do nothing. No errors, no message in the console/chat.

This is the log file if you want it: https://hastebin.com/arujudujam.md

I also update to LuckPerms 4.2.42 and still do nothing :(

Do you have an idea for this?

Thanks again and have a nice day/night.

**Comment by maxlehot1234** [comment]
Works again now. Close it

**Comment by Yaboioioioioioi** [comment]
lol
