### ISSUE TITLE
Admin/Owner approval for editor changes

### ISSUE THREAD

**Issue by ThisTNTSquid** [lucko/LuckPerms#1077]
When given editor permission, the user is able to make changes to permission nodes through editor, but one must wait for approval from administrators / server owner with (maybe a new) luckperms admin permission before changes are made to the server

**Simplified workflow chart:**
User with "luckperm.editor" (without admin permission) --> opens editor--> make changes ---> server prompts server admin for changes ---> admins approve/reject changes 
server admin my be distinguished by "luckperms.admin"

**Comment by BrainStone** [comment]
Don’t give the player the `luckperms.applyedits` permission. That’s what’s needed to actually make changes.

Though you shouldn’t let players edit permissions anyways.

**Comment by ThisTNTSquid** [comment]
will that prompt admins for pending changes? 

p.s. I'm doing this to allow server managers to edit permissions by their own and wait for my approval so that i could do less but at the same time "knows" what they are attempting to change

**Comment by lucko** [comment]
You could just give your admins access to the editor, but not the applyedits permission, and ask them to send you the command link, for you to apply it.

Furthermore, the changes they make will all be appended to `/lp log`, so you could review them there.

I think a queued changes + review system is a bit overkill, and don't think it's really in-scope for inclusion within a permissions plugin.

**Comment by BrainStone** [comment]
Maybe a dry run flag, to preview the changes would be doable.

**Comment by lucko** [comment]
https://github.com/lucko/LuckPermsWeb/issues/34

**Comment by BrainStone** [comment]
But like ingame instead of the editor.
