### ISSUE TITLE
issue with unset BEC

### ISSUE THREAD

**Issue by madtomic** [lucko/LuckPerms#1078]
![image](https://user-images.githubusercontent.com/6004542/42258008-7dbd7c6c-7f27-11e8-89a9-dbcfe7f8b9fc.png)

what is the issue here? I have the permission but when trying to unset, it said I do not have it.

Using https://www.spigotmc.org/resources/betterenderchest.2073/

**Comment by BrainStone** [comment]
You need to specify all the contexts. So I’m your case you need to specify the server.

**Comment by madtomic** [comment]
Latest paperspigot build

**Comment by madtomic** [comment]
Contexts, sorry I misread your reply. I will try to give it more context and see what happen.

**Comment by BrainStone** [comment]
No no. I mean the permission has a server context specified (`server=hub`). And you need to specify that to delete it

**Comment by madtomic** [comment]
how come for some permission, I could unset permission without server context and only this plugin is giving me trouble?

**Comment by BrainStone** [comment]
Then those permissions simply didn’t have a context

**Comment by madtomic** [comment]
![image](https://user-images.githubusercontent.com/6004542/42275109-36c0dec2-7f5d-11e8-8e2d-142af87f6398.png)

**Comment by madtomic** [comment]
what am I doing wrong here? i use true and world and still giving me issue?

**Comment by madtomic** [comment]
I did some more testing and still don't work with any of the used context.

![image](https://user-images.githubusercontent.com/6004542/42275675-0faccd12-7f5f-11e8-9513-603cd7ab6793.png)

**Comment by madtomic** [comment]
The weird part is that the permission works in game.

**Comment by BrainStone** [comment]
The correct context is in the second pair of parentheses. 

And unset doesn’t allow `true` or `false`

**Comment by BrainStone** [comment]
So use `world=world` as context

**Comment by madtomic** [comment]
I understand now. Thank you for the explanation.
