### ISSUE TITLE
Unable to open editor (timeout?)

### ISSUE THREAD

**Issue by katalinea** [lucko/LuckPerms#1082]
First off, forgive me if this is a silly issue. I'm not very well versed with this sort of stuff, which is why i'm posting an issue. Yesterday I was able to open my web editor just fine, however when I tried today I was unable to. At first I thought it was taking a while, but after 3 minutes I still had not received the editor link, so I tried restarting my server and sending the command again. After I resent it I still did not get a link, so I checked my console and found a large error message. Here's the message:

https://hasteb.in/upuwozab.md

**Comment by Andre601** [comment]
Please use https://hastebin.com in the future to post errors.

And the site for the web-editor is currently down/unavailable and only Luck can fix that, so you have to be patient...

**Comment by katalinea** [comment]
Understood, thanks for letting me know!

**Comment by Andre601** [comment]
According to luck should the issue be fixed now
