### ISSUE TITLE
Illegal Reflective Access Warning on Spigot Server start.

### ISSUE THREAD

**Issue by joeberardis** [lucko/LuckPerms#1084]
Hello,

I noticed today when I ran my server that this warning appeared at start.

>WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by me.lucko.luckperms.common.dependencies.classloader.ReflectionClassLoader (file:/C:/Users/***%20********/Desktop/Minecraft%20Spigot%20Server/plugins/LuckPerms-Bukkit-4.2.17.jar) to method java.net.URLClassLoader.addURL(java.net.URL)
WARNING: Please consider reporting this to the maintainers of me.lucko.luckperms.common.dependencies.classloader.ReflectionClassLoader
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[15:01:40 INFO]: [LuckPerms] Loading LuckPerms v4.2.17

I am not sure what it means but as per the instructions it says to report it to you.

If there is any other information I can provide please let me know as I would be happy to assist with this issue.

Love your plugin btw, has helped so much in managing my small server.

Cheers,

Joe B.

**Comment by lucko** [comment]
It relates to changes made in Java 9 - there's nothing I can do about it for now, and you're safe to ignore the warning message. :)
