### ISSUE TITLE
Implement meta priority

### ISSUE THREAD

**Issue by sgdc3** [lucko/LuckPerms#1086]
I need to override the group order just for one meta value, this was already implemented for prefixes and suffixes, but it is missing for other custom meta values.

**Comment by codingJWilliams** [comment]
I second this - all my plugins use luckperms as a backend storage mechanism because its just so convenient, but there's a couple times I've had to try and figure out how to do this. It'd be great if this was implemented

**Comment by lucko** [comment]
I've had a go at implementing this, but not too happy with the result at this point.

3e62702c5d7b4db5568db304099977ad3d2dd839

If anyone wants to have a go at addressing the comments in that commit, then a PR would be appreciated. :)

Unless someone else wants to finish this up, I think it's unlikely that the feature will be added to the project.
