### ISSUE TITLE
The plugin won't connect to MySQL server

### ISSUE THREAD

**Issue by EmperorSuper** [lucko/LuckPerms#1087]
I've linked it to a MySQL server but it keeps erroring

When I try to log in:

> `[09:09:16 ERROR]: [LuckPerms] Exception occurred whilst loading data for 1c4a9f82-b0c7-4f85-a5c8-ee2c3c180351 - EmperorSuper
> [09:09:16 WARN]: java.util.concurrent.CompletionException: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5001ms.
> [09:09:16 WARN]:        at me.lucko.luckperms.common.storage.AbstractStorage.lambda$makeFuture$0(AbstractStorage.java:94)
> [09:09:16 WARN]:        at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
> [09:09:16 WARN]:        at me.lucko.luckperms.common.plugin.scheduler.AbstractJavaScheduler$WrappedRunnable.run(AbstractJavaScheduler.java:79)
> [09:09:16 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
> [09:09:16 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
> [09:09:16 WARN]:        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
> [09:09:16 WARN]:        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
> [09:09:16 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
> [09:09:16 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
> [09:09:16 WARN]:        at java.lang.Thread.run(Unknown Source)
> [09:09:16 WARN]: Caused by: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5001ms.
> [09:09:16 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:676)
> [09:09:16 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:190)
> [09:09:16 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:155)
> [09:09:16 WARN]:        at me.lucko.luckperms.lib.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
> [09:09:16 WARN]:        at me.lucko.luckperms.common.storage.dao.sql.connection.hikari.HikariConnectionFactory.getConnection(HikariConnectionFactory.java:128)
> [09:09:16 WARN]:        at me.lucko.luckperms.common.storage.dao.sql.SqlDao.getPlayerName(SqlDao.java:986)
> [09:09:16 WARN]:        at me.lucko.luckperms.common.storage.dao.sql.SqlDao.savePlayerData(SqlDao.java:916)
> [09:09:16 WARN]:        at me.lucko.luckperms.common.storage.AbstractStorage.lambda$savePlayerData$20(AbstractStorage.java:287)
> [09:09:16 WARN]:        at me.lucko.luckperms.common.storage.AbstractStorage.lambda$makeFuture$0(AbstractStorage.java:91)
> [09:09:16 WARN]:        ... 9 more
> [09:09:16 WARN]: Caused by: me.lucko.luckperms.lib.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
> 
> The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
> [09:09:16 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> [09:09:16 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
> [09:09:16 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
> [09:09:16 WARN]:        at java.lang.reflect.Constructor.newInstance(Unknown Source)
> [09:09:16 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.Util.handleNewInstance(Util.java:425)
> [09:09:16 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990)
> [09:09:16 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:342)
> [09:09:16 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2188)
> [09:09:16 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2221)
> [09:09:16 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2016)
> [09:09:16 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
> [09:09:16 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
> [09:09:16 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> [09:09:16 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
> [09:09:16 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
> [09:09:16 WARN]:        at java.lang.reflect.Constructor.newInstance(Unknown Source)
> [09:09:16 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.Util.handleNewInstance(Util.java:425)
> [09:09:16 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
> [09:09:16 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
> [09:09:16 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:428)
> [09:09:16 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:136)
> [09:09:16 WARN]:        at me.lucko.luckperms.lib.hikari.pool.PoolBase.newConnection(PoolBase.java:369)
> [09:09:16 WARN]:        at me.lucko.luckperms.lib.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:198)
> [09:09:16 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:467)
> [09:09:16 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool.access$100(HikariPool.java:71)
> [09:09:16 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:706)
> [09:09:16 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:692)
> [09:09:16 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
> [09:09:16 WARN]:        ... 3 more
> [09:09:16 WARN]: Caused by: java.net.ConnectException: Connection timed out: connect
> [09:09:16 WARN]:        at java.net.DualStackPlainSocketImpl.connect0(Native Method)
> [09:09:16 WARN]:        at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
> [09:09:16 WARN]:        at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
> [09:09:16 WARN]:        at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
> [09:09:16 WARN]:        at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
> [09:09:16 WARN]:        at java.net.PlainSocketImpl.connect(Unknown Source)
> [09:09:16 WARN]:        at java.net.SocksSocketImpl.connect(Unknown Source)
> [09:09:16 WARN]:        at java.net.Socket.connect(Unknown Source)
> [09:09:16 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:211)
> [09:09:16 WARN]:        at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:301)
> [09:09:16 WARN]:        ... 24 more`

On startup:

> `[09:07:57 INFO]: [LuckPerms] Enabling LuckPerms v4.2.42
> [09:07:57 INFO]:         __
> [09:07:57 INFO]:   |    |__)   LuckPerms v4.2.42
> [09:07:57 INFO]:   |___ |      Running on Bukkit - CraftBukkit
> [09:07:57 INFO]:
> [09:07:57 INFO]: [LuckPerms] Loading configuration...
> [09:07:58 INFO]: [LuckPerms] Successfully downloaded 'mysql_driver-5.1.46.jar' with matching checksum: MSIIl2HmQD8C6Kge1KLWWi4QKXNGUboA8uqS2SD/ex4=
> [09:07:58 INFO]: [LuckPerms] Successfully downloaded 'slf4j_api-1.7.25.jar' with matching checksum: GMSgCV1cHaa4F1kudnuyPSndL1YK1033X/OWHb3iW3k=
> [09:07:58 INFO]: [LuckPerms] Successfully downloaded 'slf4j_simple-1.7.25.jar' with matching checksum: CWbob/+lvlLT2ee4ndZ02YoD7tCkVPuvfBvZSTvZ2HQ=
> [09:07:58 INFO]: [LuckPerms] Successfully downloaded 'hikari-3.2.0.jar' with matching checksum: sAjeaLvYWBH0tujwhg0JZsastPLnX6vUbsIJRWnL7+s=
> [09:07:58 INFO]: [LuckPerms] Attempting to apply relocations to mysql_driver-5.1.46.jar...
> [09:07:59 INFO]: [LuckPerms] Attempting to apply relocations to hikari-3.2.0.jar...
> [09:07:59 INFO]: [LuckPerms] Loading storage provider... [MYSQL]
> [09:07:59 WARN]: [Server thread] INFO me.lucko.luckperms.lib.hikari.HikariDataSource - luckperms-hikari - Starting...
> [09:07:59 WARN]: [Server thread] INFO me.lucko.luckperms.lib.hikari.HikariDataSource - luckperms-hikari - Start completed.
> [09:08:04 ERROR]: [LuckPerms] Failed to init storage dao
> [09:08:04 WARN]: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5001ms.
> [09:08:04 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:676)
> [09:08:04 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:190)
> [09:08:04 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:155)
> [09:08:04 WARN]:        at me.lucko.luckperms.lib.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
> [09:08:04 WARN]:        at me.lucko.luckperms.common.storage.dao.sql.connection.hikari.HikariConnectionFactory.getConnection(HikariConnectionFactory.java:128)
> [09:08:04 WARN]:        at me.lucko.luckperms.common.storage.dao.sql.SqlDao.tableExists(SqlDao.java:145)
> [09:08:04 WARN]:        at me.lucko.luckperms.common.storage.dao.sql.SqlDao.init(SqlDao.java:162)
> [09:08:04 WARN]:        at me.lucko.luckperms.common.storage.AbstractStorage.init(AbstractStorage.java:122)
> [09:08:04 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> [09:08:04 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> [09:08:04 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> [09:08:04 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
> [09:08:04 WARN]:        at me.lucko.luckperms.common.storage.wrappings.PhasedStorage.lambda$wrap$0(PhasedStorage.java:64)
> [09:08:04 WARN]:        at com.sun.proxy.$Proxy25.init(Unknown Source)
> [09:08:04 WARN]:        at me.lucko.luckperms.common.storage.StorageFactory.getInstance(StorageFactory.java:117)
> [09:08:04 WARN]:        at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:132)
> [09:08:04 WARN]:        at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onEnable(LPBukkitBootstrap.java:152)
> [09:08:04 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
> [09:08:04 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
> [09:08:04 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
> [09:08:04 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:382)
> [09:08:04 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:331)
> [09:08:04 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:206)
> [09:08:04 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545)
> [09:08:04 WARN]:        at java.lang.Thread.run(Unknown Source)
> [09:08:04 INFO]: [LuckPerms] Loading messaging service... [BUNGEE]
> [09:08:04 INFO]: [LuckPerms] Loading internal permission managers...
> [09:08:04 INFO]: [LuckPerms] Performing initial data load...
> [09:08:09 WARN]: java.util.concurrent.CompletionException: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5001ms.
> [09:08:09 WARN]:        at me.lucko.luckperms.common.storage.AbstractStorage.lambda$makeFuture$1(AbstractStorage.java:105)
> [09:08:09 WARN]:        at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
> [09:08:09 WARN]:        at me.lucko.luckperms.common.plugin.scheduler.AbstractJavaScheduler$WrappedRunnable.run(AbstractJavaScheduler.java:79)
> [09:08:09 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
> [09:08:09 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
> [09:08:09 WARN]:        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
> [09:08:09 WARN]:        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
> [09:08:09 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
> [09:08:09 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
> [09:08:09 WARN]:        at java.lang.Thread.run(Unknown Source)
> [09:08:09 WARN]: Caused by: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5001ms.
> [09:08:09 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:676)
> [09:08:09 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:190)
> [09:08:09 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:155)
> [09:08:09 WARN]:        at me.lucko.luckperms.lib.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
> [09:08:09 WARN]:        at me.lucko.luckperms.common.storage.dao.sql.connection.hikari.HikariConnectionFactory.getConnection(HikariConnectionFactory.java:128)
> [09:08:09 WARN]:        at me.lucko.luckperms.common.storage.dao.sql.SqlDao.loadAllGroups(SqlDao.java:609)
> [09:08:09 WARN]:        at me.lucko.luckperms.common.storage.AbstractStorage.lambda$loadAllGroups$10(AbstractStorage.java:214)
> [09:08:09 WARN]:        at me.lucko.luckperms.common.storage.AbstractStorage.lambda$makeFuture$1(AbstractStorage.java:102)
> [09:08:09 WARN]:        ... 9 more
> [09:08:09 INFO]: [LuckPerms] Successfully enabled. (took 12010ms)`

**Comment by electronicboy** [comment]
`[09:09:16 WARN]: Caused by: java.net.ConnectException: Connection timed out: connect`
Not an LP issue, you've misconfigured the mysql connection somewhere, I'd suggest asking on the discord channel for support

**Comment by lucko** [comment]
https://github.com/lucko/LuckPerms/wiki/Storage-system-errors
