### ISSUE TITLE
A Few IMPORTANT issues

### ISSUE THREAD

**Issue by parkermeyers25** [lucko/LuckPerms#1088]
I have luckperms on my server and it is GREAT! I love it. Permissions ex won't work so that is why I switched to LuckPerms. But now, I have another plugin (skyblock) that needs vault but Vault Does Not Recognise LuckPerms, it recognizes permissionsEX, even though I don't have it. Here is the latest log. https://pastebin.com/Ua3L78he Also, luckperms prefixes so not show up. Can you tell me what plugin is causing that too? 

Thanks,
Parker

**Comment by electronicboy** [comment]
With how vault loads and detects those plugins, you likely either stuff have other permission plugins in the plugins folder, or have some plugins doing weird things...

Vault only really prints messages for stuff it has in-built support for, as LP registers its own implementation provider for these, it won't log any messages about them

prefixes is likely down to the fact that it's seemingly picking up other plugins, or your chat plugin isn't setup to display them.

I'd heavily suggest joining/asking on the discord for better support

**Comment by lucko** [comment]
Vault is being setup successfully.

```
[10:57:48] [Server thread/INFO]: [LP] Registered Vault permission & chat hook.
```

Running `/vault-info` will also show you what providers are registered.
