### ISSUE TITLE
Mass permission removal

### ISSUE THREAD

**Issue by Wertik1206** [lucko/LuckPerms#1090]
Hey, I'm new to github, so sorry if I mess something up.

A suggestion of a command, something like /lp remove params node context
Where params would be where to search, for ex. all / players / groups / group:default

What would this command do should be obvious, remove nodes from the destination you entered.
If it is already a feature and i just missed it, please let me know, so I can remove this request.

**Comment by BrainStone** [comment]
Already exists. Have a look at bulkupdate on the wiki (or bulkedit. I can never remember what it’s called)

**Comment by Wertik1206** [comment]
Thanks, I'll have a look at it. Sorry for posting this and for my mistake.

**Comment by BrainStone** [comment]
Don’t worry. No harm done. Though for future reference, Discord is the best place to ask.

**Comment by codingJWilliams** [comment]
And remember @Wertik1206 to close this if you manage to solve it ;)

Also IMO github issues are a good place to ask questions lol, like support tickets.
