### ISSUE TITLE
No Track creation

### ISSUE THREAD

**Issue by Chazotu** [lucko/LuckPerms#1091]
Luckperms Spigot Version : 4.2.42
Luckperms Bungee Version: 4.2.42

Issue: LP is not creating tracks 

Console Ouptput: https://hastebin.com/oxenobebah.md

**Comment by Andre601** [comment]
Before opening an issue, make sure, that you use the same versions for the BungeeCord and spigot.
As you shown at the top, this isn't the case.
Also please use a page like [hastebin.com](https://hastebin.com) next time. It makes solving issues a lot easier for us.

**Comment by Chazotu** [comment]
I just reproduced the same Issue whit both versions running on 4.2.42 Console Output is edited to an hastebin link.

**Comment by lucko** [comment]
Should be fixed in the latest version.

https://luckperms.github.io/

**Comment by Chazotu** [comment]
Confirmed Problem Solved
