### ISSUE TITLE
Editor permissions

### ISSUE THREAD

**Issue by r4nx** [lucko/LuckPerms#1096]
When running `lp editor users` in the console, I get an error:
`[LP] You do not have permission to use this command!`

But `lp editor` or `lp editor groups` work fine.

Spigot 1.12.2-R0.1-SNAPSHOT
LuckPerms v4.2.17

**Comment by Andre601** [comment]
I can reproduce and confirm that error.

**Comment by lucko** [comment]
Message is being sent because no users are connected to the server - not a permission checking error, just sending the wrong message. :)
