### ISSUE TITLE
Plugins without Permission nodes

### ISSUE THREAD

**Issue by ArcaneEcho** [lucko/LuckPerms#1103]
Hi, 

I have been looking for hours for this and haven't found anything.
im using a few sponge plugins that don't have permission nodes.
Is there a way to allow a certain user/group to have all permissions.
example; when joining the server you have 0 perms and you have to assign them user permission nodes.
is there a way to give users access to all permissions and from there blacklist permissions instead of whitelisting.

Thanks,

**Comment by BrainStone** [comment]
That's in fact terrible practice. You rather want people to not have permissions to things they should have permissions to, than them having permissions to thing they should not have to, as they easily might damage the server that way if you just forget to blacklist one permission.

But reagrdless, using the `*` wildcard is the way to go.

I also don't understand what exactly the plugins with no permissions have to do with that question.
