### ISSUE TITLE
Luckperms 4.2.15 & Waterfall

### ISSUE THREAD

**Issue by Phyther** [lucko/LuckPerms#1108]
I am starting to setup a waterfall proxy and loaded in luckperms to get started and received this error:
`19.07 04:13:21 [Server] WARN Error enabling plugin LuckPerms
19.07 04:13:21 [Server] INFO java.lang.NoClassDefFoundError: org/bukkit/plugin/java/JavaPlugin
19.07 04:13:21 [Server] INFO at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_172]
19.07 04:13:21 [Server] INFO at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_172]
19.07 04:13:21 [Server] INFO at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_172]
19.07 04:13:21 [Server] INFO at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[?:1.8.0_172]
19.07 04:13:21 [Server] INFO at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[?:1.8.0_172]
19.07 04:13:21 [Server] INFO at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[?:1.8.0_172]
19.07 04:13:21 [Server] INFO at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[?:1.8.0_172]
19.07 04:13:21 [Server] INFO at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_172]
19.07 04:13:21 [Server] INFO at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[?:1.8.0_172]
19.07 04:13:21 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_172]
19.07 04:13:21 [Server] INFO at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:34) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:7c850b9:192]
19.07 04:13:21 [Server] INFO at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:27) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:7c850b9:192]
19.07 04:13:21 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_172]
19.07 04:13:21 [Server] INFO at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:338) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:7c850b9:192]
19.07 04:13:21 [Server] INFO at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:246) `~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:7c850b9:192]``

**Comment by merjilin** [comment]
You're attempting to use the luckperms-bukkit jar on bungeecord :P Use this build https://ci.lucko.me/view/LuckPerms/job/LuckPerms/lastSuccessfulBuild/artifact/bungee/target/LuckPerms-Bungee-4.2.51.jar

**Comment by Phyther** [comment]
Thanks... dumb night. :)
