### ISSUE TITLE
1.13 compatible ?

### ISSUE THREAD

**Issue by TheIntelloBox** [lucko/LuckPerms#1109]

**Comment by Andre601** [comment]
Yes

**Comment by RJHaytree** [comment]
Yes, LuckPerms should already be 1.13 compatible. The latest build also has some additional features to 1.13 https://ci.lucko.me/view/LuckPerms/job/LuckPerms/lastSuccessfulBuild/artifact/bukkit/target/LuckPerms-Bukkit-4.2.51.jar

**Comment by lucko** [comment]
Yes
