### ISSUE TITLE
Whitelist > autorank?

### ISSUE THREAD

**Issue by DatNubTriz** [lucko/LuckPerms#1111]
Im currently using MCLink as a Twitch whitelist for the Server to only allow Twitch Subscribers on the server. MCLink registers the Subscription Tier of each person to join, would it be possible to have it set where depending on the Tier that MCLink provides in the console, could i potentially use that to auto-assign users to certain groups with LuckPerms?

**Comment by lucko** [comment]
There is no special link between the two plugins. Maybe MCLink supports Vault? in which case, it will be able to change permissions data in LuckPerms.
