### ISSUE TITLE
[Question] /lp log

### ISSUE THREAD

**Issue by Rbot48** [lucko/LuckPerms#1112]
Hey,
When typing `/lp log recent`, it only displays 65 actions from 4 months ago. Is there anything that would prevent the logs from being saved?

**Comment by lucko** [comment]
What version of LP?
Which storage type are you using?

Any errors when you run the command?
What data is missing, more recent items, or entries older than 4 months ago?

**Comment by Rbot48** [comment]
I'm using LuckPerms v4.2.51, both on bungee and the other servers. The storage type is MySQL.
No errors are displayed. The most recent data is missing. There are changes to the permissions almost every day.

**Comment by lucko** [comment]
Is logging enabled in the config? Do you see the log messages in chat and in the console?

Could you try reverting to the most recent build on Spigot to see if that resolves the issue?

**Comment by Rbot48** [comment]
Yes, I have `log-notify` set to true in the config and I can see the log messages in chat and in the console.
Tried with LuckPerms-Bukkit-4.2.17, same thing. :/

**Comment by lucko** [comment]
??
