### ISSUE TITLE
Spacing in prefixes

### ISSUE THREAD

**Issue by ghost** [lucko/LuckPerms#1115]
Hello, is it possible to add spaces at the end of a prefix via a command?

What I want: [test] Bob: blah
What I get: [test]Bob: blah

This is the command I use: /lp user Bob meta addprefix 50 '[test] '

Note: The 's aren't there, they're simply to show the space at the end.

**Comment by BrainStone** [comment]
As voodootje0 said wrap it in `"`: `/lp user Notch meta addprefix 1337 "[We love you] "`

Alternatively just add the space in your chat format.
