### ISSUE TITLE
Migration Issue (follow-up from Spigot)

### ISSUE THREAD

**Issue by pozzzzy** [lucko/LuckPerms#1118]
Hello. I am Chissey from the support forum on SpigotMC.
I had the issue with migration from GroupManager.
[![Screenshot from Gyazo](https://gyazo.com/c14e38316f9a177f95470dfce79c27c0/raw)](https://gyazo.com/c14e38316f9a177f95470dfce79c27c0)

users.yml: https://pastebin.com/0Qg7ubSm
groups.yml: https://pastebin.com/Rz7styuw

**Comment by pozzzzy** [comment]
Pastebin has done some faulty indentation with the first node in groups and users. I'll attach the original files instead. 


[Groupsandusers.zip](https://github.com/lucko/LuckPerms/files/2222821/Groupsandusers.zip)

**Comment by lucko** [comment]
You missed out the important bit:

https://gist.github.com/triagonal/675a8a22b7a9212de74e45b8b676de31

**Comment by lucko** [comment]
Should be fixed in the latest dev build.
DL from here: https://luckperms.github.io/

Thanks for reporting :)
