### ISSUE TITLE
Pex migration > User cannot be found

### ISSUE THREAD

**Issue by VoidAngel** [lucko/LuckPerms#1119]
Hello I have run into an issue after migrating from pex to luckperms.

### Description: 
After migrating from pex to luckperms, all luckperms commands do not work with usernames. It seems I have to use UUIDs only to edit or pull up info about a user. I know its better to use UUID anyways, but not all plugins have uuid placeholders (such as EZPrestige, or other ranking plugins). It is very strange, though, because the plugin seems like it has all the info it needs. If I run the command via UUID it even outputs the correct username. 

NOTE: I, VoidAngel, have logged on to the server multiple times after migrating, so I should be in the luckperms cache, but it seems I am not somehow. See the below console output:

### Evidence:
```
24.07 13:36:51 [Multicraft] VoidAngel ran command: lp user VoidAngel info
24.07 13:36:51 [Server] INFO [LP] A user for VoidAngel could not be found.
24.07 13:37:31 [Multicraft] VoidAngel ran command: lp user 37bdf967-50f0-4434-9c8f-f17070094d5c info
24.07 13:37:31 [Server] INFO [LP] > User Info: VoidAngel
24.07 13:37:31 [Server] INFO [LP] - UUID: 37bdf967-50f0-4434-9c8f-f17070094d5c (type: mojang)
24.07 13:37:31 [Server] INFO [LP] - Status: Offline
24.07 13:37:31 [Server] INFO [LP] - Primary Group: peasant
24.07 13:37:31 [Server] INFO [LP] - Parent Groups:
24.07 13:37:31 [Server] INFO [LP] -    > peasant
24.07 13:37:31 [Server] INFO [LP] - Contextual Data:
24.07 13:37:31 [Server] INFO [LP] -    Has contextual data: false
24.07 13:37:31 [Server] INFO [LP] -    Applicable contexts: None
24.07 13:37:31 [Server] INFO [LP] -    Prefix: None
24.07 13:37:31 [Server] INFO [LP] -    Suffix: None
24.07 13:37:31 [Server] INFO [LP] -    Meta: None
```

Is there a way to fix this? Perhaps a command? or something at startup to correct all the users?

Things that don't work:
1) Restarting the server
2) Being online while running the command
3) Turning on "use-server-uuid-cache" DOES work in a sense, but the _luckperms cache still does not update_ D: I'm worried about too many requests to Mojang by leaving it on. I have a lot of servers and a lot of players so I have to be careful about that. Correct me if I'm wrong please.

**Comment by codingJWilliams** [comment]
Hey! Just out of interest, which backend are you using?

**Comment by VoidAngel** [comment]
Ah right I should mention that. xD
I'm using the default h2.
Also I'm on Luckperms 4.2.17 and Spigot 1.12.1

**Comment by codingJWilliams** [comment]
Hmm. Could you perhaps export your perms, delete the h2 and reimport please?

**Comment by VoidAngel** [comment]
Ive migrated about 6 servers from pex to luckperms already. They all have the same issue, but its not always the same users that dont get migrated correctly. On a few servers I can run "lp user VoidAngel info" with no problem, but for a user that is online even at that moment I can type "/lp user <exampleuser> info" and it will tell me that the user cannot be found.

Given the fact that I have already done this many time I dont think the outcome will change xD
But if you have something else in mind that I am not thinking of, I will try exporting and migrating again.

**Comment by codingJWilliams** [comment]
Export, don't migrate
Literally type `/lp export test` `/lp import test` into console

**Comment by codingJWilliams** [comment]
But that does sound like a bug :thinking: cc @lucko 

^so ^glad ^clippy ^isn't ^here

**Comment by VoidAngel** [comment]
Oh sorry I understand now.
Will do 👍

**Comment by VoidAngel** [comment]
That worked :D The cache is now updating itself when players log in.

**Comment by lucko** [comment]
> The version you’re using is quite old...

this ^ - I think this was fixed already

**Comment by VoidAngel** [comment]
The spigot server is offline yes, but players are authenticated with bungee.

**Comment by BrainStone** [comment]
Is IP-Forwarding enabled on the bungee and the bungee mode on the Spigot?

**Comment by Mineben** [comment]
Hello,
I have the exactly same problem.
Running on spigot offline without bungee

**Comment by lucko** [comment]
Doing the PEX migration shouldn't have any impact on how UUIDs are being saved by LP. Once a player has connected once, they should be permanently cached in the plugins storage.

Do you have any other plugins installed which could possibly be preventing LP from handling the connection, or clearing the data after they've logged in?

**Comment by BrainStone** [comment]
From what I’ve seen almost everyone that migrates has issues resolving player names. Exporting, wiping and importing usually solves the issue, as that completely wipes the username cache.

Just had another case today.  
So the PEX migration must somehow mess up the player cache.

**Comment by lucko** [comment]
Which storage type @BrainStone ?

I'd like to try to reproduce this myself, have been unable to so far.

**Comment by VoidAngel** [comment]
I can pass you a pex permissions.yml if you would like to test it with a large permissions file that can very likely reproduce the problem.

**Comment by lucko** [comment]
Ok sure :)

**Comment by BrainStone** [comment]
From what I’ve seen it’s the default H2, as most people just plug’n’play.

**Comment by VoidAngel** [comment]
All I did to migrate was:
1) Install luckperms with a brand new luckperms folder generated.
2) While pex is still on the server, do /luckperms migration permissionsex
3) Wait until the migration is done, then remove pex and restart

After this you should find that most users (not 100% of them though) will not be cached correctly.

[permissions.zip](https://github.com/lucko/LuckPerms/files/2242331/permissions.zip)

**Comment by VoidAngel** [comment]
You might need to insert a fake record or something to make it work for you though (?) Juts thought about that because you wont have any data in that pex file for your minecraft account 🤔 And making brand new records with luckperms by just logging in might not reproduce the issue.

**Comment by VoidAngel** [comment]
Nice :D Ill try a migration tonight and see how it goes. Ill let ya know

**Comment by lucko** [comment]
Marking as fixed for now. 

@codingJWilliams Quite likely they were still using an older version.
