### ISSUE TITLE
Track set support

### ISSUE THREAD

**Issue by ryall** [lucko/LuckPerms#112]
Currently we use multiple promotion tracks: "donor" and "staff". When a user purchases from the webstore, we currently cannot use tracks as there is no "set" option and we cannot use promote as the current rank is unknown. Instead we use `parent add` to assign the new group, which means a user can have multiple donor groups applied to their user, which for me is a little messy.

This feature request is for the ability to do a `set` on a named track, which would:

- Check that the specified group exists on the track, or fail
- Remove *all* groups of *the specified track* from the user
- Add the specified group to the user

The command would be something like:
`lp user {name} settrackgroup {trackname} {group}`

This would allow me to change a "donor" group, while not affecting the "staff" groups and would keep the groups clean, meaning there aren't multiple groups of the same track applied to the user. If you need further clarification let me know.

**Comment by lucko** [comment]
Yup, I like the idea.

I will probably also accompany it with a command to remove all track groups.
e.g.

`/lp user Luck parent removetrack staff` would remove me from all groups on the staff track.

Additionally, I think `/lp user Luck promoteoradd <track>` would be useful. (as promote fails if they're not already on the track.)

**Comment by ryall** [comment]
`removetrack` would be really useful, I agree. 

However, with the `promoteoradd` command, is there a reason `promote` needs to fail rather than just adding them to the first rank itself? That's actually how I would have expected this to work.

**Comment by lucko** [comment]
Took a while but I finally added it. ;)

**Comment by lucko** [comment]
https://github.com/lucko/LuckPerms/wiki/Command-Usage:-Parent#lp-usergroup-usergroup-parent-settrack
