### ISSUE TITLE
Internal Exeption

### ISSUE THREAD

**Issue by Chazotu** [lucko/LuckPerms#1121]
Issue:
While only having running Luckpersm on Bungee and Spigot i
get this error when trying to enter the game
https://www.xup.in/dl,25259138/mc.PNG

Spigot Version : Spigot-0b44fa0-1ef1ffd (1.13 Current Build)
Waterfall: Waterfall-Bootstrap:1.13-SNAPSHOT:25e3309:212 (Build 212)
LP Version : v4.2.54

**Comment by codingJWilliams** [comment]
Hey. I'm not sure this is a luckperms issue (I've never seen this error before) but could you please upload your latest.log into (hastebin)[https://hastebin.com]

**Comment by codingJWilliams** [comment]
(and send the link here)

**Comment by Chazotu** [comment]
https://hastebin.com/kujetocaha.md

**Comment by codingJWilliams** [comment]
@Chazotu Your database is not configured correctly - check your config.yml settings are correct.

**Comment by Chazotu** [comment]
The Databases loads fine on end already had the error whit
