### ISSUE TITLE
SevTech Server Advancements Failing

### ISSUE THREAD

**Issue by Tylerun** [lucko/LuckPerms#1122]
Hello, 

I am lead developer over at Tactical Universe and we were planning on launching a Sevtech server as it was one of the most requested servers for our community. We began testing and realized that some advancements do not work. "Caveman Hate Tree" Which is the second advancement does not work when Luckperms is installed. Not sure if there is a workaround for this but have been testing to no result. Opened here first as the advancement mod is implemented and can not be removed. 

How to test: Install Luckperms and Sponge into a sevtech server. 
Whats wrong: Some advancements do not work "Caveman Hate Tree" 
What should happen: Advancement should progress as normal
Steps taken: Clean install of modpack and update to Sponge and luckperms no result. 

Environment: 8GB ram, Dedicated Server

Let me know if any other information is needed as I can not find the cause. 

Better Advancements Issue #29
https://github.com/way2muchnoise/BetterAdvancements/issues/29

**Comment by Andre601** [comment]
Can you also give us your Server and LP-Version please?

**Comment by Tylerun** [comment]
Forge Version: forge-1.12.2-14.23.4.2738-universal
Sponge Version: 1.12.2-2705-7.1.0-BETA-3353
Luckperms: LuckPerms-Sponge-4.2.42
Minecraft: 1.12.2

**Comment by codingJWilliams** [comment]
Hey @Tylerun. Could you turn `/lp verbose on & MemberName` and have MemberName perform the steps to get the advancement, if there are permission checks failing then you should add the default group these permissions. If there aren't any permission checks that fail, then I'm not sure it's luckperms that's the issue.

**Comment by Tylerun** [comment]
Will do thank you shoulr have a result within a couple of hours

**Comment by Tylerun** [comment]
So the issue is I do not believe that the Verbose is functional according to half of the quests. Some quests sure it shows up but half of the others it doesnt affect a player. is there another command i can use to filter with

**Comment by Tylerun** [comment]
Thanks everyone seems that when converting the ssp to smp files some scripts broke and for some reason luckperms was the wildcard factor. Repaired the scripts and issue resolved

**Comment by BrainStone** [comment]
One additional thing would be installing ForgedPerms so that Forge permission checks are also handled through Sponge (and therefore LP)
