### ISSUE TITLE
[SPONGE] Where is the version for API 7?

### ISSUE THREAD

**Issue by Subilan** [lucko/LuckPerms#1123]
My server's version is 1.12.2 and the sponge API version is 7.1.0. But the latest version in Jenkins is for sponge API 8, and the old versions are for sponge API 6, where is the version for sponge API 7?
If LuckPerms doesn't support API 7, then I didn't say anything.

(I really don't know where it is, or my eyes broken?)

I need some help, thank you!
~~If you think my English is weird, that's absolutely right.~~

**Comment by lucko** [comment]
The LuckPerms-Sponge jar works on all API releases from 5 to 8.

**Comment by Subilan** [comment]
Thank you very much.
But my server said
> Sponge The mod luckperms was designed for spongeapi 8.0.0-SNAPSHOT but spongeapi 7.1.0-SNAPSHOT-d453c3e is in use. It may not work properly.

Should I ignore it?

**Comment by lucko** [comment]
Yep :)
