### ISSUE TITLE
Limited context mode + tab complete

### ISSUE THREAD

**Issue by voodootje0** [lucko/LuckPerms#1125]
The possibility to enable this mode, and when that's enabled you can use contexts that are in a list, it could be a config string list or storage based with command usage. You can only use contexts that are set in the list. Also when the context is in the list you can use it for tab complete.

**Comment by lucko** [comment]
I don't really see what the benefit would be?

**Comment by voodootje0** [comment]
The main reason was to prevent typos. When you're having over 40+ different contexts in use and some look very similar you make mistakes very quickly. But using now I'm using https://github.com/lucko/LuckPerms/wiki/Context#defining-your-own-contexts for all servers and that fixes the 'problem' for me :)
