### ISSUE TITLE
MySQL Unexpected error

### ISSUE THREAD

**Issue by Artuto** [lucko/LuckPerms#1126]
Hi, I started my server today and LuckPerms was giving an error related to MySQL connection, ehich you can see here:

https://hastebin.com/ofategugup.sql

I'm not sure what is happening since every other plugin works fine, except LuckPerms. I'm using LP Version 4.2.51 and MySQL 8.0.12

**Comment by codingJWilliams** [comment]
I'm pretty sure it's an SQL syntax change in a later version, mysql 5.7.22 works fine for me

**Comment by lucko** [comment]
Update to latest

https://luckperms.github.io/

**Comment by Artuto** [comment]
Error still happening with 4.2.55

**Comment by lucko** [comment]
Please try again with `4.2.56`

**Comment by Artuto** [comment]
It worked! No errors now, Thanks for the support!
