### ISSUE TITLE
"Damages"

### ISSUE THREAD

**Issue by MagicallyGringo** [lucko/LuckPerms#1129]
for some reason on our server using anvils will send a chat message "damages" that has to do with luckperms and was wondering if anyone knows a fix.

**Comment by lucko** [comment]
LuckPerms doesn't do anything related to that. It'll be caused by another plugin. 

I guess just try removing one at a time until the message goes away. If removing LuckPerms fixes it, perhaps a plugin is running a permission check before sending the message.

**Comment by codingJWilliams** [comment]
Also a quicker way to narrow it down, make a test server and remove half your plugins at a time until it stops happening, and narrow it down like that.
