### ISSUE TITLE
PlotSquared Permissions

### ISSUE THREAD

**Issue by hyWse** [lucko/LuckPerms#1131]
Hello,

i can't claim any plots with LuckPerms.
There comes the error: "You can't claim more plots", although I have set all permissions correctly. My permission system had the same problem.
However, with PermissionsEx and GroupManager you can

**Comment by lucko** [comment]
Unlikely to be a bug in LP.

I don't know how the plot claiming system works, but you can use the `/lp verbose` command to diagnose the issue further.

https://github.com/lucko/LuckPerms/wiki/Verbose

**Comment by hyWse** [comment]
Oh sorry, my vault. Everything is okay ^^ There was another permission on the server ._.

**Comment by lucko** [comment]
ok cool :)
