### ISSUE TITLE
i am getting a error 

### ISSUE THREAD

**Issue by greensabob** [lucko/LuckPerms#1132]
http://prntscr.com/kdwsqg  http://prntscr.com/kdwszc http://prntscr.com/kdwt51 http://prntscr.com/kdwt9x http://prntscr.com/kdwtfo http://prntscr.com/kdwtmq so this started happening last night not sure why i was off playing other server then go on to remove a staff memebers rank and found out it will not let me add/remove stuff from people i tryed restarting all of the servers did not fix it. for some people it does not give them there rank but others do get it 

i love luckperms good plugin i been using it for long time idk what happening now 
oo server is 1.12.2 idk if this is need telling you the server is 1.12.2 or not

**Comment by BrainStone** [comment]
Please provide the error in textual form. Upload it preferably on https://gist.github.com
