### ISSUE TITLE
/lp sponge is undocumented and empherial 

### ISSUE THREAD

**Issue by codingJWilliams** [lucko/LuckPerms#1133]
So to allow commandblocks permissions to do commands, you need /lp sponge, however there is no documentation for this, no way to remove a collection or subject, data doesn't save to db correctly etc etc.

Hopefully I'll be able to make a pr tomorrow to neaten some of this up but I feel like this command needs to be fixed

**Comment by lucko** [comment]
PRs are welcome, but I don't really agree with your judgement.

The command has no documentation in the wiki as end-users are highly unlikely to need to ever use it. The Sponge permission service terminology and layout (subjects, collections etc etc) tend to confuse lots of plugin developers, let alone server administrators.

Perhaps there's room for the exact commands you need to achieve certain functions in the wiki - e.g. editing command block or console permissions, but beyond that I don't think any further documentation is necessary.

RE: the bugs you mentioned, yes of course those can be fixed, but I need reproducible steps. All seems to work fine in my experience.
