### ISSUE TITLE
WorldEdit permissions do not work

### ISSUE THREAD

**Issue by Johnystar** [lucko/LuckPerms#1135]
Today, I downloaded LuckPerms and added it to all my servers and BungeeCord. I made a MySQL database and set everything up and it's working very well, except that LuckPerms doesn't work with WorldEdit for some reason.
I tried updating WorldEdit, restarting the server that WorldEdit is on, but nothing I tried worked. When I use the command `/lp tree`, there are no WorldEdit entries. It works perfectly with other plugins though. I checked if there were any previously reported issues about this, but all I could find was an issue from someone who tempered with the WEPIF file. To make sure that I'm not experiencing the same problem, I even tried deleting the file and restarting the server so that it would generate a clean new WEPIF file.

**Comment by smmmadden** [comment]
sorry for stating the obvious, but did you add the WorldEdit Permissions?  If they don't show in the tree or the editor, then it sounds like it would be a quick fix to just re-add them or import them from a backup or another server.

**Comment by Johnystar** [comment]
I'm using BungeeCord 1.13 and all the other servers are running "git-Spigot-642f6d2-6103339 with Spigot API 1.12.2-RO.1. LuckPerms is version 4.2.58 on all servers. WorldEdit is only on the main Spigot server, version 6.1.9.
I tried `/lp verbose` but nothing shows up when I try `//pos1` or `//set`.
It seems like there's no communication between WE and LP at all.
I'm also using WESV for visualizing WorldEdit and AsyncWorldEdit.

**Comment by lucko** [comment]
Do you have any other permissions plugins installed on your server?

**Comment by lucko** [comment]
It seems that WorldEdit doesn't run any permission checks when you're opped.

You need to set `no-op-permissions: false` for it to check permissions as usual.
