### ISSUE TITLE
/lp group listmembers click action is wrong

### ISSUE THREAD

**Issue by codingJWilliams** [lucko/LuckPerms#1138]
Clicking a members name in /lp group listmembers suggests the command /lp group TheirName parent remove Group, but it should start with /lp user

[Affected code](https://github.com/lucko/LuckPerms/blob/master/common/src/main/java/me/lucko/luckperms/common/commands/group/GroupListMembers.java#117) 

Suggested Fix: change HolderType.Group to HolderType.User or equivalent

I would make a PR but I'm away at the moment, sorry

**Comment by lucko** [comment]
Are you using the latest version of LP? Seems to be fixed already?

**Comment by codingJWilliams** [comment]
Huh, I swear I reproduced this 🤔 Can't now, closed, sorry
