### ISSUE TITLE
[LP] Permissions data could not be loaded. Please contact an administrator

### ISSUE THREAD

**Issue by Bubble0seven** [lucko/LuckPerms#114]
Keep getting the above errors 

Running Bungee Cord and this is on one of my Main servers I Have online mode set to true as required in the configs  I am not using SQL but YAML Format since the permissions are different per server. Not sure if that is the reason 

Luckperms Version LuckPerms-Sponge-2.16.75.jar
Sponge Version is spongeforge-1.10.2-2171-5.1.0-BETA-1992

I know its not the latest version of sponge but we are currently having issues with the latest build of sponge and this seems to be the most stable for us currently. 

[FML Log](https://gist.github.com/Bubble0seven/61b304546d2a2cdb910907e1eebd696al)
[Sponge Config](https://gist.github.com/Bubble0seven/16ca26272baa5d4c053e42d9d3f1dd18)
[LP Config](https://gist.github.com/Bubble0seven/e979977692a1ec04306d8f4df4701b56)

**Comment by Bubble0seven** [comment]
I understand things get busy and there are other issues being raised but i need a fix soon otherwise i have no choice but to move to Permissionsmanager or something as currently using PEX and its like all our players have been given OP Status. 

I have had LuckPerms working on a test server fine but as soon as i moved it over to the bungee network servers with the same versions and setup apart from bungee it gave those errors and i am unable join.

So please if you can let me know if this is fixable relatively soon as i need to move to any permission system that works i much prefer LP due to it being more server freindly.

**Comment by lucko** [comment]
Can't read the FML log.

**Comment by Bubble0seven** [comment]
[FML LOG](https://gist.github.com/Bubble0seven/61b304546d2a2cdb910907e1eebd696a)

That should work sorry about that

**Comment by lucko** [comment]
Delete the /luckperms/local folder.
https://paste.lucko.me/igeroxolig.avrasm
