### ISSUE TITLE
Migration from Spigot to Sponge

### ISSUE THREAD

**Issue by lastsamurai26** [lucko/LuckPerms#1141]
Hey, 

can i copy the Config from Spigot Luchperms to Sponge Luckperms ?

I want to copy my world from Spigot to Sponge  because i want to use some Mods like Biome o plenty, Custom NPCs and so one.

**Comment by codingJWilliams** [comment]
As far as I'm aware this should work :)

Just make sure to test on a throwaway server first!

**Comment by lastsamurai26** [comment]
I want to completely rebuild the server without a world migration from Spigot to Sponge. I just want to copy the Configs and insert the map later via Worldedit 

i will try :)

**Comment by BrainStone** [comment]
No. You can’t copy the config. Mainly because Sponge uses a different config format. And there a platform dependent settings. You have to manually migrate.  
The database however can just be copied (assuming you’re using a file based storage typE)
