### ISSUE TITLE
Timed groups

### ISSUE THREAD

**Issue by erik1988** [lucko/LuckPerms#1145]
Hi, Does this support timed groups?
And if it does, is it possible to add a new time to the old time. 
e.g if I add a group for 1 day and then run the same command again, will it become 2 days?
If not, can this be added?

**Comment by codingJWilliams** [comment]
https://github.com/lucko/LuckPerms/wiki/Command-Usage:-Parent#lp-usergroup-usergroup-parent-addtemp

It supports all of these features :) - see the accumulate option

**Comment by erik1988** [comment]
Awesome!  Thank you.
