### ISSUE TITLE
LuckPerms won't apply all permissions globally thru all servers

### ISSUE THREAD

**Issue by K1ish** [lucko/LuckPerms#1146]
I am running a bungeecord network on 1.12.2, and running Luckperms 4.2.58
I have about 4 servers, One bungeecord/waterfall proxy and 3 spigot/paper servers
I'm trying to apply permissions, most of them being essentials perms. I have the permissions set to be applied globally thru all servers and worlds. The servers are using SQL messaging and MariaDB and all connected to the same database. 
When I apply certain permissions, ex. essentials.help each server receives a SQL message in the logs and says they have been applied, but it only applies to one server, titled 'creative' (I even do /lp networksync)
They do apply when I duplicate all nodes 4 times and set them to each server
Creative Server Config: [https://pastebin.com/wkjj2Fes](https://pastebin.com/wkjj2Fes)
Lobby Server Config: [https://pastebin.com/iEUwhNwP](https://pastebin.com/iEUwhNwP)
Survival Server Config: [https://pastebin.com/mNZa7hnh](https://pastebin.com/mNZa7hnh)

**Comment by K1ish** [comment]
I'm using the web editor but each server seems to acknowledge the
permissions being updated.

**Comment by lucko** [comment]
Can you show me a sample of your data?

**Comment by DeCarvalho83** [comment]
Hey, i did see it right now, and it happened once or twice when using web editor.. i dont remember the last time it didnt work, but today, right after applying a webeditor change i do networksync just to be sure..
If you want some info just tell what do you need and i'll provide,,
Im using 1x bungee latest version, 6x spigot 1.12.2, all inside a pterodactyl daemon with mariadb, java 8, ubuntu 18.04
