### ISSUE TITLE
Item Dropping

### ISSUE THREAD

**Issue by Traylon** [lucko/LuckPerms#1147]
I can't drop items with luckperms, nor can anyone else in groups. Is there a command to fix this?

**Comment by Traylon** [comment]
We are using Nucleus 1.5.2, and the latest versions of Grief Prevention and Spongeforge

**Comment by ktole1999** [comment]
then you will need to test. GP has an item protect module in config. if you disable this are you able to drop items? if so then its a GP permission that is blocking it

**Comment by lucko** [comment]
Not directly caused by LuckPerms.

You can use the verbose command to attempt to diagnose the cause of the issue.
https://github.com/lucko/LuckPerms/wiki/Verbose
