### ISSUE TITLE
Applyedits returning unknown groups despite them being in storage

### ISSUE THREAD

**Issue by RJHaytree** [lucko/LuckPerms#1148]
**The Issue**

So we were met with an interesting case in the support discord just now. A user was unable to successfully apply edits from the web editor on their 1.12.2 spigot server. The message in change states that non of the groups apart from `default` existed in storage, however they are clearly there as they appear in the web interface and `/lp listgroups`

Strangely enough, I tested the same setup on a Sponge API 7 dev server and the same issue didn't arise.

**Their Setup**

Server Software: Spigot 1.12.2
LuckPerms Build: 4.3.66
Permission data: [perms.zip](https://github.com/lucko/LuckPerms/files/2279582/perms.zip) (It's a text file but github just hates us)

**Reproduce** 

1. Run `/lp editor`
2. Remove a permission
3. Save and run the applyedits commands

**Comment by lucko** [comment]
I can't reproduce using those steps. Seems to be working fine?

**Comment by WolvPlayz** [comment]
BTW this is the bug for me. The web editor isn't working. If you need more info ask me on discord Wolv_Playz#7952 i'm also in ur discord server. @lucko More detail: I do /lp editor and I open it and then I make changes and then hit save and then copy the command and enter it into Minecraft BUT then it said no edits were made. Also, updates aren't changed on the web editor for me for example when I deleted a role it still showed it on the web editor.

**Comment by DarkFort** [comment]
I use the command /lp groups editor, then change and save, and run the command /lp applyedits ...
![image](https://user-images.githubusercontent.com/25278617/44004116-85dd5a0e-9e65-11e8-98f4-fdb08b8176df.png)
![image](https://user-images.githubusercontent.com/25278617/44004122-a0492a08-9e65-11e8-8113-60f099ed5ea9.png)

storage-method: h2
Latest version LuckPerms
PaperSpigot 1.12.2

**Comment by WolvPlayz** [comment]
Yeh same for me except i use mysql and normal spigot
