### ISSUE TITLE
Documentation omissions

### ISSUE THREAD

**Issue by totemo** [lucko/LuckPerms#1149]
Hi.

I note some problems with the wiki documentation:

 * `config.yml` assures the reader:
   > The meaning and influence of "primary groups" are explained in detail on the wiki.
   * However, although the phrase "primary group" appears on several wiki pages, I can not find an explanation of it. There is some oblique discussion in the `switchprimarygroup` command sub-option and that's the extent of it. This is something that deserves its own heading on the wiki.

 * `group.name` permission nodes are treated specially. If you try to add `group.x` as a permission node, then `x` is added as a parent group instead (even if group `x` does not exist). Testing for the `group.x` _permission_ through Vault returns `false`. There is some allusion to this handling in the `config.yml` comments preceding the `default-assignments` section, however, it is not made clear that this is a general behaviour of the plugin that applies outside of that configuration file. This is really a "gotcha", exceptional behaviour of the plugin that deserves to be highlighted somewhere in introductory sections of the documentation, perhaps in a discussion of group related concepts.

* The `default-assignments` section does not have a description at https://github.com/lucko/LuckPerms/wiki/Configuration. Preferably the description would note the requirements to escape permissions in conditions with `<` and `>`, and the special significance of `group.<name>` permissions.

**Aside:**
I'm looking into migrating to LuckPerms and I have encountered several issues so far. I've spent many hours trying to resolve them and I have searched for the specific issues here as well. I'll be submitting distinct issues for each.

**Comment by lucko** [comment]
Hi, firstly, thank you for the detailed message. I appreciate you taking the time to suggest improvements. :)

> However, although the phrase "primary group" appears on several wiki pages, I can not find an explanation of it. This is something that deserves its own heading on the wiki.

Agreed. The default groups page could use some work too.

I'll hopefully find some time to take a closer look at these pages, and write up some new stuff sometime in the next week.

> group.name permission nodes are treated specially

You're quite right. The details of these nodes were previously mentioned, but a lot of it was removed as pages were rewritten.

In general, I've been trying to phase out the appearance of these nodes. Whilst it's true that they're still used internally, in all of the commands, as well as the file-based storage, this node is no longer used. Groups management is now done using a separate set of commands, and so called "group nodes" no longer show in the output to the `permission info` command.

However, they are indeed still used in a few places - incl. the web editor, and default assignments system as you pointed out. So, yes, I agree, a mention would be useful.

> The default-assignments section does not have a description on the wiki

Yep, that would be nice to add. Adding a dedicated section for it has been quite low down my to-do-list though, as my opinion has been that the comments containing explanation/examples in the config file itself are decent enough.

Re: importance of `<` and `>`, I've been meaning to rewrite the system to not require them. It's easily possible from a programming POV, and they can be confusing / easy to miss.

> I'm looking into migrating to LuckPerms and I have encountered several issues so far. I've spent many hours trying to resolve them and I have searched for the specific issues here as well. I'll be submitting distinct issues for each.

Thank you - I appreciate it :)

If you have any other questions or thoughts which you think don't deserve an issue on GH, the best place to discuss that sort of thing is on Discord.

**Comment by totemo** [comment]
Awesome. Thanks.
