### ISSUE TITLE
[Feature] Argumented Promotion

### ISSUE THREAD

**Issue by Fawkd** [lucko/LuckPerms#1151]
Hello, 

I am in a situation where an automated levelup/rankup is my go to goal, and the promotion track is kind of grinding against of this.

I have 7 individual groups on my server (called Group1,2,3.. from now on) and every 30 levels (leveling plugin which runs commands) I'd like to have the user be promoted on their current track "Group 1 Track" in this case.

So my Lv. 30 command would look like this;

- lp user <user> promote Group1
- lp user <user> promote Group 2
- lp user <user> promote Group 3

Since not everyone plays Group1, I have to run all the promotions to make sure that every track is promoted with the Lv. 30-60-90-120-150 and so on.
This makes it hard since as an example, Player X has Group1 so on rankup he would be promoted to Rank 2 on Group 1 and Rank 1 on Group 2 and 3 which then makes it so that he has 3 groups instead of 1 intented.

What I am suggesting here is a feature either to somehow have the /lp user <user> promote check for the current tracks and promote them accordingly or some way of disallowing promotion start to new track if you are already part of one. 

Example;
/lp user <user> promote human if notothertrack

Thank you for your time! If you need any additional information feel free to reply and I try to elaborate on it more.

Regards,
Fawked

**Comment by BrainStone** [comment]
A reasonable alternative would be to have an option to enable default assignments every time user permissions change as. That would allow to assign a rankup group and the rules then chose the right upgrade.

**Comment by lucko** [comment]
How about (optionally) changing the behaviour of the promote command to only run the promotion if they're already on the track?

**Comment by BrainStone** [comment]
I think that’s a good idea if it’s an opt-in option. The current behavior is better for the general use case.

**Comment by Fawkd** [comment]
That would work as well, then you'd only need to run `/lp user <user> promote` and it would promote them on their existing track.

**Comment by lucko** [comment]
No, it would just mean you could run the command multiple times without affecting tracks the user is not yet on.
