### ISSUE TITLE
Custom Providers

### ISSUE THREAD

**Issue by Matthis974JumpCoder** [lucko/LuckPerms#1152]
Hello !
Here is my problem I have a restApi for my server and I would like luckperms can respond to a request via a provider if possible any idea ???

**Comment by lucko** [comment]
Your options are:

* Implement a webserver within a plugin and use the LP API to read data
  * Information about this is available here https://github.com/lucko/LuckPerms/wiki/Developer-API
* Read the database manually from a standalone app
  * The database schemas should be fairly self explanatory.
