### ISSUE TITLE
[plugin interference] Bungeecord error[Solved]

### ISSUE THREAD

**Issue by downboy** [lucko/LuckPerms#1153]
the first error i get on startup: https://hastebin.com/fawidajaji.rb

then when a player login in:  https://hastebin.com/ixipinafag.cs

and for the logout: https://hastebin.com/oxixubewas.pl

i hope you can fix this :)

**Comment by lucko** [comment]
Can you show me the output of `/bungee`, and give a list of the plugins you have installed on the proxy.

**Comment by downboy** [comment]
The command  `/bungee` show this:
`> 00:51:13 [INFO] This server is running BungeeCord version git:BungeeCord-Bootstrap:1.13-SNAPSHOT:715ec07:1348 by md_5`

a list of all the plugin if use on the proxy:
[proxy plugin list](http://prntscr.com/ki92gi)

**Comment by lucko** [comment]
Huh, honestly I'm not sure on this one. Will look into it a bit more later, but my guess is some sort of incompatibility with another plugin.

**Comment by downboy** [comment]
The issue only appears when I add the plugin called "plan" to my proxy. They use HikariCP now. I already ask the dev from the plugin. He told me it was not his plugin that was making the error so he couldn't help me.

Url to the plugin: https://www.spigotmc.org/resources/plan-player-analytics.32536/

**Comment by KleinCrafter** [comment]
LP use HikariCP Version 3.2.0: https://github.com/lucko/LuckPerms/blob/fec87d4c6afb4de14ebd7c166a34548f45e29609/common/build.gradle#L32
PPA use HikariCP Version 3.1.0: https://github.com/Rsl1122/Plan-PlayerAnalytics/blob/385772a6a53948463a0cf59460b38104699a1bfe/Plan/pom.xml#L115

**Comment by lucko** [comment]
It shouldn't really matter, because LuckPerms shades Hikari to it's own namespace.

The issue is due to the loading of SLF4J.

**Comment by downboy** [comment]
But the question still remains, what plugin is making the issue?? Is it plan or LP.

**Comment by lucko** [comment]
Uhh, I'm not totally sure at the moment.

I'll do a bit of testing myself and see if I can reproduce the issue :)

**Comment by downboy** [comment]
i have found the issue, the plugin that makes the issue is not LP or plan. It was MaintenanceMode plugin.

**Comment by Rsl1122** [comment]
I have opened an issue on Maintenance issue tracker although it is not my plugin that is causing this issue.

**Comment by lucko** [comment]
I'd imagine if the loading order was reversed (by adding a dependency on either plugin), the error would occur in the other plugin. :)

**Comment by Rsl1122** [comment]
Turns out this was caused by Plan not relocating `org.slf4j.Logger`

Fix provided in the referenced issue above (701)
