### ISSUE TITLE
Command box bug in the WebPanel

### ISSUE THREAD

**Issue by itaquito** [lucko/LuckPerms#1154]
Hey! When you save twice in the WebPanel and then you scrow up this happens.

![image](https://user-images.githubusercontent.com/30180886/43996125-b5a6158a-9d81-11e8-820d-d62d5f57bae5.png)

and if you save more times it gets even better!

**Comment by lucko** [comment]
Please re-create your report here: https://github.com/lucko/LuckPermsWeb
