### ISSUE TITLE
Request Feature LP verbose showing the name of the group causing permission to be true/false/undefined 

### ISSUE THREAD

**Issue by HackoHaxsLord** [lucko/LuckPerms#1155]
Currently LP verbose shows the user, permission and state. It also includes more information when you click on the section.

Would it be possible to also include the name of the group which is causing the permission to be in that state?

**Comment by lucko** [comment]
This isn't really possible without negatively effecting the performance of the permission check.

The result is cached behind the verbose logging, so it would require storing lookup data in memory for all checks made, even when verbose is disabled.

Thank you for the suggestion, but unfortunately I don't think it's something I'm going to implement. :)
