### ISSUE TITLE
permissions all messed up out of nowhere.

### ISSUE THREAD

**Issue by vkaygaming** [lucko/LuckPerms#1156]
hi, so i'm not sure how to use verbose since that's what someone said earlier but let me explain my issue further

i know not all of this is relevant to luckperms but humor me since you might be abe to see a correlation that i cant.

i noticed after coming online today that 1 my worldguard had just gone and evaporated
the plugin was still there but the regions were gone
2 the npc's that i had made last night were gone, the ones from before remained (as a sidenote, we set up the worldguard 2 days ago on this particular server and a rollback of the server itself doesnt seem plausible because all the kingdoms (its a kingdoms server) and their progression were untouched
and i only mention these 2 issues that i have fixed because maybe you fine folk can see a correlation that i cant but besides that the issue that does relate to luckperms is the fact that my groups still exist, suffixes, prefixes all this is still set.

the people that were op are op etc, BUT me and others have lost the ability to /fly, /fly others, go into gamemode etcetera
its like the permissions just flipped
the people that shouldnt be able to fly were flying and the ones that should werent
causing a fair bit of mayhem and eventual bans sadly

i tried to fix it myself by manually readding the permissions to the groups, this did not work at all
i'm in the owner group and despite giving myself essentials.fly or essentials.fly.use, essentials.fly.* or essentials.flyy.others i still could not fly
i did manage to get my creative to work
and for the default roles to no longer be able to use gamemode
but only by taking it away user per user from them
and not by groups

**Comment by codingJWilliams** [comment]
Sounds like something happened to your database, causing it to drop luckperms data, worldguard data etc. Not really a luckperms issue

**Comment by lucko** [comment]
I think @codingJWilliams 's suggestion is most likely what happened, but I'm just guessing too. :(

Without knowing specifics about individual broken permission assignments, etc, there's not really much we can do to help you. :/
