### ISSUE TITLE
Web Editor Bug

### ISSUE THREAD

**Issue by VKartze** [lucko/LuckPerms#1157]
(my english is bad, so i'll use pictures)
Group "admin" exists, it has permissions, prefixes etc 
![2018-08-14_14 15 59](https://user-images.githubusercontent.com/41291372/44077120-c7f05bc2-9fcc-11e8-8a5d-a07fc38dbb5d.png)
but this happens when try to apply changes made in web editor
![2018-08-14_14 16 28](https://user-images.githubusercontent.com/41291372/44077191-ffab1e08-9fcc-11e8-8769-b492c7c9bc66.png)
i can create any group, define it's perms using commands and this will work, but LP cannot apply changes made in web editor even for "default"!

**Comment by RJHaytree** [comment]
Hi there, can you please make sure you're on the latest update from here please https://ci.lucko.me/job/LuckPerms/

There was a fix made for this previously
