### ISSUE TITLE
LuckyPerms and Worldedit

### ISSUE THREAD

**Issue by commandocody116** [lucko/LuckPerms#1158]
Hi, I am trying to prevent the default permission from using world edit, but I have been unsuccessful thus far. I did try this "/lp group default permissions set worldedit.* false" but this didn't seem to work. I also noted that the autofill for the command groups, where it says minecraft and bukkit, does not mention worldedit. I would like to prevent people from crashing the server time and time again by removing the permissions for it from everyone. Please help me, this has begun to frustrate me.

Thank you,
Claire (psuedonym)

**Comment by BrainStone** [comment]
Make sure that you’re not using another perms plugin besides LuckPerms and that all users are either in the default group directly or that the group they are in inherits default.

**Comment by lucko** [comment]
The verbose command may also help you to diagnose the problem. :)

https://github.com/lucko/LuckPerms/wiki/Verbose
