### ISSUE TITLE
LuckPerms Doesn't Work

### ISSUE THREAD

**Issue by xXramezXx** [lucko/LuckPerms#1159]
I Downloaded The Latest Version Of LuckPerms And When I Type /plugins the plugin is in red color.
Im Running 1.8 Spigot

**Comment by merjilin** [comment]
Update spigot to 1.8.8 if you must run your server on a version of 1.8.

**Comment by Andre601** [comment]
But it's also highly recommended to use the latest Spigot-version (1.12.2 since 1.13 isn't that stable) since those have all mostly fixes to known bugs in 1.8.8 and additional content.
