### ISSUE TITLE
How to change the player group?

### ISSUE THREAD

**Issue by Eustiya** [lucko/LuckPerms#1160]
![image](https://user-images.githubusercontent.com/36254769/44192850-86311d00-a163-11e8-889e-9d125fc17269.png)
Pointed place without effect
Player is still in original group
plz help me fix this problem
be  deeply grate ful

**Comment by codingJWilliams** [comment]
setPrimaryGroup only works if the player has the group. See https://gitlab.com/nightborn_mc/bungee_side_plugins/blob/master/src/main/kotlin/me/voidcrafted/bungeeplugins/DiscordAuthenticator.kt#L37 for an example. If you wanted to set the group, replace my predicate in clearMatching with one that returns true if the node is a group node

**Comment by BrainStone** [comment]
https://github.com/lucko/LuckPerms/wiki/Developer-API:-Usage#modifying-usergroup-data

**Comment by Eustiya** [comment]
thank you
