### ISSUE TITLE
Luckperms save the incorect uuid if a user try to login on authme with incorect capitalizazion (

### ISSUE THREAD

**Issue by xion87** [lucko/LuckPerms#1161]
i installed luckperms on bungee, when a user try to login, (i got authme and authmebungee that kick if the name is not equal in same format (example bOb instead Bob), if bOb will enter and wiill be kicked from authme but the incorect UUID is being saved by luckperms and trow the warn (https://gist.github.com/xion87/5f0085ac3d2c84ee3fca57b5872d0ed1).

In my bungee i have use-server-uuids: false, instead all servers have use-server-uuids: true
(both bungee and servers are in offline mode)

**Comment by lucko** [comment]
That's because users are given different UUIDs depending on the capitalisation of their username. That's just something you're going to have to accept if you run a cracked server.

I don't see what I could do to "fix" this in LuckPerms.

**Comment by xion87** [comment]
so my config is correct? you can just make some delay before updating the UUID on table?

**Comment by lucko** [comment]
Why would I do that - it's not going to solve the root cause?

**Comment by xion87** [comment]
because the user with wrong name is not going to enter in server (is kicked by authme, so it stay online for like 1s), user with correct name will not kicked and the luckperms will have alway the correct UUID

**Comment by lucko** [comment]
If you don't want users with incorrect UUIDs to even be processed by the server, then AuthMe needs to kick them at a protocol level, before their profile is handled by plugins.

**Comment by xion87** [comment]
posssibly using authmebungee so, ok i got it

**Comment by sgdc3** [comment]
@lucko Can't you just treat usernames as case sensitive?

**Comment by lucko** [comment]
No, Mojang considers them case-insensitive, so LuckPerms does the same.

**Comment by sgdc3** [comment]
@lucko maybe make it configurable? I can't implement that into authmebungee in the current state, as it doesn't have any access over the db, it uses plugin messaging only.

**Comment by lucko** [comment]
Not easy to make that sort of handling configurable.

> users are given different UUIDs depending on the capitalisation of their username. That's just something you're going to have to accept if you run a cracked server

As I said before ^^, I don't believe this is an issue LP should be responsible for solving.
