### ISSUE TITLE
webeditor problem: "Target group <group> does not exist"

### ISSUE THREAD

**Issue by RedstoneFuture** [lucko/LuckPerms#1168]
If I use the webeditor to set new permissions for group e.g. "moderator" I get ingame the follow messages:

> Target group moderator does not exist. No changes were applied from the web weditor. The returned data didn't contain any adits.

With "/lpb group Moderator permission set plots.add hs bauevent" LuckPerms set the permission.

replication:

1. "/lpb group <groupname> editor"
2. add or delete a permission in the web-interface
3. use the "/lpb applyedits ..." command from the web-interface

installations:

- LuckPerms version: 4.2.58
- MySQL 8
- no errors or warnings
- BungeeCord + PaperSpigot 1.12.2

notes: I use the feature:

- group-name-rewrite:
-   moderator: '&2Moderator'

**Comment by lucko** [comment]
Update to the latest dev build.

https://luckperms.github.io/
