### ISSUE TITLE
small chat-style "bug"

### ISSUE THREAD

**Issue by RedstoneFuture** [lucko/LuckPerms#1170]
With the feature:

> group-name-rewrite:
>  moderator: '&2Moderator'

the group-color uverwrite the first character color:

![2018-08-21_23 42 04](https://user-images.githubusercontent.com/4140635/44430769-0a3c3800-a59c-11e8-8aca-ca3c598a0aed.png)

Maybe the plugin can add a "&r" at the end of add renamed group-name for a better usability. ^^

**Comment by lucko** [comment]
It's not really easy for me to fix this - the brackets are applied inline, before the format.

Potential options are:

* Stripping all color from display names when they're formatted
* Disallowing color codes in display names completely

Neither of those are particularly attractive to me - so I think it's just going to have to stay the way it is.

So yea, this will just be a quirk if you choose to use color codes for the aliased names. Simply appending the reset char doesn't work, as it just makes the following bracket white.

**Comment by RedstoneFuture** [comment]
And a "&b" (teal) bevore the ")" isn't a solution too? Okay. ^^

**Comment by lucko** [comment]
No because

> the brackets are applied inline, before the format

In other words, when the brackets are added, it's not known that `&b` will be the color.
