### ISSUE TITLE
1.13.1 support

### ISSUE THREAD

**Issue by TheIntelloBox** [lucko/LuckPerms#1174]

**Comment by RJHaytree** [comment]
Please test the latest dev build from here https://ci.lucko.me/job/LuckPerms/

If it does not work, please provide your full latest.log in paste service such as gist.github.com

**Comment by Wyzcraft** [comment]
Hello RJHaytree,
I've tried the build 4.2.82. The server loads, but when I do /lp editor it freezes and gives me errors.
Please find in attachment the latest log file.
Hope it can help.

[latest.log](https://github.com/lucko/LuckPerms/files/2335818/latest.log)

**Comment by lucko** [comment]
@Wyzcraft Different issue, should be fixed now
