### ISSUE TITLE
NodeAddEvent called when checking permissions

### ISSUE THREAD

**Issue by TauCubed** [lucko/LuckPerms#1177]
Reproduction steps:
1. Set/(Join as) a user (to have/that has) no explicit group(s) or permissions.
2. Listen for NodeAddEvent
3. /lp user <user> listnodes

My thoughts on why:
Perhaps the plugin adds then removes a node to display "default" groups.

Reasons why this is a bug:
Make it impractical for another plugin to listen for specific node changes

My thoughts on a solution:
1. Add enum for checking reason for (Add|Remove)/mutate
2. Prevent LP from firing this event for seemingly no reason.

**Comment by lucko** [comment]
c59f2ab37aa0267252b676bfe1fbe64bed8cf9f7
