### ISSUE TITLE
user.getPermissionValue does not check default user

### ISSUE THREAD

**Issue by bloodmc** [lucko/LuckPerms#118]
https://github.com/MinecraftPortCentral/GriefPrevention/blob/master/src/me/ryanhamshire/griefprevention/permission/GPPermissionHandler.java#L127

If the user does not have a permission set with the passed context, it should be checking default user automatically but it does not forcing GP to do it manually here

https://github.com/MinecraftPortCentral/GriefPrevention/blob/master/src/me/ryanhamshire/griefprevention/permission/GPPermissionHandler.java#L168

**Comment by lucko** [comment]
It definitely is checking.

https://github.com/lucko/LuckPerms/blob/master/sponge/src/main/java/me/lucko/luckperms/sponge/calculators/DefaultsProcessor.java
https://github.com/lucko/LuckPerms/blob/master/sponge/src/main/java/me/lucko/luckperms/sponge/SpongeCalculatorFactory.java#L55

**Comment by bloodmc** [comment]
It does not work

I checked the following perm

griefprevention.flag.projectile-impact-entity.minecraft.source.pixelmon.occupiedpokeball

the default subject json had this
    {
        "gp_claim": "66d63200-c3f2-41db-b8ef-24628458fbfb"
      },
      {
        "griefprevention.flag.projectile-impact-entity.minecraft.source.pixelmon.occupiedpokeball": true
      }

The result was UNDEFINED

**Comment by bloodmc** [comment]
@lucko I just tested with latest dev build and this issue still occurs.

[me.ryanhamshire.griefprevention.permission.GPPermissionHandler:getUserPermission:140]: 
value = UNDEFINED
contexts [gp_claim=122b2c6c-abf8-4233-b7c4-b848ec334cd7]
permission griefprevention.flag.block-break.minecraft.grass.source.minecraft.player.0

This is in my default.json
      {
        "gp_claim": "122b2c6c-abf8-4233-b7c4-b848ec334cd7"
      },
      {
        "griefprevention.flag.block-break": true
      }

**Comment by bloodmc** [comment]
[21:43:19] [Server thread/INFO] [STDOUT/]: [me.lucko.luckperms.sponge.service.persisted.PersistedSubject:getPermissionValue:254]: getPermissionValue ImmutableContextSet(contexts={world=[world], gp_claim_defaults=[BASIC]}), node griefprevention.flag.interact-block-primary.minecraft.stone.source.minecraft.player.0, t = FALSE

Restarting the server always works but when I change the value, while in game, it seems LP never updates cache and continues to use the PersistedSubject value.

**Comment by lucko** [comment]
Change which value, and by what means? Using commands, editing the file??

**Comment by lucko** [comment]
Please reopen if this isn't fixed, but I recall you saying it wasn't happening anymore?
