### ISSUE TITLE
UserManager#savePlayerData doesn't actually register a player that has not joined the server.

### ISSUE THREAD

**Issue by Aerodog** [lucko/LuckPerms#1181]
Setting the primary group of a player that has not joined returns null after using this method.

**Comment by lucko** [comment]
Sample code? What storage type are you using?

The code for `UserManager#savePlayerData` is just a straightforward insert query. It definitely works for players that haven't joined the server.

> Setting the primary group of a player that has not joined returns null after using this method

That may indeed be true, but it's not related to this issue. :) (perhaps more related to #1182)
