### ISSUE TITLE
Group#getDisplayName returns nothing if the group doesn't have a display name, but group info shows it should default to the friendly name.

### ISSUE THREAD

**Issue by Aerodog** [lucko/LuckPerms#1183]
If it doesn't default to the friendly name, can it? 😝

**Comment by lucko** [comment]
This is intended behaviour.

`Group#getDisplayName` returns a value only if the group has a *different* display name set. In other words, a display name that differs from it's actual name.

The `#getFriendlyName` method always returns a value, eventually falling back to the actual name.


https://github.com/lucko/LuckPerms/blob/38613e5f03e6e4163199464dd575eaafca629fb0/api/src/main/java/me/lucko/luckperms/api/Group.java#L49-L61

https://github.com/lucko/LuckPerms/blob/38613e5f03e6e4163199464dd575eaafca629fb0/api/src/main/java/me/lucko/luckperms/api/PermissionHolder.java#L74-L90
