### ISSUE TITLE
Feature request: Permissions lock

### ISSUE THREAD

**Issue by Leomixer17** [lucko/LuckPerms#1184]
LuckPerms is of curse the best permissions plugin, with the largest variety of features, but there is a new permissions plugin (PermissionsPlus) that has a feature that LuckPerms doesn't have: the permissions lock.
It allows you to temporarily disable the permissions of an user without having to remove them or having to remove the group. It can be very useful when testing permissions, because in this way you don't have the hassle to remove existing permissions or login with another account. But it can also be an extra measure of safety.

**Comment by lucko** [comment]
I honestly don't see how this would be useful.

If you removed all of a users permissions, then surely any "test" checks would just return false? I've never felt the need for this sort of feature in all of the years of MC server admin-ing :)

I don't want to just add functionality for the sake of it - it needs to be useful for the majority of users.

**Comment by lucko** [comment]
Assuming groups are being used properly, this should just be as simple as running `/lp user <user> parent set default`.

My opinion is that a dedicated command for this feature doesn't really fit within LuckPerms. Thank you for the idea anyway! :)
