### ISSUE TITLE
Feature request: Permissions finder

### ISSUE THREAD

**Issue by Leomixer17** [lucko/LuckPerms#1185]
LuckPerms is of curse the best permissions plugin, with the largest variety of features, but there is a new permissions plugin (PermissionsPlus) that has a feature that LuckPerms doesn't have: the permissions finder.
It allows you to find a permission: when executing an action, it shows you the permission required to execute it.

**Comment by RJHaytree** [comment]
This is already a feature in luckperms, but is instead called 'verbose' rather than a permission finder. https://github.com/lucko/LuckPerms/wiki/Verbose

**Comment by Leomixer17** [comment]
@RJHaytree ok thanks, I had not found it
