### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by morgan2233** [lucko/LuckPerms#1187]
First im using MySQL and all plugin permissions do work

However i have tried time and time again but i can not negate permissions...

i have tried to add as a perm -bukkit.command.help i have also tried bukkit.command.help with a status of false but in both formats the help command still works without restrictions etc

With pexs doing "- --bukkit.command.help" (file format) worked.

**Comment by lucko** [comment]
You negate permissions by setting a false flag.

e.g.

`/lp group default permission set bukkit.command.help false`


Other things to note is that you may have another plugin (e.g. Essentials) that's overriding the help command on your server. You can use the verbose command to debug this.

https://github.com/lucko/LuckPerms/wiki/Verbose
