### ISSUE TITLE
Hello permision Placeholders

### ISSUE THREAD

**Issue by LoToRTv** [lucko/LuckPerms#1190]
Hello there is some possibility Placeholders permisions other server npr.. %luckperms_inherits_permission_server_permission% ? 

Iknow https://github.com/lucko/LuckPerms/wiki/Placeholders I have not found anything similarly.

THX for help sorry for my bad eng.

**Comment by lucko** [comment]
Yes, you're right, there's not a placeholder for this at the moment.

The placeholder integration is a separate project, so if you don't mind, I'd appreciate it if you could create another ticket for your suggestion there.

https://github.com/lucko/LuckPermsPlaceholders

Thanks!
