### ISSUE TITLE
FastAsyncWorldEdit throws a NPE when LuckPerms is enabled [Nukkit]

### ISSUE THREAD

**Issue by funniray** [lucko/LuckPerms#1191]
Only when LuckPerms is installed, FAWE throws an NPE when you try to do /wea.
![image](https://user-images.githubusercontent.com/16416198/44957702-c4884500-aea2-11e8-9837-be914fe73776.png)
https://github.com/boy0001/FastAsyncWorldedit/issues/1108

**Comment by lucko** [comment]
This is a FAWE bug. :)
