### ISSUE TITLE
Sync only rank ?

### ISSUE THREAD

**Issue by CryLegende** [lucko/LuckPerms#1194]
Hello,
I would like to know if it is possible to sync only the rank of the player and not these permissions.

Thanks you !

**Comment by lucko** [comment]
Perhaps split storage is what you're looking for? (check the config)


Beyond that, no there's not any functionality like it.

**Comment by CryLegende** [comment]
I'd like to link my lobby ranks with my Faction server but not permissions.
For example: I give the permission "essentials.fly" on the lobby, the player can fly on the lobby but it does not put the permission on the faction
