### ISSUE TITLE
Hello  I need one placeholder rly fast 

### ISSUE THREAD

**Issue by LoToRTv** [lucko/LuckPerms#1195]
Hello would be possible ? 

add placeholder %luckperms_inherits_permission_server_permission% or %luckperms_inherits_permission_world_permission% 

We need on one big project.... I wrote here https://github.com/lucko/LuckPermsPlaceholders/issues/8 
I give money for add placeholder thx for fast suport :) 

SORRY FOR SPAM

**Comment by lucko** [comment]
No, you need to be patient. 🙂 

It will be added when I have time to work on it. Alternatively, you or someone else could make a pull request to add support for it.

**Comment by LoToRTv** [comment]
how add pull request ? I need it enough......
