### ISSUE TITLE
Automatic organizator

### ISSUE THREAD

**Issue by GuerreroCraft61** [lucko/LuckPerms#1197]
Suggest: Add a automatic alphabetic organizator to order permissions in the "config/yml data" and in the "web editor"

**Comment by lucko** [comment]
The file data is already sorted - it's sorted alphabetically, after priority order.

You can also do sorting on the web editor by clicking on the column you want to sort by.
https://github.com/lucko/LuckPerms/wiki/Web-Editor#sorting-the-data
