### ISSUE TITLE
Import groups from h2 storage to yaml.

### ISSUE THREAD

**Issue by RikoDEV** [lucko/LuckPerms#12]
How to move permissions and groups from h2 database to yaml? When I changed the type of storage to yml rank were not transferred.

And how to set default group? Like Player is the default.

**Comment by lucko** [comment]
Make sure you're using the latest build from https://ci.lucko.me/job/LuckPerms/

1. Run "/luckperms export \<file\>". 
2. Stop your server, switch the storage option.
3. Start your server and run "/luckperms import \<file\>"

**Comment by RikoDEV** [comment]
@lucko on latest 2.8.12 this command is not found and send the help commands:

![2016-09-10_17 22 25](https://cloud.githubusercontent.com/assets/18230443/18411638/9b57e84e-777b-11e6-9196-3083a57e3a9d.png)

**Comment by RikoDEV** [comment]
@lucko error in console:
![error](https://cloud.githubusercontent.com/assets/18230443/18411697/e77a763c-777c-11e6-936d-f6237ac050b6.PNG)

**Comment by lucko** [comment]
f9025c7a51b3bcbb74548d28b2cfd80d99c96476 should fix it.

Use this build: https://ci.lucko.me/job/LuckPerms/129/

**Comment by RikoDEV** [comment]
Now work, thanks :)
