### ISSUE TITLE
Server Set problems

### ISSUE THREAD

**Issue by Heroruler** [lucko/LuckPerms#1200]
Hey, so my problem is when I am creating my ranks at first are to global and they work but when I am setting the and also via commands or via web editor is not working  only the permissions are being added to the player and the default rank stills remains I want to say I am using the latest LuckPerms version also and the LuckPerms Bungee addition I did have set the weights correctly and I have also change the server: global to Server: skywars into the config file also I am using MYSQL. The global ranks are working tho only the ranks that are being set to a single server are not working

**Comment by BrainStone** [comment]
So do I understand correctly that when set a group or a permission per server it doesn't work?

If so did you set the server names in the LP configs?

**Comment by Heroruler** [comment]
yes I did but when I am setting it up from the webeditor or from the in-game I don't know what happens but you get only the permissions and not rank the rank it stills default due to I have set the staff ranks and the member rank as global and I  want to set donator ranks per server but when I do that they are working for a bit and when I am adding a permissions and changing to global the ranks are not working

**Comment by lucko** [comment]
Sorry for the super late reply, this issue slipped past me.

Can you show some screenshots of what you mean? I'm struggling to follow exactly what the problem is.

**Comment by Heroruler** [comment]
when I try to set it the permissions per server the player gets the permissions put the prefix of the rank is not going to the player it. I have it like the Member rank and the staff ranks to global but the donator ranks per server.

**Comment by BrainStone** [comment]
What chat plugin do you use?

**Comment by Heroruler** [comment]
I am using vaultchatFormat
on global ranks is working just fine but on ranks per server is not

**Comment by lucko** [comment]
Can you show the output of `/lp user <player> meta info`, `/lp user <player> info` (for the player with broken prefixes) and `/lp info`

**Comment by Heroruler** [comment]
alright

**Comment by Heroruler** [comment]
also I want to add when I am starting the server I am getting this warns

INFO Loading configuration...
08.10 14:09:02 [Server] INFO Loading storage provider... [MYSQL]
08.10 14:09:02 [Server] INFO luckperms-hikari - Starting...
08.10 14:09:02 [Server] INFO luckperms-hikari - Start completed.
08.10 14:09:02 [Server] WARN me.lucko.luckperms.lib.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'fh_2587.luckperms_actions' doesn't exist
08.10 14:09:02 [Server] WARN at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
08.10 14:09:02 [Server] WARN at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
08.10 14:09:02 [Server] WARN at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
08.10 14:09:02 [Server] WARN at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
08.10 14:09:02 [Server] WARN at me.lucko.luckperms.lib.mysql.jdbc.Util.handleNewInstance(Util.java:425)
08.10 14:09:02 [Server] WARN at me.lucko.luckperms.lib.mysql.jdbc.Util.getInstance(Util.java:408)
08.10 14:09:02 [Server] WARN at me.lucko.luckperms.lib.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
08.10 14:09:02 [Server] WARN at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)
08.10 14:09:02 [Server] WARN at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
08.10 14:09:02 [Server] WARN at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
08.10 14:09:02 [Server] WARN at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
08.10 14:09:02 [Server] WARN at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2491)
08.10 14:09:02 [Server] WARN at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2449)
08.10 14:09:02 [Server] WARN at me.lucko.luckperms.lib.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:845)
08.10 14:09:02 [Server] WARN at me.lucko.luckperms.lib.mysql.jdbc.StatementImpl.execute(StatementImpl.java:745)
08.10 14:09:02 [Server] WARN at me.lucko.luckperms.lib.hikari.pool.ProxyStatement.execute(ProxyStatement.java:95)
08.10 14:09:02 [Server] WARN at me.lucko.luckperms.lib.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java)
08.10 14:09:02 [Server] WARN at me.lucko.luckperms.common.storage.dao.sql.SqlDao.init(SqlDao.java:202)
08.10 14:09:02 [Server] WARN at me.lucko.luckperms.common.storage.AbstractStorage.init(AbstractStorage.java:122)
08.10 14:09:02 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
08.10 14:09:02 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
08.10 14:09:02 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
08.10 14:09:02 [Server] WARN at java.lang.reflect.Method.invoke(Method.java:498)
08.10 14:09:02 [Server] WARN at me.lucko.luckperms.common.storage.wrappings.PhasedStorage.lambda$wrap$0(PhasedStorage.java:64)
08.10 14:09:02 [Server] WARN at com.sun.proxy.$Proxy15.init(Unknown Source)
08.10 14:09:02 [Server] WARN at me.lucko.luckperms.common.storage.StorageFactory.getInstance(StorageFactory.java:117)
08.10 14:09:02 [Server] WARN at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:132)
08.10 14:09:02 [Server] WARN at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onEnable(LPBukkitBootstrap.java:152)
08.10 14:09:02 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
08.10 14:09:03 [Multicraft] Skipped 12 lines due to rate limit (30/s)

even tho the global ranks and the MySQL works perfect.

**Comment by lucko** [comment]
`Table 'fh_2587.luckperms_actions' doesn't exist` is the important part of the error.

It seems that the actions table has been deleted? Perhaps you did that by mistake?

If you know how to use MySQL, you can re-create it by running the query from the schema file.
https://github.com/lucko/LuckPerms/blob/f96518b8e4c8eba2e99dd2daf6b4e045937c0bba/common/src/main/resources/me/lucko/luckperms/schema/mysql.sql#L44-L54

Alternatively, export all of your data using the `/lp export` command - then change the table prefix (to target a different set of tables) and restart your server, before importing the data.

https://github.com/lucko/LuckPerms/wiki/Command-Usage:-General#lp-export
https://github.com/lucko/LuckPerms/wiki/Command-Usage:-General#lp-import
https://github.com/lucko/LuckPerms/blob/f96518b8e4c8eba2e99dd2daf6b4e045937c0bba/bukkit/src/main/resources/config.yml#L139-L141

**Comment by Heroruler** [comment]
I dont know how to mysql and I didnt even touch the mysql. So idk what happened what else can I do except of coding on mysql.

**Comment by Heroruler** [comment]
Also what do you mean by changing the table prefix

**Comment by SomeRqndomName** [comment]
Prefix as in “lp_” or if my name was the prefix “somerqndomname_”

Sorry for randomly joining this convo by the way.

**Comment by BrainStone** [comment]
You can set the table prefix in the config.

**Comment by Heroruler** [comment]
Ok ty
