### ISSUE TITLE
Issue with tracks and default

### ISSUE THREAD

**Issue by blakepete** [lucko/LuckPerms#1201]
Users auto added default
promoted user to track
added default group to the track
cannot promote or demote because player located on track twice.

it seems the error message seems to exist because of this case. might it be possible on the addition of a group to a track for the plugin to "clean" affected profiles and remove lowest rank, or an option to chose to enable this clean up?

**Comment by lucko** [comment]
Perhaps using the cleartrack command?
https://github.com/lucko/LuckPerms/wiki/Command-Usage:-Parent#lp-usergroup-usergroup-parent-cleartrack
