### ISSUE TITLE
Server hangs when initially loading data

### ISSUE THREAD

**Issue by Brycey92** [lucko/LuckPerms#1202]
[This](https://gist.github.com/Brycey92/d3d4139c5be57aa400387b25dd7f3743) is the log for my server startup. As it shows, after LP loads data, nothing else happens, but the file watcher still works. Version 4.2.87 works normally, but 4.2.89 does not.

**Comment by Brycey92** [comment]
I just tested 4.2.89 again on my server, and the hang no longer happens. It may have been related to specific mod/plugin configurations or mods/plugins installed at the time.

**Comment by lucko** [comment]
Ok, feel free to re-open if it happens again.
