### ISSUE TITLE
Lack of documentation for default-contexts

### ISSUE THREAD

**Issue by codingJWilliams** [lucko/LuckPerms#1206]
I can't see any documentation on the contexts.yml/default-contexts option. Here's something I wrote  that could go at the end of https://github.com/lucko/LuckPerms/wiki/Context#defining-static-contexts but I'm open to improvements :rofl: 

---

### Default Contexts
Default contexts allow you to specify contexts that are applied to commands if you don't add contexts to the end of the command - for example `/lp user Luck permission set example.permission`. You can define them in the `contexts.yml` file, in the same folder as the main config.

For example, to add a default context to the file, simply add, below the static-contexts section:

```json
{
 "default-contexts": {
    "world": "world_nether",
    "server": "survival"
  }
}
```

This would mean that, for `/lp` commands on the server which you've added the default context, any commands that can be performed with a context will use `world=world_nether,server=survival` unless you specify otherwise.

**Comment by lucko** [comment]
Thanks, merged with https://github.com/LuckPerms/wiki/commit/7a98e73319db8cb553e7d1df66676eaf207eae27
