### ISSUE TITLE
Improve permission unset command autocomplete

### ISSUE THREAD

**Issue by JimusHimus** [lucko/LuckPerms#1207]
Make autocomplete /lp user <user> permission UNset ... better. Now all possible perms are represented there, I propose to make unset only those perms that are available to the player of the group, and so on.

**Comment by lucko** [comment]
This is computationally too complex for tab completions in my opinion. Needs to be fast as they're ran on the main thread.

I'm going to close this suggestion on the basis that it's unlikely to make it into the main plugin in the near future. A quality PR implementing this functionality would likely still be accepted, but it's not something I'm going to work on. :)
