### ISSUE TITLE
Group Removal

### ISSUE THREAD

**Issue by tmoflash** [lucko/LuckPerms#1216]
I cannot leave group. 

I was doing some testing to set up stacked prefixes - I finally got it all working. However, I went to remove myself from the groups no longer needed. I did it using in-game commands /lp user [user] parent remove [group] - It still shows up as a prefix. I checked the user file it was no longer there (YAML) I also checked the editor and it is no longer there. I ran /lp reloadconfig /lp sync and also did a restart.

http://prntscr.com/kubvbu

uuid: [my uuid]
name: tmoflash
primary-group: default
parents:
- default
- owner
- staff

http://prntscr.com/kubwik

I also tried to add myself back to the group and then remove.

**Comment by BrainStone** [comment]
What’s the output when you remove the groups and you run `/lp user <you> info`

**Comment by tmoflash** [comment]
http://prntscr.com/kucimz

**Comment by tmoflash** [comment]
Well kinda. The ultimate goal is for users are are in all 3 groups to show up as so. However, this isn't always the case. The way it should look is. If they are in vip, staff, own.

[VIP] [Staff] [Rank] however, I have removed myself from VIP but it still shows up as a prefix, but I am not in that group. I have inheritance setup (it may not be correct) but I do have it set up. 
**Basic Group**
default (peasant) > freeman (parent default) > metics (parent freeman) > tyrant (parent freeman) > hero (parent tyrant)

**VIP**
centaur (parent hero) > minotaur (parent centaur) > olympian (parent minotaur) > titan (parent olympian) > primordial (parent titan)

**Staff**
helper (parent centaur) > mod (parent helper) > admin (parent mod) > headadmin (parent admin) > owner (parent headadmin)

**Comment by BrainStone** [comment]
I gave you the command you can use to check which prefixes you inherit from where. If VIP still shows up, then you inherit it indirectly through another group (maybe several layers deep of inheritance)

**Comment by tmoflash** [comment]
/lp user [nam] info that command?

If so this is what shows up. http://prntscr.com/kudzs0 

How to I remove that inheritance?

**Comment by tmoflash** [comment]
Oh I see command /lp user [name] meta info
http://prntscr.com/kue1pi

**Comment by BrainStone** [comment]
No. `/lp user <you> meta info`. Reading my answers would help.

Anyways you remove the inheritance by changing the group inheritance structure. In other words you need to figure out what the inheritance chain is and change it so that you get the desired behavior. You might end up having to not use inheritance at all or having a set of groups with permissions that use the inheritance like before and the have prefix groups, which inherit from the corresponding normal group and add the desired prefix. And make sure to only assign these groups.

**Comment by tmoflash** [comment]
So what I did was added myself to the primordial group as well as the vip group. (VIP is also a track) It showed up correctly once in VIP group. I then removed myself from both the primordial as well as the vip group but [Centaur] shows back up.

**Comment by tmoflash** [comment]
It was an inheritance issue as you said. I modified and removed accordingly, did multiple tests adding/removing and it works as intended. Thanks for help.
