### ISSUE TITLE
Im in need of help. Console spam for life!

### ISSUE THREAD

**Issue by Duqino** [lucko/LuckPerms#1219]
Hello,

I dont know which plugin is causing it (bungeetablist or luckperms) so im placing my problem on both sites.

https://pastebin.com/XmCuasgm
https://pastebin.com/1m4cRFgR

Almost full error list:

https://pastebin.com/cDJhNhTB

Help!

Kind regards,

Duqino.

**Comment by codingJWilliams** [comment]
As far as I can tell, that's a BungeeTabList error. If an error happens during a permission check luckperms prints it out, even if it isn't a luckperms error. That's why you have the word luckperms mixed in there :)

**Comment by codingJWilliams** [comment]
Wait scratch that, there's also an error with LP

**Comment by codingJWilliams** [comment]
@Duqino, could you please update to the latest version of LP and try again :)

**Comment by Duqino** [comment]
I did that already. Im running jenkins version. Joined discord today and join message said it so i did :)

**Comment by Duqino** [comment]
In the first pastebin are both bungeetablist and luckperms. Bungeetablist is shown first, that means bungeetablist is causing the problem?

**Comment by lucko** [comment]
This is a LuckPerms issue, duplicate of #1212 

I'm planning to look into it a bit more tomorrow. :)

**Comment by lucko** [comment]
Please use the other ticket to track progress
