### ISSUE TITLE
OpenAudio Stuck Loading

### ISSUE THREAD

**Issue by Clarkcj12** [lucko/LuckPerms#122]
I just updated the OpenAudio plugin to version 1.6.3, but for some reason it is stuck on Loading the Audio Client. Even though it previous versions have not done that before. The audio client is on our website. It only seems to have the problem if you try to connect via in game.

**Comment by Clarkcj12** [comment]
It looks to me it might be the update with the https auto redirect because if I add https to the link it loads successfully, until the auto redirect kicks in then stays on loading the Audio Client page.

**Comment by lucko** [comment]
Uhh, are you sure you're reporting in the right place?

**Comment by Clarkcj12** [comment]
Sorry about this. to many tabs open.
