### ISSUE TITLE
[LP] A database error occurred whilst loading permissions data. Please try again later.

### ISSUE THREAD

**Issue by Adam413** [lucko/LuckPerms#1222]
So, this just barely started happening out of no where.

Currently running LP v4.2.103, but we were previously running v4.2.17 for months actually and this never happened, I upgraded to 103 just 30 minutes ago but it did nothing. Both versions displayed the same exact error listed in the pastebins.

Minecraft 1.12.2 on Forge build 2611, Sponge build 2990. We get this error: https://pastebin.com/0GSxYQPq

This happens when a player attempts to join (with debug-login on): https://pastebin.com/XhJgvyTk

The only thing I spot different is that the H2 database stored on our server is 9.5 MB, or 9,500 KB exactly, it didn't use to be like that but I wouldn't think it would be a huge problem, although perhaps maybe it is a limitation of the database? I wouldn't mind migrating to MySQL but I still need the data in that database.

If there's something else needed, please do ask, we really need this solved ASAP or at least guided towards migrating it to MySQL as /lp export doesn't work since the database isn't even being loaded.

**Comment by lucko** [comment]
Some custom data for a internal subject seems to have been corrupted. Perhaps you made manual changes to one of the LP files?

Should be fixed by the above commit.

**Comment by Adam413** [comment]
Just wanted to update: That commit fixed it, although there still is an error about not reading the defaults.json located in luckperms/sponge-data/defaults/defaults.json, but it doesn't seem to cause any issues. Would you like to see the error displayed in the console?

I looked over some logs on our node and it seems that it had ran out of memory on the operating system's storage drive, which I corrected yesterday. I believe the database was corrupted because it was unable to save when there was "no space" leaving the database in a bad state?

Thanks so much for your work by the way!

**Comment by lucko** [comment]
Yes, please send the error you're seeing

**Comment by Issemoran** [comment]
im confused
