### ISSUE TITLE
Plugin not work (Thermos 1.7.10)

### ISSUE THREAD

**Issue by pingvikin** [lucko/LuckPerms#1223]
**Server Core**: Thermos-1.7.10-1614
**Plugin Version**: LuckPerms-Bukkit-4.2.58

server-log: https://gist.github.com/pingvikin/b79e5cd0b8e3e3176cb58cf21770cd1d

**Comment by lucko** [comment]
Please see https://github.com/lucko/LuckPerms/wiki/Installation#cauldron-thermos-etc
