### ISSUE TITLE
Permissions 

### ISSUE THREAD

**Issue by Darkphenixs01** [lucko/LuckPerms#1226]
Hello,
I'm using the latest version of LuckPerms (4.2.58) on spigot 1.13.
When I set false permissions the players can still use the commands.
<img width="1191" alt="capture d ecran 2018-09-22 a 12 59 00" src="https://user-images.githubusercontent.com/35899335/45916484-60382000-be67-11e8-81ec-e66b57bcc8d9.png">
<img width="107" alt="capture d ecran 2018-09-22 a 12 59 15" src="https://user-images.githubusercontent.com/35899335/45916485-63331080-be67-11e8-9f46-6d69bf69048b.png">

Thank you in advance.

**Comment by Andre601** [comment]
Did you actually click on the save-icon in the editor and run the command in the server?

**Comment by Darkphenixs01** [comment]
Yes, I do /lp group default permission info 
<img width="411" alt="capture d ecran 2018-09-22 a 15 10 49" src="https://user-images.githubusercontent.com/35899335/45917544-c5950c80-be79-11e8-8b8e-1e813cc85c78.png">

**Comment by Andre601** [comment]
Maybe another plugin uses /me

Use the verbose-command too check for the right permissions.

**Comment by Darkphenixs01** [comment]
There is that luckperms WorldEdit and Worldguard.

**Comment by Imortalshard** [comment]
Use the permission minecraft.command.me and set it to false.

**Comment by Darkphenixs01** [comment]
It's already done.

**Comment by Darkphenixs01** [comment]
Thank you.
