### ISSUE TITLE
Negative Permissions with Vault

### ISSUE THREAD

**Issue by haz8989** [lucko/LuckPerms#1231]
In addition to issue #761 I would like to add negative permissions through vault's API (1.7).
For example:
`Permission.playerAdd(player, "-example.permission")`

EDIT: Since my server is being custom developed by me I know that luck perms will be used so i could replace this line with a command being executed however this issue may persist with others.

**Comment by lucko** [comment]
The `-` character at the start of a permission node to denote a negated setting is something specific to the PermissionsEx plugin.

It is not a feature of Bukkit, and doesn't appear to be a documented feature/requirement of the Vault API either.

I'd prefer to see proper methods for setting a boolean "value" added to the Vault API, or at least some sort of documentation noting that use of `-` is expected for negated nodes.

**Comment by haz8989** [comment]
Wow, thanks for the fast reply also I think i may stop using Vault if it starts to become obsolete on my server. Could you direct me to a LuckPerms API that i could use to directly manage permissions through methods? If not I will continue to execute commands.

**Comment by lucko** [comment]
Indeed, I definitely recommend using the native API in LuckPerms if you're writing plugins that don't need to be compatible with multiple permission plugins.

This issue can be reopened in the future if this is brought up again, but as I said previously, I'd like to see a proper solution in Vault as opposed to changing LuckPerms to conform to PEX standards.
