### ISSUE TITLE
give perms ? 

### ISSUE THREAD

**Issue by LoToRTv** [lucko/LuckPerms#1232]
Hello it could be added will give someone your permission example /lp perms give PLAYER all you permision on you nick name give other player and reset you permisie
example: PLAYER1 has permision cmi.command.fly write on chat /lp perms give PLAYER2 
example: PLAYER2 has permision cmi.command.fly
example: PLAYER1 no has permision cmi.cmonad.fly 

I want for warez server example original change nick name or warez change nick name so you can get your permission 

SORRY for bad eng

**Comment by Andre601** [comment]
There is the clone-command [`/lp user <user> clone <user2>`](https://github.com/lucko/LuckPerms/wiki/Command-Usage:-User#lp-user-user-clone), but as far as I understand it do you want a command, that lets you move permissions from one user to another.

I honestly don't really see a benefit of that.
But it's not up to me, to make decitions here.

**Comment by lucko** [comment]
I don't see the benefit either.

You can do a full user clone using the command Andre linked to above - or manually remove the one specific permission from one user and add it to another.
