### ISSUE TITLE
Group Formats Not Displaying In Chat

### ISSUE THREAD

**Issue by Kalasky** [lucko/LuckPerms#1233]
I am currently using Luckperms, ExpansionLuckPerms, and LuckPermsHook. 

My Group Formats are coming from the Spigot plugin "CMI".

This is what I have in CMI's configuration file:
 GroupFormat:
    '1': '%luckperms_prefix% &8{DISPLAYNAME} &8&l> &a{MESSAGE}'
    '2': '{prefix_vault}&f{displayName}&7 > &r{message}'
    '3': '{prefix_vault}&f{displayName}&8 > &r{message}'

**Comment by BrainStone** [comment]
And what exactly isn’t working? You gave a detailed explanation of your setup but not the issue itself (not working isn’t an issue description)

**Comment by Kalasky** [comment]
My group prefixes aren't displaying in chat, all it shows is <user>

**Comment by Kalasky** [comment]
![image](https://user-images.githubusercontent.com/42560806/46088297-fc607080-c160-11e8-9e57-3572e9ab7bc6.png)
 In the screenshot above it shows that I have a prefix but it's not showing up when I type in chat.

**Comment by BrainStone** [comment]
You need a chat plugin for the prefixes to show

**Comment by TheTopCz** [comment]
> You need a chat plugin for the prefixes to show

CMI plug-in can show prefixes, but it looks like it does not work with placeholder

**Comment by BrainStone** [comment]
It looks like CMI isn’t even formatting the chat. As that is the default vanilla chat. LuckPerms itself does no formatting whatsoever. So it looks like you need to properly configure the CMI Chat. How that is done should be documented on the CMI pages/docs/wiki.
