### ISSUE TITLE
Luckperms meta username-color, and other values? Help

### ISSUE THREAD

**Issue by jakeroy** [lucko/LuckPerms#1234]
Hey i'm trying to use the placeholder {luckperms_meta_username-blue} in my chat control formatting. First of all, where can i find a list of available keys i can use, username-blue, etc?

The username shows up correctly, but instead of changing my name to blue, it just says this: https://gyazo.com/c3833917f8f3ac95f2dcb2a13749aad6

Heres what i have in my formatting config:

{luckperms_prefix} {luckperms_meta_username-color}{player}&f: {message}" 

I know an alternative would be to just include it in the prefix such as "&4Owner &f". So the name color would be white. But i want more efficient way to handle prefixes and name colors. Because i'm going to use the format for tab, and other plugins.

**Comment by jakeroy** [comment]
> LuckPerms itself only offers meta values. These are nothing but named values.
> 
> The chat plugin itself must support using meta. And it depends on the chat plugin what meta values are supported and how they are called.

Oh ok. I'm using Chat Control Pro. Any idea if CCP supports meta values?

**Comment by Imortalshard** [comment]
> > LuckPerms itself only offers meta values. These are nothing but named values.
> > The chat plugin itself must support using meta. And it depends on the chat plugin what meta values are supported and how they are called.
> 
> Oh ok. I'm using Chat Control Pro. Any idea if CCP supports meta values?

I currently use CCP for my chat plugin and i'm using {luckperms_meta_name-colour} and it works fine for me.
