### ISSUE TITLE
1.13.1 Bungeecord/server weird problem

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [lucko/LuckPerms#1237]
Hi, I have a little weird situation with disconecting players from server while joining. It reqires short explanation.

I have 3 servers - Bungeecord (1.13.1), Lobby, Skyblock (1.13.1). Everything has LP 4.3.7.
I have conneted them via bungeecord channel and I have one mysql database for all.

When I'm connecting from Lobby to Skyblock it loggs me to server for a while and dropps out to Lobby again with saing that server I was before shutted down (what didnt happened). When I disable bungeecord in spigot.yml on Skyblock and join directly, without bungeecord it works properly, so its weird. So I thought that was something with my bunge. I tried to disable all permissions on my nick - then I could join server normally via bungee. Next, i changed all permissions from 'global' to 'skyblock', so there is no global and its working now. But sometimes, when i try to join in it dropps me out, and i can join normally on next try. The other thing is, when i try to reload NameTagEdit plugin in game it dropps all players out with 'Unable to pass event $Proxy75 to handler com.nametagedit.plugin.hooks.HookLuckPerms$$Lambda$2191/1875216821', but again - not on every reload, but after 2/3.

Its so strange, so I literally dont know, what can i do in that case. Especially that there were NO errors in logs on any server. I'm so helpless now, so Im writing here - maybe you have any idea what can be problematic.

**Comment by Andre601** [comment]
Only thing I can think of is a not properly setup IP-forwarding for bungeecord.

To my knowledge (so don't count on it) does LP kick a player:
- when the database couldn't be loaded (would give an own kick-reason)
- when his UUID isn't the same as the one saved. (Don't count me on that. I never had that so idk if LP really does that or not)

I recommend you, to check if IP-forwarding is properly setup since this is the only thing I can think of, that would cause such issues.
I *could* also be a 1.13 bug but idk.

**Comment by Kryniowesegryderiusz** [comment]
Thank you. I was wondering, when it kicks player, but i couldnt find it. I think it could be problem with UUIDs, because im using offline online-mode and FastLogin (which is perhaps chanking UUIDs)


I have another bug:
`27.09 12:25:48 [Server] INFO [LP] LOG > (Krynio@skyblock) [G] (zwiedzajacy)
27.09 12:25:48 [Server] INFO [LP] LOG > delete
27.09 12:25:48 [Server] WARN [LuckPerms] Unable to pass event $Proxy75 to handler com.nametagedit.plugin.hooks.HookLuckPerms$$Lambda$2191/1875216821
27.09 12:25:48 [Server] WARN org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
27.09 12:25:48 [Server] WARN at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.validate(CraftScheduler.java:488)
27.09 12:25:48 [Server] WARN at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:150)
27.09 12:25:48 [Server] WARN at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.runTaskLater(CraftScheduler.java:133)
27.09 12:25:48 [Server] WARN at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.runTask(CraftScheduler.java:116)
27.09 12:25:48 [Server] WARN at org.bukkit.scheduler.BukkitRunnable.runTask(BukkitRunnable.java:43)
27.09 12:25:48 [Server] WARN at com.nametagedit.plugin.NametagHandler.applyTagToPlayer(NametagHandler.java:429)
27.09 12:25:48 [Server] WARN at com.nametagedit.plugin.hooks.HookLuckPerms.onUserDataRecalculateEvent(HookLuckPerms.java:28)
27.09 12:25:48 [Server] WARN at me.lucko.luckperms.common.event.LuckPermsEventHandler.invoke(LuckPermsEventHandler.java:108)
27.09 12:25:48 [Server] WARN at me.lucko.luckperms.common.event.LuckPermsEventHandler.invoke(LuckPermsEventHandler.java:45)
27.09 12:25:48 [Server] WARN at me.lucko.luckperms.lib.eventbus.SimpleEventBus.post(SimpleEventBus.java:107)
27.09 12:25:48 [Server] WARN at me.lucko.luckperms.common.event.AbstractEventBus.post(AbstractEventBus.java:84)
27.09 12:25:48 [Server] WARN at me.lucko.luckperms.common.event.EventFactory.lambda$post$0(EventFactory.java:124)
27.09 12:25:48 [Server] WARN at me.lucko.luckperms.common.plugin.scheduler.AbstractJavaScheduler$WrappedRunnable.run(AbstractJavaScheduler.java:79)
27.09 12:25:48 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
27.09 12:25:48 [Server] WARN at java.util.concurrent.FutureTask.run(FutureTask.java:266)
27.09 12:25:48 [Server] WARN at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
27.09 12:25:48 [Server] WARN at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
27.09 12:25:48 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
27.09 12:25:48 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
27.09 12:25:48 [Server] WARN at java.lang.Thread.run(Thread.java:748)
27.09 12:25:48 [Server] WARN [LuckPerms] Unable to pass event $Proxy75 to handler com.nametagedit.plugin.hooks.HookLuckPerms$$Lambda$2189/1878043152
27.09 12:25:48 [Server] WARN org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
27.09 12:25:48 [Server] WARN at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.validate(CraftScheduler.java:488)
27.09 12:25:48 [Server] WARN at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:150)
`

**Comment by lucko** [comment]
I don't think this is a LuckPerms issue - the unable to reload thing is most likely a NTE bug.
