### ISSUE TITLE
put several servers/worlds with a single command

### ISSUE THREAD

**Issue by CryLegende** [lucko/LuckPerms#1238]
Hello, 
Can you add the possibility to put several servers/worlds to a permission with only one command please ?
Like that:
/lp user Luck permission set chatformat.unlucky true faction,skyblock,lobby
(that will set the permission "chatformat.unlucky" on the server faction, skyblock and lobby but not to other servers)
or
/lp group admin permission set chatformat.admin true global world,world_the_end
(that will set the permission "chatformat.unlucky" on the world world and world_the_end but not to other worlds like world_nether...)

**Comment by Andre601** [comment]
See #1124 for an answer
