### ISSUE TITLE
Luckperms MYSQL database error.

### ISSUE THREAD

**Issue by 0xC1A551C** [lucko/LuckPerms#1239]
Running spigot 1.13.1 with the latest version of luckperms off spigot at this date.

Error happens after leaving the server on over night then logging in with no players on.

https://hastebin.com/nizexepeva.shell

**Comment by Andre601** [comment]
Please see this page:
https://github.com/lucko/LuckPerms/wiki/Storage-system-errors#luckperms-cannot-connect-to-my-mysql-server

**Comment by lucko** [comment]
https://github.com/lucko/LuckPerms/wiki/Storage-system-errors#mysql-no-operations-allowed-after-connection-closed-error

^ is the appropriate section for you.
