### ISSUE TITLE
[LP 212] [Sponge] uuid does not have any data loaded

### ISSUE THREAD

**Issue by i9hdkill** [lucko/LuckPerms#124]
Since some builds after ~200 we constantly getting warnings like that:
[pool-2-thread-58/WARN] [luckperms/luckperms]: User _Patii_ - 4b2f4d0c-ce12-4946-9498-f5bb1425add7 does not have any data loaded.

FML latest:
https://pastebin.com/N6EMtjJ7
another fml log:
https://pastebin.com/SKP2LrbF

SF: 2022
LP: 212
Forge 2202
Storage: Yaml

Anything we can do to debug any further?

**Comment by Bubble0seven** [comment]
I am also having the same issue I have 3 servers hooked to a single database with my permissions and only one server is acting up and all members have lost their permissions and ranks etc and I have had to use the file format backup for the time being till this is fixed. I am not sure if i have to increase the pool-size to be more than 10 or not FML LOG below 

[FML-LOG](https://gist.github.com/Bubble0seven/a38431c372a82f6d5bf4020f6f030949)

LuckPerms-Sponge-2.16.83
spongeforge-1.10.2-2202-5.1.0-BETA-2022
