### ISSUE TITLE
Commandblock not working

### ISSUE THREAD

**Issue by walldi222** [lucko/LuckPerms#1240]
Commands didn't work on commandblocks.

Commamdblock is missing anything at the end if you use

![lp_03](https://user-images.githubusercontent.com/37932983/46204158-856fd700-c31c-11e8-99af-fe817bde64b9.PNG)

![lp_4](https://user-images.githubusercontent.com/37932983/46204159-856fd700-c31c-11e8-8112-0df910e03fc4.PNG)

Here is the problem "@p"

![lp_5](https://user-images.githubusercontent.com/37932983/46204160-86086d80-c31c-11e8-8327-5b4c36190319.PNG)

Last thing my Plugin List
![lp_6](https://user-images.githubusercontent.com/37932983/46204161-86086d80-c31c-11e8-960b-95ad737a7b70.PNG)

**Comment by BrainStone** [comment]
That’s a Spigot issue. Spigot doesn’t fully support command blocks in 1.13. Their hacked way used in 1,12 and below broke completely with 1.13.

**Comment by lucko** [comment]
Yeah, I'm fairly sure you can't use the `@p` etc selectors with plugin commands.

**Comment by lucko** [comment]
Not much I can do about that ^^

**Comment by Rouchesta** [comment]
Something to fix this ?
