### ISSUE TITLE
How can I make it so that users only inherit permissions from a certain group?

### ISSUE THREAD

**Issue by Facti0n2** [lucko/LuckPerms#1243]
I want to make it so that only a certain group has access to certain warps. Like red has access to /warp redbase, but it inherits self permissions so it also has access to blue's warp which isn't what I want. This is why I want to make it so that people on red team only inherit permissions from red group and not self permissions so that I can customize the two team's permissions individually. Maybe there is a way to wipe everyone's self permissions so I can start their permissions from scratch?

**Comment by BrainStone** [comment]
Well, the solution is simple:

Don’t give people direct permissions.

And to clear them of existing permissions you use bulkedit. The wiki will explain it in detail.

**Comment by Facti0n2** [comment]
The account I was testing has no permissions. He only inherits three permissions from a group, yet he still has access to more than three commands. https://gyazo.com/e5afda80a8bdec8bfb8154cf456540ef

**Comment by BrainStone** [comment]
He inherits all permissions from that group. Including permissions that group inherits from other groups.
