### ISSUE TITLE
Because i did not an answear on Discord.

### ISSUE THREAD

**Issue by DutchUser** [lucko/LuckPerms#1246]
We have some issue's with LP, as example. LP does not know about a uuid that does exsist. Its not in the users folder. or it does not get the correct one. Because the one that i get from the join section in the console does not work. there is not such uuid.

So basicly, how the hell does LP store it uuid if they are not the same as i see in the console.
Also the uuid from the logs from LP does not match up...

I need this because i need to check what for additional permissions a user have as i can see in the logs he have a permission what he not should have at all. Also his fly was enabled so i want to check if he have the fly permission. 

And i have something else. But i did not yet manage to see if it LP fault. (player is not online, as i need him to be online because offline lookup does not work for some oid reason)

And yes. I know, i can check his also ingame. But it should be in the plugins folders. Not that it only can get checked by doing it when he is online.

**Some more context.**
**Server:** Spigot 1.12.2
**Luckperms version:** LuckPerms v4.3.2
**Storage type:** YAML
**Vault:** Vault v1.5.6-b49

Let me know if i need to show something what is not above here.
**ps:** The topic name... Not mean it in a bad way, but i have it a bit busy and in here it may is more clear.

**Comment by lucko** [comment]
I can't really follow what you're asking.

Can you show some screenshots, or extracts from your log file to illustrate the issue?

**Comment by DutchUser** [comment]
What i am asking is how can i access an user from the *users* folder. Because some users are not in there. 

As example.

02.10 15:46:54 [Server] INFO UUID of player Twan_MC is eaf3de81-e7e9-4395-a0b1-456735b63aa7

This UUID does not exsist in the *users* folder. Because i want to see if he have additional  assigned to only him. 

https://i.postimg.cc/B6Gw0271/image.png
https://pastebin.com/VY3Ap5EU

**Comment by lucko** [comment]
Ah I see what you mean.

A file for each user isn't created in the folder if they don't have any permissions/parent groups/prefixes etc set. If you add a permission to the user in-game, you'll see a file will be created for them.

**Comment by DutchUser** [comment]
Alright. Il test it later today,

But can you add that a user does not need to be online for as example /lp check (user) (permission)? 

Because that make a other issue we have much faster to fix.

**Comment by codingJWilliams** [comment]
Use UUID to check the permission, use it like /lp user <UUID> permission check essentials.fly

**Comment by DutchUser** [comment]
It then set something. Not check.

.10 18:49:50 [Server] INFO [LP] samimiliano01 has permission cmi.placespawner.* set to undefined in context global.

**Comment by PrincessRTFM** [comment]
That means they don't have that permission set to true or false. If you use `checkinherits`, it checks all parent groups, `check` only looks at the user's personal permissions, and the checks will return one of `set to true` (has permission enabled), `set to false` (has permission _explicitly_ disabled), or `set to undefined` (permission is not set on user, so it's _implicitly_ disabled). The check commands do not set permissions, although the phrasing might be a bit confusing.

Luck, might I suggest `does not have permission <node> set` or something similar for this? Just changing the wording a little might make it clearer what the setting is.

**Comment by DutchUser** [comment]
Uhm.

Well... the issue is, 2 players that are in the same group does not have the same permissions for some reason. I hoped that i can see it more clear with an permission check. But so far i see the both do have that permission. What means its not LP that does something wrong so far i can see atm.

**Comment by PrincessRTFM** [comment]
The groups aren't singular - players can inherit from multiple groups, each group can inherit from multiple groups, and players can have individual permissions set directly. `checkinherits` also shows where the permission setting is inherited from _if_ it's set (be it `true` or `false`), IIRC.

**Comment by DutchUser** [comment]
The issue we had seem to be an server related issue, nothing todo with LP, so il close this one. 

Thanks for helping <3
