### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by JuanFerGamerYT** [lucko/LuckPerms#1247]
Hi! I have a idea, and that is to add an option through which I can delete the data of all the bot players, let's say it in another way, the plugin will not create a data of players that have the nickname of a bot.

The nicks of the bots are usually like this: jpahbzojj2ifxw1h

**Comment by BrainStone** [comment]
Or you enable online mode.

In any case if you are using file based storage types the players should not get saved assuming you don’t have default assignments setup.  
And if you have a database, then it’s not even an issues as they can handle millions of entities easily.

**Comment by lucko** [comment]
Functionality to reliably detect & ignore bot users is far out of scope for a permissions plugin like LuckPerms.

I suggest looking for a separate plugin to do this.
