### ISSUE TITLE
Auto-Group

### ISSUE THREAD

**Issue by jagyCZ** [lucko/LuckPerms#1248]
Hello , is there way to auto-set user group after some time ? I mean when player joins server for first time , there will be countdown for example 12h. After 12h he will be automatically moved from group default to another group. Sorry for my bad english.

**Comment by lucko** [comment]
Not possible with LuckPerms only - you need an extra plugin to do this.

As far as I know, this is something that's possible using the https://dev.bukkit.org/projects/ontime plugin.
