### ISSUE TITLE
Libsdiguise permission system

### ISSUE THREAD

**Issue by xion87** [lucko/LuckPerms#1251]
Hi i just want use libdisguise without creating every permission per entity so i used:
libsdisguises.disguise.(JOLLY).(JOLLY)
but since i don't want people use slime option "setsize"
i used libsdisguises.disguise.slime.-setsize
but it seem to don't block the "setsize" option, 
i tried also to set i used libsdisguises.disguise.slime.setsize to false, but it block completly the ability to use slime disguise
this option was working with bungeeperms and other permission, instead is not working with luckperm, 
The wiki https://www.spigotmc.org/wiki/lib-s-disguises-setting-up-permissions/

**Comment by BrainStone** [comment]
You can debug the permissions with verbose. See the wiki for usage and details on the usage.

And denying permissions is only possible by setting them to false.
But anyways it sounds like you are either setting the permission to false incorrectly, you are forgetting to set required permissions or the plugin is doing something weirdly.

Verbose should help you with the first two or and maybe the third option.

**Comment by xion87** [comment]
I already do the debug by suggested by discord, it output this
[14:21:32 INFO]: [LP] VB > huzuno - libsdisguises.seecmd.disguise - true
[14:21:32 INFO]: [LP] VB > huzuno - libsdisguises.disguise.* - undefined

**Comment by smmmadden** [comment]
I think its more on libsdisguises to support singular permission nodes and not expect it to be combined like he has on his page https://www.spigotmc.org/wiki/lib-s-disguises-setting-up-permissions.  If he supports it as a singular permission node, then it should just work.  Then if it is supported and not working in LP, it could be either Luck's to investigate or libraryaddict to investigate.  Turning on debug at that point will help resolve where it is.

**Comment by lucko** [comment]
I can't really follow what the issue is here - LP seems to be behaving correctly?

```
[14:21:32 INFO]: [LP] VB > huzuno - libsdisguises.seecmd.disguise - true
[14:21:32 INFO]: [LP] VB > huzuno - libsdisguises.disguise.* - undefined
```

Those are the results you expected, right? :)

LuckPerms just responds to queries made by plugins, it's then up to the plugin (LibsDisguises in this case) to use that result accordingly, or make the right set of checks in the first instance correctly.

**Comment by smmmadden** [comment]
Hey @lucko - the question was about the use of a negated permission within a permission as shown in the original request.
i used libsdisguises.disguise.slime.**-setsize**
but it seem to don't block the "setsize" option,

I think the developer is trying to do something not supported in LP.  Correct?

**Comment by lucko** [comment]
Yes, and I don't know of any permission plugin where that syntax (using the `-` char in the middle of the node) *is* supported.

You can negate permissions with LP, as I'm sure you know, by setting the node to false.

**Comment by smmmadden** [comment]
exactly my thought as well
