### ISSUE TITLE
People join with non-existing group

### ISSUE THREAD

**Issue by kakd** [lucko/LuckPerms#1252]
I deleted a rank. When a player who used to have that rank rejoined, they still had that rank which no longer existed, and therefore had no permissions until an admin was able to come on and give them the default rank

Can you update LP to make it so that if someone joins with a rank that doesn't exist, it removes that rank from them, and if that's their only rank, it'll give them the default group? Thanks!

**Comment by BrainStone** [comment]
Remove the rank globally from all players with bulkupdate. The wiki page should have an example on exactly that.

And removing nonexisting groups is a terrible idea. There are several use cases where that would completely break everything.
