### ISSUE TITLE
Small issue

### ISSUE THREAD

**Issue by blijgozertje** [lucko/LuckPerms#1253]
Hello,

When my players try to /f show or /f who another faction using the SavageFactions plugin it will put this error in console and the players will only see the owner of the faction instead of all the members https://hastebin.com/zusajopeko.sql

I would like to know what causes this and maybe what could fix it.

**Comment by BrainStone** [comment]
You might want to read the error message. It clearly says everything you need to know.

What you should do is forward this to the plugin author, telling them they should execute the command async.
