### ISSUE TITLE
No permission to use Commands from Mods

### ISSUE THREAD

**Issue by Charismara** [lucko/LuckPerms#1254]
I can not use commands from mods. Is there any solution that makes this possible?

```
Minecraft: 1.12.2
Forge: 14.23.4.2766
Sponge: 7.1.0-BETA-3477
LuckPerms: 4.2.110
```

**Comment by BrainStone** [comment]
Use the plugin ForgedPerms. It’s an adapter so Forge permission checks can be handled by Sponge plugins.

**Comment by lucko** [comment]
This will hopefully end up merged into SpongeForge at some point. :)

https://github.com/SpongePowered/SpongeForge/pull/1660
