### ISSUE TITLE
Can't set WorldEdit permissions to false

### ISSUE THREAD

**Issue by chedadmin** [lucko/LuckPerms#1255]
![luckperms capture](https://user-images.githubusercontent.com/41842655/46574567-3c172b80-c99d-11e8-9535-ed77e11d0307.JPG)

I want my "expert" rank to have access to most WorldEdit commands, but I do not want them to use WorldEdit at all in "world". I tried setting the worldedit.* permission to false for that world, but it doesn't work. It doesn't work if set to global either. Have also tested negating individual worldedit permissions and none of them work.

**Comment by BrainStone** [comment]
That's because longer wildcard permissions are considered first. In other words `xxx.xxx.*` is considered first before `xxx.*`.

So you'll need to set all the permissions you don't want to false for the world:

```
worldedit.analysis.*      true    global
worldedit.analysis.*      false   world
worldedit.biome.*         true    global
worldedit.biome.*         false   world
```

etc.

Details on permission calculation is detailed here: https://github.com/lucko/LuckPerms/wiki/Advanced-Setup#permission-calculation

**Comment by chedadmin** [comment]
Thanks BrainStone but I've just edited to say that I've tried negating individual permissions and that doesn't work either.

**Comment by BrainStone** [comment]
Try negating the exact permissions you set to true.

In any case I'd like a screenshot.  
Also keep in mind that you need to save and run the command that shows in order to be able to apply the changes made in the web editor. The changes are not live.

**Comment by chedadmin** [comment]
Okay so negating permissions does work fine after all. Somehow the WE wand didn't get removed from my inventory when I changed worlds, which obviously has nothing to do with LuckPerms. So problem solved I think, thank you!
