### ISSUE TITLE
Website Editor Via Console

### ISSUE THREAD

**Issue by augesrob** [lucko/LuckPerms#1260]
When I type /lp group default editor in the console it makes a link but the link doesn't work

07.10 22:57:45 [Server] INFO [LP] Preparing a new editor session. Please wait...
07.10 22:57:46 [Server] INFO [LP] Click the link below to open the editor:
07.10 22:57:46 [Server] INFO https://luckperms.github.io/editor/CqB1HV67B

```
404
File not found

The site configured at this address does not contain the requested file.

If this is your site, make sure that the filename case matches the URL.
For root URLs (like http://example.com/) you must provide an index.html file.

Read the full documentation for more information about using GitHub Pages.

GitHub Status — @githubstatus
```

**Comment by BrainStone** [comment]
It’s a know bug of MultiCraft.
MultiCraft messes up the links output to console.  
To get the correct links, use the command ingame or retrieve it from the logs.

**Comment by lucko** [comment]
Yep, unfortunately nothing I can do about it.
