### ISSUE TITLE
Something wrong with tracks and primary groups

### ISSUE THREAD

**Issue by i0xHeX** [lucko/LuckPerms#1261]
I have two "branches" of groups named "donation" and "level", the first one have a role as rank, the other one is for level up plugin. First time player joins he has `default` group and when player has enough exp command executes: `/lp user {user} parent settrack level l_X`. Of course I use that command for `donation` also in order to not reset other parents, like `parent set` does. So, when level track set, user have `default` primary group, `default` and `l_X` parent groups.

The problem occured today, when I restored some donate ranks on people, who had `default` as primary and +some `l_X` as parent. I executed something like that:
`/lp user {user} parent settrack donation premium`

After that player has `l_X` as primary group and `l_X` + `premium` as parents. And from that point I can't even change primary group, switchprimarygroup notify me, that player already has that group as primary, but that's definitely not, and even in H2 database all players have `default` primary group. Command `... parent set` works on primary group, but I can't use it because I will lose `level` track. What can I do now?

![lu](https://user-images.githubusercontent.com/33582973/46663474-d312fc00-cbc6-11e8-9f42-71f87dc86782.png)
![db](https://user-images.githubusercontent.com/33582973/46663646-4fa5da80-cbc7-11e8-95db-49fc0b1d450e.png)

**Comment by i0xHeX** [comment]
I fixed that with setting weight to all `donation` groups to `1`.

**Comment by lucko** [comment]
Sorry I just forgot to reply to this - as you've worked out, primary groups in this case are being determined by weight. :)

https://github.com/lucko/LuckPerms/wiki/Configuration#primary-group-calculation

**Comment by CycTaker** [comment]
> I fixed that with setting weight to all `donation` groups to `1`.

how did you fix the problem. plz help me.
