### ISSUE TITLE
Ezprestige.

### ISSUE THREAD

**Issue by CozyLeprechaun94** [lucko/LuckPerms#1267]
Dear Lucko,

I used your amazing featured plugin luckperms.
I have a prison server, that I'm working on.

But when I do the prestige command and I already set my last rank it tells me that I need to be that rank.

I have 3 tracks.
ranks ( for donators)
rankup (for the upgrading system)
staff ( for the staff-team)

hope to hear from you soon.

kind regards,
CozyLeprechaun94

**Comment by Andre601** [comment]
This isn't really LP related, since it has more to do with EZPrestige.

I recommend to go to the [Help Chat-discord](https://discord.gg/FtArYRQ) and ask for support there.
Also please close #1266

**Comment by CozyLeprechaun94** [comment]
Thanks for replying I'm already in that discord, but I was not sure if it was for all the plugins.

**Comment by Andre601** [comment]
#1266 needs to be closed too please.
