### ISSUE TITLE
HOCON configuration support

### ISSUE THREAD

**Issue by Bammerbom** [lucko/LuckPerms#127]
I would love to see support for hocon support for permission storage.

**Comment by lucko** [comment]
Is there really a benefit of it over JSON?

**Comment by Bammerbom** [comment]
It think it is easier to edit because the syntax is less strict

**Comment by lucko** [comment]
I don't think the benefits of implementing HOCON support would outweigh the time taken to add & maintain it, especially when it's so similar to JSON.

I'll happily accept a PR for it, but currently it's not a priority for me. :)
