### ISSUE TITLE
Undesirable command ambiguity for 'parent set' vs 'set parent'

### ISSUE THREAD

**Issue by Bobcat00** [lucko/LuckPerms#1271]
LuckPerms 4.3.2, CraftBukkit 1.8.8

When attempting to issue a user **parent set** command, LuckPerms may incorrectly assume that the intent is to set a permission.  This occurs because LuckPerms assumes the command:
**/lp user \<user\> set...**
is equivalent to:
**/lp user \<user\> permission set...**

Note that **/lp user \<user\> set...** is not shown as a valid command in the documentation.

Example - User attempts to set Bobcat00's parent group to default:
**/lp user Bobcat00 set parent default**
[LP] Set parent to true for bobcat00 in context server=default.

Correct usage:
**/lp user Bobcat00 parent set default**
[LP] bobcat00 had their existing parent groups cleared, and now only inherits default in context global.

LuckPerms should not assume that the permission argument is missing, due to the resulting ambiguity.

**Comment by lucko** [comment]
I'll keep this in mind for the future, but at the moment I think the aliases probably have to stay.

**Comment by BrainStone** [comment]
LP 5 would be the right time to drop these aliases.
