### ISSUE TITLE
Ability to export permissions of certain servers

### ISSUE THREAD

**Issue by DarkFort** [lucko/LuckPerms#1273]
It would be very convenient to export the permissions of certain servers or groups. For example:
/lp export <file>
/lp export <file> server:survival - export survival server permissions
/lp export <file> groups - export groups, prefixes, suffixes and weight

This is very convenient if you want to separate some permissions from the entire list, since often this list is very huge and it is very difficult to edit it manually.

**Comment by MrMIStakee** [comment]
I agree, it will be useful!

**Comment by BrainStone** [comment]
What exactly is your end goal where you would need to only export the permissions applying to a server?

Also does this include global permissions or just permissions with that specific context?

**Comment by DarkFort** [comment]
Oops. I want to be able to export permissions to a specific context, I think you can specify a few. For example / lp export <file> server:survival, global

**Comment by BrainStone** [comment]
But why. I think you might be trying to do something that can be solved easier in a different way.

**Comment by DarkFort** [comment]
I do not know of another solution. Maybe you offer your solution?

**Comment by BrainStone** [comment]
**Why** do you want to export permissions for a specific context?

**What** do you **want to achieve** with it?

What is your **goal**?

**Comment by DarkFort** [comment]
This is useful for migrating the permissions of a specific server. For example, I want to transfer bed wars permissions and global prefixes, suffixes and weight to another server.

**Comment by BrainStone** [comment]
Why not use a shared database?
Without one server contexts are pretty useless anyways.

**Comment by DarkFort** [comment]
I don't know what you're talking about, but I share a database. But you can only export everything together, nothing else. That's the problem.

**Comment by MrMIStakee** [comment]
Yes, I support @DarkFort. I've had quite a few issues with transferring certain permissions to another server.

**Comment by BrainStone** [comment]
Why do you need to transfer permissions to another server when they are using a shared/common database? Just let the server use the same database.

**Comment by BrainStone** [comment]
Then give them different names. I’m not aware of any setup where using a common database for all servers wouldn’t make any sense.

And I mean you can group servers together and assign certain permissions per server group instead of per server. Then you can still have server specific overrides.

What you’re trying to do sounds like a very round about way of doing things and like a very whacky setup.

**Comment by lucko** [comment]
Your suggestion for `/lp export groups` can already be achieved using `/lp export --without-users`.

I don't see a need for the server specific flag.
