### ISSUE TITLE
Missing meta in verbose output

### ISSUE THREAD

**Issue by LemADEC** [lucko/LuckPerms#1277]
As of LuckPerms-Sponge-4.3.12build790 + spongeforge-1.12.2-2768-7.1.3-RC3498, the verbose command doesn't capture meta checks.
Please extend verbose output or add something so we can check meta/options.

**Comment by LemADEC** [comment]
For the record, SkyClaims is using default values instead of the ones provided through meta. Logging meta would help understand what's wrong between LP and SC on this.

**Comment by lucko** [comment]
5e0b8ebdf66bda62205450fa4236a282c6254600
