### ISSUE TITLE
A temporary privilege

### ISSUE THREAD

**Issue by MrOneLA** [lucko/LuckPerms#1278]
Hi
I gave the user the VIP privilege for 30 days
I immediately wanted to give more for 30 days, so that he was 60 days, but I wrote already temporarily inherits

What am I to do?

**Comment by BrainStone** [comment]
Check out the https://github.com/lucko/LuckPerms/wiki/Command-Usage:-Parent#lp-usergroup-usergroup-parent-addtemp
The temporary modifier is what you are looking for.
