### ISSUE TITLE
Server filtering incompatible with meta values

### ISSUE THREAD

**Issue by LemADEC** [lucko/LuckPerms#1279]
As of LuckPerms-Sponge-4.3.17 build 795, meta assigned to current server aren't recognized.
Only meta assigned globally appears to be working.

Server is set to skyadventures:
```
/lp info
[LP] Running LuckPerms v4.3.17 by Luck.
[LP] -  Platform: Sponge
[LP] -  Server Brand: SpongeForge
[LP] -  Server Version:
[LP] -  SpongeAPI: 7.1.0-70763aa8 - SpongeForge: 1.12.2-2768-7.1.3-RC3498
[LP] -  Storage:
[LP] -     Type: MySQL
[LP] -     Ping: 1ms
[LP] -     Connected: true
[LP] -  Messaging: Sql
[LP] -  Instance:
[LP] -     Static contexts: skyadventures
[LP] -     Online Players: 2 (2 unique)
[LP] -     Uptime: 29m 1s
[LP] -     Local Data: 5 users, 19 groups, 2 tracks
```

In that same server context (skyadventures), a `skyclaims.default-schematic` meta is defined for SkyClaims:
```
/lp group member meta info
[LP] member's Prefixes
[LP] -> 2 - 'Member ' (inherited from self)
[LP] member has no suffixes.
[LP] member's Meta
[LP] -> skyclaims.default-schematic = 'skyadventures' (inherited from self) (server=skyadventures)
[LP] -> skyclaims.min-size = '16' (inherited from self) (server=skyadventures)
[LP] -> rank-ladder = 'staff' (inherited from self)
[LP] -> rank = '1000' (inherited from self)
[LP] -> weight = '99999' (inherited from self)
```

However, LP returns null for this meta according to verbose output:

Target | Request | Result
-- | -- | --
lemadec | skyclaims.command.reset | true
lemadec | meta: skyclaims.default-schematic | null
defaults/user | meta: skyclaims.default-schematic | null
defaults/default | meta: skyclaims.default-schematic | null

Now, if I add a global value for same meta with
 `/lp group member meta set skyclaims.default-schematic test`
Then the meta returned is test:

Target | Request | Result
-- | -- | --
lemadec | skyclaims.command.reset | true
lemadec | meta: skyclaims.default-schematic | test

**Comment by BrainStone** [comment]
Did you set the server name in the LP config or in the static contexts?

**Comment by LemADEC** [comment]
It sets in the config and `/lp info` reports it properly.
Not sure what you mean by static contexts here.

**Comment by lucko** [comment]
Can you send me the actual verbose report please.

**Comment by LemADEC** [comment]
https://luckperms.github.io/verbose/#AalBUBCMT1
Looks like you are right on SkyClaims using the global context

**Comment by lucko** [comment]
Nope, this is indeed a LuckPerms bug. Woops

**Comment by lucko** [comment]
No clue how that one went unnoticed for so long. I guess because permission checks through Sponge bypass that method via `getPermissionValue`...

Thanks for finding it :)
