### ISSUE TITLE
How can I instal it on bungeecord

### ISSUE THREAD

**Issue by BluetoDark** [lucko/LuckPerms#128]
I have a a bungeecord server Network its made a bungeecord with a local host it are all apart server conected but its not working I have tried many things but it don`t works please help. the plugin it self works  
but its not connected to the other servers on the bungeecord console it works but if I /bperms do I only get the version of the plugin.

**Comment by lucko** [comment]
Please see here: https://github.com/lucko/LuckPerms/wiki/Setup
