### ISSUE TITLE
Suggestion: Add a Web UI system that can be configured to a custom link such as staff.server.com

### ISSUE THREAD

**Issue by TechieBlort** [lucko/LuckPerms#1280]
The way the current Web UI is it's set up on a system where you need to type in a command then paste another command when done and go to a github.io link. I propose a more advanced UI that you run one command and it adds perms and also set on your server's website or something. It would be cool to see this. In more details: I am trying to make a Web UI for our staff team so they can see stuff such as luck perms web system which always them to go to a set link and type in a code set for their player and using this gives them access if they have permissions such as "luck.ui" to the server permissions instead of generating a random code and stuff that they need to use. This may seem a little confusing so if needed I can provide more info. Thanks for looking at this.

**Comment by Andre601** [comment]
I personally can't see a way to achieve this with how the system works right now.
At the moment does LP send different kind of data (permissions, online user, groups, etc.) to a sit from luck (bytepin iirc) where the editor gets the data from. (And it works the same the other way around.)

**Comment by lucko** [comment]
If you want to use a custom version of the editor, you can simply host your own copy and then add the following to your LP configuration file.

```yaml
web-editor-url: https://luckperms.github.io/editor/
```

except obviously pointing to your own site.

The files you need to host for the editor are located here.
https://github.com/lucko/LuckPermsWeb/tree/master/editor

Hopefully that helps. :)

**Comment by BrainStone** [comment]
Also they you’d like to have it, which is the website/webeditor creating the session would require direct communication with the server. Or in other words the Minecraft server would need to run its own Webserver so it can respond to requests. 
I think I’m not alone in the assessment that that would be way out of scope.
However it’s certainly possible to have someone create an addon that creates such a dedicated editor that would work in the “opposite” direction as the current webeditor.

**Comment by TechieBlort** [comment]
Isn't there a plugin that does allow Minecraft to chat with a Web server? If not how do forums work the big servers like Hive, Hypixel, or Mineplex? How does it allow players to sync their ranks?

**Comment by codingJWilliams** [comment]
Also, those big networks have lots of paid developers and all their plugins are completely custom - it's not fair to compare LuckPerms to this.

**Comment by lucko** [comment]
Once again:

> I don't see how this is relevant?

The current web UI is entirely functional and designed in a way that *everyone* can use it. That was the aim of the system. 

I know you *could* develop a system that interacted directly with the database, but it would:

* be harder to setup
* require a web server & probably some other app to run
* require a direct connection to the database, and if you wanted instant changes, to the messaging service too

I don't see how such a design is desirable? It has no upsides compared to the current system.
