### ISSUE TITLE
[Suggestion] 'Self' permission

### ISSUE THREAD

**Issue by Gaderr** [lucko/LuckPerms#1281]
Some people in my server wanted to have their own suffix, but I haven't found a permission to allow a user the ability to attribute himself a suffix without being able to modify thoses of other users.

So I though about it and a argument `self` like, for the request I got, `/lp self meta addprefix <priority> <suffix> [context]` with the perm `luckperm.self.__` could be great! 😄 

What do you think?

**Comment by BrainStone** [comment]
You can already let players modify their own prefixes. You need to enable `argument-based-permissions` in the config. Then the permission checks of LP will be a lot more detailed.

Then with verbose you can figure out the permissions you need so players can only modify their own prefixes.

Though the command will stay like `/lp user <player> ...`

**Comment by Gaderr** [comment]
Damn I haven't read that part of the wiki! Thanks for your reply, that's exactly what I was looking for.
