### ISSUE TITLE
Stack trace thrown to console on erroneous filter usage

### ISSUE THREAD

**Issue by AACJ** [lucko/LuckPerms#1283]
Instead of printing a stack trace, only send the user friendly error message detailing the problem with the syntax.

https://github.com/lucko/LuckPerms/blob/42c8cb1354917b55d9fa00725279cc38c61b1285/common/src/main/java/me/lucko/luckperms/common/commands/misc/VerboseCommand.java#L82

**Comment by lucko** [comment]
Could you make a PR for this? ;)
