### ISSUE TITLE
Add track context

### ISSUE THREAD

**Issue by DreamplaySE** [lucko/LuckPerms#1286]
Add track context so you can clear a players track progression.

**Comment by BrainStone** [comment]
You can set them to the first rank of the track. And contexts are considered when using commands to modify a players track position (`demote`, `promote` and [`parent settrack`](https://github.com/lucko/LuckPerms/wiki/Command-Usage:-Parent#lp-usergroup-usergroup-parent-settrack))

**Comment by lucko** [comment]
You can clear track progression using https://github.com/lucko/LuckPerms/wiki/Command-Usage:-Parent#lp-usergroup-usergroup-parent-cleartrack, or the settrack command to reset to the first position as Brainstone said.
