### ISSUE TITLE
"sql" messaging service is not working on Bungee

### ISSUE THREAD

**Issue by Turbotailz** [lucko/LuckPerms#1287]
4.3.18 is showing `Messaging service "sql" not recognised` on start up and `Messaging: None` in `/lpb info`.

Downgrading to 4.3.11 fixed this issue.

**Comment by Turbotailz** [comment]
Note: the messaging service was working for the user's spigot servers. Just Bungee was affected.

**Comment by lucko** [comment]
Working for me

**Comment by Turbotailz** [comment]
I'm just going to close this then, maybe it was another issue they were having but they went silent on Discord so /shrug
