### ISSUE TITLE
Query a Groups prefix and color

### ISSUE THREAD

**Issue by Mikeoso** [lucko/LuckPerms#1288]
Hey there,
currently im creating a LuckPermsInterface for my Plugin API but i have some problems getting the groups prefix and color, any ideas? I have my meta keys set like "meta.color.x" "meta.gender.x" the x values are those im trying to get.

I use the version 3.3.13
Sorry if i reported the issue on the wrong way.

Greetingz Mike0so

**Comment by BrainStone** [comment]
That is beyond outdated. Please use a recent version.

**Comment by Andre601** [comment]
The newest official/stable release can be found on the [Spigot-page](https://www.spigotmc.org/resources/28140/) and the newest dev-releases on the [github.io-page](https://luckperms.github.io/)

**Comment by Mikeoso** [comment]
Thanks for the advise, is there any special to me mentioned for this "big" update? Critical Database Migrations or anything?

**Comment by Mikeoso** [comment]
be*

**Comment by Andre601** [comment]
To my knowledge aren't there any major breaking changes.
If so, then they would be mentioned in the updates on the Spigot-page.

**Comment by BrainStone** [comment]
Though you should rename your config so that a new default config can be generated. And the manually migrate over. There have been quite a lot of changes regarding the config.

But the data will migrate automatically.

**Comment by Mikeoso** [comment]
Alright, thanks also found a way to query the wanted results. Thanks for the awesome help, can be closed
