### ISSUE TITLE
Using UTF-8 characters inside Prefix/Suffix instead gives ?.

### ISSUE THREAD

**Issue by Seeroh** [lucko/LuckPerms#129]
If I try and set a prefix/suffix for a group/player, via command that uses an odd UTF-8 character, it appears fine in the chat, but is saved to the storage as a ?. This is for YAML storage, I haven't tested this with H2 or MySQL at all.

Example:

1) I set the group prefix via command /lp group default meta addprefix 200 "&f【&8Prefix&f】"
(the odd brackets are the symbols that are not being set correctly)
2) Chat gives confirmation. [LP] default had prefix "【Prefix】" set at a priority of 200.
3) Typing in chat with chat settings enabled to display prefix/suffix show up as ?Prefix? NAME
4) Looking at the storage for the group to see the permission node for the prefix shows 
prefix.200.&f?&8Prefix&f?: true

I could likely fix this issue through editing the files, but that's not a plausible solution.

**Comment by lucko** [comment]
Thanks for reporting 👍

**Comment by lucko** [comment]
Looks like this still doesn't work quite right, reopening.
