### ISSUE TITLE
Error in Console Bukkit - No visible issues other then console showing this...

### ISSUE THREAD

**Issue by Questercraft** [lucko/LuckPerms#1290]
11:13:21 AM CONSOLE: reflective access by me.lucko.luckperms.common.dependencies.classloader.ReflectionClassLoader (file:/home/shady/McMyAdmin/Minecraft/plugins/LuckPerms-Bukkit-4.3.25.jar) to method java.net.URLClassLoader.addURL(java.net.URL)
11:13:21 AM CONSOLE: consider reporting this to the maintainers of me.lucko.luckperms.common.dependencies.classloader.ReflectionClassLoader
11:13:21 AM CONSOLE: --illegal-access=warn to enable warnings of further illegal reflective access operations
11:13:21 AM CONSOLE: illegal access operations will be denied in a future release

**Comment by BrainStone** [comment]
Use Java 8. In Java 9 and above they decided to throw in this warning when some people are adding libraries at runtime, which is stupid to say the least.

**Comment by lucko** [comment]
Please see the response linked in the issue above.
