### ISSUE TITLE
About converting storage databases.

### ISSUE THREAD

**Issue by ProblemsSender** [lucko/LuckPerms#1291]
Let make an example
For now I used yaml for my storage method, then after few days I finish my permissions.yml(just an example), but now I want to change it to MySQL(storage method)... What happens next?
1/ I have to configure it again...
2/ It would automatically convert to MySQL
3/ I don't need to configure it again, but I must convert it by hands
If you choose 1 or 3, then how could I configure that, or how to convert it?

**Comment by Turbotailz** [comment]
There is a wiki page that explains how to do this

https://github.com/lucko/LuckPerms/wiki/Switching-storage-types

**Comment by Andre601** [comment]
Also just in case you actually edit perms manually, we don't recommend to do that and instead use the web editor, which can use with `/lp editor`
