### ISSUE TITLE
Permissions aren't being checked 1.13.2 Spigot due to me rushing through the config and messing it up

### ISSUE THREAD

**Issue by aWitch-Doctor** [lucko/LuckPerms#1292]
I have created a fresh install of spigot 1.13.2, I have several servers on a waterfall (bungeecord) network and had no issues with luckperms before. Unless i am op'ed I cant use any command. I have verified that the server name in LP config and server name used for commands are the same. I have included all the info I can think to add about the server. All the screenshots are just as a proof thing showing that I didn't screw that part up.

Here is some verbose. I had the player de-op'ed and try to run gm commands. He had 3 perms for the "aquatic" server where this is happening. luckperms.\* minecraft.\* and \*. He should have everything now but still can't run /gm 0. Here is the verbose during that. 
https://luckperms.github.io/verbose/#yEkj52YcD0
I then gave him essentials.* and tried again. Verbose for that 
https://luckperms.github.io/verbose/#wang0P177K
I verified that I'm not removing essentials.* anywhere 
https://drive.google.com/file/d/1Sbly_FMIsWuNBpVMXJoUu2QjK6g488Xf/view

Screenshots showing the results of /lpb user username info and /lp user username info
/lpb https://drive.google.com/file/d/1PnmsLWZbRS-KbVxdguCG2yxKsoTl3-3I/view
/lp https://drive.google.com/file/d/1mUxii9ZHYSUCU_OfA3wTxJXVzIcinLX8/view
The uuid's are good, I set up that part right.

It doesn't matter what the perm is or what groups/users I give them to, LP just won't say the user can run the commands.

My current plugin list:
spigot-1.13.2
worldguard-legacy-7.0.0-beta01.jar
worldedit-bukkit-7.0.0-beta-01.jar
Vault.jar
UltimateChat-JDA.jar
UltimateChat-1.8.8-b200-Universal.jar
Ridables.jar
mcMMO.jar
LuckPerms-Bukkit-4.3.25.jar
GriefPrevention.jar
EssentialsXSpawn-2.15.0.55.jar
EssentialsX-2.15.0.55.jar
CoreProtect-2.15.1.jar
BungeeTabListPlus_BukkitBridge-2.8.9.jar

Current LP config, in case I screwed something up in there.
https://hastebin.com/anuseroven.shell

**Comment by Andre601** [comment]
You should set a messaging service (since you're using MySQL you can use `sql`) to make changes apply on all servers.

**Comment by aWitch-Doctor** [comment]
Is that not default when using MySQL? 
`# - Possible options:
#   => sql       Uses the SQL database to form a queue system for communication. Will only work when
#                'storage-method' is set to MySQL or MariaDB. This is chosen by default if the
#                option is set to 'none' and SQL storage is in use. Set to 'notsql' to disable this.`
This is the only server that has a version of LP with a sql option for messaging service. Once I get this set up im going to move them all to redis. It looks like redis is the only option between all versions of LP that I'm running.

**Comment by Turbotailz** [comment]
You have set `include-global` and `include-global-world` to false in your config, that's your problem.

**Comment by Turbotailz** [comment]
As for messaging service, you really don't need to use Redis unless you have multiple Bungeecord instances. `sql` is the best option there and you're right in that it does default to that if it's set to `none`, though I'd set it to `sql` just in case. If your config files don't mention it then they are probably outdated.

**Comment by aWitch-Doctor** [comment]
... You have any idea how annoying it is that one little config setting that i over looked is the reason that 3 different people couldn't fix this. One of them being an Unlucky (MOD) from discord. Thank you, include-global-world should have been set to true. Include-global should be set to false for my use. The version of LP that I have loaded on all the other servers are old. They were established a while back and haven't had a need to update yet. That's why there is no sql config option for messaging service. 

Thank you for figuring it out.
