### ISSUE TITLE
[NEED HELP] Bungeecord - Spigot sync

### ISSUE THREAD

**Issue by DeinPlay** [lucko/LuckPerms#1297]
Is it possible to add permissions from the bungeecord server via the minecraft chat on a bungee cord network? (sync between bungeecord and spigot) That I can add permissions like bungeecord.command.server on the spigot server without restarting the bungeecord server.

And if it's possible how to do  #it?

Thanks

**Comment by Andre601** [comment]
You can use the BungeeCord-version of LuckPerms, which you can find on the [github.io](https://luckperms.github.io/) page of LuckPerms.

**Comment by Turbotailz** [comment]
You need to point all your servers (including Bungee) to a single database, follow the guide here:
https://github.com/lucko/LuckPerms/wiki/Network-Installation

Once your servers are all connected, it doesn't matter where you add permissions.

If, for some reason, you aren't going to connect the servers to the same database, you will have to use `/lpb` to control the Bungeecord version of LuckPerms.
