### ISSUE TITLE
Adding permission to all players having another permission

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [lucko/LuckPerms#1298]
Is ot possible to add (ex. via bulk) permission to all players that have another permission?

**Comment by Andre601** [comment]
Bulk edit only allows the edit or deletion of a permission.
There isn't a way, to mass-add a permission to users.

Also depending on what you want to achieve, can you simply give a role, that has the permission, to a user.

**Comment by Kryniowesegryderiusz** [comment]
I want to add all users who has permission shop.access.witch.nether_star new permission shop.access.witch_vip.nether_star. Is it possible somehow?

**Comment by Turbotailz** [comment]
This is what groups are for. You will not be able to bulk add a permission like that, you can _edit_ the permission, however.

If you have a MySQL database then it should be possible with a query.

**Comment by Kryniowesegryderiusz** [comment]
Okay, so if i have a group, can i add it to players that have certain permission?

**Comment by Kryniowesegryderiusz** [comment]
Oh. I know, what you mean. Updating a permission with group and add two permissions to group. Thanks guys.

**Comment by Turbotailz** [comment]
What you could do is create a group, add the permissions to the group, then bulk edit that original permission updating it to `group.<groupname>`.
