### ISSUE TITLE
lp editor links from console

### ISSUE THREAD

**Issue by perpterds** [lucko/LuckPerms#1299]
I'm unsure if this belongs to LuckPerms or LuckPermsWeb, as I've no idea where the error actually is coming from. As such, I'm posting to the exact same message to both. By all means remove or notify me to remove as necessary :)

Running the command "lp editor" (or any alternate version, e.g. for group or user, et cetera) via console does generate a link as expected, but when copied and pasted to a web browser it's a 404 error.  I've already noticed that the link doesn't have the normal "?" after "editor/",  so I tried adding that, at which point it then gives the "incorrectly copied or session expired, please try again" page.

I've tried with a few different browsers, no change, and it's happened on two different servers, both running 4.3.8.  The command, and the link, work fine from in-game, on both servers.  Screenshots to follow.

https://snag.gy/qHgyQI.jpg
https://snag.gy/UubWck.jpg

**Comment by perpterds** [comment]
issue answered over on luckpermsweb.

**Comment by lucko** [comment]
https://github.com/lucko/LuckPermsWeb/issues/70
