### ISSUE TITLE
[QUESTION] - How to Install LuckPerms on BungeeCord Server?

### ISSUE THREAD

**Issue by Ar1sC** [lucko/LuckPerms#13]
How can I install LuckPerms on BungeeCord Server? (Should I Use Mysql? I have VPS so its not that hard)

**Comment by lucko** [comment]
Grab the jar from the CI server and place it in your plugins folder.

If you only want to use LuckPerms on your proxy, there's no need to configure MySQL, but if you plan to use it on other platforms/servers in the future, it's best to start using MySQL or MongoDB from the beginning.

Just setup a MySQL server; MariaDB is a popular choice. You can find loads of how-to guides on the internet if you're not sure how. Then put the same credentials in to each LuckPerms config file, and swap the storage option setting to "mysql".

**Comment by SirFaizdat** [comment]
If LuckPerms is installed on the proxy, should it be installed on the other servers too?

**Comment by lucko** [comment]
LuckPerms should be installed on all platforms you want to use it on. If you want it to manage permissions on your Spigot server, install it there. If you want it to manage permissions on your proxy, install it there too.

**Comment by Ar1sC** [comment]
Thank's.
