### ISSUE TITLE
MySQL string to long error

### ISSUE THREAD

**Issue by arkobat** [lucko/LuckPerms#1305]
When trying to create a long permission list
https://hastebin.com/ibukixazey.sql

I'm not using the latest version of LuckPerms, as the one I'm using have worked perfctly until now.
But will updating fix this error?

**Comment by Andre601** [comment]
The provided perm is too long to be saved in the table.

**Comment by arkobat** [comment]
> The provided perm is too long to be saved in the table.

Yeah, but can that be changed?
I don't have much knowledge of how databases work.

**Comment by Andre601** [comment]
Just add the perms seperately instead of just one huge perm...
The regex and wildcard system was meant to be used, to combine multiple perms, but not like 200 in one.

In your case could you simply give a perm like `particlehats.particle.*` and then allow/deny those you (don't) want to give.

**Comment by lucko** [comment]
You can also increase the field size in MySQL if you really wanted to, but yeah, Andre's suggestion is better. :)
