### ISSUE TITLE
Player Permissions Not Set to default upon Joining. 

### ISSUE THREAD

**Issue by Inysal** [lucko/LuckPerms#1307]
Players not getting auto assigned to default class upon joining the first time. In fact nothing is getting assigned to new players.

I have updated to the latest build #807 (to see if that is fixed)
I am running BungeeCord - IP Forwarding is set to True 
I do not have an SQL Database Setup, using .yaml on main server only.

I am running Spigot 1.13.2
Default Config set to defaults.

I was wondering if there were any ideas out there to assist, or if I just fail at life.

**Comment by Andre601** [comment]
Both LuckPerms and LuckPermsBungee have a group called, which as the name implies, act as the default group for every player.
You can check the [default groups](https://github.com/lucko/LuckPerms/wiki/Default-Groups) page for information about how to use (and change) the default group.

Also a little note about BungeeCord and Spigot:
Both LPs (for bungee and spigot) **won't** interact with each other. Especially in the case of file-based storage-methods.

**Comment by Inysal** [comment]
@Andre601 

I fail at life. I verified this was true. My biggest issue was (which I didn't clarify) that their default permission file wasn't created when they joined. However, once I promoted them from a default class, it created it's self. I remember back in 1.11 they use to auto create themselves when players under default. I do believe so. I am going to leave it at that, thank you.

**Comment by Andre601** [comment]
LP won't create any files for users, as long as they not meet at least one of those requirements:
- The player has own permissions applied.
- The player has another group applied than default.

That is to prevent an unneeded increase of storage-space.

**Comment by thada2607** [comment]
@Inysal Hello, have you found a fix? I'm having the same problem.

**Comment by BrainStone** [comment]
No need for necromancing.
