### ISSUE TITLE
When setting a group for a certain server it bugs out.

### ISSUE THREAD

**Issue by TechieBlort** [lucko/LuckPerms#1309]
When setting up my Test server I noticed a tweak I made on the settings to make the user only have a certain group on that one server it bugs out and don't show the player's prefix if they have said role unless it's global and not for X server. Provided is screenshot proof of the permission the player has. and the prefix they should have.
![2018-11-19_10 27 51](https://user-images.githubusercontent.com/29681046/48716735-f5486280-ebe5-11e8-8832-c3f1ec06b776.png) Shown in that screenshot the player inherits from VIP however, not the prefix like it should be.
![image](https://user-images.githubusercontent.com/29681046/48716801-22951080-ebe6-11e8-8cc7-533a82ff2d30.png) Also, as shown in that screenshot they have a group prefix but it's showing as the Default one.

**Comment by BrainStone** [comment]
Can we see the output of `/lp info` and `/lp user <you> info`?

**Comment by TechieBlort** [comment]
![image](https://user-images.githubusercontent.com/29681046/48718977-6ab63200-ebea-11e8-89e3-2a4c322d9bb1.png)
^ /lp info
\/ /lp user Desert_rat_03 info
![image](https://user-images.githubusercontent.com/29681046/48719075-9e915780-ebea-11e8-9c09-1b92cd6438b0.png)

**Comment by BrainStone** [comment]
Can we also get `/lp user <you> meta info`?

**Comment by TechieBlort** [comment]
`/lp user Desert_rat_03 meta info`
19.11 11:06:45 [Server] INFO [LP] desert_rat_03's Prefixes
19.11 11:06:45 [Server] INFO [LP] -> 100 - '[U] ' (inherited from default)
19.11 11:06:45 [Server] INFO [LP] -> 100 - '[VIP] ' (inherited from vip)
19.11 11:06:45 [Server] INFO [LP] desert_rat_03 has no suffixes.
19.11 11:06:45 [Server] INFO [LP] desert_rat_03 has no meta.
(sorry had to send this one from console since I am not on the server atm)

**Comment by BrainStone** [comment]
Console is preferred anyways. Especially when putting it in code blocks. 

Anyways both prefixes have the same priority. Therefore they conflict. Lower the priority of the the default one.

**Comment by TechieBlort** [comment]
Will do thanks!

**Comment by lucko** [comment]
Assuming fixed? ;)
