### ISSUE TITLE
UUID Error

### ISSUE THREAD

**Issue by Auntex** [lucko/LuckPerms#1314]
Well, I was using an Login Authenthicator, so when you are premium, your UUIDS changes to the premium UUID. Then I wanted to use only Offline UUIDs even if you are premium, is there a way to fix now my account? 
That happens only to my account, error logs: https://pastebin.com/z1nrqwkf

**Comment by BrainStone** [comment]
Just as a side note, doing that will make name changes of premium players no longer work.

**Comment by Auntex** [comment]
So, Using Offline UUIDS on a Premium player will produce that error?

**Comment by BrainStone** [comment]
That too.

**Comment by Auntex** [comment]
Oh, there isn't a way to prevent that? Or I need to use Online UUID to premium users?

**Comment by BrainStone** [comment]
If you want to allow name changes, the yes, absolutely.

**Comment by Auntex** [comment]
Done, no problems right now. Thanks :P
