### ISSUE TITLE
SSL spam

### ISSUE THREAD

**Issue by ludvdber** [lucko/LuckPerms#1317]
I use LuckPerms 4.3.17 and this message spam my console : 

>  [22:00:21] [luckperms-hikari connection adder/WARN]: Sun Dec 02 22:00:21 CET 2018 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.

What can I do to stop or hide that?

**Comment by Imortalshard** [comment]
Hi,

Check out those link to fix those errors.

https://github.com/lucko/LuckPerms/wiki/Storage-system-errors#mysql-ssl-errors

**Comment by ludvdber** [comment]
Thank you :)
