### ISSUE TITLE
Config option to change verbose levels of track [pro/de]motion

### ISSUE THREAD

**Issue by Seeroh** [lucko/LuckPerms#132]
As title says. If you have tracks that are populated with 20+ ranks, server logs will quickly become bloated from just a stream of Rank1 ---> Rank2 ---> Rank3 ---> Rank4 ---> Rank5 etc etc.

Perhaps an option to turn off, or limit verbose levels logged to console. The "Promoting user along track {TRACK} from {rank} to {rank}" should suffice in nearly all cases.

**Comment by lucko** [comment]
I guess it could be useful, but are there any other use cases for something like this?

I'd rather add them all in one go, than create a config option specifically for this.

**Comment by Seeroh** [comment]
Ah, I didn't proofread my text before I sent it. Adding all the tracks isn't too big of a deal, but it's when you have many users progressing along those 20+ tracks that it begins to become an issue.

**Comment by lucko** [comment]
Yes, I understand the issue. My question was, what other chat messages should be limited. 

I would rather not create a config option specifically to disable this one message, and would prefer to disable a group of messages in one go.

It seems a bit wasteful to add just one option, and I don't want to bloat the config with 100 different settings for small insignificant options. (It deters admins from actually reading the whole thing :P)

**Comment by Seeroh** [comment]
Ah, most other commands aren't really "spammy" enough to warrant it, I'd thing. From my testing, it appears only commands pertaining to tracks will show enough information to really make a difference in the logs. 

The [LP] (User data was saved to storage) message might fall under being redundant though, but there could be a use for that I haven't considered.

**Comment by lucko** [comment]
This was added a while ago, but I forgot to close the ticket. 

Just add "-s" to to the end of the command.

**Comment by Seeroh** [comment]
adding -s to the end of the command results in
`[LP] USERNAME isn't in any groups on this track, so they were added to the first group, GROUP in context world=-s.`
