### ISSUE TITLE
Is Luck Perms got Timed prefixes? (Question or Suggestion)

### ISSUE THREAD

**Issue by ProblemsSender** [lucko/LuckPerms#1324]
It seems buggy to patch other rank's prefix into default or other prefixes as I haven't used to use LuckPerms, I asked Google for help, he said I could used "weight" or "rank" to determine what should use first. But I don't get it at part "what should use first". For JUST an example I use rank Member with:
rank: 10
default: true
Prefix: &0Member
Note that its suffix is blank. Second rank Donor with:
Rank: 9
Suffix: &0Donor
And I apply both ranks to the member, I will get:
Rank: 9
Prefix: &0Member
Suffix: &0Donor
Above just an example for you to follow, and now for real question
There's additional prefix I want the player to have when they're "online to get rewards" to placed with is "&4RewardHunter"
The player will still have ordinary perms they should have of both the donator and member, but must change the prefix or suffix that we want to make them separate, ordinary member just enjoy the server will have ordinary "&0Member" prefix, Player Killer or "online to get rewards" will have "&4RewardHunter" prefix
Because I still not used to use LuckPerms, if there is already have this function to timed prefix, or timed group, timed permission, or some function that I could use it for force changing prefix for only a period time. Please guide me! Or this would be the Suggestion for LuckPerms, this function is needed great!

**Comment by Imortalshard** [comment]
Adding a prefix for a certain amount of time:
https://github.com/lucko/LuckPerms/wiki/Command-Usage:-Meta#lp-usergroup-usergroup-meta-addtempprefix

Adding a group for a certain amount of time:
https://github.com/lucko/LuckPerms/wiki/Command-Usage:-Parent#lp-usergroup-usergroup-parent-addtemp

**Comment by ProblemsSender** [comment]
It helps me a lot! Thank you Mr. Imortal :+1:

**Comment by Andre601** [comment]
Is your question answered/the issue resolved?
Then please close that issue :)
