### ISSUE TITLE
How to override inherited luckperms.modify.group.XXX 'false'

### ISSUE THREAD

**Issue by Aberdeener** [lucko/LuckPerms#1326]
When my Mod group has luckperms.modify.group.mod set to false, my admin group (inherits all of mods permissions) cannot promote (or do anything) to the Mod group because they inherited the false luckperms.modify.group.mod.
How do I let the admin group override this?
Thanks, let me know if you need clairity

**Comment by BrainStone** [comment]
Set it to true for admin

**Comment by Aberdeener** [comment]
> 
> 
> Set it to true for admin

Nope, doesnt seem to work. would my group yml files be helpful?

**Comment by BrainStone** [comment]
Set the exact permission to true. Not a wildcard.

The wiki page “Advanced Setup” contains info on which permissions take precedence over others.
