### ISSUE TITLE
Editor cannot connect

### ISSUE THREAD

**Issue by KittyNyu** [lucko/LuckPerms#1327]
When opening the editor it gets stuck on Please wait, giving this error

https://pastebin.ubuntu.com/p/Jfhm5V3b6n/

**Comment by BrainStone** [comment]
There have been some issues with the domain. They have been resolved now but some DNS servers might still have the wrong ones.

It should be working fine within the next 24h. If you can’t wait that long use for example Google’s DNS. There should be guides available

**Comment by lucko** [comment]
Should be fixed now.
