### ISSUE TITLE
Bad Gradle include snippet

### ISSUE THREAD

**Issue by CommanderTvis** [lucko/LuckPerms#1332]
I suggest to replace this

```gradle
repositories {
    mavenCentral()
}

dependencies {
    compile ("me.lucko.luckperms:luckperms-api:4.3")
}
```

with this

```gradle
repositories {
    mavenCentral()
}

dependencies {
    implementation 'me.lucko.luckperms:luckperms-api:4.3'
}
```

* `implementation` configuration is faster than deprecated `compile`. 
* There's no reasons to use GStrings when you don't need ${...} pattern syntax. 
* Braces are not necessary.

**Comment by Imortalshard** [comment]
You could always make a pull request, to make the changes then Luck can decide if the changes are good or not. Would be quicker than using an issue.

**Comment by CommanderTvis** [comment]
It's for wiki. Can I PR it?

**Comment by Imortalshard** [comment]
Yeah you can, i've done it before.

**Comment by Andre601** [comment]
There's a repository containing all wiki pages.
You can contribute to that, to suggest changes. I sadly don't have a link, but it's either one of Luck's repos or one of the LuckPerms organisation.

**Comment by CommanderTvis** [comment]
ok, i'll try to find

**Comment by lucko** [comment]
It's here: https://github.com/LuckPerms/wiki

I'm fine with the changes, but don't really know enough about the `implementation` configuration to say if it's valid or not.

@kashike almighty gradle master, any opinion?

**Comment by CommanderTvis** [comment]
@lucko 
https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_separation

![image](https://user-images.githubusercontent.com/38042667/49934964-5839ca80-ff02-11e8-8bc2-450ac5cdafa8.png)

**Comment by kashike** [comment]
@lucko Yes, `api` and `implementation` should be used instead of `compile` now.

**Comment by lucko** [comment]
I've updated the wiki page, thanks for the suggestion. :)
