### ISSUE TITLE
[Suggestion] FastLogin support

### ISSUE THREAD

**Issue by Lmmb74** [lucko/LuckPerms#1333]
Hello. I was setting up a new Survival server and I wanted to add FastLogin. But when I set a permission for a player, it is stored according to its UUID. So when the player changes from cracked to premium and you have set the permission while still cracked, the permission check returns undefined for the same player due to having its UUID changed. I thought it would be useful if LuckPerms actually changed the stored UUID whenever FastLogin is activated/deactivated. Or should I ask this to the developer of FastLogin?
And thanks for taking your time to read this in advance :D

**Comment by lucko** [comment]
I mean, you're going to have issues with more than just LuckPerms - if a players UUID is different, as far as the server/plugins are concerned, they are a completely different entity, with a different inventory, location, balance (e.g. Essentials), level (e.g. McMMO) etc etc etc.

I don't really think it's for LuckPerms to work around this sort of thing. It's really just something you have to deal with if you want to use plugins like FastLogin.
