### ISSUE TITLE
"allow-invalid-usernames" does not work when using API

### ISSUE THREAD

**Issue by jiongjionger** [lucko/LuckPerms#1336]
https://github.com/lucko/LuckPerms/blob/master/common/src/main/java/me/lucko/luckperms/common/api/ApiUtils.java#L39-L42

forgot "if (!plugin.getConfiguration().get(ConfigKeys.ALLOW_INVALID_USERNAMES))"

**Comment by lucko** [comment]
879a88a39824f92215743326574e9ff95e9b6184
