### ISSUE TITLE
Error in the console when you install meta

### ISSUE THREAD

**Issue by ZConnorZ** [lucko/LuckPerms#1337]
When you install meta suffix or prefix in Russian or Unicode characters, you receive an error in the console.
Error: https://pastebin.com/j3jqRACN

Mysql: Ver 14.14 Distrib 5.5.62
Server: Paper 1.12.2
Luck: v4.3.52

**Comment by lucko** [comment]
The above commit fixes this issues for all new database creations, but as your database already exists, this patch won't apply and you'll need to manually adjust the charset using this SQL command.

```mysql
ALTER TABLE luckperms_user_permissions CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE luckperms_group_permissions CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
```
