### ISSUE TITLE
Luckperms won't sync to the database 

### ISSUE THREAD

**Issue by 123hotdog1100** [lucko/LuckPerms#1339]
when ever i try and use a command to give someone perms i get this error in the console [16:32:47 WARN]: 367096 [luckperms-3] WARN me.lucko.luckperms.lib.hikari.pool.PoolBase - luckperms-hikari - Failed to validate connection me.lucko.luckperms.lib.mysql.jdbc.JDBC4Connection@3f1ce9ca (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value. and this in game 
![image](https://user-images.githubusercontent.com/14129417/50233732-f539af00-03ab-11e9-8ea1-d4e8c99ff863.png)

**Comment by Andre601** [comment]
https://github.com/lucko/LuckPerms/wiki/Storage-system-errors#mysql-no-operations-allowed-after-connection-closed-error

**Comment by 123hotdog1100** [comment]
I've tried that and still the same problem

**Comment by lucko** [comment]
Please also read the content at the top of this page.
https://github.com/lucko/LuckPerms/wiki/Storage-system-errors

The error you're getting is not being caused by LuckPerms, it is almost definitely an issue with your database or the networking connecting your MC server to the database.
