### ISSUE TITLE
LuckPerms does not work with any plugin.

### ISSUE THREAD

**Issue by DanHCraft** [lucko/LuckPerms#1341]
I have a big problem with LuckPerms. The permissions I set in the groups does not apply to the player.
The group have the permission nodes, the players are asigned to the groups with "/lp user USER parent add GROUP", but every command shows "You are not allowed to use this command!". The only thing there the plugin works fine is:
* ChatEx (1.4) -> Prefix, etc
* EssentialsXAntiBuild (2.15.0.57) -> Building Permissions
* Vault (?) -> Prefix, etc

Plugins where it isn't working:

* EditableSign (?)
* EssentialsX (2.15.0.57)
* LWC (1.7.6)
* WorldEdit (6.1.8-cd4729f)
* WorldGuard (6.2.1-84bc322)
* Multiverse (2.6.0)

Spigot 1.12.2 (Build git-Spigot-e8ded36-acbc348)
mit LuckPerms (4.3.17)

I hope you can help me with this issue.

**Comment by smmmadden** [comment]
In other words, if you haven't OP'd yourself or added all the admin commands to your permission group, you will not have access to add other permissions when you are in-game.  You have to grant yourself the 100+ permissions first, that's what the error is telling you.

Adding the permission nodes from the server console initially (IMO) is much easier than trying to do it in-game when you're first setting up your server.

**Comment by DanHCraft** [comment]
@Andre601
Here is the gist for the groups.yml:
https://gist.github.com/DanHCraft/99ba32b4769e430aaf4559b7c6b21a1f

If you need more information, then tell me waht do you need. ^^

@smmmadden
I wrote that the groups HAVE the permission, but LuckPerms does not aply them to the user, even though the user has set the group as parent. And I have assigned all permission through the console.

Thanks for answering so fast. ^-^

**Comment by smmmadden** [comment]
groups.yml ?  I don't see any file with that name so not sure where it is coming from.  From the console, issue this command to see what luckperms has in the database.
lp export AllPermissions.txt
The file will get written to the plugins/luckperms folder and you can use NotePad++ or other text editor to see what's in it.

This will list out everything that is configured and show which users have what for groups.  Nothing that you have provided shows what the users have access to.  Getting the export (dump) will show what you may be missing.  You can turn on verbose debugging too, but you should first understand what you think you have setup is actually correct.

**Comment by lucko** [comment]
As mentioned above, try debugging with the verbose command.

https://github.com/lucko/LuckPerms/wiki/Verbose
