### ISSUE TITLE
Bungee's new tab complete aka inject_commands

### ISSUE THREAD

**Issue by x1p** [lucko/LuckPerms#1343]
BungeeCord has a new feature which they call `inject_commands`. This basically implements tab complete like we know from spigot. If enabled, it reveils every possible command of luckperms to players. Players normally have no permission to use these commands, but still can see them. This should not be possible if it laks the correct permission. Normally players have no permissions at all. Better yet: a player should not be aware that a server runs luckperms or not.

Could this be prevented?

Luckperms 4.3.38 for BungeeCord

**Comment by lucko** [comment]
The LuckPerms tab complete handler already checks for the corresponding commands permissions before providing completions to players.

https://github.com/lucko/LuckPerms/blob/fc69002c86941981d54a59386d611fda29e639ed/common/src/main/java/me/lucko/luckperms/common/command/CommandManager.java#L242

> Better yet: a player should not be aware that a server runs luckperms or not.

They will always see at the very least the tab completion for `/lpb` and equivalent, as players are able to use the base LuckPerms command with no arguments given without being given any specific permission.

**Comment by x1p** [comment]
Ah I see. No sub commands are coming through.
Imho even the base command is not necessary but maybe I'm a bit to strict on these things
Thanks for letting me know.
