### ISSUE TITLE
Per servers

### ISSUE THREAD

**Issue by VortexCraft1** [lucko/LuckPerms#1345]
I have tried a number of methods on the per server settings, however, I have been unable to get it set up. Currently they are set up to a database, whenever I do /lp networksync it comes up with https://i.imgur.com/uOyvB2Q.png

There are settings come up, I have tried changing it. They are set up on MySQL at the moment with luckperms installed on all servers. What am I missing?

**Comment by lucko** [comment]
If you're using the latest version of LP and using `MySQL` for storage, then the plugin should automatically enable an SQL messaging service.

Could you send over the logging output you get when LP enables on that server?
