### ISSUE TITLE
Crash server random

### ISSUE THREAD

**Issue by alexhackers** [lucko/LuckPerms#1346]
my server is crashing out of nowhere, randomly, I am seeing mysql and it is sending many queries, it sends 1,000 requests and crashes my server

![image](https://user-images.githubusercontent.com/23200468/50379624-bae34280-0635-11e9-9223-5cda81ad5b3f.png)

https://pastebin.com/cPTLQY2u

**Comment by lucko** [comment]
That's not the full crash log, so I can't really comment on what the cause is.

Nothing there to suggest it's an LP problem though.
