### ISSUE TITLE
Context question

### ISSUE THREAD

**Issue by BowMcGee** [lucko/LuckPerms#1347]
Basically I want to give players the abillity to change their own suffix, and only their own suffix. 
So I'm thinking I can do that via contexts, or can that not be done?
Does that context exist already, do I need to create it, or is there a better way to do this?

Thanks

**Comment by lucko** [comment]
You can do this with LuckPerms, just not using "contexts" - they're something different. :)

You're looking for "Argument based command permissions" - https://github.com/lucko/LuckPerms/wiki/Argument-based-command-permissions
