### ISSUE TITLE
Adding not equal operator to context

### ISSUE THREAD

**Issue by Poggicek** [lucko/LuckPerms#1349]
I could not find something like requests on GitHub so I marked it as an issue, sorry.
It would be nice to have more comparison operators for contexts, for example having group/permission in every world except for "spawn". /lp user NoSuchFieldError permission set * world!=spawn
Or having multiple contexts. like /lp user NoSuchFieldError permission set * world=spawn && world=test

**Comment by Andre601** [comment]
[context]: https://github.com/lucko/LuckPerms/wiki/Context#defining-your-own-contexts
I mean the first one can be easily achieved like this:
```
/lp user Andre_601 permission set * true
/lp user Andre_601 permission set * false world=spawn
```
That would allow * on a global/server-wide scale, while it is denied in the world spawn (per world perms override global ones.)

And you can define your own kind of context, to then use it in a permission.
More info can be found [here][context]

**Comment by Poggicek** [comment]
Oh, you are right. I think this is great solution, because now he doesnt have to update whole editor just for that stupid think
