### ISSUE TITLE
world context not set on login

### ISSUE THREAD

**Issue by SavageCore** [lucko/LuckPerms#135]
Given a server with 2 worlds 'world' (default) and 'redstone' if you join the server in redstone then `lp user SavageCore info` it returns `world=world`

After `mv tp world` and `mv tp redstone`, context is correct `world=redstone` and permissions work.

Is this a configuration issue or bug?

Multiverse-Core-2.5.0 ([#725](https://ci.onarandombox.com/job/Multiverse-Core/725/))
LuckPerms-Bukkit-2.17.0
Vault 1.5.6
spigot-1.11

**Comment by lucko** [comment]
I'm not having this issue at all. It's reporting the correct world on login. (my spawn world is called "mainworld")

I'll do some testing, there's a few flaws in what I'm doing for this feature - hopefully changing some of the handling of this will fix the issue.
