### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by muddup** [lucko/LuckPerms#1355]
Latest Spigot version 1.13.2
Problem plugin is SimplePortals.
Issue: Add simpleportals.* perm, and all users can use all portals.
          Use just the simpleportals.portal.jungle perm and user can't use that portal.
Any help much appreciated.

Muddup

**Comment by Andre601** [comment]
Use the verbose command from LP, to find out what permissions are required.
Also please don't use issues here to ask for support with plugins other than LP.
