### ISSUE TITLE
Error while enabling LuckPerms (runs OKAY if no other plugins installed

### ISSUE THREAD

**Issue by call911nowplz** [lucko/LuckPerms#1356]
I get this error if i restart the server and join https://pastebin.com/5D213nEu
And i get this error when i disable luckperms and re-enable it via plugman https://pastebin.com/DcVw1cTu
If i delete all the other plugins, LP works fine and connects to the database.

**Comment by lucko** [comment]
Hmm ok seems to be a logging error.

What server version are you using?

**Comment by call911nowplz** [comment]
1.8.8
When i disable few plugins ( i can give the list of the plugins ) LP works fine again.

**Comment by call911nowplz** [comment]
https://imgur.com/uAhYMtB 
this is my plugins list. The plugins that are disabled (I disabled them manually) Are the ones that are causing LP not to connect to the database.

**Comment by call911nowplz** [comment]
I give up. I am switching back to PEX, No way for me to fix this and my network is big, I can't delay it any longer

**Comment by lucko** [comment]
> I can't delay it any longer
Apologies, but we don't have the resources to provide live, 24/7 support. This is a free project!

If you're able to, could you provide me with a zip file of your plugins directory. I'll try to reproduce the error myself. As you've worked out, it seems to be some sort of incompatibility with another plugin you're using.

**Comment by call911nowplz** [comment]
Sorry if i sounded like i'm complainig but i wasn't! The support is amazing i simply assumed i won't go through any problems so i shut down my network thinking i can finish the whole setup in few hours.
And, Because i don't want to post the server files here, I will send you a message on discord and give you everything you need.
call911/HowAreU#0021 is my discord, I will message you rn

**Comment by call911nowplz** [comment]
the problem is probably this:
the class org.apache.logging.log4j.spi.LoggerContext has a method getLogger that luckperms uses
that class isnt included in spigot, so luckperms needs to include it in its own jar

another plugin also uses a different version of th same class, without the getLogger method, that version gets loaded, and luckperms cant find the correct version of the class

the solution would be to rename the class to ANYTHINGHERE.org.apache.logging.log4j.spi.LoggerContext and then both plugins will be able to access their own version of it (this is part of shading when building)

**Comment by call911nowplz** [comment]
update:
Our dev tried that, But didn't solve my issue.

**Comment by lucko** [comment]
Resolved now afaik.

> call911/HowAreU - 30/12/2018
@Luck we've solved the logging issue. Mind contacting me so i can explain?
We've edited the  hikari.jar file thanks to our dev

> Luck - 30/12/2018
Okay awesome
You can explain here
Was it just a case of removing the slf4j shading orrr?

> call911/HowAreU - 30/12/2018
i modified one class from the library (HikariConfig.class)
it has now changed the error to say 
at me.lucko.luckperms.lib.hikari.HikariDataSource.<clinit>(HikariDataSource.java:42) ~[?:?]
which means, this workaround works
so i ended up downloading the original source for the library, spent some time editing it, and got this
if you look at the stack trace https://pastebin.com/DcVw1cTu 
(random letters and shit after the error), its actually describing the path java took to get from working code to the broken code.
lines 3 to 8 begin with at org.apache.logging they are a part of the logging stuff
line 9 begins with at me.lucko.luckperms.lib.hikari.HikariConfig which is the name of one of the classes from the database library
line 10 onwards is unrelated to the error


> Luck - 30/12/2018
Tbh I don't really follow
But if it's all sorted for you now that's good :smiley:
