### ISSUE TITLE
CustomNPC mod - Npc cannot deal damage on Npc, animals and player.

### ISSUE THREAD

**Issue by wa66rpg** [lucko/LuckPerms#1358]
Hi,there.
I just met a problem while using CustomNPC mod and LuckPerms.
the CustomNpc cannot deal damage on Npc, animals and player,which means they can not hurt others except monsters.
They will attack target but could not deal any damage.
I tried to unload Luckperms and this problem was fixed, but I need Luckperms......
What should I do?

[Edited]------------------------------------------------------------------------------------------------------
I have used /verbose to check the issue and I found there is some permissions about Griefprevention which stop CustomNPC to deal damages on animals and other Npc.
But there is still some problem that the Npc would not fight back when you are attacking him which they should like any other monsters.

**Comment by BrainStone** [comment]
If it’s really a mod and not a plugin add ForgedPerms to your server (the 1.12.x version can be found in the discussion of the Ore-Resource page).

Then you can use verbose to debug what permissions are being denied. See LP wiki for details on that.

**Comment by wa66rpg** [comment]
> If it’s really a mod and not a plugin add ForgedPerms to your server (the 1.12.x version can be found in the discussion of the Ore-Resource page).
> 
> Then you can use verbose to debug what permissions are being denied. See LP wiki for details on that.

That is what I thought, but I do not really understand how to give a CustomNPC permissions, they are not players. It looks like some global setting problem on Luckperms maybe ?
For me, it looks like there is some game rules stopping CustomNPC to deal damages on any friendly creatures.

**Comment by BrainStone** [comment]
You can assign them permissions via their UUIDs. And verbose should tell you if it’s a permissions issue.

Lastly I think there’s ways to target all of them on Sponge iirc. @lucko would know more about that.

**Comment by lucko** [comment]
This should be something you can control through GriefPrevention.
