### ISSUE TITLE
Web editor resets rank weight

### ISSUE THREAD

**Issue by Chappy202** [lucko/LuckPerms#1360]
Hi,

When I make changes to my permissions using the web editor, and re-add them using the command that the web editor generates when I save, it resets the weight of the rank that I edited using the web editor.

So for example: My default group is set at weight 20, and I would change a permission of the default group to only apply on my "skyblock" server and not "global" and when I paste the generated command the weight resets back to 0.

**Comment by Andre601** [comment]
Did you made sure, that there's actually a `weight.20` permission for the group?

**Comment by Chappy202** [comment]
![capture](https://user-images.githubusercontent.com/45310480/50551070-4dae5d80-0c84-11e9-827b-ea77d181093b.PNG)

Yes I did, but it seems to ignore that permission...
![capture](https://user-images.githubusercontent.com/45310480/50551075-70407680-0c84-11e9-894a-113ba54b1d4d.PNG)

**Comment by Andre601** [comment]
You set the weight for only skyblock.... So it won't be set for all other servers.
Also make sure, that you actually set a server name in the config of LP
