### ISSUE TITLE
Blank lines in console (Bungee)

### ISSUE THREAD

**Issue by Chappy202** [lucko/LuckPerms#1362]
Hi,

I am currently having an issue where my luckperms installation on our Bungeecord server only prints out blank lines when executing commands.

I am currently running bungeecord: **git:BungeeCord-Bootstrap:1.13-SNAPSHOT:7dd0928:1386**

Things that I have tried:
- Clean bungeecord install with the default settings
- Only luckperms loaded on bungeecord
- Restart bungeecord
- Use waterfall
- Use different hosting platforms

The /lpb command works in-game
![capture](https://user-images.githubusercontent.com/45310480/50552177-34aea800-0c96-11e9-90ad-d7d83d59a3f5.PNG)
![capture1](https://user-images.githubusercontent.com/45310480/50552194-75a6bc80-0c96-11e9-84a9-847dc52ce41b.PNG)
![capture3](https://user-images.githubusercontent.com/45310480/50552206-b7cffe00-0c96-11e9-8b6a-c82f1f15eded.PNG)

**Comment by Chappy202** [comment]
I have fixed this issue by downgrading to luckperms bungee version 4.3.60, any version above this causes the issue as well as some permission issues (4.3.61/4.3.62)

Build #837 and below works fine, so something with #838 and #839 is broken.

**Comment by md678685** [comment]
4.3.61 ([build 838](https://ci.lucko.me/view/LuckPerms/job/LuckPerms/838/changes)) appears to be commit 8eed3131f29672aa249e41b3e3dde642b9a0b572.

**Comment by lucko** [comment]
Seems to be resolved by ^
