### ISSUE TITLE
Permission nodes are case-sensitive

### ISSUE THREAD

**Issue by DrPanic** [lucko/LuckPerms#1366]
Hey,

working with version 4.3.63 and got a litte thing:
When unset permissions the nodes are case sensitive, can this be case-insensitive?
![Sample](https://user-images.githubusercontent.com/5235435/50575029-96852400-0df4-11e9-9ba7-9fe7ab4af9d3.png)

**Comment by lucko** [comment]
I'm kinda reluctant to change this. The commands to manipulate permissions are intentionally case sensitive, because things like prefixes, suffixes and meta values are stored in them, and need to retain their case.

However, the permission checks themselves are case insensitive.

**Comment by lucko** [comment]
Going to close for these reasons ^.

Thanks for the suggestion though. :)
