### ISSUE TITLE
players can't see each other

### ISSUE THREAD

**Issue by fanjinhui** [lucko/LuckPerms#1369]
Thanks for this plugin,But I find a error,when I add the plugin,players can't see others.My game is 1.12.2 spongeforge,Wish you updata the plugin and solve the problem

**Comment by fanjinhui** [comment]
oh! this plugin is no problem if add it only,but I add the Nucleus,It's going to happen as before I said.

**Comment by BrainStone** [comment]
Don’t give the permission `*`, `nucleus` or `nucleus.*`. Because that’ll include a permission that will make you join vanished.
