### ISSUE TITLE
Question: /lp user <user> info - permission?

### ISSUE THREAD

**Issue by andrewkm** [lucko/LuckPerms#1371]
I can't seem to figure out what the permission for allowing someone to use **/lp user <username> info** would be.

I gave the permission luckperms.info however it doesn't seem to work.
It just shows:
https://i.imgur.com/B1jU9Cj.png

Running on LP 4.3.64

**Comment by HugoMauricio72** [comment]
You can see the permission for it on:

https://github.com/lucko/LuckPerms/wiki/Command-Usage:-Permission#lp-usergroup-usergroup-permission-info

**Comment by BrainStone** [comment]
Additionally there’s the `verbose` command which you can use for debugging permissions.  
Details can be found on its wiki page.
