### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by DarkFort** [lucko/LuckPerms#1374]
Connection error. What is the reason? IPtables clean.
https://pastebin.com/J3Jz9pA3

**Comment by DarkFort** [comment]
Ping does not go to the site, then the hoster has blocked it?
https://imgur.com/a/AxeSBBM

**Comment by DarkFort** [comment]
I checked another IP CloudFlare and ping is coming. So only IP is blocked where the site bytebin.lucko.me is located
https://imgur.com/a/Wr5N9gs

**Comment by DarkFort** [comment]
How to solve this problem? What should I do?

**Comment by lucko** [comment]
Speak to your hosting provider.

**Comment by DarkFort** [comment]
Hello.
 
Unfortunately, the IP address (104.27.150.106) is unavailable due to the inclusion in the Unified Register of domain names, website page indexes on the Internet and network addresses that identify websites on the Internet that contain information whose distribution in the Russian prohibited by the Federal Service for Supervision of Communications, Information Technology and Mass Communications (https://blocklist.rkn.gov.ru/).
 
We hope for understanding and further cooperation.

**Comment by BrainStone** [comment]
You can’t just change the IP address. If it was possible blocking IP addresses would be pointless.

**Comment by lucko** [comment]
Seems like the Russian government is censoring content served by CloudFlare - not really much I can do about that haha.

You or your hosting provider might be able to configure some sort of proxy to bypass that restriction, but that's well beyond the scope of what I'd be able to help you with.

This isn't a problem with LuckPerms.
