### ISSUE TITLE
give players a permission based on whether they have a certain permission or not

### ISSUE THREAD

**Issue by runescapejon** [lucko/LuckPerms#1375]
Like the title mention give players a permission based on whether they have a certain permission or not possible using bulk command ?

**Comment by BrainStone** [comment]
Use groups for that purpose.

**Comment by runescapejon** [comment]
I want to do in users not groups

**Comment by BrainStone** [comment]
I mean create a group just for these permissions you are talking about. And then give the users this group (users can have multiple groups)

**Comment by runescapejon** [comment]
I understand but i prefer doing it in users because sometimes i give permission directly by users. Also when i setup new server with the same group but different permissions with different servers then users who has the group in one server but not in the new server. Having this feature give me the ability to correct this issue. This is one of many reasons on why i am making this suggestion.

**Comment by BrainStone** [comment]
You can assign permissions per server and assign groups per server too.

This suggestion has been shut down numerous times because there’s hardly any upside to doing it like that.

Because if permissions go together in a set, a group is what you want.

**Comment by runescapejon** [comment]
Yes i know you can assign permissions per server and assign groups also
I am talking about if the user that has the group in server1 which will not be applied onto server2 i would have to manually assign it to them

**Comment by BrainStone** [comment]
Then assign them globally?

**Comment by runescapejon** [comment]
What do you mean?

**Comment by BrainStone** [comment]
If you don’t specify a server a group assignment is global. It applies on all servers. Only exception is if you defined a default context. But then you can still set it to global.

**Comment by runescapejon** [comment]
Ohhh oh no i can't because i need the permission separate per server

**Comment by BrainStone** [comment]
I wasn’t talking about the permissions. But the groups.

You can assign a group globally and have it have per server permissions. No issue whatsoever.

**Comment by runescapejon** [comment]
o.0 you can set the group globally  and still have it set per server? i never heard of this and i read the wiki how? if so this suggestion is useless

**Comment by BrainStone** [comment]
Well, assign the group globally, and have the group's permissions per server.
