### ISSUE TITLE
Vault Chat Priority

### ISSUE THREAD

**Issue by AlbertoCoder97** [lucko/LuckPerms#1379]
Hello,
why luckperms gets priority over essentialsXchat in vault? Would be possible to add a config option for that? It is impossible right now (unless you use an external plugin -> memory waste) to format chat text (messages, not prefixes & suffixes).

**Comment by AlbertoCoder97** [comment]
[https://imgur.com/a/IjZF882](url)
As you can see, when vault checks for chat plugin, it sets it to LuckPerms. Since EssentialsXChat allows you to format also chat messages and not only prefix & suffixes, would be possible to add a config option to give priority to EssentialsXChat instead of LuckPerms?

**Comment by Andre601** [comment]
You most likely doesn't use EssentialsXChat.
Make sure to have EssentialsX and EssentialsXChat installed, since it's proven, that EssentialsX and LuckPerms work together without any issues.

**Comment by AlbertoCoder97** [comment]
@Andre601
I have EssentialsX and EssentialsXChat installed :D I'm not that stupid xD I've sent some messages also in the public discord in #general showing the problem :)

**Comment by lucko** [comment]
If you uninstall LuckPerms, EssentialsX still won't show in that Vault log output.

That's because it's listing Vault "providers". EssentialsXChat does not provide data to Vault, it just reads from it.

That output is totally normal and as expected.
