### ISSUE TITLE
Shorthand Permissions not registering correctly?

### ISSUE THREAD

**Issue by freak-dk** [lucko/LuckPerms#1380]
Hey,

I am running Luckperms 4.3.73.
I am trying to utilize the shorthand permission system, like "lp user freakdk perm set test.(1-2)"
but instead of adding both "test.1" and "test.2" to my list of permissions, "test.(1-2)" is added, same thing applies when I try to unset permissions. 

I have the, **apply-shorthand: true** set in the config. 

Anything else I could be doing wrong or is this infact a bug?

**Comment by BrainStone** [comment]
That is infact expected behavior. The permissions get applied, but the shorthand itself is saved.

Try it. You'll see you'll have both/all permissions.

**Comment by freak-dk** [comment]
Ah, alright @BrainStone 
But this doesn't solve my issue when trying to unset the permissions.

Throught time a player may have "test.1" and then some time after "test.2" added - Though in my setup more than this will be added.
Then eventually I want to utilize the shorthand system to unset a rather large range "test.1-10" etc. But I guess this just isn't possible then?

**Comment by BrainStone** [comment]
That's correct. That's not possible like that.

What I would recommend is using a track with groups that inherit from eachother.
