### ISSUE TITLE
how to stop this spam in my console

### ISSUE THREAD

**Issue by TheCompieter** [lucko/LuckPerms#1382]
17:12:13 [INFO] 17:12:13.281 [luckperms-hikari housekeeper] DEBUG me.lucko.luckperms.lib.hikari.pool.HikariPool - luckperms-hikari - Pool stats (total=10, active=0, idle=10, waiting=0)

17:12:43 [INFO] 17:12:43.282 [luckperms-hikari housekeeper] DEBUG me.lucko.luckperms.lib.hikari.pool.HikariPool - luckperms-hikari - Pool stats (total=10, active=0, idle=10, waiting=0)

17:13:13 [INFO] 17:13:13.282 [luckperms-hikari housekeeper] DEBUG me.lucko.luckperms.lib.hikari.pool.HikariPool - luckperms-hikari - Pool stats (total=10, active=0, idle=10, waiting=0)

17:13:43 [INFO] 17:13:43.282 [luckperms-hikari housekeeper] DEBUG me.lucko.luckperms.lib.hikari.pool.HikariPool - luckperms-hikari - Pool stats (total=10, active=0, idle=10, waiting=0)

17:14:13 [INFO] 17:14:13.283 [luckperms-hikari housekeeper] DEBUG me.lucko.luckperms.lib.hikari.pool.HikariPool - luckperms-hikari - Pool stats (total=10, active=0, idle=10, waiting=0)

17:14:43 [INFO] 17:14:43.283 [luckperms-hikari housekeeper] DEBUG me.lucko.luckperms.lib.hikari.pool.HikariPool - luckperms-hikari - Pool stats (total=10, active=0, idle=10, waiting=0)

17:15:13 [INFO] 17:15:13.284 [luckperms-hikari housekeeper] DEBUG me.lucko.luckperms.lib.hikari.pool.HikariPool - luckperms-hikari - Pool stats (total=10, active=0, idle=10, waiting=0)

**Comment by lucko** [comment]
They're coming from Hikari, a library used by LuckPerms - there's not anything I can do within the plugin to prevent them.

However, you might find the information here useful.

https://github.com/lucko/LuckPerms/issues/119

**Comment by iSilviu-student** [comment]
these logs appeared mainly when the AEGIS platform was entered;
