### ISSUE TITLE
Server freezes while syncing with BungeeCord

### ISSUE THREAD

**Issue by BestMark** [lucko/LuckPerms#1383]
Hello,
Sometimes my server hangs when I remove permission for some group on the other server in my BungeeCord network. Ping between BungeeCord and Bukkit servers (they are on remote dedicated server) is more than 80 mg (also I have enabled messaging-service: pluginmsg). I think, it's may be reason of freeze.
In that time I saw a lot of Paper thread dumps in console, such as: https://pastebin.com/vETSQuDj
Before this crash I entered the command /lp group default permission unset essentials.tpaccept skyblock (skyblock is the other server): https://pastebin.com/3Mpd4Ush.
Also I did JFR record when my server hung in that moment. If you need it, I can send you. Thread dump of the server thread: https://pastebin.com/Cn5Mt1CN

P.S. Sorry for my bad English, I'm from Russia.

**Comment by BestMark** [comment]
Does your plugin have some kind of caching system? If so, how can I turn it on?

**Comment by BrainStone** [comment]
Everything is cached. That can't even be turned off.  
Though the cache gets emptied when a network sync occurs.

**Comment by lucko** [comment]
Make sure this option is set to false in the `config.yml` file, and that you're using the latest version of the plugin.

https://github.com/lucko/LuckPerms/blob/3c0d1ba7a1c19f3231b0227b7e68c6823d01b947/bukkit/src/main/resources/config.yml#L493-L502

**Comment by BestMark** [comment]
Thank you very much.
Also I have a question about synchronisation. Should I disable the pluginmsg service if I have Bukkit remote server on the other dedicated server? Is it worth to use only on localhost servers?

**Comment by BrainStone** [comment]
The messaging service informs the other linked servers that there’s been an update and that they should reload their data.

So you want to have it. I’d recommend using `sql`. But whichever you chose, it needs to be the same on all of them.

**Comment by BestMark** [comment]
But if I use `sync-minutes` instead of `messaging-service`, will the plugin synchronize on other servers every "sync-minute"?

**Comment by lucko** [comment]
Correct
