### ISSUE TITLE
Add optional time parameter to parent removetemp command

### ISSUE THREAD

**Issue by koca2000** [lucko/LuckPerms#1384]
As it is possible to accumulate time of temp parent it would be useful to be able to remove part of the time of temp parent.

The command would look like this: /lp user <user> parent removetemp <group> [time]

**Comment by BrainStone** [comment]
Have you tried adding a negative amount of time?

**Comment by koca2000** [comment]
I have. It says that player already temporarily inherits from that group.

**Comment by BrainStone** [comment]
You have to tell the Command that you want to add the new amount to the current amount. That should be no different than adding an amount. Which can be done by simply adding `accumulate` right after the time.

**Comment by koca2000** [comment]
I am sorry, I forgot to add accumulate. Strange is that this command lp user koca2000 parent addtemp vip -2m accumulate have added 2 minutes. Sorry for bad formatting. I am sending this message from phone.

**Comment by BrainStone** [comment]
Worth a shot. Then it seems to be not possible at the moment and like a fair suggestion.

**Comment by Bricec6** [comment]
Hello, is there anything new on this system? I think it's still important (automatic menu, need to remove time etc etc...), thank you.

**Comment by Bricec6** [comment]
Hello
Have news ? thanks.

**Comment by Bricec6** [comment]
When we place the order:
/lp user Extazii parent addtemp vip zddz20d accumulate

The plugin will not take into account the "-" and will add +5 minutes, I tested by putting any letter, for example:

/lp user Extazii parent addtemp vip zddz20d accumulate

he's still gonna add another 20 days. 
if that helps.

**Comment by lucko** [comment]
![](https://i.imgur.com/zUEAxDn.png)

**Comment by BrainStone** [comment]
`unsettemp` is kind counter intuitive. ``removetemp`` would be better I think. Maybe even just allow negative time values for ``addtemp``

**Comment by lucko** [comment]
`unsettemp` is the name of the previous command - I've just added an extra argument for duration ;)

**Comment by Bricec6** [comment]
I look forward to this update! Thank you :D

**Comment by BrainStone** [comment]
> 
> 
> `unsettemp` is the name of the previous command - I've just added an extra argument for duration ;)

I am aware. But ``unset`` always meant removing a node, not modifying it. That's where I take issue. It's inconsistent with the other unsets.
