### ISSUE TITLE
[Feature Request] Editor filter

### ISSUE THREAD

**Issue by DrZoddiak** [lucko/LuckPerms#1387]
I was wondering if it'd be possible to make the editor use a filter of some kind.
i.e `lp editor server=vanilla` 
The editor is a really nice tool, but it's a bit annoying scrolling though and double checking existing perms.
I'd like to be able to see perms for the server I'm currently working on. 
This feature could also apply to worlds in the same respect.
 `lp editor world=creative`

**Comment by lucko** [comment]
I think feature would be better implemented in the editor itself.
