### ISSUE TITLE
Hi im noob

### ISSUE THREAD

**Issue by FabianOphoff** [lucko/LuckPerms#139]
Hi, im using this plugin for todays first time, and im trying to figure out how I can make the plugin save all the data, thats get saved in a .db file, to a JSON file. Ive already changed the 'h3' to 'JSON'

Can someone please help me? I want to release my server this weekend and I kinda need a headstart.
Ive been using Permission Manager all the time and before in 1.7.10 Group manager, which is not there for 1.10.2

Thank you in advance!

**Comment by lucko** [comment]
Have you restarted your server since switching the storage option?

**Comment by FabianOphoff** [comment]
Yes I have

**Comment by lucko** [comment]
Can you send me the output of "/lp info" please.
