### ISSUE TITLE
Perms not saving after being added in Web Permissions editor

### ISSUE THREAD

**Issue by MrBuzzzz** [lucko/LuckPerms#1393]
When I add perms in the web editor after opening it by /lp editor they don't save. When I come back an hr later all the changes I have made and saved and applied to the server via /lp applyedits  are gone. Very rarely a random permission may save. I have lost count of how many times I have done this over many many days. It's a 1.12.2 paper spigot bungee server.

**Comment by BrainStone** [comment]
What message appears when you run the `/lp applyedits` command?  
And which version of LP are you using?

**Comment by MrBuzzzz** [comment]
Version 4.4.2

The message that appears when running /lp applyedits is a positive. It says permissions added/or removed depending on what I am doing... 

Could it be this setting below as the perms I am adding are world specific but its a bungee server:
# If users on this server should have global (non-world specific) groups applied
apply-global-world-groups: true

So I am guessing this should be false. The dev has LP on every server. Do I need to go in and change config on each one? Thats a problem as I cannot access a few servers with FTP due to persistent errors. 


![2019-01-21_19-37-57](https://user-images.githubusercontent.com/46713560/51472351-2b57bd80-1db4-11e9-94ab-f003bff764e5.jpg)

**Comment by BrainStone** [comment]
That setting shouldn’t affect anything. It just means that if a group has the world `global` that it also gets applied. Which is what you want typically. And you’re running 4.2.2 which is severely outdated. Please update the plugin. Latest is 4.3.73 or something like that.  
When you do that I suggest you rename your old configs and let the new one generate. As there have been quite a few changes to the config.

**Comment by Chefeku** [comment]
When i put in any perms they wont save. I save it, copy the link into minecraft. The perms work as long as the server is open or as long as the web editor is open. When I refresh the web editor the perms are gone. I have LuckPerms version 4.4.30 and the server is 1.14.4.

**Comment by Andre601** [comment]
> When i put in any perms they wont save. I save it, copy the link into minecraft. The perms work as long as the server is open or as long as the web editor is open. When I refresh the web editor the perms are gone. I have LuckPerms version 4.4.30 and the server is 1.14.4.

2 things:
1. This is not the right way to report problems. Make a separate issue next time.
2. This is no bug or issue at all. The editor uses the session that was created when using `/lp editor` as seen by the `#<code>` in the web address. The changes you made aren't saved on that specific address/code but on a separate one which is why a new command is created when saving the changes.
You have to do `/lp editor` again after applying your changes in-game, to receive the up-to-date session of the permissions, groups and users.
