### ISSUE TITLE
[LP] An unexpected error occurred. Unable to load all groups.

### ISSUE THREAD

**Issue by Alexxxiox** [lucko/LuckPerms#1394]
Error Log: https://pastebin.com/8DPZyfWg

[groups.zip](https://github.com/lucko/LuckPerms/files/2780344/groups.zip)

Loads Default, Mod, Admin but not Owner and Vip.

Happend while i ran "listgroups", after i manually deleted TABS from the yaml files

**Comment by lucko** [comment]
Is that the full error? Seems to be some info missing from the top.

**Comment by Alexxxiox** [comment]
What am i doing wrong?

**Comment by Alexxxiox** [comment]
So from what i understand, it came from the "&" in the files

- &8[&4Owner&8]:
    priority: 1

above is wrong
this should be the right way, but prefixes are still not shown.

- $8[$4Owner$8]:
    priority: 1

**Comment by Andre601** [comment]
Did you edit the files manually (Added the stuff manually) or did you made it through commands/the web editor?
Because editing files manually isn't recommended from us, because errors like the one you reporting can (and will) appear.
We really recommend to actually use the commands or the web editor.
And to your issue: Mind sharing the group-files with us? preferably through hastebin or a GitHub-gist.

**Comment by Alexxxiox** [comment]
at First i used the Web-Panel,  but i accidentally copied the TAB, so deleted them manually.

I tried replacing ChatEx with EssentialsChat but it didn't change anything, i just don't get why the Prefixes aren't there.

[groups.zip](https://github.com/lucko/LuckPerms/files/2780344/groups.zip)

**Comment by lucko** [comment]
```
[15:40:25] [luckperms-0/WARN]: [LuckPerms] Exception thrown whilst performing i/o: owner
```

So yeah, your owner.yml file has bad formatting, around this area:

```
[15:40:25] [luckperms-0/WARN]: java.io.IOException: while scanning an anchor
 in 'reader', line 5, column 3:
    - &8[&4Owner&8]:
      ^
expected alphabetic or numeric character, but found [(91)
 in 'reader', line 5, column 5:
    - &8[&4Owner&8]:
        ^

```

I suggest deleting that section of the file and re-adding the prefix using the commands - the formatting will definitely be correct that way. :)

**Comment by Alexxxiox** [comment]
I don't get an Error anymore, but Prefixes stilll don't show. I don't Know Why

**Comment by Alexxxiox** [comment]
Deinstalled ChatEx, Installed your VaultChatFormatter. Everything works perfect now.

Thank you for your Help
