### ISSUE TITLE
BungeeCord hangs after housekeeper run

### ISSUE THREAD

**Issue by voodootje0** [lucko/LuckPerms#1396]
LuckPerms Bungee 4.3.73 seems to randomly hangs/crash bungeecord without any further response. 
Log: https://haste.jartexnetwork.com/idusimozis
Bungeecord version https://ci.md-5.net/job/BungeeCord/1390/ (https://github.com/SpigotMC/BungeeCord/commit/9a2acc826e4cc37642219f718cdb8c1eca0c8703)

I am not sure this really crash has to do with luckperms as I never had any issues with luckperms before, but because I only saw this luckperms error I thought it could have something to do with it.

**Comment by lucko** [comment]
I'm not sure the two are necessarily related

**Comment by lucko** [comment]
Haven't been able to reproduce this - if anyone has any ideas feel free to re-open.
