### ISSUE TITLE
Allow support for wildcard permissions without having to define it

### ISSUE THREAD

**Issue by RoboBlawck** [lucko/LuckPerms#14]
Recreating Steps:
A)Install Modifyworld
B)Install LuckPerms
C)Enable item-restrction, item-use-check and player notifications on modifyworld config
D)Apply permission (modifyworld.items.hold.*) or (modifyworld.items.have.*)
E)Make modifyworld check for items(Spawn in item to your inv, then select your item slot to that item)

There are some reasons why it's a wildcard issue since if you use a more specific permission (modifyworld.items.hold.STONE), it seems to work.

Also, config directly says that wildcards "will only work for plugins that define all of their permissions to the server". Coincidentally modifyworld's plugin.yml has no permissions defined.

The reason why it should be implemented because modifyworld has potentially 100s of different nodes and not being able to use wildcard permission is severely limiting.

**Comment by lucko** [comment]
I'll work on it. ETA: maybe sometime later today.

It's a pretty horrible change to make though... 😢

**Comment by RoboBlawck** [comment]
why not add an enable/disable function so that people who don't want it and disable it, and people who do want it can enable it? The best of both worlds :)

**Comment by lucko** [comment]
Yeah, it wasn't as simple as that, unfortunately. :wink: 

Anyway, it actually brings a bunch of performance improvements, so it's a win win. 

Here's a download: https://ci.lucko.me/job/LuckPerms/133/
