### ISSUE TITLE
[Feature Request] Migration from UltraPermissions

### ISSUE THREAD

**Issue by CraftSteamG** [lucko/LuckPerms#1409]
I would really like to switch from UltraPermissions to LuckPerms, but I do not want to re-do all my permissions, and currently migrating from UltraPermissions to LuckPerms is not supported.

**Comment by lucko** [comment]
If you send me the UltraPermissions jar I can take a look at implementing it. :)

**Comment by CraftSteamG** [comment]
I'd have to talk to TechsCode because I believe I am not allowed to share the jar :(

**Comment by lucko** [comment]
Err yeah, he'd probably prefer if you didn't post it publicly, but you can PM it to me on Discord if you like.

https://discord.gg/luckperms

**Comment by BrainStone** [comment]
Isn’t there a public API?

**Comment by lucko** [comment]
Nope...
