### ISSUE TITLE
Can't load data

### ISSUE THREAD

**Issue by TheSilentPro** [lucko/LuckPerms#1410]
When i try to login to my local server to test some stuff luckperms doesnt let me join,
![image](https://user-images.githubusercontent.com/46107752/52054116-b9256c80-255b-11e9-8348-7078b9a6ece2.png)

**Comment by lucko** [comment]
Gonna take a wild guess that you're using CraftBukkit + offline mode.

Please make sure you are using Spigot or Paper, or enable online-mode.

Failing that, I need to see your server logs.
