### ISSUE TITLE
Issue with bungeecord syncing.

### ISSUE THREAD

**Issue by FishbirdDD** [lucko/LuckPerms#1411]
I am creating a bungeecord network and using LuckPerms. I have made a bungeecord network with LP before and it worked fine. I followed all of the instructions in the GitHub for setting up with a network. I am using the same configs and jars from the previous server (besides the bungeecord proxy), and I have no clue why it doesn't work.

**Comment by lucko** [comment]
All servers connected to the same database?

IP forwarding enabled and setup correctly?

In what way is it not working? Can you login? Are user permissions syncing? Are groups syncing?


I need waaay more information in order to help identify the cause of the issue.
