### ISSUE TITLE
Problems With Prefix and Group Name  label:type:issue

### ISSUE THREAD

**Issue by Nim54321** [lucko/LuckPerms#1413]
So i created my group i then add a prefix to it, but the problem happens when i not only see the prefix but also the group name. How do i get rid of the group name, but still get the prefix in front of my name?

**Comment by BrainStone** [comment]
Entirely up to your chat format and chat plugin.

Btw. you can’t tag issues.

**Comment by lucko** [comment]
> Entirely up to your chat format and chat plugin.

^^ - LuckPerms just provides the data to your chat plugin when requested. If it isn't being formatted the way you want, you need to dig into your chat plugins configuration.
