### ISSUE TITLE
MySQL "No operations allowed after connection closed" error

### ISSUE THREAD

**Issue by akiraic** [lucko/LuckPerms#1414]
Hello,

As the title says, **only** luckperms is having this problem from 1 to 3 hours after I start the server. The error message appears around that window of time. No other errors. Just keeps repeating itself again after 1 to 3 hours between each message.

Yes, I already followed the "Storage system errors" in the Wiki.
I double checked the MySQL **wait_timeout** and it is **28800** (default). I didn't change the default in config.yml either.
Here is the [storage section from my config file](https://pastebin.com/udHyRBRG)
And the [Console error log](https://pastebin.com/KjjH6f7C)

Sumary:

1. My setup has **Spigot 1.13 latest build** and **LuckPerms 4.3.73**
3. Error happens in production (several plugins) and in test setup (luckperms only)
4. Error also happens with new MySQL databases
5. Startup connection works fine
6. Also tested maximum-lifetime set to half (900000ms, 15min)

I found the [autoReconecct](https://dev.mysql.com/doc/connector-j/5.1/en/connector-j-reference-configuration-properties.html) property for MySQL, not sure how LuckPerms handle that tho.

Any ideas? Thank you in advance.

**Comment by BrainStone** [comment]
Does it happen to be a MariaDB server?  
Because if so, you should use the MariaDB storage type. And also it has several configs. I'm never sure which config it actually uses, so I'd check all.

**Comment by akiraic** [comment]
Is MySQL 5.7+, in this case. I was using MariaDB before, it was fine (no errors).

**Comment by lucko** [comment]
Appreciate you taking the time to read the wiki before making an issue! <3

I'm not sure either. These errors aren't from LuckPerms, and I don't know enough about the way MySQL / the MySQL driver works to be able to give much more advice.

As it's not an LP issue, there's really nothing I can do. I guess in terms of practical advice, you could:

* Attempt to set the lifetime even lower
* Switch back to MariaDB?? (if it worked before then perhaps that's gonna be the easiest way to resolve the problem)

**Comment by lucko** [comment]
Bear in mind also that timeout errors can be a result of dodgy network connections - if the link between the servers is bad that could result in connections timing out.

**Comment by akiraic** [comment]
Well, around 17 plugins use that database, and all of them are fine. Only LuckPerms is having the issue.
My database logs show no signs of LuckPerms trying to reconnect.

As you said, you don't know enough about MySQL, this could mean you may have left out some important configuration (or correction) while setting up the JDBC? Several other plugins that I use have the  **autoReconect** option in their code for MySQL. 

The issue is closed, no need for me to keep poking. Just asking kindly to not disregard issues like that because it is not impossible (or unusual) to miss something like that.

Just keep your eyes open for any leads, alright? <3 

Thanks for the hard work.

**Comment by lucko** [comment]
Absolutely, I'm definitely not infallible - far from it. 😉 

The reason I closed the issue is because as far as I can tell, there's nothing I can immediately change or identify within LuckPerms itself to resolve the issue.

The JDBC settings are fairly standard, and I'm using a very popular (and I would say generally well regarded) 3rd party library to handle connection pooling. I believe auto reconnect functionality is handled by Hikari in this instance.

If anything else comes up, or if anyone has any ideas, please feel free to comment and I'll reopen the issue. (or you can!)

**Comment by GeToNIX531** [comment]
Добрый день, напишу немного зацепок по этому вопросу. 
Я разрабатываю плагины, и тоже столкнулся с проблемой, как и в вашем плагине Lucky Perms.

1. При выполнении задач в одном потоке, ошибка возникает в указанном интервале.
2. В случае выполнение многопоточным запросов, проблема проявляется сразу, при попытки спама
3. AutoReconnect и другие настройки не помогают. 

Для решения, этих проблем, требуется пул. И постоянно "вручную" менять подключении раз в какой-то интервал.
Да мы решаем эти проблемы, но появляются другие ошибки, куда серьёзнее. Т.к есть шанс попасть в интервал сброса подключения, если множество игроков в этот момент за спамят запросами - краш сервера.

Единственный выход менять базу данных, особенно выраженная проблема касается панели: phpmyadmin использующий mysql. Поэтому вы правильно сделали, что не сфокусировались на решение, этой бессмысленной ошибки.
