### ISSUE TITLE
Error with Citizens

### ISSUE THREAD

**Issue by BrainRTP** [lucko/LuckPerms#1417]
Hi, i have a bug, when i set custom skins (/npc skin -t <uuid> <data> <signature>)
<img width="831" alt="2019-02-03 23 22 02" src="https://user-images.githubusercontent.com/22731705/52180635-a5ebf880-280a-11e9-9d47-c01a7c53771f.png">
Error: https://pastebin.com/WMuWtGMk
And when rename NPC
Error: https://pastebin.com/v8Y34DFt

**Comment by BrainStone** [comment]
The error message very clearly says what you need to do. And that it's not a bug.

**Comment by BrainStone** [comment]
Report it to the Citizens author btw. It's something they need to fix.
