### ISSUE TITLE
Multiple prefixes with ChatEx 1.5

### ISSUE THREAD

**Issue by Renay** [lucko/LuckPerms#1420]
I use LuckPerms v4.3.87, last build on this moment.
ChatEx - v1.6.
So .. I have problems with the tracks and not only.
I have two tracks, a donor and a staff. So, if I set the donor track to the user and then install the track to it, the user will have the last group from the first track and the penultimate of the second in the chat. Two prefixes as in the first screenshot.
![image](https://user-images.githubusercontent.com/23015901/52238700-58888d80-28d5-11e9-8e98-39b5194069dd.png)
![image](https://user-images.githubusercontent.com/23015901/52238959-ff6d2980-28d5-11e9-8cab-df44dd1ffd8b.png)

And if i use lp user {user} parent add {group} with WEIGHT, i have this
![image](https://user-images.githubusercontent.com/23015901/52239235-a8b41f80-28d6-11e9-90bc-28281d377cdf.png)

Another screenshots
![image](https://user-images.githubusercontent.com/23015901/52239273-be294980-28d6-11e9-909e-735f202d76b5.png)
![image](https://user-images.githubusercontent.com/23015901/52239294-ca150b80-28d6-11e9-8d61-caaea5548dd6.png)
![image](https://user-images.githubusercontent.com/23015901/52239327-dac58180-28d6-11e9-848e-eac837747942.png)

**Comment by BrainStone** [comment]
It seems like that `/lp user <user> info` shows the right prefix. So that is what LP is passing to ChatEx. Which means it's a ChatEx configuration issue.

Ask their support for help.

And in general. If `/lp user <user> info` shows the correct prefix it's not LP messing up.

**Comment by lucko** [comment]
Yep, seems to be a configuration issue with your chat plugin. :)
