### ISSUE TITLE
Migartion PowerfulPerms

### ISSUE THREAD

**Issue by arkobat** [lucko/LuckPerms#1421]
Hello
I'm trying to migrate from PP to LP, but have a small problem.
 [LP] Migration Sub Commands: (/lp migration ...)
 > no available plugins to migrate from

I've have both LP and PP installed, and I followed the provided guide at the wiki.
Here is a complete log, of the start.
https://pastebin.com/LkfneQaz

On line 1523 I should have used the command correctly.

**Comment by lucko** [comment]
Update to the latest PowerfulPerms version.
