### ISSUE TITLE
Need a way to unregister and unsubscribe.

### ISSUE THREAD

**Issue by Pangamma** [lucko/LuckPerms#1422]
In the API there are calls to register a context calculator and calls to subscribe to events. I need a way to unsubscribe and unregister as well so my plugin works well with loading and unloading. Otherwise I cannot say that my plugin handles memory management properly. 

A lot of people say you should never reload plugins. Personally, I reload my plugins individually 100 times before a server reboot is considered because of good housekeeping practices. To prevent any memory leaks I would like to have some unregister and unsubscribe API calls be added to luckperms. Can we make this happen? If so I would be very grateful. Thank you.

**Comment by Pangamma** [comment]
Based on what I have seen so far from the code I believe the easiest way to add this functionality without breaking existing API calls would be to make your system like the bukkit scheduler system. When you add a listener or something of that nature, return an integer key that can be used to remove the item later. Alternatively, allow people to unregister all "things" that have been registered by plugin X.

**Comment by Pangamma** [comment]
I tried to get the project up and running on my local computer, but was unable to resolve some of the issues with the project. If you're willing to help me get this thing set up I can take it the rest of the way and do these code changes for you.

**Comment by lucko** [comment]
#### Unregistering event handlers

Calling [`EventBus#subscribe`](https://github.com/lucko/LuckPerms/blob/85d2f0b51f7378fcf024046c5c1c4ca9e163bfbb/api/src/main/java/me/lucko/luckperms/api/event/EventBus.java#L54) returns a [`EventHandler`](https://github.com/lucko/LuckPerms/blob/master/api/src/main/java/me/lucko/luckperms/api/event/EventHandler.java) instance. You can call [`EventHandler#unregister`](https://github.com/lucko/LuckPerms/blob/85d2f0b51f7378fcf024046c5c1c4ca9e163bfbb/api/src/main/java/me/lucko/luckperms/api/event/EventHandler.java#L53-L58) to unsubscribe.

Alternatively, you can use the [`subscribe` method which accepts a `plugin` parameter](https://github.com/lucko/LuckPerms/blob/85d2f0b51f7378fcf024046c5c1c4ca9e163bfbb/api/src/main/java/me/lucko/luckperms/api/event/EventBus.java#L56-L74). This will automatically unregister the handler when your plugin disables. (in the same way the Bukkit event system works)

#### Unregistering context calculators

(this was only added in the commit referenced above)

Use [`ContextManager#unregisterCalculator`](https://github.com/lucko/LuckPerms/blob/85d2f0b51f7378fcf024046c5c1c4ca9e163bfbb/api/src/main/java/me/lucko/luckperms/api/context/ContextManager.java#L152-L158).

**Comment by Pangamma** [comment]
@lucko have you tested that fix on bungee cord?

**Comment by lucko** [comment]
I haven't tested but it should be absolutely fine.

**Comment by Pangamma** [comment]
One of the unregister methods as a blank method body. Is that intentional? I noticed that the register method in that same class is not left blank.

**Comment by lucko** [comment]
Can you send a link to that class?


> Also I do not use sponge API but what I was browsing the code for that I noticed the register method would wrap the inserted context in a proxied sponge context wrapper or something like that.

That's correct, but the Sponge API doesn't offer a way to unregister calculators anyway.

**Comment by Pangamma** [comment]
https://github.com/lucko/LuckPerms/blob/85d2f0b51f7378fcf024046c5c1c4ca9e163bfbb/common/src/main/java/me/lucko/luckperms/common/api/implementation/ApiContextManager.java

**Comment by lucko** [comment]
Woops - thanks!

**Comment by Pangamma** [comment]
Thanks for fixing it man!
