### ISSUE TITLE
Crash using Spigot 3GB

### ISSUE THREAD

**Issue by hornta** [lucko/LuckPerms#1426]
Version: LuckPerms-Bukkit-4.3.80.jar
Spigot: 1.13.2
My server is crashing from time to time. I think it is LuckPerms but I am not totally sure:
https://pastebin.com/raw/VwNjUsWu
https://pastebin.com/raw/8TRerhzs
https://pastebin.com/9hLqbatv

**Comment by lucko** [comment]
`java.lang.OutOfMemoryError: GC overhead limit exceeded` just means your server is running out of memory.

Nothing in any of those logs will tell you specifically which plugin is causing it. No reason to believe it's LuckPerms.

**Comment by lucko** [comment]
As for practical advice, I suggest removing plugins, especially those written by less reputable authors, which you've updated or installed recently, and see if that fixes the problem.

Alternatively, you can more frequently restart your server, to try to prevent it from getting to a point where it runs out of memory.
