### ISSUE TITLE
Trying to get luckperms to work with spigot + forge permissions at the same time.

### ISSUE THREAD

**Issue by MaxIsH0t** [lucko/LuckPerms#1428]
Hello, I have currently a pixelmon server (gen 7.0.1) and I have it running on spigot/bukkit. I am basically running spigot/bukkit with mods for 1.12.2. So the problem I have is that I have luckperms on my server and I put the perms etc. on each rank and they work. When I put forge permissions like permissions from the pixelmon mod to luckperms they don't still allow the users to use the command or anything. Is there a way to get forge perms compatible to use on my spigot server? I have down to pay to do this as well!

Discord: MaxIsHot#0001

**Comment by lucko** [comment]
If you want to use plugins alongside mods, I recommend using Sponge.
https://www.spongepowered.org/

Bukkit + Forge isn't really supported anymore. If permissions aren't working as you expect them to, then this is likely an issue with the server software you're using, or something to do with the way Pixelmon is checking for permissions.
