### ISSUE TITLE
Shorthand on Server Names not working

### ISSUE THREAD

**Issue by PoisonedPanther** [lucko/LuckPerms#143]
I'm trying to set permissions on some of my servers on a Bungeecord network, but not all, so I try to format the server name like, for example, (hub|creative), but I just get back "[LP] Server names can only contain alphanumeric characters." I'm unsure if the wiki is outdated and this is no longer supported, if this is an ID10T error, or if this is a bug.

**Comment by lucko** [comment]
Should be fixed. :)
