### ISSUE TITLE
Luckperms Placeholder error

### ISSUE THREAD

**Issue by xGlenor** [lucko/LuckPerms#1431]
Hey 😄 I have a problem with variables
i have a rank vip+8 and plugin FeatherBoard, LuckPermsMVdWHook
The problem is that the variable does not work because of the character "+"
variables: {luckperms_group_expiry_time_vip+8}

Could this be corrected?

**Comment by Imortalshard** [comment]
_{luckperms_group_expiry_time_<group name>}_
_{luckperms_inherited_expiry_time_<permission>}_
_{luckperms_expiry_time_<permission>}_

Unless the groupname actually is _vip+8_ than you're not really needing to add the +8

**Comment by xGlenor** [comment]
I don't understand
Group name is vip+8 and I can not change the name of this group so it can be fixed?

**Comment by Imortalshard** [comment]
Why can't you change the name of the group? There is a re-name command, Just keep in mind with the rename command you need to also update the groups of all users who are in that group, but that can easily be done with bulkupdate

**Comment by xGlenor** [comment]
Ok, I'll think about it.
But could you fix it? Just asking 😄

**Comment by Turbotailz** [comment]
It's not a LuckPerms issue.

**Comment by lucko** [comment]
Yep, this isn't a LP issue. You'd need to ask the author of MVdW placeholders to fix this.
