### ISSUE TITLE
Deploy implementation/common core for more advanced usage of API

### ISSUE THREAD

**Issue by gabizou** [lucko/LuckPerms#1434]
Currently, the API is available on maven, but there's some specific platform agnostic code that exists in [`common`](https://github.com/lucko/LuckPerms/tree/master/common) that is only usable as a dependency if one were to manually add a platform jar to their repo. I'd rather be able to depend on the common core from maven.

I know that @bloodmc uses it quite extensively

**Comment by bloodmc** [comment]
I actually just removed all usage of common so I won't need this =).

**Comment by lucko** [comment]
I could deploy the common code to Sonatype snapshots or something like that - although I'm intrigued as to exactly what parts you're using?

If it's just small bits, certain methods or hooks, these could be exposed in the API.

**Comment by bloodmc** [comment]
This can be closed as I am only using API now.
