### ISSUE TITLE
Permissions data for your user was not loaded during the pre - login stage - unable. Please try again later

### ISSUE THREAD

**Issue by FNG12358** [lucko/LuckPerms#1436]
So guys as i said i have problems with it 

http://prntscr.com/mmf6xx

I cant join the server.

**Comment by FNG12358** [comment]
[WARNING] [LuckPerms] User bc7ee6b4-a219-3f2e-8e68-85e7ab62db82 - FNGaming doesn't have data pre-loaded, they have never been processed during pre-login in this session. - denying login.

[INFO] Disconnecting com.mojang.authlib.GameProfile@c9d61f1b[id=bc7ee6b4-a219-3f2e-8e68-85e7ab62db82,name=FNGaming,properties={},legacy=false] (/46.217.73.209:51515): §7§l[§b§lL§3§lP§7§l] §cPermissions data for your user was not loaded during the pre-login stage - unable to continue. Please try again later.

[INFO] com.mojang.authlib.GameProfile@c9d61f1b[id=bc7ee6b4-a219-3f2e-8e68-85e7ab62db82,name=FNGaming,properties={},legacy=false] (/46.217.73.209:51515) lost connection: §7§l[§b§lL§3§lP§7§l] §cPermissions data for your user was not loaded during the pre-login stage - unable to continue. Please try again later.

**Comment by lucko** [comment]
> Luck - Last Sunday at 23:21
Fng I'm assuming you're FNG12358 on github

> Fng - Last Sunday at 23:21
yes

> Luck - Last Sunday at 23:21
are you using craftbukkit?
or spigot?

> Fng - Last Sunday at 23:21
yes
craftbukkit

> Luck - Last Sunday at 23:21
is your server in offline mode

> Fng - Last Sunday at 23:21
yes its cracked

> Luck - Last Sunday at 23:22
ok, you need to either make it online mode (not cracked) or use spigot/paper instead

> Fng - Last Sunday at 23:22
let my try

> Luck - Last Sunday at 23:22
luckperms does not work with craftbukkit + offline mode
https://github.com/lucko/LuckPerms/wiki/Installation#craftbukkit-and-offline-mode
