### ISSUE TITLE
Permission issue DeluxeChat

### ISSUE THREAD

**Issue by CodeByCam** [lucko/LuckPerms#1437]
**Server:** Paper version git-Paper-474 (MC: 1.13.2)
**LuckPerms Version:** 4.3.73
**DeluxeChat Version:** 1.13.2
**Group information:** https://pastebin.com/raw/mbTzHgmJ

There's an issue with my chat format being displayed due to a permission issue with LuckPerms. With help from Imortalshard in Discord we've ruled out DeluxeChat being the cause of this (so far). 

To give you a rundown, the `default` group having the permission `chatformat.default` (with contextual data matching the server name defined in the LuckPerms config) isn't actually displaying the correct chat format in-game. When I changed the DeluxeChat config node to `settler` it **did** work and displayed the correct chat format in-game, although the permission was still set as `chatformat.default`

I'm not too sure what else to write about this, but you can find Imortalshard and I chatting about this in #general on LuckPerms Discord (started an ~hour ago). We tried a lot of different things to make it work, but weren't able to resolve the initial issue. 

I hope I've included enough information, please let me know if you need anything further from me!
Cheers

**Comment by lucko** [comment]
I'm not too sure what to suggest.

You might be able to use the verbose command whilst using DeluxeChat & writing chat messages to see what's going wrong.

https://github.com/lucko/LuckPerms/wiki/Verbose

**Comment by CodeByCam** [comment]
Hey lucko, 
Cheers for your reply. 

I ran verbose and received the following:
`[LP] VB > camm_ - chatformat.default - undefined` 
It's stating the permission is undefined for my user, which means not true nor false, correct?

My groups are:
`[LP] - Primary Group: default`
`[LP] - Parent Groups:`
`[LP] -    > default (server=survival)`
`[LP] -    > default`

The group I'm in has the correct permissions:
`[LP] default (Settler)'s Permissions:  (page 1 of 1 - 3 entries)`
`> chatformat.default (true) (server=survival)`

With the above showing what it did, it still isn't working. 
I added the permission `chatformat.default` directly to my user, and now it works: `[LP] VB > camm_ - chatformat.default - true`
So the issue is, what, my user not inheriting the permission properly from the parent group (`default`)? 

Cheers

**Comment by Turbotailz** [comment]
If you remove the context from the `chatformat.default` permission (i.e. the `server=survival` part (you can do this easily on the web editor)), does it work? This might potentially be an error with your contexts.

**Comment by CodeByCam** [comment]
Hey Turbotailz, 
I removed the permission and re-added it without context to the default group: `LP] Set chatformat.default to true for default (Settler) in context global.`

Still doesn't wanna play.

**Comment by Andre601** [comment]
Perhaps the fact that you have the default group set twice (once with context and once without) causes this weird behaviour?

**Comment by Turbotailz** [comment]
Are you on Discord? Might be easier to help you if you join our support server https://discord.gg/luckperms

**Comment by CodeByCam** [comment]
@Andre601 I thought that, but I can't actually remove the `default` parent:

`> lp user CAMM_ parent remove default`
`[LP] camm_ no longer inherits permissions from default in context global.`

I assume the above would remove the `default` parent with no contextual data, however it still displays both groups. 

@Tur

> 
> 
> Are you on Discord? Might be easier to help you if you join our support server https://discord.gg/luckperms

I am in the Discord already :)

**Comment by CodeByCam** [comment]
After adjusting all the groups/permissions to remove contextual data and have everything global, and trying some troubleshooting with Unlucky Mods on Discord, the problem still persists. 

The permission `chatformat.default` being added directly to myself works, verbose and in-game chat confirms this. The same permission being added to my primary group, doesn't work, verbose and in-game chat confirms this.

I'm really not sure what else to do, adding permissions **per** player **per** rank, simply won't work due to the amount of players, although I considered it because this issue is tiring, haha.
Cheers :)

**Comment by CodeByCam** [comment]
_OhGodTriplePost_
Issue is resolved, took Turbo's advice and just wiped everything and set it up again. Everything is exactly the same but at least it works now. 

Cheers to everyone for your help!
