### ISSUE TITLE
Group names containing non alphanumeric characters

### ISSUE THREAD

**Issue by Seeroh** [lucko/LuckPerms#144]
I imported from PEX, and due to the differing system of reading permission groups, I changed my group names to make it easy to keep them organized and the like. Group-01-name, group-02-name, etc etc.

Since these were imported groups, they have the non-alphanumeric '-'. But I can't create new groups to match the scheme of my other groups. To be safe, would I be better off changing the group names to no longer have alphanumeric characters?

**Comment by lucko** [comment]
I'd say so, yeah.
