### ISSUE TITLE
API - im trying to get a players ownnodes using the API

### ISSUE THREAD

**Issue by Twi5TeD** [lucko/LuckPerms#1441]
int permsamount = Main.lp.getUser(target.getUniqueId()).getOwnNodes().size();
          List<Node> perms = Main.lp.getUser(target.getUniqueId()).getOwnNodes();

this is the way im getting the permissions but it shows other stuff aswell which i dont want how would i fix this?

**Comment by Andre601** [comment]
[api]: https://static.javadoc.io/me.lucko.luckperms/luckperms-api/4.3/me/lucko/luckperms/api/PermissionHolder.html#getPermissions--
[Discord]: https://discord.gg/luckperms

With node you mean the permission of a user?

In that case you may want to use [`me.lucko.luckperms.api.PermissionHolder#getPermissions`][api]

I never used the API, so I can't say if that would be the right/better way to do.
It would be a good thing to join the [Discord] and ask in the #api channel for support if you aren't on it.

**Comment by Twi5TeD** [comment]
ive asked in the discord channel and havent had any help with it ive tried #getPermissions but that also has alot more information that i dont need all i need is all the players permissions with group perms

**Comment by lucko** [comment]
The getOwnNodes method should do what you need.

You can then extract the permission from the `Node` object using the `getPermission` method.

**Comment by Twi5TeD** [comment]
how would i do that?

**Comment by lucko** [comment]
Call `node.getPermission()`.

**Comment by Twi5TeD** [comment]
what would i do though? 
    List<Node> node = Main.lp.getUser(target.getUniqueId()).getOwnNodes();
node.getPermission();

would it be like this?

**Comment by Twi5TeD** [comment]
anyone able to help?

**Comment by BrainStone** [comment]
The Javadoc (and your IDE) should help you figure out which method is the correct one (I don't know by heart)

**Comment by Twi5TeD** [comment]
ive already looked at it ive found out how to get the nodes but it shows other stuff aswell i just want the list to show like perm.test.1, permtest2

**Comment by BrainStone** [comment]
Now is the best time to familiarize yourself with Java Streams. Easiest way to bulkedit lists and collections in Java.

And how to get the permission from a node should be trivial to figure out with your IDE.
