### ISSUE TITLE
Can't Use Signs

### ISSUE THREAD

**Issue by ShadowAngel25** [lucko/LuckPerms#1443]
Hello, Maybe you guys can help me.
      When I try to use a sign I made with essentials, i can only use them as a server OP. Nobody can use them even as owner with all-perms. The only way I can use the signs is if i'm op'ed from the server cmd. Even when i give myself in-game all-perms. as my personal account, warp signs wont help. I even went through the config. files and checked everything to the best of my ability. Please help. Here are some picture for you to see the perms. of all groups. 
<img width="863" alt="luckyperms commands default" src="https://user-images.githubusercontent.com/46704592/53466459-afd2d700-3a17-11e9-9e40-089f9dbc3daa.PNG">
<img width="353" alt="lp me not serverop" src="https://user-images.githubusercontent.com/46704592/53466471-bbbe9900-3a17-11e9-814e-3e6500fe74ed.PNG">
<img width="849" alt="lp owner file with star" src="https://user-images.githubusercontent.com/46704592/53466472-bf522000-3a17-11e9-8a8b-44873a19367b.PNG">
<img width="897" alt="default with star" src="https://user-images.githubusercontent.com/46704592/53466476-c37e3d80-3a17-11e9-92ee-792dface81f5.PNG">
<img width="905" alt="lucky perms me" src="https://user-images.githubusercontent.com/46704592/53466488-cda03c00-3a17-11e9-8cbe-4b02a250799f.PNG">
<img width="149" alt="no warp as default" src="https://user-images.githubusercontent.com/46704592/53466501-d8f36780-3a17-11e9-98a1-6a42c6f4b97f.PNG">

On top of all that, I can't break blocks as owner group only if, again, i'm the server op from the server cmd. (no point in using pictures for this one.)
Also, this server is open to the public but only for certain people who know the ip.

**Comment by ktole1999** [comment]
for starters you can remove the * from your perm nodes. not needed. just use the base node: essentials

**Comment by ShadowAngel25** [comment]
@ktole1999  I'm assuming you're referring to the owner permissions?

**Comment by ktole1999** [comment]
Any perm.* reference should be changed



Sent via the Samsung Galaxy S® 6, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by BrainStone** [comment]
@ktole1999 incorrect. That only works on Sponge.

And in regards to your problem @ShadowAngel25 I'd highly recommend you debug your permission issues with [Verbose](https://github.com/lucko/LuckPerms/wiki/Verbose).  
Also please keep in mind that LuckPerms is not responsible for the actual permission nodes. When you're having issues with plugin's permissions, ask for help on their support places.

**Comment by ktole1999** [comment]
> Hello, Maybe you guys can help me.
> When I try to use a sign I made with essentials, i can only use them as a server OP. Nobody can use them even as owner with all-perms. The only way I can use the signs is if i'm op'ed from the server cmd. Even when i give myself in-game all-perms. as my personal account, warp signs wont help. I even went through the config. files and checked everything to the best of my ability. Please help. Here are some picture for you to see the perms. of all groups.

> On top of all that, I can't break blocks as owner group only if, again, i'm the server op from the server cmd. (no point in using pictures for this one.)
> Also, this server is open to the public but only for certain people who know the ip.

What server environment are you using?

**Comment by BrainStone** [comment]
Essentials pretty much always means Spigot/Bukkit

**Comment by ShadowAngel25** [comment]
> > Hello, Maybe you guys can help me.
> > When I try to use a sign I made with essentials, i can only use them as a server OP. Nobody can use them even as owner with all-perms. The only way I can use the signs is if i'm op'ed from the server cmd. Even when i give myself in-game all-perms. as my personal account, warp signs wont help. I even went through the config. files and checked everything to the best of my ability. Please help. Here are some picture for you to see the perms. of all groups.
> 
> > On top of all that, I can't break blocks as owner group only if, again, i'm the server op from the server cmd. (no point in using pictures for this one.)
> > Also, this server is open to the public but only for certain people who know the ip.
> 
> What server environment are you using?

Paper if that's what you're asking. But somehow when i was messing around with everything i could use the signs and so could my friend who was a test dummy. but they could only use them ONCE then they wouldn't work anymore. So like a one time use. So now i have to look into that but not sure where. But thanks for the help guys.

**Comment by BrainStone** [comment]
As I said, check out [Verbose https://github.com/lucko/LuckPerms/wiki/Verbose](https://github.com/lucko/LuckPerms/wiki/Verbose)

**Comment by ShadowAngel25** [comment]
> As I said, check out [Verbose https://github.com/lucko/LuckPerms/wiki/Verbose](https://github.com/lucko/LuckPerms/wiki/Verbose)

I'm sorry, but i have no idea how to debug this stuff with verbose so idk what youre talking about. I looked at verbose but i don't understand it.  I know that commands are fine because I can use the signs as owner with the essentials.* node. So i'll just talk to the developers support about this.

**Comment by Andre601** [comment]
Just use `/lp verbose on <your IGN>` and use the signs, to see what permissions are checked.
You can then disable verbose again after that with `/lp verbose off`

LPs verbose can return permissions with three values:
- `true` The user has permission to use the command/function.
- `false` The user has the permission, but it is denied.
- `undefined` The permission isn't set for either the user and/or the group.
