### ISSUE TITLE
[API Question] How can I force load player?

### ISSUE THREAD

**Issue by DrOreo002** [lucko/LuckPerms#1445]
So I need to access the User data for x player and I'm facing a problem where the User class cannot be found by getting it using the player's UUID. So I need a way to "force load" the player data into LuckPerms cache or whatever...

Please reply to this ASAP. Thanks ;D

**Comment by DrOreo002** [comment]
Nvm, found it

**Comment by lucko** [comment]
`loadUser` method - for anyone looking at this in the future. :')
