### ISSUE TITLE
Unknown character set: 'utf8mb4'

### ISSUE THREAD

**Issue by TRose2000** [lucko/LuckPerms#1447]
https://gist.github.com/TRose2000/f068e71f53ce74626e18aabbd0a33789

**Comment by BrainStone** [comment]
Update your MySQL server.

**Comment by TRose2000** [comment]
to what version.
I have currently 

8.0.15

**Comment by BrainStone** [comment]
Latest. Though it’s weird that MySQL 8 is having issues with that.

**Comment by TRose2000** [comment]
`MariaDB [(none)]> create database minecraft character set UTF8mb4 collate utf8mb4_bin;
ERROR 1115 (42000): Unknown character set: 'UTF8mb4'`

idk if I miss something

**Comment by TRose2000** [comment]
solved. -Thrasilias

**Comment by lucko** [comment]
What was the solution, out of interest?
