### ISSUE TITLE
How to bootstrap initial user?

### ISSUE THREAD

**Issue by vorburger** [lucko/LuckPerms#145]
@lucko thanks for this - looks cool! I've installed it, switched from h2 DB to YAML, and am trying to learn using it, but I'm stuck with not getting how you intended for the initial user to be bootstrapped...

So apparently (log) `[LP] Server Operator status has no effect when a permission plugin is installed. Please edit user data directly.` and so, kind of obviously, anything I first do, incl. a simple `/lp info`, gives `[LuckPerms] [WARN] User ... does not have any data loaded` ...

I sure could now peek into the src, figure out the YAML schema you use etc. but it feels like I must be missing something in the doc on the Wiki - like how do you add an initial op like user, so that one can first get started using the commands, creating groups, adding a few other initial users, etc. ?

**Comment by vorburger** [comment]
@lucko oh I got it.. you use the console to grant initial permissions, then in-game. Obvious; now.. ;) sorry!

**Comment by lucko** [comment]
No worries. :)
