### ISSUE TITLE
Can't open the editor (502 Bad Gateway)

### ISSUE THREAD

**Issue by Feniksovich** [lucko/LuckPerms#1450]
When you try to start the editor (/lp editor) and an error appears in the server console (502 Bad Gateway) and a link to the editor is not generated.

Pastebin: https://pastebin.com/9LCDweki

**Comment by nzminecraftDOTcom** [comment]
Already got one open :) https://github.com/lucko/LuckPerms/issues/1448

**Comment by Feniksovich** [comment]
I think that is related to another issue: https://github.com/lucko/LuckPerms/issues/1448

**Comment by smithy9901** [comment]
+1

**Comment by Feniksovich** [comment]
Web-site is already working, command operational.

**Comment by lucko** [comment]
Thanks for reporting - all fixed now :)
