### ISSUE TITLE
PEX to LP migration issue

### ISSUE THREAD

**Issue by ItsMatthewP** [lucko/LuckPerms#1453]
I am using version 4.3.73 for my game servers... I took all of the nessasary steps to migrate from PEX to LP, although when I run /lp listgroups I do not see any of our old PEX groups. 
-First I connected all our server’s PEX filed into the same database
-Then I downloaded LP on each server
-After, I ran the migrate command
-I then ran the bulk update command
-After that I ran the export command
-I deleted all PEX files
-I shut down all of our servers and configured LP onto the same database
-I started the server back up, and imported the export I made before

**Comment by Andre601** [comment]
Did you remove PEX at the end?

**Comment by ItsMatthewP** [comment]
>Did you remove PEX at the end?

@Andre601 Yes, although I did not remove the PEX folder just in case it didn’t work, only the .jar

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ItsMatthewP** [comment]
Sorry about closing it, that was a mistake

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lucko** [comment]
At what stage did the migration fail?

Were all of the groups migrated successfully before you tried to use the export/import commands?

**Comment by call911nowplz** [comment]
Did you try migrating while using a database? I assume so since you said " PEX filed into the same database"
If that's the case, Store everything on permissions.yml pex file without using a database. Then migrate.
