### ISSUE TITLE
Use in Dev-Environment causes AbtractMethodError

### ISSUE THREAD

**Issue by Panakotta00** [lucko/LuckPerms#1454]
So...
my problem is that I'm currently working on a bigger project and now the time comes to use luckperms as permission system. I'm developing a Mod and Plugin which run on SpongeForge. When I now try to run the server and then connect via client to the server, i get this error:

> [19:55:43] [User Authenticator #1/ERROR] [Sponge]: Could not pass ClientConnectionEvent$Auth$Impl to Plugin{id=luckperms, name=LuckPerms, version=4.3.99, description=A permissions plugin, url=https://luckperms.github.io, authors=[Luck], source=.\mods\LuckPerms-Sponge-4.3.99.jar}
> java.lang.AbstractMethodError: me.lucko.luckperms.common.storage.misc.PlayerSaveResultImpl.includes(Lme/lucko/luckperms/api/PlayerSaveResult$Status;)Z
> 	at me.lucko.luckperms.common.plugin.util.AbstractConnectionListener.loadUser(AbstractConnectionListener.java:73) ~[AbstractConnectionListener.class:?]
> 	at me.lucko.luckperms.sponge.listeners.SpongeConnectionListener.onClientAuth(SpongeConnectionListener.java:81) ~[SpongeConnectionListener.class:?]
> 	at org.spongepowered.common.event.listener.AuthListener_SpongeConnectionListener_onClientAuth105.handle(Unknown Source) ~[?:?]
> 	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:?]
> 	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:386) [SpongeModEventManager.class:?]
> 	at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:443) [SpongeModEventManager.class:?]
> 	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:404) [SpongeModEventManager.class:?]
> 	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:465) [SpongeEventManager.class:?]
> 	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:242) [SpongeImpl.class:?]
> 	at net.minecraft.server.network.NetHandlerLoginServer.fireAuthEvent(NetHandlerLoginServer.java:604) [NetHandlerLoginServer.class:?]
> 	at net.minecraft.server.network.NetHandlerLoginServer$2.handler$fireAuthEvent$zkf000(NetHandlerLoginServer.java:547) [NetHandlerLoginServer$2.class:?]
> 	at net.minecraft.server.network.NetHandlerLoginServer$2.run(NetHandlerLoginServer.java:198) [NetHandlerLoginServer$2.class:?]

**Comment by BrainStone** [comment]
Don't shade the API.  
In fact **never** shade any API, unless told otherwise.

**Comment by Panakotta00** [comment]
in my project I added the API Maven repository in my gradle build, but then i need the binaries at runtime so luck perms can function, so I added the normal luckperms sponge jar to the run/mods folder... whats with that the problem?

**Comment by BrainStone** [comment]
How did you add the API to the project (in gradle)?

**Comment by Panakotta00** [comment]
I added the api for my Addon with gradle:
```
repositories {
    mavenCentral()
}

dependencies {
    compile 'me.lucko.luckperms:luckperms-api:4.3'
}
```
and I've then added the binaries with the mods folder... so i moved the `LuckPerms-Sponge-4.3.99.jar` in the SpongeForge/run/mods folder

**Comment by bernieplayshd** [comment]
I think you have to use `compileOnly` instead of `compile` in the dependencies section, so the api doesnt't get included in the build

**Comment by lucko** [comment]
This isn't a LP error, it's most likely being caused by the hotloading your IDE is doing.

Setting to `compileOnly` might be a good fix. :+1:
