### ISSUE TITLE
Add FAQ Entry - "Where is my permissions.yml file!?"

### ISSUE THREAD

**Issue by Foxtrek64** [lucko/LuckPerms#1455]
This is a question I see quite often in the Discord - someone comes from PEX and gets worried when they don't see a `permissions.yml` file. So instead of accepting the learning curve and learning a new system, they decide that remaining with what they know, even if it's detrimental for the server, is better than the objectively better system. This FAQ entry would provide some insight into why LP doesn't default to flat file permission systems with a hope of dissuading someone from using it without a reason beyond "it's the way PEX did it so it's the best way" or "it's what I'm used to."

Below I've included a sample of what this FAQ entry may look like. We can discuss this further on Discord, but I wanted to get it up here in a more permanent manner. I'll be editing this post as things come up or are decided on.

As an added bonus, the bbcode format can be copy-pasted into a Discord Embed, which supports Markdown link formatting (the `[title](url)` format).

**Question: I'm coming over from PEX. Where is the permissions file?**
Answer: LuckPerms defaults to an H2 database for its storage system because of performance issues with flat file storage systems like `permissions.yml`. You may find that running with a flat file storage system causes LuckPerms to run much slower than usual, and it will complain of such in the server console. As such, it is strongly recommended you remain with the default, or if you're going to change, to change to a Remote Database configuration (MySQL, PostgreSQL, etc.). If you would like to change your storage type, you can do so by reading the [Storage Types](https://github.com/lucko/LuckPerms/wiki/Storage-types) page in the wiki.

**Comment by ktole1999** [comment]
in the wiki there is a migration section. https://github.com/lucko/LuckPerms/wiki/Migration that explains it.

**Comment by lucko** [comment]
> You may find that running with a flat file storage system causes LuckPerms to run much slower than usual, and it will complain of such in the server console.

This isn't true - it won't have an impact on the speed at which LP will run.

I'm happy to add a FAQ entry for this, but I believe it is already covered somewhat by the benefits/drawbacks section of this page.

https://github.com/lucko/LuckPerms/wiki/Storage-types

**Comment by lucko** [comment]
Will happily accept a PR for this.

https://github.com/LuckPerms/wiki
