### ISSUE TITLE
Rank away after name change

### ISSUE THREAD

**Issue by SupehSloht1** [lucko/LuckPerms#1456]
I am using BungeeCord and if someone changes his Minecraft name his rank on the spigot servers is gone but the rank on the bungeecord stays.

**Comment by SimonOrJ** [comment]
Is the bungeecord option turned on in the `spigot.yml` on your spigot settings?  If this is false, the spigot server may get the wrong UUID information.

This is likely a configuration error.

**Comment by lucko** [comment]
I agree with @SimonOrJ - most likely a config issue.

Please follow the steps outlined here.
https://github.com/lucko/LuckPerms/wiki/Network-Installation

:)
