### ISSUE TITLE
error when using mysql

### ISSUE THREAD

**Issue by hYdos** [lucko/LuckPerms#1457]
i have this error in console java.lang.NoSuchMethodError: org.apache.logging.log4j.spi.LoggerContext.getLogger(Ljava/lang/String;)Lorg/apache/logging/log4j/spi/E

and in minecraft when i connect from the bungee i get a database error occured whilst loading permissions data. please try again later.

**Comment by Andre601** [comment]
This gives like 0 information for us.

Please provide the startup log for your BungeeCord through https://paste.helpch.at (And maybe also Spigot log)

**Comment by hYdos** [comment]
https://paste.helpch.at/meduxogave.coffeescript is the startup log and i dont have luck perms on the bungee yet

**Comment by lucko** [comment]
Please try updating to the latest version of the plugin to see if that resolves the issue.

https://luckperms.github.io/
