### ISSUE TITLE
Make luckperms compatible with MySQL 5.7+

### ISSUE THREAD

**Issue by runelynx** [lucko/LuckPerms#1459]
Hiya,

The latest luckperms does not allow for the security options necessary to manage a secure MySQL installation as of versions that have been out for a good while now (at least a year). Please refer to below.

Every time luckperms accesses secured MySQL, the log generates this. This is normal for plugins that ignore secure vs insecure MySQL and there is no way to stop these.

[07:35:18] PST 2019 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.

Other plugins have accomplished this by building it into the connection string...
   address: jdbc:mysql://localhost:3306/rpgame?useSSL=false
Or by adding options and managing it in the code...  [[ideal]]
  mysql:
    username: ---
    password: --
    hostname: localhost:3306
    database: rpgame
    table-prefix: Jobs_
    verify-server-certificate: false
    use-ssl: true

**Comment by electronicboy** [comment]
The configuration file has a connection properties for specifying properties like that which lets you specify any connection properties you want, including `useSSL`

**Comment by Andre601** [comment]
[MySQL SSL error]: https://github.com/lucko/LuckPerms/wiki/Storage-system-errors#mysql-ssl-errors

LuckPerms has an option to disable SSL verification which you have to add manually to the config.
This is explained in the [MySQL SSL error] of the storage error-page on the wiki.

**Comment by lucko** [comment]
You can define extra connection properties in this part of the config file.

https://github.com/lucko/LuckPerms/blob/d1511e43f2e1d4e900e119756cc87ba76ded9a17/bukkit/src/main/resources/config.yml#L135-L138
