### ISSUE TITLE
Getting 2 Prefixes

### ISSUE THREAD

**Issue by XMaxTheKillerX** [lucko/LuckPerms#1460]
Hi guys,

I am currently running on Sponge with Nuclius and LuckyPerms. But I have a problem where when a player types something in the chat you will see his name twice.
https://prnt.sc/mvuqkz
Can someone help me out?

Kind regards,
Maxs

**Comment by BrainStone** [comment]
Entirely up to your chat plugin. Which is Nucleus in your case.

**Comment by XMaxTheKillerX** [comment]
Do you know where in Nucleus I can edit this. I cant find it

**Comment by BrainStone** [comment]
Ask their support
