### ISSUE TITLE
[Suggestion] split storage, redundant tables.

### ISSUE THREAD

**Issue by Ipshin** [lucko/LuckPerms#1461]
Curently (version 4.3.75) if I select split storage and configuring it to save only groups and tracks into my database (postgres) - all other luckperms_* tables are being created. Specifically user_permissions, actions and users. And since they have no functionality with such configuration and only cluttering my DB schema it would be such a great addition to skip tables creation for not configured data types. 

I have checked the code and see that **SqlStorage.init()** method have no parameters, and just loading postgresql.sql (and analogous) and executing it. Only check is for existence of the user_permissions table, and if it is deleted then all initialization is marked as failed :(

**Comment by lucko** [comment]
You're quite right - however, this would require splitting up the schema files. :/

I'm not too keen on doing this, and would rather just have redundant (empty) tables - the effort required to tidy this up doesn't justify the benefits imo. Hopefully you see where I'm coming from.
