### ISSUE TITLE
YAML File correct syntax?

### ISSUE THREAD

**Issue by baileyfreestone** [lucko/LuckPerms#1464]
Enabled yaml file but can't get any of the permissions to work
https://pastebin.com/B3tMJuA3
name: default
permissions:
- ftbutilities.homes.max: <10>
- ftbutilities.homes.cross_dim
- command.ftbutilities.tpa
- command.ftbutilities.tpaccept
- command.ftbutilities.sethome
- command.ftbutilities.home
- command.ftbutilities.delhome
- command.ftbutilities.back
- command.ftbutilities.warp
- command.ftbutilities.setwarp
- command.ftbutilities.delwarp

**Comment by baileyfreestone** [comment]
Have also tried adding :true to the end to no avail

**Comment by baileyfreestone** [comment]
Been trying to setup perms for awhile if anybody can help would be greatly appreciated

**Comment by Andre601** [comment]
We do not recommend to manualy edit permission.
Use ingame commands or the web editor.

Also there's the verbose command of LP that helps you to find out what permissions are checked for what plugin.
Check the wiki for more info.

**Comment by lucko** [comment]
The `ftbutilities.homes.max: <10>` line seems like incorrect formatting? I don't know what you're trying to achieve there though.

As Andre said, if you're not comfortable editing the files directly, I suggest using commands or the web editor.
