### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by ricardoborsato** [lucko/LuckPerms#1466]
Hey its there a way to purge inactive players data?

**Comment by BrainStone** [comment]
Define inactive players.

Also why exactly are you concerned with that?  
The database will take up a few MBs max

**Comment by ricardoborsato** [comment]
Like... A player who does not connect to the server for more than 90 days(exemple) ... There is an automatic way to "clear" on the user?

**Comment by BrainStone** [comment]
No. As LP does not track the last login of a player.

**Comment by ricardoborsato** [comment]
Oh ok.

**Comment by ricardoborsato** [comment]
Thanks ♥ ^-^

**Comment by BrainStone** [comment]
If you have a plugin tracking that, you can potentially use the LP API to clear the data.

But again. There's no real point in doing that.
