### ISSUE TITLE
Issues using Luckperms and Pixelmon

### ISSUE THREAD

**Issue by bba3075** [lucko/LuckPerms#1467]
When testing things for my server I tried using the /lp group group permission set pixelmon.command.pokegive true command to give my admins the /pokegive command, and it went through. But when attempting to use the pokegive command it did not work. It worked only once I used the /lp user user permission set pixelmon.command.pokegive true to give myself access. I ampart of the admin group, so it should have worked, But it doesn't, and if I run the group command again it says that the admins group already has the permissions in context global, but none of the admins can use the command.

**Comment by lucko** [comment]
Very unlikely to be a bug, you can use verbose to try to work out what's going on. :)

https://github.com/lucko/LuckPerms/wiki/Verbose
