### ISSUE TITLE
API with Eclipse

### ISSUE THREAD

**Issue by mnjg123** [lucko/LuckPerms#1468]
Hey, i am kinda "new" to spigot peogramming, and i wanted do connect my Chat plugin with Luckpers. i e. I want to get the prefix from the User/group.

Hwo do i do this?

I have no clue!

I use Eclipse and i dont know how to "connect" the API to Eclipse.

**Comment by BrainStone** [comment]
Use the Vault API instead. That’ll mean you automatically support any permission plugin that supports Vault too (essentially all of them) and using it is easier and a lot more streamlined for chat plugins. And there will be a lot more people being able to help.

**Comment by lucko** [comment]
The API documentation is available here: https://github.com/lucko/LuckPerms/wiki/Developer-API

Unfortunately, I can't provide general programming help. You can search online for how to import other jars into your Eclipse classpath.
