### ISSUE TITLE
Allow Ultra Permissions importing

### ISSUE THREAD

**Issue by Firefox8821** [lucko/LuckPerms#1473]
Allow us to import Ultra Permissions groups and perms. To see the plugin, look here:
https://www.spigotmc.org/resources/ultra-permissions.42678/

**Comment by BrainStone** [comment]
This has been requested numerous times. But due to Ultra Permissions not providing an API it is not possible.

**Comment by lucko** [comment]
Not only does it not have an API, the internals are organised in such a way that makes it pretty much impossible to extract data without a lot of supporting code.

It's also a paid resource, which I'm certainly not prepared to purchase. :wink:

**Comment by Firefox8821** [comment]
There actually is an API, look here: https://www.spigotmc.org/resources/ultra-permissions.42678/update?update=178077

**Comment by call911nowplz** [comment]
I have the plugin purchased and yes it does have an API, But adding a migration from it takes ALOT of time and not many users use ultra permissions, So it isn't really worth it. but if it's really important, I'm sure if you pay someone to do it manually you can find plenty of people.

**Comment by BrainStone** [comment]
If you manage to find a link to the API, that would help. Saying it's offering an API and actually offering one are two different things. And I honestly can't find it.

**Comment by call911nowplz** [comment]
The guy already sent a link above. You need the plugin before you use the API obviously.

**Comment by BrainStone** [comment]
That's a link to an update note. And the plugin. Not the API itself. Which needs to be accessible externally. Else it's utterly pointless.

**Comment by Firefox8821** [comment]
There actually is API notes attached to it.

**Comment by call911nowplz** [comment]
Nope, it isn't. The plugin itself is the API, you cannot use the API without the plugin, As they mentioned in their discord server

**Comment by BrainStone** [comment]
Which makes it useless.

**Comment by Firefox8821** [comment]
If you join his discord server, you can get the API directly.
