### ISSUE TITLE
Error while loading up LuckPerms.

### ISSUE THREAD

**Issue by imrowin** [lucko/LuckPerms#1474]
Could anyone tell me what this error means?
 https://pastebin.com/aUXkHDfQ

Using the LuckPerms Legacy, since I am using a 1.7.10 paperspigot build.

Can't join the server since it says "Luckperms has a issue with the database" or something like that.

**Comment by call911nowplz** [comment]
Hello, I think i may know what's causing this issue, It's the remapped hikari, I will send you an edited version of it, But keep in mind this is not from the official build and it's something me and my dev made. 

[remapped-hikari.zip](https://github.com/lucko/LuckPerms/files/2998432/remapped-hikari.zip)

**Comment by call911nowplz** [comment]
P.S unzip it, Delete the remapped-hikari that is generated by the plugin and replace it with this one. And start your server, If your database is working the server should work just fine

**Comment by imrowin** [comment]
lmao, I don't trust you. I just need a official answer on what the error means exactly, and from someone who is apart of LuckPerms.

**Comment by call911nowplz** [comment]
Yep I completely understand! But let's hope you get your problem fixed, Because I don't know if the version you're using is still supported

**Comment by imrowin** [comment]
Just wishing to know what the error means.

**Comment by call911nowplz** [comment]
luckperms doesnt use the slf4j logging It uses default bukkit logging, Atleast in that version, Can you try loading it up with no plugins other plugins? (I think Vault is required)
And tell me if the error is still there

**Comment by lucko** [comment]
Can you send over your full startup log please.

(sorry for the huge delay in replying - I've been very busy with other things 🙁  )

**Comment by imrowin** [comment]
Will do it at some time later, currently busy.

Thank you for the response.
