### ISSUE TITLE
Non default permission for console

### ISSUE THREAD

**Issue by dhkim0800** [lucko/LuckPerms#1475]
My plugin has a non-default permission. I need to use the command that checks this permission in console. How can i do it with console?

**Comment by call911nowplz** [comment]
/lp user (name) permission info. 
/lp group (name) permission info. 
Please read the wiki before posting an issue!

**Comment by dhkim0800** [comment]
Have you ever tried /lp user CONSOLE permiossion ?
Or did you read my issue carefully?

**Comment by call911nowplz** [comment]
there is no such thing as console permissions, /lp user CONSOLE will edit the user called "console" not the actual console.

**Comment by dhkim0800** [comment]
So i wrote this issue to add console specific permissions.

**Comment by call911nowplz** [comment]
It isn't possible to take away or give console a permission. Permission is where you can type any administrative commands.

**Comment by md678685** [comment]
The console isn't a player or group. It has full access to all permissions, and you can't change that.

If a command doesn't work from the console, then that's because the command itself refuses to work on the console. For example, a command like Essentials' `/suicide` refuses to work on the console, because the console isn't a player and can't die. This has nothing to do with permissions - it's just how the commands work.

**Comment by dhkim0800** [comment]
If plugin.yml's permission's 'default' is set to false, console can't use the command with LuckPerms

**Comment by call911nowplz** [comment]
Neither there is a way to make it possible. Luckperms will not be able to give console permission to do it

**Comment by ktole1999** [comment]
like was mentioned if console cant run command then that command is meant to run in game by player

**Comment by lucko** [comment]
> If plugin.yml's permission's 'default' is set to false, console can't use the command with LuckPerms

This is normal.


Test plugin:

```java
package me.lucko.test;

import org.bukkit.command.Command;
import org.bukkit.command.CommandSender;
import org.bukkit.plugin.java.JavaPlugin;

public class TestPlugin extends JavaPlugin {

    @Override
    public boolean onCommand(CommandSender sender, Command command, String label, String[] args) {
        sender.sendMessage("success!");
        return true;
    }
}
```

```yml
name: Test
main: me.lucko.test.TestPlugin
version: 1.0
commands:
  test:
    description: Test command
    usage: /home
    permission: test.perm

permissions:
  test.perm:
    default: false

```


Running `/test` as console with no other plugins installed:
```
> test
[14:31:04 INFO]: I'm sorry, but you do not have permission to perform this command. Please contact the server administrators if you believe that this is in error.
>
```

Running `/test` as console with LuckPerms installed:
```
> test
[14:33:36 INFO]: I'm sorry, but you do not have permission to perform this command. Please contact the server administrators if you believe that this is in error.
>
```
