### ISSUE TITLE
Having trouble with prefixes.

### ISSUE THREAD

**Issue by WiiShopChannel** [lucko/LuckPerms#1476]
I may have set up my groups wrong, but I am having trouble adding multiple prefixes. If I set a format to be the highest on track, it'll set the player's rank to the highest group inside of the parented group. How would I set it so it shows all of the prefixes they have?

**Comment by call911nowplz** [comment]
Give them all of the groups that you want them to have a prefix for, From my experience, Giving someone the highest rank in a track does not give them multiple prefixes, Because the priority is always gonna be the top rank prefix, Unless you give them multiple ranks. From another track

**Comment by call911nowplz** [comment]
Also 
https://github.com/lucko/LuckPerms/wiki/Prefix-&-Suffix-Stacking
