### ISSUE TITLE
[LP] An database error occurred whilst loading permissions data. Please try again later.

### ISSUE THREAD

**Issue by Saalty** [lucko/LuckPerms#1477]
I know there are similar issues out there but I am a newbie at all this stuff so didn't understand a word of it. The server boots completly fine but when a player joins the real issue occurrs: [LP] An database error occurred whilst loading permissions data. Please try again later. I looked in the console and found this: [https://pastebin.com/XbsVfY3y](https://pastebin.com/XbsVfY3y). I don't know what is happening at all I've had my server for a few days now and it has worked completly fine so I don't know why this is happening although I do know the offending file is: luckperms-h2.mv.db . Sooo... Please help.

**Comment by call911nowplz** [comment]
Can you please update to the latest version of LP https://luckperms.github.io that may fix it

**Comment by Saalty** [comment]
Thanks it fixed!

**Comment by Buddelbubi** [comment]
Still exist on Nukkit

**Comment by BrainStone** [comment]
Open a new ticket and provide your full log. Be sure to follow the template.
