### ISSUE TITLE
Issue in only specific server

### ISSUE THREAD

**Issue by Arttu1** [lucko/LuckPerms#1478]
Note: I Have this error only in my hub, also I've tried the "Storage system errors". But it works correctly on other servers.

my error: https://pastebin.com/NjRQpQVX

**Comment by Andre601** [comment]
It doesn't matter when it works on other servers.
When it doesn't work on that server, then it doesn't work.

Double-check that you followed the same steps, that you use the same version (preferably latest) and that everything listed here is correct:
https://github.com/lucko/LuckPerms/wiki/Storage-system-errors#luckperms-cannot-connect-to-my-mysql-server

**Comment by call911nowplz** [comment]
Please update to the latest version 
https://luckperms.github.io
That alone will fix many problems.

**Comment by Arttu1** [comment]
I updated it for every server, and bungee seems to be having that issue now.  Storage system errors I fixed earlier and I've had Bungee issues earlier too. Is Hexacord incompatible?

**Comment by Arttu1** [comment]
Update: I even tried switching database (Everything from cannot connect to the database).

**Comment by call911nowplz** [comment]
What storage method are you using? Are you sure the database is working? You can test it with another plugin and see if it works.

**Comment by Arttu1** [comment]
MySQL, other plugins it works. I've never had issue that i need to make thread here.
It is working with other servers and plugins.

**Comment by call911nowplz** [comment]
Use MariaDB Instead of MySQL, And double check if you entered your data right, If that doesn't fix it guess you have to wait for Luck to see the issue here

**Comment by Arttu1** [comment]
I could if my eu host would have that option, my us host (only for 1 server and its for other kind of server) may have it as it is multicraft?

**Comment by Arttu1** [comment]
I checked it alot of times.

**Comment by call911nowplz** [comment]
MariaDB works with any MySQL database. Its just a better storing method for LP than MySQL

**Comment by Arttu1** [comment]
Oh, i've always though they were completely different.

**Comment by call911nowplz** [comment]
Nope, it works fine with any database

**Comment by Arttu1** [comment]
Okay, rightnow i'm not at home, i can try later.

**Comment by Arttu1** [comment]
Still, tried to switch to MariaDB.

**Comment by lucko** [comment]
Is the server that can't connect on a different host / different machine?

Could perhaps be a firewall issue?

Either way, unfortunately (or maybe fortunately?!) this isn't a LuckPerms bug/issue.

All of the guidance I have for this issue is listed here:

https://github.com/lucko/LuckPerms/wiki/Storage-system-errors#luckperms-cannot-connect-to-my-mysql-server
