### ISSUE TITLE
Placeholders api fails to get rank

### ISSUE THREAD

**Issue by Alexhupp** [lucko/LuckPerms#1479]
whenever i try to use placeholder api i will get the error of ERROR:me.lucko.luckperms.sponge.service.reference.CachedSubjectReference Cannot be cast to org.spongepowered.api.service.permission.subject in virtual chest I am trying to use placholder apis %rank% or whatever it is and get that idk if it would just be the 1 thing as ive had nothing else to test it in but will later

**Comment by Arttu1** [comment]
Does papi have support for sponge?

Also have you downloaded LuckPerms sponge from jenkins?

**Comment by lucko** [comment]
This is a PlaceholderAPI issue - make sure you're using the latest version, and failing that, speak to the author and ask them to update the plugin to support newer Sponge API versions.
