### ISSUE TITLE
Prefix Stacking does not work with contextually applied prefixes

### ISSUE THREAD

**Issue by Hwiggy** [lucko/LuckPerms#1480]
I am not truly certain how to explain this issue further except with a bunch of photos.
I am using VaultChatFormatter (because I thought the problem existed only within EssentialsXChat) with the following format: `format: "{prefix}{name}{suffix}&7:&r {message}"`

I have configured prefix stacking to work as such:
```meta-formatting:
  prefix:
    format:
      - "highest_on_track_staff"
      - "highest_on_track_donor"
      - "highest_on_track_local"
    duplicates: first-only
    start-spacer: ""
    middle-spacer: " "
    end-spacer: " "
```

And the result, very visibly incorrect is this:
![image](https://user-images.githubusercontent.com/8173016/55126307-0b5db680-50e3-11e9-8853-40fa967397eb.png)
![image](https://user-images.githubusercontent.com/8173016/55126320-16b0e200-50e3-11e9-84f2-54b769dd7038.png)

The `local` track:
![image](https://user-images.githubusercontent.com/8173016/55126344-23353a80-50e3-11e9-829d-eca8a116eecb.png)

And some debug output: https://hastebin.com/raw/inamibefic

As a note, this issue is not present if the prefixes exist in a global sense, rather than a specific server context.

Output of `/lp verbose` after a bit of checking: https://luckperms.github.io/verbose/#3sZPlKmyUn
Some things to check out:
![image](https://user-images.githubusercontent.com/8173016/55127690-685b6b80-50e7-11e9-83e5-968ea3c051c8.png)
vs
![image](https://user-images.githubusercontent.com/8173016/55127698-714c3d00-50e7-11e9-8036-061654344011.png)
Which shows that the check from vault is not maintaining the same contextual information as the check from the plugin itself.

**Comment by lucko** [comment]
Make sure this option is set to `false`

https://github.com/lucko/LuckPerms/blob/c7a0d7026c9122292b33c8f1ea445cf0eef9201a/bukkit/src/main/resources/config.yml#L504-L507

Failing that, double check you're using the latest version. (it looks like you are already though)
https://luckperms.github.io/

**Comment by Hwiggy** [comment]
The configuration was outdated. These options were not present. However, the issue is fixed after migrating to a new configuration file.
