### ISSUE TITLE
Using UTF-8 Characters Inside Prefix/Suffix In-Game Generates a Console Warning

### ISSUE THREAD

**Issue by InteriorCamping** [lucko/LuckPerms#1481]
![image](https://user-images.githubusercontent.com/49039536/55186839-e7938280-516d-11e9-8241-e65b60354e98.png)

Unsure if this is an issue, given that the prefix displays properly in game with the UTF-8 symbol.
This occurs on a bungee server, connected with MySQL.

**Comment by lucko** [comment]
Latest version of LP?

You can try running these MySQL statements to change the charset. If you first ran LP with a version newer than https://github.com/lucko/LuckPerms/commit/2cb5e437fd65200eefe9a39f418d94da6a14c167#diff-eda03aa13dd70ab596751634e727f2b5 , this change will not have applied.

```sql
ALTER TABLE luckperms_user_permissions CONVERT TO CHARACTER SET utf8mb4;
ALTER TABLE luckperms_group_permissions CONVERT TO CHARACTER SET utf8mb4;
```
