### ISSUE TITLE
Suggestoin - addtemp command

### ISSUE THREAD

**Issue by blek-id** [lucko/LuckPerms#1483]
Hi there, I've been loving LP so far, and I have a suggestion for the devs. Can you please add a addtemp command so that we could add more time into a temp permission that already has a time? right now we only have settemp, where if we wanted to settemp the same permission, it doesn't do anything

**Comment by Andre601** [comment]
There is a setting in the config that defines, what LP should do, when you set the exact same temporary permissiion again.
Default is denying it, but there is an option, to actually let LP add the time to the remaining one.

https://github.com/lucko/LuckPerms/blob/2da6298c533445d766445c5ffd8660158f86fba3/bukkit/src/main/resources/config.yml#L250-L261

**Comment by BrainStone** [comment]
Also you can append one of those keywords after the time to override the default behavior

**Comment by Turbotailz** [comment]
This is already possible with the following command:

`/lp user <user> permission settemp <permission> <true/false> <duration> accumulate`

[Check the wiki next time ;)](https://github.com/lucko/LuckPerms/wiki/Command-Usage:-Permission#lp-usergroup-usergroup-permission-settemp)

**Comment by blek-id** [comment]
Oh my, I'm very sorry for not reading the wiki first haha. I thought by the name of the command "set" there wouldn't be any feature like that. Thanks for the help everyone!
