### ISSUE TITLE
Adding worldguard region as context

### ISSUE THREAD

**Issue by david-bla** [lucko/LuckPerms#1485]
Hi, would you consider this idea as valid?
What will be the disadvantages?

I'm currently struggling on spawn permissions, where I deny in some region things that are handled by worldguards block permission - and becomes overwritten by them.

Of course this is a priority thing from worldguard - but in general I'll have so much use cases where I want to apply permissions for some special group within a special region :+1: 
 

thank you in advance

**Comment by BrainStone** [comment]
The plugin ExtraContexts already turns WG regions into contexts

**Comment by david-bla** [comment]
Thank you :)
/close
