### ISSUE TITLE
Luckperms placeholder API (Some not working)

### ISSUE THREAD

**Issue by blek-id** [lucko/LuckPerms#1487]
Hi there, I'm currently using:
paper Build #577
luckperms v4.3.73
PlaceholderAPI 2.9.2

I've download luckperm's placeholder on PlaceholderAPI, and now I'm trying to test out the placeholder.

I've tested %luckperms_groups%, it returns an empty line and a 'member'
then i set a temp permission on a user with /lp user playername permission settemp insertpermissionhere true 24h

after that, i tested the placeholder %luckperms_check_permission_<permission>%, and it says yes, which means I have the permission

now i used %luckperms_has_permission_<permission>% for the same permission but now it says no, then when I check for remaining time 
%luckperms_expiry_time_<permission>%
and 
%luckperms_inherited_expiry_time_<permission>%

they both returns an empty line.

I'm trying to get the expiry time to work here but I just can't seem to get it to work. Is this a possible bug?

**Comment by blek-id** [comment]
Is bumping this okay?

**Comment by lucko** [comment]
Yes, sorry I had read this ticket, but then forgot to reply. 

I'll look into this & try testing myself, then get back to you. :)
