### ISSUE TITLE
YAML combined permissions file not working

### ISSUE THREAD

**Issue by Onyxtite** [lucko/LuckPerms#1490]
Hello, first of all, let me say your plugi has a lot of great things, its well developed. However, there are too many issues with yml files.
I understand you 'dont recommend to us' manually editing permission files, but its something that in theory you let us do with your plugin, and its something many server owners want, specially on a combined file . 

Issues with YMl files on luckperms:
-There is no way to create multiple groups on a single file from the console/game
-Manually trying to set up more than one grup on a YAML combined permissions doesnt work at least with any sintax i could think of.
-There is no real documentation for the sintax of yml files; people shouldnt have to guess how the plugin reads the config file in order to setup the groups.

Don't get me wrong, its a nice plugin, YML and combined YML are features or they aren't. Please, either  really support them or be transparent and don't say you do.

**Comment by Turbotailz** [comment]
I'm sure you'll appreciate that this is a very large plugin and not *everything* can possibly be documented thoroughly. There is a brief description of how it works in the config, which to be completely honest, covers it well enough in my opinion.

So how exactly does it not work for you? Maybe describe the steps you have taken so far to come to this conclusion.

On the other hand, it's generally not a good idea to blindly edit files without knowing how they're meant to be written. Generally you should create groups in game with the provided commands `/lp creategroup <group>` and then check how it's formatted within the file, that way you've got something to work from.

Lastly, have you tried the web editor? `/lp editor`

**Comment by Onyxtite** [comment]
Hey, yes, i understand, and im sorry if my initial comment was a bit harsh. I've tried to create a combinedgroups file, creating a yaml file named yaml-combined.yml and then i placed more than one group using the normal sintaxes using the examples you provide on the webpage, but the lastly listed groups overwritte the first ones, for example from the yaml parser:
https://yaml-online-parser.appspot.com/?yaml=name%3A%20VIP%0Aprefix%3A%20%27vipprefix%27%0Asufix%3A%20%27VIPsufix%27%0Apermissions%3A%0A%20-%20group.default%0A%0A%0Aname%3A%20helper%0Aprefix%3A%20%27nice%27%0Apermissions%3A%0A-%20group.default%0A&type=json

Then i tried to go inside of the game and creategroups, but while /lp creategroup does make a new group and place it in a new file, there is no way to place more than one group on the same file. 

Then i opened the web editor using /lp editor, but still didnt see any way to place more than one group on the same file.

I checked the groups made and their characteristics using ingame commands for example /Lp listgroups and the web editor.

**Comment by Andre601** [comment]
> There isnt anywhere that says what parameters you can include for a group in the config file, or which structure they should follow, how to make temporary/worldbased permissions /group paths/ etc.

This is mainly because it isn't meant to be edited by file.
Either use the commands or what Turbotailz suggested, use the web-editor.

Also there is a storage setting in the config to have all groups in one single yaml file (that doesn't mean you have to create a yaml file with `-combined` in its name, but to add `-combined` to the storage-method in the config.yml), but again it's really not recommended to edit files manually, no matter the reasons.

https://github.com/lucko/LuckPerms/blob/62ca2d9c7913aa0a95d766f65b1eb2e88f6a2bfa/bukkit/src/main/resources/config.yml#L82

**Comment by Onyxtite** [comment]
Thanks for the last explanation, that helped.

**Comment by Onyxtite** [comment]
For further reference, the grouped yml config will appear in groups.yml, and use the following sintax:

firstgroup:
  permissions:
  - xxxxx.xxx
  - xxxx.xxxx
secondgroup:
  permissions:
  - xxxxx.xxx
  - xxxx.xxxx


Keep in mind that other valid parameters such as prefix can probably replace permisisons.

**Comment by lucko** [comment]
The documentation is open source, so if you feel some sections could be improved or added, any contributions would be most appreciated.

https://github.com/LuckPerms/wiki
