### ISSUE TITLE
/afk and suffix's in tab

### ISSUE THREAD

**Issue by Aberdeener** [lucko/LuckPerms#1494]
While player using /afk with feature AFK tab list modification enabled, using LuckPerms, the command for adding suffix is incorrect. A priority is not specified.

Expected behaviour: Running /lp user <player> meta addsuffix <priority> *Afk*

Actual behaviour: Running /lp user <player> meta addsuffix *Afk*

**Comment by Andre601** [comment]
The right command is `/lp user <user> meta addsuffix <priority> <suffix>` but I don't see a reason why you use such a weird way, just to display people as AFK in the tablist(?)

**Comment by Aberdeener** [comment]
Apologies, another plugin was interfering. This was not luckperms fault. Closed
