### ISSUE TITLE
Nucleus Setupperms No longer working with newer updates

### ISSUE THREAD

**Issue by DrZoddiak** [lucko/LuckPerms#1495]
I've tested a few versions.
`4.3.8` On ore appears to be the last working version

`4.3.75` Also on ore is where the breakage begins.

I also tested the latest and oldest available versions on Jenkins (that I could manage to find)
`4.4.4` and `4.3.108` and neither of those worked.

Tested with 
Nucleus: `1.9.2-S7.1`
Sponge: `7.1.6-RC3616`

Steps to reproduce:

`/lp creategroup mod` 
`/nucleus setupperms mod mod`

`/lp group mod permission list` -> just for listing perms, also doesn't show up in editor either.

**Comment by lucko** [comment]
Thanks for reporting - sorry it took a while for me to get to fixing it! :)
