### ISSUE TITLE
MySQL - request timed out

### ISSUE THREAD

**Issue by DarkoGNU** [lucko/LuckPerms#1496]
Hey! I recently had to change LuckPerms storage method because of this. MySQL server is stable, the server is used by other plugins, and they all work well. My maximum-lifetime was set to 10 minutes, exactly like MySQL wait_timeout (yeah, it should be less, but it shouldn't kick everyone from the server). Server log: [hastebin](https://hastebin.com/vuqopixazo.md)
My previous config: [hastebin](https://hastebin.com/dixiwekipa.shell) (confidential data removed)

**Comment by lucko** [comment]
It's probably not LuckPerms that's timing out the players - I'd guess something else is causing high network latency, or the server is overloaded in some other way.

I don't think there's a LP bug here.
