### ISSUE TITLE
Trying to set up mysql storage and getting this error bungee.

### ISSUE THREAD

**Issue by hnmitch** [lucko/LuckPerms#1497]
Like the title says I'm getting errors when starting my bungee server up with Mysql storage settings

12.04 05:02:40 [Server] INFO Attempting to apply relocations to mysql_driver-5.1.47.jar...
12.04 05:02:40 [Server] INFO Attempting to apply relocations to hikari-3.3.1.jar...
12.04 05:02:40 [Server] INFO Loading storage provider... [MYSQL]
12.04 05:02:40 [Server] SEVERE INFO me.lucko.luckperms.lib.hikari.HikariDataSource - luckperms-hikari - Starting...
12.04 05:02:40 [Server] SEVERE INFO me.lucko.luckperms.lib.hikari.HikariDataSource - luckperms-hikari - Start completed.
12.04 05:02:42 [Server] SEVERE Failed to init storage dao
12.04 05:02:42 [Server] SEVERE java.sql.BatchUpdateException: Unknown character set: 'utf8mb4'
12.04 05:02:42 [Server] SEVERE at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
12.04 05:02:42 [Server] SEVERE at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
12.04 05:02:42 [Server] SEVERE at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
12.04 05:02:42 [Server] SEVERE at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
12.04 05:02:42 [Server] SEVERE at me.lucko.luckperms.lib.mysql.jdbc.Util.handleNewInstance(Util.java:425)
12.04 05:02:42 [Server] SEVERE at me.lucko.luckperms.lib.mysql.jdbc.Util.getInstance(Util.java:408)
12.04 05:02:42 [Server] SEVERE at me.lucko.luckperms.lib.mysql.jdbc.SQLError.createBatchUpdateException(SQLError.java:1163)
12.04 05:02:42 [Server] SEVERE at me.lucko.luckperms.lib.mysql.jdbc.StatementImpl.executeBatchInternal(StatementImpl.java:1060)
12.04 05:02:42 [Server] SEVERE at me.lucko.luckperms.lib.mysql.jdbc.StatementImpl.executeBatch(StatementImpl.java:970)
12.04 05:02:42 [Server] SEVERE at me.lucko.luckperms.lib.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128)
12.04 05:02:42 [Server] SEVERE at me.lucko.luckperms.lib.hikari.pool.HikariProxyStatement.executeBatch(HikariProxyStatement.java)
12.04 05:02:42 [Server] INFO Loading messaging service... [SQL]
12.04 05:02:42 [Server] SEVERE at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.init(SqlStorage.java:196)

**Comment by lucko** [comment]
This issue really exists because your MySQL server is a really outdated version - I suggest you upgrade to a newer version...


However, I've pushed a workaround fix for this in the above commit.
