### ISSUE TITLE
Add restriction to parent set

### ISSUE THREAD

**Issue by basman93** [lucko/LuckPerms#1498]
Add a way to restrict groups to set the parent of user that are only in specific groups.

For Example:
The Group Moderator has following permissions:
- luckperms.user.parent.set
- luckperms.user.parent.set.user
- luckperms.user.parent.set.default
- luckperms.user.parent.set.modify.others
- luckperms.user.parent.set.usecontext.global

Overall there are 4 groups:
Default, User, Moderator and Admin.

There are two User:
UserA --> group Moderator
UserB --> group Admin

Now, as far as I know there is no way to stop the Moderator from set the parent of UserB from Admin to Default.

**Comment by Andre601** [comment]
As far as I'm aware can you actually prevent that by using argument based command permissions.

Just enable this option here, restart the server and use the Verbose-command to find the right permission for the command:
https://github.com/lucko/LuckPerms/blob/4fa6cd25773c38f2bb82ca52a8398183b1b55ec9/bukkit/src/main/resources/config.yml#L276-L283

**Comment by lucko** [comment]
Indeed - this is possible with argument-based permissions, as linked above. :)
