### ISSUE TITLE
Don't work with java 7

### ISSUE THREAD

**Issue by arturek1666** [lucko/LuckPerms#15]
Hi, I am currently using spigot 1.10.2 and your plugins don't work on java 7. Before you send me a message back saying upgrade to java 8, I can't because I am not the owner of the host.  

It will be really nice if you make it work with java 7

**Comment by lucko** [comment]
Not going to happen, I'm sorry.

I would have to literally rewrite the whole thing. I use Java 8 streams and functions constantly throughout the entire plugin. 

I suggest you contact your host and ask them to update. You really shouldn't be running Java 7 anymore.
