### ISSUE TITLE
Prefixes aren't working,

### ISSUE THREAD

**Issue by ThatOneWolfe** [lucko/LuckPerms#1503]
I have no idea what I'm doing wrong, I've set up the groups, I've set up the group's prefixes, but they arent displaying the prefixes in game - What it says is [world] (ign) >> ______
The plugins we have installed are:
BF	-	Folder	
CoreProtect	-	Folder
Essentials	-	Folder	
HolographicDisplays	-	Folder	
LuckPerms	-	Folder	
Multiverse-Core	-	Folder	
OpenInv	-	Folder	
PlayerHeads	-	Folder	
PluginMetrics	-	Folder	
Updater	-	Folder	
WorldEdit	-	Folder	
WorldGuard	-	Folder
bStats	-	Folder
ArtMap-master.zip	
CoreProtect-2.16.3.jar	
EssentialsX-2.16.1.0.jar	
HolographicDisplays.jar	
LuckPerms-Bukkit-4.4.1 (1).jar	
Multiverse-Core-3.0.0-SNAPSHOT.jar	
OpenInv.jar	
PlayerHeads.jar
votifier-1.9.jar	
worldedit-bukkit-7.0.0-beta-05.jar	
What should I do?

**Comment by Andre601** [comment]
You need to have Vault installed.
LuckPerms provides the prefixes through Vault so that other plugins can use it.

**Comment by ThatOneWolfe** [comment]
Alright thank you

**Comment by ThatOneWolfe** [comment]
I downloaded the vault.jar but it still seems to not be working

**Comment by lucko** [comment]
You need to install a chat formatting plugin too. ;)

https://github.com/lucko/LuckPerms/wiki/Prefixes,-Suffixes-&-Meta#displaying-prefixes-and-suffixes
