### ISSUE TITLE
Meta Issues

### ISSUE THREAD

**Issue by Yorkforce** [lucko/LuckPerms#1505]
Luckperms 4.4.5
SpongeForge 1.12.2-2768-7.1.6-RC3652
GriefPrevention 1.12.2-4.3.0.662

I currently having issues with the meta set command using YAML setup.
When running the /lp group default meta set griefprevention.initial-claim-blocks 0
I get the following expected entry into the permission file:

```
meta:
- griefprevention.initial-claim-blocks:
    value: '0'
```

But when I do /lp group default meta set griefprevention.blocks-accrued-per-hour 0
It changes the above option to:

```
permissions:
- meta.griefprevention\.initial\-claim\-blocks.0:
    value: false
```

and enters the following in its place:

```
meta:
- griefprevention.blocks-accrued-per-hour:
    value: '0'
```

Am I doing something wrong here or is this an issue with luckperms/griefprevention?
The permissions for both don't seem to be working regardless.

**Comment by Andre601** [comment]
Use the `meta add` option because `meta set` replaces all existing entries with the provided one.

I can't tell if that works that way, and have no experience with griefprevention and if you set stuff through the meta-option, but it's worth a try.

**Comment by Yorkforce** [comment]
There doesn't appear to be a `meta add`, only in reference to `meta addprefix`?

**Comment by lucko** [comment]
Thanks for reporting, this is fixed in the latest version.
