### ISSUE TITLE
LP trying to load Brigadier when that is a 1.13.2 thing

### ISSUE THREAD

**Issue by LagClear** [lucko/LuckPerms#1506]
I am getting this with latest version of paperspigot 1.12.2

Error: https://paste.helpch.at/sigetataji.md 
Server Version: https://gyazo.com/de7a302666ef6ae68eaab1368441d7ca?token=bef4736d23321a04b6dc4a6a682875e3

**Comment by Andre601** [comment]
I had the same issue with my 1.12 server.
Re-downloading the spigot version again and restarting the server with it fixed it for me.
Could you try that?

**Comment by LagClear** [comment]
I am pretty sure its because of latest version of paperspigot due to it start happening right when I updated it 
my old paperspigot version is https://gyazo.com/f38cda569362de515c73e13a9c4d6136

**Comment by Andre601** [comment]
Like I said: This issue was fixed for me when I stopped my server, re-downloaded the latest version from Spigot and then started the server again with it.
