### ISSUE TITLE
suggestion: list online players with group-order

### ISSUE THREAD

**Issue by RedstoneFuture** [lucko/LuckPerms#1508]
Can you add a command like "/lpb list <maybe server-name>" to show the list of online-players like:

```
<prefix><groupname 1>:
    &f<user1>, <user2>
<prefix><groupname 2>:
    &f<user3>
...
```

BungeeCord have a "/glist" command an Bukkit a "/list" command but without a group-order.

I think it would be great, if the staff (or the player too) can check the player-groups with this feature without a staff-tablist or other external list plugins.

**Comment by lucko** [comment]
I think this would be better implemented by a separate plugin.

I don't think the usecase is enough to justify including it in LP.
