### ISSUE TITLE
Make verbose only show permissions that have changed

### ISSUE THREAD

**Issue by Andre601** [lucko/LuckPerms#1510]
When using `/lp verbose on` LuckPerms will show permission checks of plugins in the console or in-game, depending on where you run the command.
The issue here is, that this can get quite spammy and the permissions you actually searched for can get go down in the flood of permission checks.

This is because some plugins check permission every single tick (f.e. Scoreboard plugins).
My idea is to add an option, to make Verbose only show permissions in chat/console that had a recent change.
For example: I set a permission called `my.permission` with context `world=world` and with value `true`. This permission is checked by a plugin every tick.
When I now enable verbose with `/lp verbose` will LuckPerms show the permission once as true (when the verbose is activated) but won't show it again until I switch worlds to f.e. `world_nether`. Because context `world` has changed and is no longer world will LuckPerms show the permission again in chat with value false. But again just once since the permission doesn't change again until context or value changes.

> But you could use filters.

That is true but most people don't know about it or simply are too lazy to actually apply filters to the command.
Having such an option (f.e. as a config-setting) would help to find permissions without getting flooded by tons of other permission checks from plugins you aren't interested in right now.

**Comment by lucko** [comment]
I'm not so sure about this.

Verbose is meant to be, well, verbose. It's in the name!

Actually implementing the change detection system isn't super straightforward either - I don't think it's worth it personally.

Filters solve this issue perfectly - you can filter right down to a specific plugin / player very easily. "Most people" not knowing or being too lazy isn't a good reason to implement this.

**Comment by ChineseMarc** [comment]
LuckPerms - Lazy People edition when™

**Comment by PrincessRTFM** [comment]
LuckPerms - That's In The Documentation™

**Comment by ChineseMarc** [comment]
Back to topic, i think this would be hard on server but on web interface well that's another thing

**Comment by lucko** [comment]
Closing this for the reasons stated above.
