### ISSUE TITLE
Could not pass event AsyncPlayerPreLoginEvent to LuckPerms - v4.4.7 - Spigot 1.8.8

### ISSUE THREAD

**Issue by KyneasSurYoutube** [lucko/LuckPerms#1511]
Version Française :
Hey Salut,
Je vous avez déjà envoyé un message privé sur spigot, et je me suis dis en re-lisant l'affiche de LuckPerms, qu'il fallait ouvrir un ticket sur Github. Donc avant de commencer, désolé de vous avoir mp :/
LuckPerms (j'utilise la version 4.4.7 sous Spigot 1.8.8) est incompatible avec deux plugins présent sur mon serveur : UUID Spoof Fix et Staff+.
Elle empêche de lire les données lié à l'UUID d'un joueur qui se connecte sur une base MySQL.
Elle provoque l'erreur suivant : Could not pass event AsyncPlayerPreLoginEvent to LuckPerms v4.4.7.
Et voici le message d'expulsion que le serveur donne au joueur sur le client : [LP] A database error occurred whilst loading permissions data. Please try again later.

Voilà... Amicalement
Kyneas

---------------------------------------------------------------------
Version translated with Google Translate:

Hey Hello,
I have already sent you a private message on spigot, and I told myself reading the poster LuckPerms, it was necessary to open a ticket on Github. So before we start, sorry for having you mp: /
LuckPerms (I use version 4.4.7 under Spigot 1.8.8) is incompatible with two plugins present on my server: UUID Spoof Fix and Staff +.
It prevents reading data related to the UUID of a player that connects to a MySQL database.
It causes the following error: Could not pass event AsyncPlayerPreLoginEvent to LuckPerms v4.4.7.
And here is the ejection message that the server gives to the player on the client: [LP] A database error occurred while loading permissions data. Please try again later.

That's it ... Regards
Kyneas

**Comment by Andre601** [comment]
Please provide any information from the console.
When there is a database error, a error in console is pretty much guaranteed.
But I can already tell that the issues with LP are most certainly caused by your mentioned, incompatible plugins.
