### ISSUE TITLE
Context for weights

### ISSUE THREAD

**Issue by Vankka** [lucko/LuckPerms#1514]
Allowing setting contexts for weights eg. server=bungee world=skyblock etc.

**Comment by Turbotailz** [comment]
This might be possible using the web editor.

**Comment by Vankka** [comment]
if the weight permission has a context it will get ignored completely as of now

**Comment by lucko** [comment]
Usecase?

**Comment by Vankka** [comment]
Per server 'ranks', eg. skyblock & prison have different 'ranks'

Would make it possible for eg. BungeeTabListPlus to sort them correctly. Instead of having none-ranked with ranked players at the top. (because they have a rank with a high weight on the other server)

Aswell as displaying the right primary group on the right server

**Comment by Kryniowesegryderiusz** [comment]
@lucko it would be awesome solution for BungeeTabListPlus, which now makes huge problems with displaying players because of global weights. Could you reconsider adding this feature?

@Vankka Have you somehow managed to get rid of this BungeeTabList problem?

**Comment by Andre601** [comment]
BTLP has many more options for sorting which sure would be useful for you.

**Comment by Kryniowesegryderiusz** [comment]
They are not in case described by Vankaa

**Comment by Kryniowesegryderiusz** [comment]
That if somebody has rank with ex. 100 priority on one server, even if he does not have permissions on another - he would have very high priority

**Comment by Vankka** [comment]
@Kryniowesegryderiusz, no I never did. This suggestion is still valid

**Comment by Kryniowesegryderiusz** [comment]
@Andre601 Is it hard to implement that? Is that why are you avoiding this?

**Comment by Kociamba** [comment]
Yeah, I'm nervous too about that. I can't set ranks :/

**Comment by ZonK256** [comment]
Same here, I would also like to see that feature added

**Comment by lucko** [comment]
Unlikely to happen, the contexts system wasn't ever designed to support this.

I'm still toying with the idea of implementing node priority, which would cover this.
