### ISSUE TITLE
[Question] Pex Migrate users primary group

### ISSUE THREAD

**Issue by x1p** [lucko/LuckPerms#1515]
I'm trying a migration from Pex.
The basic setup is:
Groups:
- default
- group1 (inherites default)
- group2 (inherites group1)
- group3 (inherites group2)
- staff (inherites group3)
- admin  (inherites staff)

When migrating, LP saves admin/staff users like:
```
uuid: whatever
name: AdminPlayer123
primary-group: admin
parents:
- admin
```
I noticed that staff/admin doesn't inherit the some of the default permissions.
According to the wiki, if I'm correct, the staff players should be made staff by executing:
`lp user AdminPlayer123 parent add admin`
This results in:
```
uuid: whatever
name: AdminPlayer123
primary-group: default
parents:
- admin
- default
```
From what I understand, the config option `primary-group-calculation: parents-by-weight` should sense that the primary group for this player should be admin in this case.
The wiki is a bit scarce with examples. So what would be the most basic setup which should work so staff inherits all player groups?

**Comment by ktole1999** [comment]
use the editor in game

**Comment by ChineseMarc** [comment]
@x1p there are group weights for reason
https://github.com/lucko/LuckPerms/wiki/Command-Usage:-Group#lp-group-group-setweight

**Comment by x1p** [comment]
thnx. I know enough for this moment
