### ISSUE TITLE
How do I use LuckPerms BungeeCord?

### ISSUE THREAD

**Issue by DexenTV** [lucko/LuckPerms#1519]
Hello, 

I've recently switched to BungeeCord LuckPerms (downloaded from luckperms.github.io) and I put it in BungeeCord. I'm not sure if I should do that, OR just put it in all of my servers but I'm just double checking just to be positive so I don't mess up. Thanks!

**Comment by Andre601** [comment]
https://github.com/lucko/LuckPerms/wiki/Network-Installation

**Comment by DexenTV** [comment]
Thankyou!
