### ISSUE TITLE
Parent addtemp sum time if player already has temp perm/group

### ISSUE THREAD

**Issue by hsombini** [lucko/LuckPerms#152]
Hello, how about the command parent addtemp on a player that already has the target addtemp group/perm sums up the time instead of a message warning that he already has it?

With this the user can extend their time before the temp/group expires!

**Comment by lucko** [comment]
Thanks for the suggestion, I've been meaning to do this for a while 👍

**Comment by sudoman281** [comment]
Any update? Would be REALLY handy.

**Comment by BrainStone** [comment]
This has been implemented for for more than a year. Check your config and the Command Usage page.

**Comment by sudoman281** [comment]
Oh, thanks for your quick response. Sorry for bothering, I was blind :D
