### ISSUE TITLE
LuckPerms incompatibility with Staff+

### ISSUE THREAD

**Issue by call911nowplz** [lucko/LuckPerms#1520]
Hello. I noticed something interesting while using LP. It works just fine, Using MariaDB. But when i add this plugin https://www.spigotmc.org/resources/staff-the-ultimate-moderation-plugin-1-7-1-13.41500/
I get this error
https://pastebin.com/1Vzw0aAy
https://pastebin.com/94NmCg8L
And obviously i cannot join the server because 
§7§l[§b§lL§3§lP§7§l] §cA database error occurred whilst loading permissions data. Please try again later.

**Comment by call911nowplz** [comment]
Using old versions of StaffPlus fixes the issue. But not sure why the latest version causes the Database not to work.

**Comment by Andre601** [comment]
If adding a plugin causes LP to throw an error, then it's clear that it probably isn't a LP issue and should be reported to the plugin dev of the other plugin ;)

**Comment by call911nowplz** [comment]
Yep, already reported it to the other dev.

**Comment by lucko** [comment]
Hard to tell what the underlying issue is without the full log file.

Feel free to re-open if the Staff+ author is unable to resolve this.

**Comment by call911nowplz** [comment]
The developer of the plugin seems to be inactive. Older versions of the plugin solves the issue, But I am positive staff+ isnt the only plugin that isnt compatible with LuckPerms. 
https://github.com/lucko/LuckPerms/issues/1356#issuecomment-451901393 we had this issue and it was also caused by having an incompatible plugin, Luckily our developer fixed it

**Comment by lucko** [comment]
Yep, that issue was with an external logging API though, not sure LuckPerms was necessarily to blame.

Soo, latest version of Staff+ causes the problem? I can try testing myself to see if it can be reproduced?

**Comment by call911nowplz** [comment]
Sure, go ahead. Using MariaDB and staff+ installed on my server caused the error.

**Comment by lucko** [comment]
Is Staff+ configured with MySQL too? Perhaps the same issue as the one you linked if that's the case.

**Comment by call911nowplz** [comment]
In both cases it seemed to break LuckPerms, With mySQL and without
