### ISSUE TITLE
Configurations for bungee and spigot has error on messaging-services

### ISSUE THREAD

**Issue by Stattx** [lucko/LuckPerms#1521]
Server version 1.13.2
LuckPerms Bungee version -  LuckPerms-Bungee-4.4.17.jar
Luckperms Spigot version - LuckPerms-Bukkit-4.4.1.jar

Hello, I have found after long night of research that the Messaging portion has a small error which causes a failed 'Networksync' in game.

When you set 'messaging-service: sql'  in the configs whether it is on spigot server or in bungee it causes the error recorded in the screenshots below.

When you set 'messaging-service: none' it assumes that you are using sql based on that you have MySQL set as DB.  and it works flawless when all servers configs are matching.

if using 'messaging-service: none' it allows MySQL database to update properly and networksync command to function as it should.

Why is this an error if we set the messaging to sql instead of none?

![Error In Game](https://user-images.githubusercontent.com/20090766/57188775-21287d80-6ed2-11e9-80e6-3613cfee4269.png)
![Messaging-service none](https://user-images.githubusercontent.com/20090766/57188776-21287d80-6ed2-11e9-98ed-e974cd6eb63f.PNG)
![Messaging-service](https://user-images.githubusercontent.com/20090766/57188777-21287d80-6ed2-11e9-91d6-2a7471eb99bc.PNG)
![networksync with none for messaging-service](https://user-images.githubusercontent.com/20090766/57188778-21c11400-6ed2-11e9-96ad-07f3034bb763.PNG)

**Comment by BrainStone** [comment]
Which LP version are you using? I remember a big like that way back. And what you describe seems to work just fine for most people, if not all.

**Comment by Stattx** [comment]
> Server version 1.13.2
LuckPerms Bungee version - LuckPerms-Bungee-4.4.17.jar
Luckperms Spigot version - LuckPerms-Bukkit-4.4.1.jar

**Comment by lucko** [comment]
Can you post your server startup log here please :)
