### ISSUE TITLE
3 Groups - 3 Perms

### ISSUE THREAD

**Issue by DesperoKF** [lucko/LuckPerms#1522]
I have 3 groups: default, Premium, Ultra. They are connected to parent groups. How can I do that for example in default-perms: teamspeak.default, premium-perms: teamspeak.premium and ultra-perms: teamspeak.ultra. That is all permissions for only 1 group.

But if I have Ultra Rank, he'll take rank.default, rank.premium, and rank.ultra.

How can I do the rank.premium only for Premium and not for Premium and Ultra?

**Comment by Turbotailz** [comment]
Simply set permissions to `false` if they are inherited.

E.g: in the `premium` group, set `teamspeak.default` to `false` and in the `ultra` group, set `teamspeak.premium` to `false`.

**Comment by DesperoKF** [comment]
Thank you :D
