### ISSUE TITLE
WE NEED SETTEMP COMMAND.

### ISSUE THREAD

**Issue by successed** [lucko/LuckPerms#1524]
We need /lp user USERNAME parent settemp GROUPNAME 1m
I want a player to go to the group I want for 1 minute and then go back to the previous group.

I want to turn off the player's entry into more than one group because i don't need this. That's is ranks problem.

**Comment by SimonOrJ** [comment]
Why not use `addtemp`?  This should work perfectly (if group priorities are set up properly)

**Comment by successed** [comment]
> Why not use `addtemp`? This should work perfectly (if group priorities are set up properly)

i have inheritance so 1 player should be given a maximum of 1 group.

**Comment by SimonOrJ** [comment]
I'm not sure what inheritance has to do with adding another group

**Comment by Andre601** [comment]
If you setup weight and inheritance correctly then there should be absolutely no issue with using addtemp.
Higher weighted groups override lower ones by defalt

**Comment by successed** [comment]
> I'm not sure what inheritance has to do with adding another group. Just add the second group and all should work properly, provided you set group ~properties~ priorities (weight) properly



> If you setup weight and inheritance correctly then there should be absolutely no issue with using addtemp.
> Higher weighted groups override lower ones by defalt

İ have +30 ranks and +30 kits. i need single group set.if this is not the case, the authority of the kit that I have assigned to each group will interfere.

**Comment by SimonOrJ** [comment]
> i need single group set.if this is not the case, the authority of the kit that I have assigned to each group will interfere.

I would like you to rethink the setup.  I'm not sure what you're ultimately trying to do, but that sounds like a badly configured set-up or a bad plugin.

Consider the following:

* Group `default` has permission:
  * `kit.basic` = true
  * weight of 1
* Group `silver` has permission:
  * inherits `default` permissions
  * `kit.silver` = true
  * weight of 20
* Group `tempgod` has permission:
  * `kit.god` = true
  * `kit.silver` = false
  * `kit.basic` = false
  * weight of 50
* Group `tempjail` has permission:
  * `kit.silver` = false
  * `kit.basic` = false
  * `kit.jail` = true
  * weight of 60

Let's say you want to give John `tempgod` group for 1 minute.  John is in group `silver` already.  You can use `parent tempadd tempgod 1m`, and John will no longer be able to use `/kit silver` or `/kit basic` anymore.

Let's say Tom cheated, so you are punishing him by temporarily giving him a `tempjail` permission.  Just use `tempadd tempjail` to him and he won't be able to use any other kits except `/kit jail`. for some time.

You should set up permissions based on these examples.  Having a temporary *default* group just doesn't make sense.

**Comment by lucko** [comment]
This isn't particularly easy for me to implement, and to be honest I don't see the benefit, especially as pointed about above, this sort of behaviour is already possible when priorities are defined correctly.

Sorry, but yeah, I don't think it's something I'd be interested in adding to the plugin.
