### ISSUE TITLE
Bug with LP/BungeeChat2

### ISSUE THREAD

**Issue by Cosido** [lucko/LuckPerms#1526]
https://pastebin.com/hHTuQkm1

Luck Perms 4.4..17 works, 18/19 give this problem

Waterfall 282
Luck Perms 4.4.18
BC2 2.1.6.855

After logging in and typing a chat message, nothing shows in the ingame chat, my bungee discord bot DOES carry it to discord. But that error is what spams the console. Reverting to 4.4.17 fixes, so it appears to be with 4.4.18. I did test 4.4.19 this morning and got the same error though.

Reported it to BC2, was told it was a LP bug

**Comment by Porama6400** [comment]
@Cosido Based on your logs, seem like It's a duplicated report

I've reported it earlier today, here
https://github.com/lucko/LuckPerms/issues/1525

**Comment by Cosido** [comment]
I mean, we have some similar errors in the log, but the reason were getting them is entirely different. 

I dont have problems with disconnecting or commands, or permissions, I have problems with chat being carried. If Im told they are duplicates, Im sure it will be closed by someone who has a bit more information. Thank your for the response though

**Comment by Porama6400** [comment]
When you think about it, it's probably the same.

This is LuckPerms, it grant people permisson.
What do chat and command have in common, which handle by luckperms? ;) It's permission <3

**Comment by BrainStone** [comment]
It’s a duplicate. Same exact error as the other report.

**Comment by BrainStone** [comment]
And for future reference, post your case on the existing issue. And only if told to make a separate issue, make a separate issue. Not the other way round.  
Creating duplicates creates unnecessary noise that makes keeping track of bugs easier.
