### ISSUE TITLE
Permission applied Energestics crafting storage imbreacable

### ISSUE THREAD

**Issue by chouuul** [lucko/LuckPerms#1527]
Hello, i'm new on gitHub because i need your help ! When i place a crafting block only in the overworld
crafting co processing unit
crafting storage 1k
crafting storage 4k
crafting storage 16k
crafting storage 64k

i can't break them. disapear and replace... i didn't know what mod/plugin do this bug :(
AE2 codder said me it was a permission plugin, and i'm using luckPerms and universe guard... Somebody have an idea ?

Minecraft Version: 1.12.2
AE2 Version: appliedenergistics2-rv6-stable-6.jar
LP Version : LuckPerms-Sponge-4.4.4.jar
Forge Version: 1.12.2 - 14.23.5.2768 & sponge : spongeforge-1.12.2-2768-7.1.6-RC3641.jar

**Comment by lucko** [comment]
You can check with the verbose command.

LuckPerms isn't doing anything to specifically block those actions.

https://github.com/lucko/LuckPerms/wiki/Verbose
