### ISSUE TITLE
LuckPernc

### ISSUE THREAD

**Issue by Kotenol** [lucko/LuckPerms#1528]
I myself am a beginner, I hope not zagnobite.
The problem is that I cannot register op on the server due to LuckPerms [Server thread / INFO] [minecraft / DedicatedServer]: [LP] Please note that it’s not a problem. Please edit user data directly.

**Comment by Andre601** [comment]
[Discord]: https://discord.gg/luckperms

And your issue is........?

For general support should you join the [Discord] because while support is given on GitHub too, it's much faster and easier on Discord.

**Comment by Kotenol** [comment]
Luckperms 
Не разрешает выдавать op на сервере майнркафта через консоль

**Comment by Andre601** [comment]
Can you please talk english here?
Use a translator if you have issues.

**Comment by Kotenol** [comment]
I have problems with English, so I’ll use a pre-translator with Google,

**Comment by Kotenol** [comment]
I can not register op on the server minecraft, because Lp swears at something in the console, could you tell me what it is swearing at and how to fix it?

**Comment by Tobi406** [comment]
Are you using Sponge / SpongeForge?

**Comment by Andre601** [comment]
Sponge disables OP as soon as a permission plugin is installed.
So you can't use OP

**Comment by Kotenol** [comment]
Is it possible to somehow configure it through permission?
And I also registered permissions for the admin group, then I added myself through the console there, and it was still forbidden to use commands.

**Comment by Kotenol** [comment]
In the perm settings, the default group is prescribed, other permissions are tied to it, but commands are still not available

**Comment by ktole1999** [comment]
once you add user to admin group from console do /lp sync     then use in game editor to set perms if needed.
