### ISSUE TITLE
How do i give someone a permission in a multiverse world but not in a regular world?

### ISSUE THREAD

**Issue by Jxsten** [lucko/LuckPerms#1530]
I want to give my "builders" group permissions to "essentials.time" permission in my multiverse world called "creative" but not in my main world called "world"

**Comment by Andre601** [comment]
[`/lp group <group> permission set <permission> true world=<world>`](https://github.com/lucko/LuckPerms/wiki/Command-Usage:-Permission#lp-usergroup-usergroup-permission-set)

The wiki is your friend.
