### ISSUE TITLE
Permission sync issue

### ISSUE THREAD

**Issue by AconTM** [lucko/LuckPerms#1534]
Hey Luck,

we use a method to give players temp perms via your API. But without "lp sync" vault doesnt check this perm. More Informations here (i9hdkill via Discord):

![vcTeVQI](https://user-images.githubusercontent.com/26600880/57970321-27156880-7980-11e9-9b34-e10b5a35973b.png)

**Comment by i9hdkill** [comment]
Basically we are adding a temp permission via api and refreshing the group where the permission was added. The usecase is, that this temp perm should apply to all users on this server, as this group is the basegroup off all existing groups. We probably have to refresh all groups, but that sounds like too heavy hitting. In my opinion this permission add should somehow reflected instant in the cache(Its even in the db/yml)

**Comment by lucko** [comment]
Should be resolved in the latest commit. :)

**Comment by i9hdkill** [comment]
Thanks:)
