### ISSUE TITLE
useSSL doesn't work with Postgresql

### ISSUE THREAD

**Issue by hornta** [lucko/LuckPerms#1535]
And because I can only connect to my postgresdatabase with ssl, there is currently no way for me to use postgres. 
Either make useSSL work with Postgres or give me the ability to use my own connectionstring(instead of building the connection string in luckperms)

**Comment by Andre601** [comment]
[storage system errors]: https://github.com/lucko/LuckPerms/wiki/Storage-system-errors

It would be much better if you would provide actual information **why** useSSL doesn't work.
- What are the errors?
-  Are there even any?
- What did you try?
- Did you check the wiki for any ideas/options?
  - You should check the [storage system errors] page.

If you can answer those questions and perhaps provide more information maybe then we will be able to assist you.

**Comment by frengordev** [comment]
I both have a similar problem. In the console I got this:
`[luckperms-hikari connection adder/WARN]: Wed May 15 11:26:48 CEST 2019 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.`

I'm using a MySQL connection

**Comment by Tobi406** [comment]
Error is on the [storage system errors page here](https://github.com/lucko/LuckPerms/wiki/Storage-system-errors#mysql-ssl-errors).

**Comment by frengordev** [comment]
Oh, I didn't see that. Thank you

**Comment by lucko** [comment]
You can define your own connection options in this section of the config.

https://github.com/lucko/LuckPerms/blob/7f4f9bb9174ebd3d2225a814a86f9b717843207f/bukkit/src/main/resources/config.yml#L135-L138

**Comment by hornta** [comment]
@lucko I tries the useSSL option but it doesn’t work with postgres

**Comment by lucko** [comment]
I'm not familiar with how SSL works with PostgreSQL.

However, the options specified in that config section are just what LP passes on to the database connection pool.

If the option isn't working, then it's an issue with the PostgreSQL driver or your SQL server.

**Comment by muff1nman** [comment]
For anyone else stumbling upon this, I found that the following allows luck perms to connect to a database with a pg_hba config only allowing ssl:

```
data:
...
  pool-settings:
  ...
    properties:
      sslMode: require
```
