### ISSUE TITLE
/lp import imports at a random order which results in some data not applying

### ISSUE THREAD

**Issue by i9hdkill** [lucko/LuckPerms#1538]
I noticed that at least on sponge and bukkit, /lp import handles commands randomly, seems like it's async.
As groups should be created first, this often leads to group not exist errors. Using /lp import the second time fixes that, as all groups are created by now.

We imported all of our servers with 40k lines+ per file and I noticed after two servers that group assignments etc are missing. Luckily I realized that after a few servers, but some people might miss that and now have completely destroyed perm setups.

I can send you a big testfile to test, but it might be enough to make simple one by adding three groups.
Try /lp import a few times and watch how group creation is in a random order.

LP: 4.4.24
Sponge 7.1.6 - 2713
PaperSpigot 1.13.2

**Comment by Turbotailz** [comment]
I think you need to send through an import file for anyone to replicate this error.

**Comment by lucko** [comment]
Should now be resolved, was included in the v5 changes/fixes.
