### ISSUE TITLE
Either the URL was copied incorrectly or the session has expired.

### ISSUE THREAD

**Issue by tgray96** [lucko/LuckPerms#1539]
Hello,

I am having some issues after completing the self hosted web setup. I received the following error:
Either the URL was copied incorrectly or the session has expired.

Information:
Ubuntu 18.04
Nginx
Mariadb

BitByte is proxied behind nginx as well. 

![luckperms](https://user-images.githubusercontent.com/19181446/58143543-2cd9ab00-7c19-11e9-9687-95d257a8731e.png)

Related error from nginx's error.log

22816#22816: *1 connect() failed (111: Connection refused) while connecting to upstream, client: MyIP, server: BitByteURL, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8081/", host: "BitByteURL"

**Comment by lucko** [comment]
Check your browsers console when opening the page.

I'd guess this is probably caused by a Nginx misconfiguration.
