### ISSUE TITLE
Case Sensitive?

### ISSUE THREAD

**Issue by BokiP22** [lucko/LuckPerms#154]
Hi, today someone joined in my server with name "Abcfer" but the owner name is "abcfer".
It's possible to set the permissions case sensitive? In that case the name "Abcfer" don't have all permissions like "abcfer"

**Comment by lucko** [comment]
Nope. It's a limitation of running cracked servers.

LuckPerms doesn't modify this behaviour. You could try using an authentication plugin to change this though.
