### ISSUE TITLE
NoSuchMethodError: org.apache.logging.log4j.spi.LoggerContext

### ISSUE THREAD

**Issue by LuckyClutch07** [lucko/LuckPerms#1540]
https://hastebin.com/jicedenuru.md
Only happens when I switch to MongoDB
from h2
SRV VER: CraftBukkit version git-PaperSpigot-8b18730 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

Works fine on localhost also i am using mongodp from cloud.mongodb.com

**Comment by BrainStone** [comment]
Try to delete the `libs` folder in the `luckperms` folder.

**Comment by lucko** [comment]
This is most likely being caused by another plugin shading SLF4J incorrectly. Try running with only LuckPerms installed, if it works then you know the issue isn't being caused by LP.
