### ISSUE TITLE
/lp editor just gives list of commands

### ISSUE THREAD

**Issue by mebob33** [lucko/LuckPerms#1543]
Whenever I try to open the online editor, it just gives me a list of commands in minecraft. When i try using /lp group editor it gives me this error in the console,

22.05 22:10:15 [Server] WARN java.lang.RuntimeException: Connection returned response code: 401 - Unauthorized
22.05 22:10:15 [Server] WARN at me.lucko.luckperms.common.commands.impl.generic.other.HolderEditor.paste(HolderEditor.java:167)
22.05 22:10:15 [Server] WARN at me.lucko.luckperms.common.commands.impl.generic.other.HolderEditor.execute(HolderEditor.java:109)
22.05 22:10:15 [Server] WARN at me.lucko.luckperms.common.commands.impl.generic.other.HolderEditor.execute(HolderEditor.java:70)
22.05 22:10:15 [Server] WARN at me.lucko.luckperms.common.commands.abstraction.MainCommand.execute(MainCommand.java:102)
22.05 22:10:15 [Server] WARN at me.lucko.luckperms.common.commands.abstraction.MainCommand.execute(MainCommand.java:45)
22.05 22:10:15 [Server] WARN at me.lucko.luckperms.common.commands.CommandManager.execute(CommandManager.java:181)
22.05 22:10:15 [Server] WARN at me.lucko.luckperms.common.commands.CommandManager.lambda$onCommand$0(CommandManager.java:131)
22.05 22:10:15 [Server] WARN at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
22.05 22:10:15 [Server] WARN at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:58)
22.05 22:10:15 [Server] WARN at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
22.05 22:10:15 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
22.05 22:10:15 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
22.05 22:10:15 [Server] WARN at java.lang.Thread.run(Thread.java:748)
22.05 22:10:15 [Server] INFO [LP] Unable to upload permission data to the editor.

Any help would be appreciated. Thank you.

**Comment by BrainStone** [comment]
What LP version are you using?

**Comment by mebob33** [comment]
Im Running LuckPerms v4.0.18.

**Comment by BrainStone** [comment]
Update. This is almost 2 years old if I remember correctly.

**Comment by mebob33** [comment]
Oh shoot really? Ok ill try that.

**Comment by mebob33** [comment]
It worked thank you so much. I am an idiot
