### ISSUE TITLE
Luckperms and prestige issue on prison

### ISSUE THREAD

**Issue by RisenCloud** [lucko/LuckPerms#1544]
Hello, we are having some issues that whenever someone prestiges or even reaches our last rank before they prestige, it takes all their perms and their chat format and everything. Here is the config here. Our whole luckperms file is 1 GB and would be way too much to even upload to Mega, I am not sending you 838 ranks each file individually so all I can send is the config. 

https://hastebin.com/ofiqodozos

**Comment by BrainStone** [comment]
How are the players ranked up?

**Comment by i9hdkill** [comment]
99% an issue with your rankup plugin doing weird stuff on the last stage(removing the users group and don't adding the last one or your last group is broken without having the previosu ones). Either provide info on how the plugin is doing that or even better, ask the plugin dev of your rnakup plugin for help

**Comment by RisenCloud** [comment]
The thing is, we use this as rankup plugin too :P sooo something wrong with LuckPerms. They rankup by doing /mru or /rankup and it takes away their last ranks and adds the next rank to them.

**Comment by BrainStone** [comment]
@RisenCloud check if they get the new group.

**Comment by RisenCloud** [comment]
They do, it's the same config we have had for almost 4 years. Same groups, same perms, everything. Just now it starts to glitch.

**Comment by lucko** [comment]
Sounds like an issue with your rankup plugin, not LP.
