### ISSUE TITLE
Run command when temporary permission ran out?

### ISSUE THREAD

**Issue by blek-id** [lucko/LuckPerms#1546]
Hi there, can we have a command to be run when the player no longer has the permission?

**Comment by ChineseMarc** [comment]
Using luckperms api in your own plugin, yes
Using luckperms, i don't think so

**Comment by Andre601** [comment]
There is no reason for a perm plugin to have this.

**Comment by lucko** [comment]
Sorry, not something I plan to include in LuckPerms itself at the moment.

As has been pointed out above, this can be done using the API - you could either write your own plugin to do this, or ask someone else to make one for you. :)
