### ISSUE TITLE
/lp group editor only displaying LuckPerms version

### ISSUE THREAD

**Issue by Busuw3** [lucko/LuckPerms#1547]
I am currently having an issue when I run the command /lp group editor - It just displayed the luckperms version with nothing else. I have used LuckPerms on a vanilla server so I am familiar with how it works overall. 

![image](https://user-images.githubusercontent.com/11339778/58356825-dbf2ce00-7e35-11e9-8a40-2a2903f42786.png)

SpongeForge Version 1.12.2-2768-7.1.5
LuckPerms Version 4.3.75

Any help would be greatly appreciated!

**Comment by Busuw3** [comment]
Just noticed there was an issue between LuckPerms and another Sponge Plugin. Removing the plugin has granted me the ability to use the /editor. Please set this to solved/remove it if need be.

**Comment by BrainStone** [comment]
Also make sure you update. Your version is fairly outdated.

And if that message appears it means you don't have permissions.
