### ISSUE TITLE
Bungeecord error

### ISSUE THREAD

**Issue by coco0325** [lucko/LuckPerms#1549]
Bungeecord version: latest
Luckperms version: 4.4.24
https://pastebin.com/K0fSrYwM

**Comment by BrainStone** [comment]
Not an error. Just a warning. And it’s because your Java is too up to date. It’s recommend to use Java 8 for Minecraft.

**Comment by coco0325** [comment]
But I'm using java 11 for bungeecord.

**Comment by coco0325** [comment]
And bungeecord won't listening on port.

**Comment by BrainStone** [comment]
As I mentioned, it’s not an error. And it goes away when you use Java 8. Which you should.

And it not listening on the port is not a LP issue.

**Comment by coco0325** [comment]
You are right. It works on Java 8.
