### ISSUE TITLE
[Not an issue] Question

### ISSUE THREAD

**Issue by AlwaysCandr** [lucko/LuckPerms#155]
Hello,
I would like to know what happens if I install LuckPerms and give a person temporary permission test.test for let's say 2h and then give that same person the same temporary permission test.test for 5h, will the person have the test.test permission for 2h, 5h or 7h? 

I would need time combining because I would like my creative server to have 1 vote=1h of WorldEdit. And in case the person votes multiple times, I wonder what would happen with LuckPerms.

Best Regards

**Comment by lucko** [comment]
Related to #152.

Currently, the command will just fail.   
I'll be changing that though.

**Comment by AlwaysCandr** [comment]
Very well. I hope it gets updated soon so that a new command will just increase permission time. 😃

**Comment by lucko** [comment]
Sometime next week hopefully.
