### ISSUE TITLE
Prefix string for essentials 

### ISSUE THREAD

**Issue by Sembauke** [lucko/LuckPerms#1552]
I wonder if there is any kind of prefix string for essentials.
e.g : [Rank]

**Comment by i9hdkill** [comment]
Hi, have a look here
https://github.com/lucko/LuckPerms/wiki/Command-Usage:-Meta#lp-usergroup-usergroup-meta-addprefix

**Comment by lucko** [comment]
More info here as well: https://github.com/lucko/LuckPerms/wiki/Prefixes,-Suffixes-&-Meta

**Comment by Sembauke** [comment]
thanks
