### ISSUE TITLE
litebans error can't run the /ban command.

### ISSUE THREAD

**Issue by DarrenSanders123** [lucko/LuckPerms#1553]
it works if I type it in the console but when I try to type it in game it doesn't even give me a response, and my bungeecord console is spammed with errors of luckperms.

**Comment by DarrenSanders123** [comment]
and no other bungeecord command works. and /server doesn't give me a response but works when I type a server behind it.

**Comment by BrainStone** [comment]
What error...?

That might be tad useful, you know?

**Comment by DarrenSanders123** [comment]
it is a really long error

**Comment by DarrenSanders123** [comment]
do you want the hole thing?

**Comment by BrainStone** [comment]
No. I'll just telepathically read it. Now problem!

**Comment by DarrenSanders123** [comment]
This are the latest logs
[proxy.log](https://github.com/lucko/LuckPerms/files/3219541/proxy.log)

[proxy (3).log](https://github.com/lucko/LuckPerms/files/3219540/proxy.3.log)

**Comment by BrainStone** [comment]
Update LuckPerms

**Comment by DarrenSanders123** [comment]
thx it works now
