### ISSUE TITLE
Errors after upgrading from 4.4.22 -> 4.4.25

### ISSUE THREAD

**Issue by TMCGH** [lucko/LuckPerms#1555]
After updating to the latest version, one of my staff members was unable to login and was sending this error to console. http://prntscr.com/nu78hk and recieving this error when logging in http://prntscr.com/nu8603

Shortly after trying to reupdate all plugins, it began happening to me aswell.

**Comment by Andre601** [comment]
We need more information like what server version you run, if it is in online or offline mode and if it is part of a bungeecord network.

Also delete the libs folder in the LuckPerms folder and let LP download the jars again (restart the server for that)

**Comment by TMCGH** [comment]
This is a bungeecord network, the version is 1.8.8 . I also deleted the lib folder in the bungee lp folder + the hub servers lp folder and restarted both and am still receiving the same error on login after updating from 4.4.22->4.4.25

What happens in the bungee screen on login: http://prntscr.com/nuhhlp

**Comment by Andre601** [comment]
The screenshot doesn't show the actual error itself (the stacktrace)

**Comment by i9hdkill** [comment]
Weird, there were no changes between those versions that could cause that error. That error while setting a group should happen on 4.4.22 too.
Looks like you messed up the database config options or changed the db password. Check the startup log for details
