### ISSUE TITLE
Group displayname in group format.

### ISSUE THREAD

**Issue by GetJiggyWitIt** [lucko/LuckPerms#1556]
I'm using essentialsxchat and when I try to use group formats with LuckPerms the displayname of the group automatically added itself to the format.
![chat](https://user-images.githubusercontent.com/51163178/58558625-54b7a880-81ef-11e9-9255-a2bb2b5ffa77.PNG) 
How can I fix this issue?

**Comment by GetJiggyWitIt** [comment]
Also heres my config: 
[config.txt](https://github.com/lucko/LuckPerms/files/3232514/config.txt)

**Comment by Andre601** [comment]
This is an issue related to your chat-plugin and not LuckPerms.
Please ask in the [M.O.S.S. Discord](https://discord.gg/casfFyh) for support with EssentialsX and EssentialsXChat
