### ISSUE TITLE
LuckPerms isn't Showing Prefix

### ISSUE THREAD

**Issue by xd-Color** [lucko/LuckPerms#1558]
I have a BungeeCord server that runs LuckPerms on it. When I set a prefix for a group and added myself to the group, it shows the prefix in every single one of my servers except for my Skyblock server. I have no idea if this is because of a plugin I have or just an error I had in the console.

![Error](https://user-images.githubusercontent.com/43486893/58668124-9898d380-82fd-11e9-899c-a7251ec4fa1d.png)
![Plugins](https://user-images.githubusercontent.com/43486893/58668125-9898d380-82fd-11e9-99d2-3882d9924312.png)

Edit: My 1.14 Survival server is also having the same problem.

**Comment by Andre601** [comment]
Do you by any chance run a BungeeCord chat plugin like BungeeChat 2?
if not make sure that:
- [x] The end-server (Spigot) has LuckPerms, Vault and a Chat plugin supporting it install.
This seems to be the case for you.
- [ ] LuckPerms is connected to the same database to receive the groups, permissions and prefixes.

**Comment by xd-Color** [comment]
All of that is a check. They all sync across, as you can see it is coming through on my Skyblock server, it just isn't showing the prefix.

**Comment by ShiftingKill** [comment]
same
https://hastebin.com/raw/ayigefukol

**Comment by SimonOrJ** [comment]
Does the issue arise only in 1.14 servers? What chat plugin are you using to display the prefix?

**Comment by ShiftingKill** [comment]
Using LP to display prefixes for me and I'm on 1.14.2

**Comment by Turbotailz** [comment]
@shiftingkill Luckperms does not display prefixes, you need another plugin for that.

**Comment by xd-Color** [comment]
Every server of mine is 1.12.2 (including Skyblock), but my Survival server is 1.14.

**Comment by lucko** [comment]
Check the configuration of your chat formatting plugin on skyblock.

You can use `/lp user <user> info` to see if the prefix is correct, if it's correct there but not showing up in chat, it's a chat formatting plugin issue.
