### ISSUE TITLE
So uh... Patreon?

### ISSUE THREAD

**Issue by Dracathio** [lucko/LuckPerms#1559]
http://prntscr.com/nw3lyr

I put 2 dollars instead of 1 because why not? 

So it sadly didn't have the discord rank go through.

Dracathio#2739

Thanks for making this plugin man, it's a great help ^,..,^
Hope I can hide in the Patreon channel soon.

**Comment by Andre601** [comment]
Did you made sure you actually have your Discord account linked to Patreon?
Also the Issue-tracker is reserved for reporting bugs/searching help with the plugin LuckPerms.

**Comment by Dracathio** [comment]
Well... if it was easier to talk to him on discord I guess I wouldn't of done this.

Also http://prntscr.com/nw5v68 yea it's connected.  Patreon doesn't really work too well when you wish to give more than what is listed for tiers if something like a discord thing is involved.

Unless Patreon broke discord connection.

Last time I tried to message luck on discord it was just blocked because he has those who aren't friends blocked from being able to message.

and to be honest... since the patreon is connected to the luck perms discord, thus supporting the plugin in a way, it would be considered a bug if the patreon is messing up slightly.  That's just my view on that though.  but oh well, nvm.. I'll just close this and go on my way.

**Comment by Turbotailz** [comment]
@Dracathio I have pinged Luck in our staff channel to take a look at this for you :)

**Comment by lucko** [comment]
Hey, I've manually applied your tag. Thanks for your support!
