### ISSUE TITLE
Prefix does not work 1.7.10

### ISSUE THREAD

**Issue by Westus** [lucko/LuckPerms#156]
Thermos-1.7.10-1614-server
Plugins list:
- Essentials
- EssentialsChat
- LuckPerms-Bukkit-Legacy-2.17.39
- Vault-1.4.1.jar

default.json

```
{
    "name": "default",
    "perms": {
        "group.member": true,
        "prefix.1000.[Default] ": true
    }
}
```

member.json

```
{
    "name": "member",
    "perms": {
        "prefix.100.&7[Player] ": true,
        "test.*": true,
        "testt.*": true,
        "testtt.*": true
    }
}
```

[config.yml](https://gist.github.com/Westus/4ba87ef0bb3d0b8cd7b64c32bacb2518)

**Comment by Jamie4224** [comment]
Are you sure, Maybe first check if that function in essentials is enabled that adds prefixes and then try the chat again with this

**Comment by lucko** [comment]
https://github.com/lucko/LuckPerms/wiki/FAQ#im-using-essentialschat-and-its-not-working
