### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Domantas357** [lucko/LuckPerms#1560]
Hello i instaled https://www.spigotmc.org/resources/reportplus-bungeecord-☆-gui-☆-discord-☆-customizable-☆-titles-☆-discord-announcements-☆-and-more.50455/
this plugin and luckperms not work :) 

concole logs:
http://prntscr.com/nw5jj9
http://prntscr.com/nw5job

**Comment by BrainStone** [comment]
This is an issue with that other plugin not properly including a library. Report it to them

**Comment by Domantas357** [comment]
All said well on their side
Cat on your side is bad

**Comment by Turbotailz** [comment]
Bad kitty 😾

**Comment by Andre601** [comment]
This is not a LP issue.
Like BrainStone said is the cause a plugin that doesn't shade a library properly.
