### ISSUE TITLE
Permissions working for one user but not other

### ISSUE THREAD

**Issue by xWaffles** [lucko/LuckPerms#1562]
So basically, me and my friend are in the same group and have the same user permissions but my friend can break protected land and I can't break that protected land. We both have the permission to break the land in our group permissions but I can't break it

I'm using PlotSquared and the problem may be with that but I'm just checking if there is anything wrong with my LuckPerms.

**Comment by Turbotailz** [comment]
I'm going to suggest the protection is caused by PlotSquared and your friend just needs to trust you in their plot.

Otherwise you can always use LuckPerms' [verbose mode](https://github.com/lucko/LuckPerms/wiki/Verbose) to see if you are missing any permissions.

**Comment by xWaffles** [comment]
Nevermind... This isnt a luckperm issue... its to do with plotsquared or another plugin. I tried removing luckperms and oping my self and the issue is still there.
