### ISSUE TITLE
3 LP errors: luckperms-worker-6, luckperms-scheduler, background writer 1.14.2

### ISSUE THREAD

**Issue by kaniesha** [lucko/LuckPerms#1563]
3 luck perms errors:
Current Thread: luckperms-worker-6
MVStore background writer nio:/multicraft/servers/server4137/plugins/LuckPerms/luckperms-h2.mv.db
Current Thread: luckperms-scheduler
https://gist.github.com/kaniesha/177fff44dfd27cf0dc1b7091c45fd2d4

Server running: Paper spigot
Version: git-Paper-67
Minecraft version: 1.14.2

**Comment by lucko** [comment]
These aren't errors, just part of the crash log debugging message.
