### ISSUE TITLE
Transient resolution order not working properly on bukkit

### ISSUE THREAD

**Issue by bloodmc** [lucko/LuckPerms#1564]
LP Version: 4.4.26

https://github.com/lucko/LuckPerms/blob/master/sponge/sponge-service/src/main/java/me/lucko/luckperms/sponge/service/model/ResolutionOrder.java#L38-L41

Persistent permissions set on the default type should have higher priority than transient permissions. This works perfectly fine on Sponge side with LuckPerms but does not work at all with LP Bukkit. Without this feature, GriefDefender default permissions do not work as expected.

zml2008 changed this years back when I requested it for PEX

https://github.com/PEXPlugins/PermissionsEx/commit/a8da1bd0df447bc13eaf119cc60e3b5d9f10d328

**Comment by lucko** [comment]
LP Bukkit has no concept of a default subject.

**Comment by bloodmc** [comment]
https://github.com/lucko/LuckPerms/wiki/Default-Groups

The default group is serving the same purpose as sponge’s default subject. All users are part of the default group which is what GriefDefender uses to set defaults.

**Comment by Andre601** [comment]
The default group is just that: A group.
It doesn't apply any permissions on its own (at least not in bukkit/spigot)
It is just a group every player gets.

**Comment by bloodmc** [comment]
I never stated it set permissions on its own. My plugin sets ‘default’ transient permissions on the default group which all users inherit since they are part of the group. The problem is when I set a persistent permission on the default group. The persistent permission should have higher priority than the transient permission.

**Comment by lucko** [comment]
In general, transient has more "priority" than persistent across the board in LuckPerms.

The special case for Sponge default subjects in LP was added at your request many months ago, but I'm not so sure about doing the same for LP's default group subject.

**Comment by bloodmc** [comment]
@lucko zml added the change to PEX core in 2016 which affects both Bukkit and Sponge. Servers are still using PEX so I would only predict that the setting is fine. We also all agreed it made sense for the default group. Currently, I am handling this myself within GriefDefender but I would prefer if LP handled it.

**Comment by bloodmc** [comment]
@lucko Would you be able to add a setting I could hook into to force default group to check persisted before transient?

**Comment by lucko** [comment]
Yes, working on this for API 5

**Comment by lucko** [comment]
This has been added into the v5 API.

See

* [net.luckperms.api.query.dataorder.`DataQueryOrder`](https://github.com/lucko/LuckPerms/blob/master/api/src/main/java/net/luckperms/api/query/dataorder/DataQueryOrder.java)
* [net.luckperms.api.query.dataorder.`DataQueryOrderFunction`](https://github.com/lucko/LuckPerms/blob/master/api/src/main/java/net/luckperms/api/query/dataorder/DataQueryOrderFunction.java)
