### ISSUE TITLE
Error with joining (bukkit)

### ISSUE THREAD

**Issue by Zizoska** [lucko/LuckPerms#1566]
Hey, today i instaled luckperms, but when i want to join the server it says >[2K [19:02:57 INFO]: com.mojang.authlib.GameProfile@1f53c91[id=658df945-9c6a-30c3-a3e2-6a7aa1da7493,name=Zizoska,properties={},legacy=false] (/) lost connection: §7§l[§b§lL§3§lP§7§l] §cPermissions data for your user was not loaded during the pre-login stage - this is likely due to a conflict between CraftBukkit and the online-mode setting. Please check the server console for more information. 
>[2K [19:03:07 WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2319ms behind, skipping 46 tick(s) 

>Please help

**Comment by Andre601** [comment]
Read the error. It clearly mentions what the issue is (In your case using CraftBukkit in offline mode)

**Comment by ArlanDiscord** [comment]
You can see in the https://luckperms.net/wiki/Installation#craftbukkit-and-offline-mode
Wikipedia for a problem
