### ISSUE TITLE
My server keeps lagging and crashing due to unknown error

### ISSUE THREAD

**Issue by CookieKenneth** [lucko/LuckPerms#1568]
Hello,

My server freezes and eventually crashes and the console is spammed with [these messages](https://hastebin.com/pavunonojo.shell). What seems to be the problem?

Luck Perms Version: 4.4.1
Mc Version: 1.12.2

**Comment by Imortalshard** [comment]
Hi CookieKenneth,

Have a read of:
https://github.com/lucko/LuckPerms/wiki/Storage-system-errors#mysql-no-operations-allowed-after-connection-closed-error

That should help resolve the error. 

Thanks.
