### ISSUE TITLE
Postgresql support

### ISSUE THREAD

**Issue by LartyHD** [lucko/LuckPerms#1569]
Can you add postgresql support please?

**Comment by LartyHD** [comment]
I see it is implementet [postgresql.sql](https://github.com/lucko/LuckPerms/blob/master/common/src/main/resources/me/lucko/luckperms/schema/postgresql.sql) but why is it not on the LuckPerms comparison picture on Spigot?

**Comment by BrainStone** [comment]
Because that picture is outdated.

**Comment by LartyHD** [comment]
ok, thx for the answer @BrainStone
