### ISSUE TITLE
yaml does not work 1.7.10

### ISSUE THREAD

**Issue by Westus** [lucko/LuckPerms#157]
Thermos-1.7.10-1614-server

Plugins list:

- Essentials
- EssentialsChat
- LuckPerms-Bukkit-Legacy-2.17.39
- Vault-1.4.1.jar

admin.yml

```
name: admin
perms: {}
```

Command:
/lp group admin permission set test.test

Server response:
Set test.test to true for admin

Command
/lp group admin permission set test.testt

Server response:
Group could not be fond.

admin.yml

```
name: admin
perms:
  test.test: null
```

**Comment by lucko** [comment]
Server log please.

**Comment by Westus** [comment]
https://gist.github.com/Westus/e610092d1e797b81f65521ed750d3f89

**Comment by lucko** [comment]
Please delete the admin.yml file & try again. :)

**Comment by Westus** [comment]
https://gist.github.com/Westus/e71fd47bda96b271b7563dfd6b678302

**Comment by lucko** [comment]
Cannot reproduce locally.
![](http://i.imgur.com/eyJNUbO.png)

What does the file look like once you've tried adding something to it?

**Comment by Westus** [comment]
Try my assembly. It already has a fixed [CyberdyneCC/Thermos#498 (comment)](https://github.com/CyberdyneCC/Thermos/issues/498#issuecomment-247083549). From the first time it starts. [link](https://www.mediafire.com/?yc2i22bhre73ea7)

**Comment by lucko** [comment]
Nop, doesn't load.

http://i.imgur.com/r5pAqFO.png

**Comment by Westus** [comment]
Try again. For some reason, it can not run the first time.

**Comment by lucko** [comment]
Your server software is packaging a very old version of SnakeYAML. (a 6 year old version, to be exact)

So, in the same manner that you have to update SpecialSource, you need to update SnakeYAML.

Navigate to `/<server root>/libraries/org/yaml/snakeyaml/1.9`
Replace `snakeyaml-1.9.jar` with the file found here.
[https://repo1.maven.org/maven2/org/yaml/snakeyaml/1.17/snakeyaml-1.17.jar](https://repo1.maven.org/maven2/org/yaml/snakeyaml/1.17/snakeyaml-1.17.jar)

Obviously you'll need to rename it in the same manner as you did for SpecialSource.
