### ISSUE TITLE
permission luckperms.* does not exist with 1.13+

### ISSUE THREAD

**Issue by VanillaChan6571** [lucko/LuckPerms#1570]
permission luckperms.* does not exist with 1.13+ resulting the user unable to use /lp anything making this completely useless for owners as admins could just right them self as owners. And No I am not turning off ops as some plugins and command blocks are needed for op.

**Comment by Turbotailz** [comment]
That doesnt seem right. Are you sure the plugin just hasn't loaded correctly? Did you check the console logs during start up to see if everything is working correctly?

**Comment by VanillaChan6571** [comment]
> That doesnt seem right. Are you sure the plugin just hasn't loaded correctly? Did you check the console logs during start up to see if everything is working correctly?

Never mind I found out that you need to force stop the server for this to apply. (Exiting the Server Forcefully for some reason stopping and starting it doesn't work.) Which is weird, Assuming 1.14 bug with paper. Thanks for the great plugin anyways <3

**Comment by ktole1999** [comment]
once you made the perm change did you reload perm command and /lp sync

**Comment by Andre601** [comment]
Some permissions require you to update the cache which is done by either reconnecting to the server or switching the world...
This shouldn't be the case any longer tho since there was a change way back that made LP auto-update the cache after changes were made to permissions... Not sure tho.
