### ISSUE TITLE
Error with mysql

### ISSUE THREAD

**Issue by Zeusox** [lucko/LuckPerms#1571]
I have a server with a minigame that when finished, the server restarts
The thing is that I installed luckperms with mysql and everything worked fine until I rebooted the server and now it does not let me enter
![2019-06-11_08 44 43](https://user-images.githubusercontent.com/47507230/59278820-54280480-8c28-11e9-8e4c-d01cc8897015.png)

**Comment by Andre601** [comment]
[Storage system errors]: https://github.com/lucko/LuckPerms/wiki/Storage-system-errors

Please actually check the console of the server for the error and see if it is listed in the [Storage system errors] page.
