### ISSUE TITLE
MySQL problem

### ISSUE THREAD

**Issue by vincevd1** [lucko/LuckPerms#1573]
I setup a MySQL database today to sync LuckPerms groups and permissions over my network, I have 5000 as the max_connections but when launching my servers luckperms still gives an error that all the connections have been used. The database worked for about 3 hours before I got this error.

**Comment by vincevd1** [comment]
I got more info on the issue: When I connect my bungeecord server and 1 spigot server it takes up 66 of the max 5000 threads, once I connect up another spigot server it says the max_connections have been exceeded

**Comment by BrainStone** [comment]
@vincevd1 did you check the config or the live MySQL server for the value of max connections?

These values can be changed at runtime and so the config value is not reliable. Also changing that value from config requires a restart of the MySQL server.

And lastly if you're using MariaDB (an improved version of MySQL and the default for many newer linux systems (even when installing "MySQL", they install MariaDB instead (It's 99.9% compatible))) it's possible, that you're changing the value in the wrong config. MariaDB has several configs. And I'm never sure which one it actually uses, so be sure to look around. There should be at least two almost identical configs. Make sure they are identical.

**Comment by vincevd1** [comment]
I checked the live max_connections, I rent my minecraft servers from a hosting company, they supply a free MySQL database with every server, so I don't use MariaDB, and 5000 max connections are set as default (I checked in the PHPMyAdmin control panel.

**Comment by BrainStone** [comment]
Then you need to contact your hoster.

**Comment by vincevd1** [comment]
To higher the max_connections? It's on 5000 I don't think it should be any higher

**Comment by BrainStone** [comment]
No to help you debug what's the issue.  
One server doesn't create several thousand connections.

It's possible that they have a lower limit on the server than on your account.

**Comment by vincevd1** [comment]
Ah yea that could be it

**Comment by vincevd1** [comment]
Fixed, the issue was that "max_user_connections" was on 30 thanks for your help!

**Comment by BrainStone** [comment]
You're very welcome
