### ISSUE TITLE
DisplayName not displaying

### ISSUE THREAD

**Issue by blacky62** [lucko/LuckPerms#1574]
Hello ! I have LuckPerms 1.12.2 with VaultChatFormatter but the displayname isn't working.

**Comment by Turbotailz** [comment]
Do you mean display name, or prefix/suffix? Because these are both entirely different things.

**Comment by Andre601** [comment]
Also 1.12.2 is the server version, **not** the LP version

**Comment by blacky62** [comment]
I mean displayname.. I don't know how to set prefixes/suffixes..

**Comment by blacky62** [comment]
And the version of luckperms is: 
LuckPerms-Bukkit-4.4.1

**Comment by Andre601** [comment]
VaultChatFormatter doesn't change the displayname of the player. It is only for adding prefixes and suffixes and for basic chat formatting (setting colours)

You need another plugin like EssentialsX and EssentialsXChat to display the displayname.

**Comment by Turbotailz** [comment]
The wiki is your friend: https://github.com/lucko/LuckPerms/wiki/Prefixes,-Suffixes-&-Meta

**Comment by blacky62** [comment]
Ok i Will set the prefix when i'm back To my home. I Will inform you for the advencement

**Comment by blacky62** [comment]
Ok it's working ! Thank you for the support !
