### ISSUE TITLE
MySQL spam in console?

### ISSUE THREAD

**Issue by Telesphoreo** [lucko/LuckPerms#1575]
Pastebin here:
https://pastebin.com/1AQfaTPJ

On LuckPerms 4.4.26 with Paper 1.14.2 b-82.
Using MySQL. Everything is working and setup but I get this spam in the console.

Server startup log if you need it: https://pastebin.com/RnSmmv5m
No errors AFAIK

**Comment by Andre601** [comment]
Check the storage error page on the wiki.
Issue right after the SSL one

**Comment by Telesphoreo** [comment]
That fixed it, thanks
