### ISSUE TITLE
MysqlSpam on external server

### ISSUE THREAD

**Issue by tacticalpidgeon** [lucko/LuckPerms#1576]
Despite having the configs set as per the wiki `  useSSL: false` and `verifyServerCertificate: false` still gives the console spam 

Server: 
Paper on 1.13.2-R0.1-SNAPSHOT
LP Version: LuckPerms 4.4.26

> [09:33:06] [Server thread/WARN]: Fri Jun 14 09:33:06 BST 2019 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.

**Comment by BrainStone** [comment]
Do you have other plugins using MySQL?

**Comment by tacticalpidgeon** [comment]
i have a few, i've even tried using a staging server with just luckperms installed, and same issue occurs

**Comment by BrainStone** [comment]
Then my guess would be that you put the config values incorrectly. Can you post the  config of your staging server (without IPs and PWs)?

**Comment by tacticalpidgeon** [comment]
https://pastebin.com/sGsmy2D2 - here is my configuration file

**Comment by lucko** [comment]
Hm that looks ok to me.

Not sure what to suggest, the error is being thrown by the MySQL driver, so I can't really advise why it's happening or how to debug further.

Sorry, but his isn't a LP issue, and therefore not something I can really help with.
