### ISSUE TITLE
[Suggestion] Custom JDBC

### ISSUE THREAD

**Issue by MrFishCakes** [lucko/LuckPerms#1577]
Allow people to customise the a JDBC URL or at least add their own flags to to them seen in plugins such as LiteBans and PremiumVanish.

**Comment by lucko** [comment]
Already possible.

https://github.com/lucko/LuckPerms/blob/ffe6c24b53e75af2aa94def451c183795026fd36/bukkit/src/main/resources/config.yml#L135-L138
