### ISSUE TITLE
Need help cinfiguring LuckPerms with Deluxe Chat

### ISSUE THREAD

**Issue by huskerfan49** [lucko/LuckPerms#1578]
I just got deluxechat to have my luckperms pfrefixes show in chat, what do I type in chat using hte luckperms plugin to add prefixes to DeluxeChat?

**Comment by BrainStone** [comment]
You can already do that. At least add flags to the URL. The pool-settings have a section called properties. Add whatever you want. They are added directly to the URL

**Comment by lucko** [comment]
I think Brainstone's response above was meant for another issue. ;)

To answer your question, you need to use the addprefix command.

https://github.com/lucko/LuckPerms/wiki/Prefixes,-Suffixes-&-Meta
