### ISSUE TITLE
Logger not found on Nukkit

### ISSUE THREAD

**Issue by TrainmasterHD** [lucko/LuckPerms#1579]
LuckPerms throws me this error while loading. I'm using the latest version of LuckPerms and NukkitX.

https://hastebin.com/enurajisom.java

**Comment by lucko** [comment]
Your paste is empty for me!

**Comment by TrainmasterHD** [comment]
No text on the page? If yes, here is another link: https://pastebin.com/eaJDRK0s

**Comment by lucko** [comment]
Apologies for the delay, this is now fixed.
