### ISSUE TITLE
I have a problem with activate Redis

### ISSUE THREAD

**Issue by jimmy57000** [lucko/LuckPerms#158]
Good evening everyone! 
I currently have a problem that I activate Redis on LuckyPerms my API which also uses Redis this my in error (Error: http://pastebin.com/nn3r6BTj) 

It's been 3 days since I search for my I do not find

Thanks you!

**Comment by lucko** [comment]
Make sure you're packaging the newest Jedis version in your plugin. Seems like there's an issue there?

**Comment by jimmy57000** [comment]
Could you give me the redis version you used for LuckyPerms? :)

Thanks!

**Comment by lucko** [comment]
Ah yeah. I just realised, this is a LuckPerms issue.

I shade this version.
https://github.com/lucko/jedis/releases/tag/jedis-2.9.0-shaded

I'll fix that when a get a chance. (probably tomorrow)

**Comment by jimmy57000** [comment]
I tried to update it in my API
I think the connection system needs to change ..

I get an error in my code! (http://prnt.sc/e2vk2z)
I would probably do with my developer to look at my API :)

Thanks :)

**Comment by lucko** [comment]
Should be fixed in this build. 
https://ci.lucko.me/job/LuckPerms/41/

Let me know if you have any further issues.
