### ISSUE TITLE
NullPointerException: permission

### ISSUE THREAD

**Issue by Demeng7215** [lucko/LuckPerms#1580]
My plugin is making LuckPerms produce an NPE. All it says is "permission". I have debugged and confirmed that the permission is not null.
The permission nodes are:
rankgrantplus.grant
custom.permission

Could it be possible that custom.permission might produce an NPE because it doesn't start with the plugin name?

**Comment by lucko** [comment]
What's the full stack trace?

**Comment by Demeng7215** [comment]
https://pastebin.com/DqyuevzF

RankGrant+ is at https://github.com/Demeng7215/RankGrantPlus
