### ISSUE TITLE
Error dispatching event PlayerDisconnectEvent

### ISSUE THREAD

**Issue by andrewkm** [lucko/LuckPerms#1582]
I keep getting this everytime I "end" the waterfall instance.
Water - 284
LuckPerms - 4.4.26

Just recently started, no idea why it continues to happen.
https://pastebin.com/raw/YAVkALRz

**Comment by lucko** [comment]
Not really something LuckPerms can fix.

It seems like Bungee/Waterfall is shutting down the scheduler, and then continuing to fire disconnect events. Ideally (and presumably in the past), these have happened the other way around.
