### ISSUE TITLE
Info about meta - dont use colors

### ISSUE THREAD

**Issue by Iwitrag** [lucko/LuckPerms#1583]
**FEATURE SUGGESTION**

When showing information about metas, it would be great to actually NOT format them and use color codes instead...

Usually I need to see raw meta (like group prefix) to use it elsewhere (e.g. NameTagEdit) without remembering all color codes...

So instead of

> admin's prefixes
> -> 100 - '[admin]'  (prefix is showing in dark red)

it would show

> admin's prefixes
> -> 100 - '&4[admin]'

**Comment by Tobi406** [comment]
You can see the prefixes in a permission like format in the web editor. Without color codes parsed, it would eg. show `prefix.100.&4[admin]`.

**Comment by Andre601** [comment]
Also from what I can remember can you just hover over the prefix/Suffix to see the raw format itself.

**Comment by lucko** [comment]
Basically ^, yeah.

You can hover to see the raw format, or use the web editor.
