### ISSUE TITLE
MySQL error

### ISSUE THREAD

**Issue by Zeusox** [lucko/LuckPerms#1585]
I have a server (bungee) where you must restart a minigame at the end of a game.
What happens is that I put luckperms on all servers and connected it to MySQL and I receive this error on that server.
![received_448461295971078](https://user-images.githubusercontent.com/47507230/59818679-75ed4f80-92ea-11e9-84f0-3c78ce324f6a.png)

**Comment by Tobi406** [comment]
Can you provide logs of the server you're trying to connect to?

**Comment by Zeusox** [comment]
Ready

![Screenshot_20190620-085028](https://user-images.githubusercontent.com/47507230/59854522-b5428d00-9338-11e9-8551-ee4c7f8bec74.png)
![Screenshot_20190620-085040](https://user-images.githubusercontent.com/47507230/59854539-bd9ac800-9338-11e9-9d23-2d80c47c30f4.png)

**Comment by Zeusox** [comment]
![Screenshot_20190620-085129](https://user-images.githubusercontent.com/47507230/59854781-2c782100-9339-11e9-8da5-1a054c26914c.png)
![Screenshot_20190620-085138](https://user-images.githubusercontent.com/47507230/59854792-31d56b80-9339-11e9-923e-dcebdbb9c16a.png)

**Comment by Zeusox** [comment]
![Screenshot_20190620-085146](https://user-images.githubusercontent.com/47507230/59854812-3ac63d00-9339-11e9-9d9f-d1d605d8bd11.png)
![Screenshot_20190620-085152](https://user-images.githubusercontent.com/47507230/59854824-3f8af100-9339-11e9-894b-8c909391e6ac.png)

**Comment by Andre601** [comment]
Please provide the **logs** as Tobi asked you to do.
Those screenshots are pretty much unreadable.

**Comment by Zeusox** [comment]
https://paste.helpch.at/calahirota.sql

**Comment by lucko** [comment]
Issue is with your MySQL server, not LuckPerms.

```
 message from server: "Host 'Ip' is blocked because of many connection errors; unblock with 'mysqladmin flush-hosts'"
```
