### ISSUE TITLE
Language does not change! LuckPerms

### ISSUE THREAD

**Issue by DamageAsh** [lucko/LuckPerms#1587]
I copy the file "lang.yml" and put mods> luckperms and reboot the server, but it does not replace the pl language!

**Comment by reaktiv** [comment]
I have the same problem. Version 4.4.26 for Sponge

**Comment by Tobi406** [comment]
Are there any errors in the console on startup?

**Comment by reaktiv** [comment]
There are no errors in the console. I put the translation in the / luckperms folders and in the config / luckperms and the translation as a whole began to work as seen in the screenshot, but the translation of the message about insufficient rights to the command does not work.
![Безымянный](https://user-images.githubusercontent.com/3639233/59976214-dbcb2700-95c9-11e9-82e6-a5d1d0965136.jpg)

**Comment by lucko** [comment]
That message isn't being sent by LuckPerms, so isn't affected by LP's locale file.
