### ISSUE TITLE
Please convert my permissions.yml from pex to luckperms

### ISSUE THREAD

**Issue by eero619** [lucko/LuckPerms#1589]
For me it dosent work or i dont know how please help me.

[permissions.zip](https://github.com/lucko/LuckPerms/files/3313665/permissions.zip)

**Comment by Imortalshard** [comment]
Hi eero619,

Please take a read of the page i've linked below, it will explain how to migrate your permissions from PermissionsEx to Luckperms.

https://github.com/lucko/LuckPerms/wiki/Migration

Thanks,
Imortalshard.
