### ISSUE TITLE
Prefix properly imported into mysql

### ISSUE THREAD

**Issue by Westus** [lucko/LuckPerms#159]
Thermos-1.7.10-1614-server
Plugins list:
- LuckPerms-Bukkit-Legacy-2.17.46
- EssentialsX-2.0.1
- EssentialsXChat-2.0.1
- EssentialsXGeoIP-2.0.1
- EssentialsXSpawn-2.0.1
- Vault-1.4.1

I configure permissions and prefixes in yaml. But after you import the file into mysql prefixes stopped check.

![2017-02-02_7-15-15](https://cloud.githubusercontent.com/assets/4818769/22537194/56dbb3fc-e919-11e6-89c4-15401d2dc278.png)
![2017-02-02_7-17-17](https://cloud.githubusercontent.com/assets/4818769/22537195/5aa85a94-e919-11e6-9eac-d9061264049d.png)

[fml-server-3.txt](https://github.com/lucko/LuckPerms/files/746829/fml-server-3.txt)

**Comment by lucko** [comment]
Thanks for reporting :)
