### ISSUE TITLE
Luck Perms MySQL Database Issue

### ISSUE THREAD

**Issue by korra2** [lucko/LuckPerms#1591]
Hello,
So I am trying to connect to a MySQL database that my permissions are all saved on. All my other servers are connected to this database and work, but this one server does not appear to be connecting. I tried updating the plugin, I tired re-installing it completely, and I am not quite sure what else I can do. Recently my server was terminated by the host by mistake, but they recovered it onto a different server with a new IP address. In essence, it is the same server with a new ip and port. I am not sure if this is the problem because before the server was terminated it was using this database. Here is the error code I keep getting: https://pastebin.com/EXXetZwe. 

Thank you!

**Comment by Imortalshard** [comment]
Hi Korra2,

See if you can fix the issue with some of the things mentioned on this page. 

https://github.com/lucko/LuckPerms/wiki/Storage-system-errors#luckperms-cannot-connect-to-my-mysql-server

**Comment by korra2** [comment]
I found the issue. It had to do with the host.

Thanks
