### ISSUE TITLE
Update Russian translation

### ISSUE THREAD

**Issue by DarkFort** [lucko/LuckPerms#1592]
Update Russian translation - https://pastebin.com/g0cJ144w

**Comment by Tobi406** [comment]
Might be a better idea to create a issue / pull request on the [LuckPerms/locale](https://github.com/LuckPerms/locale) repository

**Comment by DarkFort** [comment]
I do not know how to do that

**Comment by lucko** [comment]
Thanks

https://github.com/LuckPerms/locale/commit/f7d719e97cdc8380e9f1ab06e845410c79c2db70
