### ISSUE TITLE
PrisonRanksX

### ISSUE THREAD

**Issue by omgitsAngus** [lucko/LuckPerms#1595]
I'm trying to switch ranks plugin to get one that works better with luck perms so players do not have their ranks cleared, however others ones i've tried don't seem to really work. For example I tried PrisonRanksX and it just throws this huge error: https://pastebin.com/AfYB6sNW
Any idea of a plugin that is compatible/recommended? These other plugins work with PeX..

**Comment by Tobi406** [comment]
Seems more like a problem with PrisonRanksX

**Comment by omgitsAngus** [comment]
Ok i'll keep trying

**Comment by lucko** [comment]
I've heard EzRanksPro is good, but never used it myself. Sorry, nothing else to suggest!
