### ISSUE TITLE
Per server permissions not working

### ISSUE THREAD

**Issue by EnderdragonJEM** [lucko/LuckPerms#1597]
Hello. My server has been using LuckPerms for around a week now. In the first few days it was going fine, but in the last 3ish days I have had a problem with per server permissions. I have set per server permissions and they are not working. 

e.g.1 "/lp user <player> set <permission> <servername>" does not work.
e.g.2 "/lp user Syncinating set <permission>" works fine.

**Comment by Imortalshard** [comment]
Hi EnderdragonJEM,

For per server permissions to work, you need to make sure you have set the server name option in the Luckperms config, on all servers, to the correct server name. Then when you are setting the permissions you do `/lp user|group <name> permission set <permission node> true|false server=<servername>`. 

Note:
You can also add the server=<servername> when you're adding groups to users or other groups, and when you're adding prefixes and other meta options as well.

Thanks,
Imortalshard

**Comment by EnderdragonJEM** [comment]
I have left that setting to the default setting. here is the setting https://pastebin.com/1MgHN75m

**Comment by Tobi406** [comment]
You need to simply change that setting.
Eg. if you want to do `/lp user|group <name> permission set <permission node> true|false server=survival` you would need to change that setting to `server: survival`, but just on the server(s) you want to have permissions with that servername working.

**Comment by EnderdragonJEM** [comment]
That fixed it. Thank you all very much
