### ISSUE TITLE
LuckPerms hangs when shutting down server

### ISSUE THREAD

**Issue by wrecktify** [lucko/LuckPerms#1598]
Issue happens on spigot 1.14.2 and LuckPerms-Bukkit-4.4.26

Server hangs during shutdown process after saying Goodbye!

This causes the world to not save on shutdown because I have to kill the server process to get it to shut down.  

No error message or indication what is causing the hangup.

Plugins (13): LuckPerms, dynmap, FoundDiamonds, WorldEdit, PhantomSMP, LogBlock, HolographicDisplays, Vault, FarmLimiter, WorldGuard, Essentials, EssentialsGeoIP, EssentialsChat

**Comment by Tobi406** [comment]
I don't think LuckPerms is the plugin that makes that, does it still happen when you remove LuckPerms?

**Comment by wrecktify** [comment]
Ok, I will do more extended testing by removing plugins on a test server and report back to confirm it is or isn't luckperms.

**Comment by lucko** [comment]
Assuming this ended up being caused by something else? :p
