### ISSUE TITLE
Continuous error with plugin

### ISSUE THREAD

**Issue by omgitsAngus** [lucko/LuckPerms#1599]
https://pastebin.com/fZHG1dtz

What file is causing this error? it happens every time someone changes ranks which is a lot. How do I fix it

**Comment by omgitsAngus** [comment]
The plugin is functioning so bad for me for some reason I can't use the notify log to see what's causing all the issues for players on the server. Their ranks are not being removed properly when ranking up...

**Comment by electronicboy** [comment]
You have a corrupted action logger file, I'd suggest stopping the server and deleting it

**Comment by omgitsAngus** [comment]
I'm unsure what this "action logger file" is or looks like @electronicboy, which file should I delete?

**Comment by lucko** [comment]
The `actions.json` file. :)
