### ISSUE TITLE
Thermos 1.7.10 Load Error

### ISSUE THREAD

**Issue by Firestar311** [lucko/LuckPerms#16]
I get a class not found exception when I try to load your plugin on Thermos for 1.7.10 Forge. 
It works just fine in 1.10.2

**Comment by lucko** [comment]
There's a special Bukkit legacy build on the CI server. Use that jar, it has some extra shaded libs that aren't included in older Bukkit builds.

**Comment by lucko** [comment]
Assuming you sorted it. If not, feel free to re-open this.
