### ISSUE TITLE
No permissions but with permissions.

### ISSUE THREAD

**Issue by Yronusa2000** [lucko/LuckPerms#1602]
![image](https://user-images.githubusercontent.com/52044171/60291497-44dcd280-991b-11e9-8417-99ba7b7dcc26.png)

Even if I have a permission, well I can't use it. I'm using Luckperm last release and imported the permissions files with /lp export and /lp import from my skyblock server (where everything is okay). 
That's the only permission plugin i'm using, there is no issues in console. 
When i'm OP, there is no problem, and yes I have the default group.

Thanks you in advance 👍

**Comment by Imortalshard** [comment]
Hi Yronusa2000,

You can try out the verbose feature to see if there are any missing or incorrectly typed permissions that are required for the command(s) to work. 

https://github.com/lucko/LuckPerms/wiki/Verbose

**Comment by Yronusa2000** [comment]
Hi, thanks you, but this isn't the issue. I have the permission, as you can see in the Screenshot. But whatever: I just can't use it without OP.

**Comment by lucko** [comment]
The steps you need to resolve this issue are here:

https://github.com/lucko/LuckPerms/wiki/Installation#essentials

:)

**Comment by Yronusa2000** [comment]
This is not an issue from Essentials. Try what you said & even remove essentials but that's still the same.

**Comment by ktole1999** [comment]
what mods and versions are being used?

**Comment by Yronusa2000** [comment]
I'm under a spigot 1.12.2 server. 

Here's my plugin list ^^ : 

![image](https://user-images.githubusercontent.com/52044171/62381462-d0b1d200-b54b-11e9-95f4-74c4612ff3ea.png)

**Comment by Yronusa2000** [comment]
Okay so, I did a lot of test and I conclude this is a bukkit permission priority bug. Have you heard anything like that ?

**Comment by Yronusa2000** [comment]
Fixed! thanks for all
