### ISSUE TITLE
LuckPerms-Bungee YAML Issue

### ISSUE THREAD

**Issue by JordanPlayz158** [lucko/LuckPerms#1603]
So the LuckPerms Bungee config.yml file isn't working it showed in the logs and also in [YAML Validator](http://www.yamllint.com/). So all i need to known is how to fix the config file, this is the default config file other than changing it to MariaDB and putting in the correlating MariaDB database login information.

BungeeCord Proxy Log: https://pastebin.com/MGybw2dF
LuckPerms Config YAML: https://pastebin.com/iTfAYZLy

**Comment by Andre601** [comment]
You made a basic yaml error:
Using `:` without quotes.
Yaml doesn't like it that much when you use collons in values, because it mostly sees as new sections.

Change `localhost:<port>` to `'localhost:<port>'`

**Comment by JordanPlayz158** [comment]
k i'll try that out because the YAML Validator didn't tell me how to fix it just shows the output, do you know any good YAML resolvers (tells you the issues to fix the yaml because it pointed to address not localhost).

**Comment by lucko** [comment]
The issue is that you have a hashtag `#` character in your MySQL password.

Try wrapping the password in double quotes `" "`.

**Comment by JordanPlayz158** [comment]
Lol Some Dude Tried To Hack Me With That Database Info But I Changed It A Long Time Ago XD
