### ISSUE TITLE
Bulkupdate question

### ISSUE THREAD

**Issue by LogGits** [lucko/LuckPerms#1604]
Confused on how to use bulkupdating. Chatcontrol changed their perms from `chatcontrol.commands.x` to `chatcontrol.command.x`. Is there a way to update all player permission? (players have individual perms for chatcolours)

Is it possible to change those perms using bulkupdate? I just need to change the all instances of `chatcontrol.commands.x` to `chatfcontrol.command.x`where `x` is the command name.

**Comment by Imortalshard** [comment]
Hi LogGits

You can use bulkupdate like so:

`lp bulkupdate users update permission <new permission> "permission == <old permission>"`

EXAMPLE:

`lp bulkupdate users update permission chatcontrol.command.x "permission == chatcontrol.commands.x"` This will update all users who have the permission `chatcontrol.commands.x` and change it to `chatcontrol.command.x`.

NOTE: Remember you have to run the command in the console and use the confirmation command the console gives you.

**Comment by Andre601** [comment]
I don't think this would work for all permissions in __one command__ @imortalshard 
@LogGits wants to update all appearances of `chatcontrol.commands.<identifier>` to `chatcontrol.command.<identifier>` preferably with one command but bulk edit doesn't have support for placeholder values.
