### ISSUE TITLE
UltraPermissions Support (API Included!)

### ISSUE THREAD

**Issue by raimuakuna** [lucko/LuckPerms#1605]
Please add support to transfer from uPerms to LuckPerms.

https://raimu.tried-to-do.science/i/wthsgqh3.png is a screenshot from the owner of uPerms saying how to use their API.

**Comment by BrainStone** [comment]
This has been brought up before. The issue being that the author of UltraPerms doesn't understand why the API needs to be public. And since it is not, it won't happen.

**Comment by Andre601** [comment]
This is easier said than done.
The UltraPermissions API is not a public thing like BrainStone said and afaik do you need to purchase the plugin in order to actually get access to the API.
So as long as the API won't be made public, the migration can't be added.

**Comment by lucko** [comment]
^
