### ISSUE TITLE
Prefix doesn't show correctly.

### ISSUE THREAD

**Issue by sharcoth** [lucko/LuckPerms#1607]
I tried setting the title of my knight rank as [Sir] by issuing the command. /lp group ritter meta addprefix 1 "&c[Sir]". Should work correctly; however, it displays like in the attached image. How do I fix this and make it display normally?

![git](https://user-images.githubusercontent.com/52472602/60551506-4e31ba80-9ce0-11e9-970d-302078b26a3b.JPG)

**Comment by Tobi406** [comment]
Looks more like a problem with the format of your chat plugin

**Comment by sl4w** [comment]
I'm also having this issue. I know it's not a luckperms issue though, hoping someone could help out with this anyway though!
I'm using essentialsx, and the chat part of the config looks like this.

 # Chat formatting can be done in two ways, you can either define a standard format for all chat.
  # Or you can give a group specific chat format, to give some extra variation.
  # For more information of chat formatting, check out the wiki: http://wiki.ess3.net/wiki/Chat_Formatting
  # For EssentialsX changes, take a look at the EssentialsX wiki: https://github.com/EssentialsX/Essentials/wiki

  # format: '<{DISPLAYNAME}> {MESSAGE}'
  #format: '{DISPLAYNAME}&7:&r {MESSAGE}'
  #format: '&7{PREFIX}&r {DISPLAYNAME}&r &7{SUFFIX}&r: {MESSAGE}'

  group-formats:
  #  Default: '{WORLDNAME} {DISPLAYNAME}&7:&r {MESSAGE}'
  #  Admins: '{WORLDNAME} &c[{GROUP}]&r {DISPLAYNAME}&7:&c {MESSAGE}'

  # If you are using group formats make sure to remove the '#' to allow the setting to be read.




Sorry by the way, bit of a new comer at this and I'm struggling to find an answer anywhere as I guess it's a simple answer.

**Comment by equalent** [comment]
You should ask these kinds of questions somewhere else (for example on Spigot forums).
For LuckPerms prefix is simply a permission node and LP has nothing to do with prefixes being displayed.

Uncomment (remove `#`) the `format` line in `config.yml` of EssX and change the value. You should use predefined variables like `{PREFIX}` or `{DISPLAYNAME}` along with formatting codes and other characters to make chat look exactly the way you want it.
