### ISSUE TITLE
Players being promoted to highest group

### ISSUE THREAD

**Issue by MsDemonicRaven** [lucko/LuckPerms#1608]
Hello.
So i have 2 tracks. one is player with (IN ORDER) default, peasant, dweller, and civilian. the 2nd one is a betatest track with (IN ORDER) founder and beta. i am trying to give one of my players the betatest track. its working, however it is promoting them on the player track all the way to civilian. he is only supposed to be at peasant. why is this happening????

**Comment by Andre601** [comment]
Please provide more information like what command(s) you have used, where you used them (console or in-game) and if you or perhaps a plugin performed those commands.

**Comment by MsDemonicRaven** [comment]
i have used /lp user <player> group set founder. i used it in game. and its only luckperms that uses the groups. i just tried it on my superadmin, and it gave him civilian. so his tags are [duke][civilian] but i just want him to have duke.

**Comment by MsDemonicRaven** [comment]
in the config, the stacking is "highest_on_track_staff" "highest_on_track_player".

**Comment by BrainStone** [comment]
Add duke to the staff track. Or if you don’t want that, create a helper track that contains all player ranks and staff ranks (or just duke. Just add all ranks of which you want the double prefix to disappear). And use that helper track in the config instead of the player track.

**Comment by MsDemonicRaven** [comment]
duke is added to staff track. i got rid of the helper track, but when i gave my super admin the duke role, it gave him the civilian prefix too. like it upgraded him to civilian on that track for some reason.

**Comment by BrainStone** [comment]
Add duke to the player track is what I meant.
