### ISSUE TITLE
error mariadb/paper 1.11.2

### ISSUE THREAD

**Issue by mat41997** [lucko/LuckPerms#161]
logs
https://gist.github.com/mat41997/c91c4efe5b379cd7582057449434758b

config
https://gist.github.com/mat41997/d7d4cc10cdd75883a8afac256b2f0564

timigns
https://timings.aikar.co/?id=6664b7c17b5542339a8bebf7b2b8be5d

https://gist.githubusercontent.com/mat41997/6b128daf64003689a8ef26d6d62b69c1/raw/b3a0222e99711964cbee7aec2588754588e4042a/gistfile1.txt

**Comment by lucko** [comment]
You can ignore the error. It just took a little longer than expected to process one of the queries, probably because the server was starting up,
