### ISSUE TITLE
Warps permission not overriding lower false permissions

### ISSUE THREAD

**Issue by Shiunin** [lucko/LuckPerms#1610]
When a user is in two groups with conflicting Nucleus warp permissions (ie: One group called default has the warp set to false, and one group called Staff has the warp set to true) the returned permission is always false. Regardless of weighting of the groups. Even in my admin role with the wildcard 'nucleus.warps' cant access the warp 

Reproduction steps:
Give group 'default' weight 1 and set 'nucleus.warps.test' to false
Give group 'notdefault' weight 100 and set 'nucleus.warps.test' to true
Give user both groups parents, have user run '/warp test' note that they are being set to false despite the higher weighted group having the permission true

**Comment by lucko** [comment]
Does the user *only* inherit from those parents, or are there other groups that might interfere.

Setting this option to true might resolve the issue.

https://github.com/lucko/LuckPerms/blob/5577e3f59068a10d80201a6e07e60f620e5c654f/bukkit/src/main/resources/config.yml#L370-L381

**Comment by Shiunin** [comment]
I do not see this specific configuration in my config. Is it different per version? Apologizes for not specifying my version I'm on Spongeforge 1.12.2

I do see this:
`inheritance-traversal-algorithm = "depth-first-pre-order"`


Whats odd to me is that we have numerous perms that work and are set up in a similar fashion. The 'default' parent has it as false, and a higher weighted permission has it as true. It only seems to be nucleus warps this happens for. 

To answer the question i can reproduce the issue with a user who ONLY inherits from those two parents.

To complicated the answer, my own permissions suffer from this as well, and my highest weighted 
'admin' parent has the wild card 'nucleus.warps' which is suppose to allow me access to all warps, but i also get 'false' returned for any warps set to false in default.

Let me know if i can provide any further information! Thanks in advance for your time :)

**Comment by i9hdkill** [comment]
LP does not add new nodes to existing configs. Just add the node from /resources/config. to your config
