### ISSUE TITLE
Suggestion - Prefix abbreviations for stacking

### ISSUE THREAD

**Issue by Refrizor** [lucko/LuckPerms#1611]
Prefix stacking seems cool; however, I'd really want to merge other ranks as an abbreviation w/ the highest rank. For example, instead of [Helper][Elite], it would be nice to have a way to abbreviate other rank prefixes you may have with the stacking, so it's [Helper][E].

This would really, really help me with combining prefixes without making a mess. It would be awesome if you all looked forward to it! Maybe you set the short prefix (abbreviation) with a command and can bring it up @ the configuration. Anyway, thanks!

**Comment by lucko** [comment]
Yep, nice idea!

However, I think this is probably a bit out of scope & too complicated for LuckPerms to implement.

Perhaps something your chat plugin could add? :)
