### ISSUE TITLE
Player prefixes not showing anymore.

### ISSUE THREAD

**Issue by MsDemonicRaven** [lucko/LuckPerms#1615]
My players prefixes arent showing, while mine is. I have essentials chat, and nothing has changed in it. it just happened today. my superadmin still has his group, but now his prefix is gone along with the color of his name. i have a chatmanager plugin as well, but that just managing the chat like cursing, anti-ads, etc. nothing about player prefixes.

**Comment by MsDemonicRaven** [comment]
i even tried setting the prefix on his user file and it just shows in plain white text

**Comment by Andre601** [comment]
It could be that the chatmanager for some reason lets essentialschat think it manages chat.
But it could also be that Vault is no longer working.
Make sure you're running the right version of Vault, EssentialsX and EssentialsXChat for your server.

**Comment by MsDemonicRaven** [comment]
everything is up to date. and chatmanager just manages cursing, anti-ads, clearing chat, all that. it hasn't interfered like this.

**Comment by MsDemonicRaven** [comment]
now i just restarted my server now my prefix isnt showing.

**Comment by lucko** [comment]
All plugins still enabled & starting up correctly?

Do the correct prefixes show when you run `/lp user <user> info` ?

Sounds like an issue in configuration, not a bug :)
