### ISSUE TITLE
Waterfall Errors

### ISSUE THREAD

**Issue by coco0325** [lucko/LuckPerms#1617]
https://pastebin.com/nDrEBLe2

**Comment by Andre601** [comment]
Please provide actual information like server/proxy type, version, LP version and what you tried so far.
We can't read minds and just posting errors won't give us enough information

**Comment by lucko** [comment]
Need to see your full startup log please.

Also, please try setting this to true & restarting your proxy.

https://github.com/lucko/LuckPerms/blob/5577e3f59068a10d80201a6e07e60f620e5c654f/bukkit/src/main/resources/config.yml#L554-L557

Then wait for the error to occur again & send that log over.
