### ISSUE TITLE
Permissions data could not be loaded. Please contact an administrator.

### ISSUE THREAD

**Issue by zippyb081203** [lucko/LuckPerms#1619]
when i install luck perms it said Permissions data could not be loaded. Please contact an administrator. and im useing viaversions from 1.8 to 1.14

**Comment by Andre601** [comment]
Please provide actual information like Version of LuckPerms, Server Version, what Storage type you use and the console error you receive (There must be an error in console. Please share it through hastebin or a similar site)

**Comment by zippyb081203** [comment]
here you go https://pastebin.com/QZgEH0Qk

**Comment by toxamin** [comment]
try luckperms-legacy

**Comment by zippyb081203** [comment]
ok
