### ISSUE TITLE
luckperms + Worldguard not work

### ISSUE THREAD

**Issue by SliderKP** [lucko/LuckPerms#162]
http://wiki.sk89q.com/wiki/WorldGuard/Regions/Flags#Setting_Groups
this not work s:!

**Comment by DeathVirus** [comment]
What exactly did you try?

**Comment by SliderKP** [comment]
Attempt to give permission for a group to destroy / build in a region

with the command: /rg flag <region_ID> entry -g vip
 or /rg addmember <region_ID> -g vip


And none worked

**Comment by lucko** [comment]
The documentation specifically says:

"This does NOT refer to a permission group. It refers to region members/owners"

**Comment by DeathVirus** [comment]
It does however state HOW to make a permission group work. Read the page before you look for help

**Comment by SliderKP** [comment]
I'm sorry, it was my mistake
