### ISSUE TITLE
User are not getting Default permissions when joining

### ISSUE THREAD

**Issue by znepb** [lucko/LuckPerms#1620]
I set up a basic LP Default group, but whenever new players join, they don't get permissions set. The player does not show up when I run `/lp group default listmembers`, but do get a test prefix I applied to the group. I will attach my config.yml and default.yml rank files.
Sidenote: I am using YAML configurations instead of the default. 
(I changed the YAML files to text because GitHub wouldn't let me upload them, the file extension for them is .yml on the server
[default.txt](https://github.com/lucko/LuckPerms/files/3389351/default.txt)
[config.txt](https://github.com/lucko/LuckPerms/files/3389352/config.txt)

**Comment by lucko** [comment]
Users who don't have any permissions or groups aside from the default group will not show up in listmembers - that's normal, although perhaps something that needs to be noted.

Make sure you're setting the right permissions - use the verbose command if you're not sure.
