### ISSUE TITLE
Database Error

### ISSUE THREAD

**Issue by EzJamo** [lucko/LuckPerms#1621]
Im getting this error when starting my sever using mysql and luckperms. Everything setup correctly and still getting this error.
> [22:53:50 WARN]: [Server thread] INFO me.lucko.luckperms.lib.hikari.HikariDataSource - luckperms-hikari - Starting...
> [22:53:50 WARN]: [Server thread] INFO me.lucko.luckperms.lib.hikari.HikariDataSource - luckperms-hikari - Start completed.
> [22:53:55 ERROR]: [LuckPerms] Failed to init storage dao
> [22:53:55 WARN]: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5000ms.
> [22:53:55 WARN]: at me.lucko.luckperms.lib.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:697)
> [22:53:55 WARN]: at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:196)
> [22:53:55 WARN]: at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:161)
> [22:53:55 WARN]: at me.lucko.luckperms.lib.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
> [22:53:55 WARN]: at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.getConnection(HikariConnectionFactory.java:131)
> [22:53:55 WARN]: at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.tableExists(SqlStorage.java:151)
> [22:53:55 WARN]: at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.init(SqlStorage.java:168)
> [22:53:55 WARN]: at me.lucko.luckperms.common.storage.Storage.init(Storage.java:110)
> [22:53:55 WARN]: at me.lucko.luckperms.common.storage.StorageFactory.getInstance(StorageFactory.java:119)
> [22:53:55 WARN]: at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:135)
> [22:53:55 WARN]: at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onEnable(LPBukkitBootstrap.java:153)
> [22:53:55 WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
> [22:53:55 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
> [22:53:55 WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
> [22:53:55 WARN]: at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
> [22:53:55 WARN]: at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
> [22:53:55 WARN]: at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:203)
> [22:53:55 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
> [22:53:55 WARN]: at java.lang.Thread.run(Thread.java:748)
> [22:53:55 WARN]: Caused by: me.lucko.luckperms.lib.hikari.pool.PoolBase$ConnectionSetupException: java.sql.SQLException: null, message from server: "Host '172.18.0.3' is not allowed to connect to this MariaDB server"

**Comment by lucko** [comment]
`message from server: "Host '172.18.0.3' is not allowed to connect to this MariaDB server"`
