### ISSUE TITLE
Option to have Sponge style wildcards on other platforms

### ISSUE THREAD

**Issue by BrainStone** [lucko/LuckPerms#1625]
It would be extremely nice to have the ability to have Sponge style wildcards on all the platforms as an enable option.

This is mainly for networks that use different server platforms, but have plugins (like LuckPerms) that work on multiple platforms and have the same permission structure there.

**Comment by BrainStone** [comment]
I mean the code is in place already. Wouldn't it be either a move to Common, or a copy paste to the other projects?

**Comment by lucko** [comment]
Yes

**Comment by BrainStone** [comment]
Then why are we waiting since July :P

**Comment by lucko** [comment]
Because nobody has made the change?

My todo list is never ending, and this doesn't sit very high on it at the moment - sorry.

**Comment by BrainStone** [comment]
Thank you :)
