### ISSUE TITLE
\n newline not work

### ISSUE THREAD

**Issue by mat41997** [lucko/LuckPerms#163]
ss
![2017-02-03 02_38_32-formatowanie tekstu oficjalna minecraft wiki polska](https://cloud.githubusercontent.com/assets/5884000/22576171/68a9e15c-e9ba-11e6-99bb-8cab8c415cd5.png)

![2017-02-03 02_49_40-minecraft 1 11 2](https://cloud.githubusercontent.com/assets/5884000/22576431/a666ab64-e9bb-11e6-929b-6d2a9bb0b963.png)

![2017-02-03 02_50_54-](https://cloud.githubusercontent.com/assets/5884000/22576435/a8442894-e9bb-11e6-8eaf-096033deb701.png)

**Comment by lucko** [comment]
Not a LP issue, raise it with the author of your chat formatting plugin.
