### ISSUE TITLE
permission lag on aternos

### ISSUE THREAD

**Issue by cjwijtmans** [lucko/LuckPerms#1631]
running a free server on aternos, so ofcourse it is not a performant server in the first place, however i think there could be some improvements to make? 

> [WARN] [Essentials] Permissions lag notice with (SuperpermsHandler). Response took 28.091630ms. Summary: Getting group for -user-

When i install vault it complains about prefixes in a similar fashion as well.

Using minecraft 1.14.3 latest release of spigot and luckperms and essentialsx. Was using separated flat files first but then switched to a single h2 file to try to reduce the lag.

My question is are these queries cached? Is it essentials or luckperms lagging?

**Comment by Andre601** [comment]
It is most likely the server itself lagging.
Like you just said....
> running a free serveron aternos, so ofcourse it is not a performant server in the first place, [...]

**Comment by BrainStone** [comment]
The only time LP reads from the disk is when a player joins or when `/lp sync` is run.  
Meaning that if you’re running an up to date version of LP, then it means that the server itself is lagging severely.
