### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by mamilicalmir** [lucko/LuckPerms#1633]
Hello Luckperms developer/s! My name is Almir R. Mamilic. I ma currently using your plugin and it is a very good permission manager plugin. But this time, I got this unusual error that popped out suddenly. I hope you can help me. Thank you so much =D

Here's a pastebin link for the error
https://pastebin.com/aAabie7r

**Comment by BrainStone** [comment]
It appears that the way you configured your prefix/suffix stacking is incorrect.

Feel free to post that part here, should you not be able to fix it yourself.

**Comment by mamilicalmir** [comment]
Sorry for the late response. Here's the config for my prefix/suffix stacking https://pastebin.com/DTMWzbVA
And in addition, I copy pasted the config before I put the highest in the suffix format. It was empty before. Just tellin you maybe it was the cause. But please help me :(

Thank you

**Comment by lucko** [comment]
Very strange, the configuration looks ok to me.

Perhaps worth resetting that part of it and starting again? I can't see anything super obvious there.
