### ISSUE TITLE
Temp permissions keep disappearing randomly

### ISSUE THREAD

**Issue by Sir-Will** [lucko/LuckPerms#1634]
I keep having the issue that temp permission disappear from the database randomly before they expired.
The action entry is still in the database, just the permission is missing in group_permissions table.

This wasn't an issue before and I have no idea whats causing this issue.

version: LuckPerms-Sponge-4.4.26 and LuckPerms-Bukkit-Legacy-4.4.26
storage-method: mysql

**Comment by BrainStone** [comment]
What timeframes are we talking about?

**Comment by Sir-Will** [comment]
The temp permissions are set around 30 days.

**Comment by Sir-Will** [comment]
Permanent permissions seem to be disappearing too.
Added a permission few days ago and today I checked and it was no longer there. The actions table has a record of adding that permissions but no action of someone removing it.
![](https://i.imgur.com/c45o2jc.jpg)

**Comment by lucko** [comment]
Perhaps an issue with server time being out of sync?

That's my best guess. Could potentially add something to combat this.

**Comment by Sir-Will** [comment]
Not that I have noticed but I guess it can be out of sync for just a moment, on any server luckperms is running on and cause this.

**Comment by lucko** [comment]
I believe this has most likely been fixed in v5. The system for auditing temporary permissions is now much improved, this kind of data loss should not be possible.

**Comment by Sir-Will** [comment]
Thank you!
