### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by EzJamo** [lucko/LuckPerms#1635]
Hey my server is crashing every couple hours with this error. https://pastebin.com/ipDA0Ga3

It says some things about LuckPerms in the crash so i thought id ask here to see if you guys know what i can do to fix this?

Any help is appreciated, Thanks :D

**Comment by Andre601** [comment]
The first thing/plugin that is listed in that crash dump is:
`fr.nashoba24.wolvsk.serverquery.MinecraftPingUtil.readVarInt(MinecraftPingUtil.java:62)` so it's pretty much not an issue on LPs side.
