### ISSUE TITLE
nucleus.inventory.keepondeath doesn't work for the nether, how to apply it to the nether and the end?

### ISSUE THREAD

**Issue by Willbound** [lucko/LuckPerms#1637]
We're running a pixelmon server along with all the sidemods except AGP, however I don't think pixelmon is interfering with it.
Keep inventory works in the overworld and the ultraworld(pixelmon), however it doesn't work in the nether and by extension probably the end, how to I make it work in every dimension?

**Comment by Andre601** [comment]
Just give permission globally, which LP does by default.

This isn't really an LP related issue and more a configuration problem.

**Comment by Willbound** [comment]
How do I give it globally?

**Comment by Andre601** [comment]
LP does give permissions globally by default as long as you don't provide any context.

Examples:
```
/lp group default permission set some.permission # Sets the permission as true for all worlds (globally)
/lp group default permission set some.other.permission false # Sets the permission as false for all worlds (globally)
```
