### ISSUE TITLE
Confusing error with MySQL & Redis

### ISSUE THREAD

**Issue by GetJiggyWitIt** [lucko/LuckPerms#1638]
I'm running a redis database and a MySQL database on my VPS and when I try to connect them to LP my console gets spammed by a bunch of errors. I don't run my network on the server as my databases btw.

23.07 00:27:37 [Server] INFO __    
23.07 00:27:37 [Server] INFO |    |__)   LuckPerms v4.4.27
23.07 00:27:37 [Server] INFO |___ |      Running on Bungee - Travertine
23.07 00:27:37 [Server] INFO [LuckPerms]: Loading configuration...
23.07 00:27:39 [Server] INFO [LuckPerms]: Loading storage provider... [MYSQL]
23.07 00:27:39 [Server] INFO [me.lucko.luckperms.lib.hikari.HikariDataSource]: luckperms-hikari - Starting...
23.07 00:27:39 [Server] INFO [me.lucko.luckperms.lib.hikari.HikariDataSource]: luckperms-hikari - Start completed.
23.07 00:27:39 [Server] ERROR Tue Jul 23 00:27:39 EDT 2019 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
23.07 00:27:39 [Server] ERROR Tue Jul 23 00:27:39 EDT 2019 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
23.07 00:27:40 [Server] ERROR Tue Jul 23 00:27:40 EDT 2019 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
23.07 00:27:40 [Server] ERROR Tue Jul 23 00:27:40 EDT 2019 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
23.07 00:27:41 [Server] ERROR Tue Jul 23 00:27:41 EDT 2019 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
23.07 00:27:42 [Server] ERROR Tue Jul 23 00:27:42 EDT 2019 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
23.07 00:27:44 [Server] ERROR [LuckPerms]: Failed to init storage dao
23.07 00:27:44 [Server] ERROR java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5013ms.
23.07 00:27:44 [Server] ERROR at me.lucko.luckperms.lib.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:697)
23.07 00:27:44 [Server] ERROR at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:196)
23.07 00:27:44 [Server] ERROR at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:161)
23.07 00:27:44 [Server] ERROR at me.lucko.luckperms.lib.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
23.07 00:27:44 [Server] ERROR at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.getConnection(HikariConnectionFactory.java:131)
23.07 00:27:44 [Server] ERROR at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.tableExists(SqlStorage.java:153)
23.07 00:27:44 [Server] ERROR at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.init(SqlStorage.java:170)
23.07 00:27:44 [Server] ERROR at me.lucko.luckperms.common.storage.Storage.init(Storage.java:110)
23.07 00:27:44 [Server] ERROR at me.lucko.luckperms.common.storage.StorageFactory.getInstance(StorageFactory.java:88)
23.07 00:27:44 [Server] ERROR at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:136)
23.07 00:27:44 [Server] ERROR at me.lucko.luckperms.bungee.LPBungeeBootstrap.onEnable(LPBungeeBootstrap.java:124)
23.07 00:27:44 [Server] ERROR at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:283)
23.07 00:27:44 [Server] ERROR at net.md_5.bungee.BungeeCord.start(BungeeCord.java:289)
23.07 00:27:44 [Server] ERROR at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
23.07 00:27:44 [Server] ERROR at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
23.07 00:27:44 [Server] ERROR Caused by: me.lucko.luckperms.lib.hikari.pool.PoolBase$ConnectionSetupException: me.lucko.luckperms.lib.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Access denied for user 'admin1'@'%' to database 'mydb1'
23.07 00:27:44 [Server] ERROR at me.lucko.luckperms.lib.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:501)
23.07 00:27:44 [Server] ERROR at me.lucko.luckperms.lib.hikari.pool.HikariPool.access$100(HikariPool.java:71)
23.07 00:27:44 [Server] ERROR at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:727)
23.07 00:27:44 [Server] ERROR at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:713)
23.07 00:27:44 [Server] ERROR at java.util.concurrent.FutureTask.run(FutureTask.java:266)
23.07 00:27:44 [Server] ERROR at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
23.07 00:27:44 [Server] ERROR at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
23.07 00:27:44 [Server] ERROR at java.lang.Thread.run(Thread.java:748)
23.07 00:27:44 [Server] ERROR Caused by: me.lucko.luckperms.lib.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Access denied for user 'admin1'@'%' to database 'mydb1'
23.07 00:27:44 [Server] ERROR at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
23.07 00:27:44 [Server] ERROR at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
23.07 00:27:44 [Server] ERROR at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
23.07 00:27:44 [Server] ERROR at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
23.07 00:27:44 [Server] ERROR at me.lucko.luckperms.lib.mysql.jdbc.Util.handleNewInstance(Util.java:425)
23.07 00:27:44 [Server] ERROR at me.lucko.luckperms.lib.mysql.jdbc.Util.getInstance(Util.java:408)
23.07 00:27:44 [Server] ERROR at me.lucko.luckperms.lib.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
23.07 00:27:44 [Server] ERROR at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)
23.07 00:27:44 [Server] ERROR at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
23.07 00:27:44 [Server] ERROR at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:871)
23.07 00:27:44 [Server] ERROR at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1714)
23.07 00:27:44 [Server] ERROR at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1224)
23.07 00:27:44 [Server] ERROR at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2199)
23.07 00:27:44 [Server] ERROR at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2230)
23.07 00:27:44 [Server] ERROR at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2025)
23.07 00:27:44 [Server] ERROR at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:778)
23.07 00:27:44 [Server] ERROR at me.lucko.luckperms.lib.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
23.07 00:27:44 [Server] ERROR at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
23.07 00:27:44 [Server] ERROR at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
23.07 00:27:44 [Server] ERROR at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
23.07 00:27:44 [Server] ERROR at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
23.07 00:27:44 [Server] ERROR at me.lucko.luckperms.lib.mysql.jdbc.Util.handleNewInstance(Util.java:425)
23.07 00:27:44 [Server] ERROR at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
23.07 00:27:44 [Server] ERROR at me.lucko.luckperms.lib.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
23.07 00:27:44 [Server] ERROR at me.lucko.luckperms.lib.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:428)
23.07 00:27:44 [Server] ERROR at me.lucko.luckperms.lib.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:136)
23.07 00:27:44 [Server] ERROR at me.lucko.luckperms.lib.hikari.pool.PoolBase.newConnection(PoolBase.java:353)
23.07 00:27:44 [Server] ERROR at me.lucko.luckperms.lib.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
23.07 00:27:44 [Server] ERROR at me.lucko.luckperms.lib.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)
23.07 00:27:44 [Server] ERROR ... 7 more
23.07 00:27:44 [Server] INFO [LuckPerms]: Loading messaging service... [REDIS]
23.07 00:27:44 [Server] ERROR me.lucko.luckperms.lib.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
23.07 00:27:44 [Server] ERROR at me.lucko.luckperms.lib.jedisutil.Pool.getResource(Pool.java:59)
23.07 00:27:44 [Server] ERROR at me.lucko.luckperms.lib.jedis.JedisPool.getResource(JedisPool.java:235)
23.07 00:27:44 [Server] ERROR at me.lucko.luckperms.common.messaging.redis.RedisMessenger.lambda$init$0(RedisMessenger.java:70)
23.07 00:27:44 [Server] ERROR at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
23.07 00:27:44 [Server] ERROR at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
23.07 00:27:44 [Server] ERROR at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
23.07 00:27:44 [Server] ERROR at java.lang.Thread.run(Thread.java:748)
23.07 00:27:44 [Server] ERROR Caused by: me.lucko.luckperms.lib.jedis.exceptions.JedisDataException: ERR invalid password
23.07 00:27:44 [Server] ERROR at me.lucko.luckperms.lib.jedis.Protocol.processError(Protocol.java:130)
23.07 00:27:44 [Server] ERROR at me.lucko.luckperms.lib.jedis.Protocol.process(Protocol.java:164)
23.07 00:27:44 [Server] ERROR at me.lucko.luckperms.lib.jedis.Protocol.read(Protocol.java:218)
23.07 00:27:44 [Server] ERROR at me.lucko.luckperms.lib.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:341)
23.07 00:27:44 [Server] ERROR at me.lucko.luckperms.lib.jedis.Connection.getStatusCodeReply(Connection.java:240)
23.07 00:27:44 [Server] ERROR at me.lucko.luckperms.lib.jedis.BinaryJedis.auth(BinaryJedis.java:2286)
23.07 00:27:44 [Server] ERROR at me.lucko.luckperms.lib.jedis.JedisFactory.makeObject(JedisFactory.java:140)
23.07 00:27:44 [Server] ERROR at me.lucko.luckperms.lib.commonspool2.impl.GenericObjectPool.create(GenericObjectPool.java:874)
23.07 00:27:44 [Server] ERROR at me.lucko.luckperms.lib.commonspool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:417)
23.07 00:27:44 [Server] ERROR at me.lucko.luckperms.lib.commonspool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:346)
23.07 00:27:44 [Server] ERROR at me.lucko.luckperms.lib.jedisutil.Pool.getResource(Pool.java:50)
23.07 00:27:44 [Server] ERROR ... 6 more
23.07 00:27:44 [Server] INFO [LuckPerms]: Loading internal permission managers...
23.07 00:27:44 [Server] INFO [LuckPerms]: Performing initial data load...
23.07 00:27:44 [Server] ERROR Tue Jul 23 00:27:44 EDT 2019 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
23.07 00:27:47 [Server] ERROR Tue Jul 23 00:27:47 EDT 2019 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
23.07 00:27:49 [Server] ERROR java.util.concurrent.CompletionException: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5000ms.
23.07 00:27:49 [Server] ERROR at me.lucko.luckperms.common.storage.Storage.lambda$makeFuture$1(Storage.java:99)
23.07 00:27:49 [Server] ERROR at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
23.07 00:27:49 [Server] ERROR at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
23.07 00:27:49 [Server] ERROR at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
23.07 00:27:49 [Server] ERROR at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
23.07 00:27:49 [Server] ERROR at java.lang.Thread.run(Thread.java:748)
23.07 00:27:49 [Server] ERROR Caused by: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5000ms.
23.07 00:27:49 [Server] ERROR at me.lucko.luckperms.lib.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:697)
23.07 00:27:49 [Server] ERROR at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:196)
23.07 00:27:49 [Server] ERROR at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:161)
23.07 00:27:49 [Server] ERROR at me.lucko.luckperms.lib.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
23.07 00:27:49 [Server] ERROR at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.getConnection(HikariConnectionFactory.java:131)
23.07 00:27:49 [Server] ERROR at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.loadAllGroups(SqlStorage.java:646)
23.07 00:27:49 [Server] ERROR at me.lucko.luckperms.common.storage.Storage.lambda$loadAllGroups$10(Storage.java:190)
23.07 00:27:49 [Server] ERROR at me.lucko.luckperms.common.storage.Storage.lambda$makeFuture$1(Storage.java:94)
23.07 00:27:49 [Server] ERROR ... 5 more
23.07 00:27:49 [Server] ERROR Caused by: me.lucko.luckperms.lib.hikari.pool.PoolBase$ConnectionSetupException: me.lucko.luckperms.lib.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Access denied for user 'admin1'@'%' to database 'mydb1'
23.07 00:27:49 [Server] ERROR at me.lucko.luckperms.lib.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:501)
23.07 00:27:49 [Server] ERROR at me.lucko.luckperms.lib.hikari.pool.HikariPool.access$100(HikariPool.java:71)
23.07 00:27:49 [Server] ERROR at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:727)
23.07 00:27:49 [Server] ERROR at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:713)
23.07 00:27:49 [Server] ERROR at java.util.concurrent.FutureTask.run(FutureTask.java:266)
23.07 00:27:49 [Server] ERROR ... 3 more
23.07 00:27:49 [Server] ERROR Caused by: me.lucko.luckperms.lib.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Access denied for user 'admin1'@'%' to database 'mydb1'
23.07 00:27:49 [Server] ERROR at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
23.07 00:27:49 [Server] ERROR at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
23.07 00:27:49 [Server] ERROR at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
23.07 00:27:49 [Server] ERROR at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
23.07 00:27:49 [Server] ERROR at me.lucko.luckperms.lib.mysql.jdbc.Util.handleNewInstance(Util.java:425)
23.07 00:27:49 [Server] ERROR at me.lucko.luckperms.lib.mysql.jdbc.Util.getInstance(Util.java:408)
23.07 00:27:49 [Server] ERROR at me.lucko.luckperms.lib.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
23.07 00:27:49 [Server] ERROR at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)
23.07 00:27:49 [Server] ERROR at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
23.07 00:27:49 [Server] ERROR at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:871)
23.07 00:27:49 [Server] ERROR at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1714)
23.07 00:27:49 [Server] ERROR at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1224)
23.07 00:27:49 [Server] ERROR at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2199)
23.07 00:27:49 [Server] ERROR at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2230)
23.07 00:27:49 [Server] ERROR at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2025)
23.07 00:27:49 [Server] ERROR at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:778)
23.07 00:27:49 [Server] ERROR at me.lucko.luckperms.lib.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
23.07 00:27:49 [Server] ERROR at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
23.07 00:27:49 [Server] ERROR at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
23.07 00:27:49 [Server] ERROR at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
23.07 00:27:49 [Server] ERROR at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
23.07 00:27:49 [Server] ERROR at me.lucko.luckperms.lib.mysql.jdbc.Util.handleNewInstance(Util.java:425)
23.07 00:27:49 [Server] ERROR at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
23.07 00:27:49 [Server] ERROR at me.lucko.luckperms.lib.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
23.07 00:27:49 [Server] ERROR at me.lucko.luckperms.lib.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:428)
23.07 00:27:49 [Server] ERROR at me.lucko.luckperms.lib.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:136)
23.07 00:27:49 [Server] ERROR at me.lucko.luckperms.lib.hikari.pool.PoolBase.newConnection(PoolBase.java:353)
23.07 00:27:49 [Server] ERROR at me.lucko.luckperms.lib.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
23.07 00:27:49 [Server] ERROR at me.lucko.luckperms.lib.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)
23.07 00:27:49 [Server] ERROR ... 7 more
23.07 00:27:49 [Server] INFO [LuckPerms]: Successfully enabled. (took 12177ms)
23.07 00:27:49 [Server] INFO Enabled plugin LuckPerms version 4.4.27 by Luck

**Comment by IdrizPelaj** [comment]
`ERROR Caused by: me.lucko.luckperms.lib.hikari.pool.PoolBase$ConnectionSetupException: me.lucko.luckperms.lib.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Access denied for user 'admin1'@'%' to database 'mydb1'`

This makes me believe that your authentication information is incorrect.

**Comment by GetJiggyWitIt** [comment]
> `ERROR Caused by: me.lucko.luckperms.lib.hikari.pool.PoolBase$ConnectionSetupException: me.lucko.luckperms.lib.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Access denied for user 'admin1'@'%' to database 'mydb1'`
> 
> This makes me believe that your authentication information is incorrect.

Is auth required?

**Comment by BrainStone** [comment]
MySQL always requires auth. Imagine the security issues you'd run into if everyone could just read and write every database.

**Comment by GetJiggyWitIt** [comment]
The auth info is correct. Heres my config it might be something else: https://pastebin.com/raw/R79q2rji

**Comment by BrainStone** [comment]
Congrats. Now you need to change your password.
And the issue is most likely that that user doesn't have access to the database.
