### ISSUE TITLE
"X doesn't have data pre-loaded."

### ISSUE THREAD

**Issue by dereklanz517** [lucko/LuckPerms#1639]
I am getting this in my console, and permissions don't seem to be working. https://pastebin.com/EF1LrJxE
![thing](https://user-images.githubusercontent.com/53240872/61754489-3510ac80-ad68-11e9-8976-1b9c62e01f04.PNG)

**Comment by Andre601** [comment]
Try updating to either Spigot or PaperMC. Maybe that will fix your issue.

**Comment by dereklanz517** [comment]
@andre601 It’s already on spigot

**Comment by lucko** [comment]
Any auth plugins, or plugins which might be changing player uuids on login?

Usually this is an issue caused by plugins attempting to merge legacy (cracked) connections with legit ones.
