### ISSUE TITLE
Players can't pick up items

### ISSUE THREAD

**Issue by leshacoplays** [lucko/LuckPerms#1640]
default players can't pick up items how can to fix that? thanks lucko you are really awesome!
1.14.4

**Comment by Turbotailz** [comment]
This isn't an issue with LuckPerms, you will have installed a plugin that blocks players from picking up items. First step to figuring this out is to check your list of installed plugins and figure out what could possibly be blocking item pickups.

Alternatively you can use the [Verbose feature](https://github.com/lucko/LuckPerms/wiki/Verbose) to see if any permission checks are being called that may be blocking item pickups, then you should be able to add those permissions.

**Comment by leshacoplays** [comment]
I got EssentialsX only default players cant pickup items

**Comment by leshacoplays** [comment]
should i delete essentialsxantibuild then go for world guard?

**Comment by Andre601** [comment]
Yes.

It's recommended to not just upload EssentialsX and all its add-ons. Only upload those you really need.

**Comment by leshacoplays** [comment]
Thanks!
