### ISSUE TITLE
[API] Permission check event

### ISSUE THREAD

**Issue by Sir-Will** [lucko/LuckPerms#1641]
hey,
it would be great if there is an event in the API for when LP checks the permissions which allows changing the result, so we can overwrite the LP permission check in some situations.

**Comment by BrainStone** [comment]
Terrible idea. Straight up kills the performance. Event systems are not cheap, you know?

The next best thing LP offers are transient permissions. They are permissions plugins can assign to players (and groups I think). They overrule all other permissions, they are never saved and don't show up with any commands. Perfect to override certain permissions.

**Comment by lucko** [comment]
As Brainstone said, unfortunately this isn't viable for performance reasons.
