### ISSUE TITLE
Prefix glitch with Paper-146

### ISSUE THREAD

**Issue by neyumners** [lucko/LuckPerms#1642]
I had set my prefixes for "staff ranks" and set their weight and staff track. Prefixes show up in chat.

Now I made player ranks and when I attempted to set prefixes, they do not show up.

LAN server

EssentialsXChat-2.17.0.5
Vault v1.7.2-b107
LuckPerms v4.4.27
Paper version git-Paper-146 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**Comment by Andre601** [comment]
Run `/lp group <your group> info`
If it displays the prefix but not in chat, then it's clearly an issue with either Vault (most unlikely) or EssentialsXChat.

**Comment by neyumners** [comment]
I cleared all my LuckPerms, and Vault data, it is working now.
Thank you, though.
