### ISSUE TITLE
Ultra Permissions Migration Support

### ISSUE THREAD

**Issue by TakoidGit** [lucko/LuckPerms#1643]
[Ultra Permissions SpigotMC Resource Link](https://www.spigotmc.org/resources/ultra-permissions.42678/)

I've ran into an increasing amount of situations in which UltraPermissions is not supported by a plugin so I am looking to transition to LuckPerms. Unfortunately, the time it would take to migrate permissions between Ultra Permissions and LuckPerms holds me back from doing so.

**Comment by Andre601** [comment]
As long as UPerms doesn't have an oen, available API to use is it impossible to get the data from it to migrate

**Comment by TakoidGit** [comment]
> As long as UPerms doesn't have an open, available API to use is it impossible to get the data from it to migrate

Thanks for letting me know. Annoyingly enough the files storing the permissions data is encoded so I can't easily transfer everything over manually either.

I think it's probably time to make the switch regardless. UPerms is probably excellent for novice server owners but it's continually had drawbacks since I've started using it.

Appreciate the quick response. Thanks again!
