### ISSUE TITLE
No permissions working on any plugin in any group

### ISSUE THREAD

**Issue by HotdogVanDriver** [lucko/LuckPerms#1648]
Hey,

I've setup all my permissions (used the groupmanager loader thing that was super helpful) 🗡 

However went to test perms on my alt account yesterday and nothing works D:

My alt account running "/tags": https://ibb.co/0ZjBkVq
My alt is in adventurer group in Factions world: https://ibb.co/P1rvbgs
That permission resides in the adventurer group for factions world: https://ibb.co/YDQbMF4

Extra info:
1. None of the commands work no matter which group I'm in or which plugin the command is from. 
2. All commands work completely fine on my opped account. 
3. Applyedits has been done
4. Changing the world to global doesn't fix the issue

Would appreciate some help! Idk what I've done wrong.

**Comment by Andre601** [comment]
Did you migrate from GroupManager?
If yes then make sure you have removed GroupManager and restarted your server. As long as an other (known) perm plugin is installed will LP limit its own functionality (including permission checks) to prevent any conflicts with the other perm plugin. Only migration command and some other commands will be functional, but as I said will perm checks be disabled.

**Comment by HotdogVanDriver** [comment]
Group manager was deleted after migration. Which was about 2 weeks ago


Sent from Yahoo Mail for iPhone


On Saturday, July 27, 2019, 5:47 pm, Andre_601 <notifications@github.com> wrote:


Did you migrate from GroupManager?
If yes then make sure you have removed GroupManager and restarted your server. As long as an other (known) perm plugin is installed will LP limit its own functionality (including permission checks) to prevent any conflicts with the other perm plugin. Only migration command and some other commands will be functional, but as I said will perm checks be disabled.

**Comment by HotdogVanDriver** [comment]
Would I be able to pay you to come on and have a look at it?


Sent from Yahoo Mail for iPhone


On Saturday, July 27, 2019, 5:47 pm, Andre_601 <notifications@github.com> wrote:


Did you migrate from GroupManager?
If yes then make sure you have removed GroupManager and restarted your server. As long as an other (known) perm plugin is installed will LP limit its own functionality (including permission checks) to prevent any conflicts with the other perm plugin. Only migration command and some other commands will be functional, but as I said will perm checks be disabled.

**Comment by lucko** [comment]
Perhaps try using the verbose command to see what's going on.

Unfortunately I don't have time to come and look at your own setup. You should be able to work it out using the tools available in the plugin though. :wink:
