### ISSUE TITLE
Give luckperms.user.parent.set.example command with out access to all parent.set

### ISSUE THREAD

**Issue by DocNobb** [lucko/LuckPerms#165]
I have groups like Admin, Mod, Player, Spectator, Jail ect, and i want Mod to be able to grant levels below it but not above and at the same level as Mod. Is this possible with LuckPerms?

**Comment by DragoSpiro98** [comment]
How did you solve this? I use luckperms.user.parent.set.[name of my group, in my case is helper] but it doesn't work

I use luckperms.user.parent.set.helper

**Comment by Andre601** [comment]
> How did you solve this? I use luckperms.user.parent.set.[name of my group, in my case is helper] but it doesn't work
> 
> I use luckperms.user.parent.set.helper

There is the option to enable argument-based command permissions to restrict commands to certain patterns only.
https://github.com/lucko/LuckPerms/wiki/Argument-based-command-permissions

**Comment by DragoSpiro98** [comment]
> > How did you solve this? I use luckperms.user.parent.set.[name of my group, in my case is helper] but it doesn't work
> > I use luckperms.user.parent.set.helper
> 
> There is the option to enable argument-based command permissions to restrict commands to certain patterns only.
> https://github.com/lucko/LuckPerms/wiki/Argument-based-command-permissions

I try it, it's says "you don't have permission to use any sub commands", what's the problem?
