### ISSUE TITLE
Illegal reflective access issue with Java 11 on server start

### ISSUE THREAD

**Issue by axemwa** [lucko/LuckPerms#1650]
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by me.lucko.luckperms.common.dependencies.classloader.ReflectionClassLoader (file:/C:/CivcraftBETA/plugins/LuckPerms-Bukkit-4.4.1.jar) to method java.net.URLClassLoader.addURL(java.net.URL)
WARNING: Please consider reporting this to the maintainers of me.lucko.luckperms.common.dependencies.classloader.ReflectionClassLoader
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

Using 1.13.2 Paper Build 641

**Comment by Tobi406** [comment]
See #952

**Comment by axemwa** [comment]
dang, ty
