### ISSUE TITLE
Context with comma in name not working

### ISSUE THREAD

**Issue by GuusLieben** [lucko/LuckPerms#1652]
When setting any type of context with a comma in its name (e.g. a world context) it doesn't match and thus doesn't do anything.

E.g. ```/lp user Steve meta addprefix 1 &"cSample Prefix" world=4,-4``` won't display the prefix even if the user is in that world.

These world names are generated by PlotSquared, and thus cannot be changed in this use-case.

On SpongeAPI 7.1.0-d453c3e / Minecraft 1.12.2

**Comment by Andre601** [comment]
The world context is for world names and therefore what you tried (I assume coordinates?) don't work.
From what I remember are commas not supported for world names and therefore not usable here either.

PlotSquared doesn't generate such world names. What you're most likely referring to are the **Plot IDs** which are a completely different story.

**Comment by GuusLieben** [comment]
PlotSquared has a worlds feature, which allows you to claim entire worlds with it. That does use worlds with comma's in the names. That name is used globally in Sponge, and plugins hooked into it. It's very much possible when enabled

**Comment by lucko** [comment]
Commas are now allowed in world names.
