### ISSUE TITLE
Permission with variable

### ISSUE THREAD

**Issue by chouuul** [lucko/LuckPerms#1653]
Hello guys. I will be fast.
It will be 1 month i'm trying to use LuckPerms with FTBUtilities.
I have try so much combos to change the :
"ftbu.claims.max_chunks": 50

Somebody can help me ? Maybe we can do a timed ranks on ftbutilities... i found nothing...
Please help

**Comment by Andre601** [comment]
[settemp]: https://github.com/lucko/LuckPerms/wiki/Command-Usage:-Permission#lp-usergroup-usergroup-permission-settemp
[addtemp]: https://github.com/lucko/LuckPerms/wiki/Command-Usage:-Parent#lp-usergroup-usergroup-parent-addtemp
[wiki]: https://github.com/lucko/LuckPerms/wiki

Can you try to rephrase what you're trying?
I can't really understand what you want to achieve here.

Do you want to give permission or a specific group for a certain time to the player/group?
Use either [`/lp user|group <user|group> permission settemp <permission> <true|false> <time> [modifier] [context]`][settemp] or [`/lp user|group <user|group> parent addtemp <group> <time> [modifier] [context]`][addtemp] (Both are linked to their corresponding wiki entry)

Try to set something else temporary?
There are different commands to f.e. add meta information to groups users for a certain time.
Check the [wiki].

**Comment by chouuul** [comment]
Sorry for my very bad english :(

I'm want to set this permission : "ftbu.claims.max_chunks": 50
for a group

**Comment by chouuul** [comment]
I used every combo possible but it didn't work :/

Can you help me ?

**Comment by lucko** [comment]
You need to set meta.

https://github.com/lucko/LuckPerms/wiki/Command-Usage:-Meta#lp-usergroup-usergroup-meta-set

**Comment by CorvetteCole** [comment]
@chouuul did this work for you?
