### ISSUE TITLE
Please add useSSL=false in the mysql8 connection

### ISSUE THREAD

**Issue by kevinlovely** [lucko/LuckPerms#1654]
Please add useSSL=false in the mysql8 connection.

WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.

I used mysql8 and set the authentication method to be compatible with mysql5, but the console still warned me.
It seems that need a url like this: jdbc:mysql://...?useSSL=false

**Comment by Andre601** [comment]
There is a sectionin the wiki covering this.
Look at the storage error page forthe one you have

**Comment by kevinlovely** [comment]
> There is a sectionin the wiki covering this.
> Look at the storage error page forthe one you have

Sorry, I didn't find it. Can you give me a URL?

**Comment by Tobi406** [comment]
Step to step guide how to get your information on the LP Wiki:
1. Open the wiki (click "Wiki) in the navigation bar, if you can't find it, use the search function of your browser
2. Search "error" (The page is called "Storage system errors", but no gurantee) in the sidebar, if you can't find it, do the same as in step 1
3. Search `useSSL` on the page, if you can't find it, do the same as in step 1

**Comment by kevinlovely** [comment]
> 步骤指导如何在LP Wiki上获取您的信息：
> 
> 1. 打开维基（点击导航栏中的“维基”），如果找不到，请使用浏览器的搜索功能
> 2. 在侧栏中搜索“错误”（该页面称为“存储系统错误”，但没有保证），如果找不到，请执行与步骤1中相同的操作
> 3. 在页面上搜索“useSSL”，如果找不到，请执行与步骤1相同的操作

Thank you so much. My sorry, forgot to find the wiki before issues.xD
