### ISSUE TITLE
Bulkupdate can't remove permission when user only has 1 permission

### ISSUE THREAD

**Issue by AmazedMender16** [lucko/LuckPerms#1655]
Hello,

I can't seem to bulk remove a permission when a user has only 1 permission.
Tried it on 4.4.27

Regards,
Glenn R.

**Comment by Andre601** [comment]
This doesn't help us at all.
You have to tell us what you tried and what the results are.

**Comment by AmazedMender16** [comment]
@Andre601 

Talked about it in the discord channel today, anyway here is what we did.
```
lp bulkupdate all update permission all.permission.nodes "permission ~~ permission.node.%"
lp bulkupdate all update permission all.permission.nodes "permission ~~ node.%"
lp bulkupdate users delete "permission == all.permission.nodes"
```
The wanted permission nodes will change to `all.permission.nodes` which is expected, then I would like to delete `all.permission.nodes` with the 3rd command.
It will delete that permission for all users that have other permission aswell. The permission won't get delete if the user has only that permission left.

**Comment by lucko** [comment]
Fixed in the latest version.
