### ISSUE TITLE
WorldGuard Region Support

### ISSUE THREAD

**Issue by BoyJamal** [lucko/LuckPerms#1657]
Recently switching over from Pex to LuckPerms and the region entry flags seem to not be working and I was wondering what I am doing wrong. I have a group for each "Mine Rank" (A-Z) and in WorldGuard flags have done the command rg flag <region> entry deny and rg addmember <region> g:<rank> and even if im that rank It will not let me enter the mine. I see there is a plugin called ExtraContexts but I was wondering how I would apply that to this. Thanks for help!

**Comment by Turbotailz** [comment]
Make sure the groups are entered as lower case as that's how LP stores them (and they are case sensitive).

ExtraContexts isn't really a solution here as that will only allow/deny permissions in certain regions, not flags.

**Comment by BoyJamal** [comment]
all the groups are labeled a,b,c, etc. so I don't think that is the issue. I also made sure each group had the group.<group> permission and it still was blocking me from entering the region

**Comment by BoyJamal** [comment]
maybe it has something to do with how I setup the weight or parent?

**Comment by BoyJamal** [comment]
I made a the lowest and went up 100 each time, and each rank inherits each other

**Comment by BoyJamal** [comment]
they also all are on a track for like staff, donor,mineranks

**Comment by BoyJamal** [comment]
just going to go back to Pex

**Comment by Turbotailz** [comment]
Yikes.

Have fun with that.

**Comment by BoyJamal** [comment]
luckperms clearly is the better plugin but there is solution to one of the biggest things that needs to be on my server.

**Comment by nintendnerd** [comment]
To anyone finding this, I found that the recent version of worldguard is checking for node groups.name not group.name like everyone says.  make it plural and it will fix this.

**Comment by Andre601** [comment]
Or even better, report to the devs of WorldGuard as this is most likely not intended and can be seen as a bug.
