### ISSUE TITLE
Automatic promotion/demotion based on timeplayed/mcmmo etc.

### ISSUE THREAD

**Issue by Gizmopwns** [lucko/LuckPerms#1658]
Hi there,

Is it possible to implement some feature that would allow Luckperms to assign a player to a certain group, based on MCMMO skill levels, MCMMO powerlevel, time played on the server etc?

There used to be specific plugins that did this, such as AutoRank, but they seem to be no longer supported. 

Thank you!

**Comment by Andre601** [comment]
LP is not for automatic stuff like this.
You need to use a separate plugin to listen for those specific events to then assign the groups either through commands or the LP-API.

LuckPerms is a permission-plugin and constantly checking for playtime, mcmmo levels or similar would be way out of its use.

**Comment by Gizmopwns** [comment]
Ok, thanks for clarifying.

Sadly there don't seem to be any functional autorank plugins for MCMMO at this time, or maybe I'm not looking in the right place. :p 

Either way it was worth a try.

**Comment by Andre601** [comment]
Can you then close this please?
