### ISSUE TITLE
Colour codes in hovermessages aren't translated to right colour.

### ISSUE THREAD

**Issue by Andre601** [lucko/LuckPerms#1663]
I discovered this when I unset a permission from a group that has a Display name set, but when you hover over a permission does it show the colour/formatting code without translating it to the provided colour/format. A screenshot of this can be seen below.

This is a minor thing, but it's still weird to look at so a correction of this (by f.e. show only the group name, translate the colours or remove them) would be appreciated.

**Screenshot**:
![2019-08-08_16 51 08](https://user-images.githubusercontent.com/11576465/62713570-3e9f4300-b9fd-11e9-9e63-fd5e45ca7a4e.png)

**Comment by lucko** [comment]
This is intentional - the color codes are translated in the actual chat message but not in the hover.

**Comment by Andre601** [comment]
It looks weird tho that it is like that in the hover... The &r is really not needed and could imo be removed.

**Comment by lucko** [comment]
Ahhh okay I see what you mean.
