### ISSUE TITLE
Suffix won't show in another world

### ISSUE THREAD

**Issue by DymaxAnimaSky** [lucko/LuckPerms#1665]
Im using paper 1.13.2 and multiverse, 
![luckperms](https://user-images.githubusercontent.com/53934138/62764400-5ee40600-bac0-11e9-9d5f-656c794127dd.png)
![island](https://user-images.githubusercontent.com/53934138/62764430-758a5d00-bac0-11e9-84fa-5788e49d1c11.png)
As shown in the images, I used the online /lp editor to have the suffix apply in multiple worlds, but as you can see when i was in 'world' , the suffix applies but when i went to 'bskyblock_world' 'bskyblock_world_nether' 'bskyblock_world_the_end' it won't apply. The world name is the same.

**Comment by lucko** [comment]
Most likely because your chat plugin doesn't support multiworld.

Maybe worth using the verbose command to see what's going on?
