### ISSUE TITLE
[Need Support] I tried since some days to prevent ...

### ISSUE THREAD

**Issue by crizyx** [lucko/LuckPerms#1666]
Hello since 5days i tried **to prevent a player in the modo group from modifying a player's groups in the admin group**
I'm using **based-commande-permissions-arguments**, a negate weight ladder (but is not the problem) and this commands /lp user "username" parent set/add/remove membre.
What I remember is that, the weight system does not work with my permission setup.
I searched many times on the wiki but I did not find a concrete way.

__Tried permissions for resolve my problem__:
group.admin **false**
luckperms.user.parent.set.admin **false**
luckperms.user.parent.set.modify.admin **false**
luckperms.user.parent.set.modify.others.admin **false**
luckperms.user.parent.set.usecontext.admin **false**
luckperms.user.parent.set.usecontext.global.group.admin **false**
luckperms.user.parent.set.usecontext.group.admin **false**
luckperms.user.parent.set.usecontext.modify.admin **false**
luckperms.user.parent.set.usecontext.modify.user.parent.admin **false**

eloak is my modo and crizyx my admin, eloak can modify all groups of my admin incule the group admin:
https://cdn.discordapp.com/attachments/362931224571805707/609066690516484171/unknown.png

My weight ladder (No problem with it):
https://cdn.discordapp.com/attachments/362931224571805707/609066906758152200/unknown.png

My permission editor:
https://luckperms.github.io/editor/#yTCNAwxTrK

My plugin config:
https://cdn.discordapp.com/attachments/362931224571805707/609067594607099924/config.yml

My logic of groups:
https://cdn.discordapp.com/attachments/362931224571805707/609351153129357312/LogicladderGroup.png

Do you know how help me ?
Thanks :)

**Comment by crizyx** [comment]
Up

**Comment by mcj201** [comment]
argument-based-command-permissions enables upto 3 extra checks that all have to be true.

Your base command is lp user <user> parent set <group> so first you need to set
- luckperms.user.parent.set.<group> true
to be able to issue the command. (See table in wiki-page)

Then you have to allow editing a user so
- luckperms.user.parent.set.modify.user.* true
to be able to modify yourself and others.

Then you have to allow a context. This allows the global context for every command:
- luckperms.usecontext.global true

You also should set a proper inheritance.
/lp group admin parent add modo
/lp group modo parent set membre
etc.
to then allow admins to additionally set the admin group:
luckperms.user.parent.set.admin true

**Comment by crizyx** [comment]
This is what I have done many times but it does not work, you tried with my settings?
Because there is really everything referenced.

**Comment by fuatcob** [comment]
Hi. Can you do something for me please?
I want you to produce a gist for me on https://gist.github.com/
file name will be **keybase.md**
i'll add the text below, copy and paste it into gist. Finally you should select "create public gist"
You may say "why should i do that?", just for helping me. Thank you for your interest...



### Keybase proof

I hereby claim:

  * I am crizyx on github.
  * I am reyhancob (https://keybase.io/reyhancob) on keybase.
  * I have a public key ASBMXWvV18bzm7i-4KnI85OyHsUCXiHgjtIX9eFjerF_ogo

To claim this, I am signing this object:

```json
{
  "body": {
    "key": {
      "eldest_kid": "01204c5d6bd5d7c6f39bb8bee0a9c8f393b21ec5025e21e08ed217f5e1637ab17fa20a",
      "host": "keybase.io",
      "kid": "01204c5d6bd5d7c6f39bb8bee0a9c8f393b21ec5025e21e08ed217f5e1637ab17fa20a",
      "uid": "4703ceef2719a1cccf69a2f6586c4319",
      "username": "reyhancob"
    },
    "merkle_root": {
      "ctime": 1568457539,
      "hash": "b276a639d725eccdb81255c8515ac9bf9f50d5fb86f36555932fc86d1cb86ba575721e98ea77e556b8b2901876d5bf2e8429d24ecff8653b21ac19e4af6f648d",
      "hash_meta": "990a4cff1bd150428170b2095e8be9592849949ce7dd271a939db264df20e08f",
      "seqno": 7289546
    },
    "service": {
      "entropy": "eNH17QCrKg2gC+SxabXNmgh+",
      "name": "github",
      "username": "crizyx"
    },
    "type": "web_service_binding",
    "version": 2
  },
  "client": {
    "name": "keybase.io go client",
    "version": "4.4.0"
  },
  "ctime": 1568457563,
  "expire_in": 504576000,
  "prev": "c1daee1ebc5ee025ebc0b425afb4bf28b3677d0b8a3f40caa1623584bde13562",
  "seqno": 17,
  "tag": "signature"
}
```

with the key [ASBMXWvV18bzm7i-4KnI85OyHsUCXiHgjtIX9eFjerF_ogo](https://keybase.io/reyhancob), yielding the signature:

```
hKRib2R5hqhkZXRhY2hlZMOpaGFzaF90eXBlCqNrZXnEIwEgTF1r1dfG85u4vuCpyPOTsh7FAl4h4I7SF/XhY3qxf6IKp3BheWxvYWTESpcCEcQgwdruHrxe4CXrwLQlr7S/KLNnfQuKP0DKoWI1hL3hNWLEIBJYfwGHVgpPuV0FJBSPUnIOdf7yjvbM4ruYRF2yCMHdAgHCo3NpZ8RAI8nqZcdDsIWVO0wlMQDBgRtCHutUNOs+pnYNioUXRW8XxxnqCen6AtjtS84/oZQ2lbi2LETch/df/sPZq5JCBqhzaWdfdHlwZSCkaGFzaIKkdHlwZQildmFsdWXEIMq8fu+H43P6eoSnh0mB6nNMPauerDqFBvzUEa1f0b61o3RhZ80CAqd2ZXJzaW9uAQ==

```

And finally, I am proving ownership of the github account by posting this as a gist.

### My publicly-auditable identity:

https://keybase.io/reyhancob

### From the command line:

Consider the [keybase command line program](https://keybase.io/download).

```bash
# look me up
keybase id reyhancob
```

**Comment by fuatcob** [comment]
Hi. Can you do something for me please?
I want you to produce a gist for me on https://gist.github.com/

File name will be **keybase.md**

The attached text file contains the codes, copy and paste it into gist. Finally you should select "create public gist"

You may say "why should i do that?", just for helping me. Thank you for your interest...
[gist.txt](https://github.com/lucko/LuckPerms/files/3612643/gist.txt)

**Comment by Andre601** [comment]
> Hi. Can you do something for me please?
> I want you to produce a gist for me on https://gist.github.com/
> 
> File name will be **keybase.md**
> 
> The attached text file contains the codes, copy and paste it into gist. Finally you should select "create public gist"
> 
> You may say "why should i do that?", just for helping me. Thank you for your interest...
> [gist.txt](https://github.com/lucko/LuckPerms/files/3612643/gist.txt)

Just do it yourself man. You have the option to do so and this is also NOT the right place to ask for favours like that.
Please remove your comment, thanks.

**Comment by fuatcob** [comment]
> > Hi. Can you do something for me please?
> > I want you to produce a gist for me on https://gist.github.com/
> > File name will be **keybase.md**
> > The attached text file contains the codes, copy and paste it into gist. Finally you should select "create public gist"
> > You may say "why should i do that?", just for helping me. Thank you for your interest...
> > [gist.txt](https://github.com/lucko/LuckPerms/files/3612643/gist.txt)
> 
> Just do it yourself man. You have the option to do so and this is also NOT the right place to ask for favours like that.
> Please remove your comment, thanks.

it must be an old account, thats why i'm asking for help.
