### ISSUE TITLE
Suggestion: Change default messaging service

### ISSUE THREAD

**Issue by Andre601** [lucko/LuckPerms#1669]
This was once mentioned in the PR #1537 and I think it would make sense to do so.

The idea is to add a messaging-service (setting) called `auto` that acts like currently `none` does.
`none` is a bit misleading since it technically isn't just none. It acts as `sql` when you use MySQL or MariaDB as database and can cause problems if people don't want to have a messaging service set.
The setting `none` should always do nothing or else it just becomes confusing.

So add the `auto` option as new default, which would do act as sql when using MySQL/MariaDB and else nothing (is disabled).
And when we would make none to actually disable the service, then let us get rid of `notsql` since it wouldn't be used anymore with this new configuration.

**Comment by BrainStone** [comment]
This would be a good change for v5, since that'll break lots of other stuff too.

**Comment by lucko** [comment]
Added in v5 - thanks :)
