### ISSUE TITLE
Not working in kcaldrdon

### ISSUE THREAD

**Issue by popcorn9499** [lucko/LuckPerms#167]
I was trying to load the latest luckperms bukkit legacy build in kcaldron and it failed with an exception.
This is the specific part referencing [luckperms](http://pastebin.com/dHc7xunZ)

The full log is [here](http://pastebin.com/Yc7W6YC9)

Versions:
minecraft 1.7.10
luckperms LuckPerms-Bukkit-Legacy-2.17.55.jar	
kcaldron: 1.7.10-R0.1-SNAPSHOT

**Comment by lucko** [comment]
You need to update ASM. (or stop using outdated software.)

https://github.com/CyberdyneCC/Thermos/issues/498#issuecomment-247083549
