### ISSUE TITLE
Hiding tabbing/commands users can't use when they type '/'

### ISSUE THREAD

**Issue by jessica-jorgenson** [lucko/LuckPerms#1671]
Hey again!
Is there any way to hide like '/summon' or '/enchant' from my users when they do not have the permissions for them? If it's not in LuckPerms, is there another plugin that works with LuckPerms to do this?
Thanks!

**Comment by Andre601** [comment]
If you're talking about hiding the suggestion that is shown when typing / followed by pressing tab, then no: LuckPerms won't manage that. It only checks permissions and returns to the plugin if the player has it or not.
It depends completely on the plugin on how to handle tab-completion when permissions are missing. Some deny/hide it, others don't.

There are plugins that help you hide those commands, but I can't give an example. Just try searching for one on Google. You might get lucky and find one.
