### ISSUE TITLE
LuckPerms shows log messages twice (bungee)

### ISSUE THREAD

**Issue by Sikatsu** [lucko/LuckPerms#1672]
Hey,

So i've installed LuckPerms on both the proxy and the spigot servers, however logs show up twice now. Did I do something wrong?

http://prntscr.com/or32nf

**Comment by Tobi406** [comment]
Are you using the `pluginmsg` messaging service?

**Comment by Sikatsu** [comment]
Yes I am. It shows it once for me when I make a change in luckperms, but when someone else does they see the logs twice.

http://prntscr.com/oul0yt

**Comment by Sikatsu** [comment]
> 13:42:09 [INFO] [LP] LOG > (Console) [U] (ni20ck05)
> 13:42:09 [INFO] [LP] LOG > parent set villager
> 13:42:09 [INFO] [LuckPerms] [Messaging] Received user update ping for 'ni20ck05' with id: afd53817-802c-4e33-9cc8-a65bcb84db29
> 13:42:13 [INFO] [/84.86.12.184:62155] <-> InitialHandler has connected
> 13:42:15 [INFO] [LP] LOG > (Console) [U] (ni20ck05)
> 13:42:15 [INFO] [LP] LOG > parent set novice
> 13:42:15 [INFO] [LuckPerms] [Messaging] Received user update ping for 'ni20ck05' with id: 1b54aa6b-3248-4041-b126-fa3d0664a87b

**Comment by lucko** [comment]
https://github.com/lucko/LuckPerms/blob/c86f6c0f368610152112ece73c898aa0954cfcc9/bungee/src/main/resources/config.yml#L227-L232

:)))

**Comment by Sikatsu** [comment]
@lucko I have that set to true on the proxy and false on the spigot servers, yet it still shows duplicates.

http://prntscr.com/ouqa1i

**Comment by lucko** [comment]
Do you have multiple proxies?

**Comment by Sikatsu** [comment]
I only have one proxy.

Bungee config: https://pastebin.com/86JSjj00 (database leftout, they're all on the same though)
Spigot config: https://pastebin.com/GthK6jYX

**Comment by Sikatsu** [comment]
Any idea?

**Comment by Sikatsu** [comment]
@lucko Any news? :P

**Comment by Sikatsu** [comment]
I disabled it on the proxy and enabled it on all backend servers, that seems to work.

**Comment by Sikatsu** [comment]
Actually no, now the permissions don't sync.

**Comment by lucko** [comment]
That setting only controls whether log entries received from other servers via the messaging service are broadcasted to online players.

It doesn't change any other property of the system, and has no side effects.

**Comment by Sikatsu** [comment]
Yeah, that comment was invalid.

However, setting it to true on the backend servers and false on the proxy stopped the double log messages.

However, it no longer seems to broadcast the logs among all servers. Really not sure what I do wrong.

**Comment by lucko** [comment]
I'm unable to reproduce this now on the latest version. :)

**Comment by Sneakometer** [comment]
I'm facing the exact same problem here using LuckPerms 5.2.35. All messages a broadcasted twice on the server where the command was executed. 
![Screenshot_1](https://user-images.githubusercontent.com/50603525/101684905-670ed580-3a67-11eb-816c-792c23b8d2b6.png)

`broadcast-received-log-entries` is set to false on all bukkit servers and true on proxy.
Also using the pluginmsg channel.
