### ISSUE TITLE
[Suggestion] Allow to override rank expire

### ISSUE THREAD

**Issue by partydragen** [lucko/LuckPerms#1673]
Allow us to overide rank expire time or add time instead already interact error message thing

When Players buying monthly ranks from my store i must set buycraft to execute lifetime, then buycraft remove when it expire 

but if people buy a new month before it expire then it will mess up as the old purchase will remove the rank

Aswell im not able to use the expire placeholders ingame to tell them when it expire

I want buycraft to execute temp commands instead but because of the already interact it will mess up if buycraft executing it to early or it them rebuy a new month of vip before it expired

**Comment by Tobi406** [comment]
If I understand you right, you should be able to use the temporary modifier to achieve what you want. 
Eg. `/lp user <user> parent add vip 1m accumulate` and the user has 2d left, it will be added to the existing time (1m2d now).
You can also set the default the default modifier in the [config.yml](https://github.com/lucko/LuckPerms/blob/master/bukkit/src/main/resources/config.yml#L254L265).

**Comment by partydragen** [comment]
Thanks @Tobi406 It worked :D
