### ISSUE TITLE
Prefix for groups default not work

### ISSUE THREAD

**Issue by JavituRec** [lucko/LuckPerms#1674]
Hey,

I have a prefix and suffix for all groups. The group default have a prefix and suffix. The suffix work correctly but prefix not work. I have been looking at the configuration to see if I was doing something else but everything is correctly configured, exactly as in the other groups.

Defautl perms:
- 'suffix.1.[User]+'
- 'prefix.1.&2[User] '

All the best.

**Comment by Andre601** [comment]
If your problem is that prefixes/suffixes aren't shown in chat, tab or similar, then make sure that they are shown in `/lp group <group> meta info`.
If they are shown there, then this is a issue with your chat plugin, tablist plugin or where you want to use it.
