### ISSUE TITLE
2 Suggestion 

### ISSUE THREAD

**Issue by GameHoundInteractive** [lucko/LuckPerms#1675]
Fix discord link on home page, its currently invalid. also 
add gui control like this: https://www.spigotmc.org/resources/ultra-permissions.42678/ ??

**Comment by Tobi406** [comment]
1.  Discord Link works for me.
2.  See #619

**Comment by GameHoundInteractive** [comment]
nvm about the invite link, It seems i've been banned??? No idea why? I have never done anything wrong in discord servers and i am in over 30 discord servers for spigot plugins???

**Comment by Turbotailz** [comment]
What is your discord username?

**Comment by GameHoundInteractive** [comment]
GHStudios#1425

**Comment by Turbotailz** [comment]
You were banned in February last year for insulting staff. I will unban you but you must follow our rules which includes respecting the staff.

**Comment by GameHoundInteractive** [comment]
I will follow the rules. I don't honestly remember insulting staff. Sorry.

**Comment by GameHoundInteractive** [comment]
Thank you

**Comment by Andre601** [comment]
[response]: https://github.com/lucko/LuckPerms/issues/619#issuecomment-353216667
[Web editor]: https://github.com/lucko/LuckPerms/wiki/Web-Editor
[gui]: https://www.spigotmc.org/resources/53460/

To be a bit more clear about your GUI request...

Your request to add a GUI to LuckPerms is not the first one and it most likely won't be the last either.
Each time this request was made, did Luck decline it for the same reasons.

### What are the reasons?
A complete and detailed list with the reasons behind this decision can be found in the **[issue #619][response]**.

I listed the most important reasons here (Note that this is not the full list and that it is slightly different to summarize certain points):
- **An in-game GUI is limited.**
  - You only have a limited amount of slots to use (54 in total before the GUI would become glitchy).
  - You're limited to items and the text that can be displayed on the screen. Some text might get unreadable if it is too long.
  - You can't show text natively: This means that you have to hover over an item to see what text it has. This wastes time when searching for specific permissions or groups.
- **Text input is only possible through chat or an anvil-GUI.**
  - The chat can't always be used. For example when you have a BungeeCord network and a chat plugin for BungeeCord is used.
  - An anvil-GUI is version-dependant meaning each new version requires LP to update to support it. This makes LP lose its version-independency.
- **LuckPerms supports multiple platforms**
  - GUIs can't be used on all platforms. E.g. BungeeCord doesn't have the required libraries to generate and/or manage inventories.
  - Multiple platforms mean multiple different types of code for GUIs to be used.

### Any other solutions than commands?
There are two solutions for you if you aren't the fan of commands.

#### Web editor (Recommended)
LuckPerms has a web editor that allows you to easily add, edit and remove permissions within your browser and then apply those changes in-game.
The editor is fast, easy to understand and very user-friendly.
In addition, can (visual) changes be made to the editor without requiring LuckPerms to be updated (Exception is if the change depends on what LP sends to/receives from the editor).
You can create a new editor session using one of those commands:
- `/lp editor` for Spigot (and forks), Sponge and Nukkit.
- `/lpb editor` for BungeeCord and its forks.
- `/lpv editor` for Velocity.

You can find additional information on the [Web editor] wiki page.

#### GUI-plugin for LuckPerms (Not recommended)
A member of the LuckPerms community created a plugin called [LuckPerms in GUI!][gui] which adds an in-game GUI to LuckPerms.
That said we do not recommend, nor officially support this plugin. If you encounter problems with it, contact the developer of the plugin and not Luck or the LuckPerms staff.

### Additional information
This is by no means the full (and official) response of Luck.
Again, you can find his general response to this topic in the above-linked issue.
