### ISSUE TITLE
Chat formatting problem

### ISSUE THREAD

**Issue by SamuDu24** [lucko/LuckPerms#1676]
Hello,

I am having a problem with chat formatting. To manage the chat, I use the plugin TownyChat, which is essential to me. I added in the default format {permprefix} so, to display the prefixes.

I have also configured the meta formatting, to display two different prefixes (one representing the player rank and another the Staff rank).

Only one of them is necessarily duplicated, even though I have removed the duplication option.

I leave you below pictures for you to understand, I hope you will help me, thank you very much!

[TownyChat config](https://image.noelshack.com/fichiers/2019/33/1/1565620115-townychat.jpg)
[Meta formatting](https://image.noelshack.com/fichiers/2019/33/1/1565620124-metaformatting.jpg)
[Chat exemple](https://image.noelshack.com/fichiers/2019/33/1/1565620109-chat-result.jpg)

Thanks !

**Comment by Andre601** [comment]
Removing the `duplicates: first-only` does exactly the opposite of what you want. Re-add it to only have each prefix once without any duplicates.

Also, next time add the images directly into your issue by just drag and drop them here to upload or with `![](url-to-image)`

**Comment by SamuDu24** [comment]
Hello,

Thank you for your reply. 
But with or without this option, the result is the same, except that it is the prefix "[Citoyen]" which is duplicated ...

**Comment by SamuDu24** [comment]
Hello,

I'm not one to ask for support as soon as I can not do something. I think I did everything I could on my side, so I turn to you ...

**Comment by SamuDu24** [comment]
Hello,

The problem was actually TownyChat. I would have taken many hours to understand it, but I was not using the good placeholder. Indeed, I had to use {permuserprefix} and not {permprefix} ... Too bad for me.
