### ISSUE TITLE
LuckPerms Command not recognised.

### ISSUE THREAD

**Issue by leon47331** [lucko/LuckPerms#1679]
Hello,
today I installed the LuckyPerms Plugin on my server.
Everything works fine, until the server shutdown.
When I came back home and start the server, it started normally.
When I type the command: /lp group default permission add PrivateMessager.msg in the chat, I became the message that the command is not recognised.
This command works before I shut the server down.
What is wrong with it?

Best regards
leon47331

Server information:
Bukkit Server on 1.8.8
[latest.log](https://github.com/lucko/LuckPerms/files/3498019/latest.log)

**Comment by Andre601** [comment]
Did you try `/lp group <group> permission set <permission>` because permission add is not an option for my knowledge.

Also please use a page like hastebin.com to share logs since not everyone wants to download files.

**Comment by leon47331** [comment]
Oh sorry,
I have made a screenshot from this command.
Now I saw this was the wrong command!
