### ISSUE TITLE
LuckPerms Bungee Error

### ISSUE THREAD

**Issue by PlesCZ** [lucko/LuckPerms#1681]
First error: https://pastebin.com/h61DxXTq
Second error: https://pastebin.com/4iHXtWCF
Bungeecord version: git:BungeeCord-Bootstrap:1.14-SNAPSHOT:34febec:1419 by md_5
LuckPerms version: LuckPerms-Bungee-4.4.28

**Comment by PlesCZ** [comment]
HEYY!!
 FIX!

**Comment by Turbotailz** [comment]
Hey!! Show some respect, Luck can't get to every issue and every error the moment they are posted.

Have you tried updating your bungeecord to the latest version? Removed the libs folder from luckperms and let it regenerate?

What have you done to try and FIX this issue yourself?

**Comment by lucko** [comment]
Possibly a corrupted LuckPerms jar? Try redownloading.
