### ISSUE TITLE
mongodb cluster error

### ISSUE THREAD

**Issue by poompk1pk** [lucko/LuckPerms#1683]
URI:
**mongodb_connection_URI:** 'mongodb+srv://username:password@test1-3bo8j.mongodb.net/test?retryWrites=true&w=majority'

Error: [https://pastebin.com/02Q48nZ1](https://pastebin.com/02Q48nZ1)

Version: LuckPerms-Bukkit-4.4.1
thanks !

**Comment by electronicboy** [comment]
`Caused by: java.net.UnknownHostException: test1-3bo8j.mongodb.net`
The hostname you're trying to use does not exist
