### ISSUE TITLE
Permissions Won't Take Effect In Groups

### ISSUE THREAD

**Issue by RoseaMarie** [lucko/LuckPerms#1684]
Hi, I installed LuckPerms yesterday and I've since been setting it up. /lp editor won't generate a link for me, it tells me to wait a moment and then never gives me a link, so I've been doing everything from within the game. I'm currently trying to set up a Mod group, and I have the prefix set up fine, but no permissions will take effect. I've given the rank to a few of my friends, but none of them are able to do any of the permissions I've set as true (such as minecraft.command.kick and some essentials permissions) but they still can't use them so I've had to give them OP for the time being while they build some stuff. The chat will tell me that the permission has been set to true in the Mod group, but it still won't work.

When i check the group info, it only lists the first 6 permissions as being configured, and when I cleared the permissions  it only showed 6 permissions as being removed, so I don't know where the rest of the ones I set went to. The ones that are shown as being true still don't work either. (Like I can't use the essentials Free sign thing, doesn't work when I right click unless I'm oped, can't set weather, etc) Does anyone know why this is happening or how I can get the editor to work? Thanks.

**Comment by Imortalshard** [comment]
Hi RoseaMarie,

Firstly, with the web-editor, what errors are you getting in the console when you try to use /lp editor?

Secondly, the default minecraft kick command is probably being overridden by the essentials plugin. The best way to debug most common permission issues is to use the verbose feature, this will give you a list of all the permissions being checked for when you use certain commands or perform certain actions.

You can read more about it here:
https://github.com/lucko/LuckPerms/wiki/Verbose

Thanks,
Imortalshard.

**Comment by RoseaMarie** [comment]
It gives me the error 

> pool-7-thread-1/WARN java.lang.RuntimeException: java.net.ConnectException: Failed to connect to bytebin.lucko.me/2606:4700:30:0:0:0:681b:976a:443

over and over again in the console when I do /lp editor

**Comment by lucko** [comment]
Your server is not able to connect to the editor server.

This isn't a LuckPerms error (probably!).

More likely an issue with your servers networking.
