### ISSUE TITLE
/lp editor won't generate link

### ISSUE THREAD

**Issue by RoseaMarie** [lucko/LuckPerms#1685]
When I enter the command /lp editor, it tells me it's generating the link but it never gives me one. I updated to the latest version but it still won't work, and I'm not able to configure groups.

**Comment by Andre601** [comment]
[in-game commands]: https://github.com/lucko/LuckPerms/wiki/Command-Usage

You can still configure groups, just not through the editor, but through [in-game commands].
Did you check the console for any errors?

**Comment by RoseaMarie** [comment]
> You can still configure groups, just not through the editor, but through [in-game commands](https://github.com/lucko/LuckPerms/wiki/Command-Usage).
> Did you check the console for any errors?

I've tried configuring groups within game, and it says it should be working however the permissions don't actually take effect. Even though they're listed as true and functional, it doesn't actually let people use said commands when given the group.

**Comment by Andre601** [comment]
Then it's most likely the wrong permissions.
We can't help you without any actual information. You so far only said to us that something isn't working without telling us **what**.

**Comment by RoseaMarie** [comment]
I've been using the command /lp group {GROUP} permission set {permission} and the console says they're set as true but it doesn't work. I'm using the permissions from the drop down menu it gives (Like essentials.kick) and I've checked perm lists and used what it says but they still dont function.

**Comment by lucko** [comment]
Try testing with the verbose command.

Most likely just the wrong permission being set.

https://github.com/lucko/LuckPerms/wiki/Verbose
