### ISSUE TITLE
When enable use-server-properties-name server can't start.

### ISSUE THREAD

**Issue by Focusprw** [lucko/LuckPerms#1688]
https://pastebin.com/1GEaDQQ1

use-server-properties-name: true
Version paper 1.14.4

**Comment by Andre601** [comment]
The server name was removed somewhere around 1.13 and 1.14, making the setting in the server.properties useless and redundant... And as you may expect does it also cause those errors when a plugin tries to load the settings while they aren't supported anymore.
Disable the setting and set an own server name in the LP config (first option)
