### ISSUE TITLE
Server crash after giving a group Sethome permission

### ISSUE THREAD

**Issue by DaymnPhil** [lucko/LuckPerms#1692]
Hey there! i'm starting a server and for my twitchsub group the permission essential.back does work but when i put in the set home nodes my server crashed an all my plugins couldnt load anymore here is the crashlog:

![crash](https://user-images.githubusercontent.com/54237320/63224008-668d6400-c1be-11e9-84b6-4956e9f31c74.gif)

i hope you can help me out!

**Comment by BrainStone** [comment]
The file you uploaded is corrupted. Download it again and put it on your server.  
And use the latest version from here:  https://luckperms.github.io/

**Comment by Andre601** [comment]
Also don't spam an issue with empty lines
