### ISSUE TITLE
[Question] Special characters in prefixes

### ISSUE THREAD

**Issue by dzineit** [lucko/LuckPerms#1693]
Desired outcome: setting prefix to ( ͡° ͜ʖ ͡°)
Command tried: lp user dzineit permission set prefix.1.( ͡° ͜ʖ ͡°)
Result: "[22:33:37 INFO]: [LP] Set prefix.1.( to true for dzineit in context server=͡°, world=͜ʖ."

How would I set the prefix to ( ͡° ͜ʖ ͡°) globally without LuckPerms interpreting it as specifying a server and world?

**Comment by Turbotailz** [comment]
Put quotes around the prefix.

Also there is a better command for setting prefixes: /lp user <user> meta addprefix <weight> <prefix>

**Comment by dzineit** [comment]
Great, thanks
