### ISSUE TITLE
Hack?

### ISSUE THREAD

**Issue by 1RIeN1** [lucko/LuckPerms#1694]
Hello, the other day on my server through the nickname of another player and the console and other servers gave permissions.But the server ports were closed, luckperms commands were blocked on all servers, uuid protection was.As I was told, hacking through LuckPerms itself is possible. Sorry for my English. Servers BungeeCord

**Comment by Andre601** [comment]
This is not possible at all.
The only way someone could gain access to op or the * permission is either
1. Joining with a cracked account that has the name of a certain user on a cracked server.
2. Gain access to such an account or
3. Using a plugin that hooks into LP to grant permissions.

**Comment by 1RIeN1** [comment]
@Andre601 We checked by logs, it connected via bungeecord.All plugins written without hacks.LP commands cannot be written.But in action luckperms you can see how he gave himself * and other permissions through console players.Can say checked.

**Comment by 1RIeN1** [comment]
@Andre601 There is a check uuid and nick. He could not connect through the nickname of another.Even if he connected, he could not write luckperms commands.

**Comment by 1RIeN1** [comment]
@Andre601 But we have suggestions that in bungeecord when luckperms registers a channel, you can connect to it

**Comment by Andre601** [comment]
This doesn't mean it's caused by LP. It could be more a misconfiguration on your end. There can always be something that we made wrong, but without any proof and with just claims, there is no way we can check what is happening.

**Comment by 1RIeN1** [comment]
@Andre601 sadly

**Comment by lucko** [comment]
Most likely due to no firewall setup on your BungeeCord proxy.
