### ISSUE TITLE
Suggestion: Web Editor Offline Users

### ISSUE THREAD

**Issue by TheOnlyMaldred** [lucko/LuckPerms#1695]
Currently the Web Editor with the `users` argument only works on online players. Could we get a feature (maybe in the config somewhere) to also load offline users using `/lp editor users`?

I understand this can be nasty when you have a lot of players loading into the cache, but it'd be nice to still have this feature available if at all possible?

**Comment by ktole1999** [comment]
or the ability to load/unload an offline user?

**Comment by Andre601** [comment]
This wouldn't efficient, considering how many players a server could have.
Imagine LP loading hundreds if not thousands of offline players for the web editor. This would either break the editor, bytebin (the site Luck made to temporary store info for/from the editor) or LuckPerms itself...
You can load a single user through `/lp user <user> editor` even if he's offline... For editing multiple players at once to give, remove or change permissions to a certain one use the bulk edit option.

**Comment by lucko** [comment]
It's a possibility with the new version - but it would be capped in terms of users.

**Comment by Turbotailz** [comment]
> it would be capped in terms of users.

What kind of cap are we thinking?

**Comment by lucko** [comment]
@Turbotailz I was thinking 1000? Sound manageable?

**Comment by Turbotailz** [comment]
We can give it a go 👌

**Comment by lucko** [comment]
Added in v5
