### ISSUE TITLE
Permissions updates not being recognized at random cases

### ISSUE THREAD

**Issue by markusew** [lucko/LuckPerms#1696]
Hi, I'm having an issue with luckperms not recognizing permission updates at random. For example; if a player is promoted along a track (/lp promote <track>) it sometimes bugs out and the user is left without both the permission for the previous group they upgraded from and the group they upgraded to. This is however "fixed" when the user relogs or a lp sync occurs. So the database stays "correct" but the user doesn't have their permission dynamically update during the session. This can happen with any add/removal of permissions. Again, this is seemingly random and I haven't found a way to recreate it with certainty.

I started having this issue when updating from LuckPerms 4.3.2 to 4.3.73 on the 17th of March this year. At the same time as updating this I also put LuckPerms on the bungee but that was later removed from the bungee.

I've also seen this happen with SQLite under the same config so I don't think it's an issue with a remote database/my database.

Currently using LuckPerms 4.4.28 on paper-641(1.13.2)
Here's a copy of one of the configs: https://hastebin.com/keqawafitu.shell

Any help is appreciated and I'll gladly provide more information if needed. Thanks!

**Comment by Andre601** [comment]
Are there any errors in the console when this is happening?

**Comment by hihihih565** [comment]
> Are there any errors in the console when this is happening?

No, there are no errors in the console when this happens.

**Comment by markusew** [comment]
Nope, no errors. In the console it's listed normally as someone being promoted along a track or someone having a permission set to their profile. So everything looks like it works and the database is updated correctly but the players permissions needs to be reloaded/re-synced for it to work.

**Comment by hihihih565** [comment]
Any update on this?

**Comment by lucko** [comment]
Very difficult for me to debug/fix without any reproduction steps, other than just kinda staring at the code and hoping to see something.

It does some similar to some other undiagnosed issues with the plugin, namely #1330

**Comment by lucko** [comment]
I think this was probably another bug caused by the issue fixed here. 4d3c692402398ca20cabc57dd669225048efbf32
