### ISSUE TITLE
Promoting a player along track sometimes breaks permission

### ISSUE THREAD

**Issue by hihihih565** [lucko/LuckPerms#1697]
When promoting a player across a track, sometimes it causes the player's permissions to break making them unable to do anything, relogging or running /lp user {player} info will fix the player's permission, currently storing players permission info via mysql.

**Comment by Andre601** [comment]
This is a duplicate of #1696 

Please comment on that issue before making your own one thanks.

**Comment by lucko** [comment]
duplicate of #1696
