### ISSUE TITLE
Give permissions on just one group of a track

### ISSUE THREAD

**Issue by Maestrie** [lucko/LuckPerms#1702]
Hy, 

Is there a way to give acces to the promote and demote command but not to be able to set a higher group to yourself? 
my goal is to give for example moderation rights but if I do that moderators are also going to be able to promote themselves to administrators.

thanks for your reply

Maestrie

**Comment by Andre601** [comment]
The [Argument based command permissions](https://github.com/lucko/LuckPerms/wiki/Argument-based-command-permissions) are exactly what you're searching for.
