### ISSUE TITLE
Capital Letters in my Username

### ISSUE THREAD

**Issue by odysseydead** [lucko/LuckPerms#1706]
So my IGN is FoundOdyssey, but the permission manager retains my name as foundodyssey.
So it's not counting me it as me?? The commands using my name like /lp user FoundOdyssey parent add Owner. Works but I never get the prefix or the commands because it really adds foundodyssey.

**Comment by Tobi406** [comment]
Is the group and/or the prefix showing in `/lp user FoundOdyssey info`?

The case of the letters shouldn't matter, because it is still the same UUID

**Comment by odysseydead** [comment]
Yes it is showing up under there.
