### ISSUE TITLE
Malformed JSON Data

### ISSUE THREAD

**Issue by CarrlosM** [lucko/LuckPerms#1709]
After setting the weight of a group I receive
> There was an error whilst saving group data for gold

Then checking at the json file I see

```{
  "name": "gold",
  "permissions": [
    {
      "permission": "weight.2"
```

It completely removed the set prefix and didn't properly close the tag.

The command threw this error https://pastebin.com/FG0AgypN

Running Spigot 1.8.8-R0.1 and LuckPerms 4.4.1

**Comment by Andre601** [comment]
Download the latest version from the jenkins page and maybe recreate the files.

**Comment by lucko** [comment]
Try deleting that group file and then restarting your server.
