### ISSUE TITLE
bot attack and crash Luckperm

### ISSUE THREAD

**Issue by EduBRz** [lucko/LuckPerms#1711]
version git-Paper-175 (MC: 1.14.4)

link crash https://pastebin.com/kA9Eapi9

**Comment by BrainStone** [comment]
LuckPerms can only handle so many new players per second.  
It is your responsibility to protect your server from spam attacks.
Easiest way to do that is by turning on online-mode. If you choose not to do that what you are experiencing is a known risk and blaming other plugins is not the right way to go about it.

**Comment by Andre601** [comment]
If you keep using a server in offline-mode, get an anti-bot plugin that handles bots on the packet level.
This will prevent them from joining in the first place, preventing the PlayerPreLoginEvent to get fired which in term causes LP to create/load the user info.

As BrainStone said is running a server in offline-mode a risk and bot-attacks like these will be a daily issue you'll encounter. There isn't anything Luck can do to prevent this. It is your responsibility to handle and fix this.

**Comment by Turbotailz** [comment]
![image](https://user-images.githubusercontent.com/10846855/63769288-d1a10e00-c915-11e9-9a8c-6f80597e6c0f.png)

**Comment by BrainStone** [comment]
That statement here shows that you cleary have absolutely no clue how any of this works.

The specific reason LP crashes while PEX doesn't is quite simple. When a new player joins LP stores that. PEX doesn't. LP does so because it needs to. This is not some optional process that can postponed.

In orther words LP does more. Especially when it comes to storing the data of player.

Though while you have prevented the issue of your server crashing from being overloaded you have sacrificed functionality and support (good luck getting any response from the PEX dev if you were to have this (or any really) issue with PEX) and are still left with your core problem.

**Comment by Andre601** [comment]
> I solved here by returning PermissionsEx because there are no bugs like luckperms

So working as intentional is now a bug... Noted.

**Comment by DimitarBogdanov** [comment]
> 
> 
> I solved here by returning PermissionsEx because there are no bugs like luckperms

Have fun updating to any new version with a plugin, last updated 3 years ago, for 1.11/.10/.9 that is much more limited compared to LuckPerms.

**Comment by Andre601** [comment]
> "My father once told me that the winning team doesn't move"

I never in my life saw a soccer team winning by not moving.
You just try to excuse why you can't afford MC (which is stupid anyway considering MC is a rather cheap game compared to other ones) and not even try to fix the issues. We gave you ideas how you could solve this but instead, you just switch to an outdated, not supported version of a Permission-plugin that I'm sure will also cause issues once the next heavy bot-attack will arrive.
Just do what we suggested (Getting a proper anti-bot or at least set up some firewall stuff) to solve this... Or just get MC legit. If you can afford to host a server then you sure can buy mc.

**Comment by DimitarBogdanov** [comment]
> can't afford MC (which is stupid anyway considering MC is a rather cheap game compared to other ones)

While I respect your point; this is very incorrect. OP said they live in a poor country. Social statuses cannot be judged. OP cannot do anything to fix their country's financial problem.

**Comment by BrainStone** [comment]
Keep in mind OP that you can solve the bot problem without using online mode.

**Comment by Andre601** [comment]
Also, since you moved to PEX, can you please close this issue as having it open doesn't really serve a good purpose.
