### ISSUE TITLE
server crash when using luckperms (bungee and papermc)

### ISSUE THREAD

**Issue by stw222** [lucko/LuckPerms#1712]
im not 100% sure if luck perms is the cause of this, but according to console, im supposed to report to any plugins mentioned first
[https://pastebin.com/rHpNyHxw](https://pastebin.com/rHpNyHxw)

**Comment by Andre601** [comment]
The first plugin appearing is actually `com.github.mrivanplays.announcements.shades.org.apache.commons.io.IOUtils.toString(IOUtils.java:1198)[0m`
