### ISSUE TITLE
Permissions say undefined

### ISSUE THREAD

**Issue by MajorGoodHeart** [lucko/LuckPerms#1713]
When users parent is inheriting from other parents (rank inheriting from default for example) a lot of the permissions say UNDEFINED when using /lp check user command,  and user gets a no permissions statement when trying to use them.  I am using 1.13.2 Spigot, LP version 4.4.1 upgraded from GroupManager.

Permissions are correct in the group and verified inheritance is set in global.

**Comment by Andre601** [comment]
undefined just means that permission isn't set yet.

**Comment by Andre601** [comment]
When you set the permissions on the web editor and then applied the changes (clicked the save icon and then copy-pasted the command) the permissions should take effect nearly instantly.

**Comment by Andre601** [comment]
Make sure you actually use the right permissions.
You can find them with the verbose command.

**Comment by Andre601** [comment]
Did you actually remove GroupManager?

**Comment by Andre601** [comment]
Can you please provide a list of your plugins

**Comment by Andre601** [comment]
I can't see anything that could cause issues.
Did you restart the server after migration or just used PlugMan (Which isn't recommended.)

Also try latest dev version from https://luckperms.github.io

**Comment by Andre601** [comment]
I'm out of ideas... We have to wait for @lucko to take a look.

**Comment by BrainStone** [comment]
Make sure there are not any spaces before or after the permission in the webeditor. And capitalization matters

**Comment by lucko** [comment]
Please try debugging with the verbose command.

https://github.com/lucko/LuckPerms/wiki/Verbose
