### ISSUE TITLE
How to fix multiple prefixes using luck perms. 

### ISSUE THREAD

**Issue by FlareonOCE** [lucko/LuckPerms#1716]
![image](https://user-images.githubusercontent.com/54440984/63907192-dbce2400-ca5d-11e9-9194-7d8d4bdf4088.png)
How do I remove the double prefix, I am using essentials chat is there a specific line I need to enable or disable :3

**Comment by Turbotailz** [comment]
This isn't a LuckPerms issue but you have most likely set `{PREFIX}{DISPLAYNAME}` in your Essentials chat config.

Simply remove `{PREFIX}` and it should work. The `{DISPLAYNAME}` adds the prefix and suffix to the user's name.

If you don't want that functionality, you can turn it off with a setting earlier on in the config, something like `add-prefix-suffix`.
