### ISSUE TITLE
how can I set a group for a player using the API plug-in

### ISSUE THREAD

**Issue by muffincolor** [lucko/LuckPerms#1717]
Hello, how can I set a group for a player using the API plug-in? I tried to create a new node and add it to the player, but that didn't work. And still it is necessary to establish this group for a while.

**Comment by Andre601** [comment]
[Wiki]: https://github.com/lucko/LuckPerms/wiki/Developer-API
[Javadocs]: https://javadoc.io/doc/me.lucko.luckperms/luckperms-api/4.4
[Discord]: https://discord.gg/luckperms

I would recommend you to either read the [Wiki] about the API, the [Javadocs] of it or join the [Discord and ask in the #api channel.

**Comment by muffincolor** [comment]
I already read the documentation for the API and asked the discord two times. Due to a misunderstanding, he went into discord, but received no answer

**Comment by Andre601** [comment]
Patience is a rare ability

**Comment by muffincolor** [comment]
Of course, but tech support doesn't respond for days

**Comment by Andre601** [comment]
Please keep in mind that we indeed aren't tech support.
We're all collaborators to the LuckPerms plugin one way or the other. We aren't obligated in any way to respond to you at all. It's completely up to a person to decide if they want to provide support or not. And perhaps do not all people know and use the API?
