### ISSUE TITLE
Setting players rank (position in track) instead of promoting?

### ISSUE THREAD

**Issue by CreeperSlayer523** [lucko/LuckPerms#1720]
Is there a way to set a players rank within a track instead of promoting a demoting them?
I ask this due to a complication that would arise if my players were to try and buy a donator rank.

**Comment by Turbotailz** [comment]
[`parent settrack` command](https://github.com/lucko/LuckPerms/wiki/Command-Usage:-Parent#lp-usergroup-usergroup-parent-settrack)

**Comment by CreeperSlayer523** [comment]
Many thanks!
