### ISSUE TITLE
Execute Command via Command Block

### ISSUE THREAD

**Issue by imsmn** [lucko/LuckPerms#1721]
Hey,

is there a way to execute a command like /lp user ... parent add player with a command block?
It seems that replacing ... with @p doesn't work. 
Main reason is that I want to add a user to the player group after he read the rules by clicking a button.

**Comment by Andre601** [comment]
Command blocks are - to my knowledge - not supported by plugins or spigot in general.
The plugin has to either support the command blocks, or spigot has to add support for the selectores like @p (See https://hub.spigotmc.org/jira/browse/SPIGOT-4295)

**Comment by imsmn** [comment]
Thanks for the response. Do you know any other way to add a player to a group? Is there a way to issue a command after a certain time for a player?

**Comment by Andre601** [comment]
After searching "Give permissions after certain Playtime Spigot"
https://www.spigotmc.org/resources/1-8-1-13-playtimerewards.60266/
