### ISSUE TITLE
permissions wont take affect?

### ISSUE THREAD

**Issue by transdino** [lucko/LuckPerms#1722]
I set my perms correctly and they even show up on the web editor. i have 3 groups and they're all connected. i have default -> mod -> owner. All of the perms though won't work for even the default group. what is wrong? I'm using LuckPerms 4.4.1

**Comment by Tobi406** [comment]
Have you tried debuggig with [Verbose](https://github.com/lucko/LuckPerms/wiki/Verbose)?

**Comment by transdino** [comment]
> Have you tried debuggig with [Verbose](https://github.com/lucko/LuckPerms/wiki/Verbose)?

how would i debug with it? i tried on and it just spammed chat

**Comment by Turbotailz** [comment]
Did you read further on into the page? It explains about filters which help avoid the spam.

**Comment by transdino** [comment]
yeah i tried to look into the filters. and it only says I (i'm OP) have the /help but in the web editor it said everyone had it

**Comment by Turbotailz** [comment]
Never debug permissions with OP, of course it's going to tell you that you have everything.

De-op yourself, put yourself in the group you are trying to debug and try again.

**Comment by transdino** [comment]
okay I de-oped myself and i ran the command in the console and now it shows no one has the commands i filtered

**Comment by Turbotailz** [comment]
So it is saying `undefined` next to the permissions? Please be more specific.

If so, that means you have not set the permission.

**Comment by transdino** [comment]
in the webeditor it says i did. what do i do? should i remove all the perms and redo them?

**Comment by Turbotailz** [comment]
Post your web editor link, and share a screenshot of what verbose shows.

**Comment by transdino** [comment]
https://luckperms.net/editor/#8OPajRlzeH and 
![unknown](https://user-images.githubusercontent.com/54754130/64071711-ef3fe180-cc4d-11e9-8a42-9e91d2e4ad85.png)

**Comment by transdino** [comment]
and this when i tried /help 
![unknown](https://user-images.githubusercontent.com/54754130/64071730-683f3900-cc4e-11e9-9cfb-ad3fcb64f99d.png)

**Comment by Turbotailz** [comment]
You haven't added any permissions correctly, you have just added the end of each node, you need to use the FULL permission not just the end of it.

**Comment by transdino** [comment]
oh hell okay
