### ISSUE TITLE
Promote via the API

### ISSUE THREAD

**Issue by dirtyequi** [lucko/LuckPerms#1726]
Hi,

how can I promote a user along a track via the API? This is not documented and I cannot find anything in the API to do so.

Thanks

**Comment by NgLoader** [comment]
https://github.com/lucko/LuckPerms/wiki/Developer-API:-Usage#modifying-usergroup-data

**Comment by NgLoader** [comment]
Example:

```java
public void givePermission(UUID uuid, String permission) {
UserManager userManager = luckPermsApi.getUserManager();
CompletableFuture<User> userFuture = userManager.loadUser(uuid);
userFuture.thenAcceptAsync(user -> {
user.addPermission(permission);
});
}
```

**Comment by NgLoader** [comment]
Node: to add a player in a group set the permission "group.<groupName>"

**Comment by dirtyequi** [comment]
This is not a real promotion. The plugin knows which groups are in which track and it should definitely find the next group by itself, without me telling the API what to do.
Sorry, but this is complete nonsense. Beides, your example only covers the part of adding the group, but you omitted the unsetPermission part (which is also part of the promotion).

So if the API cannot promote users along a track, see this as a feature request.

**Comment by Turbotailz** [comment]
Luck has overhauled the API for v5, it probably has already been done.

**Comment by lucko** [comment]
`promote` method in the `Track` interface.

https://github.com/lucko/LuckPerms/blob/34db10edeb08a9adb3cc4d73181c23f3c4a7e103/api/src/main/java/me/lucko/luckperms/api/Track.java#L89-L97
