### ISSUE TITLE
Editor css fix

### ISSUE THREAD

**Issue by MNLaugh** [lucko/LuckPerms#1727]
Hi, can you please set this properties on autocomplete ul css:
overflow: auto;
max-height: 430px;

Thanks, bye.

**Comment by Turbotailz** [comment]
The editor is getting an upgrade and this issue has been addressed but thank you for the suggestion.

**Comment by Andre601** [comment]
Also for the next time report this to the right repository, namely [lucko/LuckPermsWeb](https://github.com/lucko/LuckPermsWeb) or in the case of the update [Turbotailz/LuckPermsWeb](https://github.com/Turbotailz/LuckPermsWeb)
