### ISSUE TITLE
I need Help with lp!

### ISSUE THREAD

**Issue by ItzTracer** [lucko/LuckPerms#1730]
every time i create a group its fine. I do /lp group owner meta addprefix 1 "Owner " And its fine! But when i do /lp user ItzTracer parent add Owner It works, but it never ever for any group or player, makes the prefix before name: Like This: "Owner ItzTracer" It never works, when i type or talk it just says: ItzTracer. I have searched and watched many videos, and none seem to work. Please Help.

**Comment by Tobi406** [comment]
Is the prefix showing in `/lp user <user> info`?

**Comment by TheOnlyMaldred** [comment]
Did you install a chat formatting plugin?

**Comment by ItzTracer** [comment]
???
Do you recommend any?

**Comment by ItzTracer** [comment]
i do have installed: Chat Control

**Comment by Andre601** [comment]
Make the following steps:
1. Check if the prefix is shown in `/lp user <user> info` as Tobi asked you to do.  
If it does show up, go to step 3.
2. If it doesn't show any prefix, set one with `/lp group <group> meta addprefix <weight> <prefix>`  
Use double quotes to use spaces at the start/end (example: `"my prefix "`)
3. Make sure you have Vault installed (Spigot) and a supported chat plugin. Any chat plugin that supports vault does support LP.
4. If you're using a chat plugin on BungeeCord, make sure it supports LuckPerms Bungee.

**Comment by ItzTracer** [comment]
What Chat Plugins do you recommend? (I am using minehut, so my options are limited)

**Comment by Andre601** [comment]
ChatControl does support Vault and therefore should support LuckPerms.
Just make sure that you have Vault installed.

**Comment by ItzTracer** [comment]
i do but it still no work

**Comment by Andre601** [comment]
Go over the steps I mentioned earlier

**Comment by ItzTracer** [comment]
i did

**Comment by ItzTracer** [comment]
they all have prefixes and when i do /lp user itztracer info it says my prefix. but not when i type in chat

**Comment by Andre601** [comment]
Then it's an issue on your chat plugin and not LuckPerms as it has the prefix set and provides it as usual.

**Comment by ItzTracer** [comment]
should i use essentialschat?

**Comment by ItzTracer** [comment]
i downloaded essentials chat, And it works now! ty for all the help.
