### ISSUE TITLE
One user always has lag

### ISSUE THREAD

**Issue by SirBlobman** [lucko/LuckPerms#1732]
Posted in discord but I think it got lost when other people needed help

One of my players is complaining about lag and he is the only one having these issues during chat and chest opening

Wondering if this has anything to do with it (he is the only one having the Vault handler issue)
https://hastebin.com/irihidagid.md

As you can see, it took 3 seconds for his chat message to actually send
but if I sudo anyone else, their message is instant

**Comment by lucko** [comment]
Your hastebin won't load for me - could you try https://paste.gg

**Comment by SirBlobman** [comment]
Not having the issue anymore, maybe it was just a glitch. I'll reopen this if it happens again
