### ISSUE TITLE
[v5] Undo and Redo

### ISSUE THREAD

**Issue by BrainStone** [lucko/LuckPerms#1734]
I think it's time to elevate this plugin to the next level.

By adding undo and redo. More than once have I (and countless others) mistyped a command or made an error in the editor (before noticing of course) and therefore messed something up.  
While I agree that backups are a must, you can't always rely on them. Because you usually make backups before and after big changes. Not during. Meaning that if you mess up during working on the permissions you're screwed.

So having a history of changes (especially with webeditor applies) you can go back and forward in would be incredibly useful. It does not need to be infinite (like the last 100 or 1000 (config value)) changes are preserved and only commands need to be captured.

**Comment by lucko** [comment]
Sorry, this is really unlikely to be ever added - the complexity behind such a system is just a bit too much.

Undo/redo in the web editor is good enough imo.

I'll accept a PR for it, but not something I'm going to work on.

**Comment by BrainStone** [comment]
How about an autobackup functionality? Aka creating a backup before webeditor changes are applied?
