### ISSUE TITLE
Feature Request: meta command add

### ISSUE THREAD

**Issue by klugemonkey** [lucko/LuckPerms#1736]
Would like to have a meta command for add/remove that would work on a numeric value.

Right now you can set a value with

/lp user/group <user|group> meta set <key> <value>

What I propose is adding commands for add and remove: 

/lp user/group <user|group> meta add <key> <amount>
/lp user/group <user|group> meta remove <key> <amount>

that would increase/decrease the meta's value by the amount.

The typical use case is where you give a player some meta value that represents a capability,  and you want to allow them to purchase addition amounts that would increase this number.

For example, lets say I have a warp plugin that allows players to have a number of warps defined by a meta value.  I could give them a default value in this meta, then allow them to use a command to increase this value that is run when the user purchases additional warps through a shop plugin.

Or perhaps the meta is the maximum listings in an auction house.  With a shop plugin, the user purchases additional slots that are added by the command and increases the meta value.

**Comment by lucko** [comment]
Technically meta values are just strings, so in my opinion it doesn't make sense to implement a command to increment/decrement them.

I think this would be best served by the plugin which is using/modifying the meta value.
