### ISSUE TITLE
Selective command permissions

### ISSUE THREAD

**Issue by lucko** [lucko/LuckPerms#174]
Pretty low priority, would be cool though.

### `/lp user <user> promote <track>`
Currently checks for luckperms.user.promote

Should be changed to check:
* luckperms.user.promote.\<track\>.\<group promoting to\> (if false return, if true allow, if undef continue)
* luckperms.user.promote.\<track\> (if false return, if true allow, if undef continue)
* luckperms.user.promote (if true, allow, otherwise deny)

Should be the same for demote.

### `/lp user <user> parent add <group>`
Currently checks for luckperms.user.parent.add

Should be changed to check:
* luckperms.user.parent.add.\<group\> (if false return, if true allow, if undef continue)
* luckperms.user.parent.add (if true, allow, otherwise deny)

Should be the same for permission equivalents.

## How to determine whether players can actually use the command
I guess this should be achieved through parsing the command string directly. Instead of doing the check at execution, it will be done ahead of time.

**Comment by BiGUNMAN** [comment]
This would be really useful imo.

**Comment by FireFliesMC** [comment]
I would love this to be added, but also with **/lp user <user> parent remove <group>** and as permission **luckperms.user.remove.<group>**
