### ISSUE TITLE
Multiple perm adding

### ISSUE THREAD

**Issue by Arkkanus** [lucko/LuckPerms#1743]
I am unable to find a local file for adding bulk perms in 1 go. with cmi for an example i have to add 17 individual perms just for access to armor stand editing. Is there a way the web editor can allow for pasting in multiple perms in one go. or can someone tell me the location of the file so i can do it there to save some time? Thanks alot.

**Comment by Turbotailz** [comment]
Currently the web editor does not allow for bulk adding. It will be added in the next version.

Also the default storage type is not editable (assuming you haven't changed it). If you want the ability to copy/paste bulk permissions then you may need to consider changing it to YAML. Be sure to follow [this guide](https://github.com/lucko/LuckPerms/wiki/Switching-storage-types) if that is what you want to do. Be aware that editable database types are [generally not recommended](https://github.com/lucko/LuckPerms/wiki/Storage-types#text-config-files).

Another thing - remember that wildcard and regex permissions are possible, so if your CMI permissions follow a similar pattern, you could just add one permission that covers them all (e.g: `cmi.armorstand.*`).

**Comment by Andre601** [comment]
Also, requests for the web editor should be made on the right repository, which in this case is [lucko/LuckPermsWeb](https://github.com/lucko/LuckPermsWeb) or for the future update [Turbotailz/LuckPermsWeb](https://github.com/Turbotailz/LuckPermsWeb)
