### ISSUE TITLE
How to hide suffixes in chat display?

### ISSUE THREAD

**Issue by Yronusa2000** [lucko/LuckPerms#1744]
Hi,
I'm using Luckperm 4.4.28 as permissions plugins and EssentialsChat as ChatFormater.
In the EssentialsChatconfig, I can't control the display of the suffixes and prefixes: 

`format: '{factions_relcolor}§l{factions_roleprefix}§r{factions_relcolor}{factions_name|rp} &7{DISPLAYNAME} &7:&r {MESSAGE}'`

I guess the prefixes and suffixes are a part of the "DISPLAYNAME" placeholder. I need suffixes to show it in the TAB, but I don't want to keep it in the chat formater.

Thanks you in advance! ;)

**Comment by Tobi406** [comment]
Try something like `&7{PREFIX}{USERNAME}` or `&7{PREFIX}{PLAYERNAME}` instead of `&7{DISPLAYNAME}`.

Also, please note, that your issue isn't actually relating to LuckPerms, but anyways, I hope my solution works for you.
