### ISSUE TITLE
Is it possible for the same world to have multiple aliases?

### ISSUE THREAD

**Issue by k0nker** [lucko/LuckPerms#1745]
Is this possible?

> world-rewrite:
>   113s: normal
>   113c: normal
>   113c: creative
>   114s: normal
>   114c: normal
>   114c: creative

With that when you define a perm as applying in "normal" world it would apply to all of them. Then if you define a perm as applying in "creative" it would only apply to 113c and 114c since they have that alias as well.

**Comment by lucko** [comment]
Sorry for the super late reply - unfortunately no this isn't directly possible.

A world can only be "remapped" to one other world with this system.
