### ISSUE TITLE
Adding Regex to the unset command

### ISSUE THREAD

**Issue by Flavourized** [lucko/LuckPerms#1746]
Hello,

I wanted to suggest adding Regex support to the unset command. I need to remove a number of permissions all starting with the same string, but i need to do it on a per user basis, as i am running some other commands based on how many permissions that user has, etc. 

I asked in discord and was told that Regex is only meant for adding permissions, not deleting.

**Comment by lucko** [comment]
I think this is probably out of scope for the plugin at this stage.

I'm going to close this suggestion on the basis that it's unlikely to make it into the main plugin in the near future. A quality PR implementing this functionality would likely still be accepted, but it's not something I'm going to work on. :)
