### ISSUE TITLE
Command to add player to multiple groups without changing parent

### ISSUE THREAD

**Issue by Stager83** [lucko/LuckPerms#1747]
I need a command to add a user to a group. Some users have more than one group but the "/lp user {name] parent set hero" for example will change the group since it is parent command. I need a command that will just add the player to another group. I can do this in the webgui but I need the command since it is for buycraft.

**Comment by BrainStone** [comment]
Try `parent add`.  
Check the Command Usage page for further reference.

**Comment by Stager83** [comment]
Trying it now

**Comment by Stager83** [comment]
Works perfectly many thanks!!
