### ISSUE TITLE
Permissions.yml is not updated!

### ISSUE THREAD

**Issue by SadLittleOctopus** [lucko/LuckPerms#1748]
I started using this plugin today as it looked well done, I installed it and I like the layouts of all the features. One small problem: It just doesn't work
I'm running the newest Spigot 1.14.4 build and when I setup a group that would let players use the /mw goto <world> command with MultiWorld, it wouldn't work. Upon restarting my server, PC the server is on, and rejoined multiple times, the permissions.yml file had not been updated with the new info, it was just blank. Nowhere did it say that I can to change the permissions file to anywhere within the /plugins/ folder, what can I do?

**Comment by Andre601** [comment]
Don't use yaml.
It's unforgiving on typos and uses more storage.
Stay with the default h2 and use the web editor.
Also, make sure to set the right permission.
You can use the verbose command to find out which permission is checked.

**Comment by BrainStone** [comment]
I think Andre misunderstood you issue.

LuckPerms does not touch the permissions.yml file in the base directory of server. And neither does any other permissions plugin, nor are they supposed to.  
LuckPerms and all other permissions plugins have their own permission storage.  
By default LP uses a very efficient flat file database storage type (h2) that is not human readable or editable.  
You can change it to a human readable format like YAML, JSON or HOCON, though that's really not recommended. We also will not be able to provide support for fixing those files, should you mess them up by accident.  
Instead we recommend editing permissions with commands (read [this](https://github.com/lucko/LuckPerms/wiki/Usage) and [this](https://github.com/lucko/LuckPerms/wiki/Command-Usage)) or the [web editor](https://github.com/lucko/LuckPerms/wiki/Web-Editor).
