### ISSUE TITLE
losing permissons when logging off or switching worlds

### ISSUE THREAD

**Issue by Castiella** [lucko/LuckPerms#1753]
Whenever an OP moves worlds or logs off, they lose all their permissions and op power. They need to be deopped and reopped via console. Please advise.

**Comment by Andre601** [comment]
You don't provide enough information for us to actually help you.
Please make sure you provide the following information:
- Any error you encountered (Upload the content of your logs on https://hasteb.in or similar)
- What Server or Proxy type are you running?
  - What is the version of it?
- What LuckPerms version are you running?
- What are your config settings? (Remove any potentially sensitive data like passwords before sharing the file)

### Additional Links/Information
**Synchronizing groups, permissions, etc. accross servers**:
https://github.com/lucko/LuckPerms/wiki/Network-Installation

**Setup prefixes/suffixes and display them in chat, tablist, etc.**:
https://github.com/lucko/LuckPerms/wiki/Prefixes,-Suffixes-&-Meta

**Storage system errors (MySQL/MariaDB related errors)**:
https://github.com/lucko/LuckPerms/wiki/Storage-system-errors

**Comment by Castiella** [comment]
My apologies, half my post was actually cut off.

No errors. 
Server Version;  git-Paper-192 (MC: 1.14.4) - 1.14.4-R0.1-SNAPSHOT
LuckPerms-Bukkit-4.4.30.jar (#919) 
Config: https://hastebin.com/abonohohif.shell
Latest Log: https://hastebin.com/literiluxe.md

**Comment by Castiella** [comment]
Fixed itself, weird.
