### ISSUE TITLE
User parent add not working

### ISSUE THREAD

**Issue by Grandof1** [lucko/LuckPerms#1755]
Luckperms user parent set command sends off error `You do not have permission to use that command!` when running `/lp user <username> parent add <groupname>` in game.

Requested help from discord and have tried things listed  below.
- User has permission `luckperms.*`.
- Tried while being opped.
- `enable-ops` in config is `true`.
- `argument-based-command-permissions` in config is `false`.
- Ran `/lp verbose on` with no errors but shows `group.test - undefined`.
- Ran command in console which executed command as it should.

**Comment by Grandof1** [comment]
Wiped db file to start clean and was not able to reproduce the issue. On a test server, but on my official server did a db wipe after doing an `/lp export` command and then imported permission file into clean db and issue was reproduced. Get the same errors. Can not find a way so far to reproduce again.

**Comment by RJHaytree** [comment]
Hi there, are you using bukkit (spigot/paper/craftbukkit), bungee, or sponge?

**Comment by Grandof1** [comment]
Oh wow i cant believe i forgot that part, my appoligies.
I am using spigot. I can grab the build of spigot later today and add that.




On September 18, 2019 2:54:53 AM CST, Ryan Haytree <notifications@github.com> wrote:
>Hi there, are you using bukkit (spigot/paper/craftbukkit), bungee, or
>sponge?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/lucko/LuckPerms/issues/1755#issuecomment-532589505

--

**Comment by lucko** [comment]
Apologies for the super super late reply. I'm guessing some other command blocker plugin was causing this issue.
