### ISSUE TITLE
Error when user tries to join server

### ISSUE THREAD

**Issue by frostdr4gon2** [lucko/LuckPerms#1756]
17.09 22:30:33 [Server] SEVERE Sep 17, 2019 10:30:33 PM me.lucko.luckperms.lib.hikari.pool.PoolBase isConnectionAlive
17.09 22:30:33 [Server] INFO WARNING: luckperms-hikari - Failed to validate connection me.lucko.luckperms.lib.mysql.jdbc.JDBC4Connection@bbed24a (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.

**Comment by Andre601** [comment]
https://github.com/lucko/LuckPerms/wiki/Storage-system-errors#mysql-no-operations-allowed-after-connection-closed-error

**Comment by frostdr4gon2** [comment]
Thank you. I was unable to change my wait_timeout through godaddy but changing the maximum-lifetime value worked. Don't see an error!
