### ISSUE TITLE
Database Connection

### ISSUE THREAD

**Issue by ECLIP3S** [lucko/LuckPerms#1759]
I copied and pasted all things from one spigot 1.8.8's luckperms to another servers and one wont let me connect and says database connection error.

**Comment by Turbotailz** [comment]
It's generally not a good idea to copy/paste configs like that. I would let the plugin regenerate a new config and change the options manually to see if the problem still persists.

**Comment by ECLIP3S** [comment]
I tried that as well

**Comment by ECLIP3S** [comment]
> It's generally not a good idea to copy/paste configs like that. I would let the plugin regenerate a new config and change the options manually to see if the problem still persists.

I tried that as well

**Comment by ECLIP3S** [comment]
I updated plugin, let it generate its own config, fill in the credentials, and restart.

**Comment by ECLIP3S** [comment]
Bump

**Comment by Turbotailz** [comment]
You probably should add some error logs as there really isn't a whole lot we can go off of here.
