### ISSUE TITLE
Prefix Stacking Not Working

### ISSUE THREAD

**Issue by variantLegend** [lucko/LuckPerms#1760]
Currently on 1.14.4 LuckPerms.

meta-formatting:
  prefix:
  format:
    - "highest_on_track_staff"
    - "highest_on_track_grade"
  start-spacer: ""
  middle-spacer: " "
  end-spacer: ""

my highest group on staff track is owner, my highest group on grade track is senior, and yet it's only showing owner prefix. It should be showing [Owner] [Senior] speedgump for myself, and yet it's only showing [Owner] speedgump or [Senior] speedgump.

**Comment by Marotheit** [comment]
Chiming in to say that I am also having this issue.

This is my [config.yml](https://gist.github.com/Marotheit/46f9ec756df958e4da37d0ea58a7f5a8)

**Comment by BrainStone** [comment]
Can you post the section between \`\`\`?

Like this?

\`\`\`
config here
More lines
\`\`\`

It will look like this and keep spaces in front which is very important in your case. 

```
  config here
    More lines
```
