### ISSUE TITLE
Luckperms AUTOMATIC changing player groups (?)

### ISSUE THREAD

**Issue by NoFace851** [lucko/LuckPerms#1763]
I have no idea of why and how this is happening, but it happened 2x already. I was playing and talking and suddenly this happened: https://imgur.com/a/a17TQ6e . Yes, it executed a command as the console, and only I have access to my server's console. I had set this player group 30 minutes before that with /lp user Felsp parent set adm. How did this happen?

I'm using MariaDB for LP storage. Here is my exported perms: https://pastebin.com/twbKrugb

**Comment by Andre601** [comment]
This is not an LP thing.
Either someone gained access to your console and did this or a plugin does this.
