### ISSUE TITLE
All player nametags have "1 amanamaguchi owner" attached

### ISSUE THREAD

**Issue by Syrkulous** [lucko/LuckPerms#1764]
![2019-09-26_16 07 24](https://user-images.githubusercontent.com/55862273/65734888-f3fb8800-e089-11e9-8fe8-13df395be3d4.png)
Please help me...

The names look like this (since I can't share images)
[Default] AmanamaGuchi1 AmanamaGuchi owner

Original
[Default] AmanamaGuchi

**Comment by Andre601** [comment]
This is not an LP issue.
Please check whatever plugin you use to manage playernames.

**Comment by Syrkulous** [comment]
> This is not an LP issue.
> Please check whatever plugin you use to manage playernames.

It said report bugs here so I did. I was using luckperms and this happened.

**Comment by Andre601** [comment]
This is to report issues **with LuckPerms** not with other plugins.
It's not LuckPerms' job to handle the displayed player name (tag). This is handled by another plugin. Again: Check your used plugins and fix it.
