### ISSUE TITLE
meta int variable

### ISSUE THREAD

**Issue by chouuul** [lucko/LuckPerms#1765]
Hello guys,

I have a really hard problem for 4 months. I absolutely want to have a duration for ftbu claims and chunk loaders.
I've tried everything like permissions of LuckPerms (On sponge) or find a rank duration for ftbutilities... i have no ideas... please help !

**Comment by Andre601** [comment]
You could try to temp set permissions/groups to use user if it's that what you want.

**Comment by chouuul** [comment]
I'm trying to set this meta : 

ftbutilities.chunkloader.max_chunks: 50

But it didn't work

**Comment by chouuul** [comment]
Someone have a solution please ? :)

**Comment by lucko** [comment]
Really sorry for the super late reply, but something like:
```
/lp user <user> meta settemp ftbutilities.chunkloader.max_chunks 50 4mo
```
should work.

**Comment by chouuul** [comment]
I have already tried that but it didn't work ...

**Comment by BrainStone** [comment]
Make sure you’re using a recent version of Spongeforge. And if that doesn’t help, you’re better off asking for help on the Sponge Discord or wherever FTB utils receives support.
