### ISSUE TITLE
Question about Error

### ISSUE THREAD

**Issue by Royul2k** [lucko/LuckPerms#1767]
So, I'm getting the error "luckperms-hikari - Failed to validate connection me.lucko.luckperms.lib.mysql.jdbc.JDBC4Connection@7095334e (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value."

I read the FAQ and ask my 3rd party host what was there wait_timeout set to and they said 43 minutes and my maximum-lifetime is set to 20 minutes, so why am I still getting the error?

**Comment by Royul2k** [comment]
^

**Comment by BrainStone** [comment]
Quite frankly there’s a variety of reasons. Many of which are outside of the control of LP.

A connection may be closed because the TCP connection is dropped. To prevent that it would need a keep-alive. I’m not 100% sure if that is possible, but I’ll look into it.
