### ISSUE TITLE
"Cascading worldgen Lag" 

### ISSUE THREAD

**Issue by BarcodeGIT** [lucko/LuckPerms#1768]
30.09 20:11:19 [Server] Server thread/WARN [FML]: Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
30.09 20:11:19 [Server] Server thread/WARN [FML]: LuckPerms loaded a new chunk [-318, 219] in dimension 0 (overworld) while populating chunk [-317, 220], causing cascading worldgen lag.

I am receiving server lag from this Plugin and was told to report it! Is there a fix?

**Comment by Andre601** [comment]
You don't provide enough information for us to actually help you.
Please make sure you provide the following information:
- Any error you encountered (Upload the content of your logs on https://hasteb.in or similar)
- What Server or Proxy type are you running?
  - What is the version of it?
- What LuckPerms version are you running?
- What are your config settings? (Remove any potentially sensitive data like passwords before sharing the file)

### Additional Links/Information
**Synchronizing groups, permissions, etc. accross servers**:
https://github.com/lucko/LuckPerms/wiki/Network-Installation

**Setup prefixes/suffixes and display them in chat, tablist, etc.**:
https://github.com/lucko/LuckPerms/wiki/Prefixes,-Suffixes-&-Meta

**Storage system errors (MySQL/MariaDB related errors)**:
https://github.com/lucko/LuckPerms/wiki/Storage-system-errors

**Comment by BarcodeGIT** [comment]
Sorry my bad! 
- The error is merely the "cascading worldgen" log I pasted, just numerous times in the server console which shows up when it lags in-game : https://hasteb.in/oluvezay.cpp (I also just noticed its showing the same log with nucleus as well)

30.09 20:11:19 [Server] Server thread/WARN [FML]: Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
30.09 20:11:19 [Server] Server thread/WARN [FML]: LuckPerms loaded a new chunk [-318, 219] in dimension 0 (overworld) while populating chunk [-317, 220], causing cascading worldgen lag.

- Im running a Spongeforge( spongeforge-1.12.2-2838-7.1.7-RC3880.jar)
-Luckperms- LuckPerms-Sponge-4.3.75.jar
- this is my config- https://hasteb.in/xarahozi.shell

**Comment by BrainStone** [comment]
Forge or Sponge is misattributing this to LuckPerms. It really can’t be LuckPerms either because it does not interact with the world whatsoever.

It’s hard to say which plugin or mod causes this but it’s not LuckPerms
