### ISSUE TITLE
Brigadier is not supported by the server

### ISSUE THREAD

**Issue by tomkeuper** [lucko/LuckPerms#1769]
I am getting this error at startup (https://hastebin.com/otezowoxeh.css) on one of my servers and it seems like its an error with tab complete? But idk if there is a way to bypass this or if i just need to ignore it. It doesnt seems to do anything to tab completion.

Plugin Version: 4.4.1
Server version: CraftBukkit git-TacoSpigot-bf023c7d (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)

**Comment by Andre601** [comment]
LuckPerms uses Brigardier which is a Mojang library for the 1.13+ command suggestion.
It normally wouldn't load on versions older than 1.13.
Try updating to the [latest dev build of LP](https://luckperms.net).

If it still causes errors, try changing the server to PaperMC

**Comment by tomkeuper** [comment]
Thanks that fixed the issue!
