### ISSUE TITLE
[1.10.2 sponge] Unable to use commands

### ISSUE THREAD

**Issue by YOYOK9** [lucko/LuckPerms#177]
Every time I try to use any command I just get what version of lucky perms im using. I have updated to the latest version of sponge, luckyperms and forge for 1.10.2. I have looked at my console and don't see any errors when running the commands. 

Is there something I am missing or some issues with sponge and luckyperms? Need help.

Sponge: 1.10.2-2221-5.1.0-BETA-2136
LP:Sponge-2.17.61
Forge:1.10.2-12.18.3.2221

**Comment by lucko** [comment]
You need to use the console to give yourself access.
