### ISSUE TITLE
Make group rename command perform a bulkupdate querry

### ISSUE THREAD

**Issue by Andre601** [lucko/LuckPerms#1772]
I think it would be useful if `/lp group <group> rename <new name>` just performs a bulk update querry, to also rename any saved instances like parents.

Because to fully rename a group, including its saves as parents, does require using the example bulkupdate command on the wiki, which already makes the rename command useless.

**Comment by Turbotailz** [comment]
At least make it optional.

**Comment by lucko** [comment]
Added to the above issue ^
