### ISSUE TITLE
Reload bug

### ISSUE THREAD

**Issue by Jason897759** [lucko/LuckPerms#1774]
When you reload with / reload then you still have your rank but you have no rights anymore. A reboot does fix that, but it's pretty annoying to have to reboot.(spigot)

**Comment by BrainStone** [comment]
You shouldn't be doing a reload in the first place. Spigot even warns you about it.

**Comment by JavaCalorious** [comment]
It's best to do restarts as it refreshes the plugins correctly, it's the same with Windows tbh, reloads only restart some parts of the plugins, which will remove permission plugins' set prefixes/permissions.
