### ISSUE TITLE
Blocked "*"

### ISSUE THREAD

**Issue by StarozytnySky** [lucko/LuckPerms#1776]
Hi,
Is it possible to block adding * to nickname?
Example: /lp user NICK permission set *

**Comment by Andre601** [comment]
LP doesn't manage chat at all.
Please check your chat plugin's configuration file.

**Comment by Tobi406** [comment]
Hey may also mean, blocking the usage of `/lp user <user> permission set *`, I think.
If so, then [Argument-based-command-permissions](https://github.com/lucko/LuckPerms/wiki/Argument-based-command-permissions) with [Verbose](https://github.com/lucko/LuckPerms/wiki/Verbose) would be your best try.
