### ISSUE TITLE
Can't figure out prefixes 

### ISSUE THREAD

**Issue by SouthBeastGaming** [lucko/LuckPerms#1777]
I have the prefix set, I can apply screenshots and my config if need be
Using EssentialsX and EssentialsXChat with Vault also installed
1.1.4.4 Spigot server running LP
Help?

**Comment by Andre601** [comment]
If the prefix shows in `/lp user <name> meta info` then your chat plugin messes up.

**Comment by SouthBeastGaming** [comment]
> If the prefix shows in `/lp user <name> meta info` then your chat plugin messes up.

How do I fix it? I dont really understand chat prefixes and stuff like that

**Comment by Andre601** [comment]
like I said:
> If the prefix shows in `/lp user <name> meta info` then **your chat plugin messes up**.

Check the command. If the prefix shows under Prefix, then either Vault or EssentialsXChat mess something up.
In that case, ask the devs of EssentialsX for assistance as it no longer is an LP issue.
