### ISSUE TITLE
server delay and the luckperm stops

### ISSUE THREAD

**Issue by hkj7913** [lucko/LuckPerms#1778]
LuckPerms-Bukkit-4.4.1
jre-11.0.4.11-openj9
paper-209

https://pastebin.com/r72WNbCZ

I don't know if papermc is a problem or LuckPerms is a problem.
When this error occurs, people can't connect.

**Comment by Andre601** [comment]
It's just a guess but it could more be cause by your Java version...
OpenJ9 is known for shipping with headless Java versions, which can miss some stuff that may or may not break stuff.

It would also help to actually provide content from the Startup of your server and not just the error itself. That way can we understand the context of your situation more easy.

**Comment by hkj7913** [comment]
> It would also help to actually provide content from the Startup of your server and not just the error itself

What does the content mean?

https://pastebin.com/39Z70SR2
Is this correct?
I can offer you anything.

**Comment by Andre601** [comment]
I asked for the startup log

**Comment by hkj7913** [comment]
https://pastebin.com/p0Uu9YHi

**Comment by Andre601** [comment]
Do me a big favour and stop using leaked/cracked plugins.
I won't support you for this exact reason as I don't like people that leak/crack plugins and those using them.

Someone else might help you.

**Comment by hkj7913** [comment]
I'm sorry, sir.
I won't use it.
It's embarrassing.
