### ISSUE TITLE
unrecognized  command

### ISSUE THREAD

**Issue by LorianSiz** [lucko/LuckPerms#1779]
Hello,
I have a problem with my Sponge server. I downloaded the latest version of LuckPerms and now the server does not recognize any command other than LuckPerms.
It tells me that even the command help is not recognized.
I don't know what I can show you so that you can help me.

**Comment by BrainStone** [comment]
You need to give permissions to use the commands.  
That's litterally the only reason to install a permissions plugin.

Also OP gets disabled by Sponge when a permissions plugin is installed.

To get started read this: https://github.com/lucko/LuckPerms/wiki/Usage

**Comment by LorianSiz** [comment]
Yes, I know that but I have already created a Founder rank with all the perms and I gave them to me too.
(With the luckperms.*)
The server just doesn't recognize basic perms. (like the /help)

**Comment by Andre601** [comment]
Perhaps because you set the wrong permissions?
We can't tell you if the server, or a plugin uses /help or other commands since every server setup is different.
Your best way is to use LuckPerms' verbose command to find out which permissions are being checked.

**Comment by LorianSiz** [comment]
Ok, ok, I just understand that he tells me he doesn't recognize the command when I don't have access. I'm an idiot. But now I don't know what is the permission for basic commands like the /help or the /time set.
