### ISSUE TITLE
Luckperms with ezrankspro issue

### ISSUE THREAD

**Issue by TheLittleYH** [lucko/LuckPerms#1781]
I'm using ezrankspro with luckperms and it caused an issue:
sometime when players rank up it just ranks them up to the same rank, here is an example:
that's how it looks in chat: https://imgur.com/a/NI8DWfy
all I get in console is: https://pastebin.com/4D6qW5E4
that's my ezrankspro config.yml: https://pastebin.com/iCw8URnu
that's my ezrankspro rankups.yml: https://pastebin.com/WfZZ8kkt
here's the info about the groups:
for every rank from A-Y the permissions are:
If the rank is X for example:
- essentials.warps.X
- ezranks.ranks.X
- weight.24 (the weight is the place of the letter in the alphabet)
for Z it's like that:
- essentials.warps.Z
- ezranks.lastrank
- weight.26
the bug doesn't happen really often but when it does happen it's really bad because people can get many rankup keys really fast because they just rank up to the same rank for a cheap price (because they don't have to rankup till Z)
and I checked for every group the permissions are using the same template, so it's not a problem with F's permissions, also it happens for other ranks and it's not always happening.
also happened today earlier with rank C.
Can anyone please help?

**Comment by Andre601** [comment]
I think this is more a bad configuration with EZRanksPro and not LuckPerms.

Better join the helpchat discord and ask there for support: https://helpch.at/discord

**Comment by TheLittleYH** [comment]
I asked the same question on the discord, the thing is, this setup has no problems with other permissions plugins, only with luckperms as far as I know

**Comment by TheLittleYH** [comment]
Can I get any help?

**Comment by Andre601** [comment]
I'm pretty sure this is more an issue with EZRanksPro than with LuckPerms.

**Comment by lucko** [comment]
Please try updating to the latest version to see if the issue is still present.

If there are still problems then feel free to re-open.
