### ISSUE TITLE
Disabling OP & Auto-Op

### ISSUE THREAD

**Issue by JohnS19** [lucko/LuckPerms#1782]
**LP Version:** 4.4.31
**Platform:** Paper
**Version:** 1.14.4

I have recently disabled vanilla OP and have started using the auto-op feature from luckperms. It seems to work fine for the permissions of most plugins, however, **it does not work for luckperms permissions**. I don't think it's just luckperms.autoop either; I have given myself specific luckperms perms and those don't seem to work either. I have tried relogging and doing /lp sync but to no avail.

**Comment by BrainStone** [comment]
There’s a config option that determines whether LP respects OP or not. Pretty sure that’s off by default.

**Comment by Andre601** [comment]
The option is true (on) by default.
Give yourself luckperms.* and try again.

**Comment by JohnS19** [comment]
It is already enabled and I have tried giving myself luckperms.*. It still does not work.

**Comment by lucko** [comment]
You can check what's going on with the verbose command.

https://github.com/lucko/LuckPerms/wiki/Verbose
