### ISSUE TITLE
 Add in the API

### ISSUE THREAD

**Issue by Louuuwh** [lucko/LuckPerms#1783]
Hey!

I create this request to propose a suggestion! I would very much like to find an expression in the API that would retrieve as a list all players who are members of a group.

Thank you in advance if it's possible!

**Comment by lucko** [comment]
Use this method

https://github.com/lucko/LuckPerms/blob/master/api/src/main/java/me/lucko/luckperms/api/manager/UserManager.java#L174

With the permission `group.groupname`, e.g. `group.admin`
