### ISSUE TITLE
MySQL Connection issue

### ISSUE THREAD

**Issue by LozoTrioxide** [lucko/LuckPerms#1784]
Hi, so ive got a problem where luckperms always disconnects from the database randomly saying
'(No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.' 

Ive looked at the wiki about the maxlifetime and about making it shorter ive tried that and its made no difference, the host i use for my database has all default settings, so an 8 hour wait_timeout

When it does this, it likes to freeze the server somtimes so its quite a big issue, heres the log
https://pastebin.com/nZ1D2A2U

and heres the config settings for the lifetime https://pastebin.com/m6CAjaf0

**Summary**
Paper Spigot 1.14.4 #209 
Luckperms V4.4.31
When starting the DB loads fine, it just disconnects at random times

**Comment by electronicboy** [comment]
Hikari isn't the one that is freezing the server, that's redprotect which is stuck behind some transactions; This is likely completely irrelevant to LP and something else is causing the connection to be closed unexpectedly

**Comment by LozoTrioxide** [comment]
Ill send this to redprotect instead then, see what they say
