### ISSUE TITLE
Feature: Temporary groups run commands on expiry

### ISSUE THREAD

**Issue by QueenAngus** [lucko/LuckPerms#1785]
Hi there,

I run a Prison server and winning temporary ranks grants access to new areas that only donators have access to teleport to. Now, when their ranks expire after approx. 2 days, they can just stay in those donator areas until they're forced to teleport out, which is not after a long long time. What I would love is a way to make the server teleport them to spawn when their rank expires, maybe even cache it until they're online so plugins that don't register offline players can still work with this feature.

That would be amazing and likely helpful for many.
Thank you!

**Comment by Andre601** [comment]
This is nothing LP does, nor will ever do. It only manages permissions and that's it.
It's up to your plugins to handle this case when the rank/permission expires. Running commands through LP at that point would be out of scope for a permission plugin.

If you use EssentialsX with EssentialsXSpawn, could you force players to always join at the spawn (check config.yml of EssentialsX) and give donors or other the permission `essentials.spawn-on-join.exempt` to exclude them from this.
