### ISSUE TITLE
LuckPerms MySQL Connection randomly stops working

### ISSUE THREAD

**Issue by Sacha-PvP** [lucko/LuckPerms#1787]
So basically, I use a queue system plugin that requires redis to function. The queue plugin seems to be connecting to redis fine. with that being said, when I load the queue plugin on the server, it completely interfere's with LuckPerms's MySQL database connection and causes it not to connect. The weird this is though, it that it does not interfere with the litebans MySQL connection I have open on the exact same server with the LuckPerms connection. And the most strange thing of all, is that the queue system plugin has **nothing** whatsoever to do with MySQL. Any ideas on why this is happening?

Also, just to clarify, yes all of my ports are open. And yes, luckperms was running 100% fine before the queue plugin was inserted in the same spigot server. Also, as soon as I remove the queue plugin from the spigot server, luckperms starts working fine again and is successfully able to connect to my MySQL database.

The luck perms error: https://pastebin.com/fgLJjgrP

Full console log: https://pastebin.com/aHXHaZdA

For faster communication, please add my discord if you'd like. If not, its fine, this works fine too! 
Discord: Fierce#8174

**Comment by Andre601** [comment]
Looks to me like a unshaded dependency causing issues.
Can be wrong tho.

**Comment by Sacha-PvP** [comment]
> Looks to me like a unshaded dependency causing issues.
> Can be wrong tho.

i dont know. everything was working fine... i dont know what the issue could be.

**Comment by Sacha-PvP** [comment]
still having this issue :(

**Comment by lucko** [comment]
Is your queue plugin attempting to shade the SLF4J library?

**Comment by Sacha-PvP** [comment]
> Is your queue plugin attempting to shade the SLF4J library?

it does infact. would that be causing the issue?

**Comment by electronicboy** [comment]
Yes, as you're seemingly obfuscating your copy of it, which due to how classloaders are setup in bukkit can cause breakage due to multiple versions of a library in plugins

**Comment by BrainStone** [comment]
Obfuscateted code. Ewww

**Comment by Sacha-PvP** [comment]
> Yes, as you're seemingly obfuscating your copy of it, which due to how classloaders are setup in bukkit can cause breakage due to multiple versions of a library in plugins

ill get that looked at! thank you so much!
