### ISSUE TITLE
No Perms from migration

### ISSUE THREAD

**Issue by Insprill** [lucko/LuckPerms#1788]
So i migrated from PEX to LuckPerms, first i setup mysql then i went to all the servers and ran the migrate command, stopped server, got rid of pex, and started again. And now none of my groups have any perms? Prob did something wrong, any ideas?
And i do have a backup of my server right before i added luck perms so i can go back to that if needed

Note: it is a bungeecord server make of 8 servers (2 are identical)

**Comment by Turbotailz** [comment]
Can you confirm the data is in your database?

**Comment by Insprill** [comment]
I mean, it did generate stuff in there, what specifically?

**Comment by Insprill** [comment]
ok i got it
