### ISSUE TITLE
Feature Request: Allow the "server=" context to have multiple arguments

### ISSUE THREAD

**Issue by tivyhosting** [lucko/LuckPerms#1789]
Would be nice to be able to assign a permission node that applies to multiple servers.

The current way to do this involves having multiple duplicated entries for the different servers that need the per, or by assigning it globally, and then setting false on the servers you don't want it on, or by setting a static context.

This is just kind of messy, can be confusing for new users and would be nicer to just allow the context to work with multiple args, like the follwing: `server=survival,creative`

I'll put up a $20 USD bounty for this feature request.

**Comment by Tobi406** [comment]
I doubt Luck is going to make this, as he stated on another issue (#1124) that suggested similar [here](https://github.com/lucko/LuckPerms/issues/1124#issuecomment-408488049).

But let's wait what he itself will say

**Comment by Turbotailz** [comment]
I can probably do something for the web editor where it just adds the multiple permissions automatically.

**Comment by tivyhosting** [comment]
> I can probably do something for the web editor where it just adds the multiple permissions automatically.

That's easier on initial setup, but is still really messy when editing stuff later on.

**Comment by BrainStone** [comment]
Have a look at #1124
