### ISSUE TITLE
Null username

### ISSUE THREAD

**Issue by ThePurplePvPer** [lucko/LuckPerms#179]
https://gyazo.com/06fe8fa3017b44c0ac19830275bc1ad9
https://cdn.discordapp.com/attachments/251087504818569216/277602341996199946/latest2.log
I do not know if this is an issue with the plugin or just me transferring from pex with similar groups (i.e the same name)

**Comment by lucko** [comment]
Looks like an issue with UUIDs. Is your server running in online-mode=false?

**Comment by ThePurplePvPer** [comment]
no it is in online mode

**Comment by SwiftSwamp** [comment]
Happens to me as well when adding UUIDs to the plugin from users that have yet to join the server and are stored locally on the server in something such as the world data. However, once the User comes along LuckPerms does a great job of applying the UUID with the appropriate Username.

**Comment by lucko** [comment]
Right, that's the intended behaviour. However it looks like they're not being corrected in some cases.

**Comment by ThePurplePvPer** [comment]
So how do i fix that
