### ISSUE TITLE
Permissions not transferring to player when assigned a group.

### ISSUE THREAD

**Issue by darealGameknight14** [lucko/LuckPerms#1790]
I am using paper for 1.14.4 to host my server. I have several plugins on my server, but the one we will be focusing on is BetterRTP. I have researched all the permissions for BetterRTP, and have added the correct ones to allow players to type /rtp. However, when I add them to the group [Member] that I have created for them, players say they cannot use /rtp. I checked per user permissions, and on each of the users, they have no permissions, despite the fact that I just added them to the [Member] group. Please help!

**Comment by RJHaytree** [comment]
Group permissions will not be shown when viewing player permissions. If a player has a specific group, they will simply have the permission `group.<name>`. Does the player you're testing BetterRTP have a permission similar to that when you checked?

**Comment by Andre601** [comment]
Also, *what* permissions did you set and how did you set them?
How did you assign groups?
