### ISSUE TITLE
Prefix problem

### ISSUE THREAD

**Issue by Alivion** [lucko/LuckPerms#1791]
I have a prefix for my default group "&8[&2Member&8]" but when i'm trying to give my owner group also a prefix it still shows my default prefix.
![Screenshot_10](https://user-images.githubusercontent.com/56789629/67158765-7d764100-f33c-11e9-957c-bf9f03f64459.png)
![Screenshot_8](https://user-images.githubusercontent.com/56789629/67158766-7e0ed780-f33c-11e9-860e-ad4ca3b83a12.png)
![Screenshot_9](https://user-images.githubusercontent.com/56789629/67158767-7e0ed780-f33c-11e9-8655-5c21413e2c95.png)

**Comment by BrainStone** [comment]
Higher priority for higher prefixes.

Have a read here: https://github.com/lucko/LuckPerms/wiki/Prefixes,-Suffixes-&-Meta  
Also I think you'll find the web editor interesting: https://github.com/lucko/LuckPerms/wiki/Web-Editor

**Comment by Alivion** [comment]
Ahh i did it the wrong way around but Thank you
