### ISSUE TITLE
Can not create groups using yaml-combined

### ISSUE THREAD

**Issue by SteinerKD** [lucko/LuckPerms#1793]
Whenever I try to create a group from ingame or console with config set to "yaml-combined" I get a success message saying the group was created, but when running listgroups the list is empty (not even "default").
Looking in the yaml_storage subfolder a file called actions.json is generated listing the actions I have taken, but the groups.yml only contains "null".
If I add permissions to a user the combined users.yml is created, the same goes if I create a tracks.yml.
If I switch to yaml (not combined) it creates the sub folders and individual files for users, tracks and groups.
Tried with 4.4.1 and 4.4.31 under both latest Spigot and Paper.

**Comment by Andre601** [comment]
Yaml-combined is a bit buggy.

We also recommend to not use yaml storage. Better stick with the default h2 for best performance and storage usage.

**Comment by SteinerKD** [comment]
Thank you. It's been a frustrating evening trying to figure this out with the help of the helpful Discord people. I honestly would prefer an human readable option, but I've now installed and got MariaDB working.

**Comment by Andre601** [comment]
The web editor is a much better solution than editing files manually.

**Comment by SteinerKD** [comment]
Quite possibly, I'm just used to how I did things a few years back (PermissionsEX I think), cutting and pasting large chunks of permissions between groups when I was reorganizing and dividing up who could do what.
I will get there, just a bit of a learning curve, but now I have something working at least.

**Comment by lucko** [comment]
Thanks for reporting, this will be fixed in the next release.
