### ISSUE TITLE
Permissions With Bungeecord

### ISSUE THREAD

**Issue by crazykids2800** [lucko/LuckPerms#1795]
I have finished my permissions for my network and positive I set up the configs correctly yet when I give myself the rank it still says I don't have perms.

**Comment by Andre601** [comment]
You don't provide enough information for us to actually help you.
Please make sure you provide the following information:
- Any error you encountered (Upload the content of your logs on https://hasteb.in or similar)
- What Server or Proxy type are you running?
  - What is the version of it?
- What LuckPerms version are you running?
- What are your config settings? (Remove any potentially sensitive data like passwords before sharing the file)

### Additional Links/Information
**Synchronizing groups, permissions, etc. accross servers**:
https://github.com/lucko/LuckPerms/wiki/Network-Installation

**Setup prefixes/suffixes and display them in chat, tablist, etc.**:
https://github.com/lucko/LuckPerms/wiki/Prefixes,-Suffixes-&-Meta

**Storage system errors (MySQL/MariaDB related errors)**:
https://github.com/lucko/LuckPerms/wiki/Storage-system-errors

**Comment by crazykids2800** [comment]
There is nothing in console related to LuckPerms

Config: https://hasteb.in/awudicav.shell **I have that set up for the other servers the same but with the name changed**

I use BungeeCord version 1.14-SNAPSHOT:7669801:1417

I use Luckperms version 4.4.1 on my backend Spigot servers and Luckperms version 4.4.31 on my BungeeCord server.

**Comment by Andre601** [comment]
Did you make sure that the messaging service for the bungeecord version is also set to pluginmsg?
It's recommended to leave the setting to `none`, which defaults to the `sql` messaging service, when you use MySQL or MariaDB (Confusing I know)

pluginmsg requires every instance of LP (including BungeeCord) to have it set up.

**Comment by crazykids2800** [comment]
I use MySQL for a database and have set all configs to `pluginmsg`

**Comment by crazykids2800** [comment]
I need to know how to do this soon

**Comment by lucko** [comment]
Please make sure you have setup ip forwarding.

https://github.com/lucko/LuckPerms/wiki/Network-Installation#pre-setup
