### ISSUE TITLE
Equivalent Command to GroupManager's /manpromote

### ISSUE THREAD

**Issue by delbertina** [lucko/LuckPerms#1796]
This is a simple feature request to add an equivalent command to GroupManager's /manpromote.

-----------------------------------

This command promotes a player to a specific group. This means that in a LuckPerms context it would move a user up a track but only if it was a 'promotion'. 

There's currently a command to set a player to a specific location on a track, but that moves them even if it is a demotion so it doesn't function the same as the desired command. 

On the command equivalencies page, it says that /lp user <user> promote <track> is the same command. This is incorrect because that command moves the user up 1 level, and does not have an argument for what group to stop at.

If adding a command to promote up to a specific point is not feasible, it would still be nice to have some way of only promoting a user on a track if they are not yet past a specific group. That or set a user's track position only if it will result in a 'promotion'.

Maybe there's currently a way to do this, but I've asked a few times in the support chat to no avail.  :)

**Comment by lucko** [comment]
Seems very close to the current promote command - I'm not too sure an alternative that similar really has a place. I'm reluctant to implement niche changes to commands with extra config settings / flags, as it makes things harder to understand for users just wanting basic functionality.

I'm going to close this suggestion on the basis that it's unlikely to make it into the main plugin in the near future. A quality PR implementing this functionality would likely still be accepted, but it's not something I'm going to work on. :)
