### ISSUE TITLE
Craft Scheduler Thread Message Spam? Luck Perms possibly?

### ISSUE THREAD

**Issue by CreationMC** [lucko/LuckPerms#1797]
So, I been running LuckPerms version v4.4.31 on my 1.13.2 survival server.

Recently. (Like 11 hours ago ish) There was been blank messages spammed in chat every second.. Annoying players and being a hard find.

There aren't any errors for it, but than when I disable luckperms it stops spamming chat, still spams console, when trying to re-enable luckperms it gives me an error and disables again.

[![Screenshot from Gyazo](https://gyazo.com/751cd4609e9d725db21bac0b1c96ea99/raw)](https://gyazo.com/751cd4609e9d725db21bac0b1c96ea99)

[![Screenshot from Gyazo](https://gyazo.com/6874b23c92e3e60e3de831e2745a988a/raw)](https://gyazo.com/6874b23c92e3e60e3de831e2745a988a)

[![Screenshot from Gyazo](https://gyazo.com/75d4b3f1180e0e6a98d3d5243d408e19/raw)](https://gyazo.com/75d4b3f1180e0e6a98d3d5243d408e19)

[![Screenshot from Gyazo](https://gyazo.com/aa46b0a81be9cff25576958d584238b9/raw)](https://gyazo.com/aa46b0a81be9cff25576958d584238b9)

**Comment by Andre601** [comment]
Please don't use PlugMan to enable/disable LuckPerms, or any plugin for that matter, as unwanted side-effects (like those errors perhaps) can appear as the consequence of not disabling and enabling a plugin properly.
Proof of this can be seen in your last screenshot, where the error points to a path within PlugMan (`at com.rylinaux.plugman.command.EnableCommand.execute(EnableCommand.java:127) ~[?:?]`)

Please make a clean server restart (not reload) and see if this error still appears.
Also, this empty lines issue doesn't seem like something that LP would cause. It's more likely another plugin doing something like that (Like a command/"spam" blocker).

**Comment by CreationMC** [comment]
I disabled all our command/spam blocker type plugins and luckperms disabling was the only one to stop spamming in chat. But the issue still resided spamming in console, so I don't 100% believe it is LuckPerms but along those lines.

**Comment by Andre601** [comment]
I think it's more a combination of LP and another plugin (at most).
Like that as soon as LP is installed does another plugin enable something like that. Try it with a fresh server and install each plugin one by one (perhaps start with LP first to really see if it itself causes this). It's tedious I know, but it's the best way to find out what causes these issues as I highly doubt that a permission plugin would spam the chat.

**Comment by CreationMC** [comment]
I highly doubt that also.. It was just weird disabling stopped chat spam but in console it's a no go, so I am re-going through each plugin one by one.

**Comment by CreationMC** [comment]
I think I found the issue. Different plugin, so closing this.

**Comment by AtomixCM** [comment]
> I think I found the issue. Different plugin, so closing this.

Hey, I'm having this issue as well. Which plugin was it for you?
