### ISSUE TITLE
question by groups

### ISSUE THREAD

**Issue by IIuoneR** [lucko/LuckPerms#1799]
Hey. I have a lot of groups. They are stored in a yaml file. 
How to make all groups stored in one yaml file?

**Comment by Andre601** [comment]
Read the comment above the storage-type section.
It clearly mentions that you add `-combined` to the storage type (`yaml-combined`) to make it one file.

However, there are two reasons, why not to use this, or any file-based storage type (yaml, json, hcon):
1. combined method is known to be "buggy". There are some issues on this GitHub reporting weird issues when using the yaml-combined type.
2. We highly recommend to **not** edit the files manually. Not only can 1 typo mess everything up, but it also uses much more disk space compared to other storage methods like the default h2.
And with alternatives like the Web editor, for easy editing of permissions, is this storage type really not that beneficial.
