### ISSUE TITLE
Request for datetimestamp in user_permission mysql table

### ISSUE THREAD

**Issue by epicbastion** [lucko/LuckPerms#180]
This is a feature add request to add a column for datetimestamp in the user_permission table for use in pruning old users.

**Comment by lucko** [comment]
This wouldn't really help. The timestamp would only be updated when permissions are modified.

So if you added a permission to a user 9 months ago, then didn't add/remove/modify that permission for 9 months, the timestamp will still show as being last modified 9 months ago, even if the user has logged in and "used" that permission in the time.

Also, I think that generally permission data isn't the sort of thing you'd want to prune, and I don't really think implementing specific support for it is worth my time. If you just want to order permissions by insertion order, just order by the id. It auto-increments, so a smaller ID number = an older permission.
