### ISSUE TITLE
Reload the "permission recognizing system" without server reload/restart

### ISSUE THREAD

**Issue by DasBabyPixel** [lucko/LuckPerms#1801]
I created a plugin that installes other of my plugins as APIs. The Problem is, LuckPerms does not find the permissions of the plugins. (ik, i can search for the perms manually but luckperms is easier). When I install the other plugins, I use the pluginmanager and load+enable them. Reloading/Restarting does not help, because the APIs get reinstalled to have always the newest version. Any Ideas how I can reload the system that recognizes the permissions with the luckperms API?

NOTE:
I enable the APIs after the server has loaded and before the server is done enabling

**Comment by lucko** [comment]
This should work fine already, the permissions should be picked up by LuckPerms as they're enabled.

Does your API loader plugin replace the `PluginManager` with reflection? That could potentially be the cause of the issue?
