### ISSUE TITLE
That is only a suggestion.

### ISSUE THREAD

**Issue by DevJoey** [lucko/LuckPerms#1803]
Hey, i use your Permissions Plugins Meta function to set a players color. I have created a meta called color and set it for every group to the rank color. Like &4 for Admin i will use this, to allow players zu set thier own rank color. Now i have a little question. if i use /lp user %name% meta info it shows me the meta that the player have set . But colorcodes are replaced by a whitespace. can you plese make, that are colorcodes in meta info are normaly shown? Like &6 instead of this http://prntscr.com/prn5v1

It would be very nice :)

Thanks for this nice Plugin. And i will be happy for an answer.

Joey :)

**Comment by Andre601** [comment]
Usually, does it show the raw format when hovering over the text.
Like when you create a prefix does it show the prefix in their colours and formats, while hovering over them shows the raw format.

**Comment by DevJoey** [comment]
Tank you, Thank you, Thank YOUUUUU <3 <3

**Comment by DevJoey** [comment]
I love this plugin so hard
