### ISSUE TITLE
Server does not start when Luckperms is installed

### ISSUE THREAD

**Issue by DeadlyKltten** [lucko/LuckPerms#1805]
LuckPerms v4.4.31
Paper 1.12.2 b1618

Console Log: https://pastebin.com/raw/eeaSXutm
if you wait a little longer you will get this: https://pastebin.com/raw/KFLNRiGP

**Comment by Andre601** [comment]
Please take a look at the [Storage system error](https://github.com/lucko/LuckPerms/wiki/Storage-system-errors) page.
