### ISSUE TITLE
 WARNING: An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by llronaldoll** [lucko/LuckPerms#1806]
> WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by me.lucko.luckperms.common.dependencies.classloader.ReflectionClassLoader (file:/C:/Users/Winchester/Desktop/Servidor%20Spigot/plugins/LuckPerms-Bukkit-4.4.1.jar) to method java.net.URLClassLoader.addURL(java.net.URL)
WARNING: Please consider reporting this to the maintainers of me.lucko.luckperms.common.dependencies.classloader.ReflectionClassLoader
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by Andre601** [comment]
See #1798, #1650, #1649, #1334, #1290, #1084 or #952 (tl;dr. Search for an existing issue first, even when closed)

A fix is currently worked on for this.
