### ISSUE TITLE
"Unable to get a connection from the pool. (hikari is null)"

### ISSUE THREAD

**Issue by MCEpicShasta** [lucko/LuckPerms#1808]
```
10.11 19:56:31 [Server] SEVERE ... 5 more
10.11 19:56:31 [Server] SEVERE at me.lucko.luckperms.common.storage.Storage.lambda$makeFuture$0(Storage.java:81)
10.11 19:56:31 [Server] SEVERE at me.lucko.luckperms.common.storage.Storage.lambda$savePlayerData$20(Storage.java:254)
10.11 19:56:31 [Server] SEVERE at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.savePlayerData(SqlStorage.java:947)
10.11 19:56:31 [Server] SEVERE at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.getPlayerName(SqlStorage.java:1017)
10.11 19:56:31 [Server] SEVERE at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.getConnection(HikariConnectionFactory.java:129)
10.11 19:56:31 [Server] SEVERE Caused by: java.sql.SQLException: Unable to get a connection from the pool. (hikari is null)
10.11 19:56:31 [Server] SEVERE at java.lang.Thread.run(Thread.java:745)
10.11 19:56:31 [Server] SEVERE at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
10.11 19:56:31 [Server] SEVERE at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
10.11 19:56:31 [Server] SEVERE at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
10.11 19:56:31 [Server] SEVERE at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
10.11 19:56:31 [Server] SEVERE at me.lucko.luckperms.common.storage.Storage.lambda$makeFuture$0(Storage.java:86)
10.11 19:56:31 [Server] SEVERE java.util.concurrent.CompletionException: java.sql.SQLException: Unable to get a connection from the pool. (hikari is null)
```

how to fix? using LuckPerms vBungee 4.4.31

**Comment by Andre601** [comment]
You don't provide enough information for us to actually help you.
Please make sure you provide the following information:
- Any error you encountered (Upload the content of your logs on https://hasteb.in or similar. Don't just directly paste in the issue)
- What Server or Proxy type are you running?
  - What is the version of it?
- What LuckPerms version are you running?
- What are your config settings? (Remove any potentially sensitive data like passwords before sharing the file through https://hasteb.in)

### Additional Links/Information
**Synchronizing groups, permissions, etc. accross servers**:
https://github.com/lucko/LuckPerms/wiki/Network-Installation

**Setup prefixes/suffixes and display them in chat, tablist, etc.**:
https://github.com/lucko/LuckPerms/wiki/Prefixes,-Suffixes-&-Meta

**Storage system errors (MySQL/MariaDB related errors)**:
https://github.com/lucko/LuckPerms/wiki/Storage-system-errors

**Comment by MCEpicShasta** [comment]
LuckPerms Bungee 4.4.31
proxy: bungeecord, 1.8
config: https://hasteb.in/cesefige.yaml
issue: https://hasteb.in/bupedaho.cs

**Comment by Andre601** [comment]
"BungeeCord 1.8" is not really a version.
What is the actual build of BungeeCord

**Comment by MCEpicShasta** [comment]
latest bungeecord build. i always update it

**Comment by electronicboy** [comment]
Please provide the full log file, you're missing information

**Comment by MCEpicShasta** [comment]
sorry what? nothings missing thats the full log

**Comment by electronicboy** [comment]
That's not the full log file...

**Comment by MCEpicShasta** [comment]
um well there's nothing else so..it is the full log

**Comment by MCEpicShasta** [comment]
issue: https://pastebin.com/5VdRzueb

things i tried: deleted lib folder on both lobby and bungee server, checked database details, looked at https://github.com/lucko/LuckPerms/wiki/Storage-system-errors, renamed luckperms folder on bungee server and let it regenerate then changed the database details, asked my host what the database max connections is "2,500"

**Comment by electronicboy** [comment]
Your config file is invalid and apparently missing the database section

**Comment by MCEpicShasta** [comment]
it is not missing or invalid a mod just checked my config and said everything was fine

**Comment by Andre601** [comment]
> it is not missing or invalid a mod just checked my config and said everything was fine

Better check it yourself instead of letting a mod do this.

**Comment by MCEpicShasta** [comment]
um would you like to check it too? https://pastebin.com/MG4DSubb the database section is not "missing"

**Comment by MCEpicShasta** [comment]
fixed

**Comment by BrainStone** [comment]
And how/what was the issue?
