### ISSUE TITLE
Default Assignments/Rules

### ISSUE THREAD

**Issue by Aiidoneus** [lucko/LuckPerms#181]
Hello,
This is a general help question and would very much appreciate it if you could guide me in the right direction. I am trying to understand how to use the Default Assignments section of the config for luckperms. I can't get it to work the way I am trying to set it. Maybe you can help me. I will try to be as detailed as possible with what I am trying to do. Basically I help run a big network and I am trying auto assign a permission node if you have this permission node. Just so I don't spam this page with the code in the config, I am putting it into http://pastebin.com/ve9LiydM. I also edited out the permission nodes but hope you get the gist of it. 
Thanks in Advance,
-Aiden

**Comment by lucko** [comment]
I'm not sure what you're asking for?

**Comment by Aiidoneus** [comment]
Using the Default Assignments in the LuckPerms configs, I can't seem to get the piece of code I linked to work. It detects if player has this permission and gives another permission based on the one it detects.

**Comment by bookerthegeek** [comment]
@lucko Basically, what he is looking for is:

If player has permission A, assign permission 1
If player has permission B, assign permission 2
etc, etc.

**Comment by lucko** [comment]
Your example looks fine.

Make sure you're using the latest build: https://ci.lucko.me/job/LuckPerms/

There was an issue with default assignments a while back.
