### ISSUE TITLE
/lp editor does not give me any input.

### ISSUE THREAD

**Issue by jonathanhj123** [lucko/LuckPerms#1812]
When I do /lp editor all it does it this: https://gyazo.com/3c2b0372756100c9aa904c23c8cc474c

And it gives me this in the console: https://pastebin.com/wA621xkL.

Don't know what to do, I've been searching around and I really haven't found any solution, hope you can help me!

**Comment by Turbotailz** [comment]
Which version of LuckPerms are you running?

**Comment by jonathanhj123** [comment]
I am using LuckPerms for Bukkit/Spiggot v 4.4.31

**Comment by lucko** [comment]
The console extract isn't the full error - I think you missed a line (the most important one!)

I'm guessing it's something to do with your servers network connection to the web editor host.
