### ISSUE TITLE
1M is one minute and not one month

### ISSUE THREAD

**Issue by VergilPrime** [lucko/LuckPerms#1813]
I confirmed while trying to set up temporary parents that 1M is one minute* and not one month* as listed in the documentation. Likely due to a lower casing of arguments at some point. Tested for both parent addtemp and permission settemp.

LuckPerms version 4.4.1 running on Paper 226.

Edit: Switcheroo'd

**Comment by BrainStone** [comment]
Month is `mo`.

**Comment by VergilPrime** [comment]
https://github.com/lucko/LuckPerms/wiki/Command-Usage:-Permission#lp-usergroup-usergroup-permission-settemp
"LuckPerms uses a format for the relative time similar to the SimpleDateFormat used in java. F.e. is 1M one month while 1m is one minute."

https://github.com/lucko/LuckPerms/wiki/Command-Usage:-Parent
"LuckPerms uses a format for the relative time similar to the SimpleDateFormat used in java. I.e. 1M would be one month while 1m would be one minute."

**Comment by Andre601** [comment]
This is actually my fault as I put this information there.
The wiki didn't had any examples using months at that point and the relative time option isn't that well documented, so I assumed it uses a syntax similar to the above mentioned SimpleDateTime in Java, which actually uses M for months and m for minutes.

We can honestly blame Luck a bit for not really checking the PR for valid information. ;)

I'll make a PR to fix those wrong information. Thanks for letting us know.

**Comment by VergilPrime** [comment]
Thanks for the correction!
