### ISSUE TITLE
Luckperms in chat is not working

### ISSUE THREAD

**Issue by denzencica** [lucko/LuckPerms#1815]
Hi,

I have an issue with luckpermission. In chat the group's prefix is not display. I dont know why this do. I think the problem is causes by CMI plugin.
Can anybody solve my problem?

**Comment by Turbotailz** [comment]
Do you also have Vault installed?

**Comment by denzencica** [comment]
Yes, i have vault plugin

**Comment by EOT3000** [comment]
You need a chat formatter. "Vault chat formatter" is a good one

**Comment by lucko** [comment]
Please see here for more info: https://github.com/lucko/LuckPerms/wiki/Prefixes,-Suffixes-&-Meta
