### ISSUE TITLE
Issue getting Prefix to work with Luckperms

### ISSUE THREAD

**Issue by blkwind** [lucko/LuckPerms#182]
Hello I am haveing a issue adding prefix to groups using the command /lp group admin meta addprefix "Admin" . it just returns some info on the consol:

12.02 23:04:39 [Server] pool-3-thread-1/INFO Command Usage - addprefix
12.02 23:04:39 [Server] pool-3-thread-1/INFO > Adds a prefix
12.02 23:04:39 [Server] pool-3-thread-1/INFO Arguments:
12.02 23:04:39 [Server] pool-3-thread-1/INFO - <priority> -> the priority to add the prefix at
12.02 23:04:39 [Server] pool-3-thread-1/INFO - <prefix> -> the prefix string
12.02 23:04:39 [Server] pool-3-thread-1/INFO - [server] -> the server to add the prefix on
12.02 23:04:39 [Server] pool-3-thread-1/INFO - [world] -> the world to add the prefix on

We are using the latest beta build of sponge for 1.11.2 and the latest Luckperm release. Hopefully I am just missing something or a step.

**Comment by lucko** [comment]
You need to specify a priority too.
https://github.com/lucko/LuckPerms/wiki/Command-Usage#lp-usergroup-usergroup-meta-addprefix

**Comment by blkwind** [comment]
Thanks Lucko but I am still not having success with prefix showing in chat. I tried this command /lp group admin meta addprefix 1 "Admin" global gentscraft . It says the prefix has been added to the group but it does not show the prefix in chat.

**Comment by lucko** [comment]
Which chat formatting plugin?

**Comment by blkwind** [comment]
We are using UltimateChat [v.1.7.0] - API 5 & 6

**Comment by lucko** [comment]
You should seek support from the author of that plugin, or switch to using Nucleus. (since I know that works correctly)

**Comment by JimBridger** [comment]
I'm having similar issues using ultimate chat and a plethora of other chat formatting plugins...since I read this though I've been searching for Nucleus, but I don't seem to see it anywhere...or is it NucleasHub?
