### ISSUE TITLE
Prefix and suffix are not working.

### ISSUE THREAD

**Issue by Fire2430** [lucko/LuckPerms#1824]
When I add a prefix to the owner group then add my self to this group it does not show the prefix?

**Comment by Andre601** [comment]
Not an LP issue as it doesn't manage chat, tab list or similar

**Comment by Fire2430** [comment]
But then how do i add prefixs?

**Comment by Andre601** [comment]
You use a plugin for chat or where you want prefixes to show... obviously

**Comment by lucko** [comment]
More info here https://github.com/lucko/LuckPerms/wiki/Prefixes,-Suffixes-&-Meta
