### ISSUE TITLE
Updating to v5

### ISSUE THREAD

**Issue by xXkguyXx** [lucko/LuckPerms#1825]
Hey, so I recently saw that luckperms v5 was released and decided to update.

Upon updating, I was greeted by the following error: https://ghostbin.co/paste/yoje8

Our luckperms db is about 750mb (yes I made a backup).

Thanks.

**Comment by Turbotailz** [comment]
Can you try running it by generating a new folder? Just rename your current LP folder to something else then restart the server.

**Comment by xXkguyXx** [comment]
It generates fine.

**Comment by Turbotailz** [comment]
I'm going to assume your storage is corrupt.

You say you have a backup, did you run the `/lp export <file>` command? If so, you can just run `/lp import <file>` after putting the exported file into the new LP folder.

**Comment by xXkguyXx** [comment]
Oh, I assumed when updating it would be fine, weird, maybe add a spot for that somewhere in the upgrading to v5, you only guys only mention making a backup. It also runs fine on v4.2.58 :P so I don't think it's corrupt.

Also, after exporting the data from our v4 version I get a file with no extension.
When I try to import this into v5 I get the following error: http://i.iconictech.net/18.51.40-28.11.19.png

**Comment by BrainStone** [comment]
It does update just fine. You just happened to be unlucky and it corrupted at the same time you updated. 

Regarding the error:  
The export format did change.  
So downgrade to v4, import the data and the upgrade again. Then everything should work.

**Comment by xXkguyXx** [comment]
I'm sorry I'm a little confused, you said downgrade to v4 then export, but I did export that on v4. v5 doesn't allow me to import whatever I exported from v4

**Comment by BrainStone** [comment]
No I did not.  
I said downgrade, **im**port, upgrade. Also wipe the storage before importing.
