### ISSUE TITLE
PlaceholderAPI expansion error

### ISSUE THREAD

**Issue by Nety01** [lucko/LuckPerms#1828]
Paper 1.13.2 build 652
PlaceholderAPI v2.10.4
LuckPerms 4.4.1

This occurs on server start, started to happen after updating LuckPerms expansion with papi ecloud command.

https://hastebin.com/dexenogafi.sql

**Comment by Andre601** [comment]
![image](https://user-images.githubusercontent.com/11576465/69876557-2e6ae680-12c0-11ea-8e42-02204fe31fa5.png)

**Comment by Nety01** [comment]
So? I don't really see what that image should tell me

**Comment by Andre601** [comment]
It says plain as day "Update for **LuckPerms API 5**" meaning it WON'T work for LP v4.
You would also know that if you would join the [LP Discord](https://discord.gg/luckperms) and checked the #luckperms-v5 channel for information.

The tl;dr is that the API of LP got rewritten which is a breaking change. Your solutions are either:
- Not using latest version of the expansion as it only works with LuckPerms v5
- Update LuckPerms to v5. This may break plugins that use the old v4 API and a workaround is to use the legacy-api extension of LP.

**Comment by Nety01** [comment]
Thanks
