### ISSUE TITLE
RankUp issue VIA LuckPerms

### ISSUE THREAD

**Issue by Cyncernized** [lucko/LuckPerms#1829]
I use a Plugin called RankUp that relies on LuckPerms to RankUp a user when they have reached a certain set of requirements.  In v4, this was not an issue but in v5, this issue popped up: https://pastie.io/oonylu.groovy https://pastie.io/mmtfrb.sql

I am not sure if this is due to LuckPerms or due to the Ranking Plugin itself.  This error occurs when said user reaches the requirements and types a command to rankup.  It takes the money away from them needed to rankup but will not put them in that group from LP.  Is this an issue with LP or the RankUp plugin?

I am running The latest 5.0.9
WIth the API extension.

**Comment by Andre601** [comment]
https://github.com/lucko/LuckPerms/wiki/Upgrading-from-v4-to-v5#api-compatibility

**Comment by Cyncernized** [comment]
I have the API extension installed, But you want me to install the default-assignments extension as well?

**Comment by Andre601** [comment]
No.
Make sure you actually installed the legacy-api extension in the right place (`LuckPerms/extensions`) and that you restarted (NOT reloaded, nor using plugins like PlugMan) the server.

**Comment by Cyncernized** [comment]
Its been installed for a bit now, in the right place.: https://gyazo.com/01feb4fb93b3fb744165727aaf910a8c

I did restart the server after installing this(Not using Plugman).

**Comment by okx-code** [comment]
Hi, I'm the author of Rankup. Rankup uses the Vault API, and the line which seems to error is

https://github.com/okx-code/Rankup3/blob/master/src/main/java/sh/okx/rankup/RankupHelper.java#L36

    permissions.playerRemoveGroup(null, player, rank.getRank());

**Comment by BrainStone** [comment]
Should be fixed by #1826. Just make sure people are updating to the latest version of LP.

**Comment by J3fftw1** [comment]
I used the latest but still got the same error as listed above

**Comment by lucko** [comment]
This has been fixed already. Make sure you're using 5.0.10 or newer.
