### ISSUE TITLE
error import

### ISSUE THREAD

**Issue by mat41997** [lucko/LuckPerms#183]
logs
https://gist.github.com/mat41997/b453a0e2a4573dad635a5b3138a89381

timings
https://timings.aikar.co/?id=3399f66de00a45d4bedda1bb1e1a6811

permissionsex file permissions
https://gist.github.com/mat41997/36dd9429c1f5fabb46a66d6fa81c65ae

**Comment by lucko** [comment]
There's no reason/need to run an export+import data after migrating. 

Think about it, you're exporting data, and then reimporting the same data back on top of itself. The error logs make that pretty obvious too.
