### ISSUE TITLE
luckyperms.* not working for group or user (unless OP)

### ISSUE THREAD

**Issue by KrNel** [lucko/LuckPerms#1830]
Hi, I have set both my user and the group I belong to with `luckyperms.*`, but alas it gives me the error that "you do not have permission to use any sub commands". As you can see in the screenshot, my name is being colored according to the prefix that is in the group, but the luckyperms are not working. LP commands only work when I am server OP.  Using paper-230.jar

Is there something I'm doing wrong? Thanks.

![2019-11-29_16 48 52](https://user-images.githubusercontent.com/308183/69891255-25324780-12c9-11ea-8a12-e88be861a4fb.png)

```
name: headadmins
permissions:
- worldedit.*
- luckyperms.*
- dynmap.*
parents:
- admins
prefixes:
- '&4[&cAdmin&4]&b':
    priority: 105
```

```
uuid: 4fd16bd8-e66c-4d56-872f-e5c1dd25e8c2
name: KrNel
primary-group: headadmins
permissions:
- luckyperms.*
parents:
- headadmins
```

**Comment by Andre601** [comment]
The permission is **`luckperms.*`** since the plugin is called **Luck**Perms and not LuckyPerms.
Please always check you write permissions correctly before opening issues.

**Comment by KrNel** [comment]
Terribly sorry about that. Thank you very much.
