### ISSUE TITLE
Rank help.

### ISSUE THREAD

**Issue by Fire2430** [lucko/LuckPerms#1831]
How does it work so that the owner is better than a mod, because I use Super Vanish and it uses luck perms to see what ranks can see what so the owner can see helpers who are in V but helpers can not see owners in V.

**Comment by Andre601** [comment]
Make the owner have a higher weight than the other groups and give it the permission required to see vanished players.

**Comment by Fire2430** [comment]
How do you make a rank heavier?

**Comment by Andre601** [comment]
> How do you make a rank heavier?

https://github.com/lucko/LuckPerms/wiki/Command-Usage:-Group#lp-group-group-setweight-weight

Please start to utilize the wiki as you're asking general questions that are answered there.
