### ISSUE TITLE
MySQL ssl warning spamming logs

### ISSUE THREAD

**Issue by Tarluin** [lucko/LuckPerms#1834]
WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.

to fix this put a ?useSSL=false to the end of the connection string

here is a post about it https://stackoverflow.com/questions/36756739/how-to-disable-warn-when-connecting-to-sql-database-in-java

**Comment by electronicboy** [comment]
https://github.com/lucko/LuckPerms/wiki/Storage-system-errors
