### ISSUE TITLE
database error

### ISSUE THREAD

**Issue by bobodoustaud** [lucko/LuckPerms#1835]
Hello, 
i use lp 5.0.9 and sponge 7.1.8

When i try to connect to the server, i have [LP] A database error occurred whilst loading permissions data. Please try again later. If you are a server admin, please check the console for any errors. as error. commands doesn't work in the console.

It's a fresh installed server, i touched at nothing

**Comment by BrainStone** [comment]
Did you check the console for errors...?

**Comment by lucko** [comment]
https://github.com/lucko/LuckPerms/wiki/Storage-system-errors

**Comment by bobodoustaud** [comment]
Errors from the console : https://hastebin.com/isahuretuk.md

**Comment by bobodoustaud** [comment]
it seems that lp partially load. Could it be a spongeforge error?

**Comment by Andre601** [comment]
Check the very end of the error.
You have a database error.

**Comment by Andre601** [comment]
The error already mentions a database error.
Please check the link Luck provided.

**Comment by bobodoustaud** [comment]
And how does i fix it, please?

**Comment by bobodoustaud** [comment]
I'm surely a derp but i doesn't find the error in the list. where is it?

**Comment by bobodoustaud** [comment]
fixed when resetting the luckperms file
