### ISSUE TITLE
Adding groups with server context broken on 5.0.10

### ISSUE THREAD

**Issue by andrewkm** [lucko/LuckPerms#1837]
Just jumped from latest 4.x to 5.0.10
My commands to add groups are as such:

/lp user andrewkm parent add patron
(this should add patron with global context and correctly does).

/lp user andrewkm parent add patron main
(this should add patron with main context and **does not**).

_However_
/lp user andrewkm partent add patron server=main
(this should add patron with main context and correctly does).

I don't know if the command without **server=** was removed, but please add it back or give us an option to use it again. We have hundreds of buycraft packages and automated systems relying on the command structure without **server=**

Hoping this is a bug.

**Comment by Andre601** [comment]
You need to follow the proper syntax of the command which you can find on the wiki.

**Comment by andrewkm** [comment]
This has always been the proper syntax and has always worked on 4.4.x

Just recently it changed.
I am asking @lucko to let us use the old format.

**Comment by BrainStone** [comment]
I think @lucko phased out the shortcut command. You have to specify the context name now.

**Comment by lucko** [comment]
That's correct, it was phased out as one of the breaking changes in v5.

I know it seems like a change just for the sake of it - there was (and still is) a lot of compatibility code left in the plugin to support this kind of old behaviour, which was really limiting the maintainability of the code.

The "first context without a key specified is `server`, second is `world`" behaviour dates back a very long time, like almost to the very first public releases, and was phased out very soon afterwards. It hasn't been a "documented" way to assign permissions etc for a long time.

I'm really quite reluctant to add it back, but I understand your frustration too.

I could potentially re-add it in the form of an optional extension - or it could just as easily be done with a plugin listening to the command pre-process event.

**Comment by andrewkm** [comment]
As always, lucko saves the day! Thanks man 🥇
