### ISSUE TITLE
The temporary modifier argument accumulate is not working

### ISSUE THREAD

**Issue by SrBedrock** [lucko/LuckPerms#1839]
The "temporary modifier" argument `accumulate` is not working when a try `/lp user <player> parent <group> addtemp <time> accumulate`, has anything changed?

LuckPerms Version: 5.0.9
LuckPerms Extensions: extension-legacy-api-1.0.0
Vault: 1.7.3
Paper Version: 230

**Comment by Turbotailz** [comment]
Can you provide more info? Like what happens when you run the command? What are you expecting to happen vs what actually happens. Screenshots are good.

**Comment by SrBedrock** [comment]
I add a player to a group temporarily with the command:
`/lp user Player parent Donor addtemp 30d accumulate`

After 15 days I want to increase the time by 30 days in the same group.
`/lp user Player parent Donor addtemp 30d accumulate`

When sending command to check player's parent:
/lp user Player parent info`
Should return the value of 45 days left, initial 15 plus 30 added.
