### ISSUE TITLE
Permissions not applying

### ISSUE THREAD

**Issue by Castiella** [lucko/LuckPerms#1840]
I'm trying to block players from accessing other worlds with Multiverse. The permissions used to work fine, but I'm presuming along the way an Admin may have messed up the weight of the groups?

I'd appreciate any help. New Players (default group) can access any world in multiverse without a permission. Even new worlds where no permission has been added.

I'm at a loss, I don't know if this is multiverse or a luckperms issue and i'm being passed back and forth. 

Please let me know what I need to provide

**Comment by lucko** [comment]
You can try doing some debugging with the verbose command.

https://github.com/lucko/LuckPerms/wiki/Verbose

This will show if there's an issue in the way your permissions are setup.
