### ISSUE TITLE
Bug for Placeholders

### ISSUE THREAD

**Issue by chaosworlds1** [lucko/LuckPerms#1842]
Both MVDWplaceholderAPI and placeholder API can't load in the expansion/plugin

Here is the error for placeholder API:

03.12 11:30:51 [Server] ERROR Could not pass event ServerLoadEvent to PlaceholderAPI v2.10.4
03.12 11:30:51 [Server] INFO org.bukkit.event.EventException: null
03.12 11:30:51 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
03.12 11:30:51 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
03.12 11:30:51 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
03.12 11:30:51 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
03.12 11:30:51 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:581) [spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
03.12 11:30:51 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:542) [spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
03.12 11:30:51 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:420) [spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
03.12 11:30:51 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) [spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
03.12 11:30:51 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698) [spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
03.12 11:30:51 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
03.12 11:30:51 [Server] INFO Caused by: java.lang.NoClassDefFoundError: net/luckperms/api/LuckPerms
03.12 11:30:51 [Server] INFO at me.lucko.luckperms.placeholders.LuckPermsExpansion.canRegister(LuckPermsExpansion.java:48) ~[?:?]
03.12 11:30:51 [Server] INFO at me.clip.placeholderapi.expansion.ExpansionManager.registerExpansion(ExpansionManager.java:102) ~[PlaceholderAPI-2.10.4.jar:?]
03.12 11:30:51 [Server] INFO at me.clip.placeholderapi.expansion.ExpansionManager.registerAllExpansions(ExpansionManager.java:154) ~[PlaceholderAPI-2.10.4.jar:?]
03.12 11:30:51 [Server] INFO at me.clip.placeholderapi.ServerLoadEventListener.onServerLoad(ServerLoadEventListener.java:52) ~[PlaceholderAPI-2.10.4.jar:?]
03.12 11:30:51 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_222]
03.12 11:30:51 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_222]
03.12 11:30:51 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
03.12 11:30:51 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
03.12 11:30:51 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:312) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
03.12 11:30:51 [Server] INFO ... 9 more
03.12 11:30:51 [Server] INFO Caused by: java.lang.ClassNotFoundException: net.luckperms.api.LuckPerms
03.12 11:30:51 [Server] INFO at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_222]
03.12 11:30:51 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_222]
03.12 11:30:51 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_222]
03.12 11:30:51 [Server] INFO at me.lucko.luckperms.placeholders.LuckPermsExpansion.canRegister(LuckPermsExpansion.java:48) ~[?:?]
03.12 11:30:51 [Server] INFO at me.clip.placeholderapi.expansion.ExpansionManager.registerExpansion(ExpansionManager.java:102) ~[PlaceholderAPI-2.10.4.jar:?]
03.12 11:30:51 [Server] INFO at me.clip.placeholderapi.expansion.ExpansionManager.registerAllExpansions(ExpansionManager.java:154) ~[PlaceholderAPI-2.10.4.jar:?]
03.12 11:30:51 [Server] INFO at me.clip.placeholderapi.ServerLoadEventListener.onServerLoad(ServerLoadEventListener.java:52) ~[PlaceholderAPI-2.10.4.jar:?]
03.12 11:30:51 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_222]
03.12 11:30:51 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_222]
03.12 11:30:51 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
03.12 11:30:51 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
03.12 11:30:51 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:312) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
03.12 11:30:51 [Server] INFO ... 9 more

Here is the error for MVDWHook:

03.12 11:30:40 [Server] INFO [LuckPermsMVdWHook] Enabling LuckPermsMVdWHook v5.0-SNAPSHOT
03.12 11:30:40 [Server] ERROR Error occurred while enabling LuckPermsMVdWHook v5.0-SNAPSHOT (Is it up to date?)
03.12 11:30:40 [Server] INFO java.lang.NoClassDefFoundError: net/luckperms/api/LuckPerms
03.12 11:30:40 [Server] INFO at me.lucko.luckperms.placeholders.LuckPermsMVdWHook.onEnable(LuckPermsMVdWHook.java:43) ~[LuckPermsMVdWHook.jar:?]
03.12 11:30:40 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
03.12 11:30:40 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:347) [spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
03.12 11:30:40 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
03.12 11:30:40 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:436) [spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
03.12 11:30:40 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:350) [spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
03.12 11:30:40 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:580) [spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
03.12 11:30:40 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:542) [spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
03.12 11:30:40 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:420) [spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
03.12 11:30:40 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) [spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
03.12 11:30:40 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698) [spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
03.12 11:30:40 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
03.12 11:30:40 [Server] INFO Caused by: java.lang.ClassNotFoundException: net.luckperms.api.LuckPerms
03.12 11:30:40 [Server] INFO at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_222]
03.12 11:30:40 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:136) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
03.12 11:30:40 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:82) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
03.12 11:30:40 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_222]
03.12 11:30:40 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_222]
03.12 11:30:40 [Server] INFO ... 12 more

**Comment by Andre601** [comment]
If you're using latest LP version (LP v5), please make sure to follow instructions listed here:
https://github.com/lucko/LuckPerms/wiki/Upgrading-from-v4-to-v5

**Comment by Andre601** [comment]
The latest version of the expansion is for LuckPerms v5 ONLY and not backwards-compatible.

Please either update to the latest dev build of LuckPerms v5 (You can find downloads on https://luckperms.net) or use an older version of the expansion.

Also, for the next time, please use a site like [hasteb.in](https://hasteb.in) as pasting issues that way makes it harder for us to help you. Thanks.
