### ISSUE TITLE
Add message to notify users about the API changes that may break plugins

### ISSUE THREAD

**Issue by Turbotailz** [lucko/LuckPerms#1845]
In the early versions of v5 I think you should consider adding some sort of console/in-game message for admins to help users realise they need to include the legacy API extension if there are issues with any plugins that rely on it.

We are getting a ton of questions about it on the Discord and here in the issues. It's easy enough to point them to the right place but it does get tiring. Some users even opt to downgrade to v4 because they know it works.

**Comment by lucko** [comment]
Quite hard to detect usage of the old API though unfortunately.

I intend to add a bigger warning to the version release on Spigot/Sponge, hopefully that will help.
