### ISSUE TITLE
5.0.12 MySQL Error (Build #934) Spigot 1.14

### ISSUE THREAD

**Issue by myleskeeffe** [lucko/LuckPerms#1847]
Server Version: Paper version git-Paper-233 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
LuckPerms Version: Tested with both build 933 and build 934 (5.0.11 & 5.0.12).
Error: When setting storage method to MySQL or MariaDB, there's a constant flood of errors and the plugin does not function.
Stack Trace (5.0.11):
https://hasteb.in/ifinezuq.txt

Stack Trace (5.0.12):
https://hasteb.in/hayajuza.txt

Server is hosted on an Ubuntu Server 19.10 LXC Container with latest packages and OpenJDK
Database is latest version of MariaDB (Tested this with both MySQL and MariaDB settings in config - same error always occurred). I haven't fully tested using H2, but from a quick run - it functions fine, but I'd rather use the MariaDB for sync/redundancy purposes. 

Thankyou in advance for any help! :)

**Comment by myleskeeffe** [comment]
Hi - Thankyou so much for the quick update. I've still got an error occurring when trying to use MariaDB/MySQL. I'm not 100% sure if it's the same one, but I've got a link with the console output: 
https://hasteb.in/julereju.txt
When a player tries joining they get kicked with the error:
`Kicked whist connecting to hub: [LP] A database error occurred whilst loading permissions data. Please try again later. If you are a server admin, please check the console for any errors`

Just in case I deleted my entire LuckPerms folder, reinstalled the latest jar and tried - but it gave the same error. Any help would be appreciated :) 

Also - if I wanted to make a donation (since this is by far the best support for a free plugin I've ever seen) what would be the best place for that?

**Comment by electron93** [comment]
@myleskeeffe The problem seems to be the same, but in a different place. I was able to reproduce your problem on a local setup with a table prefix containing a dash `-`. Already fixing this, but probably I also need to test this with other databases.
