### ISSUE TITLE
List extensions loaded by LP in /lp info

### ISSUE THREAD

**Issue by Andre601** [lucko/LuckPerms#1849]
I think it would be useful to list all loaded extensions for LP when executing `/lp info` to see which are loaded and which aren't.

Or perhaps have a separate command for this which would also give more info (in hover text) when an extension isn't loaded.

**Comment by ApertureDevelopment** [comment]
Some people had issues with the legacy API extension and currently can not check if the extension was even loaded. So having a way to see what extensions were loaded would be useful
