### ISSUE TITLE
Create a job in Jenkins for v4

### ISSUE THREAD

**Issue by Turbotailz** [lucko/LuckPerms#1851]
V5 is not working for some people and v4 is no longer available to download via Jenkins. Which means people must either grab an outdated v4 from Spigot/Sponge/wherever or build from source (which isn't exactly a walk in the park for most I'd assume). The Bungee version isn't even available anywhere.

Until bugs in v5 are resolved, we need a way to let users download v4 if desired.

**Comment by lucko** [comment]
I'm working through the v5 bugs quite quickly, I don't really think it's necessary to put up old builds at this moment.
