### ISSUE TITLE
world permissions ?

### ISSUE THREAD

**Issue by anemul** [lucko/LuckPerms#1853]
I do not have a bungee server . I can not negate a permission for a single world on my single server . please add the ability to do so . 
With the web editor I have added essentials.gamemode.all set to false for world: Skyblock . However that is still resulting in admins not being able to use the command in all worlds .

**Comment by Turbotailz** [comment]
As long as the permission is `true` for global and set to `false` for a single world, it should give the desired result. You might just have a misconfigured setup.
