### ISSUE TITLE
OP config options aren't functioning

### ISSUE THREAD

**Issue by SextupleTap** [lucko/LuckPerms#1858]
As of LuckPerms-Bukkit-5.0.16.jar the default config options aren't working:
enable-ops: true
auto-op: false
commands-allow-op: true

The settings are seemingly ignored as in game/through console the op and deop commands are ignored, when performing it in game it just gives the LuckPerms version and in console the command isn't recognized. I've attempted deleting the configs and having them be recreated on a server restart, I've tried /lp sync through console, I've tried to change the config and then revert it back in between server restarts, there aren't duplicate configs or duplicate entries within the main config, but the default config options that should have the server use the vanilla op system instead of LuckPerms permission and op system are ignored/don't work.

Server Start Log:
https://hastebin.com/qomexuwupo.apache

**Comment by lucko** [comment]
Seems to be working fine for me with a minimal server setup. (LP v5.0.39, Spigot 1.14.4)

![](https://i.imgur.com/o8n3ntX.png)

So my guess is another plugin is interfering with the OP system on your server.
