### ISSUE TITLE
Luck perms does not cooperate with luck perms? [Luckperms version: 5.0.12]

### ISSUE THREAD

**Issue by partridge420x** [lucko/LuckPerms#1859]
Hello, I am trying to use Epic Spawners on a bungeecord network deployment through MariaDB (luckperms db), and it seems that permissions arent applying.
I will provide a video below, along with screenshot of the permission applied

There are no console errors of any kind. Configs have been double checked several times. Epic furnaces works just fine. but spawners still seems to have a problem

The current test is on a freshly installed server. only plugins are epic spawners, and luck perms

Video: https://www.youtube.com/watch?v=uwOrHfw4tJc&feature=youtu.be
Verbose: https://luckperms.net/verbose/#KevGfdYnZD

Luckperms version: 5.0.12

openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b01-1~deb9u1-b01)
OpenJDK 64-Bit Server VM (build 25.212-b01, mixed mode)

Affected Plugins
(ES) EpicSpawners
Minecraft Version
1.12.2
Plugin Version
6.1.15
Output of /songoda diag
[17:35:44 INFO]: Songoda Diagnostics Information
[17:35:44 INFO]:
[17:35:44 INFO]: Plugins:
[17:35:44 INFO]: EpicSpawners (6.1.15 Core 2.2.11)
[17:35:44 INFO]:
[17:35:44 INFO]: Server Version: git-Paper-1618 (MC: 1.12.2)
[17:35:44 INFO]: NMS: PAPER v1_12_R1
[17:35:44 INFO]: Operating System: Linux
[17:35:44 INFO]: Allocated Memory: 989Mb
[17:35:44 INFO]: Online Players: 2
[17:35:44 INFO]: TPS from last 1m, 5m, 15m: 19.99, 19.99, 19.98

also added note. the permission is there plugin side to get that out of the way: 
![image](https://user-images.githubusercontent.com/26298829/70374571-fa945000-18c1-11ea-9d68-fc70dbeddfcc.png)

**Comment by partridge420x** [comment]
so wierd update. after the drag drop of 4.4.1, it didnt work. but i did some messing with the config a bit, also the web editor. apparently either (lp) dont like (es) using server contexts. or (es) dont agree with using lp's server contexts, cause i notice if i have the permission set globally, it applies. but if it has a set server to apply to, nada
Also, ive been messing around with split storage, and it seems like it does not want to look for the permissions of epicspawners if set outside h2
essentially found my old work around for it

![image](https://user-images.githubusercontent.com/26298829/70374779-aa6abd00-18c4-11ea-9c94-886da3e75ba8.png)


also wont apply any of epic spawners permissions to any groups if its not on h2.
i cant find the old 4.4.1 version of lp for bungeecord. so im stuck using the latest

**Comment by Govindass** [comment]
[LuckPerms-Bungee-4.4.31.zip](https://github.com/lucko/LuckPerms/files/3949487/LuckPerms-Bungee-4.4.31.zip)

**Comment by BrainStone** [comment]
Make sure the server name you use in the server context is equal to the one in the LP config. Should be the very first setting.

Also make sure your config is up to date (rename your old config and let LPv5 create a new one for you).
