### ISSUE TITLE
Event for player/group meta changes

### ISSUE THREAD

**Issue by mikroskeem** [lucko/LuckPerms#186]
I'd find such events extremely good for my scoreboard-based nametag prefix plugin. Polling isn't that good option for it in my opinion

Imagine this scenario:
- `/lp user mikroskeem meta addprefix 0 "&c&lOP"` or `... meta set shortranks_prefix "&c&lOP&4 "`
- Event gets fired and plugin listens for given event
- Scoreboard plugin updates scoreboard prefix(es)

// enhancement

**Comment by mikroskeem** [comment]
Actually I can fetch meta changes using permission node set/unset events, since metadata is stored as permissions.

Now question is that is it worth to add separate event for meta changes

**Comment by lucko** [comment]
Yeah, I'm trying to plan out a restructure of the event API to make that clearer.

The current system was a bit rushed, and isn't very expandable.

**Comment by lucko** [comment]
Question is though, is it finally time for a breaking API change (removing and replacing the current event package) or should I try to keep the old one?

**Comment by mikroskeem** [comment]
I think you can go for breaking API change, I don't mind

**Comment by lucko** [comment]
Should be resolved by 6798fb21b2e73782d086239d3d4eb25740fb6c45

I'll update the documentation soon, for now, here's the class you need to register your listeners.
https://github.com/lucko/LuckPerms/blob/master/api/src/main/java/me/lucko/luckperms/api/event/EventBus.java
