### ISSUE TITLE
Web editor doesn´t work

### ISSUE THREAD

**Issue by molinem** [lucko/LuckPerms#1860]
Hello In last 4 hours I was editing groups with command **/lp group nameofgroup editor**
 and it was perfectly but I tried **/lp editor groups** and when I tried to save doesn´t work and the console say this : 

`07.12 21:22:04 [Server] INFO Preparing a new editor session. Please wait...
07.12 21:22:05 [Server] WARN java.lang.RuntimeException: java.net.ConnectException: Failed to connect to bytebin.lucko.me/198.54.117.199:443
07.12 21:22:05 [Server] WARN at me.lucko.luckperms.common.web.AbstractPastebin.post(AbstractPastebin.java:147)
07.12 21:22:05 [Server] WARN at me.lucko.luckperms.common.web.AbstractPastebin.postJson(AbstractPastebin.java:109)
07.12 21:22:05 [Server] WARN at me.lucko.luckperms.common.commands.generic.other.HolderEditor.execute(HolderEditor.java:72)
07.12 21:22:05 [Server] WARN at me.lucko.luckperms.common.commands.generic.other.HolderEditor.execute(HolderEditor.java:54)
07.12 21:22:05 [Server] WARN at me.lucko.luckperms.common.command.abstraction.MainCommand.execute(MainCommand.java:102)
07.12 21:22:05 [Server] WARN at me.lucko.luckperms.common.command.abstraction.MainCommand.execute(MainCommand.java:45)
07.12 21:22:05 [Server] WARN at me.lucko.luckperms.common.command.CommandManager.execute(CommandManager.java:215)
07.12 21:22:05 [Server] WARN at me.lucko.luckperms.common.command.CommandManager.lambda$onCommand$0(CommandManager.java:150)
07.12 21:22:05 [Server] WARN at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
07.12 21:22:05 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
07.12 21:22:05 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
07.12 21:22:05 [Server] WARN at java.lang.Thread.run(Thread.java:748)
07.12 21:22:05 [Server] WARN Caused by: java.net.ConnectException: Failed to connect to bytebin.lucko.me/198.54.117.199:443
07.12 21:22:05 [Server] WARN at me.lucko.luckperms.lib.okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:249)
07.12 21:22:05 [Server] WARN at me.lucko.luckperms.lib.okhttp3.internal.connection.RealConnection.connect(RealConnection.java:167)
07.12 21:22:05 [Server] WARN at me.lucko.luckperms.lib.okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
07.12 21:22:05 [Server] WARN at me.lucko.luckperms.lib.okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
07.12 21:22:05 [Server] WARN at me.lucko.luckperms.lib.okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
07.12 21:22:05 [Server] WARN at me.lucko.luckperms.lib.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
07.12 21:22:05 [Server] WARN at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
07.12 21:22:05 [Server] WARN at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
07.12 21:22:05 [Server] WARN at me.lucko.luckperms.lib.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
07.12 21:22:05 [Server] WARN at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
07.12 21:22:05 [Server] WARN at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
07.12 21:22:05 [Server] WARN at me.lucko.luckperms.lib.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
07.12 21:22:05 [Server] WARN at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
07.12 21:22:05 [Server] WARN at me.lucko.luckperms.lib.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
07.12 21:22:05 [Server] WARN at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
07.12 21:22:05 [Server] WARN at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)`

and other times say : 

07.12 21:26:03 [Server] INFO Preparing a new editor session. Please wait...
07.12 21:26:04 [Server] INFO Unable to upload permission data to the editor.

Version : Paper 1.14.4
¿Can someone help me? Thanks for your attention

**Comment by NotDuckie** [comment]
I am getting the exact same error. Could it have anything to do with this?
https://status.cloud.google.com/incident/compute/19012

**Comment by Andre601** [comment]
This could be a case if either bytebin (Site used to temporary permission data, which is hosted by Luck) or the editor itself (Which is hosted on GitHub as a GitHub Page) uses the service...
From my knowledge does Luck use DigitalOcean to host sites like said bytebin and his CI-Server. So perhaps DO uses google cloud?

We have to wait for Luck to give an answer to this.

**Comment by molinem** [comment]
> I am getting the exact same error. Could it have anything to do with this?
> https://status.cloud.google.com/incident/compute/19012

Ohhh it´s possible.

**Comment by Andre601** [comment]
The editor should work again according to Luck.

**Comment by molinem** [comment]
Works perfectly :)

**Comment by SwAtRaNgEr** [comment]
Still not working WARN java.lang.RuntimeException: java.net.ConnectException: Failed to connect to bytebin.lucko.me/198.54.117.199:443

**Comment by Andre601** [comment]
Try restarting your serving and attempt again.
Also please join [the discord](https://discord.gg/luckperms) if you haven't already to get faster support.
