### ISSUE TITLE
cant figure sponge forge permissions

### ISSUE THREAD

**Issue by Roki100** [lucko/LuckPerms#1861]
hi, how do i give people all default permissions that is given without permission plugin? like luckyperms blocks use of basic commands like /help etc, i would like to give them all permission that they have without any permissions plugin, but i cant get list of the default commands or something
im on 1.12.2 sponge
thanks in advance

**Comment by lucko** [comment]
There's a list here: https://docs.spongepowered.org/stable/en/server/spongineer/commands.html
