### ISSUE TITLE
LuckPerms Web Editor won't load

### ISSUE THREAD

**Issue by RamboOne2** [lucko/LuckPerms#1863]
I have a strange issue with the Web Editor.

When I initially downloaded the plugin a few days ago, I was able to use the "/lp editor" command, click the link, and use the Web Editor without any issues.

However, after that initial day or two of using the Web Editor, I have had nothing but issues. First I was unable to get a link, as it would give me the in-game message of "Preparing a new editor session. Please wait...", but never actually provide a link. Today it does give me a link but refuses to work on Chrome. First I got it to open on Chrome, but it wouldn't save the changes and provide a link; it just kept loading. I then refreshed and got the same issue of it claiming it couldn't load the Web Editor. I tried making one or two new links, none of them worked. I then tried opening the links in Firefox, and it worked once, and I could save the changes, but that also only worked once. Now I keep getting the "Loading error", no matter what I do. 

Please help! 
![LuckPerms Error](https://user-images.githubusercontent.com/52075840/70392307-12152b00-19df-11ea-995c-dbab0b2ccaa3.PNG)

**Comment by Andre601** [comment]
Please check your browser's console for any errors and provide them to us.
Also, I think this issue is more related to [lucko/LuckPermsWeb](https://github.com/lucko/LuckPermsWeb) than the plugin itself.

**Comment by RamboOne2** [comment]
This is the console-error I get. Thanks for the reference; I wasn't aware that the Web Editor had its own forum. I will ask there as well. 

![LuckPerms Error2](https://user-images.githubusercontent.com/52075840/70392432-4e955680-19e0-11ea-8ce7-a496e69f239f.PNG)

**Comment by Andre601** [comment]
I'm afraid that you have to wait as this is most likely an issue caused by the nameservers of bytebin not being fully updated yet (It can take up to 24 hours for that)

**Comment by RamboOne2** [comment]
Hm, I just got access for a few minutes. On Chrome as well. I was able to do 1 change, save it and implement it. Once I tried changing something else it wouldn't save, and now I am back to getting the initial error. 
It is not a one-time thing, and it has been more than 24 hours since it initially happened.

**Comment by Turbotailz** [comment]
It's a DNS issue. You may need to flush your DNS cache.

**Comment by lucko** [comment]
Should be resolved now.
