### ISSUE TITLE
Data Loading Issue

### ISSUE THREAD

**Issue by soerili** [lucko/LuckPerms#1865]
Hey,

for some players the inventory just disappeared at relogging.

Log: https://hasteb.in/icuwumij.md
Spigot: CraftBukkit version git-Spigot-9de398a-9c887d4 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
LuckPerms: LuckPerms v5.0.16

LuckPerms Config: https://hasteb.in/oqexuqow.shell

**Comment by Andre601** [comment]
You don't provide enough information for us to actually help you.
Please make sure you provide the following information:
- Any error you encountered (Upload the content of your logs on https://hasteb.in or similar)
- What Server or Proxy type are you running? ("latest" is NOT a version! Use `/version`)
  - What is the version of it?
- What LuckPerms version are you running? ("latest" is NOT a version! Use `/lp` or `/version LuckPerms`)
- What are your config settings? (Remove any potentially sensitive data like passwords before sharing the file)

### Additional Links/Information
**Synchronizing groups, permissions, etc. accross servers**:
https://github.com/lucko/LuckPerms/wiki/Network-Installation

**Setup prefixes/suffixes and display them in chat, tablist, etc.**:
https://github.com/lucko/LuckPerms/wiki/Prefixes,-Suffixes-&-Meta

**Storage system errors (MySQL/MariaDB related errors)**:
https://github.com/lucko/LuckPerms/wiki/Storage-system-errors

**Comment by soerili** [comment]
Updated comment

**Comment by Andre601** [comment]
You should use Spigot or PaperMC (Recommended) as CraftBukkit is really not a good option to use.

**Comment by electronicboy** [comment]
Update your server, you're 87 commits outdated, of one which includes a fix for plugin events not being handled properly during server startup; You'll note that after the server has started up fully, those who where denied logins are able to join just fine

Inventory data has literally nothing to do with LP and would suggest that something in your setup changed; Did you enable bungee mode properly while setting up LP or something?
