### ISSUE TITLE
Network Sync

### ISSUE THREAD

**Issue by Leodragon08** [lucko/LuckPerms#1866]
Hello,
I set in all server config "messaging-service: sql", but despite this he continues to tell me "Error while pushing changes to other servers. (A messaging service has not be configured.)".

Help me please.

Sorry for my bad English.

**Comment by BrainStone** [comment]
Make sure you're using MySQL or MariaDB as your storage type on all servers.

**Comment by BrainStone** [comment]
Also for general support, please use the Discord server in the future: https://discord.gg/luckperms
