### ISSUE TITLE
Luck Perms v5 Placeholders Yielding Incorrect Expiry Time

### ISSUE THREAD

**Issue by WhatsTheBadNews** [lucko/LuckPerms#1868]
Recently I upgraded to LP v5.0.16 and installed the PAPI expansion for the new version.

Now when I parse expiry time placeholders, I get incorrect times.

For example:

This command
`/papi parse WhatsTheBadNews %luckperms_inherited_expiry_time_jobs.boost.all.money.2%`
yielded this
![image](https://user-images.githubusercontent.com/29821149/70803811-8acb0d00-1d7a-11ea-9505-9aa85d373035.png)

It returns a very large negative number and it is only in seconds. In v4 it used to have hours, minutes, and seconds.

**Comment by Andre601** [comment]
Update to latest dev build and try again.

**Comment by WhatsTheBadNews** [comment]
@Andre601 I just updated to v5.0.18 and I still have the same issues.

![image](https://user-images.githubusercontent.com/29821149/70805048-a5eb4c00-1d7d-11ea-820c-7ce374209618.png)

**Comment by lucko** [comment]
Fixed in 5ce5af87eae03f7303421d1cd3ab3487d00d97cd
