### ISSUE TITLE
Switching to mySQL storage

### ISSUE THREAD

**Issue by dukedase** [lucko/LuckPerms#187]
Hello, I did a bunch of stuff in h2 storage before realizing I needed to use MySQL storage.  I switched over to that and now when I try to join it says "Permissions data could not be loaded"

Is there a way to transfer the data over or do I need to restart?

**Comment by lucko** [comment]
https://github.com/lucko/LuckPerms/wiki/Switching-storage-types :)

**Comment by dukedase** [comment]
God, I don't know how I missed that, thanks.

**Comment by dukedase** [comment]
So I did that but when I import the file, it get's a 'failure' on everything:

Relevant part of config: https://i.gyazo.com/416dd4750e68da238e7ec15b46fb20af.png (Password is there, just whited out)
Section of console after doing import: https://i.gyazo.com/6e8c375aa553bc951b18881f8ba7fa97.png

**Comment by lucko** [comment]
LP cannot connect to your database.

**Comment by dukedase** [comment]
Hm, I don't really know much about MySQL honestly, do I need to create a database for it?

**Comment by lucko** [comment]
Yes

**Comment by dukedase** [comment]
Ok I spent some time learning to use MySQL and creating that database did indeed fix it, thanks SO much for the help, I really appreciate it!

**Comment by dukedase** [comment]
I do have one more question though...
Is it possible to make it so the rank names in /who show up with caps?

IE:  when you do /who it says
duke: <Duke> Name
instead of
Duke: <Duke> Name

**Comment by lucko** [comment]
https://github.com/lucko/LuckPerms/wiki/Default-Groups#keep-using-the-default-group-but-just-modify-the-display-name

**Comment by dukedase** [comment]
Thanks!

I am having an issue though since changing that, when I have people in the default group (Not 'default' but the one it makes them a member of, 'commoner') it will not let me 'lp user name promote track' says 

It says they aren't in any groups in the track despite being a member of commoner, the first member of the track.  When I try to promote them after it says it is "adding them to commoner, the first group in the track" it says the same thing.
