### ISSUE TITLE
More server comtext

### ISSUE THREAD

**Issue by MarkosTech** [lucko/LuckPerms#1870]
It will be good allow to have more than one server context, is more confortable.

https://i.imgur.com/1mesvLZ.png

**Comment by Andre601** [comment]
This is how LP functions.
And you have two options available:
- Set a custom context on each server, to use context for multiple servers.
- Set the permission multiple times, each with a different context.

**Comment by MarkosTech** [comment]
Setting the permission multiple times is unlickely for server owners, because we have a lot of permissions, for example, if i have 10 games modes and 1lobby and i want to put a permission only in the 10 game modes, it's to much and it will be not confortable for the web editor, it's better than in the same permission have 10 servers. I don't understand the "set a custom text on each server".

**Comment by Andre601** [comment]
You are aware that you could allow a perm globally and deny it per server (in this case your lobby) right?

**Comment by MarkosTech** [comment]
Ah. it's true. xd
