### ISSUE TITLE
Migration from UltraPermissions

### ISSUE THREAD

**Issue by CyberFlameGO** [lucko/LuckPerms#1871]
I've seen some dead issues on the repo before regarding this but no answer for it, as I'd like to learn LuckPerms and I've been intending to for awhile. Also UltraPermissions has a MySQL DB hook if that makes anything easier/harder in terms of figuring a way to migrate

**Comment by electronicboy** [comment]
Major issue is that UltraPerms doesn't offer any form of public API, so; LP cannot be compiled against UP, would basically require to support their data format directly, which as I said on another issue relating to this is a bit icky and far from ideal, do they maybe have a sane export format (if they support that)

**Comment by lucko** [comment]
I agree with @electronicboy, this is hard for LP to implement unless the UltraPermissions author decides to publish a publicly available API for us to build against - and unfortunately even when/if they do, implementing this is unlikely to be a priority for me.
