### ISSUE TITLE
How do i add spaces To Prefixes

### ISSUE THREAD

**Issue by 0H4rl3qu1n0** [lucko/LuckPerms#1874]
Example:
/lp group superadmin meta 100 addperfix "&4[&5Super&4Admin&5]"
When i add the quotations it still doesn't add a space

**Comment by lucko** [comment]
Well, your command is wrong.

It should be something like:
```
/lp group superadmin meta addprefix 100 "&4[&5Super&4 Admin&5]"
```

And then it works (for me at least)
![](https://i.imgur.com/V46ZtuJ.png)

**Comment by 0H4rl3qu1n0** [comment]
Thanks lucko

**Comment by 90poitu** [comment]
Thanks @lucko

**Comment by AngerminecraftYT** [comment]
it doesnt work

**Comment by Squeak13** [comment]
Perfect it work, thanks for help !
