### ISSUE TITLE
There's No Space Between My Name And The Prefix

### ISSUE THREAD

**Issue by 0H4rl3qu1n0** [lucko/LuckPerms#1875]
Example
/lp group superadmin meta addprefix 100 "&4[&5Super&4 Admin&5]"
Gives no space between my name and prefix
![image](https://user-images.githubusercontent.com/48165318/70863422-37a6b500-1f48-11ea-9b47-c53dbf051e23.png)

**Comment by Tobi406** [comment]
Add a space at the end of your prefix, but before the last quotation mark.

**Comment by Andre601** [comment]
That's because you don't have set a space after the ]
If you set the prefix `"&4[&5Super&4 Admin&5]"` then __obviously__ does it not have any space because as you see, between the ] and " is no space.

**Comment by 0H4rl3qu1n0** [comment]
That's so crappy lmao
But thanks for the help guys

**Comment by lucko** [comment]
> That's so crappy lmao

Seems pretty logical though, right?!
