### ISSUE TITLE
[Suggestion] Reserve Support

### ISSUE THREAD

**Issue by elwolf6** [lucko/LuckPerms#1877]
Hello
i have luck perms and Towny and TownyChat
https://elwolf6.feen.us/r8y77a.png

prefix has capital p
but townychat has lowercase p
i talked to towny dev
he says towny chat doesnt mess with the letters
https://elwolf6.feen.us/l22zsz.png
it is really bothering me
can someone please help
i did this command
/lp group default meta addprefix 100 "&e[Pleb]"
to give them the prefix
lp editor also shows it with a capital p

This was my original issue, but then i found out that Vault manages chat stuff like that https://elwolf6.feen.us/1mt4ei.png

https://www.spigotmc.org/resources/reserve.50739/
https://github.com/TheNewEconomy/Reserve

So i was wondering if u guys could make support for Reserve

**Comment by Andre601** [comment]
If the prefix shows with a capital P in the editor (And maybe also when doing `/lp group default info`) then it's **not** an LP issue as LP doesn't handle nor change the chat in any way.

**Comment by elwolf6** [comment]
https://elwolf6.feen.us/5277ah.png it has capital P there
Also when i have vault instead of reserve it has a capital p in chat

**Comment by lucko** [comment]
Sorry, adding support for Reserve isn't a priority at this time.

However, no reason why you couldn't create (or get someone else to create) a plugin which bridges LP and Reserve using the LP API.
