### ISSUE TITLE
Luckperms doesn't recognize permissions from spartan

### ISSUE THREAD

**Issue by V3x1Dev** [lucko/LuckPerms#1879]
I am using the spartan anticheat but when I give a player spartan.bypass to bypass them it still kickes me for cheating. I have talked with the developer of Spartan and he has told me that this is on Luckperms side.

**Comment by Turbotailz** [comment]
Have you tried debugging the permission with [Verbose](https://github.com/lucko/LuckPerms/wiki/Verbose)?

**Comment by V3x1Dev** [comment]
I have tried using the verbose to debug but the problem seems to only be with the spartan.bypass as it does not come up in the verbose logs as a check

**Comment by Turbotailz** [comment]
What are the exact commands you are using with verbose? Maybe you are using a filter that excludes it.

**Comment by V3x1Dev** [comment]
/lp verbose record spartan
and 
/lp verbose on spartan

**Comment by Turbotailz** [comment]
Do you mind runnning `lp verbose record` then trying out whatever it is that would (presumably) prevent you from being kicked, then run `lp verbose paste` and paste the link here?

Run it from console in case you do get kicked.

**Comment by V3x1Dev** [comment]
As in turn on verbose then give myself the bypass permission then try to cheat? Then paste the link
Correct?

**Comment by V3x1Dev** [comment]
https://luckperms.github.io/verbose/#69Jf90hX3y

**Comment by Turbotailz** [comment]
There were only three checks for Spartan permissions, 2x `spartan.manage` and 1x `spartan.chat_protection`, all checked as `true`, so I don't know what else to suggest at this point. Are you sure it is the Spartan plugin that's kicking you? What message do you get when you are kicked? Also what does the console show.

**Comment by V3x1Dev** [comment]
I use spartan to detect cheats then use litebans to ban the player because spartan doesn't support Bungeecord networks. But spartan.bypass should be stopping the anticheat from checking the player

**Comment by Turbotailz** [comment]
Well the permission isn't being checked, at all. There's nothing we can do about that, that's on the developer of your plugin.

**Comment by V3x1Dev** [comment]
Ok Thank you anyway

**Comment by Andre601** [comment]
Do you by any chance use another perm plugin like PermissionsEx on your server?
Also, did you make sure to not be OP? The plugin might check if you're OP  and skip any additional perm checks when that is the case

**Comment by BrainStone** [comment]
Just so that it is on paper. If the permission check doesn’t appear it either doesn’t happen at all or doesn’t reach LP.  
In the first case it means that the plugin is not sending the check and in the second that you probably have another permissions plugin. 

I’d recommend you link the dev this issue.

**Comment by V3x1Dev** [comment]
How would I link the dev this issue?

**Comment by Turbotailz** [comment]
Just copy the URL

**Comment by V3x1Dev** [comment]
Where would I put the url? Sorry I'm not really experienced

**Comment by Turbotailz** [comment]
I don't know, wherever you are in contact with the developer.

**Comment by V3x1Dev** [comment]
Ok

**Comment by V3x1Dev** [comment]
When I talked to the Spartan Dev he responded with this
"There is only one method for checking permissions, and that's provided by bukkit. At this point, I have extremely verified it's on their side, because even if you reload Spartan, their cache is the problem. I can actually do nothing about it, my permission cache is designed to be 100% flexible, theirs isn't"

**Comment by lucko** [comment]
Well, sounds like the permission check isn't even reaching LP, so the issue probably lies with Spartan.

**Comment by V3x1Dev** [comment]
Ok I will tell the dev
