### ISSUE TITLE
Weird issue upon using multiple servers

### ISSUE THREAD

**Issue by dukedase** [lucko/LuckPerms#188]
Hi, on one of my servers the plugin is working great, however on another server (global perms and everything are on) no matter what group you are in, it shows your name as [default] username:  instead of your prefix, and in /who it just says 'Connected players:' instead of ranks

My ONLY and primary group is Imperator, I am not a member of default, yet my prefix shows up as default.  Permissions are working fine, however.

**Comment by lucko** [comment]
Resolved in discord
