### ISSUE TITLE
TAB plugin fails to get the permission group from luckperms

### ISSUE THREAD

**Issue by bunzybunz** [lucko/LuckPerms#1880]
Basically the TAB plugin fails to get the player's permission group from LP, thus group formatting in TAB cannot be used.
Here's the log from TAB: https://pastr.io/view/Q5zw2gGpVhM
Paper 236 1.14.4
TAB v2.5.4
LuckPerms-Bukkit-5.0.23

**Comment by Turbotailz** [comment]
You may need the [legacy API extension](https://github.com/lucko/LuckPerms/wiki/Upgrading-from-v4-to-v5#api-compatibility) - also consider reporting this to the developer for them to use the new API.

**Comment by bunzybunz** [comment]
There was an update for TAB (2.6.0) which fixed this issue. I updated it just now and it all works fine. Sorry for any inconvenience I might have caused. Have a nice day.
