### ISSUE TITLE
PlaceholderAPI Expansion for Luckperms breaks plugin

### ISSUE THREAD

**Issue by Free-Lunch-1** [lucko/LuckPerms#1881]
Whenever I try downloading LuckPerms PlaceholderAPI, all other Placeholders stop working, up until removal of the LuckPerms one.  Really need a fix for this as Vault doesnt display higher ranked groups, but instead the first assigned group

**Comment by Free-Lunch-1** [comment]
Nevermind. Thought v4.4.1 was the latest but you havent updated the spigot page in over 6 months.

**Comment by Turbotailz** [comment]
Spigot page will be updated soon.
