### ISSUE TITLE
Editing values through database does not sync with the server

### ISSUE THREAD

**Issue by Free-Lunch-1** [lucko/LuckPerms#1882]
**Running on v5.0.23**
**MySQL database**
**PaperSpigot Server**
We already have everything setup in terms of permissions, groups, etc. We just want to be able to edit groups via database. 

`sync-minutes` is set to 1 and database doesn't produce errors in console. Upon editing a user's group, nothing happens.

**Comment by Turbotailz** [comment]
If you manually update the database (not recommended, btw) then you would just need to run either `/lp sync` or `/lp networksync` so LP can resync the changes.

**Comment by Free-Lunch-1** [comment]
They don't update anything

**Comment by Andre601** [comment]
Setup the database properly.
You need to use the exact same database accross all LP instances to make it work.
You should also set a messaging service to automatically sync data when changes are made.
Also note that to my knowledge, LP won't auto-sync data when you edit the database directly.
Either use the in-game commands or the web editor.
