### ISSUE TITLE
PROBLEM WITH ULTIMATE HOMES PERMISSION

### ISSUE THREAD

**Issue by Rpuxshi** [lucko/LuckPerms#1883]
To be more specific, UltimateHomes have this permission to define how many houses a player is allowed to set(ultimatehomes.sethome.max.<number>), for the default group is set to 3, and works. For the mods grop is set to unlimited (ultimatehomes.sethomes.unlimited), but now I'm creating a "VIP" group with a higher number of homes (ultimatehomes.sethome.max.4) but they are still only able to use 3 as much. (the default group is parent for the VIP group).

Any idea about what could I do? I've already given the permission directly to the users but still doesn't work, they are stuck in 3 homes just like the default's one.

**Comment by BrainStone** [comment]
Set the 3 permission to false.

**Comment by lucko** [comment]
Not sure how UltimateHomes is doing this, but I'd imagine it should be checking for the `4` permission first, might be to do with config ordering?

The LP verbose command will probably help to work out what's going wrong.

https://github.com/lucko/LuckPerms/wiki/Verbose
