### ISSUE TITLE
Parent nodes buggy

### ISSUE THREAD

**Issue by masterstreamer** [lucko/LuckPerms#1885]
Given a default group which has the permission "essentials.spawn" and a group user which has default as parent, sometimes the user group is not permitted to execute /spawn due to insufficient permissions.

**Server version:** git-Spigot-56f8471-43183ea
**LuckPerms version:** 5.0.23
**Essentials version:** 2.16.1.216

**Comment by Andre601** [comment]
So you set `essentials.spawn` to the group `default`?
Did you make sure you're using `EssentialsX` (Not Essentials. The X is important!) with EssentialsXSpawn?
Also, what is the actual MC version itself? The git version of spigot doesn't give a real clue about that.

**Comment by masterstreamer** [comment]
Yeah, default group has permission essentials.spawn. 
Yeah, I am using EssentialsX with EssentialsXSpawn.
Server is on version 1.14.4R01.

**Comment by lucko** [comment]
Could you try using the verbose command to debug this a little further.

https://github.com/lucko/LuckPerms/wiki/Verbose

It should make it clear what's going on here.

**Comment by t3rminus** [comment]
I think I may be running into the same issue. If not, let me know and I'll open a new one.

I have 3 groups:
default
member (parent: default)
mod (parent: member)

default has `essentials.*: false`
member has `essentials.(sethome|home|me|msg): true`

I am currently set as "mod", but when I try and run /home, I get "You do not have access to that command."

Running /lp verbose gives me the following output: (copied from web, sorry for the formatting)

```
t3rminus | essentials.home | false
Context: world=world
Origin: PLATFORM_PERMISSION_CHECK
Processor: me.lucko.luckperms.common.calculator.processor.WildcardProcessor
Cause: match: essentials
```

**Comment by lucko** [comment]
@t3rminus I suspect 88c432496b388c692a7139ae884fc7c40436845f will fix your issue.

**Comment by t3rminus** [comment]
> @t3rminus I suspect [88c4324](https://github.com/lucko/LuckPerms/commit/88c432496b388c692a7139ae884fc7c40436845f) will fix your issue.

Is there a new or replacement syntax that I should be using instead? I’m fine to upgrade from legacy syntax if necessary.

**Comment by masterstreamer** [comment]
@lucko But I am not using shorthand syntax and it isn't working either..

**Comment by lucko** [comment]
> > @t3rminus I suspect [88c4324](https://github.com/lucko/LuckPerms/commit/88c432496b388c692a7139ae884fc7c40436845f) will fix your issue.
> 
> Is there a new or replacement syntax that I should be using instead? I’m fine to upgrade from legacy syntax if necessary.

No need :)
