### ISSUE TITLE
sql exception

### ISSUE THREAD

**Issue by Zacushka** [lucko/LuckPerms#1887]
I get this https://hatebin.com/lizbknwjsq with using this command "lp user %player% meta setprefix 1 &6◆Bronze◆ towny"
I believe it only happens when symbols are included in the command.  I am using lp v. 4.4.1

Here are some screen sh
![databse](https://user-images.githubusercontent.com/59065830/71202755-d1cd6c80-226a-11ea-8b82-e44bc3656834.png)
![database2](https://user-images.githubusercontent.com/59065830/71202757-d2fe9980-226a-11ea-8a1a-162189e67475.png)

**Comment by BrainStone** [comment]
This seems to be related to #1586, but as you can see in the screenshots the table is using the utf8mb4 encoding,

**Comment by Andre601** [comment]
Did you actually try it with the [latest download](https://luckperms.net)?
It may have been already fixed as 4.4.1 is not the newest version at all.

**Comment by BrainStone** [comment]
Should not make any difference in this case, since 4.4.1 was released after the fix introduced is response to the original issue. And the tables look like they should with that fix.

**Comment by Zacushka** [comment]
I will update once I install the latest

**Comment by Zacushka** [comment]
https://hatebin.com/twbtymvzbm
This is with the current version
Prefix assigning from game in game command with symbols in prefix cause this.

**Comment by lucko** [comment]
I'm not sure this is a LP issue to be honest - can't see how it could be doing anything wrong encoding wise. Might be a case of https://github.com/lucko/LuckPerms/wiki/Storage-system-errors

**Comment by BrainStone** [comment]
Could you show us the structure of all tables?  
I have an idea.

**Comment by electronicboy** [comment]
https://github.com/lucko/LuckPerms/blob/master/common/src/main/java/me/lucko/luckperms/common/messaging/sql/AbstractSqlMessenger.java#L57
Collation of the messaging table isn't set to utf8_mb4, so; Will be using the platform default

**Comment by lucko** [comment]
Ah crap yeah, I glossed over this being related to SQL messaging and not normal storage.
