### ISSUE TITLE
Add a way to merge 2 groups into one

### ISSUE THREAD

**Issue by CyberFlameGO** [lucko/LuckPerms#1888]
Like /lp mergegroup <group1> <group2> as in the first group stated gets merged into the second group however we still have to delete the old group

**Comment by Turbotailz** [comment]
Eventually the web editor will let you move permissions from one group to another so this might not be needed in LP itself.

**Comment by lucko** [comment]
Out of scope for the plugin I think. Would be cool to be able to drag/drop in the editor though.
