### ISSUE TITLE
Kicked whilst connecting to LOBBY: [LP] A database error occurred whilst loading permissions data. Please try again later. If you are a server admin, please check the console for any errors.

### ISSUE THREAD

**Issue by HadockKali** [lucko/LuckPerms#1889]
As the title says I'm too tired to deal with it, uploaded the whole network take what do you need from it please just tell me how to fix it or even better, just modify it and I will give you the upload link, I spent 5 hours trying to fix this error but no luck, searched all the available threads and everything, please help me.
Server Link: https://drive.google.com/file/d/1ZxJP2KhmcI8DaIxvo9kl5PENC1nvPD1H/view?usp=sharing

Feel free to modify the settings and tell me what the f*ck is wrong because I can't fuc*ing figure it out. Thanks in advance. [Latest ver of LP, imported LP table, configured MySQL also check INSTALL.yaml file to see a complete list of what I have done inside the server files] Please I beg of you help me.

**Comment by HadockKali** [comment]
The networking side is handled already, the main problem is I can't connect to the server. Please any help is appreciated

**Comment by BrainStone** [comment]
Check the console for errors. Including during startup.

**Comment by HadockKali** [comment]
Thanks, I know what kind of place is it, just gave the whole package for people interested in details, less talking more working you know? Anyway, no errors during runtime. No error during setup and no error during lp import ranks.yml command. If it was a simple obvious problem I wouldn't be here right now. Thanks for your opinion, double-checked if I can see any runtime errors, and still nothing, the console is clean.

**Comment by HadockKali** [comment]
Maybe description was a little too rough, I am stressed enough because of this situation, sorry if I offended someone, just 5 hours of continuous debugging it's not the best thing I could have done today.

**Comment by BrainStone** [comment]
I'd be expecting a startup error. Especially related to MySQL.

**Comment by HadockKali** [comment]
Figures, MySQL initializes just fine, no problems there either.

**Comment by BrainStone** [comment]
Can we still have your log?

**Comment by HadockKali** [comment]
Wich one, bungee or backend server lobby?
[This was the main reason I included the server files]

**Comment by HadockKali** [comment]
here's bungee 
[latest.log](https://github.com/lucko/LuckPerms/files/3990287/latest.log)

**Comment by HadockKali** [comment]
and here's backend server [LOBBY] 
[latest.log](https://github.com/lucko/LuckPerms/files/3990288/latest.log)

**Comment by HadockKali** [comment]
Tell me if you need the plugins list or certain versions of things, pretty much using the latest with everything.

**Comment by Andre601** [comment]
You are aware that you can send ONE single comment right?
It is rather annoying for people to receive 3 separate notifications (through e-mail) which could easly be summed up into one major comment itself.

Also, not everyone wants to download files. It's recommended to upload them to https://hasteb.in instead.

**Comment by HadockKali** [comment]
Thanks, and sorry, just a little overwhelmed by this issue, from now on I will send compressed messages in single comments and upload it to pastebin or hastebin. Thanks for the advice.

**Comment by BrainStone** [comment]
I really don't mean to be a dick but what's that on line 143 and following of your lobby log? (P.S.: Why did you send the bungee log if there's no LP installed?)

Anyways the guide to fix MySQL errors is here: https://github.com/lucko/LuckPerms/wiki/Storage-system-errors

**Comment by HadockKali** [comment]
Yeah, that fixed it, I don't know how I overlooked whole lines like that. So very sorry for the unnecessary trouble, and thank you so much @BrainStone . The Bungee server had LP for Bungee installed but had disabled it in the latest run, the same issue. Again, sorry for the trouble and thank you!

**Comment by Sqw6** [comment]
как вы это решили?
