### ISSUE TITLE
Per server group feature request

### ISSUE THREAD

**Issue by lcswolf** [lucko/LuckPerms#189]
a per server group facility would be very useful having per server permissions is useful but having global groups and server specific groups could make factures like having global mod and admin ranks easy along with per server donation ranks etc less complex to implement and prevent groups bleeding over each other

**Comment by lucko** [comment]
It exists already.
`/lp user <user> parent add <group> [server]`

**Comment by lcswolf** [comment]
that only gives permissions to a server i am talking about having global groups but also having one group just for a server only

**Comment by lucko** [comment]
You just set the group to apply on a specific server.

**Comment by lcswolf** [comment]
oh so there is a way i must have been missing it in the wiki at first i thought it was along the lines of /lp creategroup group server but that did not work and i could not see anything about it in the wiki

**Comment by lucko** [comment]
Yup, I wrote out the command you need above.

**Comment by lcswolf** [comment]
Thank you :)
