### ISSUE TITLE
Static Contexts

### ISSUE THREAD

**Issue by Olek012** [lucko/LuckPerms#1890]
How can I add more than one server-type context?

**Comment by Andre601** [comment]
You add the perm multiple times, each one with another context

**Comment by Olek012** [comment]
Can you send me an example of the contexts.json ?

**Comment by lucko** [comment]
There's an example here.

https://github.com/lucko/LuckPerms/wiki/Context#defining-static-contexts

If you want to add more, do so like this:

```json
{
  "static-contexts": {
    "server-type": ["skyblock", "normal"]
  },
}
```
