### ISSUE TITLE
[Suggestion] Add PEX default groups as parents to default on migration

### ISSUE THREAD

**Issue by Andre601** [lucko/LuckPerms#1891]
The idea is, that each group, which is set as default in PEX would be added as a parent to default, to keep the behaviour people (most likely) had with their PEX setup, which is to have multiple groups being applied by default.

**Comment by lucko** [comment]
I'd rather leave this as a manual step after the migration.

**Comment by Andre601** [comment]
Maybe at least consider it as a config option which is false by default?

**Comment by BrainStone** [comment]
I am for this feature. As the goal of a migration is to make things work as closely as the original as possible.  
Which certainly includes the default group. And I've seen my fair share of people that get tripped up by that.

Keep in mind that the average user is not a power user. They want things to work. (Same as with the `rename` and `removegroup`)
It's always good to have an option. But the default should be what the average user wants/needs.

A simple true/false flag as an additional paramater that defaults to adding the default group should do the trick.
