### ISSUE TITLE
[Suggestion] Capitalize the check permission placeholder output.

### ISSUE THREAD

**Issue by blaukat99** [lucko/LuckPerms#1892]
Hey folks! I have a very simple request, I am using the luckperms check-permission placeholder to show players if they have unlocked a certain particle or not, and [as you can see](https://imgur.com/a/klFgK5a) in the menu it looks pretty bad. It would be nice if you could capitalize the yes or no and maybe make it green if yes, and red if no.

Thanks!
~Elias

**Comment by electronicboy** [comment]
Formatting is basically up to you, people often use the javascript placeholder stuff for "prettifying" this type of output, catering the output for specific needs really ain't doable, especially as such a change would be unwelcome to others (and potentially break people relying on the current behavior)
