### ISSUE TITLE
[Suggestion] Placeholders for other users / groups instead of the user itself

### ISSUE THREAD

**Issue by Martijnkop** [lucko/LuckPerms#1893]
Hey! I have a request, because I want to use the check-permission for a staff GUI, where you can see (and change) if sertain roles / users have a permission. However, currently I can only check for permisisons on my own player, using the placeholders. Could you add a placeholder similar to `%luckperms_group_<group>_check_permission_<permission>%`? (and the same for user)

**Comment by Andre601** [comment]
I think this would be out of scope for LP, especially considering how PlaceholderAPI (and probably MVdWPlaceholderAPI) handle placeholders.
You should look if your GUI plugin may have an option for using a placeholder for other people instead of the executor.

**Comment by lucko** [comment]
I agree, I think this is probably out of scope for the time being. Sorry.
