### ISSUE TITLE
Only works when I use vpn

### ISSUE THREAD

**Issue by Jeffreygob** [lucko/LuckPerms#1894]
I set up my server with a vpn, and a while later I truned off my vpn and attempted to change some permisions for my vip rank and it didn't work, then when I put my vpn back on it did work. Is there a way I can authorize both ips or something? When I go with no vpn, it says "Loading Error: Either the URL was copied incorrectly or the session has expired. Please try again.

**Comment by Andre601** [comment]
Are you talking about the web editor?
If you do, make sure that you allow Javascript and that the address of the editor might not be blocked from your country.

**Comment by Jeffreygob** [comment]
The both ips are in the united states, how would I check that I have allowed javascript?

**Comment by Andre601** [comment]
You check this in your browser settings.
Also, could you provide a link to an editor session so that we can check it?

**Comment by Jeffreygob** [comment]
https://luckperms.net/editor/#uIcEBpEN6O

**Comment by Jeffreygob** [comment]
the links work with the vpn, but not without

**Comment by Andre601** [comment]
The link works for me so it must be something on your end.

**Comment by Jeffreygob** [comment]
hmmm, ok I understand. I think I know what it is. Thank you!
