### ISSUE TITLE
DeluxeChat and LuckPerms

### ISSUE THREAD

**Issue by SevenX159** [lucko/LuckPerms#1895]
After Updating LuckPerms from 4.3.731 to 5.0.37 My Deluxe chat was totally broken. (Nothings Works)

On each messages send in the server, there is a Error poping up in console

https://pastebin.com/zx6DQpXp

**Comment by Andre601** [comment]
Could be an issue with the legacy-API extension.
Did you try re-downloading it to exclude any possible corruption of the jar?

Other than that would this be an issue that @lucko needs to look into.

**Comment by BrainStone** [comment]
Which is why I asked them to open this issue. As that seems to be a bug.  
Might even be related to a recent commit.

**Comment by SevenX159** [comment]
Well i Started it with the extension first, I wasn't even able to join my server and all my Plugins was just spamming errors, 
So i joined Discord, see that it needed the extensions, installed it, 
All plugin was back to normal exept Deluxechat 
So i don't think that might be because of a Corrumption otherwise my other plugins would have stopped working even with the extension

**Comment by lucko** [comment]
Should be fixed by 97f30ce63b32663a0481557f3a081a9554a5bca0

Please try updating `extension-legacy-api` to the latest version. :)
