### ISSUE TITLE
Webeditor does not work with paper1.15

### ISSUE THREAD

**Issue by Destroyer4LP** [lucko/LuckPerms#1897]
If I start the web editor with `/lp editor all` the link that I get only shows me: 

>  LuckPerms Logo
LuckPerms
Web Permissions Editor
To start a new editor session, please use
/lp editor
/lp user <user> editor
/lp group <group> editor

**Comment by Andre601** [comment]
all is not an argument.
Just use `/lp editor` and show us the output of it.

Also, what version of LP are you using?

**Comment by BrainStone** [comment]
First of all. If it gives you a link then it works in the server meaning there’s another issue.

Can you please post the link it gives you?

**Comment by Destroyer4LP** [comment]
I use Luckyperms v4.4.1. I had tied `/lp editor  /lp group default editor  /lp editor all` all of them gave me the same result.
> lp editor
[18:13:59 INFO]: [LP] Preparing a new editor session. Please wait...
[18:13:59 INFO]: [LP] Click the link below to open the editor:
[18:13:59 INFO]: https://luckperms.github.io/editor/#HY8jgwcDRp
> lp
[18:16:17 INFO]: [LP] Running LuckPerms v4.4.1.
[18:16:17 INFO]: [LP] Use /lp help to view available commands.

**Comment by Andre601** [comment]
> I use Luckyperms v4.4.1. I had tied `/lp editor /lp group default editor /lp editor all` all of them gave me the same result.
> 
> > lp editor
> > [18:13:59 INFO]: [LP] Preparing a new editor session. Please wait...
> > [18:13:59 INFO]: [LP] Click the link below to open the editor:
> > [18:13:59 INFO]: https://luckperms.github.io/editor/#HY8jgwcDRp
> > lp
> > [18:16:17 INFO]: [LP] Running LuckPerms v4.4.1.
> > [18:16:17 INFO]: [LP] Use /lp help to view available commands.

1. [**Luck**Perms, not LuckyPerms](https://andre601.com/luckperms)
2. The link works for me, so it is most likely an issue on your end.
Make sure your browser doesn't block javascript and that you use a supported one (i.e. Chrome, Opera, Firefox)

**Comment by BrainStone** [comment]
Loads for me. This means your browser or your personal internet connection is the issue.  
See if you can access https://bytebin.lucko.me/HY8jgwcDRp

**Comment by BrainStone** [comment]
Btw we also recommend you update LP to v5 (https://luckperms.net/)

**Comment by Destroyer4LP** [comment]
I know now what my issue was. I use piehole a DNS-server that blocks ads and tracking scripts. It somehow blocked some scripts. I was wondering before why I never noticed the updates on luckyperms.net 
Thank you for your quick help <3

**Comment by Andre601** [comment]
[**Luck**Perms, not LuckyPerm](https://andre601.com/luckperms)
