### ISSUE TITLE
I Can't use /ban even though i have Op and * added to my rank

### ISSUE THREAD

**Issue by SirRicharalar** [lucko/LuckPerms#190]
I can use /nucleus:ban ... but on pex i was able to just /ban {player} without a problem. it happens with /back too. players have to use /nucleus:back

https://gyazo.com/604891839930294ee9c0f51ca1b10f82

**Comment by lucko** [comment]
If you're having trouble with aliases, then that's not a permissions issue. 

Try asking for help in the Nucleus Discord, or post an issue on their GitHub instead. :)
