### ISSUE TITLE
Permission Cache not refreshing on change

### ISSUE THREAD

**Issue by bloodmc** [lucko/LuckPerms#1900]
Currently in v5, any permission changes I set via API are not reflected in permission cache until the current cached data expires.

```
group.getCachedData().invalidate();
for (User user :this.luckPermsApi.getUserManager().getLoadedUsers()) {
    user.getCachedData().invalidate();
}
```
To work around this issue in the past, I would force a cache invalidation on permission set as shown above but this does not work with v5.

Tested using LP 5.0.37

**Comment by lucko** [comment]
b2593d409ed583c175069ce2bb61d88525f2151b
