### ISSUE TITLE
Permissions don't seem to be working. I am very new to this

### ISSUE THREAD

**Issue by SirMichael87** [lucko/LuckPerms#1901]
Server version: 1.14.4-RO.1-SNAPSHOT git-Paper-226 (MC:1.14.4)
EssentialsX version: 2.17.1.0
Vault version:1.7.2-b107
EssentialsXProtect version 2.17.1.0
EssentialsXGeoIP version: 2.17.1.0
EssentialsXChat version 2.17.1.0
EssentialsXSpawn version: 2.17.1.0
EssentialsXXMPP version: 2.17.1.

src="https://gist.github.com/SirMichael87/1cafd2c3f5213f88cbfa07542920c2e8" src="https://gist.github.com/SirMichael87/8efaf65724e6d8c342854987dddeca62"
Help request
Problem
I have a plan to only add certain permissions for members and admin. /w and /msg are not working for members. I also want members to be able to /pay /sell and /balance.
I have tried to add permissions plugins, but i don't know what I am doing. please help

**Comment by SirMichael87** [comment]
seems like a silly issue to some of you i am sure, but i don't know what i am doing. the essentialsx is pretty much a necessity but it removed members ability to whisper and i can't figure out how to change it

**Comment by Andre601** [comment]
Multiple things:

1. Don't add a .js to the link of the gist. That makes it more difficult for us to read the issue(s) you have.
2. Your server icon has an invalid size. It needs to be 64x64 pixels.
3. All your Essentials plugins have an invalid plugin.yml. Make sure you downloaded the right version for your server and that you **extracted** the jar files from the zip file if you downloaded it as such.
   1. On a side note. Don't just install all essentials extensions. It's stupid and not worth it as there are better alternatives for things like protection. Just keep EssentialsX, EssentialsXSpawn for the /spawn command and EssentialsXChat for chat formatting.
4. You can find all permissions for EssentialsX here: https://essinfo.xeya.me/index.php?page=permissions
5. Installation-instructions for LuckPerms can be found here: https://github.com/lucko/LuckPerms/wiki/Installation
6. Info about the usage of LuckPerms here: https://github.com/lucko/LuckPerms/wiki/Usage

**Comment by SirMichael87** [comment]
what do you mean by invalid plugin.yml? does that mean they are out of date?

**Comment by Andre601** [comment]
> what do you mean by invalid plugin.yml? does that mean they are out of date?

> 2. All your Essentials plugins have an invalid plugin.yml. Make sure you downloaded the right version for your server and that you extracted the jar files from the zip file if you downloaded it as such.
>    1. On a side note. Don't just install all essentials extensions. It's stupid and not worth it as there are better alternatives for things like protection. Just keep EssentialsX, EssentialsXSpawn for the /spawn command and EssentialsXChat for chat formatting.

**Comment by SirMichael87** [comment]
good sir. I read what you said. i followed the installation procedures. I removed extensions that we weren't going to use.

**Comment by SirMichael87** [comment]
according to what I have read the Essentials plugins are the correct version for my server.

**Comment by SirMichael87** [comment]
https://gist.github.com/SirMichael87/6ced083fa1e602ff19512a6f125b462c

**Comment by i9hdkill** [comment]
Not an lp issue. 
Essentials archives are corrupted. They are probably not uploaded correctly to the server or your antivirus damaged the archive for some reason after downloading.
If you still cant figure out, ask in esentialsX help discord/and or spigot forums

**Comment by SirMichael87** [comment]
> Not an lp issue.
> Essentials archives are corrupted. They are probably not uploaded correctly to the server or your antivirus damaged the archive for some reason after downloading.
> If you still cant figure out, ask in esentialsX help discord/and or spigot forums

should I delete them and reinstall in the plugins folder?

**Comment by i9hdkill** [comment]
> should I delete them and reinstall in the plugins folder?

yes

**Comment by SirMichael87** [comment]
> > should I delete them and reinstall in the plugins folder?
> 
> yes

well it didn't work.. so... ugh.. okay

**Comment by SirMichael87** [comment]
okay. my plugins are in order...
can someone please walk me through adding certain permissions for regular members... not admins...
installing essentials stopped people from being able to /whisper. i also want them to be able to /pay, /sell, and /balance

**Comment by i9hdkill** [comment]
> Multiple things:

> 6. Info about the usage of LuckPerms here: https://github.com/lucko/LuckPerms/wiki/Usage

This tracker is for bugs only, ask in discord, but please read the wiki first
