### ISSUE TITLE
The database is deleted when I turn the server off and on. 1.15.1

### ISSUE THREAD

**Issue by successed** [lucko/LuckPerms#1907]
I switched from version 1.14.4 to version 1.15.1. Groups were deleted after upgrading to version 1.15.1. When I checked the Luckperm files, I found that the size of the database file was too small.I have a backup system and I installed the luckperms database file from the backup system I used in 1.14.4 while the server was off. I ran the server and the groups came back, there was no problem, then when I shut down the server again with the stop command, the groups were deleted again.

The database is deleted when I turn the server off and on. 1.15.1

Luckperm version : LuckPerms-Bukkit-5.0.39

Luckperm config:

[config (3).txt](https://github.com/lucko/LuckPerms/files/4012820/config.3.txt)

Server version : 1.15.1 Paper #32

Console : 

```
[16:31:15] [Server thread/INFO]: [LuckPerms] Enabling LuckPerms v5.0.39
[16:31:15] [Server thread/INFO]:         __    
[16:31:15] [Server thread/INFO]:   |    |__)   LuckPerms v5.0.39
[16:31:15] [Server thread/INFO]:   |___ |      Running on Bukkit - Paper
[16:31:15] [Server thread/INFO]: 
[16:31:15] [Server thread/INFO]: [LuckPerms] Loading configuration...
[16:31:16] [Server thread/INFO]: [LuckPerms] Loading storage provider... [H2]
[16:31:19] [Server thread/INFO]: [LuckPerms] Loading internal permission managers...
[16:31:19] [Server thread/INFO]: [LuckPerms] Loading extension: me.lucko.luckperms.extension.defaultassignments.DefaultAssignmentsExtension (extension-default-assignments-1.0.0 (1).jar)
[16:31:19] [Server thread/INFO]: [LuckPerms] Loading extension: me.lucko.luckperms.extension.legacyapi.LegacyApiExtension (extension-legacy-api-1.0.0.jar)
[16:31:20] [Server thread/INFO]: [LuckPerms] Performing initial data load...
[16:31:20] [Server thread/INFO]: [LuckPerms] Successfully enabled. (took 5143ms)
```

**Comment by Andre601** [comment]
You don't provide enough information for us to actually help you.
Please make sure you provide the following information:
- Any error you encountered (Upload the content of your logs on https://hasteb.in or similar)
- What Server or Proxy type are you running?
  - What is the version of it?
- What LuckPerms version are you running?
- What are your config settings? (Remove any potentially sensitive data like passwords before sharing the file)

### Additional Links/Information
**Synchronizing groups, permissions, etc. accross servers**:
https://github.com/lucko/LuckPerms/wiki/Network-Installation

**Setup prefixes/suffixes and display them in chat, tablist, etc.**:
https://github.com/lucko/LuckPerms/wiki/Prefixes,-Suffixes-&-Meta

**Storage system errors (MySQL/MariaDB related errors)**:
https://github.com/lucko/LuckPerms/wiki/Storage-system-errors

**Comment by successed** [comment]
> You don't provide enough information for us to actually help you.
> Please make sure you provide the following information:
> 
> * Any error you encountered (Upload the content of your logs on https://hasteb.in or similar)
> * What Server or Proxy type are you running?
>   
>   * What is the version of it?
> * What LuckPerms version are you running?
> * What are your config settings? (Remove any potentially sensitive data like passwords before sharing the file)
> 
> ### Additional Links/Information
> **Synchronizing groups, permissions, etc. accross servers**:
> https://github.com/lucko/LuckPerms/wiki/Network-Installation
> 
> **Setup prefixes/suffixes and display them in chat, tablist, etc.**:
> https://github.com/lucko/LuckPerms/wiki/Prefixes,-Suffixes-&-Meta
> 
> **Storage system errors (MySQL/MariaDB related errors)**:
> https://github.com/lucko/LuckPerms/wiki/Storage-system-errors

Corrected, what's not enough?

**Comment by lucko** [comment]
Hey, just to be clear - when you upgrade your _server_ version from 1.14 to 1.15 - the groups disappear - or are you talking about upgrading from LP v4 to v5?

**Comment by successed** [comment]
> Hey, just to be clear - when you upgrade your _server_ version from 1.14 to 1.15 the groups disappear - or are you talking about upgrading from LP v4 to v5?

I'm already using version 5, I'm constantly use latest the plugin. I didn't new update the plugin. I just upgraded the server from 1.14.4 to 1.15.1.

**Comment by lucko** [comment]
Could you try the upgrade again. The server version should have no effect on the LP storage system.

**Comment by successed** [comment]
İ have fixed this problem. İ removed lib direction and reload, it is fixed.
