### ISSUE TITLE
'setsuffix' Issue

### ISSUE THREAD

**Issue by Cheesearmada** [lucko/LuckPerms#1910]
When executing command with syntax 'meta setsuffix' the command does not remove and then set the new suffix, instead it just stacks on itself.

Luck Perms Version: v5.0.50

Server Version: Spigot-1.14.4

![Screen Shot 2020-01-01 at 10 23 52 PM](https://user-images.githubusercontent.com/53283473/71651716-6ad99a00-2ce5-11ea-8f69-252b423d9a21.png)

**Comment by lucko** [comment]
![](https://i.imgur.com/c0Qr6oV.png)

Seems to be working fine for me.

**Comment by Cheesearmada** [comment]
Does not appear to work for us.

Could us using MySQL have any affect on this?

- 'lp user %player% meta setsuffix 5000 " &7[&d&lAussie&7]&r" global'

**Comment by Andre601** [comment]
global is optional btw.

**Comment by Cheesearmada** [comment]
I provided that as an example of a command we're trying to use. Unfortunately for us, the 'setsuffix' command is performing the same function as the 'addsuffix' command, or at least emulating it. Perhaps I didn't do a good job of describing my situation. 

We use a GUI that players can select/purchase a suffix with points. When they click on the suffix they want, the 'lp user %player% meta setsuffix 5000 " &7[&d&lAussie&7]&r" global' command is executed. However, when a player wants to select a new suffix, the 'setsuffix' command doesn't overwrite the old suffix, instead it just adds a suffix, if that makes sense.

**Comment by Andre601** [comment]
The setsuffix command is essentially a simplified version of the addsuffix command with the difference, that the priority *should* be optional and LP would calculate a own weight to use to display the suffix.

It only replaces suffixes that are the same context as the one you set.

Quote from the [command page](https://github.com/lucko/LuckPerms/wiki/Command-Usage:-Meta#lp-usergroup-usergroup-meta-setsuffix-priority-suffix-context)
> This is different from the addsuffix command in that **existing suffixes set in the same context are removed when the new suffix is added.** Another difference is that the priority argument is optional in the setsuffix command - LuckPerms will determine an appropriate value for the priority when the command is ran.

**Comment by lucko** [comment]
Try removing the `global` bit at the end of the command - I think that will probably fix your problem.
