### ISSUE TITLE
suggestion: player's current world meta

### ISSUE THREAD

**Issue by AeSix** [lucko/LuckPerms#1916]
I don't know how useful this would be to anyone else, but figured I'd suggest it anyways.

This suggest relies on a potential future change to LPB, renaming 'server' to 'proxy' and 'world' to 'server'  (or which ever words would be used, BrainStone said this was a possibility in the future)

What I suggest is that LuckPerms catches world changes for players, and sets the player's "world meta" to the name of that world.  Then, LPB could then read that meta to be used for LPB's 'world' context.  

This would allow plugins to know which world a player is in on which server.

**Comment by lucko** [comment]
Yes, the rename is still planned (see #1668) - caching contexts so they can be used between different LP instances isn't something I want to implement in the plugin itself,  although of course there's no reason why an external plugin couldn't do this.
