### ISSUE TITLE
How Do I Stop This?

### ISSUE THREAD

**Issue by SirRicharalar** [lucko/LuckPerms#192]
I am running a command through command kits and it gives different results to when I run it through myself in game:

here is my command kit config: this command is suppose to give that player a new prefix
https://gyazo.com/eeffd43f0da3c7ff8762ae43990ec615

The Prefix before command: it will stay this way if run through CK pluggin
https://gyazo.com/ad1568fee95c5dd33d2fcd189ca113f2

This is me running the command in game exactly the same:
https://gyazo.com/4b96fb053e04d4a41f9df2a023a37f1f

You can see it works here:
https://gyazo.com/04546a940854bcc2993d6fcbb2da26e9

Console output of running the CF command:
https://gyazo.com/db3df4c25568ed5d6295a3a184f1830a

You can see in the last one for some reason its sending it to server NULL and doesn't finish the prefix after [Type ...

**Comment by SirRicharalar** [comment]
it worked fine when I was using Pex before

**Comment by lucko** [comment]
Nucleus issue.

You need to escape the `" "` quotes in the config file.

**Comment by dualspiral** [comment]
This isn't a Nucleus problem, this is a problem with Command Kits - @SirRicharalar You need to direct your query to them.

**Comment by lucko** [comment]
My bad, I assumed that "commands kits" was a Nucleus module. :P

**Comment by dualspiral** [comment]
I hope it will be... eventually!

**Comment by SirRicharalar** [comment]
It's not the "" because i've tried everything, i even replaced them with ' ' which still works the same, but does the same thing

**Comment by lucko** [comment]
You need to use `" "` for LuckPerms commands.

**Comment by SirRicharalar** [comment]
Yeh, but for some reason it says this
https://gyazo.com/db3df4c25568ed5d6295a3a184f1830a

There is no server null ... thats part of the command/rank "&7[&cType: Null&7] " it thinks that null is a server

**Comment by lucko** [comment]
Because the quotes aren't being picked up.
