### ISSUE TITLE
Lucky Perms and Essentials 

### ISSUE THREAD

**Issue by Renetaku** [lucko/LuckPerms#1921]
For the past 2 days I was doing permission related things on my server(I'm new), however, permission-EX stopped working and I found luckperms which was better, however when I added permissions for the /warp **(essentials.warps.*/essentials.warp.list/essentials.warp)** commands in essentials, it wouldn't work no matter what and later permissions such as /nick broke down as well, please help!

**Comment by Andre601** [comment]
Make sure you removed PermissionsEx from your server as LuckPerms won't manage perms as long as it is still on the server.
You could also [migrate your permissions](https://github.com/lucko/LuckPerms/wiki/Migration) from PEX to LuckPerms.

Next, make sure you're using Essentials**X** and not Essentials (Run `/ess version` to proof this. If it only displays that Essentials was reloaded, then you're running the wrong version).
Essentials is not supported as it is outdated. Switch to EssentialsX instead. A link can be found [here](https://ci.ender.zone/job/EssentialsX/).

Other than that make sure that there are no startup errors or errors in general (check console).
If there are, copy and paste them on [hasteb.in](https://hasteb.in) before sending us the link.

**Comment by Renetaku** [comment]
Thanks for the fast reply, however, i believe that Permission-EX is not the problem because I'm also testing this on a separate server with only luckperms and basic plugins.
after running the command `/ess version` as instructed, the server replied with(sorry I don't know how to add a screenshot):
EssentialsX version: 2.17.1.0
LuckPerms: 4.4.1
**Vault is not installed. Chat and permissions may not work.**
You are running an unsupported server version!

Does this mean I need to install vault?
(sorry for the late reply I timeout and got invalid login session and had to reboot game)

**Comment by Andre601** [comment]
This part here seems interesting:
> You are running an unsupported server version!

What server version and what server type are you running?
And it wouldn't hurt to try using Vault too :)

**Comment by Renetaku** [comment]
I dont't believe there is any start up errors as im only using
BackToTheRoots (1.8 PvP)
Core Protect
EssentialsX ver 4.4.1
LuckPerms
WorldEdit
I am also hosting the server on minehut

**Comment by Renetaku** [comment]
> This part here seems interesting:
> 
> > You are running an unsupported server version!
> 
> What server version and what server type are you running?
> And it wouldn't hurt to try using Vault too :)

Erm I'm sorry about this but I don't know what server type I am currently using, however, I DO know that the server is hosted on Minecraft version 1.15.1 (because minehut only hosts its servers on the latest version of Minecraft).

If you may could you please(i know this is unrelated) roughly explain what 'Vault' is because i read the entry on spigot and i have no clue what it does.

**Comment by Andre601** [comment]
You can use `/version` to get the info about the server, like version, type, etc.

And Vault is a general API used by many plugins. It allows to connect multiple plugins with each other by providing a simple API.
Like f.e. a plugin manages money and now Essentials wants to know the money of Player X. Instead of having to hook into the API of x plugins to retrieve the balance, does it just use vault and get it through it.

This is kinda how Vault acts... Just imagine it as a major plugin many other plugins support or even require.

**Comment by Renetaku** [comment]
A little update: I have installed vault and rebooted the server, instead of saying (i dont remember the exact words :P)  'There are no available warp for you', it now says 'you do not have access to that command'.

**Comment by Andre601** [comment]
Make sure you actually have the right permissions set.

A list of all permissions from EssentialsX can be found [here](https://essinfo.xeya.me/index.php?page=permissions)

**Comment by Renetaku** [comment]
> You can use `/version` to get the info about the server, like version, type, etc.
Thanks, I did that in-game and it replied that I am running **Paper**, and I am 3 versions behind :(

**Comment by Renetaku** [comment]
> Make sure you actually have the right permissions set.
> 
> A list of all permissions from EssentialsX can be found [here](https://essinfo.xeya.me/index.php?page=permissions)

Yes, I'm sure that I am using the right permission sets, because 'the sets' worked in permission EX and I actually copied them directly from that page you've sent and pasted it into the luckperms online editor(very cool).

**Comment by Turbotailz** [comment]
Since you are using Minehut, I would consider contacting their support. They like to edit plugins so they don't cause any issues with their infrastructure and may likely cause issues. LuckPerms v4 is quite old now and I'd highly recommend you upgrade to v5 but I don't think that will be possible for you.

I'd also recommend using another host which gives you more control over your server.

**Comment by Renetaku** [comment]
Okay looks like I have to contact minehut, but thank you for the support!
