### ISSUE TITLE
Warn users about migration mode

### ISSUE THREAD

**Issue by BrainStone** [lucko/LuckPerms#1923]
It has come to my attention that many users forget to remove their old permission plugin when migrating or try to use two perm plugins.

Since LP already detects that (for migration purposes) I think it would make sense to warn players that another permission plugin is installed at that theý need to remove it (after the migration if they want to migrate) when they use LP commands and at the end of the migration command.  
Maybe also display a warning to players with the log permission when they log in.

Just a quality of life feature but I think it could help a lot of people.

**Comment by Andre601** [comment]
Something like `[Migration] Done! Remember to stop your server and remove your old permission plugin, to make the migration take affect.` perhaps?

**Comment by BrainStone** [comment]
And when running a normal command something like `Hey. You still have another permission plugin installed. If you want to migrate from that, please migrate, else remove it, or LuckPerms won't manage your permissions`
