### ISSUE TITLE
Question about extension default-assignments

### ISSUE THREAD

**Issue by TheCalypso** [lucko/LuckPerms#1924]
Hello, I need your help to be able to correctly go to version V5 of the plugin. Here is my configs as a whole.

confi.yml: https://pastebin.com/5v5YkYu4
default.yml: name: default
joueur.yml: https://pastebin.com/TXEVvBt8

Currently I am using the extension you provided. However as you said it is only temporary so I would like your help to make the transition correctly.

Very nice work on this new version! Congratulations !

**Comment by Andre601** [comment]
Just make joueur a parent of default.

**Comment by TheCalypso** [comment]
Hello, how do you think I do this?

**Comment by Andre601** [comment]
This is explained here: https://github.com/lucko/LuckPerms/wiki/Default-Groups#configure-inheritance

**Comment by TheCalypso** [comment]
![image](https://user-images.githubusercontent.com/33781244/72688246-8c1ff000-3b05-11ea-8d95-766c94398582.png)

**Comment by Andre601** [comment]
I directed you to the actual section:
https://github.com/lucko/LuckPerms/wiki/Default-Groups#configure-inheritance (Note the **#configure-inheritance**)
