### ISSUE TITLE
LuckPerms blocked towny and granted jobs permissions

### ISSUE THREAD

**Issue by Feldmarschall** [lucko/LuckPerms#1928]
Hello, 

i have a problem with LP.
My server version: Paper-45 (1.15.1_R01 Snapshot)
LP: v5.0.39

LP blocked towny and granted jobs permissions. (jobs reborn)

>     permissions:
>       worker.miner.1:
>         value: true
>         level: 1
>       worker.miner.3:
>         value: true
>         level: 3

This permissions gets a player, if they reach level 1 and 3, but its doesnt work with LP. LP block this. 
Same with custom townypermissions in the townyperms.yml

What can i do?

**Comment by Andre601** [comment]
I don't quite understand what you're trying to do... From where is that code-part you showed (Also better use code blocks)

**Comment by Feldmarschall** [comment]
I hope its better now.

You get permissions on the plugin jobs reborn, but its don't work... because LP block it..

**Comment by Andre601** [comment]
Maybe, maybe not. Did you first try to contact the dev of the Jobs reborn plugin?
Because I'm pretty sure that it isn't LPs fault and either a misconfiguration on your end or a plugin issue with Jobs Reborn.

**Comment by Feldmarschall** [comment]
ok, i was wrong and it is another mistake.
