### ISSUE TITLE
Plugin disables itself upon startup

### ISSUE THREAD

**Issue by LodtheFraud** [lucko/LuckPerms#1929]
Hi! Upon installing luckperms and running the server, I have been having the following issue. When trying to run a luckperms command I recieve a message saying "An internal error occured while trying to perform this command." When I looked into the issue further, the console had said the following:
[16:08:50] [Server thread/INFO]: [LuckPerms] Disabling LuckPerms v5.0.39
[16:08:50] [Server thread/INFO]: [LuckPerms] Closing storage...
[16:08:50] [Server thread/INFO]: [LuckPerms] Shutting down internal scheduler...
[16:08:50] [Server thread/INFO]: [LuckPerms] Goodbye!
Here is the full log file for the most recent attempt:
https://hasteb.in/vizefiki.md
Thanks for looking over this!

Edit: Information linked in a hastebin. Relevant info listed below:

- Server version - 1.15.1 running spigot
- Plugins list: BetterInvisibility, Chairs, DiscordSRV, Dynmap, EssentialsX, EssentialsXSpawn, Harbor, Imagemaps, LuckPerms, OldCombatMechanics, OpenInv, PlayerHeads, RottenFleshToLeather, Trade, Vault, Vivecraft_Spigot_Extensions

**Comment by Andre601** [comment]
Please share the log file through https://hasteb.in as not everyone wants to download files.

In addition does the part you show nothing special. Only that LP disabled itself, which is normal on server shutdown.
And finally did you not mention your server version, type and other information.

**Comment by Andre601** [comment]
I quickly checked your log and from what I saw does something/someone cause plugins to disable.
This happens **after** BetterInvisibility was enabled:
```
[16:08:50] [Server thread/INFO]: [BetterInvisibility] Enabling BetterInvisibility v1.1.0
[16:08:50] [Server thread/INFO]: [0;34;1m[[0;36;1mBetterInvisibility[0;34;1m][m [0;37;22mPlugin Version [0;36;1m1.1.0[m
[16:08:50] [Server thread/INFO]: [0;34;1m[[0;36;1mBetterInvisibility[0;34;1m][m - Server running version [0;33;1mv1_15_R1[m
[16:08:50] [Server thread/INFO]: [0;34;1m[[0;36;1mBetterInvisibility[0;34;1m][m [0;37;22m- File "[0;36;1mconfig.yml[0;37;22m" loaded![m
[16:08:50] [Server thread/INFO]: [Vault] Disabling Vault v1.7.2-b107
[16:08:50] [Server thread/INFO]: [BetterInvisibility] Disabling BetterInvisibility v1.1.0
[16:08:50] [Server thread/INFO]: [LuckPerms] Disabling LuckPerms v5.0.39
[16:08:50] [Server thread/INFO]: [LuckPerms] Closing storage...
[16:08:50] [Server thread/INFO]: [LuckPerms] Shutting down internal scheduler...
[16:08:50] [Server thread/INFO]: [LuckPerms] Goodbye!
```

**Comment by LodtheFraud** [comment]
Just edited the post to include more info. Now that I think of it, betterinvis was disabling itself even before I had added luckperms. I'm not sure if it would be relevant/cause a conflict though since the plugins seem very different in function.

**Comment by MWFIAE** [comment]
Ok, this is easily explained. 
BetterInvisibility only works for 1.8 - 1.14, you are using 1.15.1, therefore it disables itself.

Somehow this results in a chainreaction and also disables vault. 
And since vault is relevant to luckperms it also disables luckperms. 

Solution: Disable the plugin until it's ready for the version you are using :)

**Comment by Andre601** [comment]
> Ok, this is easily explained.
> BetterInvisibility only works for 1.8 - 1.14, you are using 1.15.1, therefore it disables itself.
> 
> Somehow this results in a chainreaction and also disables vault.
> And since vault is relevant to luckperms it also disables luckperms.
> 
> Solution: Disable the plugin until it's ready for the version you are using :)

Wrong.
If a plugin doesn't work for version x and disables itself due to that (Uses `PluginManager#disablePlugin(this)`) then it wouldn't cause a "chain-reaction".

Next would Vault never affect LuckPerms in any way. LuckPerms is a standalone plugin which doesn't depend on other plugins. It doesn't matter if Vault disables itself or not as LuckPerms wouldn't be affected by that. Only plugins using prefixes from LP through Vault would be affected.

**Comment by LodtheFraud** [comment]
Thanks, I deleted betterinvis and its working perfectly right now! You're both life savers :D

**Comment by MWFIAE** [comment]
>Wrong.

> I deleted betterinvis and its working perfectly right now!

Somehow not wrong ;)

**Comment by Andre601** [comment]
> > Wrong.
> 
> > I deleted betterinvis and its working perfectly right now!
> 
> Somehow not wrong ;)

A plugin disabling other plugins doesn't proof that it causes a "chain-reaction".
Maybe the author (for some reason) loops through all plugins and disables them?
My point is still right that just because plugin X got disabled, does plugin Y not disable itself too unless it depends on it.

**Comment by MWFIAE** [comment]
Just to do a little research I decompiled the plugin. 
Seems he just used the wrong method.

![image](https://user-images.githubusercontent.com/6072971/72226341-612b1e80-3590-11ea-82d5-ddea4dc24839.png)

Anyways my point was that it hasn't anything to do with luckperms and all with BetterInvisibility. 
And as the "somehow" should say: It wasn't anything I could explain why. Just the symptom.

**Comment by Andre601** [comment]
@LodtheFraud Since this issue got resolved, can you close it please? :)
