### ISSUE TITLE
[1.7.10]Luckperms-Legacy not loading 

### ISSUE THREAD

**Issue by Bubble0seven** [lucko/LuckPerms#193]
Plugin will not load at all on startup 

Version: LuckPerms-Bukkit-Legacy-3.0.0
Thermos Version: Thermos-1.7.10-1614

FML LOG [LOG](https://gist.github.com/Bubble0seven/69a14cf2587d98bc93627a26ee85dc87)

**Comment by Eufranio** [comment]
```
Caused by: java.lang.IllegalArgumentException: INVOKESPECIAL/STATIC on interfaces require ASM 5
```
Update your SpecialSource.

**Comment by Bubble0seven** [comment]
Um.....thanks I guess.....special source ......

**Comment by Eufranio** [comment]
The SpecialSource library included with Thermos uses ASM4.
Updating it to the latest version will fix the issue.

Instructions for updating to ASM5:

    Navigate to the libraries\net\md-5\SpecialSource\1.7-SNAPSHOT folder of the server
    Delete the SpecialSource-1.7-SNAPSHOT.jar jar file
    Download SpecialSource v1.7.4 from http://central.maven.org/maven2/net/md-5/SpecialSource/1.7.4/SpecialSource-1.7.4.jar
    Copy the jar file to the libraries\net\md-5\SpecialSource\1.7-SNAPSHOT folder
    Rename the jar file you just copied to SpecialSource-1.7-SNAPSHOT.jar

**Comment by Bubble0seven** [comment]
Thanks Eufranio much appreciated

**Comment by lucko** [comment]
Related CyberdyneCC/Thermos#498

**Comment by Eufranio** [comment]
Yeah. Thermos will not be updated so we have to fix it by ourselves.

**Comment by MaximusMcfly** [comment]
Guys, the old link has been deleted so heres the new one https://repo1.maven.org/maven2/net/md-5/SpecialSource/1.7.4/
