### ISSUE TITLE
support for placerholder+

### ISSUE THREAD

**Issue by BenjaminHoegh** [lucko/LuckPerms#1931]
Please add support for `+`

In this case a placeholder ends with +, meaning we insert a space " " automatically if it's not empty

**Comment by Andre601** [comment]
Placeholders, in general, shouldn't contain any characters other than alphanumerical ones (a-z and 0-9) as for issues like you experience right now.
You should report this to the dev of the plugin too, as it is against any common way of making permissions in a plugin work.

**Comment by BenjaminHoegh** [comment]
@Andre601 placeholders hasn't anything todo with permissions. Second placeholders with a + is normal just take a look at placeholderAPI Wiki

**Comment by Andre601** [comment]
> @Andre601 placeholders hasn't anything todo with permissions. Second placeholders with a + is normal just take a look at placeholderAPI Wiki

Just fyi: I made the wiki so I know it all too well, and if you look closely will you notice that none of the displayed placeholders contains a + (Ctrl + F, then search for "+" and the only thing you'll find is the names of the plugins)

**Comment by lucko** [comment]
Sounds like this is something that your placeholder plugin could provide. :)

I imagine it would also be quite easily done using PlaceholderAPI's JS expansion (https://github.com/PlaceholderAPI/Javascript-Expansion/wiki) - although you didn't specify which placeholder plugin you were using!
