### ISSUE TITLE
LP Editor Dropdown Missing all permission Nodes

### ISSUE THREAD

**Issue by Antonios-P** [lucko/LuckPerms#1932]
I recently restarted the server and I went to edit some more permissions with ```LP Editor``` and The dropdown for every rank showed no results. All help is appreciated. The dropdown says the list is empty even though I have defined lots of nodes for each rank. I am running PaperMC 1.15.1 Build 43.

**Comment by Andre601** [comment]
The editor can and will only show permissions that have been checked recently. If none shows, then most no permissions where checked when running the editor command.
Try running `/help` on the server before creating a new editor session.

This could perhaps also be related to latest change of the editor (https://github.com/lucko/LuckPermsWeb/commit/dce60098c265cd6f4bea69a5a0ab6a1b7d503745) which doesn't display permissions, when the permission field is empty.

**Comment by Antonios-P** [comment]
I'm still stuck on what to do. It worked on the latest version before the server restart. Doing /help didn't help much. Thanks

**Comment by Andre601** [comment]
Did you actually write the permission?
It shows "List is empty" when you didn't type anything and only start suggesting once you typed a few letters.

**Comment by Antonios-P** [comment]
Sorry about that. The perms show when I do that. With my previous experience, the would show without typing anything. That solved my issue!

**Comment by Andre601** [comment]
Like I mentioned in my previous comment was this changed recently.
