### ISSUE TITLE
Unable to use/interact with items

### ISSUE THREAD

**Issue by Antonios-P** [lucko/LuckPerms#1934]
Greetings. I recently tried to test whether permissions work properly, but I couldn't seem to be able to interact with anything. For example, I couldn't eat steak and I couldn't interact with an Oak sign. The error that is throws is: You are not permitted to use/interact with <item name>. Thanks for your help!

**Comment by Tobi406** [comment]
LuckPerms itself doesn't restricts anything. You can use the [Verbose feature](https://github.com/lucko/LuckPerms/wiki/Verbose) to see what permissions are being checked, and so what permissions you have to give yourself.

**Comment by Antonios-P** [comment]
Thanks. I will try that now

**Comment by Andre601** [comment]
The issue you encounter is most likely with WorldGuard.
WorldGuard does to my knowledge not use permission, with the exception of bypassing flags.
You have to set the flags of the region to allow the actions you want.

But this is for sure not an LP related issue.

**Comment by Antonios-P** [comment]
*Slaps self*. Sorry for wasting your time. I forgot to allow essentials.warp.* and essentials.build.*
