### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by GameModeOnX** [lucko/LuckPerms#1935]
LuckPerms always gives error when server close
https://i.ibb.co/DY3SQMX/image.png

**Comment by Andre601** [comment]
Did you try to delete the lib folder and let LP redownload it?

**Comment by GameModeOnX** [comment]
Still it giving same error

**Comment by Swordee** [comment]
I am getting the same issue. It doesn't happen every time, but the majority of the time. I just end up having to terminate the server.

**Comment by lucko** [comment]
Thanks for reporting, this should be fixed in the above commit.
