### ISSUE TITLE
Tab completion shows minecraft:luckperms:lp

### ISSUE THREAD

**Issue by ryantheleach** [lucko/LuckPerms#1939]
pressing /minecraft: and tab, shows luckperms permissions have been namespaced under minecraft.

![image](https://user-images.githubusercontent.com/141554/72674553-18132700-3ac8-11ea-8599-7497b61d589e.png)

Git-Spigot-037559e-752cf95
LuckPerms v5.0.39 

![image](https://user-images.githubusercontent.com/141554/72674618-b7381e80-3ac8-11ea-8102-0f8523bb8f1b.png)

**Comment by Andre601** [comment]
Side-effect of LP using brigardier (library from Mojang used for command suggestions in 1.13)

**Comment by lucko** [comment]
There was a reason for doing this, I can't exactly remember what it was though...

Might no longer be necessary, I think it was to do with working around a CraftBukkit quirk.
