### ISSUE TITLE
Plugin not responding

### ISSUE THREAD

**Issue by invaded** [lucko/LuckPerms#1940]
I have a custom spigot which generates the config files at /config/ instead of /plugins/ so basically my entire configs for server etc is on my /config/(plugin-name) instead of /plugins/(plugin-name). 

Luckperms commands doesn't work at all since I have done that, may I get some fixes? (Using latest version) thanks!

**Comment by Andre601** [comment]
"Custom".
That is an actual setting in spigot to change the name of the plugins folder.
And I don't think LP breaks because of that.
What plugins are you even using?

**Comment by BrainStone** [comment]
Also error messages please

**Comment by invaded** [comment]
> "Custom".
> That is an actual setting in spigot to change the name of the plugins folder.
> And I don't think LP breaks because of that.
> What plugins are you even using?

"Custom, This is an actual setting in spigot to change the of the plugins folder" To clarify that my spigot has a lot of optimizations, potion modifier, new commands etc. To test out if there was any plugins breaking it I decided to just run WorldEdit, Vault and LuckPerms. Still doesn't work.

https://hasteb.in/ajigihim.md - error. 

[11:41:46 INFO]: Plugins (3): LuckPerms, WorldEdit, Vault.

**Comment by invaded** [comment]
But anyways who cares about what my spigot has, I just need this fixed if possible.

**Comment by BrainStone** [comment]
Can you delete the `contexts.json` file?

**Comment by invaded** [comment]
§7§l[§b§lL§3§lP§7§l] §cA database error occurred whilst loading permissions data. Please try again later. If you are a server admin, please check the console for any errors.

https://hasteb.in/iqivovaj.md

**Comment by BrainStone** [comment]
There must be an earlier error. Most likely during startup

**Comment by invaded** [comment]
Yeah you're right, my fault.

Error: https://hasteb.in/qiyocopa.swift

**Comment by BrainStone** [comment]
You need to use the LP legacy version from here: https://ci.lucko.me/view/LuckPerms/job/LuckPerms/

**Comment by invaded** [comment]
I am using LuckPerms legacy version. I did every single type of research

**Comment by BrainStone** [comment]
Are you using a Forge/Spigot fusion, like Kauldron?

**Comment by invaded** [comment]
"LuckPerms-Bukkit-Legacy-5.0.63.jar".

**Comment by BrainStone** [comment]
As the server platform/jar. Not the LP plugin jar.

**Comment by invaded** [comment]
Send me discord please. I did my research and still couldn't find it and could you clarify what you meant with your question above?

**Comment by Andre601** [comment]
He clearly asked you, if you run a modded server with plugins (a mixture of spigot and forge if you will)

One type would be Kauldron.
Also the Discord is linked on the README.md or on the Wiki.

**Comment by invaded** [comment]
Oh, no. 1.7.10 spigot forked. And thanks

**Comment by BrainStone** [comment]
https://discord.gg/luckperms
