### ISSUE TITLE
getGroup (API?)

### ISSUE THREAD

**Issue by xJust1n** [lucko/LuckPerms#1942]
English
---
Hello, I would like to have my rank read out for my scoreboard (sidebar), but I cannot find any method for this. Do they even exist?

[https://prnt.sc/qpyv4l](https://prnt.sc/qpyv4l)

------------------------------------

German:
---
Hallo, ich möchte für mein Scoreboard (sidebar) meinen Rang auslesen lassen, jedoch finde ich dafür keinerlei Methode. Gibt es diese überhaupt?

**Comment by Jaimss** [comment]
Are you looking for placeholders? If you use something like featherboard, you can use the placeholders [here](https://github.com/lucko/LuckPerms/wiki/Placeholders).
That is what I use at least.

For the group, I think you would need to use `%luckperms_primary_group_name%`.

**Comment by xJust1n** [comment]
Hey, no, I would like to program this into eclipse.

**Comment by Tobi406** [comment]
Your rank or your prefix? Check out the wiki there should be an example of how to do this. <https://github.com/lucko/LuckPerms/wiki/Developer-API:-Usage#retrieving-prefixessuffixes>

You're better of reading the whole page actually, there are a lot of other things needed to get the prefix in the end. Everything should be explained there.

**Comment by xJust1n** [comment]
I want the rank on the scoreboard to speak:

Your rank
-> Owner
(at the owner)
-> Player
(at the player)
-> Guest
(at the guest)

So I want to have a query there that queries the rank of the player
