### ISSUE TITLE
luckperms-hikari - Failed to validate connection 

### ISSUE THREAD

**Issue by vip878269086** [lucko/LuckPerms#1946]
22.01 14:54:14 [Server] INFO Running LuckPerms v5.0.63 by Luck.
22.01 14:54:14 [Server] INFO -  Platform: Bukkit
22.01 14:54:14 [Server] INFO -  Server Brand: Paper
22.01 14:54:14 [Server] INFO -  Server Version:
22.01 14:54:14 [Server] INFO -  git-Paper-240 (MC: 1.14.4) - 1.14.4-R0.1-SNAPSHOT
22.01 14:54:14 [Server] INFO -  Storage:
22.01 14:54:14 [Server] INFO -     Type: MySQL
22.01 14:54:14 [Server] INFO -     Ping: 39ms
22.01 14:54:14 [Server] INFO -     Connected: true
22.01 14:54:14 [Server] INFO [LP] -  Extensions:
22.01 14:54:14 [Server] INFO -     me.lucko.luckperms.extension.legacyapi.LegacyApiExtension
22.01 14:54:14 [Server] INFO -  Messaging: Sql
22.01 14:54:14 [Server] INFO -  Instance:
22.01 14:54:14 [Server] INFO -     Static contexts: server=land
22.01 14:54:14 [Server] INFO -     Online Players: 1 (1 unique)
22.01 14:54:14 [Server] INFO -     Uptime: 14m 26s
22.01 14:54:14 [Server] INFO -     Local Data: 1 users, 6 groups, 0 tracks

22.01 14:51:35 [Server] WARN WARN fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase - AuthMeMYSQLPool - Failed to validate connection com.mysql.jdbc.JDBC4Connection@34d9fd99 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
22.01 14:51:35 [Server] WARN WARN fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase - AuthMeMYSQLPool - Failed to validate connection com.mysql.jdbc.JDBC4Connection@842d901 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
22.01 14:51:35 [Server] WARN WARN fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase - AuthMeMYSQLPool - Failed to validate connection com.mysql.jdbc.JDBC4Connection@75b51aac (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
22.01 14:51:35 [Server] WARN WARN fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase - AuthMeMYSQLPool - Failed to validate connection com.mysql.jdbc.JDBC4Connection@1e02d10b (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
22.01 14:51:35 [Server] WARN WARN fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase - AuthMeMYSQLPool - Failed to validate connection com.mysql.jdbc.JDBC4Connection@7b58950e (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
22.01 14:51:35 [Server] WARN WARN fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase - AuthMeMYSQLPool - Failed to validate connection com.mysql.jdbc.JDBC4Connection@26e580b3 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.

**Comment by Turbotailz** [comment]
https://github.com/lucko/LuckPerms/wiki/Storage-system-errors

**Comment by Wastinqs** [comment]
Check that your MySQL max connections limit is not being exceeded. By default, LuckPerms will use 10 connections per server. If you have lots of plugins connecting to the same server, you will need to increase this limit.

What would you recommend for a server with 80+ plugins on paper 1.17.1 java17?

Would 20 connections be enough?

**Comment by Wastinqs** [comment]
@lucko 

Check that your MySQL max connections limit is not being exceeded. By default, LuckPerms will use 10 connections per server. If you have lots of plugins connecting to the same server, you will need to increase this limit.

What would you recommend for a server with 80+ plugins on paper 1.17.1 java17?

Would 20 connections be enough?
