### ISSUE TITLE
prefix stacking exemption

### ISSUE THREAD

**Issue by HHServers** [lucko/LuckPerms#1947]
Hey, I'm using "prefix stacking" but is there a way to have certain users only display one prefix and ignore the rules set in the config? EG. a staff member only having [STAFF] tag instead of [Prison] [Novice] [STAFF]

If not, could this be considered a suggestion? thanks!

**Comment by Andre601** [comment]
I think you could deny the other prefixes for that rank...

Also, you should ask this in our [Discord](https://discord.gg/luckperms) as responses there are generally faster.

**Comment by Turbotailz** [comment]
> Also, you should ask this in our Discord as responses there are generally faster.

They did, but I had no idea if it was possible, so I told them to open the issue.

**Comment by lucko** [comment]
This could probably best be done by just using the "highest" prefix stack option, and then setting appropriate weights for each prefix.
