### ISSUE TITLE
Communications Link Failure

### ISSUE THREAD

**Issue by Ra-Zim** [lucko/LuckPerms#195]
Hey, my server, for some reason, seems unable to connect to the MySQL database I have setup. I run Solder and my MC servers from one server and connect to my GoDaddy hosting for the MySQL. Solder is working fine and I've verified the information in the config, but it isn't connecting for some reason. I'm getting errors like this in the console:

luckperms - Failed to validate connection com.mysql.jdbc.JDBC4Connection@4ad86c9f (Communications link failure
Last packet sent to the server was 1 ms ago.)
pool-2-thread-24/WARN - com.zaxxer.hikari.pool.PoolBase 
luckperms - Failed to validate connection com.mysql.jdbc.JDBC4Connection@5f291da (Communications link failure
Last packet sent to the server was 1 ms ago.)

Attempting to run commands only shows a message of [LP] Running LuckPerms v2.17.46

**Comment by dukedase** [comment]
I am just some random person but - Is the password right?  Does the database exist?  Is it the right username?  Share a picture of that area of the config.

**Comment by lucko** [comment]
It can't communicate with the remote MYsQL server. Not really much I can do to help you, it's not a LP issue.
