### ISSUE TITLE
Custom Promotions / Demotions (Tracks)

### ISSUE THREAD

**Issue by Jaimss** [lucko/LuckPerms#1950]
Allow users to append a group at the end of the /lp user promote command:
`/lp user {name} promote {track} {final-group}`

If the track is laid out like: `default->vip->donor->staff` and I do `/lp user {name} promote track1 donor`.

If the user was in the group default, it would be cool if they moved through VIP and on to donor in one command.

**Comment by Andre601** [comment]
[parentSet]: https://github.com/lucko/LuckPerms/wiki/Command-Usage:-Parent#lp-usergroup-usergroup-parent-set-group-context
[parentAdd]: https://github.com/lucko/LuckPerms/wiki/Command-Usage:-Parent#lp-usergroup-usergroup-parent-add-group-context

[`/lp user <user> parent set <group>`][parentSet] and [`/lp user <user> parent add <group>`][parentAdd] exist for that.
The promotion-command is for promoting a user across a track. Everything else can/should be handled by the above commands.

**Comment by BrainStone** [comment]
You can already do that: https://github.com/lucko/LuckPerms/wiki/Command-Usage:-Parent#lp-usergroup-usergroup-parent-settrack-track-group-context

**Comment by Jaimss** [comment]
Thank you Brian that should work for what I need 👍
