### ISSUE TITLE
Luckperms editor not working

### ISSUE THREAD

**Issue by V3x1Dev** [lucko/LuckPerms#1951]
When I try to create an editor page this error comes up and the link doesn't get made:
https://pastebin.com/wzVQdaZi

**Comment by Turbotailz** [comment]
Strange. Haven't seen this one before. Which version of LuckPerms are you using?

**Comment by V3x1Dev** [comment]
5.0.23

**Comment by V3x1Dev** [comment]
bukkit

**Comment by V3x1Dev** [comment]
It is only on that server my other backend servers are able to generate a link

**Comment by Turbotailz** [comment]
Please upgrade to the latest version (https://luckperms.net) and try it again.

**Comment by V3x1Dev** [comment]
Ok I will get back to you on that

**Comment by V3x1Dev** [comment]
I have added the latest version and the link still doesn't generate
https://pastebin.com/Nk5XhPbX

**Comment by Turbotailz** [comment]
Thanks for that. This is probably something @lucko needs to fix.

**Comment by V3x1Dev** [comment]
Ok. It's ok on other servers so it isn't that big a problem just though I would bring it up

**Comment by Turbotailz** [comment]
Just curious - are you able to generate an export with `/lp export` ?

**Comment by V3x1Dev** [comment]
Yes

**Comment by lucko** [comment]
Should be fixed in latest.
