### ISSUE TITLE
Help Permission bungeecord

### ISSUE THREAD

**Issue by AurelienGamings** [lucko/LuckPerms#1952]
Hello, I followed the tutorials my I don't understand I have a bungeecord I would like to separate the creative server and entirely survive

"server: creative"
"include-global: false

**Comment by Andre601** [comment]
[bungee]: https://github.com/lucko/LuckPerms/wiki/Network-Installation
[context]: https://github.com/lucko/LuckPerms/wiki/Context

When you followed the [Installation guide for BungeeCord][bungee] should you have a remote database setup and running.
In addition, should the version of LuckPerms for Spigot, Sponge, ... be on every backend server to handle their respective permissions.

What you can do now is setting permissions [with contex][context] (i.e. setting `essentials.fly` for the creative server only using the `server=creative` context)

For more help would we require more information like the server version(s) you use and the server type (Spigot, Sponge, ...)

**Comment by AurelienGamings** [comment]
I succeeded in starting all over again thank you for your response

**Comment by Andre601** [comment]
If that is the case, feel free to close this issue then.
