### ISSUE TITLE
Another luckperms + worldedit problem...

### ISSUE THREAD

**Issue by TheUltraXGamer** [lucko/LuckPerms#1963]
Despite multiple comments about this, none of the solutions worked on my server...

Mods installed:

Pixelmon
PixelExtras
Worldedit

---------------

I honestly don't know where the Worldedit config is so that could be the problem...  Worldedit shows up in my lp tree, but when I try to do //wand, I end up with the message, "You are not permitted to do that, are you in the right mode," which I don't understand at all... So I've been trying to figure it out by searching it up numerous times, but no success. And if anyone could help me, I will be really grateful...

**Comment by TheUltraXGamer** [comment]
![image](https://user-images.githubusercontent.com/60457722/73419089-fc363d80-4371-11ea-92cd-7ca1c0879ff9.png)

**Comment by Andre601** [comment]
> Are you in the right mode?

It probably asks if you're in creative as WE isn't really a survival mod.

**Comment by TheUltraXGamer** [comment]
My server is automatically set to Survival... so yes, that is the problem. But I don't how how to set it to creative. (I am new with servers)

**Comment by TheUltraXGamer** [comment]
Obviously, I can do /gamemode 1, but still, in creative, I can't do the command, so I am guessing the gamemode when the server was created is the problem here.

**Comment by BrainStone** [comment]
The game mode doesn’t matter. 
It’s referring to the mode in its own config. 

In any case nothing to do with LP. 
Reach out to WE support.

**Comment by TheUltraXGamer** [comment]
Ok then, I guess we can leave it here?
