### ISSUE TITLE
LuckPerms showing 2 of the same prefix

### ISSUE THREAD

**Issue by lukesfridge** [lucko/LuckPerms#1967]
I have LuckPerms Bungee on the bungee proxy and Standard LuckPerms on the Spigot Hub world.
I set the group Admin to have the permission "prefix.10.&l&8[&eAdmin&8]&r" and now it's showing the prefix twice! 
![image](https://user-images.githubusercontent.com/51542923/73590871-b39c9280-44df-11ea-81e8-36fc0cfc47eb.png)

**Comment by Andre601** [comment]
This is not LPs fault.
It is most likely caused by whatever Chat plugin you're using.

**Comment by Turbotailz** [comment]
If you use essentials, make sure you aren't setting the chat format as `{prefix}{displayname}` as displayname will show prefix/nickname/suffix.
