### ISSUE TITLE
Prioritize negative nodes / option to weight nodes

### ISSUE THREAD

**Issue by TheProX0517** [lucko/LuckPerms#1968]
Negative nodes should be prioritized or the option to weight nodes. Let's say I have '*' permission in group Owner. For some reason, I would like to make a node false. In my case, I go for essentials.build . It does not work.

**Comment by Andre601** [comment]
It should work as more detailed permissions (`essentilas.build`) override wildcards (`*` or `essentials.*`)
My idea is, that you either don't have Essentials AntiBuild (You shouldn't. That plugin is trash) or that the permission is wrong)

By default does LP calculate and manage the permission as follows:
- More detailed permissions override wildcard (as explained above)
- Permissions a group/user has override permissions they inherit.
- Permissions with world/server context override the same one without context (if the context matches)
- Permissions a user has override those they get from groups.

Adding a weight system seems quite out of scope for me and for permissions themself.
It could also break many different setups when it would be added.

You also have options to edit how inherited permissions are calculated/prioritized.
https://github.com/lucko/LuckPerms/wiki/Configuration#inheritance-traversal-algorithm

Another thing you can do is using LuckPerms' Verbose command to find out which permissions are actually checked. Perhaps the permission is different? Perhaps another plugin is managing the building stuff?
https://github.com/lucko/LuckPerms/wiki/Verbose

**Comment by lucko** [comment]
I don't see why negated nodes should be given priority over true nodes.

The system of "more specific" wildcards / permissions having priority makes sense in my opinion.
