### ISSUE TITLE
Server stop when i add the plugin

### ISSUE THREAD

**Issue by LewaIngame** [lucko/LuckPerms#1969]
Hello my serveur stop when i add the plugin with no error 1.13.2

**Comment by Andre601** [comment]
We require more information for us to help you.
Please provide this additional information:
- Server type (Spigot, Sponge, Paper, ...)
- LuckPerms version ("Latest" is not a version)
- The latest log of your server (upload it to https://hasteb.in please)
- Other plugins you use.

In addition also explain what exact steps you did, as "Server stops when I add the plugin" doesn't give us any clue what exactly you did.
