### ISSUE TITLE
At some point after a few hours this error comes from Luckperms.

### ISSUE THREAD

**Issue by ExticDev** [lucko/LuckPerms#1971]
If you then enter any command you get this error permanently and you can no longer write anything in chat.

https://hastebin.com/kiwikugeca.bash

**Comment by Andre601** [comment]
Please use https://hasteb.in for sharing errors.
GitHub issues are bsd for this

**Comment by ExticDev** [comment]
this is the error.

**Comment by ExticDev** [comment]
https://hastebin.com/kiwikugeca.bash

**Comment by lucko** [comment]
I can't reproduce this - do you have any other plugins which provide permissions or interact with providing permissions? Seems like something is removing the PermissibleBase from Player objects.
