### ISSUE TITLE
Crash log ..

### ISSUE THREAD

**Issue by SskyWorms** [lucko/LuckPerms#1973]
https://pastebin.com/z5jU80di
Hello, my server get crashed and i see this log.. please check this

**Comment by electronicboy** [comment]
> [22:28:51] [Paper Watchdog Thread/ERROR]: The server has not responded for 19 seconds! Creating thread dump

your server/JVM is basically so overloaded that the timer that's supposed to run every second took 9+ seconds to actually run, not an LP issue

**Comment by SskyWorms** [comment]
Ok thank you
