### ISSUE TITLE
Players Groups reverting on server relog

### ISSUE THREAD

**Issue by VOrlando520** [lucko/LuckPerms#1974]
Basically, ill update a users group and when they relog, it reverts the changes and puts their group back to the previous one.

LP Version: LuckPerms-Sponge-5.0.39
Sponge Version: spongeforge-1.12.2-2825-7.1.6.jar

**Comment by lucko** [comment]
Check your logs for errors. :)

**Comment by VOrlando520** [comment]
Seems updating to the latest version fixed this issue. Sorry for disturbing
