### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Sikatsu** [lucko/LuckPerms#1976]
Hey, small question.

I was planning to add DiscordSRV so when players link their minecraft account to Discord, they automatically get the rank 'Novice'. From there on, it should sync in-game ranks with Discord ranks.

If I were to implement this now, anyone who has a higher rank then 'Novice' would be set back to 'Novice' once they link their accounts.

Is there any better solution that would work out for me? For example;

1. Only Strangers that link their account get Novice.
2. Any users above 'Novice' don't get setback but just their in-game rank on Discord.

**Comment by Andre601** [comment]
This is mostly DiscordSRV's job.
Just make sure that the mc rank has the perm `discordsrv.sync.<role id>` set and that the bot has a role with manage roles perms that is above all others.

**Comment by Sikatsu** [comment]
But once they sync their minecraft account with discord, it runs the console command to give them the Novice rank. Even people who passed Novice.

I actually only want people with the ''Stranger'' rank to get promoted to Novice.

**Comment by Andre601** [comment]
> I actually only want people with the ''Stranger'' rank to get promoted to Novice.

Then set up permissions accordingly.
And we can't help you here as this isn't at all related to LP and relies on DiscordSRV, so you're better of asking on their Discord for assistance.

**Comment by Turbotailz** [comment]
You need to set the permission to False in the higher up group.

**Comment by Sikatsu** [comment]
Thanks for that information, i'll play around with it!
