### ISSUE TITLE
Problem with contexts of users

### ISSUE THREAD

**Issue by GoldEve3** [lucko/LuckPerms#1979]

**Comment by Andre601** [comment]
How about actually providing info?

**Comment by GoldEve3** [comment]
I just clicked by accident sorry, i dont know how to delete it. So i gonna write here. I have a problem a plugin called grief defender in the last update they decided to transfer all their player info to contextual data in luck perms, the migrator worked perfectly but my server is a rankup server and when someon rankups and after that the player info of grief defender update the player returns to the previous parent. I talked to the creator of grief defender and told me that grief defender doesnt change anything about parents, i tried in a empty server and I couldnt replicate de bug. Do you know if there is a bug with contextual data of users that make this happen?

**Comment by PulzHF** [comment]
Possibly related to #1977

**Comment by PulzHF** [comment]
After discussing this with a few people on the GriefDefender discord, user WhatsTheBadNews
#1060 believes that downgrading to [5.0.67 ](https://ci.lucko.me/view/LuckPerms/job/LuckPerms/987/) resolves the issue.

**Comment by lucko** [comment]
Not enough info here for me to be able to help. But no, I doubt there's any underlying issue/bug here.
