### ISSUE TITLE
Silence some notifications

### ISSUE THREAD

**Issue by Sikatsu** [lucko/LuckPerms#1980]
I'm making a badge selector using BossShopPro and LuckPerms.
I do want notifications/logging to be enabled for other purposes, but I don't want to see when a user switches his/her badge.

Could it be possible to add a -s argument to commands so that it doesn't show the logs for certain commands?

![image](https://user-images.githubusercontent.com/5664135/74056112-a4d34580-49e1-11ea-9d5e-556357226976.png)

**Comment by BrainStone** [comment]
Only admins can see those logs. And you can turn them off for yourself too.

**Comment by Sikatsu** [comment]
I understand that, but if I do want the logs enabled for other purposes. I basically have 2 options;

1) Ignore those badge switch logs
2) Disable all logs/notifications

**Comment by arenmarsden** [comment]
I believe a feature to silence specific tracks would heavily benefit people who have larger servers, and/or servers that have features like this.

**Comment by Sikatsu** [comment]
@lucko I updated to the latest build and added those sections, but I can still see the notifactions.

**Comment by Sikatsu** [comment]
![image](https://user-images.githubusercontent.com/5664135/85399766-9f713480-b557-11ea-9c52-20cfe35f4dbf.png)

**Comment by lucko** [comment]
It matches the actual log description - could you send an example of one of the notifications you're getting?

**Comment by lucko** [comment]
In your example above, to filter those messages you'd want to use something like `parent settrack badges .*` - it's a regex pattern so the `.*` at the end is a wildcard to match anything. :)

**Comment by Sikatsu** [comment]
Thanks for such a fast response! I haven't tried it for badges yet, I will do that soon!

It looks like this:

![image](https://user-images.githubusercontent.com/5664135/85402811-9afb4a80-b55c-11ea-88b4-15b74bc83301.png)

Also another question, do I just have to do it on the bungee config, or also on all backend-servers their configs?

**Comment by lucko** [comment]
Ok so just put the bit in white as an entry in the config file :)

You need to do it for all servers
