### ISSUE TITLE
User Data Expiration Suggestion

### ISSUE THREAD

**Issue by JavyMC123** [lucko/LuckPerms#1983]
Hello I'm using the plugin in my network and all is fine. My suggestion is if you can add an option for user data removing if the player don't join the network in like 3 months or whatever time I want? With this, I clear my database of useless data.

Sorry for my english...

**Comment by Andre601** [comment]
I don't think this is a useful option as it is outside of LPs main purpose imo.

**Comment by lucko** [comment]
Sorry, not something I plan to add.
