### ISSUE TITLE
Change addtemp

### ISSUE THREAD

**Issue by QuiquePineyro** [lucko/LuckPerms#1985]
Hello, I have a problem, I have the plugin EzRankPro, and I have multiple ranks, I want to accumulate the rank between the normal rankup rank and Vip rank this is my problem: (for example) I'm rank B and I want to upgrade to rank C, so I have to use /rankup, but, if I use (if a player buys the rank vip) /lp user (user) parent set vip this remove the rank B and I cant upgrate to C, but if I use /lp user (user) parent add vip this accumulate the rank and it works well.

This is my main problem, I want to give temporal group and when I use /lp user (user) parent addtemp vip 5d, this command doesn't accumulate and remove my rank B until the time of the rank ends.

I would like if could you change the option "addtemp" to be accumulated.

**Comment by Andre601** [comment]
To my knowledge does addtemp just add it, as the name implies.
The issue is most likely based on how the weights of your groups are set.

**Comment by BrainStone** [comment]
This is incorrect.  
You can have ``addtemp`` accumulate the time. See https://github.com/lucko/LuckPerms/wiki/Command-Usage:-Parent#lp-usergroup-usergroup-parent-addtemp-group-duration-temporary-modifier-context

**Comment by QuiquePineyro** [comment]
Thanks, I'm new using this plugin, I defined the weights of all my groups and now works well :)

**Comment by HunterzTheBoz** [comment]
Hello, how does this function, does it only lower the rank or prohibit players from joining again after the time given is up

**Comment by HunterzTheBoz** [comment]
Hope someone can help
