### ISSUE TITLE
Purge Old Player Data

### ISSUE THREAD

**Issue by JavyMC123** [lucko/LuckPerms#1986]
There is a way of delete old player data? /lp purge PLAYER? Or auto delete players ranks, permissions that dont join the server in X time?

**Comment by lucko** [comment]
LuckPerms doesn't track the last join time of players, so implementing this isn't possible.

(it's also not something I'd like to store - seems a bit out of scope for a permission plugin)

Thanks for the suggestion, but sorry, this isn't something I plan to add.
