### ISSUE TITLE
[LP] A database error occurred whilst loading permissions data. Please try again later.

### ISSUE THREAD

**Issue by GopnikJr** [lucko/LuckPerms#1987]
Anytime anyone tries to log on, I get this:
https://pastebin.com/PXzQLsyz

I have tried restarting the server with no luck of it fixing.

**Comment by Feniksovich** [comment]
I'm sure the problem isn't in LuckPerms. Read this article related to this error: https://github.com/lucko/LuckPerms/wiki/Storage-system-errors#luckperms-cannot-connect-to-my-mysql-server

**Comment by GopnikJr** [comment]
Yeah, you were right.  I had to recreate the MySQL database because I guess something went wrong?  Would you know of any way to grab the old database information without having to redo all perms?

**Comment by Feniksovich** [comment]
> Yeah, you were right. I had to recreate the MySQL database because I guess something went wrong? Would you know of any way to grab the old database information without having to redo all perms?

You can export tables of LuckPerms with phpMyAdmin function called "Export":
![image](https://user-images.githubusercontent.com/33875970/74409328-ae84ff00-4e60-11ea-8597-0af0da493fcc.png)

or if you don't have PMA, you can do it with command prompt through SSH:
https://stackoverflow.com/questions/3031412/how-to-export-a-mysql-database-using-command-prompt
