### ISSUE TITLE
Warnings while stopping server

### ISSUE THREAD

**Issue by Weasel-Beans** [lucko/LuckPerms#1989]
Console warnings: https://pastebin.com/LiFcbpYh

Timings v2: https://timings.aikar.co/?id=bc5b96d62a2d4ecc93d71c1c73f9b21d

Config: https://pastebin.com/VpYbjtnQ

**Comment by Andre601** [comment]
Timings are not are reliable way to find any cause of lags or similar. You would need to use a proper profiling plugin lik Lucko's Spark.

**Comment by Weasel-Beans** [comment]
It's more just to show the plugins and server version

**Comment by lucko** [comment]
Thanks for reporting, should be fixed in the above commit.
