### ISSUE TITLE
[1.7.10] Exception whilst reading file console spam 

### ISSUE THREAD

**Issue by Bubble0seven** [lucko/LuckPerms#199]
Keep getting the below spam in console not sure why only change i have made was update my special source as instructed in a previous ticket and this has been a problem since. 

Version: LuckPerms-Bukkit-Legacy-3.0.0
Thermos: 1.7.10.1614

Error: [Console Error](https://pste.me/#/luckperms/CEygSQDTLtgjsdaYqQlM2szgQD6SdS2c)

**Comment by lucko** [comment]
That's not the full error.

Either way, it seems to be an issue with that file?
