### ISSUE TITLE
Unable to gain luckperms permission

### ISSUE THREAD

**Issue by SemicolonStruggles** [lucko/LuckPerms#1992]
I've just set up my server and have configured all of my essentialsX permissions, however I am only able to do so when I am OP myself.

I would rather not have to be OP and use the `/lp user <your username> permission set luckperms.* true` command.

I have only executed the command above, other than that there are no groups or users that have any luckyperms permissions.

Am I missing something or have I stumbled across a bug?

I am using LuckPerms v5.0.72 on Spigot 1.15.2

**Comment by Andre601** [comment]
Did you literally used `<your username>`?

If yes: 🤦‍♂ 
You obviously have to replace `<your username>` with your own player name.

**Comment by SemicolonStruggles** [comment]
Obviously I did not. I used my own username.

**Comment by OmegaWeaponDev** [comment]
Where did you execute the said command? If you tried to do it in-game it would have failed and you would need to do it in the servers console. 

If said command does not work in the console, please show us screenshots of what it does say it console.

**Comment by SemicolonStruggles** [comment]
I am able to do it successfully both in-game (as long as I am OP) and from the console.

My user permissions show that I have full luckperms permissions but I still require OP to make any changes.

![image](https://user-images.githubusercontent.com/38405582/75109970-94011180-5628-11ea-8509-eb10a6b17c2a.png)

**Comment by Andre601** [comment]
Permission is **not** `luckyperms.*`

Where does it tell you that the perms start with luckyperms?

**Comment by SemicolonStruggles** [comment]
The wiki does: https://github.com/lucko/LuckPerms/wiki/Permissions

What is it supposed to be?

**Comment by SemicolonStruggles** [comment]
Well this is dumb... Made a typo. Thanks!
