### ISSUE TITLE
Server shut down when start up!

### ISSUE THREAD

**Issue by LJIT-WD** [lucko/LuckPerms#1993]
After installing LuckPerms, I restarted my server. The server crashed and shut down!

Then, I removed LuckPerms and restarted my server. Everything worked well!

My server is using Paper 1.12.2. I hope the issue can be solved and I can continue using LuckPerms as I like the features that LuckPerms provide!

**Comment by Andre601** [comment]
Without any logs or similar can we get 0 help.
Please upload them to https://hasteb.in

I'm quite sure it's not LP "crashing" the server.
And with restarting you mean stopping the server, adding/removing the plugin and starting again? Because adding/removing a plugin and then restarting will cause issues.

**Comment by LJIT-WD** [comment]
My console log:
https://hasteb.in/ivunufen.md

**Comment by LJIT-WD** [comment]
According to the guidelines:

> Download the LuckPerms-???-x.x.x.jar file that corresponds to your platform. You can find the latest versions here.
> Navigate to your mods/plugins directory. This is usually either /plugins/ or /mods/. Then place the LuckPerms jar in this directory.
> Fully stop & start your server, and allow the default configuration to be generated.

I followed it and restarted my server after uploading LuckPerms to the plugin folder.

**Comment by Andre601** [comment]
Like I thought is not LP "crashing" the server. It doesn't even crash at all.
The cause of your issue is AuthMe, as it disables itself when something isn't properly configured:
```
[09:47:17] [Server thread/WARN]: [AuthMe] Aborting initialization of AuthMe: [InjectorReflectionException]: Could not invoke method 'setup' for fr.xephi.authme.permission.PermissionsManager@11b55135
[09:47:17] [Server thread/WARN]: [AuthMe] THE SERVER IS GOING TO SHUT DOWN AS DEFINED IN THE CONFIGURATION!
```

Please read the logs/console feed next time, as it is clearly mentioned in CAPS what causes it and why.

**Comment by LJIT-WD** [comment]
But if I removed LuckPerms, server don't shut down!

**Comment by Andre601** [comment]
> But if I removed LuckPerms, server don't shut down!

> Please read the logs/console feed next time, as it is clearly mentioned in CAPS what causes it and why.

**Comment by LJIT-WD** [comment]
So you mean AuthMe have conflict with LuckPerms?

**Comment by Andre601** [comment]
AuthMe shuts down the server, because of a config-setting that tells it to do so.
It has to be something around Vault from my knowledge, so you have to change the settings. Please contact the AuthMe support as this is something on their end and not ours.

**Comment by LJIT-WD** [comment]
> It has to be something around Vault from my knowledge
However, it is about some sql problems. I fixed the issue and it works well. Thanks for your support!
