### ISSUE TITLE
[Suggestion] Bring the Auto-Op from bukkit to sponge

### ISSUE THREAD

**Issue by shinyafro** [lucko/LuckPerms#1995]
This actually has a few use cases with forge mods, which some will check for operator. Would be nice to have a node set to each rank to define it, most famously, FTBLib requires OP for claims bypass, as an example. Not sure how hard this would be , but since it is an already existing feature i figure it was worth a shot asking.

**Comment by Andre601** [comment]
This would have 0 usages as Sponge will automatically disable the OP system when a permission plugin is loaded.

**Comment by shinyafro** [comment]
Except such mods even with sponge and luckperms still require op.

**Comment by Andre601** [comment]
Then it's an issue with the mod and not LP.
Like mentioned will sponge disable the OP-system, which is out of LP's control.
An auto-op system for a server that disables OP is useless.

**Comment by shinyafro** [comment]
It's not an issue with the mod, since mods are not plugins and thus by design do not target the sponge framework but instead use forges native permission systems which generally is just ops and op levels.

Secondly, the feature already exists - it has a valid use case in sponge due to the aforementioned reasons. I'm just asking or suggesting it be enabled for sponge as well. If you have ever ran a modded server you would understand, mods don't give a damn about sponge. No one makes a mod and adds their debug commands in such a manner that they have sponge permission nodes. They simply have some form of capability, such as a creative debug item that enables the command, OP checks (most commonly). Sponge does have a way for you to make forge mods work with permissions, using the command name as a node i believe, however some things such as GUI based actions generally will require either op or a capability as sponge has no such ability to meddle with non-command based permission systems.

Even if it was an issue with the mods, it's not practical to solve it in such a manner. I mean, why should they depend on the sponge API and add permission nodes? Many mods don't even fire events early, which is why sponge went to the lengths it did to make a phase tracker.

**Comment by lucko** [comment]
There are methods in Forge to check permissions, so your argument there is flawed. :p

Sponge (and it's API) has no concept of OP - so it's not possible for a Sponge plugin to manipulate the operator status of players.
