### ISSUE TITLE
storage-method: MySQL working, MariaDB not working

### ISSUE THREAD

**Issue by Mintaka3a** [lucko/LuckPerms#1997]
Setting "storage-method" in config.yml to "MySQL" (along with address/database/username/password) works perfectly. The database tables get created and permissions are stored successfully.

However, if the value for "storage-method" is set to "MariaDB", which is actually what I am connecting to, it results in the following ClassNotFoundException error during startup:

[Server thread/INFO]: [LuckPerms] Loading configuration...
[Server thread/INFO]: [LuckPerms] Loading storage provider... [MARIADB]
[Server thread/WARN]: [Server thread] INFO me.lucko.luckperms.lib.hikari.HikariDataSource - luckperms-hikari - Starting...
[Server thread/ERROR]: [LuckPerms] Failed to init storage implementation
[Server thread/WARN]: java.lang.RuntimeException: java.lang.ClassNotFoundException: me.lucko.luckperms.lib.mariadb.MariaDbDataSource
[Server thread/WARN]: at me.lucko.luckperms.lib.hikari.util.UtilityElf.createInstance(UtilityElf.java:102)
[Server thread/WARN]: at me.lucko.luckperms.lib.hikari.pool.PoolBase.initializeDataSource(PoolBase.java
:316)
[Server thread/WARN]: at me.lucko.luckperms.lib.hikari.pool.PoolBase.<init>(PoolBase.java:109)
[Server thread/WARN]: at me.lucko.luckperms.lib.hikari.pool.HikariPool.<init>(HikariPool.java:108)
[Server thread/WARN]: at me.lucko.luckperms.lib.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
[Server thread/WARN]: at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.init(HikariConnectionFactory.java:91)

Obviously, the database tables don't then get created and LuckPerms fails to function correctly.

Same results for LuckPerms 5.0.39 and 5.0.72.

**Comment by lucko** [comment]
Try deleting the `plugins/LuckPerms/libs` folder and try again. Failing that, please could you send your full startup log.
