### ISSUE TITLE
Prefix issue

### ISSUE THREAD

**Issue by Kepall** [lucko/LuckPerms#1998]
I set up everything and tried it out, but the prefix isn't working at all. Instead of "&4[Owner]" it just adds the number 4 in front of my name
![Annotation 2020-02-14 215811](https://user-images.githubusercontent.com/46631908/74582857-ed58a900-4f75-11ea-843a-25b0edea1c17.png)

**Comment by electronicboy** [comment]
LP is showing that the prefix is there, that's more going to be on your chat plugin setup

**Comment by Kepall** [comment]
how do I change that?

**Comment by electronicboy** [comment]
not an LP issue, I'd suggest speaking to the people behind your chat plugin or asking for support on the discord

**Comment by Turbotailz** [comment]
> how do I change that?

Check your chat plugin configuration? Not much we can suggest without that information.

**Comment by Kepall** [comment]
its also not working without the chat plugin

**Comment by electronicboy** [comment]
LP doesn't modify chat, it just stores/provides that information for other plugins, it's up to you to install/configure a chat plugin to fetch that info from LP

**Comment by Turbotailz** [comment]
You *need* a chat plugin to display prefixes.

Do you also have Vault?

Maybe read the FAQ on prefixes: https://github.com/lucko/LuckPerms/wiki/FAQ

**Comment by Kepall** [comment]
what chat pl should I use?

**Comment by Turbotailz** [comment]
Whichever one fits your needs, and supports Vault (assuming you use a Bukkit based server).

**Comment by Kepall** [comment]
what did U use?

**Comment by Kepall** [comment]
I just need  a few examples of good plugins, supporting LP (spiggot)

**Comment by electronicboy** [comment]
There is some examples on the wiki of plugins to use, this issue tracker is for issues with LP, not for discussion/support, please use the discord for that.

**Comment by Kepall** [comment]
what wiki?

**Comment by Turbotailz** [comment]
The LuckPerms wiki. Scroll up, you'll find it (I also linked to it earlier).

You'll find the chat plugins on the prefix page.

**Comment by Kepall** [comment]
Ok - another thing, the permisiions arent working, i can switch between the groups and will still have every permission, could be because i'm an op?

**Comment by Turbotailz** [comment]
You should not use Op when debugging permissions. Please read the FAQ, almost everything you've asked is answered there.

**Comment by Kepall** [comment]
Thx for everything
