### ISSUE TITLE
Bulkupdate constraint parsing issue with matching quotations

### ISSUE THREAD

**Issue by Steev93** [lucko/LuckPerms#1999]
Speaking to luck.

Bulk update replacing permissions is broken.

http://prntscr.com/r2mf0b

**Comment by OmegaWeaponDev** [comment]
Which version are you using? Might be more helpful for luck to actually work it out. If he knows the details.

**Comment by Steev93** [comment]
> Which version are you using? Might be more helpful for luck to actually work it out. If he knows the details.

http://prntscr.com/r6v95u

**Comment by lucko** [comment]
I suspect this issue is related to character encoding - the regex used to match quote arguments needs to be improved.

**Comment by Steev93** [comment]
The issue is still pending have issued an email to the host to see if I can find further information maybe about there end.
