### ISSUE TITLE
[minor] Unsupported Operation

### ISSUE THREAD

**Issue by MakerTim** [lucko/LuckPerms#20]
When calling "MetaUtils.getPrefix(new GroupLink(group), null, null, true);"
I got a Unsupported Operation Exception

When i trace it down, it comes down to this,
You create here a new Empty list, but that list is immutable
Documentation:
> Returns an empty list (immutable).

https://github.com/lucko/LuckPerms/blob/2429831153d574da42bd9d290691294d57ec590c/common/src/main/java/me/lucko/luckperms/api/implementation/internal/PermissionHolderLink.java#L68

So when you do later the add method on it, it is unsupported :/

Stacktrace
http://pastebin.com/3vbjWNFs

**Comment by lucko** [comment]
Can you send the full stack trace please.

**Comment by MakerTim** [comment]
http://pastebin.com/5BJLbqFG
full stacktrace, dint see reason for it, but here ya go ;)

**Comment by lucko** [comment]
Yeah by bad, didn't see what you meant initially.
