### ISSUE TITLE
Question about Redis

### ISSUE THREAD

**Issue by andbut12** [lucko/LuckPerms#2000]
Does LuckPerms use Redis as a message broker or as a caching system too? I want to reduce connections to Database by using redis.

**Comment by BrainStone** [comment]
It just uses it as a messaging broker. Caching is done internally.  
The database connections are due to LP using a connection Pool to improve performance. Having multiple connections shouldn’t be an issue whatsoever.

**Comment by lucko** [comment]
It's used only as a message broker.

If you want to limit database connections - firstly make sure you *actually do* need to reduce them (are you trying to solve a specific problem?) - then try tweaking the connection pool settings.
