### ISSUE TITLE
[BUG] Trying to ./rankup on my prison server and LP display its info randomly and "loop"

### ISSUE THREAD

**Issue by maxlehot1234** [lucko/LuckPerms#2001]
Hi everyone, I just want to know how it is even possible to have this thing in a simple rankup command on my prison server:
https://gist.github.com/maxlehot1234/a53e6abf6914397b1580c49ece1fa4b5

Sometimes, Luckperms start to "lag" (maybe?) and display its help command.
Sometimes, LP say that I already have the group...

How I can fix this?

Weight, permissions, track and everything was correctly setup.
I can't post the setup here for differents reasons, but I can by PM (discord)

I have 2038 groups in total if this change anything.
I have PaperMC 1.15 build 105
I have Java 8
I have LuyckPerms 5.0.78

The .json file I import was perfect since LP was able to import it perfectly without any errors and display everything perfectly in the webeditor.

Thanks again

**Comment by BrainStone** [comment]
This is very clearly your rankup plugin creating a loop.  
Report that issue with them. It's most likely a misconfiguration on your part.

**Comment by maxlehot1234** [comment]
Ok but how you explain the fact that LP display all commands info?

**Comment by BrainStone** [comment]
Because the rankup plugin is executing LP commands.
