### ISSUE TITLE
Locking lower ranks to modify ranks on higher positions

### ISSUE THREAD

**Issue by Sninito9** [lucko/LuckPerms#2003]
Hi, I'm writing here because I searched online but didn't find anything to this relatively easy question:
I gave to my staff (of course) the luckyperm.group.* (which, as you know, gives the ability to set groups permissions) but since this staff is in a lower rank (I also put his group to a lower position in track than my owner rank) I want him to not being able to modify my perms... which he can.
How do I remove from him the permission to modify perms on a specific group (in this case the owner group)? Something like luckyperm.group.*.owner or something like that?

**Comment by Andre601** [comment]
Take a look at the wiki page about argument based command permissions.

**Comment by Sninito9** [comment]
Oh sorry I always say it wrong, anyway thanks
