### ISSUE TITLE
Can't connect using MySQL SSL

### ISSUE THREAD

**Issue by ConstructorLeo** [lucko/LuckPerms#2004]
Hi,

LuckPerms isn't connecting to MySQL SSL. We can manually connect to the MySQL database using the MySQL command, LiteBans which is also using MySQL SSL works just fine on the same machine, LuckPerms still has issues with a different machine, the LuckPerms and LiteBans databases are setup exactly the same.

Thanks.

**Comment by ConstructorLeo** [comment]
Here’s the error that showed up in console. https://pastebin.com/fM33Jbb4

**Comment by ConstructorLeo** [comment]
Here are some updates, been talking to the moderators.
https://prnt.sc/r5i6tj
https://prnt.sc/r5i7l0
https://prnt.sc/r5i7ms
https://prnt.sc/r5i7qs

eletroniccat also said our SSL is busted, but it's not as we are still able to connect to our MySQL databases over SSL from any of our machines, i.e LuckPerms is the only plugin having issues with MySQL.

please hurry the fuck up we're losing money BECAUSE IT'S 3 DAYS DOWN

**Comment by ConstructorLeo** [comment]
Here are some updates, been talking to the moderators.
https://prnt.sc/r5i6tj
https://prnt.sc/r5i7l0
https://prnt.sc/r5i7ms
https://prnt.sc/r5i7qs

eletroniccat also said our SSL is busted, but it's not as we are still able to connect to our MySQL databases over SSL from any of our machines, i.e LuckPerms is the only plugin having issues with MySQL.

**Comment by lucko** [comment]
> please hurry the fuck up we're losing money BECAUSE IT'S 3 DAYS DOWN

May I draw your attention to:

https://github.com/lucko/LuckPerms/blob/9f7d431d34867038c2abc252d876a9ca424b72a0/LICENSE.txt#L16-L22

Regarding your issue, this wiki page is most relevant.

https://github.com/lucko/LuckPerms/wiki/Storage-system-errors

LuckPerms delegates absolutely all connection handling with MySQL to HikariCP and the underlying JDBC driver.

Aside from possibly tweaking the Hikari configuration, see:

* [`HikariConnectionFactory`](https://github.com/lucko/LuckPerms/blob/master/common/src/main/java/me/lucko/luckperms/common/storage/implementation/sql/connection/hikari/HikariConnectionFactory.java)
* [`MySqlConnectionFactory`](https://github.com/lucko/LuckPerms/blob/master/common/src/main/java/me/lucko/luckperms/common/storage/implementation/sql/connection/hikari/MySqlConnectionFactory.java)

or upgrading the MySQL driver version used, there's absolutely nothing I can do to attempt to fix the problem.

**Comment by ConstructorLeo** [comment]
All fixed

**Comment by lucko** [comment]
Would you mind explaining what you did to fix, just incase anyone else has the same problem in the future? :)
