### ISSUE TITLE
Cannot get luckperms to allow me permissions bungee 

### ISSUE THREAD

**Issue by Nosneross** [lucko/LuckPerms#2010]
I have setup the servers as they should be and have done the commands necessary through console but it still hasint giving me any options I can force change my account to different groups from the  server console but i cant do it from my own rig even though i have all the permissions set as they would be its very confusing!  It allows me to create groups  but i cant add parents it keeps telling me i dont have permission!

**Comment by OmegaWeaponDev** [comment]
Make sure you have all server using luckperms and that they are using the correct versions of luckperms. Then make sure all servers are connected to the same database to allow for much easier syncing. If all is setup correctly then you should be able to add the groups/permissions normally and it should all work.
