### ISSUE TITLE
LuckPerms not letting me use /trigger

### ISSUE THREAD

**Issue by gamer4life1** [lucko/LuckPerms#2011]
Hello! I love this plugin. However, since I installed it, I cannot use /trigger for anything. When I use it, it says:
You cannot trigger this objective yet.

Any ideas?
Thanks.

**Comment by OmegaWeaponDev** [comment]
There is probably a permission behind the command. Have a look at using the verbose feature to determine if there are any required permissions you need to add. 

https://github.com/lucko/LuckPerms/wiki/Verbose

**Comment by gamer4life1** [comment]
I already have *.* and minecraft.commands.trigger

**Comment by Andre601** [comment]
I don't think /trigger is a minecraft command as I can't remember any command like that.
So you should double-check that you have the right permission (Use Verbose like Omega suggested) for the command.
Maybe LP is in conflict with another plugin? A common mistake people make is to not remove the old permission plugin, if they switch/migrate from it (f.e. from PEX)

**Comment by gamer4life1** [comment]
I removed PEX after migrating

**Comment by gamer4life1** [comment]
/trigger triggers a scoreboard objective. It's used in datapacks.

**Comment by gamer4life1** [comment]
https://minecraft.gamepedia.com/Commands/trigger

**Comment by Turbotailz** [comment]
Did you use verbose?

**Comment by gamer4life1** [comment]
Yup

**Comment by gamer4life1** [comment]
Everything is true

**Comment by gamer4life1** [comment]
[List of plugins](https://pastebin.com/NDCgZwZq)

**Comment by Turbotailz** [comment]
Does `/minecraft:trigger` work?

**Comment by gamer4life1** [comment]
Nope

**Comment by Turbotailz** [comment]
Same deal in verbose? Can you actually show us some output?

Please do `/lp verbose record`, type the command, `/lp verbose paste` then send the link here.

**Comment by BrainStone** [comment]
Keep in mind that the score needs to be allowed to be triggered beforehand. And that every time

**Comment by gamer4life1** [comment]
@Turbotailz Ok! Let me try

**Comment by gamer4life1** [comment]
[Here](https://luckperms.net/verbose/#6sHBU5ifMC)

**Comment by gamer4life1** [comment]
@BrainStone Yes, I enabled all the scoreboard objectives

**Comment by lucko** [comment]
Maybe you need to be opped?

**Comment by BrainStone** [comment]
The thing is the permission check succeeds. So I don't see anything on the LP side that's going wrong here.  
Sadly vanilla commands are handled very wonkily on Spigot. Maybe try reaching out to their support.

**Comment by lucko** [comment]
The permission check may be succeeding, but the code might be checking for op too.

**Comment by gamer4life1** [comment]
@lucko I have op

**Comment by gamer4life1** [comment]
@BrainStone thanks for the suggestion.

**Comment by lucko** [comment]
Spigot has a JIRA bug tracker available from their website under "Hub".

**Comment by Ghione1** [comment]
Any solution? i have the same problem with luckperms in paper 1.21.6-48
