### ISSUE TITLE
Square brackets showing before prefix.

### ISSUE THREAD

**Issue by lukesfridge** [lucko/LuckPerms#2012]
Looks like this:

![image](https://user-images.githubusercontent.com/51542923/75096060-57370b00-5593-11ea-8e0d-b99545887619.png)

Any ideas how to fix this?

**Comment by Andre601** [comment]
This is not caused by LP.

Check your chat plugins (if you use any) and maybe your World Management plugin, if you have multiple worlds.

**Comment by lukesfridge** [comment]
Thanks for the advice Andre!
