### ISSUE TITLE
Luckperms conflict on startup

### ISSUE THREAD

**Issue by Niko302** [lucko/LuckPerms#2015]
We get the following response on bungeecord startup when we try to use another plugin with luckperms:
`> 18:12:05 [SEVERE] [LuckPerms] Exception occurred whilst loading data for fc123b5f-c423-411f-9f10-9c616fb61083 - red_man234
> 18:12:05 [SEVERE] java.lang.NullPointerException
> 18:12:05 [SEVERE] at me.lucko.luckperms.common.plugin.util.AbstractConnectionListener.loadUser(AbstractConnectionListener.java:67)
> 18:12:05 [SEVERE] at me.lucko.luckperms.bungee.listeners.BungeeConnectionListener.lambda$onPlayerLogin$0(BungeeConnectionListener.java:90)
> 18:12:05 [SEVERE] at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
> 18:12:05 [SEVERE] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 18:12:05 [SEVERE] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 18:12:05 [SEVERE] at java.lang.Thread.run(Thread.java:748)
> 18:12:05 [SEVERE] Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@4983490b, id=69, owner=me.lucko.luckperms.bungee.LPBungeeBootstrap@441e351b, task=me.lucko.luckperms.bungee.listeners.BungeeConnectionListener$$Lambda$347/376602170@50339a7, delay=0, period=0, running=true) encountered an exception
java.lang.NullPointerException `

**Comment by Andre601** [comment]
1. What BungeeCord version (and type) are you running?
2. What is the "other plugin"?
3. Any other errors?
4. Is the BungeeCord in online or offline mode?

**Comment by Niko302** [comment]
1.#1486 (latest build 23 hours ago)
2. The other plugin is a custom written plugin my dev codded to link discord bot with the bungee network.
3. No
4. Online

**Comment by lucko** [comment]
Can you send the full startup log?
