### ISSUE TITLE
LuckPerms resets after server restart.

### ISSUE THREAD

**Issue by Froczi** [lucko/LuckPerms#2017]
Hey guys so I love luck perms and its features but every time I get finished setting up everything through the /lp editor (I've tried just in game set ups as well) It comes out great and the way I want it to look, work e.t.c. But every time I restart the bloody server it all gets reset!!! of course I'm using /lp applyedits yet when I restart the server it all gets reset. Its very stupid in my opinion. My storage method is mysql. It seems to work fine on both my lobby and kit pvp server through the sql, until I restart that is.

**Comment by lucko** [comment]
Any errors in your console? Can you send your full log so we can have a look?

Maybe your server provider is resetting the database on restart?
