### ISSUE TITLE
placeholders and sponge server

### ISSUE THREAD

**Issue by hunter688** [lucko/LuckPerms#202]
Does luckperms support placeholders on sponge server?
I would like use bungeeTablistPlus, but cannot get group placeholder to work.

https://www.spigotmc.org/resources/bungeetablistplus.313/updates

**Comment by Eufranio** [comment]
They're working here. Try updating to latest BTLP and BTLP-Sponge, and send the variable that you're using.

**Comment by hunter688** [comment]
I have latest (2.7.2)

**Comment by hunter688** [comment]
related issue on BTLP: https://github.com/CodeCrafter47/BungeeTabListPlus/issues/199

**Comment by lucko** [comment]
The BTLP author has replied on that ^^ issue with what the problem (probably) is.
