### ISSUE TITLE
Repetitive Crashes

### ISSUE THREAD

**Issue by Irititam** [lucko/LuckPerms#2021]
https://pastebin.com/HHT9Kw2T

Hi, I've been experiencing repetitive crashes for about 8 months (since I use LuckPerms). I run 5 servers (versions 1.12.2, 1.13.2 and 1.15.2) on a BungeeCord and I use the last version of LuckPerms for Spigot on each of them.

At the beginning the issue occurred like once a month so I used to ignore it but since the last two months it's been terribly annoying because it occurs almost every day and is getting worse as the time passes. Most of the time it happens in middle of the night when nobody's online and all the servers crash at the same time.

I thought of a problem of resources from the server but I cannot see any excessive use of ram or cpu (plus the resources I have are more than enough to easily run the server, mostly when nobody's online), so I was wondering if the problem wasn't caused directly by LuckPerms, as it is mentioned a lot each time in the crash report.

Any ideas ? Thanks !

**Comment by electronicboy** [comment]
Nothing to do with LP, lp just has threads running in a pool to allow processing stuff, your server quite simply just took too long to tick, you'll wanna use a sampler or something to view what is going on, Paper does have better logging for recentish versions, there was also some plugin that adding a better watchdog for spigot/bukkit, no idea what it was

**Comment by Andre601** [comment]
You probably mean [Spark](https://github.com/lucko/spark) which can be used to profile your server and see what causes lag.

**Comment by Irititam** [comment]
Thank you, I will test that.
