### ISSUE TITLE
I cant find the Permission to use this command 

### ISSUE THREAD

**Issue by Zenth815** [lucko/LuckPerms#2022]
I want to use the /scoreboad command and when ever i do lucyperms said i dont have permissions to do so. So when i go into lucky perms to find the line to give me that permission i cant find it anywhere. I need to use this command for the mod Ancient Warfare 2.

**Comment by Zenth815** [comment]
Oh also i use Nucleus for my normal server command

**Comment by Andre601** [comment]
> I want to use the /scoreboad command and when ever i do lucyperms said i dont have permissions to do so. So when i go into lucky perms to find the line to give me that permission i cant find it anywhere. I need to use this command for the mod Ancient Warfare 2.

What now? `lucyperms` or `lucky perms`? (It's **LuckPerms** btw)

In addition does LuckPerms not handle `/scoreboard` so the error message about missing permissions is for sure not from LuckPerms itself.

To find out what permissions are required, use Verbose:
https://github.com/lucko/LuckPerms/wiki/Verbose

**Comment by Zenth815** [comment]
That Worked thank you! also i cant spell XD
