### ISSUE TITLE
New Players Not Getting Command Access

### ISSUE THREAD

**Issue by aRelevant** [lucko/LuckPerms#2023]
Recently on my server, a friend joined my game, but they did not have access to any commands. When I looked at their group, it says that they are in group.default and all the commands on it are working. However, my friend can't use those commands so I'm hoping this issue can be fixed. Maybe I'm just doing something wrong

Thanks

**Comment by lucko** [comment]
Use the verbose command to debug.

https://github.com/lucko/LuckPerms/wiki/Verbose
