### ISSUE TITLE
[LuckPerms] Failed to init storage implementation

### ISSUE THREAD

**Issue by syuakame** [lucko/LuckPerms#2024]
I don't understand why i have this error .. ''[LuckPerms] Failed to init storage implementation'' on MySQL
i have setup
- Db
- User who have acces to this db and grant him the perms
- Setup the config file with the user login info

i don't know what im doing wrong ..

**Comment by Turbotailz** [comment]
Once again you have left out the most important part - the console errors. Please send them here.

**Comment by syuakame** [comment]
ya sorry im tired 
https://hastebin.com/qewedudivi.md

**Comment by lucko** [comment]
> java.lang.NullPointerException: address

Check your config formatting, make sure you've provided an address for the database.

**Comment by syuakame** [comment]
you can take a look i think i have setup all correctly
https://hastebin.com/ebayatosiy.shell

**Comment by electronicboy** [comment]
try using just localhost instead of `localhost:3306`, or, throw it in `"quotes"`

**Comment by syuakame** [comment]
i have tried to set it just to localhost but same error, nothing change

**Comment by syuakame** [comment]
someone ??? i have this problem for 2 days i ve tried everything the people say me to do but nothing work .....

**Comment by syuakame** [comment]
i want to die i solve my problem by reinstalling the plugin i was on the point to punch someone in the face
