### ISSUE TITLE
Permission issue

### ISSUE THREAD

**Issue by xdLulux** [lucko/LuckPerms#2025]
So some players are having perms like /invsee and else from plugins such as essentials and more and it had a lot of issues on my server and it is only happening with luckperms and when I switch to group manager or pex 0 issues please fix this ASAP

**Comment by Andre601** [comment]
You give us zero information.
How should we fix something without knowing what the issue is?
We don't know your setup, nor can we read your mind.

**Comment by lucko** [comment]
Try debugging the issue using the verbose command.

https://github.com/lucko/LuckPerms/wiki/Verbose
