### ISSUE TITLE
Timed Permissions

### ISSUE THREAD

**Issue by NikV2** [lucko/LuckPerms#2027]
**Greetings !

Currently if you give a player a timed permission (/lp user <user> permission settemp <perm> <true/false> <time>

The timer will still count even if the player leaves the server.

I feel like it would be really great if you gave the option in the config to disable/enable the Time Count if a player leaves the server. I'm sure it'd be helpful to a lot of people using settemp Permissions !

If you end up implementing that, Please make sure to Tag me (Spam me if needed) cause i really need such a feature!

Yours sincirely, Nik.**

**Comment by NikV2** [comment]
*bump*

**Comment by lucko** [comment]
Sorry, this is something that's out of scope for LuckPerms at the moment.

It could be quite easily added by another plugin though, hooking into either LP or Vault.
