### ISSUE TITLE
Constant "Timed Out" Velocity-1.1.0

### ISSUE THREAD

**Issue by STG-Allen** [lucko/LuckPerms#2028]
Velocity Version: 1.1.0-SNAPSHOT 
Luckperms Version: 5.0.79
Other plugins installed: Catalyst, Anvil (Both found on AnvilPowered GitHub)

Issue: Ever since updating to version 1.1.0 of velocity and updating luckperms there have been a few issues. Initially, there was an issue with 5.0 of velocity when setting permissions for a player or a group would kick up to 4 random players at once. After updating we were able to set permissions but the issue of random timeout's has been present since.

Additional Information: Messaging is done trough PluginMessage, and permissions are stored via MySQL

**Comment by lucko** [comment]
I don't see how this would be LuckPerms related. What makes you think that it is?

**Comment by STG-Allen** [comment]
My suspicions are based off of the issues that were present before i updated to 5.0.79.

**Comment by STG-Allen** [comment]
After further investigation, The timeout's were caused by my plugin. 

What was happening?

Each time a player was sending a message in chat, I was getting their prefix, suffix, name color, and chat color from LP. So each time it was hitting up LP about 4 times. 

Before : https://github.com/AnvilPowered/Catalyst/blob/4644a6b2f56588018c85256d2ef36b3afd8313de/velocity/src/main/java/org/anvilpowered/catalyst/velocity/utils/LuckPermsUtils.java

After : https://github.com/AnvilPowered/Catalyst/blob/master/velocity/src/main/java/org/anvilpowered/catalyst/velocity/utils/LuckPermsUtils.java

**Comment by BrainStone** [comment]
Weird. Those lookups shouldn't matter. As LP caches that data.

Only time that might become an issue is when you're spamming several thousand requests a second.

**Comment by STG-Allen** [comment]
It shouldn't be thousands a second, shown in this class is how many times I'm requesting the data

https://github.com/AnvilPowered/Catalyst/blob/4644a6b2f56588018c85256d2ef36b3afd8313de/velocity/src/main/java/org/anvilpowered/catalyst/velocity/listeners/ProxyChatListener.java#L108
