### ISSUE TITLE
Suggestion - List members

### ISSUE THREAD

**Issue by PiggyPiglet** [lucko/LuckPerms#203]
Add a command that allows users with a certain permission to view members of a certain group. Command would be something like /lp group builder members or /lp group builder list

**Comment by PiggyPiglet** [comment]
Also, maybe a command to list groups? This would be useful for staff like admins that don't have access to ftp to see the groups but they have access to the command to change a users group.

**Comment by lucko** [comment]
`/lp listgroups`?

**Comment by PiggyPiglet** [comment]
Yeah, Sorry. You replied just as I deleted my comment since I remembered the command.
