### ISSUE TITLE
"Whilst saving user data" etc.

### ISSUE THREAD

**Issue by Deevez** [lucko/LuckPerms#2030]
Upon first setting up my server LuckPerms was one of the first things I began setting up. I typed in the command to set all my permissions to true in the console. It came back with the error saying "Error whilst saving user data".

I tried a bunch of other things such as creating groups or tracks. Same error. It's always along the lines of "whilst saving".

I'm not too sure how better to explain that, I've ran it in Verbose mode and everything seems fine, LuckPerms is my only permissions plugin. I'm just not too sure as to why it won't let me do anything.
![Inked2020-02-27_21 29 37_LI](https://user-images.githubusercontent.com/26390968/75505139-70cbbe80-59a8-11ea-8576-a8823d744258.jpg)

**Comment by Andre601** [comment]
If there is an error **while saving data** then there must be some issues with whatever data storage you use.

Please check the console for stacktraces (this error usually has some) and provide more info like the LP version, server type and version, other plugins you use and the output of `/lp info`

**Comment by Deevez** [comment]
> If there is an error **while saving data** then there must be some issues with whatever data storage you use.
> 
> Please check the console for stacktraces (this error usually has some) and provide more info like the LP version, server type and version, other plugins you use and the output of `/lp info`

I'm not too sure what I'd be looking for with stacktraces. Could you explain that a little for me please?

Here's the all the plugins I'm running;
![Capture](https://user-images.githubusercontent.com/26390968/75580322-8dfa9e80-5a35-11ea-846e-dfbae2ea3ef4.PNG)


And here's what /lp info tells me;
![Inked2020-02-28_14 15 35_LI](https://user-images.githubusercontent.com/26390968/75580347-981c9d00-5a35-11ea-9ea3-0ed3d419a675.jpg)

**Comment by Andre601** [comment]
You have essentials twice in your plugin list, so better remove one.

And I personally suggest to not use file-based storage as it would increase storage space used and could get corrupted.
Staying with the default h2 storage is recommendet.

**Comment by Deevez** [comment]
> You have essentials twice in your plugin list, so better remove one.
> 
> And I personally suggest to not use file-based storage as it would increase storage space used and could get corrupted.
> Staying with the default h2 storage is recommendet.

This isn't my storage system, this is all through MCProHosting. So I'm not too sure how else to do all that storage wise on there.

**Comment by Andre601** [comment]
This is for sure not "through MCProHosting", if you refer to the storage-type LP currently uses (Which is set to YAML in your case.
You **can** switch the storage type following [this wiki page](https://github.com/lucko/LuckPerms/wiki/Switching-storage-types) and if MCP doesn't allow you to switch storage type of a plugin (Which wouldn't make sense), then switch the host.

**Comment by Deevez** [comment]
> This is for sure not "through MCProHosting", if you refer to the storage-type LP currently uses (Which is set to YAML in your case.
> You **can** switch the storage type following [this wiki page](https://github.com/lucko/LuckPerms/wiki/Switching-storage-types) and if MCP doesn't allow you to switch storage type of a plugin (Which wouldn't make sense), then switch the host.

I'm receiving an error "unexpected error occurred whilst writing to the file" when I try to export it

**Comment by Andre601** [comment]
There must be more to this error than just that.
As I mentioned earlier should you check the console for stacktraces... They should be pretty obvious to spot and if not: Google "Stacktraces Java" to see how one looks like. This is basic server-management 101

**Comment by Deevez** [comment]
> There must be more to this error than just that.
> As I mentioned earlier should you check the console for stacktraces... They should be pretty obvious to spot and if not: Google "Stacktraces Java" to see how one looks like. This is basic server-management 101

java.nio.file.NoSuchFileException: /opt/service/plugins/LuckPerms/yaml-storage/users/38703788-e609-426c-9344-f09c8435c09c.yml

This is what the stacktrace is saying. I searched around and found one article on it, and the fix was to update to the latest version, which I am using.

**Comment by Andre601** [comment]
Looks like LP can't find a file (Maybe was deleted?)
Try restarting the server and maybe remove the lib/libs folder in the LuckPerms folder to let it re-download any required libraries.

**Comment by Deevez** [comment]
> Looks like LP can't find a file (Maybe was deleted?)
> Try restarting the server and maybe remove the lib/libs folder in the LuckPerms folder to let it re-download any required libraries.

At this point everything seems to be working as it should. Somehow when restarting my server though it changed the world seed so I'm gonna have to backdate that. There were a few missing libraries.
