### ISSUE TITLE
Wiki: "Developer API: Usage" wrong method in example code

### ISSUE THREAD

**Issue by KaiKikuchi** [lucko/LuckPerms#2031]
[In this section](https://github.com/lucko/LuckPerms/wiki/Developer-API:-Usage#registering-contextcalculators) there is the following example code:

```java
public class CustomCalculator implements ContextCalculator<Player> {

    @Override  
    public void calculate(Player t, ContextConsumer contextConsumer) {
        contextConsumer.add("gamemode", t.getGameMode().name());
    }
    
    @Override
    public ContextSet estimatePotentialContexts() {
        ImmutableContextSet.Builder builder = ImmutableContextSet.builder();
        for (GameMode gameMode : GameMode.values()) {
            builder.add(KEY, gameMode.name().toLowerCase());
        }
        return builder.build();
    }
    
}
```

ContextConsumer does not have an "add" method, but "accept". [Link to ContextConsumer.java](https://github.com/lucko/LuckPerms/blob/master/api/src/main/java/net/luckperms/api/context/ContextConsumer.java)

I also suggest to change "KEY" to "gamemode" in order to have a working example.

**Comment by Andre601** [comment]
I [made a PR](https://github.com/LuckPerms/wiki/pull/43) to correct this.

You could do it next time as the wiki is mirrored [here](https://github.com/LuckPerms/wiki).

**Comment by KaiKikuchi** [comment]
Okay I will do that next time, thanks!

**Comment by lucko** [comment]
Thank you both :)
