### ISSUE TITLE
/lp user [user] parent add [group]

### ISSUE THREAD

**Issue by En0tS** [lucko/LuckPerms#2032]
I can't use _/lp user [user] parent add [group]_ (**command-no-permission** message) with * and **luckperms.*** permissions, all other commands like _permission set_ or _editor_ or _applyedits_ are ok. Tested with argument-based-permissions enabled/disabled.

Server: paperspigot-1.12.2 (b-1648), LuckPerms 5.0.83

**Comment by Andre601** [comment]
Can you show the actual response of the command?
And you can always use [Verbose](https://github.com/lucko/LuckPerms/wiki/Verbose) to debug stuff and see what may be checked.

**Comment by En0tS** [comment]
Response is _command-no-permission_ message.

**Comment by En0tS** [comment]
I can use any other command, but not this.

**Comment by Andre601** [comment]
> Response is _command-no-permission_ message.

This isn't a valid response at all as LP never returns this. So either another plugin is sending this (And blocks LP for whatever reason) or you messed something up.

Provide actual information, like screenshots and such.

**Comment by En0tS** [comment]
I mean this message from lang.yml
![image](https://user-images.githubusercontent.com/36606833/75566449-5b15d200-5a58-11ea-95ae-1bee218f3c71.png)

**Comment by En0tS** [comment]
I can use any other LuckPerms command, but not parent command.

**Comment by lucko** [comment]
Check with verbose - Andre linked the wiki page for it to you above.
