### ISSUE TITLE
No way to add new permissions in LuckPerms Web Editor

### ISSUE THREAD

**Issue by MrLaturi** [lucko/LuckPerms#2035]
So yesterday I started to make new ranks for my server. I had added every rank and prefix yesterday so I could begin adding permissions today, but now there's no way to add new permissions through the web editor; I can only edit existing ones.

**Comment by Turbotailz** [comment]
Can you explain in more detail, please? Maybe provide some screenshots?

**Comment by MrLaturi** [comment]
Yesterday there was (if I remember correctly, my memory is really bad) a field where you could write down a permission and then add it by pressing ENTER or by pressing a big button in the down right corner, but now there isn't any of this. And this happened all within 12 hours.
![luckperms problem](https://user-images.githubusercontent.com/61616142/75604242-55af9a80-5adf-11ea-96fb-c1c91fc71946.PNG)

**Comment by Turbotailz** [comment]
I did push a new change just a couple hours ago, but it shouldn't have affected that at all.

What browser are you using?

**Comment by Turbotailz** [comment]
Also please send your editor URL in case it is a more isolated issue.

**Comment by MrLaturi** [comment]
I am using Firefox version 73.0.1
Editor URL: https://editor.luckperms.net/FxAuL8ryi7

**Comment by Turbotailz** [comment]
That's odd, it is working fine for me with that browser version.

Can you hit `ctrl + shift + i`, go to the console tab and see if there are any errors?

**Comment by MrLaturi** [comment]
This is the only error
![luckperms problem2](https://user-images.githubusercontent.com/61616142/75604404-05d1d300-5ae1-11ea-97ba-f9844d305f55.PNG)

**Comment by Turbotailz** [comment]
Can you please hard refresh the page with `ctrl + shift + r`

**Comment by MrLaturi** [comment]
I hard refreshed it and same error happens once I go back to a group

**Comment by Turbotailz** [comment]
Can you try in another browser?

**Comment by MrLaturi** [comment]
I tried it in Microsoft Edge, but the same thing happens there

**Comment by Turbotailz** [comment]
Huh, interesting. Wonder what happened. It worked in every mainstream browser for me, even Safari 🤔

**Comment by MrLaturi** [comment]
Well that is very odd indeed

**Comment by Turbotailz** [comment]
I'm gonna guess it's a caching issue. We've just recently set LPWeb up on Netlify so there may be some teething issues to sort out for future deployments.

**Comment by MrLaturi** [comment]
Probably that yeah. Well I hope that the issue gets sorted out at some point so that this thing doesn't happen often. Good luck with future developing of this awesome and easy-to-use plugin.

-MrLaturi
