### ISSUE TITLE
Info/option nodes

### ISSUE THREAD

**Issue by pvvvo** [lucko/LuckPerms#2039]
How  I can use LP where get/setPlayerInfoString is used? I need it to Towny plugin.
I try it with `/lp user pvvvo meta set towny_default_modes local` but it doesn't work, (It should put me in towny local chat for default) I even talk to the developer of Towny and he said me this: 
> yes so you should ask Luck how you can use LP where get/setPlayerInfoString is used.

**Comment by lucko** [comment]
You're correct. The `meta set` command is equivalent to calling `setPlayerInfoString` in Vault.

If it's not working then check with the verbose command to see what's going wrong.
https://github.com/lucko/LuckPerms/wiki/Verbose

**Comment by math3x3** [comment]
How did you manage to set permissions for towny ?

**Comment by Turbotailz** [comment]
> https://github.com/lucko/LuckPerms/wiki/Verbose

Did you try this @math3x3 ?
