### ISSUE TITLE
Old export format.

### ISSUE THREAD

**Issue by andrewkm** [lucko/LuckPerms#2040]
Please allow us to export using the old export format.
Some of us keep track of our permissions changes via github, and the old format made this absolutely beautiful when it comes to debugging recent changes, issues and problems.

The new JSON format unfortunately, as much as I understand it's the new system, simply is very difficult to use with our tracking systems.

Example: https://i.imgur.com/TGd8M68.png

Please allow a command syntax to export using the old format <3
This would be absolutely amazing!

**Comment by Andre601** [comment]
I don't really think there would be any real need to add any more support for the old export format.
The new one is more compact and allows LP to handle all the actions for the import slightly faster (from what I know)
Right now does LP have support to import exported files from v4, but I don't think there will be anything more to that.

**Comment by andrewkm** [comment]
This suggestion is simply for exporting in the old format for maintenance reasons, nothing to do with importing from it / supporting it.

I'm a simple syntax could be added for those of us who wish to examine an old export style file.

**Comment by lucko** [comment]
You can track changes in the same way with the new json based format.

It's a `.json.gz` file, which you can extract using 7zip to get just `.json` - then changes should be easily readable / identifiable in that file.

**Comment by andrewkm** [comment]
Yeah no no I kno, it's just more readable and pretty in the old format :(

**Comment by lucko** [comment]
JSON is most definitely a readable format!

Sorry it's not really worth re-adding this just for this reason. The code to generate commands based on nodes wasn't very nice, which was one of the reasons for moving away from this system in the first place.

**Comment by andrewkm** [comment]
No worries, had to try lol <3
