### ISSUE TITLE
* Permission not working per server!

### ISSUE THREAD

**Issue by Dblxy** [lucko/LuckPerms#2042]
I have multiple servers and for prison I give one group not all perms so that they don't have all prison ranks. However in the lobby I want to give them all perms.
Unfortunately this just doesn't work! Even when I check the permission and it says it's set to true?!
![gm](https://user-images.githubusercontent.com/61641687/75732306-24da8b80-5cc0-11ea-9849-a3719de402f3.PNG)
![lp nt working](https://user-images.githubusercontent.com/61641687/75732311-2906a900-5cc0-11ea-876b-1fd706cbfa96.PNG)

**Comment by Turbotailz** [comment]
That is a *really* bad idea to give all users the `*` permission. It could give them access to LuckPerms and, well, obviously that's not something you want in any situation.

**Comment by Andre601** [comment]
Giving * to all is, like Turbo mentioned, one of the most stupid ideas ever.
You could then also just give OP for the same effe t.
Better setup your permissions properly.

**Comment by Dblxy** [comment]
I meant that it would only be for the owner rank!
