### ISSUE TITLE
Luckperms permission issue

### ISSUE THREAD

**Issue by kaistenning1018** [lucko/LuckPerms#2046]
hello there 

I recently started a sky blocks server I added a plug-in to let people to do /shop called economy shop GUI. I added luck perms to allow people to do /shop and added it to the default but if people leave the server then join again it says you do not have to permission and I have to reload the server for them to have with the permission   /Re-confirm can you help?

**Comment by Andre601** [comment]
Any errors?
Any messages when they join?
What is your server setup? Is it a network?

You miss out crucial information for us to actually assist you in your issue.
