### ISSUE TITLE
Import issue on Luckperms v5

### ISSUE THREAD

**Issue by diamkil** [lucko/LuckPerms#2047]
When trying to import my h6.json.gz it gives me this error: https://hastebin.com/imuyoverej.cs
I tried with the command: /lp import h6 and /lp import h6.json.gz and get the same error

**Comment by BrainStone** [comment]
Is this fixed?  
Or why did you close it?

**Comment by diamkil** [comment]
> Is this fixed?
> Or why did you close it?

wasn't an issue actually, just me being stupid
