### ISSUE TITLE
Re add "group" alias for the parent command

### ISSUE THREAD

**Issue by LogGits** [lucko/LuckPerms#2054]
`/lp user {username} group set {group}` was an easy to understand addition. With its removal comes unnecessary confusion. If I were to give access to a staff member and said, "change this users group" they would look through 2 routes:
```
/lp group {groupname} add {player} - not a thing.
/lp user {username} group set {group} - not a thing anymore.
```
With the first obviously being the easiest to understand and the second being very self explanatory. 
They are referred to as "groups". When you create it, you create a group (`/lp creategroup, /lp group`). 

Using the term `parent` in `parent set {group}` to refer to group modification causes unnecessary confusion and isn't congruent(probably not the term im lookin for xD) with the actual term "group".

It would be nice if `parent` could be swapped out for `group`, or even `group` be added as an alias of `parent` to avoid confusion.

**Comment by kmecpp** [comment]
Agree with this. Not having a single letter alias is annoying (Ex: lp u kmecpp g set test)
