### ISSUE TITLE
Pixelmon commands

### ISSUE THREAD

**Issue by funkydealer42** [lucko/LuckPerms#2058]
i'm playing on a pixelmon server and i have myself set as an admin and everything works, except for the pixelmon commands, i can't find those in the lp editor permission tab either

**Comment by Andre601** [comment]
Either check the documentation of the Pixelmon mod(?) and if that doesn't help, use LuckPerms' [Verbose command](https://github.com/lucko/LuckPerms/wiki/Verbose)
