### ISSUE TITLE
 Gm usage permissions

### ISSUE THREAD

**Issue by levirzx** [lucko/LuckPerms#2059]
How can I grant permissions to a group on gamemode spectator and survival? But so that the player in the group could not use creative, adventure.

**Comment by Andre601** [comment]
This entirely depends on your Server setup and not LP itself, as it doesn't manage the gamemodes of players.
If you use a plugin like Essentials(X) that manages the /gamemode command, check its documentation for the command permissions.
If it is the default vanilla command, then the permissions would be `minecraft.command.gamemode`

Note that vanilla /gamemode doesn't have permissions to restrict it for specific gamemodes only, while EssentialsX does.

**Comment by levirzx** [comment]
> This entirely depends on your Server setup and not LP itself, as it doesn't manage the gamemodes of players.
> If you use a plugin like Essentials(X) that manages the /gamemode command, check its documentation for the command permissions.


Yes, I have essentialsX, but I did not quite understand where to enter the permissions.

**Comment by Andre601** [comment]
https://github.com/lucko/LuckPerms/wiki/Usage

**Comment by levirzx** [comment]
![image](https://user-images.githubusercontent.com/62181675/76685941-90114f80-6628-11ea-8760-cbc628be5ce6.png)
I issued such permissions for the players. But it still doesn’t work

**Comment by BrainStone** [comment]
No ``.`` at the end. Also be sure to click save and to run the command.

**Comment by levirzx** [comment]
> No `.` at the end. Also be sure to click save and to run the command it shows after clicking save.

it's worked, thank u <3

**Comment by BrainStone** [comment]
You're welcome. Feel free to close this issue.
