### ISSUE TITLE
making a node false seems to do nothing?

### ISSUE THREAD

**Issue by gerardvanschip** [lucko/LuckPerms#206]
I created a group "Resident" and stuck "/lp group Resident permission set essentials.tpa false" but the users can still use TPA.

Likewise I also added "essentials.gamemode" to "Engineer" and they cant use gm1

Other permissions seem to work fine, its just some of them that dont seem to stick

**Comment by VankkaGithub** [comment]
Are you sure your users have the group Resident? and the permission actually updated (/lp group resident permission info)

Are you using EssetialsX? https://github.com/drtshock/Essentials/wiki#differences-between-essentialsspigot-essentials-and-essentialsx
