### ISSUE TITLE
1.15 Permissions

### ISSUE THREAD

**Issue by Durpy** [lucko/LuckPerms#2061]
I am using the newest version of Luckperms but in version 1.15.2 even when all my perms are in there they dont get the permission. I have essentials.hat enabled for all my groups and nobody can do /hat. Same goes for all of my moderator perms (Litebans permissions) I closed my server from 1.14-1.15 and when i reopped I put the new version of the plugin into my folders, it worked fine before.

**Comment by lucko** [comment]
Use the verbose command to debug.

https://github.com/lucko/LuckPerms/wiki/Verbose
