### ISSUE TITLE
Server Freezes 

### ISSUE THREAD

**Issue by SladeHazard** [lucko/LuckPerms#2062]
Console errors server freeze when using the plugin quests: https://hastebin.com/dujucemeno.shell
I reported this to the author this was his reply: https://gyazo.com/e7f84db4d94364ddfe31484cd5b28f39

**Comment by Tobi406** [comment]
The author of the Quests plugin already made a PR himself that tries to fix the issue: #2060

**Comment by lucko** [comment]
Strange, it's not obvious to me that either plugin is to blame.

The call that the Quests plugin is making to `getEffectivePermissions` seems to be perfectly safe (although arguably could be avoided for performance reasons, but that's besides the point)

https://github.com/PikaMug/Quests/blob/ccc2ee8ada6b8c9ce14d1933901e81a10296adb6/main/src/main/java/me/blackvein/quests/Quests.java#L3037

And the LP implementation of that method seems to be ok too, so I'm not sure.

Does the crash happen frequently, or reliably? Has it happened more than once?

**Comment by electronicboy** [comment]
crossref: 
https://github.com/PikaMug/Quests/issues/1121#issuecomment-599201817

**Comment by SladeHazard** [comment]
> Strange, it's not obvious to me that either plugin is to blame.
> 
> The call that the Quests plugin is making to `getEffectivePermissions` seems to be perfectly safe (although arguably could be avoided for performance reasons, but that's besides the point)
> 
> https://github.com/PikaMug/Quests/blob/ccc2ee8ada6b8c9ce14d1933901e81a10296adb6/main/src/main/java/me/blackvein/quests/Quests.java#L3037
> 
> And the LP implementation of that method seems to be ok too, so I'm not sure.
> 
> Does the crash happen frequently, or reliably? Has it happened more than once?

Only happend once

**Comment by lucko** [comment]
Ah I hadn't seen the timings report - makes sense.

Doesn't seem to be an LP issue then. :)

**Comment by PikaMug** [comment]
I suspect that the problem arises when the `getEffectivePermissions()` call occurs too frequently (either by the same player or multiple) as a result of it being used in Quests' event listeners. While it is, of course, possible to address the issue with a workaround on my end, the underlying issue appears to be with LuckPerms as I have explained in https://github.com/lucko/LuckPerms/pull/2060
