### ISSUE TITLE
Luckperms web editor

### ISSUE THREAD

**Issue by SaltyPotata** [lucko/LuckPerms#2065]
I don't know why but luckperms editor link is only showing up in console, It's not showing up in the game chat. 
![image](https://user-images.githubusercontent.com/62210667/76703950-f011ff80-66d5-11ea-9533-3ee9cd19ef9e.png)

![image](https://user-images.githubusercontent.com/62210667/76703966-0750ed00-66d6-11ea-8865-f61433ab176d.png)

**Comment by Andre601** [comment]
1. Not an LP issue, as LP generates the link (as shown in your second screenshot)
2. Check your plugins. It could be one like an anti-ad plugin, that prevents links from being shown in chat (And handles this extremely poorly)?
3. No need to censor the editor link. Nobody can harm your server through it unless they have console-access or can use the applyedits-command of LP.

**Comment by lucko** [comment]
> Check your plugins. It could be one like an anti-ad plugin, that prevents links from being shown in chat (And handles this extremely poorly)

This sound like the most likely cause - alternatively are you using a chat mod client side? Maybe that's affecting it?
