### ISSUE TITLE
Suggestion: Allow the use of prefix element in meta to broaden spacing options.

### ISSUE THREAD

**Issue by larryb11** [lucko/LuckPerms#2068]
Hey Luck, I had an idea:

Would it be possible to allow something like 
![image](https://user-images.githubusercontent.com/58414982/76737564-a30e4780-672e-11ea-925c-c4ebaa2135b2.png)
in order to be able to take advantage of spacing when using placeholders like %luckperms_prefix_element_highest_on_track_staff%? 

As it is right now, using that placeholder will return the prefix that is highest on that track in chat, but spacing from the meta-formatting section will not be applied to it, though it would be pretty darn useful (and super cool) if it did. Being able to have the existing `prefix:`, and `suffix:` categories alongside the ability to add in or change them to `prefix_element:` or `suffix_element:` would broaden possibilities for the use of the element placeholders.

Thanks!

Larry

**Comment by lucko** [comment]
Could you not just add the spacers in when you use the placeholders?

Sorry I think expanding the meta formatting function any further is out of scope at this point.

**Comment by larryb11** [comment]
Aight thanks Luck!
