### ISSUE TITLE
Prefix stopped working on Luck Perms 1.15.2

### ISSUE THREAD

**Issue by freezeline** [lucko/LuckPerms#2071]
My prefix worked very good, but last time i joined my server my prefix was gone, i typed "/lp user Freeze_Line info" and i had prefix "Owner" but when i typed "hi" i saw this "[world]<Freeze_Line> hi" i don't know what happend and what to do.

**Comment by BrainStone** [comment]
LuckPerms does not handle the chat. Your chat plugin does. So there's an issue with your chat plugin, not LP (as you demonstrated with the ``/lp user Freeze_Line info`` command).

Reach out to the support of your chat plugin.

**Comment by freezeline** [comment]
I will try it, thank you

**Comment by freezeline** [comment]
But i don't know why it stopped working, it worked before.

**Comment by BrainStone** [comment]
Neither do I. Though this isn't the right place because LP clearly still works as intended.

**Comment by freezeline** [comment]
I have only one chat plugin "EssentialsXChat"

**Comment by freezeline** [comment]
And i don't have a map for this plugin

**Comment by freezeline** [comment]
Do i have to uninstall EssentialsXChat?

**Comment by BrainStone** [comment]
What map are you talking about?  
You are supposed to reach out to their support.

**Comment by freezeline** [comment]
But how do I supposed to reach their support?

**Comment by freezeline** [comment]
I have never asked for support for my server

**Comment by BrainStone** [comment]
https://www.spigotmc.org/resources/essentialsx.9089/

Google is a thing too.

**Comment by Turbotailz** [comment]
What does /ess version show you?
