### ISSUE TITLE
Warning on 1.15.2

### ISSUE THREAD

**Issue by dansleboby** [lucko/LuckPerms#2075]
I get some warning on 1.15.2

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by me.lucko.luckperms.common.dependencies.classloader.ReflectionClassLoader (file:/opt/minecraft/mineqc/plugins/LuckPerms-Bukkit-5.0.94.jar) to method java.net.URLClassLoader.addURL(java.net.URL)
WARNING: Please consider reporting this to the maintainers of me.lucko.luckperms.common.dependencies.classloader.ReflectionClassLoader
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by BrainStone** [comment]
#952 

Please check for existing issues in the future.
