### ISSUE TITLE
lp user <name> group add/remove <group>

### ISSUE THREAD

**Issue by AlekseyTitov99** [lucko/LuckPerms#2076]
Please add back: "lp user <name> group add/remove <group>"

It was randomly removed from the newer version of luck perms. I need it because I have a ton of purchases using that command for my global ranks and there is no way I can change it now.

**Comment by Turbotailz** [comment]
It wasn't randomly removed, it was one of many legacy aliases that shouldn't really have been added in the first place.

Why can't you just change them?

**Comment by AlekseyTitov99** [comment]
Essentially, if a player has already purchased a global rank and has not joined the server then the command won't process, so those who haven't joined all the servers have commands pending and I don't think I can change pending commands with buycraft

**Comment by Turbotailz** [comment]
I'd consider contacting their support

**Comment by Turbotailz** [comment]
An alternative is to downgrade to version 4

**Comment by BrainStone** [comment]
There was a reason this alias was undocumented btw. And yes downgrading temporarily to a v4 and then changing the commands and upgrading back should work.
