### ISSUE TITLE
[Suggestion] Store groups' permissions in JSON when SQL type of storage is used

### ISSUE THREAD

**Issue by MrIvanPlays** [lucko/LuckPerms#2077]
For example

"INSERT INTO luckperms_groups_permissions(group, permissions) VALUES (`admin`, `{"permission.node": true, "another.permission.node": false}`)". Would look much better compared to current thingy

**Comment by electronicboy** [comment]
That breaks database design and usage and is a whole lot more inefficient for working with

**Comment by RJHaytree** [comment]
Out of interest, why do you want this to be changed, and what would be the benefit of using this over the current system?

**Comment by Andre601** [comment]
I myself can also not see any benefit from this.
If you want to store it as JSON, just use JSON storage I guess?
There is no real benefit for having the information stored as JSON on a remote database.

**Comment by lucko** [comment]
> That breaks database design and usage and is a whole lot more inefficient for working with

This
