### ISSUE TITLE
First joining players don't get assigned automatically to default group

### ISSUE THREAD

**Issue by thada2607** [lucko/LuckPerms#2078]
After new players joined my server, they didn't get assigned to default group, I've checked with listmembers and they weren't there. I had to manually add each one of them to the group. Am I missing something?
I'm using the 5.0.72 version for my Spigot 14.4.4 server.

**Comment by BrainStone** [comment]
Yes. Players added automatically to the default group that are not online don't show with listmembers.
You can use ``/lp user <user> info``  to verify that they are in the default group.

**Comment by thada2607** [comment]
@BrainStone "Online players" mean players that are connected with a Mojang account right?
I tried your method and it works. Thank you.

**Comment by BrainStone** [comment]
I mean players that are on the server.  
There *might* be a chance that they then still don't show there.

**Comment by BrainStone** [comment]
I see. Then listmembers does exclude all players that are automatically assigned to default. There's a technical reason for that.

**Comment by MWFIAE** [comment]
Basically everyone who doesn't have a group is in the group default. 
No database entry is created to be more flexible and use less space in the database, etc. 

Therefore there is no way to know who is in the group as there could be million members, but they aren't saved anywhere.

**Comment by lucko** [comment]
Yeah this is normal :)
