### ISSUE TITLE
GriefPrevention permission gets overwritten

### ISSUE THREAD

**Issue by Sir-Will** [lucko/LuckPerms#208]
hey,

there seems to be an issue with LuckPerms which causes the permissions set by `/cfg` command from GP to overwrite. This did only happen with h2 and MySQL but not json.
More info here: https://github.com/MinecraftPortCentral/GriefPrevention/issues/349

**Comment by lucko** [comment]
I need more detail than that.

**Comment by Sir-Will** [comment]
What exactly do you need?

**Comment by lucko** [comment]
An indication of how to reproduce the issue would be good, or even what the issue is? /cfg is not a LuckPerms command, so I don't understand why you're posting it here?

Can you give me code to test with?

**Comment by Sir-Will** [comment]
That's why I linked the issue on the GriefPrevention repo which includes that information.

**Comment by lucko** [comment]
No, show me proof this is a LP issue. I need reproducible test code.

**Comment by bloodmc** [comment]
@lucko https://github.com/MinecraftPortCentral/GriefPrevention/blob/master/src/me/ryanhamshire/griefprevention/command/CommandClaimFlagGroup.java#L125

https://github.com/MinecraftPortCentral/GriefPrevention/blob/master/src/me/ryanhamshire/griefprevention/command/CommandHelper.java#L439

Those are what I am calling for /cfg commands.

@Sir-Will Provide an export of the data when it breaks.

**Comment by Sir-Will** [comment]
Sorry, which data do you mean?
