### ISSUE TITLE
Permissions failing after joining game

### ISSUE THREAD

**Issue by Weasel-Beans** [lucko/LuckPerms#2080]
https://pastebin.com/j2kKzEWs

Upon joining the server at one particular point, luckperms gave this warning, and subsequently I was unable to type any commands presumably due to a lack of permissions. Relogging fixed this.

**Comment by BrainStone** [comment]
What LuckPerms version and Spigot version are you using?

**Comment by Weasel-Beans** [comment]
My bad, here's a timings report that shows all that:

https://timings.aikar.co/?id=6afc95b40df84587bd8e8cf21ac82d5f

**Comment by BrainStone** [comment]
Update https://luckperms.net/

**Comment by lucko** [comment]
Thanks for reporting, should be fixed in the latest version.
