### ISSUE TITLE
/lp applyedits not found

### ISSUE THREAD

**Issue by iAMtheDelusion** [lucko/LuckPerms#2082]
As the title suggests, whenever I attempt to use this command on the console, the server doesn't recognize the command. Any help is appreciated.

version is: 5.0.72 on a spigot server hosted on Shock Byte on version 1.15.2
*context: Used the Web Permissions Editor and used the command generated by the website when I saved the page.*

**Comment by larryb11** [comment]
A couple of things to try would be:
1. make sure that you ditch the `/` in console - it should be `lp applyedits <code>`
2. Update to newest LP

You can ask on the discord if it continues - you'll probably be helped faster that way! https://discord.gg/luckperms
