### ISSUE TITLE
Suggestion: Can you support nicknames with space? (Bedrock Edition) (Nukkit)

### ISSUE THREAD

**Issue by good777LUCKY** [lucko/LuckPerms#2083]
In Bedrock Edition, it is possible to add spaces in the nickname. However, Luckperm commands don't  support nicknames have space so I can't use Luckperm commands like ```/lp user player 123 permission info```. So can you support it like using quotes. For example, ```/lp user "player 123" permission info```. I think it would be useful than writing UUID or change config(allow-invalid-usernames) instead.

**Comment by good777LUCKY** [comment]
Also, ```allow-invalid-usernames: true``` doesn't work that nicknames have space.

**Comment by lucko** [comment]
Quotes are already supported.

![](https://i.imgur.com/j8FIb17.png)
