### ISSUE TITLE
Users not automatically assigned to the default group

### ISSUE THREAD

**Issue by emanuele3d** [lucko/LuckPerms#2086]
Hi everybody, my name is Manu, i am typing from Switzerland and I'm a dad setting up a server for the children of our neighborhood to help them stay healthy and entertained while we are collectively fighting the coronavirus with self-isolation. 

I am using LuckPerms (v5) and I am puzzled because it appears nobody by default is in the default group. Is this the expected behaviour? If not, how can I debug what is going on?

Thanks for your help!

**Comment by emanuele3d** [comment]
It should be noticed I did read the page https://github.com/lucko/LuckPerms/wiki/Default-Groups but I see nothing to suggest this is the normal behaviour.

**Comment by Andre601** [comment]
The group `default` should be assigned on join.
Could you provide us with the output of `/version` and the exact version of LuckPerms?

(Also hello from a fellow person in switzerland 👋)

**Comment by emanuele3d** [comment]
Hmmm... interesting, I just found something. 

If I try to add people to the default group I get:

   [user] already inherits from default () in context global

However, if I use /lp groups default listmembers

There is only one user listed in the group out of 4 connected to the server, and I never assigned them to any group.

**Comment by Andre601** [comment]
Listmembers won't work reliably on the default group. This is iirc an intentional behaviour due to its programming

**Comment by emanuele3d** [comment]
Ah. That would explain it. =)

It still makes sense to assign permissions to it though right? So that normal users have a set of permissions?

**Comment by emanuele3d** [comment]
I'm closing this as @Andre601 last reply addressed the issue. Thank you Andre!

**Comment by BrainStone** [comment]
If you want to check if a user is actually in the default group or not, just run `/lp user <user> info` and it should tell you ;)
