### ISSUE TITLE
Unable to upload permission data to the editor.

### ISSUE THREAD

**Issue by ArifJanMC** [lucko/LuckPerms#2087]
When i try to use `/lp editor` or `lp editor` in console i recieve this message

> Unable to upload permission data to the editor.

I tried latest spigot and https://luckperms.net, but problem is still here, What can i do?

Additional info:
```
[20:59:04 INFO]: [LP] Running LuckPerms v5.0.72 by Luck.
 [LP] -  Platform: Bukkit
 [LP] -  Server Brand: Paper
 [LP] -  Server Version:
 [LP] -  git-Paper-1618 (MC: 1.12.2) - 1.12.2-R0.1-SNAPSHOT
 [LP] -  Storage:
 [LP] -     Type: H2
 [LP] -     File Size: 0,02MB
 [LP] -  Messaging: None
 [LP] -  Instance:
 [LP] -     Static contexts: None
 [LP] -     Online Players: 0 (0 unique)
 [LP] -     Uptime: 14m 21s
 [LP] -     Local Data: 0 users, 2 groups, 0 tracks
```

**Comment by Andre601** [comment]
Please provide the message and any possible errors associated with it.
But the fact that LP can't upload permission data could mean, that your server might not allow connections to other sites, which LP needs for the editor to work.

**Comment by ArifJanMC** [comment]
> 
> 
> Please provide the message and any possible errors associated with it.
> But the fact that LP can't upload permission data could mean, that your server might not allow connections to other sites, which LP needs for the editor to work.

No error message. I don't use any VDS or dedicated at the moment. It happened on my PC with disabled antivirus.

**Comment by lucko** [comment]
There should be an error in the console if the upload failed.

**Comment by BrainStone** [comment]
I personally checked the logs, there are no errors there.

**Comment by ArifJanMC** [comment]
If you don't trust me, here's a video. Check it.
https://youtu.be/Cm7fUgD0TJI

**Comment by ArifJanMC** [comment]
![изображение](https://user-images.githubusercontent.com/51852933/77413808-b0e95a00-6e0b-11ea-9a33-98d5eab77fd0.png)
Here's a screenshot from logs. You can check time on video and log time to understand that it's valid logs.

**Comment by lucko** [comment]
Ah my bad, the error should be printed on the latest version.

Try 5.0.104 or newer. https://luckperms.net/

**Comment by ArifJanMC** [comment]
Sure thing, it's here:
https://pastebin.com/qAxbknAL

**Comment by lucko** [comment]
Seems like the connection is being blocked - most likely your host is doing this.

**Comment by ArifJanMC** [comment]
I use it on my PC

**Comment by lucko** [comment]
Then possibly your ISP? The editor upload facility is behind Cloudflare, fyi.

If not, possibly some sort of antivirus or content filter on your internet connection.

It's definitely not a LP issue, sorry!
