### ISSUE TITLE
Send specific message when player uses /lp group default listmembers

### ISSUE THREAD

**Issue by Andre601** [lucko/LuckPerms#2088]
When I remember correctly does `/lp group default listmembers` not show all members in that group (Because of code or whatever).
If that's still true should there be a note/message about this when using this exact command, to inform tha player about this fact and reduce confusion about why some players aren't displayed within that group's listed members.

**Comment by BrainStone** [comment]
And I think that is should show at least online players (that are in default).

**Comment by Turbotailz** [comment]
Yeah this confuses so many people.
