### ISSUE TITLE
Execute Command via Command Block 

### ISSUE THREAD

**Issue by lemafor** [lucko/LuckPerms#2089]
Hey,
is there a way to execute a command like /lp user ... parent add player with a command block?
Yes, exactly this question was here several months ago and it was closed with: "Command blocks are - to my knowledge - not supported by plugins or spigot in general." ([https://github.com/lucko/LuckPerms/issues/1721](https://github.com/lucko/LuckPerms/issues/1721))
I have the same problem but I performed some tests and here is my results. 
I have command block with this command:
`/pex user Adam group set group-a`
There is not "@P" but specific username ("Adam").
Spigot + PEX: it works
PaperMC + PEX: it works
PaperMC + LuckPerms: does not work (with `/lp user Adam parent add group-a` and `/luckperms:lp user Adam parent add group-a`), nothing happens.
So I think it is not problem of Spigot/PaperMC but LuckPerms.

**Comment by lucko** [comment]
Assuming your tests are accurate, it does indeed seem to be a LP issue.

Hopefully I'll get some time to look into it soon - if anyone else wants to have a try in the meantime that would of course be appreciated.

**Comment by JasonHorkles** [comment]
Command blocks w/ LP work fine on my server (Tuinity 1.15.2 but also worked when I used Paper)
The only thing I have that could maybe be making it work is the fact that I have CommandHook installed

**Comment by lucko** [comment]
I've tested using the above setup and it seems to work fine. Closing for now.
