### ISSUE TITLE
Errer, timeout by the Mysql login

### ISSUE THREAD

**Issue by Neo-miner** [lucko/LuckPerms#209]
When i start my Lobby Server the Console says that:
https://hastebin.com/lerugurada.md
and Than he stops to start

**Comment by lucko** [comment]
I replied on Discord.

**Comment by Neo-miner** [comment]
I dont ask it to you,i dont have even discord

**Comment by lucko** [comment]
The log you posted here is identical to the one a user sent me on Discord.

Anyway, my reply was "does it happen after every startup, or only once?"

**Comment by Neo-miner** [comment]
it happens at every Server start

**Comment by lucko** [comment]
Can you try with the latest build from here please: https://ci.lucko.me/job/LuckPerms/

**Comment by Neo-miner** [comment]
I try it , when it doesnt work i write it in here

**Comment by Neo-miner** [comment]
Same Problem
https://hastebin.com/zunetohewi.md

**Comment by Neo-miner** [comment]
here is also the Latest Log
https://hastebin.com/utivukizug.md

**Comment by lucko** [comment]
That's still an initial startup.

**Comment by Neo-miner** [comment]
but how i fix it/ where why is the error happening

**Comment by Neo-miner** [comment]
in the Latest log can you see that he trys to download Drivers but failed, can i download then 
manually or do something else ?

**Comment by Neo-miner** [comment]
do you know from where the Error is ore something other to fix it ?

**Comment by lucko** [comment]
The drivers are being downloaded fine. I don't really understand the issue with the duplicate entries though. 

You still haven't answered my question clearly, does this happen after *every* startup, or only when you run the plugin for the first time?

**Comment by Neo-miner** [comment]
when i start the Server LuckPerms is loading, than i see the error Message and than it stops to start the Server

**Comment by lucko** [comment]
Alright, couple of questions:

1. Have you modified the table prefix setting in the config?
2. Have you tried to modify the database manually previously?
3. Which database server are you using?

**Comment by Neo-miner** [comment]
1.I dont modify anything in the config, only the Login for the Database
2.What do you mean with this ?
3. MySQL

**Comment by lucko** [comment]
> 2.What do you mean with this ?
Have you manually edited anything in the DB, or used some tool to change the data directly?

**Comment by lucko** [comment]
Feel free to reopen if this is still an issue.
