### ISSUE TITLE
Issue with /luckperm <user> parent remove in context global

### ISSUE THREAD

**Issue by AerWyn81** [lucko/LuckPerms#2092]
Hello, we have a little issue with the command `/luckperm <user> parent remove` in the global context. 

If we define a rank, for example the rank adept, on our survival with the command `/luckperm <user> parent add adept survival`, the player has the rank. If we remove him with the command `/luckperm <user> parent remove adept survival` everything works.

So there's my player : https://i.imgur.com/Dv9b0Ro.png
Setting him the rank adept : https://i.imgur.com/bm5cdo2.png
Removing him the rank adept : https://i.imgur.com/xv035lL.png

Now if we set this rank globally, when we remove the rank with the command `/luckperm <user> parent remove adept global`, it doesn't work, he keeps the permission.

Setting him the rank on global : https://i.imgur.com/TQGYLbW.png
Removing : https://i.imgur.com/6v8FbgE.png

However, if we execute the removal from the webeditor, it works.

Interface : https://i.imgur.com/525bLRU.png
After deletion the rank from webeditor : https://i.imgur.com/XYIvD2F.png

I don't understand where is the problem...

Paper : `131`
Waterfall
Database : `MySQL`
Luckperm : `v5.0.100`

Thanks,
AerWyn81

**Comment by Andre601** [comment]
`globally` is not a context. It would be `global`

**Comment by Andre601** [comment]
Nvm. But maybe try removing without any context?

**Comment by AerWyn81** [comment]
If I remove the context from the command, it will take the context that I defined in the context.yml file of each server

**Comment by lucko** [comment]
Should be fixed in the above commit.
