### ISSUE TITLE
From 5.0.95+, getMajorJavaVersion is crashing on Java 13

### ISSUE THREAD

**Issue by karer** [lucko/LuckPerms#2093]
Java 13 returns code '13-ea' (13 early acccess) on java 13 docker image.

https://github.com/lucko/LuckPerms/blob/779bbb9f88bd50def5f55d6c138ea5e12e785801/common/src/main/java/me/lucko/luckperms/common/dependencies/classloader/ReflectionClassLoader.java

**Comment by Andre601** [comment]
This is probably related to the illegal access warning you get in Java 11+

**Comment by lucko** [comment]
Thanks for reporting, should be fixed in the above commit.
