### ISSUE TITLE
I can't list user permissions

### ISSUE THREAD

**Issue by IlPicasso** [lucko/LuckPerms#210]
Hello , I have this issue when I use /lp user (User) permission info
http://f.cgm.rs/javaw_2017-03-19_00-20-57.png

get this, it does not output the real information  which are the 14 entries

**Comment by lucko** [comment]
Which server version? Any info in console when you try to run the command?

**Comment by IlPicasso** [comment]
When I do it through console it works

`> [13:09:10 INFO]: [LP ]Il_Picasso's Nodes:
> [13:09:10 INFO]: > ezprestige.prestige.1 (true) (server=prison)
> ezprestige.prestige.2 (true) (server=prison)
> ezprestige.prestige.4 (true) (server=prison)
> group.a (true) (server=prison)
> prestige1.cost.multiplier (true) (server=prison)
> prestige2.cost.multiplier (true) (server=prison)
> prestige4.cost.multiplier (true) (server=prison)
> asd (true)
> asdasd (true)
> asdasdasdasdas (true)
> asdjf (true)
> asdsadas (true)
> group.owner (true)
> testeando (true)`

in game

http://f.cgm.rs/javaw_2017-03-19_07-11-38.png


Using luckyperms 
3.0.46

**Comment by lucko** [comment]
Which server version? Spigot/CraftBukkit/Paper, etc? Which version are you running? It should say in the log file when LP starts.

**Comment by lucko** [comment]
I think this is probably a ViaVersion issue, not really much I can do about it. Can't reproduce on my end.
