### ISSUE TITLE
One-Time permissions

### ISSUE THREAD

**Issue by Masterfixer06** [lucko/LuckPerms#2100]
Hi there,

I wondered if it's possible to give a group a one-time permission. With this I don't mean a temporary permission so they can use the command unlimited over a period of time. With this I mean that the group can only use the command once.

Thanks in advance!

**Comment by Andre601** [comment]
This isn't the job of a permission plugin, but rather of whatever plugin handles the command.
LP doesn't check if command xyz was run, because it wouldn't make sense to do so and is also out of scope for it.

**Comment by Masterfixer06** [comment]
Wow, thanks for the fast reaction! I'll look for options in the plugin itself then.

Thanks for your help!

**Comment by lucko** [comment]
I agree, out of scope for now.
