### ISSUE TITLE
I have some question about luckperms

### ISSUE THREAD

**Issue by Kunnay** [lucko/LuckPerms#2101]
Hello everyone ! So, i started to create a mimecraft server and I decided to use luck perms instead of Groupmanager, until now Luckperms for me is better and I have some question about using it with Tebex/Buycraft. I learned the plugin a bit but I don't know how I can sell ranks. I know about the tracks and that there is a comand wich upgrade your ranks depending to the track. I can use that as rank upgrade in my store but I don't know this things:
1. How can I sell ranks directly without nedding to upgrade
2. How you use tebex/buycraft in a BungeeCord like i want to sell things on every gamemode that i create
3. Example of my ranks: VIP<VIP+<MVP, lets say someone buy MVP,  what happens if he buys VIP after? Does he get demoted? Is it possible? With Luckperms, how can I block that to happen?

**Comment by Andre601** [comment]
1. [`/lp user <user> parent add <group> [context...]`](https://github.com/lucko/LuckPerms/wiki/Command-Usage:-Parent)
2. This is more or less the job of Tebex and not LuckPerms. But you can [setup LuckPerms for BungeeCord](https://github.com/lucko/LuckPerms/wiki/Network-Installation) to have permissions synchronized across servers.
3. Just setup Tebex in a way to directly give the ranks the player purchases and not use tracks. Those really are mostly for easy promotion/demotion and not really for usage in shops.

**Comment by Kunnay** [comment]
> 1. [`/lp user <user> parent add <group> [context...]`](https://github.com/lucko/LuckPerms/wiki/Command-Usage:-Parent)
> 2. This is more or less the job of Tebex and not LuckPerms. But you can [setup LuckPerms for BungeeCord](https://github.com/lucko/LuckPerms/wiki/Network-Installation) to have permissions synchronized across servers.
> 3. Just setup Tebex in a way to directly give the ranks the player purchases and not use tracks. Those really are mostly for easy promotion/demotion and not really for usage in shops.

So the command you wrote me up there is the command to give the player directly the rank?

**Comment by Andre601** [comment]
> > 1. [`/lp user <user> parent add <group> [context...]`](https://github.com/lucko/LuckPerms/wiki/Command-Usage:-Parent)
> > 2. This is more or less the job of Tebex and not LuckPerms. But you can [setup LuckPerms for BungeeCord](https://github.com/lucko/LuckPerms/wiki/Network-Installation) to have permissions synchronized across servers.
> > 3. Just setup Tebex in a way to directly give the ranks the player purchases and not use tracks. Those really are mostly for easy promotion/demotion and not really for usage in shops.
> 
> So the command you wrote me up there is the command to give the player directly the rank?

You could find it out by clicking it, considering I added a link to it?
