### ISSUE TITLE
Strange error

### ISSUE THREAD

**Issue by ArifJanMC** [lucko/LuckPerms#2104]
What can it be caused by?
https://pastebin.com/VKVsWBth
it was printed on server disable.

**Comment by Andre601** [comment]
https://github.com/lucko/LuckPerms/wiki/Storage-system-errors#luckperms-cannot-connect-to-my-mysql-server

**Comment by lucko** [comment]
If you're only seeing it on disable, then it's probably safe to ignore. :)
