### ISSUE TITLE
Is it possible to block certain variables in a permission node?

### ISSUE THREAD

**Issue by Khongen** [lucko/LuckPerms#2111]
So let's say I wanna allow x group access to /gamemode spectator and /gamemode survival, but not /gamemode creative, is that something I can configure using the editor?

**Comment by Tobi406** [comment]
If the plugin (and if you don't have a plugin for that it is probably vanilla and that does not provide such functionality) that manages the `/gamemode` command allows for seperate permission nodes for each gamemode, you can add these nodes using the web editor.

**Comment by Khongen** [comment]
Could you specify how I could use Verbose, and yes this is the default minecraft command I'm talking about, does that mean I need to find a plugin that is more specific for gamemodes?

**Comment by Khongen** [comment]
Update: I found this one but it's not for 1.15.2 do you happen to know one that is compatible?

https://www.spigotmc.org/resources/gamemode-control.13832/?__cf_chl_jschl_tk__=82343fbaa9fdd7d37f26a6d813f9db68a54def53-1585358079-0-ARWry5jQxvj4dPAm2kIGzRM_DJHfMtE3UGKVlR5ySyFh31pOIHQsmCpmmVdfKJokNYYxHX9vaaFtsrDtGWyZNWKbCrhsbt7lVrk2Bb1tRisLD9HnSgrPJLB872e1NBWlpJfDze5J6RAUvNdhM_3A1fsWgMxeYrvFq4gPKNWiz5h8XeqAB5O4n6R9TfngTTzM9cDYCQfSholamP0x3WtlwCEHxxD66ItRbOgvRvxN24z5F1FBGr0gwlWkn1RX3DNYvi6Iue5NDEfluGYbf2J8nUZvhVQ7IMvvSPKWjxLmS1VliQqOjxgTd93S5mmH5YXm-A

**Comment by Andre601** [comment]
Use EssentialsX, as default mc commands don't have those selective perms.

Also, verbose can have filters to only show specific perms.

**Comment by Khongen** [comment]
For those wanting the same result as me:
So EssentialsX worked after some tinkering, how it works is you gotta give the intended group the permissions `essentials.gamemode` and `essentials.gamemode.others`. After this you gotta save those unless you do it all in the .yml, if you use the editor as myself, save those first and "update" editor by getting a new link ingame (/lp editor) go back in and search for `essentials.gamemode.spectator` and `essentials.gamemode.survival` now it should work for the intended group.

**Comment by Andre601** [comment]
You don't need to create a new session for the permissions to work. Just because they don't appear in the editor doesn't mean they don't exist.
