### ISSUE TITLE
Guys help

### ISSUE THREAD

**Issue by 0tickpulse** [lucko/LuckPerms#2113]
As you know, Im very new to this database thing, i experienced an error whenever i join the game
https://pastebin.com/MF2QaFiZ

**Comment by larryb11** [comment]
That error is detailed on the wiki page here: 

https://github.com/lucko/LuckPerms/wiki/Storage-system-errors#luckperms-cannot-connect-to-my-mysql-server

If you have any more troubleshooting problems, feel free to ask on the discord! You'll probably be helped faster! (https://discord.gg/luckperms)
