### ISSUE TITLE
Luckperms Pleas help

### ISSUE THREAD

**Issue by BrownciosB** [lucko/LuckPerms#2114]
I work with luck perms.
If i set a prefix /lp group owner meta addprefix 100 &4[&c&lOwner&4]
I get this if i chat [Owner] [Owner] BrownciosB
i get 2 prefixes. but i want onliy one time like this [Owner] BrownciosB
How do i fix that pleas help me as soon you guys can !!

**Comment by Tobi406** [comment]
LuckPerms will send what can be seen in `/lp user <user> info` to other plugins, if it shows only one time there it is something with your chat format and so not LP related.

**Comment by BrownciosB** [comment]
![image](https://user-images.githubusercontent.com/62801384/77825776-d0ce9580-710b-11ea-9739-47e3ea841791.png)

**Comment by BrownciosB** [comment]
It is like this i dont know how to fix this

**Comment by Tobi406** [comment]
It is an issue with whatever chat plugin you use.

**Comment by BrownciosB** [comment]
I use vault

**Comment by Tobi406** [comment]
Vault itself does not format the chat.

**Comment by BrownciosB** [comment]
And have essentialschat to

**Comment by Tobi406** [comment]
Then it has to do with that. Look in your EssentialsX config, in your chat format if you have like `{PREFIX} {DISPLAYNAME}` remove the `{PREFIX}` part

**Comment by BrownciosB** [comment]
Okay thank you

**Comment by BrownciosB** [comment]
Its work thanks man :) but how do i split the rank from my name

![image](https://user-images.githubusercontent.com/62801384/77826042-5bfc5b00-710d-11ea-9fe8-77bbbf0c1727.png)

**Comment by Tobi406** [comment]
You can either add it in the command (`/lp group owner meta setprefix 100 "&4[&c&lOwner&4] "`), change your EssentialsX chat format to something like `{PREFIX} {USERNAME} {SUFFIX}` or do it in the LP config using the [end-spacer](https://github.com/lucko/LuckPerms/blob/master/bukkit/src/main/resources/config.yml#L351)
