### ISSUE TITLE
Prefix in both essentials and luckperms

### ISSUE THREAD

**Issue by splendidtank** [lucko/LuckPerms#2118]
I have all prefixes in both essentials and luckperms so my name in chat is "[Owner][Owner] Splendidtank. I tried setting change-displayname to false in the essentials config, but then /nickname did not work anymore (it did fix the double prefix)

**Comment by Laarryy** [comment]
change-displayname will not affect /nick. It will solve the double prefix issue, though. Check out the prefix part of the FAQ on the LP wiki.

**Comment by Laarryy** [comment]
Also duplicate of #2114 look at it for some info

**Comment by splendidtank** [comment]
set the format to "format: '{DISPLAYNAME}&r: {MESSAGE}'" and it worked
