### ISSUE TITLE
Vault primary group permission doesn't respect weights

### ISSUE THREAD

**Issue by Phoenix616** [lucko/LuckPerms#212]
When trying to set Vault's primary group via the `vault.primarygroup.<groupname>` permission it seems to not respect the weights of any child or parent groups. It seems to take a random one and it is definitely independent from the group's weight. (Changing it does nothing and it's not the one with the lowest or highest weight) It's easily noticeable in Essential's /list command that the groups don't match up.

**Comment by lucko** [comment]
Yep you're right. 

However, that setting is quite likely to be deprecated pretty soon. Not many people use it and it's a pain to configure / explain to people.

It has been replaced in the development builds by this option: https://github.com/lucko/LuckPerms/blob/master/bukkit/src/main/resources/config.yml#L65

It basically allows you to scrap the primary group storage option, and instead just use the players "highest" group. I guess that's what you're trying to to anyways?

**Comment by Phoenix616** [comment]
Yeah, that feature does exactly what I want to achieve with it and I will switch to using that instead as it's way easier to handle.

**Comment by lucko** [comment]
Alright, going to close this issue then. The primary group permission will be phased out over the next few versions.
