### ISSUE TITLE
Nukkit: LuckPerms doesn't support names with spaces.

### ISSUE THREAD

**Issue by ProxmaDev** [lucko/LuckPerms#2127]
Hello,

there is a problem with the nukkit version of LuckPerms. It doesn't support names with spaces. 
When you execute for example ` /lp user "My Cool Name" parent add Test` it returns command not recognized. It's also a problem when you try setting a prefix or suffix. "" support is missing.

Best regards,
Proxma

**Comment by Laarryy** [comment]
You can use UUID in the case a username has spaces, since it's really rare and not really a problem for most haha

**Comment by Andre601** [comment]
> You can use UUID in the case a username has spaces, since it's really rare and not really a problem for most haha

Nukkit (Minecraft: Bedrock Edition) doesn't really have UUIDs for players to my knowledge.

@ProxmaDev You need to enable this setting here:
https://github.com/lucko/LuckPerms/blob/2ed45c92a6a55ada6d9c1e50a0082b1b15fa5d66/nukkit/src/main/resources/config.yml#L515-L519

**Comment by ProxmaDev** [comment]
It's enabled by default.

**Comment by ProxmaDev** [comment]
> You can use UUID in the case a username has spaces, since it's really rare and not really a problem for most haha

Using UUID is not really a way.

**Comment by A248** [comment]
It sure looks like Nukkit uses UUIDs
https://github.com/NukkitX/Nukkit/blob/master/src/main/java/cn/nukkit/IPlayer.java#L45

**Comment by Andre601** [comment]
I have been made aware of this by others and it seems to be true.
The solution I suggested should in theory work. If not, then perhaps the name is too long, or something else is causing trouble?
And just to be clear: From what I understand can you not set a user's permission if they didn't join at least once and therefore got cached/saved (Unless Nukkit has a different save-policy in that regard) and I don't think the UUID would work, as it looks like to be a Nukkit thing and not a general MC: BE thing (Also seems to be a randomly generated UUID too?)
That's just what I know about MC: BE and Nukkit, which is a very limited knowledge.

**Comment by ProxmaDev** [comment]
Ok, well I'm using the UUID of players now. Thank you for helping me out :)
