### ISSUE TITLE
i get a 500 error for self hosted web gui

### ISSUE THREAD

**Issue by riverbubles** [lucko/LuckPerms#2129]
I have done all the steps without bytebin
![Capture](https://user-images.githubusercontent.com/39760456/78123891-36938800-7452-11ea-89d4-74597427fbe9.JPG)

**Comment by riverbubles** [comment]
I do not have access to logs

**Comment by lucko** [comment]
Check your server error log?

Sorry, this issue tracker isn't really the place to ask for help with setting up a webserver.
