### ISSUE TITLE
Luckperms-Sponge - Enable /op in luckperms.conf

### ISSUE THREAD

**Issue by TechnoRunner18** [lucko/LuckPerms#213]
I was helping someone out on the LuckPerms Discord and noticed something that in my opinion should be fixed. When using luckperms for bukkit, the option to enable the /op command is present as "enable-op: <verbose>" but this option is NOT available in the sponge version of the plugin. Is this how it is supposed to be?

**Comment by bookerthegeek** [comment]
Bukkit has the permission. Sponge removes vanilla op iirc.

**Comment by lucko** [comment]
Open an issue on SpongeAPI. It's not my decision, just the way sponge is designed.
