### ISSUE TITLE
How do you disable plugins on certain worlds in 1.15?

### ISSUE THREAD

**Issue by MillenniumAlpha** [lucko/LuckPerms#2138]

**Comment by Andre601** [comment]
You can't disable plugins themself in specific worlds... At least not with LP.

You can only deny permissions in specific worlds using [Context](https://github.com/lucko/LuckPerms/wiki/Context)

**Comment by Laarryy** [comment]
Not with luckperms.
You need another plugin for that.
You can disable permission nodes from working on certain world's using contexts, which you can find on the wiki.
