### ISSUE TITLE
How to add spaces to prefixes/suffixes?  (Read my Comment?

### ISSUE THREAD

**Issue by tufcat13** [lucko/LuckPerms#2139]
So, for my Staff Manager, I need it to have spaces.  I can’t use the /lp group <group> meta addprefix command because it doesn’t work for me and gives no prefix.  Because of this I give my prefixes and suffixes on the online /lp editor and use prefix.<weight>.<prefix> but quotes doesn’t work the same through that.  What would I do?

**Comment by Andre601** [comment]
Did you double-check that the command actually doesn't work?
You can always check if you (or the group) has a prefix by running `/lp user|group <user|group> info`

If the prefix shows there and has the space, then LP did everything it needed to do.

**Comment by Laarryy** [comment]
There should be no reason for ingame commands to not work, and if the issue persists, please join us on the [discord](https://discord.gg/luckperms) and we'll try and troubleshoot it. If the editor also doesn't work, also join us on discord and we'll troubleshoot. An easy solution is to just add the space in your chat format line, for whatever plugin you use. 

As Andre said, LP might actually be doing what it needs to do. Make sure you don't have more than 1 permissions plugin.

**Comment by tufcat13** [comment]
> Did you double-check that the command actually doesn't work?
> You can always check if you (or the group) has a prefix by running `/lp user|group <user|group> info`
> 
> If the prefix shows there and has space at the end, then LP did everything it needed to do.
> 
> I also think this would be better suited for the [LuckPermsWeb](https://github.com/lucko/LuckPermsWeb) repository as it has to do with it.

Uhh, yeah.  I’m so stupid.  I forgot that it wouldn’t give it if it had a space and didn’t have quotes.  Sorry, I’m a newer server owner.  Just started in January.

**Comment by lucko** [comment]
It's ok!
