### ISSUE TITLE
permission feature

### ISSUE THREAD

**Issue by popcorn9499** [lucko/LuckPerms#214]
Is it possible for the plugin to add a way to list the permissions required for a command so say if you dont know the permissions you can run a command to show the permissions required and it gives the permissions that are required to use the command. I am mostly wanting this for sponge as the forge mods dont have permissions for commands and its "<modid>.command.<commandname>"

Hopefully can figure something out. this would be great for modded server owners. its hard to find the modid and the the command name so this would help me alot. Thanks

**Comment by lucko** [comment]
Already exists.

/lp tree and /lp verbose
