### ISSUE TITLE
Applyedits command does not update track order

### ISSUE THREAD

**Issue by Turbotailz** [lucko/LuckPerms#2144]
Reported in lucko/LuckPermsWeb#162

- have a track with groups [default, mod, admin, owner]
- run `/lp editor`
- JSON looks like this:
![image](https://user-images.githubusercontent.com/10846855/78549780-404c2f80-7846-11ea-9a96-a7603cd13209.png)
- use the web editor to re-order the staff track, owner and admin now before default
- click save
- JSON looks like this:
![image](https://user-images.githubusercontent.com/10846855/78549845-62de4880-7846-11ea-87aa-5ce7470a186e.png)
- run `/lp applyedits <code>`
- plugin reports no changes were made

**Comment by Andre601** [comment]
Is this in fact the cause of the web editor, or perhaps not LP not recognizing the new order in the `groups` section?

**Comment by Turbotailz** [comment]
Web editor is sending back correct info, as far as I'm aware.

Also, adding a group to the track will update the order as well as add the new group.

**Comment by Andre601** [comment]
Wow. I'm so blind that I didn't notice this to be the LuckPerms issue tracker. I thought it was the one of LuckPermsWeb....
If you excuse me now, I go and hide in shame.
