### ISSUE TITLE
End of track

### ISSUE THREAD

**Issue by FazzyPlayzMc** [lucko/LuckPerms#2146]
Hey, i created the track "Helper" and appended the group "Helper" and "Default" to it so the person gets the perms from both and prefix from helper, but when I try and promote myself to the track it just gives me this error "[LP] The end of track helper was reached. Unable to promote FazzyPlayzMc."
Could anyone give me why this happens and how to fix it?

**Comment by lucko** [comment]
Note that tracks do not imply inheritance automatically.

See: https://github.com/lucko/LuckPerms/wiki/Tracks

Commands for editing parent groups are described here: https://github.com/lucko/LuckPerms/wiki/Command-Usage:-Parent#lp-usergroup-usergroup-parent-set-group-context
