### ISSUE TITLE
Config file does not create itself/No config file

### ISSUE THREAD

**Issue by Mikisaurus** [lucko/LuckPerms#2147]
Hello.

I recentely reset my server completely (1.12.2 Sponge Server), I used LP without issues on there before.
I wanted to reuse LP, but after trying to install it again the **config file does not create itself**.
Not sure what to do here as there are no console logs or anything the like to indicate what is wrong, **it's just not there**, like I haven't installed it on the server.

Help is much appreciated as this is for an ongoing server project that had to be reset unexpectedly, hence we want to be able to bring it up again as soon as possible.

Thank you!

**Comment by lucko** [comment]
Send your server log.
