### ISSUE TITLE
#2145 still doesn't work

### ISSUE THREAD

**Issue by hwalker928** [lucko/LuckPerms#2148]
I opened a issue request, it was closed even though it still doesn't work.

**Comment by Turbotailz** [comment]
Please use the same issue and don't open new ones.

**Comment by Turbotailz** [comment]
Also saying "doesn't work" is not a very good way to explain what the problem is.

**Comment by hwalker928** [comment]
The group's don't sync between servers

**Comment by Turbotailz** [comment]
https://github.com/lucko/LuckPerms/wiki/Syncing-data-between-servers

https://github.com/lucko/LuckPerms/wiki/FAQ#how-do-i-get-permissions-to-sync-across-multiple-servers
