### ISSUE TITLE
rankgrant+ issue

### ISSUE THREAD

**Issue by ecud** [lucko/LuckPerms#2149]
i use a rank mod called rankgrant+, to use its ranking system i have have to use luckperms and the ranks arent showing up in chat. I went to the rankgrant support discord and they said to come to your discord and make a ticket. Please help.

**Comment by Laarryy** [comment]
https://github.com/lucko/LuckPerms/wiki/FAQ#why-are-prefixessuffixes-not-working

This link contains common questions and answers about prefixes. Please note that LP does not handle the displaying of prefixes, but your chat formatting plugin must. Feel free to come on over to the [discord](https://discord.gg/luckperms) for further questions!
