### ISSUE TITLE
WorldGuard

### ISSUE THREAD

**Issue by pixar02** [lucko/LuckPerms#215]
I know that you have created a side plugin for this. (don't know if it does what I want it to do).

Dearest

I'm trying to use luckperms on my prison server. Creating ranks, permissions per rank,... but when I setup the worldguard regions they need a permission node... like group.<a region>. But the plugin doesn't allow that to be a permission... How can I fix this? Or how do I do it with the side plugin?

the site where the WorldGuard region is explained and how I use it.:
https://bukkit.org/threads/how-to-use-the-entry-group-flag-in-worldguard.124066/ 

greetings pixar02.

**Comment by lucko** [comment]
The `group.<group name>` permissions are added by default. :)

**Comment by pixar02** [comment]
As long as the region name the same is a the group name...
right?

**Comment by lucko** [comment]
No, it allows you to use addmember with the group name.
