### ISSUE TITLE
WebGUI does not Show User 500+? .Error?

### ISSUE THREAD

**Issue by CloudeLecaw** [lucko/LuckPerms#2151]
![image](https://user-images.githubusercontent.com/12080017/78769975-4baa7280-798e-11ea-90ae-02f2ce5a101b.png)

I have a question about the WebGUI

You can see it shown an amount of 500 Users

![image](https://user-images.githubusercontent.com/12080017/78770408-d12e2280-798e-11ea-9895-cfcba178bef0.png)

The real value of Playerfiles is 2130. is it possible to list them all in the GUI?
and if not is it still possible to give/take perms to the playersfiles that are needed, even if they not listet in the 500?

Edit:
i dont wanne edit all 500 ;) But the chance is high that the may 20 that i want to edit are not listet in this 500.
And yes we store files about 2130 users ;).. most of them are emptry because they just have the normal permissions. but not all ;) Also some plugins grand user permissions we might need to edit..
So it has to make sure all are listet :)

**Comment by Turbotailz** [comment]
You can give groups or permissions to users that are not on the list with the usual commands in game.

**Comment by CloudeLecaw** [comment]
> You can give groups or permissions to users that are not on the list with the usual commands in game.

u saved my day *g*

**Comment by CloudeLecaw** [comment]
hm i tried the name of a not listet player /lp user Blueeyestar editor
image
i need to use the UUID...
image
then it works... is there any chance to search for the playnername when the player is not online too?
looking inside the players folder showed me the yaml i use are stored as .yml

i wanne use yml because its the format i more conformal with

**Comment by lucko** [comment]
Set this option to true.

https://github.com/lucko/LuckPerms/blob/cc80fe510560759f2b51cd80a939d2ac09d83943/bukkit/src/main/resources/config.yml#L36-L44
