### ISSUE TITLE
I can´t see my prefix

### ISSUE THREAD

**Issue by NowPro1556** [lucko/LuckPerms#2152]
Hello
I tried some things and went through the config but couldn't find the problem.

here is a picture to elaborate:
https://pasteboard.co/J2ReiTA.png

Regards
Philip

**Comment by Andre601** [comment]
https://github.com/lucko/LuckPerms/wiki/Prefixes,-Suffixes-&-Meta

**Comment by NowPro1556** [comment]
thanks
