### ISSUE TITLE
LuckPerms Add on feature

### ISSUE THREAD

**Issue by Steev93** [lucko/LuckPerms#2153]
Is it possible to add on timed perks,

Not like the settemp, but addtemp

So the timer can increase the perk or node applied to the user/group to extend the timer available

**Comment by BrainStone** [comment]
https://github.com/lucko/LuckPerms/wiki/Command-Usage:-Permission#lp-usergroup-usergroup-permission-settemp-node-truefalse-duration-temporary-modifier-context

Have a closer read.

**Comment by Steev93** [comment]
Thanks, heaps! Must have missed this.

**Comment by BrainStone** [comment]
You’re welcome

**Comment by Steev93** [comment]
@BrainStone 

IS it possible to display say this node:
"cmi.command.fly" in a API/Placeholder to say this is active, but not show if it is not active?

Eg Timed perks that could be active on the server for 24 hours for those receiving the free perks.
I do use MyCommand yet to play around with it but thought to ask
