### ISSUE TITLE
Question regarding a Java 14 issue.

### ISSUE THREAD

**Issue by Quavelen** [lucko/LuckPerms#2154]
So, I searched for previous issues prior to creating this and found issue #2120. This is a duplicate of my issue, and I'm currently using LuckPerms 5.0.72, which I believe is older than the [c3128de](https://github.com/lucko/LuckPerms/commit/c3128dec0d3cb955ffbe8b8bed7eae66d4b7fd33) commit you mentioned in that issue.

Proof of being a duplicate:

![image](https://cdn.discordapp.com/attachments/554025062106136648/697509302428106822/unknown.png)

My question is this - how do I go about using this commit? I've never learned how to compile a jarfile from GitHub, and before digging into that, I want to be certain of what exactly I'm supposed to do to use this edit you made.

**Minor edit:**
Apparently despite throwing an error, LuckPerms still correctly assigned permissions:

![image2](https://cdn.discordapp.com/attachments/689215119498018883/697513979140112464/unknown.png)

Does this mean I have nothing to be concerned about? Or are there issues which may occur that still require me to use the commit you made?

**Comment by BrainStone** [comment]
https://luckperms.net/ for downloads.

**Comment by Quavelen** [comment]
> https://luckperms.net/ for downloads.

Huh. Well, today I learned LuckPerms has a dedicated website. I've only ever been aware of the GitHub and Spigot page. Thank you, @BrainStone.

**Comment by Quavelen** [comment]
Okay, updating from 5.0.72 to 5.0.128 resolved this issue. Thank you again, @BrainStone.
