### ISSUE TITLE
just a suggestion

### ISSUE THREAD

**Issue by Ramen1234** [lucko/LuckPerms#2155]
In the online editor there should be a feature where you can make groups/sections of permissons. like if your using bungee you should be able to section off the groups like a prisons tab, survival,etc

**Comment by Andre601** [comment]
I personally don't see a benefit here as things like context exists to easly distinguish the different permissions/groups/...

Also, I think this issue would be better suited towards the lucko/LuckPermsWeb repository

**Comment by lucko** [comment]
I'm going to close this suggestion on the basis that it's unlikely to make it into the main plugin in the near future. A quality PR implementing this functionality would likely still be accepted, but it's not something I'm going to work on. :)
