### ISSUE TITLE
"Received invalid first login packet!"

### ISSUE THREAD

**Issue by UltimateSartox** [lucko/LuckPerms#2157]
Basically I use a fork of bungeecord, aegis to be more specific(It worked perfectly), today I updated the fork and I started getting this error message spammed in my console. I thought it was an error from the fork but after I searched a lot and tried many thing I reached to the conclusion that is an luckperms error, because the error disapears when I remove that plugin. I tried putting the plugin in a clean server, but I got the same thing again, I dont know what does it implies or what should I do, it makes my players get the "disconected" when they are joinin thru the bungeecord. Any Idea?
![image](https://user-images.githubusercontent.com/40326845/78939644-28f58800-7a7a-11ea-9c80-8e31c335ee94.png)

**Comment by Andre601** [comment]
I suggest to use either the original BungeeCord or Waterfall, as there is no need to use yet another (rather unknown) fork of BungeeCord, that might change stuff in bad ways.

**Comment by UltimateSartox** [comment]
I actually use it because I need it, my server is a cracked one(No premium server), Aegis fork allow us to make a auth in a virtual server created in the bungeecord, so we dont need to buy other server just for an auth, also gives an antiBot and a AntiVPN/Proxy, so is very useful for my network.

**Comment by Andre601** [comment]
Might be a similar issue as #2143

**Comment by UltimateSartox** [comment]
I checked more deeper and it was a problem with the configuration of the fork. It didnt allow that much packets, already fixed, not a LuckPerms issue.
