### ISSUE TITLE
Player cannot promote user after setting up that they can promote up to specific group and nothing more.

### ISSUE THREAD

**Issue by silicondev** [lucko/LuckPerms#2158]
Hi there,

I have the permission nodes set up from the bottom FAQ of https://github.com/lucko/LuckPerms/wiki/Argument-based-command-permissions.

I have enabled Argument based permissions in the config, but my user in this rank cannot promote other users at all.

![luckperms perms](https://user-images.githubusercontent.com/47757443/78941963-96bca680-7ab0-11ea-9dec-fb6f4d662500.png)

Please could you help?

Thanks,
Silicon

**Comment by Andre601** [comment]
Use verbose to find all required permissions as those you've set won't be enough to actually use the promote command properly.

https://github.com/lucko/LuckPerms/wiki/Verbose

**Comment by silicondev** [comment]
Does this mean I need to set every single node in this list to be true?
https://luckperms.net/verbose/#LrNO8w5KTi

**Comment by silicondev** [comment]
@Andre601 Sorry to pester you with this, it's just that there are over a thousand nodes in that list and some of them would grant the user access to things I don't want them to be able to do.

**Comment by Andre601** [comment]
I can't really help with this as I don't use it myself, but just activating verbose and running the specific command to grant access to should display the required permissions

**Comment by silicondev** [comment]
Could you check the link as there are many nodes in that list, with some such as luckperms.group.permission.set which I don't want the user to be able to do.

**Comment by silicondev** [comment]
If there is an alternative place I can go for assistance with this please could you point me in the right direction?

**Comment by Andre601** [comment]
https://discord.gg/luckperms
