### ISSUE TITLE
"Legacy" import broke between 5.0.72 & 5.0.150

### ISSUE THREAD

**Issue by jlsjonas** [lucko/LuckPerms#2159]
It seems that importing v4-style exports broke between above mentioned versions.
I had to update the plugin in our 1.14 server while migrating as URI-based MongoDB connections were broken on 4.4.1 (what was installed at the time).

5.0.150 (latest on website) seems to try unzipping the file, even after specifically renaming it to a `.txt` (it was just an extensionless file before)

Luckily, yesterday I downloaded 5.0.72 _somewhere_ (via spigot directly?) instead of the latest 5.0.150; which did import correctly.

**Comment by lucko** [comment]
Yes, legacy importing was removed from the plugin. 

If you have old files in this format, you'll need to revert to an earlier version, run the import, and then switch back to the new version.

**Comment by jlsjonas** [comment]
Thanks for the clarification, for later reference (in case someone else stumbles upon it, as I couldn't find a changelog indicating this removal).
The following should download the v4-import compatible version: https://www.spigotmc.org/resources/luckperms-an-advanced-permissions-plugin.28140/download?version=312826
