### ISSUE TITLE
Error with BungeeTabListPlus and Sorting Rule

### ISSUE THREAD

**Issue by Joapple** [lucko/LuckPerms#216]
Since i have it most described there, i'll link to the issue in bungeetablist plus. I thought the error was from there, but he can't seem to find why it is not working. Maybe you can find it? Thanks a lot of the help.

https://github.com/CodeCrafter47/BungeeTabListPlus/issues/206

**Comment by lucko** [comment]
1. Make sure you're using the latest version from the CI server on both Bungee / Spigot.
2. Make sure your groups have weights assigned

You then need to sort by the weight placeholder.

**Comment by Joapple** [comment]
Okay, loaded the version 3.0.56 to both bungee and spigot. The sorting rule playerOrder: "luckPermsGroupInfo,alphabetically" luckPermsGroupInfo doesn't work at all, i am gonna try to sort by vault, but this need to be fixed, i don't think it's a misconfiguration, all my groups has weight.

owner: 0
admin: 1
builder: 2
moderator: 3
apprentice: 4
helper: 5

but they only get sorted alphabetically, as my owner list on bottom , and i have a builder between 2 mod..

**Comment by lucko** [comment]
You might need to use `luckPermsGroupInfo` in reverse.

**Comment by Joapple** [comment]
Sorry for my lack of english, but yeah reversed or not, it just doesn't work. Using Vault or the luckPermsGroupInfo or luckPermsGroupInfoReversed, none works. All my groups has their weight and i made sure my staff has their primarygroup set to the one i want to sort. Meaning all players has default + their donor group, but my staff in luckperms it's the primarygroup only for that reason..

**Comment by Joapple** [comment]
![2017-03-25_16 02 59](https://cloud.githubusercontent.com/assets/22040491/24325675/4bf0bd42-1174-11e7-914c-2b4933363a9a.png)

**Comment by lucko** [comment]
Can you pastebin your BungeeTabListPlus config, I'll try it out myself.

Also, just confirm, you're using the latest BTLP version, right?

**Comment by Joapple** [comment]
btlp: 2.7.3
lp: 3.0.56 (updated today)
http://www.joapple.ca/files/skyblock.yml (btlp file)

**Comment by lucko** [comment]
The placeholders you're using to pull ranks are coming from Bukkit via PlaceholderAPI, which makes me think it may be an issue with the BTLP <--> LP integration on the proxy.

Can you confirm that `permissionSource: LUCKPERMS` is set in your config file?

**Comment by Joapple** [comment]
It was set to bungee, but it used to work with vaultGroupInfo, i changed it to LUCKPERMS, still doesn't work..

**Comment by lucko** [comment]
After changing permissionSource to LP, the luckpermsGroupInfo should work. It wouldn't have worked before making that change.

**Comment by Joapple** [comment]
Do i need to restart the bungee for the permission source to take effect? Because it doesn't work at all, even having permissioursource to LUCKPERMS

**Comment by lucko** [comment]
Not sure. Worth a try I suppose.

Also, just to clarify, your Bungee LP instance needs to be connected to the same DB as the Spigot ones.

**Comment by Joapple** [comment]
Yeah it is connected to the same database, since i have plugins loaded in bungee and perms are in spigot groups, luckperms itself works perfect, just the order of the staff groups that aren't

**Comment by lucko** [comment]
In that case, I don't really know what else to suggest. There's no debug facility in BTLP in order to check the values being returned by the sorting rule, so I'm not sure what to suggest.
