### ISSUE TITLE
Promotion along a track with server context needs explicit permissions to promote a user to each group

### ISSUE THREAD

**Issue by zkharit** [lucko/LuckPerms#2162]
When attempting to utilize the documentation in: https://github.com/lucko/LuckPerms/wiki/Argument-based-command-permissions#promote-other-players-but-not-to-or-past-their-own-level-on-a-track

If the permissions listed are given in a server context to a group (G1), the functionality is backwards of what is listed in the documentation. Instead of having to specify the groups G1 cannot promote to or beyond, I have to add permissions for the groups that G1 can promote with the context. 

Relevant lp editor link; https://editor.luckperms.net/kwz30zRC2a

In this case: the group btccraft-admin can promote a default user to the rank btccraft-helper, but only because of the permission: luckperms.user.promote.btccraft-staff.btccraft-helper server=btccraft

Without that perm specified (like the documentation directs) the group btccraft-admin cannot promote a default user to btccraft-helper

**Comment by Laarryy** [comment]
Verbose log, with example of promoting within limits and trying to promote past: https://luckperms.net/verbose/#aOR4qcVkjx

**Comment by lucko** [comment]
I believe the documentation has now been corrected - you need to get the permissions to false for the groups you don't want them to promote past.
