### ISSUE TITLE
MYSQL SLL BUG

### ISSUE THREAD

**Issue by p82183645** [lucko/LuckPerms#2163]
![image](https://user-images.githubusercontent.com/5382252/79030483-c8766000-7bcb-11ea-91a9-a322ed331688.png)

if no use SSL , will happen
LuckPerms Force use SSL  (This is the problem)

Please add option SSL: true / false

**Comment by zkharit** [comment]
there is an option within the config look for:

properties:
      useUnicode: true
      characterEncoding: utf8
      useSSL: false

add the "useSSL: false" part

**Comment by BrainStone** [comment]
Have you taken a look at the config? https://github.com/lucko/LuckPerms/blob/master/bukkit/src/main/resources/config.yml#L142

Also: https://github.com/lucko/LuckPerms/wiki/Storage-system-errors#mysql-ssl-errors

**Comment by p82183645** [comment]
ok, thank all
