### ISSUE TITLE
LuckPerms Database Error

### ISSUE THREAD

**Issue by MrzcookieCode** [lucko/LuckPerms#2164]
Hello, I am new to using Databases with LuckPerms.
I have read the setup for databases with LuckPerms but when I try to set the storage-method to mariadb (mariadb is the database application I am using) it says connection refused. 
I have when through the troubleshoot to find out but I cant find anything, I even installed phpmyadmin to see what is going on. If anyone can tell me why this is happening and a solution to fix this.

**Comment by codingJWilliams** [comment]
Hello,

Could you please send the errors you get in console via an https://pastebin.com, along with your LuckPerms config.yml, you can replace the database host with `example.com` and the password with `password`.

**Comment by lucko** [comment]
Likely to be one of the issues covered here: https://github.com/lucko/LuckPerms/wiki/Storage-system-errors
