### ISSUE TITLE
[Suggestion] Rank with Permission

### ISSUE THREAD

**Issue by Jaimss** [lucko/LuckPerms#2165]
Honestly, I don't know if this is even possible, and it may just need to be implemented within plugins themselves, but if there was a %luckperms_rank_with_permission% placeholder so I could create messages when someone tries to do something like
> You must be MOD rank or higher to use this.

That would be kinda cool. It probably isn't possible, but if it is it would be a cool feature.

**Comment by Andre601** [comment]
What exactly should the placeholder do now?

**Comment by Jaimss** [comment]
Basically when a player doesn't have permission to execute a command, look through the groups on the server and find the first one in terms of priority that has permission to do the command. Then set the placeholder to that group displayname.

Again though, maybe not possible.

**Comment by Andre601** [comment]
Sounds really weird and like a rare edge case to be supported.
And yes, this would probably require to go through the entire list of groups, checking which one has the required permission.

**Comment by Jaimss** [comment]
Ok haha
