### ISSUE TITLE
Meta weight inheritance issues [Potentially a feature request?]

### ISSUE THREAD

**Issue by DrZoddiak** [lucko/LuckPerms#2167]
So let's say there's 2 groups
`helper` & `officer`

`default`, has an option set of "home-count 5", and a group weight of 0
`helper` inherits from default, and the group has a weight of 30
`officer` has an option set of "home-count 10", and the group has a weight of 15

User `dino` has both `helper` and `officer`, but the player gets 5 homes because `helper`'s weight is higher, despite inheriting the option from default, a lower weighted group.

I don't particularly want `officer` to be weighted higher since `helper` is a staff position, and I don't want certain permissions to be weighted incorrectly by making that change.

I did attempt to try setting `meta.home-count.1` false for `helper` and in `officer` as per recommendation from Turbotailz to someone else around March 9th, but that didn't seem to have an effect.

If there's a way to prioritize metas in groups that have higher weights over groups that don't I think that would make for a great configuration setting.
i.e Allowing the Group of weight 15, to take precedent over the group of weight 30 when the meta from weight 30 comes from a weight 0 group.

If that makes sense, I'm finding it difficult to articulate this cleanly.

**Comment by Andre601** [comment]
Set the officer group as the primary group of a user using the switchprimarygroup command.
This should - to my knowledge - fix your problem.
https://github.com/lucko/LuckPerms/wiki/Command-Usage:-Parent#lp-user-user-parent-switchprimarygroup-group

Alternatively should it be possible to just make default the parent of officer too, and since it has a own permission + higher priority than default *should* it override the permission... Don't quote me on this one tho.

**Comment by DrZoddiak** [comment]
I attempted to set it as my primary group, but I believe with the current setting "parents-by-weight" that actually doesn't matter, suffice to say, it didn't work.

I then tried adding my default group to officer as it's parent, and that also did not work.

home-count of 1 from default (inherited by `helper`)
home-count of 5 from officer 
Still resulting in home count of 1.

**Comment by Brycey92** [comment]
![image](https://user-images.githubusercontent.com/666399/79077006-12466f80-7ccc-11ea-9261-3f60b0509232.png)
Image of the issue for those who are better grasping things visually than textually

**Comment by Brycey92** [comment]
In this issue case I think `parents-by-weight` may be acting like `all-parents-by-weight`.

**Comment by lucko** [comment]
Added this config section which should allow you to achieve what you want. :)

https://github.com/lucko/LuckPerms/blob/4d7a6cb6582e96676c1157f44b7df8912d92d68e/sponge/src/main/resources/luckperms.conf#L419-L434
