### ISSUE TITLE
Migration from PowerfulPerms threw errors but says succeeded

### ISSUE THREAD

**Issue by Zippyduda** [lucko/LuckPerms#2168]
Hi there. 

I have 1 BungeeCord VM and 2 Spigot VMs, currently running the latest PowerfulPerms, version 4.5.2 (not developed any more) alongside the latest versions of ProtocoLib and Placeholder API.

I have setup LuckPerms 5.0.130 on all 3 VMs from https://luckperms.net/ (Bungee version on BungeeCord VM, Spigot versions on Spigot VMs), with MySQL and Redis on the BungeeCord VM.

On 1 of the 2 Spigot VMs, I have ran the following command in the server console to try and migrate from PowerfulPerms to LuckPerms:

_luckperms migration powerfulperms BUNGEEIP:3306 mysql_db mysql_usr mysql_usr_pw players_

This returned the following log with mostly errors but saying it had succeeded at migrating data: https://pastebin.com/kCwhg1vg

Post migration I have also run the following command in the server console:

_lp editor_

However in the web URL it has provided me with, it only appears to have moved the Groups over and about 4 Permissions. I don't see any Players or the majority of the Permissions. I can provide the editor URL via private message if someone would like to take a look.

**Comment by Andre601** [comment]
Seems like PowerfulPerms didn't even had the db connection active?

Anyway, about the errors:
```
[15:15:51] [pool-11-thread-1/WARN]: Thu Apr 02 15:15:51 UTC 2020 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
```
Not 100% sure if this is from PP, or LP... But for LP will you need to set the `useSSL` setting as described here:
https://github.com/lucko/LuckPerms/wiki/Storage-system-errors#mysql-ssl-errors

From what I undestand in the other error is the issue possibly related to a empty value in the database?
And I'm not sure how Exactly migration works from PP to LP, but should it disable database connection midway through the migration?

This is something only @lucko can look into.

**Comment by Zippyduda** [comment]
Hi Andre.

Ah interesting, I shall check PP's remote DB connection now and let you know ASAP.

Regarding SSL, I've set useSSL=false already in the LP config :) That's fixed, it's just throwing that message for PP rather than LP.

**Comment by lucko** [comment]
Should be fixed by the above commit.
