### ISSUE TITLE
Chat Prefixes not existing, even after setting it 

### ISSUE THREAD

**Issue by ApertureDevelopment** [lucko/LuckPerms#2169]
Hello,

This is more a question then a bug report, because I don't think it actually is a LP issue but I can't figure out what it is.

So basically I set a prefix to a group but ``/lp group [grp] info`` shows no prefix, and it also doesnt show up in the user info. I looked with verbose but I don't see what the issue is, I think something might overwrite the LuckPerms prefix provider.

Here is the verbose session:
https://luckperms.net/verbose/#WUyv46pC7b

and here a editor session to see that I should have a prefix:
User: https://editor.luckperms.net/jPXCwQBF0M
Primary Group: https://editor.luckperms.net/BXaMIQ6epg

**Comment by FeaturedSpace** [comment]
Prefixes are stored in the group's meta. Check `/lp <group> meta info`

**Comment by ApertureDevelopment** [comment]
Huh, well there the prefixes show up, but the verbose log still shows them as nil, as well as in the user info ( which does show the users Prefixes ), so this still doesnt explain why they don't show up

**Comment by FeaturedSpace** [comment]
Try deleting the group and creating the prefix again with this command
`/lp <group> meta setprefix 0 <prefix>`

**Comment by ApertureDevelopment** [comment]
Already tried that, and also tried setting a prefix to the user directly. I am 100% convinced that one of the addons causes that, LuckPerms is fine and doing what it should do, but one of the plugins tries to overwrite the Prefix Provider

**Comment by FeaturedSpace** [comment]
Most likely.

**Comment by lucko** [comment]
Try resetting your LP config file, sounds like you've tweaked a setting there which is causing it to return nil.
