### ISSUE TITLE
Ranks and Permissions Disappearing after restart

### ISSUE THREAD

**Issue by AccioAce** [lucko/LuckPerms#2170]
Hello,

I have a auto restart system setup, every time when the server restarts all the ranks and permissions have been removed from every player. Every time when that happens we need to manually restart it again to restore it. It's been happening for a while now. I believe it's a luckperm bug.

**Comment by BrainStone** [comment]
Check for startup errors. If data isn't being saved it's because LP can't properly initialize the data storage.
