### ISSUE TITLE
NO LABLE BEFORE NAME

### ISSUE THREAD

**Issue by jasonzgames** [lucko/LuckPerms#2171]
there is no owner lable before my name
![Annotation 2020-04-12 232516](https://user-images.githubusercontent.com/63572031/79089670-eb605b80-7d14-11ea-856d-8f1b139b8b7b.png)

**Comment by benwoo1110** [comment]
Check that you have the appropriate chat plugins install: https://github.com/lucko/LuckPerms/wiki/Prefixes,-Suffixes-&-Meta#displaying-prefixes-and-suffixes

for more support, you can go to luckperm's discord at  https://discord.gg/luckperms. Thanks!
