### ISSUE TITLE
LuckPerms Bungee Commands are unable to be executed by Grant plugins

### ISSUE THREAD

**Issue by xDavidG10** [lucko/LuckPerms#2173]
For some background, I have LuckPerms installed on my Spigot and Bungee servers.

The issue is that I have a plugin known as 'GrantX' and everything works fine.  Although, it does not seem to be able to execute this - "lpb user %target% parent set %group%". Although,  "lp user %target% parent set %group%" works fine. I contacted the GrantX plugin developer. However, he stated that it doesn't have anything to do with the GrantX plugin as it simply executes the command and that I should come to here for support.

**Comment by Andre601** [comment]
Bungee and Spigot are separate things.
A spigot plugin can't run bungee commands.
That is basic knowledge.
