### ISSUE TITLE
Not exactly an issue. A question.

### ISSUE THREAD

**Issue by bryanrmelo** [lucko/LuckPerms#2174]
My server is based on the fact that, as you progress, you can buy better ranks that guarantee better permissions, but I couldn't find how I define a user without saying his nickname to LuckPerms.
I know my explanation was bad but what I tried to do was:
/ svs add lp user <user> parent add admin
to add the player that interacts with the sign (from the ServerSigns plugin) to a certain group but I don't know what to put in "<user>" so that LuckPerms recognizes that it is the player that is interacting.
The server version is at 1.12.2, LuckPerms is at v.5.0.130
The question must be simple to answer,
Any answer will be of great help.

**Comment by codingJWilliams** [comment]
I'd recommend checking the wiki of ServerSigns. They have a placeholder for getting the player's username: https://i.jay.network/C5PqMQ.png

From the looks of that wiki, it would be `/svs add lp user <player> parent admin` then svs will automatically replace `<player>` with, for example `bryanrmelo` if it was you who clicked it.

I would note however that this is out of scope of the LuckPerms project and definitely would be better answered by the makers of the ServerSigns plugin.

**Comment by bryanrmelo** [comment]
Update: now I need to use the feature and this is what is happening to me, no more text on the server's console, no anything. I am very new to servers and plugins so I ask you a little patience with me. I don't know if it's Server Signs that are not doing its job or is Luck Perms that are.

https://youtu.be/rYnQB223Wfg

YT link bc GitHub doesn't support video.
