### ISSUE TITLE
Permission is set but, not working

### ISSUE THREAD

**Issue by GallopingGold** [lucko/LuckPerms#2175]
I set the worldedit permission to true for the WildHearts rank and its not working. Also tp/eco  isnt working for any rank for Mod+

![Screen Shot 2020-04-13 at 1 36 47 PM](https://user-images.githubusercontent.com/60898731/79144253-a841cf00-7d8c-11ea-84d3-83fe5a72bdb2.png)
![Screen Shot 2020-04-13 at 1 42 14 PM](https://user-images.githubusercontent.com/60898731/79144254-aa0b9280-7d8c-11ea-81b3-e07406729ea5.png)

**Comment by Wocoos** [comment]
I am having the same  issue on my server as well!

**Comment by lucko** [comment]
Use the verbose command to debug further.

https://github.com/lucko/LuckPerms/wiki/Verbose

**Comment by GallopingGold** [comment]
Funny. Verbose didn’t help me. My server host helped me better on this. They said to do /lp user instead of group which it worked. and do permissions individually on each player. I don’t fully get or understand verbose on how it’s supposed to help me and my server
