### ISSUE TITLE
LP not working

### ISSUE THREAD

**Issue by jameslinimk** [lucko/LuckPerms#2177]
I was trying to set up permissions with the default group (the group LP already makes) and did this command
`/lp group default permissions set essentials.kit.newplayer true`
It said it worked so when I tested it I couldn't use /kit newplayer so I tried it again but with this
`/lp group default permissions set essentials.kit true
and
/lp group default permissions set essentials.kit.* true`
Both of those still didn't work. I have the latest version of LP and essentiallX

**Comment by Laarryy** [comment]
https://github.com/lucko/LuckPerms/wiki/Verbose

Try using verbose to find what nodes are being denied you, super easy and tells you exactly what you need!

**Comment by jameslinimk** [comment]
> https://github.com/lucko/LuckPerms/wiki/Verbose
> 
> Try using verbose to find what nodes are being denied you, super easy and tells you exactly what you need!

I did verbose for myself and noticed something strange. Even though I did
`/lp group &l&4owner permission set essentials.* true`
I cannot do /kit and verbose tells me that essentials.kit = false.
Owner inherits default and it still tells me that I cannot use /kit even when op'ed. As far as I know LP is the only plugin on my server that can control permissions

**Comment by Laarryy** [comment]
How strange! Make sure you're using the owner group's name and not displayname, and maybe send a screencap of your plugins list? 

For some speedy response, feel free to join [the discord](https://discord.gg/luckperms), and I'd be happy to help out a bit quicker there.

**Comment by jameslinimk** [comment]
Yes I checked and did it again
`/lp user jameslinimk parent add &l&4owner`
and
`/lp group &l&4owner parent add default`
and tried everything again and still I cant use `/kit` and says infussient permissions
Here are my plugins:
[https://imgur.com/a/xlskzjq](url)

**Comment by Laarryy** [comment]
Some basic questions, then:
What version of MC?
What type and version of server software?
What version of LP? 

Additionally, in the LP config file, ensure you haven't changed any settings regarding global context permission application.

**Comment by jameslinimk** [comment]
Its a 1.14.4 paper server
the version is `LuckPerms-Bukkit-5.0.130`
I haven't touched the config at all.

**Comment by lucko** [comment]
I suspect essentials.kit is being overridden somewhere. Try setting that permission to true on owner directly.
