### ISSUE TITLE
me/lucko/luckperms/luckpermsAPI

### ISSUE THREAD

**Issue by AdelaPlays** [lucko/LuckPerms#2180]
Hello. Today I present issue with LuckPerms and if I can get help.

I own SpongeForge server, and decided to add Luckperms as well as tabmanager from spongeforge. Unfortunately when I do /tabmanager reload it pops out issue with LuckPerms saying: Error executing this command me/lucko/luckperms/luckpermsAPI.

**Comment by Tobi406** [comment]
https://github.com/lucko/LuckPerms/wiki/Upgrading-from-v4-to-v5#api-compatibility

**Comment by AdelaPlays** [comment]
Thanks. Just sucks because sponge website doesnt have the plugin I want updated :c
