### ISSUE TITLE
Server plugin shows user rank, but on database it is stored as a default user

### ISSUE THREAD

**Issue by Kledioz** [lucko/LuckPerms#2181]
I am making a PHP script, in which I query the primary group that a specified user has, to do some stuff.
The problem here, is that said user has the default group in my SQL Database, and in the server shows me that he has the vip rank.

/lp user info:
![image](https://user-images.githubusercontent.com/29718791/79270994-efdf5e00-7e53-11ea-95d8-d45f6ae7b056.png)
(VIP Rank is 'magnate')

SQL Query:
![image](https://user-images.githubusercontent.com/29718791/79271021-fd94e380-7e53-11ea-807d-6a0c6be23d0b.png)
(User is stored as a 'default' user)

I need the primary group to be in the database as well.
 ¿Where is LuckPerms getting this information from?

That server has been restarted so many times, also i executed /lp sync and /lp networksync.

Im currently using `LP v4.4.1`, Although I will update the plugin later, I don't think that being 2 versions behind is the problem

Using:
`Spigot 1.8.8`
`LuckPerms v4.4.1.`
`10.0.38-MariaDB-0ubuntu0.16.04.1`

**Comment by Tobi406** [comment]
Does `magnate` have a higher weight than `default`?

**Comment by Kledioz** [comment]
> Does `magnate` have a higher weight than `default`?

Yes, magnate has '8 weight' and default has '0'

**Comment by Kledioz** [comment]
When we setup LuckPerms on our server a while ago, LuckPerms stored the group that a user had on a single permission, in this case it is "group.magnate", i think LuckPerms doesn't do this anymore , i'm not sure, so i resolved this by querying:
`SELECT 'permission' FROM 'luckperms_user_permissions' WHERE 'uuid' LIKE 'uuid' AND 'permission' LIKE 'group.%'`
![image](https://user-images.githubusercontent.com/29718791/79277408-9892bb00-7e5e-11ea-9d3d-feed4d3425af.png)
Yeah.

**Comment by Andre601** [comment]
The way LuckPerms stores groups applied to users hasn't changed. They are still stored as permissions in the form of `group.<groupname>`
