### ISSUE TITLE
Assign a user a different parent automatically

### ISSUE THREAD

**Issue by ThunderDong76** [lucko/LuckPerms#2182]
Hi, what I'm trying to do is have a player enter a portal (Advanced Portals) and when they enter that portal they'll be assigned a LuckPerms group. However I can't figure out a way to assign this based on anything but their username, which I'd have to do manually.

Is there a way to have LuckPerms assign this automatically? I tried using @p to mimic command blocks but had no success there. Ideally I'd like to be able to tie LuckPerms groups to the Towny nation a player belongs to, but I've no idea how I'd go about doing that. Is there a way to do what I'm trying to do? Or should I resign myself to manually assigning permissions each time?

For context, the reason I'm doing it like this is to prevent players from being able to do anything before they join one of our server's three teams to prevent them from branching off and building elsewhere, as the point of the server is for community builds.

**Comment by lucko** [comment]
You can enable command selectors in the config file.

https://github.com/lucko/LuckPerms/blob/07b2df7c7e2ee141bdc30ceb96e505abba3a98a2/bukkit/src/main/resources/config.yml#L593-L595
