### ISSUE TITLE
Don't have a Console to give rights

### ISSUE THREAD

**Issue by Ramel05** [lucko/LuckPerms#2183]
Hey Guys,
So I was just about to set up my Server with LP, everything works fine, the only Problem I have is that I don't have a Console for my Server, is there another way to give me rights on my Server?
Thanks and good Day.

**Comment by Andre601** [comment]
A server without any console is quite impossible.

**Comment by Ramel05** [comment]
Is it possible to write it directly into the File(s)?

**Comment by Andre601** [comment]
Like I said: A server without console is impossible. Every server has one, or else it wouldn't make sense at all.
You *could* write permissions to a file, but we don't recommend nor support it.
https://github.com/lucko/LuckPerms/wiki/Switching-storage-types

**Comment by Ramel05** [comment]
It is possible when you have the Server on a Qnap and when you've got a maybe to secure Network (no RCon).
But nvm, I just set up a little Server on my PC and made the "starting command" to give me Access and copied my user File to the Server, worked perfectly.
But thanks for your help^^
