### ISSUE TITLE
when i set permissions in OP it does not work when i deop myself

### ISSUE THREAD

**Issue by TheChemist123** [lucko/LuckPerms#2185]
i am trying to allow users who have just joined the server to be able to do basic things, /kits , use jumpads and teleport, I am able to do all of this in OP and when i create a permission in luckperms and deop  myself it does not let do the command that i just allowed users to do. For example i want my jumpads to work so in lucky perms in the default group i have put the code 
jumppads.use and set it to true, then when i join the server i am unable to use the jumpads. I am wondering if it could be that i am using other plugins that they may be overriding luckyperms. 
heres a list of the plugins that i am using
luckperms, worldedit, greatkits, multiverse-portalsGUI, clearlag, nametagedit, holographicdisplays, KP-PVP, multiverse-core, worldguard, advancedportals, infinitepotions, powerranks, vault, essentials, jumppads, commandpanels, citizens, essentialsXMPP, statsSB, essentialsprotect, essentialsGeoIP, essentialschat, TAB, Eyu-BungeeNPCs, CommandNPC, essentialsspawn

if anyone could please help me out that would be amazing, thank you

**Comment by Andre601** [comment]
1. The plugin is called LuckPerms 😉 
2. What exactly is powerrank? If it is a permission plugin, then it might interfere with LuckPerms and cause unwanted side-effects.
3. How did you give the permissions? And did you double-check that it is the right permission?  
You can use Verbose to find the right perms: https://github.com/lucko/LuckPerms/wiki/Verbose
4. EssentialsProtect, EssentialsGeoIP and EssentialsXMPP are pretty much useless (especially XMPP which nobody uses) so you should remove and eventually replace them with something else. I suggest CoreProtect for protection and logging of actions

**Comment by Turbotailz** [comment]
I'm going to say it's probably PowerRanks overriding the permission checks.

Also forget about OP when it comes to debugging permissions. OP gives you every permission so of course things are going to work when you try them while opped.

**Comment by TheChemist123** [comment]
> 1. The plugin is called LuckPerms 😉
> 2. What exactly is powerrank? If it is a permission plugin, then it might interfere with LuckPerms and cause unwanted side-effects.
> 3. How did you give the permissions? And did you double-check that it is the right permission?
>    You can use Verbose to find the right perms: https://github.com/lucko/LuckPerms/wiki/Verbose
> 4. EssentialsProtect, EssentialsGeoIP and EssentialsXMPP are pretty much useless (especially XMPP which nobody uses) so you should remove and eventually replace them with something else. I suggest CoreProtect for protection and logging of actions

Thanks for your quick reply.
I have disabled powerranks and added essentials.home as a permission in luckperms to the default group, when deoped i was able to do /home

It just seems to be the jumppads plugin that i am unable to be able to use even though i have imputed the correct permission into luck perms, but at least i know that i am able to create perms with luckperms, just a bit annoying that jumppads does not seems to work.

**Comment by Turbotailz** [comment]
Either you aren't using the correct permission or there is something else wrong with the plugin.

Verbose mode will likely tell you the correct permission that's being checked.

**Comment by TheChemist123** [comment]
> Either you aren't using the correct permission or there is something else wrong with the plugin.
> 
> Verbose mode will likely tell you the correct permission that's being checked.

Thanks again for the quick reply, i am going to get in touch with the plugin developer as it is definitely just that plugin that seems to be failing. I will keep you updated with how it goes. Thanks

**Comment by Turbotailz** [comment]
No problem, feel free to close the issue if you feel it is resolved, helps save Luck some time later on :)
