### ISSUE TITLE
Partnership

### ISSUE THREAD

**Issue by BenG271** [lucko/LuckPerms#2186]
Hi Luck,

My name is Ben, and I work with Sparked Host LLC, and we would be interested in discussing a partnership with you!

If you are interested, I have sent you a friend request via Discord (Ben G#0001) and we can start talking.

Kind Regards,
Ben G.
Sparked Host LLC Marketing Team

**Comment by BenHall-1** [comment]
@BenG271 I'd recommend trying to contact them for this on their discord :) [LuckPerms Discord](https://discord.gg/luckperms)

**Comment by lucko** [comment]
Get in touch via hey@lucko.me :)
