### ISSUE TITLE
Web editor - Always send potentialContexts as an array

### ISSUE THREAD

**Issue by Turbotailz** [lucko/LuckPerms#2187]
Re: lucko/LuckPermsWeb#190

Their `potentialContexts` array looks like this:

```
  "potentialContexts": {
    "server": "survival",
    "world": [
      "world",
      "world_nether",
      "world_the_end"
    ]
  }
```

It would be great if the single value for `server` was an array instead of a string :)

**Comment by Turbotailz** [comment]
Took matters into my own hands :P https://github.com/lucko/LuckPermsWeb/commit/fcf0b11e4b4c8d3c8ef7dcab39d0daaa48d50c85

**Comment by lucko** [comment]
I was going to suggest that :P 

Means that it will work with people still using older versions of LP. :)
