### ISSUE TITLE
MariaDB Connection Issues

### ISSUE THREAD

**Issue by Kudaa41** [lucko/LuckPerms#2189]
Hey. I currently have the spigot version of LuckPerms on a backend server and I have the bungee version on the bungee. I have went through how to set it up and made sure that it was working on the backend server before putting it into the bungee server. It works fine alone in the spigot/paper server, and it is even connected to the database correctly. However, when I put it into the bungee server, it shows a message in chat after connecting saying "Permissions data for your user was not loaded during the pre-login stage - unable to continue. Please try again later. if you are a server admin, please check the console for any errors."

Checking the console, I found that it showed something to do with connecting to the database. I am not sure if I am doing something wrong, or if it is just having trouble connecting and pulling info from the database. I have tried to empty the database and even did fresh installs of the plugin in both servers. Sadly, none worked. Here is what the console is spitting out:

```
16.04` 21:54:13 [Server] SEVERE at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
16.04 21:54:13 [Server] SEVERE at net.md_5.bungee.BungeeCord.start(BungeeCord.java:286)
16.04 21:54:13 [Server] SEVERE at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:250)
16.04 21:54:13 [Server] SEVERE at me.lucko.luckperms.bungee.LPBungeeBootstrap.onEnable(LPBungeeBootstrap.java:125)
16.04 21:54:13 [Server] SEVERE at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:145)
16.04 21:54:13 [Server] SEVERE at me.lucko.luckperms.common.storage.StorageFactory.getInstance(StorageFactory.java:88)
16.04 21:54:13 [Server] SEVERE at me.lucko.luckperms.common.storage.Storage.init(Storage.java:114)
16.04 21:54:13 [Server] SEVERE at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.init(SqlStorage.java:151)
16.04 21:54:13 [Server] SEVERE at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.init(HikariConnectionFactory.java:79)
16.04 21:54:13 [Server] SEVERE at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.appendConfigurationInfo(HikariConnectionFactory.java:69)
16.04 21:54:13 [Server] SEVERE at me.lucko.luckperms.common.storage.misc.StorageCredentials.getDatabase(StorageCredentials.java:60)
16.04 21:54:13 [Server] SEVERE at java.util.Objects.requireNonNull(Objects.java:228)
16.04 21:54:13 [Server] SEVERE java.lang.NullPointerException: database
16.04 21:54:13 [Server] SEVERE Failed to init storage implementation
16.04 21:54:13 [Server] INFO Loading storage provider... [MARIADB]
> 
```

If needed, I can turn on the debug option and see if it shows anything different if this isn't enough. Thanks.

**Comment by lucko** [comment]
Make sure the `database` setting is correct in your config.yml.
