### ISSUE TITLE
Why can not get the player given permission expiration time?

### ISSUE THREAD

**Issue by xyblues** [lucko/LuckPerms#219]
![jdzzpp qmfpge 153e suu](https://cloud.githubusercontent.com/assets/15712089/24336333/f6ae0126-12bf-11e7-91d9-ebf586f6bd49.png)
![l23 q8 u ue_d13 2thpa](https://cloud.githubusercontent.com/assets/15712089/24336334/f6d817ea-12bf-11e7-944f-8d842ba3ccfa.png)

**Comment by lucko** [comment]
Fixed version can be downloaded here https://ci.lucko.me/job/LuckPermsPlaceholders/2/ or in the PAPI ecloud. 

Thanks for reporting it. :)

**Comment by xyblues** [comment]
Thank you very much, and now it works very well.
![uzq_84 sd 6 mjp y m p4](https://cloud.githubusercontent.com/assets/15712089/24432823/3aa637e8-1457-11e7-8314-0273677fe1cb.png)

But can it be localized?
I want to localize 18h 20m 12s to 18小时 20分钟 12秒

**Comment by lucko** [comment]
I use the function in PlaceholderAPI to convert it to that format, so you'd need to ask clip about changing it.
