### ISSUE TITLE
Permissions not showing in web editor

### ISSUE THREAD

**Issue by connorfarkas** [lucko/LuckPerms#2193]
I was remaking a pixelmon server with the same mods i used before just updated. So my old server i was able to see any permission node (worldedit. whatever and something like pixelmon,* and pixelextras.* but now all i can see is nucleus, grief protection and luckperms nodes. i will add screenshot of both new and old for reference im just stumped why before i could look to see what nodes i wanted and now i have to manually type them so its like why use the web editor and just use the ingame commands to do it, i also have to search each mod for them. 

Thanks for your time,

![old](https://user-images.githubusercontent.com/12475256/79624162-fd177980-80ed-11ea-8381-70c8ca0e00a3.PNG)
![newluckperm](https://user-images.githubusercontent.com/12475256/79624181-13bdd080-80ee-11ea-9379-dedfa42fc62d.PNG)

**Comment by Tobi406** [comment]
The pixelmod nodes have been checked atleast once since the last server restart? You can confirm that by running a [Verbose](https://github.com/lucko/LuckPerms/wiki/Verbose) check and then start another editor session

**Comment by connorfarkas** [comment]
it isnt showing default minecraft permission nodes either in the suggestion bar, verbose went nuts when moving due to grief protection and saw pixelmon command /pixelgive when i used this command. im stumped.
![luckperm](https://user-images.githubusercontent.com/12475256/79624918-2d154b80-80f3-11ea-86b7-2f6fa25b7407.PNG)

**Comment by Tobi406** [comment]
Is the `pixelmon.command.pokegive` permission now showing up in your 2nd editor session?

**Comment by connorfarkas** [comment]
yes, before when i used this and this works on my vanilla server i set up yesterday shows all the permissions, but yes it is there now. im just confused why even default minecraft permissions do not show

**Comment by Tobi406** [comment]
Because they probably weren't checked. Something like `/help` might show some of them. But directly doing the command like `/trigger` too

**Comment by connorfarkas** [comment]
well this is embarrassing /help doesnt work i did enable minecraft.command.help and nucleus.help

**Comment by connorfarkas** [comment]
ok i combated this with setting * as a permission to allow all. a few more showed up like AGP and FAWE but not all, i cycled all help pages

**Comment by connorfarkas** [comment]
i think if i keep this and ask my friends who are helping me setup this server run all commands they need it will update as time goes on. sorry if i sounded angry and rude, im just confused why it wouldnt load all the perms

**Comment by f43tgdrdgdfbd** [comment]
> Because they probably weren't checked. Something like `/help` might show some of them. But directly doing the command like `/trigger` too

hey i know this is an old. but i have the same issue. I'm wondering how you do /help or /trigger. I tried doing the commands in my server but nothing changed.

**Comment by benwoo1110** [comment]
Open new issues if you really think it’s an issue eight luckperms. No point bumping closed issues.

**Comment by jameszie44** [comment]
I was having the same issue I corrected by adding 'sponge.command.help'
