### ISSUE TITLE
Permission help with certain plugin

### ISSUE THREAD

**Issue by J5m00th** [lucko/LuckPerms#2194]
Hello,
I am extremely new with how plugins with minecraft servers work. I have a server that has multiple worlds (factions and creative plots), and I want to have certain permissions for each rank for each world. I use luckperms for my permissions and I am trying to put permissions for the plugin, plotsquared. I have a few ranks and I want to know how permissions is responsible on figuring out how many plots a certain rank can claim, and how I can set it up. (Example: member - 2 plots, VIP - 4 plots, etc).

**Comment by Tobi406** [comment]
LuckPerms itself won't manage plots or anything like that, it's on PlotSquared to provide permission nodes for that.

Try looking at the documentation of the plugin, or, if that doesn't solve your issue, try using [Verbose](https://github.com/lucko/LuckPerms/wiki/Verbose) which can show you what permissions are checked in real time.

If you have found a permission to limit that, you can use [Context](https://github.com/lucko/LuckPerms/wiki/Context) to only have these set in a specific world.
