### ISSUE TITLE
Need some help with bungeecord setup

### ISSUE THREAD

**Issue by FazzyPlayzMc** [lucko/LuckPerms#2195]
Hey, i just moved on to using luckperms bungeecord instead of having to manage perms on each server, so I have luckperms on my main proxy server and on each backend server, and also I have linked all of them to one MySQL database as to control all permissions from the bungeecord server, now I want to control every group, track and permission so should I just use /lpb or /lp? I'm a little confused on it, also if I want players to only have a certain group on a certain server and not on all servers what should I do? And is there an easy way of controlling perms and groups without having to use the inbuilt editor and without using the MySQL database? Like edit the groups in a text editor?

**Comment by upstreamsea** [comment]
Please use /lpb on the Bungee server, and LuckPerms will message all attached servers.

**Comment by FazzyPlayzMc** [comment]
What about controlling perms from a text editor instead of using the inbuild editor or the database?

**Comment by Turbotailz** [comment]
Why do you not want to use the web editor?

You can switch your storage type to a text based database but we don't recommend that for a variety of reasons which can be found on the wiki under "storage types"

**Comment by FazzyPlayzMc** [comment]
Its a lot easier to use a text editor and I can't change the storage type to Yaml since I'm using bungeecord so I'm limited to mysql

**Comment by Turbotailz** [comment]
Sorry misread the part about bungeecord.

The commands you use to control your database should not matter, /lp or /lpb will be fine to use if everything is connected to the same database.

For adding groups and permissions to users on certain servers then you need to read about Contexts on the wiki.

The web editor is the only method of editing this, unless you use the in-game commands.

**Comment by FazzyPlayzMc** [comment]
Well, alright it does suck that I cant use any other form of editor but alright, imma close this now
