### ISSUE TITLE
Change Message: Running LuckPerms v5.0.x

### ISSUE THREAD

**Issue by Martin-Hausleitner** [lucko/LuckPerms#2196]
![image](https://user-images.githubusercontent.com/55828102/79644986-b89ee300-81ac-11ea-9529-a07c7989fc1f.png)

Please let me change this message or if a player with no perms type /lp the bukkit no permssion messsage comes

**Comment by Andre601** [comment]
Luck already answered this in #2190 

> Yeah these messages aren't configurable - the name of the plugin & the version aren't locale dependant.

**Comment by BrainStone** [comment]
I've also yet to see the issue with that message being non changable
