### ISSUE TITLE
"Child" permissions

### ISSUE THREAD

**Issue by punchinglikes** [lucko/LuckPerms#2198]
Everything about parent seems a little buggy. I have a prefix on each group set, but when I set default as a parent so I can have the same permission + some, the default overwrites the prefix and I cannot seem to change it to operate more like a child, or to have the prefix have a higher weight then the default one. doing /lp user (username) meta info, I can see that default is taking full priority when I do not want that and there does not seem to be any way to change it. Please correct me if I am wrong.

**Comment by benwoo1110** [comment]
https://github.com/lucko/LuckPerms/wiki/Prefixes,-Suffixes-&-Meta

make sure you are setting weight for your groups and prefix correctly, `weight.WEIGHT` and `prefix.WEIGHT.PREFIX`

the higher the weight the perms and prefix will take priority.

**Comment by punchinglikes** [comment]
> prefix.WEIGHT.PREFIX
thank you, I did not notice and I could not find a guide for it anywhere.
