### ISSUE TITLE
How to change language, prefix and all the displaying message ?

### ISSUE THREAD

**Issue by Seeyko** [lucko/LuckPerms#220]
Hello lucko !
I manage a french server and i use your permission plugin. i bloqued all the commands and all the way to see the plugins use on my server (in order to not beeing copy). 
So the player can't see that i use luckperms or other plugins. But if a players use /luckperms (i don't know why because he can't even know that i have this plugin but why not, one day it will happens)
so if i use this, it's running a message error LP Running LuckPerms 3.X.X
I want to disable this message and change all the En_US.yml file but how i can do this ? 
I mean, i got it from the source code, how to implement it to the already running plugin on my server ? 
And if you things that i want to simply attribute the plugins to myself in changing prefix luckperms to "SeeykoPerms" or i don't know what don't worry, when a player do a command, it returns him a message and tell him that if he wan't to know what plugins the server use he can contact the administrator and we will tell him.

Thanks you for reading this ! 

Have a nice day !

**Comment by lucko** [comment]
You can change most messages using locale files, following this brief guide.
https://github.com/lucko/LuckPerms/wiki/Locale-and-Translations
