### ISSUE TITLE
Connection error with mysql help (MariaDB)

### ISSUE THREAD

**Issue by TheKingHackYT7** [lucko/LuckPerms#2200]
Hello, I have an error with the plugin, related to the database, basically it doesn't connect, check the plugin's github and it said it would change some things in mysql, but everything is default and I don't know what else to do. do, so here I leave the console log, if you can help me it would be great (I use MariaDB) with pterodactyl panel
https://pastebin.com/NVXw6NiQ

**Comment by BrainStone** [comment]
``127.0.0.1`` targets the docker container, not the host computer. Use ``172.18.0.1`` instead. If that doesn't work reach out to the Ptero Discord. LP not being able to reach the database is not a LP issue.

**Comment by TheKingHackYT7** [comment]
It did not work thank you very much for the help anyway, I will try to contact the ptero support, a pleasure
