### ISSUE TITLE
Bungeecord luckperms

### ISSUE THREAD

**Issue by aliengameer** [lucko/LuckPerms#2202]
When i put bungeecord luckperms in my bungeecord plugins folder it only makes a lib folder nothing else not a config file or anything else. I also downloaded luckperms on my other server connected to bungeecord. Please help

**Comment by Andre601** [comment]
We can't help without some actual information to begin with.

You should provide
- The version and type of Proxy you use ("Latest" does not count)
- The version of LuckPerms Bungee ("Latest does not count)
- Any possible errors in the BungeeCord console (Use https://hasteb.in for sharing those)
