### ISSUE TITLE
MySQL: SSL warning despite useSSL=false

### ISSUE THREAD

**Issue by Picajoluna** [lucko/LuckPerms#2203]
Hello,

I'm trying to set up LP with a **locally** hosted MySQL db.
Everything works -- the permissions data is correctly stored in the database.
I seem to be running into a persistent/spammy (and somewhat annoying) console warning. This warning is flashed ~10 consecutive times at boot, and every 10-20 minutes:

```
[18:15:51 WARN]: Mon Apr 20 18:15:51 UTC 2020 WARN: Establishing SSL connection without 
server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ 
requirements SSL connection must be established by default if explicit option isn't set. For 
compliance with existing applications not using SSL the verifyServerCertificate property is set to 
'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and 
provide truststore for server certificate verification.
```

To access the db, I created a mysql user with an associated password, and granted it all privileges.

Here's my config file, where I have in fact set `useSSL=false`:
```yml
137     # By default, the following options are set to enable utf8 encoding. (you may need to remove
138     # these if you are using PostgreSQL)
139     #   useUnicode: true
140     #   characterEncoding: utf8
141     #
142     # You can also use this section to disable SSL connections, by setting:
143     useSSL: false
144     verifyServerCertificate: false
145     properties:
146       useUnicode: true
147       characterEncoding: utf8
```

When I [look up](https://stackoverflow.com/questions/34189756/warning-about-ssl-connection-when-connecting-to-mysql-database) the issue, it seems that using `useSSL=false` should fix the issue, yet it has not for me this far. Anyone know what the problem might be? Thanks :pray:

**Comment by benwoo1110** [comment]
it should be:
```
    properties:
      useUnicode: true
      characterEncoding: utf8
      useSSL: false
      verifyServerCertificate: false```

as stated in the wiki here: https://github.com/lucko/LuckPerms/wiki/Storage-system-errors#mysql-ssl-errors

**Comment by Picajoluna** [comment]
Argh my bad. Thanks so much!
