### ISSUE TITLE
LuckPerms BungeeCord no folder creating.

### ISSUE THREAD

**Issue by MeZeOfficial** [lucko/LuckPerms#2205]
So today i have started my bungeecord server and i added it some plugins (LuckPerms for BungeeCord)
i started my servers and luckperms did not made folders and did not started on my server so i wasn't able to use it.
BugeeCord version :1.7.10 - 1.8
LuckPerms Version : LuckPerms-Bungee-5.0.136

**Comment by Andre601** [comment]
The BungeeCord version you mention is not a valid one.

If you want to use BungeeCord, that supports 1.7.10, use [Travertine](https://papermc.io/downloads#Travertine)

**Comment by MeZeOfficial** [comment]
Hi, i have changed my BungeeCord version to the latest (1.8 - 1.15) but it still does the same error

**Comment by Andre601** [comment]
You still don't provide a valid BungeeCord version.

Also... What error? We can't read minds nor see your server console, so you have to actually provide some information to us.
