### ISSUE TITLE
Prefix bug name same color

### ISSUE THREAD

**Issue by Orion81200** [lucko/LuckPerms#2206]
Bug with the user name 
Minecraft : 1.15.2
papermc-1.15.2-b193
![Error](https://user-images.githubusercontent.com/64050499/79813520-306f3800-837c-11ea-8a9b-16866e262180.JPG)

**Comment by Laarryy** [comment]
That's not a bug. You add &r after the prefix to reset formatting, or it carries over

**Comment by Orion81200** [comment]
After [ADM] ?

**Comment by Laarryy** [comment]
After the prefix. I can't tell you if adm is your prefix but it sure looks like it. Try it before asking, maybe?

**Comment by Orion81200** [comment]
Thks a Lot , 2hours on this i feel dumb ^^'
