### ISSUE TITLE
Suffixes and prefixes doesn't work

### ISSUE THREAD

**Issue by MaestroMagnifico** [lucko/LuckPerms#2207]
Hello. My Minecraft version is 1.15.2, I'm using Paper v184. I tried to delete all plugins except LuckPerms to make sure there is no conflicts. There's a group "admin", I tried to add prefix like so:

`/lp group admin meta addprefix 100 "Admin"`

I checked prefix:

`/lp group admin meta info`

It shows that prefix is there. Then I checked myself:

`/lp user MyName parent info`

It shows that I'm in the group "admin" and it's my only group. But there is no prefix in chat. Same thing with suffixes.

**Comment by Turbotailz** [comment]
You need a chat formatting plugin + vault if you want to display the prefixes in chat.

**Comment by Laarryy** [comment]
https://github.com/lucko/LuckPerms/wiki/FAQ

**Comment by MaestroMagnifico** [comment]
Thanks. Now it works.
