### ISSUE TITLE
groups names are all lowercase

### ISSUE THREAD

**Issue by JhueiGitHub** [lucko/LuckPerms#2209]
Hey, I was just wondering if there was a way to add capitals (such as the first letter) to group names so they dont show up all lowercase in scoreboards etc. Its not a problem it just looks untidy so was wondering if there was a fix =D

**Comment by Tobi406** [comment]
Try [setting the displayname](https://github.com/lucko/LuckPerms/wiki/Command-Usage:-Group#lp-group-group-setdisplayname-name) for that group, you can use uppercase there.

**Comment by JhueiGitHub** [comment]
Tyvm! :D
