### ISSUE TITLE
Add a command parameter to allow you to add temporary permissions.

### ISSUE THREAD

**Issue by xyblues** [lucko/LuckPerms#221]
Hello, sorry for my poor English.
I do not know if you can understand what I mean.

![qdx2 2c 1b ne3e nm96p4g](https://cloud.githubusercontent.com/assets/15712089/24383648/c367370c-1390-11e7-81b0-7463bc3951cf.png)
I run this command twice, I want to give temporary permission for two days.
But it says I already have temporary permission.

So I want to add a command parameter: addtemp

When I use this command to obtain temporary permission to day.
/lp user XYBlue permission addtemp essentials.fly 1d

Once again, I use this command will give me permission to temporarily increase the day

**Comment by lucko** [comment]
Change this config option: https://github.com/lucko/LuckPerms/blob/master/bukkit/src/main/resources/config.yml#L67
