### ISSUE TITLE
Essentials keepinv and keepxp not working when applied to group

### ISSUE THREAD

**Issue by NerdyKyogre** [lucko/LuckPerms#2210]
This could be me being a n00b, but here goes.
I want to give keepInventory to only certain players using the essentials plugin. If I apply the permissions to a user with "/lp user $username permission set essentials.keepinv true" it works fine. But it's a pain to manually apply this to all the users I want individually, so I created a group as follows:

/lp creategroup keepinv

/lp group keepinv permission set essentials.keepinv true

/lp user $username parent add keepinv

And then smited $user to death. User dropped their items as though they didn't have the permission, even though the same permission works when applied to them individually. Increasing the weight of the group didn't help either.

**Comment by benwoo1110** [comment]
the commands should be `/lp user $username parent add keepinv`

**Comment by NerdyKyogre** [comment]
> the commands should be `/lp user $username parent add keepinv`

Apologies, that's what I meant to write. Edited.

Just to make sure I didn't do it wrong initially, I tried that exact command again and the issue still persists.

**Comment by NerdyKyogre** [comment]
Hold on a second, I figured out what I was doing. When I tested this on myself and my alts I was setting user perms to false instead of unsetting them. There's my problem.
