### ISSUE TITLE
Issue with magma

### ISSUE THREAD

**Issue by BP2004** [lucko/LuckPerms#2213]
Hy, I have a Magma server that allows plugins and mods, the problem is that when I install it, it "blocks" all the mods and I don't know if there is a way to allow to use mods. Please help me

**Comment by BrainStone** [comment]
If they are tied to permissions, you can debug that with [verbose](https://github.com/lucko/LuckPerms/wiki/Verbose).

**Comment by BP2004** [comment]
The problem is LP, because as Iam OP I should have all the permissions even the mods, but even I can't use them.

**Comment by BrainStone** [comment]
If magma follows Sponge, then OP is completely disabled when a permissions plugin is installed.

Also if you have permissions explicitly denied in LP, they then override OP.

**Comment by BP2004** [comment]
OP works, don't know why I can't use mods. Magma is different from sponge, don't know how it works so I leave you the link: https://magmafoundation.org/

**Comment by Andre601** [comment]
I don't think this really is a bug.
It mentions to be like a Cauldron for 1.12, but nothing more.
If it has an OP system based on Sponge does what you experience happen on purpose.
Other than that is there not much we can do here, as this is a fork/separate jar we barely heard from and it would most likely require an additional implementation of LP specifically for Magma. But seeing how this is currently only for 1.12 is this in my opinion not worth it...

**Comment by BrainStone** [comment]
In any case I don't even know LP could be doing wrong.  
I already suggested you have a look at verbose and see if any permissions are being checked. If not, it's not LP. If there are, you need to give them.

In any case all this not covered by LP support (specific permissions are nothing we can help you with, as they are defined by the plugins (and mods) themselves). I'd suggest you reach out to Magma support.

**Comment by BP2004** [comment]
All right thank you
