### ISSUE TITLE
BungeeCord Network Error

### ISSUE THREAD

**Issue by rustysbro** [lucko/LuckPerms#2214]
In previous issues it says that putting the server into offline mode caused this error however you can't do this for a bunge network since setup requires offline mode.

https://pastebin.com/9uD34tQ1

**Comment by Laarryy** [comment]
You put the spigot/paper servers into offline mode and set `ip-forwarding` as well as `bungee-online-mode` to true in the bungee config. Additionally, you set `bungeecord` to true in the spigot.yml files of all non-bungee servers and if you're running paper also turn on the bungee settings in the paper.yml files.

**Comment by rustysbro** [comment]
That is not an option in my paper.yml it works in my proxy but not any of my lobby servers I am running 1.8.8 this is the error I get (proxy) https://pastebin.com/BaLyTZH3 and this is my paper config  https://pastebin.com/eG6eABkw (Lobby)

**Comment by Andre601** [comment]
The bungeecord option is in the **spigot.yml** and not the paper.yml

**Comment by rustysbro** [comment]
The bungeecord option is enabled if anyone has discord I'll screenshare my config files I need to get this fixed asap

**Comment by Laarryy** [comment]
https://discord.gg/luckperms
