### ISSUE TITLE
Add an option to "copy" a permission's duration and use that duration in another permission

### ISSUE THREAD

**Issue by 02Miki** [lucko/LuckPerms#2217]
Allow placeholders to be parsed inside /lp commands, for example:
/lp u %player% perm set (etc)

Also possibly, add a placeholder similar to %luckperms_expiry_time_<perm>% but that can actually be used in these /lp commands (rn it parses the date with spaces, like 1d 5h 50m), but the command needs it without spaces

Thank you!

**Comment by Andre601** [comment]
Handling placeholders is not LPs job but whatever plugin might wanna use the command itself.
So you better request it from the dev of the plugin, where you want to use it.
There is no reason for LP to actually handle placeholders, especially when it serves multiple platforms from which some do not use the same plugin (i.e. PlaceholderAPI)

**Comment by Laarryy** [comment]
There is one space where it could use placeholder support, and that is in player-run commands for dates that use an unknown (pre-set) specific date. That way, you don't have to be checking and counting the seconds to apply another permission with the same end time. I do agree that the easiest way is to do the command through a plugin which parses and runs them, but even in that case the `date to expiry` placeholder needs to have an alternative with the spaces removed so LP can read the whole date once it's parsed.

**Comment by BrainStone** [comment]
I feel like this is a classic case of the [XY Problem](http://xyproblem.info/).

What's your use case? What do you want to use this for?

**Comment by 02Miki** [comment]
We had a chat about it on discord, I need to check for a date & time of a permission, and give the same duration to another permission (the 2 perms don't get set at the same time, so the 1st could've been set 1 month ago)

**Comment by BrainStone** [comment]
So in short you don't want placeholders, you just want to be able to give a second permission that copies the expiry time another permission has?

A little tip for the future: When making feature proposals make cleary *why* you want something. Or better even just ask for something to satisfy your use case and if you have a proposal on how to achieve that, explain that too ;)

**Comment by BrainStone** [comment]
Much better ;)

**Comment by lucko** [comment]
Sorry, this is out of scope for inclusion in the main plugin. 

Perhaps you could achieve a similar effect with a plugin which lets you inject placeholders into commands (this would be trivial for PlaceholderAPI to add, if it doesn't exist already)
