### ISSUE TITLE
[Sponge-3.0.65] Error with adding groups to track

### ISSUE THREAD

**Issue by Nerokinkage** [lucko/LuckPerms#222]
I am having issues trying to add groups to tracks and I keep receiving this error when doing so. 
https://pastebin.com/9jHyrjNw

**Comment by AlexMason** [comment]
Can verify I am getting this error as well.  SpongeForge v2255, LuckPerms 3.0.65

**Comment by Nerokinkage** [comment]
Oh, forgot to include that I was using json file storage and forge...
