### ISSUE TITLE
Luck perms isnt showing the prefix.

### ISSUE THREAD

**Issue by Juliaria08** [lucko/LuckPerms#2220]
# I have instaled this plugins
![image](https://user-images.githubusercontent.com/54623995/80215892-87576480-863d-11ea-9dda-6596b7f3e3ed.png)
![image](https://user-images.githubusercontent.com/54623995/80216181-f634bd80-863d-11ea-9b43-9be441016cf8.png)

**Comment by benwoo1110** [comment]
Are you in owner's rank? What is the ourput of `/lp user USER info` ?

do read this as well: https://github.com/lucko/LuckPerms/wiki/FAQ#why-are-prefixessuffixes-not-working

**Comment by Juliaria08** [comment]
![image](https://user-images.githubusercontent.com/54623995/80218502-89bbbd80-8641-11ea-87d8-f5a6f2c87220.png)

**Comment by Juliaria08** [comment]
F

**Comment by Juliaria08** [comment]
Correct the setting on esentials

**Comment by Juliaria08** [comment]
Thanks

**Comment by Juliaria08** [comment]
@benwoo1110 Thanks for the wiki
