### ISSUE TITLE
Promote to specific group on a track

### ISSUE THREAD

**Issue by FazzyPlayzMc** [lucko/LuckPerms#2221]
Hey i want to promote a person to a specific group on a track but don't want to do /lpb user {user} promote staff over and over again until the rank comes, how do i do it? is there a command like /lpb user {user} promote staff owner?

**Comment by benwoo1110** [comment]
You can just `/lpb user {user} parent add {group}` if you want to promote directly to a higher rank

**Comment by FazzyPlayzMc** [comment]
but then the previous rank perms wont be added to the person would it?

**Comment by benwoo1110** [comment]
you should set group inheritance.

![inheritence](https://user-images.githubusercontent.com/30431861/80219746-7b879480-8675-11ea-84c6-b33295a53a93.PNG)

**Comment by FazzyPlayzMc** [comment]
Ill check it out

**Comment by FazzyPlayzMc** [comment]
If i set "Default" as the parent of "Owner" owner rank will get perms from the default rank am i right?

**Comment by Andre601** [comment]
Yes.
Making default the parent of Owner will give Owner all permissions of default (And if default has any parents themself, also the perms of those)

**Comment by FazzyPlayzMc** [comment]
Ahh thank you :D i will close this now!
