### ISSUE TITLE
List indirectly inherited permissions

### ISSUE THREAD

**Issue by avi12** [lucko/LuckPerms#2227]
When I want to list the permissions of a user/group, I'm only getting the permissions they're inheriting directly, but not via inheritance of other groups.
E.g.
```
/lp user <user> permission info // Will list the permissions the user is directly inheriting
```
If I do:
```
/lp user <user> parent add <parent>
/lp user <user> permission info // Will still list the permissions the user is directly inheriting,
but not the ones that are inherited from the group
```

**Comment by OmegaWeaponDev** [comment]
That is how the command is suppose to work. If you're wanting to check if a user/group is inheriting a certain permission you can use the command: https://github.com/lucko/LuckPerms/wiki/Command-Usage:-Permission#lp-usergroup-usergroup-permission-checkinherits-node-context

**Comment by avi12** [comment]
I don't want to check the "if", but the "what"
Listing the permissions of each and every group individually to know what permissions are being inherited in total is a very tedious work

**Comment by avi12** [comment]
Are the developers working to fix this?

**Comment by OmegaWeaponDev** [comment]
Not currently no. You have to wait until you get a rely from Luck about it.

**Comment by lucko** [comment]
> Listing the permissions of each and every group individually to know what permissions are being inherited in total is a very tedious work

Use `/lp tree`

https://github.com/lucko/LuckPerms/wiki/Command-Usage:-General#lp-tree-scope-player

e.g. `/lp tree . lucko`

**Comment by avi12** [comment]
I believe that the average user will mostly want to see the permissions that are inherited directly and the ones inherited from a group

For example:
```
Bob
  Directly inheriting:
    permission-a
  Indirectly:
    group-a
      Permissions:
        permission-b
      Inheriting from:
        group-b: permission-c , permission-d
```
If there's an issue of high CPU usage on the server-side, it's also possible to use the webpage-based tree structure that the `tree` command generates
