### ISSUE TITLE
Pex importations

### ISSUE THREAD

**Issue by Lunatik934** [lucko/LuckPerms#2228]
Hey permissionsex importation don’t work correctly.. all players don’t have their permissions

**Comment by Andre601** [comment]
We can't help with such few info.
But my guess is, that you need to set the groups the player has as default in PEX as parent for default.

LuckPerms has a different handling of default groups

**Comment by OmegaWeaponDev** [comment]
> Hey permissionsex importation don’t work correctly.. all players don’t have their permissions

Hi, without some more information there is little we are able to really do to help. So with the information given, all I can suggest is that you check out this page: https://github.com/lucko/LuckPerms/wiki/Migration

It should help resolve any issues.
