### ISSUE TITLE
luckperms does not download modules

### ISSUE THREAD

**Issue by mat41997** [lucko/LuckPerms#223]
i have this error on hosting enderchest.pl
https://gist.github.com/mat41997/1d3d48761efd279a10bcfbcabe781bf7

on my local pc normaly work
https://gist.github.com/mat41997/6c8f47d9de8db4cee716b4d21b72912a

java 8
Paper-1062
LuckPerms-Bukkit-3.0.65.jar

what is wrong?

**Comment by lucko** [comment]
Your host isn't allowing LP to connect to the internet. Perhaps it only allows certain protocols.

Just copy the contents of the `/lib/` folder on your local PC to the server.

**Comment by mat41997** [comment]
Support enderchest asks me what ip address i get these files. They want to add that address to the firewall

**Comment by lucko** [comment]
`maven.org` and `github.com`.

**Comment by mat41997** [comment]
maven.org not works : O

ok. i use
151.101.16.209 ( repo1.maven.org ) outbound
192.30.253.133 ( github.com ) outbound
and works : )

thx. for the help
