### ISSUE TITLE
Maven central LuckPermsAPI is out of date.

### ISSUE THREAD

**Issue by thinkverse** [lucko/LuckPerms#2230]
I saw that someone made an issue about WorldCalculator (#2119) before but that issue was closed like a month ago but it's still throwing warnings in the newest `5.0.139` version, at least it does for me. The problem is I didn't use to throw any warning before, but my console is filled with:
```log
[LuckPerms] An exception was thrown by me.lucko.luckperms.bukkit.context.WorldCalculator whilst calculating the context of subject CraftPlayer{name=Thinkverse}
java.lang.NoSuchMethodError: net.luckperms.api.context.Context.isValidValue(Ljava/lang/String;)Z
 	at me.lucko.luckperms.bukkit.context.WorldCalculator.calculate(WorldCalculator.java:60)
 	at me.lucko.luckperms.bukkit.context.WorldCalculator.calculate(WorldCalculator.java:47)
```
Every time I log in to the server it throws a warning, every time I run a LuckPerms command it throws a warning, is there a fix for this? Because it seems to bug out my whole server.

I tried regenerating the config files, rebuilding a new `1.15.2` Spigot server, re-downloading LuckPerms `5.0.139`, nothing works, it's getting annoying.

**Comment by thinkverse** [comment]
Any permissions I set don't seem to get persisted either, and this is using a newly generated config, default h2, on a fresh and latest build of Spigot `1.15.2` running the newest LuckPerms `5.0.139`

**Comment by thinkverse** [comment]
I've now tested previous versions of LuckPerms through `5.0.130` -> `5.0.139` and the issue is persistent on all those versions, all of them throw the same exception.
```log
java.lang.NoSuchMethodError: net.luckperms.api.context.Context.isValidValue
```

**Comment by thinkverse** [comment]
It seems the API for LuckPerms on maven central hasn't been updated. 👍

**Comment by OmegaWeaponDev** [comment]
Try installing the legacy api extension and see if it resolves the issue. https://github.com/lucko/LuckPerms/wiki/Upgrading-from-v4-to-v5#installing-the-extension

**Comment by thinkverse** [comment]
I'm running LuckPerms 5 on both the main plugin and the API, the legacy extension is for LuckPerms 4? How's that gonna help when the LuckPerms 5 API is out of date on maven, it hasn't been updated since November.
https://search.maven.org/artifact/net.luckperms/api

**Comment by OmegaWeaponDev** [comment]
Just try installing the extension and see if it works. Some plugins that make use of the LuckpermsAPI have not updated to use the v5 API. If installing it does not fix the issue, then it's an issue with the Luckperms V5 API.

**Comment by thinkverse** [comment]
I'm testing the new API, it's loading directly in from maven, using the `net.luckperms:api:5.0` but sure I'll try it I guess.

**Comment by lucko** [comment]
> java.lang.NoSuchMethodError: net.luckperms.api.context.Context.isValidValue

This error is caused by a plugin shading the LuckPerms API into its jar.

> It seems the API for LuckPerms on maven central hasn't been updated

It only gets updated periodically - this isn't problematic so long as plugins don't shade it, and just allow the LP jar to provide it at runtime.

**Comment by thinkverse** [comment]
Thank you @lucko with that information I noticed I'd missed the `<scope>` in my pom file, thank you for a useful answer. 😄 👍
