### ISSUE TITLE
EssentialsX prefix/suffix issue

### ISSUE THREAD

**Issue by cypher90** [lucko/LuckPerms#2232]
Hi there,

I'm having the issue that the prefix & suffix show up twice. Once from EssentialsX, once from luckperms (as can be seen in the prinscreen below).

![image](https://user-images.githubusercontent.com/19732035/80309225-f1a20d80-87d3-11ea-8018-9d84c5d43938.png)

Is there any way to remove the ones that luckperms attaches so that I can use this essentialsx format:
format: '{SUFFIX}&r {PREFIX}&r {DISPLAYNAME}&r: {MESSAGE}'

**Comment by Andre601** [comment]
This is not an LP issue.
You're using the `{DISPLAYNAME}` placeholder, which contains the (nick)name of the player aswell as the prefix and suffix they might have (See how the A suffix shows at the start and after your name)

You can disable `add-prefix-suffix` (Uncomment it. Can be found near the top of essentials' config.yml) to fix this.

But again: Not an LP issue, so refer to the M.O.S.S. Discord for help with EssentialsX: https://discord.gg/casfFyh

**Comment by cypher90** [comment]
Oh dang, thanks
