### ISSUE TITLE
LuckPermsAPI not working in project

### ISSUE THREAD

**Issue by hamelech2007** [lucko/LuckPerms#2233]
I am trying to create a plugin that can give a rank through a command and I need luckperms api for it but I cant make it work. I've downloaded the jar and used it in the project structure but it doesn't recognize it in the IDE I am using IntelliJ 2020 community edition. I am very new to programming so if someone can help me please do it as detailed as you can. Thank you for any help.

**Comment by Andre601** [comment]
Either use Maven or Gradle for plugin development, because using Jars isn't really good to do.

**Comment by hamelech2007** [comment]
Do i need to put `<dependencies>
    <dependency>
        <groupId>net.luckperms</groupId>
        <artifactId>api</artifactId>
        <version>5.0</version>
        <scope>provided</scope>
    </dependency>
</dependencies>}` In the pom.xml because when I do put it there it shows invalid element found starting with element....

**Comment by Andre601** [comment]
1. Please use code blocks. Inline code is ugly for this.
2. https://github.com/lucko/LuckPerms/wiki/Developer-API#maven

**Comment by hamelech2007** [comment]
it is what i typed exactly but it does not work

**Comment by Andre601** [comment]
Then you made something wrong.
We can't read minds, nor see your PC, so actually provide information

**Comment by hamelech2007** [comment]
Can you tell me what I did wrong?
![1](https://user-images.githubusercontent.com/64367386/80337607-f792ff80-8862-11ea-8e23-dad0857ce36b.png)
![2](https://user-images.githubusercontent.com/64367386/80337610-f8c42c80-8862-11ea-9352-a23df8489ad1.png)

**Comment by hamelech2007** [comment]
```<dependencies>
    <dependency>
        <groupId>net.luckperms</groupId>
        <artifactId>api</artifactId>
        <version>5.0</version>
        <scope>provided</scope>
    </dependency>
</dependencies>

**Comment by Tobi406** [comment]
Sure you don't already have another
```xml
<dependencies>
...
</dependencies>
```?

**Comment by hamelech2007** [comment]
I don't understand

**Comment by Tobi406** [comment]
Can you paste your whole `pom.xml` in https://hasteb.in, but be sure to strike out any passwords (if you have some in there)

**Comment by hamelech2007** [comment]
is there any thing wrong here?

**Comment by Tobi406** [comment]
```
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>me.hamelech2007</groupId>
    <artifactId>Signs</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>Signs</name>

    <description>signs</description>
    <properties>
        <java.version>1.8</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <build>
        <defaultGoal>clean package</defaultGoal>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.7.0</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.1.0</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <createDependencyReducedPom>false</createDependencyReducedPom>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
    </build>

    <repositories>
        <repository>
            <id>spigotmc-repo</id>
            <url>https://hub.spigotmc.org/nexus/content/repositories/snapshots/</url>
        </repository>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/groups/public/</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>org.spigotmc</groupId>
            <artifactId>spigot-api</artifactId>
            <version>1.15.2-R0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
             <groupId>net.luckperms</groupId>
             <artifactId>api</artifactId>
             <version>5.0</version>
             <scope>provided</scope>
        </dependency>
    </dependencies>
</project>
```

Try that

**Comment by hamelech2007** [comment]
it shows a problem with .luckperms

**Comment by hamelech2007** [comment]
when I uploaded the .jar of the api it wont show it in the external libraries as a .jar it shows it as a folder and inside it instead of .java there is .html

**Comment by hamelech2007** [comment]
![3](https://user-images.githubusercontent.com/64367386/80404531-fd6ffb80-88c9-11ea-9bf2-b42d54c6fda1.png)

**Comment by hamelech2007** [comment]
Maybe I am doing everything wrong. Can someone make a step-by-step guide on how to do it in maven

**Comment by BrainStone** [comment]
> Can someone make a step-by-step guide on how to do it in maven

Learn to use maven. This has nothing to do with LuckPerms. Nothing about the LP API is special in terms of usage with Maven (or Gradle for that matter)

**Comment by hamelech2007** [comment]
I use another API in my project and all I had to do is just put the .jar in the project structure and everything worked fine.

**Comment by BrainStone** [comment]
LP should work the same way. I am not sure what you are doing wrong.

**Comment by hamelech2007** [comment]
I am stupid... I've put the wrong .jar. Thank you for anyone who tried  helping me. I'm sorry for wasting your time.
