### ISSUE TITLE
Error spamming console and causing problems: "Exception thrown during asynchronous load"

### ISSUE THREAD

**Issue by BlueSoapTurtle** [lucko/LuckPerms#2235]
Hi
For some reason my server has started spamming an error related to async loads which is caused whenever plugins are checking perms, it seems.
ex: [https://pastebin.com/raw/KMfMNDac](https://pastebin.com/raw/KMfMNDac)
more examples showing it's not just worldguard failing: [https://pastebin.com/raw/6ESHtsk9](https://pastebin.com/raw/6ESHtsk9)
I've been running my server fine and then suddenly yesterday it started happening.
I tried regenerating the config file as well as deleting the libs folder to try and solve it, but with no success. 

Hardware: I9-9900ks, 128GB Ram, SSDs
Luckperms version: 5.0.140
(I was having the error on 4.x as well and upgrading didn't seem to solve it)

**Comment by lucko** [comment]
It's being caused by one of your plugins doing something silly when registering their permissions. I've added a workaround for it in LP tho :)

**Comment by BlueSoapTurtle** [comment]
Hi, thanks! It ended up being the latest Jobs Reborn update causing it, we downgraded and it stopped happening. Thanks for fixing this!
