### ISSUE TITLE
Sponge style wildcard option for other plugins

### ISSUE THREAD

**Issue by BrainStone** [lucko/LuckPerms#2237]
It would be a nice addition if other server platforms could optionally turn on Sponge sytle wildcards. That is useful if you want the permissions to be consistent on networks that use Sponge with other server platforms (like BungeeCord).

**Comment by lucko** [comment]
Ok ok, I get it.. :wink: (duplicate of #1625)

**Comment by BrainStone** [comment]
xD Totally forgot I had it open already.
