### ISSUE TITLE
LuckPerms not Syncing

### ISSUE THREAD

**Issue by garrettpfoy** [lucko/LuckPerms#2239]
Hello! I've coded a Restful API Integration for Minecraft which hooks into Luckperms, however whenever a player joins, one of the ranks aren't displayed until ./lp sync is done, or some sort of query is sent.

I use the following code to set the group:
```
for(String group : groups) {
                if(checkIfRole(group, config)) {
                    Node temp = Node.builder("group." + group)
                            .withContext(DefaultContextKeys.SERVER_KEY, "global")
                            .build();
                    permission.getUserManager().getUser(playerUUID).data().remove(temp);
                }
            }
```

This works as intended, however when it comes down to another set of groups I set, it doesn't update in chat or tag places until sync'd, however they are a part of the group. This is not to do with the chat plugin as we have tested it on different plugins, and both present the same issue.

I save the user via:
`permission.getMessagingService().get().pushUpdate();
            permission.getUserManager().saveUser(permission.getUserManager().getUser(playerUUID));
            permission.getGroupManager().loadAllGroups();`

I am running Luckperms version 5.0.78
Running bungeecord
Not in offline mode

Any help whatsoever would be greatly appreciated!

**Comment by lucko** [comment]
Make sure you're definitely calling `saveUser` after making your modifications.

**Comment by garrettpfoy** [comment]
I've double checked and the save methods I posted above are being run

Additionally I have updated to the newest version and nothing has changed

**Comment by garrettpfoy** [comment]
Can be marked as solved, changed my modification type to InheritanceNode
