### ISSUE TITLE
LuckPerms server consistent crashing

### ISSUE THREAD

**Issue by ArisDraws** [lucko/LuckPerms#2240]
Hi! I have a small 1 GB RAM server which runs the plugins:
Citizens // CompromiseMOTD // EpicRename // EssentialsX set // GUIPlus // HolographicDisplays // LuckPerms // MyCommand // PlaceholderAPI // Vault // WorldEdit

Every few hours or so, the server will crash with the same console log: https://pastebin.com/QTesyDcs

It repeats luckperms-scheduler-worker-(random number)
I'm running PaperSpigot 1.15.2

Any help to solve the issue would be greatly appreciated!
Thank you!
Have a nice day!

**Comment by Laarryy** [comment]
While it says luckperms in the thread dump, the first section that says (look for plugins here) is the important part. It's probably a lack of RAM, and definitely not luckperms causing it.

**Comment by ArisDraws** [comment]
> While it says luckperms in the thread dump, the first section that says (look for plugins here) is the important part. It's probably a lack of RAM, and definitely not luckperms causing it.

Oh alright, I'll be sure to upgrade soon! Thank you!!
