### ISSUE TITLE
I can´t put command blocks

### ISSUE THREAD

**Issue by JesusLaCo** [lucko/LuckPerms#2244]
Hi, I have a server with Luckperms and Nucleus; I´m already op but I can´t put a command block; what should I do?

**Comment by MeZeOfficial** [comment]
I know im not supposed to respond but maybe that in your server config commablocks are not allowed

**Comment by Laarryy** [comment]
This issue has been resolved in the LP discord. It was the fact that OP doesn't do much when a permissions system is used on sponge. The node `*` allowed for command block placement
