### ISSUE TITLE
Missing a File yaml.storage

### ISSUE THREAD

**Issue by PrankWars** [lucko/LuckPerms#2245]
Whenever I install LuckPerms onto my server, I am missing a file compared to a friends server who has the same plugin. In missing this file, it makes it so whenever I make a new group it doesn't seem to actually make it or store the data anywhere. Whenever I do it on the /lp editor website it still doesn't seem to connect with the server. I tried to create the folders and files myself but it didn't seem to read them.

**Comment by Laarryy** [comment]
By default, the file where groups and permissions are stored is an h2 file. Hop on to the discord at https://discord.gg/luckperms and we can sort it out real quick :)

**Comment by lucko** [comment]
Sounds like filesystem permission errors on your host if the files aren't being created automatically.

You can check in console - there should be some more descriptive error messages there if that's the case.
