### ISSUE TITLE
no tp permission - but has the permission

### ISSUE THREAD

**Issue by Akorian** [lucko/LuckPerms#2246]
Every player from Builder upwards should be able to use tp commands. But they aren't. I have set the tp permissions and the players are in the correct groups. 

![image](https://user-images.githubusercontent.com/37375458/80756653-38289c80-8b33-11ea-8743-f818668b4f20.png)

**Comment by Andre601** [comment]
1. Don't use *.
In cases like essentials would this give access to all TP-related commands including but not limited to: Teleporting others, forcefully teleporting, bypassing any TPA requests.
2. Players need `essentials.tp` to be set to access the TP commands.
3. If the issue persists with higher groups, make sure they inherit from the builder group.

**Comment by benwoo1110** [comment]
Another thing to note is:
1. essentials overrides default minecraft teleport commands.
2. Check that you have set up your group weights as well: https://github.com/lucko/LuckPerms/wiki/Weight

**Comment by Akorian** [comment]
I am aware, that the essentials.tp.* gives access to all tp commands. It is only for my builders and upwards. So thats ok.
I have set the weights. And I double checked for conflicting permissions. 
I didn't know, that minecradt perms are overwritten. But that shoudn't be the issue here i think.

**Comment by OmegaWeaponDev** [comment]
You're able to use Verbose which should give you an idea of what is happening. https://github.com/lucko/LuckPerms/wiki/Verbose
