### ISSUE TITLE
Per track permissions not working

### ISSUE THREAD

**Issue by Krokogator** [lucko/LuckPerms#2248]
I wanted to set permission for track promotion only for certain groups just like here:
https://github.com/lucko/LuckPerms/wiki/Argument-based-command-permissions#for-sponge-and-spigot

i have track "administracja" with groups:

default -> mod -> admin -> owner

luckperms.user.promote  -  true
luckperms.user.promote.administracja.(admin|owner)  -  false

(same for demote)

Unfortunately it doesn't work, with those permissions I can still promote past admin and owner. I also tried setting all permissions (just like in example) and also setting up this permission:
luckperms.user.promote.administracja.(admin|owner)  -  false

in a group with higher weight

**Comment by BrainStone** [comment]
Did you enable ``argument-based-permissions`` in the LP config?

**Comment by Krokogator** [comment]
OMG ! I missed it. Yes it works now, i had to include all permissions from example.
Thank you!

**Comment by BrainStone** [comment]
I mean it says so on the page (for both things). But I'm glad it's working now.
