### ISSUE TITLE
Suggestion : Add command to give the remaining time for a permission

### ISSUE THREAD

**Issue by anxic** [lucko/LuckPerms#2249]
Hi,

I would like to suggest a command that allow user to check the remaining time for a temporary permission.

Currently the only way to know the remaining time for a permission is by:
lp user ... info
lp user ... editor

When we use the commande lp user ... check permission, it's just give the status of permission if it's enabled, unset or disabled.

I would like to inform my user the number of day, that they still have access to a command. The only way I know from today is to use the information from database and show it on my website.

It will be easier for player if they can write a command like
lp permissiontmp <permission name> time
lp grouptmp <group name> time

To inform exactly the time left for that permission / group.

Thanks for reading

**Comment by OmegaWeaponDev** [comment]
While I do agree it would be good to have a specific command to check the remaining time. You can also use the `%luckperms_expiry_time_<permission>%` placeholder which will return the time remaining.

**Comment by lucko** [comment]
The placeholder is your best bet :)
