### ISSUE TITLE
Issue with adding prefix

### ISSUE THREAD

**Issue by mike40376** [lucko/LuckPerms#225]
I'm trying to add a prefix to a group but when it says the prefix is added it doesn't actually work. When a person from that group chats the prefix does not appear. I've tried clearing and adding it multiple times but it still wouldn't work.

**Comment by lucko** [comment]
You need to use a supported chat formatting plugin.

See here: https://github.com/lucko/LuckPerms/wiki/Prefixes,-Suffixes-&-Meta#displaying-prefixes-and-suffixes
