### ISSUE TITLE
Command Blocks giving 2 items instead of 1

### ISSUE THREAD

**Issue by Elrze** [lucko/LuckPerms#2250]
We are making an amusement park style server, and we would love to use LuckPerms. However, when it is installed in the server, even without any permissions added, anyone who is not /op on the server receives 2 items instead of 1. Here is an example command for giving an item:

/minecraft:give @ a[level=1,x=-36,y=65,z=439,distance=..2] minecraft:nether_brick

(we use levels to make sure the ride is actually ridden, and the levels are removed at the same time as the item is recieved)

Any help would be great!

(edit: put a space between @ and a, because it looked like it was marking someone's profile)

**Comment by Andre601** [comment]
LP is not responsible for these commands

**Comment by Elrze** [comment]
So LP, a minecraft plugin, isn't responsible for LP not working with a minecraft command?
Sounds pretty stupid to me.

**Comment by Andre601** [comment]
The command you mentioned is not a LP command at all, so yes it is not in LP responsability to handle it.

**Comment by Elrze** [comment]
Yes it is?

**Comment by Andre601** [comment]
See my updated comment.
LP is **not** a minecraft plugin.
Vanilla Minecraft does **not** run plugins. You use a modded Server like Spigot for this.

And LP handles permissions. Period.
Everything outside of this (chat, handling commands, etc.) is not the job of LP.

Please learn the basics about plugins and modded servers before assuming that a **Permission plugin** would handle everything.

**Comment by Elrze** [comment]
See my updated comment. This is a LP issue, as it is only an issue when LP is installed.

**Comment by Andre601** [comment]
It doesn't matter if LP is installed or not. If a command worked before LP (and especially a vanilla command) then having a perm plugin wouldn't affect it in such a way.

**Comment by Elrze** [comment]
Except it does? Adding LP makes the command not work as intended. Thus it is a problem with LP.

And LP making a vanilla minecraft command function incorrectly is a big problem! You can say all you want that "having a perm plugin wouldn't affect a vanilla command", except it does!. This was the ONLY plugin on the SPIGOT SERVER, and it caused this issue. Thus is it a problem with this plugin.

I came here for help, and all I'm getting is some idiot saying that "adding LP wouldn't change any vanilla commands" which is what I spent all day testing for. Removing plugins, adding them. I made the ONLY plugin on the server LP and it still gave that issue. So you can say "it's not LP's issue" all you want, the proof says otherwise.

**Comment by HgeX** [comment]
This is just nonsense. The vanilla give command works fine on our 1.15 paper server regardless if LP is installed or not.

**Comment by Elrze** [comment]
So instead of giving help, people just come to insult and say "this isn't an issue with LP". Nice community you got here. Almost makes me glad we are unable to use LP.

**Comment by kadenscott** [comment]
You incorrectly said that LuckPerms is causing your issue. When others (who know far more about the plugin than you do) told you it wasn't, you still insisted that LuckPerms was the issue, instead of asking for other possible causes. I think it's quite unreasonable to be upset with the maintainers of this plugin.

Since the vanilla give command works perfectly on my paper 1.15.2 LuckPerms server, it's clearly not the fault of the plugin, rather than your specific server setup.

**Comment by Andre601** [comment]
We provide the information we have.
You use a vanilla command with a command block that can easly be triggered twice.
A perm plugin would not trigger a command twice. It would only deny access to it, when the player lacks permissions. If the player hss the perm, then the command is executable.
LP won't trigger twice.

From the 2,200+ issues is yours the first one reporting this, which is a clear indicator that it isn't LPs fault.

Also, we try to help and be nice here. You're the person calling others idiots for spending time answering questions and such. Your attitude is bad and you should work on it.

Additionally did you not try at all to provide any usable information like your Server type and version, version of LP and what steps you did to reproduce.

**Comment by Elrze** [comment]
The command block isn't being triggered twice. If you had actually read the OP, you would have seen that anyone who isn't opped on the server gets 2 items. Meanwhile anyone who is opped gets 1 item, as intended.

**Comment by kadenscott** [comment]
Now is a great time to "provide any usable information like your Server type and version, version of LP and what steps you did to reproduce."

**Comment by Elrze** [comment]
Paper Spigot 1.15.2
LP 5.0.72
Uninstalled all plugins. Did /deop Elrze. Rode a ride. Received 1 item. Did /op Elrze. Rode the same ride. Also Received 1 item.
Installed LP 5.0.72. Did /deop Elrze. Rode a ride. Received 2 items. Did /op Elrze. Rode the same ride. Received 1 item.

**Comment by lucko** [comment]
Sooo? Did you manage to find the source of the problem?

I'm assuming that you've closed this issue because it wasn't being caused by LP, but please correct me if that's wrong.

**Comment by Elrze** [comment]
I closed it because I received no help. We moved onto another permissions plugin.

**Comment by lucko** [comment]
Sorry, this isn't a 24/7 helpdesk. At least give me a chance to reply... it hadn't even been 24 hours.

I'd like to see the bug resolved so it doesn't affect other users, so would appreciate your cooperation. However if you've given up that's fine too I guess.

**Comment by Bladesteel** [comment]
Of course. 
Doing some more research with the plugins on the server, the issue is caused by both EssentialsXAntibuild and LuckPerms (I thought essentialsX would be fine, as that is what is recommended on the webpage for LuckPerms.. Only when both plugins are on the server does this issue happen. Once I figured this out, I attempted to allow default rank to use command blocks, as well as to use powered rails (setting essentials.build.interact.command_blocks and .powered_rails to true), and that didn't work.

**Comment by Laarryy** [comment]
If you allow them all antibuild permissions (the * wildcard) does it work properly?

**Comment by Laarryy** [comment]
One more thing to try is turning verbose on, and noting exactly which permissions are checked when an OP does the thing and exactly which permissions are checked when a non-OP does the thing. If the op is getting true for a node that comes back as false or undefined for the non-OP, try giving that node to the non-OP group

**Comment by Bladesteel** [comment]
We don't want them to have access to all antibuild permissions. Only wooden (oak) pressure plates, buttons, trapped chests, and ender chests. All permissions are turned off for non-opped people (except the 4 items set to true), and when someone is Opped they have all permissions true.

**Comment by Laarryy** [comment]
I completely understand, but this is likely an issue with a missing permission or something like it, so testing with the user having a wildcard node would be valuable, as it will let us know if it's an op vs non op thing or a missing permission thing

**Comment by Bladesteel** [comment]
Its a missing permission. Having all the permissions permitted gives the single item as expected. I wouldn't know which permission it could be.

**Comment by Laarryy** [comment]
> One more thing to try is turning verbose on, and noting exactly which permissions are checked when an OP does the thing and exactly which permissions are checked when a non-OP does the thing. If the op is getting true for a node that comes back as false or undefined for the non-OP, try giving that node to the non-OP group

This is the next logical step. Compare the permissions checked for an op player to those of a non-OP player

**Comment by Bladesteel** [comment]
Thank you. The issue was that essentials.build.drop.* had to be given. Otherwise the /give command from a command block gives 2 items instead of 1.

**Comment by Laarryy** [comment]
Glad it's resolved!

**Comment by BrainStone** [comment]
That might be worth reporting to EssentialsX btw!

**Comment by BeardedSavage2** [comment]
Where do you correct this in the config?

**Comment by BrainStone** [comment]
It's a permission thing, not a config thing @BeardedSavage2

**Comment by BeardedSavage2** [comment]
So if it’s a permissions issue do you know what I would have to do to fix
this? By chance

**Comment by BNTFryingPan** [comment]
> The issue was that essentials.build.drop.* had to be given. Otherwise the /give command from a command block gives 2 items instead of 1.

what about this is unclear in what is needed to resolve the issue?

**Comment by BeardedSavage2** [comment]
I tried to give that command in luckperms but it doesn’t show up as an
available command in luckperms

**Comment by BNTFryingPan** [comment]
i assume you are referring to the suggestions, which are exactly that. suggestions. you can still type whatever node you want and add it

**Comment by BeardedSavage2** [comment]
Oh okay I was unaware of that. I’m just now learning how to use all these
mods and how to successfully run a server. I apologize for not being
knowledgeable about these things. This is a new adventure Iv kinda thrown
myself into
