### ISSUE TITLE
Make a group for 1 server only

### ISSUE THREAD

**Issue by FazzyPlayzMc** [lucko/LuckPerms#2251]
I have a bungeecord server and i want to create a group for only one of the backend servers instead of having to make it for every server, how do i do it?
I have luckperms bungee setup and running btw

**Comment by Andre601** [comment]
You can't.
Groups are global. You can however assign it to players per server, or set permissions for it per server

**Comment by FazzyPlayzMc** [comment]
Okay, thanks
