### ISSUE TITLE
Kicked for permission data not loaded

### ISSUE THREAD

**Issue by MathieuB59** [lucko/LuckPerms#2252]
Sometimes, when players join the server, there kicked for this reason "doesn't have data pre-loaded, they have never been processed during pre-login in this session. - denying login." §7§l[§b§lL§3§lP§7§l] §cPermissions data for your user was not loaded during the pre-login stage - unable to continue. Please try again later. If you are a server admin, please check the console for any errors.

version lp : 5.0.72
tacospigot

**Comment by Laarryy** [comment]
That's caused by running a cracked server, usually. Either use a better authentication plugin, or make it online-mode: true

**Comment by Laarryy** [comment]
If you don't run a cracked server, try updating to the latest version of LP from https://luckperms.net
