### ISSUE TITLE
uuid issue

### ISSUE THREAD

**Issue by MrFreasy** [lucko/LuckPerms#2253]
Hi, I have a problem with the luckperms plugin installed on the bungeecord server.
When a player tries to enter into the server he is kicked with an error message: ReadTimeoutException: null
And an error message is sent to the console: https://pastebin.com/k9x8ntq8
how can I solve this problem?

Thanks in advance

**Comment by Laarryy** [comment]
That's caused by running a cracked server, usually. Either use a better authentication plugin, or make it online-mode: true. 

If you don't run a cracked server, update to the latest version of LP from https://luckperms.net

**Comment by lucko** [comment]
Most likely ^ - need to see your full bungee log file with the debug-logins config option enabled to know for sure.
