### ISSUE TITLE
server crashes

### ISSUE THREAD

**Issue by oliverjdk** [lucko/LuckPerms#2254]
Log before crash: https://hastebin.com/agumavojul.md

**Comment by Laarryy** [comment]
![Screenshot_20200502-150431](https://user-images.githubusercontent.com/58414982/80892308-4804c580-8c86-11ea-871c-f88b3059eb96.jpg)
This part of the thread dump is what tells you what caused the crash. The rest just says what was also going on. The cause of your crash was a skript/inventory click event error that definitely had nothing to do with LP. I'd take a look at your skript for inventory guis or something like that as the cause of the crash.

**Comment by oliverjdk** [comment]
oh it just said luckperms in the top so though it was that sry :)
