### ISSUE TITLE
MySQL issue

### ISSUE THREAD

**Issue by turbodavid999** [lucko/LuckPerms#2255]
Hello, i have a error of LuckPerms in my network.
When I open the skywars console, the LP leaves me in big error.

` Notes:
- I use PaperSpigot 1.8.8

Link: [hastebin.com/dejonuseno.shell](url)

**Comment by Laarryy** [comment]
Try updating to the latest version from https://luckperms.net

**Comment by turbodavid999** [comment]
@Laarryy Ok, I use the latest version at luckperms.net [5.0.146], but I have a new error, I don't know if it is the same.
[hastebin.com/wizodoralu.shell](url)

**Comment by Laarryy** [comment]
Try deleting LP's config and the `libs` folder, and restart the server. Might help.

**Comment by turbodavid999** [comment]
Well, i did but i have a new error.
[https://hastebin.com/oduyavofak.shell](url)

**Comment by lucko** [comment]
It's the same error. One of your other plugins is improperly shading SLF4J.

I suggest removing plugins methodically to determine which one it is.

Try with LP + half of the rest of your plugins, if issue is fixed, you on the problematic plugin is in the other half, and so on.

**Comment by lucko** [comment]
Oh, seems like it could be PremiumVanish? ^^

Try removing that if you have it.
