### ISSUE TITLE
Adding to Groups

### ISSUE THREAD

**Issue by FireGB** [lucko/LuckPerms#2257]
There doesn't seem to be any kind of option to actually add people to groups. I'm sure there is, but where is it? There's no command for it on the wiki page. I know, it's not really an issue, more a question, I just didn't know how else to contact you.

**Comment by Laarryy** [comment]
The group add commands are synonymous with the parent add/set commands. And `parent` mention refers to group. Also, feel free to join the discord at https://discord.gg/luckperms
