### ISSUE TITLE
Add more time

### ISSUE THREAD

**Issue by Axer22** [lucko/LuckPerms#2258]
I suggest to add possibility to add time for timed permissions and groups. For example, I gave someone permissions for an hour and I want to add one more hour to them in total. I didn't find a command that would allow this thing.

**Comment by Andre601** [comment]
Already a thing.
For example:
[`/lp user Andre_601 permission settemp essentials.fly true 1d accumulate`](https://github.com/lucko/LuckPerms/wiki/Command-Usage:-Permission#lp-usergroup-usergroup-permission-settemp-node-truefalse-duration-temporary-modifier-context)

This will add the provided time to the permission, when it is already set. So f.e. a perm with 1 hour becomes 1 day and 1 hour.
This is explained in detail on the above linked section and applies to any other command for temporary adding/setting something.
