### ISSUE TITLE
Temporary perm.

### ISSUE THREAD

**Issue by crsglobalmusic** [lucko/LuckPerms#2260]
Hello, as knowing already you can:
- 'lp user %Player% permission settemp essentials.fly true 1m'
to another plugin let's say "vouchers" so if they click an item, they will recieve the command /fly for 1min.
After 1min, the player can fly without any problem and also he can't /fly again to disable.

Is there any option to disable the command /fly after the time ?
Is there any luckperms thing to do that or do i need another thing to solve this ?

Thank you in advance.

**Comment by OmegaWeaponDev** [comment]
Luckperms only handles the permission side of things. If you want the fly to be disabled after the permission is removed you'll need another plugin that handles that side of things.

**Comment by crsglobalmusic** [comment]
Thank you sir, can you give me a path to a plugin who does that ?

**Comment by OmegaWeaponDev** [comment]
I'm not sure of one sorry.

**Comment by lucko** [comment]
https://github.com/lucko/fly-permission/
