### ISSUE TITLE
Players can't use perms given to them

### ISSUE THREAD

**Issue by PotatoFart** [lucko/LuckPerms#2265]
I worked with the /lp editor and followed a direct guide that told me how to set up the group and the permission and members still can't access the perm I gave them. The group "member" should have access to essentials.rules but they can't do /rules when in game. I ran the update command it gives you once you hit save in the editor and I've tried restarting the server to see if the changes took effect but nothing happens. The command is marked 'true' in the editor.

**Comment by lucko** [comment]
Maybe you got the permission node wrong.

The verbose command will help to see where things are going wrong.
https://github.com/lucko/LuckPerms/wiki/Verbose
