### ISSUE TITLE
Default rank bug

### ISSUE THREAD

**Issue by RealSounds** [lucko/LuckPerms#2266]
So, I created 
default (It was already there) - vip - god - legend - hyplex - etc. 
and when I move the player to vip or god, it stays in chat the same default, but when you use commands it shows you the group, any ideas why does it happen also the default group doesn't want to change its name. I have already read the text document about default and also I couldn't find the selection about the default settings in the yml. file. Or is it from the chat control or something?

**Comment by Andre601** [comment]
> and when I move the player to vip or god, it stays in chat the same default,

This is most likely a chat issue and not a LP issue. [LP doesn't handle the chat](https://github.com/lucko/LuckPerms/wiki/FAQ#why-are-prefixessuffixes-not-working)

> also the default group doesn't want to change its name. I have already read the text document about default and also I couldn't find the selection about the default settings in the yml. file. Or is it from the chat control or something?

The default assignment - if you mean that with "default settings in the yml" - was removed in version 5 of LP and is only available through a separate extension. This is, however, not recommendet.
You have two alternatives which are [modifying the display name](https://github.com/lucko/LuckPerms/wiki/Default-Groups#keep-using-the-default-group-but-just-modify-the-display-name) or [set up parents for default](https://github.com/lucko/LuckPerms/wiki/Default-Groups#configure-inheritance)
