### ISSUE TITLE
Converting from flatfile to MySQL

### ISSUE THREAD

**Issue by Jacob-Evans** [lucko/LuckPerms#2267]
Hello! I was looking on the wiki and i don't know if i missed it, but i don't see any documentation on moving from 1 storage type to another. What is the process for this?

**Comment by Andre601** [comment]
There is a wiki page literally called [Switching Storage Types & Backups](https://github.com/lucko/LuckPerms/wiki/Switching-storage-types)

**Comment by Jacob-Evans** [comment]
Well, i am blind.
