### ISSUE TITLE
Incompatibility with forked spigot

### ISSUE THREAD

**Issue by kingpolar** [lucko/LuckPerms#2268]
**Note:** This is a follow up to: https://github.com/lucko/LuckPerms/pull/2091 I apologize for making this another issue, please close it if you feel it is not worth your time.

Recently, I noticed the issue of SportPaper not being able to support LuckPerms. I was really hoping to see if there is any news of an upcoming solution? Many servers like mine like to utilize "custom forked spigots" and some use SportPaper as the base making it really frustrating when you find out LuckPerms isn't supported (I really don't want to drop this permissions plugin). Is there any solution to this specific way to add compatibility? I don't mind becoming a pateron to have this feature since its more like a request. Please get back to me on any possible solutions!

**Comment by lucko** [comment]
As you can see from the replies in #2091, the issue is going to be resolved at the SportPaper end. You'd need to talk to the maintainers there for a status update.

**Comment by Electroid** [comment]
For posterity, this is now fixed: https://github.com/Electroid/SportPaper/commit/3d0a5ccef48dee073c3fdbd960eefc54149eb002
