### ISSUE TITLE
CMI Vault message -> could be removed?

### ISSUE THREAD

**Issue by Volgeop** [lucko/LuckPerms#2271]
Hi, could you remove this message when using CMI Vault? I would like to have clear log without warns.

`[LuckPerms] Loaded class net.milkbowl.vault.permission.Permission from Vault v1.7.3-b${env.TRAVIS_BUILD_NUMBER} which is not a depend, softdepend or loadbefore of this plugin`

**Comment by benwoo1110** [comment]
see #1959
