### ISSUE TITLE
Ldap sync?

### ISSUE THREAD

**Issue by Spacelord09** [lucko/LuckPerms#2272]
Hey guys!
Firstly I must thank you for this realy nice permisson plugin!
So let's get back to my question: Can Ldap sync be implementet in near future?

I have a global ldap server for my staff to login to our systems.
This makes the administration effort extremely easy for me and my admins.

**Comment by Laarryy** [comment]
Could you please clarify what you mean by ldap sync? What would you like it to do, (and what is ldap, for the me who doesn't know) and how would you like to have it done?

**Comment by Spacelord09** [comment]
I mean with ldap sync to set permisson based on ldap groups

**Comment by lucko** [comment]
Sorry, this is out of scope for LuckPerms.

**Comment by BrainStone** [comment]
The one big question that remains is how to you link player accounts to LDAP accounts?

**Comment by Spacelord09** [comment]
Thats right @BrainStone!

**Comment by KleinDevDE** [comment]
> The one big question that remains is how to you link player accounts to LDAP accounts?

You can add some extra Infos/fields to LDAP users.
So you can set the UUID of the player.
