### ISSUE TITLE
Crash when i use LuckPerms in server (Sponge-Forge)

### ISSUE THREAD

**Issue by Oxibaros** [lucko/LuckPerms#2274]
Hi, I want to make my server with Sponge-Forge mods and I have a problem with LuckPerms, it crashes the console, tries to connect to some website or something like that, but it doesn’t work out and it crashes the console. Even if nothing happens to remove LuckPerms, even Anvil-Sponge didn’t delete, it didn’t help, another plug-in started complaining. Help, [here is a crashlog](https://hasteb.in/ohebesoc.rb)

**Comment by Andre601** [comment]
The log you provide isn't available.
Please use a proper site to share errors (e.g. https://hasteb.in) and not google drive.

**Comment by Oxibaros** [comment]
I read Crash Log carefully and understand what the problem was, I already fixed it
