### ISSUE TITLE
Slow shutdown on Velocity

### ISSUE THREAD

**Issue by jordanamr** [lucko/LuckPerms#2275]
Hello, I have noticed that the plugin takes a very long time to shutdown on Velocity (I tested with versions 1.0.5 and 1.0.8 of velocity, and build 151 of LuckPerms). It can take up to 1 minute to shutdown
MariaDB storage, Redis messaging, everything else is default settings.

Issue does not happen on BungeeCord with the same settings

**Comment by BrainStone** [comment]
How long is very long?

**Comment by jordanamr** [comment]
> How long is very long?

"It can take up to 1 minute to shutdown"

**Comment by BrainStone** [comment]
I should stop responding to issues when I’m half asleep. My apologies.

**Comment by lucko** [comment]
Could you try generating a thread dump while it's hanging?

If you're on unix, you can use `jps` to get a list of the Java process pids. Identify which process is your Velocity instance, then run `jstack <pid>`.
