### ISSUE TITLE
How do i use lpb on the console?

### ISSUE THREAD

**Issue by FazzyPlayzMc** [lucko/LuckPerms#2276]
Title asks it all, i need to run /lpb on the console, is there a way?

**Comment by Laarryy** [comment]
Yes, if you're in the proxy console, just dont use a `/`

**Comment by FazzyPlayzMc** [comment]
It should actually be in the backend server

**Comment by FazzyPlayzMc** [comment]
So is there a way from the backend to run it?

**Comment by Turbotailz** [comment]
`/lpb` is a bungeecord command, so you have to use it on the bungee console or in game.

It sounds like you may have mistaken the bungee version of LuckPerms as a solution for your whole network when you actually need to install LuckPerms on every server.

**Comment by Turbotailz** [comment]
Read this for more info about installing on a network:
https://github.com/lucko/LuckPerms/wiki/Network-Installation

**Comment by FazzyPlayzMc** [comment]
I have luckperms on everyserver, and i want to give players a rank using the console so i can do "lpb user {user} parent set {group} in the console instead of doing lp because i dont think lp syncs ranks

**Comment by FazzyPlayzMc** [comment]
I have read that already and have setup luckperms bungeecord properly

**Comment by Turbotailz** [comment]
Then you need to figure out why it's not syncing. It shouldn't matter whether you use `/lp` or `/lpb` to modify the database if it's all connected properly.

**Comment by FazzyPlayzMc** [comment]
Hmm okay

**Comment by Turbotailz** [comment]
Feel free to jump in the discord to get quicker help.

**Comment by Laarryy** [comment]
See this link https://github.com/lucko/LuckPerms/wiki/Syncing-data-between-servers

**Comment by FazzyPlayzMc** [comment]
nvm i figured it out

**Comment by BrainStone** [comment]
It is common curtesy to explain your solution if you found one yourself.  
So other people stumbling upon this can have their issue solved too. Also so support people know what’s going on so they can help others better.
