### ISSUE TITLE
Luckperms just isnt working.

### ISSUE THREAD

**Issue by galaxyy9** [lucko/LuckPerms#2278]
i downloaded luckperms and when i run /plugins on my minecraft server it shows luckperms there. it says to do /luckperms but when i do that it says nothing at all. it doesnt say unknown command or anything it just does nothing

**Comment by Andre601** [comment]
Then you might do something wrong?
Double-check you installed the right version of LuckPerms. If it shows red in /plugins (On spigot) then there was an issue enabling LP and you should check the console for any errors.

Other than that is the information you provide really not useful and since we can't see your Server-setup can we also not help.

**Comment by galaxyy9** [comment]
it was red when i did /plugins and i checked the console and it didnt say anything at all about luckperms except when i did /luckperms. i put it in a google doc and did ctrl+h to search it and i searched for the word error and the word luckperms i dont know how to fix it.

**Comment by Laarryy** [comment]
Use https://hasteb.in - paste the entire console into it, upload it, and send the link it generates.

**Comment by galaxyy9** [comment]
https://hasteb.in/joxasaho.md

**Comment by Andre601** [comment]
That doesn't show anything about LuckPerms.
We need a log from when you had LP installed.

**Comment by galaxyy9** [comment]
i still do have luckperms installed. https://imgur.com/a/O0cT2iS i dont know why its doing nothing

**Comment by benwoo1110** [comment]
1. send the full server startup from start to done!
2. show us a screenshot of `lp info` ran from **console**

**Comment by galaxyy9** [comment]
https://hasteb.in/fipowino.md
is the startup.

https://drive.google.com/file/d/1dq619BdGELNE4fAEWlixmJsoJVSzWGRr/view?usp=sharing
and here is a link showing a video of what happens when i do lp info in console. i do have luckperms in the plugins and it shows up in red when i do /plugins.

**Comment by Turbotailz** [comment]
That doesn't look like a full startup log.

**Comment by benwoo1110** [comment]
> That doesn't look like a full startup log.

Unfortunately, as Turbo said, its not the full server log. 

1. Restart your server fully.
2. Go into your server files and get `./yourserver/logs/latest.log` and send us the full contents in it via https://hasteb.in/

**Comment by lucko** [comment]
I'm gonna take a wild guess that you probably want the legacy Bukkit version.

But the console message will tell you that anyway if you read it :)

**Comment by galaxyy9** [comment]
ok so it says the problem in there sorry i didnt know. im bad at this :/
https://hasteb.in/icegasej.md

**Comment by SpooksxAce-op** [comment]
Mine just says the version every time I do /lp help or any command

**Comment by Laarryy** [comment]
@SpooksxAce-op that's because you need to follow this guide carefully: https://luckperms.net/wiki/Usage

In future, do not reply to closed issues and ask trivial support questions in the LP discord if possible, at https://discord.gg/luckperms

Thanks
