### ISSUE TITLE
Suffix isn't showing,

### ISSUE THREAD

**Issue by Tonyism8669** [lucko/LuckPerms#2279]
https://gyazo.com/0525d9f13af045dfd797ad1e0855a43d
https://gyazo.com/bda74e7ee6b267a29cd7fffa96728acd
https://gyazo.com/a33a74d570ef75cd7df6aac2d2440890
https://gyazo.com/7afa9105cc7e376cd08eddb91cb2c993
https://gyazo.com/faefa9eb7db50d60cc2797062f52f1e7
https://gyazo.com/fb98cb634e30074e7c15e21e7639dec4
https://gyazo.com/6b9725666cf97137760f5e173220c112

The problem is everything below builder isn't showing it's prefix, I just updated LuckPerms to and I still have the same issue.

**Comment by Laarryy** [comment]
It's the prefix :P

Also, the prefix is showing in `lp user <user> meta info` as well as `lp group vip++ meta info` but not `lp user <user> info` - I'm at a loss, any help would be appreciated

**Comment by Tonyism8669** [comment]
Fuck I always get suffix and prefix mixed up lol.

**Comment by lucko** [comment]
Can you pastebin your LP config please.

All I can think of is you've changed the meta stacking settings or something like that by mistake.

**Comment by Tonyism8669** [comment]
https://pastebin.com/5y29eu3V

**Comment by Laarryy** [comment]
Is VIP++ on any of the three tracks you have set in your meta formatting section? If it's not, try adding it to one of the three. I noticed that you have three tracks in the meta formatting section but only two in the editor. Make sure you add it to a track that is the same name as one in your config.

If that doesn't convince it to show up, let us know.

**Comment by Tonyism8669** [comment]
Hello, I found the issue. My track had another name then the config, thanks for helping out the problem!

**Comment by Tonyism8669** [comment]
It went back to the same thing now, same problem.

**Comment by Laarryy** [comment]
Then I'm sorry to say it but there's a really good chance it's the same solution

**Comment by Tonyism8669** [comment]
When I change to it it says test before the name of the player.

**Comment by Tonyism8669** [comment]
https://editor.luckperms.net/GbacUMAN0R the same solution isn't working anymore for some reason.

**Comment by Laarryy** [comment]
It says test because that is a prefix that is set. 

This is not a Luckperms issue, you just need to go through everything and ensure that it's set up properly. If something isn't showing correctly, it because it isn't set correctly 

https://i.imgur.com/9zprDHh.png
