### ISSUE TITLE
In-game console not printing properly

### ISSUE THREAD

**Issue by Yavin7** [lucko/LuckPerms#228]
When in game, using any /luckperms command return '[L' per line for however many lines ought to be printed.  When I run the command in console, the command runs like normal.  I'm running on FTB Beyond 1.3.0 server with spongeforge 5.2.0 and minecraft 1.10.2
![luckperms](https://cloud.githubusercontent.com/assets/12129571/24596730/b48ce702-1806-11e7-9f3d-24f8a6a81097.png)
![2017-04-03_00 41 39](https://cloud.githubusercontent.com/assets/12129571/24596742/d5738570-1806-11e7-8e3c-6880e7018f22.png)

**Comment by lucko** [comment]
Which LP version?

**Comment by Yavin7** [comment]
filename: LuckPerms-Sponge-3.0.71.jar
it looks like the most recent version is .74, will update and and check to see if the problem persists.

**Comment by Yavin7** [comment]
updated and same problem persists.
list of sponge plugins: 
   - SpongeForge v2254-5.2.0-BETA-2262
   - Nucleus v 0.27.0
   - Nucleus Mixins v 0.25.2
   - WorldEdit forge v mc1.10.2-6.1.4-dist
   - FAWE v (unknown)

I've not changed the modpack in any other way and am updating sponge to see if that helps

**Comment by Yavin7** [comment]
Updating sponge had no effect on the issue.

**Comment by lucko** [comment]
Running:
* Forge 1.10.2-12.18.3.2254
* SpongeForge 1.10.2-2254-5.2.0-BETA-2262
* LP 3.0.74

![](http://i.imgur.com/2BI9DvV.png)

So, by guess is it's an issue with your client or another plugin/mod which is messing with packets.

**Comment by Yavin7** [comment]
Ok, will do a check to see if i can figure it out and let you know what I find out. (time to start removing plugings)

**Comment by Yavin7** [comment]
Found it out.  It's a mod in the pack called ChatFlow that was reading [LP] as a regex expression and deleting everything that came after i guess, I'm looking into changing the config to make it work.  (This will be interesting because I've never used regex).

Am closing the issue regardless, as it's not a bug.
