### ISSUE TITLE
MySQL Error

### ISSUE THREAD

**Issue by Saymoan** [lucko/LuckPerms#2286]
When attempting to connect my LuckPerms on a 1.8.8 Spigot server to a MySQL database so that I can have shared permissions throughout my network, I am getting this error https://hastebin.com/owekogoziy.apache

I've got LuckPerms running on a Bungee server and a 1.12.2 Spigot server and I've been having no problems whatsoever.

**Solutions I've tried:**
Using PaperSpigot 1.8.8
Deleting the libs folder
Using the latest version from SpigotMC
Using the latest version from luckperms.net
Using the latest legacy version
Using a different MySQL database

All the servers are using the same version of LuckPerms and none of the troubleshooting steps had any effect on my issues

**Comment by lucko** [comment]
Are you using PremiumVanish by any chance?

**Comment by lucko** [comment]
Seems related to #2285 and #2255

**Comment by Saymoan** [comment]
Nope. No PremiumVanish. Would you like a plugin list?

**Comment by lucko** [comment]
Yes please.

**Comment by Saymoan** [comment]
https://cdn.discordapp.com/attachments/706513958370279474/709187082547101727/Screen_Shot_2020-05-10_at_5.35.39_PM.png
Sorry for the non-alphabetical list and it being a screenshot. Console wont let me run /pl for some reason

**Comment by lucko** [comment]
Can you try with this jar.


https://cdn.discordapp.com/attachments/357229422614544415/709192653991968878/LuckPerms-Bukkit-5.1.3.jar

**Comment by Saymoan** [comment]
Doesn't seem to have made any changes. Here is my latest.log also https://hastebin.com/goxabuqoyu.makefile

**Comment by lucko** [comment]
Nope that's perfect.

I added some extra logging:

```
[19:59:50] [Server thread/INFO]: org.slf4j.LoggerFactory is provided by BCommons
[19:59:50] [Server thread/INFO]: org.apache.logging.slf4j.Log4jLoggerFactory is provided by StaffPlus
[19:59:50] [Server thread/INFO]: org.apache.logging.log4j.spi.AbstractLoggerAdapter is provided by StaffPlus
```

You have different plugins trying to load different versions of SLF4J and Log4J (these are logging libraries).

Seems like either `StaffPlus` or `BCommons` is at fault here.

Unfortunately I don't actually think there's anything I can do to work around the problem in LuckPerms. (I was hoping there would be)

**Comment by Saymoan** [comment]
So in theory removing one or both of these plugins should fix the issue? I'll give it a try and let you know if it helps at all!

**Comment by lucko** [comment]
It should do yeah.

**Comment by Saymoan** [comment]
It's now working! Guess I'll have to just live without those plugins. I've got no idea why Commons is even installed either. Thanks so much for the help!
