### ISSUE TITLE
[BUG ?] Luckperms take more than a minute to load the mysql database info

### ISSUE THREAD

**Issue by maxlehot1234** [lucko/LuckPerms#2287]
Hi,

Anyway to optimize the load of the LP database?

It take more than 1 minute to load for 800 differents players and 2050 groups

I store everything on a MYSQL database and it take a lot of time to start/restart the server cause of that.

Mysql server was another server.
This my ./lp info results:
https://gist.github.com/maxlehot1234/ffe1e6c1780dfb496d6ced254050dcec

If I setup a server on my computer with LP with the same MYSQL server, it take maximum 1 second to load with another tables. So connection was perfect to the MYSQL server.

If you know a way to optimize the DB, let me know.

If that change anything,
I Have paper-mc build 262
Java 11

Thanks again and have a nice day/night

**Comment by lucko** [comment]
I'm sure it can be optimised, yes.

Question though... 2050 groups??

**Comment by Turbotailz** [comment]
> Question though... 2050 groups??

I had the same reaction lol. It's a prison server.

**Comment by Andre601** [comment]
Best optimisation is to not have 2.5k Groups.
If you have so many groups is it no surprise that it loads that long.

**Comment by maxlehot1234** [comment]
Yeah but using the same MYSQL server on another server on my computer take 1 second to load. So LP was not able to load a lot of groups I think.

But decrease it to 1k group will end up to the same results when more and more players will joined the server

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lucko** [comment]
Should be improved by the above commit, try using v5.1.5.

**Comment by maxlehot1234** [comment]
The LP plugin load in less than 2 seconds instead of 1 minute. INSANE improvement :)

Server took 47 seconds to start instead of 110 seconds+.

Thanks a LOT @lucko

**Comment by lucko** [comment]
Great :)
