### ISSUE TITLE
Suggest: Improve temporary commands

### ISSUE THREAD

**Issue by tuanjr** [lucko/LuckPerms#229]
First of all, my english not good. 
I hope you can understand what i want to said
Can you make an option for duration on temporary commands?
example: player Luck in group Vip and will expirate in 1day, now i want extend vip time for player Luck, but i need to wait 1day for Luck expirate Vip time run out and run this command again: /lp user Luck parent addtemp Vip 30d
But if you add option -a, i don't need wait Luck expirate 1d vip time, just run command with option -a so Vip time will extend more 30day, example: /lp user Luck parent addtemp Vip -a 30d. So now Luck has 31days on Vip group.

**Comment by lucko** [comment]
Already exists.
https://github.com/lucko/LuckPerms/blob/master/bukkit/src/main/resources/config.yml#L67

Change that option to `accumulate`.

**Comment by tuanjr** [comment]
OK, i will look into it.
Can you add option to translate time stamp to another language? (on expension_lucperm placeholder)
i mean Days, hours, minutes, seconds, etc
and option to set null time to another instead of nothing?

**Comment by lucko** [comment]
Ask the PlaceholderAPI dev. It's not my code.
