### ISSUE TITLE
LP wont run on  newer nukkit

### ISSUE THREAD

**Issue by andsim** [lucko/LuckPerms#2290]
getting this error
https://bytebin.lucko.me/BlyhSiVwcx
running 2:29:05 [INFO ] Starting Minecraft: BE server version v1.14.60

**Comment by Laarryy** [comment]
User (without GH account, that's why I'm here haha) reports same problem today 

Full startup log:
https://bytebin.lucko.me/eSPT6C1Qay

**Comment by lucko** [comment]
Should be fixed now :)

Thanks for reporting
