### ISSUE TITLE
Permissions check for offline players causing errors/crashes on proxy

### ISSUE THREAD

**Issue by TheRAPT3X** [lucko/LuckPerms#2291]
Hello. Over the past few days I've been experiencing this error in my waterfall proxy console only and sometimes even proxy crashes. It's the exact same error for each player. 

https://bytebin.lucko.me/aI3QP4LtOv

The odd thing is all the players that are coming up in the error are not online at the time of the error, and in some cases the player has not been online for days. I've spoken to both Turbo and Larry in the discord, and they did not know what could be causing it. It is an online-mode network with the instances running 5.1.10 and the proxy running 5.0.152 (the version that was on luckperms.net under "bungeecord" just last night). I will update to 5.1.15 tonight and reply if the errors occur again. Thanks!

edit: Just read that another player is having the exact same error. I'll change the debug-logins to true and post any updates.

**Comment by lucko** [comment]
If the player definitely is not online, then this is a BungeeChat issue. :)

**Comment by BrainStone** [comment]
Make sure BungeeChat is up to date

**Comment by TheRAPT3X** [comment]
Bungeechat is up to date. I went to the plugin's support discord and they told me it wasn't a bungeechat issue, which is why I went to the luckperms support discord. They never said anything about it being a bungeechat issue.

**Comment by BrainStone** [comment]
You didn't mention that the players it was checking for were offline. Please reach out to me on my Discord again.
