### ISSUE TITLE
Support Question (Primary Group Prefix Placeholder)

### ISSUE THREAD

**Issue by Vehzx** [lucko/LuckPerms#2293]
Hi, I can't seem to find a primary group prefix placeholder, I can see this %primarygroup% placeholder but I need a placeholder that shows the prefix of the group not the group name.

I looked all over for it and can't seem to find it, any help is appreciated.

**Comment by benwoo1110** [comment]
https://github.com/lucko/LuckPerms/wiki/Placeholders

I believe what you are looking for is `%luckperms_primary_group_name%`

**Comment by Vehzx** [comment]
This shows the group name, i'm wondering if there is a placeholder to show the primary group prefix that you enter in the group file.
This: https://i.gyazo.com/9119e18a72d79ad55c1362a5e9ac0c7c.png

**Comment by Laarryy** [comment]
%luckperms_prefix% will show the highest priority prefix, unless you've changed stacking settings in `meta-formatting`

**Comment by Vehzx** [comment]
ty
