### ISSUE TITLE
Error when a player joins

### ISSUE THREAD

**Issue by AbooseYou** [lucko/LuckPerms#2295]
Any reason i am getting this error i have ever tryed resetting the  configs

https://paste.helpch.at/omojowuhuk.md

**Comment by Laarryy** [comment]
Have you changed the contexts *file* in the Luckperms folder?

**Comment by AbooseYou** [comment]
no

**Comment by lucko** [comment]
One of the plugins on your server is incorrectly shading the LuckPerms API.

**Comment by lucko** [comment]
Try removing any plugins you have which depend or hook with LuckPerms and see if that resolves the issue.
