### ISSUE TITLE
Event Handling on BungeeCord and Spigot

### ISSUE THREAD

**Issue by meerpaluten** [lucko/LuckPerms#2297]
I have a BungeeCord and a spigot server, LuckPerms is connected to MongoDB, the messagin is üb he redis. If I change the rank of a player in the BungeeCord, the event will not be executed on the spigot server, but only on the BungeeCord. The same is also the other way around. v5.1.16

**Comment by lucko** [comment]
Make sure you have IP Forwarding setup correctly.

https://github.com/lucko/LuckPerms/wiki/Network-Installation

**Comment by meerpaluten** [comment]
i have setup all for my bungeecord

**Comment by lucko** [comment]
Are they both connected to a MySQL database?

What does `/lp info` and `/lpb info` show?

**Comment by meerpaluten** [comment]
20:42:51 [INFO] [LP] Running LuckPerms v5.1.16 by Luck.
20:42:51 [INFO] [LP] -  Platform: BungeeCord
20:42:51 [INFO] [LP] -  Server Brand: Aegis
20:42:51 [INFO] [LP] -  Server Version:
20:42:51 [INFO] [LP]      Aegis fork
20:42:51 [INFO] [LP] -  Storage:
20:42:51 [INFO] [LP]      Type: MongoDB
20:42:51 [INFO] [LP]      Ping: 7ms
20:42:51 [INFO] [LP]      Connected: true
20:42:51 [INFO] [LP] -  Messaging: Redis
20:42:51 [INFO] [LP] -  Instance:
20:42:51 [INFO] [LP]      Static contexts: server=proxy
20:42:51 [INFO] [LP]      Online Players: 0 (0 unique)
20:42:51 [INFO] [LP]      Uptime: 1h 7m 21s
20:42:51 [INFO] [LP]      Local Data: 0 users, 16 groups, 1 tracks
 and
[20:43:12 INFO]: [LP] Running LuckPerms v5.1.16 by Luck.
[20:43:12 INFO]: [LP] -  Platform: Bukkit
[20:43:12 INFO]: [LP] -  Server Brand: Paper
[20:43:12 INFO]: [LP] -  Server Version:
[20:43:12 INFO]: [LP]      git-Paper-284 (MC: 1.15.2) - 1.15.2-R0.1-SNAPSHOT
[20:43:12 INFO]: [LP] -  Storage:
[20:43:12 INFO]: [LP]      Type: MongoDB
[20:43:12 INFO]: [LP]      Ping: 12ms
[20:43:12 INFO]: [LP]      Connected: true
[20:43:12 INFO]: [LP] -  Messaging: Redis
[20:43:12 INFO]: [LP] -  Instance:
[20:43:12 INFO]: [LP]      Static contexts: server=builder-1
[20:43:12 INFO]: [LP]      Online Players: 0 (1 unique)
[20:43:12 INFO]: [LP]      Uptime: 7h 33m 48s
[20:43:12 INFO]: [LP]      Local Data: 0 users, 16 groups, 1 tracks
both connected

**Comment by lucko** [comment]
Check that the UUIDs match when you run the info command for the user, and that they both show as being online.

**Comment by meerpaluten** [comment]
Yes, that match! The player has the same groups in lpb and lp. And the same uuid!

**Comment by lucko** [comment]
Can you show screenshots of that - and show what the issue is?

**Comment by meerpaluten** [comment]
Spigot:
![image](https://user-images.githubusercontent.com/45709417/102785089-af01f680-439d-11eb-9de2-bb1bfc35f7af.png)
BungeeCord:
![image](https://user-images.githubusercontent.com/45709417/102785119-bc1ee580-439d-11eb-9317-81e9f831d2e1.png)

Issue:
When I update the group on the bungeecord, the event is not triggered. but when I run it on the spigot it is triggered properly.
