### ISSUE TITLE
world column too small in database

### ISSUE THREAD

**Issue by pixelsquared** [lucko/LuckPerms#2298]
The `world` column is only VARCHAR(36) but that is too small for my use case.

A plugin I am using ([World System Plugin](https://www.spigotmc.org/resources/worldsystem-●-the-one-world-per-player-solution-●-gui-●-highly-configurable-●-1-8-1-15.49756/)) uses the players' uuid plus an id for the world name which ends up longer than 36 letters.

I wanted to use the context system in luckperms to give players perms in only their world but I can't because of this error:
```
13.05 12:55:07 [Server] WARN Caused by: org.h2.jdbc.JdbcBatchUpdateException: Value too long for column """WORLD"" VARCHAR(36) NOT NULL": "'id1-6e05911c-d04a-4cba-ab04-fe0bf50c8388' (40)"; SQL statement:
13.05 12:55:07 [Server] WARN INSERT INTO `luckperms_user_permissions` (uuid, permission, value, server, world, expiry, contexts) VALUES(?, ?, ?, ?, ?, ?, ?) [22001-199]
```

**Comment by pixelsquared** [comment]
Is the only place that needs to be updated these files?

[common/src/main/resources/me/lucko/luckperms/schema](https://github.com/lucko/LuckPerms/tree/master/common/src/main/resources/me/lucko/luckperms/schema)

**Comment by lucko** [comment]
Yes, that's the only place.

Sorry I haven't replied, I'm not really sure the best way to resolve this, the 32 character limit seemed reasonable to me at the time, I could bump it but but where do you set the bar? 🙃

**Comment by pixelsquared** [comment]
I personally think a 64 limit would be good but I am not sure if there would be a better way to go about it.
