### ISSUE TITLE
Request: Adding multiple servers in Context counting as this OR that server

### ISSUE THREAD

**Issue by zettlinger** [lucko/LuckPerms#2299]
I have multiple servers and as i understood from a Mod on Discord (Larry) i would have to add each node to each server either by duplicating data or adding in specific groups.
This can get pretty messy and complicated , i am working on a 9 server setup to add to the 4 i have already. Even the group would mean i can only add the exact same list of perms OR i need to make a ton of groups again.

What i would like is that i can add multiple server: server 1 , server 2
The editor allows this but apparently reads it as that that node wont get active unless the player is on 2 servers at once. this makes no sense.

Please kill this data redundancy and just read SERVER and WORLD context as OR iso AND

ps a simple way to COPY a line would also help not with redundance but ease of adding

**Comment by ApertureDevelopment** [comment]
In a way it makes sense if it's the same context.

You are right that a user can't be on two servers/worlds at the same time, a User can always only be on one world, making "OR" the better choice here, but when its different contexts (e.g. Server and World ) they should be AND connected

So as a not working example:
``(World 1 OR World2) AND (Server1 OR Server2)``

**Comment by lucko** [comment]
Added in ed85ab1bfd1673e10a313179936ad211c313910f :)
