### ISSUE TITLE
Support permission options other than prefix/suffix

### ISSUE THREAD

**Issue by dualspiral** [lucko/LuckPerms#23]
This is an issue based on https://forums.spongepowered.org/t/luckperms-an-advanced-permissions-system/14274/121

As far as I can see, so far, LuckPerms only supports adding the permission options `prefix` and `suffix`. Unfortunately, in Sponge plugins such as mine, Nucleus, we make much heavier use of options, and while we try to mitigate it in the plugin when the support isn't there, it's still somewhat essential to have the support to gain full functionallity.

A good example of where the lack of permission options is hitting us is setting the number of homes a player can has. Using numbered permissions is time consuming and wasteful, because permissions are pretty much just a true/false/undefined state. Options allow us to solve that problem by being any form we choose, and only having to make one query, not multiple queries. We would also expect them to be inheritable, so the meta system you provide would (unfortunately) not quite fit how Options are expected to work.

For context on why this is being requested, http://nucleuspowered.org/docs/modules/chat.html and http://nucleuspowered.org/docs/modules/home.html explains how we use options, and it would be appreciated if you support them too, else Nucleus and other plugins will run with reduced functionallity.

(In case of confusion, I'm suggesting that it should be something like GroupManager's variables (added using `manuaddv` etc.), or PEX's options)

**Comment by bloodmc** [comment]
GriefPrevention also makes use of options for claim limits.

**Comment by lucko** [comment]
Sure. The backend system is already there, but you're right, they're not inherited. (that's a simple fix, there's no specific reason for it to be that way.)

And yes, there's no commands currently either, so I'll add that too.

Thanks for bringing it to my attention. 😃 (it has been in need of a rewrite for a while anyway.)

**Comment by dualspiral** [comment]
Thank you kindly!

**Comment by lucko** [comment]
Sorry it took a while. I decided to re-write the entire caching system and refactor meta commands in the process of implementing this. :relieved:
