### ISSUE TITLE
Bukkit permissions.yml issues

### ISSUE THREAD

**Issue by selfslaughter** [lucko/LuckPerms#2302]
**apply-wildcards: true**

 - Wildcards don't apply from within bukkits permissions.yml

Example: if you gave a group the user.worldguard permission below, they would get the claim and wand permission, but not the info permissions.

```
user.worldguard:
  default: false
  children:
    worldguard.region.claim: true
    worldguard.region.wand: true
    worldguard.region.info.*: true
```
**apply-bukkit-default-permissions: false**

- This setting in LuckPerms config seems to be ignored. Default permissions apply regardless of this setting and seem to ignore the "default: op" setting as well.

Example: Having these parent nodes in permissions.yml, with the above setting on true or false, would  prevent the console being able to use the version command, with lp verbose returning: 

[LP] VB > internal/console - bukkit.command.version - false
```
all.bukkit:
 default: true
 children:
   bukkit.command.version: false

op.bukkit:
 default: op
 children:
   bukkit.command.version: true
```

**Version Info**
```
> lp info
[16:10:01 INFO]: [LP] Running LuckPerms v5.1.16 by Luck.
[16:10:01 INFO]: [LP] -  Platform: Bukkit
[16:10:01 INFO]: [LP] -  Server Brand: Paper
[16:10:01 INFO]: [LP] -  Server Version:
[16:10:01 INFO]: [LP]      git-Paper-282 (MC: 1.15.2) - 1.15.2-R0.1-SNAPSHOT
[16:10:01 INFO]: [LP] -  Storage:
[16:10:01 INFO]: [LP]      Type: MySQL
[16:10:01 INFO]: [LP]      Ping: 2ms
[16:10:01 INFO]: [LP]      Connected: true
[16:10:01 INFO]: [LP] -  Messaging: Sql
[16:10:01 INFO]: [LP] -  Instance:
[16:10:01 INFO]: [LP]      Static contexts: server=survival
[16:10:01 INFO]: [LP]      Online Players: 0 (0 unique)
[16:10:01 INFO]: [LP]      Uptime: 2h 53m 2s
[16:10:01 INFO]: [LP]      Local Data: 0 users, 14 groups, 5 tracks
```

**Comment by Laarryy** [comment]
Luckperms does not, to the best of my knowledge, have any power in the realm of bukkit's permissions.yml. As such, Luckperms options will not apply there. 

Ya know, the whole point of Luckperms is a replacement / more configurable and powerful alternative to that permissions.yml file, which is incredibly limited in capability, as you point out in the issue.

Luck will be able to tell you why what is happening is happening (probably) but regardless, the permissions yml file is not under the control of LP, and shouldn't really be functional or expected to be doing things with two permissions systems.

**Comment by lucko** [comment]
> apply-wildcards: true - Wildcards don't apply from within bukkits permissions.yml

This is intended.

> Example: Having these parent nodes in permissions.yml, with the above setting on true or false, would prevent the console being able to use the version command, with lp verbose returning:
[LP] VB > internal/console - bukkit.command.version - false

LuckPerms doesn't touch the console's permissions - it only manages permissions for players.

I could potentially add a configurable override for the console (make it always have all permissions) if that would be useful?
