### ISSUE TITLE
how to fix multiple prefixes on my Minecraft Server + one other issue

### ISSUE THREAD

**Issue by KingLee79** [lucko/LuckPerms#2304]
I am using Luck Perms with essentials chat and towny chat, when ever I say anything it goes [g] [world] OwnerOwner {playername}. the [g][world]Owner is correct (the first part is the towny chat the other part is the correct prefix) but it gives the second prefix. The other issue is my admin is stuck with Admin|[playername] and wont show their /nick unless they die or go /afk. Please help.

**Comment by benwoo1110** [comment]
Its not an LuckPerms issue but rather a config issue with your essentials chat and/or towny chat. You can try setting `add-prefix-suffix: false` in essentials config.yml 

As for /nick and /afk as long as you have the permissions, the behaviour is not handled by LP. 

for essentials support: https://discord.gg/casfFyh

**Comment by KingLee79** [comment]
just added add-prefix-suffix: false to both chat configs and still is giving 2 prefixes (even tried with it only being in the essentials chat config.)

**Comment by benwoo1110** [comment]
Not sure how you are modifying the config, but can you show the screenshot of `/lp user USER info`?

If it shows the correct prefix, i suggest contacting essentials support and possibility towny chat support as well to ask in how to format your chat properly.

**Comment by KingLee79** [comment]
![image](https://user-images.githubusercontent.com/65350682/81944763-34812500-95cb-11ea-9e4a-1b5807ff6794.png)

**Comment by benwoo1110** [comment]
this means you have not given yourself luckperms permission to run luckperms command, either give yourself `luckperms.*` permission nodes or run the command in console then send the screenshot again.

**Comment by KingLee79** [comment]
![image](https://user-images.githubusercontent.com/65350682/81945338-fdf7da00-95cb-11ea-9b78-6daa0107b297.png)
the weird thing is my group (owner) has that exact perm set in it so yea

**Comment by benwoo1110** [comment]
prefix set by LP looks good, with duplicates. This means its your chat plugin's issue. for some troubleshooting on chat plugin: https://github.com/lucko/LuckPerms/wiki/FAQ#why-are-prefixessuffixes-not-working


I suggest relaying this issue to essentials support: https://discord.gg/casfFyh

**Comment by KingLee79** [comment]
thanx for the info, now to go do that and then figure out why my commands are showing up red (as if they are not commands)

**Comment by benwoo1110** [comment]
assuming the issue is with your permissions set (or the lack of setting them), you can use verbose while running those commands to find out the permission nodes needed.

On how to use lp verbose: https://github.com/lucko/LuckPerms/wiki/Verbose

**Comment by KingLee79** [comment]
again thank you
