### ISSUE TITLE
People are duplicated when they connect to my server.

### ISSUE THREAD

**Issue by Akoui** [lucko/LuckPerms#2305]
Hello, 

when someone connects to my server it is displayed twice on luckperms editor.
![image](https://user-images.githubusercontent.com/65348707/81956631-d6286680-960b-11ea-987e-fbabbae3ecb6.png)

When I was the first to be connected to my server I was displayed normally without any problems. However when people join my server and I run the /lp editor command to edit permissions, they show me duplicate players.
I think players have to log in at least twice before they get this. It also duplicate the permissions twice like this:

![image](https://user-images.githubusercontent.com/65348707/81957701-45eb2100-960d-11ea-8161-b815186af047.png)

Best regards.

**Comment by Laarryy** [comment]
This was *very* recently fixed in an update. Try downloading the latest version from https://luckperms.net

**Comment by Akoui** [comment]
Ok, thanks it's good.
