### ISSUE TITLE
No Access to minecraft/bukkit commands

### ISSUE THREAD

**Issue by Flammenfuchs** [lucko/LuckPerms#2306]
My parent group has the permission "*" true, that is fine.
I hava all permissions from plugins, all from bungee, but no permission to access spigot/bukkit/minecraft commands

**Comment by Laarryy** [comment]
Is there perhaps a higher weighted (or non-weighted) group the player inherits that has those perms all set to false?

**Comment by Flammenfuchs** [comment]
There is a user group, but this group hasn't got defined any parent groups and it is the group with the heighest weight

**Comment by Flammenfuchs** [comment]
I added the permission bukkit.* and minecraft.* but it do not solves the problem, I have no access

**Comment by BrainStone** [comment]
Do you by any chance have any other permission plugins installed like PermissionsEx/PEX, GroupManager, UltraPermissions?  
If so you need to remove them.
