### ISSUE TITLE
% luckperms_expiry_time_ <permission>% does not work

### ISSUE THREAD

**Issue by cvczcvc** [lucko/LuckPerms#2308]
Limited time permissions seem to be unrecognized

**Comment by Andre601** [comment]
In what way?
What does it display?
If it just displays the placeholder then you might've forgotton to download the expansion with PlaceholderAPI (`/papi ecloud download LuckPerms`)

**Comment by cvczcvc** [comment]
> 用什么方式？
> 它显示什么？
> 如果仅显示占位符，则您可能已经忘记了使用PlaceholderAPI（`/papi ecloud download LuckPerms`）下载扩展

The extension has been installed correctly, but it does not display any numbers. I have set the duration of the permissions, but nothing is displayed

**Comment by cvczcvc** [comment]
> In what way?
> What does it display?
> If it just displays the placeholder then you might've forgotton to download the expansion with PlaceholderAPI (`/papi ecloud download LuckPerms`)

The extension has been installed correctly, but it does not display any numbers. I have set the duration of the permissions, but nothing is displayed

**Comment by cvczcvc** [comment]
- AK47.use:
    value: true
    expiry: 1589566939

&7Time_left: %luckperms_expiry_time_AK47.use%

The result is:&7Time_left: 
No display

**Comment by lucko** [comment]
Should be resolved by 46fcebb9d76c5ae4bb1ebff75c26efe5ff1e955d

**Comment by cvczcvc** [comment]
> 应该由46fcebb9d76c5ae4bb1ebff75c26efe5ff1e955d解决

What does it mean？

**Comment by lucko** [comment]
Try these builds of the expansion.

https://ci.lucko.me/job/LuckPermsPlaceholders/22/
