### ISSUE TITLE
addgroup/removegroup command

### ISSUE THREAD

**Issue by steenooo** [lucko/LuckPerms#231]
Hey!
I might be wrong. But as far as i know there is no support for multiple groups without tracks or something in that way.
I'd love to see a /lp user <user> addgroup <group> command, and a /lp user <user> removegroup <group>. Just like zPermissions.

**Comment by lucko** [comment]
You need `parent add` and `parent remove`.

The `addgroup` command is also added as an alias.

**Comment by steenooo** [comment]
Ah thanks!
