### ISSUE TITLE
Issue with Web Panel Editor + LP

### ISSUE THREAD

**Issue by TMCGH** [lucko/LuckPerms#2310]
If you leave a server in offline mode on your bungee network, and another user spoofs your accounts UUID it will then cause problems and conflict with things such as the Editor along with blocking the original account that had its IGN spoofed from logging into the bungee and server. 

This is what shows in the panel: https://prnt.sc/sila9t

Basically, the place where my account in the panel now has the username of the spoofers IGN which blocks me from logging in or using the /lp user <username> clear command on the spigot server.

**Comment by lucko** [comment]
> along with blocking the original account that had its IGN spoofed from logging in.

Can you show an example of that?

LuckPerms just stores data using whatever UUID the server has registered for the player. There's not much LP can do to cleanup if you've allowed people to connect without authentication.

**Comment by TMCGH** [comment]
LuckPerms is the thing blocking the connection only for that account when I try to login with the account.
 here is the error: https://prnt.sc/sila9t

**Comment by lucko** [comment]
That error has already been fixed, you just need to update.
