### ISSUE TITLE
A way to set a users parent without removing parents on different tracks

### ISSUE THREAD

**Issue by kmecpp** [lucko/LuckPerms#2313]
When I give players donor roles from a Buycraft/Enjin site I currently just set there parent to the donor role that they purchase but this removes their staff rank.

I can think of some workarounds for this but all of them are pretty bad.

Could we have a way to set a users parent without removing their parents which are on different tracks?

For example,
`lp u <name> parent set <donor rank> (but without removing their staff rank?)`

Or is there already some easy way to accomplish this that I'm not aware of?

**Comment by Tobi406** [comment]
`lp user <user> parent add <donor rank>`?

**Comment by kmecpp** [comment]
The problem with that is that then the user potentially builds up like 10 different parents where 9 of them are redundant and if I want to remove them manually

It also makes it more difficult when there's a lot of groups to figure out which one is the highest/important one.

That's why I always like to remove their old parent but this is not possible with Enjin/Buycraft because you don't know what their old rank was

**Comment by lucko** [comment]
Use `parent settrack`

https://github.com/lucko/LuckPerms/wiki/Command-Usage:-Parent#lp-usergroup-usergroup-parent-settrack-track-group-context
