### ISSUE TITLE
First command isnt working

### ISSUE THREAD

**Issue by Tedber13** [lucko/LuckPerms#2315]
Inputing "lp user <your username> permission set luckperms.* true" like it says in the usage page, onto the server console prompts no response letting me know it worked. how do i fix this

**Comment by Turbotailz** [comment]
You need to put a username after "user".
Although *something* should have been output to the console when you wrote it. Care to share a screenshot?

**Comment by Tedber13** [comment]
Sure, I tried every variable I thought I could think of

![Screenshot (23)](https://user-images.githubusercontent.com/65695625/82519870-be138400-9af0-11ea-8d4c-1ec3e88fdbcd.png)

**Comment by benwoo1110** [comment]
Run `lp user USERNAME permission set luckperms.* true` without the `/` and `<>`.

**Comment by Tedber13** [comment]
I did that as well, but there isn't
 a response, nothing shows up after.

**Comment by benwoo1110** [comment]
send your full server startup log via https://bytebin.lucko.me/ 

1. restart your server fully
2. copy contents of `./yourserver/logs/lastest.log` and upload to https://bytebin.lucko.me/ 
3. send the bytebin link here.

**Comment by Turbotailz** [comment]
It's possible the plugin just didn't load, so you need to provide a full console log from start up as Ben said so we can see if there were any errors.

You may also be using an old version of LP, as a recent version introduced the ability to run `/lp` on a console.

**Comment by Tedber13** [comment]
https://bytebin.lucko.me/Y65xY1ABHb

here you go

**Comment by Turbotailz** [comment]
Hmm, so LP didn't enable.

Can you try removing the `lib` or `libs` folder from the `LuckPerms` plugin folder? Then restart the server.

**Comment by Tedber13** [comment]
Okay, then I try again?

**Comment by Tedber13** [comment]
oh okay nevermind, yeah that fixed it, i put in the command it now its working.

**Comment by Turbotailz** [comment]
Sweet :)

Feel free to close the issue if you're happy with the solution.
