### ISSUE TITLE
I still have an SSL issue even though I followed the guide in the wiki.

### ISSUE THREAD

**Issue by JackOUT04** [lucko/LuckPerms#2316]
_**Console warn :**_
21.05 11:12:55 [Server] WARN Thu May 21 11:12:55 CEST 2020 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.

__** Config :**__https://pastebin.com/Wba5FGqZ

Hope you can help me. 
Thank you in advance

**Comment by BrainStone** [comment]
Looks like you configured LP correctly. My guess is that there’s another plugin that also uses MySQL, that’s the issue here.

**Comment by JackOUT04** [comment]
Ok thanks for the help.

**Comment by StrangeOne101** [comment]
This could also be avoided if LuckPerms gave the option for database connection flags. If the database is local, you can set `useSSL=false` in the connection flags and the warning will no longer display.

Could this feature be perhaps added? I get this warning spammed a lot but can't disable it. Thanks.

**Comment by benwoo1110** [comment]
The options are already present in LP config.yml

```
```

**Comment by benwoo1110** [comment]
And it seems like JackOUT04 has already set those options. Therefore, the warm shown is most likely from another plugin and not luckperms @StrangeOne101

**Comment by StrangeOne101** [comment]
@benwoo1110 It appears my config was out of date. I looked over all configuration documentation but couldn't see it anywhere when checking every page related to storage. Thanks for making me check the latest version of the config.

Ignore my comments above. Thanks.
