### ISSUE TITLE
"Failed to load jar for dependency SLF4J_SIMPLE"

### ISSUE THREAD

**Issue by Tenelia** [lucko/LuckPerms#232]
> [20:37:12] [Server thread/INFO] [MinecraftServer]:   Loading version v3.0.46 on Sponge - SpongeVanilla
> [20:37:12] [Server thread/INFO] [MinecraftServer]:   Running on server version SpongeAPI: 6.0.0-SNAPSHOT-43b286d - SpongeVanilla: 1.11.2-6.0.0-BETA-234
> [20:37:12] [Server thread/INFO] [MinecraftServer]:  
> [20:37:12] [Server thread/INFO] [MinecraftServer]: [LP] Loading configuration...
> [20:37:12] [Server thread/INFO] [MinecraftServer]: [LP] Detecting storage method...
> [20:37:12] [Server thread/INFO] [MinecraftServer]: [LP] Loading dependencies...
> [20:37:12] [Server thread/INFO] [MinecraftServer]: [LP] Identified the following dependencies: [MYSQL_DRIVER, SLF4J_API, SLF4J_SIMPLE, HIKARI]
> [20:37:12] [Server thread/INFO] [MinecraftServer]: [LuckPerms] [ERROR] Failed to load jar for dependency SLF4J_SIMPLE
> [20:37:12] [Server thread/ERROR] [STDERR]: java.lang.ClassNotFoundException: org.slf4j.impl.SimpleLoggerFactory
> [20:37:12] [Server thread/ERROR] [STDERR]: 	at java.net.URLClassLoader.findClass(Unknown Source)
> [20:37:12] [Server thread/ERROR] [STDERR]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
> [20:37:12] [Server thread/ERROR] [STDERR]: 	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
> [20:37:12] [Server thread/ERROR] [STDERR]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
> [20:37:12] [Server thread/ERROR] [STDERR]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106)
> [20:37:12] [Server thread/ERROR] [STDERR]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
> [20:37:12] [Server thread/ERROR] [STDERR]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
> [20:37:12] [Server thread/ERROR] [STDERR]: 	at me.lucko.luckperms.common.dependencies.DependencyManager.loadJar(DependencyManager.java:143)
> [20:37:12] [Server thread/ERROR] [STDERR]: 	at me.lucko.luckperms.common.dependencies.DependencyManager.loadDependencies(DependencyManager.java:104)
> [20:37:12] [Server thread/ERROR] [STDERR]: 	at me.lucko.luckperms.common.dependencies.DependencyManager.loadDependencies(DependencyManager.java:81)
> [20:37:12] [Server thread/ERROR] [STDERR]: 	at me.lucko.luckperms.sponge.LPSpongePlugin.onEnable(LPSpongePlugin.java:182)
> [20:37:12] [Server thread/ERROR] [STDERR]: 	at org.spongepowered.common.event.listener.GamePreInitializationEventListener_LPSpongePlugin_onEnable62.handle(Unknown Source)
> [20:37:12] [Server thread/ERROR] [STDERR]: 	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95)
> [20:37:12] [Server thread/ERROR] [STDERR]: 	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:305)
> [20:37:12] [Server thread/ERROR] [STDERR]: 	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:320)
> [20:37:12] [Server thread/ERROR] [STDERR]: 	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:324)
> [20:37:12] [Server thread/ERROR] [STDERR]: 	at org.spongepowered.common.SpongeImpl.postState(SpongeImpl.java:201)
> [20:37:12] [Server thread/ERROR] [STDERR]: 	at org.spongepowered.server.SpongeVanilla.preInitialize(SpongeVanilla.java:115)
> [20:37:12] [Server thread/ERROR] [STDERR]: 	at net.minecraft.server.dedicated.DedicatedServer.handler$onServerLoad$znp000(SourceFile:1223)
> [20:37:12] [Server thread/ERROR] [STDERR]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(SourceFile:112)
> [20:37:12] [Server thread/ERROR] [STDERR]: 	at net.minecraft.server.MinecraftServer.run(SourceFile:436)
> [20:37:12] [Server thread/ERROR] [STDERR]: 	at java.lang.Thread.run(Unknown Source)

**Comment by lucko** [comment]
Can you try with the latest version from https://ci.lucko.me/job/LuckPerms

**Comment by Tenelia** [comment]
My bad! Thanks!
