### ISSUE TITLE
Track migration from zPerms doesn't convert periods from track names like from group names

### ISSUE THREAD

**Issue by Laarryy** [lucko/LuckPerms#2320]
A user today came in with a track problem after zPerms migration - while groups are converted from `rank.rankname.continuation` to `rank-rankname-continuation` the group listings in tracks remain like the first while the the group names get changed, leaving promote commands to see no valid group in the track. 
![](https://i.imgur.com/n52dfJw.png)

**Comment by lucko** [comment]
I think this is due to a user configuration error.

Seems like the migration just copies exactly what ZPermissions provides via it's API.
