### ISSUE TITLE
/lp Editor Not working correctly

### ISSUE THREAD

**Issue by JTKoops** [lucko/LuckPerms#2322]
When I generate an editor link the webpage spits out the the code was copied wrong or expired. This happens over and over again. I have found that in some instances, you must wait several minutes for the link to generate server side on your webpage. The was never an issue with your old webhost, and has only come about now that you have the new host.

**Comment by lucko** [comment]
Nothing has changed recently with the hosting of the site, I've been using the same setup for around 1 year.

If you open the developer tools console in your browser after opening the page, the actual error encountered when loading will be displayed there. :)
