### ISSUE TITLE
Ranks not Syncing

### ISSUE THREAD

**Issue by itzblazie** [lucko/LuckPerms#2323]
I have luckperms across my network using MYSQL, it was working perfectly fine yesterday no issues, but now my Survival server is not linking up to the rest of the network, all permission nodes go through across to all servers but the rank don't.

**Comment by lucko** [comment]
1. Check console for errors.
2. Ensure you've definitely got it connected to the same database.
3. Make sure you've followed these steps: https://github.com/lucko/LuckPerms/wiki/Network-Installation
