### ISSUE TITLE
/lp import overwriting previous data

### ISSUE THREAD

**Issue by FawksX** [lucko/LuckPerms#2324]
While attempting to merge some user data into another database I have found that importing user groups now overwrites data which the user already had. For example:

User had groups: Group1, Group2, Group3
I attempted using /lp import to give the user Group5
User now has groups: Group5

This also applies to groups in terms of permission nodes. However, this only happens if the user already exists/has groups/permissions added to them.

**Comment by lucko** [comment]
Added in the above commit:

`/lp import example --merge`
