### ISSUE TITLE
doesn't have data pre-loaded, they have never been processed during pre-login in this session.

### ISSUE THREAD

**Issue by blueGecko921** [lucko/LuckPerms#2325]
I am trying to set up a Minecraft server network. So I am using LPB and LP when I added a MySQL database with noting on it yet. But now all I get is kicked.

LPB(Bungeecord server):
> 15:07:23 [SEVERE] [LuckPerms] Exception occurred whilst loading data for b7bd9991-acdf-4547-bb29-24faa1f8aa5f - blueGecko921
> 15:07:23 [SEVERE] java.util.concurrent.CompletionException: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5000ms.
> 15:07:23 [SEVERE] at me.lucko.luckperms.common.storage.Storage.lambda$makeFuture$0(Storage.java:90)
> 15:07:23 [SEVERE] at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
> 15:07:23 [SEVERE] at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
> 15:07:23 [SEVERE] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 15:07:23 [SEVERE] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 15:07:23 [SEVERE] at java.lang.Thread.run(Thread.java:748)
> 15:07:23 [SEVERE] Caused by: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5000ms.
> 15:07:23 [SEVERE] at me.lucko.luckperms.lib.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:689)
> 15:07:23 [SEVERE] at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:196)
> 15:07:23 [SEVERE] at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:161)
> 15:07:23 [SEVERE] at me.lucko.luckperms.lib.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
> 15:07:23 [SEVERE] at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.getConnection(HikariConnectionFactory.java:131)
> 15:07:23 [SEVERE] at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.getPlayerName(SqlStorage.java:679)
> 15:07:23 [SEVERE] at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.savePlayerData(SqlStorage.java:609)
> 15:07:23 [SEVERE] at me.lucko.luckperms.common.storage.Storage.lambda$savePlayerData$20(Storage.java:258)
> 15:07:23 [SEVERE] at me.lucko.luckperms.common.storage.Storage.lambda$makeFuture$0(Storage.java:85)
> 15:07:23 [SEVERE] ... 5 more
> 15:07:23 [SEVERE] Caused by: me.lucko.luckperms.lib.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown database 's2172_Perms'
> 15:07:23 [SEVERE] at sun.reflect.GeneratedConstructorAccessor19.newInstance(Unknown Source)
> 15:07:23 [SEVERE] at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 15:07:23 [SEVERE] at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
> 15:07:23 [SEVERE] at me.lucko.luckperms.lib.mysql.jdbc.Util.handleNewInstance(Util.java:425)
> 15:07:23 [SEVERE] at me.lucko.luckperms.lib.mysql.jdbc.Util.getInstance(Util.java:408)
> 15:07:23 [SEVERE] at me.lucko.luckperms.lib.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
> 15:07:23 [SEVERE] at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3933)
> 15:07:23 [SEVERE] at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869)
> 15:07:23 [SEVERE] at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:864)
> 15:07:23 [SEVERE] at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1707)
> 15:07:23 [SEVERE] at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1217)
> 15:07:23 [SEVERE] at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2189)
> 15:07:23 [SEVERE] at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2220)
> 15:07:23 [SEVERE] at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2015)
> 15:07:23 [WARNING] [LuckPerms] User b7bd9991-acdf-4547-bb29-24faa1f8aa5f - blueGecko921 doesn't have data pre-loaded, they have never been processed during pre-login in this session.
> 15:07:23 [SEVERE] at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:768)
> 15:07:23 [SEVERE] at me.lucko.luckperms.lib.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
> 15:07:23 [SEVERE] at sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
> 15:07:23 [SEVERE] at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 15:07:23 [SEVERE] at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
> 15:07:23 [SEVERE] at me.lucko.luckperms.lib.mysql.jdbc.Util.handleNewInstance(Util.java:425)
> 15:07:23 [SEVERE] at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:385)
> 15:07:23 [SEVERE] at me.lucko.luckperms.lib.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:323)
> 15:07:23 [SEVERE] at me.lucko.luckperms.lib.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:428)
> 15:07:23 [SEVERE] at me.lucko.luckperms.lib.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:136)
> 15:07:23 [SEVERE] at me.lucko.luckperms.lib.hikari.pool.PoolBase.newConnection(PoolBase.java:354)
> 15:07:23 [SEVERE] at me.lucko.luckperms.lib.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)
> 15:07:23 [SEVERE] at me.lucko.luckperms.lib.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)
> 15:07:23 [SEVERE] at me.lucko.luckperms.lib.hikari.pool.HikariPool.access$100(HikariPool.java:71)
> 15:07:23 [SEVERE] at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:719)
> 15:07:23 [SEVERE] at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:705)
> 15:07:23 [SEVERE] at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 15:07:23 [SEVERE] ... 3 more
> 15:07:23 [INFO] [blueGecko921] <-> ServerConnector [hub] has connected
> 15:07:28 [INFO] [blueGecko921] disconnected with: Kicked whilst connecting to hub: [LP] A database error occurred whilst loading permissions data. Please try again later. If you are a server admin, please check the console for any errors.
> 15:07:28 [INFO] [blueGecko921] -> UpstreamBridge has disconnected
> 15:07:28 [INFO] [blueGecko921] <-> ServerConnector [hub] has disconnected

LP(Hub server):
> [15:07:28 ERROR]: [LuckPerms] Exception occurred whilst loading data for b7bd9991-acdf-4547-bb29-24faa1f8aa5f - blueGecko921
> [15:07:28 WARN]: java.util.concurrent.CompletionException: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5000ms.
> [15:07:28 WARN]: at me.lucko.luckperms.common.storage.Storage.lambda$makeFuture$0(Storage.java:91)
> [15:07:28 WARN]: at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
> [15:07:28 WARN]: at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596)
> [15:07:28 WARN]: at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
> [15:07:28 WARN]: at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
> [15:07:28 WARN]: at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
> [15:07:28 WARN]: at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
> [15:07:28 WARN]: Caused by: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5000ms.
> [15:07:28 WARN]: at me.lucko.luckperms.lib.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:689)
> [15:07:28 WARN]: at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:196)
> [15:07:28 WARN]: at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:161)
> [15:07:28 WARN]: at me.lucko.luckperms.lib.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
> [15:07:28 WARN]: at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.getConnection(HikariConnectionFactory.java:151)
> [15:07:28 WARN]: at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.getPlayerName(SqlStorage.java:706)
> [15:07:28 WARN]: at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.savePlayerData(SqlStorage.java:636)
> [15:07:28 WARN]: at me.lucko.luckperms.common.storage.Storage.lambda$savePlayerData$20(Storage.java:259)
> [15:07:28 WARN]: at me.lucko.luckperms.common.storage.Storage.lambda$makeFuture$0(Storage.java:86)
> [15:07:28 WARN]: ... 6 more
> [15:07:28 WARN]: Caused by: me.lucko.luckperms.lib.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown database 's2172_Perms'
> [15:07:28 WARN]: at sun.reflect.GeneratedConstructorAccessor42.newInstance(Unknown Source)
> [15:07:28 WARN]: at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> [15:07:28 WARN]: at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
> [15:07:28 WARN]: at me.lucko.luckperms.lib.mysql.jdbc.Util.handleNewInstance(Util.java:425)
> [15:07:28 WARN]: at me.lucko.luckperms.lib.mysql.jdbc.Util.getInstance(Util.java:408)
> [15:07:28 WARN]: at me.lucko.luckperms.lib.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
> [15:07:28 WARN]: at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3933)
> [15:07:28 WARN]: at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869)
> [15:07:28 WARN]: at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:864)
> [15:07:28 WARN]: at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1707)
> [15:07:28 WARN]: at me.lucko.luckperms.lib.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1217)
> [15:07:28 WARN]: at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2189)
> [15:07:28 WARN]: at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2220)
> [15:07:28 WARN]: at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2015)
> [15:07:28 WARN]: at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:768)
> [15:07:28 WARN]: at me.lucko.luckperms.lib.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
> [15:07:28 WARN]: at sun.reflect.GeneratedConstructorAccessor38.newInstance(Unknown Source)
> [15:07:28 WARN]: at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> [15:07:28 WARN]: at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
> [15:07:28 WARN]: at me.lucko.luckperms.lib.mysql.jdbc.Util.handleNewInstance(Util.java:425)
> [15:07:28 WARN]: at me.lucko.luckperms.lib.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:385)
> [15:07:28 WARN]: at me.lucko.luckperms.lib.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:323)
> [15:07:28 WARN]: at me.lucko.luckperms.lib.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:428)
> [15:07:28 WARN]: at me.lucko.luckperms.lib.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:136)
> [15:07:28 WARN]: at me.lucko.luckperms.lib.hikari.pool.PoolBase.newConnection(PoolBase.java:354)
> [15:07:28 WARN]: at me.lucko.luckperms.lib.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)
> [15:07:28 WARN]: at me.lucko.luckperms.lib.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)
> [15:07:28 WARN]: at me.lucko.luckperms.lib.hikari.pool.HikariPool.access$100(HikariPool.java:71)
> [15:07:28 WARN]: at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:719)
> [15:07:28 WARN]: at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:705)
> [15:07:28 WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [15:07:28 WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> [15:07:28 WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> [15:07:28 WARN]: at java.lang.Thread.run(Thread.java:748)
> [15:07:28 INFO]: Disconnecting com.mojang.authlib.GameProfile@1340d88[id=b7bd9991-acdf-4547-bb29-24faa1f8aa5f,name=blueGecko921,properties={textures=[com.mojang.authlib.properties.Property@311ddad4]},legacy=false] (/65.25.78.49:36561): §7[§b§lL§3§lP§7] §cA database error occurred whilst loading permissions data. Please try again later. If you are a server admin, please check the console for any errors.
> [15:07:28 INFO]: com.mojang.authlib.GameProfile@1340d88[id=b7bd9991-acdf-4547-bb29-24faa1f8aa5f,name=blueGecko921,properties={textures=[com.mojang.authlib.properties.Property@311ddad4]},legacy=false] (/65.25.78.49:36561) lost connection: §7[§b§lL§3§lP§7] §cA database error occurred whilst loading permissions data. Please try again later. If you are a server admin, please check the console for any errors.

**Comment by lucko** [comment]
> me.lucko.luckperms.lib.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown database 's2172_Perms'

Your database doesn't exist
