### ISSUE TITLE
When connected to a HikariCP, leaks accumulate and crash occurs.

### ISSUE THREAD

**Issue by GeorgyCherkasov** [lucko/LuckPerms#2326]
Hello. There is a problem. We have suspicion  that when connected to a HikariCP, leaks accumulate and crash occurs. At first, we thought that the location of the database was to blame, but after replacing the location, nothing changed.

![47C28C0B-F44A-4AFB-975E-557A6BFA0EF0](https://user-images.githubusercontent.com/65384051/82738090-7d6d7200-9d5f-11ea-8822-0080f33c4fa3.jpeg)

**Comment by lucko** [comment]
What version of LP?

**Comment by GeorgyCherkasov** [comment]
5.1.26

**Comment by lucko** [comment]
Huh weird, do you have the full error?

It shouldn't be leaking connections, the connection pool takes care of that.

**Comment by GeorgyCherkasov** [comment]
Sorry, but we have only this screenshot of the error.

**Comment by lucko** [comment]
Has the issue not happened since then?

**Comment by GeorgyCherkasov** [comment]
This issue has always been there.

**Comment by lucko** [comment]
Can you send a full log then please:)

**Comment by GeorgyCherkasov** [comment]
Hm... From LP there are only these messages.

**Comment by lucko** [comment]
The `[luckperms-scheduler-worker-x]` log prefix in your screenshot does not line up with what I'd expect to see from the latest version - this was changed a while ago. Are you sure you're definitely using the version you say you are?

I'd also expect to at least see *some* other messages from LuckPerms, but if you say so....

Unless you're willing to cooperate there's very little I can do to actually help.

**Comment by GeorgyCherkasov** [comment]
I want to cooperate with you. Okay, I will send the full log.

**Comment by GeorgyCherkasov** [comment]
[Uploading 2020-05-23-1.log…]()

**Comment by GeorgyCherkasov** [comment]
Sorry

**Comment by GeorgyCherkasov** [comment]
There is an error at the bottom.
[2020-05-23-1.log](https://github.com/lucko/LuckPerms/files/4703668/2020-05-23-1.log)

**Comment by lucko** [comment]
Alright thanks, I've had a quick look, seems that your database is just not responding to connections - there's nothing else in the log which would indicate it's a problem caused by LP.

There are some more details about these sort of problems here:
https://github.com/lucko/LuckPerms/wiki/Storage-system-errors

**Comment by GeorgyCherkasov** [comment]
We can agree that the DB server does not accept connections. But clearly the crash connection - the fault of LuckPerms. 
P.S. our build has a plugin that works with the same DB on the same server using HikariCP. So there this problem is not noticed, which means that LuckPerms is to blame.

**Comment by lucko** [comment]
"Crash connection"? Sorry, I don't know what you're referring to.

If you can point to a specific Hikari configuration option that you think is causing the problem then I'm happy to try changing things.

However, the current configuration is working perfectly fine for thousands of other servers - if there was such an egregious error in the way that LP was handling connections, you would not be the only person experiencing them.

**Comment by GeorgyCherkasov** [comment]
We went through the items and checked everything. Even shortened the pool's "life" time. But this is a "crutch", so at least please tell me what else might be the problem. LP crashes every 2-3 days.

**Comment by GeorgyCherkasov** [comment]
2 times a day crashed.
