### ISSUE TITLE
Error when using %luckperms_prefix_element_highest%

### ISSUE THREAD

**Issue by NEZNAMY** [lucko/LuckPerms#2327]
One of my users sent me this error: https://paste.helpch.at/ekubokacow.pl
It is generated when using %luckperms_prefix_element_highest% placeholder.
He claims to be using LP 5.1.26 with legacy api extension (his original words http://prntscr.com/smys99).
That's about all i know. If the info is not sufficient you can close this. Just wanted to inform you about the error.

**Comment by lucko** [comment]
Thank you for reporting :)
