### ISSUE TITLE
Q: Add rank after played time

### ISSUE THREAD

**Issue by Yeti-Programing** [lucko/LuckPerms#2328]
Is there a way to add a rank to a player after they have played on a server? (example: they get a rank after 1 week playtime/ logging on for the 7th day)

**Comment by Tobi406** [comment]
That's not something LP can do, you'd need another plugin for that.

**Comment by Yeti-Programing** [comment]
@Tobi406 Do you have a recommended plugin?

**Comment by lucko** [comment]
Try OnTime
