### ISSUE TITLE
Get prefix with new api (LuckPerms API v5)

### ISSUE THREAD

**Issue by Faall1n** [lucko/LuckPerms#2329]
As title says.

**Comment by Laarryy** [comment]
What?! You should check out this, https://github.com/lucko/LuckPerms/wiki/Developer-API

If that doesn't help you'll need to be more clear. An issue that's says a thing that's this ambiguous is painfully difficult to decipher

**Comment by lucko** [comment]
Also some examples here:

https://github.com/LuckPerms/api-cookbook/blob/master/src/main/java/me/lucko/lpcookbook/commands/GetPrefixCommand.java
https://github.com/LuckPerms/api-cookbook/blob/master/src/main/java/me/lucko/lpcookbook/commands/GetOfflinePrefixCommand.java
