### ISSUE TITLE
BungeeluckPerms error

### ISSUE THREAD

**Issue by det483** [lucko/LuckPerms#233]
Hello,

I have some problems with Luckperms for bungeecord. I get this error: https://pastebin.com/ZXye38wU
I am using the latest bungeecord version, the latest Luckperms and I don't know what causes this.

Kind regards,
det483

**Comment by lucko** [comment]
Can you try to re-download a fresh jar?

**Comment by det483** [comment]
Thank you! The new version works!

**Comment by lucko** [comment]
I ran out of disk space on the server which generates those downloads. Think that must've corrupted a few builds. 🕺
