### ISSUE TITLE
Prefix Issues

### ISSUE THREAD

**Issue by GamingProduction** [lucko/LuckPerms#2330]
Issue: theres no space between the prefix and actuall name and adding a spoace to the prefix command doesnt work

looking at it now
paste here pls where you have set the format for chat
GamingProToday at 12:42 PM
ok
ItzZaexYTToday at 12:42 PM
like where you set it to say owner
GamingProToday at 12:43 PM
/lp group owner meta addprefix 11 &cOwner>
ItzZaexYTToday at 12:43 PM
ohh
no what you want to do
is
go into the files
and edit the config
but i dont know that
im  no expert
maybe ask a mod or some1?

**Comment by lucko** [comment]
Add quotes

`/lp group owner meta addprefix 11 "&cOwner> "`
