### ISSUE TITLE
Update primary group after adding group by "parent add".

### ISSUE THREAD

**Issue by Nikox3003** [lucko/LuckPerms#2335]
Hi,
I wanted to get player's highest group from database (I can't use the API, I'm not writing plugin). I thought about using player's "primary group", but it doesn't update if group have been added by "parent add".
If this behaviour was intended, consider it as suggestion / question.

**Comment by lucko** [comment]
By default the plugin doesn't actually use the stored field in the database.

https://github.com/lucko/LuckPerms/wiki/Configuration#primary-group-calculation

It's set to `parents-by-weight` usually. :)
