### ISSUE TITLE
Bungeecord Context seperation

### ISSUE THREAD

**Issue by ShockCharge** [lucko/LuckPerms#2336]
Image: https://media.discordapp.net/attachments/241667244927483904/714838619289813241/unknown.png?width=610&height=478

Imgur: https://imgur.com/a/agKCi66

Here's my question: 
ShockChargeToday at 5:05 PM
have anyone answered my question?
about seperating a server=bungee to be only used in a specfic server context like server=survival but can't be used on server=faction
or  i need to use this instead?
ShockChargeToday at 5:11 PM
i'm asking about perms
since the permission requires a bungee, is there any way Luckperms has a method on seperating those access, network servers already done this, and i myself don't know how to make that possible.
they're also using Luckperms
TobiToday at 5:16 PM
So you want a permission for a bungee plugin only on the Bungee if the user is in a specific server? Try using server=bungee world=survival to target the survival server
ShockChargeToday at 5:16 PM
exactly
and the context doesn't allow that
or i'm just dumb asf
okay let me try this

Tobi asked me to try-it-out but after i said it ben ask me to report it as a bug, so here you go! :)

**Comment by ShockCharge** [comment]
Already tried that, it doesn't work.

**Comment by lucko** [comment]
It does, in all of your examples you were using `server=bungee server=survival`, the backend server is considered a "world" in `/lpb` land.
