### ISSUE TITLE
Web Editor Duplicates User

### ISSUE THREAD

**Issue by mrvander18** [lucko/LuckPerms#2337]
After following the install instructions everything seems to work just fine. When I use the /lp user info command, it shows assignment into the correct group. When I check the permission info, it shows the correct luckperms.* (wildcarded) permission.

Now when I launch the web editor, the same user is listed twice with double the permissions. So it looks like everything is configured correctly but the web interface is querying and outputting a duplicate row.

![Annotation 2020-05-26 101911](https://user-images.githubusercontent.com/65966034/82918637-9ed68580-9f3a-11ea-8e09-0288dc1d5cca.png)

**Comment by Laarryy** [comment]
Try updating to the latest from https://luckperms.net this issue was fixed (or should've been)

**Comment by mrvander18** [comment]
Doh! I just installed the plugin from a hosting repository - didn't see the code was just updated last week. Thanks!
