### ISSUE TITLE
BungeeCord Luckperms Jar

### ISSUE THREAD

**Issue by ShreyasAyyengar** [lucko/LuckPerms#2338]
Is there difference (or exsistence) between the jar file that is used for spigot servers (the plugins folder in the spigot server) and the jar file that is used to be put in the bungee cord server (the bungee cord plugins folder). 

If there is a Luckperms for Bungeecord can someone link it?

Thanks,
Shreyas

**Comment by Tobi406** [comment]
As Bungee and Spigot are different, plugins are also different, altough LuckPerms' functions are the same in almost all veresions of it (some may change depending on the platform)

The different versions are available from https://luckperms.net/download

**Comment by ShreyasAyyengar** [comment]
Thanks! That’s the answer I was looking for thank you. So the download that says Bukkit on thr website that you provided, I should put that in every backend server, and the one that’s says bungee cord I should put that in the bungee cord plugins folder correct?

Thanks,
Shreyas

**Comment by Tobi406** [comment]
Yes, that's correct :+1:

**Comment by ShreyasAyyengar** [comment]
Ahhh! Thank you Tobi! Best support ever

**Comment by ShreyasAyyengar** [comment]
And just to add on, I need to set up MySQL on every configuration file related to luckperms right?

**Comment by Tobi406** [comment]
Yes, all servers (BungeeCord and your Spigot servers) need to use the same database if you want permissions shared accross them.

**Comment by ShreyasAyyengar** [comment]
Ahh okay. Could you give me a link to a video or a wiki on how to set up a mysql account for Mac?

**Comment by Tobi406** [comment]
https://dev.mysql.com/doc/mysql-osx-excerpt/5.7/en/osx-installation-pkg.html might help you

**Comment by Tobi406** [comment]
Or https://dev.mysql.com/doc/mysql-osx-excerpt/5.7/en/osx-installation.html

**Comment by ShreyasAyyengar** [comment]
Thanks my guy! Absolutely great plugin by the way. Couldn’t be better

**Comment by ShreyasAyyengar** [comment]
I’ve set up mySQL thing but I can’t find my database which I am supposed to put in the config. I know the username is root, I have set my own password, I believe I can keep the host as localhost but I don’t know that my database is or how to find it on Mac. Can you help?

**Comment by lucko** [comment]
You probably need to create a database.

If you've got a MySQL shell running, you can use `CREATE DATABASE luckperms;` - then your database name will be luckperms.
