### ISSUE TITLE
LuckPerms problem

### ISSUE THREAD

**Issue by PszemoPL** [lucko/LuckPerms#2339]
hello I have a problem with luckperms because my players can't connect to the server if they want to connect I write something like this:
[LuckPerms] Another plugin has cancelled the connection for fa042274-c242-3df8-85f6-9dad62ab7ed1 - szlafroczek690. No permissions data will be loaded.
and on the player's side something like this:
do you believe this is an issue? contact us  with your  analyze ID:ofW8fg

**Comment by lucko** [comment]
> Another plugin has cancelled the connection for fa042274-c242-3df8-85f6-9dad62ab7ed1 

It tells you what the issue is.

Another plugin on your server is blocking their connection before LP handles it.

**Comment by molor** [comment]
@lucko, can you please add option to turn off this message? We have our custom disconnection logger and this message is useless for us and just fills the server log with unnecessary information every time. Thanks!

**Comment by HauserGrim** [comment]
> > @lucko, can you please add option to turn off this message? We have our custom disconnection plugin/logger and this message is useless for us and just fills the server log with unnecessary information every time. I can open a new issue if needed. Thanks!
> 
> this should be done! when im getting bot attack, these logs on console are lagging the server. please ..

+1

**Comment by Turbotailz** [comment]
Please open a new issue with the suggestion of turning the message off instead of bumping a closed issue.
