### ISSUE TITLE
Ability for certain tracks to have ability to not show prefix stacking type: suggestion

### ISSUE THREAD

**Issue by Hallowhead1** [lucko/LuckPerms#2340]
As the title states:

For my staff track I don't want to see random player ranks & even donation ranks - just staff ranks.

**Comment by Laarryy** [comment]
Use per-group chat formatting and PlaceholderAPI and you can use the Luckperms expansion provided prefix element placeholder for highest on track staff for all staff groups.

**Comment by lucko** [comment]
Or can also probably be achieved by tweaking the metastacking options in the LP config.
