### ISSUE TITLE
AdvancedBan BungeeCord Plugin Permissions are not showing up as an autofill in LuckPerms Web Editor

### ISSUE THREAD

**Issue by ShreyasAyyengar** [lucko/LuckPerms#2341]
Hi, 

I have been trying to figure out this problem for a while now. I contacted the AdvancedBan support but they couldn't pin the problem down and asked me to ask the LuckPerms support. 

I have a plugin called AdvancedBan (which is a custom ban plugin) which has it's own permission for player and stuff. I have installed LuckPermsBungee & AdvancedBan on my BungeeCord Plugins folder, and 3 LuckPermsSpigot files on my backend spigot servers. 

Usually with LuckPerms if I open the editor, I can set permissions and create groups all in the web editor. When I add a permission, usually the web editor will try to autocomplete the permission I intend to modify. I can see that permission like EssentialsX, LuckPerms, and vault are all showing up which is good, but for some reason I can't see any AdvancedBan permissions in the LuckPerms web editor. Even when I try to manually type one of the permission, for example ab.ban.perma, once I apply the edits, it still doesn't seem to work. I tried contacting advancedban support but they couldn't narrow it down to see what the problem is. 

If anyone could help, or is in the same position could you please offer any solutions?

Thanks,
Shreyas Ayyengar

**Comment by lucko** [comment]
The permission autocompletions don't sync between servers (or between Spigot / Bungee).

So, if you run `/lp editor`, it won't show completions for plugins installed on your proxy, and if you run `/lpb editor`, it won't show completions for plugins installed on your backend Spigot servers.

There's also no way for permissions to be registered as such on BungeeCord, so LuckPerms will just pick them up over time as plugins check for them.

Hope that helps :)
