### ISSUE TITLE
MySQL MariaDB SSL Problem

### ISSUE THREAD

**Issue by gwladyka** [lucko/LuckPerms#2344]
Hello. 
I have a problem connecting to the database via SSL. I have created the user "luckperms" and a database with the same name. 
Without SSL encryption the connection occurs, but whenever I turn it on in config.yml, and using ALTER I give REGUIRE SSL to the user, I get the errors. 
No plugin connects to SSL, not just luckperms, so it's not the plugin's fault... I think so. However, when I connect using HeidiSQL or other software, there are no problems. 
Thanks...

https://pastebin.com/GQFMcETG <- errors.
![ssl](https://user-images.githubusercontent.com/60066487/83322168-b8870e00-a255-11ea-9704-5c0d28dd4cc7.png)
![cipher](https://user-images.githubusercontent.com/60066487/83322171-bcb32b80-a255-11ea-91e6-f261ae382cba.png)
![TLS](https://user-images.githubusercontent.com/60066487/83322335-0ea88100-a257-11ea-9601-d0318a7694e9.png)

**Comment by lucko** [comment]
The important part of the error is:
> Access denied for user 'luckperms'@'x.x.x.x'

There are some tips here:
https://github.com/lucko/LuckPerms/wiki/Storage-system-errors
