### ISSUE TITLE
Luckperms help

### ISSUE THREAD

**Issue by Rqz0r** [lucko/LuckPerms#2345]
So i have this problem where it says [world] and then the prefix... anyone that can help??

**Comment by Tobi406** [comment]
Does it also display the `[world]` when you do `/lp user <user> info`?

If it does: Then just change the prefix.

If it doesn't: Then it's an issue with another plugin, I suspect MultiverseCore. 

Maybe it is the `prefixchat` setting? https://github.com/Multiverse/Multiverse-Core/wiki/config.yml#multiverse-2-core-sample-config
