### ISSUE TITLE
LP not returning groups

### ISSUE THREAD

**Issue by L0L1NC3K** [lucko/LuckPerms#2346]
So basically i wanted to format chat messages for every group separatly, but it seems like lp is not returning groups to essentialsX Chat as well as TAB List. i used proper weight system and followed your wiki on how to create groups since i am old school PEX user.

**Comment by BrainStone** [comment]
Make sure you put the group names lowercased in the essentials config

**Comment by L0L1NC3K** [comment]
![image](https://user-images.githubusercontent.com/55282950/83339220-f1fa6080-a2cb-11ea-9c86-1bb4ac8eaa0e.png)
![image](https://user-images.githubusercontent.com/55282950/83339231-05a5c700-a2cc-11ea-89b8-e5de7dd7b233.png)
![image](https://user-images.githubusercontent.com/55282950/83339241-18200080-a2cc-11ea-9f95-84d1ecd6b094.png)

These are the screens of config in essentials, LP, and how chat is showing it

**Comment by Laarryy** [comment]
If you set a displayname, the name you use in other plugin configs has to match the displayname. This is because the displayname is the group's name as far as vault and PAPI are concerned and so they will see the displayname only.

**Comment by L0L1NC3K** [comment]
So i downloaded papi, I completely forgot about it, swapped {DISPLAYNAME} with %player_name%, still same response in chat i guess essentials cant find that group and is using some default format

**Comment by Laarryy** [comment]
EssX doesn't play nice with PAPI by default like it does with vault. You'll need another plug-in for it. If the EssentialsX config, when using either {DISPLAYNAME} or {USERNAME} and the displayname of the group rather than its actual name, (for mod, use Mod instead, for example) then it's an EssX problem. If the prefix for a user shows up properly in `lp user <username> info` then Luckperms is doing its job

**Comment by L0L1NC3K** [comment]
I do not have issues with names or papi, my problem is that i have a group named mod in LP and EssX do not detect this group so it's not using group formating. That's the reason for that default format in chat.

**Comment by Laarryy** [comment]
I understand, this is because the name of the group in the Essentials config needs to case match the displayname of that group if one is set. Please try it

**Comment by L0L1NC3K** [comment]
group name is "mod" and displayname of group is "Mod" i tried both and still default format, nvm i'll just use default format and format colors in prefixes and suffixes.
