### ISSUE TITLE
Minor error on wiki?

### ISSUE THREAD

**Issue by CrypticCabub** [lucko/LuckPerms#2347]
in the Context page for the LuckPerms wiki is the following statement:

"Crucially, for a permission/parent/meta value to apply, the player must satisfy all of the contexts required by the value. (when I say satisfy, I mean their current context set must contain all of the contexts required by the value **- or mathematically, the players context set must be a subset of the value's context set)**"

Should this not say that the player's context must be a superset of the value's context (or conversely the value's context must be a subset of the player's context)? 

Apologies if my mathematical set vocabulary is faulty in this circumstance.

**Comment by Laarryy** [comment]
I think you have a good point but that's been recently changed - you no longer have to fulfill all the values, just one of each type. A rewrite is in progress.

**Comment by lucko** [comment]
Wiki has been updated to resolve this, thanks :)
