### ISSUE TITLE
LuckPerms Console Spam (Issue)

### ISSUE THREAD

**Issue by DeveloperJackYT** [lucko/LuckPerms#2352]
**Heyyo!** Recently, I've been using luckperms to deal with my permissions and have started to notice some console spam. I've been using luckperms for a long while now and never seen this before. This is also only happening on my hub, and not my bungeecord, (We have other servers, but they aren't setup / don't have plugins yet)
The spam lines I'm noticing are:

`02.06 11:22:10 [Server] Startup 15:22:10.000 [luckperms-hikari housekeeper] DEBUG me.lucko.luckperms.lib.hikari.pool.HikariPool - luckperms-hikari - Pool stats (total=10, active=0, idle=10, waiting=0)` - This one spits every 30 seconds
and this one
`02.06 11:21:10 [Server] Startup 15:21:10.330 [luckperms-hikari connection closer] DEBUG me.lucko.luckperms.lib.hikari.pool.PoolBase - luckperms-hikari - Closing connection me.lucko.luckperms.lib.mysql.jdbc.JDBC4Connection@5a12b2dc: (connection has passed maxLifetime)` - It seems to happen whenever it wants

Any support would be appreciated, just want to understand the messages and hopefully stop them if it possible 😄

**Comment by lucko** [comment]
Erm, you need to tweak your Log4j config to exclude the `DEBUG` entries.

This should be done for you though - are you using a custom server? Or custom log4j config?

**Comment by DeveloperJackYT** [comment]
To my knowledge, I dropped in the LP.jar, and the same on my bungeecord, hooked them both up to the mysql database and made my groups :/

@lucko

**Comment by DeveloperJackYT** [comment]
@lucko ?

**Comment by lucko** [comment]
It doesn't happen on a clean install, so it's definitely something you've changed or done differently.

Sorry I don't really know much more than that

**Comment by DeveloperJackYT** [comment]
Do you think I should remove LuckPerms from my Hub and put it back? Might that solve it?

**Comment by lucko** [comment]
Try to reproduce it on a clean server I guess is probably where I'd start.

Anyway, sorry either way, this isn't an LP issue. The server controls the logging for the most part.
