### ISSUE TITLE
MySQL Error

### ISSUE THREAD

**Issue by RPGMais** [lucko/LuckPerms#2355]
My server run in offline mode.
Full error in pastebin.
https://pastebin.com/VDpx7QQW

text 10.81 KB
09:22:48 [WARNING] [LuckPerms] A permission check was made for player pedrosz - b716883e-290b-3185-b23a-e4f1ecd2a0da, but LuckPerms does not have any permissions data loaded for them. Perhaps their UUID has been altered since login?
09:22:48 [SEVERE] java.lang.Exception
09:22:48 [SEVERE]   at me.lucko.luckperms.bungee.listeners.BungeePermissionCheckListener.onPlayerPermissionCheck(BungeePermissionCheckListener.java:67)
09:22:48 [SEVERE]   at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)

**Comment by darbyjack** [comment]
If it runs in offline mode, it shouldn't have changed, did you accidentally try load something in online mode?
