### ISSUE TITLE
Error on 'permissions' in 'field list'

### ISSUE THREAD

**Issue by BBSnowIce** [lucko/LuckPerms#2357]
Hi,
  I tried to update luckperms on the last version and when I start my server it seems to be no problems but when I wait a couple of minutes, I got this message https://onyxworld.fr/upload/notepad%2B%2B_52arOxSTFE.png and permissions are not set correctly anymore.

**Comment by lucko** [comment]
That's a weird error - have you manually edited the database at all? Seems like something has corrupted there.

Easiest way to fix is probably to export all of your data (`/lp export`), wipe the DB tables and then re-import
