### ISSUE TITLE
WARNING: An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by Joeairforce82** [lucko/LuckPerms#2359]
>WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by me.lucko.luckperms.common.dependencies.classloader.ReflectionClassLoader (file:/C:/Users/KendallCraft/Desktop/1.15.2%20Server/plugins/LuckPerms-Bukkit-5.1.26.jar) to method java.net.URLClassLoader.addURL(java.net.URL)
WARNING: Please consider reporting this to the maintainers of me.lucko.luckperms.common.dependencies.classloader.ReflectionClassLoader
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

 [Server thread/INFO]: [LuckPerms] Loading LuckPerms v5.1.26
[23:08:56] [ForkJoinPool-2-worker-51/INFO]: [LuckPerms] It is safe to ignore any warning printed following this message starting with 'WARNING: An illegal reflective access operation has occurred, Illegal reflective access by me.lucko.luckperms.common.dependencies.classloader.ReflectionClassLoader'. This is intended, and will not have any impact on the operation of LuckPerms.

**Comment by lucko** [comment]
I mean it literally tells you...

> It is safe to ignore any warning printed following this message 

> This is intended, and will not have any impact on the operation of LuckPerms

**Comment by Joeairforce82** [comment]
It also said to consider reporting it, so I did.
