### ISSUE TITLE
[LP] Permission Data Could Not Be Loaded. Please Contact An Administrator.

### ISSUE THREAD

**Issue by DiscoDuck151** [lucko/LuckPerms#236]
[LOG] Disconnecting com.mojang.authlib.GameProfile@47b2678d[id=2e48bffa-2617-3052-b445-0936e3c23c1d,name=DiscoDuck,properties={},legacy=false] (/127.0.0.1:61087): §7§l[§b§lL§3§lP§7§l] §cPermissions data could not be loaded. Please contact an administrator.

I am using 3.0.0 luckperms on bukkit. Everytime I try to join I get this error.  I have seen similar issues like this around but I could never find a solution to fixing the issue. Please help as soon as possible.
-DiscoDuck

**Comment by lucko** [comment]
Can you try updating to the latest dev build, and then pastebin your full log file.

**Comment by DiscoDuck151** [comment]
Oh I seemed to have fixed it. I was running it on an outdated bukkit server and when I downloaded the latest server it worked.
