### ISSUE TITLE
Contexts are broken

### ISSUE THREAD

**Issue by rcmaehl** [lucko/LuckPerms#2360]
Contexts appear to be broken on 5.1.43

I am using the web editor to apply contexts. It should be noted that "server" is not selectable as a key despite it being a listed autocomplete. I am using the names of my servers as I would type them in /server in bungee.

**Comment by Turbotailz** [comment]
> It should be noted that "server" is not selectable as a key despite it being a listed autocomplete.

Can you elaborate more on this?

**Comment by underscore11code** [comment]
> I am using the names of my servers as I would type them in /server in bungee.

Have you set server names in your `config.yml`s on all your servers?

**Comment by rcmaehl** [comment]
> > I am using the names of my servers as I would type them in /server in bungee.
> 
> Have you set server names in your `config.yml`s on all your servers?

My god. I am an idiot. I thought that was for server TYPE. e.g. global perms vs bungee perms. It all makes sense.
