### ISSUE TITLE
[BUG / REQUEST ]  Allow and Deny not processed correctly

### ISSUE THREAD

**Issue by zettlinger** [lucko/LuckPerms#2361]
Hi i noticed that if a lower level deny gets put as an allow higher up it works correctly

BUT ... When on the SAME level i have a ALLOW all and add a DENY 1 world it will still ALLOW ALL

Expected behaviour is to load all ALLOW first per level, overwriting lower ones then layering it with the DENIES for that level.

aka i have someone added to a group for all worlds with the perms belonging to that but want to DENY the perms for only one (anarchy) world.

i could list all worlds except the one but then if i add more worlds i have to keep adding them.
So if possible do ALLOW first then DENY so if i add more worlds they will be allowed and the one i dont want denied

**Comment by Laarryy** [comment]
Global contexts should be overridden by specific ones, so if you set it to allow a permission everywhere and then set the same permission to false in a world, the false one should be taking precedence. If you're sure it isn't, would you mind sending your editor link and describing which group's perms are not applying. The Advanced Setup section of the wiki explicitly covers this as something that should already be happening, so any more info would be appreciated! Thanks!

**Comment by zettlinger** [comment]
basically my head builder wanted his perms taken off on the anarchy server  

so he had: 
group.headbuilder  TRUE NEVER NONE

to take his perms on anarchy i added:

group.headbuilder FALSE NEVER SERVER ANARCHY

this did not take away his permissions.
I ended up just setting the global one false so now he has no perms till he asks me to reinstate them

**Comment by Laarryy** [comment]
Make sure that server: anarchy matches the name of the actual anarchy server as defined in the LP config

**Comment by zettlinger** [comment]
just checked (i know i made that error before when copying to a new server...)

it is: server: anarchy  so correctly put, when he is on again (tomorrow most likely since it is now almost 5.30 AM here) i will try once more

**Comment by zettlinger** [comment]
Ok 2nd test same result, i pasted his permission set (the one where the FALSE doesnt overwrite the TRUE below

http://prntscr.com/svdenq

**Comment by lucko** [comment]
Overriding group inheritances with false nodes is not supported at the moment - and probably not something I plan to support in the future either, sorry.
