### ISSUE TITLE
Implement adding values via bulk editing

### ISSUE THREAD

**Issue by bartyrealms** [lucko/LuckPerms#2362]
Currently the documentation states that bulk editing can only update or remove values. This means that you get to dive into SQL commands to execute it yourself instead of using the simplified bulk editing commands that make updating/removing values simple.

https://github.com/lucko/LuckPerms/wiki/Bulk-Editing

**Comment by lucko** [comment]
Hey thanks for the suggestion - I've made a note of this on the overall bulk update improvements issue.
