### ISSUE TITLE
Connection with command blocks and @p, @s etc.

### ISSUE THREAD

**Issue by Foxagone** [lucko/LuckPerms#2364]
Hi,

i'm starting a server and i want to make an execute command to command block that will remove your permissions if you are on certain location. It didn't work but that's lowkey usual with plugins so I tried it with /setblock redstone_block to activate a command block with the command that removes the permission but I figured out that luckperms isn't working with @p,@a,@s,@e,@r so my question is if it is fixable or I have to find another way to remove permission.

**Comment by Tobi406** [comment]
Try turning on the `resolve-command-selectors` option in the config

**Comment by Foxagone** [comment]
> Try turning on the `resolve-command-selectors` option in the config

Yeah I've tried that too, but it still is not working

**Comment by lucko** [comment]
What server type / version?
