### ISSUE TITLE
AdvancedBan Permissions not Showing Up with LuckPerms

### ISSUE THREAD

**Issue by ShreyasAyyengar** [lucko/LuckPerms#2365]
Steps to Reproduce the problem

1. Download LuckPerms and AdvancedBan
2. Put AdvancedBan in your BungeeCord 
3. Plugins folder (not the individual spigot servers) just the Bungeecord Plugins folder
4. Put the LuckPerms plugin in any server plugin folder you like.
5. Put LuckPermsBungee in your bungee cord plugin folder
Lauch MC
Go into your BungeeCord server and do /server (Server you put luck perms in)
Enter the console command /lp user permission set luckperms.* true
Do /lp editor.
Open the assigned link
Try to do any ab. perms. (It won't autofill)
If it doesn't autofill, try just inputting any perm manually like ab.ban.perma
Click the save changes at the top of the luck perms editor, and copy and paste the command it gives you into your game (player command).

When you try to do /ban 

It will say,
AdvancedBan You don't have perms for that (or somthing similar)
When I try to add a perm for AdvancedBan, I try to add a perm to luck perms web editor by just doing ab. usually the web editor will complete the perm I am trying to input, but nothing shows up for me with AdvancedBan at all.

Even when I manually type a perm into luck perms such as ab.ban.perma, when I apply the edits, in game it still doesn't work. I can do the command from the console so I know the commands work I just don't know why perms doesn't

Advanced ban is in my bungee plugin folder. 

While luck perms is in my spigot server.

Any help?

Sincerely
Shreyas Ayyengar

**Comment by benwoo1110** [comment]
Have you synced all your LuckPerms on all server (including bungeecord) to a common sql database?

**Comment by underscore11code** [comment]
Ensure your bungee network has been properly synced as per this guide: https://luckperms.net/wiki/Network-Installation.
