### ISSUE TITLE
Import error?

### ISSUE THREAD

**Issue by AbooseYou** [lucko/LuckPerms#2366]
https://paste.helpch.at/tovefahigi.md

i get this error when i import is there any fix for this

**Comment by Laarryy** [comment]
What version did you export from? If it was v4, you need to first update that to v5 and then export.

**Comment by AbooseYou** [comment]
Was export on v5 and I’ll try .json.gz  later to day

**Comment by AbooseYou** [comment]
so i did some testing i exported exported  it on v5.1.47 and then  switched MySQL and then try to import on v5.1.47 just on a new database and i get the below error

https://paste.helpch.at/elusutaval.md

**Comment by Laarryy** [comment]
@lucko would be able to tell you exactly what the error points to but I imagine it means you have an invalid context key/value somewhere- what contexts do you use? It would be beneficial if you ran `lp editor` and sent that link here

**Comment by AbooseYou** [comment]
i get this when i do lp editor

https://paste.helpch.at/ekibobuyow.md

**Comment by benwoo1110** [comment]
1. can you send you full startup log?
2. did you use storage method such as yaml before and edit the file directly?
3. did you unzip / edit the backuptest.json.gz file directly?

**Comment by AbooseYou** [comment]
1. https://paste.helpch.at/ujuqufuvud.md
2. no been On mysql the hole time
3. no didnt even move it out of the folder it backed up to

**Comment by lucko** [comment]
You have another plugin which is shading the LuckPerms API into its jar.
