### ISSUE TITLE
Prefix color affects texting chat color

### ISSUE THREAD

**Issue by tom2405** [lucko/LuckPerms#2367]
When I set a specific prefix for a group, I se a color for the username it’s self as well “[&4&lAdmin&r] &4” for the admin group in this case it should set the username only to be red. Whenever the person in the admin group types In chat it shows the same color as the name. Is there any way I can disable that

**Comment by underscore11code** [comment]
LuckPerms is not responsible for chat. We only can send info such as prefixes and suffixes to other plugins, and they do what they want with it. Consult your chat plugin's configuration.

**Comment by tom2405** [comment]
Oh ok thank you so much for your help. Have a good day

**Comment by SamPoulton** [comment]
A quick fix for this would to be include a &r formatter after your chat message.
For example: 
`%displayname%&r: %message%`

**Comment by tom2405** [comment]
Yeah that makes sense. Thank you for your help :)

**Comment by OffendedDragon** [comment]
> A quick fix for this would to be include a &r formatter after your chat message. For example: `%displayname%&r: %message%`

This is sufix command??

**Comment by lucypoulton** [comment]
> This is sufix command??

necropost 100
In all seriousness, that goes in your chat format.
