### ISSUE TITLE
Doesn't Respond to any commands

### ISSUE THREAD

**Issue by EdwardYork1** [lucko/LuckPerms#2368]
I am running the plugin on a CraftBukkit Server (latest) and i am trying to set up seperate teams and i don't seem to get any response. I am using the Bukkit Legacy install of the plugin, Any ideas? :/

**Comment by benwoo1110** [comment]
1. Whats is your server version and type?
2. Is it on online-mode=false server?
3. Do you get any errors in console?

**Comment by EdwardYork1** [comment]
1.15.2, CraftBukkit
??
I don't seem to get any errors in console.

**Comment by Laarryy** [comment]
Why Bukkit Legacy for 1.15.2? 
Use the latest from https://luckperms.net (Bukkit, not Legacy)

**Comment by EdwardYork1** [comment]
I updated the file and now it won't show as installed anymore.

**Comment by Laarryy** [comment]
can you use https://bytebin.lucko.me to copy/paste your entire startup log into and send the link it makes

**Comment by EdwardYork1** [comment]
https://bytebin.lucko.me/hogxwgtdqu

**Comment by Laarryy** [comment]
looks like the file you're using is corrupted somehow - if you're using a host, upload it to the server with filezilla. 

If you aren't, try redownloading and use the latest one, from https://luckperms.net this time. 

If that still doesn't work, try using Paper (https://papermc.io) or spigot as server software.

If Paper doesn't work, and you are also doing all the previous steps, let me know.

**Comment by EdwardYork1** [comment]
Perfect Thank you. i changed to paper. :)
