### ISSUE TITLE
/ban commands (or similar type) isn't recognised to advancedban

### ISSUE THREAD

**Issue by ShreyasAyyengar** [lucko/LuckPerms#2369]

**Comment by BrainStone** [comment]
When you solve something before someone answered, don't just delete the post. Leave it and state that you solved (ideally how you solved it too).

**Comment by ShreyasAyyengar** [comment]
Sorry, I just posted my issue to the wrong support page,my problem has noting todo with luckoerms. 

> When you solve something before someone answered, don't just delete the post. Leave it and state that you solved (ideally how you solved it too).
