### ISSUE TITLE
SportPaper support

### ISSUE THREAD

**Issue by Lmmb74** [lucko/LuckPerms#2372]
Hello. Everytime the plugin loads the following [error](https://hastebin.com/irotiyefeb.sql) is thrown, but it then says that the plugin is successfully enabled. I have not tested further. The current server software I'm using is [this one](https://github.com/Electroid/SportPaper) and I tried using the Bukkit build 5.1.51. Tell me if you need any more information.

**Comment by Lmmb74** [comment]
Just checked and it seems that SporPaper patched the PermissibleBase attachments from a List to a Set. You can check it [here](https://github.com/Electroid/SportPaper/blob/76145e71f69c32ee0dd6333233091038ee2c7dd9/patches/api/0024-Improve-Permissible-interface.patch#L126).

**Comment by BrainStone** [comment]
The incompatibility is known and attempts to fix it have been undertaken. But it’s not looking good as the changes are problematic.

**Comment by Lmmb74** [comment]
Oh. Sorry, I didn't know. Should I close this issue then?

**Comment by Lmmb74** [comment]
Just read the other issues. I'll just close this one. And thanks.

**Comment by lucko** [comment]
My understanding was that SportPaper were going to patch this at their end :)

**Comment by Lmmb74** [comment]
Yup, read that. Just submitted an issue there to know how's it going on.
