### ISSUE TITLE
Support for * in Usernames

### ISSUE THREAD

**Issue by TheMattVid** [lucko/LuckPerms#2373]
Hello, I am using GeyserMC to allow for cross-compatibility between Bedrock and Java. Bedrock users are all given usernames beginning with a "*" in order to ensure that nobody with an identical Java username will have their account taken over.

Each of these players are assigned a unique UUID and have their permissions handled properly in the LuckPerms editor. However, when trying to change one of these user's permissions via LuckPerms command, it does not work. There is the error *<user> is not a valid username/uuid.

Adding support for the * character within player usernames would be a huge help for me when running a weekly event that I do on my server, as well as a Prison server, where players need to be upgraded automatically via command.

**Comment by lucko** [comment]
Set this option to true:

https://github.com/lucko/LuckPerms/blob/97a0dbebcbba6124c400d242eae649ef896b1243/bukkit/src/main/resources/config.yml#L609-L613

**Comment by NBS-Paste** [comment]
what file is this and is it all of the colored lines? if it is the config.yml i couldnt find any of those in it.

**Comment by LeotomasMC** [comment]
this issue was closed over 2 years ago...

**Comment by NBS-Paste** [comment]
well is there a new fix then? it still wont work

**Comment by LeotomasMC** [comment]
did you change that option?

**Comment by NBS-Paste** [comment]
i tried to cahnge it but none of it was in the config.yml

**Comment by NBS-Paste** [comment]
also rather than * it is a .

**Comment by LeotomasMC** [comment]
> i tried to cahnge it but none of it was in the config.yml

then either your luckperms version is out-of-date, or your config was generated on an older version and you just need to manually add that option.

**Comment by NBS-Paste** [comment]
would copping it all and pasting it over  my current config work?

**Comment by OmegaWeaponDev** [comment]
> what file is this and is it all of the colored lines? if it is the config.yml i couldnt find any of those in it.

Instead of necroposting. Please post a new issue if the above solution does not resolve the issue for you.
