### ISSUE TITLE
Is there a way to make the actual chat message depending on the rank

### ISSUE THREAD

**Issue by ShreyasAyyengar** [lucko/LuckPerms#2375]
I’m using bungee cord luckperms with MYSQL and I was wondering how to change the actual message color and formatting depending on the rank. Like for example, I have an owner prefix setup as “&4&l[OWNER] “ I want the chat to show up as bold if a person has an owner rank. The same thing goes to my other groups and ranks. The same thing also with the username. So if someone is a mod they will have a yellow tag. This information would be really helpful. I also have EssentialsX and EssentialsChat installed. 

Best,
Shreyas

**Comment by l1ttleO** [comment]
You need to either
1) Use group formats for EssentialsXChat
2) Remove every color code after the prefix in normal chat format

**Comment by ShreyasAyyengar** [comment]
> You need to either
> 
> 1. Use group formats for EssentialsXChat
> 2. Remove every color code after the prefix in normal chat format

Could you explain that a little more? 

Thanks

**Comment by l1ttleO** [comment]
> > You need to either
> > 
> > 1. Use group formats for EssentialsXChat
> > 2. Remove every color code after the prefix in normal chat format
> 
> Could you explain that a little more?
> 
> Thanks

You need to change config.yml in "CHAT" section
I can help with that

**Comment by ShreyasAyyengar** [comment]
Okay, if you want, I can send you my config file or you could just tell me how to edit it

**Comment by l1ttleO** [comment]
It's how you prefer :). It would be better if you send it tho

**Comment by ShreyasAyyengar** [comment]
Okay, how do I send it on here?

**Comment by l1ttleO** [comment]
We need to talk thru something else. Discord?

**Comment by ShreyasAyyengar** [comment]
Sure, but can we do it tomorrow, (it’s late where I am right now)

If you can discord tomorrow please let me know the time in your time zone

**Comment by Laarryy** [comment]
https://discord.gg/luckperms

While this isn't LuckPerms related, we can help you in #off-topic to set up per group chat formatting.

**Comment by ShreyasAyyengar** [comment]
Okay, do I just go in and state my concern?
