### ISSUE TITLE
Is there an Event like an GroupChangeEvent

### ISSUE THREAD

**Issue by byRaqe** [lucko/LuckPerms#2376]
Dear Developer of Luckperms,

I would like to ask if there is an Event when a Group of a User Change

**Comment by HookWoods** [comment]
This: https://github.com/lucko/LuckPerms/blob/master/api/src/main/java/net/luckperms/api/event/user/UserDataRecalculateEvent.java (I use this one to change my scoreboard prefix for example and it works great)
Or this: https://github.com/lucko/LuckPerms/blob/master/api/src/main/java/net/luckperms/api/event/user/track/UserTrackEvent.java

**Comment by lucko** [comment]
Or `NodeMutateEvent` :)
