### ISSUE TITLE
LuckPerms bungeecord error

### ISSUE THREAD

**Issue by GoldenGlassBR** [lucko/LuckPerms#2377]
>.... [22:50:22 ERROR]: java.lang.Exception
>.... [22:50:22 ERROR]: at me.lucko.luckperms.bungee.listeners.BungeePermissionCheckListener.onPlayerPermissionCheck(BungeePermissionCheckListener.java:67)
>.... [22:50:22 ERROR]: at sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source)
>.... [22:50:22 ERROR]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>.... [22:50:22 ERROR]: at java.lang.reflect.Method.invoke(Method.java:498)
>.... [22:50:22 ERROR]: at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
>.... [22:50:22 ERROR]: at net.md_5.bungee.event.EventBus.post(EventBus.java:47)
>.... [22:50:22 ERROR]: at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:453)
>.... [22:50:22 ERROR]: at net.md_5.bungee.UserConnection.hasPermission(UserConnection.java:565)
>.... [22:50:22 ERROR]: at be.woutdev.bungeestaffchat.listeners.PlayerListener.onPlayerChat(PlayerListener.java:48)
>.... [22:50:22 ERROR]: at sun.reflect.GeneratedMethodAccessor42.invoke(Unknown Source)
>.... [22:50:22 ERROR]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>.... [22:50:22 ERROR]: at java.lang.reflect.Method.invoke(Method.java:498)
>.... [22:50:22 ERROR]: at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
>.... [22:50:22 ERROR]: at net.md_5.bungee.event.EventBus.post(EventBus.java:47)
>.... [22:50:22 ERROR]: at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:453)
>.... [22:50:22 ERROR]: at net.md_5.bungee.connection.UpstreamBridge.handle(UpstreamBridge.java:150)
>.... [22:50:22 ERROR]: at net.md_5.bungee.protocol.packet.Chat.handle(Chat.java:60)
>.... [22:50:22 ERROR]: at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:105)
>.... [22:50:22 ERROR]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
>.... [22:50:22 ERROR]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
>.... [22:50:22 ERROR]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
>.... [22:50:22 ERROR]: at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
>.... [22:50:22 ERROR]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
>.... [22:50:22 ERROR]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
>.... [22:50:22 ERROR]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
>.... [22:50:22 ERROR]: at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
>.... [22:50:22 ERROR]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
>.... [22:50:22 ERROR]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
>.... [22:50:22 ERROR]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
>.... [22:50:22 ERROR]: at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
>.... [22:50:22 ERROR]: at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
>.... [22:50:22 ERROR]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
>.... [22:50:22 ERROR]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
>.... [22:50:22 ERROR]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
>.... [22:50:22 ERROR]: at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
>.... [22:50:22 ERROR]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
>.... [22:50:22 ERROR]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
>.... [22:50:22 ERROR]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
>.... [22:50:22 ERROR]: at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
>.... [22:50:22 ERROR]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
>.... [22:50:22 ERROR]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
>.... [22:50:22 ERROR]: at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
>.... [22:50:22 ERROR]: at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
>.... [22:50:22 ERROR]: at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)
>.... [22:50:22 ERROR]: at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
>.... [22:50:22 ERROR]: at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
>.... [22:50:22 ERROR]: at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
>.... [22:50:22 ERROR]: at java.lang.Thread.run(Thread.java:748)

**Comment by Laarryy** [comment]
What version of LuckPerms are you on?

**Comment by GoldenGlassBR** [comment]
5.1.5.3, bungee and spigot

**Comment by Laarryy** [comment]
Can you use pastebin or https://bytebin.lucko.me to send your entire startup log, start to finish, not just the LP error?

**Comment by GoldenGlassBR** [comment]
Ok: https://bytebin.lucko.me/rCGrgpl60k

**Comment by Laarryy** [comment]
Make sure you've followed everything here: https://github.com/lucko/LuckPerms/wiki/Network-Installation#pre-setup

It looks like you have authentication/ip-forward or something not enabled correctly because their UUIDs are changing. Make sure the bungee has `online-mode` set to true and each backend has `bungeecord` set to true in the spigot.yml. Also ensure `ip_forward` is enabled in the bungee config and each spigot server.properties has `online-mode` set to false. Lastly, make sure the players are only joining through the proxy.

**Comment by lucko** [comment]
Seems like you may have a plugin which is altering player UUIDs on your Bungee proxy? That's likely the issue here.
