### ISSUE TITLE
Context Edittor

### ISSUE THREAD

**Issue by Ninjablader101** [lucko/LuckPerms#2378]
Hello, I was wondering if a feature that lets you group what you want by context. Because if I'm on bungee then I got tons of permissions in one group. Especially default.

**Comment by Laarryy** [comment]
Add the groups to the user with context, or add the groups as parent of other groups with context, and give the users the other groups

**Comment by Ninjablader101** [comment]
Hello is there a way then to make it a separate folder type thing so Staff are in one folder followed by Prisons and ect

**Comment by Laarryy** [comment]
Not currently

**Comment by Ninjablader101** [comment]
What are those and how do i use them?

**Comment by Turbotailz** [comment]
You should just organise your groups better by creating separating the permissions into groups then add those groups to default with the contexts.

**Comment by Laarryy** [comment]
https://github.com/lucko/LuckPerms/wiki/Tracks

**Comment by Ninjablader101** [comment]
Is there ever going to be a better way of grouping it?

**Comment by Turbotailz** [comment]
You've just been told a better way to group it :P
