### ISSUE TITLE
MongoDB Connection Feedback

### ISSUE THREAD

**Issue by ExZiByte** [lucko/LuckPerms#2379]
Hello, I was trying to use the username/password combo to connect to MongoDB with LuckPerms and it was failing with "Authentication Failed". I used the connection URI with the same data and it worked to connect, I was also looking at the MongoStorage driver for LuckPerms I believe the issue of not being able to use the username/password combo stems from never specifying the authentication database(which iirc the default auth database being set to admin was removed in a recent MongoDB update)

I was told to make an issue here by TurboTailz on the discord.

**Comment by lucko** [comment]
I don't believe I'm using the driver incorrectly - if you need to specify an auth database which is different to the database used for LP data, then I think the connection URI is your only option.

**Comment by lucko** [comment]
Will happily accept a PR tho if anyone wants to implement a better way of doing it :)
