### ISSUE TITLE
DiscordLink & LuckPerms issue

### ISSUE THREAD

**Issue by ElBananaa** [lucko/LuckPerms#2380]
Hey! I noticed [this error](https://hastebin.com/osoxononar.sql) when using the /lp editor command with luckperms 5.1.26+ (I also tried with 5.1.55) and [DiscordLink ](https://www.spigotmc.org/resources/discord-link-spigot-bungeecord.72684/)1.8.6

I don't think luckperms is the cause and if you can fix this, but now, you are aware of this issue :)

**Comment by lucko** [comment]
Nope, ya you need to report this to DiscordLink. :)
