### ISSUE TITLE
LPB and LP issue

### ISSUE THREAD

**Issue by Ahmadh26** [lucko/LuckPerms#2381]
Hey, I have a bungeecord network. Luckperms Bungee on my bungee, rest are Luckperms spigot.

`lp info`
![Sever](https://user-images.githubusercontent.com/57562297/84599863-d66f8800-ae7d-11ea-9522-0fd78b1ac408.png)

`lpb info`
![Bungee](https://user-images.githubusercontent.com/57562297/84599867-dcfdff80-ae7d-11ea-98a1-e9e965c247d0.png)

All the permissions are synced, doing `lbp editor` and `lp editor` will show the same permission nodes. 
I have advancedBan running on my bungee, all the perms added to my mods. For some reason my mod team cannot `/tempban` as it says no perms. 
i tried running a command `/lpb <user> permission set ab.ban.temp true` and the tempban worked.

i'm pretty sure that the bungee commands should work since everything is in sync.. am i doing something wrong?

**Comment by BrainStone** [comment]
Make sure the UUIDs match, when you run ``lp(b) user <user> info``.

If they don't be sure to follow this: https://github.com/lucko/LuckPerms/wiki/Network-Installation#pre-setup

**Comment by Ahmadh26** [comment]
That guide is how I installed LPB and LP. I'm pretty sure all UUIDs match cz it's happening to all of my mods.

**Comment by Ahmadh26** [comment]
Any updates on this?

**Comment by BrainStone** [comment]
Yes it would happen to all players. Please verify they match.
