### ISSUE TITLE
LPB -- doesn't let owner/admins connect to host.

### ISSUE THREAD

**Issue by staceeann** [lucko/LuckPerms#2382]
I've tried several methods to get the proxy server to connect to the hub, it worked shortly. I switched from my laptop to my desktop, and it no longer works for it. I have up-to-date luck perms, and luckperms bungee. I have all my messaging set to the correct: sql and my storage type is set to MariaDB. I tried restarting the servers: all four (proxy, hub, survival, and skyblock) and it still hasn't corrected itself. 

I am getting the same issue on both accounts that I have. 

https://bytebin.lucko.me/Uvp3WeAZZ6

I have the /lpb info and /lp info from the servers. 

I can send over the errors, but it's telling me duplicate entry for me. 

**This is the error I receive:** 
![image](https://user-images.githubusercontent.com/66919272/84601197-79a7a980-ae4c-11ea-9c7b-08f5295be2c7.png)

**This is the error my co-owner receives:** (which is the same message that my niece's account gets when I try to log-on.)
![JPEG_20200614_110149](https://user-images.githubusercontent.com/66919272/84601210-8b894c80-ae4c-11ea-93b6-a7f0d9d44b15.jpg)

It worked for a bit, until I switched computers like I stated.

**Comment by BrainStone** [comment]
Check the console for errors.

**Comment by staceeann** [comment]
> Check the console for errors.

I already posted the error from the console in the link provided.

**Comment by BrainStone** [comment]
My bad.

It looks like either the database got corrupted somehow or the database server isn't running.

**Comment by staceeann** [comment]
> My bad.
> 
> It looks like either the database got corrupted somehow or the database server isn't running.

I'm not sure how to check either of those. I looked in the MySQL and I cannot create a new database there, but there is already one on it. 

But I'm not sure if I should delete the old one and create a new one?

**Comment by BrainStone** [comment]
So you can connect to the MySQL server and access the database there?

**Comment by staceeann** [comment]
> So you can connect to the MySQL server and access the database there?

Yes, I can.

**Comment by BrainStone** [comment]
Alright. This is all sorts of weird. Try deleting the database and making a new one. Make sure the user in the LP config has access to the database btw.

**Comment by lucko** [comment]
If you're able to login to Phpmyadmin or something similar for your database, try "dropping" all entries from the `luckperms_players` table.
