### ISSUE TITLE
Bukkit/Spigot User from LuckPerms?

### ISSUE THREAD

**Issue by byRaqe** [lucko/LuckPerms#2384]
Hey,

 I would like to ask if there is a way to become a Bukkit/Spigot User by a net.luckperms.api.model.user.User

**Comment by Tobi406** [comment]
You might be able to use this method to get an UUID using [this method](https://javadoc.io/static/net.luckperms/api/5.1/net/luckperms/api/model/user/User.html#getUniqueId--) and then get a player from that

**Comment by byRaqe** [comment]
Thanks I have forgotten it 😄
