### ISSUE TITLE
Installing LuckPerms stops my MOTD showing

### ISSUE THREAD

**Issue by Matemarthur** [lucko/LuckPerms#2387]
Hi, recently I started a new server on Shockbyte and I used the Sponge version (ore) of LuckPerms. 
Before installing it my MOTD was working right, but now it has dissapeared. I'm using Nucleus to run my server. 

Any help?

**Comment by benwoo1110** [comment]
You are most likely missing a permission node. Depending on the plugin you use to show MOTD, you need to set the perm node accordingly. 

LuckPerms provides a verbose command to help you find out what permissions a command/plugin is checking: https://github.com/lucko/LuckPerms/wiki/Verbose

Nuleus perm node list: https://nucleuspowered.org/docs/permissions.html

Also note that OP will be disabled when a permission plugin like luckperm is installed on a forge server, its just how a forge server works. So you will have to use LP to set permissions for all relevant commands.

**Comment by benwoo1110** [comment]
Just to add-on about sponge forge disabling OP: https://github.com/lucko/LuckPerms/wiki/FAQ#i-use-spongeforge-and-when-i-install-luckperms-i-lose-all-my-permissions-why

**Comment by Matemarthur** [comment]
Fixed ! Thank you very much.
