### ISSUE TITLE
I, the owner cant chat on my server.

### ISSUE THREAD

**Issue by Akorian** [lucko/LuckPerms#2388]
I started a Bungee-Paper Server on the 1.15.2. I really have problems setting everything up. 
I just installed a few plugins like EssentialsX, Bungeechat, and LuckPerms.
Since I installed LuckPerms, I am not allowed to chat anymore. Via the proxy-console I managed to give me the permission to change servers because that didn't work either. 

My knowledge so far: 
everything is set on MySQL and connected to the correct database.
The configs are configured so every server can have his own permissions. (that is what we want)
Permissions, which are supposed to be on all servers must be set via the /lpb editor command in the Proxy-console.
I added thebungeechat.command.msg perm and it didn't work. 

I assume I made a mistake in one of the config-files. Me and my buddy where double-checking everything. but since we have no experience with Bungeecord, we may have overlooked or misunderstood something. 
We spend HOURS figuring the problem out but didn't succeed.

I can't really post the configs here cuz of the database passwords etc. But I hope, my description of our problem is enough or someone helps us in Discord (etc.)
I'd REALLY appreciate every useful help.
 (Me and My bud read all the instructions on the wiki)(

**Comment by Laarryy** [comment]
Looks like you have plugin, perhaps BungeeChat, which requires permission to chat. You can try verbose to find it, or look through the plugin docs for BungeeChat to find the required permission. If your perms are synced, just add the required permission to your user/group with no context, and it will apply everywhere.

**Comment by ValentinoAgui** [comment]
Hi, I have the same problem. I have been looking for solutions for this error, but I can't find one, did you find any solution?
