### ISSUE TITLE
Server crashes when I join

### ISSUE THREAD

**Issue by AltyriaServer** [lucko/LuckPerms#2389]
Hi I am the owner of a server and I use luck perms I have been running this server for about a month using luck perms and I have not had any problems. Starting today everytime I join the server it crashes but when other people join it works fine. It only seems to happen when I try connecting when I have given myself op or the owner rank in luckperms.
[crash-2020-06-18_00.15.16-server.txt](https://github.com/lucko/LuckPerms/files/4795633/crash-2020-06-18_00.15.16-server.txt)

**Comment by underscore11code** [comment]
Your Luckperms is a tad bit out of date, can you see if the latest version fixes it?

https://luckperms.net/download

**Comment by AltyriaServer** [comment]
I just updated it and it does not fix it, but I have narrowed it down a bit further the owner rank had the minecraft.* permission and after I removed it it allowed me to join again. Also it seems to have the same problem if I am opped.

**Comment by underscore11code** [comment]
> Also it seems to have the same problem if I am opped.

OPs always have `minecraft.*`, so it must be something about that. Could you send your plugin list?

**Comment by AltyriaServer** [comment]
TitleManager, SimpleRename, SignEditor, ProtocolLib, PlotSquaredV5, NoPhysics, MyCommand, MultiversePortals, Multiverse Inventories, Multiverse Core, Luckperms, KixsAutoAnnouncer, Holograms, HeadDatabase, FAWE, ExtraContexts, EssentialsXSpawn, EssentialsXChat, EssentialsX, Dynmap, DiscordSRV, AmorStandTools, WorldGuardFlags, WorldGuard, Vault

**Comment by underscore11code** [comment]
Not seeing any obvious red flags...Could you see if you can still reproduce the issue with no plugins other then LP installed?

**Comment by AltyriaServer** [comment]
I ran the server with only LP installed and then opped myself via console then tried to connect but it still crashed the server.

**Comment by underscore11code** [comment]
Just in case something changed, could you send the crash log from when there was no other plugins installed?

**Comment by AltyriaServer** [comment]
[crash-2020-06-18_01.36.02-server.txt](https://github.com/lucko/LuckPerms/files/4795915/crash-2020-06-18_01.36.02-server.txt)

**Comment by benwoo1110** [comment]
1. Try with only luckperms plugin installed on your server.
2. Send your full startup log.

**Comment by underscore11code** [comment]
> Try with only luckperms plugin installed on your server.

@benwoo1110 Already had him do so, scroll up lol

**Comment by AltyriaServer** [comment]
Yea its weird I have not changed anything on the server in about a month and this just started happening today

**Comment by underscore11code** [comment]
Think I found it, [according to one of the Paper devs, this is an issue with Spigot](https://www.reddit.com/r/admincraft/comments/hawusi/why_does_my_server_crash_when_an_operator_joins/fv5dvx9/). See if a older build fixes it.
