### ISSUE TITLE
Add a few placeholders

### ISSUE THREAD

**Issue by BirkhoffLee** [lucko/LuckPerms#239]
I'm opening an issue here so we can track the development easily!

Add more placeholders: `%luckperms_highest_group_prefix%`, `%luckperms_prefix_highest_ontrack_<track>%` and `%luckperms_prefix_lowest_ontrack_<track>%`.

**Comment by BiGUNMAN** [comment]
I'd like to suggestion the addition of the same options for suffixes too, I like the suggestion, very useful!

**Comment by BirkhoffLee** [comment]
any progress yet? Just curious :)

**Comment by lucko** [comment]
I've moved this issue to the correct repo.

I haven't forgotten, just been busy with other stuff. (and adding more placeholders isn't a priority for me atm)

Will happily accept a PR on that other repo if someone else wants to add it.
