### ISSUE TITLE
java.lang.NoClassDefFoundError: me/lucko/luckperms/LuckPerms Error

### ISSUE THREAD

**Issue by ren-kun** [lucko/LuckPerms#2391]
I am using velocity 1.1.0

With the following mods and versions and console log copy

https://hastebin.com/otosebofok.sql

Anvil-Velocity-0.1.3.jar
bungeequack-1.0-SNAPSHOT.jar
Catalyst-Velocity-0.1.3.jar
LuckPerms-Velocity-5.1.55.jar
RememberMe-1.1.jar

Happens when: 
Starting up velocity

**Comment by lucko** [comment]
Try updating `com.actualplayer.rememberme` to a newer version, or if that doesn't work, install the legacy API extension.

https://github.com/lucko/LuckPerms/wiki/Upgrading-from-v4-to-v5#api-compatibility
