### ISSUE TITLE
[Suggestion] Be able to change the time-format for expiry placeholders.

### ISSUE THREAD

**Issue by Tomi010817** [lucko/LuckPerms#2395]
### Regards!
 I've been using this plugin since 2017 and always worked like a charm for me, you can do everything on mind because of its variety of features.

 Today I wanted to share my suggestion. So some weeks ago I asked on the Discord Support, if there was some way to change the time-format for expiration placeholders such as:
%luckperms_expiry_time_{permission}%
%luckperms_inherited_expiry_time_{permission}%
%luckperms_group_expiry_time_{group name}%
 Saddly there wasn't any way, so the only way to change it was using JavaScript on PlaceHolderAPI plugin, and I did that. After a couple of days of hard trying, I could successfully finish it but it wasn't that easy as I thought so here it is the suggestion. Could there be a section on the config file to change the time-format on those expiration placeholders on some future update?
**It could look something like this, for example**: https://pastebin.com/bgbF6D7s
This feature will probably save a lot of time to future people that will have to deal with this.

Thanks for reading!

**Comment by Tobi406** [comment]
LuckPerms seems to use (atleast for the PAPI side of things, mvdw is self-calculated) a [PlaceholderAPI method](https://github.com/PlaceholderAPI/PlaceholderAPI/blob/master/src/main/java/me/clip/placeholderapi/util/TimeUtil.java#L114). Not sure if this should be changed at the placeholders expansion or in PAPI directly.

Don't take my reply as anything final, I'm not a developer of LuckPerms!

**Comment by Tomi010817** [comment]
Hello Tobi406, thanks for answering
 Didn't know about that one! Anyways I still see it very confusing for people that will have to deal with this in the future, I think that a place for that should be on the config file of LuckPerms, it will be way very helpful and would save a lot of time to everyone who deals with that inconvenient.

**Comment by lucko** [comment]
The time is rendered by PlaceholderAPI - you need to speak to them if you want the format changed!
