### ISSUE TITLE
Error to start de server closed when charge luckperm

### ISSUE THREAD

**Issue by Alee-OneHit** [lucko/LuckPerms#2396]
https://pastebin.com/7MMZ0htN

need help plz

**Comment by BrainStone** [comment]
Are you using SportSpigot?

**Comment by lucko** [comment]
This has been fixed already afaik (13ebc87b29db80b097dbe3ca785811db4666c7e7) - please update LP.

**Comment by lucko** [comment]
https://luckperms.net/download
