### ISSUE TITLE
A Database error occurred whilst loading permissions data

### ISSUE THREAD

**Issue by Maxifort1** [lucko/LuckPerms#2397]
I can not connect to my server due to an error. I'm an admin so I do have the console which say me that : Player connection was re-allowed for "series of numbers and letters". 
Someone said to me that I had to fix it in the config file, but i've seen nothing in it (I don't know what to search exactily).
For a bit of context I've already done the permissions on a previous server and i want them on a new one, so I just copy the file on the new one. I can not write "/lp editor" in the console too, is it normal ?

Thanks for any help
Maxifort1

<img width="1372" alt="Capture_decran_2020-06-20_a_16 05 49" src="https://user-images.githubusercontent.com/67198332/85205536-35208000-b31c-11ea-98c0-f7e0996d56f5.png">
<img width="628" alt="Capture d’écran 2020-06-20 à 17 33 33" src="https://user-images.githubusercontent.com/67198332/85205542-3f427e80-b31c-11ea-82bc-28a1c23c9f7a.png">

**Comment by Tobi406** [comment]
Look for errors on server startup

**Comment by Maxifort1** [comment]
There is no errors with luckperms when the server starts

**Comment by BrainStone** [comment]
We need your console log

**Comment by Maxifort1** [comment]
Is it this that you need ?
<img width="676" alt="Capture d’écran 2020-06-20 à 20 31 21" src="https://user-images.githubusercontent.com/67198332/85209066-3f02ad00-b335-11ea-92ec-1aa24c1e704c.png">

**Comment by BrainStone** [comment]
Your full console log.

And that looks like either LP can't connect to the database or you didn't select the proper storage type. Most likely the former.
So double check your credentials.

**Comment by Maxifort1** [comment]
I'm really new in all this, how can i give you the full console log ?

**Comment by BrainStone** [comment]
You go in the logs folder and then it's the latest.log

**Comment by Maxifort1** [comment]
Here is the log

[latest.log](https://github.com/lucko/LuckPerms/files/4808427/latest.log)

**Comment by lucko** [comment]
You're getting a connection refused error to your MySQL server.

> Caused by: java.net.ConnectException: Connexion refusée (Connection refused)

Please see here for some things you can try:

https://github.com/lucko/LuckPerms/wiki/Storage-system-errors
