### ISSUE TITLE
Plugin doesn't work

### ISSUE THREAD

**Issue by lolpixel12** [lucko/LuckPerms#2398]
When I open the server with the plugin it closes automatically but when I remove it it works perfectly

**Comment by Laarryy** [comment]
Do you have authme? If so, you should check out the FAQ on the wiki for the setting in authme config that you must modify. I'm on mobile but if you have trouble finding it please let me know and I'll send the link as soon as I can get to my PC

**Comment by lolpixel12** [comment]
Yes, yes I have the AuthMe

**Comment by Turbotailz** [comment]
So read the part on the FAQ that relates to this issue.
