### ISSUE TITLE
Sponge 2838 Startup Error

### ISSUE THREAD

**Issue by Laarryy** [lucko/LuckPerms#2399]
Hello Luck, user came in today with this https://bytebin.lucko.me/JaFa5D4K6w error on startup for LP-Sponge on the newest version of LP (5.1.58). They tried removing config and restarting, same problem. They've downgraded to a 4.2 version because it starts, but that's definitely not preferred. Any clue why this is happening?

**Comment by Hamilegit** [comment]
I am having that issue described

**Comment by Tobi406** [comment]
Can you add
```
log-notify-filtered-descriptions = [
]
```
to the end of your config?
