### ISSUE TITLE
fix the default group re-create on export and import

### ISSUE THREAD

**Issue by mat41997** [lucko/LuckPerms#240]
https://gist.github.com/mat41997/2268416d622d5a89e0d6cae78ed26d3c
to
[edb_113252.zip](https://github.com/lucko/LuckPerms/files/917781/edb_113252.zip)

logs
https://gist.github.com/mat41997/3169937aa58e952c64b4182fd216bed8

**Comment by lucko** [comment]
This has been fixed already, but the fix will only apply to exports made using the fixed version. :/
