### ISSUE TITLE
Lag issue

### ISSUE THREAD

**Issue by TwerkRekt** [lucko/LuckPerms#2400]
Hello, i have a issue with luckperms !

Problem on timings

https://i.imgur.com/4k3duE2.png

Version server: 1.13.2 (paper653)
Version luckperms: v5.1.55

**Comment by benwoo1110** [comment]
do you have other proof apart from the timing's report? As timing reports may be always telling the whole story, especially when you only show a small part of the entire report. So do send the entire timing's link.

Another thing to note is that 1.13.2 version servers is one of the most poor-performing Minecraft server version. Do consider upgrading to the latest 1.15.2 as well

**Comment by lucko** [comment]
Set this option to false, or consider updating your server to Paper 1.15 (where this issue has been fixed) :)

https://github.com/lucko/LuckPerms/blob/bfaa543ecd987427c0d1f70d7623c2f51cee9047/bukkit/src/main/resources/config.yml#L626-L627
