### ISSUE TITLE
Suggestion about a placeholder

### ISSUE THREAD

**Issue by WarnDangerous** [lucko/LuckPerms#2401]
I wanted a placeholder like 
%luckperms_inherited_expiry_time_<permission>%
but to know the default expiry time of a permission, so if you set a permission of "2hr" to a player, you'll have a placeholder that will return "2hr".

It would be useful to give some datas to players, like "your permission expiry time is 30mn left on the 2hr I gave you"

**Comment by lucko** [comment]
Unfortunately, LuckPerms doesn't store this data, there's only a single property for the expiry time, not the time when the permission was given.
