### ISSUE TITLE
Can't do /lp editor

### ISSUE THREAD

**Issue by NXxEpicXCreeperxX** [lucko/LuckPerms#2406]
Doing /lp editor just says it makes an editor
then can't access it, no link or anything
I guess I might have to reset my config to fix the issue and redo all permissions?

Version: LuckPerms 5.1.62

**Comment by BrainStone** [comment]
Check for errors in the console and no, you dont have to reset anything. At least not at this point.

**Comment by NXxEpicXCreeperxX** [comment]
I just used a lower version and now it works

**Comment by BrainStone** [comment]
Try the latest version again. Chances are it's caused by the server, not the plugin.

**Comment by NXxEpicXCreeperxX** [comment]
Okay

**Comment by NXxEpicXCreeperxX** [comment]
Didn't work, I guess ill luckperms is broken

**Comment by BrainStone** [comment]
Any errors in the console?

And then use the older version again, but please provide errors you see in the console. Else we can't diagnose or fix it.

**Comment by NXxEpicXCreeperxX** [comment]
No errors :( so I don't know whats up

**Comment by NXxEpicXCreeperxX** [comment]
Anyway to fix? or Just keep using Older version?

**Comment by BrainStone** [comment]
Can you just provide us your server log?

**Comment by NXxEpicXCreeperxX** [comment]
here's my log https://hasteb.in/uwecilar.md

**Comment by BrainStone** [comment]
A log where you ran the editor command

**Comment by NXxEpicXCreeperxX** [comment]
Um idk why its not showing it in the logs.. so

**Comment by NXxEpicXCreeperxX** [comment]
I will use the older version till you tell me its okay to use the newer one

**Comment by OmegaWeaponDev** [comment]
We won't tell you the newer one is okay to use until you give us the logs where you run the editor command like BrainStone wanted. As how can we "fix" something without you giving us proof it's actually broken?
