### ISSUE TITLE
switching from the pirate UUID to the premium UUID

### ISSUE THREAD

**Issue by NoOneBoss** [lucko/LuckPerms#2411]
https://prnt.sc/t694aa
When switching from the pirate UUID to the premium UUID, a very strange error occurs, causing permission to break down on the entire BungeeCord. I think this is due to the fact that the pirate and licensed account are completely different, although the nickname is the same, but still, we can ask you to fix it

**Comment by lucko** [comment]
The plugin you're using to dynamically change UUIDs isn't supported.
