### ISSUE TITLE
doesnt run on Bungee

### ISSUE THREAD

**Issue by OriginalPhizzle** [lucko/LuckPerms#2412]
![image](https://user-images.githubusercontent.com/46453696/85761980-b5841e00-b72c-11ea-9c38-8379a84add76.png)

**Comment by thetayloredman** [comment]
A few things

[1] Are you using the BungeeCord LuckPerms on your proxy?
[2] Are each of your servers connected to the same MySQL database? (Including the proxy)

**Comment by OriginalPhizzle** [comment]
> A few things
> 
> [1] Are you using the BungeeCord LuckPerms on your proxy?
> [2] Are each of your servers connected to the same MySQL database? (Including the proxy)

1. yes
2. yes

**Comment by lucko** [comment]
Please try deleting the `/plugins/LuckPerms/libs` folder and restarting the proxy. :)
