### ISSUE TITLE
Permissions data for your user was not loaded during the pre-login stage

### ISSUE THREAD

**Issue by Frosty717** [lucko/LuckPerms#2413]
Hello, i am trying to make new server spigot 1.16.1. Installed essentialsx but i needed to add groups for perms, so i added luckperms. Unfortunately i cant join the server.
![image](https://user-images.githubusercontent.com/67478916/85884381-dc049080-b7e2-11ea-9dc6-96d50b55c1de.png)

**Comment by underscore11code** [comment]
As the error suggests, check your console. If you can't figure it out on your own, please send your console log here, ideally via a pastebin site.

**Comment by untuned** [comment]
Are you using the latest version of LuckPerms from their [CI server?](https://ci.lucko.me/view/LuckPerms/job/LuckPerms/)

**Comment by Frosty717** [comment]
I am using the newest version 5.1.63. Is this enough? https://ctrlv.cz/WRpU

**Comment by untuned** [comment]
> I am using the newest version 5.1.63. Is this enough? https://ctrlv.cz/WRpU

Don't use CraftBukkit, use Spigot instead.

**Comment by Frosty717** [comment]
looks like it solved my problem. Thank you very much. If i may ask my last question, do you know Worldedit that is already running on 1.16?

**Comment by untuned** [comment]
> looks like it solved my problem. Thank you very much. If i may ask my last question, do you know Worldedit that is already running on 1.16?

It will take time for plugin authors to update to 1.16, as it only came out a couple days ago.
Please close the issue if your problem is solved. :)
