### ISSUE TITLE
Lag causing server to hang for a few seconds every x minutes

### ISSUE THREAD

**Issue by Movinggun** [lucko/LuckPerms#2418]
Every x minutes my server is getting a big lag spike of 5 seconds and timings show it is this
https://i.imgur.com/yRYElEY.png

I believe it has something to do with this line   
https://github.com/lucko/LuckPerms/blob/0f23b7a460af276659d0122c2b7842194103cd47/bukkit/src/main/java/me/lucko/luckperms/bukkit/listeners/BukkitCommandListUpdater.java#L100
As it is running on the main thread. Any help would be appreciated.

**Comment by lucko** [comment]
You can fix this issue in two ways:

1) Update to use Paper instead of Spigot, you can just swap the jars (reccomended)
2) Set this option to false in the LP config: https://github.com/lucko/LuckPerms/blob/0f23b7a460af276659d0122c2b7842194103cd47/bukkit/src/main/resources/config.yml#L626-L627
