### ISSUE TITLE
feathure request: add hashing to permissions and groups?

### ISSUE THREAD

**Issue by mat41997** [lucko/LuckPerms#242]
argon2
https://github.com/P-H-C/phc-winner-argon2
scrypt
https://github.com/wg/scrypt
other hashing
https://github.com/Nycto/Hasher

**Comment by lucko** [comment]
Why?

**Comment by mat41997** [comment]
i don't know. for most privacy and safety?

**Comment by lucko** [comment]
Do you know how hashing works?

**Comment by mat41997** [comment]
no, i'm good at thinking

**Comment by lucko** [comment]
:D
