### ISSUE TITLE
TabModifier Crashes Server when starting!

### ISSUE THREAD

**Issue by AdriPlaysz** [lucko/LuckPerms#2420]
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Tab Modifier (tabmodifier)
Caused by: com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: Lme/lucko/luckperms/api/LuckPermsApi;

**Comment by Laarryy** [comment]
If that's the exact error you're getting, could you please use a pastebin service to send the entire stacktrace? It looks like TabModifier is relying on an old version of the LPAPI and needs to be updated. Or, perhaps using the [legacy expansion](https://github.com/lucko/LuckPerms/wiki/Upgrading-from-v4-to-v5#api-compatibility) will allow it to start? Give it a go, and please send, if not the entire log, the entire error for sure.
