### ISSUE TITLE
Constant crash

### ISSUE THREAD

**Issue by Kubson6969** [lucko/LuckPerms#2423]
Since yesterday I've been having this crash and I don't know what it's worng.
https://pastebin.com/nJSaxp1F

First line is the name of an user, but it happens with every user.
we're on: Paper 1.15.2

**Comment by benwoo1110** [comment]
hmm looks like a plugin on your server is hooking into vault in an unexpected way. If you remove all plugin other than LP, does the issue persist?

Also, do you happen to have authme?

**Comment by lucko** [comment]
`com.loohp.interactivechat.Modules.PlayernameDisplay.processPlayer` is effectively doing Vault lookups for offline players via PlaceholderAPI on the main server thread. Perhaps remove those placeholders from it's config?
