### ISSUE TITLE
Plugin Cant load MySQL

### ISSUE THREAD

**Issue by Cryptics1999** [lucko/LuckPerms#2424]
I think this has to do with the Luckperms Editor as the ip specified 

>.... [08:59:14 WARN]: Caused by: java.sql.SQLException: null, message from server: "Host '172.18.0.9' is blocked because of many connection errors; unblock with 'mysqladmin flush-hosts'"

Is not min, and the MySQL worked proberly until we disconnected it cause we did a restart on the server.

https://hastebin.com/ebifofakos.shell

**Comment by lucko** [comment]
Not related to the editor, the error is originating from your MySQL server, not LuckPerms.

Try running the command it suggests?
