### ISSUE TITLE
Server crash, *might* be related to LuckPerms

### ISSUE THREAD

**Issue by jennasisis** [lucko/LuckPerms#2426]
Hello, I'm having an issue with my server. I'm running spigot currently, before I was running paper and getting the same issue. I'm not really sure what's causing it, but from what I can see in the error logs it seems to have something to do with either villagers or LuckPerms. 
Yesterday I [opened an issue on the spigot JIRA](https://hub.spigotmc.org/jira/browse/SPIGOT-5920) and I haven't heard much from md_5 about it, so I figure I'd look through the logs again and see what the issue was. All I know is that LuckPerms was mentioned.

For reference, here's the log: https://pastebin.com/qYmy6rqn

uname -a: `Linux samir-mackde 5.3.0-59-generic #53~18.04.1-Ubuntu SMP Thu Jun 4 14:58:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

java -version:
```
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-8u252-b09-1~18.04-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)
```

Spigot version: `git-Spigot-4d9262c-3b9cf0f (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)`

**Comment by BrainStone** [comment]
Your server froze. Not related to LuckPerms.

**Comment by jennasisis** [comment]
Ah, ok. Thanks that's good to know. I saw LuckPerms in the list of threads and thought it had something to do with it. My bad

**Comment by jennasisis** [comment]
Unrelated to luckperms though, do you have any idea as to why it froze? Or would i be better off asking another resource?

**Comment by BrainStone** [comment]
Not the place.
