### ISSUE TITLE
Placeholder not working on 1.16

### ISSUE THREAD

**Issue by Sikatsu** [lucko/LuckPerms#2429]
On 1.16, this placeholder doesn't seem to work using PAPI, but on 1.15 it works fine. Is this an issue with PAPI or Luckperms?

![image](https://user-images.githubusercontent.com/5664135/86460056-0648d780-bd28-11ea-81d1-634d76067b63.png)

**Comment by benwoo1110** [comment]
First, get latest version of LuckPerms: http://luckperms.net/download

Also, ensure you got the placeholder API extension installed: https://github.com/lucko/LuckPerms/wiki/Placeholders

Then, screenshot what you get for `/papi parse me %luckperms_check_permission_winnerthree.perm%`

**Comment by Sikatsu** [comment]
Latest version is installed, as well for the placeholder expansion. When I parse it, it results into "Ja" which means "Yes", so I have no idea why it doesn't actually work ^^

**Comment by benwoo1110** [comment]
If `/papi parse` shows the correct placeholder, means both LuckPerms and Placeholder API is working. Do look into the plugin that you are using to display the placeholder, and possibly contacting the dev of that plugins. Thanks!

**Comment by Sikatsu** [comment]
The thing is, bossshoppro works fine with the same version on 1.15, and any other stats work fine too. It's just this specific one from luckperms.

Could it not be something in spigot or paper 1.16?

**Comment by Volgeop** [comment]
Same for me... Im using LuckPerms placeholder in BungeeTabListPlus (supports 1.16) and placeholders from luckperms arent displayed.

**Comment by lucko** [comment]
There's nothing special about the placeholders for 1.16 - if /papi parse is displaying the correct value, LP is working correctly.

**Comment by Sikatsu** [comment]
That is actually weird, because in 1.15 it worked. I thought it might have been the plugin, but any placeholders work not from LuckPerms. I also can't get the same permission to work in another plugin (ChatControl), but when I parse it it says ''Ja''

![image](https://user-images.githubusercontent.com/5664135/87357765-df2ea900-c564-11ea-872f-cbb09ec5a16e.png)

Can we debug this any other way?

**Comment by Laarryy** [comment]
Ja is "yes", no? That placeholder will return a yes or no if they have the permission or not.

**Comment by Sikatsu** [comment]
It's yes indeed, and it only works when I parse it, I can not get it to work in any plugin. Other PAPI expansions work fine

**Comment by Laarryy** [comment]
As Luck mentioned, the fact that it parses correctly means that everything is working on the LP side. I'm really unsure what in the chain of displaying it could be causing that, however as Ben mentioned, something is going wrong between PAPI and whichever plugin you're trying to get to display the placeholder.
