### ISSUE TITLE
Turning off certain commands

### ISSUE THREAD

**Issue by fallenfrance** [lucko/LuckPerms#243]
Hello I'm trying to create a pixlemon server and I'm having trouble with my default group's commands/permissions. The default group's greifprevention is on but is there a way to turn off certain commands because with it being off they can't acces claiming, deleting, trust and etc. This is all on a sponge server with the plugins: LuckPerms, GriefPrevention and Nucleus. Also I'm using FTP to access the config files however the config were the permission are located can't be found for griefprevention. Sorry if this all over the place.

**Comment by lucko** [comment]
I'm slightly unclear on what you're actually trying to do?

To disable a command, you should just be able to negate that permission (set it to false), and players won't have access.

**Comment by fallenfrance** [comment]
One of the commands I'm trying to disable for my default group is /deleteadminclaims. I'm testing it out with my second mc and some commands are still accessible. Would the disable command be

/lp group default permission set minecraft.griefprevention.deleteadminclaims false? 

I'm sorry I'm just really confused.

**Comment by lucko** [comment]
You need to find out which permission is associated with that command. You can use https://github.com/lucko/LuckPerms/wiki/Verbose to find out.

**Comment by fallenfrance** [comment]
Okay so I was able to find the permissions I would like to turn off here are a couple that I would like to disable: griefprevention.adminclaims griefprevention.claimslistother griefprevention.transferclaim

Now how would that go in the /lp group default code? Would it be like what I put in my previous post?

**Comment by lucko** [comment]
Yes, that's the correct usage

**Comment by fallenfrance** [comment]
So I tried it and nothing worked. My mc account is still about to access those commands

**Comment by fallenfrance** [comment]
Thank you it worked :)
