### ISSUE TITLE
API not working

### ISSUE THREAD

**Issue by RandomPersson** [lucko/LuckPerms#2431]
I've tried both the Bukkit and static providers and they keep returning null with the following message produced in the console:
_Loaded class net.luckperms.api.LuckPermsProvider from LuckPerms v5.1.63 which is not a depend, softdepend or loadbefore of this plugin._
The provider is in try-catch block and doesn't throw any exception. I do have LuckPerms dependency specified in my plugin.yml:
_softdepend: [LuckPerms]_

Running Tuinity 1.15.2-R0.1, LuckPerms 5.1.63

**Comment by BrainStone** [comment]
Make sure that you don't shade in the LP API in you own jar (the must be no LP classes in your jar file. If there are you are doing it wrong)

**Comment by RandomPersson** [comment]
It's just included in build path, in runtime the accessed class is within the original LuckPerms jar.
It's the same error whether I'm using the main LuckPerms jar or the 5.1 API.

**Comment by RandomPersson** [comment]
Issue was on our end, sorry for inconvenience.
