### ISSUE TITLE
LuckPerms commands unresponsive at times

### ISSUE THREAD

**Issue by Pulz-TCP** [lucko/LuckPerms#2436]
I've been having an issue lately (for a month) whereby _sometimes_ running an LP command (such as lp group default editor) will return nothing- and the plugin becomes completely unresponsive. Then 5 or more minutes later it processes the command(s)- during this time there is nothing from LP output to console and no server-lag/low tps.

I'm on 5.1.64 (I understand this is slightly behind latest, I update every week or so when I remember to check for new versions)
The issue has persisted since at least 5.1.47- so probably not version related.

My configuration is the default, with the storage method set to mysql.
I'm on SpongeForge 1.12.2-2838-7.2.3

How should I go about diagnosing this issue? I am happy to provide further details if required.

**Comment by lucko** [comment]
Hey, I ideally need a stack dump from when the unresponsiveness happens.

You can use the `jstack` command if you host your own server to get this.

**Comment by Pulz-TCP** [comment]
> You can use the `jstack` command if you host your own server to get this.

Thanks for the response, sadly I use a hosting provider and do not have direct access to the machine. If there is any other information I can provide, please let me know. Otherwise, if this is beyond your scope of support feel free to close the issue. It's an inconvenience for managing my servers, but the plugin otherwise operates great.

**Comment by lucko** [comment]
Ok no worries.

Unfortunately there's not much I can do without that info - however I've taken a guess that the unresponsiveness is being caused by http requests stalling. I've added a 15 second timeout, hopefully that will help.
