### ISSUE TITLE
World inheritance

### ISSUE THREAD

**Issue by aWitch-Doctor** [lucko/LuckPerms#244]
Right now I can tell a group to inherit all the perms from another group, Can you make it so worlds can inherit perms from other worlds?

So I make the_nether and the_end both inherit overworld. Any permission the player has for only overworld will also transfer to the_nether and the_end. This would allow me to have 3 trees for worlds.

Spawn
.....shopworld
.....Overworld
..........mineworld
...............mine_nether
...............mine_end
..........nether
..........the_end

Creative
.....plotworld

skyworld
.....skyworld_nether

So If I want a player to have a perm only in the first tree I would need to add the perm to 8 worlds instead of just the spawn world and at the same time if I want them to have a perm in overworld and lower I can add it to overworld which the rest inherit.

I'm hoping this isnt too much work. All the commands for a user copy for worlds. 
/lp world overworld parent set spawn
and things like that.

**Comment by lucko** [comment]
This is already possible with world rewrites.
https://github.com/lucko/LuckPerms/blob/master/bukkit/src/main/resources/config.yml#L53
