### ISSUE TITLE
Failed to validate connection even after configuring wait_timeout and maximum_lifetime.

### ISSUE THREAD

**Issue by VergilPrime** [lucko/LuckPerms#2441]
Mariadb's wait_timeout is 28800 (8 hrs) and LuckPerms' maximum-lifetime is set to 1800000 (30 min), mariadb's max_connections is set to 500

`[me.lucko.luckperms.lib.hikari.pool.PoolBase]: luckperms-hikari - Failed to validate connection me.lucko.luckperms.lib.mariadb.MariaDbConnection@32a7a62e ((conn=33569) Connection.setNetworkTimeout cannot be called on a closed connection). Possibly consider using a shorter maxLifetime value.`

Is conn=33569 referring to the amount of simultaneous connections?

**Comment by Laarryy** [comment]
Would you please pastebin the entire error and stacktrace you're getting? That little snippet could mean a whole bunch of things

**Comment by VergilPrime** [comment]
It's just that over and over again.
https://paste.thezomg.com/75514/54471159/

**Comment by VergilPrime** [comment]
The issue happens in spurts of 3-8 times every x minutes where x is Luckperm's maximum-lifetime value. The conn=33569 value continues to increase persisting restarts. Is it possible that Luckperms is opening connections and never closing them?

**Comment by VergilPrime** [comment]
After restarting mariadb service this appears to have gone away. Maybe the settings didn't propagate correctly before?
