### ISSUE TITLE
Luckperms Dev API Problems

### ISSUE THREAD

**Issue by byRaqe** [lucko/LuckPerms#2447]
Hey, 

when I am trying to get LuckPerms with the LuckpermsProvider it, returns null, same at the Registration Service.

**Comment by Jaimss** [comment]
https://github.com/lucko/LuckPerms/wiki/Developer-API#obtaining-an-instance-of-the-api

The `LuckPermsProvider#get` method won't return `null`. If it is `null`, it will throw an `IllegalStateException`, so I am a bit confused by you saying it returns `null`.https://github.com/lucko/LuckPerms/blob/0fd7f643a777f90b61c992454dd6dfe0151d3fcd/api/src/main/java/net/luckperms/api/LuckPermsProvider.java#L48-L53 

Would you please send the error you are getting in your console?
