### ISSUE TITLE
Migrate between offline mode / online mode UUIDs

### ISSUE THREAD

**Issue by codingJWilliams** [lucko/LuckPerms#2448]
It is a common scenario where a user will accidentally run their Bungeecord for a month or so without IP forwarding enabled. 

They will then find some issue with this, IP bans don't work, or whatever, and when fixing the issue and changing to IP forwarding mode, all UUIDs will change and their permissions data will be lost. 

Not sure whether this is possible or not, but it might be a good feature to have a command such as `lp migrateuuids online` which would then go through LP's users table, resolve the online mode UUID of every username there, and save this back to the database. `lp migrateuuids offline` would go through the LP user table, convert every username to the correct offline mode UUID, and save the UUID

**Comment by lucko** [comment]
I don't think this is a problem for LP to solve.

> user will accidentally run their Bungeecord for a month or so without IP forwarding enabled

Permissions are gonna be the least of their troubles - any half decent plugin will store player data based on uuids, even if LP adds a migration function, everything else will still be broken.
