### ISSUE TITLE
Permissions has no effect

### ISSUE THREAD

**Issue by minhthanh920** [lucko/LuckPerms#2451]
Paper 1.16.1
Luckperms : 5.1.26
No error via console

After i update my server from 1.15.2 to 1.16.1 all of permissions,group doesn't working. Luckperms just have prefix working ( 1.15.2 working so well )

**Comment by benwoo1110** [comment]
We need more info than doesn't work. When you run `/lp see USER info` is the players in the correct group and correct prefix is shown? What type of storage method are you using? And best is to restart and check of startup errors for all plugins including luckperms.

**Comment by minhthanh920** [comment]
1. /lp user NAME info . correct  ( they the same my old server (1.15.2, working well) )
2. I using YAML to storage data. 
3. I tried restart so many times, many ways but won't work. ( nothing errors show up console )

**Comment by benwoo1110** [comment]
1. Have you directly edited the YAML files before?
2. Can you please explain what isn't working? Given exact commands and permission nodes?
3. To debug permission nodes, run commands `lp check USER <node>` as well as lp verbose feature
4. Also ensure you are on latest version of lp, I think its 5.1.75 for now

https://luckperms.net/download
https://github.com/lucko/LuckPerms/wiki/Verbose
https://github.com/lucko/LuckPerms/wiki/Command-Usage:-General#lp-check-user-permission

**Comment by minhthanh920** [comment]
thanks for reply. 
my bad. i found that issue. 
a plugin scoreboard made that issue.
