### ISSUE TITLE
Lp and Tebex

### ISSUE THREAD

**Issue by HungryHobos** [lucko/LuckPerms#2454]
Trying to use place holders for commands from tebex to console but placeholders %player% doesnt replace with buyers name. Looked at luck perm placeholder and never found one for player. Am i missing something?

[12:07:19 INFO]: [BuycraftX] Dispatching command 'lp user %player% parent add coal' for player 'ContentHobos'.
[12:07:19 INFO]: [LP] %player% is not a valid username/uuid.

Sorry if this in not the correct format please link me to one if there is.

Help appreciated spent way to much time on this....

**Comment by HungryHobos** [comment]
same for %player_name% and %player_uuid%

**Comment by HungryHobos** [comment]
used {name} and it worked idk lolz probably Tebex end

**Comment by benwoo1110** [comment]
Yea, Tebex have their own placeholder. Look into their documentation or ask their support for the full list of it.

**Comment by lucko** [comment]
Tebex issue if they say those placeholders should work.
