### ISSUE TITLE
Cannot handle when players have spaces in name

### ISSUE THREAD

**Issue by Instinct1V** [lucko/LuckPerms#2455]
When i try to use for example /lp user Fred Freddy parent add coal it doesn't work because of the space.. i tried to fix by doing  /lp user "Fred Freddy" parent add coal. but it still didn't work.. Please fix this

**Comment by Laarryy** [comment]
Use the UUID of the user, see if that works

**Comment by BrainStone** [comment]
There’s a config setting to allow invalid user names.
