### ISSUE TITLE
problem database

### ISSUE THREAD

**Issue by eclair62009** [lucko/LuckPerms#2456]
[luckperms-hikari connection adder/WARN]: Mon Jul 13 01:02:51 CEST 2020 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.

**Comment by benwoo1110** [comment]
I think the error is quite self explanatory. See: https://github.com/lucko/LuckPerms/wiki/Storage-system-errors#mysql-ssl-errors
