### ISSUE TITLE
Constant console spam

### ISSUE THREAD

**Issue by HumanTarget** [lucko/LuckPerms#2457]
12.07 20:54:34 [Server] WARN [LuckPerms] An exception was thrown by org.kingdoms.services.ServiceLuckPerms whilst calculating the context of subject CraftPlayer{name=MrHumanTarget}
12.07 20:54:34 [Server] WARN java.lang.NullPointerException
12.07 20:54:34 [Server] WARN at org.kingdoms.services.ServiceLuckPerms.calculate(ServiceLuckPerms.java:36)
12.07 20:54:34 [Server] WARN at org.kingdoms.services.ServiceLuckPerms.calculate(ServiceLuckPerms.java:19)
12.07 20:54:34 [Server] WARN at me.lucko.luckperms.common.context.ContextManager.calculate(ContextManager.java:138)
12.07 20:54:34 [Server] WARN at me.lucko.luckperms.common.context.QueryOptionsCache.supply(QueryOptionsCache.java:54)
12.07 20:54:34 [Server] WARN at me.lucko.luckperms.common.context.QueryOptionsCache.supply(QueryOptionsCache.java:42)
12.07 20:54:34 [Server] WARN at me.lucko.luckperms.common.cache.ExpiringCache.get(ExpiringCache.java:64)
12.07 20:54:34 [Server] WARN at me.lucko.luckperms.common.context.QueryOptionsCache.getQueryOptions(QueryOptionsCache.java:59)
12.07 20:54:34 [Server] WARN at me.lucko.luckperms.common.context.ContextManager.getQueryOptions(ContextManager.java:82)
12.07 20:54:34 [Server] WARN at me.lucko.luckperms.bukkit.LPBukkitPlugin.lambda$getQueryOptionsForUser$3(LPBukkitPlugin.java:379)
12.07 20:54:34 [Server] WARN at java.util.Optional.map(Optional.java:215)
12.07 20:54:34 [Server] WARN at me.lucko.luckperms.bukkit.LPBukkitPlugin.getQueryOptionsForUser(LPBukkitPlugin.java:379)
12.07 20:54:34 [Server] WARN at me.lucko.luckperms.common.model.User.getQueryOptions(User.java:96)
12.07 20:54:34 [Server] WARN at me.lucko.luckperms.common.api.implementation.ApiUser.getPrimaryGroup(ApiUser.java:74)
12.07 20:54:34 [Server] WARN at me.neznamy.tab.shared.PluginHooks.LuckPerms_getPrimaryGroup(PluginHooks.java:255)
12.07 20:54:34 [Server] WARN at me.neznamy.tab.platforms.bukkit.TabPlayer.getGroupFromPermPlugin(TabPlayer.java:40)
12.07 20:54:34 [Server] WARN at me.neznamy.tab.shared.ITabPlayer.updateGroupIfNeeded(ITabPlayer.java:196)
12.07 20:54:34 [Server] WARN at me.neznamy.tab.shared.features.GroupRefresher$1.run(GroupRefresher.java:17)
12.07 20:54:34 [Server] WARN at me.neznamy.tab.shared.cpu.CPUManager$4.run(CPUManager.java:91)
12.07 20:54:34 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
12.07 20:54:34 [Server] WARN at java.util.concurrent.FutureTask.run(FutureTask.java:266)
12.07 20:54:34 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
12.07 20:54:34 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
12.07 20:54:34 [Server] WARN at java.lang.Thread.run(Thread.java:748)

**Comment by codingJWilliams** [comment]
Looks like ` org.kingdoms`'s problem, they're trying to provide custom contexts and throwing an error.
