### ISSUE TITLE
Paper 1.16.1 - Getting This Error

### ISSUE THREAD

**Issue by BobbyMere** [lucko/LuckPerms#2458]
https://pastebin.com/g6pe8XSr

The error isn't very consistent as it seems to randomly show up doing various tasks involving luckperms. I deleted all of the groups, restarted the server and it still showed' up. The files are a migration from groupmanager.
[LuckPerms.zip](https://github.com/lucko/LuckPerms/files/4915887/LuckPerms.zip)

here's an example with the error with default groups but with user data https://pastebin.com/KPK06q3P
The error doesn't show up when it's manually editing the file but only when the file is auto detected randomly to say there's been a modification to it even though nothing has changed. 
[LuckPerms.zip](https://github.com/lucko/LuckPerms/files/4916358/LuckPerms.zip)

**Comment by benwoo1110** [comment]
Did you happen to edit permissions from the YAML files directly?

**Comment by BobbyMere** [comment]
nope

**Comment by BrainStone** [comment]
Did you symlink the permission files/folder(s) so that you can sync permissions across the servers?

**Comment by lucko** [comment]
Set `watch-files` to false in the LP config.
