### ISSUE TITLE
LuckPerms doesn't detect a user if it has - in nickname

### ISSUE THREAD

**Issue by musabagriyanik** [lucko/LuckPerms#2461]
I tried to add my friend to a group with /lp user Abu-Ha group add "group name" and i got "invalid nickname/uuid" error, i tried samething using console and i got same error again. I used the /lp editor to add my friend to group, my other friend and my nickname doesn't have a - symbol and i didn't got a error when i am adding myself and my other friend to a group.

**Comment by Laarryy** [comment]
The LP config has an option to allow/accept invalid usernames - try enabling that
