### ISSUE TITLE
Performance Hit First Login

### ISSUE THREAD

**Issue by DarkArc** [lucko/LuckPerms#2463]
The first login of a player seems to initialize some state. This regularly results in some code I have running to monitor server ticks getting triggered. It would probably be better to do this as the plugin is starting.

https://spark.lucko.me/#UadmsXcKEx

**Comment by BrainStone** [comment]
So you mean the very first login of any player after the server has started, not the first ever login of each player, right?

**Comment by DarkArc** [comment]
Yes, first login of the first player after the server starts, sorry :)

**Comment by DarkArc** [comment]
Thanks :)
