### ISSUE TITLE
Can't do /lp reload (Interenal error accored) 1.16.1 and restarting doesn't refresh

### ISSUE THREAD

**Issue by NXxEpicXCreeperxX** [lucko/LuckPerms#2466]
Anyway to fix this issue?
LuckPerms 5.1.29
https://www.spigotmc.org/resources/luckperms.28140/
Thanks and hope it get fixed soon!

**Comment by BrainStone** [comment]
Full errors please. Also try the latest version from here: https://luckperms.net/

**Comment by NXxEpicXCreeperxX** [comment]
Okay
