### ISSUE TITLE
Luckperms won't work at all

### ISSUE THREAD

**Issue by SkippoAPS** [lucko/LuckPerms#2467]
I have a new Minecraft server that I had just gotten yesterday, I put the plugin on the server to find it wasn't working at all when doing /pl to have a look the plugins name was in red as shown below hope someone can help me.

https://gyazo.com/b04fa3d051bfb2d9550ac6a51f4f8268

**Comment by Laarryy** [comment]
Unfortunately you'll need to send a pastebin of your entire startup log for us to be able to tell you what's wrong.
