### ISSUE TITLE
The server does not start

### ISSUE THREAD

**Issue by Raffaele07** [lucko/LuckPerms#2469]
I have created a minecraft server in 1.8.8 and I would like to put LuckPerms because I am fine but when I put it on the server the server does not start. You can help me?

**Comment by Tobi406** [comment]
Any console output? `latest.log` content may also be useful to know. 

I can't really say much with the limited information you provide.

**Comment by Raffaele07** [comment]
sono riuscito a sistemare

Il ven 17 lug 2020, 11:59 Tobi <notifications@github.com> ha scritto:
