### ISSUE TITLE
Offer servers in context in a web editor

### ISSUE THREAD

**Issue by diskotekastar** [lucko/LuckPerms#2470]
I have such an idea to add an option to config.yml, which would display the menu of servers in context in the web editor

Bungeecord configuration file:
<img width="230" alt="luckperms-issue2" src="https://user-images.githubusercontent.com/61634734/87815352-bb6daa80-c865-11ea-9b7e-ded1fb13a2aa.png">

LuckPerms web editor:
<img width="433" alt="luckperms-issue1" src="https://user-images.githubusercontent.com/61634734/87815354-bc9ed780-c865-11ea-845d-ec7d0f7b0a83.png">

**Comment by benwoo1110** [comment]
maybe suggest here will be a better place: https://github.com/lucko/LuckPermsWeb/issues
