### ISSUE TITLE
Adding permissions error

### ISSUE THREAD

**Issue by Chris54300** [lucko/LuckPerms#2471]
I can add people to groups but whenever i add a command/perm to the group (ban, kick, mute, etc) It says added but the command doesnt show when i display perms for the group and users in the group cant use the perm

**Comment by benwoo1110** [comment]
its too little information.

1. Check for console errors.
2. what exact commands / method are you using to add perms nodes and what exact perm nodes are those?
3. screenshot relevant information and paste console log wherever possible.
