### ISSUE TITLE
Feature request, run configurable commands on successful permission check

### ISSUE THREAD

**Issue by MikeHollisJr** [lucko/LuckPerms#2472]
If Luckperms added and option that gave administration the ability to run a configurable set of commands when a permission check succeeds, it would easily become one of the most configurable admin tools out there and greatly enhance every other plugin, far beyond the awesomeness it is already

(And solve one of my problems, I want to delete a waypoint on my maps when the player removes a home)

**Comment by benwoo1110** [comment]
I think luckperms works such that when the player run a command of a plugin, that plugin request luckperms to check if the player has the allowed/required permission node, not the other way round... for example when `/delhome` is ran, the permission node `essentials.delhome` is checked by luckperms. If the player has this permission node, then essentials will run the corresponding actions of that command, else it tells the user it doesn't have permission to run the command. 

From what I understand, you want to run multiple commands when a home is deleted, for that, you should use a command alias plugin, there can map a single command to execute multiple commands together.

**Comment by MikeHollisJr** [comment]
> I think luckperms works such that when the player run a command of a plugin, that plugin request luckperms to check if the player has the allowed/required permission node, not the other way round... for example when `/delhome` is ran, the permission node `essentials.delhome` is checked by luckperms. If the player has this permission node, then essentials will run the corresponding actions of that command, else it tells the user it doesn't have permission to run the command.
> 
> From what I understand, you want to run multiple commands when a home is deleted, for that, you should use a command alias plugin, there can map a single command to execute multiple commands together.

That is exactly what I'm doing, but the issue is that the waypoint plugin does not look for the home to be deleted because the home is from a different plugin than the waypoints.

If I could detect and run a command to delete the waypoint in plugin 2 when the permission check is done to delete the home in plugin 1, then I can fully integrate the two.  

Luckperms would essentially enable full integration between the two related (or completely unrelated) systems using tried and true permission triggers that are deep rooted into the minecraft server culture. 

You could start doing things like spawn 10 ghasts when a chest is opened without downloading yet another plugin to make it happen.

I don't know if Luck sees this after he closed it but it is my hope  that they do and sees just how intensely powerful this type of feature could be for cross plugin integration.

**Comment by BrainStone** [comment]
I can tell you right now that just alone performance wise this is not possible.

You should much rather reach out tot the plugin dev to have them perform the proper checks instead of trying to create dirty hacks.

**Comment by MikeHollisJr** [comment]
well I know that you don't want things like hunger to be used, but if the admin is careful and checks his permissions before implimenting it,  it would be an extremely extremely powerful integration tool

**Comment by BrainStone** [comment]
Throttling does nothing. If anything that makes it worse.  
Having to check for potential events to call is very computationally expensive, especially if there are handlers registered.

I'd say you'd notice a performance degradation *without* any registered handlers. Having handlers will just make it so much worse.

**Comment by lucko** [comment]
Sorry yeah, this sort of thing isn't viable.
