### ISSUE TITLE
Database Overload for Online Editor?

### ISSUE THREAD

**Issue by Roboninja7777** [lucko/LuckPerms#2474]
Hi, I have a an issue with Luckyperms. I was using the online editor to change up A LOT of perms for my server. When I ran the applyedits command (/lp applyedits XWo6mZOkuR), it said it was successful at the beginning, but at the end it said "[LP] There was an error whilst saving group data for default." Here is the full error log from the Console, including the command run, the error, etc: https://pastebin.com/HfSihdC7
The discord told me to report this to GitHub, so here I am!
How do I fix this?
Thanks :)

**Comment by lucko** [comment]
You're adding too many contexts to a single permission node which is exceeding the column size limit in the database.

I suggest making use of the "world rewrite" functionality in the LP config file. :)
