### ISSUE TITLE
LuckPerms doesn't work on Bungeecord

### ISSUE THREAD

**Issue by sherwood2142** [lucko/LuckPerms#2476]
I use the latest build of BungeeCord and LP doesn't work correctly. You can see the error logs in the screenshot at the link
[https://ibb.co/RTzL6tg](url)

**Comment by Laarryy** [comment]
That link isn't taking me anywhere... Perhaps you sent the wrong one?

**Comment by benwoo1110** [comment]
Best is to upload your full errors and startup log to https://bytebin.lucko.me/ and send the link here.
