### ISSUE TITLE
Adding placeholder for weight of primary/highest group

### ISSUE THREAD

**Issue by MoonSoD** [lucko/LuckPerms#2481]
Hey, I would like to see a PAPI placeholder that would show you the weight of players primary/highest group, something like `%luckperms_primary_group_weight%`

**Comment by benwoo1110** [comment]
Not sure, but you can try `%luckperms_meta_weight%`

**Comment by MoonSoD** [comment]
Nope, doesn't show 😄

**Comment by lucko** [comment]
That placeholder works for me :)

**Comment by MoonSoD** [comment]
Oh, I forgot, that I need an ecloud expansion.
