### ISSUE TITLE
Lp and Tebex 

### ISSUE THREAD

**Issue by SirDeathnote1** [lucko/LuckPerms#2482]
Hello there,

i have insure with my plugin that

[LP] Command not recognised.

https://gyazo.com/0dcc975171265524773e3377acaf487a

https://pastebin.com/KQ5D1aes

Could you help me to fix it ??

thanks SirDeathnote

**Comment by Laarryy** [comment]
Resolved in discord - mind closing?

**Comment by SirDeathnote1** [comment]
yes that correct close now
