### ISSUE TITLE
fail to load the permission 

### ISSUE THREAD

**Issue by thebladeofflame** [lucko/LuckPerms#2483]
server version 1.16.1paper
when I use EssentialsX-2.17.2.130,LuckPerms can't find the essentials.fly,but GroupManager can find the essentials.fly
picture ⬇
https://sm.ms/image/l8ywqFjZrYQODUS

**Comment by Laarryy** [comment]
If you have two permissions plugins, things break, so just use one.

If `essentials.fly` does not appear with luckperms, you simply have to type it out and the same thing will happen, as the auto-complete is only a suggestion and does not list everything.
