### ISSUE TITLE
Bypass bulkupdate confirmation

### ISSUE THREAD

**Issue by AymerickA** [lucko/LuckPerms#2484]
Hi,

Can you add an option in config.yml of Luckperms to not need /lp bulk confirm <number> after the command bulkupdate was executed.

add in config.yml like:
#BulkUpdate configuration
- only-console: true
- need-confirmation: true

Config per default but if i change to "false" i can directly use bulk update without confirmation

It's an interessant suggestion because if bulkupdate command was executed by a script (like sh) it's hard to detect number etc.

**Comment by BrainStone** [comment]
Using bulkupdate through a script sounds like a recipe for dissaster.

What's your actual underlying usecase?

**Comment by AymerickA** [comment]
A player host event, that start a script (that function perfectly no problem), but i want to remove all users of a group (i have try to delete group and clone a group) but the parent on user stay

**Comment by AymerickA** [comment]
BrainStone I see you everywhere, issue bungee cat and even luck perms now haha.
I have a lot of respect for developers like you.

Otherwise please consider my suggestion?

**Comment by BrainStone** [comment]
I'm not a developer for LuckPerms.

**Comment by lucko** [comment]
I will consider this as part of the planned changes to bulkupdate linked above.
