### ISSUE TITLE
Unable to query default group name from API

### ISSUE THREAD

**Issue by bloodmc** [lucko/LuckPerms#2485]
I can't seem to find a way to query the default group name from API. I know the default name is `default` but if the server renames this to another name then I have no way of knowing what the group is.

**Comment by Laarryy** [comment]
The server is unable to rename it unless they hardcode the change - which I don't think the API accounts for. If they try, LP creates a new default group.

**Comment by bloodmc** [comment]
Ah yes, I see the wiki states `display name` here

https://github.com/lucko/LuckPerms/wiki/Default-Groups#keep-using-the-default-group-but-just-modify-the-display-name 

So this is a non-issue.

Thanks!

**Comment by Laarryy** [comment]
No worries!
