### ISSUE TITLE
Issue with maxLifeTime value (MySQL)

### ISSUE THREAD

**Issue by Azuuno** [lucko/LuckPerms#2486]
Hi ! Recently I’ve set up my database for LuckPerms, but I encountered a problem with the maximum lifetime value. 

Everyday I’ve got some errors about it. I tried to change the value a lot of times, but everytime it doesn’t change anything, the error still appear.

My database is a classic MySQL database.

Sorry if I’m not clear, my english isn’t perfect :/.

**Comment by Azuuno** [comment]
I forgot to send the error :

[22:14:10 WARN]: [me.lucko.luckperms.lib.hikari.pool.PoolBase] luckperms-hikari - Failed to validate connection me.lucko.luckperms.lib.mysql.jdbc.JDBC4Connection@17f4b005 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.

**Comment by Laarryy** [comment]
Hello! There are several possible causes for this error. If you haven't already, please try [the solutions documented here](https://github.com/lucko/LuckPerms/wiki/Storage-system-errors#mysql-no-operations-allowed-after-connection-closed-error). 

If you have tried those solutions, please take a look at and try [the possible solutions found here](https://github.com/lucko/LuckPerms/issues?q=is%3Aissue+maxlifetime). Please let us know if nothing you try, in all of these resources, ends up working!

**Comment by Azuuno** [comment]
Hi ! Thanks, but none of these are helping me... I already tried to ask my Hosting Service if they have changed the wait_timeout, but they haven't.  Same for my maxLifeTime, it's under the 8 hours of the wait_timeout :/.

**Comment by Laarryy** [comment]
Does everything still work and you just get annoying errors every so often? Or does it break whenever the maxLifetime expires?

**Comment by lucko** [comment]
The wiki lists the the extent of the advice I have to offer on this issue, sorry.
