### ISSUE TITLE
%luckperms_highest_group_by_weight% not showing the highest group by weight

### ISSUE THREAD

**Issue by maks244** [lucko/LuckPerms#2487]
This is my newbie group
![notepad++_Y1ovqGq5Vo](https://user-images.githubusercontent.com/26513663/88341211-794cd900-cd3d-11ea-822d-134578944335.png)
This is my VIP group
![notepad++_LYNehbS9B3](https://user-images.githubusercontent.com/26513663/88341447-e496ab00-cd3d-11ea-9903-477676daf221.png)
And this my scoreboard line
![notepad++_bLMtVGEnmS](https://user-images.githubusercontent.com/26513663/88341472-ee201300-cd3d-11ea-87be-b42604c57727.png)

When a player has the VIP rank and the Newbie rank the expected result is for the placeholder to show "VIP", but instead, it shows "Newbie".

This is the output from typing `lp user GamingDay info` and `papi parse GamingDay %luckperms_highest_group_by_weight%`
![javaw_gZiimVlAsx](https://user-images.githubusercontent.com/26513663/88341645-42c38e00-cd3e-11ea-9471-37bf184e33b5.png)

**Comment by lucko** [comment]
Could you try using `lowest_group_by_weight` - I might've just got things the wrong way around.

Failing that, how about `highest_inherited_group_by_weight`?

**Comment by maks244** [comment]
> lowest_group_by_weight
Works, and by that I mean it's reversed (VIP). %luckperms_highest_inherited_group_by_weight% doesn't exist
