### ISSUE TITLE
[NPE] LuckBungee

### ISSUE THREAD

**Issue by SeniorCluckers** [lucko/LuckPerms#249]
While trying to set up luckbungee I get this error...

```
some error BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@4d910fd6, id=21, owner=me.lucko.luckperms.bungee.LPBungeePlugin@865dd6, task=me.lucko.luckperms.common.utils.BufferedRequest$Processor@6b1a562f, delay=0, period=0, running=true) encountered an exception
17.04 06:13:16 [Server] INFO java.util.concurrent.CompletionException: java.lang.NullPointerException
17.04 06:13:16 [Server] INFO at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
17.04 06:13:16 [Server] INFO at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
17.04 06:13:16 [Server] INFO at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1592)
17.04 06:13:16 [Server] INFO at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
17.04 06:13:16 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
17.04 06:13:16 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
17.04 06:13:16 [Server] INFO at java.lang.Thread.run(Thread.java:745)
17.04 06:13:16 [Server] INFO Caused by: java.lang.NullPointerException
17.04 06:13:16 [Server] INFO at me.lucko.luckperms.common.storage.backing.sqlprovider.MySQLProvider.getConnection(MySQLProvider.java:118)
17.04 06:13:16 [Server] INFO at me.lucko.luckperms.common.storage.backing.SQLBacking.loadAllGroups(SQLBacking.java:640)
17.04 06:13:16 [Server] INFO at me.lucko.luckperms.common.storage.AbstractStorage.lambda$loadAllGroups$7(AbstractStorage.java:159)
17.04 06:13:16 [Server] INFO at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
17.04 06:13:16 [Server] INFO ... 4 more
```

**Comment by lucko** [comment]
Make sure you're using the latest version & that your MySQL settings are correct.

It can't get a connection from the server.

**Comment by SeniorCluckers** [comment]
Not working. I can tell you that its not my mysql because I use the plugin for my hub server and it connects to it when I set the mysql details and it even creates the tables etc. Bungee on the other hand does not work it returns the same NPE. Its not my mysql so what is it?

**Comment by lucko** [comment]
> Bungee on the other hand does not work it returns the same NPE. Its not my mysql so what is it?

Even more likely that it's a networking problem / issue with MySQL.

If your hub can connect fine but Bungee cannot, then it's 100% an issue with your MySQL server setup. The LP database code is the same across all platforms.

**Comment by SeniorCluckers** [comment]
@lucko 

Still not working..I even install mariadb and uninstalled mysql. Any ideas ? Same error.

**Comment by Yann151924** [comment]
Have you check the mysql "max_connections" variable ? If you have some servers, luckperms can open a bunch of connection and reach the max connection.
Little tutorial found on google : https://www.electrictoolbox.com/update-max-connections-mysql/
