### ISSUE TITLE
Group check command returns incorrect value

### ISSUE THREAD

**Issue by xxcodianxx** [lucko/LuckPerms#2490]
### Description
The command used to check a permission node of a group returns false information.
If the node is not defined, it will return `undefined` as it should, however if the node _is_ defined and its value is `false`, the command will still return that the permission node is set to `true` regardless.

### Steps to Reproduce
1. Set up a clean installation of Spigot (Paper 1.16.1 was used for testing) with only LuckPerms.
2. Add any permission node to the `default` group. (here, we'll use `example.example`) and set its value to `false`:
```
/lp group default permission set example.example false
```
3. Query the value of the permission node you created using the command:
```
/lp group default permission check example.example
```
### Expected Output
Notice how it says that the node is set to `false`, as it should be.
```
[LP] default has permission example.example set to false in context global.
```
### Actual Output
Notice how it says that the node is set to `true`, despite us clearly declaring its state.
```
[LP] default has permission example.example set to true in context global.
```

**Comment by MikeHollisJr** [comment]
It was suggested that I add this screenshot to this issue. 

https://cdn.discordapp.com/attachments/241667244927483904/736249179935866971/unknown.png

**Comment by lucko** [comment]
Should be fixed by the above commit! Thank you for the excellent bug report. :)
