### ISSUE TITLE
Crash on startup after loading worlds and dimensions Hybrid bukkit forge (Mohist)

### ISSUE THREAD

**Issue by xerminator** [lucko/LuckPerms#2491]
Server crashes on startup when I only have luckyperms installed
Asked in the discord for help and @Laarryy told me to put a issue on the github with crash-report

Bukkit version: bukkit.craftbukkit.v1_12_R1 (hybrid Mohist)
LP version: LuckPerms-Bukkit-5.1.26

Crash-report: https://bytebin.lucko.me/vwnsBsQ7bd
latest-log.txt: https://bytebin.lucko.me/dnZJNo55WB

Edit:

Special-source in md5 folder version: SpecialSource-1.8.5

**Comment by lucko** [comment]
This has been fixed already, please update to the latest version: https://luckperms.net/download
