### ISSUE TITLE
Don't work 1.15.2

### ISSUE THREAD

**Issue by Kn-RedDeath** [lucko/LuckPerms#2492]
does not work on version 1.15.2

**Comment by Tobi406** [comment]
Can you give us more information?

For example what platform you are running on (Bukkit, Spigot, Paper, BungeeCord, Velocity, Sponge, etc.)?
Are there any errors in console? And if yes: Can you send them?

**Comment by Kn-RedDeath** [comment]
Version Bukkit   
Errors:  
Error occurred while enabling LuckPerms v5.1.26 (Is it up to date?)  
java.lang.NoClassDefFoundErro me/lucko/luckperms/lib/okhttp3  
    at me.lucko.luckperms.common.web. ~[?:?]  
    at me.lucko.luckperms.common.plug ~[?:?]  
    at me.lucko.luckperms.bukkit.LPBu ~[?:?]  
    at org.bukkit.plugin.java.JavaPlu ~[server.jar:git-Paper-371]  
    at org.bukkit.plugin.java.JavaPlu ~[server.jar:git-Paper-371]  
    at org.bukkit.plugin.SimplePlugin ~[server.jar:git-Paper-371]  
    at org.bukkit.craftbukkit.v1_15_R ~[server.jar:git-Paper-371]  
    at org.bukkit.craftbukkit.v1_15_R ~[server.jar:git-Paper-371]  
    at net.minecraft.server.v1_15_R1. ~[server.jar:git-Paper-371]  
    at net.minecraft.server.v1_15_R1. ~[server.jar:git-Paper-371]  
    at java.lang.Thread.run(Thread.ja [?:1.8.0_212]  
Caused by: java.lang.ClassNotFoundExcepti me.lucko.luckperms.lib.okhttp3  
    at java.net.URLClassLoader.findCl ~[?:1.8.0_212]  
    at org.bukkit.plugin.java.PluginC ~[server.jar:git-Paper-371]  
    at org.bukkit.plugin.java.PluginC ~[server.jar:git-Paper-371]  
    at java.lang.ClassLoader.loadClas ~[?:1.8.0_212]  
    at java.lang.ClassLoader.loadClas ~[?:1.8.0_212]  
    ... 11 more 
  Dnia 25 lipca 2020 12:55 Tobi   napisał(a):  
 Can you give us more information? 
 For example what platform you are running on (Bukkit, Spigot, Paper, BungeeCord, Velocity, Sponge, etc.)?  
Are there any errors in console? And if yes: Can you send them?

**Comment by BrainStone** [comment]
Turn the server off, delete the libs folder in the luckperms folder and start again.

**Comment by Kn-RedDeath** [comment]
Don&#39;t work  
  Dnia 25 lipca 2020 21:23 Yannick Schinko   napisał(a):  
 Turn the server off, delete the libs folder in the luckperms folder and start again.

**Comment by lucko** [comment]
Try again, but make sure you completely stop the server before deleting the libs directory.
