### ISSUE TITLE
Rank Prefix BUG

### ISSUE THREAD

**Issue by eliyash31** [lucko/LuckPerms#2493]
Okay I just realized it now everytime when I do /lp editor and then after putting all the permission and save the file and reload the plugin. The rank prefix is bugged where I tried to promote myself to another rank and still the prefix stays the same but my rank was changed or was promoted. it is a weird bug because it doesn't do this to all the ranks but only to a one or two ranks. When I check to see the lp editor I can still see on the list of permissions that the rank prefix is still there, I tried promoting and demoting my self or setting myself to a specific rank but still it keeps on the same prefix. I happen to encounter this many times or maybe everytime I use the lp editor

**Comment by lucko** [comment]
Does the correct prefix show when you run `/lp user <user> info`?

Could you give a short reproducible example I could follow myself in order to make the issue happen?
