### ISSUE TITLE
Prefix Meta Won't Save 

### ISSUE THREAD

**Issue by DryerBox** [lucko/LuckPerms#2494]
When I try to add a prefix to a group, it doesn't show up in the "group info command"
When added by a command, it appears to have executed successfully, and appears in the editor. Then in chat there's no prefix, and in the group info there's no prefix. 

I'm using LuckPerms v5.1.81 on minecraft 1.16 with paper build 110

My old groups that were created before 1.16 have their prefixes and are working, but I can not add new prefixes to them or any new groups. The permission in the editor looks identical to the old groups, but doesn't show up in game at all.

**Comment by lucko** [comment]
Working fine for me:

![](https://i.imgur.com/6fysYHd.png)

Could you give a short example I could follow in order to make the issue happen?

**Comment by DryerBox** [comment]
Yes, I am able to change the default group as well, the issue is when I create a new group I can't seem to change the prefix no matter what. 

I do
lp creategroup testgroup
lp group testgroup setweight 50
lp group testgroup meta setprefix 50 test
lp group testgroup info

and the info shows no prefix
Same result if I do addprefix instead of setprefix, and the same result as if I add it through the editor

**Comment by lucko** [comment]
Completely fresh install:

![](https://i.imgur.com/Twx30HG.png)

Perhaps there's something wrong with your config? Try resetting it back to the default.
