### ISSUE TITLE
Verbose creating dumps + crashed the server

### ISSUE THREAD

**Issue by LoSCraft-Network** [lucko/LuckPerms#2495]
Good afternoon,

While looking for a permission using /lp verbose, I got spammed some WitherAC permissions and then when checking console I had some dumps until the server crashed

https://hasteb.in/imejuyeq.shell

**LuckPerms version 5.1.82**
**Server: Tuinity version git-Tuinity-"7b639ea" (MC: 1.16.1)**

**Comment by lucko** [comment]
Your paste seems to have expired.

Try using `/lp verbose record` instead, followed by `/lp verbose paste` to use the web viewer instead of ingame output, and/or filter out the witherac checks using `!witherac` at the end of the verbose command.
