### ISSUE TITLE
Luckperms displayname problem

### ISSUE THREAD

**Issue by Saterrr** [lucko/LuckPerms#2496]
The problem that i have is shown on screenshot 1 and my list of plugins on the server is shown on screenshot 2
For some reason groups dont want to use color codes.

![Screenshot_93](https://user-images.githubusercontent.com/68790281/88464773-b93aca00-cebd-11ea-80e7-72b2d269f4bd.png)
![Screenshot_94](https://user-images.githubusercontent.com/68790281/88464774-b93aca00-cebd-11ea-83b9-7eafb75138c1.png)

**Comment by xxcodianxx** [comment]
This does not look like an issue with LuckPerms, but rather EssentialsXChat. For proper handling of prefixes, use the prefix functionality of LuckPerms.

Read more about prefixes [here](https://github.com/lucko/LuckPerms/wiki/Prefixes,-Suffixes-&-Meta).

**Comment by lucko** [comment]
EssXChat doesn't seem to support using color codes in group names.

Perhaps you mean to set a prefix instead?
