### ISSUE TITLE
2500 issues! Thanks Luck, for all your hard work <3

### ISSUE THREAD

**Issue by Laarryy** [lucko/LuckPerms#2500]
Damn! We've made 2500 issues, and still going strong. Thank you so much, Luck, for making an epic plugin that so many people love and rely on, and for continuing to make it better. It's really appreciated!

**Comment by codingJWilliams** [comment]
<3 Much love for Luck & Turbo, gratz!

**Comment by ParadauxIO** [comment]
Made it to 2500 issues, here's to the next 2500 bugs !

**Comment by mbax** [comment]
2500 issues! That's a lot of problems! 🥳

**Comment by OmegaWeaponDev** [comment]
2500 issues, that's a lot of time spent by luck always remaining dedicated and active to the project and not letting it fall. Well Done Luck!

**Comment by pop4959** [comment]
We're all very lucky to be able to use your perms. Thank you!

**Comment by ParadauxIO** [comment]
Anyone have a link to download group manager?

**Comment by disconsented** [comment]
I heard group manager was a fork of LP @ParadauxIO

**Comment by BillyDaPoop** [comment]
<3 random admin that really likes using this luckypermissions plugin and finds it very useful. web interface also very niceeeeeeeeeeeee

**Comment by Draycia** [comment]
AAAAAAAAAA

**Comment by TristanWiley** [comment]
Thank you Luck! For all you do :D

**Comment by benwoo1110** [comment]
I have to say, Luckperms is truly amazing! Glad to be able help out in LP discord!

**Comment by Turbotailz** [comment]
PEX is better

**Comment by TehloWasTaken** [comment]
Much love to the entire LP Team ♥️

**Comment by Tobi406** [comment]
Thanks for making LuckPerms, it's quite a good plugin! Always makes fun to use it and don't let me start with all the features it has

**Comment by Aberzhulan** [comment]
Fashionably late, as usual. Congrats on all the issues? Great plugin, either way. Thanks for your hard work, guys! :)

**Comment by underscore11code** [comment]
While I question celebrating the issue count, Luck still deserves a huge amount of credit. Thanks for all you've done!

**Comment by BrainStone** [comment]
Keep up the good work!

**Comment by lucko** [comment]
Thanks everyone 😊
