### ISSUE TITLE
Time permission to increase

### ISSUE THREAD

**Issue by botany111** [lucko/LuckPerms#2502]
lp user <user> permission settemp <permission> true 2592000.00
When the player has this permission , Entering again will have no effect

I hope there is something like this that can adjust the time the player has this permission

lp user <user> permission add <permission> is 2592000.00

**Comment by benwoo1110** [comment]
You can use the accumulate modifier feature for the settemp command. 
See: https://github.com/lucko/LuckPerms/wiki/Command-Usage:-Permission#lp-usergroup-usergroup-permission-settemp-node-truefalse-duration-temporary-modifier-context

**Comment by botany111** [comment]
thank you!
