### ISSUE TITLE
Wildcards for permission contexts

### ISSUE THREAD

**Issue by Ivan8or** [lucko/LuckPerms#2506]
Hello!

I think it'd be swell if a feature was added to contexts to allow them to interpret wildcards (if that isn't already a feature)

This would be a very practical way to give players permissions limited to a certain type of server, based on the world / server / bungee name (for example, it would make assigning per server permissions a breeze while shuffling players into one of numerous lobby/minigame/etc... servers) 

Having wildcards would drastically reduce the amount of effort on the server manager's side, since currently the only current solutions would be time consuming and difficult to set up

thank you for your time :)

**Comment by lucko** [comment]
Make use of static contexts instead:

https://github.com/lucko/LuckPerms/wiki/Context#defining-your-own-contexts

:)
