### ISSUE TITLE
Support for multiple World Contexts per permission

### ISSUE THREAD

**Issue by baailey** [lucko/LuckPerms#2507]
Hello, I've just done a massive permission rework on my groups, only to discover that having multiple worlds assigned to one permission isn't supported..

My suggestion is to introduce support for this option, as repeating the same permission over and over for different worlds is just incredibly inconvenient and time-consuming

The LP Web Editor [allows adding multiple](http://prntscr.com/tpu4u1) World Contexts, and commands [in-game also allow it](http://prntscr.com/tpu6fh).

**Comment by benwoo1110** [comment]
It should iirc, ensure you are on the latest version of luckperms. http://luckperms.net/download
you can see: LuckPerms/2300

**Comment by baailey** [comment]
Ah, guess I was outdated a bit. Thanks!
