### ISSUE TITLE
Waterdog & CloudNet

### ISSUE THREAD

**Issue by Supermann77** [lucko/LuckPerms#2509]
Hey

I have a Problem with my Server.

I use CloudNet and I use Waterdog (it is a fork from Bungee for the minecraft bedrock edtion).
When I turn on CloudNet maintenance and a player tries to join, this error comes up.

Error: https://paste.devin.id/kayekuvaho.md

**Comment by lucko** [comment]
CloudNet is checking for the permissions of a player that either is not online or hasn't has a login event fired for them.

**Comment by SuprexDE** [comment]
I have the same problem. 
Can you fix that?
