### ISSUE TITLE
MongoDB authentication credentials

### ISSUE THREAD

**Issue by lifehome** [lucko/LuckPerms#251]
I cannot find fields to put my mongodb credentials, perhaps implementing MongoDB authentication is more secure than current connection method?

**Comment by lucko** [comment]
Your user/pass go here.
https://github.com/lucko/LuckPerms/blob/master/bukkit/src/main/resources/config.yml#L220-L228

**Comment by lifehome** [comment]
Oh dear, I overlooked that section, thanks!
