### ISSUE TITLE
Error on joining to the server

### ISSUE THREAD

**Issue by Adrigamer2950** [lucko/LuckPerms#2511]
When the server is opening, it puts an error in the console, and when I try to join the server, it puts another error :(
![console](https://user-images.githubusercontent.com/58531641/88841361-28762e00-d1de-11ea-9a2b-de0ef0640dfc.JPG)
![join](https://user-images.githubusercontent.com/58531641/88841369-2a3ff180-d1de-11ea-867a-84187b40ed79.JPG)
How I fix this?

**Comment by lucko** [comment]
Please try again using LP `5.1.90` or higher - it won't fix the problem but should give more informative errors.

**Comment by Adrigamer2950** [comment]
![image](https://user-images.githubusercontent.com/58531641/93373587-d6549f00-f855-11ea-866a-0a571ab26736.png)
I put the luckperms 5.1.107 and this is the new error.

**Comment by BrainStone** [comment]
Please check for errors during startup.
