### ISSUE TITLE
[feature] LuckPerms as Forge mod

### ISSUE THREAD

**Issue by Minecraftschurli** [lucko/LuckPerms#2512]
A version of luck perms as a forge mod would be cool
Reference: [https://mcforge.readthedocs.io/en/1.13.x/utilities/permissionapi/](https://mcforge.readthedocs.io/en/1.13.x/utilities/permissionapi/)

**Comment by lucko** [comment]
For now, I suggest using Sponge + LuckPerms. Sponge will implement the Forge permissions API and forward the requests onto LuckPerms.,

**Comment by Minecraftschurli** [comment]
Sponge is only available for mc <= 1.12
