### ISSUE TITLE
Placeholder not shown correctly

### ISSUE THREAD

**Issue by Srborjaa** [lucko/LuckPerms#2513]
![imagen](https://user-images.githubusercontent.com/29895095/88850850-3c289100-d1ec-11ea-9239-1dfc82ec9d87.png)

![imagen](https://user-images.githubusercontent.com/29895095/88850862-3fbc1800-d1ec-11ea-974c-2d7a1b4d9e7b.png)

**Comment by lucko** [comment]
The colours not working isn't to do with me.
