### ISSUE TITLE
Instance on the bungeecord

### ISSUE THREAD

**Issue by Faall1n** [lucko/LuckPerms#2514]
How do I load the instance on the bungeecord?

**Comment by Laarryy** [comment]
Down load Luckperms-Bungee from https://luckperms.net

**Comment by Faall1n** [comment]
> Down load Luckperms-Bungee from https://luckperms.net

I need the API

**Comment by Faall1n** [comment]
As far as I know bungeecord doesn't have getServicesManager().load(class)

**Comment by Fefo6644** [comment]
I mean... https://luckperms.net/wiki/Developer-API#using-the-singleton-static-access
