### ISSUE TITLE
Prefixes in game

### ISSUE THREAD

**Issue by Diddyski** [lucko/LuckPerms#2515]
So i've recently updated my server to 1.16 and the plugins that I use are all up to date. On the old version of my server (1.15.2) we had a 3 tracks, level ups (ez ranks pro),  donator prefixes and staff prefixes which showed up in the chat fine. As we've now updated these don't work like they did before.

It sets it out as [donator rank] [default group prefix] [ex rank pro prefix].

Is there a way to remove the default group prefix from the chat?

**Comment by lucko** [comment]
In your chat formatting plugin's config.
