### ISSUE TITLE
MySQL and error MaxLifeTime

### ISSUE THREAD

**Issue by Lyrians** [lucko/LuckPerms#2516]
Hello,

A while ago I posted this issue I'm having with LuckPerms, and I also asked on Discord, but they all send me to the same Github section on maxLifeTime, and it doesn't work.

I clarify that I am only having this problem with LuckPerms. With, without other plugins inside the server.

The problem with MaxLifeTime and wait_timeout comes from the first day that I started using LuckPerms. Go through various Minecraft hosts, and now a VPS.

Errors: https://paste.enginehub.org/6Uf53HEoO

I know what they are going to tell me, how to review the documentation, etc. I already did it, and it didn't work for me. He checked countless pages on the subject, and I couldn't figure it out. Dropped the value to maxLifeTime, and MySQL wait_timeout value varied.

|-LuckPerms (config.yml & version): 
|--https://paste.enginehub.org/HLbgXypaQ
|--5.1.26

|-MySQL (wait_timeout):
![image](https://user-images.githubusercontent.com/25081787/89047756-384c5a00-d325-11ea-800d-579ff6c87831.png)

I need a little more help. I am not an expert, I am in something basic, and I am learning little by little. It is the first time that I use MySQL in a VPS, and the 1st time that I have full access to it.

Clarification: I fully understand that LuckPerms is a free plugin, and that I have no rights to demand anything. I come to ask for help, to anyone who offers to explain what I can do.

**Comment by Lyrians** [comment]
Error in shutdown: https://paste.enginehub.org/euOO0VBLS

**Comment by Bobbbe** [comment]
i have same but server shutdown 2 https://pastebin.com/NGzf2B45
