### ISSUE TITLE
LuckPerms | helpme pls

### ISSUE THREAD

**Issue by MineShark** [lucko/LuckPerms#2519]
I was looking at the wiki and I tried changing "wait_timeout" to "28800" on my lobby server and it worked perfect, but after a while I got the same error (but in Bungeecord I still got the same error when this happened).

When I tried to do the same on the bungeecord it didn't work with the same of: "wait_timeout", "28800" or "5000". (excuse my bad English)

Luckperms error (Bungeecord) : https://pastebin.com/3aYFyS0x

Lobby error (Lobby) : https://pastebin.com/qVNcNEDp

**Comment by lucko** [comment]
https://github.com/lucko/LuckPerms/wiki/Storage-system-errors is the extent of the knowledge/advice I have to give on this issue.
