### ISSUE TITLE
Prefix Stacking

### ISSUE THREAD

**Issue by M1st3rMinecraft** [lucko/LuckPerms#2520]
Hi, Im using the latest version of luck perms and essentialsX chat version 2.18.

My issue is when I've tried to stack prefixes it just wont show up.
luck perms prefix config:
https://pastebin.com/9hd5Xj9m

essentialsX chat:
https://pastebin.com/WXwYpfSc

Image of what is showing in chat:
![image](https://user-images.githubusercontent.com/43493315/89104080-7ffae080-d40e-11ea-881f-315c87eea33e.png)

where as it should be:
[B] [Owner] M1st3rminecraft: hello world

**Comment by benwoo1110** [comment]
Looks like wrong indentation, it should be something like:
```
meta-formatting:
  prefix:
    format:
      - "highest_on_track_prison"
      - "highest_on_track_donor"
    duplicates: first-only
    start-spacer: ""
    middle-spacer: " "
    end-spacer: ""```

**Comment by M1st3rMinecraft** [comment]
thanks :)
