### ISSUE TITLE
Implement weight calculations for non-prefix/suffix meta key/value pairs.

### ISSUE THREAD

**Issue by Fefo6644** [lucko/LuckPerms#2523]
### Would be something nice to have, and there is a reasoning behind this idea:
* My first thought was, since prefixes and suffixes do have weights, why wouldn't the other meta key/values? I understand it's probably weighted from the group weight but it would also be nice for them to have their own weights; which brings me to the next point, if not:
* Why would prefixes/suffixes have their own weight system if the other meta pairs are "group weighted"?

I initially thought about this when I had to set up a `tab_prefix` set of meta key/values, to have a separate set of prefixes from the chat ones; the "normal chat" prefixes have their own weights as seen below, yet the custom `tab_prefix`es don't.

![Meta info](https://media.discordapp.net/attachments/690683905677983756/739261668013506560/unknown.png)

I get that *this* specific setup is **very** linear and straightforward, but it would be much more useful in a more complex inheritance tree scenario.

**Comment by lucko** [comment]
This config based system was implemented as a bit of a compromise to allow for more custom selection rules.

https://github.com/lucko/LuckPerms/blob/6f90e545fc42afc9d9a2c06ef446b198c62a2ef6/bukkit/src/main/resources/config.yml#L436-L450

I'm not keen on adding further weights/priorities to the meta system.
