### ISSUE TITLE
[BUG] require-sender-group-membership-to-modify

### ISSUE THREAD

**Issue by zettlinger** [lucko/LuckPerms#2526]
When using:
argument-based-command-permissions: true

in combo with:
require-sender-group-membership-to-modify: true

OPS can no longer set themselves to a rank they do not have.

Expected use is that OPS have ALL permissions unless specifically denied in the editor on a group they are in or on the user itself.

I would like to set both settings to TRUE and still have OPS have access to ALL other luckperm permission not explicitly denied

**Comment by lucko** [comment]
This is the intended behaviour - ops need to be a member of the group in order to modify it.
