### ISSUE TITLE
Permission unset commands takes `false` value of permission as context `server=false` when unsetting permission

### ISSUE THREAD

**Issue by Laarryy** [lucko/LuckPerms#2530]
Accidentally discovered this watching pop4959 livestream EssX tpr functionality. No idea what causes it but it is indeed rather misleading. 
What happens: 
https://i.imgur.com/pIx3Dkc.png

Command used to see bug:
/lp user pop4959 permission set essentials.afk false essentials:afk=false world=world
`/lp user pop4959 permission unset essentials.afk false essentials:afk=false world=world`

**Comment by Jaimss** [comment]
If I remember correctly, you don't need a true/false for the unset command. Try running it without `false` and see if it works.

**Comment by Laarryy** [comment]
You're totally right that you don't need to, however the output is what I am reporting here - it says it unsets in context server=false but does not, it unsets in the global context

**Comment by Jaimss** [comment]
if you want it to unset in the global context run the command without the `false`

right now it appears that it isn't doing anything at all except telling you it can't unset the permission because the permission isn't set

**Comment by Laarryy** [comment]
You're totally right again - that's exactly what it *says* - however, it still unsets the permission

**Comment by Jaimss** [comment]
so if you set the permission `essentials.afk` for the user, then you remove it with the word false, you are saying the message luckperms sends doesn't accurately represent what happens?

could you maybe try and list the permissions and send them here both before you run the add permission command, after you run the add permission command, and once you run the remove permission command?

it doesn't seem like it should be removing it, but if it is then i guess it might be a bug.

**Comment by Laarryy** [comment]
I mean, I tested it, as did pop4959. I'm not saying there's something I need help with - I don't even run a server. I'm simply reporting the bug as I see it. When you set the false permission, it sets it. When you run the unset command I said above, it says it can't unset it, but actually seems to unset it just fine while not outputting that.

**Comment by lucko** [comment]
Seems to be working as expected:

![](https://i.imgur.com/YMfnoiU.png)
