### ISSUE TITLE
Luckperms issue with placeholderapi %luckperms_group_expiry_time_vip% not working as it should.

### ISSUE THREAD

**Issue by arturek1666** [lucko/LuckPerms#2535]
**What's the issue** 
The issue is the when doing %luckperms_group_expiry_time_vip% it dosn't show actual expire time, as it's wrong images of evidence:
![image](https://user-images.githubusercontent.com/1558228/89440703-eb60ed00-d743-11ea-83f3-e79379813051.png)

How you can see the actual time of rank is different then when on a placeholderapi.

**Useful information:**
PlaceholderAPI version:
2.10.9
Luckperms version:
LuckPerms-Bukkit-5.1.86

The extension was re downloaded just to be sure it's not because of outdated extension.

**Comment by Fefo6644** [comment]
This is an issue with how the [`TimeUtil`](https://github.com/PlaceholderAPI/PlaceholderAPI/blob/master/src/main/java/me/clip/placeholderapi/util/TimeUtil.java#L139) utility class (provided by PAPI, which is used to format the time it is given) calculates the number of days and hours from the provided duration.
The PAPI Expansion for LP [just asks it to format the remaining time](https://github.com/LuckPerms/LuckPermsPlaceholders/blob/master/luckperms-papi-expansion/src/main/java/me/lucko/luckperms/placeholders/LuckPermsExpansion.java#L73) in seconds into a (supposedly) nicely human-readable formatted string.

Already made a PR for it PlaceholderAPI/PlaceholderAPI#423, hope it gets reviewed soon.

**Comment by HelloZhangf** [comment]
What a efficient man!
Thank you!
