### ISSUE TITLE
PREFIX

### ISSUE THREAD

**Issue by einsblack** [lucko/LuckPerms#2538]
i make a prefix with meta but dosn work
![image](https://user-images.githubusercontent.com/69310929/89539160-b4e6a900-d7fb-11ea-910f-dcba861076a0.png)
![image](https://user-images.githubusercontent.com/69310929/89539204-c6c84c00-d7fb-11ea-991d-93d170c47b53.png)
btw i have essentials chat plugin
![image](https://user-images.githubusercontent.com/69310929/89539303-e1022a00-d7fb-11ea-8e41-9a7cccc1666c.png)

**Comment by Tobi406** [comment]
[This section](https://github.com/lucko/LuckPerms/wiki/FAQ#why-are-prefixessuffixes-not-working) of the wiki might help.

**Comment by benwoo1110** [comment]
You need vault.

**Comment by einsblack** [comment]
ok thanks
