### ISSUE TITLE
Hexa prefix & suffix

### ISSUE THREAD

**Issue by Tylwen** [lucko/LuckPerms#2541]
Hello

How to put the hexadecimal color directly in a prefix or a suffix?

cordially

**Comment by Laarryy** [comment]
just write it in front of where you want it to apply. `lp user <name> meta setprefix 100 &#00ff00Prefix`

The `&#` that I use is determined by the chat plugin. Some chat plugins have different required prefixes to parse hex.

**Comment by Tylwen** [comment]
I have tried these methods before but the color does not apply. it literally writes it

**Comment by Tylwen** [comment]
Its {#RRGGBB} mostly

**Comment by benwoo1110** [comment]
It means either your chat plugin uses a different format for RGB, or it doesn't support it at all. It not up to LP to show RGB colours of prefix/suffix in chat, but rather its your chat plugin's job.

**Comment by Tylwen** [comment]
So why are classic colors applied directly to LP? It doesn't make sense that there isn't a way that the hex applies directly

**Comment by underscore11code** [comment]
Luckperms only can send prefix info to plugins, we don't touch formatting whatsoever.

**Comment by thecenters** [comment]
I have this same issue. Using Hero Chat, but other gradients work in chat.

**Comment by TheDragonsRoost** [comment]
Same here

**Comment by Fefo6644** [comment]
LuckPerms does not format prefixes/suffixes nor does it display them in chat/tab/tags/scoreboard, it's totally up to the chat/tab/tags/scoreboard plugin you use on your server to format the prefix/suffix accordingly, so you have to use the RGB format they specify on their documentation.
