### ISSUE TITLE
Issue when setting a user's LP bungeecord group

### ISSUE THREAD

**Issue by endopvp** [lucko/LuckPerms#2544]
Hello, I have get an error when I do /lpb user {example} group set {example}
here is the console error https://hastebin.com/omosapidep.cs

**Comment by endopvp** [comment]
Also, on my other spigot servers I get console spam (https://hastebin.com/iwiregakag.sql) In the config.yml, the useSSL is set to false and the same for verifyServerCertificate.

**Comment by lucko** [comment]
Check the server startup log.

https://github.com/lucko/LuckPerms/wiki/Storage-system-errors
