### ISSUE TITLE
Trouble giving group prefix (Prefix: None)

### ISSUE THREAD

**Issue by PickleClick** [lucko/LuckPerms#2545]
Hello, in the server I'm trying to set up I tried to give a few groups prefixes, but they aren't getting added. 
Editor view: https://imgur.com/zRIRmzC
When using "/lp group ky info" (group is named ky) it only says "Prefix: None" no matter what I try. In game I have tried "/lp group ky meta clear" and then using "/lp group ky meta addprefix &7[&eKY&7]" and "/lp group ky meta setprefix &7[&eKY&7]" with either no context or world, and both with and without quotes around the prefix.  I've also tried using the command with Kentucky instead of ky but no luck since they're different names for the same thing. None of these have worked. I'm using Paper 1.16, and the LuckPerms plugin is in the most recent version. I've read through the FAQ on prefixes already, and I have chat plugins like EssentialsXChat. No one could help me on the LuckPerms discord server, so I'm coming here now for help.

**Comment by underscore11code** [comment]
Not sure how no one caught this on the Discord, your command stynax is simply wrong. The command is `/lp <user|group> meta setprefix <weight> <prefix>`.

See https://luckperms.net/wiki/weight forinfo about weight.

**Comment by Fefo6644** [comment]
Oh no, he did use the command properly, we tried a million things, clearing meta and restarting, setting other groups, from the editor, from commands; the node was being applied but when running `lp group <group> info` it showed `null`.

[Context (sort of)](https://discordapp.com/channels/241667244927483904/241667244927483904/742087300497932339).

**Comment by PickleClick** [comment]
> Not sure how no one caught this on the Discord, your command stynax is simply wrong. The command is `/lp <user|group> meta setprefix <weight> <prefix>`.
> 

The commands do something, but in game it's still stuck on "Prefix: None" when I go to the group info. Either syntax for the command are executable, but they don't work.

**Comment by Laarryy** [comment]
Which command, exactly, are you trying? Also, please run `lp editor` and send the link it generates here.

**Comment by PickleClick** [comment]
> Which command, exactly, are you trying? Also, please run `lp editor` and send the link it generates here.

Anything that will add a prefix to a group. Was trying addprefix and setprefix in particular but neither worked. In the editor it looks like it should be there but in game it always says "Prefix: None" 
https://luckperms.net/editor/SbDQ2iMOVX

**Comment by Laarryy** [comment]
Alright, could you please also send a pastebin of your full LP config?

**Comment by PickleClick** [comment]
> Alright, could you please also send a pastebin of your full LP config?

https://pastebin.com/uZQTcyfn

**Comment by benwoo1110** [comment]
looks like you are missing `duplicates: first-only` line for prefix and suffix formatting. See https://github.com/lucko/LuckPerms/wiki/Prefix-&-Suffix-Stacking#how-does-it-work

**Comment by PickleClick** [comment]
> looks like you are missing `duplicates: first-only` line for prefix and suffix formatting. See https://github.com/lucko/LuckPerms/wiki/Prefix-&-Suffix-Stacking#how-does-it-work

Added it, still nothing changed. Still says "Prefix: None"

**Comment by lucko** [comment]
You're using track selectors (`highest_on_track_staff`, etc)

Are those groups actually on the track? Does it work if you just use `highest`?
