### ISSUE TITLE
LuckPerms multiple prefixes not working

### ISSUE THREAD

**Issue by somerandomsteve** [lucko/LuckPerms#2546]
I did everything on the wiki page but still it's not working. Yes meta-formatting same name with the tracks I've made in lp editor. My ranks have different weights. Owner -> default.

**Comment by lucko** [comment]
I can't do anything to help you if you don't give any information about the problem.

What have you tried so far? Show me your config? Screenshots of command output? Have you checked if the correct prefix shows when you run `/lp user <u> info`?
