### ISSUE TITLE
Difficulty with the minecraft.command.help

### ISSUE THREAD

**Issue by X5RaPiDZZ** [lucko/LuckPerms#2547]
So im following the step by step guide on how to setup the plugin, and well i did "lp group default permission set minecraft.command.help true"  and Even though i made the admin a parent to the mod group and the mod group a parent to the default group, it still says that when i try to use /help and /? it says that i dont have permissions to use the command. I set myself as a parent to the admin group, just as the guide instructed.

Could i get some help if possible, thanks =) 
![Chat](https://user-images.githubusercontent.com/32991328/89770339-87994400-daf6-11ea-9221-5e76aff4f55d.PNG)
![Console](https://user-images.githubusercontent.com/32991328/89770342-8831da80-daf6-11ea-91a6-3b43fb26a8a6.PNG)

**Comment by underscore11code** [comment]
(Verbose mode)[https://luckperms.net/wiki/Verbose] can help you debug permission issues. Quite likely you have another plugin handling `/help` (probably EssentialsX), and therefore the vanilla nodes won't help.

**Comment by X5RaPiDZZ** [comment]
> (Verbose mode)[https://luckperms.net/wiki/Verbose] can help you debug permission issues. Quite likely you have another plugin handling `/help` (probably EssentialsX), and therefore the vanilla nodes won't help.

 I have only got lucky perms installed to my server because i was focusing on getting the permissions sorted first before focusing on installing and configuring more plugins.
But thank you, ill check out the Verbose section

**Comment by underscore11code** [comment]
I'd recommend doing it the other way around, install all the plugins you want, then configure perms. Often plugins override default Minecraft commands (EssentiaslX being a big one), so you may need to redo perms.

**Comment by Turbotailz** [comment]
Yeah in most cases it is not the vanilla minecraft `/help` that is actually being checked. Verbose will uncover the true permission here.
