### ISSUE TITLE
Problems with Gamemode 1

### ISSUE THREAD

**Issue by MoTastisch** [lucko/LuckPerms#2549]
Hello there
I have installed LuckPerms on my Server. It is a great plugin but unfortunately /gm 1 stopped working. It gives me no response when I type in /gm 1 but when I disable LuckPerms it workes.

**Comment by benwoo1110** [comment]
Its most likely do to you lacking the permission to run that command. Try verbose to see what permission node is needed and then set it.

https://github.com/lucko/LuckPerms/wiki/Verbose
https://github.com/lucko/LuckPerms/wiki/Usage
