### ISSUE TITLE
page editor just shows black screen

### ISSUE THREAD

**Issue by GreensaPenguin** [lucko/LuckPerms#2550]
when i run the command lp user/group editor it links me to page but if i go to it it just a black page with nothing on it 
this use to work idk why it stopped working not sure if its something we did or if its on the sites end 

i did try restarting the server that did not fix it not sure what its doing this for =C
https://prnt.sc/txf5d5
![download](https://user-images.githubusercontent.com/50413041/89838824-31e68b00-db3a-11ea-9b05-c8479392cde8.png)

**Comment by BrainStone** [comment]
We are currently experiencing an outage. I can't give an ETA on when it's back but it's being worked on. For the time being you can try a VPN if you have one. Try different cities all over the world until you find a working one.

**Comment by GreensaPenguin** [comment]
oo ok thanks i thought i did something but i can wait

**Comment by lucko** [comment]
Should be all resolved now.
