### ISSUE TITLE
My server crashed abnormally

### ISSUE THREAD

**Issue by hongshige** [lucko/LuckPerms#2556]
This is log about LuckPerms
https://paste.ubuntu.com/p/9JWryhMGK2/

**Comment by BrainStone** [comment]
Your server froze. Your VoxelSniper action took too long.

**Comment by hongshige** [comment]
> Your server froze. Your VoxelSniper action took too long.

What?But I did not install VoxelSniper plugin.

**Comment by BrainStone** [comment]
Oops. I misread the error message. No VoxelSniper. But in any case your server froze. Not related to LuckPerms.
