### ISSUE TITLE
players data

### ISSUE THREAD

**Issue by Thomass368** [lucko/LuckPerms#2558]
Somebody send bots to my server
in mysql i have 5000 players data 
https://ctrlv.cz/nYoe
Is it possible to add an account after logging in? (when by on lobby servers) 
I use captcha robots will not register

**Comment by benwoo1110** [comment]
maybe you should look into why your server got bots attack. My guess its an `online-mode: false` type of server?

Also, default group players shouldn't be stored in database iirc, unless you have a `online-mode: false` server and plugins altering UUID?  see: https://github.com/lucko/LuckPerms/wiki/Default-Groups#where-to-start
