### ISSUE TITLE
[Suggestion] - Additional Placeholder

### ISSUE THREAD

**Issue by GenSecrets** [lucko/LuckPerms#2559]
We currently have the following placeholders related to my suggestion:
- one to check an expiry time for a player's personal groups/parents
- one to check and see all inherited groups a player has
- one to check an expiry time for a player's personal permission
- one to check for expiry time on a player's inherited permission

But we do not have:
- one to check expiry time on a player's inherited group/parent

Usage:
- We have global boosts that we have a load of permissions store in a parent group called "boost" for example. When someone purchases a global boost, the parent "boost" is added to the default rank for so many hours. 
- We want to create a custom command that goes "Time left on \<specified> boost: \<placeholder>". Which is definitely possible thanks to Papi and LP but wondering if we can get a placeholder added which combines a couple features of your other placeholders

Suggested papi name:
- %luckperms_inherited_group_expiry_time_<group_name>%

**Comment by lucko** [comment]
This was already added :)
