### ISSUE TITLE
When updating a prefix the prefix is not pushing to some members

### ISSUE THREAD

**Issue by Camebridge** [lucko/LuckPerms#2560]
When I updated the prefix of my VIP role, some of the members (who have this role set as a temp role for a period of time) do not have their prefix updated when I changed it.
https://gyazo.com/070466ff87825964e50a090b099639e7
The (VIP) is what it should look like however my users still retain the [VIP] tag.

**Comment by lucko** [comment]
This is likely a caching issue with your chat formatting plugin.
