### ISSUE TITLE
/lp editor not working (luckperms)

### ISSUE THREAD

**Issue by JensGamerYT** [lucko/LuckPerms#2563]
i created my own server and i want to go to the luckperms editor but when i type /lp editor it doesn't do anything.
all he does is: [15:23:09 INFO]: [LP] Preparing a new editor session. Please wait...
when i do that command i can't use / lp afterwards

can anyone help me

**Comment by Turbotailz** [comment]
Do you see any errors in the console when doing the command?

Is this a self hosted server (on your own PC) or are you using an online hosting service?

**Comment by JensGamerYT** [comment]
i don't see any errors in the console when i run that command.

i use an online hosting service.
I don't know if you know but that hosting service is Jetstax.

**Comment by Turbotailz** [comment]
What about when you run the command from the console?

**Comment by JensGamerYT** [comment]
then I get exactly the same

**Comment by Turbotailz** [comment]
I think maybe you should talk to your host then.

**Comment by JensGamerYT** [comment]
is it not a fault of the plugin?

**Comment by BrainStone** [comment]
Most likely. Also make sure you're on the latest LP version. The logging was improved in the past.

**Comment by JensGamerYT** [comment]
I am using the latest version

**Comment by BrainStone** [comment]
What version number specifically?

**Comment by JensGamerYT** [comment]
LuckPerms-Bukkit-5.1.93.jar

**Comment by JensGamerYT** [comment]
does it matter that I play on spigot. because it does include bukkit

**Comment by BrainStone** [comment]
Ok. Good. Just making sure. You wouldn't believe how many people are 100% certain they have the latest version only to be met with a two year old no longer supported version.

And yes that's fine. Even recommended. Every bukkit plugin works on Spigot.

**Comment by JensGamerYT** [comment]
I 100% sure have the latest version because I downloaded it from the site itself

**Comment by JensGamerYT** [comment]
*** correcion ***I am 100% sure the latest version because I downloaded it from the site itself

**Comment by JensGamerYT** [comment]
its fixed

**Comment by JensGamerYT** [comment]
the server host owner has fixed it

**Comment by JensGamerYT** [comment]
but thanks guys for your help

**Comment by BrainStone** [comment]
Please don't send your message across multiple posts. It's very annoying.
