### ISSUE TITLE
[SUGGESTION] Allow wildcards for group names

### ISSUE THREAD

**Issue by jvdoorn** [lucko/LuckPerms#2564]
**Description of suggested behaviour:**
Allow the usage of wildcards in group names so that you can easily add or remove all groups start with a certain tag.

**Example of suggested behaviour:**
Say we have a couple of groups all starting with `something-`. If you want to remove all of the groups the suggested syntax would be `lp user <user> parent remove something-*`. In this case, all groups starting with `something-` would be removed from the user.

**Comment by lucko** [comment]
Sorry, whilst I can appreciate this may be useful, I want to keep wildcards as a concept for permissions which are resolved during the checking process, not command handling.
