### ISSUE TITLE
[SUGGESTION] Create a group modifier so that it only allows one of a set of groups.

### ISSUE THREAD

**Issue by jvdoorn** [lucko/LuckPerms#2565]
**Description of suggested behaviour:**
When you have multiple groups, create a modifier so that only one of the groups is allowed to be a parent for a user.

**Example of suggested behaviour:**
Say we have two groups `group-a` and `group-b`. When a user is a member of `group-a` and I add `group-b` to the user, I want LP to automatically remove `group-a`.  Important here is that there is no specific order for the groups (which is the case in a track).

**Comment by BrainStone** [comment]
Just use `/lp ... parent set`

**Comment by jvdoorn** [comment]
That will remove all groups right? I do not want to remove all groups, just the ones beloning to the same "set" of groups.

**Comment by Turbotailz** [comment]
Then use `/lp user <user> parent settrack <track> <group>`

**Comment by jvdoorn** [comment]
I guess that works, thanks!
