### ISSUE TITLE
Chat Prefixes are not Displaying at ALL in Chat

### ISSUE THREAD

**Issue by Antonios-P** [lucko/LuckPerms#2566]
I have setup chat prefixes for every group, but it is not showing. The permissions seem to be working correctly, so I must be doing something right at least. For example, the ```chatmod``` group has the prefix ```&6[Chat-Mod]``` using the node ```prefix.3.&6[Chat-Mod]```. However, when a chat-mod says something in the chat, it just has the default of ```<playerName>```.  I am running the latest ```LuckPerms``` version for ```Nukkit``` built from source code. Build was successful. Is there another dependency that I should fulfill in order for chat prefixes to work (I don't think so)?

**Comment by TheKiller65YT** [comment]
Read this: https://github.com/lucko/LuckPerms/wiki/Prefixes,-Suffixes-&-Meta#displaying-prefixes-and-suffixes

**Comment by Antonios-P** [comment]
@TheKiller65YT Ah...I see. Is [SVault](https://cloudburstmc.org/resources/svault.243/) supported? I couldn't find a Nukkit build for Vault. I have the same question for the chat plugins (EssentialsXChat, VaultChatFormatter, etc.) Thank you!

**Comment by benwoo1110** [comment]
As long as prefix show in the command output `/lp user USER info`, luckperms is working. For nukkit chat plugin you can probably search up on their website I suppose. 

https://cloudburstmc.org/resources/categories/nukkit-plugins.1/

**Comment by Antonios-P** [comment]
@benwoo1110 It shows up with ```/lp user USER info```, but not in chat. I suppose I'll have to got find some plugins then.
