### ISSUE TITLE
Error on load

### ISSUE THREAD

**Issue by AbooseYou** [lucko/LuckPerms#2569]
so i no i have posted this be for but i am only getting this error of 2 of 5 of my hub servers all out hubs sync so all the files are copyed so nothing changed only thing that is not the same is that hub 1-2-5 is on dedi 1 and hub 3-4 is on dedi 2 100% same plugins  and dedi specs

https://paste.helpch.at/fanefonise.md

let me no if you need more info but this one is stumped me

**Comment by arenmarsden** [comment]
I noticed you're running CraftBukkit, please post what version you are running.

You're running on LuckPerms v5.1.93, which is the latest published version, but you're trying to load a Legacy API as seen by this: `[17:36:22 INFO]: [LuckPerms] Loading extension: me.lucko.luckperms.extension.legacyapi.LegacyApiExtension (extension-legacy-api-1.0.0.jar)`. You don't need a legacy extension if you're not running `<= 1.7.10`

**Comment by AbooseYou** [comment]
Server Version is BeerSpigot 1.8.8
Luckperms is LuckPerms-Bukkit-5.1.93

on all server 5 server as i said 3 of the 5 work fine and from what i read 
extension-legacy-api is used for "An extension for LuckPerms v5, which implements the legacy v4 API."

**Comment by AddmanMinecraft** [comment]
Bumping

**Comment by Laarryy** [comment]
@AddmanMinecraft bumping someone else's issue? 

This error is caused by an invalid context key. Ensure that the first setting in each LP's config (`server:`) has a valid word or string following it- it cannot be empty.

**Comment by AbooseYou** [comment]
thing i dont get about his is it only happens on 2 of my 5 hubs

**Comment by BrainStone** [comment]
Then try finding the difference between those that work and those that don't.

**Comment by AbooseYou** [comment]
thats the thing there is not one the server are 100% synced

**Comment by BrainStone** [comment]
Computers are not magic. There must be something different in your setup.

**Comment by AbooseYou** [comment]
only thing that would be not the same is something on the dedi its self i need to no what eles would make this happen as i said the 5 servers are 100% sysnced and are the same thing

**Comment by lucko** [comment]
You have some other plugin installed which is incorrectly shading the LuckPerms API.
