### ISSUE TITLE
Player name replaced by storage type

### ISSUE THREAD

**Issue by leNicDev** [lucko/LuckPerms#257]
In the latest development build, the storage method is shown in various messages instead of the player name:

![image](https://cloud.githubusercontent.com/assets/9200820/25285463/9e7660c0-26ba-11e7-86a2-11f25c90966d.png)

**Comment by lucko** [comment]
Errr, that is really weird.

I'm not having that issue at all.
![](http://i.imgur.com/LPKDE3X.png)

**Comment by lucko** [comment]
Lazy copy pasting 😕
