### ISSUE TITLE
Not an issue, just wondering where your code for Tab Completion is at?

### ISSUE THREAD

**Issue by realwakils** [lucko/LuckPerms#2570]
Title

**Comment by benwoo1110** [comment]
idk but this file looks like there is some thing related to tab completion.

https://github.com/lucko/LuckPerms/blob/master/bukkit/src/main/java/me/lucko/luckperms/bukkit/BukkitCommandExecutor.java#L88

**Comment by Turbotailz** [comment]
https://github.com/lucko/commodore
