### ISSUE TITLE
Spam in console

### ISSUE THREAD

**Issue by WIBOR2002222** [lucko/LuckPerms#2571]
Hello, I always have the same message in my console with different player

Image
https://ibb.co/dWQrV06

**Comment by underscore11code** [comment]
As the error says, this is not a Luckperms bug. Looks like your playervaults plugin is doing stuff improperly, send that error to them.

**Comment by WIBOR2002222** [comment]
"Alternatively, server admins can disable this catch by setting 'vault-unsafe-lookups' to true "

@underscore11code Can I put this ? or is dangerous ?

**Comment by underscore11code** [comment]
You could, but as the warn says, the consequence is lag. Fixing it properly would be better.
