### ISSUE TITLE
[Suggestion] Add offline parsing

### ISSUE THREAD

**Issue by WarnDangerous** [lucko/LuckPerms#2575]
Hello,

I'm using your plugin and I made a top player in which you can see the rank of the player, using placeholderapi, but your plugin doesn't allow placeholderapi to be parsed if the player is OFFLINE, it's easy to add into PAPI, it's just some lines;

Here is the link :
https://www.spigotmc.org/resources/placeholderapi.6245/update?update=229457

Hope it will be added soon :D

**Comment by lucko** [comment]
It's not that simple.. sorry, only online lookups are supported for now.
