### ISSUE TITLE
Wiki repo

### ISSUE THREAD

**Issue by PiggyPiglet** [lucko/LuckPerms#258]
A little suggestion, make a repository for the wiki where people can contribute changes and/or add their own pages.

**Comment by lucko** [comment]
Unfortunately, that's not supported by GitHub.

You can clone the wiki locally and make changes that way, and then open an issue I guess.

`git clone https://github.com/lucko/LuckPerms.wiki.git`

**Comment by PiggyPiglet** [comment]
I meant like a repo that you would check every now and then, and then you would update the actual wiki with the changes/additions u like.

**Comment by lucko** [comment]
https://github.com/LuckPerms/wiki
