### ISSUE TITLE
LuckPerms not working with WorldGuard

### ISSUE THREAD

**Issue by Doomce** [lucko/LuckPerms#2584]
I will show the sequence of actions:
1. I defined a WorldGuard region, named B.
2. I fulfilled command: /rg addmember B g:miner (miner is a group name)
3. Also I executed: /rg flag B -g non members entry deny.

After these ways I can't go to region. Also I tried addmember, using nickname method and I could to enter to region.

**Comment by Fefo6644** [comment]
Are you using FAWE?

**Comment by Doomce** [comment]
Yeah

**Comment by Fefo6644** [comment]
There's your issue, try with the original WorldEdit, should work fine. FAWE is a bit broken regarding that aspect.

**Comment by Doomce** [comment]
I going to try it tommorow and I will give response!

**Comment by benwoo1110** [comment]
Do note, you need vault installed as well for what you wan to do to work.

**Comment by Doomce** [comment]
I replaced FAWE into stock WorldEdit, and WG member groups working!
