### ISSUE TITLE
Connection me.lucko.luckperms.lib.mysql.jdbc.JDBC4Connection@4f03c043 marked as broken because of SQLSTATE(08S01), ErrorCode(0)

### ISSUE THREAD

**Issue by IITFA** [lucko/LuckPerms#2585]
https://pastebin.com/raw/M1pSqLps

So, I have a bash script to run mysqldump on my MySQL database for backups. Every time it is run, this error pops up in the console. Not sure if this is something that can be "safely ignored" or if it's an issue that needs to be resolved.

Hope everyone is doing well.

**Comment by lucko** [comment]
You're probably ok to ignore it :)
