### ISSUE TITLE
ExtraContext for wg-regions doesn't work with FAWE

### ISSUE THREAD

**Issue by TheoRetisch1** [lucko/LuckPerms#2588]
If one sets a permission for a worldguard region to false, the permission will still be executed when using the forbidden command in the region. Lp verbose shows true even though the permission for the region is set to false. If you use Worldedit instead of FastAsyncWorldedit, the wg-feature works fine. It would be great to add FAWE support here, as FAWE offers many unbeatable advantages and is widely used, regardless of some controversies.

LuckPerms 5.1.87 
ExtraContexts 2.0-SNAPSHOT   
Paper 1.16.1 - 138
WorldGuard  7.0.4-beta1;bc551da
FAWE 1.16 - 325

**Comment by Laarryy** [comment]
I am fairly sure that it's on FAWE to replicate functionality of WE, so that WG works as normal.

**Comment by lucko** [comment]
Yeah, this is something that you need to report to FAWE.
