### ISSUE TITLE
luck perms issue with towny

### ISSUE THREAD

**Issue by Kbryst** [lucko/LuckPerms#2594]
Description:
An issue with towny and luckperms that was fixed in a version previously.
When a new player joins a town, they cannot run town commands until they reconnect to the server.
https://github.com/TownyAdvanced/Towny/issues/4264

Expected Behavior:
Player should be able to run /plot and /res commands once they join a town, without needing to reconnect to the server.

Edited to include:
Tested on paper spigot 1.16.2, Luckperms 5.1.93, and Towny 0.96.2.15

**Comment by underscore11code** [comment]
I don't see how this could be Luckperm's fault. Permission checks are handled on the other plugins end. If I had to guess, Towny is caching the permission results and only rechecking them after a relog.

Just to rule out LP, try turning on verbose with `/lp verbose on <yourIGN> & towny`, then trying the affected commands before a relog. If you could send a screenshot of that, that would be ideal.

**Comment by Kbryst** [comment]
Alright so I tested it on my alt and I did have issues with commands, but not as many as most players are reporting to me. 

I am also getting reports of the same issues, but different systems on my server. All minor systems like a cosmetic effect got unlocked and they had to relog to get it. Those aren't connected to the towny plugin in any way.


BeardedBen issued server command: /t add AlpacaSpice
[com.palmergames.bukkit.towny.Towny] [Town Msg] StaffRoom: BeardedBen invited AlpacaSpice to the town.

 [14:12:51 INFO]: [LP] Verbose logging enabled for checks matching AlpacaSpice & towny.

>.... [14:12:56 INFO]: AlpacaSpice issued server command: /accept staffroom
>.... [14:12:56 INFO]: [com.palmergames.bukkit.towny.Towny] [Town Msg] StaffRoom: AlpacaSpice joined the town!

>.... [14:12:58 INFO]: AlpacaSpice issued server command: /t spawn
>.... [14:12:58 INFO]: [LP] VB > alpacaspice - towny.admin - false
>.... [14:12:58 INFO]: [LP] VB > alpacaspice - towny.* - undefined
>.... [14:12:58 INFO]: [LP] VB > alpacaspice - towny.admin.spawn - false
>.... [14:12:58 INFO]: [LP] VB > alpacaspice - towny.* - undefined
>.... [14:12:58 INFO]: [LP] VB > alpacaspice - towny.admin.* - undefined
>.... [14:12:58 INFO]: [LP] VB > alpacaspice - towny.town.spawn.town - false
>.... [14:12:58 INFO]: [LP] VB > alpacaspice - towny.* - undefined
>.... [14:12:58 INFO]: [LP] VB > alpacaspice - towny.town.* - undefined
>.... [14:12:58 INFO]: [LP] VB > alpacaspice - towny.town.spawn.* - false

>.... [14:13:01 INFO]: BeardedBen issued server command: /tpahere AlpacaSpice
>.... [14:13:07 INFO]: AlpacaSpice issued server command: /cmi tpaccept BeardedBen
>.... [14:13:17 INFO]: AlpacaSpice issued server command: /plot claim

>.... [14:13:17 INFO]: [LP] VB > alpacaspice - towny.admin - false
>.... [14:13:17 INFO]: [LP] VB > alpacaspice - towny.* - undefined
>.... [14:13:17 INFO]: [LP] VB > alpacaspice - towny.command.plot.claim - true
>.... [14:13:17 INFO]: [LP] VB > alpacaspice - towny.command.plot.claim - true
>.... [14:13:17 INFO]: [LP] VB > alpacaspice - meta: towny_extraplots - null

>.... [14:13:22 INFO]: AlpacaSpice issued server command: /plot info
>.... [14:13:22 INFO]: [LP] VB > alpacaspice - towny.admin - false
>.... [14:13:22 INFO]: [LP] VB > alpacaspice - towny.* - undefined
>.... [14:13:22 INFO]: [LP] VB > alpacaspice - towny.command.plot.perm - true
>.... [14:13:22 INFO]: [LP] VB > alpacaspice - towny.command.plot.perm - true

**Comment by 0liverGMC** [comment]
I've had the same issue and opened an issue on Towny, seems like this is a luckperms related issue. Works on relog of player everytime.

**Comment by Kbryst** [comment]
Yeah.... I commented your ticket.

Towny devs usually close stuff fast and say "not my problem".


Update, I'm seeing issues with plugins like jobs reborn and such, doing the same thing now.

**Comment by lucko** [comment]
As far as I know this issue has been fixed in Towny itself.

https://github.com/lucko/LuckPerms/issues/1330#issuecomment-689791023
