### ISSUE TITLE
Bring back actual usernames (not lowercased) when displaying info to the user

### ISSUE THREAD

**Issue by kmecpp** [lucko/LuckPerms#2595]
When running any LuckPerms command that outputs the name of a user its always lowercase now. This can be pretty annoying if we need the real version of their usernames for whatever reason like using it in another plugin or just to know what their actual username is.

Can we display the user's real names in commands again?

**Comment by Laarryy** [comment]
Is this server offline mode? If not, it is irrelevant, because usernames in almost all (there are admittedly a couple of exceptions) situations can only have the one sequence of characters, uppercase or not?

**Comment by kmecpp** [comment]
No, my server isn't in online mode and I wasn't even aware there could be multiple players with the same and different cased usernames (although that is another very important reason to implement this suggestion)

My only issue originally was just that it's annoying to go through that extra step of getting the getting the real username when I do need it, especially when I didn't used to have to.

**Comment by Turbotailz** [comment]
This issue sounds completely unrelated to LuckPerms, you shouldn't need to rely on LP to get a user's proper username. LP is simply a permission plugin, not a username authentication plugin.

**Comment by BrainStone** [comment]
Why does the capitalization matter in the first place? Usernames are not case sensitive.

**Comment by kmecpp** [comment]
@Turbotailz Yes, I don't rely on LP to get the user's proper username its just nice to have so I don't have to go through the extra step of getting it when I do need it.

And one of the most common examples of when it matters are if there are other plugins which use case sensitive usernames to retrieve player data easily for a command sender providing a username. Previously I could just search for like all players in a certain group, get their exact usernames from LP and feed it into another plugin but now I have to go through the extra step of getting their real username for each person before I can use it.

**Comment by BrainStone** [comment]
LuckPerms always stored the usernames in lowercase.

**Comment by kmecpp** [comment]
v4.3

![image](https://user-images.githubusercontent.com/6520738/92063274-d0948f00-ed68-11ea-9510-37209defd2ba.png)

**Comment by lucko** [comment]
All usernames are converted to lowercase for certain datastores - it makes case insensitive lookups and queries much easier if all of the data is already in the same case.

Changing this isn't a high priority for me, sorry.

**Comment by kmecpp** [comment]
Easy solution would be to just store both the lowercased name and actual cased name and use the lowercase one for lookups and regular one for displaying but I can understand if that's too much work if only one person is asking for it :(

**Comment by BrainStone** [comment]
> Easy solution

Absolutely not. Not even close

**Comment by Timmy109** [comment]
> Easy solution would be to just store both the lowercased name and actual cased name and use the lowercase one for lookups and regular one for displaying but I can understand if that's too much work if only one person is asking for it :(

Isn't it easier having every username in the same case instead of having to look players up with weird combinations of both upper and lower case?
Usernames aren't generally case sensitive anyway so I don't understand what the issue is.

**Comment by kmecpp** [comment]
> > Easy solution
> 
> Absolutely not. Not even close

@BrainStone What about that is not easy besides a database schema change.



> > Easy solution would be to just store both the lowercased name and actual cased name and use the lowercase one for lookups and regular one for displaying but I can understand if that's too much work if only one person is asking for it :(
> 
> Isn't it easier having every username in the same case instead of having to look players up with weird combinations of both upper and lower case?
> Usernames aren't generally case sensitive anyway so I don't understand what the issue is.

That's what I'm suggesting? I'm saying keep case insensitive lookups but display the real usernames to players

**Comment by BrainStone** [comment]
> What about that is not easy besides a database schema change.

The database scheme change. In all storage types.

Also you clearly stated to store both the normal cased username and the lowercased username, not to just store the normal cased name and perform case insensitve lookups.

**Comment by kmecpp** [comment]
> > What about that is not easy besides a database schema change.
> 
> The database scheme change. In all storage types.
> 
> Also you clearly stated to store both the normal cased username and the lowercased username, not to just store the normal cased name and perform case insensitve lookups.

Yes?

**Comment by BrainStone** [comment]
You have to understand that LP as of now uses a unversioned database scheme. Reliably upgrading these is near impossible.

And your original solution suggested to add a second name column that keeps the capitalization. That's very impractical, It would make a lot more sense to just have the existing column not lowercase the strings and to compare case insensitive.
