### ISSUE TITLE
"NoSuchMethodError: com.google.gson.JsonObject.size()I"

### ISSUE THREAD

**Issue by Fefo6644** [lucko/LuckPerms#2598]
### Description

Ever since commit https://github.com/lucko/LuckPerms/commit/4d5a24f2c419cc93b8d238c181bcc47b54c1fd90, some people have been having the issue the title suggests (as shown [here](https://discordapp.com/channels/241667244927483904/241667244927483904/750368577009483896), [here](https://discordapp.com/channels/241667244927483904/241667244927483904/750105747269877821), [here](https://discordapp.com/channels/241667244927483904/241667244927483904/750065304909905923), [here](https://discordapp.com/channels/241667244927483904/690683905677983756/750391272942076014) and issue #2597) on startup when LP tries to load/parse the `contexts.json`.
The common factor in here seems to be the base version of the vanilla server, apparently having a version prior 2.7 of the gson library shaded in them (which didn't even have a `JsonObject#size()`). Might as well be time to consider a 4 year old version of the game to be legacy :) 

### Reproduction steps

1. Use an old server version (between 1.8.8 and 1.11.2)
2. Install LP (not legacy) for the appropriate server brand.
3. Start the server.
4. Restart the server.

### Expected behaviour

I mean, it won't work anyway, it has an old version of the library shaded, `JsonObject#size()` didn't exist back then.

### Environment details

* Server type/version: `any?` running version `1.8.8` up to `1.11.2` build `any???`
* LuckPerms version: `v5.1.95` and higher.

### Any other relevant details

Nope :)

**Comment by dnyferguson** [comment]
same error, plugin wont load on 1.8.8 https://pastebin.com/f6a6xGZS

**Comment by Laarryy** [comment]
Seems to also affect 1.16.2? Got this today https://hastebin.com/mudunafaga.sql
