### ISSUE TITLE
Temp Permission (Not implying timed permissions)

### ISSUE THREAD

**Issue by TrevorMickelson** [lucko/LuckPerms#2600]
Hello,

I believe you guys should implement a temporary permission system for users. To further explain, I'll lay out an example of the issues I have, and why I want this.

During the duration of a map, I have upgrade systems that give my players permissions to do certain things, I will generally set this permission in the context of that specific server. This works fine, however, at the end of the map I want to clear these permissions. The problem here is that, there are some permissions that need to stay tied to the user, such as "essentials.fly" or many others, and then there are permissions that aren't tied which would be (temp permissions). I know there are ways to clear permissions and avoid certain permissions through bulk-editing, but it's overly difficult to do for my situation, and I think this would make a lot more sense, plus, when I do it that way, a few people always end up losing a rank, even if I do it right, 

The feature should function like this (as an example), "/lp user <user> permission set <permission>:temp, or something like that. This would store this permission in a different section tied to that user, which at any moment I could clear for an individual, or all users tied to a server, or all servers. This for me, would be absolutely amazing, as there's never been a good solution to this problem for me.

I know this is a fairly specific thing, and maybe most server owners don't need it, but I've always personally found myself in this predicament, and this would be a super nice thing to finally have a good and easy way to handle. <3

**Comment by Turbotailz** [comment]
Maybe think about using groups instead of users? That way you can add the groups to users and instead of clearing the group from the users, clear the permissions in the group.

**Comment by TrevorMickelson** [comment]
The issue with that, is when I have like 20 rankups, and I don't think making 20 groups makes a lot of sense you know what I mean. If I put them all into 1 group, then they'd have too many abilities.

**Comment by lucko** [comment]
Using groups is what I was going to suggest too - remember users can inherit from more than one at a time!
