### ISSUE TITLE
Luckperms + fastlogin error

### ISSUE THREAD

**Issue by frogglen** [lucko/LuckPerms#2604]
### Description

when you activate the fastlogin premiumUuid option, when trying to enter the server, luckperms sends an error message to the console and does not let me enter the server.

The message is this:
```
(LP) doesn't have data pre-loaded, they have never been processed during pre-login in this session. - denying login.
Permissions data for your user was not loaded during the pre-login stage - unable to continue. Please try again later. If you are a server admin, please check the console for any errors.
```

It should be noted that this did not happen to me in 1.16.1, until I updated to 1.16.2 it started to happen to me and I am using the latest snapshot of fastlogin and luckperms.

### Reproduction steps

1. Open the config.yml file in fastlogin and set premiumUuid to true.
2. Restart the server
3. Trye to login

### Expected behaviour

It is expected that the user's Premium UUID is loaded and the server is allowed to enter.

### Environment details

last version of paper 1.16.2

Plugins (48): AdvancedAchievements, AdvancedLogin*, AntiCraft, BeautyQuests, BetterEnd, BloodMoon, ChatControl, ChatItemDisplay, ChatReaction, ChestSort, Citizens, CoreProtect, ExtraHardMode, FastLogin, Geyser-Spigot, Graves, InventoryRollback, LibsDisguises, LuckPerms, Maintenance, MarriageMaster, Matrix, MobFarmManager, Multiverse-Core, Multiverse-NetherPortals, MyPet, MythicMobs, OreAnnouncer, PacketLimiter, PiggyBank, PlaceholderAPI, PlugMan, ProtectionStones, ProtocolLib, PvPManager, ServerlistMOTD*, Shopkeepers, SkinsRestorer, SpecializedCrates, TAB, TabCompleteFilter, TutorialCreator, Vault, Wild, WorldEdit, WorldGuard, WorldGuardExtraFlags

LuckPerms version: 5.1.98

**Comment by benwoo1110** [comment]
Does the server allow cracked mc account to join?

**Comment by frogglen** [comment]
> Does the server allow cracked mc account to join?

yes

**Comment by lucko** [comment]
This isn't a LP issue, perhaps try reporting it to the FastLogin author.
