### ISSUE TITLE
Removing groups from a specified user with specific meta tags.

### ISSUE THREAD

**Issue by Ash10744** [lucko/LuckPerms#2605]
### Description
Have the ability to remove groups from a specific user with a specific meta tag.

So say a user has groups with the meta tag 'Visual' once running this it'll remove all the groups from the specific user with the meta tag 'visual'.

ALTERNATIVE 

Allow specific bulkupdates to specified users.

### Proposed behaviour
The feature would work by scanning the current groups the specified user has, and checks to see if any have the meta tag that's specified, after doing such it'll remove those specific groups.

It allows for features in a server that allow users to collect rank designs and have them removed in bulk instead of hafting to remove all the specific groups of those designs. 

### EXTRA INFORMATION

The reasoning behind this feature is due, to the fact I have many groups a user changes between with a GUI and writing them all in individually is quite lengthy.

I have tried doing switchprimarygroups but it does not work functionally on how my server is formatted. And I require an additional group for each group for the permission to access to the group via the gui (So I cannot remove every other group in the players list)

I have included some screenshots of what I mean exactly by this:
https://i.imgur.com/NVHWhnw.png

and the command will detect the groups set to the user with the visual meta tag, and it'll remove them.

Thank you for taking the time to read this :D and I love your plugin and appreciate all the work you do <3

**Comment by lucko** [comment]
Sorry, I think this behaviour is too complex for inclusion directly within LuckPerms - it's quite niche!

Perhaps you could achieve what you're after using a different approach, or through use of the developer API in a separate plugin.
