### ISSUE TITLE
papi display error

### ISSUE THREAD

**Issue by asdf80730** [lucko/LuckPerms#2606]
### Description

when I addtemp parent exceed 24 days. the display thou papi will wrong.

![圖片](https://user-images.githubusercontent.com/5961443/92247650-1765be80-eefa-11ea-86bf-03ed07d4dc2c.png)

### Reproduction steps

/lp user asdf80730 parent addtemp vip1 24d
/papi parse asdf80730 %luckperms_group_expiry_time_vip1%
/lp user asdf80730 parent addtemp vip1 1d
/papi parse asdf80730 %luckperms_group_expiry_time_vip1%

1. Open the config.yml file and set example to true.
2. Restart the server
3. Run /lp user example permission set x from the console

### Environment details

* Server type/version: `paper` running version `git-Paper-136` (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
* LuckPerms version: [LuckPerms] Enabling LuckPerms v5.1.98

**Comment by Fefo6644** [comment]
That's a PAPI bug that's been fixed in the latest dev builds :)
https://ci.extendedclip.com/job/PlaceholderAPI/

**Comment by asdf80730** [comment]
thank you!!
it fix.
