### ISSUE TITLE
Bungee Console SEVERE Error accessing editor

### ISSUE THREAD

**Issue by myk3sr** [lucko/LuckPerms#2607]
### Description

 CONSOLE executed command: /lpb editor

SEVERE ERROR

### Reproduction steps

tried to execute editor from ingame and from console, same error

### Expected behaviour

gives link, nope!

### Environment details

running byngeecord with 2x paperspigot and 1x spigot servers 1.16.2

* LuckPerms version: `5.1.98*'

https://gist.github.com/myk3sr/de13a6ee2056f73d8b099c4a06226950

**Comment by underscore11code** [comment]
> LuckPerms version: `latest dev experimental build'

That tells us nothing. Luckperms doesn't have dev or experimental builds. In the future, please tell us the actual version number (`/ver luckperms` or `/lp info`)

Either way, your enviroment is irrelevent. The error is your server not being able to contact https://bytebin.lucko.me, the backend service that powers the various luckperms web editors. Check your firewall etc.

**Comment by myk3sr** [comment]
ok... i updated version.. told u i was on latest dev build... i didnt have it at the time... so how do i access firewall? i have installed bungeeguard the only thing besides ipforward  i was gonna add whitelist only to the proxy also, but i dont have a firewall, im using apex hosting, i would use a firewall if i could cause its actualy the best way to setup a bungeecord server so no one can access the buckkit and paper/spigot servers....

regardless....

so its a contact/response issue... well... i guess i can go thru settings... besides running paper and spigot bungeecord im also running geyser, which allows bedrock clients to connect to a java server, im thinking because geyser uses an " * " asteric for determining bedrock clients from java, im also finding a possible issue with the asterik acting as a wildcard value instead of a username... unsure... 

my end game is a plugin called SkinChange which allows users to change their skin via command line, i need to give the lowest privileged users access to the plugin so they can attempt to change their skin... not sure if it works... perms wont set on my server...

**Comment by myk3sr** [comment]
well i was able to work around and change the wildcard prefix .... now i have plugin issues with the specific plugin i was tryin to make work....  i will close this issue considering that its not a lucky perms issue now, but!!!! wildcards in names are a issue... id suggest being able to use " " quotes in namespace for weird players who decide to choose random names... (or plugins that autoset)
