### ISSUE TITLE
Permissions not updating

### ISSUE THREAD

**Issue by EpicPuppy613** [lucko/LuckPerms#2608]
### Description
When setting permissions luckperms is not detecting permissions from plugins in each server.

### Reproduction steps
none

### Expected behaviour
permissions are updated in all bungeecord servers

### Environment details

* Server type/version: `Spigot 1.16.2`
* LuckPerms version: `Bungeecord v5.1.98`

**Comment by Fefo6644** [comment]
Do you have LuckPerms Bukkit in all your backend servers as well?

**Comment by EpicPuppy613** [comment]
no

**Comment by Fefo6644** [comment]
You need LP in all your backend servers too, read here for more info https://github.com/lucko/LuckPerms/wiki/Network-Installation
LuckPerms Bungee only takes care of Bungeecord permissions. If what you want to achieve is synchronize all your server's permissions, you need to follow this guide https://github.com/lucko/LuckPerms/wiki/Syncing-data-between-servers

**Comment by EpicPuppy613** [comment]
oh thx
