### ISSUE TITLE
Per world groups

### ISSUE THREAD

**Issue by ChickenPillow** [lucko/LuckPerms#261]
How do I set a per world group (multiverse) so that a player could have group 'Example' in the world 'Example_World' but have the group 'Test' in the world 'Test_World'?

**Comment by c00ldude1oo** [comment]
Do /lp user <USERNAME> parent add <GROUP> world=<WORLD>

**Comment by lucko** [comment]
See here: 

* https://github.com/lucko/LuckPerms/wiki/Command-Usage#what-is-context
* https://github.com/lucko/LuckPerms/wiki/Command-Usage#lp-usergroup-usergroup-permission-set
