### ISSUE TITLE
1.16.2 LuckPerms issue

### ISSUE THREAD

**Issue by JasonMCs** [lucko/LuckPerms#2610]
### Description

On LuckPerms.jar (5.1.98) i keep getting [15:02:15 INFO]: [LuckPerms] Failed to load NMS for this server version: version v1_16_2 PLEASE CONTACT AUTHOR for some reason (PaperSpigot 1.16.2)

### Proposed behaviour

This should probably be fixed and I suggest i hope it gets fixed eventually and if not I will just use spigot page one or wait for new update

**Comment by JasonMCs** [comment]
My startup log with error:
https://pastebin.com/gxnPUWf9

**Comment by Laarryy** [comment]
Can you reproduce this with only LuckPerms installed on your server, and a fresh download from https://luckperms.net ?

Also, the correct label for this would have been the `issue` one - this is not a suggestion for the plugin but rather a report of a bug.

**Comment by JasonMCs** [comment]
Oh, how do i change it from suggestion to bug? I was just told to post it here

**Comment by lucko** [comment]
This error is not originating from LuckPerms, and in fact seems to come from "SongodaCore".

https://github.com/songoda/songodacoreold/blob/35729d46848b6afda7961476250cd22b03c9f56d/Core/src/main/java/com/songoda/core/nms/NmsManager.java#L46

SongodaCore is doing something silly with the server logger there, which I guess is why it appears as coming from LP.

**Comment by JasonMCs** [comment]
Oh okay
