### ISSUE TITLE
Empty DSRV Context Values IllegalArgumentException

### ISSUE THREAD

**Issue by Laarryy** [lucko/LuckPerms#2611]
### Description

Empty DSRV contexts throw errors when calculating potential contexts for editor session 

### Reproduction steps

1. Install LP and DSRV
2. run `/lp editor`
3. See error: https://paste.gg/p/anonymous/7d9ca3d66e2d474898b7f56ee284f73e

### Expected behaviour

No empty contexts, or, if present, no error.

### Environment details

Precise details unknown, sadly.

### Any other relevant details

Reported by a user. Perhaps a decent fix is to have empty contexts simply be disqualified when calculating for the editor, and not throw errors. Honestly not even sure if this should be something done on LP's end or something with a root cause fixed on DSRV's. Jsut wanted to let ya know :)

**Comment by lucko** [comment]
This is an issue in the code I PRed to DiscordSRV, woops.

Seems like a fix has already been implemented - it just needs to be applied to the estimatePotentialContexts method too - https://github.com/DiscordSRV/DiscordSRV/commit/2a6c027f28821644d90baa7de77296dd67d9ea1e

Perhaps if you ask nicely they'll copy it over, if not I'll try get around to PRing the change soon.

**Comment by Laarryy** [comment]
I asked nicely and they fixed it! https://github.com/DiscordSRV/DiscordSRV/issues/856
