### ISSUE TITLE
Command to parent people to a group for a certain amount of time 

### ISSUE THREAD

**Issue by Endphoenix** [lucko/LuckPerms#2613]
### Description

You can give people temporary permissions, but you can't temporarily parent them into a group. 

### Proposed behaviour

If you temporarily parent people to a group, then the player has the permissions of the group temporarily. 

The command would probably be: /lp user %player_name% parent settemp vip 30d 

This is very useful when offering a subscription option.

**Comment by Endphoenix** [comment]
Please note the following problem too:

https://github.com/lucko/LuckPerms/issues/2609

**Comment by Laarryy** [comment]
You can do this easily - reading the wiki helps in situations where you're not sure of a feature.

`lp user <name> parent addtemp <parent> [temporary modifier]`

**Comment by Laarryy** [comment]
https://github.com/lucko/LuckPerms/wiki/Command-Usage:-Parent#lp-usergroup-usergroup-parent-addtemp-group-duration-temporary-modifier-context

**Comment by Endphoenix** [comment]
But did you noticed my other issue too? How can do this?

**Comment by BrainStone** [comment]
You still haven't explained anything. What you write doesn't make any sense whatsoever.

**Comment by Endphoenix** [comment]
If someone has a Permission, but then gets it again for a certain amount of time by being parented to a group for a certain amount of time, and then he is de-parented the group is from him after that time, then he no longer has the permission, because the plugin does not remember the permissions that the player had before he was parented to the group for this certain amount of time.

**Comment by BrainStone** [comment]
Yes it does.  
Permissions assigned directly to players persist and don't get removed when a parent gets removed.

**Comment by BrainStone** [comment]
Yes of course.

**Comment by BrainStone** [comment]
Did you even test this before coming here to request that as a feature?  
Same with temporary groups.

I mean there's documentation for a reason.
