### ISSUE TITLE
PaperSpigot 1.8.8

### ISSUE THREAD

**Issue by GoT-HiM** [lucko/LuckPerms#2614]
LuckPerms don't run in this version

**Comment by underscore11code** [comment]
I've heard rumors that current LP has issues on 1.12.2 and under on the latest version. Try this build for the time being, and check back later.

https://ci.lucko.me/view/LuckPerms/job/LuckPerms/1152/

**Comment by Laarryy** [comment]
That was fixed in the absolute latest version @underscore11code - the newest one should work well

**Comment by underscore11code** [comment]
@GoT-HiM Download the latest version of Luckperms from https://luckperms.net/download.

**Comment by GoT-HiM** [comment]
I used the latest version

**Comment by underscore11code** [comment]
What version LuckPerms do you have? "Latest" tells us nothing, that could mean anything.
