### ISSUE TITLE
Timed Ranks

### ISSUE THREAD

**Issue by Troopsdv** [lucko/LuckPerms#2615]
I think it would be a great idea to add Time Ranks to Luckperms,  you know Default > Member is an Hour of game play.

I belive if you did that more people will download your plugin due to the fact everyone is looking for timed ranks.

Im not sure how hard it will be to add. but by adding a clock or timer for how long players have been on since the receive the Default Rank, cause as soon as they join the server they will be Default. I have no idea how to code. but i do know people and what they want. and right know i am trying to set up a server, but i have not founf any good timed ranks that will work with luckperms with ease. This is just something to think about

**Comment by Timmy109** [comment]
There are plenty of plugins out there that can do this for you.

**Comment by BrainStone** [comment]
As mentioned on Discord, not only is this out of scope for this plugin it’s also not possible as LuckPerms doesn’t track online time of players.
