### ISSUE TITLE
luckperms

### ISSUE THREAD

**Issue by Frostyyyyyy** [lucko/LuckPerms#2616]
### Description

I think you should add modification to the tablist

### Proposed behavior

like the rank will show next to your name in tab, there would be a header, a footer, and like just a tablist with custom stuff

**Comment by Laarryy** [comment]
This is entirely out of scope for Luckperms, a plugin designed to handle permissions and permissions only. A plugin like [TAB](https://www.spigotmc.org/resources/tab-1-5-x-1-16-2.57806/) does what you need and is designed to do so.

**Comment by Frostyyyyyy** [comment]
does TAB work with luck perms?

**Comment by Turbotailz** [comment]
Course it does

**Comment by Frostyyyyyy** [comment]
ok thank you so much

**Comment by Frostyyyyyy** [comment]
been looking for a 1.16.2 plugin for luckperms

**Comment by Turbotailz** [comment]
Almost any plugin will work with LuckPerms if they were developed properly

**Comment by Frostyyyyyy** [comment]
ok so im dumb and i typed TAB [1.5.x - 1.16.2] and the plguin did not show on

**Comment by Laarryy** [comment]
I hyperlinked the plugin in my first response. In case that was unobvious, here - https://www.spigotmc.org/resources/tab-1-5-x-1-16-2.57806/

**Comment by Frostyyyyyy** [comment]
thank you

**Comment by Frostyyyyyy** [comment]
thank you
