### ISSUE TITLE
luck perms is not compatible with a plugin

### ISSUE THREAD

**Issue by broken1arrow** [lucko/LuckPerms#2617]
### Description
I have not set any player perms or group perms, but by default all perms is on true on veinminer. No problem if i use ultra permissions (i have copy in same perms for hand) And i not set any perms for veinminer in any groups.

### Reproduction steps
Yes i done several steps and get help on DC.

this is only part of perms player shall not have access too, players get access too all veinminer commands
https://luckperms.net/verbose/YruRTYJpWn

No player not op, he cant use /plugin,/version or /reload

### Expected behaviour
Shall not have access too all commands.

### Environment details

Pappermc 1.16.2 184

LuckPerms version: 5.1.93

### Any other relevant details

I have ask on veinminer, but i think is more a LP issue.
![2020-09-12_08 04 59](https://user-images.githubusercontent.com/16368286/92989874-c3e60880-f4d7-11ea-9fe5-bff4cf558cc0.png)

**Comment by Laarryy** [comment]
Looks like the player you're testing with has that permission from somewhere. Run `lp user <name> checkinherits veinminer.toggle` to see where it's coming from. If it returns undefined, run `/lp editor` and send the the link.

**Comment by broken1arrow** [comment]
![2020-09-12_09 16 55](https://user-images.githubusercontent.com/16368286/92990025-d7de3a00-f4d8-11ea-9d2c-bfdb00c6bb37.png)

I don´t know if good idea to post it with all user uuid.

**Comment by Laarryy** [comment]
User uuids aren't private and can be found by simply googling their names. Send the link

**Comment by broken1arrow** [comment]
> 
> 
> User uuids aren't private and can be found by simply googling their names. Send the link

oright https://luckperms.net/editor/Y0eRq0YXlA

**Comment by broken1arrow** [comment]
When i look on it, it give player /veinminer mode, /veinminer toggle /veinminer version but not /veinminer reload.

And all of veinminer perms, i think players get this some how, ultra permissions can block this for player use some how. I think you need add something to LP, some block all perms from get use if I not add it. 
veinminer.veinmine.*
veinminer.toggle
veinminer.mode

**Comment by benwoo1110** [comment]
Looks like a miss configuration. You have perms set to true directly for the user, which will be prioritised over perms inherited from group. And this spins also why you are experiencing perm being true even if it's not set in any group. The issue you face not due to a incompatible or a bug.

![image](https://user-images.githubusercontent.com/30431861/92994841-8bbee400-f530-11ea-93de-400ac0185746.jpeg)

**Comment by broken1arrow** [comment]
> 
> 
> Looks like a miss configuration. You have perms set to true directly for the user, which will be prioritised over perms inherited from group. And this spins also why you are experiencing perm being true even if it's not set in any group. The issue you face not due to a incompatible or a bug.
> 
> ![image](https://user-images.githubusercontent.com/30431861/92994841-8bbee400-f530-11ea-93de-400ac0185746.jpeg)

Yes i know, it way i use a other player some not have admin group and only "luffare"

**Comment by broken1arrow** [comment]
Seems to be so in any case with these two plugins, so perms are handled quite differently and it is not easy to know what is a bug or user error.

But may put perms on false in the group and see if the person who makes the plugin can change a bit (because on the server it is not so good to give everyone access to all tools directly).

I simply have to watch out for this in the future in the plugin I add.
Yes i give glizh_ perms, but it was for testing it on an account that does not have staff perms
https://luckperms.net/editor/QZTa4Ru1yn

**Comment by lucko** [comment]
Seems to be misconfiguration then, not a bug :)

**Comment by broken1arrow** [comment]
> 
> 
> Seems to be misconfiguration then, not a bug :)

Depends a lot on what you are used to how prems also work.

In any case, it seems to be quite different between these two plugins (one allows some defualt perms others do not even allow these).

So not only "misconfiguration", the error is how different these two plugins I compare work with perms.
