### ISSUE TITLE
Extra users being added

### ISSUE THREAD

**Issue by DaddyGamerGuy** [lucko/LuckPerms#2618]
### Description

Every time I open the editor there are more and more no name users added, right now its at 323 when we only have 3 players playing

### Reproduction steps

Not sure, it seems to get worse over time, maybe on restart

1. Open the config.yml file and set example to true.
2. Restart the server
3. Run /lp user example permission set x from the console

### Expected behaviour

Only show users who exist

### Environment details

* Server type/version: `ExampleSpigot` running version `1.12.2` build `???`
* LuckPerms version: `v???` forge 1.12.2 5.1.82

http://gamerguys.net:85/lp1.png

**Comment by BrainStone** [comment]
What setting in the config are you talking about?

**Comment by DaddyGamerGuy** [comment]
Nothing in the config, I think its adding non existent users to the database.
I see them in the editor, we only have 3 players but over 300 users in LP
Look at the screenshot here http://gamerguys.net:85/lp1.png

**Comment by benwoo1110** [comment]
Your luckperms version is important as it may have been an old bug that was fixed. Send screenshot of `/lp info`

**Comment by benwoo1110** [comment]
Your luckperms version is important as it may have been an old bug that was fixed. Send screenshot of `/lp info`

**Comment by benwoo1110** [comment]
Your luckperms version is important as it may have been an old bug that was fixed. Send screenshot of `/lp info`

**Comment by benwoo1110** [comment]
Your luckperms version is important as it may have been an old bug that was fixed. Send screenshot of `/lp info`

**Comment by benwoo1110** [comment]
Your luckperms version is important as it may have been an old bug that was fixed. Send screenshot of `/lp info`

**Comment by benwoo1110** [comment]
Your luckperms version is important as it may have been an old bug that was fixed. Send screenshot of `/lp info`

**Comment by benwoo1110** [comment]
Your luckperms version is important as it may have been an old bug that was fixed. Send screenshot of `/lp info`

**Comment by benwoo1110** [comment]
Your luckperms version is important as it may have been an old bug that was fixed. Send screenshot of `/lp info`

**Comment by benwoo1110** [comment]
Your luckperms version is important as it may have been an old bug that was fixed. Send screenshot of `/lp info`

**Comment by benwoo1110** [comment]
Your luckperms version is important as it may have been an old bug that was fixed. Send screenshot of `/lp info`

**Comment by benwoo1110** [comment]
Your luckperms version is important as it may have been an old bug that was fixed. Send screenshot of `/lp info`

**Comment by benwoo1110** [comment]
Your luckperms version is important as it may have been an old bug that was fixed. Send screenshot of `/lp info`

**Comment by DaddyGamerGuy** [comment]
Cant run minecraft right now, but here it is ran from console
12.09 07:05:11 [Server] pool-5-thread-1/INFO [LP] Running LuckPerms v5.1.82 by Luck.
12.09 07:05:11 [Server] pool-5-thread-1/INFO [LP] -  Platform: Sponge
12.09 07:05:11 [Server] pool-5-thread-1/INFO [LP] -  Server Brand: SpongeForge
12.09 07:05:11 [Server] pool-5-thread-1/INFO [LP] -  Server Version:
12.09 07:05:11 [Server] pool-5-thread-1/INFO [LP]      SpongeAPI: 7.3.0-299f484b6 - SpongeForge: 1.12.2-2838-7.3.1-RC4077
12.09 07:05:11 [Server] pool-5-thread-1/INFO [LP] -  Storage:
12.09 07:05:11 [Server] pool-5-thread-1/INFO [LP]      Type: H2
12.09 07:05:11 [Server] pool-5-thread-1/INFO [LP]      File Size: 0.38MB
12.09 07:05:11 [Server] pool-5-thread-1/INFO [LP] -  Messaging: None
12.09 07:05:11 [Server] pool-5-thread-1/INFO [LP] -  Instance:
12.09 07:05:11 [Server] pool-5-thread-1/INFO [LP]      Static contexts: None
12.09 07:05:11 [Server] pool-5-thread-1/INFO [LP]      Online Players: 0 (1 unique)
12.09 07:05:11 [Server] pool-5-thread-1/INFO [LP]      Uptime: 1h 11m 16s
12.09 07:05:11 [Server] pool-5-thread-1/INFO [LP]      Local Data: 3 users, 2 groups, 0 tracks

**Comment by DaddyGamerGuy** [comment]
I upgraded it and will see if hat helps, is there any way to remove all of the extra users?
I know SQL if there is a way to connect to the db, I cant find a config file with the users in it

**Comment by benwoo1110** [comment]
If you are using SQL database as perm storage, then perms won't be in a config file, but rather sqltables in your SQL database, so you need to login to your SQL database to see it. User's sqltable name should be named `luckperms_user` iirc.

If you are using the latest version of luckperms from https://luckperms.net/download, you will also be able to delete users using the new web editor feature.
![image](https://user-images.githubusercontent.com/30431861/92997955-96d23e00-f549-11ea-87ad-c307fcbb60ba.png)
