### ISSUE TITLE
Unable to open web editor.

### ISSUE THREAD

**Issue by Blizz2210** [lucko/LuckPerms#2619]
Greetings,

Today as usual when I was editing permissions everything was working fine and suddenly I got an error.
"Unable to communicate with the editor. Check the console for the error".

Here is the console log.

https://pastebin.com/MqQcW7UW

I restart Server, delete config, tried opening "https://bytebin.lucko.me/" it was loaded, but I don't know what to upload...
I tried all the basic solutions.

**Comment by benwoo1110** [comment]
Seems that cloudflare is having issues, https://www.cloudflarestatus.com/

**Comment by broken1arrow** [comment]
I get it work now, but cloudflare can still have issues.

**Comment by Blizz2210** [comment]
Aah, seems like there is nothing I could do right now.

Thanks!
