### ISSUE TITLE
BungeeCord API hasPermission returns false, even if it's set to true.

### ISSUE THREAD

**Issue by Darkfield** [lucko/LuckPerms#262]
I check in Bungee event called: ChatEvent for permission for certain commands with:
sender.hasPermission(); and it returns false, even if should be true.

Tried /lpb sync - doesn't change anything.
[LP] Running LuckPerms v3.1.25.
This server is running BungeeCord version git:BungeeCord-Bootstrap:1.11-SNAPSHOT:53cc324:1229 by md_5

**Comment by lucko** [comment]
Pastebin your config file & the output of `/lp user <you> permission info`, as well as `/lp group <group> permission info` for the groups you inherit from.

**Comment by Darkfield** [comment]
Config: https://gist.github.com/Darkfield/9db4a9700a8efaef7268ef63f23e7a29

18:54:59 [INFO] [LP] test's Nodes:
18:54:59 [INFO] > group.default (true)
18:54:59 [INFO]
18:54:59 [INFO] [LP] test's Temporary Nodes:
18:54:59 [INFO] > group.swadmin2
18:54:59 [INFO] -    expires in 29 days 21 hours 45 minutes

18:55:25 [INFO] [LP] swadmin2's Nodes:
18:55:25 [INFO] > admin2.skywars (true)
18:55:25 [INFO] > bat.ban (true)
18:55:25 [INFO] > bat.ban.skywars (true)
18:55:25 [INFO]
18:55:25 [INFO] [LP] swadmin2's Temporary Nodes:
18:55:25 [INFO] None

**Comment by lucko** [comment]
Set this `include-global: false` to true in your config and restart the proxy.
