### ISSUE TITLE
lang.yml not working (in some cases)

### ISSUE THREAD

**Issue by beeboy07** [lucko/LuckPerms#2620]
lang.yml doesn't working in some way, I tried diffrent servers, computers, versions and translations...

Some of values not changing in mine. He is worked out (even we use same version)

https://discordapp.com/channels/241667244927483904/241667244927483904/754420625279549520
and I also told someone else to try this and he worked out too, he just restarted the server. Last time i tried it on a server and it didn't work, just like my computer

Example, German translation not working too, some of values not changing as same. No error in console and plugin finds lang.yml

**Comment by underscore11code** [comment]
With the recent 5.2 translation overhaul, this issue is likely fixed.
