### ISSUE TITLE
Prefix & Suffix Stacking does not work

### ISSUE THREAD

**Issue by bitpickle** [lucko/LuckPerms#2621]
I tried to configure to appear more than one prefix in the chat following this tutorial: https://github.com/lucko/LuckPerms/wiki/Prefix-&-Suffix-Stacking

So I did following this code:
 
`prefix:
  format:
    - "highest_on_track_prison"
    - "highest_on_track_donor"
    - "highest_on_track_staff"
  duplicates: first-only
  start-spacer: ""
  middle-spacer: " "
  end-spacer: ""`

So my configuration file looks like this:

`prefix {
    format = [
        "highest_on_track_donator",
        "highest_on_track_rankup"
    ]
    duplicates = "first-only"
    start-spacer = ""
    middle-spacer = " "
    end-spacer = ""
  }`

I did anything wrong?

I want that display in the chat something like: [MVP][Trainer]Player

But it's displaying just: [MVP]Player

**Comment by Turbotailz** [comment]
Confirmed working during Discord conversation, issue lies with the chat plugin.
