### ISSUE TITLE
I get kicked when i do `/lp` then hit space, after setting up bungeecord

### ISSUE THREAD

**Issue by MrMcyeet** [lucko/LuckPerms#2623]
### Description

So i recently installed a 2nd server, and a bungee proxy onto a dedicated server that i rent, and now when i do `/lp` then hit space, i get kicked with ``` 
DecoderException : java.lang.IndexOutOfBoundsException: readerIndex(0) + length(1) exceeds writerIndex(0): UnpooledSlicedByteBuf(ridx: 0, widx: 0, cap: 0/0, unwrapped: PooledUnsafeDirectByteBuf(ridx: 2, widx: 2, cap: 2048)) @ io.netty.handler.codec.MessageToMessageDecoder:98 ```.

Im sure its something that i have setup wrong, but i cannot seem to fix it.
Also, im like 85% sure that its something with the tab complete suggestions, cause when i do `/bc mrmcyeet lp user SarahCookie parent add staff` it works fine. (/bc is a small command i had made for our server, basically it lets us sudo other players and console and also set delays for certain commands, the only caveat is that there is no tab completes when you use `/bc`)

### Reproduction steps

1. uhh, setup bungeecord, with the luckperms bungeecord version on the proxy,
2. Have luckperms on your server
3. do `/lp` then hit space
4. get kicked?

### Expected behaviour

You not get kicked, but instead see the tab complete suggestions?

### Environment details

* Yatopia version git-Yatopia-"79de07b" (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)
* LuckPerms version: 5.1.107

Bungee config.yml = https://pastebin.com/hCMQzEQJ
Bungee lp config.yml = https://pastebin.com/YB3A3uvf
Actual server lp config.yml = https://pastebin.com/VXvcd877

### Any other relevant details

This had happened before i installed lp on the bungee proxy, i figured i might as well try to see if installing it on the bungee proxy would help/solve it.

**Comment by benwoo1110** [comment]
Firstly, what is Yatopia?
Also are you running the luckperms command on your backend server or on bungeecord?

**Comment by Laarryy** [comment]
Try using Paper and not Yatopia - keep everything else the same regarding LP. 

Also, send a full log including when you try and run the command and the full error following it - leave no lines out.

Thanks! 😄

**Comment by MrMcyeet** [comment]
1) Yatopia is a fork of Tuinity, which itsself is a fork of Paper --> https://github.com/YatopiaMC/Yatopia
2) With the latest build of paper i get kicked the same as when i was on Yatopia
3) There is no log, cause i never get the command out, it happens while im typing the command. Like as soon as i hit space after typing `/lp` it kicks me.
4) The only thing that i see is from the bungeecords console which reads this --> 
<img width="1271" alt="fadsafdsfdasfdsa" src="https://user-images.githubusercontent.com/68966344/93315722-fe4def00-f7d0-11ea-9d73-01750950b4b9.PNG">

**Comment by benwoo1110** [comment]
1. For bungee proxy are you using some fork or just stock bungeecord?
2. Can you try with only luckperms plugins installed on both paper and bungeecord server?

**Comment by MrMcyeet** [comment]
1. Stock bungeecord
2. Yeah, gimme a min to set it up.

**Comment by MrMcyeet** [comment]
oof, ok so with stock bungee(and waterfall...) and a fresh paper(and yatopia too..) it does not happen.

So its deffo a plugin (or mabey a config i have) thats causing it.
Anyone got any ideas as to which plugin might be causing it, other than removing half of em, then trying, rinse and repeat till i find the problem child.

**Comment by Turbotailz** [comment]
Hard to say without a list of plugins bit a binary search is likely the best way to find out.
