### ISSUE TITLE
Changes don't save

### ISSUE THREAD

**Issue by Prometheus2048** [lucko/LuckPerms#2625]
I really don't know what to do anymore. I've tried pretty much everything I can think off. The problem is that changes are not applied on my server. I was able to give a few players the wildcard (/lp user USER permission set * true). This works without any problems.
However: I can't take away these permissions. I originally wanted to try if Universe Guard 2 was working correctly, so I wanted to disable the wildcard for one of the players. Ok, that sounds easy. /lp user USER permission set * false. But what happens is exaclty nothing. The player can still use every vanilla command.
Next I tried the editor (/lp editor). This method kinda worked. I disabled all the permissions for the player and put him into the group default. After saving, pasting the /apply command and generating a new /editor session as the website advised, the rules were applied. At least until I closed the editor and created another session. Then his permissions magically returned.
What can I do? Is it me or the plugin?

### Reproduction steps
Ok, so:
1. /lp user EXAMPLEUSER permission set * true
2. /lp user EXAMPLEUSER permission set * false
Result: Nothing

1. /lp user EXAMPLEUSER permission set * true
2. /lp editor
3. Edit the permissions and set them all to FALSE
4. Run the /lp apply command
5. Create a new /lp editor session
Result: Works until I use the /lp editor command again

### Environment details

RunniForge 1.12.2
Version: 5.1.17 for Spongeforge

**Comment by baailey** [comment]
If you want to remove a permission, simple do /lp user [user] permission unset [permission]

Setting a permission to false will not remove it, just disallow said user access.

**Comment by Prometheus2048** [comment]
> 
> 
> If you want to remove a permission, simply do /lp user [user] permission unset [permission]
> 
> Setting a permission to false will not remove it, just disallow said user access.

Doesn't work. I unset permission for *, but the player can still use all the commands.

**Comment by Laarryy** [comment]
Run `lp editor` in console and send the link it generates here please

**Comment by Laarryy** [comment]
Also, please update your version of luckperms from http://luckperms.net
