### ISSUE TITLE
Parse hex colors in LP command outputs

### ISSUE THREAD

**Issue by paulpls** [lucko/LuckPerms#2626]
### Description

Hello,

Currently LuckPerms supports adding legacy color codes to things like group displaynames, e.g. `&4Admin`. These color codes are parsed everywhere LuckPerms shows the group's displayname, such as `lp group admin info`, `lp listgroups`, and confirmation messages when setting group permissions.

Bukkit uses the following to define hex colors: `&x&r&r&g&g&b&b`. Assuming this syntax, an admin group with a colored displayname of `&x&f&f&0&0&0&0Admin` displays as `&xAdmin` in the output of the commands above, with "Admin" in &0/black instead of the expected red. The `&#rrggbb` and `#rrggbb` formats, while preferable to the Bukkit syntax, also do not parse.

### Proposed behaviour

I'm fully aware that LuckPerms _is not intended_ to handle chat formatting and such. My suggestion instead is to add this functionality to LuckPerms's own command outputs and notifications, so that group displaynames are displayed predictably there as well.

Thank you for your consideration!

**Comment by Fefo6644** [comment]
There's currently #2419 for that. By the looks of it, while Luck is aware and does want to implement it, it seems like it's most definitely not a high priority feature; after all, LP doesn't handle chat ¯\\\_(ツ)\_/¯

**Comment by paulpls** [comment]
Duplicate of #2419
