### ISSUE TITLE
Random context when adding parent/promoting on track

### ISSUE THREAD

**Issue by DriesMelkebeke** [lucko/LuckPerms#2627]
### Description

Whenever I try to add a part to a user, or promote him on a rankstrack it gives him the correct rank but includes a duplicate with another servers context.

### Reproduction steps

1. /lp user <playername> promote <track> on one of the servers
2. User will randomly get the same rank, with another servers' context on it

### Expected behaviour

User should get promoted on the track without getting any duplicates

### Environment details

* Server type/version: `Paper-199 1.16.3`
* LuckPerms version: `v5.1.107`

Database details replaced for obvious reasons

Config on bungeecord:
https://gist.github.com/DriesMelkebeke/a768bfe50371b677942d4af3ff1c0f59

Config on backend server 1:
https://gist.github.com/DriesMelkebeke/271e7763dc912ceb7ee0d88d80980175

Config on backend server 2:
https://gist.github.com/DriesMelkebeke/cf0e61eae90b053360b7f7c3d41473dd

Issue happening in a GIF:
https://cdn.discordapp.com/attachments/241667244927483904/756844956089319444/explanation.gif

LP editor link:
https://luckperms.net/editor/veewlol3FX

**Comment by Moose1301** [comment]
Any errors in console?

**Comment by DriesMelkebeke** [comment]
No errors whatsoever. Like you see in chat I'm just getting the log on both backend servers that a user got promoted, or that his rank changed in context GLOBAL.

**Comment by benwoo1110** [comment]
Just realise, in your config `messaging-service: none`, it should be set to sql for all of LP

**Comment by DriesMelkebeke** [comment]
Exactly the same result when all servers are set to "auto" or to "sql"

**Comment by benwoo1110** [comment]
Also why is `auto-push-updates: false`? It should be true else perms may not update properly

**Comment by DriesMelkebeke** [comment]
One of the things I was testing to see if that was causing it. Also exactly the same result with `auto-push-updates: true`

**Comment by benwoo1110** [comment]
oh well, hard to conclude anything without anyone else facing the same issue, or a proper reproducible step. 2 things you should try is reproduce with only Luckperms plugin installed, and with a complete fresh database and server setup.

**Comment by DriesMelkebeke** [comment]
I understand. I've already tried that. 
Another interesting detail: 
This ONLY happens with both backend1 and backend2 server online. If one of the two goes offline it does not happen and everything works as expected.

**Comment by lucko** [comment]
I've done a lot of looking through the source code and testing this locally - I haven't been able to reproduce, and frankly not sure how it would even be possible.

The only conclusions I can come to are that either you are mistaken about what's actually happening, or there's another plugin doing something funky with LuckPerm's API. Either way, there is not much I can do investigate further.

If you come across any further details which you think may be useful, please feel free to post them. Until then, I'm going to close this issue.
