### ISSUE TITLE
Luckperms Bungeecord not working D:

### ISSUE THREAD

**Issue by Zpes** [lucko/LuckPerms#2628]
So I have recently changed my server from paper to bungee, reinstalled most of the plugins that I needed to install. Followed an youtube tutorial step by step on how to install it for bungee. Doesn't work. When I apply changes the changes apply but they dont work in game. For instance I can make an prefix, but it doesnt show ingame while I correctly made it.

**Comment by benwoo1110** [comment]
Firstly, bungeecord is a proxy server, which links multiple spigot/paper servers together. So you can’t replace your paper server with it. Then, not all plugin needs to be installed in bungeecord, some only need to be installed on the respective spigot/paper server. As for luckperms, you need normal luckperms on all normal server and luckperms-bungee on bungeecord proxy. https://www.luckperms.net/downloads

**Comment by benwoo1110** [comment]
To add on, you need to sync all of luckperms to a common sql database. https://github.com/lucko/LuckPerms/wiki/Syncing-data-between-servers
