### ISSUE TITLE
[SUGGESTION] Rank specific permissions

### ISSUE THREAD

**Issue by EvilPandaMan** [lucko/LuckPerms#2629]
### Description
A way to create a rank specific permissions that are not passed through inheritance.

### Proposed behaviour
That will permit to create plugins that allow a rank to have access to something specific to that rank without passing it forward to other ranks. 
perhaps a checkmark that when checked, set a permission to be specific to a rank. By default that option is disabled.

**Comment by Turbotailz** [comment]
This can already be done by simply setting the permission node to `false` in the group which inherits said permissions.
