### ISSUE TITLE
Wildcard in the middle not working

### ISSUE THREAD

**Issue by BrainStone** [lucko/LuckPerms#263]
Wildcards that are in the middle of a permission string are not working.

Example: Giving a player `nucleus.*.exempt.cost` and then testing if they have the permission `nucleus.rtp.exempt.cost` yields an `undefined result`.

Running LuckPerms Sponge v3.1.26 on SpongeForge 1.11.2-2282-6.0.0-BETA-2287

**Comment by Yann151924** [comment]
You can use this as a temporary workaround : https://github.com/lucko/LuckPerms/wiki/Advanced-Setup#regex

**Comment by BrainStone** [comment]
Thanks. I know about regex (and am using it already) but I'd still expect it to work.

**Comment by lucko** [comment]
This is expected behaviour for wildcards. You can only use them at the end of a permission.

If you want to include them in the middle, use regex permissions.
