### ISSUE TITLE
Unable to upload permission data to the editor. 

### ISSUE THREAD

**Issue by OLIFAB** [lucko/LuckPerms#2631]
Hi there im having a big issue when i type /lp editor! 
when i type /lp editor it comes up with this [Unable to upload permission data to the editor.]

![edito r](https://user-images.githubusercontent.com/71281565/94053312-170e6400-fdd2-11ea-96e9-8b177d3b0212.PNG)

**Comment by Moose1301** [comment]
Any Errors in console?

**Comment by OLIFAB** [comment]
Hi there when i type /lp editor nothing comes up in the console 

![ffdfffff](https://user-images.githubusercontent.com/71281565/94177376-5485f680-fe91-11ea-8e4e-f7da5205d1c2.PNG)

**Comment by Moose1301** [comment]
Server version and luckperms version

**Comment by underscore11code** [comment]
If you're able to, see if the server is able to connect to https://bytebin.lucko.me (What stores the data for the editor)

**Comment by OLIFAB** [comment]
Hi there ive just updated it because it was a older version and its now coming up with this error. and its a spigot server 
!
[edhgdfghfdghfdh](https://user-images.githubusercontent.com/71281565/94178173-a7ac7900-fe92-11ea-9463-01890f4876e2.PNG)

**Comment by Moose1301** [comment]
What version how spigot, like /about

**Comment by OLIFAB** [comment]
![Capture](https://user-images.githubusercontent.com/71281565/94180557-19d28d00-fe96-11ea-9a69-8bb8cedb6893.PNG)

**Comment by underscore11code** [comment]
@Moose1301 This is not a spigot version issue.

**Comment by OLIFAB** [comment]
Whats the issue then?

**Comment by underscore11code** [comment]
Your server not being able to contact our servers for the editor

**Comment by OLIFAB** [comment]
Ok is there anyway of fixing that?

**Comment by Laarryy** [comment]
Contact your host, there is nothing we can do to get your server to be able to connect.

**Comment by OLIFAB** [comment]
Im the host of the server im hosting it from my house! but im not sure how to do that

**Comment by OLIFAB** [comment]
What should i do now??

**Comment by Laarryy** [comment]
Open up command prompt, run `ping https://bytebin.lucko.me` and send a screenshot of the output.

Go into your browser, go to https://bytebin.lucko.me and send a screenshot of the page that comes up.

**Comment by OLIFAB** [comment]
![ping](https://user-images.githubusercontent.com/71281565/94202614-e56ec900-feb5-11ea-9386-3b0d7b53d866.PNG)

![website](https://user-images.githubusercontent.com/71281565/94202537-beb09280-feb5-11ea-8786-02855eb7de01.PNG)

**Comment by Moose1301** [comment]
are you behind a school or work firewall?

**Comment by Turbotailz** [comment]
This is either a problem on your computer or network. You might have an antivirus program installed which is blocking the connection (disable it and see if it works), or the issue could be higher up in the network chain. Not a lot we can do about that, you're going to have to investigate.

**Comment by OLIFAB** [comment]
Hi there ive tryed everything like turning the firewall of the server running my minecraft server and ive tryed turning of the firewall on my main pc but nothings worked and ive even turned the firewall of on my router and ive chcked all the setting on my router but nothing made a diffrence
