### ISSUE TITLE
LuckPerms Prefix not being assigned

### ISSUE THREAD

**Issue by Rehrocko** [lucko/LuckPerms#2632]
I have a group with a prefix with color codes and it is on the web editor, I save it, it says that the prefix is there, but when I assign myself the group and do /lp user <user> info it doesn't show the prefix.

1. Make a group with a prefix
2. Save it
3. Assign it to the player
4. /lp user <user> info

For the "Prefix" category to have the assigned prefix

### Environment details

* Server type/version: `ExampleSpigot` running version `1.12.2` build `???`
* LuckPerms version: `v???`

Paper Spigot running version 1.16.2
Luckperms version 5.1.26

No Errors in console

The prefix was very long ("&x&F&F&A&0&7&AD&x&F&F&9&1&6&6-&x&F&F&8&2&5&1C&x&F&F&7&3&3&DL&x&F&F&6&3&2&9A&x&F&F&5&4&1&4S&x&F&F&4&5&0&0S").

I use using JSON storage for longer prefix strings.

**Comment by Moose1301** [comment]
Have you tried updating Luckperms?

**Comment by Rehrocko** [comment]
Settings the player's prefix through commands won't work (It doesn't assign the prefix to the player's meta)

Updating LuckPerms did nothing.

**Comment by Rehrocko** [comment]
Fixed by reinstalling Vault
