### ISSUE TITLE
Group prefix and suffix placeholders

### ISSUE THREAD

**Issue by VendoAU** [lucko/LuckPerms#2634]
Would it be possible to implement new placeholders for the player's group's suffix and prefix?

For example, I am changing player name colours by appending colour codes to the end of player prefixes but I don't want this to affect my tablist which is using ```%luckperms_prefix%```.
I suggest a new ```%luckperms_group_prefix%``` prefix to solve this issue.

Thanks.
 -VendoAU

**Comment by Turbotailz** [comment]
You might be interested in the [prefix/suffix element placeholders](https://github.com/lucko/LuckPerms/wiki/Placeholders#luckperms_prefix_element_element) which can use any of the elements from [this page](https://github.com/lucko/LuckPerms/wiki/Prefix-&-Suffix-Stacking#how-do-i-add-other-elements).

**Comment by VendoAU** [comment]
> You might be interested in the [prefix/suffix element placeholders](https://github.com/lucko/LuckPerms/wiki/Placeholders#luckperms_prefix_element_element) which can use any of the elements from [this page](https://github.com/lucko/LuckPerms/wiki/Prefix-&-Suffix-Stacking#how-do-i-add-other-elements).

Thanks, I was able to get my desired result by creating a track containing all groups called "groups" and then using ```%luckperms_prefix_element_highest_on_track_groups%```
