### ISSUE TITLE
Attempt at reading data after H2 database connection is closed.

### ISSUE THREAD

**Issue by Fefo6644** [lucko/LuckPerms#2635]
### Description

*Sometimes* when stopping the server I get [these warnings](https://gist.github.com/Fefo6644/b7f1e784922cac47ff125d1d6f745b73).

### Reproduction steps

I don't know man, sometimes it happens sometimes it doesn't, though when it happens, it does so when stopping the server, it doesn't randomly happen at other times.

### Expected behaviour

Well I would expect it to close the connection and not make any queries after lol

### Environment details

* Server type/version: `Paper` running version `1.16.3` build `204`
* LuckPerms version: `v5.1.107`

Provided [config file](https://gist.github.com/Fefo6644/a6d38bb28388d3ea6400b483baf9880d) cuz 🤷🏻‍♂️

### Any other relevant details

It is worth noting that there is a `luckperms-h2.trace.db` :thinking:
And thankfully this just be my testing server so I have nothing to lose in here, but it could happen anywhere else I suppose.

**Comment by Timmy109** [comment]
Pfffttt aren't you supposed to help these sorts of people?
(jk)

**Comment by lucko** [comment]
Not much I can do - to be honest it throwing an exception is probably the best behaviour in this case.
