### ISSUE TITLE
LuckPerms is spamming my console??

### ISSUE THREAD

**Issue by ZanyFilmz** [lucko/LuckPerms#2636]
I have tried again and again after creating a permissions setup with different groups and such to enter in the command that the editor give you to sync the permissions with your server, But not only can I not manage to do that I can't even attempt to add myself or another player to a permission group. There is so much going though my console and I'm not sure how to fix any of this!!! Please help! 

Here is what I See in console:
https://pastebin.com/S3R5xJfR

**Comment by Timmy109** [comment]
Your pastebin link does not go anywhere

**Comment by benwoo1110** [comment]
When you use the editor, did you:
1. Press the + button after typing in the permission?
2. Press the save button on the top right and run the apply edits command (best in console)
3. Create a new editor session after every apply edits?

It will be very useful if you send your editor link as well.

**Comment by ZanyFilmz** [comment]
> When you use the editor, did you:
> 
> 1. Press the + button after typing in the permission?
> 2. Press the save button on the top right and run the apply edits command (best in console)
> 3. Create a new editor session after every apply edits?
> 
> It will be very useful if you send your editor link as well.

Yea I did. Everything with the editor was fine. It was when I have to input the command that the editor gives you after saving when the problem starts.

**Comment by underscore11code** [comment]
GriefPrevention is causing all that error spam. Ensure you're up to date on both LP and GP, otherwise go talk to GP support.

**Comment by ZanyFilmz** [comment]
> GriefPrevention is causing all that error spam. Ensure you're up to date on both LP and GP, otherwise go talk to GP support.

What is LP and GP?

**Comment by ZanyFilmz** [comment]
nvm
