### ISSUE TITLE
Permission Description

### ISSUE THREAD

**Issue by hellot1m** [lucko/LuckPerms#2638]
### Description
A way to view each permissions built in description. 

### Proposed behaviour
My thought would be when you hover your mouse over the permission name, it gives you a description of what the permission does. This text is typically already built into each plugin, so you would just need to be able to pull this information within the web editor.

Another way, would be to add a new text box to the right of the permission. There's plenty of empty room to fit this in. You could have the description auto populate there. In both the bottom search bar area and after applying it to right as well. 

A few other people on the discord gave some interesting ways this could be implemented too, like using Ctrl+t while over the permission.

**Comment by Laarryy** [comment]
If this is a web editor suggestion, it would probably be best to add it to lucko/LuckPermsWeb

**Comment by hellot1m** [comment]
Thanks! ill copy and paste this there. Isn't there a github feature to loop in another repository?

**Comment by lucko** [comment]
I think this is the sort of thing that plugins should document - I don't think duplicating it elsewhere is a good idea.

**Comment by hellot1m** [comment]
Nearly all plugins already document this and many permission plugins (like ultra permissions) pull this data already from those plugins. There's nothing on luckperms side that is needed to store this information. Just like right now, luckperms doesn't store every single permission from all plugins on the web. And they also don't store the permissions themselves in any database locally or on a online database. Luckperms just reads the permissions provided by the plugin. All that's needed is the ability to read the descriptions of those permissions. Luckperms is the only permission plugin I've come across that does not do this. And it's a very convenient feature that many others agree with. Could you please reconsider this feature instead of casting it aside as "useless".
