### ISSUE TITLE
MyCommand - custom permissions not working

### ISSUE THREAD

**Issue by LazosPlaying** [lucko/LuckPerms#264]
So you may have heard about a plugin called "MyCommand it allows you to create aliases, menus, clickable NPCs, clickable blocks, etc...
If you create a custom alias and set a custom permission for that, that permission will not work.

Example:
`send-arcade:
  command: /cmd-server-arcade
  type: BUNGEE_TP
  server_name: arcade
  delaytimer: 3
  permission-required: true
  permission-node: mycmd.server.defaults`

so the required permission should be mycmd.server.defaults but even if i add it to the user itself or the default group, it does not work. It is not checked my LuckPerms

Regards.

**Comment by lucko** [comment]
Please do the following:

1. Run `/lp verbose record <your username>`
2. Run the send-arcade command
3. Run `/lp verbose paste`, and paste the link it gives you back to me.

**Comment by LazosPlaying** [comment]
Hello.
I reinstalled the whole thing and seems like it works.
I don't know why it did not work before, i suppose my configuration...

I request lock.

Regards, thank you for such a good resource 😄
