### ISSUE TITLE
Luckperms setting 2 prefixes 

### ISSUE THREAD

**Issue by cb12438** [lucko/LuckPerms#2641]
So when i do /lp group owner meta setprefix 999 "&4Owner " it puts two of them 
![Screen Shot 2020-09-27 at 6 03 50 PM](https://user-images.githubusercontent.com/55159369/94380887-2819e680-00ec-11eb-8a13-f6bbd5ef9db8.png)
like that does anyone know how to fix this?

**Comment by Fefo6644** [comment]
Please provide a screenshot running `/lp user <yourself inheriting owner group> info`.

**Comment by cb12438** [comment]
![Screen Shot 2020-09-27 at 6 21 16 PM](https://user-images.githubusercontent.com/55159369/94381531-9069c780-00ee-11eb-934d-143500b86995.png)
if i did it wrong let me know i think i did

**Comment by cb12438** [comment]
i was confused sorry if i did it multiple times

**Comment by Fefo6644** [comment]
?? That's literally not what I asked for. Run `/lp user <yourself> info` and share a screenshot.

**Comment by cb12438** [comment]
well im sorry ima run that command "/lp user <yourself inheriting owner group> info" that what you said sounded like what i just did sorry

**Comment by cb12438** [comment]
![Uploading Screen Shot 2020-09-27 at 6.36.36 PM.png…]()

**Comment by cb12438** [comment]
![Uploading Screen Shot 2020-09-27 at 6.36.36 PM.png…]()

**Comment by cb12438** [comment]
![Screen Shot 2020-09-27 at 6 39 36 PM](https://user-images.githubusercontent.com/55159369/94382234-d45dcc00-00f0-11eb-8b26-f7bed8409dae.png)

**Comment by benwoo1110** [comment]
command is `/lp user <yourself> info` you need to include the **playername**. Also the latest screenshot isn’t loading for me

**Comment by cb12438** [comment]
yea it wasn't for me either i resent it

**Comment by Fefo6644** [comment]
Okay... now run and share a screenshot of `/lp user <yourself> meta info`.

**Comment by cb12438** [comment]
![Uploading Screen Shot 2020-09-27 at 6.43.32 PM.png…]()

**Comment by cb12438** [comment]
![Screen Shot 2020-09-27 at 6 43 32 PM](https://user-images.githubusercontent.com/55159369/94382404-6960c500-00f1-11eb-93a0-d94591126918.png)

**Comment by benwoo1110** [comment]
looks like, you haven’t even ate prefix, or delete it midway. screenshot `/lp group owner meta info`

**Comment by cb12438** [comment]
oh i removed the group off of me for now 
![Screen Shot 2020-09-27 at 6 51 15 PM](https://user-images.githubusercontent.com/55159369/94382708-96fa3e00-00f2-11eb-8853-54b735c19e52.png)

**Comment by Fefo6644** [comment]
Well, it appears properly in there, so it's probably an issue with your chat formatting plugin. You might want to give this section a read: https://github.com/lucko/LuckPerms/wiki/FAQ#why-are-prefixessuffixes-not-working specifically the item that reads "If you are using Essentials..."

**Comment by cb12438** [comment]
yes i am using essentials

**Comment by cb12438** [comment]
i have it set as false as well so it would not be a problem right?

**Comment by cb12438** [comment]
![Screen Shot 2020-09-27 at 7 03 59 PM](https://user-images.githubusercontent.com/55159369/94383245-56032900-00f4-11eb-9c09-7c1329d45cf0.png)

**Comment by Fefo6644** [comment]
Remove the `#` at the beginning.

**Comment by cb12438** [comment]
ah ok that worked ty very much for the fast response as well

**Comment by cb12438** [comment]
you can re open it if you would like
