### ISSUE TITLE
Issues with server reloads

### ISSUE THREAD

**Issue by TheDoctor025** [lucko/LuckPerms#2643]
### Description

LuckPerms throws errors when players change dimensions, but only after server reloads. This behavior was not present in LuckPerms 5.1.93.

### Reproduction steps

1. Start the server.
2. Observe no errors or warnings.
3. Reload the server with `/reload confirm.`
4. Observe the errors and warnings below. 

### Expected behaviour

Should use player login/disconnect/change world events without throwing errors.

### Environment details

* Server type/version: `Paper` running version `1.16.3` build `206`
* LuckPerms version: `5.1.107`

[Warning immediately after server reload](https://gist.github.com/TheDoctor025/20bc9367e331bf63e0ef3bd3a377e6d0)
[Error upon changing world](https://gist.github.com/TheDoctor025/8c5b92a3c2c9c0156814de448b1f511b)
[Warning upon player disconnection](https://gist.github.com/TheDoctor025/c1e10ed467e2cea6aea70824bb7cb589)
[Error upon player login](https://gist.github.com/TheDoctor025/32fc312c2b796309dfd45404637266b8)

**Comment by benwoo1110** [comment]
`/reload` should never be used on a server you care about.

**Comment by TheDoctor025** [comment]
I'm making a plugin of my own and it's cumbersome to stop/restart the server every time I make a change. That's why I use reload. I never noticed any issues with LuckPerms before updating to the latest version, which is why I opened this issue.

**Comment by Fefo6644** [comment]
If you're making your own plugin AND you know it's reload-safe (save files, clear lists/maps, unregister event listeners, etc.), ***at worst*** you should use something like PlugMan or [ServerUtils](https://www.spigotmc.org/resources/serverutils-bungeecord-spigot-manage-plugins-in-game-plugman-alternative-more.79599/) (this one I use when testing, recommended :p) to reload that specific plugin only (**still not advised**).
