### ISSUE TITLE
I can chat on my server

### ISSUE THREAD

**Issue by JuanPedroYT** [lucko/LuckPerms#2644]
I am creating a new hcf server, and the problem is that when I put luckperms for version 1.7.10 and lazarus is active I cannot chat, I leave this photo for you to review, when I chat I get this in the console.

![Screenshot 2_10_2020 04_03_04](https://user-images.githubusercontent.com/40775478/94896730-8b957280-0464-11eb-80f6-7999b36f1724.png)

Sorry if my English is bad but I'm Argentine, :D.

1- Im using LuckPerms Legacy
2- IDK if lazarus use luckperms Api
3- Im using 1.7.10 PaperSpigot

**Comment by benwoo1110** [comment]
1. Are you using LuckPerms-Legacy version?
2. Does this Lazarus plugin use luckperms API?
3. Please follow the issue template.

**Comment by JuanPedroYT** [comment]
> 1. Are you using LuckPerms-Legacy version?
> 2. Does this Lazarus plugin use luckperms API?
> 3. Please follow the issue template.

1- yeah im using luckperms legacy
2- Idk if lazarus use luckperms api
3- I don't understand what you're trying to tell me with that xD

**Comment by lucko** [comment]
Install the legacy API extension.
