### ISSUE TITLE
How can i get the Expire date from an temporary added group using /user xy parent addtemp? Cant ask on discord right now because i am blocked.

### ISSUE THREAD

**Issue by einfachBlu** [lucko/LuckPerms#2645]

**Comment by Laarryy** [comment]
Do you mean with the LP API or with commands, like `lp user <name> info`

**Comment by einfachBlu** [comment]
Via the api. I did not found any_hing in the docs

**Comment by Turbotailz** [comment]
What is your discord name?

**Comment by einfachBlu** [comment]
Blu#0002, if i remember correct. But i am disabled and have no access for the next 1-2 days

**Comment by Turbotailz** [comment]
My apologies, I thought you were saying you were banned from our Discord.

**Comment by einfachBlu** [comment]
No Problem.

@Laarryy you may know how to receive the duration over the api? i have seen a Node Object with expire fields. but there is no NodeType for PermissionGroup. Just for Permission, chat and some other things

**Comment by Fefo6644** [comment]
> but there is no NodeType for PermissionGroup
`NodeType.INHERITANCE` is what you're looking after.

**Comment by einfachBlu** [comment]
Oh, thx. I thought it is just for the inheritances, not for the permissiongroup itself. I will try that!

**Comment by einfachBlu** [comment]
![image](https://user-images.githubusercontent.com/54118058/95001495-cdd8c400-05ca-11eb-8a23-4d8381587eb2.png)
![image](https://user-images.githubusercontent.com/54118058/95001501-dc26e000-05ca-11eb-8546-007c74b073c9.png)

**Comment by Fefo6644** [comment]
I suggest you
```java
lpUser.getNodes(NodeType.INHERITANCE)
      .stream()
      .filter(Node::hasExpiry)
      .filter(node -> !node.hasExpired())
      .collect(Collectors.toList());
```
It will return a `List<InheritanceNode>` with the user's parent group nodes that have an expiry and have not expired yet. Why a list? Well you can have multiple or no parent groups with an expiry time.

**Comment by einfachBlu** [comment]
Okay thanks! I will try that one :)

**Comment by einfachBlu** [comment]
Yes it works! Thx for the help here :)
