### ISSUE TITLE
Database Error

### ISSUE THREAD

**Issue by eliyash31** [lucko/LuckPerms#2649]
Luckperms Version: 5.1.93
Minecraft version 1.16.3
Hello I don't know what happened but I was just playing in the server and it automatically signs me out and it says like this please refer in the picture 

IMG: https://imgur.com/a/q89rgcD
Pastebin: https://pastebin.com/ZM0vXpYJ

**Comment by benwoo1110** [comment]
The error just means luckperms cant connect to your database. either the db or lp config is wrong. If it was working before, maybe your database is just facing some down time. you can see: https://github.com/lucko/LuckPerms/wiki/Storage-system-errors
