### ISSUE TITLE
Issue connecting to redis

### ISSUE THREAD

**Issue by jaopedropvp** [lucko/LuckPerms#265]
https://hastebin.com/ogakiyoqus.md

**Comment by mikroskeem** [comment]
Is Redis server running, or correctly configured? Make sure it binds on correct IP and optionally set up firewall.

**Comment by jaopedropvp** [comment]
Everything is already right

**Comment by mikroskeem** [comment]
Huh? If it's right, then LP could connect to Redis properly.

Check Redis configuration, its host configuration etc. Make sure you haven't made any typos.

I'd bet that Redis is listening on `127.0.0.1`, target machine has firewall or Minecraft server host blocks outbound connections.

**Comment by jaopedropvp** [comment]
I already tested 127.0.0.1
And firewall is already disabled :(
