### ISSUE TITLE
The Plugins crashed ?

### ISSUE THREAD

**Issue by bacogi** [lucko/LuckPerms#2653]
Hello, can i ask?
after i install the luckperms into plugins folder and restarting my server it works but i have something issues, my server wont opened and always force close.
but if i delete the luckperms it worked hopefully, i dont know why but anyone can help me? it will helpfull
sorry for my english
this is the cmd
https://pastebin.com/ZhsaTw0c

**Comment by Fefo6644** [comment]
Read this one question: https://github.com/lucko/LuckPerms/wiki/FAQ#when-i-install-luckperms-my-server-shuts-down

**Comment by bacogi** [comment]
Thank you now works, sorry if i disturb
