### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by TUCAOEVER** [lucko/LuckPerms#2656]
### Description

Server got crash sometimes

### Reproduction steps

I didn't know when it happens,it does always happan randomly

### Expected behaviour

Should not crash the whole server

### Environment details

System Info: Java 1.8 (Java HotSpot(TM) 64-Bit Server VM 25.261-b12) Host: Windows Server 2019 10.0 (amd64)
* Server type/version: `Paper` running version `1.15.2` build `git-Paper-387`
* LuckPerms version: `LuckPerms version 5.1.107`

Crash Log:
https://bytebin.lucko.me/7TQjRqgzVK
Config:
https://bytebin.lucko.me/wzuvCgjwjA

**Comment by benwoo1110** [comment]
Please use a paste service to send your logs and config. https://bytebin.lucko.me/

**Comment by lucko** [comment]
Crash isn't LuckPerms related.

**Comment by TUCAOEVER** [comment]
But all errors related luckperms. So what's wrong?

**Comment by TUCAOEVER** [comment]
> Crash isn't LuckPerms related.

But all errors related luckperms. So what's wrong?
