### ISSUE TITLE
placeholder of %luckperms_group_expiry_time_<groupname>% is not rihgt

### ISSUE THREAD

**Issue by patatoplugin** [lucko/LuckPerms#2657]
### Description

When I use %luckperms_group_expiry_time_<groupname>%，the time not show right
I set my player in group vip 30days but it show 59h

### Reproduction steps

1. Open the config.yml file and set example to true.
2. Restart the server
3. Run /lp user example permission set x from the console

### Environment details

* Server type/version: `ExampleSpigot` running version `1.12.2` build `???`
* LuckPerms version: `v???`

**Comment by Fefo6644** [comment]
1. Follow the issue template.
2. Update PAPI to a dev build.

**Comment by benwoo1110** [comment]
does it show correctly in `/lp user USER info`? if so, then report the bug to placeholderAPI, if I am not wrong, they have fixed this bug in the latest PAPI build.

**Comment by Timmy109** [comment]
Why dont you try removing the extra "_" from the placeholder before the %? 
%luckperms_group_expiry_time**_**%
