### ISSUE TITLE
Server crashing 20 minutes or so after startup—possible LuckPerms confliction.

### ISSUE THREAD

**Issue by Creati0n** [lucko/LuckPerms#266]
Hey guys, the issue is the title.  Here's a pastebin with the crash log!

https://pastebin.com/d8cEtGK1

**Comment by Creati0n** [comment]
Here's a hastebin, I was told it was better!

https://hastebin.com/ugoqonuwuy.pl

**Comment by lucko** [comment]
I don't think this is LuckPerms related. 

Does it happen frequently?

**Comment by xion87** [comment]
I think he is running a incorect/old version of forge/spongeforge and pixelmon version
