### ISSUE TITLE
MySQL Userdata Error

### ISSUE THREAD

**Issue by Skeptic12** [lucko/LuckPerms#2661]
Description of issue: I try to add someone to a newly created rank, it says "There was an error saving X's Userdata." and outputs the error in the log.

Reproduction Steps: Make a new rank with Luckperms MySQL and try to add a default member to it.

Console Log: https://bytebin.lucko.me/COh899pVag

Server Version: Paper 214 1.16.3

Misc: It seems the server isn't committing the data to the MySQL Database as ranks also seem to disappear for some after leaving the game.

**Comment by lucko** [comment]
Did you previously create a LuckPerms database using an old version of the plugin?

If so, you may need to reset the tables and restart to regenerate them.
