### ISSUE TITLE
Ranks Tree (read please)

### ISSUE THREAD

**Issue by Georgak** [lucko/LuckPerms#2662]
I would suggest that you add a Rank Tree so people can recognize whats the higher rank and what rank has the most permissions.
Yes, it's "weight" but in a tree-like view
This will help new users to understand parenting and the theory behind ranks!
Hope you add it
Geo

**Comment by lucko** [comment]
Hey, thanks for the suggestion.

I think this is likely to be quite tricky to implement within the confines of the MC chat - however it's something we may consider for the web editor.
