### ISSUE TITLE
Loading errors

### ISSUE THREAD

**Issue by x9nico** [lucko/LuckPerms#2664]
https://pastebin.com/4v3G1LFT

It gives theses errors when I'm loading on Bungee (Waterfall).
Any solutions ?

**Comment by x9nico** [comment]
I have the same errors on my Paper server (1.16.3)

**Comment by benwoo1110** [comment]
the error is `Caused by: me.lucko.luckperms.lib.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Public Key Retrieval is not allowed`

See https://github.com/lucko/LuckPerms/wiki/Storage-system-errors#mysql-public-key-retrieval-is-not-allowed for a fix

**Comment by x9nico** [comment]
Got these errors now:
https://pastebin.com/bZGy1vtr
