### ISSUE TITLE
PowerRanks migration

### ISSUE THREAD

**Issue by Helios19932** [lucko/LuckPerms#2665]
### Description
Migration for PowerRanks.

### Proposed behaviour
Migration for PowerRanks.

**Comment by lucko** [comment]
Hi - sorry, this is unlikely to be worked on.

PowerRanks isn't a particularly popular plugin at the moment, so the time required to implement it likely wouldn't be worth it.

I would accept a good PR implementing this functionality, but unfortunately it's not something I'm going to be able to work on myself.
