### ISSUE TITLE
Velocity | No Command Output

### ISSUE THREAD

**Issue by Diamondman121314** [lucko/LuckPerms#2669]
EDIT: This issue MAY be invalid with the new build of Velocity, `265`, with it including Adventure 4.0.0 release.

### Description
After the commit which changes LuckPerms from using Text to Adventure, command output doesn't seem to work on Velocity.

### Reproduction steps
1. Start proxy.
2. Run ANY LuckPerms command.

### Expected behaviour
I expect to run a command and see what the output is.

### Environment details
* Server type/version: `Velocity` running version `1.1.0` build `264`
* LuckPerms version: `v5.2.2`

### Any other relevant details
Nothing out of the ordinary with logs or anything. No errors or anything.

**Comment by lucko** [comment]
b6e5b0bd47ceb248447d41ea9030b3ae3cd6ca64
