### ISSUE TITLE
LuckPerms does not work on 1.7.10

### ISSUE THREAD

**Issue by Portanna** [lucko/LuckPerms#267]
**Stacktrace:** https://pastebin.com/YAhMTN2y

**Problem:** LuckPerms fails to load on 1.7.10 PaperSpigot and Spigot

**Server Java version:** 
> java version "1.8.0_60"
> Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
> Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

GroupManager and PermissionsEx both load correctly but LuckPerms does not.

**Comment by lucko** [comment]
Use the legacy version.

https://ci.lucko.me/job/LuckPerms/

**Comment by Portanna** [comment]
Thanks :)
