### ISSUE TITLE
java.lang.ExceptionInInitializerError: null on velocity

### ISSUE THREAD

**Issue by ninjawulf98** [lucko/LuckPerms#2676]
### Description

`java.lang.ExceptionInInitializerError: null` when luckperms inititalizes on velocity 1.0.10

### Reproduction steps

1. Download the latest stable velocity
2. Download any luckperms version from 5.2.1 and above
3. The errors shows in the console

### Expected behaviour

It should not show this error

### Environment details

* Server type/version: Velocity 1.0.10 - stable
* LuckPerms version: occurs on 5.2.1 - 5.2.8

Server log: https://gist.github.com/ninjawulf98/4f5f0bcc2b981f453ee2eac11ddaf05d

**Comment by lucko** [comment]
Thanks for reporting this :)
