### ISSUE TITLE
LuckPerms bungee issue

### ISSUE THREAD

**Issue by JHarris12345** [lucko/LuckPerms#2679]
I believe luck perms on bungee enables servers to suffer crashes from bot attacks. I THINK that the plugin loads data for a player (or issues code for a player) before their connection is successful and they have actually joined. Right now I believe it issues code for a player if they have an attempted connection despite that connection not turning into a join. This means large scale bot attacks could crash the bungee.

**Comment by benwoo1110** [comment]
I dont think its in the scope of LuckPerms to prevent bot attacks. Also do provide with more detailed info then "I think" or "I believe". Can you actually justify your claim?

**Comment by JHarris12345** [comment]
You misunderstood. You cant make a plugin version for bungee if you dont intend to have it so you it works through bot attacks. The point I was making was not to prevent bot attacks, its simply to issue code after a successful join so a bot attack doesnt crash

**Comment by lucko** [comment]
LuckPerms loads data on the `LoginEvent` - this is only called after a connection has been authenticated, assuming the server is in online mode. Most botted users will not get past the auth state.

If they do, then you'll need an extra plugin to try to detect these accounts and cancel their login before it is handled by LuckPerms.
