### ISSUE TITLE
Can't set different primary group.

### ISSUE THREAD

**Issue by KatieDeForest** [lucko/LuckPerms#2681]
Hi.
I can't seem to change my "agent" to "president" behind my name in chat, not even the switchprimary group command works.
Anyone who can help?

![Screenshot_2](https://user-images.githubusercontent.com/32366847/96809202-b303ad80-141a-11eb-991c-fd35d6853ffe.png)
![Screenshot_1](https://user-images.githubusercontent.com/32366847/96809205-b4cd7100-141a-11eb-8420-5a8a35b40602.png)

**Comment by underscore11code** [comment]
Most likely cause is incorrectly configured [weight](https://luckperms.net/wiki/Weight).

**Comment by KatieDeForest** [comment]
Oh thank you so much! It worked, I didn't know it was even a thing, until you sent me that link.
