### ISSUE TITLE
LuckPerms plugin unresponsive but still appears in /pl

### ISSUE THREAD

**Issue by TylerM2022** [lucko/LuckPerms#2684]
Hey, today I started updating my 1.14.4 server to 1.16.3, after downloaded the latest versions of all my old plugins, I started by setting up LuckPerms. I ran the usual command, `/lp user playername permission add *`, but received absolutely no output from console. Strange. I try running `/lp editor` and still with no output. I don't know what on earth is happening as it has been a while since I last worked on plugins, please help!

### Reproduction steps

1. Download LP
2. Restart the server
3. Run /lp user example permission set x from the console
4. Try running lp commands

### Expected behaviour

       I expected LP to send me a link to the webeditor, but with no response.

### Environment details

* Server type/version: `Craftbukkit` running version `1.16.3` build `Not sure but probably the latest`
* LuckPerms version: `v5.2.15`

**Comment by Fefo6644** [comment]
Hmm I'll test ASAIC, but mind putting your server logs (located in `logs/latest.log`) in [gist](https://gist.github.com/) and share the link? Not necessarily the entire log but at the very least all the start up.

**Comment by TylerM2022** [comment]
https://gist.github.com/TylerM2022/f186054878dbe716a243f8a72837bcd8

**Comment by benwoo1110** [comment]
Luckperms cant download the dependencies it needs. You have something blocking it like a firewall or anti-virus software. Or if you are using a server host it may be their network config issue.

**Comment by TylerM2022** [comment]
> Luckperms cant download the dependencies it needs. You have something blocking it like a firewall or anti-virus software. Or if you are using a server host it may be their network config issue.

Thanks for the tip, I'll open a ticket to my host.
