### ISSUE TITLE
Dysfunctional Placeholders

### ISSUE THREAD

**Issue by KasearMC** [lucko/LuckPerms#2686]
LuckPerms: 5.2.15
Minecraft: 1.16.3
Paper: 245

Placeholders in question:
%luckperms_first_group_on_tracks_<tracks>%
%luckperms_last_group_on_tracks_<tracks>%

Problem:
when i use these placeholders to display the group that the player has on the premium ranks track, it simply either displays the first or last group that is on the track, regardless of which group the player has or if they're even on the track.

Example:
if the player is in the default group with no other groups, %luckperms_last_group_on_tracks_premium% shows the display name of the last group added to the premium track.

**Comment by Timmy109** [comment]
If I'm reading this correctly, the placeholder is displaying exactly what it's meant to and what you're describing is what the placeholder says it does.

**Comment by KasearMC** [comment]
> If I'm reading this correctly, the placeholder is displaying exactly what it's meant to and what you're describing is what the placeholder says it does.
> 
> %luckperms_**first_group**_on_tracks_%
> %luckperms_**last_group**_on_tracks_%

if what you're saying is correct then the wording is misleading.
[https://i.postimg.cc/MTKHjTTG/1.jpg](url)

> %luckperms_first_group_on_tracks_<tracks>%
> Description: Returns the name of the first group **a player has** on the given tracks. Tracks represents a comma separated list of tracks. Each group in the tracks is considered in order.
> Example: %luckperms_first_group_on_tracks_staff,donor%

this implies it is returning the group that the player has.
currently i use:
[https://i.postimg.cc/SsTsLh2f/2.jpg](url)

> %luckperms_highest_group_by_weight%
Description: Returns the name of the players highest prioity group.

this properly displays the highest weight group that the player has, rather than simply displaying the group that has the highest weight in the database.
the wording is similar to the placeholders that i called dysfunctional; to display the group that a player has.

**Comment by KasearMC** [comment]
i would like to get confirmation whether those placeholders are supposed to display the first/last group on tracks in the database, or if they're supposed to display the first/last group on tracks that the player in question has.

can someone please confirm so that i can continue my work?
if it's the former then i will simply resort to using placeholders for prefix elements.

**Comment by lucko** [comment]
> they're supposed to display the first/last group on tracks that the player in question has.

This is correct.

However, it considers all groups the player **has** and the groups which they **have indirectly** (i.e. inherit)

Perhaps it would be more useful to only consider the groups which they have directly - I'm happy to change it if that would be better. Placeholder related requests go here: https://github.com/LuckPerms/LuckPermsPlaceholders :)
