### ISSUE TITLE
Not all possible permissions shown in the tree under Console user (sponge problem)

### ISSUE THREAD

**Issue by cyb3rm4n** [lucko/LuckPerms#2688]
### Description

I have a bunch of plugins with their permissions, but LuckPerms doesn't seeing its permissions list in tree before i will not execute its command.
Examples:
https://luckperms.net/treeview/0B18M470sc
https://luckperms.net/treeview/ZkSmDJmOEm

### Reproduction steps

1. Install all the needed plugins
2. Start the server
3. Run /lp tree and use the link provided by LP
4. Run some not seeing in tree plugin commands
5. Run /lp[ tree again and use provided link.

### Expected behaviour

On first /lp tree command i wantiong to see all the possible permissions form all intslled polugins that support the permssions.

### Environment details

* Server type/version: `Forge` running version `1.12.2` builds `2838` and `2854` with `SpongeForge` build `1.12.2-2838-7.3.0`
* LuckPerms version: `v5.2.15`

### Any other relevant details

none

**Comment by benwoo1110** [comment]
that is not the function of `/lp tree`, lp tree can only: `Generates a tree view of permissions registered to the server. The tree is built using data exposed to the server by plugins, and expanded over time as plugins check for permissions.` If the plugin has not registered the permission node or Lp has not checked on the given node, it impossible for lp tree to show it. `/lp tree` is only really useful when your server is active for a while and **most** relevant perms are checked, even so, it cant will probably never be able to show the absolute all permissions available on your server as permission nodes are definite by **each plugin** not LuckPerms.

If you want to see relevant permission node for a given command:
1. read the plugin's documentation
2. use verbose: https://github.com/lucko/LuckPerms/wiki/Command-Usage:-General#lp-verbose-onrecordoffupload-filter

see: https://github.com/lucko/LuckPerms/wiki/Command-Usage:-General#lp-tree-scope-player
