### ISSUE TITLE
[15:10:16 ERROR]: Could not pass event PlayerJoinEvent to LuckPerms v5.2.16

### ISSUE THREAD

**Issue by explodersname** [lucko/LuckPerms#2689]
### Description

LuckPerms isn't working, when I join and execute any luckperm command I dont recieve an output. Not even a command not found which is telling me that luckperms is doing at least something. 

### Reproduction steps

1. Install the plugin
2. Restart the server
3. Join the server
4. Enter a command

### Expected behaviour

I expected luckperms to give me an output from the command.

### Environment details

Server Software: Spigot 1.8.8
LuckPerms Version: v5.2.16

https://gist.github.com/explodersname/7095b89d19192c682ab6c6abf5df7de8

### Any other relevant details

I am running LuckyPerms with ViaVersion which may have something to do with it as you can see Viaversion popping up in the log.

**Comment by lucko** [comment]
Make sure you are using the latest version of ViaVersion. :)
