### ISSUE TITLE
Make the group rename command also bulk update the group inheritors.

### ISSUE THREAD

**Issue by Fefo6644** [lucko/LuckPerms#2692]
### Description

More than often, people (like me \:D) expect the group rename command to also update the group inheritors parent groups list.

### Proposed behaviour

Maybe letting the group rename command run a bulk update query should be default behavior, and in the cases where we don't want to update the inheritors parent groups, a flag or a boolean could be provided.

Open for discussion \:)

**Comment by lucko** [comment]
I think that's reasonable.

**Comment by Fefo6644** [comment]
Was looking through the current issues listed in #1836 and this suggestion is already part of it. Apparently #1772 is already a thing!
