### ISSUE TITLE
When i try to do something myslef it says somthing

### ISSUE THREAD

**Issue by billybobjoe123412345678** [lucko/LuckPerms#2694]
it says luckperms Please Note That Server Operator status has no effect on sponge permission check when a permission plugin is installed please edit user data directly. PLEAse help

**Comment by Fefo6644** [comment]
Well, like the note says:
> Server Operator status has no effect on sponge

i.e. there is no `/op` in sponge servers. And as stated in the wiki:
> This is an intentional behaviour of SpongeForge. As soon as a permission plugin is installed, it will disable the OP system.
To fix this, give the groups and users the required permissions for the plugins. If you want OP-like permissions, you can use the wildcard `*` but this is considered [bad practice](https://nucleuspowered.org/docs/nowildcard.html).
