### ISSUE TITLE
lower weight group overwrites primary group

### ISSUE THREAD

**Issue by Marrarus** [lucko/LuckPerms#2705]
![javaw_Yuu7v9Yz1t](https://user-images.githubusercontent.com/18899815/98448547-09683000-212d-11eb-836a-b9c30cf1844c.png)
![javaw_HJNmQ5rxB1](https://user-images.githubusercontent.com/18899815/98448550-0bca8a00-212d-11eb-97fc-394b2b7a77f6.png)
when someone is in group admin and in group member, he doesnt get admin permissions.  the group member overwrites all admin permisisons. 
as the pictures show member has a weight of 10 and admin of 100, admin is also primary group. (removing the player from member enables the admin permissions again)

**Comment by lucko** [comment]
That's not the case - any permissions in admin will override the same nodes also set in other groups.

However, wildcards will not override non-wildcard permissions in lower groups - that's just the nature of the way the system works.

I suggest using the verbose command to see where things are going wrong, then adjust your permissions setup accordingly.
