### ISSUE TITLE
LuckPerms disable other plugin and he download only 1 folder

### ISSUE THREAD

**Issue by HotWaves** [lucko/LuckPerms#2707]
Help me pls
![Screenshot_13](https://user-images.githubusercontent.com/74121113/98454076-6dd7bf00-212e-11eb-8107-501b0b7aa4fa.png)
![Screenshot_12](https://user-images.githubusercontent.com/74121113/98454077-6fa18280-212e-11eb-8964-086193226499.png)

**Comment by HotWaves** [comment]
It disable the plugin ChestCommands.

**Comment by benwoo1110** [comment]
Please follow the issue template. Thanks!
