### ISSUE TITLE
How to prevent from modifying players with certain group.

### ISSUE THREAD

**Issue by soswi** [lucko/LuckPerms#2709]
I'm trying to set Moderator group, so it can't change group of player with Admin group, but it's not working.
To do that I'm using Argument based command permissions and Moderator permission looks like that.

luckperms.user.parent.set
luckperms.user.parent.set.modify.others
luckperms.user.parent.set.builder

And now - What should I add to make it work as I want it to ?

**Comment by soswi** [comment]
How is it happens that nobody ever aswers on my questions. ?

**Comment by Turbotailz** [comment]
Using verbose mode is really the only way to do this properly

**Comment by benwoo1110** [comment]
https://github.com/lucko/LuckPerms/wiki/Argument-based-command-permissions

1. did you enabled arguement-based in luckperms config.yml
2. use verbose to see the perms https://github.com/lucko/LuckPerms/wiki/Verbose

**Comment by soswi** [comment]
1. Yes I did
2. I do

**Comment by benwoo1110** [comment]
please show your verbose output when doing the relevant commands.

**Comment by Turbotailz** [comment]
Pay particularly close attention to this part here: https://github.com/lucko/LuckPerms/wiki/Argument-based-command-permissions#checks-when-a-player-makes-changes-in-a-specific-context

**Comment by soswi** [comment]
I've read that

**Comment by soswi** [comment]
and all permission from verbose are there exept for 
luckperms.user.parent.set.usecontext.global
and that's all

**Comment by benwoo1110** [comment]
do send a screenshot of the verbose output.

**Comment by soswi** [comment]
![Zrzut ekranu 2020-11-10 074246](https://user-images.githubusercontent.com/48840793/98637198-6a0f8c80-2328-11eb-9e06-a155417f0d35.png)

**Comment by benwoo1110** [comment]
I dont see any issue, if you don't want to be able to add someone to admin, then set `luckperms.user.parent.set.admin` to false.

**Comment by soswi** [comment]
but just prevent form giving this group

**Comment by soswi** [comment]
![image](https://user-images.githubusercontent.com/48840793/98641163-a09ad680-232b-11eb-8086-3428be4bbfb9.png)
![image](https://user-images.githubusercontent.com/48840793/98641214-b0b2b600-232b-11eb-96bd-15bbb19669d8.png)

**Comment by soswi** [comment]
and so u know how I've don it ^
![image](https://user-images.githubusercontent.com/48840793/98641376-f1123400-232b-11eb-9f63-2e25901f4e92.png)

**Comment by soswi** [comment]
I can't believe there is no way to do that...

**Comment by Turbotailz** [comment]
I mean that's literally the purpose of this feature. Your verbose logs show that *everything* is `true` so maybe you've set a wildcard permission somewhere or maybe you're even opped (always deop yourself when doing any permission debugging).

**Comment by benwoo1110** [comment]
@Turbotailz I think what he wants like if i am a mod, I caant touch the permissions for users in admin group. For me id suggest using tracks instead of parent  set command.

**Comment by soswi** [comment]
Okey so I'll use trakcs then
@benwoo1110  and that's exactly what I meat..
Thanks guys for help
