### ISSUE TITLE
Add a command to see the time

### ISSUE THREAD

**Issue by DjeyMute** [lucko/LuckPerms#2710]
Hi guy,

I would like to offer you a new command that would help server a lot.
This command would be used to see how much time a player has left for an add permission with this command: lp user {player} permission settemp ...

This command would simply allow to know how much time he has left before losing his advantages.

Thanks in advance for reading.

**Comment by Fefo6644** [comment]
You can see the remaining time on temporary nodes with `/lp (group|user) <group|user> (parent|permission|meta) info` \:)

**Comment by DjeyMute** [comment]
Like that ? 

lp user DjeyMute permission jobs.boost.all.money.0.5 info

**Comment by Fefo6644** [comment]
No, the command would be `/lp user DjeyMute permission info`, it prints all permissions the user has directly. If you want to *display* the remaining time, you should use the available placeholders instead (see https://luckperms.net/wiki/Placeholders).

**Comment by DjeyMute** [comment]
And wouldn't it be possible to make a prettier order?
Because I would like my players to use it to see how much time they have left but the visual is not very nice.

Because we can change the command but we cannot recover the time that a player has left for the permission :/
