### ISSUE TITLE
Luck perms default installation doesn't work. A database error occurred whilst loading permissions data.

### ISSUE THREAD

**Issue by tdragon00** [lucko/LuckPerms#2711]
I installed luckperms to my server hosted by akliz and made sure the config file was h2. So I didn't change anything.
When i try to join the server i get A database error occurred whilst loading permissions data.
https://bytebin.lucko.me/fvbyKyL0bn

Server type: spongeforge-1.12.2-2838-7.3.0.jar
Version: LuckPerms-Sponge-5.2.26.jar

**Comment by Turbotailz** [comment]
Could you please provide a full start up log

**Comment by tdragon00** [comment]
I updated the bytebin link. It should contain the full startup log

**Comment by Turbotailz** [comment]
What version of LP/Sponge are you using (probably should have followed the issue template).

**Comment by lucko** [comment]
This has definitely been fixed in the latest version - I suspect you may in fact not be using the version you think you are.

https://luckperms.net/download
