### ISSUE TITLE
Add another condition.

### ISSUE THREAD

**Issue by soswi** [lucko/LuckPerms#2712]
I'm missing a condition that checks if player has a specified group.

For example:
I want to promote a player using a track, but I want that to happen only **if** player **has** the first **group** in this track.
**track**: Builder->Stuff->Owner
**player**: has group Default
**me**: /lp user player promote track <-- and now this won't be executed, because the player has not the group builder. 

*I know that there is a batter way fo doing that but it's just a example*

The condition perm would look like this: 

   _cperms.has_group={group_name}.luckperms.user.promote.{track_name}_

And that would work with other permissions too: 

   _cperms.has_group={group_name}.luckperms.user.parent.set.{group_name}_
   _cperms.!has_group={group_name}.luckperms.user.parent.set.{group_name}_

or maybe even:

     _cperms.has_group={group_name}.essentials.home_
I know that ^this one^ doesn't really make any sense (cause u can just add 'essentials.home' to the group) but u get the point...

I don't know if that makes any sense to you.

**Comment by lucko** [comment]
As noted on the GitHub page, ConditionalPerms is [no longer supported](https://github.com/lucko/ConditionalPerms).

What you want to do is supported already anyway:

```
/lp user lucko promote staff --dont-add-to-first
```
