### ISSUE TITLE
java.util.concurrent.CompletionException: java.sql.SQLException: Malformed communication packet

### ISSUE THREAD

**Issue by chrlew082** [lucko/LuckPerms#2717]
I start my server and get this issue:

java.util.concurrent.CompletionException: java.sql.SQLException: Malformed communication packet

Here are my logs: https://hastebin.com/unicubasah.sql

**Comment by Fefo6644** [comment]
Set your `storage-method: mariadb` in LP config (see #2701), and also update LuckPerms as well :) https://luckperms.net/download

**Comment by chrlew082** [comment]
Im not using mariadb though

**Comment by Fefo6644** [comment]
See #2701, your hosting provider may say it's MySQL but are using MariaDB instead (which isn't totally false, MariaDB is based on MySQL, but a recent MariaDB causes this issue, again, see #2701).

**Comment by chrlew082** [comment]
Ok, ill try.

**Comment by chrlew082** [comment]
Resolved.
