### ISSUE TITLE
Erorr while joining during server startup for 1.8.8 paper

### ISSUE THREAD

**Issue by crimilo** [lucko/LuckPerms#2719]
### Description

While server is starting up and you try to join, it doesn't let you join the server and it gives this error in console: https://hasteb.in/gusuwobu.swift

### Reproduction steps

1. Open the config.yml file and set example to true.
2. Restart the server
3. Run /lp user example permission set x from the console

### Expected behaviour

N
### Environment details

* Server type/version: `ExampleSpigot` running version `1.12.2` build `???`
* LuckPerms version: `v???`
Server version: 1.8.8 paper
LP version: 5.2.32

https://hasteb.in/gusuwobu.swift

**Comment by lucko** [comment]
Your pastebin link doesn't work, and you haven't followed the template.
