### ISSUE TITLE
Prefixes Aren't working

### ISSUE THREAD

**Issue by Infinite2006** [lucko/LuckPerms#2722]
Yes, I have essentials chat and essntials and prefixes arent working.

**Comment by benwoo1110** [comment]
1. follow issue template.
2. show screenshot of `/lp user USER info`

**Comment by ApertureDevelopment** [comment]
Du you have Vault installed?

**Comment by Infinite2006** [comment]
> Du you have Vault installed?

No

**Comment by benwoo1110** [comment]
You need that.

**Comment by Infinite2006** [comment]
> You need that.
Ok

**Comment by Infinite2006** [comment]
> > You need that.
> > Ok

It only worked on the tab not in the chat.

**Comment by powercasgamer** [comment]
Did you install [Vault](https://www.spigotmc.org/resources/34315/)? If you don't have Vault, install it. Can you also send a screenshot of `/lp user <user> info`
