### ISSUE TITLE
Luck Perms blocking console from sending anything (Commands and Messages)

### ISSUE THREAD

**Issue by Shid0** [lucko/LuckPerms#2723]
### Description

So I have 2 servers a test server and a main server (Currently switching Permissions plugins and working on the test server)
After working for a bit I realized the console wouldn't send any commands and I thought it was just me but after testing I found out it only happened on the server with luck perms (I checked the config and saw the thing about OP but not about sending messages)

### Reproduction steps

I don't know how to reproduce this bug and I thought this would come up

1. Open the config.yml file and set example to true.
2. Restart the server
3. Run /lp user example permission set x from the console
^^ I can't do this because I don't have op on the server and I can't op through console

### Expected behaviour

I should be able to run commands through console

### Environment details

* Server type/version: `Spigot` running version `1.12.2` build `???` (I don't know the build but this is the link https://getbukkit.org/get/Fpt2yFn7HRTrot5uE1b8NFWtpQlYITgK)
* LuckPerms version: `v5.2.32`

**Comment by BrainStone** [comment]
LP should not have an effect on the console (as no plugin should be able to).  
Can you try to reproduce this with only LP and Spigot?

**Comment by Shid0** [comment]
I'm so sorry it was a bug on my end
