### ISSUE TITLE
prefixes don't work

### ISSUE THREAD

**Issue by blobglib10** [lucko/LuckPerms#2724]
create a link of lp editor and try to create prefixes for my groups and they do not work for me I was checking if I wrote it correctly and it was correct then I was changing the color codes also I had to reinstall the plugin and it still did not work for me

**Comment by BrainStone** [comment]
### LuckPerms does not perform any chat/tablist formatting of its own!

LuckPerms only acts as the source for prefixes / suffixes, it doesn't actually apply them. You need an appropriately configured chat/tablist formatting plugin for them to be displayed. If the values appear correctly when you run `/lp user <user> info`, LuckPerms is doing its job!

#### FAQ answer: Prefix isn't showing?
https://luckperms.net/wiki/FAQ#why-are-prefixessuffixes-not-working

#### List of chat/tablist formatting plugins that work with LuckPerms
https://luckperms.net/wiki/Prefixes,-Suffixes-&-Meta#displaying-prefixes-and-suffixes
