### ISSUE TITLE
Essential Warp sign/command cannot be use without being operator (spigot server)

### ISSUE THREAD

**Issue by Thomas-Lecuppre** [lucko/LuckPerms#2726]
I recently try to use LuckPerms for my spigot server. I have created all my group and set all the permissions but I have an issue with the warp sign/command from essential.

---------------------------------------------------------------------------------------------------------------------------------------------

After setting all my groups and there's prefix, I have restarting my server.
Then I create a warp with this "/setwarp Ressource"
Then I use "/lp editor" to add permissions to this new warp for the group I named "Aventurier"
In the "Aventurier" panel I add : 
     - essentials.warp
     - essentials.warps.Ressource
Then save and paste the link in minecraft.
Then I make a little "/reload"
Then I create a sign like this : 
______________________
           [warp]
        Ressource
        _nothing
        nothing_
______________________
I tell a player, set it group to "Aventurier" and ask it to click on sign
And finally it don't teleport and say nothing (but I think the feedback command is not an issue from LP)

---------------------------------------------------------------------------------------------------------------------------------------------

Can someone help me to understand why it doesn't work ?
I'm an operator and it work for me..

---------------------------------------------------------------------------------------------------------------------------------------------

There is a list of plugins that I use on my server : 
- DeathMessagesPrime
- EssentialsX-2.18.1.0
- EssentialsXChat-2.18.1.0
- EssentialsXProtect-2.18.1.0
- EssentialsXSpawn-2.18.1.0
- LuckPerms-Bukkit-5.2.35
- multiworld
- ProtocolLib
- PsudoCommands
- SuperVanish-6.2.0
- Vault
- worldedit-bukkit-7.2.0
- worldguard-bukkit-7.0.4

**Comment by Turbotailz** [comment]
1. You need to stop debugging permissions with op, de-op yourself to make things easier for you
2. You'll probably find [Verbose mode](https://luckperms.net/wiki/Verbose) is useful for these things - it will tell you in real time what permissions are lacking for a particular action.

**Comment by Thomas-Lecuppre** [comment]
Your are the best. I see I miss a permission : essentials.signs.warp

Using "/lp verbose on" and see the console all the permissions is very helpfull !
