### ISSUE TITLE
CustomNPC mod - Npc cant execute command 

### ISSUE THREAD

**Issue by Flashback083** [lucko/LuckPerms#273]
Hello, i have an issue with LuckPerm and the mod CustomNpc the npc cannot execute command like /tppos or /warp cause of LuckPerm - Sponge version :/
Here the screen of /lp verbose :
https://images.discordapp.net/.eJwFwUEOhCAMAMC_cLe0UED8zIYgQRMVAvW02b_vzFe941KbOkT63LTez5nb2GFKG6kWqK3Vq6R-Tsjt1kkk5eMuj0xtmLwPhjmawKuNyNoSMjnvrGMOa4gBtUEKC7oF_Yc8IAJZ6E9Vvz-LtiOq.F555lLny1ou1irIY8QfcBaHfqWU
Thanks !

**Comment by lucko** [comment]
You need to grant the NPC access to that command.

Refer to the documentation for CustomNpc on how to do that.
