### ISSUE TITLE
Extra placeholder suggestion

### ISSUE THREAD

**Issue by Denis99s** [lucko/LuckPerms#2731]
### Description
Hi is it possible to introduce a papi that shows all the suffixes and / or prefixes of a user regardless of their priority? for example% luckperms_prefixs% and% luckperms_suffixs%? thanks

### Proposed behaviour
I think that adding these two popes does not involve any change in the config level, but only an aspect of utility for the server administrators

**Comment by DevJoey** [comment]
> 
> ### Description
> 
> Hi is it possible to introduce a papi that shows all the suffixes and / or prefixes of a user regardless of their priority? for example% luckperms_prefixs% and% luckperms_suffixs%? thanks
> ### Proposed behaviour
> 
> I think that adding these two popes does not involve any change in the config level, but only an aspect of utility for the server administrators

Download LuckPerms Placeholder extension

**Comment by Denis99s** [comment]
Yes but it does not include the placeholders that show all suffixes / prefixes of a user, the existing placeholder is the following: "luckperms_suffix" or "luckperms_prefix" which show the prefix or suffix with the highest priority, I am requesting the placeholder "luckperms_suffix" and "luckperms_prefixs" to show all the prefixes and / or suffixes of a user without considering the priority.

**Comment by lucko** [comment]
Could you give an example use case? I can't see when this would be useful.

**Comment by Denis99s** [comment]
Yes, of course, an example would be the following: if I wanted to add a kind of notes on a user through suffixes, making them all visible to the staff through deluxechat, or if I wanted to assign 4 or 5 prefixes to a user and make them visible in chat all 4 or 5 without having to use tracks. Thanks!

**Comment by lucko** [comment]
Adding notes would be better achieved using meta (`/lp user Luck meta set note "some note"`) but bear in mind there are restrictions on the length if you are using SQL based storage. A purpose built notes plugin would be a better idea!

I've added a placeholder for you that will return all values for a given key: `meta_all`
https://github.com/LuckPerms/LuckPermsPlaceholders/commit/8558c6d7c368d811e20a84a6dcf6bc4dfae1e802

Making more than one prefix visible can be best achieved using the meta stacking functionality.
