### ISSUE TITLE
`verbose command` command does not report LuckPerms' own permission checks

### ISSUE THREAD

**Issue by Fefo6644** [lucko/LuckPerms#2734]
### Description

Running a LuckPerms command through the `verbose command` command does not report any permission checks for LP.

### Reproduction steps

1. Run `/lp verbose command <whomst'd've> lp info`
2. Observe

### Expected behaviour

It should appear on my screen/in console report checks for `luckperms.` permissions.

### Environment details

* Server type/version: `Paper` running version `1.16.4` build `288`
* LuckPerms version: `v5.2.40`

https://gist.github.com/Fefo6644/05b688865f856c6c7dc4e99e6c256eda

### Any other relevant details

Nothing else, no

**Comment by lucko** [comment]
This is a side effect of the fact that `/lp verbose command` does not support commands which execute async (therefore including LP itself).

There's no easy way to fix this unfortunately.

**Comment by Turbotailz** [comment]
If it can't be fixed, then a message warning the user that it won't work is probably a good idea.
