### ISSUE TITLE
Ranks Not updating.

### ISSUE THREAD

**Issue by Kqmu** [lucko/LuckPerms#2735]
Hello, Well I've been having an issue with Luck perms on our server, and when I use /lp user <username> parent add <rank> it adds correctly, then I run the command /lp user <username> parent switchprimarygroup <rank> and it switches successfully, but on Tablist, and in chat it still says their old rank, but when they travel through the nether, it updates to the new rank, but when they travel back it changes back to the default rank, and I don't know if this is a "Bug" or server Issue, or I'm doing something wrong, but I would like maybe a little guidance in this. we are running Paper 1.16.3, LuckPerms Version: 5.2.35, as well with all the plugins below.
![image](https://user-images.githubusercontent.com/70139586/99767805-9fa73900-2ad1-11eb-8390-86e7a8cd7873.png)
so if I could get a little assistance back. That would be much appreciated!
Sincerely _Kamu_, _**Lead Developer, MC: Blood And Steel**_

**Comment by benwoo1110** [comment]
Primary groups should be defined by the highest weight group you inherit, unless you changed the luckperms config. https://luckperms.net/wiki/Weight
