### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by ArcLand-Project** [lucko/LuckPerms#2736]
I feel that multi language services can be added. Isn't it more convenient to automatically download updates from the cloud?

**Comment by lucko** [comment]
That's what happens already?

**Comment by ArcLand-Project** [comment]
err... I think it's best to add a language folder to the luckperms folder to automatically update multiple languages. I'm just a suggestion.

**Comment by benwoo1110** [comment]
https://github.com/lucko/LuckPerms/commit/129a10aa60a8ac10c5f2a4f50cc64f448c86323a

**Comment by ArcLand-Project** [comment]
> [129a10a](https://github.com/lucko/LuckPerms/commit/129a10aa60a8ac10c5f2a4f50cc64f448c86323a)

thanks!

**Comment by ArcLand-Project** [comment]
> 那已经发生了什么？

Sorry to disturb you.
