### ISSUE TITLE
Cant set prefix to [Owner]

### ISSUE THREAD

**Issue by NurvedL** [lucko/LuckPerms#2738]
Ok so I can set the prefix and it shows but if i try to set it to [Owner] it doesn't change but when I change it to (Owner) it shows that.

![Screenshot 2020-11-21 155842](https://user-images.githubusercontent.com/73502546/99890298-83f77c00-2c12-11eb-8d76-a269156beb89.png)

**Comment by lucko** [comment]
In future, please use Discord to ask questions: https://discord.gg/luckperms

Regarding your issue, try running `/lp user <user> info` or `/lp user <user> meta info` to see/understand which prefix is being selected.
