### ISSUE TITLE
Prefix stacking

### ISSUE THREAD

**Issue by Vese883** [lucko/LuckPerms#2739]
Hey im having trouble understanding the prefix stacking. Ive read the wiki and forums and tried multiple things but I'm still having no luck.
I'm trying to have my chat show the following: {X} [Mystic] Vese883: 

I've put all my member ranks on a track named Member 
I've put all my staff ranks on a track named Staff
I've put all my Donor ranks on a track named Donor

Here is my config https://pastebin.com/NMsmnAj4

**Comment by lucko** [comment]
Please use Discord to ask questions: https://discord.gg/luckperms

This tracker is only for bugs/suggestions.
