### ISSUE TITLE
Command to clear the logs 

### ISSUE THREAD

**Issue by DevJoey** [lucko/LuckPerms#2740]
### Description

Hey, it would be so nice if you can add a command to clear the logs. /lp log clear 

### Proposed behaviour

You can run /lp log clear which resets the whole log database. It would also be nice, if the command also resets the tables AUTO_INCREMENT value, so new logs will start at zero

**Comment by BrainStone** [comment]
What is your use case for this?  
Wiping audit logs from within the application always sounds like bad idea.

**Comment by DevJoey** [comment]
Saving memory, the log gets bigger and bigger after the time bro

**Comment by BrainStone** [comment]
Just truncate the table.  
But those few MBs shouldn't matter at all.

**Comment by lucko** [comment]
I agree with Brainstone:

> Wiping audit logs from within the application always sounds like bad idea.

If you want to clear the log, then do it directly from the database. :)
