### ISSUE TITLE
Very Important Suggestion

### ISSUE THREAD

**Issue by MaximMaximS** [lucko/LuckPerms#2741]
There is an issue, that you absolutely don't care about your sub repository ExtraContext. There is outdated README.md which provides not working contexts, so players are reporting issues why do their contexts not work, I even told you on Discord, so please be that kind and check the repository. Thanks

[My Pull request](https://github.com/LuckPerms/ExtraContexts/pull/33)

**Comment by Laarryy** [comment]
Something about open source software: Luck, and everyone else, does not do this professionally - only when time is available. From my observations, Luck finds the time to clear out his repositories once every few weeks.

As it's done for free, waiting like 36 hours and then demanding attention is *not* a good strategy. 

Please, do not do this. This issue does not belong on this repository, and when Luck has the time to go through his repos and address them, he will. No whining on your part will make it go any faster.

Please close this issue, thanks.

**Comment by MaximMaximS** [comment]
I know it is free, but you provide outdated, not working information. I see that the problem is, that the repo is inactive. If there was no time like you say even this repo will be dead, and sorry there are issues older than 1 **year**, so don't tell me there was no time to check this repo. Really, since when a few weeks is more than one year. I just wanted to help people, because there is outdated, not working information, I think this means open source.

**Comment by lucko** [comment]
https://github.com/LuckPerms/ExtraContexts/pull/33#issuecomment-732337981
