### ISSUE TITLE
Server crashes.

### ISSUE THREAD

**Issue by MrMcyeet** [lucko/LuckPerms#2745]
### Description

Server seems to crash randomly.
There is never any error, or console output, only the top part of the github gist's in console.

### Reproduction steps

Not entirely sure what is causing it. but the server is hard crashing.

1. Open the config.yml file and set example to true.
2. Restart the server
3. Run /lp user example permission set x from the console
No error codes. Server does not crash when this is done.

### Expected behaviour

The server to not crash

### Environment details

* Server type/version: `ExampleSpigot` running version `1.12.2` build `???` Tuinity `( https://github.com/Spottedleaf/Tuinity )`git-Tuinity-"576a2ef" (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
* LuckPerms version: `v???` 5.2.41

https://gist.github.com/MrMcyeet/2527efffc6cfaf87cf21bee7be4ce08f
https://gist.github.com/MrMcyeet/468007ce6e3cbd2fd705c75305b6d2f1
https://gist.github.com/MrMcyeet/d5f97731cd08ed73988a2b009ef874d2
https://gist.github.com/MrMcyeet/dab5db7a42e1e0459240930b5583878f

### Any other relevant details

I do have a bungee proxy running, and have luckperms bungee on it. though im not sure if this is relevant.

**Comment by Laarryy** [comment]
Please link to your server's startup log, and ***also fill in the Environment Details and steps to reproduce section - it is asked because it is important in solving your issue.*** 
Preliminarily, it looks like somehow Java itself is crashing, and not the server, which Luckperms itself does not normally do. A startup log as well as the things requested of you in filling out this report would go a long way to understanding what is going on here.

**Comment by MrMcyeet** [comment]
Here is the most recent startup log https://gist.github.com/MrMcyeet/e6ffe1bf29cf2ce6d6fdf86d00ea739d

What all are you asking for when you say environment details?
If its this, then this is here.
```Ubuntu 20.04
openjdk version "1.8.0_275"
OpenJDK Runtime Enviroment (build 1.8.0_275-8u275-b01-0ubuntu1~20.04-b01)
OpenJDK 64-Bit Server VM (build 25.275-b01, mixed mode)```
and for the reproduction steps. I simply do not know.
It seems random. As far as I can tell, there is no simple "Do X to crash server" 

I come here, because in the java crash log gists, it says stuff like 
```
# Problematic frame:
# j  me.lucko.luckperms.common.context.QueryOptionsCache.getQueryOptions()Lnet/luckperms/api/query/QueryOptions;+4
```and I simply dont know where else to look.
I do see the line that says `Current thread (0x00007f201c007800):  JavaThread "Craft Scheduler Thread - 3201 - FeatherBoard" [_thread_in_Java, id=141523, stack(0x00007f1fcef17000,0x00007f1fcf018000)]` and have reached out to the FeatherBoard dev.

Any help, or a point in the right direction is much appreciated.

**Comment by lucko** [comment]
I don't think this is a plugin-caused issue.

Some things to check:
* Make sure your system has enough memory spare (i.e. not allocated to the Java process)
  * If for example, your system has 3G memory total, only allocate 2G to the Java process and leave the remaining 1G for the operating system.
* Consider updating to Java 11, your issue may be Java runtime related, so upgrading to the current LTS is probably a good idea
