### ISSUE TITLE
Issue with web editor

### ISSUE THREAD

**Issue by Shansha26** [lucko/LuckPerms#2747]
### Description

I keep on getting this error while using luck perms web editor:
There was an error loading the data. Either the URL was copied wrong or the session has expired.

Please generate another editor session with /lp editor.

### Reproduction steps

In the Console I wrote lp editor and it gave me a link and I followed it. It said loading and then this error message several times for the past 24 hours

1. Open the config.yml file and set example to true.
2. Restart the server
3. Run /lp user example permission set x from the console

### Expected behaviour

The web editor should have opened up but it didn't

### Environment details

Server version 1.16.4 - Spigot 
* Server type/version: `ExampleSpigot` running version `1.12.2` build `???`
* LuckPerms version: `v???`

![image](https://user-images.githubusercontent.com/75160529/100498821-c3ffb700-315c-11eb-8b95-f13f06f9335c.png)

### Any other relevant details

I have tried several times over the past 36 hours it is not working

**Comment by benwoo1110** [comment]
If you have ad blockers and/or antivirus, try disabling all of them. If you can, test with another wireless network like using your cellular service instead if home network etc.

This issue you face is usually just down to your network setup and most of the time, there isn't much luckperms can do about it.

**Comment by BrainStone** [comment]
Please fill out the last section of the issue template. These are important pieces information.

**Comment by Shansha26** [comment]
> If you have ad blockers and/or antivirus, try disabling all of them. If you can, test with another wireless network like using your cellular service instead if home network etc.
> 
> This issue you face is usually just down to your network setup and most of the time, there isn't much luckperms can do about it.

Let me try that now thanks for that suggestion

**Comment by Shansha26** [comment]
Thanks guys I solved it buy using mobile data instead of my wifi
