### ISSUE TITLE
MySQL problem

### ISSUE THREAD

**Issue by typecek123** [lucko/LuckPerms#2748]
Hello, I made another PaperSpigot server (using Waterfall) authlobby.
Each server have no problem with connecting to MySQL luckperms, but this has.
I read that site with Storage System errors... Iam sure, that everything is set-up right.
Error:
https://paste.hostify.cz/?9605c8a39567b44e#9Fot6zaK5yEmTtdSi6G9vtqcftz5fiAukuJcJ5zftdfi

**Comment by benwoo1110** [comment]
the error just means something wrong with the following listed on the Storage System errors wiki. Usually there isn't much LuckPerms can do, since it's up to your network, database setup and/or inputting correct database information for it to work.
