### ISSUE TITLE
Importing files to database

### ISSUE THREAD

**Issue by GamingVexed** [lucko/LuckPerms#2750]
I have setuped database in my bungeecord network, but i want import ranks to database from survival, i tried /lp import luckperms-h2.mv.db, but it gave an error ,i heard that luckperms-h2.mv.db is the file where are the ranks stored, so help?

**Comment by Fefo6644** [comment]
You should follow this guide if you want to change the storage method: https://luckperms.net/wiki/Switching-storage-types
The file name of the export file is anything (`backup`, `data`, `perms`, etc).

**Comment by GamingVexed** [comment]
i tried, but still dosen't work

**Comment by Fefo6644** [comment]
What did you try exactly? Please write down the *exact* steps you did.

**Comment by GamingVexed** [comment]
Well i did /lp export data then /lp export perms then i restarted server, then i did 2 same again exept import over export and in other server i did /lp sync

**Comment by Fefo6644** [comment]
1. Stop your server. Switch your `storage-method` back to how it was originally (I presume it was `H2`).
2. Start your server and run `/lp export data`.
3. Stop the server, Switch your `storage-method` to the new database one.
4. Start the server, run `/lp import data`.
5. Voilà.

**Comment by GamingVexed** [comment]
Thanks, it worked.
