### ISSUE TITLE
/lp track <track> editor

### ISSUE THREAD

**Issue by baailey** [lucko/LuckPerms#2752]
### Description
Too many times I find myself needing to edit multiple permissions for groups, and this requires opening an editor for each group each time! I suggest introducing an editor command for tracks, that will display all groups in a track and support editing them all at once. The command can be: **/lp track [track name] editor**

### Proposed behaviour
If we use the command **/lp track staff editor** it will open the web editor and provide a list of all groups on that track. The web editor already shows the [tracks](https://i.imgur.com/m6fxm7M.png), but I believe this is only visible when you simply use **/lp editor** and making changes using that on a live server is not the best idea, lol.

I believe this change will benefit many, and will make multiple group changes much easier.

**Comment by Turbotailz** [comment]
This seems like a legit suggestion tbh. No changes required from the editor end @lucko :P

> making changes using that on a live server is not the best idea

I'm curious as to why you think this?

**Comment by baailey** [comment]
`I'm curious as to why you think this?`

If I generated an **/lp editor** link and spend like 10 mins working on perm stuff, and then I push those changes, it will revert any other changes made AFTER I generated that link (perks bought, timed perk expires etc). It is v risky, so I never use **/lp editor** when making changes

**Comment by lucko** [comment]
This used to be the case in LP v4 - but we changed the system in v5.

Now only the _changes_ are applied, not the whole state.

**Comment by baailey** [comment]
Oh? I was not aware of that change. Though, either way, I think a track editor option couldn't hurt. I'm always gonna be a bit wary I think aha

**Comment by lucko** [comment]
That's fair!

And yep, definitely still a valid suggestion, thanks!

**Comment by baailey** [comment]
Hey! 

Just testing this out and noticed a minor detail - it seems that the editor option [doesn't display](https://i.imgur.com/WgQ5v8a.png) when trying to auto-tab the command. If I manually type the command the link still generates though!

Currently running version 5.2.84
