### ISSUE TITLE
Luck perms causes scoreboard issues

### ISSUE THREAD

**Issue by JHarris12345** [lucko/LuckPerms#2753]
Luck perms version: 5.2.35

Server version: Hyperion 1.8.8 (most used cannon jar)

Issue: Luck perms is causing an issue with featherboard whereby doing /fb reload is causing the scoreboard to default to an outpost scoreboard instead of the default one. The outpost scoreboard is only meant to be active in the outpost world. However, when I do /fb reload (doesnt matter what world I am in), you will see in the gif below (where I am in the normal world) that it defaults to outpost. It is not an outpost issue as Ive seen the code and the plugin only updates on player teleport event. Currently, when it defaults to outpost, activating the teleport event (like throwing an enderpearl or using /spawn) will fix it. But it shouldnt default to outpost in the first place. I know it is luckperms as deleting it fixes. Here is a gif for what I mean:

https://gyazo.com/2eb895585cd4a101bad8bd43d75b5b91

Some more info. Here is the gif without luck perms installed at all (I did a LP command to show it wasnt installed):
https://gyazo.com/a3062f4971ceb6a6997ea4aab2569a87

And here is the startup log for when LP wasnt installed:
https://pastebin.com/fZjatQvN

And here is the startup log WITH LP installed:
https://pastebin.com/dERgN3zn

Also here is /lp user jharris12345 info:
![image](https://user-images.githubusercontent.com/46936647/101083610-af7c4e00-35a4-11eb-9e77-60851937ebf0.png)

**Comment by lucko** [comment]
Please don't ignore the issue template - it is there for a reason.

You haven't given me enough information to be able to look into the problem.

I suggest you use the verbose command to try to identify exactly which permission check is failing.
https://luckperms.net/wiki/Verbose

Simply pointing out that the problem doesn't occur when LP is installed doesn't imply that there is a bug or problem in LP. I mean, of course a permission based scoreboard isn't going to work when you don't have any permissions plugin installed.

Until you can point to a specific, reproducible bug in LP, there is not much I can do to help.
