### ISSUE TITLE
Issue with Command Block

### ISSUE THREAD

**Issue by BboyZeroOne** [lucko/LuckPerms#2754]
### Description

When a player activates a command block via pressure plate with the command block executing this command "lp user @p parent add (role here)", the server instantaneously crash with this server log.

### Reproduction steps

1. Place a command block on the floor with a pressure plate above
2. Key this into the command block  "lp user @p parent add (role here)".
3. Step on the pressure plate
4. Crash

### Expected behaviour

It should give the player the parent rank/role.

### Environment details

* Server type/version: 1.16.4 - 288
* LuckPerms version: v5.2.29

https://pastebin.com/c7WCxZcs

### Any other relevant details

It did promote player to the said role but the server crashed afterwards.

**Comment by underscore11code** [comment]
Please follow the issue template.

**Comment by TheKiller65YT** [comment]
Looks like the crash report you provided was not an actual crash/error report. That message is generated when a server is lagging. If your server did exit unexpectedly, please provided the actual error log. Additionally, I was not able to reproduce with 1.16.4 Paper and the latest version of LuckPerms.

**Comment by BboyZeroOne** [comment]
> Looks like the crash report you provided was not an actual crash/error report. That message is generated when a server is lagging. If your server did exit unexpectedly, please provided the actual error log. Additionally, I was not able to reproduce with 1.16.4 Paper and the latest version of LuckPerms.

Problem is, server is not lagging at all before the pressure plate was activated. Its a brand new server with 2 players on it, pretty sure isn't server side lag.

**Comment by BboyZeroOne** [comment]
Activating the command block via pressure plate, causes the lag, then causes the "crash"

**Comment by TheKiller65YT** [comment]
It's interesting because I know since 1.13 selectors (like the @p) don't work on plugin commands. I'll review the relevant processing code, but I don't think LP has special support for them either. Are you using spigot/paper?

**Comment by BboyZeroOne** [comment]
> It's interesting because I know since 1.13 (**on spigot**) selectors (like the @p) don't work on plugin commands. I'll review the relevant processing code, but I don't think LP has special support for them either. Are you using spigot/paper?

Yes, I'm using paper 1.16. Do note that, the command did actually execute and promoted the player who stepped on the pressure plate. Just that it crashed afterwards.

**Comment by TheKiller65YT** [comment]
Okay, may I have a list of your active plugins then. It would seem one of them is doing the processing, and taking long at that. Again, `@p` shouldn't work as of 1.13, it was a spigot decision.

**Comment by BboyZeroOne** [comment]
![PL](https://user-images.githubusercontent.com/51330952/101276675-91ebf600-37e9-11eb-9f14-af193cddb4d3.png)

**Comment by TheKiller65YT** [comment]
Looks like it works fine by itself when I add CommandHook. You may be running out of resources. Either way, it's not a problem with LP.
![2020-12-05_23 44 04](https://user-images.githubusercontent.com/8169202/101276845-f3fa1c00-3753-11eb-818d-ec5013c20334.png)

**Comment by BboyZeroOne** [comment]
Ok, let me try upgrading the server and try once more

**Comment by BrainStone** [comment]
LP has special support for target selectors.

**Comment by TheKiller65YT** [comment]
Well, I don't know if that's a separate issue, but target selectors do not work when using LP by itself.

**Comment by Fefo6644** [comment]
> Well, I don't know if that's a separate issue, but target selectors do not work when using LP by itself.

Did you enable their parsing in LP config?

https://github.com/lucko/LuckPerms/blob/798a5390248516954bfd50a40b1e6569f7ecc6ed/bukkit/src/main/resources/config.yml#L635-L637

**Comment by BrainStone** [comment]
Right. It’s a config setting that needs to be enabled. Completely forgot 😅

**Comment by lucko** [comment]
Nothing here to suggest there's an issue with LP itself.
