### ISSUE TITLE
Bulk operations don't work properly on text based storage types.

### ISSUE THREAD

**Issue by Fefo6644** [lucko/LuckPerms#2755]
### Description

Bulk deletion of "LIKE" or unconstrained operations on plaintext based storage types gives nonsensical results. Ranges between not working at all to prompting wrong "statistics" data or working partially.
This is not the case for SQL based storage methods (either local or remote), presumably because the operation itself is delegated to the SQL service instead of "doing it manually".

### Reproduction steps

1. Open the config.yml file and set `storage-method` to any plaintext based storage type
2. Start the server, grant users and groups some permissions
3. Run either `lp bulkupdate all delete` or `lp bulkupdate <any> delete "permission ~~ <partial perm>%"`
4. Baffling results, check groups and users perms list

### Expected behaviour

Self explanatory

### Environment details

* Server type/version: `Waterfall` running version `1.16-R0.4` build `388`
* LuckPerms version: `v5.2.47`
* Storage method: any text based, combined or separated.

### Any other relevant details

Some screenshots:
#### H2 - Expected results
![](https://media.discordapp.net/attachments/642062687374934032/784599485728555008/unknown.png)

#### JSON - Same dataset, completely different results
![](https://media.discordapp.net/attachments/642062687374934032/784599822472445952/unknown.png)

#### By far the most impressive one
![](https://media.discordapp.net/attachments/642062687374934032/784609460139065384/unknown.png)

___
#### Additional note
Deletions with `permission ==` as constraint work correctly.

**Comment by lucko** [comment]
Thanks for the v detailed report.

Please could you confirm whether the above commit fixes the issue?

**Comment by Fefo6644** [comment]
Seems to have done the job 😄 at least for those I used as example.
