### ISSUE TITLE
Luckperms with multiverse core

### ISSUE THREAD

**Issue by TotaBank** [lucko/LuckPerms#2756]
### Description

When i got multiverse core to use multiple maps in the server, luckperms prefixes in chat disappeared forever. 
I tried to make new roles and update the plugin but nothing worked, the only one was a MITO plugin that gives a tag to 1 player.

### Reproduction steps

1. Open the config.yml file and set example to true.
2. Restart the server
3. Run /lp user example permission set x from the console
No error

### Environment details

Luck perms
NameTagEdit
multiVerse Core

* Server type/version: `Spigot` running version `1.8.8` build `???`
* LuckPerms version: 5.2.47

https://pastebin.com/4BdKsPzj

**Comment by BrainStone** [comment]
What's the output of ``/lp user <user> info`` for any user that should have a prefix?

**Comment by TotaBank** [comment]
[https://imgur.com/a/mcd8h5W](url)

This is one of 11 ranks that are in the game.

**Comment by TotaBank** [comment]
[https://imgur.com/a/mN4gKbo](url)

and just to show you, this is vip rank

**Comment by BrainStone** [comment]
Prefixes are clearly showing. So LP is working. The issue stems from your chat plugin.

**Comment by TotaBank** [comment]
thats the strangest part, because i have tags working in this chat plugin :/ https://imgur.com/a/7PbGjcV

**Comment by BrainStone** [comment]
In any case this is really not LP related as you could clearly see LP has prefixes for players.

**Comment by lucko** [comment]
Please don't ignore the template.
