### ISSUE TITLE
Joining my server gives a warning and then crashes the server

### ISSUE THREAD

**Issue by stijnjw** [lucko/LuckPerms#2757]
Hello, I just installing LuckPerms for the first time, about 30 minutes ago, and about 10 minutes ago, an issue started crashing my server everytime I joined it. [This](https://prnt.sc/vweeyq) is a warning when I join the server, and then after about 10 seconds it times me out and prints about 5 million lines of error and then stops.
It's really annoying and I just can't figure the problem out.

**Comment by BrainStone** [comment]
Please 
- follow the error report outline
- provide the full log
