### ISSUE TITLE
Incorrect placeholder expiry time

### ISSUE THREAD

**Issue by EnderGamingFilms** [lucko/LuckPerms#2758]
### Description
`%luckperms_group_expiry_time_supporter%` is resulting in 5d 59h 36m... When it should be a 30-day (4 week) countdown. The command that was used to give the rank was `lpb user {uuid} parent addtemp supporter 30d accumulate`

Placeholder:
![image](https://user-images.githubusercontent.com/25815579/101307989-9f12e000-37fd-11eb-82c3-7627984a6406.png)

Parent Inspection: `/lp user <user> parent info`
![image](https://user-images.githubusercontent.com/25815579/101308032-be117200-37fd-11eb-8418-8e585e6c05a0.png)

### Expected Behavior
It should countdown from 29d 23h 59m

### Environment details

* Server type/version: `PaperSpigot` running version `1.16.3 build `253`
* LuckPerms version: `v5.2.35`

### Any other relevant details
I am using TrMenu for the GUI but it uses PlaceholderAPI and MVdWPlaceholderAPI for placeholder handling. I have also tried downloading the LuckPerms placeholder jar from cloud but the sam error occurs.

**Comment by Fefo6644** [comment]
Update PAPI to a dev build http://ci.extendedclip.com/job/PlaceholderAPI/

**Comment by EnderGamingFilms** [comment]
Dev build fixed it.
