### ISSUE TITLE
Error in the console

### ISSUE THREAD

**Issue by Sikatsu** [lucko/LuckPerms#2759]
### Description
This error shows up in the console now and then: https://pastebin.com/062yFdpw

### Environment details

* Server type/version: `Tuinity` running version `1.16.4` build `ed9e0c4`
* LuckPerms version: `LuckPerms (5.2.32)`

**Comment by benwoo1110** [comment]
I suggest you send your full startup log, instead of just a few line. And also good to update https://luckperms.net/download and test with only luckperms installed.

**Comment by Sikatsu** [comment]
I'll try updating, this error has been around for a few months though on older versions as well. This error does not occur on startup, but randomly when the server is running. Startup: https://pastebin.com/DEt3p3tz

**Comment by lucko** [comment]
Thanks, should be fixed by the above commit :)
