### ISSUE TITLE
Long error messages after someone leaves

### ISSUE THREAD

**Issue by GapiCer** [lucko/LuckPerms#2765]
### Description
Every time someone leaves the server there's long error messages coming from luckperms. At first luckperms still works but after a while it stops working entirely. I don't know what caused this, I tried deleting and reinstalling luckperms which worked for a while but then it started happening again. It happened right after a reload, so could it be that, or is it an issue with some other plugin?

### Environment details
* Server type/version: `Paper` running version `1.16.4` build `Paper-332`
* LuckPerms version: `Bukkit 5.2.53`
Plugin List: EssentialsX, CoreProtect, Graves, LaggRemover, Modern-LWC, NoteBlockAPI, SkinsRestorer, SuperVanish, TAB, Vault, worldedit, worldguard, worldguardextraflags.

error message: https://pastebin.com/YC0dBJmS 

warn message: https://pastebin.com/wfbD41Y2 (everytime after someone leaves)

after a while of these messages and when it stopped working a player couldn't join: https://cdn.discordapp.com/attachments/516589040288530433/786575466974674988/unknown.png

I sincerely apologize if this is just me being dumb, I genuinely don't know how to fix this.

**Comment by underscore11code** [comment]
Have you used the command `/reload` at all? I seem to recall errors like this coming up when I was using /reload for development work.

**Comment by GapiCer** [comment]
> Have you used the command `/reload` at all? I seem to recall errors like this coming up when I was using /reload for development work.

yeah it happened right after a reload

**Comment by underscore11code** [comment]
Yup that's 100% why. `/reload` is a command that should never be used, it causes lots of issues like this. Restart the server, and the issues will resolve themselves.

**Comment by underscore11code** [comment]
For more information, see this blog by Me4052: https://matthewmiller.dev/blog/problem-with-reload/

**Comment by GapiCer** [comment]
Ok, thanks for the help!
