### ISSUE TITLE
Rank color placeholder

### ISSUE THREAD

**Issue by Teric7** [lucko/LuckPerms#2768]
Hi there I need to know what placeholder to use to only show luckperms group color for Featherboard reasons

**Comment by Teric7** [comment]
or is there a way for me to create a custom placeholder like what I've done here with BTLP
![image](https://user-images.githubusercontent.com/69757490/101983931-e2de6d00-3c75-11eb-85a3-5c5b3ff7991a.png)

**Comment by benwoo1110** [comment]
You could set the colour code as meta values, then use the meta placeholder.

https://luckperms.net/wiki/Meta-Commands#lp-usergroup-usergroup-meta-set-key-value-context
https://luckperms.net/wiki/Prefixes,-Suffixes-&-Meta
https://luckperms.net/wiki/Placeholders#luckperms_meta_meta-key
