### ISSUE TITLE
Error when trying to create a new group

### ISSUE THREAD

**Issue by Tobi-Jakka** [lucko/LuckPerms#2769]
### Description

Whenever I try to create a new group i get an error message

### Reproduction steps

1. /lp group creategroup name

### Expected behaviour

Following error messages appears in the console & nothing happens ingame 

### Environment details

* Server type/version: `PaperSpigot` running version `1.16.4` build `323`
* LuckPerms version: `v5.2.35`

Console Error:
https://pastebin.com/6jxrZ1z2

**Comment by Tobi-Jakka** [comment]
Not sure if this helps but I think it have something to do with MySQL
![image](https://user-images.githubusercontent.com/42676160/102028830-4a96d400-3dac-11eb-9b34-939020d36266.png)

**Comment by lucko** [comment]
It seems like you've modified the LuckPerms table in some way? That's not the standard schema...

The easiest fix is probably to delete the LP tables and let the plugin regenerate them.

**Comment by Tobi-Jakka** [comment]
Yeaa I have a table added that I use for displaying my ranks on my website, do you think regenerating the table & then manually adding the custom table would work? * this database was a save I pasted in from another MySQL database
