### ISSUE TITLE
ViaVersion is not a depend, softdepend or loadbefore of LuckPerms

### ISSUE THREAD

**Issue by HandyHat** [lucko/LuckPerms#2771]
### Description
The following warning appears in console:
`[Server thread/WARN]: [LuckPerms] Loaded class us.myles.ViaVersion.api.protocol.ProtocolRegistry from ViaVersion v3.2.1 which is not a depend, softdepend or loadbefore of this plugin.`

### Reproduction steps

1. Startup server with ViaVersion and LuckPerms
2. Observe warning in console

### Expected behaviour
No warning to appear in console

### Environment details
* Server type/version: `PaperMC` running version `1.16.4` build `323`
* LuckPerms version: `v5.2.55`
* ViaVersion version: `v3.2.1`

**Comment by lucko** [comment]
Thanks, should be resolved :)
