### ISSUE TITLE
Promoting along track doesn't work.

### ISSUE THREAD

**Issue by Aitnys** [lucko/LuckPerms#2772]
### Description

 I updated to version 5.2.55 today and promoting along a track seems to have broken. it works once, but it looks like its not removing the old rank so when it tries to promote again it fails because the player has 2 ranks on the track. https://paste.dedimc.io/oquhofolum.md

### Reproduction steps

1. install luckperms version 5.2.55 and no other plugins (no previous luckperms folder)
2. Restart the server
3. Run `/lp editor` and add group one, two and three and create a track tr and add all 3 to the track. 
4. `/lp user name parent add one`
5. run `/lp user name promote tr` twice, first time will work as expected and second time will give the error.

![](https://cdn.discordapp.com/attachments/727570283887591484/788099534550204476/unknown.png)

### Expected behavior

I expect to be able to promote along the whole track. 

### Environment details

This server is running Tuinity version git-Tuinity-"cc34294" (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
Running LuckPerms v5.2.55 by Luck.

These are from when I was testing it on my live server.
https://paste.dedimc.io/oquhofolum.md
https://paste.dedimc.io/ebeqosomaw.md

### Any other relevant details

not right now.

**Comment by Aitnys** [comment]
oof i blink and theres 4 new updates.. tried with the newest as of right now and does the same.

![image](https://user-images.githubusercontent.com/60077198/102121293-09ea9980-3e44-11eb-9fa8-1e78d69171c3.png)

**Comment by Fefo6644** [comment]
Can confirm this happens regardless of the storage system used.

**Comment by KugelblitzNinja** [comment]
Can confirm this still happens with ver v5.2.60

We have about 200 effected users so if a way of also fixing what damage has been done also it would be much appreciated.

**Comment by lucko** [comment]
This should be resolved in `v5.2.61` - nasty bug, sorry about that - didn't show up at all in testing :L 

Unfortunately there's no easy way I can think of to fix existing promotions - might be something that you have to do by hand.. sorry.
