### ISSUE TITLE
BedwarsRel 1.8.8 server

### ISSUE THREAD

**Issue by Magzypotato** [lucko/LuckPerms#2776]
### Description

I added a new mysql database for bedwarsrel stats then this error happened

### Reproduction steps

1. Download bedwarsrel and setup a game in a 1.8.8 server, 
2. when everything is setup and done make it bungeecord, 
3. then add a mysql database to bedwarsrel stats in its config. 
4. After that join it from another server, 
5. you will get many errors in the server log

### Expected behaviour

The bedwarsrel plugin to work

### Environment details

Spigot-1.8.8 Minecraft server

* Server type/version: `CraftBukkit` running version `1.8.8` build git-spigot-db6de12-18fbb24 and "(implementing API version 1.8.8-R0.1-SNAPSHOT)"
* LuckPerms version: `v5.2.40`

Error in server log: https://paste.gg/p/anonymous/247b5eeea160426bbc218f11cae51d15

**Comment by lucko** [comment]
Could you enable `debug-logins` in the LP config.yml then try again

**Comment by Magzypotato** [comment]
> Could you enable `debug-logins` in the LP config.yml then try again

And then what?

**Comment by lucko** [comment]
That's not an LP error, so seems like it's working ok?
