### ISSUE TITLE
PlaceholderAPI issue

### ISSUE THREAD

**Issue by WarnDangerous** [lucko/LuckPerms#2777]
### Description
The placeholder %luckperms_inherited_expiry_time_XXX% and %luckperms_expiry_time_<permission>% doesn't display the good amount of time of the permission.

### Reproduction steps
Give to a player a permission for more than a month, then parse him the  %luckperms_expiry_time_<permission>% or %luckperms_inherited_expiry_time_XXX%, it will display a bugged number with for example "15d 38h 10s" so it's fully bugged, it should be "1 month" for example

### Expected behaviour
 It should display the good number of time

### Environment details
Please provide details of your server environment in the space below

* Server type/version: `Paper 1.12.2 v1618 (latest one) `???`
* LuckPerms version: `LuckPerms-Bukkit-5.2.35.jar`

### Any other relevant details
https://prnt.sc/w6imbr

**Comment by WarnDangerous** [comment]
Same on 1.16.4 with latest version of PAPI and Luckperms 5.2.35.
It displays ">....=>.... [14:13:23 INFO]: 21d 59h 59m 34s" instead of 
"Set jobs.boost.all.all.1 to true for warndangerous for a duration of 1 month 1 week 4 days 13 hours 30 minutes 50 seconds in context global."

**Comment by Fefo6644** [comment]
Update PAPI to a dev build :) https://ci.extendedclip.com/job/PlaceholderAPI/

**Comment by WarnDangerous** [comment]
It seems to work on my test server,
I'll try tomorrow on my official server (after server restart) and let you know ! Thanks :D
