### ISSUE TITLE
ArrayIndexOutOfBoundsException: 18

### ISSUE THREAD

**Issue by Prasodym** [lucko/LuckPerms#2779]
Hello, 
We have since days several ArrayIndexOutOfBoundsException: 18 error messages in the console. we have also already installed an extension on it (extension-legacy-api-1.0.0.jar) also without success.
***
#Info
Plugin version: LuckPerms-Bukkit-5.2.61
Serverjar: Magma version 966e691 (Implementing API version 1.12.2-R0.1-SNAPSHOT, Forge version 14.23.5.2854)
Storage mode: Mysql
***
Plugins: Multiverse-Core-2.5.0, MysqlInventoryBridge-v2.4.1, Vault, worldedit-bukkit-6.1.9, worldguard-bukkit-6.2.2, JomluaCore-1.5.3(Suitable plugin).
***
# Files
|file|link|
|---|---|
|`Consoles error`|[Link](https://pastebin.com/StNdbaJR)|
|`latest.log`|[Link](https://sne.jomlua.de/rec/latest.log)|
|`LP Config`|[Link](https://pastebin.com/xMYBSu57)|

**Comment by lucko** [comment]
This is really an issue with your Bukkit/Forge hack, but I've added a workaround in LP anyway.
