### ISSUE TITLE
User meta issue

### ISSUE THREAD

**Issue by ItsMacs** [lucko/LuckPerms#2781]
### Description
When a group is set to a user, the user's meta gets set to the previous group's.

### Reproduction steps
1. Run the command /lp bulkupdate users delete permissions (to clear permissions and groups)
2. The user now has the default group set, with a clear user meta
3. Set the user's parent to another group
4. The user now has the default group meta set as user meta and in order to show the new group info, /lp user <user> meta clear is required.

### Expected behavior
When I set a user to a group, I expect the plugin to not set the previous group's meta to the user.

### Environment details

* Server type/version: `YAPFA (PaperSpigot) 1.15.2`
* LuckPerms version: `v5.2.38`

**Comment by ItsMacs** [comment]
Bump

**Comment by Fefo6644** [comment]
Does this happen when LuckPerms is the only plugin installed?
Screenshot `/lp info` and two `/lp editor` links from before and after running the bulk update command please.

**Comment by ItsMacs** [comment]
![LP Info Before](https://user-images.githubusercontent.com/70864018/103457038-07b98380-4cfc-11eb-9105-6e12a4509d45.png)
![Two links before](https://user-images.githubusercontent.com/70864018/103457043-0ee09180-4cfc-11eb-80bd-8feeb7c34a81.png)

![After](https://user-images.githubusercontent.com/70864018/103457106-8ca49d00-4cfc-11eb-9711-8eae0f320aef.png)

Sorry for the late reply..
