### ISSUE TITLE
Unable to Join: An unexpected error occurred whilst setting up your permissions data

### ISSUE THREAD

**Issue by Buddelbubi** [lucko/LuckPerms#2791]
### Description
Sometimes when joining a Server, you get kicked with the message  "An unexpected error occurred whilst setting up your permissions data. Please try again later." Also affects Server-Switching with waterdog. Then you'll be stuck in a world of acazia buttons.
It doesn't happens always. But very often. 

### Reproduction steps
1. Join the server
2. Read the error in the console (https://bytebin.lucko.me/4IzER2kfGX)

### Expected behaviour
Dont get kicked,
Getting no error in the console

### Environment details

 Server type/version: Nukkit git-81a74c2 API:1.0.11 
 LuckPerms version: v5.2.65

Config: https://gist.github.com/Buddelbubi/4b5dfb0d2b7b85231cd87c92c84ff3ea

### Any other relevant details
Using WaterDog, 
Using CloudNet v3

Doesn't happen that often on new servers. Let them run a little bit. Then try to join.

**Comment by lucko** [comment]
Thanks for reporting :)

Btw, it seems like for some reason either the join event is being called twice, or Player instances are being reused. That would suggest to me there is some sort of bug in either Nukkit, Waterdog or another plugin integration - might be worth looking into.
