### ISSUE TITLE
Suppressing a returning error (would mean the world to me <3)

### ISSUE THREAD

**Issue by Nick0251** [lucko/LuckPerms#2793]
### Description

I have never had any bad issues with luckperms, I love luckperms and I expect to be using it for a long time.
I do have one suggestion which would really help clean up my console, I believe it is the only error I keep seeing returning frequently because my players level up pretty quickly.

When someone levels up we give them a suffix with a few symbols in them declaring the level of the player (pvp related).
Giving these suffixes with symbols causes an error to be put in console, and I'd be really happy if we coud somehow get rid of this error: https://pastebin.com/30fgnCs7

My suggestion is that maybe you could make a configurable "suppress" option for this specific error

### Proposed behaviour

An option in config to suppress this error as it doesn't seem to break/malfunction when giving the suffix

**Comment by arenmarsden** [comment]
Wouldn't this be more of a bug report rather than a suggestion? I don't think your LP should be spitting errors like that.

**Comment by BrainStone** [comment]
You need to run this MySQL command in your LuckPerms database:

```mysql
ALTER TABLE luckperms_messenger CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
```

Assuming your table prefix is the default `luckperms_` (if you didn't change it, that's what it still is)
