### ISSUE TITLE
user Promote and Demote commands won't conserve the expiry time.

### ISSUE THREAD

**Issue by Tomi010817** [lucko/LuckPerms#2794]
### Description
When you use the promote or demote command on someone that has a group on a specific track, the expiry time (in case it is a temporary group) won't conserve and it will turn permanent.

### Reproduction steps
1- Create a track including 2 groups (group "A" and group "B")
2- Apply yourself one of those groups **temporarily**.
3- Promote or demote yourself on that track, and the expiry time won't be conserved, turning into a permanent group.

### Expected behaviour
I actually don't really know if this is an intended behavior, but actually the current behavior is not that bad, but I think that maybe a flag (on the promote and demote command) for keeping the expiry time instead of turning it permanent, would solve this issue.

### Environment details
PaperSpigot 1.8.8
Luckperms v5.2.67

### Any other relevant details
I labeled this as "bug" because I discussed this issue on the luckperms discord to get opinions on this behavior, but this could be also interpreted as a suggestion/idea.

**Comment by lucko** [comment]
I'm not sure a flag is necessary - but I've switched it so the expiry time is preserved :)

**Comment by Tomi010817** [comment]
Thank you lucko
Have a hppy new year!

**Comment by CuBeR116** [comment]
How use tmp promote?
