### ISSUE TITLE
Boolean to let specific permissions override wildcards

### ISSUE THREAD

**Issue by Helmasaur** [lucko/LuckPerms#2797]
### Proposed behaviour
If a parent have a specific permission which is set to false and the child wildcard where the specific permission is is set to true, the command will not work. It would be nice to add a boolean in the configuration file so this behavior could be activiated.

When there are a few commands I want to disable, I set the wildcard to true and then get rid of the specific permissions, then I add the wildcard to true in the stronger group (for example `admin` > `moderator`).

**Comment by BrainStone** [comment]
Just set the specific to true/false in the child. That overrides the parent.

**Comment by Helmasaur** [comment]
All the rest will inherit the right way?

**Comment by BrainStone** [comment]
What?

No idea what you mean.

**Comment by benwoo1110** [comment]
I suggest you take a look at this: https://luckperms.net/wiki/Advanced-Setup#permission-calculation

**Comment by lucko** [comment]
This is supported already, see the link above :)

**Comment by Helmasaur** [comment]
On Discord, I was told that if there is a specific right that is forbidden for a group, it won't be authorized in the child group, even if allow the wildcard in the child group.

The way I use permission is to add the whole wildcare and set to false the couple permissions i don't want in the group. Maybe it's the wrong way to do it?
