### ISSUE TITLE
When joining through a proxy to a lobby, I get an error which crashes my client.

### ISSUE THREAD

**Issue by MrRazamataz** [lucko/LuckPerms#2799]
### Description
When joining through a proxy to a lobby, I get an error which crashes my client, this doesnt happen everytime but it happens a fair amount to be annoying. I have LuckPerms installed on both my proxy (WaterDog) and my lobby (nukkit).

### Expected behaviour
Player should join with no issues.

### Environment details
The client either crashes or gets stuck in a locating server glitch screen of which the player cannot get out of and has to restart the client.

* Server type/version: `ExampleSpigot` running version `1.12.2` build `???`
* LuckPerms version: `v???`
Lobby: Nukkit git-da41bf2
Luckperms: LuckPerms v5.2.67
Proxy: This server is running Waterdog version git:Waterdog-Bootstrap:1.15-SNAPSHOT:607faf3:15 by md_5
https://bytebin.lucko.me/kjRUYl1SED

**Comment by Buddelbubi** [comment]
Same error: https://github.com/lucko/LuckPerms/issues/2791

**Comment by lucko** [comment]
Thanks for reporting :)
