### ISSUE TITLE
Set default group on join

### ISSUE THREAD

**Issue by TheOneWhoKnocks** [lucko/LuckPerms#28]
Is it impossible to set the default group one gets assigned on the first join or is it me who just can't find the correct command? :)

Great plugin so far!

**Comment by lucko** [comment]
This seems to be a commonly asked question, so I'll write a wiki article about it. 🙂

**Comment by TheOneWhoKnocks** [comment]
That would be awesome :)

**Comment by Jamie4224** [comment]
You can read this 'Issue' created by me, this created very conditional default systems for almost anything in the plugin:
https://github.com/lucko/LuckPerms/issues/25

-Jamie

**Comment by lucko** [comment]
Here's the wiki page: https://github.com/lucko/LuckPerms/wiki/Default-Groups

Still very much a WIP, I just dumped all of my thoughts to the page, and haven't really had a chance to refine it much yet.

Let me know if you have any questions, and I'll happily refine my descriptions. 🙂
