### ISSUE TITLE
`luckperms.*` no longer works by default

### ISSUE THREAD

**Issue by Fefo6644** [lucko/LuckPerms#2800]
### Description

Due to the recent commit https://github.com/lucko/LuckPerms/commit/8167fbf73f99debb0cd8c1a46412a0176afb88af and the addition of the setting https://github.com/lucko/LuckPerms/blob/8167fbf73f99debb0cd8c1a46412a0176afb88af/bukkit/src/main/resources/config.yml#L473-L482 which is true by default (although it fallbacks to false if not found) **and** LP's nature of defaulting its own permissions to false prevent it from being used (by default) without being server operator, regardless of the permission.

### Reproduction steps

1. Install LuckPerms v5.2.67 or latter.
2. Give a user the `luckperms.*` wildcard permission.
3. Try running any LP command.

### Expected behaviour

Granted `luckperms.*` one would expect to have full access to LP commands, especially since it's the very first post-installation step in the usage guide!
For most other plugins wildcards would work fine since they default to OPs only (classic "false undefined").

### Environment details

* Server type/version: `Paper` running version `1.16.4` build `352`
* LuckPerms version: `v5.2.67`

### Any other relevant details

non

**Comment by lucko** [comment]
`commands-allow-op` defaults to true, so it should still work fine?

**Comment by lucko** [comment]
I've just tested & confirmed it does indeed still work.

Of course, if the user chooses to set `commands-allow-op` to false it won't - but that's the nature of that option.

**Comment by Fefo6644** [comment]
Yeah, it should work fine if one is op (which may be the case when first setting everything up), but the wildcard itself no longer "works". Besides, not all platforms allow for a server operator, e.g. Sponge disables it or BungeeCord in which there is no server operator.

**Comment by lucko** [comment]
No, I'm saying it does still just work.

On a completely fresh server, you can grant `luckperms.*` in the console without opping to give access to all LP commands.

The potential issue doesn't apply to Sponge or BungeeCord because LP doesn't mark the permissions as explicitly false by default on those platforms.

**Comment by Fefo6644** [comment]
Uuh.. I must have missed something when testing? It works fine :thinking: well, closing the issue then.
