### ISSUE TITLE
permissions not working

### ISSUE THREAD

**Issue by Capta1nBlockhead** [lucko/LuckPerms#2801]
### Description

with any of my ranks on my server, i give them permissions, and i give myself the rank, i deop my self, and i cant do any commands

### Reproduction steps

1. Open the config.yml file and set example to true.
2. Restart the server
3. Run /lp user example permission set x from the console

### Environment details

* Server type/version: `ExampleSpigot` running version `1.12.2` build `???`
* LuckPerms version: `v???`

**Comment by benwoo1110** [comment]
Follow the issue template...
