### ISSUE TITLE
Data too long for column 'world' 

### ISSUE THREAD

**Issue by call911nowplz** [lucko/LuckPerms#2803]
### Description

Using auto-generated worlds (Worlds get UUID-alike names) I cannot give perms using world=(world name) because the name is too long.

### Reproduction steps

- Have a world with long name (Such as mine being island_ad9e0a4c-897c-4d13-b224-1edf2dca8d16_normal)
- Try adding a specific permission using world=world=island_ad9e0a4c-897c-4d13-b224-1edf2dca8d16_normal

### Expected behaviour

A permission to apply no matter the world name length

### Environment details

Using MariaDB

* Server type/version: `1.8.8 Spigot` 
* LuckPerms version: `v5.2.35`

https://pastebin.com/NYMprrML

**Comment by lucko** [comment]
That's a pretty long world name! But, it should still be ok - the max length is 64 characters.

(or it might be shorter if you started using / created your LP database a while ago)

You might need to manually increase the column limit in your MySQL database, should be relatively easy to do with phpmyadmin or something like that.

Failing that, might just be worth trying to generate shorter world names? :/
