### ISSUE TITLE
Connection.setNetworkTimeout cannot be called on a closed connection

### ISSUE THREAD

**Issue by Jackk999** [lucko/LuckPerms#2805]
Good evening, I have been experiencing the underlying problem for some time now where the server crashes completely without even restarting with the loop.
Reading some online guides and from the same error message I tried to lower the MaxLifeTime over and over again the connection-timeout but nothing, how can I do to solve?

Pastebin with log here:
https://pastebin.com/kUPXkHpp

**Comment by lucko** [comment]
Can you try switching to `mysql` storage instead of mariadb to see if that resolves the issue.

**Comment by Jackk999** [comment]
Yes, I try to let you know by tomorrow because it usually crashes after a few hours

Thanks 👍

**Comment by Jackk999** [comment]
Goodmorning how are you?
  Unfortunately apparently the problem was not that, now it gives me this error:

https://pastebin.com/3j5mLfYt

Thanks so much for your help

**Comment by Jackk999** [comment]
PS: but this time the server hasn't crashed and if I run in game / lp it seems to work ... mhh

**Comment by Jackk999** [comment]
Okay I think I understand the problem but I don't know how to solve it, that is after 8 hours of inactivity I think that mysql disconnects some connections like that of LuckPerms and also LiteBans, in fact from the logs putting the connection in MySQL instead of MariaDB now this "The last packet successfully received from the server was 54,318,428 milliseconds ago. The last packet sent successfully to the server was 54,318,448 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and / or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector / J connection property 'autoReconnect = true' to avoid this problem. "

I leave you the complete logs if you want to help me
[2021-01-02-1.log](https://github.com/lucko/LuckPerms/files/5760901/2021-01-02-1.log)

**Comment by lucko** [comment]
You can find details about how to fix this issue on our wiki :) 

https://luckperms.net/wiki/Storage-system-errors#mysql-no-operations-allowed-after-connection-closed-error
