### ISSUE TITLE
Plural Elements

### ISSUE THREAD

**Issue by Tomi010817** [lucko/LuckPerms#2806]
### Description
 Having the elements that let you define a track or a group on plural instead of singular, would make the meta formatting much more manipulable and comfortable to edit at your liking.
Example:
`highest_on_track_<track>` would turn into `highest_on_tracks_<tracks>`
So instead of only being able to put 1 track, you would be able to set more than 1.
`highest_on_tracks_staff,donors`

Same with elements that include `<group>`. So for example `highest_from_group_<group>` would turn into `highest_from_groups_<groups>`
And you would be able to add more than only 1 group: `highest_from_groups_owner,admin,vip`

**Comment by lucko** [comment]
I want to try to keep the system from becoming any more complex.. so unlikely to implement this as-is. I do have a suggestion for you though:

`highest_from_groups_...` can be replicated by just creating a throwaway track (i.e. one you're not going to use for promotion) with the groups you want.

Likewise with `highest_on_tracks_...`, just create another track which contains a union of the tracks you want to query for.

Thanks for the idea, but probably not something that is in-scope for LP at the moment:)
