### ISSUE TITLE
LuckPermsMessagingService#receivedMessages leak

### ISSUE THREAD

**Issue by voodootje0** [lucko/LuckPerms#2807]
[receivedMessages](https://github.com/lucko/LuckPerms/blob/63878166db13b7a5cdc1edce52af8beca530e51c/common/src/main/java/me/lucko/luckperms/common/messaging/LuckPermsMessagingService.java#L63) will keep on growing, even it's only a UUID. 
On high production proxies with uptimes of a few weeks, this will all count up to 100+ MB's.

**Comment by lucko** [comment]
Thanks for bringing this to my attention :)
