### ISSUE TITLE
Ability to remove user from the web editor

### ISSUE THREAD

**Issue by owlman5126** [lucko/LuckPerms#2811]
### Description

People with access to the web editor should be able to remove users from there like you can with groups

### Proposed behavior

an **X** next to a players username that when you click it it will remove all data with that player

**Comment by benwoo1110** [comment]
its already there, ensure you are on the latest version of lp. https://luckperms.net/download
![image](https://user-images.githubusercontent.com/30431861/103672791-c1904880-4fb7-11eb-9b2f-a4fe9f9f3e71.png)

**Comment by owlman5126** [comment]
I thought I was updated. ._. sorry about wasting your time
