### ISSUE TITLE
Fabric: Mincraft commands not auto filling & do not work

### ISSUE THREAD

**Issue by ElijahRus250** [lucko/LuckPerms#2812]
### Description
I give someone the persimmon node `minecraft.command.seed`

However it does not work and says unknown command, (works with op)

Aswell as on the web editor and in game the default Minecraft commands do not auto fill.

### Reproduction steps

1. do `/lp editor` or `lp editor` from console
2. select a user / group
3. start typing in minecraft
4. see it does not auto fill
5. give someone a perm like `minecraft.command.seed`
6. make sure you do not have op or * perms
7. save the editor and apply edits 
8. type `/seed` or whatever Minecraft command in game

### Expected behaviour

It will autofill and allow the user to type a command like `/seed`

### Environment details

* Server type/version: `Fabric` running version `1.16.4` build`0.6.1.51`
* LuckPerms version: `v5.2.76`

### Any other relevant details
I used /seed in this example but have tested the issue with commands like ban, kick and others

**Comment by ElijahRus250** [comment]
<img width="644" alt="Screen Shot 2021-01-05 at 10 58 28 PM" src="https://user-images.githubusercontent.com/64851720/103727557-87b84580-4fa9-11eb-845b-2005bcde9766.png">


*Note it is only showing up here due to me typing it in before*

**Comment by Laarryy** [comment]
I am not certain that Fabric has inbuilt permissions for vanilla actions at this point - the examples you give, like `minecraft.command.seed` are built into Bukkit as permission nodes to control those actions specifically and you can find them 
 at https://bukkit.gamepedia.com/CraftBukkit_Commands

As LP does indeed work on fabric for things that have permissions, this is likely something that should be raised with the Fabric team. LP cannot control what perms are called or what they do - it only gives them and takes them away from players in the end.

**Comment by Laarryy** [comment]
I can in fact confirm that fabric does not have permissions for those actions at all - it only recently got a permissions API and nothing has, as of yet, been added in terms of permissions for vanilla actions
