### ISSUE TITLE
Setting require-sender-group-membership-to-modify to true Completely Breaks the plugin (Reproducible)

### ISSUE THREAD

**Issue by bugattiboy01** [lucko/LuckPerms#2815]
### Description

Spent last 3 days setting perms on a server. Needed to make it so lower staff cannot demote higher staff
Support in discord told me to set require-sender-group-membership-to-modify to true
set this. Restarted server did /lp editor. It worked fine 
Noticed i had no permission to do anything with luckperms even though i was OP and had the Permission* set in my username
also had basically no perms for anything.
Did /lp editor. Only 2 of the Groups out of 10 were there now. 
Used support to import export backup etc. They couldnt make it work.
Deleted the database. 
/LP info still showed the right amount of groups. But the editor still only showed 2 and forcing the exact same permissions i know i had into it as i had an old editor tab with all the perms still open. Wouldnt apply in game.

Deleted complete folder of Luckperms and jar
Reinstalled.
Redit all of the perms then i still NEEDED the require-sender-group-membership-to-modify :true to work so i set that again.
Did this restarted. Same problem.

Sending the /lp editor Link to the support staff they saw something was wrong directed me to open an issue here
The editor again only showed 2 groups contrary to /lp info

Only way to fix it so delete the entire plugin and redo but NOT setting that variable to True

### Reproduction steps

1. Have all permissions set and working.
2. set require-sender-group-membership-to-modify in the config.yml true
3. Restart
4. Open /lp editor and apply a change of any kind
5. Open it again and 80% of the groups are missing but /lp info shows the correct amount
6. Try permissions now missing from the editor. Wont work even though showing in /lp editor

### Expected behaviour
My permissions not to disappear and break
Currently i have 0 way of making it so mods cant demote admins and this has been Incredibly frustrating trying to get ti to work all day as im the only person setting up the Servers systems. Please help me im losing my mind

### Environment details

* Server type/version: `Tuinity Paper` running version `1.16.4` build `latest as shown by apexhosting`
* LuckPerms version: `v5.2.35`
* Hosted by Apex

**Comment by Fefo6644** [comment]
As the name of the setting suggests, you need to "be member of the group" / inherit a group to be able to edit it, this also applies to which groups are uploaded to bytebin when you run `/lp editor`. The groups are still there and their permissions are still there, but the editor will not upload the groups you do not inherit (at the time of running `/lp editor`).

**Comment by Fefo6644** [comment]
Also as for the backing reason why you set it to true in the first place (which there was no need) you want to set up [argument based permissions](https://luckperms.net/wiki/Argument-based-command-permissions) to let other people use LuckPerms but in a very limited way based on the actual arguments passed to the commands (group name, track name, contexts, etc.).
