### ISSUE TITLE
Luckyperms won't work on Fabric server on bungeecord network

### ISSUE THREAD

**Issue by kristianbinau** [lucko/LuckPerms#2816]
### Description

Fabric server on bungeecord network won't work w/ luckperms...

### Reproduction steps

1. Create a new fabric server w/ luckyperms & fabricproxy
2. Connect the server to a bungeecord network
3. Try to join

### Expected behaviour

I want to login : )

### Environment details

* Server type/version: `Fabric` running version `1.16.4` build `v0.6.1.51`
* LuckPerms version: `v5.2.77`
* Fabric API version: `v0.28.3`
* FabricProxy version: `v1.4.4`

Error message: `[LP] Permissions data for your user was not loaded during the pre-login stage - unable to continue.`
https://gist.github.com/kristianbinau/db630ba2f2a7a1fe36020dfd608fe8c6

**Comment by lucko** [comment]
This is an issue with FabricProxy overriding the Fabric networking API which LP uses.

It seems like FabricProxy v1.4.5 has been released which may resolve the issue :)
