### ISSUE TITLE
[Fabric] /perms Permission Bug

### ISSUE THREAD

**Issue by TehcJS** [lucko/LuckPerms#2818]
### Description

I honestly have no idea why it does this. It says "`Permissions have not been initialised for this player yet.`"

### Reproduction steps

1. `/kill` yourself (with or without op)
2. Type `/perms`
3. Check Console

### Expected behaviour

Log spam.

### Environment details

Minecraft Environment: `Floader 0.10.8 + Fabric + Jellysuite` running `1.16.4`
Operating System: `Ubuntu 18.04 x64`

https://gist.github.com/TehcJS/bbd1375e911b80e12db1e267d263f1c0

### Any other relevant details

It also happens when it tries to give you suggestions when using `/perms`. For instance, if I typed `/perms h`, it would spam the error until I stopped typing.

**Comment by lucko** [comment]
Thanks for reporting, this should be fixed :)
