### ISSUE TITLE
Exception thrown

### ISSUE THREAD

**Issue by srnyx** [lucko/LuckPerms#2819]
### Description

Console is being spammed with an error about "An exception was thrown by me.lucko.extracontexts.calculators.WorldGuardFlagCalculator whilst calculating the context of subject CraftPlayer{name=srnyx}"

### Reproduction steps

1. Enable MySQL for LuckPerms
2. Add WorldGuard and WorldGuardExtraFlags
3. Join the server

### Expected behaviour

No error

### Environment details

* Server type/version: `Paper-Spigot-400` running version `1.16.4`
* LuckPerms version: `5.2.7.8`

[https://gist.github.com/srnyx/ea29db92e317140387814dc23289efde](https://gist.github.com/srnyx/ea29db92e317140387814dc23289efde)

### Any other relevant details

N/A

**Comment by srnyx** [comment]
Here is the error: https://gist.github.com/srnyx/b8336658b2e5636555e77376429cc92a

**Comment by Username4723** [comment]
This seems like the same issue as ExtraContexts issues 29, 32, and 34. Are you using the WorldGuardExtraFlags `command-on-entry` or `command-on-exit` flags? I know they can cause issues, but don't know why.

**Comment by srnyx** [comment]
> This seems like the same issue as ExtraContexts issues 29, 32, and 34. Are you using the WorldGuardExtraFlags `command-on-entry` or `command-on-exit` flags? I know they can cause issues, but don't know why.
> 
> EDIT: I haven't tested every flag comprehensively, so other flags may cause the same error.

Not as far as I'm aware

**Comment by lucko** [comment]
This issue belongs on the ExtraContexts repo
