### ISSUE TITLE
Luck Perms Bug

### ISSUE THREAD

**Issue by LegitFusionX** [lucko/LuckPerms#282]
I do /lp it doesn't say anything. I use bungeecord and I also tried putting it in my bungee server folder. I also tried from the console, nothing.

**Comment by mikroskeem** [comment]
There is not enough information.

Also server panels tend to filter out some information, maybe look into `logs/latest.log`?

**Comment by ryanwoods1706** [comment]
That is because your using the bungee cord version and the command is /lpb NOT /lp
