### ISSUE TITLE
LuckPerms causes server to not shutdown fully

### ISSUE THREAD

**Issue by vx888** [lucko/LuckPerms#2820]
### Description

Upon executing the /stop command, the server does not shut down 100%. LuckPerms seems to cause it to hang?

### Reproduction steps

Install LuckPerms and use /stop command /shrug

### Expected behaviour

For the server to stop completely and restart

### Environment details

* Server type/version: `Tuinity` running version `1.16.4` build `8954b61`
* LuckPerms version: `v5.2.76`

Shutdown log: https://gist.github.com/vx888/91dbae6d951a0a17db9541de97ecb29d

### Any other relevant details

 startup / restart script: https://gist.github.com/vx888/beac2c6e8892a365634403d847ffd4cb#file-sh

**Comment by lucko** [comment]
I'm confused.. you say it hangs but the timestamps seem to show that it wasn't waiting at all?

```
[23:06:30] [Server thread/INFO]: [LuckPerms] Disabling LuckPerms v5.2.76
[23:06:30] [Server thread/INFO]: [LuckPerms] Starting shutdown process...
[23:06:30] [Server thread/INFO]: [LuckPerms] Closing storage...

HANGS HERE ^ 

[23:06:30] [Server thread/INFO]: [LuckPerms] Goodbye! <-- CTRL + C 
```

Ideally, I need a thread stack dump taken while it is hanging. You can use the `jps` command to find the PID of the Java process, then use the `jstack -l <pid>` command to generate a dump.

https://docs.oracle.com/en/java/javase/11/tools/jps.html
https://docs.oracle.com/en/java/javase/11/tools/jstack.html

Let me know if you run into any issues doing that :)

**Comment by lucko** [comment]
I suspect this is probably the issue you were experiencing: 2a44572fb2dc7a74307a1b90c48958978245b4c7

Should now be fixed in the latest dev version.
