### ISSUE TITLE
%luckperms_group_expiry_time_<group>% is broken

### ISSUE THREAD

**Issue by JustJP2K** [lucko/LuckPerms#2821]
It breaks if a player has an expiration time of over 3 weeks. once it hits 25 days and above it will start over from 60 hours for some reason.
Meaning at 24 days it says for example: 23d 12h 34m 13s
But as soon as it hits 25 days and over it starts at 60h.

its really odd.

**Comment by Fefo6644** [comment]
Update PAPI to a dev build https://ci.extendedclip.com/job/PlaceholderAPI/
