### ISSUE TITLE
ViaVersion Sponge incompatability

### ISSUE THREAD

**Issue by Willsr71** [lucko/LuckPerms#2822]
### Description
ViaVersion seems to be incompatible with LuckPerms on Sponge. The error is [here](https://gist.github.com/Willsr71/e5b8a171a50f6fee35a96afe98a12c9a). 
I've narrowed this down to [this line in ViaFacet of the LuckPerms adventure platform](https://github.com/lucko/adventure-platform/blob/master/api/src/main/java/net/kyori/adventure/platform/viaversion/ViaFacet.java#L59). The issue appears to stem from LuckPerms loading the class before ViaVersion. The class loaded has a static declaration, [and one of the methods called references it's own plugin](https://github.com/ViaVersion/ViaVersion/blob/692e53427b41f3f564e4e5701c38fa9b7553e7a0/common/src/main/java/us/myles/ViaVersion/api/protocol/ProtocolRegistry.java#L186). LuckPerms manages this just fine, however when ViaVersion ends up loading it promptly fails as a result. I believe this could be solved with using a [different Class.forName method](https://docs.oracle.com/javase/8/docs/api/java/lang/Class.html#forName-java.lang.String-boolean-java.lang.ClassLoader-), however i'm not terribly familiar with Sponge classloading if they do anything weird or the LuckPerms adventure platform.

### Reproduction steps
Use the latest builds of LuckPerms and ViaVersion together on a Sponge server (tested with SpongeVanilla, probably the same on SpongeForge).

### Environment details
SpongeVanilla 1.12.2 API 7.3.0
LuckPerms Sponge 5.2.78 (5.2.76 and some in-between versions also tested)
ViaVersion 3.2.2 (or latest dev 3.3.0, back to 3.2.0 was tested a bit ago)

**Comment by lucko** [comment]
Thanks for the report - as you noted, this issue is actually coming from one of the libraries LP uses, `adventure-platform`.

Would you mind copying your report to the issue tracker here: https://github.com/KyoriPowered/adventure-platform/issues :)

**Comment by lucko** [comment]
Btw, I've added a workaround in LP for until this can be fixed in adventure. Try again using the latest version
