### ISSUE TITLE
Per Track Promote permission.

### ISSUE THREAD

**Issue by ctrieskey** [lucko/LuckPerms#2827]
I can't seem to find documentation for whether or not this is an option, but I'm using LP to create a guild system. I have a track called "guild" with groups "Guild_member," "Guild_builder," and "Guild_leader." I want to give the group "Guild_leader" the permission to promote users only along the "guild" track. I have argument based command permissions enabled, but I can't seem to get the perm to show up for my test subject unless he has permission to promote along every track.

**Comment by BrainStone** [comment]
https://luckperms.net/wiki/Argument-based-command-permissions

**Comment by ctrieskey** [comment]
> https://luckperms.net/wiki/Argument-based-command-permissions

You explained too much in your reply. Try being less helpful next time. Still no documentation on whether Luckperms.user.promote.track is a permission node, or what argument based permissions have to do with that. Good try though.

**Comment by Turbotailz** [comment]
Everyone loves a snarky reply.

Enable the option in the config, then use verbose mode to figure out the rest.

**Comment by ctrieskey** [comment]
> Everyone loves a snarky reply.
> 
> Enable the option in the config, then use verbose mode to figure out the rest.

If somebody is going to post a link with no explanation, they might as well not post at all. Why do developers always reply with as little explanation as possible? Are you actually trying to help? I'll try your suggestion, but my response to BrainStone is justified.

**Comment by benwoo1110** [comment]
tbf, the contents in the link does explain.
![image](https://user-images.githubusercontent.com/30431861/104536516-2ea87b80-5653-11eb-944c-95ba5556f2f7.png)
![image](https://user-images.githubusercontent.com/30431861/104536493-25b7aa00-5653-11eb-940c-e3e6bbe4b0e8.png)
And the if you are unsure if the exact permission, you can also use verbose to check. https://luckperms.net/wiki/Verbose

**Comment by BrainStone** [comment]
That’s the thing about documentation. It requires no further explanation. As it contains all the info you need. 

But it’ll be my pleasure no longer helping you out ☺️

**Comment by ctrieskey** [comment]
Ben where did you find that section in the documentation? Brain, posting a link to a wiki requires explanation on where in the massive article to look. Also you never helped to begin with.

**Comment by Fefo6644** [comment]
The wiki is very well detailed, that article *as a whole* explains argument based permissions and if you were to take your time and read in detail you would know that section is towards the bottom

**Comment by benwoo1110** [comment]
> Ben where did you find that section in the documentation?
In the link brainstone sent.

> Also you never helped to begin with.
Not sure why you are so closed-minded to ppl helping you, but we are all just chipping in to help. Hope you understand. 😄

**Comment by BrainStone** [comment]
Well if around two pages of text is too much to read then you shouldn’t be running a server. Reading documentation is an essential skill for successfully running a server on your own. And it’s quite impressive that you never bothered even scrolling down. Else you would’ve seen it. 

Now if you’ve read the documentation and it you don’t understand something that is fine. Ask for clarification on those parts. But don’t demand for people to regurgitate perfectly fine documentation into bite sized pieces.

**Comment by ctrieskey** [comment]
My apologies on being so hasty and not scrolling down. I don't mean to be rude. It is possible, however, to help without being vague at first, and then scornful. Moreover, the article states that it pertains only to spigot and sponge, which I am not using. The issue is still unresolved. For instance, the node luckperms.user.promote.<track>.* doesnt seem to exist. I cannot use the wildcard to invoke all groups on a track.

**Comment by BrainStone** [comment]
That’s the thing. There’s nothing meaningful for me to add to the link. As it contains all the info you need. 

And I’m not sure where you get the idea from that it only works on Spigot and Sponge. This works for all LP types. 

And lastly make sure you enable the setting that’s mentioned in the very first sentence.

**Comment by benwoo1110** [comment]
> he article states that it pertains only to spigot and sponge, which I am not using.

You didn't fill in the issue template so we can only assume you use the common server types. Tho luckperms permission nodes don't differ between server types so I don't see an issue there.


> For instance, the node luckperms.user.promote..* doesnt seem to exist. 

How do you know it "Doesnt exist", also the permission node its ` luckperms.user.promote.*` not 2 .. Then also note that there is 5 permission nodes to set with different states, some true some false as shown in the table. If you don't understand the table shown, or if you are unsure of the exact permission, you can also use verbose to check. https://luckperms.net/wiki/Verbose

Also CHECK that you have actually enabled argument based in luckperms config.

**Comment by ctrieskey** [comment]
Well if you read my original post, you'll see that that setting is in fact enabled. Also, the article SAYS "for sponge and spigot." Also, it would more appropriate to ask "is that setting correct?" or "did you try this command." That is what beig a helpful person looks like. The double dot was a typo on the post. The node is in red text when I type it.

**Comment by Fefo6644** [comment]
> The node is in red text when I type it.

That is purely client side and has no functional implications, you can wrap your permission in double quotations `"like.so.*"` and it will be yellow fancy.

If you want people to provide help without having to assume things you should follow the issue template.

**Comment by ctrieskey** [comment]
There were no details to assume, as I cleared up those missing details, however I was unaware of the issue template. I'll look at that next time.

**Comment by benwoo1110** [comment]
> The node is in red text when I type it.

Red doesn't mean its invalid, have you actually tried setting all the relevant permission node.



> the article SAYS "for sponge and spigot."

At least say what server type you are using then



> Well if you read my original post, you'll see that that setting is in fact enabled.

Im just asking you to check, didn't say you definitely didn't enable it yet.




> Also, it would more appropriate to ask "is that setting correct?" or "did you try this command."

We gave you links to 2 very detailed page with basically has that. 

Providing more info of what you have tried like commands you ran exactly, server type, screenshot of command output and permission nodes you have try setting. 




> There were no details to assume, as I cleared up those missing details,

I don't even know your server type you are using.

**Comment by ctrieskey** [comment]
Thank you Ben. You have been very patient and understanding. I'll come back to this problem when there are players to test it out. With the knowledge of the autofill suggestion status not being relevant, I should be able to get it taken care of.

**Comment by ctrieskey** [comment]
Alright, so I've used verbose mode to see what nodes are being checked when the command "/lp user name promote track" is run. I have the perms luckperms.uers.promote.modify.others, luckperms.user.promote.track.* set to true, which is all that the wiki says is needed. However, the output of the verbose command shows about 30 perms being checked, all of which seem unrelated to the command I'm trying to run, ones about viewing, clearing users, parents, and permissions. My subject does now get autofill options that he didn't before, but is denied permission when he runs the command. Do I really have to go in and enable 30 or so perms individually? This seems like it would allow people to do things that I don't want them to.

**Comment by benwoo1110** [comment]
Can you set the actual screenshot/links of permissions you set and verbose output? Also is your track named `track`?

**Comment by ctrieskey** [comment]
The names in the commands and nodes that I send here are placeholders. I don't see an option to attach an image to my post.

**Comment by benwoo1110** [comment]
![image](https://user-images.githubusercontent.com/30431861/104673159-210af880-571c-11eb-8212-e105b6105501.png)

**Comment by ctrieskey** [comment]
![2021-01-14_21 23 03](https://user-images.githubusercontent.com/47527794/104673369-9e4c5400-56af-11eb-87dc-951b2702626d.png)
![2021-01-14_21 23 14](https://user-images.githubusercontent.com/47527794/104673371-9ee4ea80-56af-11eb-9675-6afd5a67aaad.png)
![2021-01-14_21 26 33](https://user-images.githubusercontent.com/47527794/104673373-9f7d8100-56af-11eb-9959-d9134fdf7362.png)
![2021-01-14_21 27 03](https://user-images.githubusercontent.com/47527794/104673376-a0161780-56af-11eb-84af-73c71c20652b.png)

Here, angels_leader inherits from faction_leader.

**Comment by benwoo1110** [comment]
![image](https://user-images.githubusercontent.com/30431861/104674280-531d5a00-571e-11eb-80a3-b2881a228a3d.png)

Try add `luckperms.user.promote.usecontext.global` perm node as well. Also for verbose you can do a web upload with `lp verbose record`, then after doing the command `lp verbose upload`

**Comment by ctrieskey** [comment]
Ben, it looks like that one node worked.
