### ISSUE TITLE
import command --replace option description is misleading

### ISSUE THREAD

**Issue by LeotomasMC** [lucko/LuckPerms#2829]
### Description

when you do /lp import, and it tells you what the command does and how to use it, it states that `--replace` "replace existing data instead of merging", which (at least to me) implies that it will replace all permissions data

### Proposed behaviour

there are a few options here
- make the description more clear on what it is
- rename the current option and add a new one that matches the current description
- (better for compatibility) keep the current option as is (with or without description change), add a new option that does replace all existing permissions data (could be `--replaceall` or `--clear` or something)

**Comment by lucko** [comment]
I think it's already pretty clear - when the flag is provided it does replace all data for the groups/users/etc being imported.

If you want to have a completely clean slate then you need to delete the storage first then import after. :)
