### ISSUE TITLE
LuckPerms breaks XenoPanel [Sponge]

### ISSUE THREAD

**Issue by TAnthrax** [lucko/LuckPerms#283]
Hi,
I am setting up a modded server using sponge and luckperms, however when luckperms is installed the panel breaks.
I realize this makes absolutely no sense and am contacting xenopanel as well, but if you have any suggestions let me know.
I am using spongeforge build 2312 and luckperms 3.1.45
![untitled](https://cloud.githubusercontent.com/assets/1207861/25924555/94bc381c-35a0-11e7-981a-37c4a7d18df1.png)

**Comment by lucko** [comment]
Need to see an error message to be able to help. This doesn't look like an issue which could be caused by a plugin.
