### ISSUE TITLE
Checking log history causes error

### ISSUE THREAD

**Issue by baailey** [lucko/LuckPerms#2831]
### Description
When using any of the log history commands, an error will occur in console but will also complete it's expected task

### Reproduction steps
I feel this might be specific to me only but:

1. Do any of these 3 commands - /lp log userhistory/trackhistory/grouphistory [user/track/group]

### Expected behaviour
The log to appear without generating an error in console

### Environment details
Server version: git-Tuinity-"4743c34" (MC: 1.16.4)
LuckPerms version: 5.2.86

### Any other relevant details
The error that appears in console > https://gist.github.com/baailey/5ec959c1bc875a28a71d3c326b819ac6
If I try again after that error sometimes it'll simply spam `java.lang.NullPointerException`

**Comment by lucko** [comment]
You have some malformed data in your actions.txt file.

Easiest way to solve it is probably to just delete it and allow LP to regenerate it.
