### ISSUE TITLE
Database issue

### ISSUE THREAD

**Issue by Tobi-Jakka** [lucko/LuckPerms#2832]
### Description

My /lp editor is very slow & I often get warnings related to the database in my console.

### Reproduction steps

Actually, I am not sure why it happens, so I'll show the console log instead.

### Expected behaviour

It gives me editor link faster & doesnt throw warnings in console.

### Environment details

* Server type/version: `Waterfall / paperspigot (bungee network with 1 waterfall server & 2 paperspigot servers all running luckperms` running version `1.16.4` build `paper version git-Paper-323 (mc: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)` (command was run on 1 of the paperspigot servers)
* LuckPerms version: `v5.2.35`

https://pastebin.com/6RvS5ceF
### Any other relevant details

I don't think bungee is the issue but tbh I don't really know whats wrong, could it be an issue with my database? (I switched recently)

**Comment by lucko** [comment]
https://luckperms.net/wiki/Storage-system-errors#mysql-no-operations-allowed-after-connection-closed-error
