### ISSUE TITLE
LuckPerms database issue after vps reboot

### ISSUE THREAD

**Issue by turboalex21** [lucko/LuckPerms#2833]
I have connected LuckPerms to a MySql, and at first it connected fine, but when I reboot in the vps, it gives me an error.
MySql is started, i can login and manage it.

Error: https://pastebin.com/ERiUeFR9
Config: https://pastebin.com/SThjjNen
Database: https://gyazo.com/43adf9dbf233d02463171ee117ad1a30

**Comment by x9nico** [comment]
Hello, it's normal.
It removes the connection to DB when you are restarting your server.
You have to connect it with apache2/nginx (depending what you have).

**Comment by turboalex21** [comment]
> Hello, your MySQL server is active?

Yes

**Comment by x9nico** [comment]
You didn't defined password in config:

  password: 'passwordhere'

**Comment by lucko** [comment]
"Connection refused" error

Could be wrong password, bad firewall config, bad MySQL server config....

https://luckperms.net/wiki/Storage-system-errors

but nothing to do with LuckPerms. :)
