### ISSUE TITLE
Fabric Servers not loading user data

### ISSUE THREAD

**Issue by MaximumMaxxx** [lucko/LuckPerms#2835]
### Description
When joining a fabric server on a Bungeecord network user data doesn't load but also doesn't have any errors

### Reproduction steps

1. Have a bungeecord network with at least 1 fabric server
2. have everything configured to run on a MySQL database.
3. log into server and connect to the fabric world

### Environment details

* Server type/version: `Spigot` running version `1.8.8`
* LuckPerms version: `v5.2.9`

https://gist.github.com/MaximumMaxxx/c0197da9d18e8a1135e37674453079ec
https://gist.github.com/MaximumMaxxx/431a63a90c425f368156cd818d4a06de

**Comment by lucko** [comment]
Seems to be an incompatibility somewhere, the pre-login event listener doesn't seem to be being triggered.

Please make sure you are using an up-to-date version of Fabric API and FabricProxy.
