### ISSUE TITLE
Verbose stops recording/reporting checks

### ISSUE THREAD

**Issue by Fefo6644** [lucko/LuckPerms#2838]
### Description

Verbose logging on fabric stops working completely all of a sudden after some arbitrary amount of time, in the order of seconds to minutes.

### Reproduction steps

1. Install LP on fabric and enable verbose.
2. Wait for some arbitrary amount of time and do things that require permissions, no results yield.

### Expected behaviour

Well it should keep reporting :full_moon_with_face:

### Environment details

* Server type/version: `fabric@0.29.4+1.16` - `fabric-api@0.2.0+daa38b3d7d`
* LuckPerms version: `v5.2.90`

### Any other relevant details

Just an example, the first `//wand` reported fine, I waited a few minutes and it stopped working.

![image](https://user-images.githubusercontent.com/35617540/105126291-2752f900-5abd-11eb-9051-56205b085c22.png)

Sadly there aren't as many details I'd like to have in hand to report this other than "it doesn't work" :smile: but it happens with <i>any</i> check, including LP's own checks (most noticeably tab completion since it happens as you type).

This issue seems to be fabric specific, I can't seem to repro on any other platform (I have access to).

**Comment by lucko** [comment]
Thanks for reporting :)
