### ISSUE TITLE
DynmapForge not working with LuckPerms

### ISSUE THREAD

**Issue by AtaxiaGames-GM** [lucko/LuckPerms#284]
I have installed SpongeForgeAPI 5,  LuckPerms, and DynmapForge on a MC 1.10.2 server. Unfortunately, not even a group or user set with all (*) permissions can use Dynmap commands as the user is told that they don't have permissions to use them.

**Comment by lucko** [comment]
Use the verbose command to check which permission is required by the commands.

**Comment by thefirstgamemaster** [comment]
It is calling for "dynmap.command.dmarker" and "dynmap.command.dynmap" for the commands that I want to use, but I am part of a group that has permission * set to true. Isn't that supposed to take care of that? I haven't had any problems with any other permissions with exception to this on. <confused>

**Comment by thefirstgamemaster** [comment]
I just used "/lp user set <username> permission set dynmap.command.dynmap true" and "/lp ... dynmap.command.dmarker true" also, just to see if it would work, but it did not.

**Comment by liach** [comment]
probably the forge mod lacks such permission support.

**Comment by lucko** [comment]
Again, please can you check with [/lp verbose](https://github.com/lucko/LuckPerms/wiki/Verbose) to see if that node is *actually* being checked for.

**Comment by AtaxiaGames-GM** [comment]
Okay. I suppose that I should have included a screenshot with my last entry, as "it is calling for" was referring to /lp verbose. This time I have included a screenshot for clarity.
![2017-05-12_05 20 28](https://cloud.githubusercontent.com/assets/16582333/25970341/3eacd1d2-36d3-11e7-822a-cb286bd6ec68.png)

**Comment by lucko** [comment]
Ok yeah, since those logs are showing a result for `TRUE` is being returned, then this is definitely a mod issue. :/

**Comment by YorVeX** [comment]
Why was this closed? I got exactly the same problem. So my only option is to move over to a different permission plugin?

**Comment by donkeymonkey1** [comment]
Cause it's mod issue?

**Comment by YorVeX** [comment]
And that means what?

**Comment by lucko** [comment]
Dynmap

**Comment by YorVeX** [comment]
OK thanks.

**Comment by smmmadden** [comment]
FWIW @YorVeX , Dynmap-3.0-alpha-1-forge-1.12.2 and LuckPerms-Sponge-4.1.30 work perfectly with each other on Sponge Forge API 7.1.0-BETA-2958 and Forge 1.12.2-14.23.2.2615.  So it doesn't surprise me that 1.10.2 is having issues. :-)  You may find an [updated version](http://dynmap.us/builds/DynmapForge/) of Dynmap that may fix your issue for 1.10.2.

**Comment by YorVeX** [comment]
@smmmadden I am already on 1.12.2 but I was using Dynmap-2.6-beta-1-forge-1.12.jar so far, didn't even know that a 3.0 alpha existed. Was checking before posting here whether there is a newer version and didn't find this one. Will try the combination of versions you have mentioned now.

**Comment by YorVeX** [comment]
I didn't find LuckPerms-Sponge-4.1.30 for download anywhere. I the one I had (43) for testing and tried both the other versions you mentioned and newer versions of these components. In detail I tried these two combinations:

- Dynmap-3.0-alpha-1-forge-1.12.2 + LuckPerms-Sponge-4.1.43 + Sponge Forge API 7.1.0-BETA-2958 + Forge 1.12.2-14.23.2.2615
- Dynmap-3.0-alpha-1-forge-1.12.2 + LuckPerms-Sponge-4.1.43 + Sponge Forge API 7.1.0-BETA-2970 + Forge 1.12.2-14.23.2.2635

Result is the same for both combinations:

![image](https://user-images.githubusercontent.com/528974/37876214-816f0862-3049-11e8-9f44-741b6dbe122b.png)

Maybe when you tried you were op on your server? Because it works when I am op. But I want to give that permission to someone without having to give him op. Or it's the older LP version that you are using which is making the difference (which I doubt).

**Comment by lucko** [comment]
This is a Dynmap issue and has nothing to do with LuckPerms.

DynmapForge supports two ways of checking for permissions. You can choose between using the file based internal permission system, or just checking if the user is op.

https://github.com/webbukkit/DynmapForge/tree/master/src/main/java/org/dynmap/forge/permissions

There's nothing I can do about that. You need to ask the author of Dynmap to add support for proper permission checks.

**Comment by YorVeX** [comment]
Posted an issue there. In the meantime I am using the file based permissions, it's working now. For anyone else finding this post and wondering how they can set marker permissions in DynmapForge I posted an example of a permissions.yml file here that has to be placed on the /dynmap folder on the server: https://pastebin.com/M1VADY7u

**Comment by smmmadden** [comment]
3 variables that are different in my scenario.

1. I am an admin
2. I am OP level 4
3. I do NOT allow any dynmap commands for players. The map is provided as a courtesy, not as a feature that can be manipulated.
So if the dmarker perms do not work in the release you are testing with, report it to the Dynmap Team.

**Comment by liach** [comment]
@smmmadden If your case is different, you should rather open a new issue.

**Comment by smmmadden** [comment]
i'm not reporting any issue, merely replying to @YorVeX - everything is working fine for my setup.
