### ISSUE TITLE
Data too long for column 'permission' at row 1

### ISSUE THREAD

**Issue by MinecraftAdmin** [lucko/LuckPerms#2840]
### Description
I am trying to insert `"meta.rankintab.&c[[color=#FF4400]&lL[color=#FF5F01]&lE[color=#FF7A02]&lA[color=#FF9603]&lD[color=#FFB104]&l-[color=#FFCD05]&lA[color=#FFB104]&lD[color=#FF9603]&lM[color=#FF7A02]&lI[color=#FF5F01]&lN&c]&f &r"` as a permission but am hit with a `Data too long for column 'permission' at row 1` error in the logs.

This is so I can use `%luckperms_meta_rankintab%` placeholder in RGB compatible plugins.

### Reproduction steps
Command `/perm group staff4 permission set "meta.rankintab.&c[[color=#FF4400]&lL[color=#FF5F01]&lE[color=#FF7A02]&lA[color=#FF9603]&lD[color=#FFB104]&l-[color=#FFCD05]&lA[color=#FFB104]&lD[color=#FF9603]&lM[color=#FF7A02]&lI[color=#FF5F01]&lN&c]&f &r"`

* Server type/version: `Purpur` running version `1.16.4` build `956`
* LuckPerms version: `5.2.44`

### Error
`[RAW] java.util.concurrent.ExecutionException: java.sql.BatchUpdateException: Data truncation: Data too long for column 'permission' at row 1`

**Comment by lucko** [comment]
The default length limit for permissions is 200 characters.

If you want to insert anything longer than that, then you'll need to go into your DB and increase the length of the column. :)
