### ISSUE TITLE
Only getting back Version information when trying to execute any luckperms command in the console (Fabric)

### ISSUE THREAD

**Issue by Paul42812** [lucko/LuckPerms#2841]
### Description

Only getting back version information When trying to execute any luckperms command in the console (Fabric)

### Reproduction steps

1. Install the Fabric Loader, API and Luckperms.
2. Start the Server
3. Try to give a User `luckperms.*` by executing `lp user Paul_42812 permission set luckperms.* true` in the Console.
4. Get `[LP] Running LuckPerms v5.2.91.` back.

### Expected behaviour

Permissions are not updated and `[LP] Running LuckPerms v5.2.91.` is returned.

### Environment details

* Linux manjaro 5.9.16-1-MANJARO #1 SMP PREEMPT Mon Dec 21 22:00:46 UTC 2020 x86_64 GNU/Linux
* Fabric API 0.29.4
* LuckPerms v5.2.91
* openjdk version "15.0.1" 2020-10-20

**Comment by andrewkm** [comment]
Same issue here on bukkit.

**Comment by lucko** [comment]
Thanks for reporting, should be sorted :)
