### ISSUE TITLE
Tables not being created when loading plugin on MySQL database.

### ISSUE THREAD

**Issue by UltimateWafflee** [lucko/LuckPerms#2842]
### Description

When I start my server I get this error:
`java.util.concurrent.CompletionException: java.sql.SQLSyntaxErrorException: Table 'permscv.luckperms_groups' doesn't exist`
I have the latest version of LP and I have tried making new of everything but it doesn't work. I have figured out that its not actually creating the table in the DataBase so it isn't finding it.

### Reproduction steps

1. Put your database credits in config.yml
2. Restart the server
3. See error
4. If you want to further make sure that its not actually creating the tables then you can go to you MySQL Command Line Client and type `show tables;` and it will show you that only `luckperms_messenger` has been created.

### Environment details

* Server type/version: `PaperMC` running version `1.16.4` build `415`
* LuckPerms version: `v5.2.92`

Full LP startup log: https://bytebin.lucko.me/s39CuTJIoh

**Comment by lucko** [comment]
Try stopping your server, then dropping all LP tables, then starting it again.

If that doesn't fix it, then it's most likely an issue with your database server. The first thing I would check is that the MySQL user has the right privileges assigned to create tables, etc.
