### ISSUE TITLE
Blank Log Notifications

### ISSUE THREAD

**Issue by bennycio** [lucko/LuckPerms#2843]
### Description

All in game log notifications are showing up as blank lines, and when a permission edit is made the line will start with either a plus or a minus depending on if a permission was added or removed but the rest of the line is completely blank. The notifcations do however show up in the console normally

### Reproduction steps

1. Use /lp applyedits or any /lp command that edits permissions or groups or have anyone else use a command that you should be notified about

### Expected behaviour

A chat notification of exactly what was changed after a command. 

### Environment details

* Server type/version: Paper-414 for MC 1.16.4
* LuckPerms version: 5.2.76

**Comment by Fefo6644** [comment]
What client are you using?

**Comment by bennycio** [comment]
> What client are you using? 

Well that solves it, I feel quite stupid now. Thanks for the help!
