### ISSUE TITLE
Issues uploading my backup file (Json file ext)

### ISSUE THREAD

**Issue by Damox** [lucko/LuckPerms#2844]
When I attempt to upload a json abckup i did of my previous luckperms config, it says it is unable to fidn the file. The minecraft output seems to shorten the location fo the directory it is searching against, but I have made sure that this file is available in /server/luckperms and /server/config/luckperms
The command I am using is 
lp import file.json
lp import file.json [--upload]
lp import <file.json>
lp import <file.json> [--upload]
The issue it seems is that it cannot fidn the file itself. I am using Spongeforge Sponge 7.3, MC 12.2
Any help is greatly appreciated.

**Comment by BomBardyGamer** [comment]
I believe the output should be a json.gz file, that can then be imported with `/lp import filename` (providing it's in the LuckPerms plugin folder, plugins/LuckPerms)

**Comment by Damox** [comment]
It was - Fefo on discord ended up helping me. I was using the gz extension as well, but it turned out, the import method was case sensitive, and I had an intial capped letter. Fefo resolved this for me. Thank you very much for your insanely fast response, and thank you for having such an amazing community.
