### ISSUE TITLE
My command /lp kicks me from my server

### ISSUE THREAD

**Issue by haloslayser** [lucko/LuckPerms#2845]
### Description

I have recently set up my server with bungee cord and now when i do the command /lp then a space in my main server it kicks me to my hub 

### Expected behaviour

I expected to do /lp editor but i am not able to do a space after the command due to the server kicking me to the hub

### Environment details

* Server type/version: `PaperMc` running version `1.16.4 + with viaversion` build `???`
* LuckPerms version: `Bukkit`

### Any other relevant details

This is also happening with /br, //br and /brush with my other plugins

**Comment by BomBardyGamer** [comment]
This doesn't seem like a LuckPerms issue, especially if it's happening with other plugins' commands.

**Comment by LeotomasMC** [comment]
I would agree that this likely isn't a luckperms issue, however I would suggest looking at the console of the server you get kicked from to see if its kicking you for spam. That can happen on pre-1.13 servers when using viaversion or protocolsupport as those plugins translate chat tab events to an event that counts as spam, although i am not sure why it would be happening on 1.16.4. I would also suggest updating to 1.16.5 (1.16.4 and 1.16.5 use the same protocol version btw, and are 100% compatible with each other for some reason, so unless you have viaversion to allow 1.16-1.16.3 users to join your 1.16.4/1.16.5 server, you may want to get rid of it)
