### ISSUE TITLE
the bug with death

### ISSUE THREAD

**Issue by Destroyer4ik** [lucko/LuckPerms#2846]
There was such a problem. After death-the player loses all the roles, he can not write to the chat, etc. After the relog - it returns all the rights. What to do? Server version 1.16.4, Mohist core, LuckPerms version 5.2.92

**Comment by Remering** [comment]
I also met this issue, do others have a way to solve it? Thanks a lot

**Comment by lucko** [comment]
This is an issue with Mohist not copying permissions when a player respawns - nothing to do with LuckPerms.
