### ISSUE TITLE
What is the problem?

### ISSUE THREAD

**Issue by Juiceqad** [lucko/LuckPerms#2848]
![image](https://user-images.githubusercontent.com/61871941/105667744-b2892000-5efd-11eb-81d7-0c0329024c97.png)

**Comment by Aberdeener** [comment]
Impossible for anyone to know.
Did you read the error?
It tells you to check console for errors.
So, check the console for errors and upload the whole logs/latest.log to pastebin

**Comment by Turbotailz** [comment]
> If you are a server admin, please check the console for any errors

You should really learn to read console logs

**Comment by Tsoccerguy3** [comment]
I'd have to agree , The latest builds are not right . If a player logs off while in the air , they get kicked when logging back on , contrary to setting allow flight in survival . I just became aware of this . I think it started with last weeks builds . When I have time I can look into it some more.

[16:45:35] [Server thread/WARN]: maelnelson was kicked for floating too long!
[16:45:35] [Server thread/INFO]: maelnelson lost connection: Flying is not enabled

**Comment by underscore11code** [comment]
@Tsoccerguy3 How is that a LuckPerms issue?
