### ISSUE TITLE
Luckperms Editor Link Doesn't work

### ISSUE THREAD

**Issue by typecek123** [lucko/LuckPerms#2849]
### Description

When I do lp editor (in game or in console) it says "[LP] Preparing a new editor session, please wait...
[08:15:05 INFO]: [LP] Click the link below to open the editor:" and no link shows up.

### Reproduction steps

1. Open the config.yml file and set example to true.
2. Restart the server
3. Run /lp user example permission set x from the console

### Expected behaviour

Please help me solve it this problem, I want to use LP Web Editor.

### Environment details

* Server type/version: `ExampleSpigot` running version `1.12.2` build `???`
 Paper version git-Paper-443 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
* LuckPerms version: `v???`
 Running LuckPerms v5.2.92

Config:
https://pastebin.com/qSiXqZxJ
Latest log:
https://pastebin.com/0VSfeUAK

![2021-01-24_23 26 38](https://user-images.githubusercontent.com/74290177/105673467-641c5700-5ee6-11eb-89aa-6fed0d9f2ef9.png)

### Any other relevant details

Maybe this happened after I connected it to MySQL

**Comment by benwoo1110** [comment]
Can you check that the computer running your mc server can access https://bytebin.lucko.me/

**Comment by typecek123** [comment]
I have hosting, how can I check that?

**Comment by typecek123** [comment]
Config: https://bytebin.lucko.me/Q8Z3FJLf0p

**Comment by benwoo1110** [comment]
> I have server on hosting, how can I check that?

Contact your server host to ask...?

**Comment by typecek123** [comment]
okay, I will
