### ISSUE TITLE
Implement LuckPerms for MinecraftForge

### ISSUE THREAD

**Issue by CKATEPTb** [lucko/LuckPerms#2852]
GIT - https://github.com/MinecraftForge/MinecraftForge.
Permission API - https://github.com/MinecraftForge/MinecraftForge/blob/1.16.x/src/main/java/net/minecraftforge/server/permission/PermissionAPI.java
Example permissions hook for command (with mixin) - 
```
@Mixin(CommandSource.class)
public class MixinCommandSource {
    @Final
    @Shadow
    private ICommandSource source;

    @Inject(method = "hasPermissionLevel", at = @At(value = "HEAD"), cancellable = true)
    public void onHasPermissionLevel(int level, CallbackInfoReturnable<Boolean> callbackInfo) {
        if (this.source instanceof PlayerEntity) {
        //TODO
```

**Comment by lucko** [comment]
Hey, my suggestion for people wanting to use permissions on Forge servers is to install Sponge. :)

**Comment by CKATEPTb** [comment]
> Hey, my suggestion for people wanting to use permissions on Forge servers is to install Sponge. :)

At the moment, it does not support versions higher than 1.13, and in addition to advantages it has disadvantages. For example, in real tests, forge will withstand more online than spongeforge

**Comment by WOLFI3654** [comment]
> Hey, my suggestion for people wanting to use permissions on Forge servers is to install Sponge. :)

SpongeForge brings a few issues with it. There are communities out there that are looking forwards a forge only server and simply do not use sponge.
