### ISSUE TITLE
Editing group's properties in web editor.

### ISSUE THREAD

**Issue by SkillzGamingYT** [lucko/LuckPerms#2854]
### Description

In the web editor (https://luckperms.net/editor), you are not able to edit group non-permission based properties such as Display name, Parent, Weight, Prefix, Suffix. You should be able to.

**Comment by Fefo6644** [comment]
You absolutely can! Just not in a "regular" way; they are sort of like permissions and they are explained and shown here https://luckperms.net/wiki/Web-Editor under "LuckPerms Nodes"

**Comment by Fefo6644** [comment]
(also this would be more suitable for the lucko/LuckPermsWeb repo :p)

**Comment by SkillzGamingYT** [comment]
> 
> 
> You absolutely can! Just not in a "regular" way; they are sort of like permissions and they are explained and shown here https://luckperms.net/wiki/Web-Editor under "LuckPerms Nodes"

I didn't know that. Thanks.
