### ISSUE TITLE
User Data Not Loaded During The Pre Login Stage

### ISSUE THREAD

**Issue by MaximumMaxxx** [lucko/LuckPerms#2855]
### Description

I know I submitted this before but I'm very confident it's either luckperms or fabric poxy being broken here

### Reproduction steps

1. Have a bungeecord and fabric server 
2. Using MYSQL as storage type join the fabric server
3. be sad

### Environment details

Fabric Running Latest Build, Fabric Api Latest Build, Fabric Proxy latest buildLuckPerms version: v5.2.92

https://gist.github.com/MaximumMaxxx/27c1f7f25dd9d8c84643b77cbd3e6716 Bungeecord Log
https://gist.github.com/MaximumMaxxx/9d38897d0d784024f2dcd80dd734e151 Server Log
https://gist.github.com/MaximumMaxxx/016695eb56c062e1c9dd764ef5b6f96a Server.properties
https://gist.github.com/MaximumMaxxx/76eab24ad3946c6049d16c32874b1332 luckperms config(fabric server)
https://gist.github.com/MaximumMaxxx/4810a9389de6fbb356a27a7d68dafab8 Luckperms Config(Bugeecord)

### Any other relevant details

Changing Online mode doesn't do anything

**Comment by lucko** [comment]
Well.. I already told you what the problem is:

https://github.com/lucko/LuckPerms/issues/2835#issuecomment-764615885

This isn't a LuckPerms issue - the event simply is not being called.
