### ISSUE TITLE
No way to add all permissions.

### ISSUE THREAD

**Issue by MrKippo** [lucko/LuckPerms#2856]
Hi,

I've just switched over from group manager to Luck since groupmanager breaks all the time, and I wanted to add all permissions to the Owner rank, since in its default state with op, it blocks a bunch of permissions. In groupmanager I used to be able to put the '*' permissions, but there doesnt seem to be something like that in Luck, is there any solution for this?

**Comment by Fefo6644** [comment]
You can use the same `*`, it's a global wildcard.
