### ISSUE TITLE
WebEditor changes do not fire NodeMutateEvent, NodeAddEvent and NodeRemoveEvent

### ISSUE THREAD

**Issue by SaltyAimbOtter** [lucko/LuckPerms#2857]
### Description
The `NodeMutateEvent` , `NodeAddEvent` and the `NodeRemoveEvent` are only fired when the Nodes are changed using in-game commands. All editor changes are ignored.

### Reproduction steps

1. Register listeners for `NodeMutateEvent`, `NodeAddEvent` and the `NodeRemoveEvent`.
2. Make them print a debug message.
3. Compile plugin and put it on the server.
4. Run `/lp user <name> permission set <somePermission>` -> See debug message
5. Do the same thing from the editor
6. Save editor changes using command   -> There is no debug message / The listeners are not getting called.

### Expected behaviour
I would expect the `NodeMutateEvent` , `NodeAddEvent` and the `NodeRemoveEvent` to reflect any change to the Nodes state, not depending on which service changed them.

### Environment details

* Server type/version: `Paper` running version `1.16.5` `git-Paper-372`
* LuckPerms version: `v5.2.92`

**Comment by lucko** [comment]
Thanks for the detailed report! This should be fixed by the above commit :)
