### ISSUE TITLE
Getting permissions from previous group(s)...

### ISSUE THREAD

**Issue by lowheartrate** [lucko/LuckPerms#286]
I am running Minecraft server _(version 1.11.2)_ and have tried multiple times to _/lp creategroup_ and _addsuffix_ / _addprefix_ to that group. When adding myself to the group using _/lp user <username> parent set <groupname>_. After adding myself to group and typing in chat though, nothing appears before / after my name. Not exactly sure what I am missing, [Here is a list of the plugins that I am currently running on my server](https://puu.sh/vQghr/9dc696764a.png).

**Comment by colmagi** [comment]
The same thing happened to me, but that was because I forgot to install vault. Try checking to see if vault is installed correctly.

**Comment by lowheartrate** [comment]
@colmagi I installed Vault after _Essentials Chat_ & _Luck Perms_. I don't think when I install it really made a difference though as I tried to restart the server and create the group(s) with the prefixes and suffix's again afterwards and got the same result.

**Comment by colmagi** [comment]
Maybe try using another chat plugin? I use ChatEX and it works fine.

**Comment by PiggyPiglet** [comment]
I'd remove essentials anti build and essentials protect because they're 99% useless. As for chat, is that essentials or essentialsx? If essentials, I highly suggest changing to essentialsx.

**Comment by lowheartrate** [comment]
@PiggyPiglet Thanks, Using the latest build of _Essentials X_ got it working for me! I can't seem to find it but is there an in-game command to use for the groups so lets say I have two groups with the following permissions each:

- Guest
  - essentials.kit
  - essentials.kits.guest
- Member
  - essentials.kits.member

I am looking for a command that will make it so when I use `/lp user <username> parent set member` the user will not only get the permissions from Member but they will get the permissions from the previous group as well _(Guest)_. Currently I am having an issue where I will _parent set_ a user to the next group and they don't have any permissions from the previous group. As I am sure you can imagine it will be much harder task to repeat all of the permissions from the previous group into the next one _(Especially when it comes to the point where I have 5+ groups on the server)_.
