### ISSUE TITLE
Can't Give all permissions to owner/op

### ISSUE THREAD

**Issue by MrKippo** [lucko/LuckPerms#2866]
Hi, I made a post here a while back asking about adding the * perm to my server. It doesn't seem to work and I've tried all of the main options, I've tried * and then the following ones too: *.* '*'.  and none of them seem to work. I'm running a 1.8.9 server which your plugin page says is supported, but me and the other owners are trying to do things after switching over from essentials, but we're constantly being blocked by LP saying we dont have permission, how do I fix this?

**Comment by speed-MikeM** [comment]
What happens if you specifically include the permissions for essentials as: `essentials.*` as additional line?
I am running the latest MC server and it works fine for me setting: `*` with value: true

**Comment by MrKippo** [comment]
When I do it for specific plugins, it works, but the wildcard * doesnt work on 1.8.9 which is the version of one of our prominent servers. It seems to work on newer version but not on 1.8

**Comment by Fefo6644** [comment]
Paste your LuckPerms config in https://bytebin.lucko.me/ and send the link over.

What LuckPerms version? ("latest" is not a version).

Any errors on console?

What server software are you running?

Basic debugging information 👏

**Comment by Turbotailz** [comment]
Please consider using the issue template next time...
