### ISSUE TITLE
Placeholder time is not parsed properly

### ISSUE THREAD

**Issue by piotrskibapl** [lucko/LuckPerms#2870]
### Description

All placeholders that return an amount of time are not parsed correctly - the amount of hours is often greater than or equal to 24. For example, when I run the `/papi parse USER %luckperms_group_expiry_time_GROUP%`, I get values like "5d 36h 1m 23s".

### Reproduction steps

1. Run `/lp user USER permission settemp test.test true 1d2h`
2. Run `/papi parse USER %luckperms_expiry_time_test.test%`
4. See the returned value - you should see something like `1d 25h 59m 58s`

### Expected behaviour

The returned value should be properly parsed.

### Environment details

* Server type/version: `Paper` running version `1.16.4` build `388`
* LuckPerms version: `v5.2.96`

### Any other relevant details

I am using the PlaceholderAPI plugin (v 2.10.9) for placeholders.

**Comment by Fefo6644** [comment]
Update PAPI to a dev build https://ci.extendedclip.com/job/PlaceholderAPI/

**Comment by piotrskibapl** [comment]
Works well on the latest dev build. Thanks!
