### ISSUE TITLE
[Close] Problem mysql

### ISSUE THREAD

**Issue by KyneasSurYoutube** [lucko/LuckPerms#2872]
### Description

**Quite simply, once two servers are connected to the same database (for luckperms only), the console will spam the error: `me.lucko.luckperms.lib.hikari.pool.PoolBase - luckperms-hikari - Failed to validate connection me.lucko.luckperms.lib.mysql.cj.jdbc.ConnectionImpl@(No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value`.**

### Reproduction steps

**1. Have a Bungeecord server and a Spigot server
2. Put Luckperms on both servers (Bungee version for Bungeecord, and spigot for Spigot)
3. Configure the database for the two servers (the same database) with a different server name
4. Start both servers**

### Expected behaviour

**No error message**

### Environment details

Bungee:
* Server type/version: `Bungeecord` running version `1.16.4` build `???`
* LuckPerms version: `v5.2.76`
Spigot:
* Server type/version: `Spigot` running version `1.16.4` build `???`
* LuckPerms version: `v5.2.76`

**Comment by Laarryy** [comment]
Take a look at https://luckperms.net/wiki/Storage-system-errors#mysql-no-operations-allowed-after-connection-closed-error for a detailed look at your problem and potential solutions.

Also, make sure to update to latest LP at https://luckperms.net/

**Comment by KyneasSurYoutube** [comment]
Hello, after the change of the database, the problem seems **resolved** ...
I hope at least. Thank you very much for your help, I had already watched this article, and it had not worked, and everything is up to date.
