### ISSUE TITLE
Luckperms Fabric Permission List

### ISSUE THREAD

**Issue by dillonbarnes** [lucko/LuckPerms#2875]
### Description

Luckperms does not autofill the commands in the editor.

### Reproduction steps

1. Create a Fabric server
2. Put luckperms in the mods folder(with Fabric API)
3. Restart
4. Do /lp editor and have a look.

### Expected behaviour

I expected there to be a list of available commands.

### Environment details

* Server type/version: `Fabric` running version `1.16.5` latest.
* LuckPerms version: `1.16.4`

### Any other relevant details

Here is a currently active link. [https://luckperms.net/editor/RhWQhgc9X3](https://luckperms.net/editor/RhWQhgc9X3)
It might not be active when this is read though

**Comment by lucko** [comment]
The permissions list is populated as permission checks run - bear in mind also for Fabric that not all commands have permission checks implemented (in fact, the majority do not at the moment)
