### ISSUE TITLE
add Support for WaterdogPE

### ISSUE THREAD

**Issue by Superzock3003** [lucko/LuckPerms#2876]
### Description

Can you please add support for WaterdogPE (https://github.com/WaterdogPE)? It's an new version of waterdog with a new API.

**Comment by BomBardyGamer** [comment]
You're free to do this yourself if you want, though I don't know if @lucko has any intention of maintaining support for this.

**Comment by lucko** [comment]
Doesn't seem like there's a permissions API that LuckPerms can hook into yet.

That aside, I'm also reluctant to add support for more platforms (officially) until they've proven to be stable / popular. Perhaps we can revisit this later once Waterdog has matured a bit :)
