### ISSUE TITLE
BUG placeholders %luckperms_group_expiry_time_<groupname>% after 25d

### ISSUE THREAD

**Issue by SnaiilGaming** [lucko/LuckPerms#2878]
### Description
When the tempgroup is >25 days the placeholders %luckperms_group_expiry_time_<groupname>% doesn't work, I don't have 24d etc ... I have something like 59h etc ...

We have a big problem with the placeholders bcs if the tempgroup is 24days I have 23d **35H** etc ...

* Server type/version: `PaperSpigot 1.8.8`
* LuckPerms version: `v5.2.77`

**Comment by Fefo6644** [comment]
Update PAPI to a dev build https://ci.extendedclip.com/job/PlaceholderAPI/
