### ISSUE TITLE
Add placeholder support for meta keys

### ISSUE THREAD

**Issue by JustJP2K** [lucko/LuckPerms#2879]
Basically where you can tell the meta key that they are dealing with a placeholder so it can get parsed correctly and not into text.

example: lp prefix.

so something like meta.prefix.%luckperms_prefix%

That way you get a return of the actual prefix and not just pure text form.

I am aware that this would be stupid for this example. i simply used it as a simple explanation.

It would be useful if you are using custom placeholders and want to use multiple at the same time to where the meta keys would be useful.

**Comment by lucko** [comment]
I think this sort of behaviour would be better handled by the placeholder plugin itself. ("recursive" placeholder resolution I suppose is what you'd call it)
