### ISSUE TITLE
Fabric mod confict with Chunky

### ISSUE THREAD

**Issue by Nidre** [lucko/LuckPerms#2880]
### Description
Fabric server 1.16.5 don`t start with Chunky and LuckyPerms.

### Environment details

* Server type/version: `Fabric 1.16.5 (loader 0.11.1)`
* LuckPerms version: `v5.2.104`

### Log
[2021-02-07-5.log](https://github.com/lucko/LuckPerms/files/5939575/2021-02-07-5.log)

**Comment by lucko** [comment]
I'm not sure why you think Chunky is the issue..?

Strange error though, to be honest I'm not sure why it's happening. Try updating to the latest Fabric/FabricAPI maybe?

**Comment by Nidre** [comment]
Tested with 3 mods
fabric-api-0.30.0-1.16
Chunky-1.2.29
LuckPerms-Fabric-5.2.104

Got it 
[latest.log](https://github.com/lucko/LuckPerms/files/5959460/latest.log)

When i delete one of mod, LuckPerms or Chunky server start successfully.

**Comment by Nidre** [comment]
At the moment I really have no idea how to do this without breaking the "one-class" structure.

**Comment by dimon7147** [comment]
The same with LuckPerms 5.3.3. Chunky's author says this is a LuckPerms issue (https://github.com/pop4959/Chunky/issues/72)

**Comment by pop4959** [comment]
I want to clarify that I do not mean to assign blame here - it is entirely possible that this is not a problem in either mod. When I looked into this issue on my side, I could not find any conflicting classes. However, I was able to confirm that this only occurs when both mods are installed.

For the time being, a suitable workaround is to install Chunky and pre-generate your world, and then remove it before installing LuckPerms. Obviously less than ideal, but there isn't a suitable alternative until Luck or myself has time to dig into this more.

**Comment by lucko** [comment]
The fix is to explicitly define `archivesBaseName` on multi-module projects.

Both LuckPerms & Chunky were not doing this - and both called their Fabric module `fabric`, resulting in a conflict at runtime due to the name of the Mixin refmap file.

This should be fixed in the latest versions of each :)
