### ISSUE TITLE
User meta issue, again

### ISSUE THREAD

**Issue by ItsMacs** [lucko/LuckPerms#2884]
Hello,

it's me again!
I have a problem that makes user get their group's meta (prefixes and such) when they get set to another group.

Since last time, the problem seemed to vanish by itself, however yesterday it returned.

When we ran the command /lp user USER parent set GROUP, we observed the user got the group meta set as their own.

We tried completely deleting everything from LuckPerms - groups, tracks, users, everything, but to no effect.

The new groups suffer from the same bug.

We tried isolating LuckPerms in an empty server, but nothing, still the same bug.

I don't know what to do at this point, I really don't want to switch to another plugin but this bug is really a gamechanger.

I'm running the latest Spigot version of LuckPerms (even though we tried changing versions too, but to no effect whatsoever) with a YAPFA (PaperSpigot) 1.15.2 server.

**Comment by ItsMacs** [comment]
bump

**Comment by Laarryy** [comment]
Hello! 
1. You don't need to bump issues - they will be addressed when possible if the template requested is filled out correctly.
2. Please fill out the template requested as asked in a new issue, with specific version number details as requested, and close this one.
