### ISSUE TITLE
False contexts

### ISSUE THREAD

**Issue by TKDKid1000** [lucko/LuckPerms#2885]
### Description

Maybe if there was a way to make a context work only when it is FALSE.

### Proposed behaviour

Some might want a person to have a certain group on every world/server except one. I've needed this multiple times recently. Something like `world=!worldname`.

**Comment by lucko** [comment]
Unfortunately, this sort of thing isn't possible to implement given the way the system works currently.

In the meantime, I suggest you define/use your own static contexts, or just set a false override in the world you don't want the permission to apply in.

e.g.
```
# apply 'some.thing' in all worlds except the nether
/lp group default permission set some.thing true
/lp group default permission set some.thing false world=nether
```
