### ISSUE TITLE
Warning messages (error) / connection problems

### ISSUE THREAD

**Issue by Hazugg** [lucko/LuckPerms#2886]
Hello,

I would like to report a problem that I almost always have with the plugin.

I start to get these types of warnings that are errors that are generated, they take out all my players and it is usually repetitive. Sometimes those messages that I show in the image keep coming out, and I already checked all the configuration and it's fine, besides that I went to its page to see the error wiki and everything is correct, but I still have the same problem , and this occurs between all connected servers.

![Screenshot_1](https://user-images.githubusercontent.com/31551514/107249118-05d09780-6a01-11eb-8136-5502754343b8.png)

I also got messages like these that I take from the error wiki, and configure and verify that as I said and everything is correct but this type of message continues to persist.

![Screenshot_2](https://user-images.githubusercontent.com/31551514/107249413-5942e580-6a01-11eb-94ba-b8d252f1e6a3.png)

Could you please help me, it would be helpful, see if I have to configure something else? or what is causing the error.

Thank you very much in advance

**Comment by lucko** [comment]
The error here is originating from the driver, and is not being caused by LP.

The wiki page you referenced already (https://luckperms.net/wiki/Storage-system-errors) is my exhaustive advice on these issues - sorry but there's not much more I can do to help.
