### ISSUE TITLE
No response from luckperms on latest version

### ISSUE THREAD

**Issue by Thrasilias** [lucko/LuckPerms#2887]
### Description
Luckperms does not respond on latest version after executing more then 100 permission nodes (104)
and it does work find on older versions (76)

### Reproduction steps
https://www.youtube.com/watch?v=ESCaD_0_fF0&feature=youtu.be (Version 104 Latest)
https://www.youtube.com/watch?v=2ULt-oH2PNg&feature=youtu.be (Version 76 Older)

### Expected behaviour
LuckPerms should return a response / Error. instead of not responding

### Environment details

* Server type/version: `paperspigot` running version `1.12.2` build `???`
* LuckPerms version: `104` and `76`

**Comment by lucko** [comment]
Thanks for reporting, hopefully the above commit will help :)
