### ISSUE TITLE
User meta issue

### ISSUE THREAD

**Issue by ItsMacs** [lucko/LuckPerms#2888]
### Description
When we ran the command /lp user USER parent set GROUP, we observed the user got the group meta set as their own.

We tried completely deleting everything from LuckPerms - groups, tracks, users, everything, but to no effect.

The new groups suffer from the same bug.

### Reproduction steps
1.Create a group
2.Try setting it to a user
3.The user has now their previous group's meta set as their own.

### Expected behaviour
The user meta remains untouched

### Environment details

* Server type/version: `YAPFA` 1.15.2
* LuckPerms version: `v 5.2.76`

**Comment by lucko** [comment]
Could you send some screenshots illustrating what you mean? I don't really follow what the problem is

**Comment by ItsMacs** [comment]
![2021-02-12_22 20 04](https://user-images.githubusercontent.com/70864018/107823716-80dada80-6d80-11eb-9dcd-6149dec40661.png)

The user "dedda" has a group set as primary that does have item meta, but has inherited her previous group's meta (default), which got applied to her as personal user meta.

**Comment by lucko** [comment]
The `info` command will show inherited meta too - perhaps you want to use the `meta info` command instead?
