### ISSUE TITLE
LuckPerms Bungee Error SLF4J Fail

### ISSUE THREAD

**Issue by Hazugg** [lucko/LuckPerms#2889]
On my Bungee server I get the error when loading the plugin.

Could not load class "org.slf4j.impl.StaticLoggerBinder"

As the image shows, it is not loading correctly the corresponding class of slf4j

![image](https://user-images.githubusercontent.com/31551514/107851459-21101e00-6dd8-11eb-96da-d700cb5a4b1c.png)

**Comment by Fefo6644** [comment]
What BungeeCord version? What plugins do you have on your proxy? Is there anything else to that error?

**Comment by Hazugg** [comment]
I have this version of bungee

![image](https://user-images.githubusercontent.com/31551514/107852275-d5f90980-6ddd-11eb-9199-67f2193be194.png)

These are the plugins that I have in the bungee and I don't think that any are interfering

![image](https://user-images.githubusercontent.com/31551514/107852309-148ec400-6dde-11eb-8fea-ff6aecbe4c50.png)

And not, only does this error appear when loading luckperms, apparently the plugin is not loading the corresponding class as mentioned above, but I would not know what the reason is, that is not running, any way to resolve that error?

![image](https://user-images.githubusercontent.com/31551514/107852296-f1fcab00-6ddd-11eb-906e-506dc955d983.png)

**Comment by Fefo6644** [comment]
Are you able to reproduce the issue with LuckPerms as the only plugin?

**Comment by Hazugg** [comment]
you mean remove all plugins and just run luckperms to see if the error continues?

**Comment by Hazugg** [comment]
Apparently you are right, a plugin is interfering with the connection of the class, previously I have not had problems and I did not get this error, maybe it is with some update of the plugin that is causing the class not to be executed, some way to fix it ? Or would you just have to report it to the plugin that is doing the interference so you can validate and fix it?

**Comment by Hazugg** [comment]
Another question, what does that class not work? Would it cause a fatal error in the plugin? or in the connections?

**Comment by Fefo6644** [comment]
SLF4J is just the library used by Hikari (the library in charge of handling connections to the database) to log things in console. Everything will still work, the logger will just fallback to a NOP (no-operation) one, meaning it won't print anything, you just won't see things like errors or warnings printed by Hikari; is it ideal? Well no lol, the issue is one of those plugins is (most likely) being shipped with an ancient version of SLF4J.

**Comment by Hazugg** [comment]
Thank you very much for the report, maybe that is what is causing another error that I keep with luckperms, now that you tell me about hikari, although I will see if the problem is that, I will report right now about this inconvenience to the other plugin for see if you can do something about it, thank you very much again.

**Comment by lucko** [comment]
> Another question, what does that class not work? Would it cause a fatal error in the plugin? or in the connections?

It's not a fatal error :)
