### ISSUE TITLE
cant switch to yaml storage

### ISSUE THREAD

**Issue by chillerkraft** [lucko/LuckPerms#289]
i am 95% sure im doing everything right. i've done this at least 10 times the past month.
i set storage method to yaml but it's not creating the folder and files at startup
no errors or warns or anything in the console
latest dev build # 210

**Comment by lucko** [comment]
Pastebin your log file.

**Comment by chillerkraft** [comment]
oh man! i just made a discovery
when the console says it skipped a bunch of lines
it MEANS that its not showing me part of the log and i gotta go to my latest log to read everything
wow. dam multicraft.
SO
it said there was a problem with the config.
and it Didnt say that At All in the console
i probably don't have an issue anymore.

**Comment by chillerkraft** [comment]
thankyou lucko just had to add a :
