### ISSUE TITLE
lp Features 

### ISSUE THREAD

**Issue by 157946a** [lucko/LuckPerms#2890]
Personally suggest adding a function that can increase the limited time inheritance time. I believe this function will be very popular. The function means that it can increase the time from the original time.

**Comment by Fefo6644** [comment]
You can already achieve this by adding `accumulate` after the duration in the `addtemp` command, see the `[temporary modifier]` argument in the [`parent addtemp` command page](https://luckperms.net/wiki/Parent-Commands#lp-usergroup-usergroup-parent-addtemp-group-duration-temporary-modifier-context) :)

**Comment by 157946a** [comment]
That one. . . . . Can you give me a specific example how to write.

**Comment by 157946a** [comment]
Already understand, thank you for your confusion
