### ISSUE TITLE
Privilege group prefix problem

### ISSUE THREAD

**Issue by 157946a** [lucko/LuckPerms#2891]
The permission group is set with a prefix. After the player enters, there is no prefix of the permission group. After the expiration, the prefix of the default group cannot be returned. It must be set with addtempprefix to automatically return. I think what he implemented is that after inheriting this group, the prefix is automatically Changed to the prefix of this group, but he did not change.

**Comment by lucko** [comment]
This sounds like an issue with your chat plugin.

Please use the template next time, it's there for a reason.

**Comment by 157946a** [comment]
No, no, I use the parse test function of papi, and the test is the variable %luckperms_prefix%. No matter how you adjust it, the return is the prefix when setting, not the fixed prefix of the group

**Comment by 157946a** [comment]
I know the reason, because I inherited the relationship of the default group, and then my default group is also set, he will give priority to display the default group, you can see if you can let other groups inherit the default group or common inheritance Not inherit the prefix
