### ISSUE TITLE
Bulkupdate not working

### ISSUE THREAD

**Issue by Porkason** [lucko/LuckPerms#2894]
### Description
lp bulkupdate users delete "permission ~~ group.%"

doesn't work .-.

### Reproduction steps
issue lp bulkupdate users delete "permission ~~ group.%"
% being a group. 
on a 1.16.4 server with viaversion. viabackwards and viarewind (latest stable versions.) 
Issue the command thru console and it won't work. 

1. Open the config.yml file and set example to true.
2. Restart the server
3. Run /lp user example permission set x from the console
not even a thing? 

### Expected behaviour
For the command to remove the permission that is included in the command. 

### Environment details

* Server type/version: git-Purpur-956 (MC: 1.16.4) - 1.16.4-R0.1-SNAPSHOT
* LuckPerms version: LuckPerms v5.2.106 by Luck.

**Comment by lucko** [comment]
It's working fine for me... could you provide some screenshots to show what you mean exactly?
