### ISSUE TITLE
Luckperms & essentials permission doesn't work.

### ISSUE THREAD

**Issue by AlexioShow** [lucko/LuckPerms#2895]
### Description

Hello, i have a problem with LuckPerms and essentials. All essentials.PermissionExample doesn't work at all. I made a single rank, with "essentials.kit.daily" or "essentials.msg" (the kit was already created) and player doesn't have access to these command, even if i give them the permission. Tested everything, nothing works. All essenitals permission just doesn't work with Luckperms for some reasons.
Any help?
Sorry for the bad english :(
### Reproduction steps

1. Just do /lp editor
2. apply and in minecraft or console apply the new perms
3. Wait until a player do the command
4. "access denied."

### Expected behaviour

Give them the god'damn essentials (commands) permissions!

### Environment details

* Server type/version: Paper version git-Paper-468 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
* LuckPerms version: `v5.2.106`

### Any other relevant details

Plugins (30): AntiCreeper, AuctionHouse, BeSocial, BuycraftX, ClearLag, CoreProtect, CustomHeads*, DiscordSRV, dynmap*, Dynmap-Essentials*, Essentials, Essentials_WarpGUI, EssentialsSpawn, GoldenCrates, HolographicDisplays, LockettePro, LuckPerms, NexEngine, NoPlugins, OpenInv, PlaceholderAPI, PlayerParticles, QuickShop, ShopGUIPlus, ShopGUIPlusSilkSpawnersBridge, SilkSpawners, Smelt, Vault, WorldEdit, WorldGuard

**Comment by benwoo1110** [comment]
According to [essentials documentation](https://essinfo.xeya.me/permissions.html), lets use your kits example. You will need `essentials.kit` AND `essentials.kits.[kitname]`. I think you are just using the wrong permission nodes, contact essentials support on it and sending your editor link so we can see the perm nodes you set will be useful in this case.

**Comment by AlexioShow** [comment]
> According to [essentials documentation](https://essinfo.xeya.me/permissions.html), lets use your kits example. You will need `essentials.kit` AND `essentials.kits.[kitname]`. I think you are just using the wrong permission nodes, contact essentials support on it and sending your editor link so we can see the perm nodes you set will be useful in this case.

The problem is, it's not that.
Because every permission doesn't work so,
essentials.msg
essentials.afk
etc, etc doesn't work at all.

**Comment by benwoo1110** [comment]
Ok so here are some info youy should provide:
1. screenshot output of `/ess version` (run command from console)
2. send your editor link.
3. Run `/lp verbose command <player> <command>` replacing the placeholders appropriately

**Comment by Fefo6644** [comment]
Make sure LuckPerms is your only permissions plugin installed, other perms plugins will take over if any is present making LP not function.
You can find a very small list of permissions plugins in the [migration page] (https://luckperms.net/wiki/Migration) (keep in mind that it's **not** an exhaustive list and other perms plugins exist).
If you are unsure whether or not one of your plugins is a permissions plugin you can upload a screenshot of `/plugins`.

**Comment by AlexioShow** [comment]
> Ok so here are some info youy should provide:
> 
> 1. screenshot output of `/ess version` (run command from console)
> 2. send your editor link.
> 3. Run `/lp verbose command <player> <command>` replacing the placeholders appropriately
>    (edit: also ensure you test with a player that are in the correct permission groups.)

Version Server : 1.16.5-R0.1-SNAPSHOT git-Paper-468 (MC: 1.16.5)
>.... [19:10:47 INFO]: Version EssentialsX : 2.19.0-dev+74-36422ab
>.... [19:10:47 INFO]: Version LuckPerms : 5.2.106
>.... [19:10:47 INFO]: Version PlaceholderAPI : 2.10.9
>.... [19:10:47 INFO]: Version Vault : 1.7.3-b131
>.... [19:10:47 INFO]: Version EssentialsXSpawn : 2.19.0-dev+74-36422ab

with the lp verbose : 
Forcing X to execute command fly and reporting all checks made....
>.... [19:11:47 INFO]: [Essentials] L'accès à la commande a été refusé pour X. 
>.... [19:11:47 INFO]: [LP] VB > X - essentials.mail - undefined
>.... [19:11:47 INFO]: [LP] VB > X - essentials.fly - undefined
>.... [19:11:47 INFO]: [LP] Command execution complete.

in french : [Essentials] Access to the command has been denied for X. 

but she is in the... default group (aka member) which... got the essentials.mail and X is in the Roe group so access to the essentials.fly

it's so wierd!

**Comment by AlexioShow** [comment]
UPDATE : 
I deleted the essentials folder (except the users data + warps)
and the permissions finally works!

Sorry about all of this, i should have deleted the essentials folder in the first place!
