### ISSUE TITLE
Default-Group Error

### ISSUE THREAD

**Issue by xJust1n** [lucko/LuckPerms#2897]
### Description
* The players don't come into my own default group, but always into "default", but I want them to come into my group, because otherwise I have to rewrite most of the plugins

### Environment details

* Server type/version: `Waterfall` & `PaperMC` - `Version: 1.16.5`
* LuckPerms version: `Waterfall - v5.2.107` | `PaperMC - v5.2.104`

### The Error
* [https://prnt.sc/zrixnr](https://prnt.sc/zrixnr) - this error is on my (proxy)waterfall-server
* on my (bukkit/spigot)paper-server no mistake comes

**Comment by lucko** [comment]
The default assignments extension requires that Nashorn is installed on your system - unfortunately this is no longer being installed by default with Java installs, so you will need to add it manually for the extension to work.

The extension is for legacy support, so naturally it's not being maintained really.

Sorry, not much more I can do to help.
