### ISSUE TITLE
mohist-1.12.2-192

### ISSUE THREAD

**Issue by MakesYT** [lucko/LuckPerms#2898]
### Description

No matter how long gone,Loading configuration is always stuck during startup
![image](https://user-images.githubusercontent.com/42534870/108231508-cd595800-717c-11eb-9150-1fcdffa144cc.png)
Even though I tried this
![image](https://user-images.githubusercontent.com/42534870/108231741-085b8b80-717d-11eb-968e-9588635a7522.png)
It doesn't work
### Environment details

* Server type/version: mohist-1.12.2-192
* LuckPerms version: `v5.2.107`

**Comment by lucko** [comment]
That's strange.

I need some more details in order to look into this further - specifically a stack dump taken when the startup gets stuck.

See here for info about how to do that: https://gist.github.com/lucko/81033b72927eee0246dc8e8c284664c4

Please re-open the issue once you've got that :)

**Comment by memeorb** [comment]
mana download
