### ISSUE TITLE
Thermos Error

### ISSUE THREAD

**Issue by Yann151924** [lucko/LuckPerms#29]
I see the issue #16 , i have the same i think. I have this error when i launch with the legacy version or the normal.

http://pastebin.com/QdmmZwz0

**Comment by lucko** [comment]
Looks more like an issue with your server implementation. Usually you'd get those exceptions for the Guava and Gson classes, as they are not shaded on older versions.

I don't officially support Thermos, but it should work fine.

Which version are you using? I'll try to test. :)

**Comment by lucko** [comment]
Can I also suggest that you open an issue at https://github.com/CyberdyneCC/Thermos/issues and ask what they think? 

I've never used Thermos before, but it is my understanding that it should function in the same way as Craftbukkit when interacting with plugins.

**Comment by Yann151924** [comment]
I use the 56 version, i'll try a fresh install in case :)

**Comment by Yann151924** [comment]
Same error with a fresh intstall, i'll report to thermos and link here.

**Comment by lucko** [comment]
Yep, so it's an issue with your server software. 

Nothing I can do to fix it. 😢
