### ISSUE TITLE
Querying user meta-data does not force the input key to only-lowercase

### ISSUE THREAD

**Issue by yakovliam** [lucko/LuckPerms#2900]
### Description

Querying user meta-data (using LuckPerms API) with the method `User#getCachedData#getMetaData#getMetaValue(KEY)` does not query with the key lowercase forced, even though meta does not support uppercase characters.

This is an issue because setting new meta through the API (_or commands_) converts the key input to all lowercase if provided capital letters. This creates an inconsistency with setting/querying.

### Reproduction steps

1. Use the method with an uppercase character

### Expected behaviour

The method forces lowercase on the meta key input.

### Environment details

* Server type/version: `Paper` running version `1.16.5` build `469`
* LuckPerms version: `v5.2.76`

### Any other relevant details

N/A

**Comment by lucko** [comment]
Thanks for reporting! Should be fixed :)
