### ISSUE TITLE
Luckperms brocking chatformat from other plugin

### ISSUE THREAD

**Issue by VOENTOEN** [lucko/LuckPerms#2905]
Hey,
i have a plugin named harry potter economy for my  chatformat and if i install luckperms the chatformat dissapear for no reason here are some screenshots
without luckperms
![2021-02-21_17 12 46](https://user-images.githubusercontent.com/74774800/108631014-2ddfe200-7468-11eb-8164-fbf59b7e190e.png)
with luckperms:
![2021-02-21_17 12 03](https://user-images.githubusercontent.com/74774800/108631028-3e905800-7468-11eb-979f-06fde8e4cb43.png)
Error in console:
https://pastebin.com/Ta6MMLS3

**Comment by benwoo1110** [comment]
Note that LuckPerms isnt blocking the other plugin. From the errors you sent, it seems like harry potter economy plugin is not using the luckperms API correctly.

**Comment by lucko** [comment]
LuckPerms doesn't modify the chat directly.
