### ISSUE TITLE
Negated before wildcard with allow-op makes luckperms.* not work

### ISSUE THREAD

**Issue by Nestu14** [lucko/LuckPerms#2908]
### Description

Due to this commit [8167fbf](https://github.com/lucko/LuckPerms/commit/8167fbf73f99debb0cd8c1a46412a0176afb88af) and the way `commands-allow-op` works, having this `apply-default-negated-permissions-before-wildcards: true` and `commands-allow-op: false` set, makes luckperms.* being overriden.

### Reproduction steps

1. Open the config.yml file and set:
```yaml
apply-default-negated-permissions-before-wildcards: true
commands-allow-op: false
 ```
2. Run `/lp user example permission set luckperms.*`
3. Restart the server 
4. Run `/lp`
5. You will be said you do not have permission to use any sub commands

### Expected behaviour

At step 5, you should be said to use `/lp help` and have acces to all the sub commands

### Environment details

* Server type/version: `Spigot` running version `1.16.4` build `a19903d-23618b2`
* LuckPerms version: `v5.2.116`

### Explanation

Until said commit, having set `commands-allow-op: false` would just make opped users to need the nodes set, and `luckperms.*` would make the user have full access to LuckPerms both being it op or not. Then with this changes:
https://github.com/lucko/LuckPerms/blob/8167fbf73f99debb0cd8c1a46412a0176afb88af/bukkit/src/main/java/me/lucko/luckperms/bukkit/calculator/DefaultsProcessor.java#L63-L77
`luckperms.*` would only be overriden with `commands-allow-op: false` as it changes default permissions of LuckPerms from OP to False
https://github.com/lucko/LuckPerms/blob/8167fbf73f99debb0cd8c1a46412a0176afb88af/bukkit/src/main/java/me/lucko/luckperms/bukkit/LPBukkitPlugin.java#L268

**Comment by lucko** [comment]
Yes - you are correct, these features do not work with each other.

You need to pick which one you want to enable - I don't see what the bug here is?
