### ISSUE TITLE
Caught two warns during my "/lp migration groupmanager false"

### ISSUE THREAD

**Issue by andrewkm** [lucko/LuckPerms#291]
Thought I should report these:

https://pastebin.com/raw/zF3pi1V7

Included some lines before and after the WARNs to show what it was doing during it.

**Comment by lucko** [comment]
Looks like you have some characters in those group names which the file system doesn't like.

I'll add a debug message there so it's clearer which name caused the issue, but the easiest way for you to work out which group caused the error is probably to just look over all of your groups and find the two with the problematic character.

**Comment by mikroskeem** [comment]
Note: strip ascii colours next time :)

**Comment by lucko** [comment]
They're a pain to get rid of, gotta thank CraftBukkit for that :/

**Comment by lucko** [comment]
https://ci.lucko.me/job/LuckPerms/211/

^^ will tell you which group caused issues. If you find out which character is was, let me know and I'll add it to the rewrite rules.
