### ISSUE TITLE
Don’t spam console

### ISSUE THREAD

**Issue by Tringlle** [lucko/LuckPerms#2910]
### Description

Whenever there’s a database error, it always constantly spams my console, maybe remove that and replace it with something like this `LuckPerms Database Is Offline!` or something.

### Proposed behaviour

This could work by changing it to something like this `LuckPerms Database Is Offline!`.

**Comment by benwoo1110** [comment]
IMO, I dont see any benefit in thig change. The errors shown is important for debugging and shouldn't be cut to a single line so people can ignore them.

**Comment by lucko** [comment]
The "spam" in your console contains valuable information about what the problem is, and likely also hints what to do to fix it. I don't know why you would want to remove that... :)
