### ISSUE TITLE
Database reset

### ISSUE THREAD

**Issue by hotspuraz** [lucko/LuckPerms#2912]
### Description
I've used Luckperms for a long time and never had this issue but after the last server restart, the H2 database with all player permissions and groups just reset itself with no warnings in the logs regarding it. 

### Environment details

* Server type/version: `Paper` running version `1.16.5` build `492`
* LuckPerms version: `v5.1.93`

### Any other relevant details
Sorry that I don't have any information to give on this but the console/logs show nothing. No plugins have changed and 2 other servers restarted under the same conditions with no issues.

**Comment by lucko** [comment]
Sounds strange, unfortunately without more detail there is nothing I can do to help / potentially fix any underlying issue.

If you want something with a little more reliability, I suggest setting up a "proper" database - MySQL or something like that.
