### ISSUE TITLE
Context error

### ISSUE THREAD

**Issue by GoT-HiM** [lucko/LuckPerms#2913]
### Description

When I give a context to a permission (Work with Databases, MariaDB) and try to save them through the webgui, the plugin makes the change but when the gui is reopened all the contexts disappear.

### Reproduction steps

1. Open the gui
2. Enter a permission in a group,
3. Add a context, save send the command and close the gui. 
4. Finally, reopen the gui and there will be no contexts placed.

### Expected behaviour

In reality he had to show me the contexts I had already put (to make me remember what contexts I had put).

### Environment details

This error is not caused by plugin (For My Opinion)
* Server type/version: `ExampleSpigot` running version `1.12.2` build `???`
* LuckPerms version: `v???`
Luckperms v5.2.118 | PaperSpigot 1.8.8 latest

### Any other relevant details

There aren't other details

**Comment by benwoo1110** [comment]
What do you mean by "reopened"? Bcu you should not use the same editor link after apply edits.

![image](https://user-images.githubusercontent.com/30431861/109249200-32b6e400-7822-11eb-924d-6aa41b3f8cba.png)

**Comment by GoT-HiM** [comment]
In fact, as I have already written, you need to open a new editor.

**Comment by GoT-HiM** [comment]
And by reopened I mean I have opened a new editor.
