### ISSUE TITLE
Drivers not loading

### ISSUE THREAD

**Issue by ElijahRus250** [lucko/LuckPerms#2916]
### Description
On load the plugin cannot load the MySQL Drivers. Error: https://bytebin.lucko.me/4R3JOxIMF2

### Reproduction steps

1. I am not sure how I got this error, I will give you access to my server to see it though.

### Expected behaviour

Plugin should load normally

### Environment details

* Server type/version: `ExampleSpigot` running version `1.12.2` build `???`
* LuckPerms version: `Bungee v5.2.120`
* Flamecord: `0.4.6`

 https://bytebin.lucko.me/4R3JOxIMF2

**Comment by lucko** [comment]
Could you send a full log instead please

**Comment by ElijahRus250** [comment]
https://bytebin.lucko.me/LdHMvy4n8X

**Comment by lucko** [comment]
Please try deleting the `/plugins/LuckPerms/libs` folder and restarting the proxy.

**Comment by ElijahRus250** [comment]
That fixed it! 

Thanks so much!
