### ISSUE TITLE
the ability to change the message that pops up by doing /op when it is disabled.

### ISSUE THREAD

**Issue by iFlamingoz** [lucko/LuckPerms#2918]
### Description
Suggestion - the ability to change the /op message when disabled (https://prnt.sc/10b24dh) through a setting in the config.

**Comment by lucko** [comment]
You can change the wording by editing the language file: https://luckperms.net/wiki/Locale-and-Translations

The base file is en.properties

**Comment by lucko** [comment]
Or, you might find it easier to use another plugin to override/block the op command before LuckPerms handles it.

**Comment by iFlamingoz** [comment]
Oh, alright thank you!
