### ISSUE TITLE
LuckPerms default group

### ISSUE THREAD

**Issue by imbeandon** [lucko/LuckPerms#292]
hello i recently began using luckperms and am not too used to using it, or permissions plugins in general. I have a small basis on how to use it and before I go into my problem I must give you props on how easy you have made it ! ok, so I am trying to make a default class, one that gives certain permissions to players that just join and I read the page on the wiki, and I guess i just didnt understand it. Assuming the default group is the group players are assigned to when they come on the server for the first time, why isn't it happening for my friends that just joined? Also, if I have to make a new group for them to join by default, how would I go about that? (i am not that great on working the default assignments). Thank you for your time and effort on LuckPerms, it is a lot simpler and easier to use than the other permissions plugins !

**Comment by lucko** [comment]
Just add the permissions/groups you want players to have by default onto the "default" group.

e.g.

```
/lp group default permission set <permission> true
/lp group default parent add <group>
```

**Comment by imbeandon** [comment]
I've done that but when my other friends joined, they werent added to the group

**Comment by lucko** [comment]
They are added to "default" automatically.

**Comment by imbeandon** [comment]
for some reason, they aren't automatically added to the default group and its only happened to those who I've made admin

**Comment by lucko** [comment]
Don't use the parent set command if you want players to keep their existing ranks. Use parent add instead.
