### ISSUE TITLE
/lp crash

### ISSUE THREAD

**Issue by sondrewalnum** [lucko/LuckPerms#2920]
### Description

I get kicked from the server when I type /lp, /luckperms etc. 

### Reproduction steps

1. Type /lp or /luckperms in chat then hit space

### Expected behaviour

User will get kicked

### Environment details

* Server type/version: `Paper 1.16.4 with BungeeCord`
* LuckPerms version: `Latest, just tried changing it to the lastest version`

https://prnt.sc/10cdvbm

### Any other relevant details

This happened for the first time after adding the server to a BungeeCord Network.

**Comment by sondrewalnum** [comment]
Insatlling ViaVersion and ViaBackwards seems to have fixed the issue?

Running mc on 1.16.4 client and server on 1.16.5

**Comment by lucko** [comment]
It would be useful if you could either provide the crash log from your client, or be more specific about what version of LuckPerms you are using. "Latest" could refer to various versions depending on where you download from.

**Comment by sondrewalnum** [comment]
> It would be useful if you could either provide the crash log from your client, or be more specific about what version of LuckPerms you are using. "Latest" could refer to various versions depending on where you download from.

Found out it was another plugin causing it.
