### ISSUE TITLE
Console warns

### ISSUE THREAD

**Issue by Billyxxdd** [lucko/LuckPerms#2921]
Hi I don't know what to do. My console is going crazy because of Luckperms. Trough night log file had 20gb. Please help me to fix it
Log: https://pastebin.com/6wNMT9vE
I reinstalled whole plugin so config is and was default

Help me to fix it because I wanna use this plugin any help would help

**Comment by Fefo6644** [comment]
This is the part that concerns <i>you</i> and tells you what you <i>can</i> do about it.
> The operation to load user data for '5eb36239-c818-3d55-8f80-648ae5312bf8' was cancelled by LuckPerms. This is NOT a bug.
The lookup request was made on the main server thread. It is not safe to execute a request to
load data for offline players from the database in this context.
If you are a plugin author, please consider making your request asynchronously.
Alternatively, server admins can disable this catch by setting 'vault-unsafe-lookups' to true
in the LP config, but should consider the consequences (lag) before doing so.

Other than that you should contact `josegamerpt.realscoreboard` and send them the log too.

**Comment by Billyxxdd** [comment]
So maybe that warns are made by realscoreboard plugin ?

**Comment by Fefo6644** [comment]
The warning is made by LuckPerms but it's caused by something realscoreboard does that could lag the server. What I pasted above is very explicit about what you can do but you should contact the author regardless.
