### ISSUE TITLE
Error enabling plugin LuckPerms 5.3.0 on Waterfall

### ISSUE THREAD

**Issue by SrBedrock** [lucko/LuckPerms#2922]
### Description

Error enabling plugin LuckPerms 5.3.0 on Waterfall

### Reproduction steps

1. Start Waterfall server using Luckperms 5.3.0

### Expected behaviour

Load luckperms with no error on console

### Environment details

* Server type/version: `Waterfall Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398`
* LuckPerms version: `5.3.0`

Error on startup: https://gist.github.com/SrBedrock/4c8bf60c27177a1c02077a79f16b2ad1

**Comment by underscore11code** [comment]
Not a LP issue, seems to be an issue with the root machine, possibly permissions?

**Comment by SrBedrock** [comment]
> Not a LP issue, seems to be an issue with the root machine, possibly file permissions?
Version 5.2.82 works fine

**Comment by Fefo6644** [comment]
> Unable to create a temporary file
AccessDeniedException: /tmp/luckperms-jarinjar6361610685842350805.jar.tmp

The user you're running the server as doesn't have permissions to write in the `/tmp/` folder, this is not a LuckPerms issue. Make sure the user has read/write/execute permissions for that folder.
