### ISSUE TITLE
Nothing is saving

### ISSUE THREAD

**Issue by b1ued3mon** [lucko/LuckPerms#2926]
All the settings aren't saving once i close the browser. every time i load it back up to add new perms to a role, it reverts back to the first every permissions i first uploaded when I made the server and only shows 5 of the players on the list when the server started. I now have over 10 players but only 5 of the first ever users are always shown.

**Comment by Fefo6644** [comment]
Are you reusing the same editor session/link you previously closed?

**Comment by b1ued3mon** [comment]
I have it bookmarked. I was told by an admin on a hosting service to bookmarl it and use that. How else do I access it every time i wish to change it??

**Comment by Fefo6644** [comment]
You create a new session with `/lp editor`. You <b>have</b> to create a new editor session if you want to keep making changes after applying them. Don't reuse old or used sessions.

That is explained in the second paragraph in the [wiki page for the web editor](https://luckperms.net/wiki/Web-Editor)

**Comment by b1ued3mon** [comment]
omfg, thank you so much. I now have to go back and redo at least 40 perm lines.....
