### ISSUE TITLE
Update Extension-Legacy-API to support the new API 5.3

### ISSUE THREAD

**Issue by SwagPancakes** [lucko/LuckPerms#2927]
### Description

Update Extension-Legacy-API to support the new API 5.3

### Proposed behaviour

Support the new API 5.3 (Extension Legacy API)

**Comment by lucko** [comment]
The extension will still work on 5.3?

**Comment by SwagPancakes** [comment]
nvm I downloaded the new extension-legacy-api on luckperms.net and it works
