### ISSUE TITLE
API Method setServerName

### ISSUE THREAD

**Issue by Dreamtrailtv** [lucko/LuckPerms#2928]
### Description
An API method to change the server name. This would be helpful if you have a cloud system where you can store the config in the global plugins folder and then use the api to set the server name for the context. 

### Proposed behaviour
API-Methode:
LuckPermsProvider.get().setServerName(String servername);

**Comment by benwoo1110** [comment]
if you are talking about server context on backend servers, it's defined in luckperms config file, and afaik luckperms cannot change the config programmatically. Since you are using the API, you can just register your own context, and have full control over it.

**Comment by lucko** [comment]
Hey - sorry I actually implemented this a few days ago but forgot to reply here.

It's not an API method - but it will let you achieve the same thing: https://github.com/lucko/LuckPerms/commit/53bb61f9b25af8cc2588ef311ee3b8b8d18573fc

You can use `System.setProperty` to control this programatically.
