### ISSUE TITLE
Luckperms expire time

### ISSUE THREAD

**Issue by VojtechAdam29** [lucko/LuckPerms#2931]
### Description
So if i add temp group to player, and i type somewhere placeholder %luckperms_expire_time_group.master% (it can be whatever) the placeholder says not 30 days but 5d 59h 59m 59s.

### Expected behaviour
Expected is 30d not 5d 59h 59m 59s.

### Environment details

* Server type/version: `PaperSpigot` running version `1.15.2` build `git-Paper-390`
* LuckPerms version: `v5.3.0` - i also tried `5.1.26`

Picture https://i.imgur.com/1CLls54.png

**Comment by Fefo6644** [comment]
Update PAPI to a dev build https://ci.extendedclip.com/job/PlaceholderAPI/

**Comment by VojtechAdam29** [comment]
thanks it worked
