### ISSUE TITLE
Invalid Name setting doesnt work

### ISSUE THREAD

**Issue by Instinct1V** [lucko/LuckPerms#2932]
### Description

Players with Spaces in their names can not be reached.. 

### Reproduction steps

1. Open the config.yml file and set allow-invalid-usernames to true.
2. Restart the server
3. Run /lp user "bob junior" info
4. See you can not access the players information because they have a space in their name.

### Expected behaviour

Should access Bob Juniors information

### Environment details

Nukkit, latest version of it and luckperms
* Server type/version: `ExampleSpigot` running version `1.12.2` build `???`
* LuckPerms version: `v???`

**Comment by lucko** [comment]
I cannot reproduce this after setting the allow-invalid-username setting and restarting the server.

Could you provide some screenshots of what you mean?
