### ISSUE TITLE
Error on /lp editor command

### ISSUE THREAD

**Issue by justin0002** [lucko/LuckPerms#2934]
### Description

When typing the command /lp editor and then executing the command, I receive this error: https://bytebin.lucko.me/5b7cruIzAG

### Expected behaviour

There shouldn't be an error in the console :)

### Environment details

* Server type/version: Paper 1.12.2, Paper 1.16.5
* LuckPerms version: `v5.3.0`

**Comment by lucko** [comment]
It's fine to ignore the error - it just means that the command took a little longer to execute than expected.
