### ISSUE TITLE
The server thread has not responded for a long time by the LuckPerms.

### ISSUE THREAD

**Issue by Rollczi** [lucko/LuckPerms#2935]
(local database)
(the command was not executed it was an update of the record by another server)
![image](https://user-images.githubusercontent.com/49173834/110480933-53ffb600-80e7-11eb-9851-065817d85ec7.png)
![image](https://user-images.githubusercontent.com/49173834/110481602-0899d780-80e8-11eb-9576-845dbf472728.png)
![image](https://user-images.githubusercontent.com/49173834/110481678-1d766b00-80e8-11eb-948e-134c99779018.png)
I know I have an older version.

This is the first such bug since I have this version, so I can't check if it will appear in the new version because it occurred in a random situation.

Has it been repaired in a new one?
Maybe it is about that, but I'm not sure.
- Add timeout for command executions
- Improve Vault sync lookup error message

**Comment by lucko** [comment]
1. Please follow the issue template.
2. Please read the issue template - it makes it very clear that you should try updating before reporting an issue.
