### ISSUE TITLE
Duplicate prefix displayed when using Unicode symbol

### ISSUE THREAD

**Issue by kawaii** [lucko/LuckPerms#2939]
### Description

When using a Unicode symbol in a group prefix, requesting info on that group will display the prefix twice.
```
> lp group moderator info
[12:23:00 INFO]: [LP] > Group Info: moderator
[12:23:00 INFO]: [LP] - Display Name: moderator
[12:23:00 INFO]: [LP] - Weight: None
[12:23:00 INFO]: [LP] - Contextual Data: (mode: server)
[12:23:00 INFO]: [LP]     Prefix: "[★] [★]"
[12:23:00 INFO]: [LP]     Suffix: None
[12:23:00 INFO]: [LP]     Meta: None
```

This only effects the console, the prefix is not actually duplicated in-game.

### Reproduction steps

`lp group moderator meta addprefix 75 "&4[★]&r"`

`lp group moderator info`

You will see two copies of the prefix, instead of the intended one.

### Environment details

* Server type/version: `Paper Spigot` running version `1.16.5` build `543`
* LuckPerms version: `v5.3.0`

**Comment by lucko** [comment]
![Screenshot 2021-03-19 at 19 37 57](https://user-images.githubusercontent.com/8352868/111833835-a1033980-88ea-11eb-9d2c-68ef0f50ef05.png)
I cannot reproduce - probably a bug with your server / terminal app.
