### ISSUE TITLE
Parent remove context

### ISSUE THREAD

**Issue by VojtechAdam29** [lucko/LuckPerms#2940]
### Description

So if player has group in some context for example server=lobby and you type /lp user nick parent removetemp group1 server=lobby it removes it in global so it says that he doesnt have this group in context global, so i have to make it manually from lp editor. This happen only in new versions like 5.3.0.

### Expected behaviour

It should remove it from context Lobby but it removes it in context global

### Environment details

* Server type/version: `PaperSpigot` running version `1.15.2` build `git-Paper-390`
* LuckPerms version: `v5.3.0`

Screenshot: https://prnt.sc/10i8440

**Comment by lucko** [comment]
Thanks for reporting, this should be fixed by the above commit
