### ISSUE TITLE
lp editor,

### ISSUE THREAD

**Issue by Xns1510** [lucko/LuckPerms#2941]
### Description

Hello So i was using your Web Editor But Everytime i make a group, save it and refresh it gets deleted off of the Web Editor...

### Reproduction steps

1. Fix The Issue With It Deleting Off The Web Editor

1. Open the config.yml file and set example to true.
2. Restart the server
3. Run /lp user example permission set x from the console

### Expected behaviour

it to not delete off the web editor.

### Environment details

* Server type/version: `ExampleSpigot` running version `1.12.2` build `???`
* LuckPerms version: `v???`

Paper -1.16.5 
LuckPerms Version: LuckPerms-Bukkit-5.3.0.jar

**Comment by Fefo6644** [comment]
You **have** to create a new editor session if you want to keep making changes after applying them. Don't reuse old or used sessions.

This is well explained in the second paragraph in the [wiki page for the web editor](https://luckperms.net/wiki/Web-Editor)

**Comment by Turbotailz** [comment]
Also notice the message here when you hit the save button ;) 

![image](https://user-images.githubusercontent.com/10846855/110734969-fef5a880-827c-11eb-9f0b-1674df726a6f.png)
