### ISSUE TITLE
Lucky Perms "/lp editor" link not working

### ISSUE THREAD

**Issue by EmeraldShardx** [lucko/LuckPerms#2942]
I'm creating a pixelmon server on my computer and when I do "/lp editor" in the control panel it gives me a link that just brings me to the website and not an editor. https://luckperms.net/editor/?Jp5sOkjbsB This is an example of it. The only thing I've noticed is that there is a ? in all the links I get from the "/lp editor" command which, I don't see in any of the youtube videos showing me how to use the lucky perms mod.

**Comment by benwoo1110** [comment]
Looks like you are using an outdated luckperms version, get from https://luckperms.net/download. Also, follow the issue template next time.
