### ISSUE TITLE
server crash when going through a nether or end portal

### ISSUE THREAD

**Issue by muriplz** [lucko/LuckPerms#2944]
### Description
Going through the nether or end portal crashes instaltly the server

### Reproduction steps
Plugins and mods installed: GriefDefender 1.5.10, LP 5.2.76, create mod 0.3e and JEI for 1.16.4
Running with: Forge .58 and mohist 400 for 1.16.5

1. Open the server.
2. Use a portal.
3. see crash log:  [crash-2021-03-14_14.22.08-server.txt](https://github.com/lucko/LuckPerms/files/6136902/crash-2021-03-14_14.22.08-server.txt)

(I also tried with 5.3.0 + a PR to solve mohist compatibility, but still happens)

**Comment by benwoo1110** [comment]
I dont see how this is related to luckperms?

**Comment by muriplz** [comment]
Okey, my bad, pretty new on this and the crash error shows something about LuckPerms +  only OP players can go through nether/end portal
