### ISSUE TITLE
Problem with UUIDS

### ISSUE THREAD

**Issue by typecek123** [lucko/LuckPerms#2945]
### Description
Hello, I am using the plugin "JPremium". This plugin is for premium/cracked authentication. Premium players can join with no logging etc... I found this bug with Luckperms, when I remove myself from the JPremium database (premium account), then register... LuckPerms will not recognize my UUID and I have no groups, perms, etc. I think it is caused by LuckPerms, any other plugins using UUIDS like SkinsRestorer are okay with that. I think it is also when the premium player changes his nickname. Can you please add some support for it or something? Thanks for the response, Typecek123.

### Reproduction steps

Can you please add support for it or fix it?

* Server type/version:
* - LP 5.3.0
Waterfall (newest version)

https://pastebin.com/gPqu66jQ

**Comment by lucko** [comment]
This is definitely *not* an issue with LuckPerms, you need to speak to the author of JPremium - sorry, not much I can do to help.
