### ISSUE TITLE
[Bug] LuckPerms API: Get prefix provide an NPE

### ISSUE THREAD

**Issue by x9nico** [lucko/LuckPerms#2946]
Hello, I'm trying to get Prefix of Player with LuckPerms API.

I tried this:  `user.getCachedData().getMetaData().getPrefix();`

and it provides an NPE on this line.

I'm using purpur 1.16.5 as server software.

Latest build of LP.

**Comment by lucko** [comment]
I imagine `user` is probably null.

https://luckperms.net/wiki/Developer-API-Usage#obtaining-a-user-instance

**Comment by x9nico** [comment]
> I imagine `user` is probably null.
> 
> https://luckperms.net/wiki/Developer-API-Usage#obtaining-a-user-instance

I tried this, but I have same problem
