### ISSUE TITLE
LuckPerms.Autoop should override false-Perm from inheritation

### ISSUE THREAD

**Issue by Andre601** [lucko/LuckPerms#295]
There is this little problem with permissions, that are inherit from other ranks.

Lets say, I have the groups Member, Mod and Owner and don't want, that a member can use the commands from the plugin Citizens.

I set `citizens.npc.*` to `false` for the group member.
The players of the group mod should have access to all commands, so I give them the permission `luckperms.autoop` and set it to `true`
For safety, I let Mod inherit the permission from the group Member and now comes the problem:
Even with the autoop-permission set, all players in group Mod and Owner receive the message, that they don't have the permission to use `/npc`.

Only after giving them the permission and set it to true, the Mods can use it.

LuckPerms should just ignore every false-perms, that are inherit form other groups, if the actual group has luckperms.autoop

**Comment by lucko** [comment]
No, this is intended behaviour. 

If you want to override the negated permission, you need to specifically set it to true for mod.
