### ISSUE TITLE
Reducing timer on temporary perm node

### ISSUE THREAD

**Issue by lolmwahahah** [lucko/LuckPerms#2950]
### Description

hi is it possible to add a negative value for the accumulate temporary modifier so you can reduce the duration of the permission instead of adding a duration? Right now, it is only possible to add a duration to the timer and im hoping i can reduce timers in the future. this would be useful for servers with large playerbases as doing it manually would be way too time consuming.

### Proposed behaviour

e.g. /lp user (player) permission settemp (perm node) false (negative value) accumulate

**Comment by lucko** [comment]
The `removetemp` command accepts a duration argument 😛 

`/lp user <player> permission unsettemp <perm node> 1d` will subtract 1d from the expiry time of the node.

**Comment by benwoo1110** [comment]
Looks like its missing from the docs https://luckperms.net/wiki/Permission-Commands#lp-usergroup-usergroup-permission-unsettemp-node-context 😛 

![image](https://user-images.githubusercontent.com/30431861/111864763-de74cf00-899d-11eb-9a5c-51432e39dbcb.png)

**Comment by lucko** [comment]
Yeah it is

**Comment by Turbotailz** [comment]
Feel free to contribute https://github.com/LuckPerms/wiki/blob/master/pages/Permission-Commands.md 😉

**Comment by lucko** [comment]
https://github.com/LuckPerms/wiki/commit/c6e3a027a653eb9930b814625488ab34f70af938
