### ISSUE TITLE
Obtaining the expiration date of the group

### ISSUE THREAD

**Issue by DrakMC** [lucko/LuckPerms#2953]
### Description
I need to get the expiration date of the group.

### Proposed behaviour
It should be obtainable using PlaceholderAPI.

**Comment by Fefo6644** [comment]
Have you tried checking the placeholders page in the LuckPerms wiki? There is one for it, the very last one listed https://luckperms.net/wiki/Placeholders#luckperms_group_expiry_time_group-name

**Comment by DrakMC** [comment]
Yes, it is, but this is the remaining time until expiration. I would appreciate if it was possible to get an expiration date.

**Comment by Fefo6644** [comment]
Ah I see what you mean. The suggestion would be best fitted in the [`LuckPerms/placeholders`](https://github.com/LuckPerms/placeholders) repo to keep track of it there :)
