### ISSUE TITLE
LuckpermsBungee has 1000000 problems.

### ISSUE THREAD

**Issue by sasi2006166** [lucko/LuckPerms#2959]
Didn't fix

### Description

Without too many words, i applied manually litebans and other plugin permissions (since luckpermsbungee wasn't detecting it as normal) and still wasn't working.

### Reproduction steps

Just download a plugin bungee side, luckpermsbungee and setup manually permissions (since they will not appear)

### Expected behaviour

I expected that permissions will show as normal like luckperms bukkit but they didn't work.

### Environment details

Waterfall latest version.

* Server type/version: `ExampleSpigot` running version `1.12.2` build `???`
* LuckPerms version: ``
Waterfall latest version with luckpermsbungee 5.3.16

No errors or nothing.

**Comment by Laarryy** [comment]
> Without too many words

Definitely not enough words, definitely. 

Please close this and fill out the issue form in full, with detailed descriptions and all fields complete. Thanks.

**Comment by BomBardyGamer** [comment]
This would be due to BungeeCord not providing a way to explicitly register permissions I believe, not an issue with LuckPerms Bungee.
