### ISSUE TITLE
When the fabric version luckperms executes the / LP group default permission set command, it does not have the original permission after the set

### ISSUE THREAD

**Issue by YiGe18** [lucko/LuckPerms#2961]
When the fabric version luckperms executes the / LP group default permission set command, it does not have the original permission after the set.
![M(O$KXSYDX}JV1G 1NCSX~8](https://user-images.githubusercontent.com/81473071/112744589-f10d8a80-8fd3-11eb-87e0-b7f7a58926d1.png)
![RO}SJZ~(2LJ1 ~O4A8IP)WW](https://user-images.githubusercontent.com/81473071/112744597-01be0080-8fd4-11eb-8b3e-3faad0d395c1.png)
Mod version is 1.16.4 fabric 
The server version is 1.16.5

**Comment by benwoo1110** [comment]
As far as I can tell, fabric does not implement any form of permission checking for vanilla commands at the moment. So the only way to control is by giving OP for now.

**Comment by YiGe18** [comment]
> As far as I can tell, fabric does not implement any form of permission checking for vanilla commands at the moment. So the only way to control is by giving OP for now.

But why did the author publish the fabric version? Isn't that meaningless? So how can we solve the problem of the plug-in permissions, except Op.

**Comment by benwoo1110** [comment]
That’s up to fabric, not luckperms.

**Comment by YiGe18** [comment]
> 这取决于面料，而不是运气。
OK, thanks. I will wait for version 1.16.5 to come out and I will try again. If it still doesn't work, it will be really bad.

**Comment by TjeuKayim** [comment]
In the meantime I use LuckPerms in conjunction with player-roles-fabric, they seem to work fine together, but both have their own roles and permissions system. I couldn't find a fabric mod that enables `minecraft.commands.*` permissions to be managed with LuckPerms as a central system.

**Comment by YiGe18** [comment]
> In the meantime I use LuckPerms in conjunction with player-roles-fabric, they seem to work fine together, but both have their own roles and permissions system. I couldn't find a fabric mod that enables  permissions to be managed with LuckPerms as a central system.

Oh，thank you very much！Have you tried 'minecraft.commands.*' alone in LuckPrems before and did it work?

**Comment by TjeuKayim** [comment]
I tried to use `minecraft.commands.ban` and `minecraft.commands.whitelist` in LuckPerms for Fabric, but that didn't work. benwoo1110 is right, I looked into the Minecraft code and indeed this is just a Spigot thing.
Also see these Discord messages about the same issue: https://discord.com/channels/507304429255393322/789953494534324264/819193614574813244

**Comment by YiGe18** [comment]
> I tried to use and in LuckPerms for Fabric, but that didn't work. benwoo1110 is right, I looked into the Minecraft code and indeed this is just a Spigot thing.
> Also see these Discord messages about the same issue: https://discord.com/channels/507304429255393322/789953494534324264/819193614574813244`minecraft.commands.ban``minecraft.commands.whitelist`

Thanks for your help! As you said before, luckperms and player-roles-fabric will work together. Will player roles fabric work alone?

**Comment by TjeuKayim** [comment]
> Will player roles fabric work alone?

Yes, the player-role-fabric mod can function independently. It is an alternative to LuckPerms. These two mods do not interact/integrate with each other, but they are compatible and the permissions stack. I've installed both because I want to use LuckPerms were possible, and only use player-role-fabric for the vanilla commands which LuckPerms can't control.

**Comment by TjeuKayim** [comment]
I finished developing a new mod to implement the permissions `minecraft.command.<command>` with the Fabric Permissions API. 
It was tested with Minecraft 1.16.5 and LuckPerms v5.3.16. Now, I don't need the player-role-fabric mod anymore. Try it here https://github.com/TjeuKayim/minecraft-command-permissions-fabric/releases/latest
