### ISSUE TITLE
LuckPerms clears all permission settings on reboot

### ISSUE THREAD

**Issue by RafaSojo** [lucko/LuckPerms#2963]
### Description

We have encountered a rather strange bug that happens every 3-4 months. After a scheduled reboot we found that all LuckPerms data has been deleted.

### Reproduction steps

It is complicated to reproduce. According to our research it seems that when the database connection is restarted and closed and just at that moment a user tries to log in there is a thread that tries to make a query and fails.

![image](https://user-images.githubusercontent.com/19918951/112901325-e42c8c00-90e4-11eb-840e-9b931cab2e83.png)

### Expected behaviour

Do not delete the entire configuration.

### Environment details

Server ForgeSponge with Minecraft 1.12.2
LuckPerms version 5.1.17

### Any other relevant details

I think it must be some kind of thread synchronisation problem or something weird like that. In the image I posted before you can see how the connection closes and just at that moment a user tries to enter and from then on it fails. This is not something that happens often and luckily we constantly make backups but it could be a problem.

**Comment by Turbotailz** [comment]
You are using a dated version of the plugin, you should probably upgrade and see if the issue persists.

**Comment by RafaSojo** [comment]
We have already updated and the problem remains. What's more, it happens more frequently now.

**Comment by benwoo1110** [comment]
Did your server crash or you forcefully shut it down before?

**Comment by lucko** [comment]
Things I can think of:

1. Ensure your server has plenty of free disk space
2. Ensure that when the server shuts down, it does so gracefully (doesn't force exit)
3. Ensure that only one server is being ran in a given directory at a time

Failing that, it might be worth switching from H2 to a remote database like MySQL. There's a guide on the wiki that explains how to do this :)

**Comment by RafaSojo** [comment]
No, the server did not crash when it was restarted.

We were using H2 storage, switched to MySQL and so far it hasn't been a problem.
