### ISSUE TITLE
Editor command throws error and takes 5 minutes to execute

### ISSUE THREAD

**Issue by PotatoIQ** [lucko/LuckPerms#2968]
### Description

When I type "/lp editor" in game or console I get the following error every single time:
https://haste.olziedev.com/icaweyapid.yaml
and it takes about 5 minutes for the command to show me the editor link
Note I'm using the same mysql for my survival servers, at first I used the same mysql for also the bungee luckperms, but I then changed it to only use the same mysql for the paper servers.

### Reproduction steps

1. type "/lp editor"

### Environment details

* Server type/version: `git-Paper-576 (MC: 1.16.5)`
* LuckPerms version: `LuckPerms version 5.3.16`

### Any other relevant details

here is my config.yml
https://haste.olziedev.com/henukonofa.yaml

**Comment by benwoo1110** [comment]
Check that whatever computer running your mc server can access https://bytebin.lucko.me/. If you are using a hosting service, I suggest you contact them.

**Comment by Laarryy** [comment]
In addition to what @benwoo1110 suggested, please also ensure that the ping from the server to the database is not extremely high, as that can easily cause this issue.

**Comment by lucko** [comment]
Your database is being slow to respond, most likely a problem with that as opposed to with LuckPerms.
