### ISSUE TITLE
Temp Groups/Permissions turning into Perm

### ISSUE THREAD

**Issue by tangerine349** [lucko/LuckPerms#2969]
### Description

When i set a temp group or permission it changes to a perm group or permission sometimes when switching servers on bungee

### Reproduction steps

It just happened randomly

### Expected behaviour

The permission not to turn perm

### Environment details

* Server type/version: `Paper` running version `1.16.4` build `416`
* LuckPerms version: `v5.3.17`

Ill post if needed, im in a rush

### Any other relevant details

None

**Comment by lucko** [comment]
I'm gonna need some more details in order to look into this for you.

Could you perhaps provide some screenshots of what you mean? I can't really follow your explaination.

**Comment by tangerine349** [comment]
Hello, this is what im meaning:
The group with the expiry added onto it didnt actually work as afew minutes later when switching servers it added one that has no expiry https://gyazo.com/04479c9ae58ef01ff912e15c1bdfe960

**Comment by lucko** [comment]
There's nothing in LP that would do this on it's own, so I imagine it is being caused by another plugin.

You could try turning Vault debug on in the config to see if that gives any hints as to what it is.
