### ISSUE TITLE
Groups are leaving

### ISSUE THREAD

**Issue by jaopedropvp** [lucko/LuckPerms#297]
When I have one group and the other group I leave

Before setting:
http://prntscr.com/fcj2qc

After the command to set a group:

http://prntscr.com/fcj36q

Groups disappear...

**Comment by lucko** [comment]
Use `parent add` instead of `parent set` then.

https://github.com/lucko/LuckPerms/wiki/Command-Usage#lp-usergroup-usergroup-parent-add
