### ISSUE TITLE
Config files are mislocated in the fabric mods folder

### ISSUE THREAD

**Issue by zedwick** [lucko/LuckPerms#2972]
### Description
Luckperms config folder is now located within the mods folder, rather than the config folder. It ignores the existing configs in configs/luckperms, and creates a new folder at mods/luckperms.

### Reproduction steps

1. Install LP 5.3.9 on a fabric server
2. Start server
3. Open mods folder to see a new luckperms folder populared with files.

### Expected behaviour
In LuckPerms 5.2.29, LP created and used the configs located at config/luckperms. I believe it should continue to do so.

### Environment details

* Server type/version: `21w07a - fabric-api@0.2.1+524a2e8580`
* Fabric API: `0.30.5+1.17`
* LuckPerms version: `v5.3.9`

### Any other relevant details
Looking at the source, I think this is the line responsible: https://github.com/lucko/LuckPerms/blob/f0e1a8f0923b6784457253740bd81122d2f4f8d9/common/src/main/java/me/lucko/luckperms/common/plugin/AbstractLuckPermsPlugin.java#L273

```
Path configFile = getBootstrap().getDataDirectory().resolve(fileName);
```

Should probably be

```
Path configFile = getBootstrap().getConfigDirectory().resolve(fileName);
```

**Comment by lucko** [comment]
You're absolutely right, thanks for the detailed bug report! :)
