### ISSUE TITLE
Having issues with /lp editor

### ISSUE THREAD

**Issue by Ethanboyz** [lucko/LuckPerms#2973]
**Description**

Running the command /lp editor takes a really long time to execute (about 2-5 mins).

**Reproduction steps**

1. Open the config.yml file, set storage-method to MySQL, fill out the rest of the necessary fields
2. Restart the server
3. Run /lp editor
4. Nothing happens, then after a few seconds errors appear in console

**Expected behaviour**

A web editor link is generated in a few seconds.

**Environment details**

* Server type/version: `Tuinity` running version `1.16.5` build `218`
* LuckPerms version: `v5.3.17`

https://gist.github.com/Ethanboyz/92fabdb645ab28529fcd18e5e78c9f95

**Any other relevant details**

I have no idea what is causing the issue. Luckperms seems to enable and shut down correctly when the server restarts and stops, the configurations even work with other servers except for this particular one. It just so happens that errors appear in the console when running /lp editor, though running other commands like /lp export works fine.

**Comment by Turbotailz** [comment]
what about any of the other commands that send data to bytebin, e.g. `/lp tree` `/lp verbose record` (then `/lp verbose paste`) or `/lp export --upload` ?

**Comment by lucko** [comment]
I've made some changes which should make this process faster (and therefore not cause the warning to be printed)

If there are still issues, then it is likely just down to your MySQL server being a little slow.
