### ISSUE TITLE
[API] No default group

### ISSUE THREAD

**Issue by KleinCrafter** [lucko/LuckPerms#2974]
### Description
There is a state that a User has no Group not even the default group.
Short Conversation on Discord: https://discord.com/channels/241667244927483904/420538367986499585/829115178255515709

### Reproduction steps
```java
final var uuid = plugin.getUUID(sender); // Get UUID from CommandSender
LuckPermsProvider.get().getUserManager().modifyUser(uuid, user -> user.data().clear(NodeType.INHERITANCE::matches)).thenAccept(v -> {
    final var groups = LuckPermsProvider.get().getUserManager().getUser(uuid).getInheritedGroups(QueryOptions.nonContextual());
    sender.sendMessage("Your Group size is: " + groups.size());
});
```
Return: `Your Group size is: 0`

The `thenAccept` don't must be inside the same command,
I found this because Users got removed all Groups don't have a color or other thinks in the Chat. (No Permission need for the Chat)

### Expected behaviour
User have allways the default group.

### Environment details
* Waterfall#403
* LuckPerms 5.3.17

**Comment by Fefo6644** [comment]
https://github.com/lucko/LuckPerms/commit/46efe0ef931f7f7ed5618fe6379f30df4e3fae1c
