### ISSUE TITLE
incompatibility with carpet's `/player` command

### ISSUE THREAD

**Issue by SpaceClouds42** [lucko/LuckPerms#2975]
[stacktrace](https://paste.ee/p/Rt7Np/)

[source of bug](https://github.com/lucko/LuckPerms/blob/82488140ee6556aa41f20a89d92d31559f6904ba/fabric/src/main/java/me/lucko/luckperms/fabric/listeners/PermissionCheckListener.java#L67)

When luckperms does `.hasPermission(permission)`, it gets a null pointer exception

**Comment by lucko** [comment]
Thanks :) c533446ab0fec46a1a6299bf11d8642ade26a9dd
