### ISSUE TITLE
This is nonstop in my console any ideas?

### ISSUE THREAD

**Issue by ripperfame1** [lucko/LuckPerms#2976]
### Description
08.04 15:24:36 [Server] ERROR java.lang.IllegalStateException: zip file closed
08.04 15:24:36 [Server] WARN java.lang.IllegalStateException: zip file closed
08.04 15:24:36 [Server] WARN at java.util.zip.ZipFile.ensureOpen(ZipFile.java:686)
08.04 15:24:36 [Server] WARN at java.util.zip.ZipFile.getEntry(ZipFile.java:315)
08.04 15:24:36 [Server] WARN at java.util.jar.JarFile.getEntry(JarFile.java:240)
08.04 15:24:36 [Server] WARN at java.util.jar.JarFile.getJarEntry(JarFile.java:223)
08.04 15:24:36 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:144)
08.04 15:24:36 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:216)
08.04 15:24:36 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:122)
08.04 15:24:36 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111)
08.04 15:24:36 [Server] WARN at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
08.04 15:24:36 [Server] WARN at java.lang.ClassLoader.loadClass(ClassLoader.java:405)
08.04 15:24:36 [Server] WARN at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
08.04 15:24:36 [Server] WARN at me.lucko.luckperms.lib.adventure.text.serializer.bungeecord.SelfSerializable$AdapterFactory.create(SelfSerializable.java:54)
08.04 15:24:36 [Server] WARN at com.google.gson.Gson.getAdapter(Gson.java:423)
08.04 15:24:36 [Server] WARN at com.google.gson.Gson.toJson(Gson.java:661)
08.04 15:24:36 [Server] WARN at com.google.gson.Gson.toJson(Gson.java:648)
08.04 15:24:36 [Server] WARN at com.google.gson.Gson.toJson(Gson.java:603)
08.04 15:24:36 [Server] WARN at com.google.gson.Gson.toJson(Gson.java:583)
08.04 15:24:36 [Server] WARN at net.md_5.bungee.chat.ComponentSerializer.toString(ComponentSerializer.java:69)
08.04 15:24:36 [Server] WARN at net.minecraft.server.v1_16_R3.PacketPlayOutChat.b(PacketPlayOutChat.java:47)
08.04 15:24:36 [Server] WARN at net.minecraft.server.v1_16_R3.PacketEncoder.encode(PacketEncoder.java:46)
08.04 15:24:36 [Server] WARN at net.minecraft.server.v1_16_R3.PacketEncoder.encode(PacketEncoder.java:15)
08.04 15:24:36 [Server] WARN at sun.reflect.GeneratedMethodAccessor42.invoke(Unknown Source)
08.04 15:24:36 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
08.04 15:24:36 [Server] WARN at java.lang.reflect.Method.invoke(Method.java:498)
08.04 15:24:36 [Server] WARN at com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:529)
08.04 15:24:36 [Server] WARN at com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:71)
08.04 15:24:36 [Server] WARN at com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:269)
08.04 15:24:36 [Server] WARN at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
08.04 15:24:36 [Server] WARN at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:275)
08.04 15:24:36 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
08.04 15:24:36 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
08.04 15:24:36 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
08.04 15:24:36 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
08.04 15:24:36 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
08.04 15:24:36 [Server] WARN at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
08.04 15:24:36 [Server] WARN at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:294)
08.04 15:24:36 [Server] WARN at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
08.04 15:24:36 [Server] WARN at net.minecraft.server.v1_16_R3.NetworkManager.lambda$b$6(NetworkManager.java:323)
08.04 15:24:36 [Server] WARN at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:352)
08.04 15:24:36 [Server] WARN at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
08.04 15:24:36 [Server] WARN at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
08.04 15:24:36 [Server] WARN at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
08.04 15:24:36 [Server] WARN at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
08.04 15:24:36 [Server] WARN at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
08.04 15:24:36 [Server] WARN at java.lang.Thread.run(Thread.java:748)
08.04 15:24:40 [Server] ERROR java.lang.IllegalStateException: zip file closed
08.04 15:24:40 [Server] WARN java.lang.IllegalStateException: zip file closed
08.04 15:24:40 [Server] WARN at java.util.zip.ZipFile.ensureOpen(ZipFile.java:686)
08.04 15:24:40 [Server] WARN at java.util.zip.ZipFile.getEntry(ZipFile.java:315)
08.04 15:24:40 [Server] WARN at java.util.jar.JarFile.getEntry(JarFile.java:240)
08.04 15:24:40 [Server] WARN at java.util.jar.JarFile.getJarEntry(JarFile.java:223)
08.04 15:24:40 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:144)
08.04 15:24:40 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:216)
08.04 15:24:40 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:122)
08.04 15:24:40 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111)
08.04 15:24:40 [Server] WARN at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
08.04 15:24:40 [Server] WARN at java.lang.ClassLoader.loadClass(ClassLoader.java:405)
08.04 15:24:40 [Server] WARN at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
08.04 15:24:40 [Server] WARN at me.lucko.luckperms.lib.adventure.text.serializer.bungeecord.SelfSerializable$AdapterFactory.create(SelfSerializable.java:54)
08.04 15:24:40 [Server] WARN at com.google.gson.Gson.getAdapter(Gson.java:423)
08.04 15:24:40 [Server] WARN at com.google.gson.Gson.toJson(Gson.java:661)
08.04 15:24:40 [Server] WARN at com.google.gson.Gson.toJson(Gson.java:648)
08.04 15:24:40 [Server] WARN at com.google.gson.Gson.toJson(Gson.java:603)
08.04 15:24:40 [Server] WARN at com.google.gson.Gson.toJson(Gson.java:583)
08.04 15:24:40 [Server] WARN at net.md_5.bungee.chat.ComponentSerializer.toString(ComponentSerializer.java:69)
08.04 15:24:40 [Server] WARN at net.minecraft.server.v1_16_R3.PacketPlayOutChat.b(PacketPlayOutChat.java:47)
08.04 15:24:40 [Server] WARN at net.minecraft.server.v1_16_R3.PacketEncoder.encode(PacketEncoder.java:46)
08.04 15:24:40 [Server] WARN at net.minecraft.server.v1_16_R3.PacketEncoder.encode(PacketEncoder.java:15)
08.04 15:24:40 [Server] WARN at sun.reflect.GeneratedMethodAccessor42.invoke(Unknown Source)
08.04 15:24:40 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
08.04 15:24:40 [Server] WARN at java.lang.reflect.Method.invoke(Method.java:498)
08.04 15:24:40 [Server] WARN at com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:529)
08.04 15:24:40 [Server] WARN at com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:71)
08.04 15:24:40 [Server] WARN at com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:269)
08.04 15:24:40 [Server] WARN at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
08.04 15:24:40 [Server] WARN at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:275)
08.04 15:24:40 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
08.04 15:24:40 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
08.04 15:24:40 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
08.04 15:24:40 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
08.04 15:24:40 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
08.04 15:24:40 [Server] WARN at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
08.04 15:24:40 [Server] WARN at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:294)
08.04 15:24:40 [Server] WARN at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
08.04 15:24:40 [Server] WARN at net.minecraft.server.v1_16_R3.NetworkManager.lambda$b$6(NetworkManager.java:323)
08.04 15:24:40 [Server] WARN at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:352)
08.04 15:24:40 [Server] WARN at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
08.04 15:24:40 [Server] WARN at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
08.04 15:24:40 [Server] WARN at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
08.04 15:24:40 [Server] WARN at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
08.04 15:24:40 [Server] WARN at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
08.04 15:24:40 [Server] WARN at java.lang.Thread.run(Thread.java:748)

**Comment by DillonB07** [comment]
Attach a list of the other mods you are using and what platform/version(bukkit/paper/spigot/fabric)

**Comment by ripperfame1** [comment]
1.Advanced Enchantments
2.Better RTP
3.Chat Filter
4.Clear lag
5.Discord SRV
6.Dead chest
7.Enjinminecraftplugin
8.essentials
9.head drops
10. Holographic disaplays
11. jobs
12.Luckperms
13.Matrix
14. ShopGUIplus
15. Silk spawners
16. Single Player Sleep
17. world edit
18. world guard
19.mcmmo

JAR file-  Paper-1.16.5-584   <----- Build#

**Comment by DillonB07** [comment]
If you remove LuckPerms does it all work?

**Comment by ripperfame1** [comment]
we switched to luckperms and paper last night. None of these areas were here before luckperms

**Comment by ripperfame1** [comment]
we initially switched because some permission didn't work with group manager but luck perms fixed it. Then all of these errors were showing up

**Comment by Fefo6644** [comment]
1. Please don't dismiss the issue template, it's there for a reason, it helps everyone help faster, even yourself.
2. You didn't list all your plugins (you clearly have ProtocolLib according to the stack trace, something you didn't list)
3. Please use a paste site such as https://paste.lucko.me/ to paste logs and errors
4. Please provide all kinds of information that could be useful (entire server log, LP version, LP config, etc)

**Comment by ripperfame1** [comment]
so what else do you need?

**Comment by Laarryy** [comment]
Everything the template asks for.

**Comment by ripperfame1** [comment]
which is?

**Comment by LeotomasMC** [comment]
[this is the template.](https://github.com/lucko/LuckPerms/blob/master/.github/ISSUE_TEMPLATE/bug-report.md) you should have seen it as you were making the issue.
