### ISSUE TITLE
Disabling bulkupdate confirmation

### ISSUE THREAD

**Issue by dimon0230ru** [lucko/LuckPerms#2980]
### Description

I really need the ability to configure whether I need a bulkupdate confirmation

**Comment by benwoo1110** [comment]
Bulk edit is a very dangerous operation that should not be done by automation or without confirmation. 

May I ask what is your use case that requires the confirmation to be removed ?

**Comment by dimon0230ru** [comment]
> Bulk edit is a very dangerous operation that should not be done by automation or without confirmation.
> 
> May I ask what is your use case that requires the confirmation to be removed ?

I don't know the java language but with cmi and luckperms I can do a lot of different features, with permission I can track and manage them for the players. So I can make a point through cmi portals to which the player will capture it, only he will be given a special permission, and everyone else will have it taken away if it was, since I can't track who exactly it was issued to. This is called capturing a point and the player will receive a reward for it as long as he has this permission and other players have not captured it in the same way. I can still think of many such possibilities while I try to implement this one.
