### ISSUE TITLE
plugin not vorking on 1.12.2

### ISSUE THREAD

**Issue by zaze06** [lucko/LuckPerms#2982]
think I have the latest 5.3.3

### Description

`org.bukkit.plugin.InvalidPluginException: me.lucko.luckperms.common.loader.LoadingException: Unable to create bootstrap plugin instance`

### Reproduction steps

1. make a server using mohist 1.12.2
2. add a som mods(think this is none important tho)
3. start the server

### Expected behaviour

the plugin should get loded and work

### Environment details

* Server type/version: `mohist` running version `1.12.2` build `201`
* LuckPerms version: `v5.3.3`

### Any other relevant details

Mods https://gist.github.com/zaze06/c99fa136798463c1a51b2d16d43963df
log https://gist.github.com/zaze06/a108041cbed1c39f8bf3001ca8475b87

**Comment by Fefo6644** [comment]
Forge + Bukkit servers are not a supported server platform.
Feel free to paste in gist the entire server log (`/logs/latest.log`) for additional details (maybe it is something fixable), but there is absolutely no guaratee it *will* work.

**Comment by zaze06** [comment]
now I have added the log

**Comment by Fefo6644** [comment]
I see you are running SpongeForge + LuckPerms for Sponge, please don't use the Bukkit version of LuckPerms if you are using the Sponge version.

On another note you shouldn't be using Essentials, you should be using [Nucleus](https://v2.nucleuspowered.org/) which is also a Sponge plugin, but that's another topic not related to LP.

**Comment by zaze06** [comment]
Hi i removed the sponge version of luckperms and now I get the luckperm logog in the consol, /lp works to
