### ISSUE TITLE
Java 16

### ISSUE THREAD

**Issue by RyanAndersond4** [lucko/LuckPerms#2983]
### Reproduction steps

1. Open the config.yml file and set example to true.
2. Restart the server
3. Run /lp user example permission set x from the console

### Environment details

* Server type/version: `ExampleSpigot` running version `1.12.2` build `???`
* LuckPerms version: `v???`

**Comment by benwoo1110** [comment]
I have 0 idea what the issue is. Fill in the issue template in detail if you wish to get any help.
