### ISSUE TITLE
Java 16 Issue with Commands in game

### ISSUE THREAD

**Issue by RyanAndersond4** [lucko/LuckPerms#2985]
### Description

Java 16 issue with doing commands in game

Bungee cord version : 1.16-R0.5-SNAPSHOT:a7c6ede:1549 by md_5
paper version : git-Paper-586 ( MC : 1.16.5)
* LuckPerms version: `v5.3.21'

https://pastebin.com/7GDjxAy5

This is after typing command /lpb editor. 
lp commands seem to work so it appears to be a proxy issue. lp editor in the paper servers console also works.

**Comment by RyanAndersond4** [comment]
/lp editor in game also appears to work just not /lpb editor

**Comment by lucko** [comment]
Should be fixed in v5.3.24 and newer :)

0808392353a1b39ac51e6979d16e0e4f7061af26
