### ISSUE TITLE
Rankup Tracks by Weight

### ISSUE THREAD

**Issue by Zenomac** [lucko/LuckPerms#2987]
Hello,

My suggestion is for a command to be added for ranking up to a specific rank.
Here's an example:

The Rank Track:
Default -> Member -> Sr. Member -> Mega Member

I have vouches implemented into my server so there's the ability to claim a rank that's lower than their current rank:
Example:

Default gets Mega Member rank, uses the voucher, and gets Mega Member rank.
Mega Member gets Member rank and uses the voucher, would be demoted to Member rank.

If possible, could a track-by-weight be added, so people could only go up in weight instead of lower?

**Comment by benwoo1110** [comment]
I feel like this is a very specific use case that you either should trigger a promote/demote command on voucher usage, or use the luckperms API and code a custom plugin to handle the behaviour to your liking.

**Comment by lucko** [comment]
I agree with Ben, sorry - this isn't something I feel would be useful for the majority of people.
