### ISSUE TITLE
Mysql error truncation when i put prefix hexa in perm 

### ISSUE THREAD

**Issue by DevilishDante** [lucko/LuckPerms#2989]
### Description
Hi, when i put some hexadecimal code une permission prefix like prefix.50.&8● &#9a4dff
When i update my perm i have some MySQL error in console :

### Reproduction steps
juste put hexadécimal prefix in some group

### Expected behaviour
![image](https://user-images.githubusercontent.com/13486924/114956354-fd606700-9e5e-11eb-8741-a2cb45ee2740.png)

### Environment details
Debian 9 
Spigot 1.16.3
java version "1.8.0_151"
Luckperm 5.3.3 and lastest vault and essentials stable release

Thanks you to read me

**Comment by lucko** [comment]
Try updating the table encoding to utf8-mb4 in your MySQL panel.

Also, you're using an outdated version of LuckPerms.

**Comment by DevilishDante** [comment]
> 
> 
> Try updating the table encoding to utf8-mb4 in your MySQL panel.
> 
> Also, you're using an outdated version of LuckPerms.

In deed : updating encoding to utf8mb4_bin has solve the issue thnaks you  and have a good day :)
