### ISSUE TITLE
java.lang.IllegalArgumentException: group.default

### ISSUE THREAD

**Issue by EmanYm** [lucko/LuckPerms#299]
[This console error](https://hastebin.com/ofebafuluj.vbs) happens every time someone joins the server.
[This](https://hastebin.com/ivedoxibah.cs) is my default-assitgnment in the conf file.

The guest group has only five nodes.  Is there a way I can instead put those nodes directly on the default group on the database (then I can just get rid of guest) or is the way I'm doing it better?

LP 3.1.51 (You're probably going to suggest updating to 3.2.7)
Spongeforge 5.2.0 Build 2344

Update
I got [this error](https://hastebin.com/uyocugapoz.sql) when checking an offline player

**Comment by lucko** [comment]
You need to wrap 'group.default' in angle brackets, like: '<group.default>'

And yeah, you can just set those permissions directly onto the default group.
