### ISSUE TITLE
Support for ParseOther extension for PlaceholderAPI for offline players

### ISSUE THREAD

**Issue by democracycraft** [lucko/LuckPerms#2990]
### Description

Currently, I am unable to use the PlaceholderAPI ParseOther extension to return LuckPerms prefixes for players that are offline. I would like this to be possible, as it can really help. I understand reading a previous issue about offline placeholders that unless PAPI is async it wouldn't be added - however we would really appreciate the feature. Perhaps making it optional?

### Proposed behaviour

Placeholders such as ``%parseother_{{username}}_{luckperms_prefix_element_highest_on_track_gov-jobs}%'`` work and do not return blank for offline players.

**Comment by lucko** [comment]
> I understand reading a previous issue about offline placeholders that unless PAPI is async it wouldn't be added - however we would really appreciate the feature. Perhaps making it optional?

Without this, it is not possible for us to add the feature. It's not a question of not wanting to - simply, it is not possible.
