### ISSUE TITLE
Context doesnt work for velocity

### ISSUE THREAD

**Issue by jokbon** [lucko/LuckPerms#2992]
###**Description:**
Context server = hub 
Doesnt work for velocity commands.
By removing context, permision starts to work.

###**Image:**
image with explaination:
https://ibb.co/HH9Rk3f

###**Details:**
Server: yatopia
Proxy: velocity
Java: 16
Windows 10
Server name inside velocity configuration: hub
Server name inside luckperms configuration: hub
Proxy name inside luckperms configuration: proxy
Mysql: conected, and contains luckperms table
Mysql: opens global (synched) configuration with /lp
Synch set: 3 minutes
World name: world

**Comment by lucko** [comment]
Try setting it with `server=proxy world=hub` :)
