### ISSUE TITLE
Error TIMED OUT when connecting to MySQL database

### ISSUE THREAD

**Issue by TheDogHusky** [lucko/LuckPerms#2994]
### Description

When I'm trying to connect LuckPerms on a MySQL database, its timing out... But when I connect LuckPerms to this same database in another server, it work succesfully.

### Reproduction steps

1. Open config.ylm file
2. enter the database infos (username, password, etc..) and change storage-method to MySQL
3. restart server

### Expected behaviour

LuckPerms connects to the database and I can synchronize my perms on differents servers.

### Environment details

* Server type/version: `Spigot 1.12.2` and for the server chere it connect succeffuly: `Spigot 1.15.2`
* LuckPerms version: `LuckPerms-Bukkit-5.2.35`

https://gist.github.com/TheDogHusky/9b9423c1d72d9eaaceb895ccc2ce3ec5

**Comment by TheDogHusky** [comment]
I cannot copy all the error, sorry... My GitBash is impossible......

**Comment by benwoo1110** [comment]
```
Caused by: me.lucko.luckperms.lib.mysql.cj.exceptions.CJCommunicationsException: Communications link failure
```
Your database just cant be access by your server, nothing much luckperms can do.
see https://luckperms.net/wiki/Storage-system-errors#luckperms-cannot-connect-to-my-mysql-server

**Comment by TheDogHusky** [comment]
We cannot connect 2 luckperms tu one database ?

**Comment by TheDogHusky** [comment]
I see the wiki, but if I want to connect 3 luckperms to the same database, I need to reduce the luckperms connections ? Per default, it’s 10 but I need to change to 3 ou 4 ?

**Comment by benwoo1110** [comment]
The error you sent has nothing to do with the max-connection limit, luckperms isn't even able to communicate with your database server.

**Comment by TheDogHusky** [comment]
Oh I have found the problem, it is from thé database. You can close this issue.
