### ISSUE TITLE
LuckPerms failing to start

### ISSUE THREAD

**Issue by Nezz202** [lucko/LuckPerms#2995]
### Description

I have just updated my plugin version to the latest, alongside updating Paper to 1.16.5#599. The plugin is failing to start with the error here: https://pastebin.com/Q0cS9nif
I have checked the config file, and it seems good. I have also already tried deleting the libs folder letting itself re-create. This also did nothing to help the problem :(

### Reproduction steps

Update Plugin/Paper to versions mentioned
Reboot Server
Error in console :(

### Expected behaviour

Plugin starts correctly

### Environment details

* Server type/version: Paper-1.16.5-599
* LuckPerms version: Latest at time of posting v5.3.26

### Any other relevant details

Let me know if you need any more info. Thanks.

**Comment by Nezz202** [comment]
Seems as I was testing/writing this out, a fix appeared :D
I have tested v 5.3.27 and all issues are resolved.

**Comment by powercasgamer** [comment]
Update to 5.3.27
