### ISSUE TITLE
track editor not working

### ISSUE THREAD

**Issue by Takkapi** [lucko/LuckPerms#2997]
### Description

LuckPerms track editor command is giving an error

### Reproduction steps

1. Run /lp track dronators editor

### Expected behaviour

``` 22:30:03 [SEVERE] java.lang.IllegalArgumentException: holders is empty`

22:30:03 [SEVERE]     at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)

22:30:03 [SEVERE]     at me.lucko.luckperms.common.webeditor.WebEditorRequest.generate(WebEditorRequest.java:90)

22:30:03 [SEVERE]     at me.lucko.luckperms.common.commands.track.TrackEditor.execute(TrackEditor.java:96)

22:30:03 [SEVERE]     at me.lucko.luckperms.common.commands.track.TrackEditor.execute(TrackEditor.java:54)

22:30:03 [SEVERE]     at me.lucko.luckperms.common.command.abstraction.ParentCommand.execute(ParentCommand.java:109)

22:30:03 [SEVERE]     at me.lucko.luckperms.common.command.abstraction.ParentCommand.execute(ParentCommand.java:45)

22:30:03 [SEVERE]     at me.lucko.luckperms.common.command.CommandManager.execute(CommandManager.java:264)

22:30:03 [SEVERE]     at me.lucko.luckperms.common.command.CommandManager.lambda$executeCommand$1(CommandManager.java:166)

22:30:03 [SEVERE]     at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764)

22:30:03 [SEVERE]     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)

22:30:03 [SEVERE]     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)

22:30:03 [SEVERE]     at java.base/java.lang.Thread.run(Thread.java:831) ```

### Environment details

* Server type/version: `Spigot` running version `1.16.5` build `latest`
* LuckPerms version: `latest`

**Comment by underscore11code** [comment]
Few things:
* `latest` is not a version number. Please include the actual version numbers (both server & lp version can be found in `/lp info`). Most likely cause is you are on an out of date version of LP.
* If it's not outdated, seems like it's an issue with the permission data. Please send a `/lp editor` link
