### ISSUE TITLE
Issue with LuckPerms

### ISSUE THREAD

**Issue by Jay9519** [lucko/LuckPerms#300]
First off I want to say so far this mod is awesome
I recently converted from pex 2 days ago and a great mod I've been using with pex is a mod called OreAlerts.
In short it shows the admin team when players mine ores, but unfortunately it doesn't work with this luckperms mod, the permission node is correct as I have triple checked it.
I have spoken to the OreAlerts creator and he says to talk to you guys as he doesn't code against specific permissions systems, 
so it must be from this mod thats cause it not working?
SpongeForge-1.10.2-2281-5.2.0-BETA-2353
LuckPerms-Sponge-3.2.6
OreAlerts-1.2

**Comment by lucko** [comment]
Yeah, and I don't code against specific mods. (that's a bit of a silly argument, and not very helpful!)

It's possible that the permission checks being executed on the forge side aren't making their way to LP. You'd need to check if this was the case using /lp verbose.
