### ISSUE TITLE
Server Crash/Internal Error when Tab-Completing Command Inside of /execute

### ISSUE THREAD

**Issue by GoldMiner496** [lucko/LuckPerms#3000]
### Description

I was messing around with /execute, trying to accomplish something completely unrelated to LuckPerms, but stumbled upon this issue anyway. As far as I understand, only vanilla commands can be used in /execute, but the tab-complete menu shows a couple options from LuckPerms. Curious as I am, I started messing around with it, and got an "internal error while attempting to tab-complete this command." The first time I tried, it completely crashed the server.

### Reproduction steps

1. Start typing /execute as <player> run 
2. Put a LuckPerms command in after run
3. Put in an argument, once you hit space it errors out.

### Environment details

* Server type/version: `Paper` running version `1.16.5` build `603`
* LuckPerms version: `v5.3.29`

### Any other relevant details

[Here's the gist of the initial crash report](https://gist.github.com/GoldMiner496/507d2608a80fde4aad9bbb6159d51850)
[Here's the gist of the console error when trying to autocomplete](https://gist.github.com/GoldMiner496/c958b2436ead7c8eaa64d73a67f358eel)
[Here's a link to a YouTube clip of what I was doing](https://youtu.be/aa1TCvexEGY)

I thought it would be best to report here because it was a LuckPerms command that caused the issue, but I'm not super great at reading error logs, so if it needs to go somewhere else I'd be glad to post elsewhere.

**Comment by lucko** [comment]
Strange error, I think if anything it might be a Paper problem. Could you try updating to a newer build to see if it fixes the problem? If not, might be worth reporting it over there.
