### ISSUE TITLE
High tick usage when using DiscordSRV JDBC connection

### ISSUE THREAD

**Issue by TraceLosu** [lucko/LuckPerms#3003]
### Description
Luckperms is using tons of tick time to do a function called ExpiringCache.get() when DiscordSRV is connected using a database. You can see it from this spark report (https://spark.lucko.me/zBMwyRdauw). This might be DiscordSRV's issue, but the fact that It is luckperms that's showing up on the spark report is confusing to me, which is why i opened the issue here.

### Reproduction steps

1. Create a Waterfall server, an Airplane server, and a MySQL database with roughly 100ms ping.
2. Add Luckperms to waterfall server and airplane server, both using the same MySQL database for storage.
3. Add discordSRV to airplane server and add JDBC string to connect to the database.
4. Run the servers and add players

### Expected behaviour
Server should run normally with no lag from LuckPerms or DiscordSRV. But from running a spark report, it'll show that Luckperms is using most of the server resources on a function called ExpiringCache.get(). This leads to tick spikes of 100ms to 3000ms.

### Environment details
* Server type/version: `Airplane` running version `1.16.5` build `f5fb024`
* Server type/version: `Waterfall` running version `1.16.5` build `412`
* LuckPerms version: `v5.3.30`
* DiscordSRV Version: `1.22.0`

**Comment by lucko** [comment]
Try disabling the LuckPerms context integration in DiscordSRV, I imagine that is probably what the problem is.

**Comment by lucko** [comment]
It's a known issue: https://github.com/lucko/LuckPerms/issues/2788#issuecomment-750596964

@Vankka did you manage to get anywhere at the DSRV end? If not, it might be worth automatically disabling the contexts integration if the user is using MySQL...

**Comment by lucko** [comment]
Ah I should've done some research first, it seems you have, awesome! https://github.com/DiscordSRV/DiscordSRV/commit/e6e4fa3b53d7862a3b6240badef27b3b59ca70d9

@TraceLosu Are you sure you're using an up-to-date version?

**Comment by Vankka** [comment]
The version specified by OP is up-to-date. I've also tried looking through some of the parts that could be the culprit, but haven't found anything. Also not helping matters, the spark report doesn't show any children for ExpiringCache for some reason (I'm guessing it's not taking 2.5s itself)

**Comment by lucko** [comment]
> Also not helping matters, the spark report doesn't show any children for ExpiringCache for some reason (I'm guessing it's not taking 2.5s itself)

`ExpiringCache` is a *cache* - and has measures in place (locking) to ensure that only one thread does the actual calculation while the other threads wait.

I think this line is what's causing the problem:

https://github.com/DiscordSRV/DiscordSRV/blob/41b8f04815b028463cbccec42664943b94c199a6/src/main/java/github/scarsz/discordsrv/hooks/permissions/LuckPermsHook.java#L126

It should *always* use the cached value.

**Comment by Vankka** [comment]
`getDiscordId` provides the cached value if there is one, and players that are online are kept in the cache (unless mysql takes >30 seconds to respond to the query, which I doubt is happening). I changed it to only use cached data though, it's available on development builds: https://snapshot.discordsrv.com

**Comment by lucko** [comment]
Great, thank you!

**Comment by lucko** [comment]
@TraceLosu Could you confirm if fixed please :)

**Comment by TraceLosu** [comment]
> @TraceLosu Could you confirm if fixed please :)

Will do! Just need to wait until my server's scheduled restart.

**Comment by TraceLosu** [comment]
Yup. The dev build fixed it, no noticable lag.
