### ISSUE TITLE
Huge Database bug who make database timeout

### ISSUE THREAD

**Issue by Keendi** [lucko/LuckPerms#3004]
### Description

❗ Read my conversation with ben to fully understand my problem ❗

The short description of this bug is in the your Discord, when i talk with ben https://discordapp.com/channels/241667244927483904/241667244927483904/837274919095631892

### Reproduction steps

This problem is so strange that it is not known when it occurs. It usually occurs every morning in the morning.
I don't know how to cause this problem.

### Expected behaviour

1. Luckperms went down on all servers (spigots and bungeecords)
2. Players can't join to the server (bungeecord)
3. All players on all servers has giga ping

### Environment details

* Server type/version: Newest Waterfall, Newest Tuinity
* LuckPerms version: LuckPerms-Bukkit-5.3.0.jar, LuckPerms-Bungee-5.3.29.jar

https://paste.lucko.me/cljA8SOKdP
https://paste.lucko.me/Uv5qwerHu0
https://paste.lucko.me/XSUm5JqeFg
https://paste.lucko.me/09i4hm7ygG

### Any other relevant details

I use MariaDB + Redis for spigots and MariaDB + RedisBungee on bungeecords and all servers is connected to the same database.

**Comment by lucko** [comment]
Unless you are specific in explaining the problem, there is not much I can do to help.

I don't have time to trawl through thousands of lines of logs to find where the error is if you don't point it out to me.
