### ISSUE TITLE
Temp group time left placeholder bug

### ISSUE THREAD

**Issue by VojtechAdam29** [lucko/LuckPerms#3005]
### Description

Ok so this bug was here before but it fixed after updating LP to new version but its back again, i have group for 7d but it shows 6d 47h etc.

### Expected behaviour

It should have to result 6d 23h etc.

### Environment details

* Server type/version: `PaperSpigot` running version `1.15.2` build `git-Paper-390`
* LuckPerms version: `v5.3.3`

**Comment by benwoo1110** [comment]
Update placeholder API to its latest dev builds https://ci.extendedclip.com/job/PlaceholderAPI/

**Comment by VojtechAdam29** [comment]
Thanks, helped.
