### ISSUE TITLE
The primary group is not updated in the database

### ISSUE THREAD

**Issue by Sceri** [lucko/LuckPerms#3008]
### Description
After setting the group permission using API to a user, the primary group is not updated in the database.

### Reproduction steps
1. Add a group to the user using the API
2. Look in the database

### Expected behaviour
The database must contain the correct primary group

### Environment details
* BungeeCord/1.16-R0.5-SNAPSHOT (build 1559) 
* LuckPerms version: `v5.3.33`

https://gist.github.com/Sceri/978eca438086011245d3f2a18ded6d4f (used code)

## Before giving:
![before](https://user-images.githubusercontent.com/3617062/116851301-94714100-ac0b-11eb-87cf-1235278d3352.png)

## After giving
![after](https://user-images.githubusercontent.com/3617062/116851376-ae128880-ac0b-11eb-965e-5f5b1559d39d.png)

## Database row after giving:
![database_after](https://user-images.githubusercontent.com/3617062/116851423-c4b8df80-ac0b-11eb-8789-8139071ac593.png)

Apparently, the primary group is not updated in internal PrimaryGroupHolder when using the API. Therefore, a wrong value is written to the database when saving. But at the same time everything is fine in the cache.

**Comment by lucko** [comment]
See https://luckperms.net/wiki/Configuration#primary-group-calculation

(although the wiki is actually a bit out of date, the default is `parents-by-weight` everywhere now)

**Comment by emilyy-dev** [comment]
Just tested this and the primary group only updates in the metadata cache when using the API, and not in the underlying `PrimaryGroupHolder`. Using the `parent set|add` commands actually work as expected.
`User#setPrimaryGroup(String)` returns `FAIL_ALREADY_HAS` because it checks against the cached metadata before applying it, even though it differs.

**Comment by lucko** [comment]
Fixed by the above commit, thanks
