### ISSUE TITLE
Database cleared / h2

### ISSUE THREAD

**Issue by FelsonMW** [lucko/LuckPerms#3009]
The Database was cleared after reboot, there was also an error.
We have a method database - h2.

log error:
https://pastebin.com/MP5zwJpc

I tried to delete uuid players, the error disappeared, but there is no base.

Yatopia 1.16.5
LuckPerms 5.3.3 (but later we updated to 5.3.33)

**Comment by lucko** [comment]
Seems like your database has become corrupted in some way. I suggest reverting to a backup if you have any.

Unfortunately, there is not much I can do to help.
