### ISSUE TITLE
Plugin does not update Player Name in YAML Storage after a name change.

### ISSUE THREAD

**Issue by hatten33** [lucko/LuckPerms#301]
After tracing an issue with my chat plugin, I have come to the realization that after a user changes their name, the name field in their YAML file is not updated and as such, causes issues when Vault hooks are called.

**Comment by lucko** [comment]
Which platform? Sponge/Bukkit?

**Comment by mikroskeem** [comment]
@lucko Hint: Vault ;-) So it is Bukkit

**Comment by lucko** [comment]
Try that.

**Comment by lucko** [comment]
Is this fixed?
