### ISSUE TITLE
Editor error when players > 500

### ISSUE THREAD

**Issue by JerryTheSlime16** [lucko/LuckPerms#3010]
### Description
If you use /lp editor to get to the web editor it will only display 500 players even if a server has more.

### Reproduction steps

1. Get a server that has more than 500 players
2. Run /lp editor
3. See error

### Expected behavior
It will show all the players.

### Environment details
PaperSpigot-534
LuckPerms v5.3.0

### Any other relevant details
Server this bug was found on has 1681 unique players.

**Comment by underscore11code** [comment]
This is intended functionality, editor links are capped at 500 players.

**Comment by JerryTheSlime16** [comment]
Would it be possible for you guys to add in a config option for more or will that cause things to break?  We are doing a permission rewrite and have been using the editor to make it go faster, but we need to get everyone (not just 500 players).

**Comment by JerryTheSlime16** [comment]
NVM I found a better way to do the perm rewrite using bulk update
