### ISSUE TITLE
PAPI Support doesn't contain NEXT or PREVIOUS elements.

### ISSUE THREAD

**Issue by dynamojake** [lucko/LuckPerms#3011]
Attempting to use something like "%luckperms_prefix_element_next_group_on_track_ranks%"
This doesn't work as there is no element of "Next_group_on_track". 

Same issue applies to "Previous_group_on_track".

Will this be implemented in the future / Is this intentional?

Thanks - 
Jakob!

**Comment by benwoo1110** [comment]
There already is %luckperms_next_group_on_track%

https://luckperms.net/wiki/Placeholders

**Comment by benwoo1110** [comment]
Also this https://github.com/LuckPerms/placeholders/issues will be a better place to for placeholder salted things

**Comment by dynamojake** [comment]
If you read, that's not what I asked. Simply using next group on track returns the NAME of a group, I need a PREFIX. Working with the element part of the placeholder API support, it is indeed missing.

**Comment by lucko** [comment]
"Next group on track" doesn't really fit into the prefix stacking system, unfortunately: https://github.com/lucko/LuckPermsWeb/commit/5602b13cda59b1c4b3b799ea495e3df32f403567

Perhaps you could use a custom placeholder to achieve this. I don't think it's something that is in-scope for LP to support itself.
