### ISSUE TITLE
Prefix Not Showing

### ISSUE THREAD

**Issue by Objectables** [lucko/LuckPerms#3016]
### Description

I have created some groups using LP but prefixes don't show. I've tried 5 different chat plugins, placeholderapi and vault.
Nothing fixed the issue

### Reproduction steps

1. Make a group
2. Save changes
3. Add yourself to the group and type something
4. Prefix doesn't show

### Expected behaviour

I expected the prefix to show.

### Environment details

* Server type/version: `Paper` running version `1.8.8` build `latest`
* LuckPerms version: `vlatest`

**Comment by benwoo1110** [comment]
Does prefix show in `/lp user <user> info`

**Comment by Objectables** [comment]
Yes. Sent from Mail for Windows 10 From: Ben WooSent: Sunday 9 May 2021 12:34To: lucko/LuckPermsCc: Objectables; AuthorSubject: Re: [lucko/LuckPerms] Prefix Not Showing (#3016) Does prefix show in /lp user <user> info—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by benwoo1110** [comment]
> LuckPerms only acts as the source for prefixes / suffixes, it doesn't actually apply them. You need an appropriately configured chat/tablist formatting plugin for them to be displayed. If the values appear correctly when you run /lp user <user> info, LuckPerms is doing its job!

https://luckperms.net/wiki/FAQ#why-are-prefixessuffixes-not-working
https://luckperms.net/wiki/Prefixes,-Suffixes-&-Meta#displaying-prefixes-and-suffixes

**Comment by Objectables** [comment]
What chat plugin should I use?Herochat, EssentialsChat, VentureChat and mChat don’t work. Sent from Mail for Windows 10 From: Ben WooSent: Sunday 9 May 2021 12:59To: lucko/LuckPermsCc: Objectables; AuthorSubject: Re: [lucko/LuckPerms] Prefix Not Showing (#3016) LuckPerms only acts as the source for prefixes / suffixes, it doesn't actually apply them. You need an appropriately configured chat/tablist formatting plugin for them to be displayed. If the values appear correctly when you run /lp user info, LuckPerms is doing its job!https://luckperms.net/wiki/FAQ#why-are-prefixessuffixes-not-workinghttps://luckperms.net/wiki/Prefixes,-Suffixes-&-Meta#displaying-prefixes-and-suffixes—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by jortpepe** [comment]
I'd recommend heading over to the support text channel of the LuckPerms Discord server so we can fully figure out whether this is an actual bug or just a configuration error. Could you ask your question there as well as include any necessary details in the process?
