### ISSUE TITLE
[Suggestion] Minecraft commands as permissions

### ISSUE THREAD

**Issue by DillonB07** [lucko/LuckPerms#3017]
### Description

Would you be able to add vanilla commands to the permissions list?
So the default commands like /trigger, /stop so that you can customise them without using op.

**Comment by benwoo1110** [comment]
That should be the responsibility of the server software to add permissions check to vanilla commands, not luckperms.

**Comment by DillonB07** [comment]
Oops. I meant to put this on the Fabric Luckperms API repo. Sorry!
