### ISSUE TITLE
[MariaDB] Client does not support authentication protocol requested by server. plugin type was = 'caching_sha2_password'

### ISSUE THREAD

**Issue by RalphORama** [lucko/LuckPerms#3018]
### Description

Using MariaDB 8.0.22-0ubuntu0.20.04.3 as a backend fails because the plugin does not support `caching_sha2_password`.

### Reproduction steps

1. Install LuckPerms
2. Configure MariaDB backend in config.yml as usual
3. Start server
4. If specified MariaDB server is version 8.0 or higher and using `caching_sha2_password` as the password algorithm, the error appears in console.

### Expected behaviour
LuckPerms authenticates with MariaDB and uses it as a storage backend

### Environment details

* Server type/version: `Tuinity version git-Tuinity-"b12d0cc"` running version `1.16.5`
* LuckPerms version: `LuckPerms-Bukkit-5.3.37`
* MariaDB version: `8.0.22-0ubuntu0.20.04.3`

https://pastebin.com/Vc984jsm

### Any other relevant details

I do not have this issue with any of my other plugins that connect to the same MariaDB server. This issue is specific to LuckPerms

**Comment by einfachBlu** [comment]
Have the same Issue with tuinity 1.16.5 and Ubuntu 18.10.

Native Protocol is also not working. So no possibility to connect to mysql with that configuration yet.

@RalphORama you got a workaround?

**Comment by BomBardyGamer** [comment]
According to [this](https://mariadb.com/kb/en/authentication-plugin-sha-256/), MariaDB doesn't currently support this authentication mechanism. There is an issue linked on that page that may explain why, but you can find it [here](https://jira.mariadb.org/browse/MDEV-9804) if you're too lazy to find it for yourself on that page.
