### ISSUE TITLE
Incorrect prefixes shown multiple tracks

### ISSUE THREAD

**Issue by jortvanleenen** [lucko/LuckPerms#3020]
### Description
I seem to be running into a bug related to multiple tracks and prefix stacking. I have got three tracks set up: donateur (donator track), staff (staff track) and general (server specific ranks, similar to the 'mine' prefixes of a prison server). When I promote myself using '/lp user <name> promote staff', for example, I correctly get set to the first (from default) on the track, which would be builder in this case. This somehow messes up my prefixes, as I get shown the highest prefix of the general track, the builder staff prefix and the highest prefix of the donateur track. I suppose this has something to do with builder being technically above the highest ranks in those tracks, but I have set LuckPerms up to stack prefixes using highest_on_track_<tracknames> and the builder rank is not on either of the tracks and I should not be as well, so shouldn't they be silently ignored?

### Reproduction steps
I feel like the easiest option would be to make use of the same chat formatting plugin and configuration, LP prefix options (for both, see the 'any other relevant details' section) and lp editor (https://luckperms.net/editor/LNE6TQKVJN).

OR

(I have done the steps below in the following editor: https://luckperms.net/editor/3cp79MJZME)
1. Create three groups like: group1 (weight: 50, prefix: group1), group2 (weight 100, parent: group1, prefix: group1) and group3 (weight: 150, parent: group2, prefix: group3).
2. Create three tracks and set them up like this: track1: default -> group1, track2: default -> group2 and track3: default -> group3.
3. Go to the LP config.yml and set the prefix formatting to (make use of chosen track names):
    format:
      - "highest_on_track_track1"
      - "highest_on_track_track2"
      - "highest_on_track_track3"
    duplicates: first-only
    start-spacer: ""
    middle-spacer: " "
    end-spacer: " "
4. Reload LP config using /lp reloadconfig
5. Run /lp user <username> promote track3
6. Type something in the game.
7. See that this will result in the prefixes showing up of group 1 and 2 as well, instead of just group 3.

### Expected behaviour
[Onbekend] shows up from the general track, followed by [Builder] from the staff track and the donateur track is silently ignored as the duplicate setting is set to first-only (otherwise it would be [Onbekend] again from the default rank).

OR

The prefix of group1 should show up, the prefix of group2 should not show up (duplicate setting is set to first-only) and the prefix of group3 should be shown. For more information see the other expected behaviour explanation.

### Environment details
*Chat formatting: EssentialsX Chat 2.19.0-dev+115-071f995
*Proxy type/version: Velocity 1.1.5
* Server type/version: Purpur (Spigot fork) build 0190 running version 1.16.5 (2x)
* LuckPerms version: `v5.3.39`

### Any other relevant details
My EssentialsX Chat name format is set to {DISPLAYNAME}.
My LP prefix format is set to:
  prefix:
    format:
      - "highest_on_track_general"
      - "highest_on_track_staff"
      - "highest_on_track_donateur"
    duplicates: first-only
    start-spacer: ""
    middle-spacer: " "
    end-spacer: " "

These screenshots show my prefix with the default rank, as if the user just joined for the first time and the tracks I currently have.
![Screenshot (184)](https://user-images.githubusercontent.com/12221344/117817915-607bc880-b268-11eb-96b2-1d4e7657b5fb.png)
![Screenshot (185)](https://user-images.githubusercontent.com/12221344/117817920-61acf580-b268-11eb-83ab-df4cd0a1082a.png)
These screenshots show my prefix after using /lp user jortpepe promote staff (making me a builder) and the track I currently have.
![Screenshot (186)](https://user-images.githubusercontent.com/12221344/117817923-61acf580-b268-11eb-82b9-d2b663c6f95e.png)
![Screenshot (187)](https://user-images.githubusercontent.com/12221344/117817926-62458c00-b268-11eb-90df-9fcad5820cb3.png)

**Comment by Laarryy** [comment]
Hi - thank you so much for the detailed issue. Could you please send a screenshot also of `lp user <name> meta info`? If you're still able to reproduce on the latest version of LuckPerms from https://luckperms.net that is!
