### ISSUE TITLE
Spam & thread hang

### ISSUE THREAD

**Issue by AoElite** [lucko/LuckPerms#3021]
### Description
Server has been running fine for weeks (still daily restarts) and then it randomly died. Starting spamming luckperm messages saying "unloading user data for" and blocked the main thread which led to everyone being timed out.

### Reproduction steps
I have no idea how to reproduce this error.

### Expected behaviour
To not spam messages and block the thread.

### Environment details
Latest Tuinity (1.16.5)
LuckPerms version: 5.3.16

https://pastebin.com/fTuymg89

### Any other relevant details
None

**Comment by lucko** [comment]
Disable `debug-logins` in the LP config.yml
