### ISSUE TITLE
LuckPerms overwrites or stops some of the Multiverse Worldsettings like Gamemode  

### ISSUE THREAD

**Issue by M4RCJO** [lucko/LuckPerms#3023]
How It looks LuckPerms overwrites or stops some of the Multiverse Worldsettings like the Gamemode for each World.
Without enabling LuckPerms the Settings will work - after enabling LuckPerms the players Gamemode are still the same.
Multiverse will not change the Gamemode if you will enter an other World.

**Comment by benwoo1110** [comment]
i don’t believe luckperm’s conflict with multiverse. Likely you just have bypass permission of mv.bypass.gamemode.* set with luckperms.

**Comment by M4RCJO** [comment]
Ive testet any solution to bypass permissions but it doesnt work ... the only solution which workes is to change the LuckPerms config.yml in Line 504 from "apply-default-negated-permissions-before-wildcards: false" to "apply-default-negated-permissions-before-wildcards: true" and also change Line 676 from "resolve-command-selectors: false" to "resolve-command-selectors: true" and restart the server

**Comment by M4RCJO** [comment]
I have an Server on which the First-Join-World is only in adventure mode because i dont want others to be able to destroy or modify any stuff i build in this World (SPAWN) - like on other servers and their lobbys or so - the problem ive have starts after i updating the server from 1.16.2 to 1.16.5 ... befor that all players will change the gamemode automatically if they enter an other world - after that all players still stays in adventure mode and so they cant do anything in there own buildings on the other worlds. only an operator were able to change the gamemode of the players until we have this "solution" enabled - but its not the way it have to be i think - its still more like cheating over

**Comment by benwoo1110** [comment]
This doesn’t sounds like a luckperms conflicting or overriding with Multiverse. LP has nothing to do with changing players gamemode. If it work without LP means you have set some permissions that cause a change in behaviour in MV.

**Comment by M4RCJO** [comment]
I havent change anything ... still setup the server and put the plugins we need into it ... just setup the multiverse maps with the standard behaviour for the maps you also can choose in standard singleplayer like gamemode, maptype, cheats off and so on ... i still have used the commands which was provided by the plugins and also setup the portals to switch within the maps ... everything went as planned up to the point where we took luckperms in ... 

especially as it turned out during testing that there were changes with Luckperm and not without ... 

sorry, but where should the error came from when not by Luckperms in its settings, because without Luckperms everything went as wanted and with Luckperms then suddenly these errors or changes in behaviour were there ... so it was obvious that luckperm suddenly prevented or no longer allowed something that was intended by multiverse, because with luckperms you suddenly no longer had the rights to do so, or luckperms changed the dependencies or sequences of the rights holders

as I said - without luckperms no problems - with luckperms then yes - so it looks how i said

**Comment by benwoo1110** [comment]
Luckperm is a permission plugin, if you remove it obviously permission set in luckperms is no longer present, and every plugin that uses permissions checking will be affected. In this case, probably some gamemode related things in MV.
