### ISSUE TITLE
flat file database synchronization 

### ISSUE THREAD

**Issue by Hellohi3654** [lucko/LuckPerms#3024]
### Description

Hey
Just wondering if it would be possible to use pluginmsg to sync data between flatfile (H2 mainly) databases.
I have been using MariaDB to sync my permissions but sometimes it decides to disconnect if my VPS has a quick restart (This happens quite often for me).
Also it would mean that no external server would be needed to sync permissions.

### Proposed behaviour

Luckperms would use pluginmsg channels to sync permissions, etc. between flatfile databases (H2, SQLite). 
I'm guessing the only way to do this would be too sync from backend servers to the bungee server then to the other backend servers.

This would eliminate 90% of all downtimes my server experiences.

Really hope this can be added

**Comment by benwoo1110** [comment]
I don’t see have flat file syncing is a good idea. Plugin message only works if players is online on the server iirc. Anyways many ppl use sql database without issues.

**Comment by Hellohi3654** [comment]
> I don’t see have flat file syncing is a good idea. Plugin message only works if players is online on the server iirc. Anyways many ppl use sql database without issues.

Yes SQL is fine for me until the connection is interrupted briefly or our database restarts

This causes Luckperms to error and not let anyone join

Maybe another syncing method needs to be made that doesn't require a external database

**Comment by emilyy-dev** [comment]
> Maybe another syncing method needs to be made that doesn't require a external database

That is not really possible, the whole design around syncing is that they share a **common** storage, the messaging service does not transfer data, it only tells other LP instances what to reload from storage

**Comment by Hellohi3654** [comment]
> > Maybe another syncing method needs to be made that doesn't require a external database
> 
> That is not really possible, the whole design around syncing is that they share a **common** storage, the messaging service does not transfer data, it only tells other LP instances what to reload from storage

Would PostgreSQL or MongoDB be more stable than MariaDB?

**Comment by benwoo1110** [comment]
That’s is completely dependent on your own database reliability. Free/Poor host provider may be the cause of your issue.

**Comment by Hellohi3654** [comment]
> That’s is completely dependent on your own database reliability. Free/Poor host provider may be the cause of your issue.

Would it be possible to have a main DB (MariaDB or MySQL) then luckperms would sync permissions from the main DB to a local DB (H2) so if the main DB ever went offline luckperms could use H2 until it can reconnect?

**Comment by emilyy-dev** [comment]
"stable" is not really an applicable term I believe, I personally never had any kind of issues with LuckPerms and MySQL. But sure you can try? Those are available options after all.

**Comment by Hellohi3654** [comment]
> > That’s is completely dependent on your own database reliability. Free/Poor host provider may be the cause of your issue.
> 
> Would it be possible to have a main DB (MariaDB or MySQL) then luckperms would sync permissions from the main DB to a local DB (H2) so if the main DB ever went offline luckperms could use H2 until it can reconnect?

Or is this already possible with split storage or something?

**Comment by benwoo1110** [comment]
No split storage is not used for the issue you described. You just need a better database. Your only option is try to source for database type / providers to see what works for it. But the bottom line is, flat file is not an option if you want data syncing.

**Comment by Hellohi3654** [comment]
> No split storage is not used for the issue you described. You just need a better database. Your only option is try to source for database type / providers to see what works for it. But the bottom line is, flat file is not an option if you want data syncing.

Ok. Do you have any database providers you would recommend?
