### ISSUE TITLE
Potential memory leak

### ISSUE THREAD

**Issue by hkkongou** [lucko/LuckPerms#3027]
### Description

Luckperms seem having memory leak problem, i am using luckperms 5.3.39 , when my server run for more than 4 hours, the memory problem start going bigger and bigger, i have done a heapdump after server have running for 7-8 hours, and the heapdump result show this:

https://cdn.discordapp.com/attachments/835783863497523220/843663122547343370/unknown.png

### Reproduction steps

1. run a server and wait for 5-6 hours+
2. get a heapdump
3. use the heapdump using eclipse

### Expected behaviour

This problem makes my server G1 Old activate, by using aikar's flag, there should only be G1GC working, without memory leak, the server tps should be stable

### Environment details

* Server type/version:  This server is running Purpur version git-Purpur-1084 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
* LuckPerms version: LuckPerms version 5.3.39

**Comment by lucko** [comment]
Please could you upload the .hprof file to something like WeTransfer or Google Drive and send me the link :)

**Comment by hkkongou** [comment]
> Please could you upload the .hprof file to something like WeTransfer or Google Drive and send me the link :)

yes sure, but the file size is huge, 11 GB, i will try to upload to like dropbox, it will take me maybe an hour : (

i also heard that heapdump files have sensitive information, can i send the download link to you privately? thx

**Comment by lucko** [comment]
Sure, you can encrypt the link using Keybase (https://keybase.io/encrypt) and send it that way if you prefer.

My username is `luck`

**Comment by hkkongou** [comment]
like this?
-----BEGIN PGP MESSAGE-----
Version: Keybase OpenPGP v2.1.13
Comment: https://keybase.io/crypto

wcFMAxavkAf6LzVtAQ/+Ovrx6DkudwluO75KwIyvXcAi5cJ2HxGL1CeXu5DAWA3r
8sLFH6xoizwEvJJpurDsU0BkrlIEkIYLtZfLtqsMR4T+9QUEF/NWmvp3WNqd6g+Q
FE423ijjHZa1hjXBMNhb3O0m1Z+Zfk6K+NpXDV66XYyWI7C9vi5X7tvuPl7IkC+K
m/iK7HMYOqXF0oaFVDP3GorpUzF9rEzHJ5A7lIbeLe+LEgn2aystOpVouzMl9jY/
wvwnOkvtVoaElWnNHxc5Uzj49KjD8e4kjNkWuE9fAN0Csgu+HbCLZiz/y+yHfzmN
aK0BNdkh7G9+27jZPJmhWNA+wCKIXwyk4/cW2WfcxZ0KbJ5kZLoGBJcHYQSQYWuq
wGvlJq8kzx9tMLmCy/47hviI+EvLovpytCjDKzBPmrztB7gnPV9XXQKoamaYzGaV
H0LD4hss6i8Z907GtifDQC7BnT52fa4ZsQiARzy3HBt6N8PQjaZlVsB8fps41IH1
qNsrnUFEjffj1GqshM2m+8aczRlcvJcRbDdYV9zqePjI7OkhJv4hXskj/wFEtx5P
JDAajq7ntK1dfxCsrv6GptU9MlMQbwrqjO+PlCNkXyDadFNC7R/wa+rtxHH4cfCC
ux2v39A62tKrkjLxaxXW5rdNAYzH//9ERaDGTGO284MxirhcTXhbPjssSbLzCBTS
hgG7+XnFmWPSQ8Q9aN8U6jQX7EX7TC6sdCAxXNKMcf69lEK9/u6W74qC8NyVwE60
A+R10Q+xCGUtY/jwu+tjsIwfbmUa6Hgi2ox+23dzEowoh7szd+T+Y2UkX5s97CbJ
p9E/u7Mo4YUuRgIyO/3gvTyRebyzoyxo0GJN2ctwchQc7YTAcW7j
=iHJX
-----END PGP MESSAGE-----

**Comment by lucko** [comment]
Perfect, thanks

**Comment by lucko** [comment]
Thanks for that!

Should be fixed by the above commit (in versions >= 5.3.40)
