### ISSUE TITLE
Server crash related to CodeChickenLib and ForgeMultiPart

### ISSUE THREAD

**Issue by FreezyJackalope** [lucko/LuckPerms#3028]
### Description
When LuckyPerms is installed on a 1.12.2 Forge server running Sponge along with CodeChickenLib and ForgeMultiPart, the server crashes when trying to load FMP, but works fine if it only has CCL installed.

### Reproduction steps

1. Install CCL and FMP on a 1.12.2 Forge server running Sponge
      Downloads: https://www.curseforge.com/minecraft/mc-mods/codechicken-lib-1-8 https://www.curseforge.com/minecraft/mc-mods/cb-multipart
2. Install LuckPerms
3. Start server, and watch it crash
      After, try also:
4. Uninstall FMP
5. Restart the server, and it should work fine

### Expected behaviour
The server should run normally, but crashes instead.

### Environment details
Sponge server running Forge 1.12.2
LuckPerms version: 5.3.39
Code Chicken Lib version: 3.2.3.358
Forge Multi Part version: 2.6.2.83

### Any other relevant details
Console print during crash: https://paste.lucko.me/rux44e3ko3
Crash log: https://paste.lucko.me/L7tnLYiRFD

**Comment by lucko** [comment]
As far as I can tell from the console log, this isn't being caused by LuckPerms.
