### ISSUE TITLE
Rank Signs

### ISSUE THREAD

**Issue by LeitoCc187** [lucko/LuckPerms#3029]
Description
Please add a Sign system that lets the players to buy ranks from signs with money from vault or other ecconamy plugins 

Proposed behaviour
the sign format maybe 
sign lines
------------
1.[lp Rank]
2.gourp
3.price
4.context
------------
This would add the gourp listed to the player who clicks the sign and
the context option if left black will add the gourp to the context or 
the server the player is in when clicking when the sign is finished the 
context line would be removed from the sign but will still apply
or
It may use a command like "**/lp ranksign gourp price context**"
and that will turn the sign the admin is looking at in to a rank sign
that anyone can buy from. The command could be more indepth 
than the sign formating so the command may be nicer to use but 
both would work and do the same job 

thank  for reading my ted talk

**Comment by benwoo1110** [comment]
Not the main dev - but I can tell you signs is out of scope of luckperms

**Comment by LeitoCc187** [comment]
> Not the main dev - but I can tell you signs is out of scope of luckperms

aww damn i was kinda hoping it would work i cant find any good rank sign plugins that work with the context the right way

**Comment by lucko** [comment]
Sorry, this is better served by a separate plugin.
