### ISSUE TITLE
Network sync with bungee stops working after a few hours

### ISSUE THREAD

**Issue by BrainStone** [lucko/LuckPerms#303]
I've run into an issue that when a networksync (manually or automatically triggered) is performed the bungee doesn't recive the ping after a few hours of running.
I'm using LP 3.2.7 on my ForgeSponge and Bungee servers. Both are up to date.

**Comment by BrainStone** [comment]
Interesting. The direction `Bungee -> Sponge` works, but `Sponge -> Bungee` doesn't!

**Comment by lucko** [comment]
So it works initially, but then breaks after a while?

I need more info really. Remember the networksync won't work unless there are players connected to that server.

**Comment by BrainStone** [comment]
Yes initially it works and then it breaks. I know that at least one player needs to be connected.

I'll happily provide any infomation you want. I just don't know what you could need.
But as I said, I tried it recently. A networksync (with a player connected!) on the SF server didn't get propagated to the Bungee, but a networksync on the bungee worked without issues.

**Comment by lucko** [comment]
It will just try every 10 seconds to send the message.

https://github.com/lucko/LuckPerms/blob/master/sponge/src/main/java/me/lucko/luckperms/sponge/messaging/BungeeMessagingService.java#L69

**Comment by BrainStone** [comment]
I mean the Sponge server tries to send a message. It even says so in the logs. But the Bungee never recieves it.

**Comment by lucko** [comment]
Are all of your players connecting through the same proxy?

**Comment by BrainStone** [comment]
Yes they are.

**Comment by lucko** [comment]
I don't know why then.

**Comment by BrainStone** [comment]
I could give you access if it would help with debugging.

**Comment by lucko** [comment]
Not really, your best bet is to try to find an error in your proxy logs.
