### ISSUE TITLE
[Paper 1.16.5] Long Console Error / Lag Causing

### ISSUE THREAD

**Issue by PiggiesGoSqueal** [lucko/LuckPerms#3031]
### Description

Today a very long console error appeared regarding LuckPerms and the MySQL database. Players reported increase in lag and my server pinged me in the Discord server informing me it was experiencing extreme lag.

### Reproduction steps

I'm not sure because this has never happened before and it happened randomly.

When a player tried to connect it showed them:
https://cdn.discordapp.com/attachments/696658607001042945/845732502840279050/6877cbb22baa30e4ef12b00bf09421c1.png

### Expected behaviour

This not to happen.

### Environment details

* Server type/version:
This server is running Paper version git-Paper-670 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 45 version(s) behind
Previous version: git-Paper-562 (MC: 1.16.5)
* LuckPerms version: `LuckPerms-Bukkit-5.3.0`

latest.log: https://gist.github.com/PiggiesGoSqueal/a66f3f8f6b1c8d3d0d2d551c86571d62

### Any other relevant details

N/A

**Comment by PiggiesGoSqueal** [comment]
Perhaps has to do with the Mysql version update for more recent versions of Paper? It broke EasyBackup backups for mysql database. I had to downgrade paper to solve it. Perhaps this was the issue here?

**Comment by benwoo1110** [comment]
your sql database basically just disconnected. I don’t really see how it’s linked to paper, unless they really introduce a bug then you should report to them. Tho your version shows your are 40 builds behind. I suggest update both paper and luckperms first.

**Comment by PiggiesGoSqueal** [comment]
> 
> 
> your sql database basically just disconnected. I don’t really see how it’s linked to paper, unless they really introduce a bug then you should report to them. Tho your version shows your are 40 builds behind. I suggest update both paper and luckperms first.

I cannot update Paper until the conflict with EasyBackup is fixed. Also Luckperms I believe is already fully up to date. 

Thanks for the feedback though
