### ISSUE TITLE
Potential memory leak

### ISSUE THREAD

**Issue by hkkongou** [lucko/LuckPerms#3032]
### Description

Luckperms seem having memory leak problem, i am using luckperms 5.3.40 , when my server run for more than 7 hours, the memory problem start going bigger and bigger, i have done a heapdump after server have running for 7-8 hours, and the heapdump result show this:

![image](https://user-images.githubusercontent.com/61608872/119245473-24bbf980-bbac-11eb-846d-a2dc40e967c4.png)

### Reproduction steps

1. run a server and wait for 5-6 hours+
2. get a heapdump
3. use the heapdump using eclipse

### Expected behaviour

This problem makes my server G1 Old activate, by using aikar's flag, there should only be G1GC working, without memory leak, the server tps should be stable

https://timings.pl3x.net/?id=0c4f65be1f3e4025865ab027f62fcb91

### Environment details

* Server type/version:  This server is running Purpur version git-Purpur-1126 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
* LuckPerms version: LuckPerms version 5.3.40

### Any other relevant details

I have reported memory leak problem a weak ago, which is #3027, not sure is it relevant
but i have already installed a new version which should have fixed memory leak 🤔
![image](https://user-images.githubusercontent.com/61608872/119245523-8c724480-bbac-11eb-8829-0a6bc46c69a7.png)

**Comment by hkkongou** [comment]
A keybase private message have been sent to lucko , which have a dropbox download link of hprof heapdump file
-----BEGIN PGP MESSAGE-----
Version: Keybase OpenPGP v2.1.13
Comment: https://keybase.io/crypto

wcFMAxavkAf6LzVtAQ//fII9QcEz2D92L867rfaCxAHGhfxi/JeTxjBHSTirb+ZN
2gPpVBEKfef+FhHh/xm+0Ks8VX3kO/nAd7PV2p/Mt8yceo7tTnutMylYI6Ezy0zJ
E8ZaKgx+94OhmQfQuZsHYpcMWbomGb2Fd7fhUhok2lHMNt9cbN5RfhivpIxJNdlm
68X0nHySv9cEp2Ln8tvRb0rNNoxcHwoTayhSILTiyg6dG/79jPfYyl0yd33etAYx
QMeQirkRzY4u8LFotRh/bW7OiTcWpADipPq6y1vXxPfxSnt8sIVIc+IhHK+rMtHe
wluEeyztHQpPiRVdKFfzo2p/RIfiZzZ5+CwdjCLwM5HhfkwsnvYODKA492A4e5j9
ssrqujU9gtYp+t16z+gXvOuVlVg1C4cg7pQgaR/Z92/0e4B/mpV1g+ScFC2RZ6QB
uaEXe2FrJglmVvKU23etgRpjokvvVBzOAeecHYWSey3t/cyAwtmtjWRtfgRfNyVs
80+8I4Zx3KqzHN//YFPGd66FWG7xdHto23MXJBH+v4WWfxnTFmI6tfLJ0kEFLtbn
IL/U5ispPivv85+oszMX17q6NSupEBItRFUJHc4R5dWYmHqj4Wf0AfbnIjusAHjN
GQXAmfQkd2q8cRTIKF+wKHCDkrVoeDe1G/VRibV2Jow3FJVPj4B+ynRfbAJVe67S
iQG4c/laPr3oEA9ubEEfyBDNjJ4twDn/P2UloXU8uPlttE//gENS2056MkGFEwvk
5DPhBT5NKTYrk7qm6ryuGf3fLcRGzr48/+LLuwH/16M9JyYsZkv+Xw/bEmeLYSoe
thpRITVxi+DmkDxZSPO1+6P2/k+ao2UN0/1V5fisIZj+ijthMRTIVQhE
=M70k
-----END PGP MESSAGE-----

**Comment by lucko** [comment]
Please enable `debug-logins` in the LP config file, then send your console log over after the server has been running for a while.

**Comment by hkkongou** [comment]
> Please enable `debug-logins` in the LP config file, then send your console log over after the server has been running for a while.
here
https://paste.denizenscript.com/View/85008

i used the server i have memory problem to take this report, but turning the config setting on using lp reloadconfig

**Comment by lucko** [comment]
It seems like another plugin on your server is loading user data for lots of players at runtime then not unloading it. Doesn't appear to be a LuckPerms bug

**Comment by hkkongou** [comment]
> It seems like another plugin on your server is loading user data for lots of players at runtime then not unloading it. Doesn't appear to be a LuckPerms bug

if you talk about a plugin that load alot of data and use luckperms, the only one comes out of my mind is grief defender .. but i don't have any envidence 

this is the  plugin list of my server
![image](https://user-images.githubusercontent.com/61608872/119912643-7b4f7c00-bf8e-11eb-9e86-66c0f9d915e0.png)

**Comment by lucko** [comment]
I have no idea, sorry
