### ISSUE TITLE
ERROR WHEN MIGRATING FROM MONGODB TO MYSQL

### ISSUE THREAD

**Issue by alexeses** [lucko/LuckPerms#3034]
### Reproduction steps

1. Open the config.yml file and set example to true.
2. Restart the server
3. Run /lp user example permission set x from the console

### Expected behavior

This morning I migrated from MongoDB to MySQL following the steps indicated in the Wiki, however, the export was successful without fail. More than 1.2 million users exported correctly. However, some of them out of the blue, have had failures since their rank did not have it and I have started to give ranks, however, the problem is generated when:

I give a temporary range to users with the command 'lp user name parent name addtemp rangename 10y global' for example, it jumps a major error. 

I use the latest version of LuckPerms, I doubt very much that this is really the problem. Attached is evidence of the bug.

> Bug: https://paste.minebox.es/nasujuvugu.sql
> User permissions: https://prnt.sc/13bjdbt

It's funny because if I do a /lp editor user and set the time from the editor, it does work but with the NO command, I can only give permanent ranges. 

I hope you can help me, if you need more data, do not hesitate to ask.

**Comment by underscore11code** [comment]
Please follow the issue template.

**Comment by alexeses** [comment]
Hello!

As I well indicated, I don't think it is necessary to attach more information, it is explained in detail everything that happened, you can see all the error, it is not something that requires more information. 

Any ideas?

**Comment by underscore11code** [comment]
You've ignored the reproduction instructions section, and deleted the part where we ask for the **specific** version of LP (`latest` tells us nothing), as well as the server software and it's version. A screenshot of the output of `/lp info` will cover most of the version / software related info.
