### ISSUE TITLE
The [temporary modifier] part of the menu cannot be used

### ISSUE THREAD

**Issue by 157946a** [lucko/LuckPerms#3035]
The [temporary modifier] part cannot be used in the menu. For example, the command is: lp user id permission settemp 1 true 1m replace. I can use the command directly, but it cannot be used in the menu to replace the original time.

**Comment by lucko** [comment]
In the menu?

Assuming you're referring to the LuckPerms GUI plugin, that has nothing to do with the main project.

**Comment by 157946a** [comment]
No, no, I’m not talking about luckperms GUI, I’m talking about trmenu, you cannot use [temporary modifier] in the event section

**Comment by Turbotailz** [comment]
Can you send a screenshot of what you mean?
