### ISSUE TITLE
MongoDB error

### ISSUE THREAD

**Issue by itzJOHv** [lucko/LuckPerms#3036]
### Description
Error with MongoDB

### Reproduction steps

1. Set everything needed for MongoDB in `config.yml`
2. Start your server (bungee/bukkit)

### Expected behaviour
No errors

### Environment details

* Bungee: This server is running Waterfall version git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:e0e464b:421 by md_5
* Bukkit: This server is running Yatopia version git-Yatopia-ver/1.16.5-115 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
* LuckPerms v5.3.42

Log: https://gist.github.com/itzJOHv/4a0624f14f8a63dbc821a5710337a85c

**Comment by lucko** [comment]
That is a MongoDB error and isn't being caused by LuckPerms.

Are you sure you're entering the hostname/port/username/password correctly?

Failing that, please see here for more info: https://luckperms.net/wiki/Storage-system-errors
