### ISSUE TITLE
The [temporary modifier] part of the menu cannot be used

### ISSUE THREAD

**Issue by 157946a** [lucko/LuckPerms#3037]
The [temporary modifier] part cannot be used in the menu. For example, the command is: lp user id permission settemp 1 true 1m replace. I can use the command directly, but it cannot be used in the menu to replace the original time.I am not using luckperms GUI, it is the trmenu plugin. I configured events, that is, when I open the menu, I execute instructions, but I can't use lp user id permission settemp 1 true 1m replace to replace the original time. The prompt is that this has been set. Authority

**Comment by BomBardyGamer** [comment]
This sounds like an issue with whatever trmenu is rather than one with LuckPerms

**Comment by BomBardyGamer** [comment]
Also please do not open duplicate issues

**Comment by 157946a** [comment]
In this way, I went to find the author of trmenu. As for why not reopen it, because I don't know these functions very well.

**Comment by 157946a** [comment]
Since you are the author of luckperms, you should understand a kind of event that will be executed when opening the gui interface. Trmenu is similar to him, and you can use other plugins to cooperate with advanced operations.

**Comment by emilyy-dev** [comment]
If you can run the command manually then that is an indicator LuckPerms is working properly, how trmenus dispatches the command is not something LuckPerms (or any other plugin for all that matters) has to be aware of.

**Comment by lucko** [comment]
This doesn't sound like a LuckPerms issue, I suggest you speak to the author of trmenu

Please don't open another issue on this topic (you can reply here if you need to)
