### ISSUE TITLE
It dont work on Proxy

### ISSUE THREAD

**Issue by LPDMinecraft** [lucko/LuckPerms#3043]
### Description
I have a server with a proxy, mysql and one under server. /lpb for BungeeCord dont work
i have enabled sync. But it still not work and if I  give me over the proxy console /lpb user Cooler_LK permissions set * or lpb.* i cant run the command /lpb

### Reproduction steps

1. Installed it on the server
2. Connected it to MySQL
3. Run /lpb user Cooler_LK permission set *
4. I wrote /lpb
5. No Permissions

### Expected behaviour
I think the Plugin is how broken. It dont check permissions correctly.

### Environment details

* Server type/version: `Paper 1.16.5` `Bungeecord: dont know`
* LuckPerms version: `v5.3.42`

### Any other relevant details

* I saw that, because I cant add the permissions for bungee.* and for plugins from the Proxy server

**Comment by BomBardyGamer** [comment]
It would be much more beneficial, if you haven't already, for you to ask for support with this in our Discord server. You can join it [here](https://discord.gg/luckperms), I'm sure one of the helpers would be happy to help you out.
