### ISSUE TITLE
Chat and Tablist

### ISSUE THREAD

**Issue by LPDMinecraft** [lucko/LuckPerms#3044]
### Description

Please add an config, wich manage all about prefixes for the tablist and the chat and
over the name, is over the skin ingame.

**Comment by BomBardyGamer** [comment]
LuckPerms does not manage tablist and chat formatting itself, that is the responsibility of third-party plugins, so if you desire this feature, you would be best to ask the author(s) of the third-party plugin that you have chosen to use.
