### ISSUE TITLE
In game gui for perms

### ISSUE THREAD

**Issue by notahumanthatisimportant** [lucko/LuckPerms#3045]
### Description

Title

### Proposed behaviour

Make command like /lp promote open a chest with different ranks to allow you to easier promote and demote people in game cause rn its a bit of a pain, especially if they have a high rank cause then you have to do the command for every rank

**Comment by notahumanthatisimportant** [comment]
Love the web editor btw

**Comment by benwoo1110** [comment]
There is a set track command for you to set it directly a user to any rank in a track. See https://luckperms.net/wiki/Parent-Commands#lp-usergroup-usergroup-parent-settrack-track-indexgroup-context

**Comment by notahumanthatisimportant** [comment]
But still a gui would be nice

**Comment by emilyy-dev** [comment]
> But still a gui would be nice

See https://github.com/lucko/LuckPerms/issues/619#issuecomment-353216667

**Comment by lucko** [comment]
~3 year old comment still holds true as ever 😆
