### ISSUE TITLE
Problem with the default group

### ISSUE THREAD

**Issue by Guest1131** [lucko/LuckPerms#3047]
### Description
Hi, I have a problem with the latest build of Luckperms, on spigot server 1.13.2

If I put the group Founder, when I exit the game and re-enter, I find myself automatically no longer Founder, but the default group. I also tried on spigot 1.8.8, and everything works perfectly.

The problem there is only on 1.13.2

### Reproduction steps

Use /lp <player>parent set <any group other than the default>. 

Exit and re-enter the server.

Luckperms version : v.5.3.42

**Comment by Guest1131** [comment]
The Founder group is just an example, it can be any group.

**Comment by lucko** [comment]
Check your console for any errors, sounds like it's failing to save to storage.

**Comment by Guest1131** [comment]
In the consolel, there is no error, and the problem is only with spigot 1.13.2
