### ISSUE TITLE
My luckperms editor is not working correctly.

### ISSUE THREAD

**Issue by peanutpiggylol** [lucko/LuckPerms#3048]
Btw my luckperms is the latest.

so i go to the editor make changes to the default group and i need to save it so i do i get the code thing and i paste it into my game. it said "No changes were applied from the web editor, the returned data didn't contain any edits." ok so i go on my alt account and it did not work.

### Reproduction steps
I went to the Luckperms editor after i did /lp editor, i changed the default group with some commands i added, i saved it, i got hthe command which looks like this: /lp applyedits (some numbers here and letters I did not want to put the actual stuff)

1. Open the config.yml file and set example to true.
2. Restart the server
3. Run /lp user example permission set x from the console

### Expected behaviour
I expected that the editor changer command would work.

### Environment details

* Server type/version: `Spigot` running version `1.16.5` build `???`
* LuckPerms version: `v5.3.3

**Comment by benwoo1110** [comment]
I hope you are pressing the + button on the right when adding permissions. I suggest taking screenshot/short video of you adding and saving perms. The editor link and apply edits code is safe to share.
