### ISSUE TITLE
Storage system error

### ISSUE THREAD

**Issue by LeBaasti** [lucko/LuckPerms#3049]
### Description

When I start the proxy running on latest Waterfall, I got an error message.

### Reproduction steps

Configure the database settings and start the server.

1. Open the config.yml file and set example to true.
2. Restart the server
3. Run /lp user example permission set x from the console

### Expected behaviour

I thought it works.

### Environment details

* Server type/version: `Waterfall` running version `1.8-1.16.5` build `427`
* LuckPerms version: `v5.3.42`

https://gist.github.com/LeBaasti/08b1d89a6c97a0ddd5e12ae6dbef1477
https://gist.github.com/LeBaasti/5381b887e81814c195e6ac819d5e9f42

**Comment by benwoo1110** [comment]
You database user permission is wrong, isn't a luckperms issue. You can see https://luckperms.net/wiki/Storage-system-errors or google on how to set user access to db tables.

**Comment by LeBaasti** [comment]
So now it connects to the database on the proxy, but not on the sub-servers.
https://gist.github.com/LeBaasti/ad576892eb2fc38d73a6782accb78e83
