### ISSUE TITLE
Suggestion: "/lp search" type feature but for meta

### ISSUE THREAD

**Issue by gone-incognito** [lucko/LuckPerms#3054]
#### Description
I was wondering if it would be possible to add a ``/lp search`` type feature but instead of searching for permissions, it looks at meta (when I say meta I am talking about ``meta set <key> <value>`` commands etc)

#### Proposed behaviour
This will allow server owners/admins to quickly search for a specific meta key when needed.

**Comment by Turbotailz** [comment]
Do you want to return a set of permissions with the specific meta key set?

The web editor offers this but would probably be good for the plugin to do as well.

**Comment by emilyy-dev** [comment]
The search command can also search with lookup wildcards in the exact same manner one does with bulk updates, you'd run something like `/lp search ~~ meta.<key>.%`

**Comment by gone-incognito** [comment]
Thank you for the super fast replies @Turbotailz @emilyy-dev ``/lp search ~~ meta.<key>.%`` is 100% what I was looking for, thank you so much!
