### ISSUE TITLE
Errors on Server Shutting Down

### ISSUE THREAD

**Issue by Fyrlex** [lucko/LuckPerms#3057]
### Description

When shutting down my server, LuckPerms sends the following error: https://hastebin.com/urafirumuz.md

### Reproduction steps

I do not know exactly how to reproduce it aside from turning off my server.

### Expected behaviour

It would be expected to not have these errors, but no issues have been noticed yet.

### Environment details

Tuinity 1.16.5 latest build
Java 8
LuckPerms v5.3.42
MySQL Database

https://hastebin.com/urafirumuz.md

### Any other relevant details

No issues are present yet, but I am concerned about some issues with the connection to the Database.

**Comment by lucko** [comment]
How are you shutting down your server?

Do you have any plugins which use the LuckPerms API to load user data on shutdown, perhaps?
