### ISSUE TITLE
LuckPerms commands not working in Fabric

### ISSUE THREAD

**Issue by MoreFoxBeans** [lucko/LuckPerms#3058]
### Description

LuckPerms commands are not working in Fabric.

### Reproduction steps

Run /lp + anything

### Expected behaviour

I expected it to work like in Spigot I guess?

### Environment details

* Server type/version: `Fabric` running version `1.16.5` build `???`
* LuckPerms version: `5.3.9`

### Any other relevant details

It just says `[LP] Running LuckPerms v5.3.9.` every time I run a command

**Comment by emilyy-dev** [comment]
As per the usage guide (https://luckperms.net/wiki/Usage), you need to give yourself permissions to use LP from the server console by running `lp user <user> permission set luckperms.*`

**Comment by MoreFoxBeans** [comment]
Thanks! Sorry for not reading the guide, I thought it would be like Spigot and give opped players perms automatically.
