### ISSUE TITLE
Can't connect to the MongoDB database and all parameters are correct

### ISSUE THREAD

**Issue by Adri121221** [lucko/LuckPerms#3062]
### Description

Hi. I have MongoDB in my LuckPerms config and it was working well, but now it has been throwing this error recently, and I don't know why.

### Reproduction steps

1. I connect luckperms to MongoDB database
2. I turn on the server
3. The error

Paper: 1.8.8
LuckPerms version: 5.3.42

Error:
https://pastebin.com/d7qivYhL

**Comment by underscore11code** [comment]
Your DNS is having issues by the looks of it, that's outside of LP's control. Ensure your network connection is working properly.

**Comment by Adri121221** [comment]
I have my server in a hosting company, so i can't check my network connection

**Comment by underscore11code** [comment]
Talk to their support then, nothing LP can do about it.

**Comment by Popeye4242** [comment]
@lucko I noticed that you closed a lot of these issues without adressing them properly. You can easily reproduce this by creating a free cluster on MongoDB Atlas and using the srv connection string in the config. 
IMO it is not an issue with the driver but rather the way your plugin handles MongoDB connection strings. 

You should be able to just paste `mongodb+srv://dbUser:<password>@mycluster.awfcu.mongodb.net/myFirstDatabase?retryWrites=true&w=majority` for example and be fine. The issie is not an unknown host as many people (with half knowledge) claim. This is definitly a bug.

**Comment by lucko** [comment]
This is supported already:

https://github.com/lucko/LuckPerms/blob/4598435dd4e1e3187f4ed58e770785ec08878c7d/bukkit/src/main/resources/config.yml#L164-L166
