### ISSUE TITLE
Servercrash with Error: Exception in server tick loop

### ISSUE THREAD

**Issue by DaisukeVN** [lucko/LuckPerms#3064]
### Description

Servercrash on startup.

### Reproduction steps

Server crashed on startup with error: exception in Server tick loop.

### Environment details

Server: Fabric 0.11.3 - MC-Version: 1.16.5
Mod Version: 5.3.45

[crash-2021-06-12_00.47.04-server.txt](https://github.com/lucko/LuckPerms/files/6641240/crash-2021-06-12_00.47.04-server.txt)

**Comment by lucko** [comment]
Doesn't seem to be a LuckPerms issue

**Comment by DaisukeVN** [comment]
But if not LuckPerms. Which mod then? When I remove Luckperms then the Server runs perfectly.
