### ISSUE TITLE
Luckperm with an older bungeecord

### ISSUE THREAD

**Issue by Nono84569** [lucko/LuckPerms#3065]
Hey, I was wondering how can I get the luckperm bungee version when the latest version of bungeecord was the #1119?
I don't know if my question is understandable but I'm using the #1119 version because all my server are on 1.7.10 and I'm trying to find the version of the luckperm bungee who's working with.

**Comment by benwoo1110** [comment]
Issue #1119 is fixed a long time ago. What exact issue are you facing with luckperms on bungee? I suggest also following them issue template.

**Comment by benwoo1110** [comment]
Lol you meant bungeecord build #1119 not a luckperm issue. Use https://papermc.io/downloads#Travertine for bungee to support 1.7.10 servers.
