### ISSUE TITLE
Error on Spigot startup

### ISSUE THREAD

**Issue by Ironic8b498** [lucko/LuckPerms#3067]
LuckPerms-Bukkit-5.3.47-#1345

### Description

getting errors in Spigot 1.17

### Reproduction steps

1. Added latest jar
2. Started the server

https://paste.helpch.at/mozuhecuvi.sql
### Expected behaviour

No errors on bootup 

### Environment details

* Server type/version: `ExampleSpigot` running version `1.12.2` build `???`
* LuckPerms version: `v???`
LuckPerms-Bukkit-5.3.47-#1345

https://paste.helpch.at/mozuhecuvi.sql

**Comment by benwoo1110** [comment]
I think legacy extensions no longer work on java 16 and doesn't look like it's going to be supported, since it's legacy.

**Comment by Ironic8b498** [comment]
guess I will have to see if there is a work around

**Comment by Ironic8b498** [comment]
the default assignment is `  rule2:
    if:
      lacks: <vanilla/group.villager> & <vanilla/group.traveler> & <vanilla/group.farmer> & <vanilla/group.miner> & <vanilla/group.hunter>  & <vanilla/group.pro>
    give:
      - vanilla/group.villager
`

**Comment by Ironic8b498** [comment]
there was no need to find a work around the  legacy extensions still worked I had two of one
