### ISSUE TITLE
java.lang.String cannot be cast to net.md_5.bungee.config.Configuration

### ISSUE THREAD

**Issue by EmanYm** [lucko/LuckPerms#307]
https://hastebin.com/afatufasif.rb
What have I done wrong now?

Bungeecord build 1236
LuckPerms-Bungee 3.2.7

I suspect I may need to pull my bungeecord back to 1232

**Comment by lucko** [comment]
Uhh, I highly doubt it's a BungeeCord bug.

Can you pastebin your config file?

**Comment by EmanYm** [comment]
I was just comparing the config on bungee with the config on sponge.  It appears some quotation marks and brackets "disappeared" ...

Bungee `server: bungee`
sponge `server="play"`

And the default-assignemets
bungee `default-assignments` (no closing bracket either
sponge `default-assignments {` (with a closing bracket)

I have a feeling this is what I get for trying to edit configs in Notepad++

**Comment by lucko** [comment]
Yes. Different formats.

When you restarted, were there any errors?

**Comment by EmanYm** [comment]
I am 95% positive it's because I copied parts of the config file from the sponge config.
There were no errors after the restart.  I reset the database info (without the quotation marks...) and it's all good now.

Another case of to many derp sprinkles on my eedjit ice cream.

**Comment by lucko** [comment]
Alright, cool.

Remember to close the issue you opened on the Bungee repo too ;)
