### ISSUE TITLE
Luckperm command dosent work in mohist 1.16.5 jre 11

### ISSUE THREAD

**Issue by zaze06** [lucko/LuckPerms#3071]
tested dident work

### Description

When i run /lp and /luckperms it get nothing not papper saying that the command dosent exist or luckperms giving me anything

### Reproduction steps

1. open chat
2. type /lp
3. get nothing in the chat

### Expected behaviour

i get a message telling me that i shuld run /lp help or that its tellimg me i dont have permision to run anything else and tell me what version of luckperms i run

### Environment details

* Server type/version: `mohist (forge and bukket/spigot/papper combination)` running version `1.16.5` build `646`
* LuckPerms version: `v5.3.47`
* java runtime envierment: `adoptPenJDK 11 hotspot`

 i dont thing so i dosent get anything in the chat and its the defualt config generated by luckperms

### Any other relevant details

dont think so exept i uses it in combination whit abunch of mods can provive a mod list if you what

**Comment by Samisaprogrammer** [comment]
Are you OPped?

**Comment by benwoo1110** [comment]
mohist isn't a supported server software.

**Comment by zaze06** [comment]
> mohist isn't a supported server software.

ok thx
