### ISSUE TITLE
Issue relating to SSL TLSv1.2+

### ISSUE THREAD

**Issue by AgentKyramud** [lucko/LuckPerms#3074]
### Description
There appears to be an issue relating to SSL using TLSv1.2 or higher.  TLSv1.2 and higher is required for both Java 16 (requirement for Minecraft v1.17) and MariaDB v10.5.

### Reproduction steps

1. On the server, setup MariaDB v10.5 and configure to use SSL
2. Using MariaDB v10.5, set up a luckperms user requiring an SSL connection to log in.
3. On the client side, configure to use SSL to log in to server.  Confirm that you are able to do so from the client machine using luckperm user.
4. Configure luckperms to connect to MariaDB using appropriate credentials and boot server.  This is where I get 'login rejected'.
5. Now go back to step one and remove the configuration/requirement for SSL.  Change the configuration for luckperms to not use SSL.  Verify that on server boot, Luckperms has no issue connecting to MariaDB.

### Expected behaviour
I expect for luckperms to not have it's login attempt rejected while using TLSv1.2 or higher.

### Environment details

* SQL Server OS: Ubuntu 20.04 LTS
* Minecraft Server OS: Ubuntu 21.04
* Server: Paper 1.16.5, build 777
* Luckperms 5.3.47
* Java 16
* MariaDB 10.5
* SSL Certs Source: OpenSSL

**Comment by lucko** [comment]
This is a driver and/or configuration issue with your MariaDB instance.

See: https://luckperms.net/wiki/Storage-system-errors
