### ISSUE TITLE
Adding the constraints from bolt update to the LP user clear

### ISSUE THREAD

**Issue by GIToez** [lucko/LuckPerms#3076]
Pretty much just proposing that we had the constraints used in the bulk update to the LP user clear command so we can set it up to clear all permissions except for certain ones

### Proposed behaviour
So it would work like
Lp user clear != Group.admin
So what this would do would remove all the permissions except for the admin group off the player

**Comment by lucko** [comment]
A nice idea but in my opinion this is a bit too niche for inclusion. Perhaps the web editor can be of some help to achieve this action more swiftly.
