### ISSUE TITLE
Error with connect to server

### ISSUE THREAD

**Issue by WhiTe-Yak** [lucko/LuckPerms#3080]
### Description

Could not pass event AsyncPlayerPreLoginEvent to LuckPerms v5.3.48
java.lang.NullPointerException: null

### Reproduction steps

1. Start the server
2. Connect to server
3. See error

### Environment details

This server is running Paper version git-Paper-"558be4b" (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)
LuckPerms v5.3.48

https://gist.github.com/WhiTe-Yak/d280094860ff0484b98958150cc2d9e6

**Comment by benwoo1110** [comment]
Does this happen on 1.16.5?

**Comment by WhiTe-Yak** [comment]
No, 1.17

**Comment by WhiTe-Yak** [comment]
Solved by reinstalling from scratch
