### ISSUE TITLE
Placeholder: weight of highest group in track X

### ISSUE THREAD

**Issue by AlessioGr** [lucko/LuckPerms#3081]
### Description
I'd need a placeholder which outputs the **weight** of the **highest group** the player has **in track X**.

This can be used for automated group sorting by weight in plugins like TAB - instead of manually specifying the group names in the sorting list.

**Comment by lucko** [comment]
Placeholder requests go on this repo instead: https://github.com/LuckPerms/placeholders/

PRs preferred! I try to implement requests when I have the time, but often they are rather specific/niche - like this one - and I have to prioritise.
