### ISSUE TITLE
Not support Chinese name in command

### ISSUE THREAD

**Issue by MikuSnow** [lucko/LuckPerms#3084]
Command:
PlayerName: 我的世界
'/lp user 我的世界 permission info'
It will show:
'我的世界 is not a valid username/uuid'

**Comment by underscore11code** [comment]
Minecraft only supports a-z, A-Z, 0-9, and _. You can set `allow-invalid-usernames: true` in the config although I wouldn't be surprised if it breaks something.

**Comment by MikuSnow** [comment]
Ah, Thanks!
