### ISSUE TITLE
* permission node does not work

### ISSUE THREAD

**Issue by czhangdev** [lucko/LuckPerms#3085]
### Description

* permission node does not work in luckperms

### Reproduction steps

1. /lp user <username> permission set * true
2. See error

### Expected behaviour

should have permission to everything

### Environment details

* Server type/version: Paper version git-Paper-"47605b8" (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)
* LuckPerms version: LuckPerms-Bukkit-5.3.47

**Comment by benwoo1110** [comment]
> 2. See error

What is the error? 
Also * may not mean every permission depending on how your setup is. https://nucleuspowered.org/docs/nowildcard.html

**Comment by czhangdev** [comment]
> > 1. See error
> 
> What is the error?
> Also * may not mean every permission depending on how your setup is. https://nucleuspowered.org/docs/nowildcard.html

actually, no error is produced, it just that even after granting * node, I still wouldn't have access to commands, and to second point, it is not just a problem with one plugin, it is a problem with all the plugin i currently have installed, even including the command provided by PaperMC and Mojang, this is really awkward since I don't have this issue on 1.16.5

**Comment by lucko** [comment]
Sometimes you need to grant the specific permission instead of just a wildcard, depending on how the plugin author has defined their permissions (or the way in which they check)

Without you being any more specific, I can't help further.
