### ISSUE TITLE
Reset everyones rank back to default?

### ISSUE THREAD

**Issue by lowheartrate** [lucko/LuckPerms#309]
Is there a command I can use to make set everyones group back to default? I am trying to run an economy / group reset on my server and would rather not have to manually set 100s of users ranks back :(

**Comment by lucko** [comment]
Yeah, this should cover what you're trying to do. 

https://github.com/lucko/LuckPerms/wiki/Bulk-Editing

**Comment by lowheartrate** [comment]
Ok, thanks! Would I simply use: 
`/lp bulkupdate user parent set default`
?

**Comment by EmanYm** [comment]
Do you want to wipe all permissions or groups/users?  Or are you just trying to reset groups to default?
Your syntax is incorrect.
/lp bulkupdate <data type> <action> [action field] [action value] [constraint...]
Make sure you [read all of the information](https://github.com/lucko/LuckPerms/wiki/Bulk-Editing#lp-bulkupdate-data-type-action-action-field-action-value-constraint) on the page Luck linked

**Comment by lowheartrate** [comment]
I just want to set everyone's groups back to the default group. I want to keep all the permission for the group.

**Comment by EmanYm** [comment]
I believe `default` is no group.
I haven't tested this, so make sure you back up your database before trying

>/lp bulkupdate users delete permission

**Comment by lucko** [comment]
There's an example on that page you can use:

`/lp bulkupdate users delete "permission == group.<group name>"` will delete all memberships of the given group.

**Comment by lowheartrate** [comment]
Ok thank you and that will put them back into the default group right?

**Comment by lucko** [comment]
It'll just remove them from the group you specify.

**Comment by lowheartrate** [comment]
Is there a way I can just *update* everyones group to default instead of deleting the group from them? Maybe something like:
`/lp bulkupdate users update "permission == group.default"`

**Comment by ShinobiSondre** [comment]
This is what I did which solves the problem without having to repeat yourself with different groups.

/lp bulkupdate users update permission group.default "permission ~~ group.%"

This will reset everyone no matter the group back to the default group.
