### ISSUE TITLE
1.17 Fabric release?

### ISSUE THREAD

**Issue by Samisaprogrammer** [lucko/LuckPerms#3090]
### Description
As far as I'm aware, this mod is only for 1.16 for fabric. When is it getting 1.17? I haven't tested it yet though

### Proposed behaviour
It gets support for 1.17

**Comment by benwoo1110** [comment]
I think it works tho, even tho the actually API depend is not updated to 1.17, as long as no breaking change I don't see an issue.

**Comment by Samisaprogrammer** [comment]
> 
> 
> I think it works tho, even tho the actually API depend is not updated to 1.17, as long as no breaking change I don't see an issue.

No, I saw that there was a recently (27 days ago) merged patch that fixed a crash for 1.17 but afaik it's not in any release version.

**Comment by benwoo1110** [comment]
Yea its fixed and can be downloaded at https://luckperms.net/download

**Comment by Samisaprogrammer** [comment]
so why does it still say 1.16.4? 
![image](https://user-images.githubusercontent.com/59611020/124861287-c8b60480-dfa2-11eb-90a5-de4af1122f6e.png)

**Comment by benwoo1110** [comment]
API dependency is not updated to 1.17, so officially it's not running on 1.17. But there is no change that is breaking. (or at least those has been workaround as you stated) Are you facing an issue with luckperms on fabric?

**Comment by Samisaprogrammer** [comment]
Nope.
