### ISSUE TITLE
Adding Permission Node Grouping

### ISSUE THREAD

**Issue by Wairoa** [lucko/LuckPerms#3091]
### Description
Recently I noticed how slow it can be to scroll through existing permission nodes listed for specific groups / players on my server. I wanted to try and see if there was a way to somehow group certain permissions together to make the process of navigating the list simpler. To my surprise; this is not a current feature.

For example: some of our groups use a list of 10+ individual worldedit plugin permissions and scrolling through the full list of added permissions without searching for them feels inefficient.

### Proposed behaviour
Create a feature that allows you to 'group' specific permissions together for a specific Rank/Group's (or Player's) permissions in folders or segments. This would allow you to place all of say; the 10+ worldedit permission nodes into a single folder for that group's list of perms, decluttering the list and making navigation easier without the need to search for the node individually.

This feature would become particularly useful if you have groups/players with upwards of 30+ individual set permission nodes by allowing you to organise them into a 'subcategory/folder/group'.

**Comment by benwoo1110** [comment]
I hope you can elaborate, currently your suggestion is very very vague.

**Comment by Wairoa** [comment]
> I hope you can elaborate, currently your suggestion is very very vague.

Apologies I accidentally clicked to post pre-emptively

**Comment by benwoo1110** [comment]
You can just create a group and make other groups/users inherit from it? Unless you are taking about some more complex nested folders implementation.

**Comment by Wairoa** [comment]
> You can just create a group and make other groups/users inherit from it? Unless you are taking about some more complex nested folders implementation.

I more so mean folders of grouped permission nodes within one specific group/rank. This would be useful in organising plugin-specific permissions for a particular group/rank without creating an entirely new group itself.

**Comment by lucko** [comment]
If you want further organisation, just use subgroups.

e.g.

```
/lp group admin parent add admin-worldedit

/lp group admin-worldedit permission set worldedit.something
/lp group admin-worldedit permission set worldedit.somethingelse
...
```
