### ISSUE TITLE
Tab Modifier Crashes with LP5 with legacy extensions

### ISSUE THREAD

**Issue by JadedMagic5** [lucko/LuckPerms#3094]
### Description
Running the server with Tab Modifier crashes using LP5, I have tried all combinations of with and without both default and legacy LP extensions.

### Reproduction steps
Install latest LP with both extensions added;
Install latest Tab Modifier;
Run server

### Expected behaviour
Should use LPAPI from legacy. 

### Environment details
Data Center in New York
Rapid Deploy Server - Intel Xeon E5 1650 V3 64GB (PNJ)

* Server type/version: spongeforge-1.12.2-2838-7.3.0
* LuckPerms version: LuckPerms-Sponge-5.3.0

### Any other relevant details
I have tried to force LP to be read 1st by placing it in the mods folders as I redirect plugins and configs for sponge. 
It seems to crash directly after the servers first [FML]: Attempting connection with missing mods [my plugins] 
I am willing to accept not using Tab Modifier, this is my last ditch effort to get the plugin to work

\.log --> https://pastebin.com/kNkHCcwa
\crashreport --> https://pastebin.com/k3EaG89y

**Comment by benwoo1110** [comment]
Tab modifier needs to update. It's using outdated luckperms API.

**Comment by JadedMagic5** [comment]
This is why i noted using the LP extensions; "An extension for LuckPerms v5, which implements the legacy v4 API."

**Comment by benwoo1110** [comment]
Actually, you are using a very old LP version. Update first and try https://luckperms.net/download. But Tab modifier seriously needs to update.

**Comment by JadedMagic5** [comment]
Thank you, I really need to get into the habit of not relying on Sponge Ore to post most recent updates. Tab Modifier is an abandon project, its unique and I'm trying to squeeze as much use of it as I can, I will update to latest dev build and repost here.

**Comment by JadedMagic5** [comment]
No change, same log and crashreport. Do you have any ideas on how to delay Tab Modifier from being read to AFTER the extensions are loaded; because right now they are useless due to how fast its crashing.

**Comment by benwoo1110** [comment]
I dont code sponge, but in general, the plugin that uses the API needs to tell the server to load after the API they depend on, LP cant really control that order.

**Comment by JadedMagic5** [comment]
Ok, I will go and remove Tab Modifier's dependencies and report back, didn't think about that until now. Or as this is really not a LP issue you can feel free to close; if its still open ill share if this works or not.

**Comment by JadedMagic5** [comment]
The plugin 100% just doesnt work with Sponge7.3, I appreciate your help with this though. kudos!
