### ISSUE TITLE
API reference not being set properly?

### ISSUE THREAD

**Issue by Crypnotic** [lucko/LuckPerms#3095]
### Description

Api seems to never be enabled on newer versions. Confirmed all interactions with the LuckPerms api take place after onEnable, along with making sure the plugin.yml specifies a dependency on LuckPerms. The same code has been used since 5.2.xx and has never had an issue.

### Reproduction steps

1. Place LuckPerms dependency in plugin.yml
2. Attempt to build a MetaNode onEnable

### Expected behaviour

Documentation states that the api should be available to access onEnable.

### Environment details

* Server type/version: `Paper` running version `1.17` build `79`
* Server type/version: `Airplane` running version `1.17` build `40`
* LuckPerms version: `v5.3.50`

https://gist.github.com/Crypnotic/9a4333e5480663e72118f2b78828a37b

**Comment by benwoo1110** [comment]
Can you show your full startup log?

**Comment by Crypnotic** [comment]
> Can you show your full startup log?

Gist updated to include full startup

**Comment by emilyy-dev** [comment]
Make sure you are not shading the API and the dependency is declared as compileOnly (if you're using gradle) or scope provided (if you're using maven)

**Comment by Crypnotic** [comment]
> Make sure you are not shading the API and the dependency is declared as compileOnly (if you're using gradle) or scope provided (if you're using maven)

100% what it was. Had some gradle issues importing so I changed keywords around and didn't catch the shade. Thank you :P
