### ISSUE TITLE
Velocity 3.0.0

### ISSUE THREAD

**Issue by astei** [lucko/LuckPerms#3098]
### Description

Starting in Velocity 3.0.0, Velocity now supports handling events in an truly asynchronous matter. In particular, Velocity now has the ability to wait on a `CompletableFuture` that must complete ([see Javadoc for more information](https://jd.velocitypowered.com/3.0.0/com/velocitypowered/api/event/EventTask.html#resumeWhenComplete\(java.util.concurrent.CompletableFuture\)) and also [the Velocity wiki](https://velocitypowered.com/wiki/developers/event-api/)) and this would be useful for loading data without reserving an event thread. Likewise, Velocity Polymer will require any long-running event logic listener to run asynchronously.

Note that Velocity 1.1.x is still supported (until Minecraft 1.18, anticipated to release around Christmas), so this is more of a forward-looking suggestion.

### Proposed behaviour

LuckPerms should use the `EventTask` API introduced in Velocity 3.0.0.

**Comment by lucko** [comment]
I only support one version of each platform at any one time.

When Velocity 3.0.0 is released and being encouraged for use, I will update LuckPerms (and drop support for 1.x.x).

I'd appreciate any guidance you're willing to give as to when the best time for this is.

**Comment by astei** [comment]
> When Velocity 3.0.0 is released and being encouraged for use, I will update LuckPerms (and drop support for 1.x.x).

[Velocity 3.0.0 is already released and we are encouraging people to use it](https://forums.velocitypowered.com/t/velocity-3-0-0-and-1-1-9-released/821) - however, Velocity 1.1.x will be officially supported until MInecraft 1.18 is released to give server owners and plugin developers time to update. So the best time to make the move is January 2022, or you can create a second Velocity 3.0.0-specific version of the listener class.

**Comment by lucko** [comment]
I was confused between Velocity 3.0.0 and 4.0.0 - my apologies.

I can see that Velocity 3.0.0 is being advertised as the current stable build, so I will update.

**Comment by lucko** [comment]
https://github.com/lucko/LuckPerms/compare/feature/velocity3

Look ok?

**Comment by nayneyT** [comment]
I'm in Limbo here. Do I go with v1.1 or v3.0? It appears lucko is waiting for astei to reply?

**Comment by astei** [comment]
LuckPerms as-is still works fine with 3.0.0. I've just been very busy and not given him a response yet.

**Comment by nayneyT** [comment]
I tried it from a clean install and I cannot use the lpv commands from rcon. Nothing happens when I try and set the initial permissions. Are you sure that it works?

**Comment by astei** [comment]
Yes, this should work fine @lucko. I see the potential in a more deeper integration but this works for now.

**Comment by astei** [comment]
26de6d3a and 4332725 integrate this, so closing this issue as resolved.
