### ISSUE TITLE
Prefix not showing when using Split-Storage with user in MYSQL

### ISSUE THREAD

**Issue by EdgarG4m3r** [lucko/LuckPerms#310]
I found an Issue, Prefix is not showing IF using MySql to save user data, prefix is working fine when switched to YAML, here is my config, https://pastebin.com/BN0LkPNA

**Comment by lucko** [comment]
The only reason why it wouldn't show is if the data is different in each storage type.

Remember it doesn't move over automatically when you change your config around.

**Comment by EdgarG4m3r** [comment]
ohh ok, Is it possible to only sync the user rank, not the permissions?

**Comment by lucko** [comment]
No, a users "rank" is stored in their permissions.
