### ISSUE TITLE
Server crashes due to LuckPerms

### ISSUE THREAD

**Issue by DarkyCat** [lucko/LuckPerms#3101]
### Description
Server 1.16.5 crashes on getting LuckPerms rights tested with Airplane and Purpur kernel. Java 16

### Reproduction steps

In my case, when I write /tab reload, the server freezes and crashes.
Plugin developer TAB told to unsubscribe to you

### Environment details

* Server type/version: `Airplane and purpur ` running version `1.16.5` build `9(Airplane) or 1171(Purpur)`
* LuckPerms version: `v5.3.51`

https://p.reflex.rip/faxi.sql

**Comment by lucko** [comment]
Does it happen reliably every time you try to reload?

**Comment by DarkyCat** [comment]
Each time you reload the TAB plugin, this happens through the command. The TAB developer told you to contact you to fix this issue.

**Comment by DarkyCat** [comment]
Each time you reload the TAB plugin, this happens through the command. The TAB developer told you to contact you to fix this issue.

**Comment by lucko** [comment]
Please could you try testing using only Tab and LuckPerms installed.

If it still happens, please send a .zip of your plugins folder

**Comment by DarkyCat** [comment]
I have already identified under what circumstances this happens. When the player does not have more than one right to the board in the TAB plugin.
![изображение](https://user-images.githubusercontent.com/50515714/126566040-919f9048-12d5-4d08-924d-3adc89b5653d.png)

**Comment by lucko** [comment]
Seems like a tab issue in that case.
