### ISSUE TITLE
NPE When editing a User's Groups.

### ISSUE THREAD

**Issue by Relaxing9** [lucko/LuckPerms#3103]
### Description

When promoting a user on a track twice there is a chance for an exception to occur. 

### Reproduction steps

I believe the issue existed because of promoting someone on a track twice which then caused some sort of error on Luck Perms and DiscordSRV having an exception triggered. So far I cannot replicate the issue and am unaware of the cause.

### Expected behaviour

No console output, plugin behavior is normal just there is some sort of error triggered in the Console.

### Environment details

* Server type/version: `git-Paper-79 (MC: 1.17)`
* LuckPerms version: `5.3.47`
(checked changelog for newer version, doesn't seem to cover this issue)

Isolated Error: https://paste.gg/p/anonymous/9976323315b14d6c8fd361350c776a86
Latest Log: https://bin.scarsz.me/e39800bc-d8b1-4399-af5c-1cdb4063779d#i98HAWoywl8zw5XgWItWVa6E3xAxwIoo

### Any other relevant details

First reported this to the DiscordSRV team but they referred to LuckPerms (as a bug from here).

**Comment by lucko** [comment]
Thanks :)
