### ISSUE TITLE
The command from Carpet mod /player does not work when LuckPerms is installed on Fabric.

### ISSUE THREAD

**Issue by FlamingCherry** [lucko/LuckPerms#3104]
### Description
Hello. I am using Minecraft 1.17.1, latest Carpet and latest LuckPerms. When you enter the command /player Alex spawn, which should spawn a fake player, an error appears in the chat, and an exception appears in the console if you enter the command /carpet superSecretSettings true in advance.

### Reproduction steps
Install Carpet and LuckPerms on Minecraft 1.17.1, enter the command /carpet superSecretSettings, and then try to spawn a fake player using the command /player Alex spawn.

### Expected behaviour
Normal operation of the /player command, namely, the appearance of a fake player after its execution.

### Environment details

* Server type/version: `Fabric` running version `1.17.1`
* LuckPerms version: `v5.3.51`

https://gist.github.com/FlamingCherry/c7079e326b9afae6480574649f68b7e1

**Comment by lucko** [comment]
I've improved the error message.. but the cause is actually from `eu.pb4.placeholders`
