### ISSUE TITLE
LuckPerms Api Static Context

### ISSUE THREAD

**Issue by MassiveLag** [lucko/LuckPerms#3105]
### Description
Hello, 
I was wondering if there a way to set custom static context via the api?
My servers are dynamic, and i am looking to set some information in context.json via the api.

**Comment by benwoo1110** [comment]
You can’t set context.json. You can just register your own context calculator.

**Comment by lucko** [comment]
There is a class for static contexts in the API: [`net.luckperms.api.context.StaticContextCalculator`](https://javadoc.io/doc/net.luckperms/api/latest/net/luckperms/api/context/StaticContextCalculator.html)
