### ISSUE TITLE
Gradle not building

### ISSUE THREAD

**Issue by Vareska** [lucko/LuckPerms#3107]
### Description

Gradle command "./gradlew build" throws an error stating:

$ ./gradlew build

←[1A
←[31mFAILURE: ←[39m←[31mBuild failed with an exception.←[39m

* Where:
Settings file 'C:\Users\User\Downloads\BuildTools\LuckPerms\settings.gradle'

* What went wrong:
Could not compile settings file 'C:\Users\Njowi\Downloads\BuildTools\LuckPerms\settings.gradle'.
←[33m> ←[39mstartup failed:
  General error during semantic analysis: Unsupported class file major version 60

### Reproduction steps

run ./gradlew build in git bash or run the gradlew.bat file

### Expected behaviour

build LuckPerms.jar file

### Environment details

Windows 10 latest version

Spigot 1.17

**Comment by benwoo1110** [comment]
Ensure you are using Java 16 to build.

**Comment by Vareska** [comment]
I am using Java 16.
