### ISSUE TITLE
A Permission from Luckperms dont work.

### ISSUE THREAD

**Issue by spieleersteller** [lucko/LuckPerms#3108]
Hey  Guys!
I wanted to make an Citybuild based Server with Aternos.
So i got some plugins for the Server and for managing the permissions i choosed Luckperms.
One of the plugins was an Warp plugin so i set that everyone has the Permission to warp, but when my friend tested the server he can´t warp and it show the "error" You dont have the permission or something.
But the weird thing is all other Permissions work. And for the warp plugin there was only one permission so i cant´t choose a wrong permission.

How can i fix this?

**Comment by Chris6ix** [comment]
If this Warp plugin only has 1 permission, and it's the only permission that is not working on your server, then it sounds like there is something wrong with your Warp plugin then, and you should maybe contact the author of that plugin...

**Comment by benwoo1110** [comment]
Agree with @Chris6ix. Please look into what the actual warp permissions for that plugin is.

Luckperms also have a great built in feature to help you, see https://luckperms.net/wiki/Verbose
