### ISSUE TITLE
Create a priority list for prefixes of each group

### ISSUE THREAD

**Issue by Georgak** [lucko/LuckPerms#3109]
### Description

WHEN TALKING ABOUT PREFIXES I REFER TO SUFFIXES TOO

My idea is that you can create a list under "Tracks" named "Prefixes" where it works like the track drag and drop but instead of creating tracks you create prefix priorities. In other words, I suggested that you virtualize the "prefix.(number)" thingy and get rid of it.

### Proposed behaviour

When you click this "Prefix" list, all prefixes **FOR EACH GROUP**, will display. When you click a group, you can change it's prefix by writing it in a value box that will appear on the center of the web editor page.
Above, I made an example:

![Polish_20210720_153941761](https://user-images.githubusercontent.com/65731193/126325503-90c58a77-1648-425b-bba2-20077143867a.jpg)
![Polish_20210720_153634685](https://user-images.githubusercontent.com/65731193/126327333-768794d7-db58-4ebf-8826-3a0025f1849f.jpg)

BUT:
IF A PLAYER HAS MORE THAN 1 GROUPS CONNECTED TO HIM, THE EDITOR WON'T LET THE EDITS TO BE SAVED AND WILL ASK ONLY ONE GROUP TO BE CONNECTED, (considering that "group.(group)" is a thing and can be used instead of double grouping a player) => THIS IS A SOLUTION SO PLAYER HAS ONLY ONE PREFIX

BUT:

IF A PLAYER WANTS TO HAVE 1 OR MORE PREFIXES => You will need to create a multi prefix system and rework my idea.

This will result in prefix management get a ton simplie for newbies.

Thanks for taking my suggestion into consideration...

**Comment by benwoo1110** [comment]
...?
