### ISSUE TITLE
Using a single color code as prefix. 

### ISSUE THREAD

**Issue by LukeFlynn** [lucko/LuckPerms#311]
Hi,

For the ranks on my servers, I use a single color to denote ranks rather than tags. Functionally, this works as expected in LuckPerms, but, when looking at the info for the group via commands you don't see anything except blank quotations.

For example, with the color "&c" for group moderator, you see something like:
![](https://puu.sh/wbUPO.png)

It would be nice if it actually showed the color codes so I could easily identify them.

Thanks,

Luke

**Comment by lucko** [comment]
This should already show in the newer versions.

https://ci.lucko.me/job/LuckPerms/

**Comment by LukeFlynn** [comment]
Sorry for the late response, but it's still returning empty quotations. The prefix is supplied to Vault just fine, I just wish I could see it clearly when looking at the info and or setting them.

**Comment by LazosPlaying** [comment]
i suppose it's like that because the plugin wants to show you the colored text, since there is not text, but just a color code, it will show you a red-colored blank space.

**Comment by lucko** [comment]
Gonna close this. I assume this sort of thing is what you meant. :wink:
![](http://i.imgur.com/TgZJPAR.png)
