### ISSUE TITLE
Hover and click in chat doesn't work

### ISSUE THREAD

**Issue by KamosRZ** [lucko/LuckPerms#3110]
### Description

When you list permissions, parents, meta, etc., you should be able to hover over one item in the list, for example a permission, and see a Hover message telling you "Click to remove...". This doesn't work anymore after updating to 1.17.1 (from 1.16.5) (Clicking also doesn't generate the remove permission command like before)

### Reproduction steps

1. You can create a brand new 1.17.1 server with default settings, I tested different softwares (spigot, airplane, airplane-purpur), the bug is present in all of them.
2. Install only the LP plugin, default settings
3. Join the server, add a permission 'test' to the default group.
4. When you type 'lp group default permission info' and hover and click on the permission, nothing happens.

### Expected behaviour

See a hover text and generate a remove permission command

### Environment details

Using a panel host, but also tested on windows 10 with Java 16 Corretto

* Server type/version: `ExampleSpigot` running version `1.12.2` build `???`
* LuckPerms version: `v???`

LP 5.3.53, but bug also happens with earlier versions
Airplane-Purpur-1.17.1 (Build 23)
Airplane-1.17.1 (Build 55)
Spigot 1.17.1 (3190-Spigot)

No errors in console

### Any other relevant details

When you click on permissions, it might treat them as a link and open the "Are you sure you want to follow the link" message. I am mentioning it because it may be connected to what the real bug is, but it's not the only cause because again, no hover text and it doesn't work on prefixes, parents and other things that aren't treated as links by the Client

**Comment by benwoo1110** [comment]
So you tested on 1.16.5 and it works fine?

**Comment by KamosRZ** [comment]
Yes, I forgot to mention it, I tested with 1.16.5 using the same brand new server setup (just deleted the world so it regenerates on 1.16.5 and swapped the jar), everything worked fine

**Comment by KamosRZ** [comment]
![image](https://user-images.githubusercontent.com/43544816/126476481-381e8137-fb65-4fe9-8177-619b0e865a5b.png)
Just to make sure I explained the feature I was talking about - it's this one (screenshot is from testing with 1.16.5 Airplane-Purpur)

**Comment by lucko** [comment]
Fixed in b3ebf202fd40762be6749791dd4d9ead72c9cb59 - thanks!
