### ISSUE TITLE
Make it easier to modify language file

### ISSUE THREAD

**Issue by strahil211** [lucko/LuckPerms#3111]
### Description

I cannot find the English language file to modify the messages, I can only see other language files.
Wiki says to import it?

### Proposed behaviour

Have the language file easily accessible and editable

**Comment by lucko** [comment]
The English (native) language file is built into the plugin.

You can view it here: https://github.com/lucko/LuckPerms/blob/master/common/src/main/resources/luckperms_en.properties

This is also explained on the relevant wiki page: https://luckperms.net/wiki/Locale-and-Translations
