### ISSUE TITLE
Delete all users from a specific group

### ISSUE THREAD

**Issue by LucidAPs** [lucko/LuckPerms#3112]
Please add a way to delete all users from a specific group, or even better an option to delete everything after a certain date.

**Comment by benwoo1110** [comment]
1. You can remove a group from all users. See https://luckperms.net/wiki/Bulk-Editing
2. you can set groups to expire at a certain time for each user with https://luckperms.net/wiki/Parent-Commands#lp-usergroup-usergroup-parent-addtemp-group-duration-temporary-modifier-context

**Comment by LucidAPs** [comment]
> 1. You can remove a group from all users. See https://luckperms.net/wiki/Bulk-Editing
> 2. you can set groups to expire at a certain time for each user with https://luckperms.net/wiki/Parent-Commands#lp-usergroup-usergroup-parent-addtemp-group-duration-temporary-modifier-context

/lp bulkupdate all delete "permission == group.default" So that will work? Will it cause problems if I run the command when the server is online?

**Comment by lucko** [comment]
That will work
