### ISSUE TITLE
There's an issue on my server, when I set a prefix to my self or rank all my wolf names get the same prefix before their names

### ISSUE THREAD

**Issue by coolstudiobroyt** [lucko/LuckPerms#3115]
My Dog Has Had My Prefix When I Name It I Think Its a Bug Because I have never seen it happen before
https://gyazo.com/fce8dc2a01c67b154c1c760925ef382c

**Comment by AgentIce** [comment]
I strongly believe you are using the plugin 'TAB'. If that is the case, please check out this article where it describes exactly this issue: https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Pet-name-fix
