### ISSUE TITLE
Permissions issue...

### ISSUE THREAD

**Issue by axelski** [lucko/LuckPerms#3116]
Hi so i encountered this problem with essentials permissions, i try disabling certain permissions "warps" for my members but they can still use them...

![image](https://user-images.githubusercontent.com/32389829/126899383-23f8526d-c7ed-45f9-9ece-9de9da37c783.png)

The ones in red are the ones they shouldnt be able todo but they can anyways...

**Comment by benwoo1110** [comment]
According to essentials documentation https://essinfo.xeya.me/permissions.html, the permission node is `essentials.warps.[warpname]`, `warps` with the `s`

**Comment by axelski** [comment]
ooo fuck i missspelled it lol
thanks alot sir!!!
