### ISSUE TITLE
Permissions data for your user was not loaded during the pre-login stage - this is likely due to a conflict between CraftBukkit and the online-mode setting. Please check the server console for more information.

### ISSUE THREAD

**Issue by StupidRepo** [lucko/LuckPerms#3118]
### Description
I have online-mode=false in server.properties and LuckPerms won't let me join. How do I bypass this?

### Reproduction steps
Set online-mode to false in server.properties.
Launch CraftBukkit Server (1.16.5).
Join on premium/cracked account.
Won't let you in.

### Expected behaviour
Error should not pop up

### Environment details

* Server type/version: `CraftBukkit/Bukkit` running version `1.16.5` build `Latest at the time of 2021 Jul 16 - 11:09 AM`
* LuckPerms version: `5.3.47`

### Any other relevant details
None

**Comment by lucko** [comment]
Use Paper instead of CraftBukkit
