### ISSUE TITLE
Command to advance a player to at least a certain rank on a track

### ISSUE THREAD

**Issue by creator3** [lucko/LuckPerms#312]
I'm looking for something sort of like `parent settrack` so that I can advance players to a specific group on a track. However, I don't want it to blindly set their rank because some players will already have a higher one.

Thanks.

**Comment by EmanYm** [comment]
Check [this](https://github.com/lucko/LuckPerms/wiki/Tracks) and [this](https://github.com/lucko/LuckPerms/wiki/Command-Usage#track---lp-track-track-)

**Comment by lucko** [comment]
Example usecase?

**Comment by creator3** [comment]
Specifically, it would work nicely with automatic rank ups from various achievements. Specifically, we use AutoRank to advance players to a member rank after they've played for a few hours. However, that player may have already achieved a higher rank by voting, donating, or whatever other reason.

**Comment by EmanYm** [comment]
That sounds like a good excuse to have several ladders.
One for voting, one for donating and one for playing.

**Comment by creator3** [comment]
I considered something like that, but the groups on each track would just end up inheriting the actual rank anyway because I don't care how they got to that rank. A player would end up inheriting a playtime group that inherits member as well as a voting group that inherits member+, which in turn inherits member. Instead of having players inherit both voter and playtime groups, I may as well just use `parent add` with the single existing track.

**Comment by EmanYm** [comment]
You can use the scoreboard system.  It can track everything you see in the achievements list, then figure out how to run a command when the score for a certain task reaches a specified number.

If you must use a plugin, [here is one](https://www.spigotmc.org/resources/advanced-achievements.6239/)  for spigot and bukkit, or [here is one](https://forums.spongepowered.org/t/badgeup-achievements/16525) if you're on sponge
