### ISSUE TITLE
High ping on gamemode change

### ISSUE THREAD

**Issue by Ynfuien** [lucko/LuckPerms#3120]
### Description
**My English is really bad so I used google translator.**

LuckPerms in combination with EssentialsX increases ping when changing the gamemode or when switching to another world. The more plugins are enabled, the ping jumps higher (With ~40 plugins ping jumps to 800 and more) and it is quite bothersome because it causes temporary lag for a player.

Videos showing this:
LuckPerms and EssentialsX:
https://www.youtube.com/watch?v=00lfAOeiZdI

Only LuckPerms:
https://www.youtube.com/watch?v=g2Spht4Wtg4

Only EssentialsX:
https://www.youtube.com/watch?v=slboZZqkkVk

### Environment details

* Server: `Airplane-Purpur 1.16.5 but I also tested it on last Purpur 1.16.5 build`
* LuckPerms version: `v5.3.53`
* EssentialsX version: `v2.18.2.0`

**Comment by benwoo1110** [comment]
Likely just server lag, what is your server specs and also do send your startup log.

**Comment by Ynfuien** [comment]
**Server logs:** https://pastebin.com/rR4wnxEB

**OS:** Ubuntu 20.04.2 LTS x86_64
**CPU:** AMD Ryzen 5 3600 (5) @ 3.600GHz
**GPU:** NVIDIA GeForce GT 710
**Memory:** 16384MiB - I used 2 GB for the mc server in the videos, but also tested it on localhost with 5 GB with a similar effect

**Comment by lucko** [comment]
Try using a profiler like spark (https://spark.lucko.me/) to debug further.

You need to create a profile while the gamemode switch happens.
