### ISSUE TITLE
Add support for bedrock users (GeyserMC)

### ISSUE THREAD

**Issue by Tobi-Jakka** [lucko/LuckPerms#3122]
### Description

When using GeyserMC the users have a . (or whatever prefix you choose infront of their name). I noticed luckperms dont support this. I know that GeyserMC gives them a uuid of some sort as it works fine with some other plugins.

### Proposed behaviour

This would allow for not only interacting with java players but bedrock players as well. For example I have a bedrock user called ".killalittle05" if support is added I should be able to do /lp user .killalittle05 info which I cannot do currently.

Not sure how well I wrote this but hope that its understandable :)

Thanks,
- Tobi

**Comment by AgentIce** [comment]
This is already a thing ;)
In your luckperms config in line ~633 you will find a setting called 'allow-invalid-usernames: false'.
When set to true, this should no longer be an issue.

**Comment by Tobi-Jakka** [comment]
Okay thanks! Wasnt aware but man that was a quick reply, is there somewhere where I can donate to support the project! :)

- Tobi

**Comment by AgentIce** [comment]
You could join the team of patreons here if you want: https://www.patreon.com/luckdev
![image](https://user-images.githubusercontent.com/69111163/127691627-0e3481c6-e2c4-4cf2-8f03-d74f505850b2.png)

**Comment by Tobi-Jakka** [comment]
Alright, thanks I did so!

**Comment by lucko** [comment]
Just saw - thank you! Much appreciated :')
