### ISSUE TITLE
LuckPerms hangs Velocity

### ISSUE THREAD

**Issue by SlimeDog** [lucko/LuckPerms#3123]
### Description

LuckPerms-Velocity-5.3.54 hangs the velocity proxy. The console does not respond.

### Reproduction steps

1. Update to LuckPerms-Velocity-5.3.54 from LuckPerms-Velocity-5.3.53
2. Restart the proxy
3. Observe that the console is hung

### Expected behaviour

This issue does not exist prior to LuckPerms-Velocity-5.3.54, specificallyLuckPerms-Velocity-5.3.53

### Environment details

* Server type/version: `Velocity 3.0.0`
* LuckPerms version: `LuckPerms-Velocity-5.3.54`

**Comment by lucko** [comment]
433272518f8a35d3ce54e865c46b55e030b7e3c0

Thanks :)

**Comment by SlimeDog** [comment]
Confirmed fixed in LuckPerms-Velocity-5.3.55. Thanks.
