### ISSUE TITLE
Memory Leak or just huge allocation?

### ISSUE THREAD

**Issue by LucidAPs** [lucko/LuckPerms#3124]
I am using mysql as a database, this is headdump using spark.
![image](https://user-images.githubusercontent.com/42933023/127739344-efbb79f5-8f65-4e56-a44d-c44dfe54e0b1.png)
![image](https://user-images.githubusercontent.com/42933023/127739351-24ff056e-3703-4188-a4e9-9acb59467382.png)
![image](https://user-images.githubusercontent.com/42933023/127739406-dd821be3-1089-431b-af33-d65c6147f567.png)
Let me know if you want the whole 6gb dump.

**Comment by LucidAPs** [comment]
![image](https://user-images.githubusercontent.com/42933023/127743109-6653a181-4796-40c5-a5b1-9948bf04dc2e.png)
![image](https://user-images.githubusercontent.com/42933023/127743114-ffdbae56-61a3-4c8d-8051-00fed01fe387.png)

**Comment by lucko** [comment]
The user housekeeper should be unloading the users after they quit the server.

Using the `debug-logins` config option will allow this to be monitored in the console / log files. Try enabling it to see.
