### ISSUE TITLE
Storage type loading as H2 when mysql is chosen (1.12-pre5)

### ISSUE THREAD

**Issue by AlmightyZing** [lucko/LuckPerms#313]
I'm trying to set up LuckPerms using a mysql database on my server and am running into issues where even though I set the storage-method to mysql it's using H2 when the server boots up. The tables were set up properly using the schema provided. I did notice that the only 2 drivers in /plugins/LuckPerms/lib are h2 and caffeine. Not sure if that's part of the issue or not. I figured if it was having issues loading mysql it would have thrown errors instead of just defaulting to H2.

I'm running on Spigot 1.12-pre5 and have attached a screenshot of the relevant section of the config.yml and the server console. If this is an issue related to running on a snapshot please let me know as we're looking to switch my main server over to spigot when 1.12 officially releases tomorrow.

http://imgur.com/a/jMbPt

Thanks

**Comment by lucko** [comment]
Nothing to do with the new spigot version.

You need to make sure the file has actually been saved. Completely stop the server, double check the config file, and then start the server again.

**Comment by AlmightyZing** [comment]
I've done that several times. 

Stopped the server.
Opened the config.yml from the ftp server, discarding the local file and opening a new one. (also tried manually deleting the local file to make sure it pulled the most current one)
storage-method still says mysql
Started the server
Still says it's using H2

**Comment by AlmightyZing** [comment]
It looks to be working now. I was running version 3.1.53. Updated to 3.2.11 and it chose MySQL.
