### ISSUE TITLE
Toxic Discord Page

### ISSUE THREAD

**Issue by MCTyler** [lucko/LuckPerms#3138]
Can you Please fix the Toxic People on your Discord Page? There is much hatred and berating there. Thanks!

**Comment by ApertureDevelopment** [comment]
Hello,

Could you kindly elaborate? It may seem obvious to you what you mean but maybe not for others. If you want things to be changed you should give an appropriate explaination of what you find wrong and how you think they could do better.

Thank you very much and have a great day

**Comment by Turbotailz** [comment]
Could you be any less vague
