### ISSUE TITLE
LP unable to load in bungee.

### ISSUE THREAD

**Issue by steven5297norton** [lucko/LuckPerms#314]
```
07.06 20:35:25 [Server] WARNING Error enabling plugin LuckPerms
07.06 20:35:25 [Server] INFO java.lang.NoClassDefFoundError: org/bukkit/plugin/java/JavaPlugin
07.06 20:35:25 [Server] INFO at java.lang.ClassLoader.defineClass1(Native Method)
07.06 20:35:25 [Server] INFO at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
07.06 20:35:25 [Server] INFO at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
```

**Comment by johnfg10** [comment]
you have the wrong version it looks like you downloaded the bukkit version not the bungee version

**Comment by steven5297norton** [comment]
When I downloaded the plugin from spigot it only gave me bukkit version.

**Comment by johnfg10** [comment]
Try using the version I linked to

**Comment by steven5297norton** [comment]
That worked. It would help if both plugins are together.

**Comment by EmanYm** [comment]
They are together.  You just need to know where to look. :)
https://ci.lucko.me/job/LuckPerms/

**Comment by lucko** [comment]
The link to the BungeeCord version is at the top of the Spigot page.
