### ISSUE TITLE
Prefixes Not Working

### ISSUE THREAD

**Issue by daboss179** [lucko/LuckPerms#3147]
### Description

So I am using version 1.17 and I made a new group with a prefix. The prefix itself is showing when I type /lp user [username] info but it isn't showing up when I type in chat. I have both the essentials and vault plugins and made sure that the format was correct. Does anyone know something I can try?

**Comment by benwoo1110** [comment]
If it shows correctly in `/lp user [username] info`, then contact your chat plugin support.

**Comment by daboss179** [comment]
Okay yeah makes sense. Lucky perms seems to be doing its job it's probably on vault or essentials side.
