### ISSUE TITLE
Priority in Groups

### ISSUE THREAD

**Issue by rlemish** [lucko/LuckPerms#315]
Sometimes you need to add a player to several groups. For example: One constant, the second has a lifetime. The second must overlap the rights of the first at the time of its existence, this requires priority.
We use the [rscPermissions ](https://github.com/SimSonic/rscPermissions) plugin. 
Here it is realized, [that's the field](https://github.com/SimSonic/rscPermissions/blob/master/src/main/resources/sqlt/Deployment.sqlt)
`inheritance_priority`.
The absence of such a mechanism stops us from switching to your plugin.
Thank you in advance! We will wait for the update.

**Comment by lucko** [comment]
This exists already. 

https://github.com/lucko/LuckPerms/wiki/Command-Usage#lp-group-group-setweight
