### ISSUE TITLE
let perms can work with placeholderapi

### ISSUE THREAD

**Issue by MusicTW** [lucko/LuckPerms#3154]
like this
set perm cmi.command.sethome.%cmi_equationint_{cmi_user_maxperm_cmi.command.sethome_1}+6%
and return cmi.command.sethome.11 to the player (5(5 is from default group)+6)

**Comment by lucko** [comment]
This could be achieved using another plugin to intercept command executions before they are handled by LuckPerms.

Unfortunately, I don't think this is a good fit for inclusion in LuckPerms itself.
