### ISSUE TITLE
Mysql: No operations allowed after connection closed.

### ISSUE THREAD

**Issue by Akashiic** [lucko/LuckPerms#3155]
### Description

relentless flood on my console.

### Reproduction steps
config
    maximum-lifetime: 1440000 # 24 minutes

    # This setting controls how frequently the pool will 'ping' a connection in order to prevent it
    # from being timed out by the database or network infrastructure, measured in milliseconds.
    # - The value should be less than maximum-lifetime and greater than 30000 (30 seconds).
    # - Setting the value to zero will disable the keepalive functionality.
    keepalive-time: 0

    # This setting controls the maximum number of milliseconds that the plugin will wait for a
    # connection from the pool, before timing out.
    connection-timeout: 20000 # 20 seconds

### Expected behaviour
I've already changed the config to how it was on the wiki and the flood was still on the console

Lucperms is flooding this "[luckperms-scheduler-worker-1] WARN me.lucko.luckperms.lib.hikari.pool.PoolBase - luckperms-hikari - Failed to validate connection me.lucko.luckperms.lib.mysql.cj.jdbc.ConnectionImpl@3e375342 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value." code on my console relentlessly, and I've already taken a look at the luckperms wiki and already contacted my host to see the maximum-lifetime & wait_timeout info, and I've put this info in the luckperms config and I still insisted the problem, I already set the certificate and ssl verification as false and still without success, I set the max pool size and minimum iddle as 50 and still without success, I don't know what else to do =/

### Environment details
Console Pterodactyl
* Server type/version: `Crucible/Thermos Next Generation` running version `1.7.10` build `5.0`
* LuckPerms version: `5.3.4`

**Comment by lucko** [comment]
I see you've already seen this page, but I'll draw your attention to a specific part of it once more:

https://luckperms.net/wiki/Storage-system-errors (the first few paragraphs)

The error messages are not originating from LuckPerms, there is nothing I can do to fix them.

The wiki page contains my exhaustive advice on the issue, anything further is beyond what I am capable of helping with.
