### ISSUE TITLE
Cannot open LP Editor

### ISSUE THREAD

**Issue by Zenramen** [lucko/LuckPerms#3156]
### Description

wen /lp editor is inputed, the response is (lp editor.... is running

### Reproduction steps

do /lp editor

### Expected behaviour

the webpage to open

### Environment details

Luckperms latest version, paper 1.7.1
* Server type/version: `ExampleSpigot` running version `1.12.2` build `???`
* LuckPerms version: `v???`

**Comment by lucko** [comment]
Please put some effort into supplying the requested information. I cannot help you without it.
