### ISSUE TITLE
What is the permission node for custom commands? (MyCommand Plugin)

### ISSUE THREAD

**Issue by Canedox** [lucko/LuckPerms#316]
Hey,
What is the permission node for the custom commands i made?

For example ''/mine'', how do i make a spesific rank (PEX) get the permission to do /mine?

**Comment by lucko** [comment]
You'd have to refer to the documentation of MyCommand

**Comment by Canedox** [comment]
In examples.yml the name is '
MineA:
  command: /mine
  type: ALIAS
  alias: /warp a
  permission-required: true

What would the permission node for this be?

**Comment by lucko** [comment]
Yeah, I don't know what it is. 

You can use this to work it out: https://github.com/lucko/LuckPerms/wiki/Verbose
