### ISSUE TITLE
Setting a blank prefix causes LP to not load correctly

### ISSUE THREAD

**Issue by Internal-Exception** [lucko/LuckPerms#3160]
### Description
Setting a blank prefix in a group, i.e "", will work until restart then on restart LP will throw an error and not load any prefixes.

Only an issue with "storage-method: yaml". Works correctly when in db mode. 

### Reproduction steps
1. /lp creategroup newgroup
2. /lp group newgroup meta addprefix 1 ""
3. /lp user you parent add newgroup
4. Restart the server

### Expected behaviour
A player with no prefix.

### Environment details
Paper 243. 1.17.1
LP v5.3.48

Log output: https://gist.github.com/Internal-Exception/9a77cbb20b554dd200aedf1fee7b8644
Group file after restart: https://gist.github.com/Internal-Exception/510ac47e5a07bbdde05dbd49bca23ddb

**Comment by lucko** [comment]
Should be fixed by that commit - you may need to delete the broken lines from the .yml file to get it to start nicely.
