### ISSUE TITLE
Nicknames

### ISSUE THREAD

**Issue by Kirito1786** [lucko/LuckPerms#3161]
In my Tab the nicknames i do show up normally but then in chat it doesent i will try later if its to do with luckperms if it is/isnt i will reply later in like 10 mins bcs its rlly annoying me and ppl on my server are complaining and im simply not smart enough to fix this

**Comment by Kirito1786** [comment]
im back and i deleted the luckperms config and yes luckperms was the cause of nickname not showing can u help me?

**Comment by benwoo1110** [comment]
Luckperms has no ability or feature to display anything in chat.

**Comment by Kirito1786** [comment]
ohh ok do u know where i can find a page like this for plugin LPC 
aka luckperms chat

**Comment by lucko** [comment]
Please do not ignore the issue template.
