### ISSUE TITLE
The fabric version of luckperms should be able to give perms for normal Minecraft commands.

### ISSUE THREAD

**Issue by O3nboi** [lucko/LuckPerms#3167]
### Description
My suggestion is that you should be able to give players perms for vanilla admin commands in luckperms fabric, like how it works in bukkit.

### Proposed behaviour
On a fabric server with luckperms and fabric API in the mods folder, the command /luckperms user [user] permission set minecraft.commands.op should give the user the ability to do the /op command, exactly how it works in bukkit.

**Comment by benwoo1110** [comment]
Luckperm doesnt provide those permissions. It is up to the server software. You can see https://github.com/lucko/LuckPerms/issues/2961#issuecomment-817161201
