### ISSUE TITLE
Error while giving permission

### ISSUE THREAD

**Issue by WarnDa** [lucko/LuckPerms#3179]
### Description
I tried to add a permission to an user, it gave me a lot of errors (but it worked), and 10mn after, I tried again and I didn't get any error.
So sometimes it throw errors without reason, I didn't restart the server or change anything.

### Reproduction steps
Give a permission to a player

### Expected behaviour
Shouldn't throw an error

### Environment details
<img width="225" alt="Screenshot_6606" src="https://user-images.githubusercontent.com/31826333/136664319-32b817b6-ec83-40da-8c83-db1b9e508feb.png">

Error in console :
https://pastebin.com/CMvz6VaJ

**Comment by lucko** [comment]
Update your server software and LuckPerms to the latest versions
