### ISSUE TITLE
How to add prefix or suffix with "space"?

### ISSUE THREAD

**Issue by tuanjr** [lucko/LuckPerms#318]
example:
/perm user luck meta addprefix 100 &cthe great&r
won't work. Only "the" is set

**Comment by lucko** [comment]
Wrap the prefix in quotes. 

/perm user luck meta addprefix "&cthe great&r"

**Comment by 0H4rl3qu1n0** [comment]
This doesn't work

**Comment by Andre601** [comment]
> This doesn't work

That doesn't give any info.
WHAT doesn't work?
WHAT did you try?

**Comment by Hissam1048v** [comment]
Actually that works

**Comment by Xqow** [comment]
I agree, it works.

**Comment by LeotomasMC** [comment]
this is a closed issue from 6 years ago. is there any particular reason you needed to comment on this?

**Comment by Zaxerf1234** [comment]
> /perm user luck meta addprefix "&cthe great&r"

It is working, you just forgot to add prority:

/perm user luck meta addprefix 100 "&cthe great&r"
