### ISSUE TITLE
Console spammed because `TabTPS` mods

### ISSUE THREAD

**Issue by barraIhsan** [lucko/LuckPerms#3183]
### Description
So my console was spammed by `An exception was thrown by me.lucko.luckperms.fabric.context.FabricPlayerCalculator`
[Full Message](https://paste.lucko.me/dQ7A6bIo9m)

### Reproduction steps

1. Install Fabric
2. Install [TabTPS](https://modrinth.com/mod/tabtps) and [LuckPerms](https://www.curseforge.com/minecraft/mc-mods/luckperms)

### Expected behaviour
Nothing Happened

### Environment details

* Server type/version: `Fabric` running version `1.17.1`
* LuckPerms version: `v5.3.9`

**Comment by Laarryy** [comment]
Apologies for my poor wording - I meant to say it's not one of the recent versions of luckperms. Please reproduce on 5.3.69 from https://luckperms.net 😄

**Comment by emilyy-dev** [comment]
Did you update LuckPerms to the latest build on the website? If so please share the server logs again, if not please update LuckPerms as Larry suggested and try to reproduce the issue then.
