### ISSUE TITLE
Server permission desync

### ISSUE THREAD

**Issue by caxerx** [lucko/LuckPerms#319]
I am using BungeeCord and Spigot 1.11 with luckperms dev build 221
This is the situation:
I have bungee and 2 lobby server, 2 lobby with same config
Bukkit Config: https://pastebin.com/KNMivULt
Bungee Config: https://pastebin.com/gmFbTKwx
I am in lobby1, and lobby2 is empty

First I add a permission with
/lp user caxerx permission set test.node true server=global

Then I use /lp sync
so I can see test.node on both
/lp user caxerx permission info 
and
/lpb user caxerx permission info

Then I go to lobby2, and lobby 1 is empty now

I try both
/lp user caxerx permission info
and
/lpb user caxerx permission info 
now test.node is disappear now, even I try /lpb sync again

but test.node show again after I transfer lobby1

**Comment by lucko** [comment]
Check your IP forwarding is setup correctly for BungeeCord.

**Comment by caxerx** [comment]
oh yes, one of the lobby have bungeecord disabled. Thanks for helping. All of them works now
