### ISSUE TITLE
Web Editor Expiry not working

### ISSUE THREAD

**Issue by TheNickSkater** [lucko/LuckPerms#320]
Its a small problem, but still:

On the newest plugin Version (v3.1.53) if I use the Web Editor for groups or players and I add time to Expiry, i cant add the permission :/ Only without Expiry time. Thats all

**Comment by lucko** [comment]
Sorry, I don't understand what you mean.

Can you give an example?

**Comment by TheNickSkater** [comment]
If I use for example /lp user <user> editor and click on the link the Website opens normaly. But If I enter a Permission to add AND an expiry time and press the + it does not work, only if I leave the Expiry box empty.

**Comment by lucko** [comment]
Alright, I'll look into it.

Please open a ticket here though. ;)
https://github.com/lucko/LuckPermsWeb

**Comment by TheNickSkater** [comment]
also by issues?

**Comment by lucko** [comment]
Yes.
