### ISSUE TITLE
LP hang during server boot

### ISSUE THREAD

**Issue by EmanYm** [lucko/LuckPerms#322]
On all of my servers I get [this two minute hang](https://hastebin.com/ibiputexez.md) during LuckPerms loading.
This test was done on a hosted server with only `SpongeForge 5.2.0 build 2350` and `LuckPerms 3.2.8 build 217` in the mods folder.  Forge 12.18.3.2297 as my server jar.

**Comment by lucko** [comment]
The initial data load is just LuckPerms loading all of your group data into memory. It shouldn't take more than a couple of seconds, usually much less.

I don't know for sure why it's taking so long, but I'd guess that it's because of a really slow MySQL server, or a bad connection between your server and the MySQL server. It's very unlikely to be a LP issue.

**Comment by EmanYm** [comment]
This hang also happens during server start on the server the database is stored on.
I'll just conclude that the connection is slow.  Likely because the databases are on a different box than the servers.  I can contact my host support and inquire, but I don't think it really breaks anything.

**Comment by lucko** [comment]
Yes, I'd report it to them. It's definitely not normal.

**Comment by EmanYm** [comment]
Do you think the amount of lines on the database might have something to do with it?
I used my build server (which I'm changing back to 1.10.2 after testing 1.11.2) and installed just SpongeForge and LuckPerms, set the database to the one actually assigned to the server (it was empty at the time), and it was almost instant.

Then I imported the existing database, and there was the roughly two minute delay.

I can explain how I have it set if you need.

**Comment by lucko** [comment]
Might be. If your database is under a lot of load, that might explain the delay. However, 2 minutes is not normal at all, even if the database was overloaded.

**Comment by EmanYm** [comment]
21 pages (one per rank/group) of 500 lines is 10,500 lines on the database.
I tried figuring out how to explain it to you, but my brain can't put it in words.  The easiest way to show you might be to send you the file...

It's mostly placeholders (roughly three hundred per page) for adding, removing and changing permissions between groups without having to move a bunch of ids around.  I can probably change that to 100 lines per group with minimal issue, and knock it down to 2,100 lines.

**Comment by lucko** [comment]
Run `/lp export` and paste the output to GitHubs GIST. You can PM it to me on Discord if you'd prefer it to not be public.
