### ISSUE TITLE
Something I am getting in console

### ISSUE THREAD

**Issue by EmanYm** [lucko/LuckPerms#323]
>[07:09:39] [Server thread/INFO] [com.zaxxer.hikari.pool.PoolBase]: luckperms - Driver does not support get/set network timeout for connections. (com.mysql.jdbc.JDBC4Connection.getNetworkTimeout()I)

This particular line was from
SpongeForge 6.1.0-build 2378
LuckPerms 3.2.14-build 224

**Comment by lucko** [comment]
`INFO`, so not an error. ;) You can just ignore it.

**Comment by EmanYm** [comment]
I honestly didn't see the "info" part...
If you're able, just delete this...
