### ISSUE TITLE
Converting from groupmanager to mysql. (Data too long for column 'name' at row 1)

### ISSUE THREAD

**Issue by andrewkm** [lucko/LuckPerms#325]
I'm getting this error when converting from groupmanager.
Command: /lp migration groupmanager false

Result ends at:
https://pastebin.com/raw/UQ3kYe3i

Using very latest LuckPerms from jenkins as of this issue post.

**Comment by andrewkm** [comment]
One of the group names it seems was too long. Issue solved by reducing size of group name. Would be nice if LuckPerms told you in console what the group was. Anyhow, alls good now :)

**Comment by lucko** [comment]
Yeah, the length checking is done internally when creating groups with the commands, but isn't caught by the migration. 

I guess I can just truncate the name so it fits within the limit.

**Comment by lucko** [comment]
Actually scratch that, I think throwing an exception is probably the correct behaviour. However, it's something I'll add to the migration wiki page so you can be aware of it before the process starts.
