### ISSUE TITLE
Set player suffix

### ISSUE THREAD

**Issue by JamieSinn** [lucko/LuckPerms#327]
I've got as far as creating a node via the NodeFactory, but where do I set the suffix?
Context's as far as I've seen are read only due to caching.

MetaUtils is deprecated,
API docs don't mention it as far as I've seen

Is it as simple as setting that as a permission on a user?

**Comment by EmanYm** [comment]
Check [here](https://github.com/lucko/LuckPerms/wiki/Prefixes,-Suffixes-&-Meta#how-do-i-actually-set-prefixes-and-suffixes-for-a-user)

**Comment by JamieSinn** [comment]
I'm talking about doing this programmically, not via commands

**Comment by creator3** [comment]
Creating a suffix node: https://luckperms.lucko.me/javadocs/me/lucko/luckperms/api/NodeFactory.html#makeSuffixNode-int-java.lang.String-

Setting the context:
https://luckperms.lucko.me/javadocs/me/lucko/luckperms/api/Node.Builder.html#withExtraContext-java.lang.String-java.lang.String-

**Comment by lucko** [comment]
Follow the steps outlined here: https://github.com/lucko/LuckPerms/wiki/Developer-API#adding-a-permission-to-a-potentially-offline-user

And then just construct the node using the method @creator3 linked.
