### ISSUE TITLE
Help? Can't figure out how permissions work

### ISSUE THREAD

**Issue by Eufranio** [lucko/LuckPerms#33]
Well, I have Nucleus and LuckPerms installed on my SpongeForge 1.10.2 server. I can't figure out how the groups/permissions work...

Iinitially, I created a group called **admin**. After, I used **/nucleus setupperms ADMIN admin**, and the group received the right permissions. Then, I used **/luckperms user <my nickane> setprimarygroup admin**, but I still having no permissions. Same happened with the default group (I used **/nucleus setupperms USER default** to add permissions to the default group).

Can you help me, or point me to a wiki/something else?

**Comment by lucko** [comment]
Uhh, sorry for the delay in replying.

You can read the wiki pages here on GitHub, but that actually sounds like an issue with LuckPerms. I'll look into it and get back to you. 🙂

**Comment by lucko** [comment]
Would you mind retrying with the latest build? https://ci.lucko.me/job/LuckPerms/

**Comment by Eufranio** [comment]
Tested in a new server, it's working now. The problem was that the plugin (by a reason) needed some server-running time to set up stuff. Thank you by your work, closing as it's fixed now
