### ISSUE TITLE
Calling setPermission on group subjects doesn't always save

### ISSUE THREAD

**Issue by bloodmc** [lucko/LuckPerms#330]
As title states, whenever I attempt to call setPermission on group subjects, it doesn't always save to storage. Player subjects have no issues.

Tested with LP 3.2.20

**Comment by lucko** [comment]
I'm still thinking about the best way to solve this. Rest assured I haven't forgotten, just don't want to rush a crappy (potentially more broken) solution.

**Comment by lucko** [comment]
Should be fixed.

**Comment by bloodmc** [comment]
@lucko just tested build 3.3.20 and this appears to still be an issue.

I'm testing with json storage and running the following command

https://github.com/MinecraftPortCentral/GriefPrevention/blob/master/src/main/java/me/ryanhamshire/griefprevention/command/CommandHelper.java#L482

This doesn't always work properly with groups. I'll have to execute my command multiple times in order to see it work. However, sometimes it works instantly.

**Comment by lucko** [comment]
Might be an issue with the way i/o via Sponge is being buffered.

**Comment by bloodmc** [comment]
OK it seems like if I let it sit for awhile,  the permission is eventually applied. So the issue is, why do group permission set/unsets take much longer than players randomly?

**Comment by lucko** [comment]
Should be fixed (kinda) by: d60d0ac9c54a052678df037b8e6a1d1de95c5e01

I want to avoid removing the buffering completely, as it completely kills the storage whenever plugins try to make bulk changes to permissions.
