### ISSUE TITLE
bungeecord+LuckPerms-Bungee

### ISSUE THREAD

**Issue by xbette** [lucko/LuckPerms#331]
When i start my bungee whit LuckPerms-Bungee-3.2.20 and LuckPerms-3.2.20 on my survival server
then the luckperms "/lp" work fine 
But the LuckPerms-Bungee "/lpb" doens't work, only thing i get is "[LP] Running Luckperms v3.2.20" 
I've posted this on the Bungee github also, but they told me it was the plugin that does the issue!

"Merjilin told me to make an issue here"

Bungee github issue link: https://github.com/SpigotMC/BungeeCord/issues/2175

**Comment by merjilin** [comment]
Just to add additional information, they stated their bungee permissions were working fine before updating bungeecord to 1.12.

**Comment by lucko** [comment]
Was a config issue.
