### ISSUE TITLE
Feature Request: Skript

### ISSUE THREAD

**Issue by GermanMinerDE** [lucko/LuckPerms#334]
Hi,

do you think, you can integrate an AddOn for the scripting-language "Skript"?
Skript is an easy development language for Spigot / Bukkit and makes it possible for "java-haters" to build complex things.

Some information you can find on: https://forums.skunity.com

In the Add-on there should be...
... some events, e.g.:
- on group change

...some effects, e.g.:
- set group of player to "GROUP"
- add permission "mmm.mmm" to player

...some expressions, e.g.:
- player's group
- player's permissions

Would be great! :-)

**Comment by lucko** [comment]
I have no intentions for adding internal support for it. The majority of servers don't use Skript and therefore the additional code would just be bloat.

LP exposes an API which you can use for your Skript projects.
https://github.com/lucko/LuckPerms/wiki/Developer-API
