### ISSUE TITLE
Fly command

### ISSUE THREAD

**Issue by CoodlesSmoogles** [lucko/LuckPerms#336]
Ok so I made a new group called Member and Citizen. 

Owner, Admin, Mod. and Helper have the ability of fly command.

For some reason, Member and Citizen also have the fly command. 
What...
...the
Hell.

**Comment by merjilin** [comment]
You need to assign group weights so your lowest group has the lowest weight and the weight increases as the ranks incline. So owner would have the largest weight. The command used to do this is /lp group <grough> setweight <number>

**Comment by merjilin** [comment]
Urgh. /lp group <group> setweight {weight}. It disliked my one above for some reason.

**Comment by CoodlesSmoogles** [comment]
Ok so i set the weight to both for 1 and owner 1000, admin 100, mod idk 50?

**Comment by merjilin** [comment]
Irecommend you don't have groups with the same weight as it will only cause issues. My system has default as 1, second group as 2 and so forth.

**Comment by CoodlesSmoogles** [comment]
Ok, after setting the weights, all groups can fly even tho I have set different permissions. Still not getting this

**Comment by merjilin** [comment]
What group did you assign the fly permission to?

**Comment by CoodlesSmoogles** [comment]
mod, admin, owner, co-owner, and I have inherited Admin to Mod

**Comment by merjilin** [comment]
And can you give me an example of the parent command you did to have one group inherit the other permissions.

**Comment by CoodlesSmoogles** [comment]
/luckperms group mod parent add admin

At first I did it the other way around cause im stupid, then I changed it

**Comment by merjilin** [comment]
You'll find that you did it right the first time ;) 
The command usage is:
/lp group {higher group} parent add {lower group}

To stop confusing, think of parent as inheritance. So in your case, /lp group mod parent add admin. Mod is inheriting the permissions of admin rather than admin inheriting the permissions of mod.

So the correct command you'd need for that is:
/lp group admin parent add mod

**Comment by CoodlesSmoogles** [comment]
Ah ok. Still got this problem lol. 

Maybe If i export my LuckPerms file I can see whats inheriting this? if so how to make a file for luckPerms?

**Comment by CoodlesSmoogles** [comment]
Also to add on to that I did do essentials.fly true

after each command to owner, admin, mod, etc...
but not Member or Citizen

**Comment by merjilin** [comment]
Just to check, do member and citizen have access to all commands from the upper groups, and not just /fly?

**Comment by CoodlesSmoogles** [comment]
I made sure, they dont have commands as would higher ups do

**Comment by merjilin** [comment]
And this could actually be an issue with essentials. First odd, please make sure you're using essentialsX and try the version found here: https://ci.lucko.me/job/Essentials/ since i know this one does work for other servers.

I expect another issues is the way you've done the parenting system. What you've described to me is that the lower groups are inheriting the permissions from the higher groups.

**Comment by merjilin** [comment]
And please make sure you're using the latest luckperms found here: https://ci.lucko.me/job/Essentials/  ;)

**Comment by merjilin** [comment]
Oh bugger xD second try https://ci.lucko.me/job/LuckPerms/

**Comment by CoodlesSmoogles** [comment]
I figured out the problem, I was also in the mod group AND citizen group lmao.

And what version are those essentials? for which minecraft versions? cause the ones i got are on 1.8

**Comment by CoodlesSmoogles** [comment]
***says 1.8+

So im assuming i got latest version

**Comment by merjilin** [comment]
Those essentialsX jars should work on all versions

**Comment by merjilin** [comment]
I use them on 1.7 and others use them across all the other versions.

**Comment by merjilin** [comment]
if this issue is now sorted, please close this issue just to tidy things up :)

**Comment by CoodlesSmoogles** [comment]
how do i close it lol

**Comment by CoodlesSmoogles** [comment]
oh nvm im still retarted..got it lol
