### ISSUE TITLE
lang.yml causing NPE's

### ISSUE THREAD

**Issue by PiggyPiglet** [lucko/LuckPerms#338]
Hi, I was going to edit the lang.yml and as soon as I added the default lang file into my luckperms folder, I start getting these NullPointerExceptions on startup. 
LuckPerms startup: [Paste](https://paste.lucko.me/6vY2mPbDV9)
Plugins: LuckPerms, Vault, CrateReloaded
Spigot Version: git-Spigot-b78587d-753a8e7 - the latest as of writing this issue.
LuckPerms Version: 3.2.26 - the latest as of writing this issue.
Running on Windows 10 via git bash, with 3gb of ram allocated and java 8 (131).

**Comment by lucko** [comment]
Thanks for reporting :)
