### ISSUE TITLE
Prefix's not working?

### ISSUE THREAD

**Issue by Galadriel1640** [lucko/LuckPerms#339]
I apologize if this is just me being dumb, but I have installed LuckPerms on my Sponge server, along with Nucleus.  I am also running BungeeCord and have downloaded MultiChat and placed it in the BungeeCord plugin folder and the Sponge mod folder as the plugin stated.  I had followed the LuckPerms tutorials for basic group setups and got to the prefix section and have been unable to successfully get a prefix to show in chat.  I've tried switching chats, I've tried several other chat plugins, and I have tried messing with some config files in each of the above and still cannot seem to get it to work.  To my knowledge these are all supported, so maybe I have simply missed something?  All plugins used are up to date.  Sorry again if this is my incompetence!

**Comment by lucko** [comment]
Uhh, first thing I'd do is make sure the value you want is showing up in the output to `/lp user <you> info`, under "Current Prefix".

If the value shows up correctly there, then the issue lies with your chat formatting plugin.

**Comment by Galadriel1640** [comment]
Yeah I think you're right then, I spent hours trying to fix it then just downloaded gChat and it works like a charm! So thanks! Will gChat ever get more features?  Or stay simple chat functionality?

**Comment by lucko** [comment]
Staying simple for now.
