### ISSUE TITLE
Multiple Prefixes

### ISSUE THREAD

**Issue by lcovey22** [lucko/LuckPerms#340]
So I have prefixes assigned by groups on a single track, with 8 groups, and their prefixes ranging from 1 to 8. I have a feature on my server "titles" which uses LuckPerms to add a prefix on top of the user's group prefix and to replace it. But when I add this, it just adds on. So if they were [Member] then bought [King] title the end result would be '[Member] [King] user: chat' which isn't what I want, solely the [King] title. I am using "highest" as the option for prefix stacking. [Here is my config](https://pastebin.com/SdruPFMD), and .yml file for the [User](https://pastebin.com/u44L6kSA) and [Group](https://pastebin.com/LCPAXvMx). I tried to include as much info as possible, if more is needed let me know. Thanks for the great plugin!

**Comment by lucko** [comment]
If you're using "highest", then only one value will be used.

Perhaps the extra prefix is being added by your chat plugin?

**Comment by lcovey22** [comment]
I'm using Towny chat, and it's fairly clear to me that it's not causing the problem but rather that LuckPerms is reading two of my prefixes, sorry for the late reply but please don't keep this issue closed.
My towny configuration for chat is:
global: '{permprefix}&7{modplayername} {towntag}:' and I can't see how this would add a second prefix unless I'm using the wrong towny chat+LuckPerms placeholder. Appreciate the help,
Luc

**Comment by lucko** [comment]
Try removing the permprefix part.

**Comment by lucko** [comment]
Actually no, this is a Towny bug.

https://github.com/ElgarL/Towny/blob/master/src/com/palmergames/bukkit/towny/permissions/VaultPermSource.java#L21-L57

https://github.com/ElgarL/TownyChat/blob/master/src/com/palmergames/bukkit/TownyChat/TownyChatFormatter.java#L143-L148

`{permprefix}` will include both the players own prefix, and the prefix of their primary group.

**Comment by lucko** [comment]
Please open a new issue.

**Comment by bchewy** [comment]
still an on-going issue with latest townychat version & this, if anyone is still tracking this issue

**Comment by benwoo1110** [comment]
Please open a new issue.
  And follow the issue template with explain of how luckperms is potentially causing such an issue.
