### ISSUE TITLE
Permission set error

### ISSUE THREAD

**Issue by GordanJankson** [lucko/LuckPerms#341]
So I've been trying to for the past week to set hologram permissions to my user group, and to the user group that my group is inherited too, and I asked for help from the Holograms devs, and they said to come here and make an issue post since this is a LuckyPerms issue NOT a holograms issue. The problem is when I set the permission for the holograms, it still says that I don't have permission to use the holograms and after debugging it says that for default/user it's undefined and for me, myself, it says undefined as well. The Holograms plugin I'm using is the one that's provided by pixelmon.me multicraft so I can't even tell the version of it. I honestly have no clue what to do, so help is definitely needed. Thank you in advance for any help.

**Comment by lucko** [comment]
Have you tried using `/lp verbose` to debug which permission node is being checked for?

https://github.com/lucko/LuckPerms/wiki/Verbose

**Comment by GordanJankson** [comment]
Yes, the verbose is how I debugged and saw that it was saying that only me and the user groups default/user had the permission saying undefined.

**Comment by lucko** [comment]
Make sure you set the permission to default then. Like, I don't know what you want me to tell you other than that?
