### ISSUE TITLE
Default (?) Prefixes

### ISSUE THREAD

**Issue by lolzelig** [lucko/LuckPerms#345]
Hello :)

Please excuse this rather basic issue that I have, but.. how do I remove the light grey [default] prefix from users of the default group?

Same goes for other groups I create...

Again, sorry, this is probably a very simple fix, but I just can't seem to find it.

**Comment by EmanYm** [comment]
add a prefix to the default group?
Or there is `group-name-rewrite` option in the config.

**Comment by lolzelig** [comment]
Doesn't help... I don't want default members to have any prefix at all

**Comment by lucko** [comment]
Which chat formatting plugin are you using?

**Comment by lolzelig** [comment]
EssentialsXChat

**Comment by lolzelig** [comment]
I kind of solved it now by setting "§7" as group-name-rewrite.. it will still show two brackets, but that's better than the default tag.

**Comment by lucko** [comment]
Pastebin your Essentials config. Sounds like a configuration issue to me. :P

**Comment by lolzelig** [comment]
You are correct. :D
