### ISSUE TITLE
[Future request] Support PlaceholderAPI in prefixes

### ISSUE THREAD

**Issue by BirkhoffLee** [lucko/LuckPerms#346]
As the title said. This helps prefix-centralizing. For example I can set `%javascript_prefix%` to run a JavaScript which determines the user's primary group then return the prefix. So the prefixes can be easily managed.

**Comment by lucko** [comment]
Prefixes are not dynamic in that sense. I don't see how this fits into LuckPerms? Surely that would be better off being in a standalone plugin.
