### ISSUE TITLE
EssentialsX with LuckPerms not responding issue

### ISSUE THREAD

**Issue by cwkfr** [lucko/LuckPerms#347]
Maybe you can help ❤️ 

drtshock/Essentials#1350

**Comment by lucko** [comment]
Weird. Does it happen often?

Might be an unrelated server hang which by chance happened when a permission check was occuring. Those methods shouldn't really be taking too long to execute.

**Comment by cwkfr** [comment]
It rarely happens. I'll keep watching on this with EssX `use-bukkit-permissions` set to `true` (I don't know if this can solve the problem).

**Comment by lucko** [comment]
Alright, feel free to re-open this ticket if it happens again.

Not much I can do at this stage, since I don't know what the issue is. :P
