### ISSUE TITLE
apply-bukkit-default-permissions function NOT working

### ISSUE THREAD

**Issue by misterjacket** [lucko/LuckPerms#348]
Hello,

Even though the **default** group in my server has a count of **0 permissions** and I have **disabled** these settings:

`apply-bukkit-child-permissions: false`
`apply-bukkit-default-permissions: false`
`apply-bukkit-attachment-permissions: false`

They are still able to execute commands like /home, /sethome, /back, /tpa etc.

**Comment by pokemonspeler** [comment]
I have this to please fix this soon

**Comment by EmanYm** [comment]
Do you have any other mods/plugins that include these commands?
Turn on LuckPerms verbose and have someone run one of those commands to see what permissions are being called.

**Comment by lucko** [comment]
This isn't a LuckPerms bug, rather a design flaw (in my opinion) with Essentials.

When Vault is not installed, Essentials will check it's own config for permissions **BEFORE** checking with the permissions plugin.

You either need to install Vault, or remove all of the entries under `player-commands` in your Essentials config.

```yaml
player-commands:
  - afk
  - afk.auto
  - back
  - back.ondeath
  - balance
......
```
