### ISSUE TITLE
Op system

### ISSUE THREAD

**Issue by Demonkid1112** [lucko/LuckPerms#349]
I have enable-ops set to true however the message "The vanilla OP system is disabled on this server. I tried seeing if i could do the autoop perm that failed as well.

**Comment by lucko** [comment]
If `auto-op` is **true**, `enable-ops` is forced to be **false**.

Perhaps that's why you're seeing the message? Remember you need to restart your server for any config changes to take effect. :)

**Comment by Demonkid1112** [comment]
Welp, not my proudest moment, but thank you!

**Comment by lucko** [comment]
No worries :)
