### ISSUE TITLE
Set a default group

### ISSUE THREAD

**Issue by sandor111** [lucko/LuckPerms#350]
Hey i am really having trouble with setting a default group could you please help me.

**Comment by merjilin** [comment]
A default group is automatically given which isn't changeable. There are three ways this can be dealt with: 
1) Use the default group given and just assign it a prefix.
2) Use group-rewrite which is found in the luckperms config.
3) Use default assignments which can be found at the bottom of this wiki page and needs to be edited in the luckperms config. https://github.com/lucko/LuckPerms/wiki/Default-Groups this will make it so when a user enters the default group, you can automatically move them to the group you wish.
