### ISSUE TITLE
Cannot connect to gChat

### ISSUE THREAD

**Issue by Galadriel1640** [lucko/LuckPerms#351]
Hey I switched fully to gChat for my BungeeCord proxy and setup LuckPerms.  Worked fine on my forge server, but the Spigot server needed to have EssentialsxChat installed as well to take any effect.  My problem now, is that I cannot use a global chat and it seems gChat has no sub commands?  The servers both recognize the plugin as running, but I simply cannot link the chats.  Any idea what may be the issue?

**Comment by lucko** [comment]
I'll answer your ticket on the gChat repo.
