### ISSUE TITLE
Player not found

### ISSUE THREAD

**Issue by batkins62** [lucko/LuckPerms#353]
/lp user lazyeye506 info
[03:31:12 INFO]: [LP] User could not be found.

https://mcuuid.net/?q=lazyeye506

I can also verify that my lp config has:
use-server-uuids: true

and my server.properties:
online-mode=true

and usercache.jason:
{"name":"lazyeye506","uuid":"1884f0be-f4b5-4381-8a38-6da1993e5c05"

**Comment by lucko** [comment]
Players need to login to the server first after LuckPerms was installed. LP maintains it's own cache.
