### ISSUE TITLE
Internal UUID Cache

### ISSUE THREAD

**Issue by batkins62** [lucko/LuckPerms#354]
Ticket: #353

This actually is a critical flaw in implementation if this truly is the case, and I would like to encourage you to allow uuid/players to be found regardless if LuckPerms has it in the cache.

if i had installed LuckPerms the day i created my server (April of 2011) this wouldnt be an issue, since all my players would be saved in the internal LuckPerms cache. But the thing is, ive been through many permissions plugin, and since im installing this knowing that, i cant give someone their rank because the internal cache system doesnt see it, im not sure how you expect this to work. I have hundreds of players i need to give a rank to, some i might not see for a year or more.

**Comment by lucko** [comment]
I think describing this as a "critical flaw" is stretching it a bit... This is the first time it has ever been mentioned.

As I said in my previous reply, you can use a players uuid in place of their username in all LP commands, which eliminates the need for requesting their profile.

Anyway, I've implemented your suggestion, but you'll need to enable it using a config option. I want to retain the previous behaviour as default. (the reason for this is that it helps with data integrity. If you're running in offline mode with an auth plugin, the suggested behaviour would cause problems.)

Update to the latest build and set `use-server-uuid-cache` to true. The servers cache will only be used if there is no value stored by LP.

**Comment by SteveKitten** [comment]
Would just like to say thank you for making this work as it was a problem for me as well.
