### ISSUE TITLE
permissions for players who are offline

### ISSUE THREAD

**Issue by imaBASKET** [lucko/LuckPerms#356]
I was told that instead of being an essentials issue, this may be a problem with LuckPerms.

I want to give myself permission to join a server even if its full, however despite having the permission it shows that I do not....

https://i.imgur.com/yhkh8f0.png

Here's the issue I made on the Essentials repo:
https://github.com/drtshock/Essentials/issues/1366

**Comment by lucko** [comment]
Make sure you're using the latest version of LP from https://ci.lucko.me/job/LuckPerms/
