### ISSUE TITLE
Bungee Permissions

### ISSUE THREAD

**Issue by michaeldriskell** [lucko/LuckPerms#357]
Hello, I'm trying to add permissions for Bungee plugins such as porty and multichat but adding the permissions to groups doesn't give them permission. How do I set up permissions to work for bungee plugins?

**Comment by merjilin** [comment]
Do you have luckperms installed on bungeecord?

**Comment by michaeldriskell** [comment]
Yes I do. heres my config for the bungee version
https://pastebin.com/n8C6DNgQ

**Comment by merjilin** [comment]
If not, grab the bungee edition from here: https://ci.lucko.me/job/LuckPerms/ and install it. Now to handle it's permissions, you can treat it exactly like normal luckperms, but use /lpb in the command except /lp. You can also connect luckperms bungee to the same database the backend servers are using.

**Comment by michaeldriskell** [comment]
okay so I add bungeeperms using /lpb instead of /lp ?? I didnt see that in the wiki!

**Comment by merjilin** [comment]
It states it I the `aliases` section found here: https://github.com/lucko/LuckPerms/wiki/Command-Usage

**Comment by michaeldriskell** [comment]
Thank you so much. I read right over it.

**Comment by merjilin** [comment]
You're welcome! If this answers your ticket, please make sure you close the ticket :P

**Comment by michaeldriskell** [comment]
When I run /lpb group default permission set bungeecord.command.server
all that happens is it says [LP] running luckperms v3.2.37.

Running it in the console, I get this message. It says something about MySQL? And when I joined the server it says Permissions couldnt be loaded. Please try again later.

04.07 19:32:41 [Server] SEVERE java.util.concurrent.CompletionException: java.lang.NullPointerException
04.07 19:32:41 [Server] SEVERE at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
04.07 19:32:41 [Server] SEVERE at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
04.07 19:32:41 [Server] SEVERE at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1592)
04.07 19:32:41 [Server] SEVERE at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
04.07 19:32:41 [Server] SEVERE at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
04.07 19:32:41 [Server] SEVERE at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
04.07 19:32:41 [Server] SEVERE at java.lang.Thread.run(Thread.java:748)
04.07 19:32:41 [Server] SEVERE Caused by: java.lang.NullPointerException
04.07 19:32:41 [Server] SEVERE at me.lucko.luckperms.common.storage.backing.sqlprovider.MySQLProvider.getConnection(MySQLProvider.java:118)
04.07 19:32:41 [Server] SEVERE at me.lucko.luckperms.common.storage.backing.SQLBacking.loadGroup(SQLBacking.java:577)
04.07 19:32:41 [Server] SEVERE at me.lucko.luckperms.common.storage.AbstractStorage.lambda$loadGroup$6(AbstractStorage.java:151)
04.07 19:32:41 [Server] SEVERE at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
04.07 19:32:41 [Server] SEVERE ... 4 more

**Comment by michaeldriskell** [comment]
Nvm Im sorry I didnt have my mysql information entered correctly...
