### ISSUE TITLE
Luckperms don't reconnect mysql database

### ISSUE THREAD

**Issue by tuanjr** [lucko/LuckPerms#360]
I run minecraft server in Server A,  mysql database on Server B, when server B down (offline, broken internet) for 3, 4 minutes and after that get online back. But luckperms don't reconnect database, so players can't join. Other plugins using mysql still reconnect successfull.
Sorry my english bad.

**Comment by lucko** [comment]
If Server B goes down and then up whilst Server A is online, then it will reconnect when Server B comes back up. 

However, if Server B is offline while Server A starts up for the first time, it will not reconnect. This is the intended behaviour.

**Comment by tuanjr** [comment]
No, in my case: Server A and B both online -> B down, A still online -> B comeback, Lucperms on A don't connect B.

**Comment by lucko** [comment]
LuckPerms uses HikariCP to handle connection pooling.
https://github.com/brettwooldridge/HikariCP

It's unlikely that there's an issue there. More likely that your database isn't accepting new connections, or the old ones aren't being completely dropped.

Either way, it's definitely not an LP issue.
