### ISSUE TITLE
Forge fake player permissions

### ISSUE THREAD

**Issue by kaal-1** [lucko/LuckPerms#362]
I used to allow forge fake players with the vanilla OP system. Since LP disables it, is there a way to give all permission to fake players?

**Comment by kaal-1** [comment]
Sorry, yes, sponge forge.

**Comment by lucko** [comment]
This should all be handled by Sponge. LuckPerms shouldn't need to do anything for it.

It's my understanding that Sponge doesn't use fake players, and instead has it's own tracking system. I'm not 100% sure on that, might be worth asking the Sponge guys. :)

**Comment by merjilin** [comment]
Through my experience with sponge, fake players are tracked back to the user that placed them. So they should share permissions. As an example, with grief prevention a fake player cannot access a claim if the user isn't trusted on that claim.
