### ISSUE TITLE
[Question] Cannot change storage method to mysql

### ISSUE THREAD

**Issue by 5igm** [lucko/LuckPerms#364]
I have changed storage method to Mysql according to the wiki in Github. And I am sure that I have typed the accurate username and password. But I cannot find anything in Mysql database. Could you give me a little help?
![1](https://user-images.githubusercontent.com/11610914/27996477-e4af8d80-64e2-11e7-8330-ec81103a5808.jpg)

**Comment by EmanYm** [comment]
You have split storage on, saving everything to H2

**Comment by lucko** [comment]
Set `enabled` under split storage to false.

**Comment by 5igm** [comment]
Thank you very much!

**Comment by EmanYm** [comment]
You're most welcome.
