### ISSUE TITLE
player#hasPermission() causing error with LuckPerms

### ISSUE THREAD

**Issue by Personinblack** [lucko/LuckPerms#365]
[This](https://hastebin.com/qeracadazi.vbs) is the error I get when I try to check player's permission. And [this](https://hastebin.com/oxugayudow.cpp) is the method I'm using.

There is only one player at the server and that player is op. (via LuckPerms' auto op option)

Forgot to mention, I'm using latest development build version. (v3.2.42)

**Comment by lucko** [comment]
`permission` is null.

**Comment by Personinblack** [comment]
Ahh silly me... Thanks for pointing out the obvious.
