### ISSUE TITLE
[Question] Still cannot store in Mysql...

### ISSUE THREAD

**Issue by 5igm** [lucko/LuckPerms#366]
I am sure I have given the correct IP, port, username, password, and I have followed the suggestion from 
https://github.com/lucko/LuckPerms/issues/365 to disable the option,  split storage.

But now, the plugin still cannot connect to Mysql correctly and has given back a feedback.
Could you help to see what is wrong? Thank you very much.

https://pastebin.com/b67na0sn

**Comment by EmanYm** [comment]
check over all of your settings and login credentials, and make sure the database is online.
There was also a new commit [on the Jenkins](https://ci.lucko.me/job/LuckPerms/253/) that changed something with SQL.

**Comment by lucko** [comment]
Can you try updating to the latest version. I believe this is fixed there.

https://ci.lucko.me/job/LuckPerms/

**Comment by 5igm** [comment]
The new version works. Thank you very much!
