### ISSUE TITLE
Change printout of '/lp listgroups'.

### ISSUE THREAD

**Issue by Camm175** [lucko/LuckPerms#368]
Moving from PEX to this plugin, everything in LuckPerms is far more in-depth and superior...until I used **/lp listgroups**.
Sure it's printout in-game does what it is intended to do (list the groups), but could defiantly have room for improvement. PEX has a printout that save's a lot of time when trouble shooting, or to quickly check a parent, group weight, ladder etc. I believe this would really benefit LuckPerms.
This would also be handy/apply to **/lp listtracks**.

See: http://i.imgur.com/qqbZbhE.png
Cheers for reading, and hopefully considering this change.

**Comment by lucko** [comment]
So, what information should it show?

`Group name - Weight - ????`

**Comment by Camm175** [comment]
Cheers for the quick reply :)

In order of the lowest group (default) to the highest:
Group Name **-** Group Weight **-** Track Order/Name **-** Parent

**Example:**
Default **-** #10 **-** 1 | Ranks **-** []
Guest **-** #20 **-** 2 | Ranks **-** [Default]
Member **-** #30 **-** 3 | Ranks **-** [Guest]
Pro **-** #40 **-** 4 | Ranks **-** [Member]
Staff **-** #50 **-** 1 | Staff **-** [Pro]

I know it can look messy in text, but once you have it applied to an actual permissions system - it looks a lot cleaner and a great tool for a quick go-to to get basic information on your servers groups.
