### ISSUE TITLE
Permission System!?

### ISSUE THREAD

**Issue by ZnapGaming** [lucko/LuckPerms#37]
Hi there! ;)
So, maybe im just to dumb for this Permission System :D but i dont get, why my Permission dont work...
What i did.. 
1. Set up the MySqL Database-storage (workes fine) then i...
1.1 /luckperms creategroup admin
2. /luckperms creategroup supp
3. /luckperms group admin parent add supp
4. /luckperms group admin meta addprefix 100 "&cAdmin "
5. /luckperms group supp meta addprefix 90 "&a Supp"
6. /luckperms group supp set chatex.allowchat true lobby1
7.  /luckperms group supp set chatex.allowchat true
**(Edit: 7.1 I surely did /luckperm user ZnapGaming setprimarygroup admin / supp)**
8. But i still cant chat with the group "supp" (Im using ChatEX+Vault+Apis)
What am i doing wrong? The perm. even shows up in the DataBase: http://prntscr.com/cye1ik

Btw: maybe i will translate the lang.yml soon :) (to german)

**Comment by lucko** [comment]
Could you please send the output of "/luckperms user <your name> meta info" :)

**Comment by ZnapGaming** [comment]
Sure, http://prntscr.com/cyf196 there you go. Extra Footage:http://prntscr.com/cyf11e  |  http://prntscr.com/cyf1n0

**Comment by lucko** [comment]
Are you sure it's not an issue with ChatEx?

**Comment by ZnapGaming** [comment]
Do you know any other Chat Plugin that is supportet? I dont wanna use essentialsX on the lobby :D

**Comment by ZnapGaming** [comment]
Btw: Is this a Problem? http://prntscr.com/cyfz4b

**Comment by lucko** [comment]
No, all looks fine.

I'll do some testing with ChatEx.

**Comment by ZnapGaming** [comment]
Thanks a lot dude!

**Comment by lucko** [comment]
Seems to be working ok for me? 

![](http://i.imgur.com/Zl3vuF7.png)

**Comment by ZnapGaming** [comment]
ye, but this is just for the person (you). Not for a group?

**Comment by ZnapGaming** [comment]
And is it normal, that when i had the "setprimarygroup to admin" and i set my primary group to "supp", that i still have the admin Prefix? :O Or did i have to clear my rank (group) first?

**Comment by lucko** [comment]
Sorry, my bad. I re-read your post and understand now.

So, primary group has impact on any of the internal operations in LuckPerms, including prefix priority.

The only thing it considers is the priority of the prefix. Obviously, you're getting the admin one, because it is set at a higher priority.

If you want to force yourself to use the "supp" one, run:
`/luckperms user ZnapGaming set "prefix.90.&a Supp" false`

**Comment by lucko** [comment]
And yes, using "setprimarygroup" will not "unset" any of your previous groups. It just overrides them.

You need to use the "parent remove" command to remove other groups.

Unless you need it for Vault, setting the primary group isn't important.

**Comment by ZnapGaming** [comment]
No, im soory for my "bad" english :P 
So just Imagine: A friend of mine (that i trust) become admin and now he is griefing. So i want to revoke his admin permissions. What do i do? /perm user <name> clear or so?

**Comment by ZnapGaming** [comment]
Ohh :) But, what shall i do to become admin (or imagine my friend donor)?

**Comment by lucko** [comment]
Your English is great; I just misread. Totally my fault.

Ok so:
`/luckperms user Notch clear` will reset the user to default. As if they'd never logged into the server before.

`/luckperms user Notch parent remove admin` will remove the user from admin. If their "primary group" is also set to admin, you might need to change that too. In which case, you'd do:

```
/luckperms user Notch parent add default
/luckperms user Notch setprimarygroup default
/luckperms user Notch removegroup admin
```

**Comment by ZnapGaming** [comment]
Why are English (UK) guys alyways be sooo friendly and kind? I Love it ;D

So did i get it right?
pex inheritance isnt = parent?

**Comment by lucko** [comment]
Not sure what you mean by pex inheritance?

A parent group is just a group that a user/group inherits permissions from.

**Comment by ZnapGaming** [comment]
So if the group "Member" has the permission to "e.g. chatex.allowchat" and is the "kind" of Admin, admin will get the chatex.allowchat permission also? :) I Think, im on the right way ;D

**Comment by lucko** [comment]
Yes, to clarify:

```
/luckperms creategroup member
/luckperms creategroup admin
/luckperms group admin parent add member
/luckperms group member permission set chatex.allowchat true
/luckperms group admin permission set some.admin.permission true
```

Member gets: chatex.allowchat
Admin gets: chatex.allowchat and some.admin.permission

**Comment by ZnapGaming** [comment]
I´m slowly getting use to your super awsome Permission Plugin! Thanks a lot dude! I appreciate!

**Comment by ZnapGaming** [comment]
If I have more problems (or im just to dumb ^^) i will get in touch with you, love ya <3

**Comment by lucko** [comment]
Glad it's sorted. :)
