### ISSUE TITLE
Prefix doesn't show

### ISSUE THREAD

**Issue by InfinCZ** [lucko/LuckPerms#371]
I use command " /lp user InfinCZ addprefix 10 "&c[testing]" ".
And in chat doesn't show prefix [testing].
When I try this command again show message " infincz already has that prefix set. ".

And I use command " /lp user InfinCZ info " and show Current Prefix: "[testing] " .
Thanks,

Infin

**Comment by EmanYm** [comment]
What chat plugin are you using?
Sponge or Spigot

**Comment by InfinCZ** [comment]
Spigot, but all is ok.
I download plugin Ultra chat ---> https://www.spigotmc.org/resources/ultra-chat.13776/ .
And all is work.

Thanks,

Infin

**Comment by InfinCZ** [comment]
But how I replace current prefix ?

**Comment by EmanYm** [comment]
`/lp user/group <name> meta addprefix <weight> "<prefix>"`
@lucko might be able to answer this better than I can, though.

**Comment by InfinCZ** [comment]
Ok and how i change priority?

**Comment by EmanYm** [comment]
Weight is priority.
>Weight - this is just a number which determines the priority of the prefix/suffix. A higher number = a higher weight and a higher priority.
