### ISSUE TITLE
Plugin error when server loads

### ISSUE THREAD

**Issue by Pyra1** [lucko/LuckPerms#373]
While LuckPerms loads on my server, i get this message:

12.07 19:02:52 [Server] INFO ... 12 more
12.07 19:02:52 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_131]
12.07 19:02:52 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_131]
12.07 19:02:52 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[custom.jar:git-Spigot-c3c767f-33d5de3]
12.07 19:02:52 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[custom.jar:git-Spigot-c3c767f-33d5de3]
12.07 19:02:52 [Server] INFO at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_131]
12.07 19:02:52 [Server] INFO Caused by: java.lang.ClassNotFoundException: com.google.gson.JsonElement
12.07 19:02:52 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
12.07 19:02:52 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:505) [custom.jar:git-Spigot-c3c767f-33d5de3]
12.07 19:02:52 [Server] INFO at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:153) [custom.jar:git-Spigot-c3c767f-33d5de3]
12.07 19:02:52 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:316) [custom.jar:git-Spigot-c3c767f-33d5de3]
12.07 19:02:52 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:356) [custom.jar:git-Spigot-c3c767f-33d5de3]
12.07 19:02:52 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [custom.jar:git-Spigot-c3c767f-33d5de3]
12.07 19:02:52 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [custom.jar:git-Spigot-c3c767f-33d5de3]
12.07 19:02:52 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[custom.jar:git-Spigot-c3c767f-33d5de3]
12.07 19:02:52 [Server] INFO at me.lucko.luckperms.bukkit.LPBukkitPlugin.onEnable(LPBukkitPlugin.java:152) ~[?:?]
12.07 19:02:52 [Server] INFO at me.lucko.luckperms.bukkit.LPBukkitPlugin.enable(LPBukkitPlugin.java:169) ~[?:?]
12.07 19:02:52 [Server] INFO at me.lucko.luckperms.bukkit.BukkitConfig.<init>(BukkitConfig.java:43) ~[?:?]
12.07 19:02:52 [Server] INFO at me.lucko.luckperms.common.config.AbstractConfiguration.<init>(AbstractConfiguration.java:47) ~[?:?]
12.07 19:02:52 [Server] INFO java.lang.NoClassDefFoundError: com/google/gson/JsonElement
12.07 19:02:52 [Server] ERROR Error occurred while enabling LuckPerms v3.2.20 (Is it up to date?)

**Comment by merjilin** [comment]
Can you tell us what version of spigot you're using?

You're also out of date, please download the latest from here: https://ci.lucko.me/job/LuckPerms/

**Comment by Pyra1** [comment]
12.07 19:02:50 [Server] INFO This server is running CraftBukkit version git-Spigot-c3c767f-33d5de3 (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)

**Comment by merjilin** [comment]
You need to be using spigot 1.8.8 for the bukkit luckperms to load. For anything below that, try using the bukkit legacy version from here: https://ci.lucko.me/job/LuckPerms/lastSuccessfulBuild/artifact/bukkit-legacy/target/LuckPerms-Bukkit-Legacy-3.2.44.jar

**Comment by lucko** [comment]
You should be using 1.8.8. There are a number of security bugs in the previous releases.
