### ISSUE TITLE
Separate groups for each server

### ISSUE THREAD

**Issue by kamileks999** [lucko/LuckPerms#376]
Hi,
Could you add to your plugin possibility to create separate group for each server (with MySQL) and separate user ranks for each server?
Currently, in database, in table with groups there is only group's name, there isn't a column for server name.
Thanks

**Comment by voodootje0** [comment]
Only thing I could say is read the wiki, advanced setup.

**Comment by EmanYm** [comment]
Here, I'll do half the work for you.
[Advanced Setup](https://github.com/lucko/LuckPerms/wiki/Advanced-Setup)
[What is Context](https://github.com/lucko/LuckPerms/wiki/Command-Usage#what-is-context)

**Comment by lucko** [comment]
Groups themselves are not per-server, they're just assigned to players on specific servers, or given permissions on specific servers.

**Comment by EmanYm** [comment]
In a bungeecord network, you could have a permission that applies on both a server AND a world using context.
