### ISSUE TITLE
[Suggestion] making /lp group listmembers first show existing users instead of uuids.

### ISSUE THREAD

**Issue by voodootje0** [lucko/LuckPerms#377]
Could you make /lp group listmembers first show existing users instead of uuids.
It's showing uuids because I migrated from another plugin.

**Comment by lucko** [comment]
It will show usernames when the players have connected. 

UUIDs are only shown if a username is not available.

**Comment by voodootje0** [comment]
Yes, I know that, but I was using another group manager plugin for over 2 years. Some players will never join the server anymore. So can I never get a clear list of current members of a group. That's the reason why I'm asking to first display usernames and than UUIDs. :)

**Comment by lucko** [comment]
> UUIDs are only shown if a username is not available.

If a username is not available, what else do you want me to display?

**Comment by voodootje0** [comment]
You got me wrong ;)
I'm talking about the priority of the display. That it shows UUIDs when a username isn't available is perfect. 

Currently it shows UUIDs and usernames without a logic. Just combined and not a clear view.
![image](https://user-images.githubusercontent.com/6852308/28247207-1987b142-6a2c-11e7-886b-b55ba5b948fb.png)

What I mean is when you type /lp group listmembers it will first show all existing usernames and then when usernames are not found the UUIDs. 

As example that itzdino and raider_ are showed as first in the list instead of just random somewhere in the list.

**Comment by lucko** [comment]
This will throw off the pagination of the list, as each page is requested separately. 

I'd only be able to sort the entries per-page.

**Comment by voodootje0** [comment]
Could you change then the system behind pagination?

**Comment by lucko** [comment]
No, because the pages are formed before the conversion from uuid --> username.

**Comment by PizzaMC** [comment]
Having the usernames being displayed first before the UUIDs would of been a great change.
