### ISSUE TITLE
Split Datastore issue

### ISSUE THREAD

**Issue by Eufranio** [lucko/LuckPerms#38]
I've recently wiped my database. Now, every time i try to add a command for me, or use something, I'm receiving a error of No Permissions. I was wondering why, then I decided to add a permission for me, and seems that LuckPerms didn't re-registered me to the database. Look: http://prntscr.com/d05su5

In my database, the `user` and `uuid` tables are empty.
Running:
SpongeForge 1.10.2-6.0.0-BETA-1851
LuckPerms build 45 from Jenkins
LuckPerms in database (MySQL) mode

**Comment by lucko** [comment]
Did you wipe the database whilst the user was online?

**Comment by Eufranio** [comment]
No, I wiped with the server offline. I've tried reconnect/restart, but no effect too.

**Comment by lucko** [comment]
Is the uuid table still empty?

**Comment by Eufranio** [comment]
Yes

**Comment by lucko** [comment]
Then that's your problem.

It's working fine for me. I dropped all of my tables before testing.

![](http://i.imgur.com/ygT7mnb.png)

**Comment by Eufranio** [comment]
I'm running a modpack, I didn't erased the playerdata or something like it... Can you explain what exactly is wrong? I'm blind 😥

**Comment by lucko** [comment]
Player data shouldn't effect it. LuckPerms relies on the uuid table only for it's lookups. 

Any exceptions in console? My guess is that the server can't write to MySQL.

**Comment by Eufranio** [comment]
Hmmm, true, i've recently restarted my MySQL server, let me try restart again the server.

**Comment by Eufranio** [comment]
Nope. Didn't work. Looking in the logs, everything seems to work fine, no errors/stacktraces, and LuckPerms can connect to the database...

**Comment by lucko** [comment]
Can you try testing with H2 instead? The core behaviour is exactly the same. It will just narrow down whether it's an issue with your MySQL server or LuckPerms.

**Comment by Eufranio** [comment]
Okay, brb

**Comment by Eufranio** [comment]
```
[LP] User could not be found.
```
Using H2...

**Comment by lucko** [comment]
Can you pastebin your startup log please?

**Comment by Eufranio** [comment]
Here: http://frani.magitechserver.cf/fml-server-latest.log

**Comment by lucko** [comment]
Strange. 

Can you try on a clean Sponge installation? I cannot reproduce at all. I've tried on both SpongeForge and SpongeVanilla, using clean H2 setups.

**Comment by Eufranio** [comment]
Tried a clean Sponge installation, worked... I'm wondering why it's bugging only with my server :/

**Comment by lucko** [comment]
I guess just try out different things.

Take a copy of your old server and try removing bits.

Remove some mods, remove other plugins, reset the world, etc etc. I have no clue why you're having issues. 😢

**Comment by monotonehell** [comment]
I also hit this problem. I have managed to reproduce it once.

From a fresh install, change all the storage methods to yaml and split storage all at the same time. Luckperms will not recognise a player exists with /perms user <name> info.
```
storage-method="yaml"
split-storage {
  enabled=true
  methods {
    user="yaml"
    group="yaml"
    track="yaml"
    uuid="yaml"
    log="yaml"
  }
}
```
However when I changed from H2 to yaml storage method, then restarted, and then to split storage, it worked okay.

So perhaps it's something to do with changing storage methods and splitting all at once?

**Comment by lucko** [comment]
Shouldn't be. Is it specifically an issue with split storage? @Eufranio were you using split storage, or one option?

**Comment by Eufranio** [comment]
Yes, I was. I thought change the split was neccessary to change the database type...

**Comment by lucko** [comment]
Alright, perfect. 

I'll look into that. :)

p.s. No it's not necessary.

**Comment by Eufranio** [comment]
You could add a comment in this section, like
**DON'T MODIFY IF YOU DON'T KNOW WHAT YOU ARE DOING**

**Comment by lucko** [comment]
It did previously have that message, funnily enough. I removed it because I considered it stable enough to use. 😉 

https://github.com/lucko/LuckPerms/commit/3fd62a80e27c3aa240f65723d714c6b32be6a3ba

**Comment by Eufranio** [comment]
Thanks, i'll test it right now!

**Comment by Eufranio** [comment]
FIXED!

**Comment by lucko** [comment]
I haven't fixed the split storage issue yet. :)

**Comment by Eufranio** [comment]
Ahhh, okay, it's fixed here because i disabled split storage. Nice work
