### ISSUE TITLE
Placeholders not retrieving group aliases

### ISSUE THREAD

**Issue by Feeriix** [lucko/LuckPerms#380]
Group name rewrites don't get retrieved by the placeholders, instead the normal group name is shown.

Tried using these placeholders on DeluxeChat with PlaceholderAPI.
%luckperms_last_group_on_tracks_<tracks>% 
%luckperms_group_name%

Vault placeholders seems to be working as expected. (%vault_rank%)
Using PaperSpigot 1.12 and LuckPerms 3.2.37

**Comment by lucko** [comment]
I've moved this issue to the placeholder repo.

I'll look into fixing it when I get a chance. For now, use `%vault_rank%` if you can.
