### ISSUE TITLE
[improvment] time activator permisssions

### ISSUE THREAD

**Issue by mat41997** [lucko/LuckPerms#381]
e.g
Permissions activates every 3 seconds for 3 seconds, thus achieving an animated color of nick or rank

command
```
/lp user <user> meta addtempprefix <priority> <prefix> <duration_to_end_permission> <duration_to_refresh_permission> <duration_to_start_permission> [context...]
```

**Comment by lucko** [comment]
This should be done using an extra plugin, it is waaay out of scope for a permissions plugin
