### ISSUE TITLE
Option to disable the startup banner and console colors?

### ISSUE THREAD

**Issue by kmecpp** [lucko/LuckPerms#382]
It would be nice if there was an option to disable the startup banner. I like to keep the console as clean as possible when the server is starting, and a giant colorful picture of the words "LuckPerms" is not really all that helpful, especially considering the information in the banner is redundant because it appears earlier in the log.

![image](https://user-images.githubusercontent.com/6520738/28328246-ee8b2940-6bb3-11e7-8666-e7310303d84d.png)

Along with that, I think there should also be a way to disable the colors in the console. It is very distracting when searching for important information related to my server's custom plugin which colors messages specifically to distinguish from all the other plugin.

**Comment by lucko** [comment]
> Along with that, I think there should also be a way to disable the colors in the console. It is very distracting when searching for important information related to my server's custom plugin which colors messages specifically to distinguish from all the other plugin.

Really don't see how that's a valid argument, considering the server (at least in the newer versions) colors all warning messages yellow, and error messages red.

For example:
![](http://i.imgur.com/X6sxOPH.png)

> especially considering the information in the banner is redundant because it appears earlier in the log.

LuckPerms runs on lots of different platforms: Bukkit/Spigot/Paper, Cauldron (and the likes), Sponge, BungeeCord, and any other respective forks. 

Each of these platforms place information in different places, and in the case of some, don't show it at all. For my own sanity when providing support for people using the plugin, having the information I need in one place is a huge time saver.

Anyway, I've added an option to disable colored logging anyways. (outside of what you said, there are some other valid reasons to have it.) You can set:

```yaml
colored-logger: false
```

in the LuckPerms config file, and all LP log messages will have their color stripped.

**Comment by kmecpp** [comment]
@lucko if it's just a matter of ensuring that you have the plugin and platform information, why not have a `disable-banner` config that just shrinks the output to the two relevant lines:

![image](https://user-images.githubusercontent.com/6520738/28333681-aabb10a0-6bc6-11e7-8e6d-7dba6f1baea0.png)
