### ISSUE TITLE
An error while getting group meta

### ISSUE THREAD

**Issue by EmanYm** [lucko/LuckPerms#385]
[This](https://hastebin.com/velaqixawu.md) occures for any time I type `/lp group <group> meta info`

**Comment by pocakking** [comment]
What version of Spigot do you use?

**Comment by pocakking** [comment]
Oh, you use Sponge.

**Comment by EmanYm** [comment]
I keep forgetting that LuckPerms is cross-platform.  It slips my mind that I need to specify the API I am using.

**Comment by lucko** [comment]
Thanks for reporting, sorry it took a while to push a fix.
