### ISSUE TITLE
Group Name Capitalization

### ISSUE THREAD

**Issue by Sade66** [lucko/LuckPerms#386]
Hello, I was wondering if there is any way to make the first letter of a group capital? If not, could this be considered as an option in a future update? I use a plugin that forwards Minecraft chat to Discord and the plugin grabs the group name from LuckPerms. Because all the group names are lowercase, this is how the appear on Discord.

Thanks! :)

![image](https://user-images.githubusercontent.com/19366945/28447423-a3fb3f72-6d9e-11e7-9f15-6147b2859c54.png)

**Comment by fcpwiz** [comment]
+1

I use an auto rankup plugin and it would look much better if my group names would start with a capital letter instead of being all lowercase.

**Comment by lucko** [comment]
You can use the group-name-rewrite option.

https://github.com/lucko/LuckPerms/wiki/Configuration#group-name-rewrite

**Comment by Sade66** [comment]
@lucko I tried that and it didn't do anything.
