### ISSUE TITLE
/lp networksync throws large netty error

### ISSUE THREAD

**Issue by MstrTaffy** [lucko/LuckPerms#389]
Sponge Ver: spongevanilla-1.12-7.0.0-BETA-300
Bungee Ver: HexaCord version BungeeCord-Bootstrap:1.12-SNAPSHOT:8d152de:158
Protocol support for 1.7.x

Error: https://pastebin.com/V7PhBsJB
Log: https://pastebin.com/uWmJWBmf
Server config : https://pastebin.com/9Sppenhk
Bungee Config : https://pastebin.com/v8XVKUHi

using /lp networksync throws the above error on any of the servers (6 in total)

Network is as follows:

                                               - Vanilla Sponge
                                                - Vanilla Sponge
Domain Name - bungeecord  - Vanilla Sponge
                                                - Forge Sponge
                                                - Vanilla Sponge

MySQL DB(5.6.35) is on the same physical machine.

**Comment by lucko** [comment]
Update to the latest Sponge version. It's not a LP bug.
