### ISSUE TITLE
Command Block Permission node

### ISSUE THREAD

**Issue by Coolfeather2** [lucko/LuckPerms#391]
Need to allow admin users to place and modify command blocks without having 'OP' as it is disabled.

**Comment by EmanYm** [comment]
If you're using Sponge, you get access to two [permission nodes](https://docs.spongepowered.org/stable/en/server/spongineer/commands.html#vanilla)
>Allow editing an ordinary commandblock of the given name: minecraft.commandblock.edit.block.<name>
Allow editing a minecart commandblock of the given name: minecraft.commandblock.edit.minecart.<name>
As well as a spawn protection bypass.

**Comment by Coolfeather2** [comment]
using spigot

**Comment by lucko** [comment]
Spigot doesn't have a permission for it.

**Comment by EmanYm** [comment]
Switching server APIs is ultimatly up to you.
Most Spigot plugins and mods won't work on Sponge, but in many cases there is already a Sponge or Forge replacement.
There is a slight learning curve when switching, but I personally think it's worth it.

**Comment by Coolfeather2** [comment]
Installed a bukkit plugin that provided the permission nodes https://dev.bukkit.org/projects/commandblockperms
