### ISSUE TITLE
Unable to grant permission to promote in a single track

### ISSUE THREAD

**Issue by DrRek** [lucko/LuckPerms#3929]
### Description

Hello, I've granted a user the permission `luckperms.user.promote.classic` as in picture below.
![image](https://github.com/LuckPerms/LuckPerms/assets/12783153/4603c03a-13dd-4a52-a014-ab6a77042d0f)

But when they try to add someone to the track they are blocked, as in picture below.
![image](https://github.com/LuckPerms/LuckPerms/assets/12783153/76fc3cf9-7a50-45c5-87b1-a83b655db0c7)

### Reproduction Steps

- Create track "classic" with two groups
- Add one user permission to promote into this track with `luckperms.user.promote.classic`
- Attempt to promote a user with`/lp user PlayerName promote classic`
- Observe the user is not being promoted.

### Expected Behaviour

The "PlayerName" player is promoted to the next classic track group.

### Server Details

1.20.4

### LuckPerms Version

v5.4.121

**Comment by BNTFryingPan** [comment]
[this page](https://luckperms.net/wiki/Argument-based-command-permissions) on the wiki covers how to setup argument based permissions
