### ISSUE TITLE
Permissions data could not be loaded. Please try again later.

### ISSUE THREAD

**Issue by dex73r** [lucko/LuckPerms#393]
Happens on craftbukkit 1.12 every player login(even after deleting the plugin's folder to make sure)

**Comment by lucko** [comment]
Pastebin your log file please.

**Comment by dex73r** [comment]
Here, https://pastebin.com/K20rmDA7 I see not much wrong in the log though

**Comment by lucko** [comment]
I can't see anything in your log because of a CraftBukkit bug. :/

I've reported it, but in the meantime, you could try using Spigot instead of CraftBukkit.
https://hub.spigotmc.org/jira/browse/SPIGOT-3461

**Comment by lucko** [comment]
Ok, please update to the latest CraftBukkit and LuckPerms builds.

https://ci.lucko.me/job/LuckPerms/

**Comment by lucko** [comment]
Assuming this was resolved by updating.

Please re-open if you're still having issues. 🙂
