### ISSUE TITLE
PlotSquared ''basicpermpack'' permission not working

### ISSUE THREAD

**Issue by misterjacket** [lucko/LuckPerms#394]
I have added the basic permissions to the Default group, these ones:

`

Permission | Description
-- | --
plots.use | Allows user to use commands
plots.plot.4 | Limit to 4 claimed plots
plots.permpack.basic | Access to basic plot commands
plots.permpack.basicinbox | Access to basic commenting and inbox commands
plots.permpack.basicflags | Access to the basic flags

`

inside the permpack should be the following perms:

```
`Basic permissions

plots.use plots.info plots.claim plots.auto plots.home plots.clear plots.delete plots.list plots.list.mine plots.list.shared plots.list.world plots.list.all plots.list.forsale plots.list.unowned plots.list.unknown plots.set plots.visit plots.visit.owned plots.visit.shared plots.set.flag plots.flag.add plots.flag.remove plots.flag.list plots.flag.info plots.flag plots.buy plots...... ETC..` 
```

as described on their wiki https://github.com/IntellectualSites/PlotSquared/wiki/Commands-and-Permissions

But when the player who is in the default group uses a commando like /plot claim, the player lacks the permission and should have plots.claim (but this permission should be inside the basicpack).

It works perfectly fine with PermissionsEx when giving the basicperms to the default group.

I did the verbose thing, https://gist.github.com/anonymous/86e95bfd60b4c0ba029b87774c3148d8

I have essentials and vault installed. Tried running the server on 1.10 and 1.11
installed the latest LuckPerms version and tried various versions of plotsquared.

Can't figure this one out....

**Comment by lucko** [comment]
Can you pastebin your LP config file please.

**Comment by misterjacket** [comment]
https://pastebin.com/S7QNugW5

**Comment by lucko** [comment]
It's not gonna work if this is false. 😄 
```yml
# If the plugin should apply Bukkit child permissions.
# Plugin authors can define custom permissions structures for their plugin, which will be resolved
# and used by LuckPerms if this setting is enabled.
apply-bukkit-child-permissions: false
```

**Comment by Jecvay** [comment]
PlotSquared for Sponge have this problem, too.
Is lp for sponge didn't support the 'perm pack' feature?
