### ISSUE TITLE
plugin ignore the essentials antibuild

### ISSUE THREAD

**Issue by DanielMarkink** [lucko/LuckPerms#395]
i have essentals antibuild but i still can brake blocks (and jes i have essentials.build.* false)
and OP is set to false in the plugin config and i have deleted the ops.json and restarted the server.

But i can still break blocks.

Can enybody help me?

**Comment by DanielMarkink** [comment]
and here is my config for if you need it.
https://pastebin.com/AAnfyytU

Please note that is is the config for 1 server and not for all servers. But the data is the same only the server name is different

**Comment by lucko** [comment]
Use /lp verbose to check which permissions are being queried.

It's very unlikely to be an LP bug.

https://github.com/lucko/LuckPerms/wiki/Verbose
