### ISSUE TITLE
Prefix dont want to work

### ISSUE THREAD

**Issue by HerbertBobo** [lucko/LuckPerms#4]
Luckperms gives sending no Prefix to Vault.
It gives no Prefix in the Chat with a Chat Plugin.
I have used EssentialsChat and alot more Chat Plugins that use Vault.
My Vault is running on the latest Version.
I think its a Problem from LuckPerms.
The Prefix works with another Plugin. (BungeePerms)
I hope you can help me.

Greetings from Marcel - (GERMANY)

**Comment by lucko** [comment]
Thanks for letting me know. I'll look into it. Another user has also reported the same issue.

**Comment by HerbertBobo** [comment]
Okay thank you man :+1:  :)
I hope when you found this "bug" today. That you maybe update the Plugin today.

Sorry for my English it's not the best ^^

**Comment by lucko** [comment]
I've released 1.6.

Please download a build from https://ci.lucko.me/job/LuckPerms/. Let me know if it works. 
I have personally tested the latest version with EssentialsXChat, and it works as intended.
