### ISSUE TITLE
Make Web Editor Setting to disable it

### ISSUE THREAD

**Issue by Nightloewe** [lucko/LuckPerms#400]
Can you make an option to disable the web editor?

**Comment by lucko** [comment]
Can you explain how it is a security problem.

**Comment by EmanYm** [comment]
They might think just anyone can use the editor.  As far as I know, only people with the permission can use the editor
Don't forget to [read the wiki](https://github.com/lucko/LuckPerms/wiki/Command-Usage#lp-user-user-editor), @Nightloewe

**Comment by Nightloewe** [comment]
Okay, I read your code. I thought it would connect to a server or so.
