### ISSUE TITLE
How can I grant a group or a user all of permissions?

### ISSUE THREAD

**Issue by 5igm** [lucko/LuckPerms#401]
I have tried to grant a group the permission, *.*, but it doesn't work. Do I have to grant all of the permissions one by one? It is a huge work.

**Comment by EmanYm** [comment]
I think you might be thinking of the Astrix `*` wildcard
It's not recommended to use wildcards for any mod.

**Comment by 5igm** [comment]
Thank you. If I want to grant a group all of the permissions for a plugin such as Nations, can I just grant the group Nations.*?

**Comment by EmanYm** [comment]
That's hwo that would work.  yes.

**Comment by 5igm** [comment]
Thank you very much! 👍
