### ISSUE TITLE
Issue with ColoredTags and Luckperms

### ISSUE THREAD

**Issue by MinecraftTim123** [lucko/LuckPerms#402]
Hey there, I need help.

If I add sb in a group (with /lp user xy parent add (works fine!)), ColoredTags only shows up the primarygroup. That's not good for me, because if I want to give sb a temp. permission, the colour of the Name is different to the rank! (Like: temporary moderator (and the primary group is member) it will show the color for the member...)

Can somebody help me or is it possible to fix?

Note: For temporary rangs, I don't want to switch the primarygroup...
Note2: I synced the servers and the user left/joined the server and the colour of the name was identic, but when I change the primarygroup, the colour will change)!

Greetings
Minecraft_Tim

**Comment by mikroskeem** [comment]
Sorry for advertizing, but this might help you: https://github.com/StoneMain/Shortranks

**Comment by MinecraftTim123** [comment]
Okay, thanks, but I have a question. How can I enable/install that plugin and on which server do I have to install it (Bungee/Spigot/both)?

'Cause when I download it from github, I didn't found a Shortranks.jar-file and if I rename the .zip-file to a .jar-file it will error while starting.

Note: If I only write the command into the chat, LuckPerms "register" that command and run the command, but I don't see any Tags in the name, it is only white (ColoredTags ist removed!)

**Comment by mikroskeem** [comment]
You need to compile the plugin. ;-)

**Comment by MinecraftTim123** [comment]
And how to? (Sorry :3)

**Comment by mikroskeem** [comment]
Ugh... `./gradlew build`, but [https://0x0.st/kbY.jar](here your are).

**Comment by MinecraftTim123** [comment]
Into the ubuntu-console? (Sorry, I don't have a plan what I have to do :C )
