### ISSUE TITLE
settemp error

### ISSUE THREAD

**Issue by afroman84** [lucko/LuckPerms#403]
https://hastebin.com/vejapozofe.md
thank you for support =)

**Comment by BrainStone** [comment]
@adroman84 you missed the time amount. But regardless that seems like a bug.

**Comment by afroman84** [comment]
Thank you , In fact with the time amount it works. It would be better that
if you forget it, it returns an advice.

Il giorno sab 29 lug 2017 alle 23:33 Yannick Schinko <
notifications@github.com> ha scritto:

**Comment by lucko** [comment]
Thank you for reporting.
