### ISSUE TITLE
When removing rank, default isn't added directly.

### ISSUE THREAD

**Issue by voodootje0** [lucko/LuckPerms#405]
When you remove the only parent rank of someone the user will have no group at all (look the chat after I removed the rank). The default group has the permission to chat normally.
![image](https://user-images.githubusercontent.com/6852308/28756602-1c7f5afc-7572-11e7-96a1-b3f0dd626dff.png)

Could you a check to apply the default group after you removed someone's rank?
Thanks!

**Comment by i9hdkill** [comment]
This isn't fixed completely:
http://prntscr.com/gbtsr5

In this case, if you run 
`lp user Thewaytodoit parent remove trainee`
the group cannot be removed due to being the primary group.

**Comment by lucko** [comment]
I think this is probably the current intended behaviour, however, it can be changed if doing something else makes more sense.

**Comment by i9hdkill** [comment]
This is intended, but doesn't make that much sense. I mean, If I want to remove a user from a group, thats my final choice. In my opinion it's not the plugins decision to forbid that.
In my case adding the default group makes sense and if the user also has other groups, just set the highest weighted one as the new primary group. It can be discussed if the plugin should add the highest weighted one or another group as new primary group, but removing the primary group should definitely be possible with one command.

**Comment by lucko** [comment]
I've added a config option to enable your suggestion, and made the behaviour you suggested the default for all new config generations.

However, you'll need to add the new option to your config after updating.
