### ISSUE TITLE
Bungeecord - Latest builds - Permission data could not be loaded

### ISSUE THREAD

**Issue by LazosPlaying** [lucko/LuckPerms#408]
Hello, i am having issues with bungeecord edition of the plugin.

Using latest builds
bungeeCord: build #1250
LuckPerms: Build bungeecord-3.2.60

Issue:

With fresh install, plugin prints out message "permission data could not be loaded. please try later"
No changes in plugin files at all.
No errors at all.

**Comment by LazosPlaying** [comment]
Bungee log - https://gist.github.com/LazosPlaying/9dfc7d42051fb5bcf3d02c1647a892ba
Bungeecord config - https://gist.github.com/LazosPlaying/ec9e2d8d73c5434d10948cebd7e8cf8f
LuckPerms config (default) - https://gist.github.com/LazosPlaying/82d446ef2dfa5b56ae7307939e8e1b79

**Comment by lucko** [comment]
Is LuckPerms installed on your backend server as well?

**Comment by LazosPlaying** [comment]
It is. On every server.

**Comment by lucko** [comment]
Check the consoles of your backend servers.

If you're being kicked with that error, it's not BungeeCord.

**Comment by LazosPlaying** [comment]
Not being kicked.
Only getting the message in chat.

And it is confirmed it is bungee-side, because the rank that i should have there, it is not set. And my playerdata is not valid (when checking thru console)

**Comment by lucko** [comment]
Ok, can you actually post a log file where you connect? In the one you posted above, players never actually join.

**Comment by LazosPlaying** [comment]
```2017-07-31 23:31:24 | [LP] > User Info: lazosplaying                                                                        ││                             
│2017-07-31 23:31:24 | [LP] - UUID: 6d4a1e9f-d849-476e-bdaa-42ffabe17d2e                                                 
│2017-07-31 23:31:24 | [LP] - Status: Offline                                                                                ││                             
│2017-07-31 23:31:24 | [LP] - Primary Group: default                                                                         ││                             
│2017-07-31 23:31:24 | [LP] - Counts:                                                                                        ││                             
│2017-07-31 23:31:24 | [LP] -    Permissions: 2                                                                              ││                             
│2017-07-31 23:31:24 | [LP] -    Temporary Permissions: 0                                                                    ││                             
│2017-07-31 23:31:24 | [LP] -    Prefixes: 0                                                                                 ││                             
│2017-07-31 23:31:24 | [LP] -    Suffixes: 0                                                                                 ││                             
│2017-07-31 23:31:24 | [LP] -    Meta: 0                                                                                     ││                             
│2017-07-31 23:31:24 | [LP] - Parent Groups:                                                                                 ││                             
│2017-07-31 23:31:24 | [LP] -    > default                                                                                   ││                            
│2017-07-31 23:31:24 | [LP] - Cached Data:                                                                                   ││                            
│2017-07-31 23:31:24 | [LP] -    Has contextual data: false                                                                  ││                            
│2017-07-31 23:31:24 | [LP] -    Current Contexts: None                                                                      ││                            
│2017-07-31 23:31:24 | [LP] -    Current Prefix: None                                                                        ││                            
│2017-07-31 23:31:24 | [LP] -    Current Suffix: None```

Also detecting me as offline

**Comment by lucko** [comment]
> Ok, can you post a log file where you actually connect? In the one you posted above, players never actually join.

**Comment by LazosPlaying** [comment]
https://gist.github.com/LazosPlaying/7ec5837b710a4bfb10b04a197140b322

**Comment by LazosPlaying** [comment]
no errors at all, or any output that would mention issues.

**Comment by LazosPlaying** [comment]
This is totally default config, without anything modified.

**Comment by lucko** [comment]
Is your proxy running in offline mode?

The uuid shown in the command output shows a valid Mojang UUID. (`6d4a1e9f-d849-476e-bdaa-42ffabe17d2e`), which would indicate you have some plugin messing with UUIDs.

**Comment by LazosPlaying** [comment]
Yes correct it is Offline mode (as it is visible in the config file i also included)

**Comment by jahpe** [comment]
I have the same problem

**Comment by lucko** [comment]
LuckPerms loads it's data at `LOW` priority, and stores it against a players uuid.

https://github.com/lucko/LuckPerms/blob/master/bungee/src/main/java/me/lucko/luckperms/bungee/BungeeListener.java#L59

FastLogin then (sometimes) changes this UUID after LuckPerms has loaded its data.

https://github.com/games647/FastLogin/blob/master/bungee/src/main/java/com/github/games647/fastlogin/bungee/listener/PlayerConnectionListener.java#L81

FastLogin should be changing this data before events are even being called. You're going to have to expect incompatibilities when plugins forcefully change data which other plugins depend on.

This is a FastLogin issue, report it to them.

**Comment by LazosPlaying** [comment]
Aright thank you for the info :)

**Comment by LazosPlaying** [comment]
Just want to say that the issue has been fixed.
@jahpe @lucko 

https://github.com/games647/FastLogin/issues/167
