### ISSUE TITLE
WorldGuard max-region-count-per-group not working while using luckperms

### ISSUE THREAD

**Issue by Bodyash** [lucko/LuckPerms#409]
My WG config:
`    max-region-count-per-group:
        default: 8
        basic: 12
        vip: 15
        premium: 25
        sponsor: 50`
My Groups:
![default](https://user-images.githubusercontent.com/2454569/28834584-49d46e8c-76eb-11e7-9f2e-22e005a84de8.PNG)

**Comment by lucko** [comment]
Are you sure the config is in the right order?

LP supports the WG way of identifying group membership with a permission.

**Comment by lucko** [comment]
Please re-open this ticket if the issue is still unresolved.
