### ISSUE TITLE
GP option for extra claims not working

### ISSUE THREAD

**Issue by nettyneets** [lucko/LuckPerms#41]
Using "/perms user xxx meta set griefprevention.claim-limit 3" does not give the player the allowance for claims defined in the option. I have spoken with bloodshot to confirm it's working in GP, which means the option in luckperms isn't working properly. Other options that don't include the mod id are working fine however (for different plugins than GP).

**Comment by bloodmc** [comment]
@lucko I include the plugin id with my option to avoid interfering with other plugins using the same option name.

**Comment by bloodmc** [comment]
@lucko Just tested removing "griefprevention." from my options and everything worked as expected so there is definitely an issue with adding an option that contains a period.

**Comment by lucko** [comment]
Alrighty, thanks. That's definitely an LP issue.

Options are actually stored as permissions, whereby:
key=value gets translated into the permission meta.key.value

The periods should have been escaped. I'll fix that now.
