### ISSUE TITLE
Default Groups 

### ISSUE THREAD

**Issue by Saelman** [lucko/LuckPerms#411]
sooo, im trying to set the default group when people join the server to a group called "0" its called 0 cause im doing ranks 0-100 thats the name of each group, being a number {0-100} i cant seem to get it working, also. is there anyway to set everyone already on the server to default.

**Comment by merjilin** [comment]
Use `group-rewrite` in the luckperms config to 'change' the name of the default group to 0. I haven't tested it with numbers myself, however.

**Comment by lucko** [comment]
https://github.com/lucko/LuckPerms/wiki/Default-Groups
