### ISSUE TITLE
Get group display name via API

### ISSUE THREAD

**Issue by Eufranio** [lucko/LuckPerms#412]
If it's already possible please let me know. I would like to get a group display name (if set in the LP config) via the API, so I can use it on my plugin.

**Comment by lucko** [comment]
If you're using Sponge, you can use Subject#getFriendlyIdentifier.

Otherwise, you'll have to wait until I add it to the LP API. (which will be on the next API update)

**Comment by Eufranio** [comment]
Is this now available via the LP API for SpongeAPI 5/6?
