### ISSUE TITLE
[Suggestion]Could you add a feature about auto-rank?

### ISSUE THREAD

**Issue by 5igm** [lucko/LuckPerms#415]
Could you add a new feature about auto-rank? It means the plugin will parent a player to a group automatically according to some data like played time, kills number, death number, mining time, etc.

**Comment by merjilin** [comment]
This has been asked for many times, but it ultimately belongs in a separate plugin rather than in luckperms itself. You can use luckperms with existing autorank plugins, but they can be tedious to setup. You just have to make sure you only have 1 group assigned to the user at once.
