### ISSUE TITLE
Question about a wiki sentence

### ISSUE THREAD

**Issue by 5igm** [lucko/LuckPerms#416]
Could you explain more infomation about "the server value defined above under "server" is used for Vault operations."?

> use-vault-server
> 
> If the vault-server option below should be used.
> 
> When this option is set to false, the server value defined above under "server" is used for Vault operations.

**Comment by lucko** [comment]
There's an option directly below that one.

If `use-vault-server` is true, the value defined there will be used as the "server" when Vault looks up data.

If that makes no sense, just ignore the option. 😄
