### ISSUE TITLE
Feature request, temporary permissions count up

### ISSUE THREAD

**Issue by det483** [lucko/LuckPerms#420]
Hello,

Your luckyperms plugin is awesome, however I have one suggestion which would be nice to add I think.

At this moment you can set a temporary permission with:
- 'lp user <player> settemp <permission> <true/false> <time>'
However, if you want to give your player a temporary permission when they vote for example, you can let the votelistener run the following command:
- 'lp user det483 settemp essentials.fly true 15m'
The result is that the player has access to 15 minutes fly.

For example, if a player votes two times, it will get access to 15 minutes essentials.fly at the first vote, but at the second vote the plugin will give an error: '[LP] det483 already has this permission set temporarily!' and does not add the amount of time to the existing the time, it blocks the command and the plugin will count down further until the permission expires. After the expire, a player can vote again and the plugin will give you again access to essentials.fly.

Till so far the normal use of the plugin, however I think it will be great if you add an option to count up all amount of time a player got access to that permission in total. For example, if a player vote two times, first the player will get access to 15 minutes essentials.fly and if the player votes again one minute after the previous vote (so before voting you have still 14 minutes access to essentials.fly), the plugin will add up 15 minutes to the 14 minutes. So 14 minutes + 15 minutes = 29 minutes access to essentials.fly in this case. So 
it would be great if you can add an option like this, for example a command like 'lp user <player> addtemp <permission> true <time>' which will add up all amount of time.

I hope you can consider this, I think it will another awesome feature of the plugin which many people will like.

Kind regards,
det483

**Comment by lucko** [comment]
This can be adjusted with the `temporary-add-behaviour` option.

https://github.com/lucko/LuckPerms/wiki/Configuration#temporary-add-behaviour
