### ISSUE TITLE
Prefix Temp on addtemp group

### ISSUE THREAD

**Issue by MineSurvival** [lucko/LuckPerms#422]
Hi, I have problems adding a user to a group by time
example
**/Lp user name parent addtemp vip 7200s global**
The problem is that the prefix is not seen in the TAB

But if I use **/lp user name parent set vip global**
If you can see the prefix in the TAB

The problem I have is the temporary donation system
Any way to make the prefix appear?

Also try
**/Lp user name meta addtempprefix 100 & aVIP global** but still unseen.

Please look at this image:
My chat is based on permissions with DeluxeChat, I do not use any placeholder because using placeholder the prefix looks blank ... but since this is a good permissions plugin, create groups so that the chat looks cute
otherwise So I could not tell you if the same problem is in the chat
http://s2.subirimagenes.com/imagen/previo/thump_97783302017080600.png

**Comment by lucko** [comment]
Make sure you're using the same placeholder for the prefix in the tab as you do for DeluxeChat.
