### ISSUE TITLE
LuckPerms doesn't assign Users to a group?

### ISSUE THREAD

**Issue by FleecyTeddy** [lucko/LuckPerms#424]
Hey, 
I had to switch over to LuckPerms, because I need it for BungeeCord. I'm using the latest version (3.2.65) and the permissions are stored on MySQL. But I can't add myself to a freshly created group. I've created the group owner and added all permissions and a prefix. After doing /lp user FleecyTeddy parent set owner it said I would be in the group (/lp group owner listmembers also shows that I'm in the group), but I can't do anything and my prefix is still the default member prefix. Did I do something wrong or is it because the latest version is broken?

**Comment by merjilin** [comment]
Make sure ip-forwarding is set to true in the bungeecord config, as well as bungeecord set to true on your backend servers.

**Comment by FleecyTeddy** [comment]
This actually fixed it, but the prefix is still the default prefix, but that's probably Bungee Chat's fault

**Comment by BrainStone** [comment]
@FleecyTeddy if the priorities on the prefixes are set correctly and and LuckPerms on the bungee has set `include-global` to true then the prefix will be used by bungeechat
