### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by JohOply** [lucko/LuckPerms#426]
Hi guys

I am trying to install and using LuckPerms. I have some questions about the config. I read wiki but i didn't understand better (english is not my native language). Please could you help me to understand them?

> If the plugin should apply Bukkit default permissions.
> Plugin authors can define permissions which should be given to all users by default, or setup
> permissions which should/shouldn't be given to opped players.
> If this option is set to false, LuckPerms will ignore these defaults.
> apply-bukkit-default-permissions: true

In other words, this feature allow to let server's owner choose exactly each permission he wants to grant to each group?
It disable all permissions granted by default by plugins?

> If the plugin should apply attachment permissions.
> Other plugins on the server are able to add their own "permission attachments" to players. This
> allows them to grant players additional permissions which last until the end of the session, or
> until they're removed. If this option is set to false, LuckPerms will not include these attachment
> permissions when considering if a player should have access to a certain permission.
> apply-bukkit-attachment-permissions: true

I don't understand "attachment permissions", has you any example please?

> Define special group weights for this server.
> Default is just 0.
> group-weight:
> admin: 10

What is the goal of this option?

>  This option controls how frequently LuckPerms will perform a sync task.
>   A sync task will refresh all data from the storage, and ensure that the most up-to-date data is
>   being used by the plugin.
>   This is disabled by default, as most users will not need it. However, if you're using a remote
>   storage type without a messaging service setup, you may wish to set this value to something like 3.
>   Set to -1 to disable the task completely.
>   sync-minutes: -1

I will use mysql on a remote server, may I use this option?

Thank you for reading :)

**Comment by lucko** [comment]
> It disable all permissions granted by default by plugins?

Yes. That's exactly what it does. 🙂 

> I don't understand "attachment permissions", has you any example please?

It's similar to the previous option. It's where plugins grant specific players a permission.

> What is the goal of this option?

You an just ignore it. Most people change this option using commands and leave the config section empty.

> I will use mysql on a remote server, may I use this option?

You can, but a better description of this can be found here.   
https://github.com/lucko/LuckPerms/wiki/Instant-Update-Propagation
