### ISSUE TITLE
Prefixes / Suffixes Not Working.

### ISSUE THREAD

**Issue by DiggerZC** [lucko/LuckPerms#429]
Hi there, I am starting a factions server and my prefixes and suffixes are not working. I have EssXChat and it handles chat. When I set it to not handle chat I cannot see the faction names... only the Prefix. I need both to display. Is there anything that I can put into my EssXChat name format in config like for example "[Prefix] [FactionRoleIcon][FactionName]{NAME} &a&l>>"
Is there anything like the [Prefix] for LuckPerms that I can paste into my EssXChat config? Thanks!

**Comment by lucko** [comment]
You need to ask Essentials for support with this.

As far as I know, it's not possible. Something like DeluxeChat would be more appropriate.
