### ISSUE TITLE
Ranks randomly dissapearing

### ISSUE THREAD

**Issue by nettyneets** [lucko/LuckPerms#43]
Using LuckPermsSponge-2.14.6.jar, certain players ranks, permissions, prefixes and suffixes randomly disappear(all at the same time). I cannot confirm whether its more than one player at a time because unless you are typing in chat or issuing a command you won't notice. Relogging gives all the permission back.

**Comment by lucko** [comment]
I ideally need the server logs from when this occurs.

**Comment by nettyneets** [comment]
14.11 21:49:57 [Server] Server thread/INFO [FML]: [Server thread] Server side modded connection established
14.11 21:49:57 [Server] pool-2-thread-854/ERROR [Sponge]: The Scheduler tried to run the task luckperms-A-5470 owned by Plugin{id=luckperms, name=LuckPerms, version=2.14.6, description=A permissions plugin, authors=[Luck], source=/mods/LuckPermsSponge-2.14.6.jar}, but an error occured.
14.11 21:49:57 [Server] INFO java.lang.NullPointerException
14.11 21:49:57 [Server] INFO at me.lucko.luckperms.sponge.SpongeListener.lambda$onClientLogin$0(SpongeListener.java:90) ~[SpongeListener.class:?]
14.11 21:49:57 [Server] INFO at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:138) ~[Task$Builder.class:1.10.2-2123-6.0.0-BETA-1877]
14.11 21:49:57 [Server] INFO at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:177) ~[SchedulerBase.class:1.10.2-2123-6.0.0-BETA-1877]
14.11 21:49:57 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
14.11 21:49:57 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
14.11 21:49:57 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_91]
14.11 21:49:57 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_91]
14.11 21:49:57 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
14.11 21:49:57 [Server] Server thread/INFO srp11[/86.180.27.95:56273] logged in with entity id 89382 in world(0) at (1042.1016433052303, 72.0, -927.5195344734022)
14.11 21:49:57 [Server] Server thread/INFO srp11 joined the game

**Comment by lucko** [comment]
Strange for two reasons.

Firstly, I don't see how there could even be an error at that line. Secondly, even if there was an error at that point, it wouldn't prevent user's from having permissions. Are you sure that's the error?

Are there any other exceptions in your logs from LuckPerms?

**Comment by nettyneets** [comment]
This is the only error I have found in the last 2 hours. There's nothing relating to luckperms in the logs apart from these 
`14.11 22:02:51 [Server] Server thread/WARN [luckperms]: User Subject 'c78e8d7b-775b-42b8-9491-4fcffa91bec6' was requested, but is not loaded in memory. Loading them from storage now.
14.11 22:02:51 [Server] Server thread/WARN [luckperms]: Loading 'c78e8d7b-775b-42b8-9491-4fcffa91bec6' took 1 ms.`

**Comment by lucko** [comment]
Hmm, possibly related to d95891256ba19ea4b9b0c30f61aa97cf2052cd08

Can you try the latest dev build and see if that fixes it?

**Comment by lucko** [comment]
Assuming it was fixed already.
