### ISSUE TITLE
Global Groups

### ISSUE THREAD

**Issue by Audizign** [lucko/LuckPerms#430]
I'm requesting a permission grouping feature like in GroupManager. This allows me to easily assign groups of permissions to certain players without giving a player a bunch of permission nodes. For example

globalgroups.yml
```
g:newgroup
- permission.node.one
- permission.node.two
- permission.node.three
```
default.yml
```
###Adds permission.node.one, permission.node.two, and permission.node.three to group default.
default:
- g:newgroup
```
If there is already a way to do this, I apologize for wasting your time. Thank you for helping me in advance.

**Comment by lucko** [comment]
Yes, this is possible.

There's no concept of a "global group" in LuckPerms, but any group can be "global".

Using your example above:
```
/lp creategroup newgroup
/lp group newgroup permission set permission.node.one true
/lp group newgroup permission set permission.node.two true
/lp group newgroup permission set permission.node.three true

/lp group default parent add newgroup
```

Hopefully that makes sense. 😄
