### ISSUE TITLE
Permissions daata could not be loaded

### ISSUE THREAD

**Issue by ucraft02** [lucko/LuckPerms#431]
I get this error and ingame write me this

http://prntscr.com/g6ykwz

https://pastebin.com/gpMfXNc0

**Comment by lucko** [comment]
Check your BungeeCord log files.

**Comment by ucraft02** [comment]
in bungeecord I find only this

https://pastebin.com/5TrX29bL

**Comment by lucko** [comment]
Check when a player actually connects.

**Comment by ucraft02** [comment]
15:23:57 [INFO] [name] <-> DownstreamBridge <-> [hub] has disconnected
15:49:09 [INFO] [name] <-> ServerConnector [hub] has connected

**Comment by ucraft02** [comment]
I have disconect and conect

**Comment by lucko** [comment]
Did you get the error in chat?

**Comment by ucraft02** [comment]
no

**Comment by lucko** [comment]
So, what's the issue then?

**Comment by ucraft02** [comment]
I get this ingame

http://prntscr.com/g78v3h

**Comment by ucraft02** [comment]
Why I get this error

https://pastebin.com/gpMfXNc0

I disable luckperms and I don't get it

**Comment by lucko** [comment]
That error (the one in pastebin) has nothing to do with LP. It's totally unrelated.

When I asked if you got the error in chat, you said no?
