### ISSUE TITLE
Temporarily parent changes.

### ISSUE THREAD

**Issue by voodootje0** [lucko/LuckPerms#432]
Could you change the current /lp user <user> parent addtemp<duration> to literally to add a duration to the current duration and add a new command /lp user <user> parent settemp<duration> to set the duration.

**Comment by merjilin** [comment]
This may already be done here: https://github.com/lucko/LuckPerms/wiki/Configuration#temporary-add-behaviour

**Comment by merjilin** [comment]
The parent settemp isn't a thing yet, so that'll require luck's aid. But I hope that link shows how to add a duration to an existing temporary group/permission/meta erg.

**Comment by merjilin** [comment]
That was supposed to be etc* at the end. Whoops. Damn autocorrect got me!
