### ISSUE TITLE
LuckPerms doesn't close Database-Connections?

### ISSUE THREAD

**Issue by higgs01** [lucko/LuckPerms#433]
Today i've noticed that luckperms has many open connections(about 80, yesterday about 150) although i've just got about 15 minecraft servers running at the moment. All those connections are in `SLEEP`.

Is it possible that LuckPerms isn't closing DB-Connections properly?

**Comment by BrainStone** [comment]
They should be active while the servers are online. That's expected behavior. One instance spawns 10 connections.

**Comment by higgs01** [comment]
Aah, ok thanks for the fast response :)
