### ISSUE TITLE
[Question] What's the best way to configure Nucleus permissions for admins?

### ISSUE THREAD

**Issue by joserobjr** [lucko/LuckPerms#434]
I used to set "/lp group MyAdminGroup permission set *" to allow everything, but I've been told that it's a bad, so I checked the Nucleus permission list https://nucleuspowered.org/docs/permissions.html and it has a "suggested role" and it says that "The 'Suggested Role' column is also passed to permissions plugins", so, do I really need to set every single permission individually or is there a command to apply the suggested role to a group automatically?

**Comment by merjilin** [comment]
The actual nucleus command to setup permissions is covered here in the nucleus docs:
https://nucleuspowered.org/docs/configuration/permissions.html

**Comment by joserobjr** [comment]
Thank you merjilin
