### ISSUE TITLE
Ingame luckperms commands not working

### ISSUE THREAD

**Issue by nechtmarrie** [lucko/LuckPerms#435]
So i upgraded from v3.2.20 to v3.2.68 just now.
It looks like luckperms ralted commands are not working ingame, when issuing a lp command ingame whilst using a usergroup that has the * permission.

All i get returned is the following:  [LP] Running LuckPerms v3.2.68

Other plugins still work fine and issuing lp commands via console also still works.
Running CraftBukkit version git-Spigot-5340a52-e1f296d (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT) atm.

**Comment by lucko** [comment]
I can't reproduce.

Is your server running in offline mode, or are you using BungeeCord?

**Comment by nechtmarrie** [comment]
Yes we are using bungeecord, so our server runs in offline mode, we do use ip forwarding

**Comment by lucko** [comment]
Can you try using the /lp verbose command to debug which permissions are being checked for.

https://github.com/lucko/LuckPerms/wiki/Verbose

I'm pretty sure this is an issue with your permissions setup.
