### ISSUE TITLE
Make program?

### ISSUE THREAD

**Issue by renzotom** [lucko/LuckPerms#439]
Hello, can´t you make program like there is for PermissionsEx? I mean https://www.spigotmc.org/resources/pexbuilder-gui.42248/

What is there good?
**Available permissions** - you can select and them and transfer them to active permissions.

It looks very cool, beacuse you don´t need find permissions for specific plugin.

Or you can add that to your web interface.

**Comment by BrainStone** [comment]
LuckPerms has a graphical editor:  
![Editor Demo](https://gfycat.com/MeanThatChinesecrocodilelizard)
