### ISSUE TITLE
ChatControl's multiprefix feature

### ISSUE THREAD

**Issue by MADS0LADEN** [lucko/LuckPerms#44]
Please add support for chatcontrols multiprefix feature (i believe its from vault, no idea though)
ChatControl: https://www.spigotmc.org/resources/%E2%99%A3-chatcontrol-pro.10258/

**Comment by lucko** [comment]
Could you point me towards where that's documented?

LuckPerms already has support for Vault. Is that enough?

**Comment by lucko** [comment]
Assuming the Vault implementation is enough for the feature to work. If not, please re-open. :)

**Comment by MADS0LADEN** [comment]
### This happens if you are using the Multi_Prefix feature from ChatControl Pro:
![image](https://cloud.githubusercontent.com/assets/4103363/22406131/3603b068-e64d-11e6-8ea6-9812fffcfff3.png)

File: ChatControl/settings.yml
![image](https://cloud.githubusercontent.com/assets/4103363/22406139/651b0234-e64d-11e6-87c9-21d7fdf2f6a7.png)


Vault info
![image](https://cloud.githubusercontent.com/assets/4103363/22406092/46dff26c-e64c-11e6-972a-39225868d17c.png)

LuckPerms info
![image](https://cloud.githubusercontent.com/assets/4103363/22406122/14db4234-e64d-11e6-9b12-dca446fc4622.png)

**Comment by lucko** [comment]
Yeah. Not a LuckPerms bug, you need to seek support from ChatControl.

Alternatively, you can use the LuckPerms prefix/suffix stacking feature.
https://github.com/lucko/LuckPerms/blob/master/bukkit/src/main/resources/config.yml#L79

**Comment by MADS0LADEN** [comment]
Okay thanks, i'll contact @kangarko.
Yea i know the stacking, but i want to show them all in the prefix. :)

**Comment by kangarko** [comment]
ChatControl merely relies on Vault, to fetch prefixes and suffixes. I cannot reproduce running PermissionsEx, but I will test with this plugin as soon as I have the time frame.

**Comment by lucko** [comment]
In which case, I would assume it's a configuration issue.
