### ISSUE TITLE
BulkUpdate error running Mongo

### ISSUE THREAD

**Issue by TheDiamondBlock** [lucko/LuckPerms#443]
Running LuckPerms v3.2.66 (Legacy)

Currently trying to update the donation groups and I ran into an issue. I already renamed the group, but realized that I needed to perform a bulk update after reading the wiki section about it.

Switching donation rank "Ultimate" to "Legend".
`lp bulkupdate all update permission group.legend "permission == group.ultimate"`

After confirming the bulk update...

![Issue](https://image.prntscr.com/image/zwCDzGl_Sbu1hzWYpNmzmw.png)

Not sure if this is just me or the use of Mongo.

**Comment by lucko** [comment]
Thanks for reporting. :)
