### ISSUE TITLE
Problem with conversion 

### ISSUE THREAD

**Issue by EverMineServer** [lucko/LuckPerms#444]
After the conversation from PowerfulPerms i have this problem: all user have the primary group and the parent group inverted.
https://image.prntscr.com/image/046EVckDQOm_-CtIGsH0RA.png

Thanks for the help.

**Comment by BrainStone** [comment]
Try changing the parent-calculation setting to parents-by-weight.

**Comment by lucko** [comment]
^ should fix this.
