### ISSUE TITLE
Issue with MySQL driver on Sponge

### ISSUE THREAD

**Issue by PixelmonPRO** [lucko/LuckPerms#446]
Hello @lucko !) LP works good for 1.10.2-2281-5.2.0-BETA-2567, but version 1.10.2-2281-5.2.0-BETA-2569 and 2571 have next errors:
https://pastebin.com/dvYkECb4
All plugins for work in MySQL not connecting and work. I is error in LP, or SpongeForge?)
LP version: LuckPerms-Sponge-3.3.3

**Comment by lucko** [comment]
It's not a crash, rather, the MySQL driver installed on your server isn't working for some reason.

Can you try updating to a newer SF version?

**Comment by PixelmonPRO** [comment]
SF last in this page: https://www.spongepowered.org/downloads/spongeforge/stable/1.10.2
Thanks for the explanation, without knowledge of English it can sometimes be difficult to understand the errors and their consequences) I'll write issues in SF)

**Comment by lucko** [comment]
I doubt it's an SF issue.

More likely that you've installed a mod/plugin which is packaging an older/newer version of the driver.

**Comment by PixelmonPRO** [comment]
Version 1.10.2-2281-5.2.0-BETA-2567 and previous such errors do not cause) Only version 1.10.2-2281-5.2.0-BETA-2569, 1.10.2-2281-5.2.0-BETA-2571

**Comment by lucko** [comment]
Ok, and if you downgrade again, it works?

**Comment by PixelmonPRO** [comment]
Yes, server works, and there are no errors.
https://github.com/SpongePowered/SpongeForge/issues/1735

**Comment by lucko** [comment]
Have you actually tried downgrading to the SF version which works?    
I don't see how if that works, it could possibly be a LP issue.

blood is also mistaken, the error has nothing to do with loading groups.

```
[23:03:22] [Server thread/INFO] [STDERR/sponge]: [me.lucko.luckperms.common.storage.backing.sql.SQLBacking:init:197]: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: java.lang.NoClassDefFoundError: com/mysql/jdbc/MysqlIO
```

**Comment by ShadowKitten** [comment]
We are effected by this bug too, it has to be something in Sponge as no downgrade of LuckPerms will fix it only downgrading Sponge will help.

**Comment by bloodmc** [comment]
@lucko All we did was update our database libs

https://github.com/SpongePowered/SpongeCommon/commit/c4d8144c39c842214739f1131ca45b2cc2c53e30

**Comment by bloodmc** [comment]
Looks like this may be related to our new track method system. So don't bother looking into anything on your end.

**Comment by lucko** [comment]
Alrighty. Thanks blood.

**Comment by Sir-Will** [comment]
Same issue here after updating from spongeforge-1.10.2-2281-5.2.0-BETA-2464 to spongeforge-1.10.2-2281-5.2.0-BETA-2585.

I can't completely follow the comments above. Do I need to wait for a fix in sponge or luckperms?

**Comment by lucko** [comment]
Sponge.

Afaik, there's already a fix out, as of 3 hours ago.

**Comment by Sir-Will** [comment]
Alright, thanks.
