### ISSUE TITLE
Bug to LuckPerms

### ISSUE THREAD

**Issue by PilovMike** [lucko/LuckPerms#447]
Hi i am find bug in to do your LuckPerms plugin. I use this command /lp user Test parent addtemp VIP 10m to add temp group in to the player what works properly or problem is in the time to expire VIP group. If player is to my server to unless group expire to add automatically add tempgroup to permanent group and when expire tempgroup to player  all the time is set VIP to permanent this is very big problém to my server Please fix this bug Thanks

**Comment by lucko** [comment]
Sorry, I don't really understand what you're saying.

**Comment by PilovMike** [comment]
Oh sorry for my English. Hello problem is when I write / lp user Test addtemp VIP 10d to play the VIP settings for 10 days and start counting it down and when it is 10 days to automatically remove the players from the Parent temp list, but when the player is activated Temporarily a VIP group and idem between worlds on servers like world events, etc. So the VIP Group is placed in the Parent permanent Group, which means that the VIP Group will remain in the group after 10 days of trouble.

**Comment by lucko** [comment]
You can use `/lp user test removetemp vip` to remove the temporary permission.

**Comment by PilovMike** [comment]
Yes but player me VIP group Parent Permamanent no TempParent.  In 10 days, the players will change the temporary VIP group to the stand without to use commands.

**Comment by lucko** [comment]
In which case, you need to make sure the temporary parent is removed before you add the permanent one.

**Comment by PilovMike** [comment]
Problem is in to the that I set Player Temp Parent group and set expire time 10 Day so VIP group remains to player to expired 10 Day VIP group is set to Parent Permanent Group this is problem which i have to my server

**Comment by lucko** [comment]
Sorry, I have no clue what you're trying to say.

Could you give me an example / screenshots?

**Comment by PilovMike** [comment]
Ok Screenshots
Screenhost 1 : https://ctrlv.cz/DybB - I set player Temporaly parent groups: Sponzor witch use /lp user test parent addtemp sponzor 10m - this is ok
Problem is here:
Screenhost 2 https://ctrlv.cz/VXdG - After 3 minutes. Plugin alone set Temporaly parent groups Sponzor to Parent group to world novyspawn
Screenhost 3 : https://ctrlv.cz/sbvO - Another 3 minutes. Plugin alone set group sponzor to world eventy in Parent groups 
Screenhost 4  : https://ctrlv.cz/R34o After 10 minutes expire group sponzor and plugin remove sponzor but group sponzor is all the time set in to Parent Groups: and the player still has a sponsor group You can see the screenshot

**Comment by lucko** [comment]
The other groups in Screenshot 2 and screenshot 3 are not being added by LuckPerms.

Do you have Vault installed, or any plugins which edit permission data? I would guess it's caused by one of those.

This is definitely not an LP issue.

**Comment by PilovMike** [comment]
Yes vault is instaled to my server

**Comment by PilovMike** [comment]
I have no rights editing set through the Vault plugin

**Comment by lucko** [comment]
The only way that'd be happening is another plugin adding the groups through Vault.
