### ISSUE TITLE
Set User Group Based on Permission

### ISSUE THREAD

**Issue by hamcoremusic** [lucko/LuckPerms#448]
Hi there!

I would like to know if there is a way to give my players a specific command and only that command. The command would just add a player to a group.

For example, when people join my server they go into the Default group. The default group literally can't do anything (to prevent griefing). I want to make a command alias (/trust <player name>) that will assign them to a "Trusted" group; but I don't want the players to be able to use all LP commands for assigning groups, only one.

I hope I explained it good enough. Feel free to tell me if it doesn't make sense! Thanks!

**Comment by lucko** [comment]
Yes you can.

https://github.com/lucko/LuckPerms/wiki/Argument-based-command-permissions

However, I would suggest the easier way is to have the aliased command executed by the console.

**Comment by hamcoremusic** [comment]
Thanks for the reply. May I ask very briefly what I would put in the commands.yml to make the command run as console?

If not don't worry. Thank you!

**Comment by lucko** [comment]
Don't think it's possible with standard Bukkit aliases. You'd need another plugin.
