### ISSUE TITLE
Capitalization 

### ISSUE THREAD

**Issue by DeJayDevelopment** [lucko/LuckPerms#45]
Hi there. In converting to LuckPerms (went smoothly from GroupManager and permissionsex) all my capital lettered groups such as aGroup become agroup which breaks how the side loaded scoreboard  works/looks.

**Comment by lucko** [comment]
That's just a standardisation thing. All groups are considered case insensitive, and are made lowercase as a result.

If you want to change the way a group gets displayed, look into this: 
https://github.com/lucko/LuckPerms/wiki/Primary-Groups#can-i-use-this-feature-to-change-the-display-name-of-a-primary-group
https://github.com/lucko/LuckPerms/wiki/Default-Groups#keep-using-the-default-group-but-just-modify-the-display-name
