### ISSUE TITLE
Add CloudNet support

### ISSUE THREAD

**Issue by JarvisCraft** [lucko/LuckPerms#451]
Hello there, I would like to request plugin-support for CloudNet (https://www.spigotmc.org/resources/cloudnet.42059/) 
By this I mean an automatic ability of LuckPerms to get the Server-Group (equal to server name, but without its index, like Hub-1's group is Hub) from its API which can be enabled in config rather than manually set it up for each Server. 

I think that it would make LP more effective for usage with CN as CloudNet's permission system is quite ineffective in comparison with LuckPerms which would become even more useful with this feature. 

Thanks in Advance.

**Comment by lucko** [comment]
Cloudnet can provide this via a `ContextCalculator` in the LuckPerms API.

It's probably not something I'd be interested in adding to the main plugin though.

https://github.com/lucko/LuckPerms/blob/master/api/src/main/java/me/lucko/luckperms/api/context/ContextCalculator.java
https://github.com/lucko/LuckPerms/blob/master/api/src/main/java/me/lucko/luckperms/api/LuckPermsApi.java#L308
