### ISSUE TITLE
How do I add some permissions? Such as /spawn,/home...

### ISSUE THREAD

**Issue by Sssssti** [lucko/LuckPerms#452]
How do I add some permissions? such as /spawn,/home,/sethome...
The server is sponge 1.10.2
I can not find these permission nodes,use"minecraft.command.spawn" or "sponge.command.spawn" invalid.

I am not good in English, hope you can understanding.

**Comment by haoteng10** [comment]
These commands are from Essentials and EssentialSpawn. Check out their permission nodes.

**Comment by Sssssti** [comment]
I don't ues Essentials or EssentialSpawn.How Check？

**Comment by creator3** [comment]
You'll need to figure out which plugin/mod is providing those commands. If you're using Sponge, you're probably using the Nucleus plugin. A list of its permissions is available at  https://nucleuspowered.org/docs/permissions.html

**Comment by Axel63MC** [comment]
Just type in the command /lp tree and follow the link
