### ISSUE TITLE
Permissions not work

### ISSUE THREAD

**Issue by Andronachi-Marian** [lucko/LuckPerms#453]
1. I create a server and i put the LuckPerms and Essentials. The default group or other groups have 0 permissions defined and in game i have access to 5 pages of commands.
If i set to false i have access to command. Why is not set all permissions to false if is not defined ?
With PermissionsEx i don't have defined permissions and in game i don't have access. It works correctly.

2. Maybe need to move 4 fommands:
creategroup -> /lp group <group> create
deletegroup -> /lp group <group> delete
createtrack -> /lp track <track> create
deletetrack ->/lp track <track> delete

3. Meybe skip the message "already has this permission!" if the current permission is true and i set to false.

**Comment by lucko** [comment]
> I create a server and i put the LuckPerms and Essentials. The default group or other groups have 0 permissions defined and in game i have access to 5 pages of commands.
If i set to false i have access to command. Why is not set all permissions to false if is not defined ?
With PermissionsEx i don't have defined permissions and in game i don't have access. It works correctly.

Try setting `apply-bukkit-default-permissions` to false in the LP config.

> Maybe need to move 4 fommands:
creategroup -> /lp group create
deletegroup -> /lp group delete
createtrack -> /lp track create
deletetrack ->/lp track delete

I'm happy with the current layout. The sub commands nested behind /lp group are for making modifications to existing groups, not creating new ones.

> Meybe skip the message "already has this permission!" if the current permission is true and i set to false.

This is intended behaviour. Changing it would break the API signature internally.
