### ISSUE TITLE
Context for bungeecord plugin

### ISSUE THREAD

**Issue by xCraftRayX** [lucko/LuckPerms#455]
Hi I found this problem tried using BAT plugin for BungeeCord. Link: https://www.spigotmc.org/resources/bungee-admin-tools-basics-edition.444/

The case looks like this:
If the Admin group has the bat.admin privilege and a person receives it, then it will be able to use the / ban command. On the other hand, if someone receives this group but only on a given server and not globally, then this permission does not work properly as it should.

**Comment by BrainStone** [comment]
Since this permission is required on the bungee instead of the spigot use the context `server=<servername>` for the spigot and use `server=bungee world=<servername>` for the bungee. (Assuming you have set the servername for the bungee to `bungee` and the servernames on the bungee are the same as in the LP configs)

**Comment by xCraftRayX** [comment]
Hmm in bungee LuckPerms config name of server has name global.

I try type: /lpb group my_group permission set bat.admin server=global world=SkyBlock 
And it not working why?

**Comment by BrainStone** [comment]
It must not be named global (read the comment above the server name option). Just name it bungee

**Comment by xCraftRayX** [comment]
**Look in bungee config I have like that:**
`# The name of the server, used for server specific permissions. Set to 'global' to disable.
server: bungee

# If users on this server should have their global permissions applied.
# If set to false, only server specific permissions will apply for users on this server
include-global: true

# If users on this server should have their global world permissions applied.
# If set to false, only world specific permissions will apply for users on this server
include-global-world: true

# If users on this server should have global (non-server specific) groups applied
apply-global-groups: true

# If users on this server should have global (non-world specific) groups applied
apply-global-world-groups: true`

**And in creative server i have like that:**
`# The name of the server, used for server specific permissions. Set to 'global' to disable.
server: Creative

# If users on this server should have their global permissions applied.
# If set to false, only server specific permissions will apply for users on this server
include-global: true

# If users on this server should have their global world permissions applied.
# If set to false, only world specific permissions will apply for users on this server
include-global-world: true

# If users on this server should have global (non-server specific) groups applied
apply-global-groups: true

# If users on this server should have global (non-world specific) groups applied
apply-global-world-groups: true`

And I don't know why when I used command /lpb user NICK parent add Opiekun server=Creative | with permissions bat.admin and for example bat.ban this users with group Opiekun haven't permission to use command /ban on the Creative server.  Can you help me? I don't know what I doing bad... :(

**Comment by BrainStone** [comment]
Server names must be lowercase.

**Comment by xCraftRayX** [comment]
Okay I try it, but your plugin don't change names to small letters?

**Comment by xCraftRayX** [comment]
So, can you help me?

**Comment by lucko** [comment]
Can you explain precisely what you're trying to achieve? I'm just not sure what you're trying to do. :P

**Comment by xCraftRayX** [comment]
I have 5 servers + bungeecord:
Bungee, Survival, Creative, ColorfulMix, PvP, SkyBlock

I have 5 guardian on my server. Guardian translate to my language: "Opiekun".
Each guardian have almost full permission for selected server. Is 1 guardian per server.
And for example I using this command to set guardian on selected server: /lp user NICK parent add opiekun server=creative
And the group opiekun have this permissions which I sent to you in previous message, but it doesn't working... :(
Alternative I created group "Ban" with permission: bat.admin without context and I give this group to my guardian again without context but it is bad :( Because Guardian of Creative can ban players from Survival :( I want to resolve this problem wtih your help ;)

**Comment by lucko** [comment]
For the users who you've given the "opiekun" rank, can you run:

`/lp user <user> info`   
and   
`/lp user <user> parent info` 

whilst they're online, and then send the results here.

**Comment by xCraftRayX** [comment]
First command: https://scr.hu/yBmgDV
Second command: https://scr.hu/17aJze

**Comment by lucko** [comment]
Right, and you want to give players in that group access to the `bat.admin` permissions?

**Comment by xCraftRayX** [comment]
Yes

**Comment by lucko** [comment]
Is LuckPerms installed on your BungeeCord, and connected up to the same database>

**Comment by xCraftRayX** [comment]
Yes

**Comment by lucko** [comment]
Can you execute the same two commands again, except using `/lpb` instead this time?

**Comment by xCraftRayX** [comment]
1. https://scr.hu/a0NNjP
2. https://scr.hu/Z9eedX

**Comment by lucko** [comment]
You also need to add the group on `server=bungee world=creative` for the BAT permissions to work.

**Comment by xCraftRayX** [comment]
I do not understand, could you write me in steps what I have to do?
Because from what I understand, I have to create a Opiekun group, but it already exists.

**Comment by lucko** [comment]
`/lp user xwolfistytm parent add opiekun server=bungee world=creative`

**Comment by xCraftRayX** [comment]
Okay thanks, after school I will test it ;)

**Comment by lucko** [comment]
You might also need to update to this LP version on your BungeeCord for it to work properly.   
https://ci.lucko.me/job/LuckPerms/339/

**Comment by xCraftRayX** [comment]
Today I updated to 3.4.15.jar :D
It will be work propertly? :)

**Comment by lucko** [comment]
Nope, 3.4.16 contained a fix for a related issue.

**Comment by xCraftRayX** [comment]
Okay

**Comment by xCraftRayX** [comment]
It's working! Thanks for your work and time and I wish you luck ;)
