### ISSUE TITLE
group permission not being honered

### ISSUE THREAD

**Issue by Twidel** [lucko/LuckPerms#456]
With LP 3.3.19  groupperm in worldguard "member" not being honered.

Region:__global__
Flags:none
Owner:Leo*
Member:Josh*: *vip
Bounds: (0,0,0) -> (0,0,0)

Leo and Josh and all vip members have build perms and can build in this world
Leo is in group vip
All other members in group vip cannot build anymore after update from 3.3.15 to 3.3.19
Josh is also in group vip and could not build until added as member by name.

**Comment by lucko** [comment]
Does downgrading to `3.3.15` fix the problem? If so, can you try to do it?

**Comment by lucko** [comment]
Feel free to re-open this if it's still causing an issue.
