### ISSUE TITLE
Command to remove only prefixes/suffixes

### ISSUE THREAD

**Issue by Eufranio** [lucko/LuckPerms#457]
Actually, `lp user X meta clear` will clear everything, including options (`lp user X meta set`). I'd like to have a command like it, but only for prefixes, like `/lp user X meta clearprefix` or so, then I can remove ALL prefixes with ALL priorities from the player.

**Comment by lucko** [comment]
* `/lp user X meta clear prefixes`
* `/lp user X meta clear suffixes`
* `/lp user X meta clear chat` (both prefixes and suffixes)
* `/lp user X meta clear meta` (just meta (option) key-value pairs)
