### ISSUE TITLE
Weird issue after pex migration

### ISSUE THREAD

**Issue by q220** [lucko/LuckPerms#458]
I'm having serious issues using LP which is odd since I tested it on a different server where the migration worked perfectly fine.

Basically whenever a user joins the console is flooded with error messages, at first I thought it was related to Vault. Why would it nag about a bPermissions calculabletype class when I'm not using bPermissions?

Vault-info returns:

[12:27:04 INFO]: [Vault] Vault v1.6.1 Information
[12:27:04 INFO]: [Vault] Economy: Essentials Economy [bInfo, LuckPerms]
[12:27:04 INFO]: [Vault] Permission: LuckPerms [LuckPerms, SuperPerms]
[12:27:04 INFO]: [Vault] Chat: bInfo [bInfo, LuckPerms]

So yeah, it does seem to think bPermissions is used, while it is clearly not?

Plugins returns:

[12:27:54 INFO]: Plugins (36): CoreProtect, dynmap, LuckPerms, WorldEdit, Animations, TheGaffer, RemoteToolkitPlugin, PlaceholderAPI, BannerBoard, Multiverse-Core, WorldGuard, ProtocolLib, MCMESuite, NoCheatPlus, Freebuild, Tours, VoxelSniper, React, PlotBuild, cTablist, Guidebook, Tab, Vault, TheHelper, AutoTeleport, MyWarp, VentureChat, Essentials, ResourceRegions, DiscordSRV, LeaderHeads, PluginUtils, PremiumVanish, MCME-Architect, MiniGames, NewPlayerQuiz

The only permission manager in there is LuckPerms.

Gist to quite lengty console output on player join: https://gist.github.com/q220/7a9f99611923c7f080036965963af94e

**Comment by q220** [comment]
Also this is vault-info from my test server where all went smoothly:

`[12:39:37 INFO]: [Vault] Vault v1.6.1 Information
[12:39:37 INFO]: [Vault] Economy: Essentials Economy [LuckPerms]
[12:39:37 INFO]: [Vault] Permission: LuckPerms [LuckPerms, SuperPerms]
[12:39:37 INFO]: [Vault] Chat: LuckPerms [LuckPerms]
`

**Comment by EmanYm** [comment]
what I'm getting from your error is that WorldGuard doesn't see LuckPerms, and I think "bpermissions" might just mean the bukkit permission handler, not the bPerms plugin.

>Could not pass event PlayerJoinEvent to WorldGuard v6.2.2-SNAPSHOT

Try going back to the latest release, instead of a snapshot

Searching for "luckperms" on the error has no results, but "worldguard" is on almost every error (except the cTablist and PremiumVanish errors).
Searching for "bperm" did yield a lot of results...There's a chance that those three plugins are not compatible with LP

This is just my observation, and I could be mistaken, I'm a Sponge user not bukkit/spigot.  I would still wait for a response from Lucko.

**Comment by q220** [comment]
I tried going back to the recommended release versions of worldedit and worldguard, but the problem remains. If I have op it won't show the errors but the moment I'm de-opped it will start showing the errors every time I move or change point of view. I'm not sure if its LP related, but I started having this after the switch from pex. Could these errors be of permissions that are not set explicitly?

**Comment by q220** [comment]
I'm gonna close this for now since it seems this is related to another of our plugins. When I was disabling them one by one I managed to deductively find which plugin is making the server think it is running bPermissions.

**Comment by lucko** [comment]
(sorry for the late reply, I've been away for a couple of days)

Which plugin was it, just so I know for future reference?

My first suggestion would've been to check the wepif config file. Seems like bPermissions was being defined there.

**Comment by q220** [comment]
We have a custom made plugin that handles server resourcepacks depending on the region: https://github.com/MCME/ResourceRegions

The wepif file should be default, as far as I know it was never touched:

`#^M
# WEPIF Configuration File^M
#^M
# This file handles permissions configuration for every plugin using WEPIF^M
#^M
# About editing this file:^M
# - DO NOT USE TABS. You MUST use spaces or Bukkit will complain. If^M
#   you use an editor like Notepad++ (recommended for Windows users), you^M
#   must configure it to "replace tabs with spaces." In Notepad++, this can^M
#   be changed in Settings > Preferences > Language Menu.^M
# - Don't get rid of the indents. They are indented so some entries are^M
#   in categories (like "enforce-single-session" is in the "protection"^M
#   category.^M
# - If you want to check the format of this file before putting it^M
#   into WEPIF, paste it into http://yaml-online-parser.appspot.com/^M
#   and see if it gives "ERROR:".^M
# - Lines starting with # are comments and so they are ignored.^M
#^M
# About Configuration Permissions^M
# - See http://wiki.sk89q.com/wiki/WorldEdit/Permissions/Bukkit^M
# - Now with multiworld support (see example)^M
^M

ignore-nijiperms-bridges: true
resolvers:
    enabled:
    - PluginPermissionsResolver
    - PermissionsExResolver
    - bPermissionsResolver
    - GroupManagerResolver
    - NijiPermissionsResolver
    - DinnerPermsResolver
    - FlatFilePermissionsResolver
permissions:
    groups:
        default:
            permissions:
            - worldedit.reload
            - worldedit.selection
            - worlds.creative.worldedit.region
        admins:
            permissions:
            - '*'
    users:
        sk89q:
            permissions:
            - worldedit
            groups:
            - admins
`

**Comment by lucko** [comment]
I guess just remove `bPermissionsResolver` from that configuration.

**Comment by q220** [comment]
Removing the bPermissionResolver did not work (nor did removing every entry in the wepif.yml file) However, we found that there was a sort of 'indirect' dependency on wepif through the plugin I mentioned. So it had nothing to do with with LuckPerms :).

PS: Really loving your plugin!

**Comment by lucko** [comment]
Glad to hear the issue is fixed! :)
