### ISSUE TITLE
group x list autocomplete wrong

### ISSUE THREAD

**Issue by voodootje0** [lucko/LuckPerms#461]
When you type /lp group <group> list + TAB it's not correctly autocompleting it. It's becomming <group> info instead of <group> listmembers

**Comment by lucko** [comment]
Duplicate of #419?

**Comment by lucko** [comment]
Oh, or you just excluded that in your example?

This is likely because "list" is an alias of the `info` command.
https://github.com/lucko/LuckPerms/blob/master/common/src/main/java/me/lucko/luckperms/common/commands/CommandManager.java#L344

**Comment by voodootje0** [comment]
Aha. It would be great if you can remove the alias :)
