### ISSUE TITLE
Prefix & Suffix change the Essentials display name

### ISSUE THREAD

**Issue by Skjido** [lucko/LuckPerms#463]
Whenever I set a prefix and or suffix this appears on every line where EssentialsChat uses the player display name.
Meaning that the Prefix is visible in the tab list, /list list and also some messages like MOTD, login and logout message.
Is there a way to toggle this?
So that prefix and suffix only get used in the chat like the old PermissionsEx did?
Or that you can use {prefix} and {suffix} in the Essentials config, that the display name stays untouched like the Factions plugin does?

**Comment by lucko** [comment]
Fairly sure there's an option for this in the Essentials config. 

Either way, it has nothing to do with LuckPerms.

**Comment by Skjido** [comment]
Okay, I'll look for a way around this, but do you know how to let ranks begin with a capital letter?
It doesn't really let me.

**Comment by lucko** [comment]
https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/config.yml#L48

**Comment by Skjido** [comment]
Thanks, I will give that a try.
