### ISSUE TITLE
bungeecord plugin

### ISSUE THREAD

**Issue by aycgit** [lucko/LuckPerms#465]
can this plugin work for the bungee messaging service without interferring with bungee permissions. AFAIK there is no way to set bungee permissions in luckperms and config.yml bungee perms don't work so is it possible to make the bungee config override lp?

**Comment by Andre601** [comment]
LuckPerms does work on BungeeCord.
Just make sure, that you download the right version from the Jenkins-page.
https://ci.lucko.me/job/LuckPerms/

**Comment by aycgit** [comment]
andre, i am using the ci version? i am just saying that it breaks bungees normal perms without adding a good way to add them back

**Comment by Ryan-Haytree** [comment]
The whole point of installing luckperms on bungeecord is to manage bungeecord permissions. Having it do that makes the plugin completely redundant. 

However, it is not hard to setup your bungeecord permissions using luckperms. If you need help setting up luckperms-bungee, it would be best for you to join our support discord.

**Comment by aycgit** [comment]
okay /lpb, i am just blind
