### ISSUE TITLE
i don't can remove this permission

### ISSUE THREAD

**Issue by mat41997** [lucko/LuckPerms#467]
![2017-09-12 13_30_41-c__users_y7_appdata_local_temp_fz3temp-2_p yml - notepad](https://user-images.githubusercontent.com/5884000/30323724-9da54808-97be-11e7-8716-a98558c6da26.png)

command
```
/luckperms group svip permission unset essentials.speed
```
not removes this permission for group
```
/luckperms group svip permission set 
essentials.speed true
```

---------------------------------------------

i no have any error
and i have the latest build luckperms

---------------------------------------------

how to?
I copied badly this permissions
http://wiki.ess3.net/wiki/Command_Reference
and paste to console

**Comment by lucko** [comment]
Those commands need to be on the same line in the exported file.

**Comment by mat41997** [comment]
i know that
you can fix this bug?

**Comment by mat41997** [comment]
this is not export bug

**Comment by mat41997** [comment]
i don't can remove this "essentials.speed" permission for my databas

**Comment by lucko** [comment]
Show me the output when you run

`/lp group svip permission unset essentials.speed`, as well as any errors you get in console.

**Comment by mat41997** [comment]
no, command ```/lp group svip permission unset essentials.speed``` normaly work

i use discordsrv plugin console to paste text copy for that site "http://wiki.ess3.net/wiki/Command_Reference"

and now i can remove this data
```/luckperms group svip permission set 
essentials.speed true```

**Comment by lucko** [comment]
Sorry, I have no clue what you're trying to ask.   
You just pasted the same exact command 3 times.

**Comment by mat41997** [comment]
you can help me?

**Comment by mat41997** [comment]
ok. relax

steps to reproduc

1. copy ```

essentials.speed
``` for this site
http://wiki.ess3.net/wiki/Command_Reference

2. paste to discord console
![2017-09-12 20_04_00- s2-survival-console - discord](https://user-images.githubusercontent.com/5884000/30341243-9cd583ca-97f5-11e7-8f26-a2debecdb0cc.png)

3. generate input file
![2017-09-12 20_09_51-c__users_y7_appdata_local_temp_fz3temp-2_inpot yml - notepad](https://user-images.githubusercontent.com/5884000/30341488-708f4250-97f6-11e7-904a-376477af012a.png)

4. test  ( not work )
![2017-09-12_20 10 52](https://user-images.githubusercontent.com/5884000/30341517-92bbaf3a-97f6-11e7-903c-39643e6602c7.png)

5. add true permissions in game
![2017-09-12_20 13 08](https://user-images.githubusercontent.com/5884000/30341593-e27cc180-97f6-11e7-934d-ead41007b065.png)

6. input
![2017-09-12 20_17_18-movies tv](https://user-images.githubusercontent.com/5884000/30341750-74799c48-97f7-11e7-8d45-9a6fad3e173f.png)

7. test ( work )
![2017-09-12_20 18 19](https://user-images.githubusercontent.com/5884000/30341776-8cf09a74-97f7-11e7-812b-85dab9c80e25.png)

...

how do i can remove this from my database?
![2017-09-12 20_17_18-movies tv](https://user-images.githubusercontent.com/5884000/30341821-c858cf0a-97f7-11e7-8722-71e878c4e2d5.png)

**Comment by mat41997** [comment]
https://git.io/v5DnJ

**Comment by lucko** [comment]
Seems like the Discord console appends a newline to the start of the permission. This is *not* a LuckPerms bug.

You'll probably have to remove the permission manually, or run the unset command via Discord.

**Comment by mat41997** [comment]
yep, of course
anyway, thx for help me : P

**Comment by mat41997** [comment]
@lucko you can block give this badly permissions?

**Comment by lucko** [comment]
Yes.

**Comment by mat41997** [comment]
do it ^^
