### ISSUE TITLE
bungeechat permission

### ISSUE THREAD

**Issue by mat41997** [lucko/LuckPerms#468]
https://github.com/AuraDevelopmentTeam/BungeeChat2/issues/24#issuecomment-328883779

**Comment by lucko** [comment]
It's issue reports like this which makes me think a template is needed. (I don't like templates.)

So, can you please actually put some effort into your issue reports. The bare minimum I need is:

* A clear explanation of what the issue is
* An example
* How it can be reproduced

**Comment by Andre601** [comment]
It looks like, the problem is solved @lucko

**Comment by mat41997** [comment]
this in no a solved bug

i have "server: global" in bungee server luckperms config
and "server: global" in spigot server lucperms config
see
https://gist.github.com/mat41997/6f9a6186be5d29c496640537062d403f

i use command
```
/lp group default permission set bungeechat.command.msg
```
and not work
![2017-09-12_18 22 42](https://user-images.githubusercontent.com/5884000/30337066-74a50488-97e7-11e7-81ac-61e46a9751db.png)

This command should work

**Comment by lucko** [comment]
You need to use `/lpb`.
