### ISSUE TITLE
Excess output to console when chatting in game.

### ISSUE THREAD

**Issue by bnicholsonnc** [lucko/LuckPerms#469]
I was trying to get a suffix working and noticed that there was alot of excess output in the console when sending out a test message in chat. 

I am not sure if my failed attempt at making a suffix is to blame, but as soon as I set it I was disconnected from the server. The command I gave to create the suffix was "/lp group owner meta addsuffix 100 " &c[&nAdmin\&n]". Looking back im sure I was not supposed to try and end &n with a '\'. 

Anyways, I relogged and tried a test and the suffix was not there at all. It was at this point that I took a look at the console and saw a bunch of messages. I cleared out the suffix but the console is still outputting in abundance. I even tried logging out, restarting the server and relogging, but still the same thing.

I'm using LuckPerms-Sponge-3.2.60.jar on a spongeforge-1.12-2443-7.0.0-BETA-2498.jar server running MC version 1.12

Any help would be appreciated.

> 12.09 21:19:10 [Server] Server thread/INFO [Eonox][l]<Eonoxious>: Test
12.09 21:19:10 [Server] Server thread/ERROR [Sponge]: Could not pass MessageChannelEvent$Chat$Impl to Plugin{id=nucleus, name=Nucleus, version=1.1.3-LTS-S5.1, description=The Ultimate Essentials Plugin., source=/mods/Nucleus-1.1.3-LTS-S5.1-MC1.10.2-plugin.jar}
12.09 21:19:10 [Server] INFO java.lang.ClassCastException: me.lucko.luckperms.sponge.service.model.SubjectReference cannot be cast to org.spongepowered.api.service.permission.Subject
12.09 21:19:10 [Server] INFO at io.github.nucleuspowered.nucleus.modules.chat.util.TemplateUtil.getTemplate(TemplateUtil.java:61) ~[TemplateUtil.class:1.1.3-LTS-S5.1]
12.09 21:19:10 [Server] INFO at io.github.nucleuspowered.nucleus.modules.chat.listeners.ChatListener.onPlayerChat(ChatListener.java:152) ~[ChatListener.class:1.1.3-LTS-S5.1]
12.09 21:19:10 [Server] INFO at org.spongepowered.common.event.listener.ChatListener_ChatListener_onPlayerChat114.handle(Unknown Source) ~[?:?]
12.09 21:19:10 [Server] INFO at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12-2443-7.0.0-BETA-2498]
12.09 21:19:10 [Server] INFO at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:314) [SpongeModEventManager.class:1.12-2443-7.0.0-BETA-2498]
12.09 21:19:10 [Server] INFO at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:265) [SpongeModEventManager.class:1.12-2443-7.0.0-BETA-2498]
12.09 21:19:10 [Server] INFO at net.minecraftforge.fml.common.eventhandler.EventBus.postForgeAndCreateSpongeEvent(EventBus.java:594) [EventBus.class:?]
12.09 21:19:10 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.handler$injectChatEvent$zpe000(NetHandlerPlayServer.java:2811) [oy.class:?]
12.09 21:19:10 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:932) [oy.class:?]
12.09 21:19:10 [Server] INFO at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
12.09 21:19:10 [Server] INFO at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
12.09 21:19:10 [Server] INFO at org.spongepowered.common.network.PacketUtil.lambda$onProcessPacket$0(PacketUtil.java:147) [PacketUtil.class:1.12-2443-7.0.0-BETA-2498]
12.09 21:19:10 [Server] INFO at org.spongepowered.common.network.PacketUtil$$Lambda$1308/47245896.call(Unknown Source) [PacketUtil.class:1.12-2443-7.0.0-BETA-2498]
12.09 21:19:10 [Server] INFO at org.spongepowered.common.event.tracking.CauseTracker.switchToPhase(CauseTracker.java:161) [CauseTracker.class:1.12-2443-7.0.0-BETA-2498]
12.09 21:19:10 [Server] INFO at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:146) [PacketUtil.class:1.12-2443-7.0.0-BETA-2498]
12.09 21:19:10 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjo000(SourceFile:539) [hv$1.class:?]
12.09 21:19:10 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
12.09 21:19:10 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_45]
12.09 21:19:10 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_45]
12.09 21:19:10 [Server] INFO at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
12.09 21:19:10 [Server] INFO at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:269) [SpongeImplHooks.class:1.12-2443-7.0.0-BETA-2498]
12.09 21:19:10 [Server] INFO at net.minecraft.server.MinecraftServer.redirect$onRun$zia000(MinecraftServer.java:3988) [MinecraftServer.class:?]
12.09 21:19:10 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720) [MinecraftServer.class:?]
12.09 21:19:10 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:391) [nx.class:?]
12.09 21:19:10 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:665) [MinecraftServer.class:?]
12.09 21:19:10 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:523) [MinecraftServer.class:?]
12.09 21:19:10 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]

**Comment by BrainStone** [comment]
Try using a lower version of Sponge Forge as some big changes happened. I can recommend a version about a week old.

**Comment by lucko** [comment]
Or rather, the right version of Nucleus for your server. :)

(you're running an API 5 build but your server is API 7)
