### ISSUE TITLE
/lp migration could use an error message when used in game

### ISSUE THREAD

**Issue by LemADEC** [lucko/LuckPerms#47]
As of LuckPermsSponge-2.15.3.jar, when using /lp from ingame, there's no hint that it needs to be run from console.

**Comment by lucko** [comment]
The command simply doesn't exist for in-game users.

The only way you'd even find out about the command is by reading the Migration/Command Usage wiki pages, both of which indicate that the commands must be used from the console.

https://github.com/lucko/LuckPerms/wiki/Command-Usage#super-secret-console-commands
https://github.com/lucko/LuckPerms/wiki/Migration#how-to

So, the behaviour is just the same as if you typed in any other unknown command. 🙂

**Comment by LemADEC** [comment]
yes, the issue is actually generic:
- in game, any unrecognized command returns the plugin version with no hint that there's an issue.
- in console, any unrecognized command returns the plugin version and a list of commands to use.
So, in console, it's pretty clear the command is invalid, while in game it's far from obvious.

**Comment by lucko** [comment]
Not sure what you mean. The behaviour re: unrecognised commands is the same for Players/console. 

It however, only returns the commands a player has permission to use.

**Comment by LemADEC** [comment]
well, I'm OP and in the admin group imported from Pex.
It appears that I have no perms to use any LP commands because
```
"permissions-default": 1,
```
from Pex admin group wasn't migrated to Pex permissions.
As discussed on Discord, the fix is:
/lp group group permission set * true

With that I can see the accessible commands.
So, 1 bug and 1 improvement here:
1- default perms are lost when migrating from Pex
2- when user has no lp perms, show an appropriate message

**Comment by lucko** [comment]
No usage messages = no access to any LP commands. Again, this goes back to the migration thing, I can't automate everything.

Default perms on PEX behave differently to LuckPerms' wildcard - which is why I'm reluctant to migrate it.
