### ISSUE TITLE
Unable to read default minecraft.command nodes

### ISSUE THREAD

**Issue by onwee** [lucko/LuckPerms#470]
Hello,

I have the latest version of spigot and the latest version of luckyperms posted on the spigot site.

My problem is that none of the minecraft.command.* permission nodes are loaded in lp tree and they take no effect when I load them. I still get permission denied.

I have a few pictures, one is showing it's configured in the database, the type of error I get, proof that a minecraft.command.ban permission node is loaded and working, and version numbers of mods I'm using.

All other permission nodes work. Bukkit.* and all permission nodes for any plugin work flawlessly.

I just can't ban, can't gamemode, things like that. Please let me know if I need to handle this another way or if there is a bug. Thank you.

![capture](https://user-images.githubusercontent.com/31908821/30356375-3e914674-97fe-11e7-9aa5-5fc94438883e.PNG)
![capture2](https://user-images.githubusercontent.com/31908821/30356393-5bdb72d6-97fe-11e7-9ead-68548b94ec4c.PNG)
![capture3](https://user-images.githubusercontent.com/31908821/30356407-7cdf239c-97fe-11e7-957b-dabd1513e604.PNG)
![capture4](https://user-images.githubusercontent.com/31908821/30356446-b78cf514-97fe-11e7-8c5f-1508e8e4edfd.PNG)

**Comment by onwee** [comment]
One more note, I must op myself to use these commands. They work only when opped.

**Comment by BrainStone** [comment]
Try using the verbose feature to find out which permissions are checked when running the vanilla commands.  
The wiki has a page on verbose and how to use it.

**Comment by onwee** [comment]
Wow. Verbose is fantastic.

This led to the discovery that the essentials mod is overwriting default minecraft permission nodes. For example, instead of minecraft.gamemode it became essentials.gamemode
