### ISSUE TITLE
Prefix are broken

### ISSUE THREAD

**Issue by Shootingisgood9** [lucko/LuckPerms#475]
I just started having this problem where when I add two parent groups to an other group, it gives that other group the parent prefixs and uses one as display in chat. When I do /lp group (that group) info it says it has 3 prefixs. How do I remove them?

**Comment by Andre601** [comment]
I think, setting different weights to the prefixes should help.
Or just negate the permission of the prefix (prefix.[wheight].[prefix with color/formattingcodes]) in the group, that inherits the groups

**Comment by Shootingisgood9** [comment]
How do I set the weight of the prefix? I set the weight of the ranks already from 15weight-1weight (1 is owner and admin is 2 and so on)

**Comment by Andre601** [comment]
It's exactly the oposite...
Higher numbers are higher priorities....

You can set it with `/lp group <your group> meta addprefix <wheight> <prefix>`

**Comment by Shootingisgood9** [comment]
Neither work. I set the weights and the other prefix still shows and I did the negate permission part and still did't work.

**Comment by Shootingisgood9** [comment]
I did Set prefix.1.[PokeNoob] to false for mod in context global for the negate and I did owner as 15 and went down from there and still no.

**Comment by lucko** [comment]
You remove existing prefixes by running `/lp group <group> meta info`, and clicking on the values you want to remove.

**Comment by Shootingisgood9** [comment]
It worked Thank you!

**Comment by lucko** [comment]
Awesome!

If you encounter any further issues, feel free to open a new ticket / drop a message in Discord.
