### ISSUE TITLE
command a exported file bug

### ISSUE THREAD

**Issue by mat41997** [lucko/LuckPerms#476]
in exported file i have
![2017-09-16 18_08_44-movies tv](https://user-images.githubusercontent.com/5884000/30513832-2e6b28e6-9b0a-11e7-9839-d1afc68856ad.png)
and i use
![2017-09-16_18 11 35](https://user-images.githubusercontent.com/5884000/30513852-a251929a-9b0a-11e7-91fa-0357322ca170.png)
and i have a error
![2017-09-16_18 12 21](https://user-images.githubusercontent.com/5884000/30513854-ad3b9bce-9b0a-11e7-86c3-12417b9c15f3.png)

**Comment by creator3** [comment]
That command would be for removing a permission set with world="true". Just don't include "true" at the end.

**Comment by lucko** [comment]
Thanks @creator3 

The fail messages in the latest versions should make this more obvious. :)
