### ISSUE TITLE
How to set a other default group.

### ISSUE THREAD

**Issue by Shootingisgood9** [lucko/LuckPerms#477]
I know their is already a group called default and you start with it and I am wondering how I can set a other group to when they join, they are in it. Sorry if its in a doc but I can't find it

**Comment by BrainStone** [comment]
https://github.com/lucko/LuckPerms/wiki/Default-Groups

**Comment by Shootingisgood9** [comment]
It shows what to do but I don't know where to put my default group name as my config is


#  rule1 {
#    if {
#      has-true="(<group.vip> | <group.vip+>) & <titles.tilecollector>"
#      has-false="<some.random.permission>"
#      lacks="<prison/group.prison_titlepack>"
#    }
#    give = [
#      "prison/group.prison_titlepack"
#    ]
#    take = [
#      "some.random.permission"
#    ]
#  }

**Comment by Shootingisgood9** [comment]
Where do I put the default groups name?(Or whatever you would call it)

**Comment by Shootingisgood9** [comment]
Wait may have found how to

**Comment by Shootingisgood9** [comment]
Nope doesn't work I found this 

 rule3 {
#    if {
#      has-true="<group.default>"
#    }
#    take = [
#      "group.default"
#    ]
#    give = [
#      "group.PokeNoob"
#    ]
#    set-primary-group="PokeNoob"
#  }
}


(The areas where it says PokeNoob use to say member)

**Comment by Ryan-Haytree** [comment]
Groups are stored in lowercase. Try it with `"group.pokenoob"` and `set-primary-group:"pokenoob"`

**Comment by Shootingisgood9** [comment]
It works, thank you!
