### ISSUE TITLE
Permissions aren't working for bungeecord.

### ISSUE THREAD

**Issue by orangeman20002** [lucko/LuckPerms#478]
Hello,

I recently downloaded your plugin instead of using bungeeperms because I like the layout of the plugin and there are a lot of features that bungeeperms doesn't have. However i'm having a problem and as the title suggest it's with the permissions I enter into a group. I'll drop my permissions file for the rank i'm working on to help you see what i'm doing or trying to do. Anyway I have entered the permissions the way it's supposed to be entered and i'm using the default group with just a prefix I added. 

The problem I am having is when I got to do the command ingame after i deop myself and remove all the extra permissions from myself it's saying i can't execute the command even though i have the permission set. 
[Group i'm working on.zip](https://github.com/lucko/LuckPerms/files/1308914/Group.i.m.working.on.zip)

**Comment by Ryan-Haytree** [comment]
Make sure you have luckperms-bungee installed on bungeecord, as well as luckperms installed on your spigot servers. Then have all of them connected to the same database. If this doesn't work, it means your IP forwarding isn't setup correctly. Make sure `ip-forwarding` is set to true on bungee, as well as `bungeecord` is set to true on your spigot servers.

**Comment by orangeman20002** [comment]
Thanks for the quick reply. I'll do this and get back to you.
