### ISSUE TITLE
[Suggestion] Bulk import and export

### ISSUE THREAD

**Issue by renzotom** [lucko/LuckPerms#480]
Hello, can you add bulk import and export? I mean import and export for switching storage types (https://github.com/lucko/LuckPerms/wiki/Switching-storage-types). We can do only /luckperms export <file> and /luckperms import <file>, but what about export and import one folder, or more files in folder?

**Comment by BrainStone** [comment]
`/lp export/import` exports and imports all data.

**Comment by renzotom** [comment]
I need only one folder

**Comment by BrainStone** [comment]
Run the export and remove what you don't need from the file.

**Comment by renzotom** [comment]
And can you add way, we can choose, where it will be exported? In the main folder, it isn't to good, when I export everything. Maybe you can create special folder for it.

**Comment by BrainStone** [comment]
First of all I don't code LuckPerms. And secondly, what's the issue with a single file being generated in the main dir, so that you can easily find it?

**Comment by renzotom** [comment]
But when I export more files, there is too many files.

And I want bulk export and import, beacuse it will be easier than export ..., export ... .

**Comment by BrainStone** [comment]
You have to run export only once! It contains ALL data.

**Comment by lucko** [comment]
Just run a full export, and delete the lines you don't want.

**Comment by renzotom** [comment]
Ok, thanks, you can close it.
