### ISSUE TITLE
tab autocomplete isn't working as it should

### ISSUE THREAD

**Issue by c00ldude1oo** [lucko/LuckPerms#481]
When doing a /lp command the autocomplete does not work right examples 

if I do /lp user <name> P + TAB it does the permissions 1st if I hit tab again it doesn't show the parent one it just stays as the perms one

if I do /lp user/group <name>/<group> P + TAB and there is a player on that starts with a P it will do there username and show a list of other names if more are on (this one maybe is caused by a bungee plugin because it didn't do this weeks ago or it's from an LP update but most likely not)

I don't remember if there were any other things that didn't work haven't done any LP commands in a week also, it all may be caused by a bungee or spigot plugin and if it is could there be a way that LP can overrule the plugins?

**Comment by lucko** [comment]
Thanks for reporting 👍
