### ISSUE TITLE
Its it Possible to import Ranks/UserInfo from GroupManager?

### ISSUE THREAD

**Issue by kingdevnl** [lucko/LuckPerms#482]
Its it Possible to import Ranks/UserInfo from GroupManager?

**Comment by merjilin** [comment]
The regular migration command of `/lp migration GroupManager` should import all data into luckperms

**Comment by Andre601** [comment]
`/lp migration GroupManager`

https://github.com/lucko/LuckPerms/wiki/Migration

**Comment by kingdevnl** [comment]
THANKS!
