### ISSUE TITLE
help

### ISSUE THREAD

**Issue by SoulWolfX** [lucko/LuckPerms#484]
I use luck perms for my permission but sometimes when people relog there rank resets anyone know a fix?

Also, Does anyone know a way I can take the perms from another server drag them to all of them and edit depending on what game mode without bungee mode.

**Comment by lucko** [comment]
> I use luck perms for my permission but sometimes when people relog there rank resets anyone know a fix?

Make sure IP forwarding is setup and configured correctly on all of your servers. :)
https://www.spigotmc.org/wiki/bungeecord-ip-forwarding/

> Also, Does anyone know a way I can take the perms from another server drag them to all of them and edit depending on what game mode without bungee mode.
Yep, you need to use a remote storage type, such as MySQL.

See:
https://github.com/lucko/LuckPerms/wiki/Choosing-a-Storage-type   
https://github.com/lucko/LuckPerms/wiki/Switching-storage-types

**Comment by SoulWolfX** [comment]
@lucko IP forwarding was enabled lol some people it stays some don't.

**Comment by lucko** [comment]
Double check the setting on all of your servers.

If players are randomly losing permissions data, it is most likely due to incorrect ip forwarding on one of your servers.
