### ISSUE TITLE
Reload

### ISSUE THREAD

**Issue by Games4k** [lucko/LuckPerms#485]
Can you please add reload command?
This would be really helpful!!

**Comment by lucko** [comment]
Use `/lp reloadconfig` or `/lp sync`.

**Comment by Games4k** [comment]
It is not working like it should. it probably reloads some options, but not mysql and server-name

**Comment by lucko** [comment]
The `server` property *is* reloadable. 

Storage and messaging related options are not reloadable, as they need a full server restart to take effect. This cannot be easily changed, as data is non consistent between multiple stores.
