### ISSUE TITLE
Luckperms and bungee

### ISSUE THREAD

**Issue by GothkittyGirl** [lucko/LuckPerms#486]
Im helping run and setup a server and  we have luckperms working on all servers but 1 and cant figure out what we are missing. i have kinda limited access to luckperms stuff but wanted to see what you said about this issue and if you might know what was stopping it from working

**Comment by spannerman79** [comment]
> wanted to see what you said about this issue

What issue?  You have provided nothing - no background, no logs, just a nonsensical paragraph of blabber.

As such only help you'll get is the following - https://github.com/lucko/LuckPerms/wiki

**Comment by mat41997** [comment]
https://ci.lucko.me/job/LuckPerms/

try install luckperms bungee on you bungee server

**Comment by GothkittyGirl** [comment]
ok im sorry you made me think to check the logs and i just noticed vault wasnt installed and its fixed now. sorry to post this before looking there again this issue is Resolved now
