### ISSUE TITLE
How do I fix this?

### ISSUE THREAD

**Issue by Shootingisgood9** [lucko/LuckPerms#491]
I wanna make players able to purchase VIP and keep the perks of the rank they had before. So like we have a bunch of normal ranks and when they purchase VIP, They can keep their old rank and VIP.

**Comment by Shootingisgood9** [comment]
Reason this is a question is because no one responded in discord support chat.

**Comment by lucko** [comment]
> Reason this is a question is because no one responded in discord support chat.

Sorry, must've missed it :/

You can just use the `parent add` command to give them VIP. It'll apply on top of their existing groups.
https://github.com/lucko/LuckPerms/wiki/Command-Usage#lp-usergroup-usergroup-parent-add
