### ISSUE TITLE
Adding external permissions from other plugins

### ISSUE THREAD

**Issue by tborg2014** [lucko/LuckPerms#492]
I'm using the sponge version of this plugin for my server and I'm having a difficult time figuring/ finding out how to add external permissions to luckperms.

Example: Permissions from Project worlds, (pjw.cmd.world.properties) where would I add this perm into so then I can allow a group to access, as I keep getting I do not have permissions to use that command. /world properties is the command.

I am on v. 1.10.2

**Comment by spannerman79** [comment]
https://forums.spongepowered.org/t/project-worlds-world-manager/10170

All the perm nodes are listed

**Comment by lucko** [comment]
https://github.com/lucko/LuckPerms/wiki/Usage#creating-the-first-group

**Comment by tborg2014** [comment]
> https://forums.spongepowered.org/t/project-worlds-world-manager/10170

All the perm nodes are listed

> I know the perm nodes are there its just how do I apply them to give me perms. I put /lp group admin permission set (insert perm node) true

if i were than to do, for example, /world properties after doing the properties node it would say I don't have permission even though I just set the perms. That's the issue I am having

**Comment by spannerman79** [comment]
https://github.com/lucko/LuckPerms/wiki/Verbose#filters

Then check console while you try to issue those commands - that will tell you whats going on.

**Comment by tborg2014** [comment]
> https://github.com/lucko/LuckPerms/wiki/Verbose#filters Then check console while you try to issue those commands - that will tell you whats going on.

Ok so I did the verbose and it looks like its not working. 
<script src="https://gist.github.com/anonymous/49ab1ff52740e64e8f9d86296fcef01c.js"></script>

I tried Luck & minecraft, nothing appeared, I tried Luck & pjw, nothing appeared, i even tried Luck & pjw.cmd.world.properties and nothing popped up.

**Comment by lucko** [comment]
the `Luck & ...` example is just that, an example.

Luck is my username, you should replace it with your own.

**Comment by tborg2014** [comment]
https://gist.github.com/anonymous/e262e9f64220971d71b39dd5fbdd4131

So I did the verbose in my name and I am also in the admin group that I created. The command minecraft.command.ban was added true for admin were server=server, world = true. When I searched my name with minecraft it didn't show me anything like in the example here: https://gist.github.com/anonymous/cc5284865892659fa8b06aac1e3d024d

**Comment by lucko** [comment]
Sorry, I'm not following what you mean.

I thought the issue was with project worlds?
