### ISSUE TITLE
group-name-rewrite in mysql

### ISSUE THREAD

**Issue by voodootje0** [lucko/LuckPerms#493]
Would it be possible to change `group-name-rewrite` config option into a mysql and command based feature?

So instead of changing the config in every server you could easily do:
`/lp namerewrite <group> <new name> [context]` and it will be stored in mysql.

**Comment by lucko** [comment]
Yeah, although I'd prefer `/lp group <group> setdisplayname <name> [contexts...]`.

(also not totally sure if I like the idea of having it dependant on contexts though? Should surely be a similar system to weight?)

**Comment by voodootje0** [comment]
Hmm. I think contexts are needed. On a prison server, you use default to display the name A and on other servers, you use a name that has to do with the game mode etc. 

I don't really see this working if it's similar to the weight system.

**Comment by lucko** [comment]
Surely you should just be using different groups in that situation?

For instance, on prison you might use `prisonrank1` through to `prisonrank100`, and on survival `survivalrank1` --> `survivalrank100`.

I personally would do this, as opposed to using `rank1` --> `rank100`, with the group shared between both servers.

**Comment by voodootje0** [comment]
You're right, contexts aren't good for this. Weights are the better for this.
