### ISSUE TITLE
Export options

### ISSUE THREAD

**Issue by voodootje0** [lucko/LuckPerms#495]
Could you add that you can export specific things? Like only groups, permissions, and might also the only thing that contains a specific context. 

Command should be little bit advanced since what should it export exactly, player groups, group permission, user permission, etc.

**Comment by lucko** [comment]
The export operation should be pretty fast. (less than a minute for even the biggest of servers)

So, it should be easy enough to just export everything, then delete the stuff you don't want.

**Comment by voodootje0** [comment]
Oh yeah good one, I can just easily use bulk edit 😛
