### ISSUE TITLE
cross server issues

### ISSUE THREAD

**Issue by GothkittyGirl** [lucko/LuckPerms#498]
Im have alot of issues trying to sync up across servers.. :/ it would seem that is doing perm world and i dont want that i want all the same stuff

**Comment by lucko** [comment]
Is LuckPerms connected to the same database on all of your servers?

**Comment by GothkittyGirl** [comment]
yes

**Comment by GothkittyGirl** [comment]
copyed the config from my spigot server to all the other spigot server and left bungee with bungee

**Comment by lucko** [comment]
Can you pastebin one of your config files & send it here please. :)

**Comment by GothkittyGirl** [comment]
https://pastebin.com/wbTxRQqP Bungee

https://pastebin.com/RwJrWQGA Spigot

**Comment by lucko** [comment]
Ok, can you give me an example of a permission you've set, which command you used to set it, and where it should be applied?

**Comment by GothkittyGirl** [comment]
they should be the same i imported it from groupmanager but just not sure how to make the perms but for all server instead of per server perms

**Comment by lucko** [comment]
Ok, can I see the output to the `permission info` command for the relevant groups?

I need to see what you've got setup so far before I can actually help diagnose the problem. :)

**Comment by GothkittyGirl** [comment]
do i do that in console?

**Comment by GothkittyGirl** [comment]
or per server?

**Comment by lucko** [comment]
Doesn't matter - should be the same output for all of them

**Comment by GothkittyGirl** [comment]
gives me a list of commands when i run that

**Comment by lucko** [comment]
Try doing it in console then

**Comment by GothkittyGirl** [comment]
https://pastebin.com/1YCVwqGy Bungee

https://pastebin.com/x8XrKAEG Spigot

**Comment by lucko** [comment]
`/lp user <you> permission info` and `/lp user <you> parent info` will show you the permissions you have, and the groups you inherit from.

You can use that to check that all of your permissions are correct. 

If everything seems to be there, I suggest you check with `/lp verbose` to ensure you have the right nodes.

https://github.com/lucko/LuckPerms/wiki/Verbose

**Comment by GothkittyGirl** [comment]
welp i guess ill have to manully rank people back to there ranks because its not been working right. and not giving the right rank at all in  plotsquared server :/

**Comment by GothkittyGirl** [comment]
https://pastebin.com/ujSj2bqH is the info for plotsquared

**Comment by GothkittyGirl** [comment]
wait does the :3306 have to been there?

**Comment by lucko** [comment]
No, it's added by default.

Until you carry out the steps in my previous comment, there's not much I can do to help. If you notice anything in those outputs which is wrong, then feel free to post screenshots here.

Ultimately, the plugin will do what you tell it to do, so if things aren't working, it's because you've set something up incorrectly. :)

**Comment by GothkittyGirl** [comment]
ok so looks like when i set a perm is does it globally so thats right but Current Contexts: (world=world)
Does that need to be  world=global?

**Comment by lucko** [comment]
No, global permissions will always apply. (so long as include-global is true in the config)

**Comment by GothkittyGirl** [comment]
ok ty
