### ISSUE TITLE
essentialsx prefix not work on addtemp

### ISSUE THREAD

**Issue by mat41997** [lucko/LuckPerms#499]
timings
https://timings.aikar.co/?id=9dd0ef75bd37475784f50ca57e568a87

verbrose
https://git.io/vdi9e

perm
https://gist.github.com/mat41997/e552e14c0119171abd08fc165fd6f4e3

ss
![2017-10-13_05 32 11](https://user-images.githubusercontent.com/5884000/31529203-1f33c35a-afd8-11e7-9a1f-c45cc40a0680.png)

![2017-10-13_05 33 03](https://user-images.githubusercontent.com/5884000/31529208-23213d26-afd8-11e7-8ab5-7221fd7e3ab4.png)

the same problem as
https://github.com/lucko/LuckPerms/issues/488

**Comment by lucko** [comment]
Does the correct value show when you run `/lp user <user> info`, under 'current prefix'?

**Comment by mat41997** [comment]
not work
``/lp user konorohimarie parent addtemp admin 10m``
![2017-10-13_23 05 11](https://user-images.githubusercontent.com/5884000/31566471-0ef00196-b06b-11e7-8083-960c4859352a.png)

work
``/lp user konorohimarie group set admin``
![2017-10-13_23 07 31](https://user-images.githubusercontent.com/5884000/31566524-520302da-b06b-11e7-8c71-5f7a99ce7b6b.png)

**Comment by lucko** [comment]
Your chat formatting plugin seems to be applying formats based upon a users primary group.

As you might've noticed, in both cases, "Current prefix" shows the correct value, but the users primary groups are different.

To fix this, you can either:

1. Switch the chat plugin to just pull the prefix from LuckPerms - it's not doing this at the moment.

or

2. Change the way primary groups are calculated. (I'd change it to either `parents-by-weight` or `all-parents-by-weight`. You then need to make sure each of your groups have an appropriate weight assigned to them)

https://github.com/lucko/LuckPerms/wiki/Configuration#primary-group-calculation

**Comment by lucko** [comment]
Just to clarify, this is absolutely not an Essentials issue.

You've just configured the plugin (EssentialsChat in this case) incorrectly. I gave two solutions above.
