### ISSUE TITLE
User shows as being offline

### ISSUE THREAD

**Issue by dracnis** [lucko/LuckPerms#50]
When i try to make a bungeecord command it said i don't have perms, and when i run /lpb user Soreth info it say me i'm offline, i don't know if it's normal.

**Comment by lucko** [comment]
Any errors in BungeeCords console/logs?

**Comment by dracnis** [comment]
any error, on all spigot server spigots permissions work but bungee permissions don't work ( can't /alert /server .... )

**Comment by lucko** [comment]
Make sure you're setting the permission correctly with regard to the per-server permissions on your BungeeCord.

The default server on Bungee is "bungee".

**Comment by dracnis** [comment]
# +------------------------------------------------------------------------+ #
# |                               General                                  | #
# +------------------------------------------------------------------------+ #

# The name of the server, used for server specific permissions. Set to 'global' to disable.
server: bungee

# If users on this server should have their global permissions applied.
# If set to false, only server specific permissions will apply for users on this server
include-global: true

# If users on this server should have their global world permissions applied.
# If set to false, only world specific permissions will apply for users on this server
include-global-world: true

# If users on this server should have global (non-server specific) groups applied
apply-global-groups: true

# If users on this server should have global (non-world specific) groups applied
apply-global-world-groups: true

and and console :
19:03:32 [INFOS] [RexxarHunter] <-> ServerConnector [hub] has connected
>lpb user info
19:04:56 [INFOS] [LP] User Sub Commands: (/bperms user <user> ...)
19:04:56 [INFOS] [LP] > info
19:04:56 [INFOS] [LP] > permission
19:04:56 [INFOS] [LP] > parent
19:04:56 [INFOS] [LP] > meta
19:04:56 [INFOS] [LP] > getuuid
19:04:56 [INFOS] [LP] > switchprimarygroup - <group>
19:04:56 [INFOS] [LP] > promote - <track> [server] [world]
19:04:56 [INFOS] [LP] > demote - <track> [server] [world]
19:04:56 [INFOS] [LP] > showtracks
19:04:56 [INFOS] [LP] > bulkchange - <server|world> <from> <to>
19:04:56 [INFOS] [LP] > clear - [server] [world]
>lpb user RexxarHunter info
19:05:17 [INFOS] [LP] > User Info: rexxarhunter
[LP] - UUID: d42c51c5-b5c0-384c-b4dc-96fcc70ca3a9
[LP] - Status: Offline
[LP] - Primary Group: default
[LP] - Counts:
[LP] -    Permissions: 1
[LP] -    Temporary Permissions: 0
[LP] -    Prefixes: 0
[LP] -    Suffixes: 0
[LP] -    Meta: 0
19:05:17 [INFOS] [LP] - Parent Groups:
19:05:17 [INFOS] [LP] -    > default
19:05:17 [INFOS] [LP] - Cached Data:
[LP] -    Is Loaded: false
[LP] -    Current Contexts: None
[LP] -    Current Prefix: None
[LP] -    Current Suffix: None

**Comment by lucko** [comment]
Check your settings for online mode. They're probably incorrect.

**Comment by dracnis** [comment]
online mode is set to true as default

**Comment by lucko** [comment]
Unable to reproduce.
![](http://i.imgur.com/MnrWEY9.png)
