### ISSUE TITLE
negation not work

### ISSUE THREAD

**Issue by mat41997** [lucko/LuckPerms#501]
timings
https://timings.aikar.co/?id=51e42116c28445a4b229980b8c3cc767

perms
https://gist.github.com/mat41997/ab9f396239229717f7417f878a6271ac

verbose
https://git.io/vd1r4

![2017-10-15_01 10 01](https://user-images.githubusercontent.com/5884000/31580081-e96863d8-b145-11e7-89a4-baa42c5ae34f.png)
i still can use ``/fly`` in server skyblock 

i no have this problem on permissionsex plugin

**Comment by lucko** [comment]
Probably because you also inherit from other groups, or have the permission set directly.

Check with

* `/lp user <you> permission info`
* `/lp user <you> parent info`

You need to learn to debug your own issues instead of just identifying something not working and immediately blaming the plugin.

**Comment by mat41997** [comment]
![2017-10-15_01 28 03](https://user-images.githubusercontent.com/5884000/31580158-2c8ab704-b148-11e7-8e3c-85bba4c59c74.png)
![2017-10-15_01 28 19](https://user-images.githubusercontent.com/5884000/31580159-2cae7bbc-b148-11e7-888c-f2830ea59fbb.png)

**Comment by mat41997** [comment]
and, what is next?

**Comment by lucko** [comment]
Are you opped?

**Comment by mat41997** [comment]
i disabled op

exampled /gm 1 not work

**Comment by Andre601** [comment]
Did you set the servername in the config.yml?

**Comment by mat41997** [comment]
![2017-10-15_01 32 19](https://user-images.githubusercontent.com/5884000/31580198-bbdb6ebc-b148-11e7-8f96-8c38ee991aea.png)

**Comment by lucko** [comment]
You need to set the `server` value in the LuckPerms config.yml.

**Comment by mat41997** [comment]
no, i don't can. becaus i use ``server: global``

**Comment by mat41997** [comment]
i not, change this.

**Comment by lucko** [comment]
Ok, then that's the problem.

Server specific permissions & groups apply based on that config option.

**Comment by mat41997** [comment]
aaa ok. XD thanks

**Comment by Andre601** [comment]
Why not?
It won't change stuff. Global permissions will be still global.
That setting there just tells LuckPerms, that this server is "SkyBlock"

**Comment by mat41997** [comment]
sorry. I thought for this is the server-mode.
