### ISSUE TITLE
HELP!

### ISSUE THREAD

**Issue by ChinWashere** [lucko/LuckPerms#503]
What do i need to fill in by Address and where can i find it
https://gyazo.com/fdd7ec68754434e5bcb15c4fa11dddaa

**Comment by Andre601** [comment]
You don't even know your own MySQL-adress?

If it's on the same server, like your MC-Server, then you can use `127.0.0.1` for the localhost-adress...

**Comment by ChinWashere** [comment]
Nope i only need to know what to fill in Address  127.0.01 does not work

**Comment by ChinWashere** [comment]
Only want to know what i need to fill in
here.
https://gyazo.com/901bff09284a55c9537b2b39bf112432

**Comment by Andre601** [comment]
Do you use MySQL? And is it set in the Storage-Type?

**Comment by ChinWashere** [comment]
yes
https://gyazo.com/3a55abd36d635888dcbbf298490774ac

**Comment by Andre601** [comment]
Did you create a user AND database for LuckPerms in MySQL?
(I guess you're using PhPMyAdmin?)

**Comment by ChinWashere** [comment]
Yes i made a database called Luckperms
And a user called localhost with password 12345

**Comment by Andre601** [comment]
Is the Database on the same server (IP) like the mc-server?

**Comment by ChinWashere** [comment]
Where do i need to see that i didnt had a option

**Comment by Andre601** [comment]
Do you use phpMyAdmin?
Then get your nummerical-IP (example: 123.456.7.8) post it in the browser and add /phpmyadmin at the end.
If you get to the loginpage of phpMyAdmin, then you have it on the same server, like your MC-server.
If not, then it probably is on another IP and it can get complicated...

**Comment by ChinWashere** [comment]
Yes i use phpmyadmin and no i dont have the same IP

**Comment by lucko** [comment]
If you're paying someone else to provide your database (a hosting company), I suggest you ask them to help you with this process.

If you're hosting the database yourself, then you should know what the IP address of the machine is. :P
