### ISSUE TITLE
Unable to get user info for offline players.

### ISSUE THREAD

**Issue by mibby** [lucko/LuckPerms#504]
LuckPerms dev 358
Yaml database.

You are unable to get user information for offline players.
```/lp user <user> info``` outputs that the user could not be found. However the user does exist in the user files post migration.

**Comment by merjilin** [comment]
If they haven't logged it yet, try using their UUID  in the command

**Comment by mibby** [comment]
LP doesn't automatically look up users by the name reference in their user file? Having to find what someone's UUID is to get their groups or permissions if they haven't logged in yet seems a bit tedious with large databases.

**Comment by merjilin** [comment]
If they haven't logged on post migration, yes. The export command uses the uuid to ensure nothing dodgy goes on. After they've logged in, you can use their username.

**Comment by mibby** [comment]
The username already exists in the file though. Why not do a look-up of the name to pull the UUID file?

**Comment by lucko** [comment]
Set this option to true. 

https://github.com/lucko/LuckPerms/wiki/Configuration#use-server-uuids

**Comment by mibby** [comment]
That option is already set to true but I'm not able to look-up players by their name who haven't logged in since migration.

```
# This option only really exists for networks who for whatever reason cannot setup proper ip
# forwarding.
use-server-uuids: true
```

**Comment by lucko** [comment]
Oh, sorry my bad, I meant this option:

https://github.com/lucko/LuckPerms/blob/master/bukkit/src/main/resources/config.yml#L71

**Comment by mibby** [comment]
Changing that setting seems to work. Thanks.
