### ISSUE TITLE
[Enchancement] Event based timings

### ISSUE THREAD

**Issue by spannerman79** [lucko/LuckPerms#509]
What I propose would be something akin to having a pre-configured permission group setup for seasonal events.

Some examples would be and not limited to;

- Halloween
- Christmas
- New Years
- Easter

Plus many others. In the UK the Queens Birthday could be one such event.

These groups would be almost like `/lp user/group <user|group> permission settemp` except it wouldn't be a time set to expire - the time set would be when that group will be active between `aa` date and `bb` date.

**Comment by lucko** [comment]
Why don't you just add the group when `aa` occurs for a duration of `bb - aa`?

I don't see why this needs to be a special feature when it's easily do-able already.

**Comment by dvdcd** [comment]
i agree. just add a inherit from `Halloween` to your default group during the duration of the event.
