### ISSUE TITLE
World perms

### ISSUE THREAD

**Issue by GothkittyGirl** [lucko/LuckPerms#510]
Wrld perms are not working ive tryed everything and cant remove a perm for a world. i have to disable it alltogether

**Comment by mat41997** [comment]
use ``/lp export test.yml``
upload this file with
https://gist.github.com/

and give me

**Comment by GothkittyGirl** [comment]
https://gist.github.com/GothkittyGirl/e926fa49128d22a0b512e071f8731ed2

**Comment by mat41997** [comment]
try update your luckperms
https://ci.lucko.me/job/LuckPerms/

and try
/lp group <groupName> permission set <examplePermission> true world=<worldName>
/lp group <groupName> permission set <examplePermission> false world=<worldName>
/lp group <groupName> permission unset <examplePermission> true world=<worldName>
/lp group <groupName> permission unset <examplePermission> false world=<worldName>

**Comment by GothkittyGirl** [comment]
i didnt set those i imported from groupmanager :/

**Comment by GothkittyGirl** [comment]
THANK YOU very very much this worked /lp group <groupName> permission set <examplePermission> false world=<worldName> on the world i was trying to disable /sell hand on :D
