### ISSUE TITLE
Group Info Parent Group nuance

### ISSUE THREAD

**Issue by RussianRonin** [lucko/LuckPerms#511]
So, I was looking at group info for my admin group. The admin group is parent to four groups. But if you look at group info, it shows that the 4 are parent groups of admin. Am I missing something here? If I am not, shouldn't they appear as child groups and not parent? I honestly just think the wording is bad if so.

![image](https://user-images.githubusercontent.com/21460243/31789609-84c150a4-b4c7-11e7-832d-3c4471dee8fe.png)

![image](https://user-images.githubusercontent.com/21460243/31789632-8fd38566-b4c7-11e7-8393-147754f832f9.png)

**Comment by Andre601** [comment]
"parent group" means, that the group inherits permissions from this group.
This means, that your admin-group inherits permissions from moderator, novanisheffects, bmadmin and essentialsadmin.
That's what "parent groups" means. Groups, that give permissions to this group.

If you want that this 4 groups inherit permissions, you need to use the parent-command at them.

**Comment by RussianRonin** [comment]
I know what a parent group is... the admin group is the parent of those 4 groups. Therefore it inherits all 4 of those groups permissions unless overridden by the group itself. The wording is weird though as it can make it seem like those 4 groups are the parent of admin.

**Comment by Andre601** [comment]
>The wording is weird though as it can make it seem like those 4 groups are the parent of admin.
That makes sense to me, because Parent group = parent of that group = gives all it permission to this group
It isn't any different real life. Our parents give theyr DNA to us...

**Comment by RussianRonin** [comment]
That makes sense... when you look at it biologically, it does make sense.

But from a hierarchy, the admin group is higher than those groups as it can override.

Weird nuances between parent and child I guess.
