### ISSUE TITLE
LP v3.4.15 "lp user RussianRonin clear" issue

### ISSUE THREAD

**Issue by RussianRonin** [lucko/LuckPerms#512]
Whenever I clear my own perms for testing stuff, I still have access to all my perms until I reconnect to the server.

I use "/lp user RussianRonin clear" in game and I can still use all my owner perms unless I DC.

Same thing happens when I switchprimarygroup to owner. I need to reconnect to actually get my permissions.

Am I missing something here? Shouldn't it take effect immediately? Is there some caching mechanism in place?

 I search for issues regarding to this and couldn't find any FAQ's or anything.

Please let me know if you need any other info.

List of other plugins: 
![image](https://user-images.githubusercontent.com/21460243/31791660-2d97ff2e-b4ce-11e7-9304-ef24c82d1904.png)

**Comment by Andre601** [comment]
Do you use luckperms.autoop?
Because this permission needs you to change the server/world, to apply.

**Comment by RussianRonin** [comment]
I do and that must be the issue. Thanks for the quick response. Good to know.
