### ISSUE TITLE
API Improvements

### ISSUE THREAD

**Issue by XakepSDK** [lucko/LuckPerms#513]
1. Ability to change server name at load time
2. Ability to add own messaging service implementation
3. Ability to add custom storage provider

Can you do this? Do you accept pull requests?
Your plugin is really cool, i want to use it in my minigames core module, but i need these 2 features.

**Comment by lucko** [comment]
The first is already do-able by setting the server to "global" in the config, and then registering your own `ContextCalculator` to provide the variable at runtime.

https://github.com/lucko/LuckPerms/blob/master/api/src/main/java/me/lucko/luckperms/api/LuckPermsApi.java#L315

I can see a custom messaging service implementation working - it's really just a two way string channel.

However, custom storage providers, I'm uhh, not so sure on. Although it has now stabilised a bit, that system changes quite frequently, and I'm not sure including it in the API makes sense.

For both messaging & storage, what custom implementations are you thinking of? If it's a fairly well known storage type, you could always just PR the implementations themselves.

**Comment by XakepSDK** [comment]
For storage - cassandra
For custom messaging - http://nats.io/

**Comment by lucko** [comment]
Will happily accept decent PRs for either. :)
