### ISSUE TITLE
Make the info command interactive for parent groups.

### ISSUE THREAD

**Issue by voodootje0** [lucko/LuckPerms#517]
Could you make `/lp user <user> info` parent groups section the same as `/lp user <user> parent info` so you can click on them and directly execute the commands 😄

**Comment by lucko** [comment]
I'll be honest, I don't think it's worth the effort.

To do this, the whole message would need to be split up and sent individually. Parent groups only form a small part of the output, and is really just there for convenience. If you want to see the full list, you should use the `parent info` command.
