### ISSUE TITLE
 [Fixed] I need a Contexts instance of a player who is online on Bungeecord but not in the Bukkit server

### ISSUE THREAD

**Issue by TheGlitch76** [lucko/LuckPerms#519]
I am making a chat plugin that adds global chat, private messaging, and other essentials-chat like features and it needs to get the prefix and suffix of a player in another server, and I would like to have the plugin handle that in Bukkit, so that chats are visible in each console window, among other things. Is there any way to do this?

**Comment by TheGlitch76** [comment]
Found what I needed... Close this please.

**Comment by spannerman79** [comment]
@TheGlitch76 you should be able to close the issue yourself

**Comment by TheGlitch76** [comment]
@spannerman79 I honestly can't figure out how...

**Comment by TheGlitch76** [comment]
Oh, there it is. Sorry.
