### ISSUE TITLE
Prefixes not showing on UltimateChat 

### ISSUE THREAD

**Issue by Auroratic** [lucko/LuckPerms#522]
Running on a 1.10.2 Sponge Server with latest UltimateChat (1.8.3) and LuckPerms v3.2.60

Rank has weight of **100** - Ran the following command:
`/lp group owner addprefix 100 Owner`

Can''t seem to get any prefix parsed over from LP to UltimateChat. Is there a workaround or can you get it resolved please?

Thanks and Best Regards

**Comment by merjilin** [comment]
Could you update your Luckperms to the latest please. We can't help you if you're running on a very old build :) https://ci.lucko.me/job/LuckPerms/

**Comment by lucko** [comment]
I also suggest you update UltimateChat.

If the correct value shows when you run `/lp user <user> info`, then it's an UltimateChat issue.

If the correct value doesn't show, then you've set up prefixes incorrectly. You can use the `meta info` command to work out where you went wrong. :)
