### ISSUE TITLE
Making changes to a group file does not reload permissions for players of that group currently online.

### ISSUE THREAD

**Issue by mibby** [lucko/LuckPerms#523]
LuckPerms dev 376

If you make changes to a group.yml permissions and then re-upload the file, LuckPerms does not reload all permissions for players currently online to get a current / new snapshot of recently added or removed permissions. Players have to manually relog to get the new permissions.

```
# When using a file-based storage type, LuckPerms can monitor the data files for changes, and then
# schedule automatic updates when changes are detected.
#
# If you don't want this to happen, set this option to false.
watch-files: true
```

Using yaml storage method for all files.

Since there is no actual ```/lp reload``` command, I can't manually force a permission reload on everyone without having to do a forced server restart or kicking everyone.

Edit: Also of note, when adding permissions manually at the bottom of the file and re-uploading, it does not re-sort the permissions alphabetically in the file. Not sure if that is something done on first initialization.

Edit 2: Even relogging didn't clear all previously cached permissions for me. I had to do a full server restart to get clean and current chat formatting permissions since I uploaded new groups with negated group format permissions. I had chat formats for multiple groups despite the permissions being disabled.

Edit 3: Reloading the server did not re-sort permissions in the group file alphabetically / by wildcard first. Perhaps that may have broke too.

**Comment by BrainStone** [comment]
You can always reload the permissions with `/lp sync`.

**Comment by lucko** [comment]
> If you make changes to a group.yml permissions and then re-upload the file, LuckPerms does not reload all permissions for players currently online to get a current / new snapshot of recently added or removed permissions. Players have to manually relog to get the new permissions.

Can you check your server console after uploading the file? It's possible that the filewatcher just didnt detect the change.

> Edit: Also of note, when adding permissions manually at the bottom of the file and re-uploading, it does not re-sort the permissions alphabetically in the file. Not sure if that is something done on first initialization.

This is intended - sorting will only occur when LP writes it's own changes to the file.

> Edit 2: Even relogging didn't clear all previously cached permissions for me. I had to do a full server restart to get clean and current chat formatting permissions since I uploaded new groups with negated group format permissions. I had chat formats for multiple groups despite the permissions being disabled.

Yeah, relogging wouldn't help if the group data had changed. As Brain said, `/lp sync` will update all data.

> Edit 3: Reloading the server did not re-sort permissions in the group file alphabetically / by wildcard first. Perhaps that may have broke too.

Again, this is intended, the file is only re-sorted when LP writes a change to the file. It only reads when the server starts.
