### ISSUE TITLE
latest version

### ISSUE THREAD

**Issue by TheFrostMonster** [lucko/LuckPerms#524]
Plz Upload the latest version to spiggot or bukkit i love your plugin but the version that Aternos provides is the latest one on spiggot and bukkit and that one has a problem where players that get kicked get lp permssions data not found i understand that the latest version has fixed this but athernos only allows plugins from spiggot or bukkit so i dont have the latest version that you provide thanx :)

**Comment by lucko** [comment]
You can grab the latest version here and upload it to your server.

https://ci.lucko.me/job/LuckPerms/

I push builds to Spigot when I think they're stable enough, and have enough changes / new features to justify a release.

**Comment by TheFrostMonster** [comment]
I understand sadly Aternos dosnt allow me to upload plugins i can only download the ones they provide thanx for your help anyways
