### ISSUE TITLE
MySQL problem with action log - actor_name

### ISSUE THREAD

**Issue by Krosta8** [lucko/LuckPerms#525]
Hello, after the update to new version of LuckPerms (57) I have a problem with database table lp_actions. I tried to do "clear install". Drop all tables and generate new thorugh the plugin, but everytime I got an error with action. Everytime I got "Data truncation: Data too long for column "actor_name" at row 1.
The problem appears everytime, when I run command from console and sometimes when I run commad directly from Minecraft.

Does anyone know the solution for this?
PS: Log is still function correctly and it writes to database correctly too.

Here is an example of the problem: https://pastebin.com/NeU2tAT4

**Comment by lucko** [comment]
What's the value of `server` in your LP config file?

**Comment by Krosta8** [comment]
technicpack1122
and the second is pokecraftreborn1102 (problem is on both)

**Comment by lucko** [comment]
Should be fixed after running the latest version on at least one of your connected servers.
