### ISSUE TITLE
Empty permission

### ISSUE THREAD

**Issue by Lmmb74** [lucko/LuckPerms#526]
Whenever I try to fly/move while using a disguise of the plugin LibsDisguises (8.6.8), I get [this](https://hastebin.com/puxojodogo.md) error on console, and my player goes to its first position. It only allows me to fly up and down. But no other moves are allowed. I am using LuckPerms 3.4.60 in BungeeCord build 1278 and Spigot 1.8.8. Since I get that error printed out, I thought that it had to do a thing with this plugin. Thanks for your time.

**Comment by Andre601** [comment]
Check the permissions of the user/group and maybe run the [verbose-command](https://github.com/lucko/LuckPerms/wiki/Verbose), to find out, what exact permissions you're needing.

**Comment by lucko** [comment]
Looks like LibsDisguises is trying to remove an empty permission to a player.  (just a string with length 0 - `""`)

This isn't allowed by LP.

I've changed the Vault impl to throw an exception sooner if this is the case, so you can trace exactly where the call is from.
