### ISSUE TITLE
Ability to cost to rank up a ladder

### ISSUE THREAD

**Issue by tyler489** [lucko/LuckPerms#527]
Would it be possible to add a cost option to lp promote?

**Comment by Andre601** [comment]
Just search for a Auto-Rank-plugin, that can make that.
LuckPerms is only for creating and managing permission-groups, not for using it with economy.

**Comment by tyler489** [comment]
They only sponge compatible autorank that i saw was discontinued and it only supports time. Do you have a autorank that wokjs with spongeforge?

**Comment by lucko** [comment]
This is out of scope for a permissions plugin.

My suggestion is to create a post on the Sponge forums asking for suggestions, or to see if someone feels like making such a plugin. :)

**Comment by tyler489** [comment]
back to the origional plan of using nucleus kits to run the promote command till i get a dev to work on it i guess. thanks anyway
