### ISSUE TITLE
User clone/transfer command.

### ISSUE THREAD

**Issue by voodootje0** [lucko/LuckPerms#530]
Would it be possible to add a `/lp user <user> clone <clone user>` command or/and a `/lp user <user> transfer <new user>` account?

This would be really useful 😄

**Comment by Andre601** [comment]
For what should that be good?

**Comment by voodootje0** [comment]
For account transfer between users, if someone sells their account, for cracked servers if someone changed their name and if you got a new staff/owner that had specific permissions you want to transfer directly.

**Comment by spannerman79** [comment]
> For account transfer between users, if someone sells their account, for cracked servers if someone changed their name and if you got a new staff/owner that had specific permissions you want to transfer directly.

That is what a group is used for.  No need to "transfer" permissions, just add/remove the group that holds the needed perms.

**Comment by lucko** [comment]
I see the benefit in this as a command -- so although the discussion is appreciated, it's definitely something which I plan to add. 😄

**Comment by voodootje0** [comment]
> That is what a group is used for. No need to "transfer" permissions, just add/remove the group that holds the needed perms.

I'm talking about that the transfer command should transfer all specific user group and permissions.
As an example, a player has 3 different ranks and more than 20 permissions (as an example from unlocked abilities to unlocked kits and even prestiges), and to transfer that by hand it's confusing and will take time.
