### ISSUE TITLE
Per server prefixes

### ISSUE THREAD

**Issue by christophe6** [lucko/LuckPerms#531]
Hi

I was trying to setup per server prefixes. I did this:
/lp group snul meta addprefix 100 &8(&r&eSnul&r&8)&7 server=harrypotter
I changed the server name in the config to harry potter and /lp user Christophe6 returns that I have the right prefix. But when I use essentialschat and vault, it returns just Member... How can I solve this?

**Comment by spannerman79** [comment]
> But when I use essentialschat and vault, it returns just Member

Use EssentialsXChat, not essentialschat
The "Member" is a config setting in Essentials - not to do with Luckperms.  Check your Essentials config.

**Comment by christophe6** [comment]
I am using essentialsxchat. The permissions do perfectly work for global ranks...

**Comment by lucko** [comment]
Are you sure your prefixes are being pulled from LP, and not just the Essentials config file?

What is `use-vault-server` set to in your LP config?
