### ISSUE TITLE
When a player dies, he losses his permissions

### ISSUE THREAD

**Issue by MrLunch** [lucko/LuckPerms#532]
As the title says... when a player dies... he had to write something in the chat to have his perms/prefix back .-.

**Comment by lucko** [comment]
Can you give an example of this happening?

Whether a player is dead/alive has no impact on permission checks.

**Comment by MrLunch** [comment]
Ok, I was playing with my friends and one of them fell and died (He was in the group Member)... When he respawned, I saw the TAB and he was without his prefix, so when he tried to do /back to get his stuff back, it said he didn't have permission but I saw the Group file and it the group Member had permission to do /back, so I told him to write something in the chat and as soon as he wrote something in the chat, His prefix returned and he could do /back

**Comment by lucko** [comment]
I've never experienced this issue before myself, and haven't had any other reports of it occurring.

On a purely technical level, it couldn't happen - LuckPerms doesn't care about whether your player is alive or dead.

I need specific steps to reproduce this before I can even attempt to diagnose the issue. Perhaps it was a coincidence with another issue occurring at the same time?

Going to close this for now -- as there's not enough information for me to actually do anything.

**Comment by dunaland1** [comment]
I have the same problem now

**Comment by dunaland1** [comment]
But Players have their commands they just lose the prefix in TAB

**Comment by lucko** [comment]
Update to the latest version.
