### ISSUE TITLE
LuckPerms for Bungeecord

### ISSUE THREAD

**Issue by AdvancedGP** [lucko/LuckPerms#533]
Luckperms has bungeecord support. so i would like to ask a few questions:

1. Can i just have luckperms in my bungeecord plugins folder and not the bukkit/spigot plugin folders?

2. In the config, you have "Server: global", here i can make it global for all servers, or i can specifiy which server i want the perms to work in, what if i wanted to do both? have some perms added globally, and some that arent. should i just copy and paste the whole thing and paste it below the current one?

**Comment by MWFIAE** [comment]
1. No unfortunately a bungee plugin can't provide permissions for a bukkit server. So you need the right plugin on all of your servers+proxy

2.  server: global is just the servername this specific server should have. 

So you would do something like. 
server:server1
And all permission that have as server global or server1 would be applied on this server. 
So you can already do both! please don't copy the config, that's not how this configs work^^ :)


Hope it is clear what I meant. Feel free to ask again if something is unclear.

**Comment by AdvancedGP** [comment]
Are you saying that if i had every single bukkit/spigot luckperms config say "Server: global (or anything)" INCLUDING the bungeecord luckperms config, all perms in the bungeecord luckperms config would send perms network-wide, while the bukkit/spigot luckperms config will have its own perms including the bungee ones?

**Comment by MWFIAE** [comment]
First of all, if you do want to share permissions you probably shouldn't be using permission files, but instead a database. (eventhough you could symlink the files, but most likely you don't want that).
Unless all your servers are pointing to the exact same source the permissions wouldn't be shared at all.


Ok, so here's an example setup

bungee: 
server:proxy

bukkit1:
server:server1

bukkit2:
server:server2

bukkit3:
server:server3

You create a bunch of permissions:
/luckperms user Luck permission set luckperms.info true server=global
/luckperms user MWFIAE permission set luckperms.info true server=server1
/luckperms user AdvancedGP permission set luckperms.info true server=server1
/luckperms user AdvancedGP permission set luckperms.info true server=server2

Luck would have the permission on all servers (including bungee). 
I would have the permission only on server 1.
You would have the permission on server1 and server2, but not on server3 or on the bungeecord.

**Comment by AdvancedGP** [comment]
Aha! thank you so much

**Comment by Andre601** [comment]
I will quickly give some small infos, even if the questions are already answered.

1. The BungeeCord-version of LuckPerms is only for managing permissions of BungeeCord-plugins.
You need to have the normal LuckPerms on your spigot-servers, to manage the "normal" permissions.
1. You can give server-specific permissions, by adding world=<servername> at the end of the setpermission command. This is only for LuckPermsBungee, because the servers are worlds for that plugin.
You can find out, what the name of the server is, by using `/lpb user <user> info` and looking at the context-section.

**Comment by lucko** [comment]
One closing comment:

All of your questions were (kinda) answered on the FAQ page - there might be some additional info on the topic there which you may find helpful.

https://github.com/lucko/LuckPerms/wiki/FAQ

Thanks @Andre601 @MWFIAE for your replies :)

**Comment by LegacyMC** [comment]
i have the same problem can someone tell it me in the dutch
