### ISSUE TITLE
All groups and users disappeared.

### ISSUE THREAD

**Issue by AdvancedGP** [lucko/LuckPerms#535]
i migrated from pex, luckperms was working fine at the time but when i unloaded pex, every group seems to have disappeared saying it cannot be found, this is the same for users, where i type in my own name like /lp user AdvancedGP meta info, it says this user cannot be found. if i try to create a group it says there was an error.

**Comment by lucko** [comment]
Can you provide a log of your console when it says there was an error.

**Comment by AdvancedGP** [comment]
When i do /lp user AdvancedGP meta:

`07.11 12:35:19 [Server] INFO AdvancedGP issued server command: /lp user AdvancedGP meta
07.11 12:35:19 [Server] WARN org.h2.jdbc.JdbcSQLException: Database may be already in use: null. Possible solutions: close all other connection(s); use the server mode [90020-196]
07.11 12:35:19 [Server] WARN at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
07.11 12:35:19 [Server] WARN at org.h2.message.DbException.get(DbException.java:168)
07.11 12:35:19 [Server] WARN at org.h2.mvstore.db.MVTableEngine$Store.convertIllegalStateException(MVTableEngine.java:188)
07.11 12:35:19 [Server] WARN at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:168)
07.11 12:35:19 [Server] WARN at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:100)
07.11 12:35:19 [Server] WARN at org.h2.engine.Database.getPageStore(Database.java:2476)
07.11 12:35:19 [Server] WARN at org.h2.engine.Database.open(Database.java:697)
07.11 12:35:19 [Server] WARN at org.h2.engine.Database.openDatabase(Database.java:276)
07.11 12:35:19 [Server] WARN at org.h2.engine.Database.<init>(Database.java:270)
07.11 12:35:19 [Server] WARN at org.h2.engine.Engine.openSession(Engine.java:64)
07.11 12:35:19 [Server] WARN at org.h2.engine.Engine.openSession(Engine.java:176)
07.11 12:35:19 [Server] WARN at org.h2.engine.Engine.createSessionAndValidate(Engine.java:154)
07.11 12:35:19 [Server] WARN at org.h2.engine.Engine.createSession(Engine.java:137)
07.11 12:35:19 [Server] WARN at org.h2.engine.Engine.createSession(Engine.java:27)
07.11 12:35:19 [Server] WARN at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:354)
07.11 12:35:19 [Server] WARN at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
07.11 12:35:19 [Server] WARN at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:100)
07.11 12:35:19 [Server] WARN at org.h2.Driver.connect(Driver.java:69)
07.11 12:35:19 [Server] WARN at java.sql.DriverManager.getConnection(DriverManager.java:664)
07.11 12:35:19 [Server] WARN at java.sql.DriverManager.getConnection(DriverManager.java:270)
07.11 12:35:19 [Server] WARN at me.lucko.luckperms.common.storage.backing.sql.provider.FlatfileProvider.getConnection(FlatfileProvider.java:73)
07.11 12:35:19 [Server] WARN at me.lucko.luckperms.common.storage.backing.sql.provider.H2Provider.getConnection(H2Provider.java:32)
07.11 12:35:19 [Server] WARN at me.lucko.luckperms.common.storage.backing.sql.SQLBacking.getUUID(SQLBacking.java:1042)
07.11 12:35:19 [Server] WARN at me.lucko.luckperms.common.storage.AbstractStorage.lambda$getUUID$17(AbstractStorage.java:260)
07.11 12:35:19 [Server] WARN at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
07.11 12:35:19 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
07.11 12:35:19 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
07.11 12:35:19 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
07.11 12:35:19 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
07.11 12:35:19 [Server] WARN at java.lang.Thread.run(Thread.java:745)
07.11 12:35:19 [Server] WARN Caused by: java.lang.IllegalStateException: The file is locked: nio:/plugins/LuckPerms/luckperms-h2.mv.db [1.4.196/7]
07.11 12:35:19 [Server] WARN at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:765)
07.11 12:35:19 [Server] WARN at org.h2.mvstore.FileStore.open(FileStore.java:168)
07.11 12:35:19 [Server] WARN at org.h2.mvstore.MVStore.<init>(MVStore.java:347)
07.11 12:35:19 [Server] WARN at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2930)
07.11 12:35:19 [Server] WARN at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:155)
07.11 12:35:19 [Server] WARN ... 26 more
07.11 12:35:19 [Server] WARN Caused by: java.nio.channels.OverlappingFileLockException
07.11 12:35:19 [Server] WARN at sun.nio.ch.SharedFileLockTable.checkList(FileLockTable.java:255)
07.11 12:35:19 [Server] WARN at sun.nio.ch.SharedFileLockTable.add(FileLockTable.java:152)
07.11 12:35:19 [Server] WARN at sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1108)
07.11 12:35:19 [Server] WARN at org.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
07.11 12:35:19 [Server] WARN at java.nio.channels.FileChannel.tryLock(FileChannel.java:1155)
07.11 12:35:19 [Server] WARN at org.h2.mvstore.FileStore.open(FileStore.java:165)
07.11 12:35:19 [Server] WARN ... 29 more`

**Comment by lucko** [comment]
You have more than one server instance running, all reading from the same H2 database file.

You need to kill the extra java processes, then restart your server.

**Comment by MWFIAE** [comment]
As you're using a bungee setup I would recommend using a traditional sql-server, like mysql (mariadb).

**Comment by AdvancedGP** [comment]
at the moment i haven't yet connected it to bungee-cord, im just checking it out on 1 server. also i dont know how to kill the extra java processes since they dont exist anymore (past server host services expired)
