### ISSUE TITLE
command.*

### ISSUE THREAD

**Issue by arturek1666** [lucko/LuckPerms#539]
Is it possible to do: for example
- test.*:
value: true
and then:
- test.chat.red
value: false
And then a player can access all commands part from chat red?. When I try with essentials for example
- essentials.*
value: true
and then
- essentials.hat
value: false
player can still access /hat is there a way to block that?

So even if a command has a value: false the command still works. Is there a way to fix this?

I also put this message on Discussion page

**Comment by lucko** [comment]
Update to the latest build of EssentialsX from here https://ci.akpmakes.tech/job/EssentialsX/

This issue occurs because Essentials falls back on it's own config if a known permission plugin isn't installed. It should be fixed in the latest build from that link.

**Comment by arturek1666** [comment]
I just give exmaple however the problem is in this
- cmi.colors.privatemessage.darkred:
    value: false
- cmi.colors.publicmessage.darkred:
    value: false
- cmi.colors.privatemessage.*:
    value: true
- cmi.colors.publicmessage.*:
    value: true

This is an CMI plugin

**Comment by lucko** [comment]
In this case, the false permissions will override the wildcards.

Please show me examples with LP verbose & screenshots of your permissions data if this isn't occurring.

**Comment by arturek1666** [comment]
https://gist.github.com/anonymous/c30bda01bf42e7aa6c6cb73f53fba341

My goal was to make so premium player can write in all colours but not in red. On the log, it doesn't even show the permission:
- cmi.colors.privatemessage.darkred:
    value: false
- cmi.colors.publicmessage.darkred:
    value: false
If I would remove the cmi.colors.publicmessage.* and just change the permission: cmi.colors.privatemessage.darkred to a true player will be able to write in red. So all these permissions are correct.
