### ISSUE TITLE
Server crashing

### ISSUE THREAD

**Issue by TheIdioticOtaku** [lucko/LuckPerms#540]
I downloaded this plugin for my server so that everyone who isn't an admin can use certain commands, but my server keeps crashing since I added it. Here are the latest 3 crash logs.
[crash-2017-11-09_17.15.24-server.txt](https://github.com/lucko/LuckPerms/files/1459534/crash-2017-11-09_17.15.24-server.txt)
[crash-2017-11-09_17.18.48-server.txt](https://github.com/lucko/LuckPerms/files/1459535/crash-2017-11-09_17.18.48-server.txt)
[crash-2017-11-09_17.21.15-server.txt](https://github.com/lucko/LuckPerms/files/1459536/crash-2017-11-09_17.21.15-server.txt)

**Comment by Andre601** [comment]
1. Use next-time something like [hasetbin](https://hastebin.com) or [Gist](https://gist.github.com/)
1. Are you using the right version of LuckPerms?
I can see, that your server uses sponge. right? Download the right version from the [Jenkins-page](https://ci.lucko.me/job/LuckPerms/)

**Comment by TheIdioticOtaku** [comment]
Okay thanks! It seems that the plugin wasn't the cause of the crash I believe. I have a friend trying to help me figure out the real source, the plugin was working finely before my server started crashing. I'll use Gist next time, thanks for the tip! c:
