### ISSUE TITLE
Prefixes

### ISSUE THREAD

**Issue by Swiggo** [lucko/LuckPerms#541]
Prefixes Arent working

**Comment by Andre601** [comment]
1. Do you use LuckPerms for spigot or BungeeCord?
1. If you use it on spigot: Is Vault and a ChatPlugin like EssentialsXChat (not the normal one) or DeluxeChat installed?
1. Did you read [this page](https://github.com/lucko/LuckPerms/wiki/Prefixes,-Suffixes-&-Meta#displaying-prefixes-and-suffixes)?
80% of problems like this could be easily solved, if you would read the wiki...
