### ISSUE TITLE
Bungeecord errors.

### ISSUE THREAD

**Issue by voodootje0** [lucko/LuckPerms#544]
After a few hours of online time this bungeecord starts to give errors and resulted that redis bungee has stopped working.

https://pastebin.com/64PYg7LN

Version: LuckPerms-Bungee-4.0.5

**Comment by lucko** [comment]
Something is null on this line

https://github.com/lucko/LuckPerms/blob/master/bungee/src/main/java/me/lucko/luckperms/bungee/listeners/BungeePermissionCheckListener.java#L56

Either `plugin`, `getUserManager()` or `getUuidCache()`.

Are you reloading the plugin, or something like that? There's no reason why those instances would suddenly become null during the runtime of the plugin, unless it was disabled.

**Comment by voodootje0** [comment]
Nope, we didn't reload anything related. It just happened out of nowhere.

**Comment by lucko** [comment]
Not sure what to suggest then. No reason for any of that to be null, it's not reassigned during the runtime of the server.

**Comment by voodootje0** [comment]
The issue didn't happen the last days, so strange. Probably issue on our side.
