### ISSUE TITLE
Need compatibility with sponge API4

### ISSUE THREAD

**Issue by lnik801l** [lucko/LuckPerms#546]
Hello dear developer. Can you please make your plugin for api4? I want to make a minecraft server at version 1.8.9 and I really need luckperms

**Comment by lucko** [comment]
Simple answer is no - sorry.

Sponge doesn't support these versions anymore . They aren't even available for download anymore. The oldest available builds are for API 5.2.

https://www.spongepowered.org/downloads/spongeforge/stable/1.10.2
