### ISSUE TITLE
Prefix

### ISSUE THREAD

**Issue by AliTheSenpai** [lucko/LuckPerms#547]
Prefixes wont work at all

**Comment by lucko** [comment]
Read #541

You're going to need to actually give some information if you want help resolving the issue.

**Comment by AliTheSenpai** [comment]
The prefix ingame wont show? You can join my server: 107.175.106.232:25579 and check

**Comment by lucko** [comment]
You need to install a chat formatting plugin.

https://github.com/lucko/LuckPerms/wiki/Prefixes,-Suffixes-&-Meta

**Comment by AliTheSenpai** [comment]
I have essentials chat and chatcontrol wont work either way

**Comment by Andre601** [comment]
EssentialsChat or EssentialsXChat?
Also Vault is required, if it is a spigot/bukkit-server

**Comment by AliTheSenpai** [comment]
EssentialsChat-2.x-SNAPSHOT

**Comment by DeathVirus** [comment]
Try EssentialsXChat. I've heard EssentialsChat doesn't work

**Comment by AliTheSenpai** [comment]
Can i have a link?

**Comment by Andre601** [comment]
Use EssentialsX and EssentialsXChat, which both can be found on the [Jenkins-page](https://ci.akpmakes.tech/job/EssentialsX/)

**Comment by AliTheSenpai** [comment]
Still not working?
