### ISSUE TITLE
Prefixes

### ISSUE THREAD

**Issue by AliTheSenpai** [lucko/LuckPerms#548]
Prefixes wont work for me? The prefixes wont show at all in chat, i use essentialsX chat. My prefix https://gyazo.com/872869eadd2e8f3bfbbc2bdbdc718baa

**Comment by Andre601** [comment]
#547

**Comment by AliTheSenpai** [comment]
It wont work at all

**Comment by Andre601** [comment]
Did you read the following Wiki-pages?
https://github.com/lucko/LuckPerms/wiki/FAQ#im-using-essentialschat-and-its-not-working
https://github.com/lucko/LuckPerms/wiki/Prefixes,-Suffixes-&-Meta#displaying-prefixes-and-suffixes

**Comment by AliTheSenpai** [comment]
Ye

**Comment by merjilin** [comment]
Do you have vault installed on your server? And give us the *exact* name of your EssentialsX and EssentialsXchat please.

**Comment by AliTheSenpai** [comment]
EssentialsX-2.0.1 (3).jar
EssentialsXChat-2.0.1.jar
And yes i have vault

**Comment by merjilin** [comment]
Can you make sure they're from this build server please. There was an issue with another EssentialsX-2.0.1, which bizarrely stopped the prefixes working. https://ci.akpmakes.tech/job/EssentialsX/

**Comment by AliTheSenpai** [comment]
Their from that build yes

**Comment by Ryan-Haytree** [comment]
I've just tested this myself, and it works correctly.
Chat output:
![image](https://user-images.githubusercontent.com/31384792/32985228-ca1e42bc-ccad-11e7-9222-123b289ecf50.png)

`/lp user merjilin info` output:
![image](https://user-images.githubusercontent.com/31384792/32985231-e2b20836-ccad-11e7-8bf7-08a252919df3.png)

Jar files being used are:
[EsseentialsXChat format test.zip](https://github.com/lucko/LuckPerms/files/1485064/EsseentialsXChat.format.test.zip)

**Comment by FaZz129** [comment]
im having the same problem and im using the same essentials chat, except mine just shows me as member in the chat like something else is prefixing it

**Comment by lucko** [comment]
Then perhaps you have a different chat plugin which is overriding LP or Essentials?

**Comment by lucko** [comment]
Anyhow, this is very unlikely to be an LP issue. I'm going to close this ticket for that reason.
