### ISSUE TITLE
gamerule keep inventory

### ISSUE THREAD

**Issue by Cracks777** [lucko/LuckPerms#549]
i no longer keep my inventory since i started using this plugin how do i fix this?

**Comment by BrainStone** [comment]
Can you verify that the game rule is still turned on?

Also try debugging it with the verbose feature.

**Comment by lucko** [comment]
LuckPerms doesn't query or set gamerules.

Unless you have another plugin which sets gamerules based on permissions, this issue has nothing to do with LP.
