### ISSUE TITLE
Improve permissions debug

### ISSUE THREAD

**Issue by bloodmc** [lucko/LuckPerms#55]
So the current command of debug is a bit confusing since you do the following

/lp verbose true filter
/lp verbose false filter

Setting verbose to true sends the output to player chat and setting it to false does not. However, with the word "verbose", to me it sounds like if it is false it should be outputting to a log and if true it redirects to player chat. Perhaps there should be another command to turn perm debug on which would send ALL output to a logfile/console by default. If a user wanted it to be verbose(sent to chat), they could turn it on.

So something like

/lp permdebug on filter
/lp verbose true (sends to chat but remains logging to log file)
/lp verbose false (disables chat messages)
/lp permdebug false (disables all debugging)

**Comment by inklit** [comment]
it would be nice if UUIDs were shown in the verbose log too.
