### ISSUE TITLE
how to synchronize bungee cord permissions on luckperms?

### ISSUE THREAD

**Issue by JaoPedronull** [lucko/LuckPerms#550]
how to synchronize bungeecord permissions on luckperms?

**Comment by Andre601** [comment]
Read
https://github.com/lucko/LuckPerms/wiki/FAQ#where-do-i-install-luckperms
https://github.com/lucko/LuckPerms/wiki/FAQ#can-i-just-install-luckperms-on-bungeecord
and maybe https://github.com/lucko/LuckPerms/wiki/FAQ#how-do-i-get-permissions-to-sync-across-multiple-servers and https://github.com/lucko/LuckPerms/wiki/Network-Installation

**Comment by ToxicMushroom** [comment]
Just connect to the same database and use /lpb sync and /lp sync

**Comment by MWFIAE** [comment]
`/lp networksync` to synchronize the whole network, but with bungee messages configured you don't even have to, as it will be synchronized automagically ;)

**Comment by JaoPedronull** [comment]
Will this work between the permissions within the bungeecord config.yml and luckperms?

**Comment by Andre601** [comment]
You can enable the following option in the config.yml of LuckPerms-Bungee, to apply permissions and groups from the BungeeCord-config:
https://github.com/lucko/LuckPerms/blob/master/bungee/src/main/resources/config.yml#L160
