### ISSUE TITLE
Exception on load

### ISSUE THREAD

**Issue by FireFliesMC** [lucko/LuckPerms#553]
I recently installed the latest update of LuckPerms and I can't seem to get it working.

I refreshed the config and dependencies in the lib folder, but it still won't load correctly using the YAML file format.

This is the exception I receive:
https://hastebin.com/ocemokeweh.md

This is my config:
https://hastebin.com/oqudovahew.coffeescript

**Comment by lucko** [comment]
Update to the latest dev build. This is already fixed.

https://ci.lucko.me/job/LuckPerms/
