### ISSUE TITLE
enable-ops: true

### ISSUE THREAD

**Issue by Noudux** [lucko/LuckPerms#554]
# If the vanilla OP system is enabled. If set to false, all users will be de-opped, and the op/deop
# commands will be disabled.
enable-ops: true

In older versions when I set enable-ops to false then it's possible to give myself OP in the console.

In version 4.0.19 when I set this option to false it's not possible to give myself OP in the console. I take a message in the console calls "23.11 14:25:49 [Server] INFO The vanilla OP system is disabled on this server."

What do I wrong?

**Comment by MWFIAE** [comment]
Why would you set enable-op to false if you want the op-system to be enabled?

**Comment by Noudux** [comment]
So it's not possible to do it ingame only by using in console.

**Comment by lucko** [comment]
The previous behaviour where it was possible in console was a bug. :)

If you want op functionality with `enable-ops` set to false, then you should use the autoop permission system.
