### ISSUE TITLE
DeluxeChat Expantion Issue.

### ISSUE THREAD

**Issue by MaximumDesigns** [lucko/LuckPerms#557]
Hello there.

After contacting DeluxeChat support via their Discord chat, they informed me it was an error on your behalf. If you could please look into this, it'll be most appreciated 👍 

https://hastebin.com/wozujuhoyi.vbs
http://prntscr.com/hej68v

**Comment by lucko** [comment]
Please update LuckPerms and the LuckPerms expansion to the latest versions.

**Comment by MaximumDesigns** [comment]
Hi there.

On latest update, and happened again.
https://hastebin.com/utixiqucoy.vbs

**Comment by lucko** [comment]
You didn't update the LP expansion.
