### ISSUE TITLE
Luckperms not syncing right

### ISSUE THREAD

**Issue by FaZz129** [lucko/LuckPerms#559]
So I have luckperms on my bungee network and on the hub it will show me as coowner but when i go to survival it changes me to Helper and I have to manually fix it. It does this for my other staff aswell and when i do /networksync it doesnt fix it

**Comment by MWFIAE** [comment]
Then how exactly do you fix it manually? 
Have you read the wiki about bungeecord setup? 
Are all your configs pointing to the same permission source? (the same mysql database for example or the same file on the filesystem)

**Comment by FaZz129** [comment]
I fix it by having to change my role on that server to what it should be.
But when i also try to set it now it says there is an error saving the data and just resets me to default

**Comment by FaZz129** [comment]
I use mariadb now aswell and thats when it started to say it cant save the data

**Comment by FaZz129** [comment]
yep. i have the config all setup properly. Ive used it before but my server went down for a bit and we had to reinstall things and redo configs and thats when it started happening. Its also the start of the cant save data

**Comment by BrainStone** [comment]
Check if the storage type is MySQL on all servers. Also verify that the bungee mode is turned on on all spigot servers.

**Comment by FaZz129** [comment]
im using it on 2 of my servers as a test and they all follow that

**Comment by lucko** [comment]
Sounds like ip forwarding isn't setup correctly.

Please check through these steps for each of the servers in your network.
https://github.com/lucko/LuckPerms/wiki/Network-Installation#pre-setup

**Comment by merjilin** [comment]
Can you show us `/lp user <your username> info` on both of the servers please.

**Comment by merjilin** [comment]
Bugger! Just missed it xD

**Comment by FaZz129** [comment]
[![Screenshot from Gyazo](https://gyazo.com/64964c93734fd08f9215f1d8207d4533/raw)](https://gyazo.com/64964c93734fd08f9215f1d8207d4533)
[![Screenshot from Gyazo](https://gyazo.com/64964c93734fd08f9215f1d8207d4533/raw)](https://gyazo.com/64964c93734fd08f9215f1d8207d4533)

**Comment by FaZz129** [comment]
while i thank you for closing it there is still the question for why it wont allow me to save lucko. my survival server allows the prefix but my hub doesnt. i can get over it but if i cant change my rank or anyone elses from default whats the point

**Comment by lucko** [comment]
Please read my previous message.

**Comment by FaZz129** [comment]
but my ip forwarding has never had a problem for the about whole 2 years my server has been up for

**Comment by FaZz129** [comment]
lucko you may be right. my config files for my servers are gone and they wont regen. How can i fix this

**Comment by lucko** [comment]
Not sure, perhaps an issue with the filesystem permissions?

**Comment by FaZz129** [comment]
well ill try to fix that then the ipforwarding and if its still broken ill reopen but for now this is closed :P thank you
