### ISSUE TITLE
Using multiple servers in one command

### ISSUE THREAD

**Issue by popcorn9499** [lucko/LuckPerms#561]
So I'm currently trying to do something like this for the server entry (creative|creativeplus) and it seems that permissions that use that method for multiple in one permission dont seem to want to work. It was working previously and sadly im unsure as to when it worked exactly.

Using a global or single server permission does however seem to work
Versions
Minecraft 1.12.2
Spigot This server is running CraftBukkit version git-Spigot-3d850ec-f46ccd7 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
Luckperms 4.0.25 and 3.4.15 (was on previous version still doesnt work in the update

**Comment by lucko** [comment]
Glob or shorthand only works for permissions - not contexts (like servers).

Meaning, yes you can do things like `luckperms.(user|group).info`, but you can't do `server=(creative|creativeplus)`.

If you want to share permissions between two servers, the best thing to do is to create a new static context which is shared between them.

**Comment by popcorn9499** [comment]
Ok thank you sorry about that. Just was confused as it used to work. Anyways have a good day and thanks for the amazing plugin.
