### ISSUE TITLE
SSL-Spam

### ISSUE THREAD

**Issue by MineTim** [lucko/LuckPerms#563]
![screenshot_20171125-103527](https://user-images.githubusercontent.com/26803527/33229301-bcf05318-d1cc-11e7-9bca-8d670148d28d.png)

LuckPerms spams that messages in the console (without LP, it works)

Version: Bungee 1.12.2, LuckPerms 4.0.25

Thanks for helping!

Greetings
Minecraft_Tim

**Comment by spannerman79** [comment]
If you actually read the error message you would know it has nothing to do with Luckperms but with your mysql setup.

**Comment by lucko** [comment]
The error is printed by the MySQL driver, not LuckPerms.

**Comment by MineTim** [comment]
Can you adde a useSSL=false?

**Comment by MineTim** [comment]
G
![20171125_121602](https://user-images.githubusercontent.com/26803527/33229980-7712e6c2-d1da-11e7-841b-750175a82044.png)


Like jobs

**Comment by MineTim** [comment]
Thanks a lot!

**Comment by MineTim** [comment]
![screenshot_20171125-132708](https://user-images.githubusercontent.com/26803527/33230480-6ffe9570-d1e4-11e7-910a-89138ac10a46.png)

What did I wrong?

**Comment by lucko** [comment]
Try with the latest build

**Comment by MineTim** [comment]
Works fine - Thank you!!
