### ISSUE TITLE
MariaDB error

### ISSUE THREAD

**Issue by Max604** [lucko/LuckPerms#565]
Receiving this mariadb error only when using LuckPerms
```

[06:39:49 WARN]: [Craft Scheduler Thread - 686] WARN com.zaxxer.hikari.pool.PoolBase - luckperms - Failed to validate connection org.│··············································································
mariadb.jdbc.MariaDbConnection@6ec8ad85 (Connection.setNetworkTimeout cannot be called on a closed connection)                       │··············································································
```

**Comment by BrainStone** [comment]
Can you please verify that you entered valid MariaDB authentification data?  
Also when does this error happen? During startup or does it happen again and again?

**Comment by Max604** [comment]
Yes, it is the same information I have used for all other plugins that connect to the MariaDB database. This occurs every time there is an update to someone's permissions.

**Comment by lucko** [comment]
You might wish to tweak some of the connection pooling settings in the LP config, especially the ones nearer the end.
https://github.com/lucko/LuckPerms/blob/master/bukkit/src/main/resources/config.yml#L299-L326

LuckPerms delegates management of MySQL connections to HikariCP. You can see a bit more info about each of these options on their page here: https://github.com/brettwooldridge/HikariCP

The default options in the LP config are designed to work (and do work!) for the vast majority of users - however if you or your host have made changes to the SQL server config, then sometimes there are issues.
