### ISSUE TITLE
Permissions data couldn't be loaded!

### ISSUE THREAD

**Issue by S3nS3IW00** [lucko/LuckPerms#566]
The plugin in default settings kick all the players when join, with "Permissions data couldn't be loaded! Try again later!" message. Please fix it.

My server's version: 1.12.2
Serverfile: craftbukkit

**Comment by BrainStone** [comment]
Please enable `debug-logins` in the LP config and send us the log of the debug.

**Comment by Andre601** [comment]
You should switch to Spigot...

**Comment by merjilin** [comment]
Correct. This is a bug in craftbukkit, not luckperms. We're currently waiting for a fix on their side. For the time being, please switch to either spigot or paperspigot (I personally recommend paperspigot).

**Comment by merjilin** [comment]
If the issue persists after switching, please do as brainstone says, as well as send us your latest.log via gist.github.com.

**Comment by S3nS3IW00** [comment]
Ok, thanks, I try paperspigot.

**Comment by S3nS3IW00** [comment]
The plugin is not work in Spigot. I write a command in chat, and the plugin says me "Running LuckPerms v.4.0.18"

**Comment by S3nS3IW00** [comment]
Please fix the problem, and kompatible it for craftbukkit

**Comment by Andre601** [comment]
The message you get is normal, if you don't have permissions for LuckPerms.
Just give yourself `luckperms.*` through console and it should work...

Also reading the wiki solves a lot of problems.

**Comment by merjilin** [comment]
As for making it compatible with craftbukkit, we simply can't do that. We must wait for craftbukkit to implement the fix on their side, just like spigot and paperspigot have.

**Comment by merjilin** [comment]
Anyway, you should be good to go now. Just follow the directions laid out on the Usage section of the wiki. And if you need additional help regarding the setup of luckperms after reading the wiki page, I recommend you join our support discord. Support will be faster.

**Comment by lucko** [comment]
Regarding CraftBukkit + Offline Mode + LuckPerms, please see here:
https://github.com/lucko/LuckPerms/wiki/Setup#craftbukkit-and-offline-mode

Your other issues are addressed at the very start of the "Setup" wiki page. 🙂
