### ISSUE TITLE
permissions not shown for users group

### ISSUE THREAD

**Issue by smmmadden** [lucko/LuckPerms#567]
Migrating PermissionsEx to LuckPerms. World/Server Name: thehub  Version: 1.12.2
I've migrated PEX to LP and see the permission nodes added into "OwnerAdmin" and "TheWorld" Groups.  Reviewing the permissions shows the correct number of nodes for each.  My group "OwnerAdmin" reflects all the perms I should have PLUS I'm OP'd as level 4.  Everything appears normal.

User 1 called "Rubylady" is assigned "TheWorld" group and reflects that on the server console.  However, the only permissions recorded were the 4 permission nodes under her ID in permissions.yml and none of permission nodes from "TheWorld" are available even though she is in the right group.  All the other users have the same 4 permission nodes but not the primary groups nodes.
[Rubylady](http://www.takemetominecraft.com:8075/rubylady.png)
[smmmadden (me)](http://www.takemetominecraft.com:8075/smmmadden.png)
[The World Users](http://www.takemetominecraft.com:8075/theworldusers.png)
[The World Permssions](http://www.takemetominecraft.com:8075/theworldperms.png)
Let me know if you need anything further to troubleshoot. Thanks -Steve

**Comment by smmmadden** [comment]
I just figured out what's going on or at least I believe what it is.  When you have PermissionsEx setup where the permissions are added to "Default" which are shared to all users (default perms everyone needs) and in the same permissions.yml file at the bottom you have a Users section where you extend additional permission nodes to a user, the only perms that get migrated /lp migration permissionsex are the Users section.  The "Default" group is added and user is associated with the right group, all the permission nodes however are not available.   

One of two scenarios come to mind.  a) this is by design IF there is a Users section provided, everything else is ignored or b) the default migration is to get the User perms first and when the user logs in, only then do they get the "Default" Permission nodes or c) this is just a bug and a missed use case.

As for admin accounts where users are OP'd, I not only get assigned the OwnerAdmin Group, but I also get all the permission nodes that come with it which makes me think that (b) might be the case since I'm the only one logging into my test server.

Can you confirm what the logic is for the Migration in this use case?  If I need to move all the permission nodes down to a User level or remove the User section and manually add the nodes after, I can do that.  

Thanks -Steve

**Comment by lucko** [comment]
The permission info output only reflects the permissions a user or group has set **directly**. It does not consider inheritance.

Migration makes a complete copy of all of your PEX user & group data within LuckPerms.

Default groups work a bit differently in LP - all users are added to the group named "default" on login / if they have no other groups.
