### ISSUE TITLE
PostgreSQL failure to launch

### ISSUE THREAD

**Issue by VergilPrime** [lucko/LuckPerms#568]
http://paste.thezomg.com/25205/51184474/
org.postgresql.util.PSQLException: ERROR: syntax error at or near "MODIFY"
  Position: 31

Potential fix: https://github.com/lucko/LuckPerms/pull/569

**Comment by lucko** [comment]
Thanks for reporting - sorry it took a while to get a pushed.

**Comment by VergilPrime** [comment]
No worries!
