### ISSUE TITLE
Disable creation of new records in DB for BungeeCord

### ISSUE THREAD

**Issue by krusic22** [lucko/LuckPerms#570]
Currently if a player connects to Bungee he will get a new record (or read the old one) even if he later gets kicked by the lobby. Can you add a option that Bungee can only read player data (and modify existing data) but not create new users?

**Comment by BrainStone** [comment]
Why is this an issue?  
A player record doesn’t even take up 1 kB.

**Comment by lucko** [comment]
I'm assuming you're talking about the `luckperms_players` table here, and not the permissions one?

LP uses that table to perform UUID lookups - when you run a command to modify a user, those tables are used to find the uuid of the player. It has a specific purpose (it's not just there for the sake of it!), and therefore makes no sense to add an option to disable it - the plugin will not work correctly without the information provided by that table - you'd only be able to modify the data of online users.

It's not possible to delay the population of the table until later in the login process, as plugins which use permission data in login listeners expect the info to be ready immediately.

**Comment by krusic22** [comment]
Yeah I meant the luckperms_player because it's currently 12Mb... I guess I just have to write a function that clears unregistered users... 
Thank you anyway.

**Comment by lucko** [comment]
If you can't spare 12mb of disk space then it sounds like you you have bigger problems on your hands.

**Comment by krusic22** [comment]
It's not about the disk space used. But more about the concept of using the DB for no reason. If someone just bots the bungee server the DB will die way before bungee will due to all the requests that are mostly pointless.

**Comment by Andre601** [comment]
Then you need to use a AntiBot-plugin, that catches the bot on the PreLogin-Event (I guess...)
A recomendation is AntiBotDeluxeEX

**Comment by krusic22** [comment]
AntiBot will not help since it does way more then just a couple request to the DB (all the IP checks n stuff)

**Comment by lucko** [comment]
> If someone just bots the bungee server the DB will die way before bungee will due to all the requests that are mostly pointless.

Logins are handled by LP after authentication with Mojang - which prevents bot attacks.

> But more about the concept of using the DB for no reason.

I've already explained the purpose of the table.
