### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by SDpyro** [lucko/LuckPerms#571]
It would be nice to be able to set our own preference for pastebin and other type of exports.
for example /lp tree to go to a local file OR even a local pastebin equiv.

**Comment by lucko** [comment]
The tree and verbose paste outputs are in a special markdown/html form, which as far as I know can only be rendered by GitHub. 

There would be no point in saving it in a local form or to an alternative service as the markdown wouldn’t be rendered, and you wouldn’t be able to read or understand the output.

**Comment by BrainStone** [comment]
Also what’s wrong with Gist?
