### ISSUE TITLE
Players usernames are always "MongoDB" after migrating

### ISSUE THREAD

**Issue by Foorack** [lucko/LuckPerms#574]
Migrated from PermissionsEX. We use MongoDB as storage. If a player has not been online since migration and they are looked up by UUID then their username will show as "MongoDB".

We are running with BungeeCord. All servers have `online-mode=false` and `bungeecord: true`. BungeeCord has ip-forwarding enabled.

**Steps to reproduce:**

1. Setup a simple pex structure. Add a few groups and a few users to those groups.
2. Migrate to LP. `lp migration PermissionsEX`. Use MongoDB as backend storage.
3. Run info on a user who had been online before the migration but has not been online after. Look them up via UUID. `lp user <uuid> info`. Their username will then show as MongoDB.

![ekrankopio de 2017-11-30 11-09-04](https://user-images.githubusercontent.com/5008081/33425707-d7b37878-d5bf-11e7-83f7-26ba06e82211.png)
![ekrankopio de 2017-11-30 11-14-09](https://user-images.githubusercontent.com/5008081/33425708-d7d32dbc-d5bf-11e7-89cc-fc89bb79b603.png)

**Edit 1:** Added version data:

![ekrankopio de 2017-11-30 11-18-56](https://user-images.githubusercontent.com/5008081/33425854-4936bc94-d5c0-11e7-9b75-a924ce33e653.png)

**Comment by Foorack** [comment]
Pull request made. The name is set to the name of the database adapter rather than the stored name in the database.

**Comment by lucko** [comment]
whoooops

003ddc51def7ba232407ceedc3d605433918e567
