### ISSUE TITLE
Error 403

### ISSUE THREAD

**Issue by DarkFort** [lucko/LuckPerms#576]
https://hastebin.com/taqepohuqu.md
![image](https://user-images.githubusercontent.com/25278617/33453453-512b7e7c-d61e-11e7-87b5-2c5b7cf67985.png)

**Comment by lucko** [comment]
Your server needs to be able to access & communicate with `https://api.github.com/gists` to use the web editor.

The 403 Forbidden response code was returned when LuckPerms tried to post the data to that URL. Perhaps your host is blacklisted?

This isn't a LP issue.
