### ISSUE TITLE
Adding permissions for dummy command sender

### ISSUE THREAD

**Issue by abused** [lucko/LuckPerms#577]
Hi,
so im currently using the mod DiscordChat by shadowfacts, a problem however im running into is that when we use !exec kick <player> or such it'll go through as "you do not have permission to run this command", we cab run !exec fine but the bot does not have permission to actually execute the command, how can i go about giving an ICommandSender a permission?
"psst code for the dummysender is here"
https://github.com/shadowfacts/DiscordChat/blob/rewrite/1.10.2/src/main/java/net/shadowfacts/discordchat/one_ten_two/DummySender.java

**Comment by BrainStone** [comment]
You can try to test it with verbose active to see the permission checks happening and for whom they are checked

**Comment by BrainStone** [comment]
Also. It might make more sense to implement such a bot with the Sponge-API instead of implementing it as a Forge Mod.

**Comment by seethingword** [comment]
How do you do a verbose attack?

**Comment by BrainStone** [comment]
https://github.com/lucko/LuckPerms/wiki/Verbose

**Comment by seethingword** [comment]
I'll Give it a shot thanks

**Comment by seethingword** [comment]
So i tried a verbose attack and nothing came up but this showed in console
` [07:53:11] [JDA MainWS-ReadThread/WARN] [Sponge]: No entity type is registered for class net.minecraftforge.common.util.FakePlayer`
This is the verbose attack i ran
https://gist.github.com/anonymous/308560cdcb09132f212243fb4b8b08b2

**Comment by lucko** [comment]
This is a Sponge / DiscordChat issue if anything. If the checks aren’t being sent to LuckPerms, there’s nothing I can do.
