### ISSUE TITLE
Information does not update after bulkupdate

### ISSUE THREAD

**Issue by Foorack** [lucko/LuckPerms#579]
**Steps to reproduce:**
1. Setup a few groups with suffixes or other meta/information (with MongoDB as storage).
2. Bulk-remove all suffixes or any other information.
3. When running `lp group admin2 info` the old meta-data still shows. This is not updated until the command `lp sync` is run.

I am not certain if this is because of the MongoDB adapter or something else. Nor am I sure if this is supposed behavior. If so then it would be good to inform sync is required after a builk-update on the wiki. :smiley: 

Version:
![ekrankopio de 2017-12-01 13-04-40](https://user-images.githubusercontent.com/5008081/33482211-3a4cf44a-d698-11e7-9078-81f5fcc59535.png)

**Comment by Foorack** [comment]
From more testing, this seems to happen only on meta-data. Not on permissions. :thinking:

**Comment by Andre601** [comment]
Can you give more infos please?

`2. Bulk-remove all suffixes or any other information.` isn't a good explanation...
What exact command did you use?

**Comment by Foorack** [comment]
@Andre601 

1. `lp group admin2 meta info`
2. `lp bulkupdate groups delete "permission ~~ suffix.%"`
3. `lp group admin2 meta info`  <-- the same suffix still shows, I have to run `lp sync` for it to update.

**Comment by Andre601** [comment]
Did you try to use == instead of ~~?

**Comment by Foorack** [comment]
@Andre601 I don't understand how that would help. It updated successfully. The bug I am reporting is that the (what I assume) cache this not update. Running `lp sync` made it display the correct result, however, I think that bulkupdate should clear the cache automatically.
