### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by S3nS3IW00** [lucko/LuckPerms#581]
Hello dear Developers!

I want to set group to player with api, and add permission to player, but I don't find theese methods in API. What are the methods for this functions? Thanks for help!

**Comment by lucko** [comment]
You need to use `User#setPermission` to add the permissions / groups, and `LuckPermsApi#getNodeFactory`  to build the node instances.

**Comment by lucko** [comment]
Yeah, you can set an expiry on the node when you build it with the `Node.Builder` class.

**Comment by S3nS3IW00** [comment]
But the plugin only add the specified group permission, not add the group .

**Comment by lucko** [comment]
Group memberships are represented by permission nodes internally.
