### ISSUE TITLE
permission xxxxx set to undefined in context global

### ISSUE THREAD

**Issue by smmmadden** [lucko/LuckPerms#582]
Could you tell me why I would see the following?
lp user f098c794-f41a-4edd-a536-b638b26b748e permission checkinherits jobs
[LP] smmmadden has permission jobs set to **undefined** in context global. (inherited from self)

I have two groups (default and owneradmin).  OwnerAdmin inherits from default.
I'm using LuckPerms-Bukkit-4.0.18.jar on Spigot Server 1.12.2.

**Comment by smmmadden** [comment]
nevermind - I figured out that this means it isn't set to true or false and possibly not set at all.  The exact behavior of the permission/command may or may not work depending on the developers "default" value when not set which could be true or false.

**Comment by lucko** [comment]
On Bukkit, it also depends on whether the user is opped - but yes, you're quite right. :)
