### ISSUE TITLE
Commands Randomly Break

### ISSUE THREAD

**Issue by pinchcraft** [lucko/LuckPerms#584]
Commands always work up to /lp user (name)
However, after that, the command breaks
/lp user nick parent ... ...
This sometimes does not work. There is no message in console, no message in game, nothing happens. The only console message is default server saying ign ran /lp user (name) command. Nothing else happens and it randomly breaks. Is there any dependencies that I am missing? I have vault...

Commands just stop working. I have PaperSpigot 1.8.8, latest version of luckperms and vault. Luckperms will break randomly for a minute, then work for a minute, then break, etc.

I also have DeluxeMenus that uses LuckPerms to determine if a player has permission then what to display. Since LuckPerms is broken, this also breaks.

**Comment by pinchcraft** [comment]
Caused by: java.lang.NoSuchMethodError: me.lucko.luckperms.api.User.getUserDataCache()Ljava/util/Optional;

**Comment by lucko** [comment]
You're using an outdated version of the LuckPerms placeholder expansion.

**Comment by VreyaViress** [comment]
I'm using the last version: https://imgur.com/a/a0U5L

**Comment by lucko** [comment]
This error would only be caused by an outdated version of the expansion.

https://hastebin.com/dubicorewa.vbs
