### ISSUE TITLE
Tabprefix

### ISSUE THREAD

**Issue by BluetoDark** [lucko/LuckPerms#585]
#I would realy like if you make somthing where you can controll tabprefixes from rank + a option to change the max length of a tabprefix.

(sorry for the bad spelling I have dislexion)

**Comment by Andre601** [comment]
LP doesn't manage Tablists...
It all depends on your Tablist-plugin.

**Comment by lucko** [comment]
You need an extra plugin to format the tab - LuckPerms just provides the data.
