### ISSUE TITLE
Luckperms seems to be breaking everyting...

### ISSUE THREAD

**Issue by pinchcraft** [lucko/LuckPerms#594]
LuckPerms completely breaks
CrazyCrates stop working
DeluxeMenus "half" works. Every third time or so you try to click something in a menu, nothing happens.
CrazyEnvoy just says "OnGoing"
Genbuckets (custom plugin) stops working
RandomTP plugin breaks
Players warping without instant TP just can't teleport anymore.
MoneyPouches break

As soon as I remove LuckPerms, everything works.

Here is an error I run into: `[Server thread/INFO]: com.mojang.authlib.GameProfile@3b26ccb8[id=74d5cf6f-c583-4767-8c25-009ea2811b52,name=Greers4,properties={textures=[com.mojang.authlib.properties.Property@457f2a73]},legacy=false] (/197.**.***.***:*****) lost connection: §7§l[§b§lL§3§lP§7§l] §cPermissions data could not be loaded. Please try again later.`

I am using the latest version of LuckPerms, PaperSpigot 1.8.8

**Comment by lucko** [comment]
Please upload a copy of your servers most recent log file to https://gist.github.com/ and reply with the link.

**Comment by pinchcraft** [comment]
https://gist.github.com/pinchcraft/0b4b71ff2f892f56a98c22e6fc277164
Thanks for the fast response :P

**Comment by lucko** [comment]
Those failed login attempts were most likely because those players started to connect before LuckPerms had enabled.

**Comment by DarkFort** [comment]
Yes, at me too, there is not always work this or that plug-in or the permission. I have to redistribute the group to the player and then everything is fine.

**Comment by DarkFort** [comment]
What is that? https://hastebin.com/muluxarava.md

**Comment by lucko** [comment]
Try updating to the latest version.
https://ci.lucko.me/job/LuckPerms/
