### ISSUE TITLE
Incorrect display prefix

### ISSUE THREAD

**Issue by DarkFort** [lucko/LuckPerms#595]
Why, when I give more than three or four prefixes, is the chat shown before the last one?
lp user %player_name% meta addprefix 2 "&c&lO&3&lbey &6"
lp user %player_name% meta addprefix 2 "&d&lWither &6"
lp user %player_name% meta addprefix 2 "&9&lBoogie&a&lMan &6"
lp user %player_name% meta addprefix 2 "&8&lHerobrine &6"

**Comment by lucko** [comment]
If you want to display multiple prefixes, you need to use the stacking feature.

https://github.com/lucko/LuckPerms/wiki/Prefix-&-Suffix-Stacking

**Comment by DarkFort** [comment]
I need to display only one prefix, it does not matter what weight it is. I do not know how to do that.

**Comment by DarkFort** [comment]
for example, the player chose a prefix with a weight of 5, then chose a prefix with a weight of 2, then with a weight of 10. Display should be the last
