### ISSUE TITLE
LP Editor Permissions drop down missing all permission nodes

### ISSUE THREAD

**Issue by smmmadden** [lucko/LuckPerms#596]
The LuckPerms editor provides all the permissions in an ordered way by priority which is not ideal for an editor, but it does work. 

The top header where you can search for Permission, Expiry etc can be used to get a true sorted list of permissions or find one in the list. However, there appears to be two problems with using drop down.

The list is showing permissions (I'm assuming) that the list is both available to set, and already set which makes it a bit more difficult to know by looking which is or isn't set.  Adding a visual indicator (*, color or even a second column in the results) clearly showing which permission node is already set would be a plus!

The second problem with the Permission drop down is it does not list all the results for servers that use a lot of plugins.  One of my servers has 51 plugins from A - W, but there must be some limit restriction being imposed on the results. For mine, it stopped in the M's and I have many more after that.  It's possible that the query is limited to 500 results, which is fairly common for database apps but this list should always show all of them or include some pagination for performance reasons.

**Comment by lucko** [comment]
Make a ticket here: https://github.com/lucko/LuckPermsWeb
