### ISSUE TITLE
MySQL to vault/chat hook

### ISSUE THREAD

**Issue by kilian544** [lucko/LuckPerms#598]
I need a plugin to (obviously) format the messages with the group/prefix of the group the player is in. At first I installed them on a server with the luckperms data saved to MySQL. When formatting the chat the prefix (do not know about suffixes or any other chat variables) appers 'empty', where the prefix should be inserted it shows litterally nothing. Format would be: "(Groupprefix) Playername: Message", 'Groupprefix' would be replaced with: "", resulting in: "() Playername: Message."

Then deciding to write my own plugin for the ordeal I get it working perfectly, while testing it on a server with data on Flatfile. Fast forward to intalling it on the MySQL server it breaks, resulting in the same problem as described for the other plugins. Now it is notable I am running the server in a Bungee setup. I tried both the 'Bungee-Command' as the 'Server-Command' to set the groups and prefixes. I also tested with a 'plugin blank' server. And confirmed the data being in the MySQL database.

Is there anything known about this/can you confirm and ofcourse fix the issue on hand.

Thanks in advance,
Kilian Legters

**Comment by Andre601** [comment]
You need to have a Chatplugin like BungeeChat for your BungeeCord OR Vault and a Chatplugin like EssentialsXChat on your spigot-server.

LuckPerms doesn't format the chat at all. It only provides the prefixes/suffixes.

**Comment by kilian544** [comment]
Yes, ofcourse forgot to mention, I have indeed instaled the latest version of vault this along with a chatplugin as mentioned. I am trying to get the plugin working on a 'Server-High' level.

**Comment by lucko** [comment]
Does the correct value show when you use `/lp user <you> info` under Current Prefix?

**Comment by kilian544** [comment]
No, you are right it shows me not being in the actual group. It appears I removed the wrong entry from the MySQL database when I was testing the reason for the first plugin not working. The plugin is working with the intended behavior, my mistake, thank you!
