### ISSUE TITLE
PermissionAttachment some times doesn't work

### ISSUE THREAD

**Issue by prozhong** [lucko/LuckPerms#607]
https://github.com/NyaaCat/RPGitems-reloaded/blob/1.11/src/main/java/think/rpgitems/power/Power.java#L233
I use RPGItems and LuckPerms together

Sometimes after the RPGItems' item is used, the command bound to it won't work and player will see he has no permission

Most of time it works, but some time not

LuckPerms 4.0.11
I think the fix for #528  is included in my version

**Comment by lucko** [comment]
Try again with the latest build from Jenkins.

**Comment by prozhong** [comment]
OK I will give feedback in a few days

**Comment by lucko** [comment]
Feel free to reopen this issue when you have feedback. :)
