### ISSUE TITLE
NameTagEdit incompatibility?

### ISSUE THREAD

**Issue by Sikatsu** [lucko/LuckPerms#608]
When I promote someone along the track, the players nametag above the player and in the tablist doesn't get updated until I use /nte reload. This worked fine with PermissionsEX. Are you able to make this compatible?

**Comment by mikroskeem** [comment]
This must be done by the developers of NametagEdit.

Also that is why I made my own plugin to replace NametagEdit fully: https://github.com/StoneMain/Shortranks

**Comment by Sikatsu** [comment]
This plugin isn't available on spigot?

**Comment by mikroskeem** [comment]
No, but you can download jar from [Releases tab](https://github.com/StoneMain/Shortranks/releases)

**Comment by lucko** [comment]
Looks like someone has already pull requested the functionality. 
https://github.com/sgtcaze/NametagEdit/pull/161

It’s a shame to see things like that being rejected for the sakes of maintaining compatibility with ancient Java versions. Software has to move on at some point. 

I suggest you find a different plugin to use. @mikroskeem ‘s project looks like a great alternative. :)

**Comment by Sikatsu** [comment]
It doesn't seem to be a full replacement of NameTagEdit sadly. 
And as far as I know there isn't any good alternative available on Spigot.
I guess the other way around isn't an option?

**Comment by mikroskeem** [comment]
Define full replacement, I may implement things you'd like to have. Feel free to ask questions on Shortranks issue tracker.
