### ISSUE TITLE
Demote incorrect placeholders

### ISSUE THREAD

**Issue by Sikatsu** [lucko/LuckPerms#609]
I noticed that demoting a player along the track has some issues with the placeholders.

As seen here: http://prntscr.com/hnekk6

I think it should say ''Demoting <playername> along track ranks from villager to novice in context global.''

**Comment by lucko** [comment]
Thanks for reporting :)

**Comment by Sikatsu** [comment]
Better, but still different from promoting: http://prntscr.com/hnm5re

(The red arrow in the tracklist and capital in the names)
