### ISSUE TITLE
Bungee Permissions Issue

### ISSUE THREAD

**Issue by GMatrixGames** [lucko/LuckPerms#611]
Hello,
I am a dev for Enlightened Realms (FrediSaal's Server).
And I am having issues setting up bungeecord permissions for the servers
I set them, they are in MySQL, but I go to execute the command and it doesn't work.
I need a solution
Thanks!
GMatrixGames

**Comment by lucko** [comment]
The wiki is a good place to start if you're totally stuck.
https://github.com/lucko/LuckPerms/wiki/Network-Installation

You're going to need to provide more information if you want any further help.

Specifically:

1. Exactly what you're trying to achieve
2. What you've done so far
3. Examples of the above

**Comment by GMatrixGames** [comment]
I have tried to do this multiple times, but it seems to keep resetting the MySQL setting to h2 every time I restart multicraft, I have provided a password, username, and database name. I don't know what else to change

**Comment by BrainStone** [comment]
Be sure to change the storage type setting when the server is off
