### ISSUE TITLE
Ranks will not appear on every server

### ISSUE THREAD

**Issue by iSpoopy** [lucko/LuckPerms#613]
I have recently switched to using LuckPerms for my minecraft server, but have realised that the ranks don't appear on all of the servers (I'm using Bungeecord). How can I fix this? I have entered the mysql database on all of the servers and changed the storage type to mysql.

**Comment by merjilin** [comment]
Please ensure you have IP-Forwarding setup correctly on ever server. This means you must have `ip-forwarding` set to true in your bungeecord config, and have `bungeecord` set to true in your spigot.yml.

**Comment by Lmmb74** [comment]
@iSpoopy You must set `messaging-service` to `bungee` in both servers and BungeeCord LuckPerms config file. And your network must be setup as @merjilin said.

**Comment by lucko** [comment]
https://github.com/lucko/LuckPerms/wiki/Network-Installation
