### ISSUE TITLE
MariaDB Connection error

### ISSUE THREAD

**Issue by Quaiby** [lucko/LuckPerms#614]
`[16:23:04 WARN]: [com.zaxxer.hikari.pool.PoolBase] luckperms - Failed to validate connection org.mariadb.jdbc.MariaDbConnection@5b492719 (Connection.setNetworkTimeout cannot be called on a closed connection)`

I see this message pool-size times.
Password, port, username, privileges, Maria's server are OK.

PaperSpigot 1.12.2 (git-Paper-1256)
LuckPerms 3.4.15

And in /lp info Storage.Connected is true

**Comment by lucko** [comment]
You might need to tweak this setting in accordance with your database.
https://github.com/lucko/LuckPerms/blob/master/bukkit/src/main/resources/config.yml#L323-L326

The error itself is not being thrown by LuckPerms.
