### ISSUE TITLE
mismatch versions

### ISSUE THREAD

**Issue by augesrob** [lucko/LuckPerms#615]
It seems the LuckPerms has a mismatch between local version and spigot version which will cause Up2Date to always think there is an update available.

**Comment by lucko** [comment]
LuckPerms doesn't have an auto updater.

I think you might be getting confused with another plugin?

**Comment by GamerKing195** [comment]
Hey there, I'm the developer of [Up2Date](https://www.spigotmc.org/resources/up2date.49313/) the plugin that is having a slightly annoying bug with this specific plugin. Up2Date establishes a link between a plugin on the server and a plugin on the server and checks if the version strings are not-equal to see if there's an update. However with LuckPerms the latest version on Spigot, 4.0.18, appears as 4.0.10 ingame. This causes Up2Date to always think there is an update for LuckPerms when in reality it's always updated.

**Comment by lucko** [comment]
Nope - it correctly shows as `4.0.18` ingame.

![](https://luck.sh/26XGpaL8W2pOWEIt_IAJ5-huVrM=)

**Comment by GamerKing195** [comment]
You're quite right. Seems to be an issue with Spiget, I'll go talk to inventivetalent, thanks for your quick response time.
