### ISSUE TITLE
Assign multiple server names for specific permissions

### ISSUE THREAD

**Issue by voodootje0** [lucko/LuckPerms#618]
Would it be possible to assign multiple server names in the config? 
This would be really useful for development servers: to test both permissions as example factions and factions_dev and later you can easily bulk edit factions_dev to factions without any problems.
It will also be nice for child servers, like skywars_lobby and skywars itself.

**Comment by lucko** [comment]
Yes it's possible - you just need to use the separate contexts config.

https://github.com/lucko/LuckPerms/wiki/Context#defining-your-own-contexts
