### ISSUE TITLE
World specific permissions not working

### ISSUE THREAD

**Issue by PiggyPiglet** [lucko/LuckPerms#62]
Hi, I have this in my mysql, `{"global-hub/*":true,"prefix.5000.\u00267[\u00266Owner\u00267]":true}` and this is my config http://hastebin.com/ihadomiqoj.coffeescript

I cant get world specific permission to work :/ Owner should have * in Hub but it doesnt. The only way I have the permission is if im opped and no other permissions work either. I'm using spigot 1.10 and the latest luckperms.

**Comment by lucko** [comment]
Works for me. Need clear steps please.

Here's what I did:

1. Clean LuckPerms install
2. Named my main server world "test"
3. De-opped myself
4. Tried to use a permission - got denied
5. Ran `/lp user Luck permission set * true global aaaaa`
6. Tried to use a permission - got denied
7. Ran `/lp user Luck permission set * true global test`
8. Tried to use a permission - it worked

Not sure what you're doing wrong. Make sure you're running the latest version, and check with `/lp user <user> info` to ensure that LuckPerms is picking up the correct world name.

**Comment by PiggyPiglet** [comment]
World specific group permissions aren't working*
The world specific user ones work fine.

**Comment by lucko** [comment]
Again, can't reproduce.

Clean LuckPerms install:

1. Created group named test
2. Added regular permission to the group
3. Added myself to the group in a specific world.
4. Worked.

Then.

1. Created group named test
2. Added world specific permission to the group
3. Added myself to the group globally
4. Worked.
5. Added myself to the group in a specific world.
6. Worked.

I need specific steps, including screenshots of your "permission info" output for the users and groups in question.
