### ISSUE TITLE
MongoDB "Legacy UUIDs"

### ISSUE THREAD

**Issue by dbluk** [lucko/LuckPerms#620]
Maybe I'm completely missing something, but I was wondering why UUIDs in Mongo are stored as "Legacy UUID"? I'm trying to display staff members through my website accessing my LuckPerms MongoDB. Since some of the names in the database are "null" (due to converting from GM?), I'm trying to use UUIDs. However, when attempting to access the UUIDs, the only thing I can get is strange symbols/characters to display. I noticed that when converting the LUUIDs to JUUIDs in Robomongo it completely changed the contents of the LUUID to proper Minecraft UUIDs, but I still have no clue on how to get "LUUID" from the Database to a String containing the proper Minecraft UUID _(php5.6, mongodb driver | MC 1.8.8 Paperspigot, LuckPerms v3.3.13)_.

![wat](https://user-images.githubusercontent.com/34012699/34241471-d1804844-e5e3-11e7-994b-8a82eb75865c.gif)

Is there a specific way to access the Minecraft UUID in the LuckPerms MongoDB? Sorry for the bad explanation & if I missed something in the Wiki, just very confused.

**Comment by lucko** [comment]
Honestly: I'm not sure.

LuckPerms just passes a Java UUID object to the MongoDB driver, and it does the rest.

https://github.com/lucko/LuckPerms/blob/master/common/src/main/java/me/lucko/luckperms/common/storage/dao/mongodb/MongoDao.java#L297

I'm sure there is a way for you to decode this value in PHP, but I don't know how. :/

You'd have to dig around a bit and see how the Java driver converts the data.

Sorry I couldn't be of any more help. :(
