### ISSUE TITLE
Mod?

### ISSUE THREAD

**Issue by Sclane1** [lucko/LuckPerms#622]
Hello,

is there a chance that you can make LuckPerms as Mod for Forge?

I love LuckPerms, but i made me a Server with only Forge. And now i only can use mods.
I tested many Permission Plugins and other but LuckPerms is the best.

Thanks

**Comment by Nighko** [comment]
You could try to use Sponge. They have a  Forge powered version.

**Comment by lucko** [comment]
This ^

:)

**Comment by Sclane1** [comment]
Yeah, but when i integratet Sponge i get many Errors with different Mods and other things.
Its easyer when i can add a mod, that makes the same think like the plugin.

Is it not a idee for the future? A Mod (Server side only) that make the same?
Easyer to add and you have a bigger range of you PERFECT LuckPerms-Programm/Code

**Comment by lucko** [comment]
Quite possibly yes - I want to try to support the Sponge Ecosystem though.

**Comment by Sclane1** [comment]
sponge is nice but it need a easyer integration and better plugins, i think.
I tested a Sponge-Server 4 month ago, and we had many problems with the plugins and the Server-Ram.
it needs so many ram, i think

**Comment by BrainStone** [comment]
It has gotten considerably better recently.

Also I’m interested. Which mods are not compatible with Sponge-Forge?
