### ISSUE TITLE
Global Groups not transferring cross-server on Bungeecord network.

### ISSUE THREAD

**Issue by speddoman** [lucko/LuckPerms#623]
I've been trying to get LuckPerms to successfully transfer my Global Groups across my BungeeCord network. 
The MySQL database is setup and all servers connect, and even after making a change on say the 'Hub' server, it will not reflect that on my 'Survival' server even after doing /lp (network)sync.

I look in console and see no errors with LuckPerms as to even hint at what is going on and it is quite frustrating at this point.

**Comment by MWFIAE** [comment]
How are you setting the permissions? With command? Then did you specify server global as context?

**Comment by speddoman** [comment]
Everything is already in global context since I set it up so I would just have to negate certain permissions for each server. I'm setting permissions via command such as /lp user speddoman promote staff, and it would show **this message (view attached)** https://gyazo.com/ee4f58856e64b88e7115dff92e2dac6e. 
All is fine and I switch to that group on that server, but when I then switch to my Survival server which is connected via the same MySQL database, it doesn't change.

**Comment by MWFIAE** [comment]
And even after executing /lp sync on your survival server it doesn't work there?

**Comment by mikroskeem** [comment]
Have you set up the messaging service?

**Comment by lucko** [comment]
Also check ip forwarding settings - they're often a cause of issues like this.

https://github.com/lucko/LuckPerms/wiki/Network-Installation

**Comment by speddoman** [comment]
Q1: It doesn't work even after doing that,

Q2: I have set it up to use Bungee, I've also installed LuckPerms_Bungee onto the BungeeCord proxy as well.

**Comment by lucko** [comment]
Please go over the steps detailed at the top of the Network installation page I linked.

**Comment by speddoman** [comment]
IP-Forwarding has been enabled on all Spigot servers, and the Bungee proxy.

**Comment by lucko** [comment]
When you make changes to a group on one server, if you go to another and run `/lp sync` followed by `/lp group <group> permission info`, do the changes you've made show?

Are there any errors in your console?

Are you sure everything is connected to the same database?

**Comment by speddoman** [comment]
They're all connected to a localised database on the dedicated server, and when I do the permission check it does seem to be there on the Survival server then. No errors are in the console, the only problem occurring is that player ranks aren't updating cross-server even though group permissions are.

**Comment by lucko** [comment]
Please try connecting to the two servers in the network which aren't being synced. On each server, run `/lp user <your name> info`, and check that the UUID field shows the correct value, and that the plugin correctly identifies you as being online.

**Comment by speddoman** [comment]
Server 1: https://gyazo.com/298f5ace216b3748392e645f9f84bb3e

Server 2: https://gyazo.com/298f5ace216b3748392e645f9f84bb3e

**Comment by lucko** [comment]
Ok, your data seems to be consistent between those servers through?

**Comment by speddoman** [comment]
Yeah, permissions are updating FOR the groups, but the actual Player's groups aren't updating.

**Comment by speddoman** [comment]
Also, I see in the MySQL database, in the luckperms_players section it has me classified as this[https://gyazo.com/becae2b58d56b74d17cc1210ecb00c0e](url)

**Comment by speddoman** [comment]
I've just noticed that when I did them both, that the UUID's of the player change when connecting between the two servers. What would be causing that issue since that would be the reason for the player's group not updating because the system sees them as two separate people.

**Comment by lucko** [comment]
No worries - glad you managed to fix it. :)
