### ISSUE TITLE
Incorrect log display

### ISSUE THREAD

**Issue by DarkFort** [lucko/LuckPerms#624]
The new version stopped displaying the log correctly
https://i.imgur.com/X7kTlxt.jpg
/lp log userhistory DarkFort

**Comment by lucko** [comment]
You need to update your language file from the English one.

**Comment by DarkFort** [comment]
Same in the English translation https://i.imgur.com/YJvbD3C.jpg

**Comment by DarkFort** [comment]
But when I delete en_US locale.yml everything is fine

**Comment by lucko** [comment]
Yep - seems I haven't updated the lang file yet.

**Comment by lucko** [comment]
Locale files now live here. I've updated the en_US one with the latest changes.
https://github.com/LuckPerms/locale
