### ISSUE TITLE
Prefixes not displaying correctly

### ISSUE THREAD

**Issue by Ezacu** [lucko/LuckPerms#625]
For all of my groups, the prefix is a color code and the bold color. The color does show up but the bold does not. Example: &a&l{Owner}.
![command](https://user-images.githubusercontent.com/32415496/34281800-2a4f33bc-e68f-11e7-9880-c1ef6cf83341.PNG)
![name without bold](https://user-images.githubusercontent.com/32415496/34281801-2a5aec0c-e68f-11e7-82a3-018b05517b05.PNG)

**Comment by Nighko** [comment]
Did you set a prefix earlier that wasn't bold?

**Comment by lucko** [comment]
All of above ^^, plus:

* Does the correct value show when you run `/lp user <you> info`
* Try with `/lp user <you> meta info` - is that prefix at the top of the list?

**Comment by Ezacu** [comment]
Yes I did set a prefix earlier that wasn't bold, and I use EsentialsChat. Both Vault and LuckPerms are up to date.
