### ISSUE TITLE
Incorrect work OP

### ISSUE THREAD

**Issue by DarkFort** [lucko/LuckPerms#626]
Op works and then stops working and works again.
The config is set to enable-ops: true

**Comment by lucko** [comment]
I need more information than that.

How do I reproduce it? What are the timings of the change? Any specific commands? 

I've been using the autoop feature on my server for the last year without any issues at all.

Please re-open this ticket when you have more info to provide.

**Comment by DarkFort** [comment]
When I enter a command from the /op DarkFort console, the dispatch message appears, but op does not appear.

In the plugin AnimatedMenuPlus there is a function for executing the command on behalf of op player. But it is not executed, because op is not issued.
In menu AMPlus:
Commands:
  - 'op: disguise sheep'

**Comment by lucko** [comment]
LuckPerms doesn't modify the OP system at all if you have autoop disabled and enableop set to true.

So, it's most likely being caused by another plugin.
