### ISSUE TITLE
lp user xxx clone xxx not available in Spigot?

### ISSUE THREAD

**Issue by smmmadden** [lucko/LuckPerms#627]
I just got done using the lp user xx clone xxx on my sponge 1.12.2 servers and came to my spigot 1.12.2  servers to do the same.  Unfortunately, I'm getting Command not recognised. message when I try it.  Are we not able to clone the same way in Spigot servers as Sponge version of LuckPerms?
Thanks!

**Comment by mikroskeem** [comment]
Is your LuckPerms installation up to date?

**Comment by smmmadden** [comment]
yes, I'm using LuckPerms-Bukkit v4.0.18

**Comment by lucko** [comment]
The releases on SpigotMC and Sponge Ore are made at different times, and usually lag behind the latest build.

You can always download the very latest version from here.
https://ci.lucko.me/job/LuckPerms/

**Comment by smmmadden** [comment]
Awesome!  Thank you very much.  I'm trying to replace all three permission systems and see the bungee one is available too.  Will be so much easier when they are all the same!
Happy Holidays Lucko!
