### ISSUE TITLE
Editing permissions for non-existent users

### ISSUE THREAD

**Issue by DarkFort** [lucko/LuckPerms#629]
Please add [this feature](https://i.imgur.com/GomImuk.jpg). This is sometimes very necessary.

**Comment by merjilin** [comment]
Use their UUID instead of their username is they haven't logged in before. Luckperms doesn't know the username exists without them logging in first, but the UUID gets around that.

**Comment by DarkFort** [comment]
I have a crack server :(

**Comment by MWFIAE** [comment]
Quick googling reveals that you can generate the offline uuid if you have the playername.

**Comment by lucko** [comment]
You can enable it in the config already.
https://github.com/lucko/LuckPerms/wiki/Configuration#use-server-uuid-cache
