### ISSUE TITLE
Incorrect log display

### ISSUE THREAD

**Issue by DarkFort** [lucko/LuckPerms#631]
The new version stopped displaying the log correctly
https://i.imgur.com/X7kTlxt.jpg
/lp log userhistory DarkFort

Same in the English translation https://i.imgur.com/YJvbD3C.jpg
But when I delete en_US locale.yml everything is fine
https://github.com/lucko/LuckPerms/issues/624

**Comment by lucko** [comment]
You don't need to open duplicate tickets.
