### ISSUE TITLE
Lower case names

### ISSUE THREAD

**Issue by BobbyMere** [lucko/LuckPerms#634]
Whenever I create a group, it defaults the name to lowercase. Is there a way to remove this feature so the name can be capitalized?

**Comment by lucko** [comment]
Just set a display name.

`/lp group admin setdisplayname Admin`

**Comment by BobbyMere** [comment]
The display name doesn't work when using Ezrankspro rank up system. Is there no way to make it actually capitalized? Just seem odd it will force into lowercase.

**Comment by lucko** [comment]
It's forced to lowercase because group identifiers are case insensitive in LuckPerms.

It's significantly easier to force all identifiers to lowercase, and keep things consistent that way, than to allow entries in mixed case and perform case insensitive lookups throughout the plugin.

There's no reason why EzRanksPro wouldn't support that - Vault methods are unaffected by the change, and will resolve by display name if necessary.

**Comment by BobbyMere** [comment]
It doesn't. They all display as lowercase

**Comment by lucko** [comment]
Make sure you're using the latest version.

The Vault methods definitely return display names.

**Comment by BobbyMere** [comment]
If I manually changed all of the ranks to uppercase, would that mess anything up, functionally?

**Comment by BobbyMere** [comment]
When I ref to 'display', I mean when you type "/Rankup", the rank shows as lowercase in chat. Ezrankspro has an option to change the actual display of the rank afterwards. 

So I'm only ref to when they type /rankup

**Comment by BobbyMere** [comment]
I'm using the latest vault and it displays as lowercase

**Comment by BobbyMere** [comment]
Is there some option to put vault as primary display? I'm not seeing it if it's not standard.

**Comment by lucko** [comment]
> If I manually changed all of the ranks to uppercase, would that mess anything up, functionally?

LuckPerms expects names to be in a lowercase format, although it'd probably accept them as uppercase too.

However, as soon as they're loaded into memory, they would be converted back to lowercase - so you'd achieve nothing. As I've said already - they are identifiers, and are not intended to be displayed to end users. That's what display names / prefixes / suffixes are for.

> When I ref to 'display', I mean when you type "/Rankup", the rank shows as lowercase in chat. Ezrankspro has an option to change the actual display of the rank afterwards.

That depends entirely on how EzRanksPro is getting its data. You'd be better off trying to speak with the EzChatPro author - they'd have a better insight into how that data is being retrieved and formatted. (and it's premium and closed source - so even if I wanted to, I can't really help you much further.)

**Comment by BobbyMere** [comment]
Ok, well, lets leave the annoying lowercase letters alone for a minute. I'm trying to display two separate ranks and whenever I add (parent) another rank to the primary rank, only the primary rank is shown. I already have it setup to display two names, I know this because it works with PEX "group add" option. 

How do I get the parent ranks to act like the "added" ranks do with PEX so they both show?

**Comment by BobbyMere** [comment]
Thanks btw for trying to help with this lowercase/parent issue.

**Comment by lucko** [comment]
> I already have it setup to display two names

It depends on how you've done that.
