### ISSUE TITLE
issue with /lp <group> editor

### ISSUE THREAD

**Issue by firestrife23** [lucko/LuckPerms#635]
I've used this in the past and worked really well, until recently the generated URL is not working because i'm getting 404 - Page Not Found this time. I like this feature a lot because it's major time saver.

**Comment by lucko** [comment]
What URL are you trying to view?

**Comment by firestrife23** [comment]
https://lpedit.lucko.me/3c7beaf970ef14cf266ba442a0702df/f238205edb0432985a1fc6b995d48cd9ec92e37b

**Comment by lucko** [comment]
You're missing a `?` at the start of the id, it should be `https://lpedit.lucko.me/?3c7be...`.

And even with that aside, GitHub reports that the data payload doesn't exist.
https://gist.githubusercontent.com/anonymous/3c7beaf970ef14cf266ba442a0702df/raw/f238205edb0432985a1fc6b995d48cd9ec92e37b/luckperms-data.json

Are you sure you copied the link correctly?

Failing that, it'd be worth updating to the latest version.

https://ci.lucko.me/job/LuckPerms/

**Comment by firestrife23** [comment]
Yes i copied it straight out of console, and I'm currently on version 4.0.11

**Comment by lucko** [comment]
I don't know what else to say without repeating myself.

> You're missing a ? at the start of the id - Are you sure you copied the link correctly?

I don't see any other reason why you'd suddenly be missing that character. All of the links contain that at the start.

> it'd be worth updating to the latest version.

4.0.11 isn't the latest version.

**Comment by firestrife23** [comment]
Thank you very much for your time, I'll update to the latest version that could be the issue.

**Comment by firestrife23** [comment]
Sorry to bother you again, I updated to 4.0.67. see below for the output I'm getting on multicraft console which is rather strange... of course URL doesn't work and I tried adding "?"  at the start of the id which got through but hanged at loading message. 

[http://imgur.com/j0hIRdgl.png](url)

I executed same command inside the game and gave me working url this time and I was able to load and edit permission online... I think there's something funky with multicraft platform that mess with the console's output. Just want to let you report this strange behavior because I'm sure there are many other server owner use multicraft as well. You can download free copy multicraft at https://www.multicraft.org/ for testing purpose if you want.

**Comment by lucko** [comment]
I can't really see anything in the screenshot you provided - resolution is too low!

I've never had any reports of this issue occuring before - perhaps you're using an old version of Multicraft?

Either way, this isn't an LP issue - there's nothing I can do about a bug in Multicraft.

**Comment by firestrife23** [comment]
Appreciated your insight on this matter, I'll have to get in touch with my hosting provider about multicraft. I agree with you, it's not LuckPerm issue. Keep up with great work, and I'll continue to use your plugin.

By the way, I didn't realized imgur resized the screen shot so small! Sorry about that.
