### ISSUE TITLE
The plugin keeps breaking

### ISSUE THREAD

**Issue by BobbyMere** [lucko/LuckPerms#636]
Every time I type anything with "/LP" in it, "[LP] running luckperms v4.0.18" shows up. This happened last night as well. I tried deleting the plugin and the folder to regenerate everything, but that didn't work. I ended up having to download the same version again and it fixed it. 

12hours later, the same issue is present. There's no errors in the console. 
I'm using latest LP version with spigot 1.12.2

**Comment by lucko** [comment]
First line of https://github.com/lucko/LuckPerms/wiki/Command-Usage states:

> If the only thing returned when you type a command is the plugin version, you do not have permission to use any of the commands. You need to use the server console to give yourself access to LuckPerms commands first.

**Comment by BobbyMere** [comment]
This includes all commands starting with "/lp"

**Comment by BobbyMere** [comment]
giving myself OP doesn't work?

**Comment by lucko** [comment]
Which platform are you using? Bukkit/Spigot or Sponge?

**Comment by BobbyMere** [comment]
Spigot. I op'd myself again and it works again. Thank you
