### ISSUE TITLE
startup warning plugin using 6.0.0 but Sponge API is 7.0.0

### ISSUE THREAD

**Issue by smmmadden** [lucko/LuckPerms#637]
I'm using LuckPerms-Sponge-4.0.62.jar on my Sponge Forge 1.12.2 server and the startup shows a warning during startup.
18:15:57] [Server thread/WARN] [Sponge]: The mod luckperms was designed for spongeapi 6.0.0 but version 7.0.0-SNAPSHOT-e71c454 is in use. It may not work properly.

The sponge version I'm using is 1.12.2-2555-7.0.0-BETA-2761.jar
Isn't this supposed to work in Sponge 7.0.0?

**Comment by merjilin** [comment]
The luckperms jar for sponge is universal, it just so happens that message states API 6 :) so it isn't anything to worry about.

Luck would probably change that once support drops support for API 5 and 6 in January.

**Comment by merjilin** [comment]
Once sponge drops support for API 5 and 6* Damn autocorrect xD

**Comment by lucko** [comment]
It's a Sponge warning. The plugin is compiled against API 6, but is compatible with API(s) 5-7.

**Comment by smmmadden** [comment]
okay thanks - I've been going through the startup logs in an effort to get rid of any of the noise that's there.  Wasn't sure if this was why one of the mods I'm using isn't listing the permission nodes for it in the editor or not.  Waiting to hear back from the other dev.
