### ISSUE TITLE
Chesum check

### ISSUE THREAD

**Issue by XakepSDK** [lucko/LuckPerms#641]
I'm back with my cassandra support, and as i see, you made checksum check.
As i see, its sha-256.
You can use sha1 or md5, because maven makes checksum files automatically.
For example:
http://central.maven.org/maven2/com/datastax/cassandra/cassandra-driver-core/3.3.2/cassandra-driver-core-3.3.2.jar.sha1

**Comment by lucko** [comment]
Yep, the idea is that it hashes the downloaded jar against an expected checksum.

It does two things:

1. Ensures the integrity of the file (that all of it was downloaded correctly)
2. Prevents files from being altered on the remote server without out knowledge.

Checking against a checksum provided by Maven only achieves 1.

You'll notice that some of the dependencies aren't downloaded from official maven repositories, so it's important to check against an expected hash.
