### ISSUE TITLE
Comments on granting privileges or permissions

### ISSUE THREAD

**Issue by DarkFort** [lucko/LuckPerms#642]
Very much I ask to add function of the description of granting of a privilege or the permission. For example, I inserted a command in the / lp menu, user% player% parent set premium, the player buys it for play money, but I can not find out why he got it. Therefore, please add comments (log) to the commands - / lp user% player% parent set premium log: "Purchase privilege for virtual money"

**Comment by lucko** [comment]
No, this is beyond the scope of the logging functionality in LuckPerms. The `action` parameter of log entries is limited in terms of characters, and is intended to describe the `action` (hence the name) and not the cause.

If you want additional logging, then I suggest using an extra plugin which will let you record log entries, and then just post to that log whenever you execute your promotion commands.
