### ISSUE TITLE
Permission Node to Control Membership of Specific Group

### ISSUE THREAD

**Issue by SimonOrJ** [lucko/LuckPerms#646]
Hello,

Thank you for actively maintaining LuckPerms! I've migrated my server from PermissionsEx to LuckPerms.

When I used PermissionsEx, I was able to allow a person or group to add or remove people from a specific group using [PermissionEx's group-specific permission node](https://github.com/PEXPlugins/PermissionsEx/wiki/Commands#groups-user-management).

However, that kind of permission node doesn't seem to exist in LuckPerms.  There are groups where the head of the group can add or remove members from (for LWC's group chest protection functionality), but currently, I have to give all of my moderators all permissions to add or remove members from every permission groups (which is dangerous, but I trust my staff team to not abuse permission groups possibly by adding themselves to an admin group) until I can get time to write up another special plugin to hook into LuckPerms API.

Will the group membership management feature be added?  It was useful while I used PEx.

Thank you!
~Simon

**Comment by lucko** [comment]
Such feature already exist, but it is disabled by default.

https://github.com/lucko/LuckPerms/wiki/Argument-based-command-permissions

It's quite a lot more in-depth than the system provided by PEX, and allows for much more customization. However, it's quite difficult to understand, and therefore disabled by default. :)
