### ISSUE TITLE
Error while entering command /lp sync

### ISSUE THREAD

**Issue by DarkFort** [lucko/LuckPerms#649]
https://hastebin.com/benuxogoje.vbs

**Comment by lucko** [comment]
Have you deleted the groups table?

`Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'luckperms.luckperms_groups' doesn't exist`

**Comment by DarkFort** [comment]
Yes, I cleaned up the database to download new changes from my server to the local

**Comment by DarkFort** [comment]
Not a very convenient way

**Comment by lucko** [comment]
Ok, then you need to re-create the groups table.

https://github.com/lucko/LuckPerms/blob/master/common/src/main/resources/schema/mysql.sql#L39-L42
