### ISSUE TITLE
Powerful Perms Migration not working

### ISSUE THREAD

**Issue by hazycraft** [lucko/LuckPerms#651]
Whenever I try to execute command for migrating PowerfulPerms it just says command not recognized. Can you please fix this so I can actually migrate from PowerfulPerms Thank You
Using Latest Powerful Perms 4.5.2 and Latest LuckPerms 4.0.74
[https://preview.ibb.co/eHuqEw/Untnitled.png](https://preview.ibb.co/eHuqEw/Untnitled.png)

**Comment by Andre601** [comment]
Did you follow the instructions in the wiki-page?
https://github.com/lucko/LuckPerms/wiki/Migration

**Comment by hazycraft** [comment]
Yes I followed it...

**Comment by lucko** [comment]
Should be fixed in the latest version.

The author decided it'd be a good idea to randomly change their namespace. 🙄

**Comment by hazycraft** [comment]
@lucko Thank you ;)
