### ISSUE TITLE
Quick export to yaml file?

### ISSUE THREAD

**Issue by LogGits** [lucko/LuckPerms#652]
Is there a way to quickly export the permissions structure to yml file without having to restart? This would be useful for editing,where you could just import the yaml file back in and it would update the current filetype. This feature would save a lot of time and mean we don't need to do two restarts to do the same thing.

**Comment by lucko** [comment]
Just use the web editor?

**Comment by BrainStone** [comment]
For the web editor run `/lp group <group> editor` or `/lp user <user> editor`
