### ISSUE TITLE
Add a prefix to LuckPerms internal nodes

### ISSUE THREAD

**Issue by tomcraft** [lucko/LuckPerms#656]
Hello, I open this issue to explain you my problem and a improvement suggestion.

First, your plugin is very awesome and powerful. But I saw a little confusing problem. You use theses nodes for luckperms internals : group.<> prefix.<> suffix.<> weight.<>

But my problem is that I have plugins wich are also using this pattern, so I suggest you this modification: put a prefix behind all internal nodes. 

For example group.<> would become internals.group.<> or lp.internals.group.<>
You might also let this prefix be configurable in the config.yml file

It would be verry malfunctioning-proof (and prevent from compatibility issues) in my opinion. :)

Thank you for reading 🥇

**Comment by BrainStone** [comment]
Out of interest, which plugins are you having issues with in regards to that behavior?

**Comment by lucko** [comment]
The precedent is that plugins should prefix all of their permissions with the name of the plugin.

For example, for the commands in LuckPerms, the permissions are structured as `luckperms.user.info`. Other plugins should also be following this (unspoken) rule.

However, LuckPerms is unique in that it is the plugin which actually provides and manages permissions - so for some things, a `luckperms.` prefix is excluded, namely as you point out for group nodes, meta nodes, and things like weight and display name.

If you're having conflicts, then I suggest you report the issue to the author of the plugin which is conflicting. I see no reason why it should change in LP.
