### ISSUE TITLE
issue with space in world names (further)

### ISSUE THREAD

**Issue by frizzbee30** [lucko/LuckPerms#658]
Hi, following on from the resolved issue with assigning permissions to worlds with space names, eg our survival map world(s). I've encountered another issue when it comes to assigning groups.

The plugin appears to be assigning the group as a permission as opposed to a group. Our other worlds are fine, but this one continues to be a problem. 

I've included partials of the config below, as well as my user profile on joining. 

I have tried adding "" around the world name with no success.

Thanks as always!

  mini:
    if:
      lacks: <global-mini/group.warrior>
    give:
      - global-mini/group.warrior
      
  skyworld:
    if:
      lacks: <global-skyworld/group.islander>
    give:
      - global-skyworld/group.islander
      
  skygrid:
    if:
      lacks: <global-askygrid/group.gridhopper>
    give:
      - global-askygrid/group.gridhopper
      
  survival:
    if:
      lacks: <global-survival map/traveler>
    give:
      - global-survival map/traveler
      
  survivalend:
    if:
      lacks: <global-survival map_the_end/traveler>
    give:
      - global-survival map_the_end/traveler

uuid: f717ecde-e05a-45e5-9036-cef6ca6a22cb
name: frizzbee30
primary-group: default
permissions:
- traveler:
    value: true
    world: survival map_the_end
- traveler:
    value: true
    world: survival map
parents:
- islander:
    value: true
    world: skyworld
- e4:
    value: true
    world: prison
- citizen:
    value: true
    world: plotworld

**Comment by lucko** [comment]
You need to change the default assignment config so it uses `group.traveler`, as the others do.

**Comment by frizzbee30** [comment]
Thanks, I've changed the default primary group to traveler, but doesn't carry the perms acoss when in Survival?

I've included the full config, and my user profile (deleted, and then recreated on joining). Am I missing something really obvious?

There aren't any issues with the other worlds, just the survival worlds (we have different perms for the end and survival), as I stated, the other worlds pick up the groups no problem.

All new users enter via our hub, hence I initially set gamer as the default group

Obviously this is an issue for new users, once they enter our survival world as no perms (group) at all seem to be assigned.

All the groups listed in the config are our base groups, and higher groups follow on from these.

Any advice you could offer would be really appreciated. 

From what I can see it does appear to be the name in the space between survival and map, that appears to cause the issue when the plugin reads the config file?

config+generated user file

https://pastebin.com/5mZL1CS6



Thanks

**Comment by frizzbee30** [comment]
Sorry just spotted the **obvious** mistake!  Thanks for all your help, truly amazing plugin!!  :)  Have a good New Year!
