### ISSUE TITLE
Permision broke

### ISSUE THREAD

**Issue by DarkFort** [lucko/LuckPerms#659]
Players can build on spawn from time to time. I do not know why
https://gist.github.com/anonymous/d66f6a231dcbceeb9fda09ab523ee002
https://i.imgur.com/OccYguQ.jpg

**Comment by lucko** [comment]
The `?` symbol means undefined, which translates to false if the user isn't opped.

**Comment by spannerman79** [comment]
Well its pretty simple - don't run cracked versions of minecraft unless your willing to put up with mismatched/spoofed UUID's.
