### ISSUE TITLE
User swap command.

### ISSUE THREAD

**Issue by voodootje0** [lucko/LuckPerms#660]
Would it be possible to add a user swap command?
Every permission/parent will be swapped with the target player.

**Comment by lucko** [comment]
Why?

**Comment by voodootje0** [comment]
When people change their name, it doesn't update on cracked servers. With this command, we can easily swap their old account with their new account. Also, it can be used if people have more accounts, with this command you can easily swap all permissions/parents and meta.

**Comment by BrainStone** [comment]
That's why you don't run a cracked server, lol

**Comment by lucko** [comment]
I don't see how a `swap` command is necessary, in addition to the user `clone` command that was added previously.
