### ISSUE TITLE
Minor Issue With Essentials Chat

### ISSUE THREAD

**Issue by pinchcraft** [lucko/LuckPerms#661]
All players are set to parent default, which has the chat format, set in essentials chat, as this:
    default: '&8[[FACTION]&8] {DISPLAYNAME} &8»&r {MESSAGE}'

For donator ranks, I use parent add. For example, I'll add rank Citizen to a player, which has a higher weight than default. Citizen's chat format in essentials chat is:
    citizen: '&8[[FACTION]&8] {DISPLAYNAME} &8»&e {MESSAGE}'

The player gets the citizen prefix, as that is set in luckperms, but they don't get yellow chat which is set in the "&e {MESSAGE}" part of citizen. Only the rank that the player is set to, not included those that are added, determine what color chat a player gets. Instead, it should take into account all ranks that a player has, no matter if it is set or added, and determine which one has the highest weight to determine their chat color.

I hope you can fix this soon, thanks so much :D

**Comment by spannerman79** [comment]
https://github.com/lucko/LuckPerms/wiki/Setup#essentials

**Comment by pinchcraft** [comment]
Thanks, but that didn't work for me.
I have EssentialsX, Vault, and removed the player-commands part of essentials but still the same problem.

**Comment by lucko** [comment]
The system for determining chat formats is based on the users primary group.

You might need to change this option, then set appropriate group weights to get it to work correctly.

https://github.com/lucko/LuckPerms/wiki/Configuration#primary-group-calculation
