### ISSUE TITLE
LuckyPerms - How to add other groups? Donation stuff like that

### ISSUE THREAD

**Issue by ScheeK33** [lucko/LuckPerms#662]
How would I be able to add groups for donations and stuff like that without going to /lp editor and manual doing it. As when I set the primary group, the prefix doesn't change. So I have to manual do it. Please help, thanks!

**Comment by BrainStone** [comment]
Do you add the prefixes to the players or the groups?

**Comment by lucko** [comment]
Use the `parent add` command.
