### ISSUE TITLE
user promote and world name spaces

### ISSUE THREAD

**Issue by frizzbee30** [lucko/LuckPerms#663]
Hi,
     just a quick question, one of the features I'm really keen to use is the promote function (PEX ladders were just broke!)

So as part of a reward system, I want to be able to run the promote command, obviously I could use 'add parent', but promote appears 'tidier' if I can use it.

When testing in survival, I've tried straight promote, which when already having our traveler parent/group, adds them to traveler as a direct group, without world  (as was happening before you enabled allow spaces for other commands).

If I try to add context to the command, I get server global-survival, world map, or server-survival, world map, if I add "" around survival map, I get the allowed character error message.

I know the issue is around our horrendous primary world naming (not my doing, and so embedded would now be a nightmare to fix), but is there a way to define our 'survival map', as there was with the groups in my previous query?

If there isn't , then I'll work with add parent, or another way around it etc.

Thanks in advance!  :)

**Comment by frizzbee30** [comment]
Hi, just realised it adds the track to the bottom of the user file with other world testing, thanks and closing

**Comment by frizzbee30** [comment]
Hi, with a bit more testing that the context is required for multiworld (after it added our prison group direct, then I added the world to update the user profile correctly)

Is there thus a way to get around not being able to add 'global "survival map"' but being able to add 'global prison'  as context?

Thanks  :)

**Comment by lucko** [comment]
Could you give me the full command you're using?

**Comment by frizzbee30** [comment]
Hi, while putting together examples, it has let me use "" around survival map,eg lp user <user> promote survivalrank global "survival map", so not sure what happened initially. 
1!
Sorry to trouble you, and thanks for the quick response!
