### ISSUE TITLE
GLOB Style Parsing Error

### ISSUE THREAD

**Issue by williamhatcher** [lucko/LuckPerms#665]
For the most part, using GLOB Styles such as `myperm.chat.(color|link)` works well.
If a subject is granted `myperm.chat.(color)`, LuckPerms does not validate that.

**Comment by lucko** [comment]
Where's the bug there?

Are you saying the `myperm.chat.(color)` entry should be expanded?

**Comment by williamhatcher** [comment]
Here, I'll lay out my situation.
I'm using ProtectionPerms to block all interactions with the world. Instead of setting up the perms in the console, I'm making an import file with commands like this:
`/lp group farmer-1 permission set protectionperms.item.use.minecraft:(wood|gold)en_hoe`
This works fine! But let's say I don't want farmer-1 to be able to use golden hoes, so I edit the command to look like this:
`/lp group farmer-1 permission set protectionperms.item.use.minecraft:(wood)en_hoe`
and go about my business. When I import the file and try to use the wooden hoe, I am unable to do so. I believe the plugin sees the parentheses and starts matching, but since there is only one word, it doesn't behave properly.

**Comment by spannerman79** [comment]
Global styles are to combine 2 or more, not a single permission node that doesn't cover any other node.
`/lp group farmer-1 permission set protectionperms.item.use.minecraft:(wood)en_hoe` should be `/lp group farmer-1 permission set protectionperms.item.use.minecraft:wooden_hoe`

**Comment by lucko** [comment]
I kinda agree with @spannerman79 - but it's not a difficult change, so why not.
