### ISSUE TITLE
Replacing permissions that already exist

### ISSUE THREAD

**Issue by DarkFort** [lucko/LuckPerms#668]
I propose to add the possibility of replacing the permissions that are already available. When I give the right to the player, and then take it back, it is written that this right already exists. I have to clean this right, and then return it. It is not comfortable.

**Comment by spannerman79** [comment]
https://github.com/lucko/LuckPerms/wiki/Command-Usage#lp-usergroup-usergroup-permission-unset

**Comment by DarkFort** [comment]
I say that I have to take the permission, and then issue again. It's not convenient, I need it to be replaced by one command, not two.

**Comment by spannerman79** [comment]
Then setup an alias https://bukkit.gamepedia.com/Commands.yml

**Comment by DarkFort** [comment]
Yes, it's like a solution. But I think that the developer implements the substitution of permissions in Luckperms

**Comment by spannerman79** [comment]
What you are asking for is as clear as mud.  No, the way **all** permission systems work is that a command only takes or only gives or only sets a context/node - it doesn't perform both at the same time.

The only exception to this is bulkupdate

**Comment by DarkFort** [comment]
I can suggest adding an argument that would replace the resolution. For example: /lp user DarkFort permission set -r player.perm true survival

**Comment by spannerman79** [comment]
> I can suggest adding an argument that would replace the resolution. For example: /lp user DarkFort permission set -r player.perm true survival

That is the **exact** same as what I already mentioned here https://github.com/lucko/LuckPerms/issues/668#issuecomment-355089963

**Comment by DarkFort** [comment]
But if this permission is already there with another value, then there will be a message that this permission is already there

**Comment by spannerman79** [comment]
As I already stated, as you are as clear as mud as to what you are trying to do, as you won't (or refuse) to read the wiki there are many commands to either unset or remove or to set permission nodes.

**Comment by DarkFort** [comment]
The -r parameter must replace the resolution even when it is already

**Comment by DarkFort** [comment]
OK, how do I take and give a permission that already exists if these commands are executed together when you click on the menu?

**Comment by spannerman79** [comment]
If the permission is the **exact** same then you don't need to add that same permission again - unless its a temp node. Again - this is on the wiki - https://github.com/lucko/LuckPerms/wiki/Configuration#temporary-add-behaviour

**Again** read the wiki

**Comment by DarkFort** [comment]
but for permanent resolution how?

**Comment by lucko** [comment]
> OK, how do I take and give a permission that already exists if these commands are executed together when you click on the menu?

Make sure you're using the latest version - commands are executed in order.

**Comment by lucko** [comment]
Regarding the original suggestion, what most don't realise is that a `false` value is still a setting. It's a unique entry in the file - and therefore, replacing it when another unique entry makes no sense.

Hopefully that makes sense.
