### ISSUE TITLE
Import/export prefixes is broken

### ISSUE THREAD

**Issue by treyzania** [lucko/LuckPerms#671]
It appears that the exporter generates commands of the form:

```
/lp group admin meta addgroup 100 "&4Admin&r "
```

It says `addgroup` instead of `addprefix`, which definitely appears to be wrong.

**Comment by Nighko** [comment]
Could you show the whole file?
What version of Luckperms are you using?

**Comment by Nighko** [comment]
Update to the latest version if you haven't already.

**Comment by lucko** [comment]
#667

**Comment by treyzania** [comment]
My bad, I was using `v4.0.67`.  Didn't realize there was a newer version, I thought I grabbed the latest already.
