### ISSUE TITLE
1.7 support is broken

### ISSUE THREAD

**Issue by EnderRaider** [lucko/LuckPerms#672]
Hello, when using LuckPerms v4.0.84, local storage (yaml, hocon, json) isn't working properly.
On first startup of the server it's working fine, with h2 storage, then if I change it to yaml for example I got this error on restarting the server:
https://hastebin.com/ivegefedaj.md

**Comment by Andre601** [comment]
Do you use the Legacy version of LuckPerms?
You can find it here: https://ci.lucko.me/job/LuckPerms/

**Comment by frizzbee30** [comment]
Spigot/Bukkit (1.8.8 or higher) –> LuckPerms-Bukkit
Spigot/Bukkit (1.7.10 or lower) –> LuckPerms-Bukkit-Legacy

Latest dev builds aren't compatible with pre 1.8.8, as Andre601 states

**Comment by EnderRaider** [comment]
It's definitely a bug since I'm using the legacy version.

**Comment by lucko** [comment]
https://ci.lucko.me/job/LuckPermsLegacy/
