### ISSUE TITLE
Question for OP override permissions

### ISSUE THREAD

**Issue by johnsoncui02** [lucko/LuckPerms#673]
take /lp for example
if i set /lp to false in a group, while using  a plugin called chestcommands i can run commands as operator mode. But Luckperms prevents me to run this command as operator mode.
operator mode is supposed to override and ignore all permissions. but luckperms stops me from doing that.

so say i want players to click on a GUI to do /warp example, but i do not want them to have access to the command /warp example, so i disable the command and use chestcommands to run the commands as operator mode when players decides to click on the GUI.

Is there an alternative to achieve this?
 
Luck Perms Verbose Results
https://git.io/vNIwo

**Comment by lucko** [comment]
Actual permissions will always override op status. There's no way around that - all permission plugins implement this behaviour.
