### ISSUE TITLE
Luckperms problem with advancedban

### ISSUE THREAD

**Issue by Eloslav** [lucko/LuckPerms#676]
Hello, i have a problem with advancedban plugin comunication with luckperms maybe because i have all needed permissions listed and i set true for usage of .all but nobody can see an notification that ban or kick has been given. /ban or /kick is working

**Comment by lucko** [comment]
Test which permissions are being checked with the verbose command.

https://github.com/lucko/LuckPerms/wiki/Verbose

**Comment by Eloslav** [comment]
There is actually no chech for permissions on any server O_o

**Comment by lucko** [comment]
Where do you have AdvancedBan installed?

**Comment by Eloslav** [comment]
On Bungee only

**Comment by lucko** [comment]
Ok, make sure you use `/lpb` when running the verbose command.

**Comment by Eloslav** [comment]
Ok, now i see that Admin kicks player and it says ab.all - true but ab.kick.notify is set to undefined for every player on the server

**Comment by lucko** [comment]
Ok so just set that permission to true for the default group?

**Comment by Eloslav** [comment]
There is the problem. It is set to true in bungee config and in luckperms also

**Comment by lucko** [comment]
`/lpb group default permission set ab.kick.notify true`

**Comment by Eloslav** [comment]
ok, will try

**Comment by Eloslav** [comment]
Dude it worked! thanks a lot, I didnt know that Bungee has this kind of command

**Comment by lucko** [comment]
Great - glad you managed to fix it :)

**Comment by Eloslav** [comment]
Thanks for help, i thought it was AB problem :D
