### ISSUE TITLE
Implement multiple queries to be used on networks

### ISSUE THREAD

**Issue by Raideerke** [lucko/LuckPerms#677]
Hello,

We have a suggestion to your LuckPerms plugin,
This idea only affects the Bukkit side.

So the main conception:
-	There is a server network owner who manages the network, but want to apply server owners for each servers connected to his network. He wants to apply default permissions to specified servers.

In practice it looks like the following:
lpserver.<SERVERNAME>.something.permission
•	where servername is given in the spigot server’s config. 

1.	This additional mysql query runs on a user who can only read in a separated database.
2.	This query runs optionally before other queries (as now Luckperms is working)

It is necessary for us because of the followings:
-	The server owners does not have ability  to change other server’s permissions
-	The network owner can specify permissions applied by default to servers
-	This solution does not exclude ability to configure local (spigot-side) permissions, just adds additional permissions specified in a separated database

We have a lot of similar servers and do not want to configure each other one-by-one .. and if we connect it to the same database – everyone can modify permissions on it, and it affects the whole network. 

Think you understand, why it is necessary and hope you will implement it to the plugin, we are also able to pay for it if you don’t want to implement it to the public plugin. 

Waiting for your reply patiently. 
Regards,
Sorban Bela

**Comment by spannerman79** [comment]
Enable https://github.com/lucko/LuckPerms/wiki/Configuration#argument-based-command-permissions

**Comment by BrainStone** [comment]
I think you are looking for this: https://github.com/lucko/LuckPerms/wiki/Argument-based-command-permissions

It also allows you to restrict for what contexts the user is allowed to set permissions.

**Comment by Raideerke** [comment]
Thank you for the replies! 
It is okay, but what happens if someone uses the mysql creditals (given in the config file) to change the permissions? It can't be protected agaist it, or not?

**Comment by spannerman79** [comment]
> but what happens if someone uses the mysql creditals (given in the config file) to change the permissions? It can't be protected agaist it, or not?

That is outside of Luckperms control.

This isn't a "support to secure your server" issue tracker.
