### ISSUE TITLE
Permissions data could not be loaded

### ISSUE THREAD

**Issue by MeteoritGaming** [lucko/LuckPerms#680]
Permissions data could not be loaded, Please try again later. This is the error that gives me when enter the bungeecord server. I`ve got a MYQL DataBase and luckperms the latest build on every server. Can someone help me? 

Error: http://prntscr.com/hzu3du
Logs: https://pastebin.com/K8B3XCSy

**Comment by lucko** [comment]
A connection could not be established to your MySQL server.

```
Caused by: java.sql.SQLTransientConnectionException: luckperms - Connection is not available, request timed out after 5000ms.
```

This is not a LuckPerms issue.

https://github.com/lucko/LuckPerms/wiki/FAQ#luckperms-cannot-connect-to-my-mysql-server
