### ISSUE TITLE
Feature request: verbose

### ISSUE THREAD

**Issue by SlimeDog** [lucko/LuckPerms#682]
For fast testing, it would be really useful to push verbose output directly to the console. I appreciate that it would be up to the user to set appropriate filter(s) to make it useful (eg., masking tablist every two seconds). Something like
`perms verbose log`
same as "on" or "record" except to console/log. Just a thought...

**Comment by Andre601** [comment]
https://github.com/lucko/LuckPerms/wiki/Verbose

**Comment by lucko** [comment]
Just execute the verbose command from the console.

**Comment by SlimeDog** [comment]
My mistake. I interpreted "send you an alert in chat" as in-game. Obviously, chat is reported to the console, so...
perms verbose on
does report to the console/log, while
perms verbose record
does not.

This is an extremely useful feature. Thank you.

**Comment by Andre601** [comment]
yes.
the record option of the verbose command, followed by the paste option results in posting the checked perms on git.github.com
