### ISSUE TITLE
help me pls 

### ISSUE THREAD

**Issue by LegacyMC** [lucko/LuckPerms#683]
I can't use the plugin in 1.8

**Comment by Andre601** [comment]
Sorry dud, but my glasphere is broken since yesterday.
So I can't find out, what your issue is.

**Comment by LeCodeCo** [comment]
1.8 is a hack!!!!!!!! DO NOT USE SOMEONE GOT OP MY SERVER DROWNING NO!

LUCKPERMS IS A VERY VERY GOOD BUT YOU SHOULD 1.12.2 WITH IT safer for my servers in the working on latest papersPigot and not the 1.8 sPigot!!!!!!!

**Comment by BrainStone** [comment]
Just use Spigot for 1.8.8 or 1.8.9

**Comment by LegacyMC** [comment]
thanks @BrainStone it works
