### ISSUE TITLE
LuckPerms in the GUI

### ISSUE THREAD

**Issue by DarkFort** [lucko/LuckPerms#687]
Recently I learned that in the plugin Ultra Permission there is a setting in the GUI. I would very much like to see the same in LuckPems. I think it's cool!
Who thinks anything about this idea?

**Comment by lucko** [comment]
See my response to #619

**Comment by AsVaidas** [comment]
Created the GUI of LuckPerms using the API
https://www.spigotmc.org/resources/luckperms-in-gui.53460/
