### ISSUE TITLE
i don't can remove permission

### ISSUE THREAD

**Issue by KonoromiHimaries** [lucko/LuckPerms#690]
i create export file
![2018-01-16 17_32_36-c__users_y7_appdata_local_temp_fz3temp-2_t20b3c 16 01 h17m28 yml - notepad](https://user-images.githubusercontent.com/5884000/34999908-44f792be-fae3-11e7-8621-9ecf1ff7c643.png)

if i copy and use this command
`/lp group admin permission unset test.test true server=skyblock world=s1`

i don't have any effect
![2018-01-16_17 35 15](https://user-images.githubusercontent.com/5884000/35000065-b19410b4-fae3-11e7-8803-e513f45dd9a8.png)

timings
https://timings.aikar.co/?id=5620198d95914ff0bf338d471f284d14

**Comment by Andre601** [comment]
uhmmm... did you actually **import** the permissions before using the command?

Also the unset-command doesn't affect the exported file, if you thought it does that.

**Comment by lucko** [comment]
Should be
`/lp group admin permission unset test.test server=skyblock world=s1`

not

`/lp group admin permission unset test.test true server=skyblock world=s1`
