### ISSUE TITLE
i don't can negate my permissions on specific server

### ISSUE THREAD

**Issue by KonoromiHimaries** [lucko/LuckPerms#691]
if i use this commands
```
# Export group: default
/lp group default permission set essentials.fly true
/lp group default permission set essentials.fly false server=survival-dzialki
```

![2018-01-16_17 56 45](https://user-images.githubusercontent.com/5884000/35001234-a9f4dd4a-fae6-11e7-91ad-940961c9e4b3.png)

still i can use `/fly` command on this specific server
![2018-01-16_18 10 30](https://user-images.githubusercontent.com/5884000/35002033-9afd1e54-fae8-11e7-84bb-2f3009ea5151.png)

timings
https://timings.aikar.co/?id=5620198d95914ff0bf338d471f284d14

**Comment by KonoromiHimaries** [comment]
![2018-01-16_18 02 13](https://user-images.githubusercontent.com/5884000/35001641-7109a5b4-fae7-11e7-88d1-52d9b9d6ccf1.png)

**Comment by lucko** [comment]
* Are you sure the server setting is correct? (`/lp info`)
* Are you sure you're a member of the default group?
* Are you sure there's not some other permission overriding it?
* https://github.com/lucko/LuckPerms/wiki/Setup#essentials

**Comment by KonoromiHimaries** [comment]
![2018-01-16_18 17 49](https://user-images.githubusercontent.com/5884000/35002327-9c444b42-fae9-11e7-9909-8b0490bb37d8.png)

> Are you sure you're a member of the default group?

![2018-01-16_18 21 34](https://user-images.githubusercontent.com/5884000/35002492-1efbfae4-faea-11e7-870b-484d11819073.png)

> Are you sure there's not some other permission overriding it?

https://gist.github.com/KonoromiHimaries/b098664cb2aaeeaf7010427fb387a824

**Comment by KonoromiHimaries** [comment]
ahhh..
`/lp group default permission set essentials.fly false server=sd`
