### ISSUE TITLE
Console/log coloration

### ISSUE THREAD

**Issue by SlimeDog** [lucko/LuckPerms#693]
Please allow a configuration option to change (or delete entirely) the coloration of console/logs.

**Comment by SlimeDog** [comment]
Never mind. Found it in lang.yml.

**Comment by lucko** [comment]
Add the following to your config.yml

```yaml
colored-logger: false
```

**Comment by SlimeDog** [comment]
I have done. Running LP 4.0.98 (dev release). Console/log entries are still contain colors. Not sure what I'm doing wrong.

**Comment by SlimeDog** [comment]
And same in LP 4.0.99

**Comment by lucko** [comment]
I cannot reproduce.

![](https://luck.sh/oJxix3d1lrErGpJVaGzgTdahC-U=)

All messages sent after the configuration has been loaded are not colored.

**Comment by SlimeDog** [comment]
Agreed. I cannot reproduce. Only verbose-mode comments are color-enhanced if _colored-logger:false_.

**Comment by lucko** [comment]
Those messages aren't "log" messages - they're being sent to the console as a command executor.

So, still intended behaviour.

**Comment by SlimeDog** [comment]
Understood; I was just trying to provide a complete answer. Your addition clarifies, as always.
