### ISSUE TITLE
Default Minecraft Permissions dont work

### ISSUE THREAD

**Issue by Iceskull7** [lucko/LuckPerms#696]
Hi there,

i dont know where to ask else so maybe you can help me.
I use your Plugin and EssentialsX.

The Problem is i cant even use /help or /msg as a default User.
How i get all normal non OP commands for the Defaults to work?

here are all my Groups with the Config file
and also the Config File of EssentialsX if this interacts with LuckPerms

Hope you can help me

Thank you
[LuckPerms-YML-Files.zip](https://github.com/lucko/LuckPerms/files/1641022/LuckPerms-YML-Files.zip)

**Comment by spannerman79** [comment]
Did you look up the permission nodes for EssentialsX?
Did you look on the Luckperms wiki for Verbose and how to use it?

**Comment by Iceskull7** [comment]
Thank you, i looked into Verbose.

What a great thing  :)

i gived essentials.* to the Default Group wich fixed the problem.
I can control there if i want to remove something

https://gist.github.com/anonymous/c347e6ab3231309b2c662691a1959957

actually i just saw that /msg is used by Deluxechat, so i missed that one too


Verbose and you saved me alot of time :)

thanks

**Comment by spannerman79** [comment]
If that solved your issue then close this issue @Iceskull7
