### ISSUE TITLE
NullPointerException on player join with build 4.0.98

### ISSUE THREAD

**Issue by LXGaming** [lucko/LuckPerms#697]
https://pastebin.com/UB3BDZHk

spongeforge-1.10.2-2477-5.2.0-BETA-2788

**Comment by spannerman79** [comment]
`[LuckPerms] [ERROR] Exception occured whilst loading data for [UUID] - Optional[[NAME]]`
Need to see full start log.
Prob related to https://github.com/lucko/LuckPerms/wiki/FAQ#luckperms-cannot-connect-to-my-mysql-server

**Comment by LXGaming** [comment]
I don't believe it's a MySQL issue as only our Sponge 1.10.2 servers are affected by this, Sponge 1.12.2 and Spigot 1.12.2 servers are running 4.0.98 without any issues.

Downgrading to 4.0.86 fixes the issue for Sponge 1.10.2 servers.

https://pastebin.com/JQKixtRz - Errors from FML log

**Comment by i9hdkill** [comment]
Thats indeed an error in luckperms
java.lang.NoClassDefFoundError: me/lucko/luckperms/lib/jarrelocator/JarRelocator

**Comment by spannerman79** [comment]
> Thats indeed an error in luckperms
> java.lang.NoClassDefFoundError: me/lucko/luckperms/lib/jarrelocator/JarRelocator

... I cannot believe I missed that......

@i9hdkill you are correct. Yes @LXGaming it is a Luckperms issue.
JarRelocator was added on commit https://github.com/lucko/LuckPerms/commit/39daed23c4731a6759ed166b88b715ce8fe19872 - added on https://ci.lucko.me/view/LuckPerms/job/LuckPerms/489/ - 4.0.89 should be fine as it was *before* the adding of JarRelocator (in theory)

**Comment by lucko** [comment]
Try again using the latest build, should be fixed.
