### ISSUE TITLE
Some problem with meta-permission's overwrite while inherited form base group

### ISSUE THREAD

**Issue by Tollainmear** [lucko/LuckPerms#698]
Hi, I have a problem with inherited meta-permission.
when I give the default group meta-permission `griefprevention.blocks-accrued-per-hour 0` to limiting the default group could accrued claims block 0/h (could not accrued blocks in fact).
And give the Vip group meta-permission `griefprevention.blocks-accrued-per-hour 50` to making the donator could accrued claims block 50/h.
Then I use the `/lp user [name] parent addtemp Vip 30d` command to add a temp parent group to donator, the donator would have two meta-permissions:
- griefprevention.blocks-accrued-per-hour 0
- griefprevention.blocks-accrued-per-hour 50

And I'm sure that this player could not accrue block, so I guess the two meta-premission may only which  inherited from 'default' group's meta-permission has worked.
what is the right way to overwrite the meta-permission between two group?
Should I use that command`/lp user [name] parent addtemp Vip 30d` ?

**Comment by spannerman79** [comment]
I'm assuming your using the add-on, in that case if you look at the config file for GPAccruals
`Permission nodes are in the format griefprevention.accruals.<type>.<name>` so the node will be `griefprevention.accruals.<type>.<name>` depending on what you have set in the config

There is no spaces in GPAccruals

**Comment by lucko** [comment]
^ plus:

Make sure you have group weights setup correctly. Meta values are considered in inheritance order, so weights are important. Higher weight number = a higher priority.
