### ISSUE TITLE
Add option to disable OP access

### ISSUE THREAD

**Issue by sgdc3** [lucko/LuckPerms#7]
Atm OP users are able use any LuckPerms command, in my opinion it would be great to allow server owners to disable that, like PEX does.

**Comment by lucko** [comment]
Two new config options added in v2.8 ( ea07f05097946e43f88224c8b04ebf06c217ce87 ) should resolve this.

https://github.com/lucko/LuckPerms/blob/master/bukkit/src/main/resources/config.yml#L49-L53

Thanks for the suggestion :heart:
