### ISSUE TITLE
removing colorcodes

### ISSUE THREAD

**Issue by Assassins88** [lucko/LuckPerms#700]
hello,

Is there a way to disable the deleation of the last color code if no character follows this code.

Example:
As I would like:
&f[&4Admin&f]&4

How LuckPerms do it:
&f[&4Admin&f]

**Comment by Andre601** [comment]
Put the prefix inside "" (`"&f[&4Admin&f]&4"`)

**Comment by Assassins88** [comment]
Thanks for this fast answer but it dosnt work...

The names after the prefix are still white. Only the " is green. :'(

**Comment by Andre601** [comment]
My only guess is, that your Chatplugin changes the Color for the playername (f.e. changes the displayname of the player.)

**Comment by Assassins88** [comment]
I use Nucleus?

**Comment by BrainStone** [comment]
So I assume you want the color code to apply to the playername, right?

If so you have to set the namecolor. Check the Nucleus documentation for details
