### ISSUE TITLE
Incorrectly all permissions work '*'

### ISSUE THREAD

**Issue by DarkFort** [lucko/LuckPerms#707]
At last I have understood in what a problem. Let's say the admin group has all permissions '*' and is inherited from the default group where some permissions are limited, these rights won't work for the player with the admin group. Is this how it should be?

**Comment by DarkFort** [comment]
P.S.
The default group weighs less than admin

**Comment by lucko** [comment]
Yes intended.

Inherited permissions take priority over wildcards.
