### ISSUE TITLE
An exception was thrown whilst calculating the context of subject

### ISSUE THREAD

**Issue by jh1226** [lucko/LuckPerms#708]
Keep getting the error above, don't know why

**Comment by spannerman79** [comment]
And how is anyone able to help you if you give no actual info about your environment?

Luckperms covers from 1.7.10 (possibly even older) all the way through to 1.12.2, from Cauldron, Spigot and Sponge.

I'd say you've got a plugin that is calling an incorrect version of an API with that sort of error.  Possibly to do with SpongeForge.  Sponge API7 is still pretty new and going through constant changes.

**Comment by BrainStone** [comment]
We need the full error as it appears in the logs. The `at` lines are part of it.

**Comment by lucko** [comment]
From past experiences, this is usually a GriefPrevention issue.

Very unlikely to be caused by one of the LP calculators
