### ISSUE TITLE
Server-specific group permissions not working

### ISSUE THREAD

**Issue by melinstagibson** [lucko/LuckPerms#71]
The prefix of a local group wont overwrite the global default groups one.

parents of player:
default
recruit (server=main)

track 
default---->recruit

default has prefix [guest] with weight 1 and recruit has prefix [recruit] with weight 10

yet it wont use the recruits prefix. the only way to di this was

parents of player:
default
recruit

set recruit to global and it worked

**Comment by melinstagibson** [comment]
i tested with permissions, those work but the prefixes wont.

it wont even update the prefix if i do this on the FACTION server:

lp group default meta addprefix 1 [test]
lp group default meta addprefix 2 [nope]

the prefix on faction will still stay [test]

**Comment by bloodmc** [comment]
dupe #62

**Comment by lucko** [comment]
Works for me.

Are you using Vault? If so, what is `vault-server` set to in your config?

**Comment by melinstagibson** [comment]
global

**Comment by lucko** [comment]
You need to set it to the same value as `server`.

**Comment by lucko** [comment]
Guessing this is fixed?
