### ISSUE TITLE
Vault prefix/suffixes

### ISSUE THREAD

**Issue by LaxWasHere** [lucko/LuckPerms#710]
Setting prefix/suffix to "" via vault does not remove the su/prefix whereas PEX does. Pls implement? :D

**Comment by spannerman79** [comment]
Use the [API](https://github.com/lucko/LuckPerms/wiki/Developer-API) or use [Luckperms commands.](https://github.com/lucko/LuckPerms/wiki/Command-Usage#meta---lp-user-user-meta---lp-group-group-meta-)

**Comment by BrainStone** [comment]
Or try setting it to `null`

**Comment by LaxWasHere** [comment]
> https://github.com/lucko/LuckPerms/issues/710#issuecomment-359971334

Yes, I'm using [The](https://github.com/MilkBowl/Vault/) [Vault](https://github.com/MilkBowl/VaultAPI) [API](https://github.com/lucko/LuckPerms/tree/master/bukkit/src/main/java/me/lucko/luckperms/bukkit/vault)

> https://github.com/lucko/LuckPerms/issues/710#issuecomment-359972220
That's just gonna throw a NullPointerException..

**Comment by spannerman79** [comment]
> Yes, I'm using The Vault API

Look again at what I linked, Luckperms API, not Vault's API.

**Comment by BrainStone** [comment]
> That's just gonna throw a NullPointerException..

Did you try it?

**Comment by LaxWasHere** [comment]
@BrainStone was using an outdated build, thanks.

**Comment by BrainStone** [comment]
Don’t mind me asking, though what was an outdated build? LP or vault?

**Comment by LaxWasHere** [comment]
LuckPerms
