### ISSUE TITLE
Stack User Prefixes

### ISSUE THREAD

**Issue by Elxafil** [lucko/LuckPerms#711]
So I am using this plugin on my network but I have found a problem with the prefixes I am not loving, if for example I have a staff member assigned to the Admin role and I want them to also have Support their prefix only shows [Admin] and not [Admin][Support] which is what I would want. It also means for staff that purchase premium content to support the server can't show their support with a prefix like [Admin][Premium].

Can you please add the ability stack and combine prefixes and whether or not people want it you could just enable and disable it in the config or something?

**Comment by spannerman79** [comment]
https://github.com/lucko/LuckPerms/wiki/Prefix-&-Suffix-Stacking

I know ChatControl Pro can handle chat formatting based on perm nodes - there may be others that can do the same.  I cannot say as I don't use anything else other then ChatControl Pro.
