### ISSUE TITLE
Prefixes Not Working

### ISSUE THREAD

**Issue by dvdcd** [lucko/LuckPerms#712]
![image](https://user-images.githubusercontent.com/7674825/35371379-8fcfd600-0148-11e8-9e72-40300a641654.png)

**Comment by dvdcd** [comment]
I Don't know what more to say here. just i did the prefix tutorial and added myself to the group and i did not get a prefix

**Comment by spannerman79** [comment]
https://github.com/lucko/LuckPerms/wiki/Prefixes,-Suffixes-&-Meta#how-does-prefixsuffix-weight-work

**Comment by dvdcd** [comment]
its not that i'm getting the wrong one. its that i'm not getting any prefix at all

**Comment by spannerman79** [comment]
You need to see if in fact lp info shows you do indeed have the prefix set.

If you do then your chat formatting plugin isn't setting it correctly.  Luckperms does not handle chat formatting.

**Comment by dvdcd** [comment]
ok so i don't have a "chat formatter" installed. (well i do have chat control lite) so what chat formatters are compatible with luckperms prefix feature?

**Comment by spannerman79** [comment]
Those details are actually on the wiki itself.  Please read it.

**Comment by Nighko** [comment]
Dvdcd any chat system that uses vault is compatible.

**Comment by Nighko** [comment]
But your problem is most likely able to be fixed by reading up on the wiki like spanner has stated.

**Comment by dvdcd** [comment]
Ok, i'm dumb, thanks guys!

**Comment by Finvolers2** [comment]
DId you installed the EssentialsXChat or some addons else for your minecraft server(game)?

**Comment by Finvolers2** [comment]
My LuckPerms still doesn't work (prefixes and suffixes) before i installed the EssentialsXChat

**Comment by AgentIce** [comment]
> My LuckPerms still doesn't work (prefixes and suffixes) before i installed the EssentialsXChat

What? This post is from 2018 o.O 
Are you making this into your own support request? xD

**Comment by dvdcd** [comment]
> My LuckPerms still doesn't work (prefixes and suffixes) before i installed the EssentialsXChat

You'll need to install one of the chat formatters listed here https://luckperms.net/wiki/Prefixes,-Suffixes-&-Meta#displaying-prefixes-and-suffixes in order to get prefixes to appear in game.

If you can't get it working after doing so, please create a new issue instead of piggybacking off of my 3 year old one lmao
