### ISSUE TITLE
Placeholders not working in animated names plugin

### ISSUE THREAD

**Issue by jumbo1907** [lucko/LuckPerms#713]
I want to use the prefix from luckyperms in animated names plugin. It doesn't work for me! (https://imgur.com/a/RlHac).
I used this: https://github.com/lucko/LuckPerms/wiki/Placeholders#luckperms_prefix and I installed LuckPermsMVdWHook

**Comment by Nighko** [comment]
What's the actual name for the animated names plugin. That would help.

**Comment by Nighko** [comment]
And why does it say "prefi" not prefix?

**Comment by Andre601** [comment]
MvdWPlaceholders are using `{}` and NOT `%%`
