### ISSUE TITLE
Placeholders do not take anything out

### ISSUE THREAD

**Issue by DarkFort** [lucko/LuckPerms#714]
Placeholders do not take anything out
![image](https://user-images.githubusercontent.com/25278617/35396124-c3ed52d0-01f4-11e8-9f5b-882874ccee4a.png)
![image](https://user-images.githubusercontent.com/25278617/35396152-d00ceefe-01f4-11e8-9e0c-8e49b8f4d413.png)
![image](https://user-images.githubusercontent.com/25278617/35396185-e09058c4-01f4-11e8-922c-2c47d2f5f66a.png)

**Comment by lucko** [comment]
Your language file is out of date.

https://github.com/LuckPerms/locale/commit/b366b4e66fb2897fee17863106f504e6c99622dc

As for the placeholder issue, I don't know. Report it to the author of the the placeholder plugin you're using. They wouldn't just randomly return empty results.
