### ISSUE TITLE
luckperms not recognized

### ISSUE THREAD

**Issue by MrWonka** [lucko/LuckPerms#717]
users are only allowed to use //wand in my creative world, they have worldedit.* but the console says that there is no recognized permissions plugin

**Comment by BrainStone** [comment]
Please check for any startup errors, indicating that the plugin doesn’t start.

In addition to that information like the server version, server software and LP version (preferably even the file name) would be highly appreciated.

**Comment by lucko** [comment]
Please upload a copy of your servers most recent log file to https://gist.github.com/ and reply with the link.

**Comment by MrWonka** [comment]
No its because I'm an idiot and modified the wepif file. don't mind me
