### ISSUE TITLE
Lock temp permission/parent/meta's expire time

### ISSUE THREAD

**Issue by prozhong** [lucko/LuckPerms#718]
If one player gets his 30d VIP and then buy another 30d SVIP (unlikely but they may)
He has VIP&SVIP in the next 30days.
Could you please add a command to lock the expire time?
I think it may request much code work, but its useful..

**Comment by BrainStone** [comment]
Why not simply add 30 days to the VIP when SVIP gets bought.

**Comment by prozhong** [comment]
@BrainStone That's a fix, I will try it
It would be complex when there are VIP、SVIP、MVP、MVP+ ...
But still a good idea, thanks

**Comment by lucko** [comment]
This is beyond the scope of what should be reasonably provided by LuckPerms. 

Temporary permissions have a fixed expiry time - counters, timers, measurements in terms of play time, etc etc become too complex for reasonable functionality within a permissions plugin. 

You may find this option useful. 

https://github.com/lucko/LuckPerms/wiki/Configuration#temporary-add-behaviour
