### ISSUE TITLE
One permission, multiple servers.

### ISSUE THREAD

**Issue by TheLightHawk** [lucko/LuckPerms#720]
Hello, this may be a stupid question, I have recently switched to luckperms from pex, but I am having quite some trouble finding how to do this. How can I create a single permission node for a group, applying for _**multiple**_ specified servers? 

for example:
`/lp group people permission set somepermission.fun true server="server1,server2,server3"`

I have only been successful with nodes effecting single servers.
Thanks in advance for anyones help!

**Comment by Nighko** [comment]
https://github.com/lucko/LuckPerms/wiki/Context

I'm pretty sure you can only apply it to a single server with the Server context, but by defining your own context (Look at above link) you should be able to make a workaround.
