### ISSUE TITLE
Permissions order

### ISSUE THREAD

**Issue by SlimeDog** [lucko/LuckPerms#723]
Is it possible to retain the order in the permissions files? I organized them alphabetically, but when I added permissions via commands, the order was altered. I can manually edit the files to return them to my preferred order, but I shouldn't need to do. New permissions nodes should be added at the top or the bottom, and the existing entries should not be re-sorted.

**Comment by lucko** [comment]
No it's not possible.

Permission nodes are stored in "priority order" internally - so that's how they get saved.

**Comment by SlimeDog** [comment]
thanks for info.
