### ISSUE TITLE
Bot Spam Massive Lag

### ISSUE THREAD

**Issue by johnsoncui02** [lucko/LuckPerms#724]
Server: Cracked, using authme and fastlogin
Server Version: 1.12.2
Luckperms Version: 4.0.80

Issue: Lukcperms process every single player database even before when they login. We have a antibot plugin but luckperms will still create a file for every bot that was denied of joining. Eventually stressing out the entire server and causing it to shutdown.

Question: Does luckperms provide any assistance when encountering these types of bot attacks for offline servers?

**Comment by lucko** [comment]
Your anti-bot plugin should be cancelling the connection before it's actually handled by the Minecraft server.

LuckPerms loads it's data during the pre-login event.

**Comment by johnsoncui02** [comment]
According to your feedback. Is it possible to prevent luckperms to not load it's data during pre-login event. but rather afterwards? I believe that's exactly what's making the server lag and makes the anti-bot plugin inefficient in canceling connections.

**Comment by lucko** [comment]
No, I'm saying the anti-bot plugin should cancel connections at a packet level (before they're processed by CraftBukkit & the Minecraft server)

The standard connection throttle setting in the server will achieve just this. 

You're correct in saying it's not possible to cancel the process of LP handling a connection using the Bukkit events alone. It loads it's data regardless of cancellation status. Without doing this, LP becomes incompatible when plugins initially cancel the event, but re-allow it later.

**Comment by johnsoncui02** [comment]
Quoting on your last statement there, then luckperm means it's not crack server friendly. Am I misunderstanding this?

**Comment by lucko** [comment]
> Quoting on your last statement there, then luckperm means it's not crack server friendly. Am I misunderstanding this?

No, you just need your anti-bot plugin to cancel connections before they hit the server. (see my first sentence above)

> Edit: How about group manager/ permissionsex? would those better support this type of issue? I would appreciate it if you know any depth of that info.

They would be affected in exactly the same way.

**Comment by johnsoncui02** [comment]
Thanks for supporting me all along! I really appreciate it.

**Comment by detraismc** [comment]
can anyone suggest anti bot that cancel pre-login event? 
my server have a same problem, and we try different anti bot but not work at all, the guy that botting my server has a lot of hate to my server and he botting my server everyday until my server crash

**Comment by ktole1999** [comment]
report this to your host. if its affecting your server then its affecting their network.
