### ISSUE TITLE
Permissions not work

### ISSUE THREAD

**Issue by joeymaeuslp** [lucko/LuckPerms#726]
I can not allow my admin premium to grant the permission for Luckperms not always you dount if permissions he has these rights
- luckperms.user.parent.add.admin

**Comment by BrainStone** [comment]
Enable verbose mode (see details on the wiki) and see what permissions are being checked. Also make sure `argument-based-permissions` are enabled in your LP-config

**Comment by joeymaeuslp** [comment]
verbosemode not exists

**Comment by joeymaeuslp** [comment]
argument-based-permissions is enabled and verbosmode is enabled
argument permission not work please fix this

**Comment by joeymaeuslp** [comment]
Thank you verbose is a really good feature it works tahnk you
