### ISSUE TITLE
Specific permission to add a player in a group

### ISSUE THREAD

**Issue by Rakdos8** [lucko/LuckPerms#732]
Hi !
I'm wondering if your plugin allows to add a group to a player according to a specific permission.

Case example:
1. You have the default track "Player", "Moderator", "Admin".
2. You have several secondary groups "Mayor", "Trader", "Bandit"

As an Admin, we can add anyone in anygroup but we would appreciate if we can delegate some group addition for our Moderators.
That said they'll be able to add any player in group Mayor, Trader and/or Bandit with a permission like "_luckperms.user.group.add.Mayor_" and "_luckperms.user.group.remove.Bandit_"

Thank for the good work :+1:

**Comment by Andre601** [comment]
That page may help you: https://github.com/lucko/LuckPerms/wiki/Argument-based-command-permissions

**Comment by Rakdos8** [comment]
Well, indeed that's what I'm looking for, yet it's not sufficient.
Giving the permission _[base command permission].modify.others_ will allow "Moderator" to grant any group of any player. We really want to segregate action on groups (add/remove).

In fact we would like to allow them to add/remove group Mayor but only remove the Bandit one.
Is there any permission node to manage a group specifically such as _luckperms.group.modeartor.info_ instead of _luckperms.group.info_ ?

**Comment by lucko** [comment]
Yes, it's covered in the last section.

https://github.com/lucko/LuckPerms/wiki/Argument-based-command-permissions#checks-when-a-player-makes-changes-with-a-set-of-specific-arguments

**Comment by Rakdos8** [comment]
Ok nice, thank you for your reactivity. That's really appreciated.
Looking forward to migrate zPermissions into Luckperms ;)

**Comment by CrazeMC1** [comment]
I have an issue can we resolve it in discord? Thanos#4755
