### ISSUE TITLE
LuckPerms not support hungarian characters [cracked server]

### ISSUE THREAD

**Issue by andris155** [lucko/LuckPerms#733]
balázs20_yt is not a valid username/uuid.

ÁáÉéÍíÓóÖöŐőÚúÜüŰű

```
05.02 13:27:08 [Server] INFO Online players: 6/80
05.02 13:27:08 [Server] INFO VIP: [AFK][Elit]Balázs20_YT, [Elit]Baraka, [Elit]Foltos
05.02 13:27:08 [Server] INFO Members: [Tag]Gergo, [Tag]sanyesz, [Tag]Wessen
```

**Comment by Andre601** [comment]
https://github.com/lucko/LuckPerms/blob/master/bungee/src/main/resources/config.yml#L52

**Comment by rifaldipta** [comment]
Hello, can someone update this information? I think it's outdated.

**Comment by andris155** [comment]
Change this to true:
https://github.com/lucko/LuckPerms/blob/master/bungee/src/main/resources/config.yml#L524
