### ISSUE TITLE
Apply a node if only one context applies

### ISSUE THREAD

**Issue by TheLightHawk** [lucko/LuckPerms#735]
Hello,
By default Luckperms only applies a node if all the contexts return a true condition, for example:

/lp group agroup set somepermission.example true server=bestserver world=agoodworld

Will only apply when the user is in the server bestserver AND is in the world agoodworld.
My question is, how do I make it apply so only one requirement must be made?
Thanks! -TheLightHawk

**Comment by spannerman79** [comment]
Look under Default Assignments in your config

**Comment by TheLightHawk** [comment]
Ok thank you I will try this out!
