### ISSUE TITLE
Temporary permissions are not deleted from the database

### ISSUE THREAD

**Issue by wConstruct** [lucko/LuckPerms#736]
If you give lp /user user group.deluxe settemp 30d it will never be deleted from database (at least those who were not on the server until perm expire)

How to unset all expiried perms automatically??

LuckPerms-Bukkit-4.0.126
Storage MySQL

**Comment by spannerman79** [comment]
https://github.com/lucko/LuckPerms/wiki/Command-Usage#permission---lp-user-user-permission---lp-group-group-permission-

**Comment by lucko** [comment]
They'll be deleted next time that player logs in.

**Comment by wConstruct** [comment]
Why should I store this data? Unlikely if the return of one percent of these players for what purposes do I store megabytes of blank information?
Can u add option to clean DB automatically?

**Comment by lucko** [comment]
It *highly* doubt it will account for megabytes worth of data, you'd need to have hundreds of thousands of temporary records sitting there.

Yes, it would be possible to prune the really old stuff.

**Comment by spannerman79** [comment]
Perhaps have it as a separate command

`lp/lpb cleanup` for example.

**Comment by lucko** [comment]
@wConstruct why the :-1: ?

Seems like a valid solution to your issue, hm?

**Comment by wConstruct** [comment]
Because in the WIKI description is written a completely different:

Temporary permissions are audited once every 3 seconds, to check if they have expired. This check happens **regardless of the sync interval setting**. This means that you can safely set temporary permissions to expire after a matter of seconds, and they **will be removed on-time**.

**Comment by lucko** [comment]
Yes, that's accurate.

However, only permissions for **online** players and groups are checked.

**Comment by wConstruct** [comment]
Confused from this solution!

/lp group <group> listmembers - also outputs expired groups and I do not understand why there are not negative values

1514560807 shows me expires in 1 month 8 days 19 hours

**Comment by lucko** [comment]
Ah yeah, that's a bug :)

Should be fixed by the above commit.

**Comment by lucko** [comment]
I've changed my mind about this - it's not straightforward to implement for non-SQL data types, and I don't think it's worth only adding it for the SQL ones.

You should be able to purge old data yourself using this query:

```sql
DELETE FROM luckperms_user_permissions WHERE expiry < UNIX_TIMESTAMP()
```

I still stand by this:

> I highly doubt it will account for megabytes worth of data, you'd need to have hundreds of thousands of temporary records sitting there.

On one of the servers I run, we have 400k permission records - still only a few megabytes. Adding a specific command to prune temporary records isn't necessary imo.

**Comment by lucko** [comment]
Hopefully you understand my reasoning. :)

**Comment by spannerman79** [comment]
> You should be able to purge old data yourself using this query:

Perhaps have a separate wiki page with warning (think firefox page when you try `about:config` ) with that mysql query - so next some someone asks it can easily be pointed towards with a "here there be dragons" type warning 😛
