### ISSUE TITLE
Error enabling plugin LuckPerms

### ISSUE THREAD

**Issue by mat41997** [lucko/LuckPerms#74]
logs
https://gist.github.com/mat41997/20306c6f58a260295a9cce566e7e63c3

BungeeCord
https://github.com/HexagonMC/BungeeCord/releases

config
https://gist.github.com/mat41997/ab48920584fa29ce808125c2f7ee32f8

plugins
http://i.imgur.com/Hwz1DkA.png

**Comment by lucko** [comment]
You're not using the BungeeCord version of the plugin.
