### ISSUE TITLE
Reanswer to MySql Connector Error

### ISSUE THREAD

**Issue by joeymaeuslp** [lucko/LuckPerms#740]
And if there is your plugin name in the errors so this is your plugin error and your max-lifetime setting is -1 so according to your Pluginstrucktur no timeout be possible or am I wrong because exemption ex has no timeout so something you have in your oh so good plugin done wrong and just do not admit it is right or should I decompile your your plugin and you write the line of your error here or would you like the oh so good developer cough hust fix it yourself

**Comment by lucko** [comment]
#739 

> Please do not make any more tickets. If you have more to say, you can reply here.
