### ISSUE TITLE
Fix the mistake and I stop

### ISSUE THREAD

**Issue by joeymaeuslp** [lucko/LuckPerms#742]
I hate people who make mistakes and deny the bug just fix it and then it's fine if I found the bug you think the fixer would like to fix that bug or remove the plugin from spigot otherwise I'll take care of that plugin by spigot disappears with 2 milion subscribers on youtube is that easy

**Comment by Andre601** [comment]
That is NOT Luckos Misstake...
Just start to be mature and answer on the other Ticket (#739 ) because this here leads to nothing except being ignored more.

**Comment by lucko** [comment]
I've reported your account to GitHub for spam.

This is your final warning. If you create another duplicate ticket, I'll be left with no other option but you block you from interacting with this repository.

For the last time:

If you want to reply, do so here: https://github.com/lucko/LuckPerms/issues/739
