### ISSUE TITLE
Issue with exporting and importing

### ISSUE THREAD

**Issue by Zeyphre** [lucko/LuckPerms#743]
I'm having issues with exporting my LuckPerms information and importing it, when I create an new export, all it does is create a 93 Byte file that says "Create Groups"
(I am using my MySQL database for current storage: http://prntscr.com/ibnmqg)
But I'm getting a huge issue like this: http://prntscr.com/ibnmva
And I'm trying to fix that issue by exporting all of my LuckPerms data from my MySQL to YAML and all the export file is doing is creating this: http://prntscr.com/ibno8s I have no clue what I'm doing wrong, I had to run an old backup of the LuckPerms file just so I could see what file is in use for the MySQL database, and it's still giving the same error.

**Comment by lucko** [comment]
LuckPerms cannot connect to your MySQL server.

https://github.com/lucko/LuckPerms/wiki/FAQ#luckperms-cannot-connect-to-my-mysql-server
