### ISSUE TITLE
Clear all users from all groups

### ISSUE THREAD

**Issue by TrademarkTM** [lucko/LuckPerms#746]
Hey!
I've been searching a way to wipe out all my users in my server, and I haven't found a reliable way to do that.

I saw a solution with this:
`lp bulkupdate users update permission group.default "permission == group.something"` 
But it wouldn't work for me because I have 50+ groups, and it'd take an eternity to do that.

Can't you add a new wildcard, for "any" (like *, but using % or something like that)?
Or just a command to wipe out the users?

Thanks!

**Comment by Andre601** [comment]
The bulkupdate command has some placeholders, that you can use for that.

In your case:
`lp bulkupdate users update permission group.default "permission == group.%"`

`%` is a placeholder for one or multiple symbols.

**Comment by TrademarkTM** [comment]
Oh, there is already the % symbol I talked about. Sorry.
I'm closing the thread...

**Comment by TrademarkTM** [comment]
**Update**
It seems not to be working.
I am using: `lp bulkupdate users update permission group.default "permission == group.%"`, and all players keep in the same group.

Also tried: `lp bulkupdate users delete "permission == %"`, also without result.

How can I do this correctly? I want to simply RESET all players, all their permissions and all their groups.

**Comment by lucko** [comment]
This isn't currently possible using the bulkupdate command.

Will keep this ticket open as a reference to that - will try get that added when I get a chance.

**Comment by lucko** [comment]
In the meantime, it's probably easier for you to delete the data manually. What storage type are you using?

**Comment by TrademarkTM** [comment]
SQLite currently.

**Comment by lucko** [comment]
Ah okay, not so easy then.

I'll try implement the bulkupdate change asap

**Comment by TrademarkTM** [comment]
Alright, thanks.

**Comment by lucko** [comment]
> How can I do this correctly? I want to simply RESET all players, all their permissions and all their groups.

Just wanted to check, as this isn't what you asked for in your original request.

To delete all user group memberships, you can use:   
`lp bulkupdate users delete "permission ~~ group.%"`   
(this has always worked)

As of the latest commit, you can also use:   
`lp bulkupdate users delete`   
which will delete absolutely everything. All users, including their permissions, group membership, prefixes, etc.
