### ISSUE TITLE
Startup exception

### ISSUE THREAD

**Issue by DarkFort** [lucko/LuckPerms#749]
https://hastebin.com/gubohosila.md

**Comment by lucko** [comment]
What server version?

**Comment by DarkFort** [comment]
PaperSpigot 1.12.2
Latest LuckPerms on jenkins

**Comment by lucko** [comment]
which version of Paper

**Comment by DarkFort** [comment]
git-Paper-1305

**Comment by lucko** [comment]
Try updating to the latest version.

**Comment by DarkFort** [comment]
I'll try to do it at night, when online will be less. Please, do not close the issue

**Comment by lucko** [comment]
You can re-open it if the issue isn't fixed by updating.
