### ISSUE TITLE
Unable to load persisted subjects

### ISSUE THREAD

**Issue by Bubble0seven** [lucko/LuckPerms#75]
Not sure what is happening but permissions simply stopped  something regarding updating or something log attached but seems there is a break between sql and plugin maybe

Luckperms Version 2.16.6

[FML-Log](https://gist.github.com/Bubble0seven/a178fc8fd9c20a153497c6940284f420)

**Comment by Bubble0seven** [comment]
Updated to the latest version but problem still exists with the same error

**Comment by lucko** [comment]
Should be fixed in the latest builds.
