### ISSUE TITLE
Please Fix MySql Errors

### ISSUE THREAD

**Issue by JoeyPlayzTV** [lucko/LuckPerms#750]
Ever since I got your plugin my SERVER constantly crashes with a mysql exception of your plugin

This Error evry day evry Night  https://hastebin.com/vobabupoku.vbs

Please Fix

**Comment by lucko** [comment]
Not a LuckPerms issue.

Please see here for guidance:

https://github.com/lucko/LuckPerms/wiki/Storage-system-errors
https://github.com/lucko/LuckPerms/wiki/Storage-system-errors#mysql-exceeded-max-connections

**Comment by spannerman79** [comment]
```
The last packet successfully received from the server was 1,511,941 milliseconds ago.  The last packet sent successfully to the server was 1 milliseconds ago.)
[00:17:41] [Craft Scheduler Thread - 6855/WARN]: luckperms - Failed to validate connection com.mysql.jdbc.JDBC4Connection@ed438ab (Communications link failure
```

So let me get this right, you are too lazy/cbf'ed/ignorant to read your own log, do a little research and determine to "pass the buck" without checking your own setup thus placing the blame on **everyone** except yourself?

Here seeing as your too effing lazy and stupid - http://lmgtfy.com/?q=Failed+to+validate+connection+com.mysql.jdbc.JDBC4Connection

**Comment by lucko** [comment]
Please actually read what I've linked above.

It explains exactly what the issue is and what you need to do to fix it. (specifically the second link)

**Comment by JoeyPlayzTV** [comment]
what is your problem you just fix this mistake one

**Comment by lucko** [comment]
It's not a LuckPerms issue.

> Please actually read what I've linked above.

**Comment by JoeyPlayzTV** [comment]
I've done it all your licks do not bring you too stupid to program your own mysql you're a shame for spigot
https://github.com/lucko/LuckPerms/wiki/Storage-system-errors
https://github.com/lucko/LuckPerms/wiki/Storage-system-errors#mysql-exceeded-max-connections

**Comment by lucko** [comment]
That's not a very nice thing to say.

**Comment by JoeyPlayzTV** [comment]
Even Pex is better please fix this mistake
my database goes with each plugin only yours does not want to create it not even ne table

**Comment by lucko** [comment]
The issue is caused by your MySQL server, not LuckPerms. It tells you that in the error. :)

> Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: User 'ni883803_6sql7' has exceeded the 'max_user_connections' resource (current value: 30)

The wiki page I linked explains what you can do to resolve this.

**Comment by JoeyPlayzTV** [comment]
I now have a mysql on a VServer and get the following error please help me I like your plugin I'm mega angry because it is not working please

**Comment by JoeyPlayzTV** [comment]
https://hastebin.com/iribosixed.vbs

**Comment by JoeyPlayzTV** [comment]
here is my config with login and password you are welcome to log in to the database but please help me please

https://hastebin.com/qalububemo.coffeescript

**Comment by lucko** [comment]
Still not caused by LP. It's a driver error and **totally separate**.

Again, there are some things you can try on this page: https://github.com/lucko/LuckPerms/wiki/Storage-system-errors

For the last time, it is NOT a LuckPerms bug.
