### ISSUE TITLE
Ranks not Syncing

### ISSUE THREAD

**Issue by AleXutzZu** [lucko/LuckPerms#754]
So, I have 4 servers connected to the same database and they are called: lobby, practice, skyblock, factions. The thing is when I do for example /lp user AleXutzZu parent set owner the rank is applied only on lobby, practice and skyblock but on factions I remain the same. Why?

**Comment by Andre601** [comment]
Check, if BungeeCord and IP-forwarding are enabled on your Factions-Server.
You can find this options in the spigot.yml

**Comment by AleXutzZu** [comment]
Thanks!
