### ISSUE TITLE
Fake permission nodes

### ISSUE THREAD

**Issue by Pendragon1111** [lucko/LuckPerms#760]
For some reason, permissions keep getting corrupted while attached to players.
https://prnt.sc/ifs3zl

The red one used to be alone. I added the permission again, and it allowed me. Trying to click on it has me unset the perm... But when its only the red perm, it acts as if it isn't there.  This is something we've reported as happening with a duel plugin, and we had to wipe their playerdata to get them to go away.

Heres a copy of our config file in case its relevant: https://pastebin.com/jwZV3CTK

**Comment by lucko** [comment]
Which version of LP are you using?

**Comment by Pendragon1111** [comment]
Sorry, for some reason i wasn't recivving notifications from this report.
Version 4.0.18.

**Comment by lucko** [comment]
Can you try with the latest version please

https://ci.lucko.me/job/LuckPerms/

**Comment by Pendragon1111** [comment]
Updating removed the broken permission node from the user in question. The bug appears to be fixed; if it happens again i'll make another report. Thank you for the fast responses!
