### ISSUE TITLE
Add negative permission?

### ISSUE THREAD

**Issue by InflamedSebi** [lucko/LuckPerms#761]
Is there a way to remove a permission if the parent node was *?

like "nucleus.*" is given to admins, but they should not have "nucleus.vanish.onlogin"
In bukkit you could do something like adding "-nucleus.vanish.onlogin" as a node and it excluded that, even if * was set.

is there something similar here? If not would it be possible to add it?
(using the sponge one)

**Comment by Andre601** [comment]
LuckPerms handles negative permissions different than other plugins like PermissionsEx do.
Instead of adding a - in front of the permission, you need to set the value to `false`
eg: `/lp group owner permission set some.permission false`

**Comment by InflamedSebi** [comment]
that did the trick. awesome :)
