### ISSUE TITLE
Display ranks in playerlist

### ISSUE THREAD

**Issue by LlamaSenpai** [lucko/LuckPerms#762]
Hi, 

Is there a way to display the ranks in the player list (tablist) ? 
Like the plugin ColoredTags but I don't think it is compatible with LuckPerms :/ Do you know another plugin able to do that ? 

Thanks

**Comment by lucko** [comment]
ColoredTags should work - looks like you just need to make sure you have Vault installed.

Failing that, you could try NametagEdit?
