### ISSUE TITLE
groups and weights what is the correct usage

### ISSUE THREAD

**Issue by Ironic8b498** [lucko/LuckPerms#766]
I currently have 60 groups on my bungee network, these are my tracks, other then the track name being staff, griefer or hacker. the rest are tracks meant for just one server, the tracks with server names do not get used on more then the server it was made for. My issue is to make Uchat work right with so many groups in the players meta, where sometimes needing to call a group with lower weight. How I have done on my spigot/bukkit servers is Dchat allows me to use perms to assign the correct rank. Well sponge is so limited to what chat plugin I can use. Any suggestion on how to make this work would be great.

# Export track: sky
/lp track sky append bedrock
/lp track sky append dirt
/lp track sky append lava
/lp track sky append iron
/lp track sky append gold
/lp track sky append diamond
/lp track sky append grass

# Export track: mini
/lp track mini append spectator
/lp track mini append gamer

# Export track: survival
/lp track survival append recruit
/lp track survival append 0
/lp track survival append 1
/lp track survival append 2
/lp track survival append 3
/lp track survival append 4
/lp track survival append vip

# Export track: staff
/lp track staff append guard
/lp track staff append admin
/lp track staff append owner

# Export track: griefer
/lp track griefer append igrief
/lp track griefer append dolor

# Export track: creative
/lp track creative append adventure
/lp track creative append creative

# Export track: mmo
/lp track mmo append pleb
/lp track mmo append peasant
/lp track mmo append minion
/lp track mmo append meme
/lp track mmo append raider
/lp track mmo append guild
/lp track mmo append god

# Export track: hacker
/lp track hacker append ihack
/lp track hacker append corte

# Export track: lobby

# Export track: walkin
/lp track walkin append pikemen
/lp track walkin append armsmen
/lp track walkin append knight
/lp track walkin append earl
/lp track walkin append duke
/lp track walkin append lord
/lp track walkin append king

# Export track: forge
/lp track forge append warrior
/lp track forge append spartan
/lp track forge append demigod
/lp track forge append olympian
/lp track forge append legend
/lp track forge append kronos

# Export track: faction
/lp track faction append initiate
/lp track faction append mystic
/lp track faction append titan
/lp track faction append ender
/lp track faction append ultra
/lp track faction append hero
/lp track faction append mvp

# Export track: vanilla
/lp track vanilla append villager
/lp track vanilla append citizen
/lp track vanilla append traveler
/lp track vanilla append farmer
/lp track vanilla append miner
/lp track vanilla append hunter
/lp track vanilla append pro

**Comment by lucko** [comment]
Tracks do not control inheritance.

You need to add "parents" to groups to make them inherit from other groups.

https://github.com/lucko/LuckPerms/wiki/Command-Usage#lp-usergroup-usergroup-parent-add

**Comment by Ironic8b498** [comment]
I have the inherit set right, just can't get my chat plugin to work right, I added the weights above like I said one track is used for one server, and in the same track they inherit in order. issue is matching weights and higher weights for the chat plug to decide what prefix to display. I tried the custom-tag via perms works good for non op players, but op players gets all 6 custom tags and the prefix

**Comment by lucko** [comment]
Which chat plugin are you using?

How do you have it configured / setup?

**Comment by Ironic8b498** [comment]
sorry took so long to reply, I'm using UltimateChat-1.8.3-b97-Universal, I have the default-tag-builder="ch-tags,prefix,custom-tag,custom-tag1,custom-tag2,custom-tag3,custom-tag4,custom-tag5,custom-tag6,nickname,suffix,message" works fine for players, just for me being OP it don't work. yes the prefix displays correct when i check players info. https://www.dropbox.com/s/7aarb7fgui4r7i4/owner%20info.png?dl=0

**Comment by lucko** [comment]
Sounds like a configuration issue with your chat plugin then.

**Comment by Ironic8b498** [comment]
that's why I stopped checking this, since I felt I had Luckperm set right. but the dev of UChat has not been to helpful

**Comment by lucko** [comment]
Perhaps try with a [different plugin](https://github.com/lucko/LuckPerms/wiki/Prefixes,-Suffixes-&-Meta#displaying-prefixes-and-suffixes)?
