### ISSUE TITLE
How do I connect mysql

### ISSUE THREAD

**Issue by masri1** [lucko/LuckPerms#767]
Can someone tell me how to connect my lp plugin to my mysql database. I've read every article, and watched every video out there but still having a hard time.

**Comment by funniray** [comment]
1.) Make a MySQL server
2.) Make a database in the MySQL server
3.) Fill our the config in the database section of LuckPerms
4.) (Optional) Setup Redist or Bungeecord to sync permissions between servers

**Comment by masri1** [comment]
I did every thing but I'm having trouble doing step 3.

**Comment by funniray** [comment]
What is the error you're getting in the console? Does it say Authentication failed or anything like that?

**Comment by masri1** [comment]
Well I can't figure what to fill in for where it says "database: minecraft" do I leave it as minecraft or change it to something else

**Comment by funniray** [comment]
Leave it as Minecraft and I believe that LuckPerms will make a database if not, then you'll have to use the MySQL administrator prompt to create a database named "minecraft" and then try starting LuckPerms again.

**Comment by masri1** [comment]
The console is giving me this warning 

.02 13:36:16 [Server] WARN INFO com.zaxxer.hikari.pool.PoolBase - luckperms - Driver does not support get/set network timeout for connections. (com.mysql.jdbc.JDBC4Connection.getNetworkTimeout()I)
19.02 13:36:16 [Server] WARN INFO com.zaxxer.hikari.HikariDataSource - luckperms - Start completed.
19.02 13:36:16 [Server] WARN INFO com.zaxxer.hikari.HikariDataSource - luckperms - Starting...

**Comment by lucko** [comment]
Update to the latest version of LuckPerms
https://ci.lucko.me/job/LuckPerms/

... or don't - you can also just ignore the error. :)
