### ISSUE TITLE
Bungee perms

### ISSUE THREAD

**Issue by ucraft02** [lucko/LuckPerms#768]
I have problem with adding permissiont to luckperms.I add perms to bunge server but I can't use command

**Comment by funniray** [comment]
Is LuckPerms added on your Bungeecord server and are you using /bperm or /lpb for Bungeecord?

**Comment by Andre601** [comment]
LuckPermsBungee doesn't manage permissions of plugins on the spigot-Server. It only manages those on the BungeeCord (proxy)
You need to have the normal LuckPerms (or the sponge version, if you're using sponge...) installed on your server.

You should also check the following pages:
[Where do I install LuckPerms?](https://github.com/lucko/LuckPerms/wiki/FAQ#where-do-i-install-luckperms)
[Can I just install LuckPerms on BungeeCord?](https://github.com/lucko/LuckPerms/wiki/FAQ#can-i-just-install-luckperms-on-bungeecord) and maybe
[How do I get permissions to sync across multiple servers](https://github.com/lucko/LuckPerms/wiki/FAQ#how-do-i-get-permissions-to-sync-across-multiple-servers)

**Comment by ucraft02** [comment]
I can't use /lpb and I have luckperms on spigot and bungee server and both are conected to mysql

**Comment by ucraft02** [comment]
what perm I need to use /lpb

**Comment by funniray** [comment]
In the console of bungee do `lpb user <user> permission set *` and then work from there.

**Comment by ucraft02** [comment]
Now I now I add perms ./lp group owner perm true bungee

**Comment by ucraft02** [comment]
I didn't use lpb.
Thanks.
