### ISSUE TITLE
Nukkit Resource Page

### ISSUE THREAD

**Issue by augesrob** [lucko/LuckPerms#769]
@lucko

Can you take over the resource page itself on our website?
I posted it but wanted to give you the resource itself.

https://nukkitx.com/resources/luckperms.51/

Just sign up on the website and once I see your name ill reassign the plugin to you.

**Comment by lucko** [comment]
https://nukkitx.com/members/luck.60/

**Comment by augesrob** [comment]
All Done Thanks 👍 

Thanks this is a great plugin, I use it on my spigot bungee network aswell

**Comment by lucko** [comment]
:)
