### ISSUE TITLE
Prefix has been set but does not show (NukkitX)

### ISSUE THREAD

**Issue by AlekEagleYT** [lucko/LuckPerms#773]
![captufre](https://user-images.githubusercontent.com/20604190/36400287-411c58ea-158d-11e8-9449-14cd2a305da4.PNG)

I just cleared and reapplied the prefix but the prefix doesn't show in chat.

**Comment by lucko** [comment]
LuckPerms doesn't format the chat for you - you need to install a chat formatting plugin.

I'm not aware of one that exists for Nukkit. Is there a standard API to provide prefix/suffix data, like Vault for the Bukkit project?

p.s. I try to keep the issues on GitHub free of questions - and tend to close such tickets as soon as an answer has been given. We have a [Discord server](https://discord.gg/W3FzxHA) which you might find to be a better place to ask questions.

**Comment by AlekEagleYT** [comment]
thank you for replying after my two other non-relevant issues, and i will be on a lookout for a plugin like that.
