### ISSUE TITLE
World inherit permission

### ISSUE THREAD

**Issue by Loonyy** [lucko/LuckPerms#774]
Hey; just struggling with something - How do I make it so that the nether inherits the main survival world's permissions?

**Comment by Andre601** [comment]
A group should have permissions in all worlds by default, as long as you don't set any world-context to it.

I'm not sure, if I really understand, what you want (and would be happy, if you could explain it a bit more and maybe with one or two examples).

**Comment by lucko** [comment]
https://github.com/lucko/LuckPerms/wiki/Configuration#world-rewrite
