### ISSUE TITLE
Support for Factions-For-Nukkit?

### ISSUE THREAD

**Issue by NycuRO** [lucko/LuckPerms#778]
? 👍 

https://github.com/Nukkit-coders/Factions-For-Nukkit

Plugin uses [FACTION] tag.
If you use them tag on chat format, 99% plugins permission bug chat with them. 

So, can you fix that? 👍 
Test yourself :)

**Comment by lucko** [comment]
LuckPerms is not a chat formatting plugin.

**Comment by NycuRO** [comment]
Why not add this option to support for prefix, suffix?

**Comment by lucko** [comment]
Because LuckPerms is a permissions plugin, not a chat formatting plugin.   
You need a chat formatting plugin in order to format the chat.

See #773
