### ISSUE TITLE
Error with newest version on loading

### ISSUE THREAD

**Issue by Pendragon1111** [lucko/LuckPerms#779]
I feel like this may be a user error, but i can't really figure out what i could have done wrong. All i did was delete the old jar i had (4.0.80) and place in the new one (4.0.141), then restart. 

When logging in, i get this error. http://prntscr.com/ihjaoh
When starting up the server, i get this error: https://pastebin.com/j7dgZ4kk

(A note; this was not on the same server as my previous issue was. The other server did not have the same issue.)

**Comment by lucko** [comment]
Looks like your Java install might've corrupted?

**Comment by Pendragon1111** [comment]
Possibly. I'm using a local host for this one and i've been having an error with java loading my voxelsniper.jar as well... By chance do you know how i might be able to fix it?

My run.bat is 
```JAVA -Xmx1024M -Xms1024M -jar spigot.jar```

**Comment by lucko** [comment]
Uhh, I'd just reinstall Java on your machine

**Comment by Pendragon1111** [comment]
Done, and same issue.

**Comment by spannerman79** [comment]
> When starting up the server, i get this error: https://pastebin.com/j7dgZ4kk

Need a full server log not a snip.

If you did indeed purge java fully and install java 8 again then either;

- Your using craftbukkit - switch to spigot at least
- your server jar is FUBAR - obtain it again manually and transfer it to your VPS/dedi

**Comment by Pendragon1111** [comment]
I did purge java fully, and reinstalled. I am not using craftbukkit, i'm using spigot. 

I redownloaded it via buildtools once more and while doing this actually fixed my voxelsniper issues, it did not fix the luckperms errors.

The "snip" is the full error in relation to luckperms, and currently the only error in my console. The rest of the server log is just a bunch of other plugins loading.

**Comment by lucko** [comment]
Which Java version did you install?

**Comment by Pendragon1111** [comment]
http://prntscr.com/ihvzgx
Appears Java 8, update 161.

**Comment by lucko** [comment]
I have no idea then

**Comment by spannerman79** [comment]
I cannot reproduce this on a VPS or a dedi (I have both)

A quick spin up of a DigitalOcean droplet (Ubuntu 16.04), grabbing java via ppa ( `add-apt-repository ppa:webupd8team/java` yeah i know lazy but wanted to quickly test) grabbing spigot via buildtools and running the built spigot server on the droplet with latest Luckperms ( https://ci.lucko.me/job/LuckPerms/lastSuccessfulBuild/artifact/bukkit/target/ ) works straight away (h2)

Changing to mysql and starting the server up again has no issues with the change in storage db

@Pendragon1111 your issue is your actual server - not luckperms itself - unable to reproduce.

**Comment by lucko** [comment]
Agreed with spannerman - I don't see how this can be caused by LP.

**Comment by lucko** [comment]
@Pendragon1111 Was the issue resolved by switching back to Java 8?

The same thing problem was reported here (#815) and was traced back to a problem in Java 9. Does that help you in any way?

**Comment by Pendragon1111** [comment]
I resolved it by downgrading back to version i had prior to updating. I have since moved away from my local host, and am no longer having the issue with java. 

Thank you for letting me know about the potential fix, though. If it happens again i will try it.
