### ISSUE TITLE
[Request] New Placeholder

### ISSUE THREAD

**Issue by SpaicyGaming** [lucko/LuckPerms#789]
Can you add the following placeholder?
%luckperms_group_name_capitalized% 
For example: If I'm in the group "owner" the placeholder will show "Owner"

**Comment by Andre601** [comment]
You can change the displayname of the group to Owner in LuckPerms and use %vault_group%

**Comment by lucko** [comment]
@SpaicyGaming Does that ^^ do what you need?

**Comment by SpaicyGaming** [comment]
Yes, I didn't think about that.
