### ISSUE TITLE
not detecting vault

### ISSUE THREAD

**Issue by dalton62398** [lucko/LuckPerms#790]
i have vaults latest version installed and i keep getting an error code in console saying its not installed...

**Comment by Andre601** [comment]
What "error code"?

We can't read minds and would be happy, if you could provide us with more informations

**Comment by dalton62398** [comment]
23.02 20:39:14 [Server] WARN Detected supported permissions plugin LuckPerms without Vault installed.
23.02 20:39:14 [Server] WARN Features such as chat prefixes/suffixes and group-related functionality will not work until you install Vault.

**Comment by lucko** [comment]
That's not a LuckPerms error message.

You need to make sure you have the Vault plugin installed and that it has enabled correctly.

**Comment by dalton62398** [comment]
it works with every other plugin thats why im inquiring about it

**Comment by lucko** [comment]
> That's not a LuckPerms error message.
You need to make sure you have the Vault plugin installed and that it has enabled correctly.


Whatever plugin is printing the message has obviously detected LuckPerms - it's saying that it can't find an installation of Vault.

**Comment by lucko** [comment]
A quick Google search shows that the message is being sent by Essentials.

https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/perm/PermissionsHandler.java#L133-L138

Nothing to do with LP.

**Comment by dalton62398** [comment]
alright its just weird because the message before it has vault interacting with another plugin

**Comment by dalton62398** [comment]
ty

**Comment by dalton62398** [comment]
23.02 20:39:10 [Server] INFO Loading LuckPerms v4.0.80
23.02 20:39:10 [Server] ERROR sender initializing LuckPerms v4.0.80 (Is it up to date?)
23.02 20:39:10 [Server] INFO java.lang.NullPointerException: sender
23.02 20:39:10 [Server] INFO at me.lucko.luckperms.common.commands.sender.SenderFactory.wrap(SenderFactory.java:63) ~[?:?]
23.02 20:39:10 [Server] INFO at me.lucko.luckperms.bukkit.LPBukkitPlugin.getConsoleSender(LPBukkitPlugin.java:522) ~[?:?]
23.02 20:39:10 [Server] INFO at me.lucko.luckperms.bukkit.LPBukkitPlugin.onLoad(LPBukkitPlugin.java:154) ~[?:?]

23.02 20:39:10 [Server] INFO Enabling LuckPerms v4.0.80
23.02 20:39:10 [Server] ERROR Error occurred while enabling LuckPerms v4.0.80 (Is it up to date?)
23.02 20:39:10 [Server] INFO java.lang.NullPointerException: sender
23.02 20:39:10 [Server] INFO at me.lucko.luckperms.common.commands.sender.SenderFactory.wrap(SenderFactory.java:63) ~[?:?]
23.02 20:39:10 [Server] INFO at me.lucko.luckperms.bukkit.LPBukkitPlugin.getConsoleSender(LPBukkitPlugin.java:522) ~[?:?]
23.02 20:39:10 [Server] INFO at me.lucko.luckperms.bukkit.LPBukkitPlugin.enable(LPBukkitPlugin.java:185) ~[?:?]
23.02 20:39:10 [Server] INFO at me.lucko.luckperms.bukkit.LPBukkitPlugin.onEnable(LPBukkitPlugin.java:175) ~[?:?]



sorry i missed this

**Comment by lucko** [comment]
See here
https://github.com/lucko/LuckPerms/wiki/Setup#compatibility

**Comment by dalton62398** [comment]
okay thank you

**Comment by dalton62398** [comment]
good stuff that fixed it
