### ISSUE TITLE
Web interface update request

### ISSUE THREAD

**Issue by RFlintstone** [lucko/LuckPerms#793]
Hi,

Im using luckperms for 2 days now and it works like a charm (at least, after i fixed the prefixes with some help). Anyway, i like the editor function and it might be cool to let the administrators / people who have access to the editor see the groups in a kind of list.
Example: https://bootsnipp.com/snippets/featured/todo-example

And with an extra permission allow them to delete (certain) groups and restrict groups to certain servers on that same page.

Keep up the good work and have a nice day,
Ruben

**Comment by Andre601** [comment]
There's `/lp editor` which lets you edit all groups (and users afaik) in the same editor...

Here's a example:
![](https://thumbs.gfycat.com/ColdAbandonedBrahmanbull-size_restricted.gif)

**Comment by RFlintstone** [comment]
Yes but you can't remove it fron there.  It would be much nicer if that kind of function was added.

-Ruben

**Comment by lucko** [comment]
I've moved the suggestion to the appropriate repo

https://github.com/lucko/LuckPermsWeb/issues/41
