### ISSUE TITLE
This plugin crashes my server!

### ISSUE THREAD

**Issue by RamboIcsDee** [lucko/LuckPerms#796]
![untitled](https://user-images.githubusercontent.com/36813453/36640652-2348a2f0-1a1b-11e8-8072-19307e9a1889.png)

**Comment by pozzzzy** [comment]
Provide more information, such as:
 - server version
 - server type
 - plugin version

Also, make sure you're running the latest version of the plugin.

**Comment by RamboIcsDee** [comment]
I run ultimate version of this plugin on ultimate version of nukkit.

**Comment by lucko** [comment]
Use the latest version of NukkitX.
