### ISSUE TITLE
Grant permissions to people with spaces in their name? (NukkitX)

### ISSUE THREAD

**Issue by AlekEagleYT** [lucko/LuckPerms#798]
![regonised](https://user-images.githubusercontent.com/20604190/36647377-f39ca9e4-1a41-11e8-97f5-69f2e970c2ba.PNG)
I can't grant my friend permissions because it thinks that it's a separate arguement in the command, doesn't work with quote symbols, or declaring a symbol with `/lp user user\ name`

**Comment by spannerman79** [comment]
Because you cannot have a space in a mc name

https://namemc.com/name/squirtle%20fanboy

Your "friend" is either full of crap, pulling your leg or your running a cracked server.

**Comment by lucko** [comment]
Bedrock clients allow spaces in usernames

**Comment by lucko** [comment]
The error message you're getting actually has nothing to do with the username.

`parent friend` isn't a command. Perhaps you meant `parent add friend`?

**Comment by AlekEagleYT** [comment]
But the command `/lp user "squirtle fanboy" permission set nukkit.* true` doesn't work either.

**Comment by merjilin** [comment]
Set `allow-invalid-usernames` to true in your config and restart the server. Luck's commit above will make thay default for new installations.
