### ISSUE TITLE
Server grouping

### ISSUE THREAD

**Issue by Mikgreg** [lucko/LuckPerms#799]
Hi!

I just wanted to get a little bit more information on functionality that I'd need to be able to move over to this plugin, currently my permissions setup with Pex allows me to send permissions to a specific subset of servers, for example I can set a permission on all my Skywars severs, that wont affect anything else on the network.

I notice this plugin allows you to do server-specific perms, but it seems to be one only, would it be possible to configure groups of servers so i can send perms to the skywars group for example?

Thanks!

**Comment by spannerman79** [comment]
https://github.com/lucko/LuckPerms/wiki/Context

**Comment by lucko** [comment]
^^ 👍
