### ISSUE TITLE
Suggestion: Display permissions with pagination

### ISSUE THREAD

**Issue by M9GLiquid** [lucko/LuckPerms#80]
Display the permissions with the help of pagination.

I personally have groups with more than 100 permissions (yes, I know, alot)
and I can only display about ~90 of them.

Regards,
Thomas

**Comment by Slind14** [comment]
As a work around, use the console and if you are limited by a webinterface, the log contains them all.

**Comment by lucko** [comment]
Yeah - this is going to be pretty hard to do.

I'm really against adding a page based system, as it makes it really hard to see all of your permissions at a glance.

Any ideas on how it could be done?

**Comment by Slind14** [comment]
I suppose the command could be extended to:

`/perm u p i <items-per-page> <page-number>`

**Comment by lucko** [comment]
Huh, I guess that could work. Still not great though. I'd rather try do something like the Sponge Pagination system. Idk.

**Comment by M9GLiquid** [comment]
don't know anything about what you can do with the spongeAPI but you could add a JSON text at the bottom of the output with a JSON Hover/Click event for "<< Previous Page || Next Page >>
Would be rather sleek for the user and no real addition on commands altho it would need abit of coding for it (Perhaps add Fanciful(if work with sponge) to overcome the code issue)
