### ISSUE TITLE
Not compatible with waterfall?

### ISSUE THREAD

**Issue by Mikgreg** [lucko/LuckPerms#800]
Hi!

Trying to install this on my Bungeecord proxy, I use a fork called Waterfall found here:
https://aquifermc.org/

This error happens on Bungee load:
https://pastebin.com/6UYRF9uf

Let me know if I'm doing something wrong, thanks!

**Comment by merjilin** [comment]
You're attempting to load the Bukkit version on the Bungee server. You need to grab LuckPerms-Bungee from here https://ci.lucko.me/view/LuckPerms/job/LuckPerms/ for bungeecord :)
