### ISSUE TITLE
The editor error

### ISSUE THREAD

**Issue by ArtNRG** [lucko/LuckPerms#801]
Tested commands: 
- /lp group ... editor
- /lp editor
- /lp user ... editor

The website shows me Loading... message few minutes and after a while, there is an error "Error loading data! Please check the url was copied correctly."

Tested on LuckPerms 4.1.1 and LuckPerms v4.1.9.
I use a mySQL database.

Few editor links with this error:
https://luckperms.github.io/editor/?bfYOa8UQoH
https://luckperms.github.io/editor/?gDM4kAm0JS

**Comment by Nighko** [comment]
Works fine for me :P

**Comment by Andre601** [comment]
Maybe the browser is incompatible with the editor.
Did you test it with different browsers?
And did you just open it directly through the game, or by copy-pasting it?

**Comment by lucko** [comment]
Works fine for me as well. :)

If you hit the F12 key, you can see the full loading error in the Console.

**Comment by lucko** [comment]
p.s. editor issues live here https://github.com/lucko/LuckPermsWeb

**Comment by ArtNRG** [comment]
F12 key helped me to find the problem. I'm from Russia and here we have the one stupid gov organization that blocks IP addresses of illegal websites. As you know, IP can be changed and now we suffer from blocking the legitimate data. 
The editor wasn't working for me because of connection error with bytebin.lucko.me. The IP address of that website is contained at gov stupid blacklist. English isn't my native language so it's difficult to me to explain all about our gov methods to fight against the piracy on the internet, but you can find all you want using the words like "Roskomnadzor Russia".

**Comment by lucko** [comment]
Ah okay yeah.

I assume Cloudflare is blocked then?

**Comment by ArtNRG** [comment]
Yep, lots of Cloudflare IPs are blocked too. I wish once somebody tell them how it actually works.
bytebin.lucko.me is using IP address 104.27.151.106. Here you can find the information about blocking that IP:
https://reestr.rublacklist.net/rec/294649/
https://reestr.rublacklist.net/rec/231012/

**Comment by lucko** [comment]
Sorry! not much I can do about that, as I'm sure you know :)

**Comment by ArtNRG** [comment]
Do not worry, I already find the way to use this editor. We have the joke about Russian laws: The severity of laws is compensated by the non-mandatory nature of their execution :) Sad but true.
