### ISSUE TITLE
Suggestion: Allow a Self Hosted web based editor

### ISSUE THREAD

**Issue by PenguinNexus** [lucko/LuckPerms#802]
Could you please allow a self hosted Website interface to be created, so that the web based editor can be hosted on our own domains?

If you could make it so it can be logged into in some way, then people on my staff team can then edit permissions for users.

It would be awesome if you could do this, thanks!

**Comment by Andre601** [comment]
I don't know how luck sees this, but I can't see any benefit of that for either LuckPerms or anyone else.

**Comment by lucko** [comment]
You can already self-host the site, but you'll need to make your own changes to have a login system for it.   
The source code is here, https://github.com/lucko/LuckPermsWeb

> I don't know how luck sees this, but I can't see any benefit of that for either LuckPerms or anyone else.

Agreed, so it's up to you to implement the change if you want that.

**Comment by PenguinNexus** [comment]
Cheers, I'll look into it, thank you!
