### ISSUE TITLE
Can't connect to my PostgreSQL db

### ISSUE THREAD

**Issue by uncleSetRick** [lucko/LuckPerms#804]
[error.txt](https://github.com/lucko/LuckPerms/files/1769379/error.txt)

LP version v4.1.10
SpongeAPI: 7.1.0-SNAPSHOT-6aa4e43 - SpongeForge: 1.12.2-2611-7.1.0-BETA-2931

console log in .txt file
I don't know what to do
I haven't tried to use other db's, but it works with default h2 and with yaml 100%

**Comment by lucko** [comment]
Please update to the latest version of LuckPerms.

**Comment by lucko** [comment]
Delete the `characterEncoding` property from the config file.
