### ISSUE TITLE
Creating an editor-session from the console does not work

### ISSUE THREAD

**Issue by JustDJplease** [lucko/LuckPerms#807]
Hello!

Recently, I've tried to setup my permissions with the editor. (First, using the per-group editor from older versions, and now the complete editor that was just released) If I create a session for the editor ingame with the /lp editor command, everything goes fine. A link is created and I can modify the permissions in my browser. If I, however, execute the command from the console, there too a url is created, but opening that will lead to a 404 page on the github.io page (Example: https://luckperms.github.io/editor/NCcWNgqu3)

I am using spigot version 1.12.2 (build about 3 weeks ago) and the last version of luckperms (4.1.1)

**Comment by lucko** [comment]
There's a known issue with Multicraft stripping characters out of the url.

The format should be like this:   
`https://luckperms.github.io/editor/?<code goes here>`

Unfortunately there's not anything I can do to stop this from happening. You could try reporting the issue to Multicraft.

**Comment by JustDJplease** [comment]
Aha right. The question mark is indeed missing in the URL. Ill make a report on this! Thanks for your quick response!
