### ISSUE TITLE
Stack temporary group membership

### ISSUE THREAD

**Issue by hegedex** [lucko/LuckPerms#808]
I'd love, if the plugin would support stacking of temporary group memberships.
So when I add someone to group _premium_ for 1 week (addtemp) and then, on the next day, I add the same player to group _premium_ for another week, that this player is in group _premium_ for 13 days from now on (because one day is already over).

**Comment by lucko** [comment]
https://github.com/lucko/LuckPerms/wiki/Configuration#temporary-add-behaviour

or

https://github.com/lucko/LuckPerms/wiki/Command-Usage#lp-usergroup-usergroup-parent-addtemp
