### ISSUE TITLE
LuckPerms-Sponge-4.1.17.jar and higher not work in spongeforge

### ISSUE THREAD

**Issue by ziceptor** [lucko/LuckPerms#810]
https://gist.github.com/ziceptor/0158dcf8620f3cb06d4cf601cabff1e2

forge-1.12.2-14.23.2.2611-universal.jar
spongeforge-1.12.2-2611-7.1.0-BETA-2931.jar
LuckPerms-Sponge-4.1.18.jar

**Comment by DrZoddiak** [comment]
![capture](https://user-images.githubusercontent.com/9203727/36938775-71a7e35e-1eec-11e8-8377-ad5ddc64f901.PNG)
being fixed now :)
