### ISSUE TITLE
[Suggestion] Changing name of default group

### ISSUE THREAD

**Issue by funniray** [lucko/LuckPerms#811]
For some people, they like having a different group name. I don't know why people like having different default group names, but they just do for some reason. I know that it is possible to use rules to give them another group on login, but some people don't want to go to that extent to give them that group.

**Comment by spannerman79** [comment]
https://github.com/lucko/LuckPerms/blob/master/bukkit/src/main/resources/config.yml#L387...L463

**Comment by lucko** [comment]
You can use `/lp group <group> setdisplayname`

https://github.com/lucko/LuckPerms/wiki/Command-Usage:-Group#lp-group-group-setdisplayname
