### ISSUE TITLE
[Suggestion/Help Request] Control over certain groups

### ISSUE THREAD

**Issue by VulpusMaximus** [lucko/LuckPerms#813]
So, I know that PermissionsEX has partially got this feature, but I can't find it on here. Is there a way of making it so <Group A> can control who is in <Group B>, but no other groups, and that they can only promote people on a set track? Perhaps even promoting/demoting people to/from a set group on a set track? How much of this is already possible, and if it is not possible, it is my suggestion that it be considered as a new feature.

**Comment by VulpusMaximus** [comment]
As context for this, what I want to be able to do is have the group headmod be able to control who is in the groups moderator and trialmod, while headadmin would be able to control who is in the groups admin and senioradmin. If at all possible, headmod could promote people to mod and trialmod and demote them, but not promote them further than moderator, while headadmin would be able to promote people to admin and senioradmin and demote them all the way down to moderator, but no further.

As an example of what the permissions would look like for this:

Headmod:
    luckyperms.group.promote.stafg.trialmod --This would allow headmod to promote people who are trialmod in the staff track.
luckyperms.group.demote.staff.moderator --This one obvious from the previous. 
luckyperms.user.parent.trialmod --Would allow headmod to control who is in the group trialmod
<same but for moderator>

**Comment by VulpusMaximus** [comment]
Alternatively, allow for promotion/demotion in a specific track, but the user would only be able to promote people to/from groups they have control over, ie.

luckyperms.track.promote.staff
luckyperms.group.trialmod.members

**Comment by VulpusMaximus** [comment]
I've just been looking through the closed tickets and I believe that I have found what I am looking for, but I do not know if it would work in this context

**Comment by lucko** [comment]
Yep, all of that is possible already :)

Some of the permissions you suggested match the ones which are actually implemented. It's all explained here: https://github.com/lucko/LuckPerms/wiki/Argument-based-command-permissions
