### ISSUE TITLE
[Suggestion] Copy all data from one account to another

### ISSUE THREAD

**Issue by iaxedu** [lucko/LuckPerms#814]
Hello,

I would like to request to be able to copy all data from one account to another. This includes prefixes, permission and groups. This allows for easier testing since I use luckperms permissions for all kinds of cooldowns, upgrades and personal settings. This also allows me to transfer a rank to another account. 

Example:
/lp user <name> copy <newname>

I couldn't find this function in the WIKI so sorry if this was already implemented.

**Comment by VulpusMaximus** [comment]
You could simply create a group with all of these permissions and parent groups, etc. and add users to this group, could you not? And then if you wish to make a copy you could /lp group <group> clone

**Comment by lucko** [comment]
`/lp user <user> clone <user>`

You're right it wasn't on the wiki - but it's added now.
