### ISSUE TITLE
Permissions data could not be loaded. Please try again later. (BungeeCord Version) 

### ISSUE THREAD

**Issue by LlamaSenpai** [lucko/LuckPerms#816]
Hello, I currently have a problem when I try to set up a BungeeCord with Luckperms. I receive the following message when I log in to one of my servers (via BungeeCord): Permissions data could not be loaded. Please try again later.

Both servers and my Bungeecord proxy are connected to the same database and the IP forwarding  is setup and configured correctly. 

The logs of my servers are ok (no errors) but I get this in the logs of my BungeeCord : https://hastebin.com/loremelota.sql

Do you have a solution ? 

Thanks ! :)

**Comment by lucko** [comment]
The LP instance on BungeeCord can't connect to your database

```
Caused by: java.sql.SQLException: Access denied for user ''@'62-210-162-226.rev.poneytelecom.eu' (using password: NO)
```

It's not an LP error - but there is some guidance here:
https://github.com/lucko/LuckPerms/wiki/Storage-system-errors
