### ISSUE TITLE
Luckyperms having a delay before doing commands

### ISSUE THREAD

**Issue by nessie2013** [lucko/LuckPerms#818]
Hello

i have been using luckperms for about a month.  Recently whenever i do any command in luckperms there is a large delay (10 seconds to 2+ minutes) before getting any feedback (e.g getting player info, group changing.) nothing i do fixes this problem so i think it's something to do with the plugin (server restarts, installing the plugin,) it's also not my connection to the server.

any help would be appreciated

nessie

**Comment by Nighko** [comment]
Please update to the latest version of luckperms

**Comment by Nighko** [comment]
If this does not solve your problem look for errors in the console.

**Comment by nessie2013** [comment]
im running the latest version and no errors come up in the console

**Comment by lucko** [comment]
It'll be down to the speed of your database / the connection between your server and the database.

It's definitely not a LuckPerms issue.

**Comment by nessie2013** [comment]
after finding the debug command i ran a debug and got these errors not sure if they have anything to do with my problem

`12.03 12:12:10 [Server] WARN at java.lang.Thread.run(Thread.java:745)
12.03 12:12:10 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
12.03 12:12:10 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
12.03 12:12:10 [Server] WARN at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
12.03 12:12:10 [Server] WARN at me.lucko.luckperms.common.commands.CommandManager.lambda$onCommand$0(CommandManager.java:146)
12.03 12:12:10 [Server] WARN at me.lucko.luckperms.common.commands.CommandManager.execute(CommandManager.java:201)
12.03 12:12:10 [Server] WARN at me.lucko.luckperms.common.commands.abstraction.SingleCommand.execute(SingleCommand.java:43)
12.03 12:12:10 [Server] WARN at me.lucko.luckperms.common.commands.abstraction.SingleCommand.execute(SingleCommand.java:51)
12.03 12:12:10 [Server] WARN at me.lucko.luckperms.common.commands.impl.misc.DebugCommand.execute(DebugCommand.java:95)
12.03 12:12:10 [Server] WARN at me.lucko.luckperms.common.commands.impl.misc.DebugCommand.getPlayersData(DebugCommand.java:198)
12.03 12:12:10 [Server] WARN at me.lucko.luckperms.common.utils.gson.JObject.add(JObject.java:65)
12.03 12:12:10 [Server] WARN at me.lucko.luckperms.common.commands.impl.misc.DebugCommand.lambda$getPlayersData$6(DebugCommand.java:205)
12.03 12:12:10 [Server] WARN at me.lucko.luckperms.common.commands.impl.misc.DebugCommand.serializeMetaData(DebugCommand.java:246)
12.03 12:12:10 [Server] WARN at me.lucko.luckperms.common.utils.gson.JObject.add(JObject.java:49)
12.03 12:12:10 [Server] WARN at com.google.gson.JsonPrimitive.<init>(JsonPrimitive.java:65)
12.03 12:12:10 [Server] WARN at com.google.gson.JsonPrimitive.setValue(JsonPrimitive.java:101)
12.03 12:12:10 [Server] WARN at com.google.gson.JsonPrimitive.isPrimitiveOrString(JsonPrimitive.java:278)
12.03 12:12:10 [Server] WARN java.lang.NullPointerException`
