### ISSUE TITLE
Add filter options for search, perm info, meta info

### ISSUE THREAD

**Issue by voodootje0** [lucko/LuckPerms#819]
Would it be possible to a filter system for several commands:
`/lp search [filter]` so when you type `/lp search server=prison` only all results where the `server=prison` will be returned. Also for `/lp user/group <user> perm info` and `/lp user/group <group> meta info`  filters should be added.

**Comment by lucko** [comment]
It is already possible to sort the output to `permission info` and `parent info`, by adding a "sort" flag to the end of the command.

Currently valid is:

* `reversed`
* `priority` (sort by priority)
* `!priority` (sort by priority in reverse)
* `abc` (sort alphabetically)
* `!abc` (sort alphabetically in reverse)

I don't think adding options to further filter those results makes sense. The syntax would become too complicated.

I think using the general `/lp editor` as a way to view data is a better solution, as you can more easily sort and view information in bulk.

However, I agree with adding filters to the `/lp search` commands - the results to which can't be viewed easily in a browser.

**Comment by voodootje0** [comment]
I'm sure that contexts will be better than the sorting flags you listed above. If you don't agree, plese add another command that will make it possible like `/lp user <user> permsearch [context filter]`

About the editor, it's a really good feature in luckperms to manage perms. However, if you have 15+ different gamemodes that result in total more than 2000+ different permissions for group default, is using the web editor pretty unclear.

**Comment by lucko** [comment]
New editor makes implementing these changes unnecessary.
