### ISSUE TITLE
Players have 'default' group in addition to other groups

### ISSUE THREAD

**Issue by Trikolon** [lucko/LuckPerms#820]
Some of my players have the group `default` in addition to other groups. Is this normal?
People on Discord told me that players only have the `default` group when they have no other group assigned.

Example of user with default group:
```
lpb user ExampleUser info
Parent Groups:
 > default
 > ultimate10  (server=survival)
 > vip
```

If this is not the expected behavior, how can I go back to a consistent state?
What would happen if I ran a bulk-update command to remove the permission `group.default` for all users? Would that fix it or could it cause issues?

I've imported my database from PermissionsEx.

**Comment by VulpusMaximus** [comment]
This shouldn't cause any issues, but you should be abl safely remove default as a parent to players. As long as one of their other groups inherits from default somewhere down the line, they will still have those permissions anyway.
