### ISSUE TITLE
Ranks across server

### ISSUE THREAD

**Issue by NeutralPlasma** [lucko/LuckPerms#821]
Hello i have problem i setuped server i made bungee and spigot. But when i change like rank of player on one server it doesnt update on other server how to fix that.
Spigot luckperms config: https://pastebin.com/XZNSbG5F
Bungee luckperms config: https://pastebin.com/Uyytnipv

**Comment by Andre601** [comment]
Your issue is, that both plugins aren't connected to the same Database.
Ranks will only update accross servers, if they share the same Database (like f.e. MySQL).

Read the [Network installation page](https://github.com/lucko/LuckPerms/wiki/Network-Installation) for more information.

**Comment by NeutralPlasma** [comment]
I think i found out i forgot to set to mysql instead of h2 but when i change to mysql it says it cannot connect to mysql service i checked if i put in right info and i did im gonna ask my mysql hoster if there is connection problem

**Comment by Andre601** [comment]
Had the same issue once....
Try to change the adress to 127.0.0.1 (IP for localhost if your MySQL is on the same server)

**Comment by NeutralPlasma** [comment]
still doesnt work it says its connected

**Comment by NeutralPlasma** [comment]
i have question how can i saved info as H2 transfer to mysql?

**Comment by BrainStone** [comment]
Check the „Changing Storage Type“ page on the wiki ;)
