### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by ziceptor** [lucko/LuckPerms#824]
/lp group default meta set griefprevention.min-claim-size-basic-x 5
https://gist.github.com/ziceptor/5567d0a2993ec37904da886d399fd8ab

forge-1.12.2-14.23.2.2611-universal.jar
spongeforge-1.12.2-2611-7.1.0-BETA-2931.jar
LuckPerms-Sponge-4.1.29.jar
griefprevention-1.12.2-4.3.0.562.jar

**Comment by SirYwell** [comment]
I assume it was already reported in #823 and #822

**Comment by ziceptor** [comment]
The situation is not identical. But may have the same root. The more information, the easier it is for the developer to understand the origins of the problem. Sorry for bad English.
