### ISSUE TITLE
Failsafe - Feature/enhancement Request

### ISSUE THREAD

**Issue by Nighko** [lucko/LuckPerms#825]
I was wondering if it's possible to add a local file based failsafe. A backup really.

So that if my MySQL database is down it won't affect gameplay.

**Comment by lucko** [comment]
Inconsistent state is bad.   
In my opinion the best solution is to deny all logins until the database comes back online.

I don't like the idea of a "fallback" - it shouldn't be necessary if you have your database setup correctly.

plus: other plugins are likely to experience issues if the DB is down anyways.
