### ISSUE TITLE
Disable fly in the end

### ISSUE THREAD

**Issue by Sikatsu** [lucko/LuckPerms#827]
I tried disabling fly within the end, however it's easy bypassable. If you jump in the void and relog before you die your fly will be enabled.

This is how the permissions are setup: 

http://prntscr.com/iq7cnl

This is a debug from essentials: 

https://gist.github.com/Sikatsu/6d6ae8c56b9060ac32797b933e9f324d

/lp debug gives me an error however: 

https://pastebin.com/ueqcNuRF

**Comment by xCykrix** [comment]
This is not a problem with LuckPerms. "safelogin" automatically gives you fly on login if you are in the air due to essentials.

**Comment by Sikatsu** [comment]
But ''safelogin'' is set to false for The End. 

At essentials github they said:

> As I said, this is likely due to the fact that LP can't determine what world you're in when you may not have even spawned yet, so I doubt there's anything we can do.

**Comment by xCykrix** [comment]
Hm, this would be for Luck to look at. However as far as I know, this plugin all your permissions in "pre-login" so it should be able to check the permission.
Are you 100% sure the world is named how you have it? caps and all?

**Comment by Sikatsu** [comment]
It's definatly called ''world2_the_end''. 
Flying indeed doesn't work in the end, except for safelogin when you jump in the void and relog.

**Comment by xCykrix** [comment]
Hm, I do not know then. I haven't gotten way into the nitty-gritty of this plugin yet. It appears like the world should have the ability to be seen.

I'm unsure at what point it applies world-based permissions over global. However you can see the world programmatically at the same point that the players full data is available.

**Comment by md678685** [comment]
For the record, the DelayedJoinTask is scheduled to run asynchronous when the player logs in. I don't think the player will necessarily be in a world when EssentialsX would be doing its permissions checks, including safelogin.

I don't think the permissions check issue can be fixed on either end, but I asked @Sikatsu to report the stack trace they were receiving with `/lp debug` not the permission check issue.

**Comment by md678685** [comment]
Related EssentialsX issue: EssentialsX/Essentials#1895

**Comment by Sikatsu** [comment]
Ah, misunderstood that. So in that case it would mean theres no way to disable fly in the end unless I remove the ''safelogin'' permission?

**Comment by lucko** [comment]
You can use the verbose command to debug the checks being made.

https://github.com/lucko/LuckPerms/wiki/Verbose

If you use the paste option, this output will also contain the **context** (including the world) where the check was performed.

Ultimately if Essentials is checking the permission before the Player is actually in the world, then world specific permissions won't work. This is something for Essentials to solve, not LP.

The problem with `/lp debug` was fixed already in 1689a8abe28d5361f50eedddead567d334041e07
