### ISSUE TITLE
update from 4.1.5 to 4.1.25 breaks permissions

### ISSUE THREAD

**Issue by frizzbee30** [lucko/LuckPerms#829]
log paste

https://pastebin.com/AuXaKRW7

spigot 1.12.2

Hi, really odd issue, I noticed a drop off in players and started getting reports of various permission issues (unable to use /spawn, warping, placing blocks in skyblock, using signs etc) which seemed to vary across plugins.

I rolled back luckperms to a 2017 version, which resolved in live and test, and then worked through the releases.

it appears that moving from 4.1.5 to 4.1.25 breaks the permissions, eg even /spawn fails, but rolling back a version to 4.1.5 immediately restores all functionality.

I cannot spot anything obvious on loading, but I hope you can help as this is the very first and only real (non config) issue we have had with this fantastic plugin!

Thanks

**Comment by lucko** [comment]
There are no obvious issues there I can see.   
I need specific info to help diagnose the problem.

* Specifically, which permissions stopped working
* How are those permissions set?
* What does [verbose](https://github.com/lucko/LuckPerms/wiki/Verbose) output when those permissions are checked for?

I'm not dismissing the issue - there's just nothing I can do to help without more information.

**Comment by lucko** [comment]
Please re-open this when you have more info to provide :)

**Comment by frizzbee30** [comment]
Hi, please see verbose output limited (and edited) to just using the /spawn command, sat in our hub world with the gamer group set as a parent, and the filter looking at  permission hsp.command.spawn, which all users in all worlds inherit.

(https://pastebin.com/DteK3z3m)


The gamer group https://pastebin.com/nU3nT32D , inherits from the essentials_default group  https://pastebin.com/d3qHZjsY, which carries the /spawn permission


Then obviously I inherit the Gamer group as a parent. So  it is a cascaded inheritance, however if I recall directly adding the perm nodes to the direct parent group, still had issues, but I would need to re test that.

As I stated previously, the older version works like a charm, I have tested the latest dev version, just in case it was a quirk, but still have all the same issues.

A number of permissions have stopped working, and to be honest, we have such a complex multi plugin, multi world, multi rank system that identifying all would be more than a challenge.

However certainly our hyperdrive (warps) and homespawnplus (homes and spawn) are broken by the change

Please let me know any additional tests/commands I can run to diagnose, as I am more than keen to try and get this sorted. Obviously now we are stuck at a specific version, on a plugin that is improved on a near daily basis!



I joined our test server

**Comment by lucko** [comment]
Try using

`/lp user <you> permission checkinherits hsp.command.spawn`

**Comment by frizzbee30** [comment]
Thanks will do asap and feedback

**Comment by frizzbee30** [comment]
[19:29:27] [pool-9-thread-1/INFO]: [0;37;22m[21m[[0;36;1m[21mL[0;36;22m[21mP[0;37;22m[21m] [0;36;1mfrizzbee30[0;32;1m has permission [0;36;1mhsp.command.spawn[0;32;1m set to [0;32;1mtrue[0;32;1m in context [0;33;1mglobal[0;32;1m. [0;37;22m(inherited from [0;32;1messentials_default[0;37;22m)[m

Hi, please see above when sat in our hub world, but same issue occurs regardless of world (all groups inherit essentails_default). I note it says inheritance global, and does not specify hub, is this relevant in any way ?

(I do specify global and then the worlds for assigning parents across the groups, following on from earlier advice from yourself , which resolved the issue I was having.)


Thanks for looking into it.  :)

**Comment by lucko** [comment]
So is it resolved? I'm struggling to follow the issue here :)

**Comment by lucko** [comment]
Ok, would you mind giving me a small reproducible test to follow?

e.g.

* run `/lp user <you> permission set foo.bar true server=lobby`
* observe that you don't have the foo.bar permission in lobby

It's quite difficult to interpret your examples without knowing all of the details of your setup

**Comment by MineyShadow** [comment]
Experienced the same issue, though what i did was delete everything and start from scratch using a newer version and it started working. [deleted database tables etc]

**Comment by frizzbee30** [comment]
Hi, thanks will run the test asap.  I understand from the set up side, I work in IT and obviously looking remotely, it's like trying to find which end of a bowl of spaghetti matches another, hence I really appreciate the time take to look into it!

Sadly starting from scratch isn't really that realistic, it really is a complex multi world - multi rank - multi plugin environment built up over the years  :)

it is appreciated though that someone else had a similar issue with the version change, a rewrite may end up the only way in the future if it can't be resolved.  (we don't run it on MySQL as yet, so it's not a table issue etc)

Thanks

**Comment by frizzbee30** [comment]
Hi, I did a variant to directly assign the perm to myself in the world, without parent inheritance

/lp user frizzbee30 permission set essentials.fly true world=hub

after running the command I had access to fly (would not normally have access for my test rank)


I then tried the same but with hsp.command.spawn ( inherited already from a parent, but showing insufficient permission as discussed earlier) as a further test

I then had access to spawn, hence it looks like for some reason the parent permissions are not inheriting down to the groups which are set as the parent to the player, although the actual perm nodes work as expected when added directly to the user.

Thanks

**Comment by frizzbee30** [comment]
If it's any help, our 'gamer' (default rank in hub), is inherited by all players, it has essentials_default as a parent, with the /spawn perm based in the essentials file (so it can be inherited by multiple worlds/ranks). 


I don't know if it is this inheriting once removed which is the issue since the version change? Although I _seem_ to recall adding the nodes to the direct parent and having issues, but really **would** need to confirm that.

It's a  bit of a throwback from when we ran PEX, which was inherited from Group manager originally.

 Probably not ideal, but quite complex to rebuild with our server set up!

**Comment by lucko** [comment]
Can you give me a list of commands I can run on a fresh server in order to reproduce the issue?

As I said before,

> It's quite difficult to interpret your examples without knowing all of the details of your setup

**Comment by frizzbee30** [comment]
Hi, will do as soon as possible, would it help if I zipped and drop-boxed the storage groups etc?

**Comment by lucko** [comment]
Will re-open when you have reproduction steps to demonstrate the issue. :)
