### ISSUE TITLE
Can't change existing permission without removing it first

### ISSUE THREAD

**Issue by Sir-Will** [lucko/LuckPerms#83]
hey,

if I have a permission set to true and want to change it to false I need to remove the permission first and then add it again as false value.

**Comment by dracnis** [comment]
same problem with prefix/suffix but harder to remove since it don't show & char

**Comment by Slind14** [comment]
@dracnis you can remove all prefix/suffix with a specific priority.

**Comment by dracnis** [comment]
@Slind14 almost sure you can't the command is :
/lpb group default meta removeprefix <priority> <prefix> [server] [world]
where prefix must be writted

**Comment by lucko** [comment]
You can enter "null" instead of a prefix string.

**Comment by Slind14** [comment]
What we use and works fine: 
`/perm user <player> meta removeprefix <priority> null`

**Comment by ryall** [comment]
If this is the case, I think the command should be changed to make the prefix string optional, rather than require null.

**Comment by lucko** [comment]
I've made the prefix/suffix string optional in the remove commands.

Regarding the main issue topic however, I'm not so sure on this. I know it's an ease-of-use thing, but the core internals of the plugin are designed with this behaviour.

"some.permission=true" is [`#almostEqual`](https://github.com/lucko/LuckPerms/blob/master/api/src/main/java/me/lucko/luckperms/api/Node.java#L338) to "some.permission=false". The `#setPermission` and `#hasPermission` methods and commands follow this design.
