### ISSUE TITLE
**ALL** Data transferring / not messing up prefixes and suffixes and setting ranked people to default

### ISSUE THREAD

**Issue by SpooderCraft** [lucko/LuckPerms#831]
**ALL** Data transferring / not messing up prefixes and suffixes and setting ranked people to default

im adding a self hosted server to my bungee network and i have and when i put in the mysql it connects fine and transfers the data but it messes up the prefixes and suffixes and perms and setting all players to default including ranked players.
here is my console logs and config
LOG: https://pastebin.com/9fCe7RNS
CONFIG: https://pastebin.com/rQdDquw0

thank you

**Comment by SpooderCraft** [comment]
please can u help

**Comment by lucko** [comment]
Make sure you have ip forwarding setup correctly.
https://github.com/lucko/LuckPerms/wiki/Network-Installation
