### ISSUE TITLE
MySQL Sync

### ISSUE THREAD

**Issue by pdglobal** [lucko/LuckPerms#832]
Could we have an update to the mysql sync feature, I have here to request 2 changes

1)When syncing, only sync if a value in a mysql table is set to "1" or "true"

This would allow more optimized syncing so that we could

2)set sync time in seconds (30) or fractions of a minute (0.5)

Please consider adding this update, I'm currently setting groups using a cron job that runs through my user database and looks at their access level, and it works perfectly, other than the fact that it can sometimes 1-2 minutes for changes to propagate to the plugin.

**Comment by BrainStone** [comment]
How about you let the cronjob trigger a sync too?

**Comment by lucko** [comment]
Duplicate of #534
