### ISSUE TITLE
The command /lp import skips certain permissions from the file

### ISSUE THREAD

**Issue by DarkFort** [lucko/LuckPerms#833]
I import permissions from [a file](http://rgho.st/private/657SwPsKn/588bbc3017567fc922033eaa873ebea1)
All permissions are imported except:
/lp group sp+ permission set essentials.heal true
/lp group contr permission set supervanish.standart true
/lp group contr permission set essentials.tpo true
/lp group zam permission set essentials.setwarp true
/lp group zam permission set fakecommand.speed true
and other

[WebEditor](https://luckperms.github.io/editor/?K0PZyEEQsH)

Latest version LuckPerms in Jenkins
PaperSpigot 1.12.2 latest build

**Comment by DarkFort** [comment]
![image](https://user-images.githubusercontent.com/25278617/37413627-22653d92-27b0-11e8-9918-098bb7e2d3c6.png)
![image](https://user-images.githubusercontent.com/25278617/37413662-350b6a16-27b0-11e8-982f-2160d94b340b.png)

**Comment by MrMIStakee** [comment]
I also have this problem!

**Comment by lucko** [comment]
Thanks for reporting. 

I was able to reproduce & then confirm a fix. I'm confident this is now resolved, but let me know if you still experience issues in the latest build.

**Comment by DarkFort** [comment]
![tvzrb6ga6us](https://user-images.githubusercontent.com/25278617/37433866-489e3cc6-27e6-11e8-83c9-0b9eb9015227.jpg)
hmmm

**Comment by lucko** [comment]
Last two errors are fine, first 5 are because `owner` doesn't exist.

**Comment by DarkFort** [comment]
But he is http://rgho.st/private/657SwPsKn/588bbc3017567fc922033eaa873ebea1

**Comment by DarkFort** [comment]
But he is http://rgho.st/private/657SwPsKn/588bbc3017567fc922033eaa873ebea1
