### ISSUE TITLE
FakePlayers Permission Group stays on default, despite group Switch [DiscordIntegration]

### ISSUE THREAD

**Issue by CDAGaming** [lucko/LuckPerms#834]
Using DiscordIntegration as an example, even If I set it's UUID's group to, say a group called admin, whenever you try to type a command, it'll still check the default group for permissions, not the correct group.

https://mcuuid.net/?q=828653ca-0185-43d4-b26d-620a7f016be6

(I'm only able to give it perms via it's UUID, by "lp user 828653ca-0185-43d4-b26d-620a7f016be6 parent
setprimarygroup bot)

**Comment by CDAGaming** [comment]
Fixed. For anyone else using LP, it seems DiscordIntegration uses 41c82c87-7afb-4024-ba57-13d2c99cae77
 as it's UUID

**Comment by CDAGaming** [comment]
Related to https://github.com/lucko/LuckPerms/issues/362, except DiscordIntegration is a Forge Server-Side Mod...

**Comment by lucko** [comment]
I don't understand what the problem is?

Can you give an example of the behaviour you're currently seeing, and what you expect to be happening?

**Comment by CDAGaming** [comment]
I have created a group called 'bot and have assigned it permissions like "minecraft.command.*" or "minecraft.command.stop". The Issue is that despite this and setting the FakeUser to the bot group (via UUID, since It wont let me put in it's name), when i'd try to run !stop within discord to feed /stop into minecraft, the command returns with Insufficient permissions, even though it's set on the bot group.

**Comment by lucko** [comment]
LuckPerms won't handle permission checks for fake players, unless Sponge/Forge does anything special to bridge the gap.

I don't know how that system works (if it even exists at all) so can't really provide much help.

**Comment by lucko** [comment]
As far as I know this isn't a problem LP can solve.

There isn't any official implementation of LP for Forge servers - if you're using LP on Forge, I'm assuming it's via something like Sponge or Cauldron. Afaik it's the responsibility of those projects to bridge the gap.

**Comment by Chikachi** [comment]
`FakePlayer` extends `EntityPlayerMP`
There should be NO issues checking permissions on a `FakePlayer` instance.
I see no where in Minecraft Forge, where it distinguish between a normal player and a FakePlayer with regards to commands.

**Comment by lucko** [comment]
LuckPerms is not a forge mod.

**Comment by lucko** [comment]
To clarify:

I suggest opening a ticket on the SpongeForge repository to see if support for FakePlayer permission checks can be added in Sponge.
