### ISSUE TITLE
API-Methods moved/broken

### ISSUE THREAD

**Issue by skyybender** [lucko/LuckPerms#835]
As the saveUser(user) method moved from UserManager to Storage it is no longer possible to use the API from MavenCentral. The description in your API-Tutorial will also not work any more and doing it this way with the latest LuckPerms version (and the API of MavenCentral) will cause in a MethodNotFound exception.

One solution is adding the LuckPerms.jar as an libary directly and use the updated method-structure. Maybe you can fix the API and update your wiki.

Thank you :)

**Comment by lucko** [comment]
The wiki is correct?

Just make sure you're depending on version `4.1`.
