### ISSUE TITLE
Crash on region load

### ISSUE THREAD

**Issue by evernife** [lucko/LuckPerms#836]
When a player load an area specific area, the server crash.

Don't know if is luckperms fault, i am just creating here because it's mentioned on the crash report.

If not related, i will ask on GriefPrevention's github.

Crash Report: https://hastebin.com/ajudamepub.scala

>     Minecraft Version: 1.10.2
>     Forge: 12.18.3.2477
>     
>     spongeforge-1.10.2-2477-5.2.0-BETA-2793.jar
>     LuckPerms-Sponge-4.1.31.jar

**Comment by lucko** [comment]
I don't think the crash is related to the LuckPerms activity.
