### ISSUE TITLE
[Suggestion] Placeholder that verify permission based on given world context

### ISSUE THREAD

**Issue by hsombini** [lucko/LuckPerms#838]
#Hello Lucko,

It's possible to implement a PlaceHolder that verify permission giving a specific World context?

Example: `%luckperms_check_permission_<permission>_world_<world>%`

I'm building a DeluxeMenu and this would make possible to hide some stuff based on permission that players may have multiple times in different worlds context, every permission in every world may be equal but it means different things for my logic on this menu that I'm building! Hence the need for World context placeholder!

**Comment by lucko** [comment]
I've moved this suggestion over to the placeholders repo. Thanks!
