### ISSUE TITLE
The weight argument should be optional in addprefix /addsuffix commands

### ISSUE THREAD

**Issue by lucko** [lucko/LuckPerms#840]
Can be kinda confusing. Would be neat if LP handles this "behind the scenes".

It could either fallback to using the groups weight, or try to determine an appropriate value itself, based either on inheritances or tracks.

**Comment by meandpiggy** [comment]
I agree! I don't even know what this is... so it is useless to me

**Comment by andrewkm** [comment]
Falling back to the group weight would be very nice.

**Comment by LapizSeller** [comment]
Weight of Prefix and Suffix is very useful for me, belong with placeholder %luckperms_prefix_element_<element>% and %luckperms_suffix_element_<element>%

**Comment by Leomixer17** [comment]
@LapizSeller He didn't say that this feature will be removed, he said that the argument will become optional
