### ISSUE TITLE
luckperms_messages

### ISSUE THREAD

**Issue by NightmareInfinity** [lucko/LuckPerms#842]
Luckperms uses luckperms_ as the prefix instead of lp_ which is what i have it set to in the configuration file.
I am currently using it on a sponge forge server in mc 1.12.2, the storage engine I use is mysql.
This is what shows up when running `SHOW TABLES;` in mysql. 
![image](https://user-images.githubusercontent.com/6487069/37568889-60191ab8-2aa9-11e8-9d68-0f20aecaaceb.png)

**Comment by lucko** [comment]
I beat ya to it ;) 0150da94a8b24d6cf9e0033cab8b073e30359dd5

Thanks for reporting :)
