### ISSUE TITLE
Tchat and tab with temporary group are different

### ISSUE THREAD

**Issue by titanium63** [lucko/LuckPerms#845]
Hello,
When i add a temporary group with a less weight  that currently player group, the tchat display the weightest group but not the tab. I use Stablist and essentials chat.
Issue is only for temporary group. 
There is an option for that or it's Stablist ?

**Comment by lucko** [comment]
If the correct value is showing in the output to the LuckPerms user info command, then it’s most likely an issue with the plugin using the data (the tab plugin) or the way you have it configured.
