### ISSUE TITLE
Event based permissions

### ISSUE THREAD

**Issue by TheLimeGlass** [lucko/LuckPerms#846]
Suggestion: Adding the ability to have a file in the LuckPerms folder that controls event based permissions.

So basically when a player event happens, LuckPerms can notice that and if the configuration says to add X permissions to that player it will do so accordingly. A timer may be placed aswell.

You can execute this with Bukkit's EventExecutor and then just check when the event coming through is a player event.

I would make a pull request but I just started using LuckPerms, i'm used to private permission plugins. I will for sure be checking LuckPerms source out later in the future. This project is amazing.

**Comment by Nighko** [comment]
You could code it your self with the API. So that when the player event occurs, then it sets a permission through the API.

**Comment by TheLimeGlass** [comment]
Potentially, I don't need it. Just a really cool feature that should be added.

**Comment by BrainStone** [comment]
The biggest issue I see with that is that it would be a highly platform dependent feature if you use Bukkit events. And using more generic events will naturally limit the feature.

Also it’ll likely not work well on bungee.

Lastly I think that’s something out of the scope of LuckPerms. Though that’s ultimately up to Luck to decide.

**Comment by lucko** [comment]
I think this would be best achieved using an extra plugin and hooking into the API. 

The events (or “triggers”) would probably have to be hard coded, and it would probably be a lot of work to create and maintain. 

I agree with Brainstone, I think it’s probably out of scope for a permission plugin.
