### ISSUE TITLE
Feature request - Be able to edit offline users perms in editor

### ISSUE THREAD

**Issue by Joe7670** [lucko/LuckPerms#847]
Pretty much title. It's kind of inconvenient to not be able to see what a users perms are if they're not online. /lp user <user> editor

**Comment by Joe7670** [comment]
Command wasn't working for the specific user for unknown reasons

**Comment by lucko** [comment]
Most likely because you needed to update :)

**Comment by Joe7670** [comment]
I only installed luckperms one week ago so I definitely have the most updated jar
