### ISSUE TITLE
How to hide this message?

### ISSUE THREAD

**Issue by madtomic** [lucko/LuckPerms#849]
![image](https://user-images.githubusercontent.com/6004542/37747904-cca8dc80-2d57-11e8-9a0b-387ba937232f.png)

Can someone please tell me how to hide this?

**Comment by BrainStone** [comment]
Why do you want to hide it?  
Like what’s the harm in showing this message?

Anyways have a look at the wiki. There’s a page on localization. You can customize any message there.
