### ISSUE TITLE
.git directory is not found!

### ISSUE THREAD

**Issue by madtomic** [lucko/LuckPerms#852]
Can some help me with this?

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] LuckPerms 4.1-SNAPSHOT ............................. FAILURE [ 21.293 s]
[INFO] luckperms-api ...................................... SKIPPED
[INFO] luckperms-common ................................... SKIPPED
[INFO] luckperms-bukkit ................................... SKIPPED
[INFO] luckperms-bungee ................................... SKIPPED
[INFO] luckperms-sponge-service ........................... SKIPPED
[INFO] luckperms-sponge-service-api6 ...................... SKIPPED
[INFO] luckperms-sponge-service-api7 ...................... SKIPPED
[INFO] luckperms-sponge ................................... SKIPPED
[INFO] luckperms-nukkit 4.1-SNAPSHOT ...................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 21.551 s
[INFO] Finished at: 2018-03-22T16:35:28-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal pl.project13.maven:git-commit-id-plugin:2.2.2:revision (default) on project luckperms: .git directory is not found! Please specify a valid [dotGitDirectory] in your pom.xml -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by lucko** [comment]
Uhh, how did you clone the repository?

**Comment by madtomic** [comment]
I downloaded it from Github

**Comment by lucko** [comment]
You need to clone it using Git. Instructions are here: https://github.com/lucko/LuckPerms#building

If you don't want to use the CLI, you can also use the GitHub desktop client to clone it.

https://desktop.github.com/

**Comment by madtomic** [comment]
Thank you lucko! I will close when this is resolve.

**Comment by lucko** [comment]
:+1:
