### ISSUE TITLE
Running LuckPerms title...

### ISSUE THREAD

**Issue by madtomic** [lucko/LuckPerms#854]
![image](https://user-images.githubusercontent.com/6004542/37798324-c9722b84-2df2-11e8-9124-2568dce237fb.png)

I know I asked this already but I was able to take out the prefix using lang.yml but the plugin / version is still not editable from the lang.yml

Can you help me hide this? The main reason is I am hiding all the plugins used on the server. As you can see I am simply using the default bukkit permission for all invalid actions.

Thanks

**Comment by lucko** [comment]
If players are even thinking about using the `/lp` command, then surely they already know LuckPerms is on your server?

What's the big deal with trying to hide things?

**Comment by madtomic** [comment]
Just want to see if I can hide everything and I want to make the server appears as vanilla as possible

**Comment by lucko** [comment]
> If players are even thinking about using the /lp command, then surely they already know LuckPerms is on your server?

Just get a command blocker plugin if you're really that bothered.

**Comment by madtomic** [comment]
Thank you for your thoughts.
