### ISSUE TITLE
Typo in Wiki>Web Editor

### ISSUE THREAD

**Issue by SebSeifert** [lucko/LuckPerms#855]
In the List is an Typo (look at Bold words)

Scope | Command
-- | --
To create an editor session for all **groups**, run: | /lp editor **users**
To create an editor session for all **users**, run: | /lp editor **groups**

**Comment by lucko** [comment]
I don't see it? 😕

**Comment by SirYwell** [comment]
You mixed up the two rows

**Comment by lucko** [comment]
Ah okay :D Thanks
