### ISSUE TITLE
Has problem with GriefPrevention while reading meta value with '0'

### ISSUE THREAD

**Issue by Tollainmear** [lucko/LuckPerms#858]
griefprevention command `/playerinfo` may could not get the player's meta value which set to `0`, this situation appeared when using `storage-method="yaml"`.

I have test this for several times, it goes well if using the `h2` storage method by default, but when I change the storage-method to yaml, the meta with value which set to 0 would not work in gp `/playerinfo`, I'm sure that the gp and luckperm was the latest version, and no error in console, so if possible please have a test with this issue.

using luckperm : 4.1.43(from jenkins)
griefprevention : 4.3.0.568
Spongeapi: 7

steps:
1.set storage-method to yaml
2.restart server
3.run `/lp group default meta set griefprevention.max-accrued-claim-blocks 0` and `/lp group default meta set griefprevention.blocks-accrued-per-hour 0`
4.run `/gpreload` then executing `/playerinfo`(make sure the player was in the default group)
5.then we can notice that max accrued blocks was still 80000(even we restart the server it still 80000)
6.then set storage-method to h2
7.do as 2-4
8.`max accrued blocks` was change to 0

**that seems like `0` was regard as `false`?**  

and is that goes as expect?  QwQ

**Comment by lucko** [comment]
I've ran the command example you gave, it seems to be working ok?

The file shows:
```yml
name: default
meta:
- griefprevention.max-accrued-claim-blocks:
    value: '0'
```

and the command output for `/lp group default meta info` shows
![](https://luck.sh/Hx0mnZ3Ede01eCjokca1FYa2cdU=)

If this isn't being read by GP correctly, then there's nothing I can do about that. You'll need to report it to blood.

**Comment by Tollainmear** [comment]
thx I'll update lp now
