### ISSUE TITLE
Previous versions of libraries are not removed after the upgrade

### ISSUE THREAD

**Issue by ziceptor** [lucko/LuckPerms#860]
\luckperms\lib

**asm-5.2.jar
asm-6.0.jar**

**asm_commons-5.2.jar
asm_commons-6.0.jar**

**caffeine-2.6.1.jar
caffeine-2.6.2.jar**

h2_driver-1.4.196.jar

**jar_relocator-1.2.jar
jar_relocator-1.3.jar**

okhttp-3.9.1.jar
okio-1.13.0.jar

**remapped-caffeine-2.6.1.jar
remapped-caffeine-2.6.2.jar**

remapped-okhttp-3.9.1.jar
remapped-okio-1.13.0.jar

**Comment by lucko** [comment]
I don't really think this is an issue.

You can just delete the whole folder and it'll regenerate a fresh copy of everything.
