### ISSUE TITLE
Group used in different contexts

### ISSUE THREAD

**Issue by Rakdos8** [lucko/LuckPerms#862]
We have the same group name in different server: `Aspirants`.

If we promote a Player on the Survival server from `Visiteurs` to `Aspirants`, he/she will get the new "user_permission" `group.aspirants` but it collides with the Skyblock server. If he/she logs in, he/she will also recieve this `Aspirants` group.

Several screenshot are avaliable to explain here: https://imgur.com/gallery/U3VTP

Did we miss something ?

By the way, we've translated the tool according to https://github.com/lucko/LuckPerms/wiki/Locale-and-Translations and are willing to share once tested and verified :+1:

**Comment by lucko** [comment]
The showtracks output is a bit confusing, I can fix that.

You can see that the context is included at the end of each track, that should probably be moved to the start.

Other than that, I don't really see where the issue is?

**Comment by Rakdos8** [comment]
Actually the issue may only be in the output of the command: it shows every track (including the global) and if the player has been promoted in a specific context it will also be shown as promoted in other tracks.

Related to https://i.imgur.com/6A6atcJ.png
The player has been promoted in the `Aspirants` groups on the `server=skyblock` context but he is also promoted in the survie_staff track (context global I guess) which is weird.

**Comment by lucko** [comment]
Okay, I've clarified the command output a bit. It should be easier to understand/read now.

Aside from that, I don't think there's an underlying bug/issue here. Maybe I'm just missing the point though?? 😄 

Feel free to re-open this if you still think there's a problem to be fixed.

**Comment by Rakdos8** [comment]
Thank you ! I gave it a try and it looks like I'm still missing something, sorry bothering you :( .

Now the context  (server/world) is shown just after the name of the track which is way better to understand. Thank you again !
Yet the printed tracks are duplicated. I assume it's mandatory in order to show every possibility for every context, isn't it ? But is it really necessary ?
When you're in a different server you may want to hide track/permission which does not met yours (TMI). Worlds would still be shown, just in case I guess.

Some side question:
1. What happens if the context is `global` and the world context is `world`: will this track/permission/other will be active in every single world named `world` in every server ?
2. If I promote a player to a group - which is used in 2 differents tracks - in the `global` context, will he get this group in every single server (which match the context) ?

**Comment by lucko** [comment]
> What happens if the context is global and the world context is world: will this track/permission/other will be active in every single world named world in every server ?

Yes

> If I promote a player to a group - which is used in 2 differents tracks - in the global context, will he get this group in every single server (which match the context) ?

Yes - you can find more details about the ways contexts are matched here https://github.com/lucko/LuckPerms/wiki/Contexthttps://github.com/lucko/LuckPerms/wiki/Context

**Comment by Rakdos8** [comment]
I've tried some other stuff with it and found an issue (can't re-open by myself).

Screenshots: https://imgur.com/a/DT9C2

You have 2 tracks:
1. T1
1. T2

T1 has 5 groups:
1. G1
1. G2
1. G3
1. G4
1. G5

T2 has 3 groups:
1. G1
1. G6
1. G3

Steps:
1. You promote the player on the track T1 (server=skyblock): he will get the G1 group in both of the tracks.
1. You promote him again on T1 (server=skyblock): he will get the G2 group for T1 and stay in G1 for T2
1. You promote him again on T1 (server=skyblock): he will get the G3 group for T1 and G3 for T2 (skipping G6)
1. You demote him on T2 (server=skyblock): he will loose groups from T1 and get G6 for T2

Can we add a context to track to avoid "promoting" a player in the wrong context ?

**Comment by lucko** [comment]
The steps there show the system working as intended. That's how it should be. 😄 

You can't add a context to the track, but you can add it to the group membership.
See: https://github.com/lucko/LuckPerms/wiki/Context#defining-your-own-contexts
