### ISSUE TITLE
Add more placeholders for displaying highest weight group prefix and displayname.

### ISSUE THREAD

**Issue by PetKCH** [lucko/LuckPerms#864]
As of right now, to my knowledge, there aren't any placeholders that would display the prefix or display name of the highest weight group user is in, there's only %luckperms_highest_group_by_weight%.

The reason, why I am asking for this, is because when for an example main track contains default and expands to donator ranks when I try to display staff ranks as the primary with current placeholders being offered it often switches showing donator ranks.

So, if you could please make something like %luckperms_highest_prefix_by_weight% and %luckperms_highest_group_displayname_by_weight% I'd be more than happy.

**Comment by lucko** [comment]
`%luckperms_highest_group_by_weight%` returns the display name.

`%luckperms_highest_prefix_by_weight%` would be the same as `%luckperms_prefix%` or `%luckperms_prefix_element_highest%`

Only other thing is: make sure you're using the latest version of the expansion.

https://ci.lucko.me/job/LuckPermsPlaceholders/
