### ISSUE TITLE
/lp editor ERROR

### ISSUE THREAD

**Issue by yBarttY** [lucko/LuckPerms#865]
I tried doing /lp editor
And I'm getting an error in console
https://hasteb.in/agiputal.avrasm

**Comment by Nighko** [comment]
Do you have some sort of system that blocks websites or ports?

**Comment by yBarttY** [comment]
I do not

**Comment by lucko** [comment]
Your server cannot connect to https://bytebin.lucko.me/

Nothing I can do about it, you could try contacting your host and asking for their advice.
