### ISSUE TITLE
German translation for LuckPerms(submission)

### ISSUE THREAD

**Issue by BlackHawk2306** [lucko/LuckPerms#866]
Hey. So as I already wrote on Spigot(review), I made a de-DE translation, because there didn't seem to be one, I got the time, and I want to help. So I spent like 3 - 3.5 hours on this hopefully not too bad language file.
In case there are typos reported, I tried not to make too many, ofc you can tag me in the issue  to fix it.^^

https://itstyrion.de/random/lang.yml

There you got the file, uploaded on my own server, because GitHub doesn't like YAML as attachment ;)

**Comment by SirYwell** [comment]
There are some translations which aren't really complete. Example: Line 7 `Untercommands` should be `Unterbefehle`. However, it's better to not translate terms like Track, Group or Parent (`Elter` doesn't even exist).

 Also, I detected a `das/dass` mistake in L13.

**Comment by BlackHawk2306** [comment]
Actually, Elter does exist. It's the singular form of Eltern.. like parent and parents. 

And I didn't translate some things on purpose, i.e. commands. I will change that though, as well as the grammar mistake in L13

**Comment by SirYwell** [comment]
Yeah it exists but it's extremly rare and it sounds very uncommon. How I mentioned before, I wouldn't translate it at all.

**Comment by lucko** [comment]
https://github.com/LuckPerms/locale/commit/51d93f080b8f55b3cea7c9c827f97c6a93c1af7a

Thanks
