### ISSUE TITLE
LuckPerms does not load on BungeeCord proxy.

### ISSUE THREAD

**Issue by arrayofc** [lucko/LuckPerms#868]
I'm trying to install LuckPerms on my BungeeCord proxy but it won't let me. When I launch the server it gives me an error, and the plugin won't load properly. 
![c8acf50f4d9750b4b0fd2d146339925a](https://user-images.githubusercontent.com/23186961/37924407-1224c8ea-3132-11e8-89e2-d6fb7491318c.png)

And for your information, I'm using the latest version downloaded from Spigot. I only have two other plugins in my BungeeCord folder. I removed every single plugin except LuckPerms, and the error still occurred.

edit: Just figured out that you have to install the BungeeCord version from the Jenkins site. My bad, you may close this issue report.

**Comment by lucko** [comment]
:)
