### ISSUE TITLE
Quotes are ignored with Prefixes (on Nukkit?)

### ISSUE THREAD

**Issue by funniray** [lucko/LuckPerms#870]
Server Version: NukkitX Protocol 1.2.11 (Commit 8f52c901474a019118b849e217c34f034e2c0564)
LuckPerms Version: 4.1.43 (Nukkit)

When I try to do `/lp user <user> meta addprefix <weight> "&fTest Prefix &7"` LuckPerms interperets it as `prefix="&fTest" server="Prefix" world="&7"`. I am using normal quote marks and not the special ones from iOS. I haven't tested this version on Java edition to see if this is a Nukkit-only issue. I'm working on an updated version of EssentialsNK that adds LuckPerms prefix support but I'm waiting on this issue to be resolved before I release it.

**Comment by lucko** [comment]
My only guess is that Nukkit (or MCPE??) parses these characters differently.

The code is exactly the same for Bukkit, where it works as intended.

https://github.com/lucko/LuckPerms/blob/4923d10b86e4759b7b07a6ba38e9df6fbaccd6de/nukkit/src/main/java/me/lucko/luckperms/nukkit/NukkitCommandExecutor.java#L54

https://github.com/lucko/LuckPerms/blob/4923d10b86e4759b7b07a6ba38e9df6fbaccd6de/bukkit/src/main/java/me/lucko/luckperms/bukkit/BukkitCommandExecutor.java#L56
