### ISSUE TITLE
LuckPerms and ProjectE permission issue

### ISSUE THREAD

**Issue by cyris69** [lucko/LuckPerms#873]
This is what I posted over on ProjectE git:

> Exact ProjectE version: ProjectE-1.12-PE1.2.0
> Exact Forge version: forge-1.12.2-14.23.2.2611-universal
> SpongeForge version: spongeforge-1.12.2-2611-7.1.0-BETA-2970
> LuckPerms version: LuckPerms-Sponge-4.1.44
> 
> I'm trying to update EMC values for things that don't have any, however, with LuckPerms if I was to type this while item is in hand /projecte setEMC 32 I would get "You don't have permissions to use this command"
> 
> Also, opping a user doesn't appear to supercede LuckPerms so I can't do it that way either. I'd prefer to avoid file editing etc as it gets complicated whereas in hand is wonderful. 
> 
> So any assistance would be greatly appreciated.

A response:

> I don't know how Sponge permissions plugins interact with commands coded to vanilla, you'll have to consult your the devs who wrote the plugin.
> 
> In a pure forge/vanilla setup, only ops can use the /projecte emc commands

Since there are no permissions for the mod, then it must be a LP setting I'm missing.

**Comment by lucko** [comment]
LuckPerms just handles permission checks in accordance with the Sponge API. It doesn't provide any special hooks with individual plugins or mods.

**Comment by cyris69** [comment]
Ok, then how do I get real vanilla OP right's through sponge when it says? 

```
[Server thread/INFO]: [LP] Please note that Server Operator status ha
s no effect on Sponge permission checks when a permission plugin is installed. P
lease edit user data directly.
```

Yet when I remove LuckPerms I can use the command just fine as OP. It's for sure a LP issue, not a sponge issue.

**Comment by lucko** [comment]
It has no effect on Sponge permission checks, but it will impact on Forge mods which check for op status.

**Comment by cyris69** [comment]
So can you lightly guide my hand on how to do this whilst employing your permissions plugin with forge mods or is this something that is lost when sponge is mixed with forge?

**Comment by lucko** [comment]
Yeah, it's possible Sponge is doing some magic to bridge the gap.

The verbose command will help
https://github.com/lucko/LuckPerms/wiki/Verbose

**Comment by cyris69** [comment]
Ok, I'm inabling verbose mode and trying 
/lp verbose record ProjectE
/lp verbose record Luck & ProjectE

It confirms its that it's recording, but if I try the setEMC command I still get perm error and don't receive any info. However, I'm sure this is a PEBCAK and me understanding the exact implementation directions.

**Comment by lucko** [comment]
* Run `/lp verbose record <your username>`
* Then try to use setemc
* Then run `/lp verbose paste`

In the output it gives you, you want to look for any permissions which look relevant. 😄

**Comment by cyris69** [comment]
You lovely sob :) interestingly enough it's just called setemc no projecte involved perm wise. Just saw and read about the web editor and my this is amazing. Thanks for the hand holding :)

**Comment by lucko** [comment]
No worries :)
