### ISSUE TITLE
Problems with MySQL / Проблемы с MySQL

### ISSUE THREAD

**Issue by bo0o0t** [lucko/LuckPerms#876]
Hello
Sorry for my bad English, I'm from Russia.
Google translate me into the helper)
I will duplicate in my native language.
There was a problem usingSSL.
My solution differs from that in the FAQ. Code:

Привет.
Извините за мой плохой английский, я из России.
Гугл транслейт мне в помошь)
Буду дублировать на родном языке.
Возникла проблема useSSL. 
Моё решение отличается от того, что в FAQ. Код:

```
data:
  address: 127.0.0.1:3306
  database: my_perm_db?useSSL=false
```

**Comment by lucko** [comment]
The FAQ explains the correct way to solve the issue.

Appending `useSSL=false` to the end of the database name may work now, but it's not an intended feature, and may stop working in the future. You should use the properties map, as that's what it is there for.

**Comment by bo0o0t** [comment]
Machine translate(
Working.
I wanted to say that I will fix my config.
Машинный перевод(
Работает. 
Я хотел сказать, что исправлю свой конфиг.
