### ISSUE TITLE
[Nukkit] Suffix won't show beside my nametag!

### ISSUE THREAD

**Issue by XDqrkneZ** [lucko/LuckPerms#878]
So I did 

/lp creategroup Test
and then
/lp group Test meta addsuffix 100 "TEST"
and then 
/lp user steve parent set Test

it doesnt give me tag beside my name

**Comment by lucko** [comment]
You need a chat formatting plugin.

LuckPerms doesn't format the chat for you. I don't know of one that exists for Nukkit yet unfortunately.

**Comment by XDqrkneZ** [comment]
@lucko then I'll be waiting for you to make the chat plugin.

**Comment by lucko** [comment]
I have no intention of creating any more plugins for the Nukkit platform at this time. Perhaps you could ask for/commission the creation of such a plugin on the forums.
