### ISSUE TITLE
Permissions on other servers do not work except global

### ISSUE THREAD

**Issue by DarkFort** [lucko/LuckPerms#880]
Recently noticed that the permissions in the lobby have ceased to work, on the survival and global server everything is fine. What happened?

**Comment by lucko** [comment]
No clue, check your LP config on the lobby. Is the server setting defined properly?

**Comment by MrMIStakee** [comment]
I have the same problem!

**Comment by DarkFort** [comment]
Even if the default configuration and include-global: true, does not work ;9

LuckPerms latest build.
PaperSpigot latest build.

**Comment by lucko** [comment]
> Is the server setting defined properly

**Comment by DarkFort** [comment]
Yes, I checked everything. There should be no such problems.
This problem occurred after updating the plug-in configuration!

**Comment by lucko** [comment]
Then perhaps you should revert your changes?

**Comment by MrMIStakee** [comment]
Yes, I also had this problem after updating the configuration

**Comment by DarkFort** [comment]
But I did not change anything except the plugin itself

**Comment by lucko** [comment]
You said it broke after updating the configuration...

**Comment by DarkFort** [comment]
I deleted the config and it was created. But now the permissions in the lobby, except for survival, do not work.

**Comment by lucko** [comment]
I need to see more information about your setup to be able to help. I'm left to assume you're talking about server specific permissions - in which case, you need to set the value of `server` in the config file.

Please just be informative in your issue reports - it's painful having to extract tiny bits of information out of people who can't be bothered to write decent issue reports.

@MrMIStakee do you have anything useful to add? Just saying you're experiencing the same issue is absolutely useless.

**Comment by MrMIStakee** [comment]
https://hastebin.com/hazejunuwa.coffeescript
https://luckperms.github.io/editor/?KCehREp6fe

**Comment by lucko** [comment]
Can you show me in what way that's not working?

**Comment by MrMIStakee** [comment]
The following rights do not work on the lobby server:

customjoinitems.donat
customjoinitems.menu
welcomedonater.join

**Comment by DarkFort** [comment]
[Permission](https://hastebin.com/ividemehew.cs)
[Config survival](https://hastebin.com/julosiruti.coffeescript)

[Config lobby](https://hastebin.com/ukasogagat.coffeescript)

Do not work permits in the lobby:
/lp group helper permission set gadgetsmenu.banners.* true server=lobby
/lp group helper permission set gadgetsmenu.emotes.* true server=lobby
/lp group helper permission set gadgetsmenu.hats.* true server=lobby
/lp group helper permission set gadgetsmenu.cosmetics.* true server=lobby
/lp group helper permission set gadgetsmenu.gadgets.* true server=lobby
/lp group helper permission set gadgetsmenu.cloaks.* true server=lobby

**Comment by lucko** [comment]
Does setting `include-global: true` fix the issue?

**Comment by DarkFort** [comment]
If this option is enabled in the lobby, it still does not work.

**Comment by lucko** [comment]
Is the permission node wrong then? No reason why that in particular wouldn't work if everything else is.

**Comment by DarkFort** [comment]
But my permits do not work in the lobby ;(

**Comment by DarkFort** [comment]
And it happened after the plugin was updated, when the update for the configuration was released

**Comment by lucko** [comment]
```yml
server: test
include-global: false
```

```
> lp verbose on Luck & minecraft
[10:39:31 INFO]: [LP] Verbose logging enabled for checks matching Luck & minecraft.
[10:39:36 INFO]: Luck issued server command: /gamemode 1
[10:39:36 INFO]: [LP] VB > luck - minecraft.command.gamemode - false
> lp group default permission set minecraft.command.gamemode true
[10:39:46 INFO]: [LP] Set minecraft.command.gamemode to true for default in context global.
[10:39:49 INFO]: Luck issued server command: /gamemode 1
[10:39:49 INFO]: [LP] VB > luck - minecraft.command.gamemode - false
> lp group default permission set minecraft.command.gamemode true server=zzzzz
[10:40:02 INFO]: [LP] Set minecraft.command.gamemode to true for default in context server=zzzzz.
[10:40:05 INFO]: Luck issued server command: /gamemode 1
[10:40:05 INFO]: [LP] VB > luck - minecraft.command.gamemode - false
> lp group default permission set minecraft.command.gamemode true server=test
[10:40:10 INFO]: [LP] Set minecraft.command.gamemode to true for default in context server=test.
[10:40:13 INFO]: Luck issued server command: /gamemode 1
[10:40:13 INFO]: [Luck: Set own game mode to Creative Mode]
[10:40:13 INFO]: [LP] VB > luck - minecraft.command.gamemode - true
[10:40:13 INFO]: [LP] VB > luck - minecraft.command.gamemode - true
```


It's working exactly as intended. This isn't a LP bug, you're probably just setting the wrong permissions.
