### ISSUE TITLE
Server hangs on shutdown whilst "shutting down internal scheduler"

### ISSUE THREAD

**Issue by lucko** [lucko/LuckPerms#881]
```
[10:47:43 INFO]: [LP] Shutting down internal scheduler...
[10:47:47 INFO]: [LP] Goodbye!
```

**Comment by jackstrosahl** [comment]
This seems to still be a problem

**Comment by lucko** [comment]
Can't reproduce.

```
10:19:07 [INFO] Disabling plugins
10:19:07 [INFO] [LuckPerms] Closing storage...
10:19:07 [INFO] [LuckPerms] Shutting down internal scheduler...
10:19:07 [INFO] [LuckPerms] Goodbye!
```

Could you describe your setup?

**Comment by direded** [comment]
I got the same problem on my Spigot 1.14 server

**Comment by wrecktify** [comment]
Same issue on spigot 1.14.2 and LuckPerms-Bukkit-4.4.26

Server hangs during shutdown process after saying Goodbye!

No error message or indication what is causing the hangup.

Plugins (13): LuckPerms, dynmap, FoundDiamonds, WorldEdit, PhantomSMP, LogBlock, HolographicDisplays, Vault, FarmLimiter, WorldGuard, Essentials, EssentialsGeoIP, EssentialsChat

**Comment by Froosty11** [comment]
Having the same issue.
