### ISSUE TITLE
Argument based permissions not checked(?)

### ISSUE THREAD

**Issue by Argetan** [lucko/LuckPerms#884]
I tried giving a certain group permission to `add` a specific group (called builder) which didn't work. Adding the permission `luckperms.user.parent.add` works, but is not desired as it allows to add all groups when I tried `luckperms.user.parent.add.builder` which didn't work, it would just say `[LP] Running LuckPerms v4.1.54.`

I tried running verbose to see if I was missing any permissions, but verbose appears to list basically every permission included by LuckPerms.

Are there any additional permissions that need to be added? Or is this a bug?

**Comment by voodootje0** [comment]
Is the setting `argument-based-command-permissions` true in your config?

**Comment by Argetan** [comment]
It wasn't. Setting it to true fixed it (also fixed `verbose` listing all permissions).

Thank you for your fast response!
