### ISSUE TITLE
Question about initial setup in granting full access

### ISSUE THREAD

**Issue by barrettc** [lucko/LuckPerms#885]
I'm fairly new to Minecraft server setup. I'm going through initial LuckPerms setup and was about to perform the following step:
https://github.com/lucko/LuckPerms/wiki/Usage#granting-full-access-to-modify-permissions

However, I discovered that anyone is able to run `/lp` without being given this access which is undesirable. The only plugin I have installed at the moment is LuckPerms. Any thoughts?

```
01.04 16:42:07 [Server] INFO Loading LuckPerms v4.1.54
01.04 16:42:07 [Server] INFO Enabling LuckPerms v4.1.54
01.04 16:42:07 [Server] INFO __        __   ___  __         __  
01.04 16:42:07 [Server] INFO |    |  | /  ` |__/ |__) |__  |__)  |\/| /__` 
01.04 16:42:07 [Server] INFO |___ \__/ \__, |  \ |    |___ |  \  |  | .__/ 
01.04 16:42:07 [Server] INFO Loading version v4.1.54 on Bukkit - CraftBukkit
01.04 16:42:07 [Server] INFO Running on server version git-Spigot-b6ecf3b-2e21028 (MC: 1.12.2) - 1.12.2-R0.1-SNAPSHOT
01.04 16:42:07 [Server] INFO Loading configuration...
01.04 16:42:07 [Server] INFO Loading storage provider... [H2]
01.04 16:42:08 [Server] INFO Loading internal permission managers...
01.04 16:42:08 [Server] INFO Performing initial data load...
01.04 16:42:08 [Server] INFO Successfully enabled. (took 726ms)
```

**Comment by lucko** [comment]
Could you show me an example of that?

Assuming you haven't set any permissions (or granted OP) yet, players shouldn't have access to any of the sub-commands.

**Comment by barrettc** [comment]
Sorry, I'm a complete noob to this stuff and discovered that the 2 users I was testing with were in `ops.json`. Thank you for the fast response.

**Comment by lucko** [comment]
No worries :)
