### ISSUE TITLE
Add amount of permission entries in info

### ISSUE THREAD

**Issue by voodootje0** [lucko/LuckPerms#890]
Would be great if the amount of permissions can be added in the `/lp group <group> info`, you could also add it for `/lp user <user> info`

**Comment by lucko** [comment]
Usecase?

It was there before, but I just saw it as unnecessary clutter

**Comment by voodootje0** [comment]
After some bulk editing, you can check quickly or everything went well.

**Comment by lucko** [comment]
The total is in the output to `permission info` - I don't think it needs to be included in the user summary too.
