### ISSUE TITLE
Ability to use the same display names multiple times or inheritance it.

### ISSUE THREAD

**Issue by voodootje0** [lucko/LuckPerms#891]
If you have 'fake/dummy' groups, they will use the display name from the highest possible group inheritance (when there is no display name set) or you can just use the same display name multiple times.

Example:
```
Group A:
  display name: Owner
  weight: 100
  parents: none
Group B:
  display name: none
  weight: 99
  parents: a
```

Now people with only group B will display the displayname of group A, which is Owner in this example.

**Comment by lucko** [comment]
I don't understand what you're trying to suggest

**Comment by voodootje0** [comment]
I've added an example.

**Comment by lucko** [comment]
Display names aren't inherited

**Comment by voodootje0** [comment]
That's exactly why I made this suggestion. Make display names inherit. 😃

**Comment by lucko** [comment]
That doesn't seem like a good idea. Group names are meant to be unique.

**Comment by voodootje0** [comment]
I see your point.
