### ISSUE TITLE
Essentials Gamemode Permissions

### ISSUE THREAD

**Issue by pocketcraft1** [lucko/LuckPerms#898]
I have Luckperms and EssentialsX on my server.  Recently all essentials.gamemode permissions have stoped working.  I’m not sure if this is because of a LuckPerms or an Essentials Issue.

**Comment by lucko** [comment]
See https://github.com/EssentialsX/Essentials/wiki#per-gamemode-permissions

**Comment by pocketcraft1** [comment]
I am almost certain they have all these perms.  Here are the admin permissions. https://pastebin.com/MiytThVH

**Comment by pocketcraft1** [comment]
I did /lp verbose on essentials.gamemode while an admin was on, and nothing came up.

**Comment by lucko** [comment]
Try enabling the verbose system and then using the gamemode command

**Comment by pocketcraft1** [comment]
I enabled the verbose system by doing /lp verbose on essentials.gamemode  I had the admin type in /gamemode creative, but nothing happened.  Except that I got the ID/gm message

**Comment by lucko** [comment]
If nothing is showing in the verbose log, then LP isn't handling the check.

Do you have another permissions plugin installed?

**Comment by pocketcraft1** [comment]
No but here is my list of plugins: https://pastebin.com/BeSwmZ3z

**Comment by lucko** [comment]
`Essentiasl` ??

**Comment by pocketcraft1** [comment]
Sorry that’s a typo it’s EssentialsX

**Comment by lucko** [comment]
Are you using the latest version of EssentialsX?

What's the output of  `/essentials version`?

**Comment by pocketcraft1** [comment]
Essentials reloaded 2.0.1-b595.

**Comment by lucko** [comment]
That's not the latest version

**Comment by pocketcraft1** [comment]
Oh sorry about that is this the latest version? https://www.spigotmc.org/resources/essentialsx.9089/updates

**Comment by pocketcraft1** [comment]
I updated to EssentialsX 2.15.0.1 and updated Luckperms to version 4.1.25   Still having the same problem

**Comment by lucko** [comment]
Ok no worries, can you send a pastebin of your Essentials `config.yml` please

**Comment by pocketcraft1** [comment]
Sure: https://pastebin.com/SRUWkgsq

**Comment by pocketcraft1** [comment]
Is there any other files you need?

**Comment by lucko** [comment]
Your config looks fine.

Can you provide a log file for testing with verbose? As I said before,

> If nothing is showing in the verbose log, then LP isn't handling the check.

**Comment by pocketcraft1** [comment]
Oh and I gave one of the people essentials.gamemode.* during the check too.

**Comment by lucko** [comment]
The verbose sessions only last for 1 hour, so I can't see that now unfortunately.

**Comment by pocketcraft1** [comment]
Oh sorry about that, I will turn it into a pastebin.

**Comment by pocketcraft1** [comment]
https://pastebin.com/05XtxU0v

**Comment by lucko** [comment]
There are no checks there for a gamemode command.

> If nothing is showing in the verbose log, then LP isn't handling the check.

I suggest reporting the issue to Essentials - I don't see how this is a LP problem.

**Comment by pocketcraft1** [comment]
Wait we fixed the problem.  I had to delete chat control.  There is something in the configuration that was conflicting I think. Thanks for helping me.
