### ISSUE TITLE
2-10 Second Lagspikes on Chat with Nucleus

### ISSUE THREAD

**Issue by Slind14** [lucko/LuckPerms#90]
This appeared without updating nucleus and luckperms, the only thing that changed was sponge to build 2000 and griefprevention to 199.

Threaddumps: 
https://gist.github.com/Slind14/f846ec2f28c2b691b205fb627cf4fa10

LuckPerms 2.16.36
Nucleus 0.16.1 & 0.16.3

**Comment by SnowBlitzz** [comment]
From what versions of GP and SF did you update from?

**Comment by Slind14** [comment]
TILE-6 -> 2000
TEST2 -> 199

**Comment by SnowBlitzz** [comment]
No idea what TILE-6 and TEST2 are lol. Sponge made lots of changes (depends on which version you came from) so you might need to regenerate its config file.

**Comment by dualspiral** [comment]
I think this ties in with #69, just to create the link

**Comment by Slind14** [comment]
Thank you @lucko

**Comment by lucko** [comment]
Yes - the lag spikes are definitely related to #69. This was a different issue.

Will fix #69 now.
