### ISSUE TITLE
Feature Request: /lp user parent replace <group1> <group>

### ISSUE THREAD

**Issue by xtechgamer735** [lucko/LuckPerms#904]
Hey!

Just a feature request for command "/lp user <user> parent replace <group1> <group2>" to do what it says on the tin really. If the user is in group1, remove them from it and add them to group2 instead.

Its just helpful for plugins that only let you use one command line for actions plus a few other things I can think of.

Ta!

**Comment by lucko** [comment]
I don't see the benefit of adding another command to do this - when it's already possible using the existing commands.

If you're limited to one command execution, it'd be quite easy to setup an alias for this. (depending on the platform, using `commands.yml` or an extra plugin)

e.g.
```
swapgroup <player> <group1> <group2>
- lp user $player parent remove $group1
- lp user $player parent add $group2
```
