### ISSUE TITLE
Prefixes not showing in chat

### ISSUE THREAD

**Issue by Dinoosawruss** [lucko/LuckPerms#905]
Hi

I am trying to make groups have prefixes on my server but they will not display in chat

I have Vault and EssentialsX chat

I have LuckPerms 4.1.25 and EssentialdXChat 2.15.0.1

**Comment by lucko** [comment]
Can you give some example screenshots?

What's the output of `/lp user <you> info` - do the correct prefixes / suffixes show?

What steps have you already taken to try to diagnose/resolve the issue?

**Comment by Dinoosawruss** [comment]
![image](https://user-images.githubusercontent.com/22278485/38519112-a64cab96-3c36-11e8-85c1-af6015a07656.png)

**Comment by Dinoosawruss** [comment]
I have checked vault like it says and vault says LuckPerms is active and I have seen if I need to add a placeholder which I seems I don’t. I have tried updating both plugins to

**Comment by Dinoosawruss** [comment]
I am sorry if this inconveniences you but I have to leave right now I will be back tomorrow though. Sorry

**Comment by lucko** [comment]
Most likely an issue with your Essentials config then.

Make sure `add-prefix-suffix` is set to true, and that your chat format is configured correctly.
