### ISSUE TITLE
MSSQL Support

### ISSUE THREAD

**Issue by Patrick-Spiegel** [lucko/LuckPerms#909]
Hello,

I am going to implement MS SQL Support for luckyperms. Is that something you want me to pull request once its done? 

~Patrick

**Comment by lucko** [comment]
Uhhh, probably not to be honest.

It might make sense to do something similar to the Cassandra implementation??
https://github.com/LuckPerms/luckperms-cassandra

**Comment by Patrick-Spiegel** [comment]
I'll take a look into that. If it works all perfectly fine I'll do that.
