### ISSUE TITLE
Copy ranks permissions

### ISSUE THREAD

**Issue by da-llama** [lucko/LuckPerms#911]
Hello, I use LuckPerms with a SQL database, and I'm currently setting up all permissions. 
I have already setup the default ranks perms, but I want the same perms on mod, helper etc. So I was wondering if it's possible to copy the "default" rank permissions to "mod" rank?

**Comment by voodootje0** [comment]
https://github.com/lucko/LuckPerms/wiki/Command-Usage:-Parent
Example:  `/lp group mod parent add default`
