### ISSUE TITLE
Error found with luckbungee - Disables use of luckperms in bungee

### ISSUE THREAD

**Issue by ICEconchy** [lucko/LuckPerms#912]
This is the error that appears using debug:
https://hastebin.com/ohuzifomec.vbs

**Comment by lucko** [comment]
Is it just the debug command that doesn't work?

Is that the full error?

**Comment by ICEconchy** [comment]
That's the full error. And the bungee is unable to connect to the database even though the spigot version can.

**Comment by lucko** [comment]
Can you pastebin your full log file?

**Comment by ICEconchy** [comment]
Part of the log file that shows the error: https://pastebin.com/dRwRH7ME
The entire Log file is too large for pastebin

**Comment by lucko** [comment]
Seems like the name of your database is missing from the config file?

**Comment by ICEconchy** [comment]
It was placed in there. Does the bungee plugin support one character database names and usernames?

**Comment by lucko** [comment]
Should do

**Comment by ICEconchy** [comment]
Here is the brand new paste, I've imported the same database information as the spigot servers use: https://pastebin.com/XTnjR3JV

**Comment by lucko** [comment]
Same error, so

> Seems like the name of your database is missing from the config file?

**Comment by ICEconchy** [comment]
It seems that you need to fully turn off the bungee server, edit the config then start it

**Comment by ICEconchy** [comment]
That has fixed it

**Comment by lucko** [comment]
👍
