### ISSUE TITLE
Suggestion: Delete Permission From All Known Users

### ISSUE THREAD

**Issue by Max604** [lucko/LuckPerms#914]
Hello,

A useful feature I believe should be added is the ability to run a command to remove a 'permission' from every player who has that permission. For example, removing '*' from everyone who has it.

I know it's possible to see who has a permission with /lp search and then delete from each player manually, but for large-scale purges it becomes too tedious. I can't reset a player's special player-only permissions from buying a certain island upgrade that gives them a specific permission. I can't delete those said permissions from everyone when I do a skyblock season reset. 

Thanks,
Max

**Comment by lucko** [comment]
https://github.com/lucko/LuckPerms/wiki/Bulk-Editing

**Comment by RubenArtz** [comment]
lp bulkupdate users delete ?
