### ISSUE TITLE
Luckperms is using much more MySQL connections that it should

### ISSUE THREAD

**Issue by Guarmanda** [lucko/LuckPerms#915]
Luckperms should use 10 connections per server as it is said on the wiki. But it's totally not the case for me.
I have two servers connected on my mysql database. Luckperms is the only plugin that have access to the database. 
On the two servers, the max-pool-size is set to 10. 
On the mysql server, the max user connections is 100 and the max connections is 10 000
But, when I start my servers and then try to connect to my phpmyadmin pannel, I got this:
```#1203 - User 6620170801326b already has more than 'max_user_connections' active connections```
Luckperms should use only 20/100 connections, but it uses 100/100! And if I start a third server, it can't connect to the mysql database! Why?!

**Comment by lucko** [comment]
Perhaps you have another plugin also connecting to the database?

You can use the 

```sql
SHOW PROCESSLIST;
```

command to view the active connections.

**Comment by Guarmanda** [comment]
I changed the password so that not any other plugin can use the database. And I can't even do the show processlist command because the plugin is using all the connection slots so I can't connect to the database

**Comment by lucko** [comment]
Close one of the servers and then you'll be able to connect.
