### ISSUE TITLE
Web Editor Suggestions

### ISSUE THREAD

**Issue by MineyShadow** [lucko/LuckPerms#916]
Tabs: A feature where we can have two "group/user" tabs side by side for the web editor [This can be more than one if you want]

Permission Dragging: To support the suggestion above, a feature where you can "drag" a permission from one group/user to another for convenience.

The web editor scroll: Currently i feel like its too small and sometimes i misclick on a group/user while trying to drag it.

**Comment by lucko** [comment]
I've moved these suggestions to the correct repo - thanks!
