### ISSUE TITLE
After migration, old players are taking between 10-90 seconds to get their permissions.

### ISSUE THREAD

**Issue by Phyther** [lucko/LuckPerms#919]
When a player that has played for a while logs in, it takes between 10-90 seconds before they get their permissions. I am running paper 1.12.2 with luckperms 4.1.25 on mysql.
This started after yesterday's migration from groupmanager.

**Comment by Phyther** [comment]
Everytime a player logs in, I get this in console:
https://pastebin.com/znwrGyG6

**Comment by lucko** [comment]
Your MySQL server is taking too long to respond (or just isn't responding at all)

See https://github.com/lucko/LuckPerms/wiki/Storage-system-errors for for information.
