### ISSUE TITLE
Feature Request: See what permission nodes a WebEditor /applyedit has changed.

### ISSUE THREAD

**Issue by sorcererno** [lucko/LuckPerms#922]
Currently, if you change something using the WebEditor and you use /lp(b) log userhistory <user> the result from that command only show you that a user has done an /applyedit.
Example:
[LP] Showing recent actions by <user> (page 1 of 1)
[LP] #1 (22d 20h ago) (<user>@bungee) [G] (default)
[LP] > applyedits 1fD65UYOhs
I am looking for a feature that can either allow you to:
1) See the permission node content of a specific /applyedit
2) See the permission node changes done by a specific user by having them appear natively in /lp log userhistory <user>

**Comment by lucko** [comment]
Thanks for the suggestion - this has been added in the latest version :)

You can download it here
https://luckperms.github.io/
