### ISSUE TITLE
NullPointerException 

### ISSUE THREAD

**Issue by ziceptor** [lucko/LuckPerms#924]
On server start https://gist.github.com/ziceptor/5a32ed357a736701ae7a07df9551dd2b

forge-1.12.2-14.23.2.2611-universal.jar
spongeforge-1.12.2-2611-7.1.0-BETA-3002.jar
LuckPerms-Sponge-4.1.69.jar

**Comment by SlimeDog** [comment]
Similar with Spigot 1.12.2 and LuckPerms-Bukkit-4.1.69

**Comment by SlimeDog** [comment]
Confirmed fixed 4.1.70
