### ISSUE TITLE
Wiki mistakes

### ISSUE THREAD

**Issue by InterStena** [lucko/LuckPerms#927]
[Advanced Setup](https://github.com/lucko/LuckPerms/wiki/Advanced-Setup) page.

> Non wildcard/regex permissions will be overridden by normal permissions

Should be (by context)
> Wildcard/regex permissions will be overridden by normal permissions

>Foe example, if you wanted a user to be able to create both groups and tracks, you would normally just add the two permission nodes.

Should be
>For example, if you wanted a user to be able to create both groups and tracks, you would normally just add the two permission nodes.

**Comment by lucko** [comment]
Thanks :)
