### ISSUE TITLE
Split Storage Not Working on LP 4.1.X for Sponge

### ISSUE THREAD

**Issue by CathalCraft** [lucko/LuckPerms#928]
spongeforge-1.12.2-2611-7.1.0-BETA-3002

The split-storage setting in LP is not working on LP versions 4.1.X for sponge. I have tried v4.1.60 - v4.1.72. The settings were working fine on v4.0.141.
I have tried having it regenerate the config and "luckperms" folder after each version.

The plugin only uses the storage method defined in "storage-method" even if the "split-storage" has "enabled" set to true.

If I have storage-method = "MariaDB", it saves all the data in MariaDB and ignores split-storage.
If I have storage-method = "YAML", it saves all the data in YAML and ignores split-storage.
  split-storage {
    enabled = true
    methods {
      user = "MariaDB"
      group = "YAML"
      track = "YAML"
      uuid = "MariaDB"
      log = "YAML"
    }
  }
}

There is one error seen when the plugin is loaded:
https://pastebin.com/crbLGjK5

Config setup:
https://pastebin.com/ztgGyfUE

**Comment by lucko** [comment]
The config was incorrect - the section for `split-storage` shouldn't be inside `data`
