### ISSUE TITLE
Luckperms with Towny/townychat

### ISSUE THREAD

**Issue by Phyther** [lucko/LuckPerms#931]
I am writing the because LLmDl (towny dev) does not seem to want to contact you.

I am running towny 0.92.0.0 with LuckPerms 4.1.63. Players are randomly losing their towny permissions such as ability to speak in general chat, not getting their permissions when they login, and even if a town name/town mayor changes, the mayor loses access to commands. 

Most of the time, a relog works, but sometimes I have to manually go in and reset settings for the mayors.

After speaking at length with LlmDl about it, he seems to think the issue with towny and luckperms not working correctly together started with this commit:
https://github.com/lucko/LuckPerms/commit/a2801bff7ceca99b15fe0aa0e7e2c92516170644

Unfortunately, I cannot find a pre-November build of luckperms to test this out and see if everything works correctly before the commit. 

With very few exceptions, all of the towny perms are stored in the townyperms.yml file:
https://pastebin.com/HbB8qmD8

the only perms not stored in that file are the mod and admin perms, which I keep in seperate groups that I then add to the apropriate staff groups.

**Comment by lucko** [comment]
The commit you linked fixed an issue which meant some plugins didn't work at all with LuckPerms.   
There's therefore no way an issue would have been introduced with that commit.

The permissions players are losing -- are they being defined within LuckPerms groups, or via towny?

I'd suggest setting them directly via LP as opposed to in the Towny system - as it seems to be problematic.

**Comment by Phyther** [comment]
Ok, so towny reads the towny perms, and LlmDl says to leave them in the towny perms file. So how would towny be able to read the perms in luckperms without assigning them directly to the player. For example, towny reads the database to see the towny rank of the player. If they are a towny mayor, it gives them those permissions. If they don't have a town, they get the nomad permissions, etc....

**Comment by Phyther** [comment]
So if I add the towny permissions in, do I need to create groups for each of those and hope towny reads those groups?

**Comment by Phyther** [comment]
So I just spoke with the towny dev. Basically, I could add all the base perms to everyone, but towny won't read rank perms. So towny wouldn't read say a mayor group. 
I'm not sure where to go from here.

**Comment by Phyther** [comment]
So I spoke with someone on the discord ad nauseum regarding how my perms were setup. He steered me in the right direction and it turns out I had my groups setup all wrong. 

That has been fixed now and everything appears to be working correctly.
