### ISSUE TITLE
i installed luckPerms in my plugins foldier but it doesnt work

### ISSUE THREAD

**Issue by borgsy2** [lucko/LuckPerms#932]
Iv put luckPerms in my plugins foldier but its not installed

**Comment by Turbotailz** [comment]
A bit more info would be appreciated.

- What server platform are you running (Spigot, Sponge, etc) and what version?
- Which version of LuckPerms have you tried to install?
- Are there any errors in your console during start up? Check your console logs.

Reply with that info and we might be able to help you.

**Comment by lucko** [comment]
Feel free to reopen this ticket when you have more info to give
