### ISSUE TITLE
An error in console.

### ISSUE THREAD

**Issue by MarcIsLive** [lucko/LuckPerms#933]
I have luckyperms 4.1.63 and i see an error in console.

He works fine now, at the error there was nowone at the server. Or cronjob task.

This was the error in the bungee console https://pastebin.com/YjeSv8xP

I hope that you cane read this my englisch is not good. Sorry.

Greatings 
Marc

**Comment by lucko** [comment]
Please see here for more info: https://github.com/lucko/LuckPerms/wiki/Storage-system-errors#mysql-no-operations-allowed-after-connection-closed-error
