### ISSUE TITLE
Bug track

### ISSUE THREAD

**Issue by Ventuj** [lucko/LuckPerms#934]
i use EzRanksPro and LuckPerms, i use 3 Track in this order staff vip and prison, the plugin ezranks use the track prison and this think is correcty in way totaly random when a player arrived at a random prison rank and he have another rank in the track vip or staff, the plugin ezrank select a rank on a random track and i don't undestand the problem, i temporaly resolve the bug deleting the gruop and recreating the group but this solution don't work many time. sorry for my bad english i'm from italy .-.

**Comment by lucko** [comment]
I don't really follow what the issue is.

Could you give an example using some screenshots of the issue?

**Comment by Ventuj** [comment]
https://imgur.com/a/uIRDTWw the same problem arrived complitly random with staff track es helper in the screen there is a problem with an vip rank

**Comment by Ventuj** [comment]
use 3 track 
With this group
Track prison 
- a
- b 
- c
- d
- e
- f
- g
- h
- i
- j 
- k 
- l
- m 
- n 
- o 
- p 
- q
- r 
- s
- t
- u
- v
- w
- x
- y
- z
- free
Track vip
- Next
- Night
- Rex
- Boss
- Strayboss
Track staff
- builder 
- helperjr
- helper 
- mod
- admin
- founder
The track prison is the defaul for all player exclude Admin and Founder, when i add a plyer 1 group off staff or vip and the default group is before group i (a, b, c, d, e, f, g, h) the plugin ezrankpro work perfectly. When player rankup to i or higher the plugin don't select from track prison but select from staff or vip this bug don't allow player to rankup  because the rank are made for only track prison, i post a screen of my scoreboard because show the rank of ezranks and when add the group don't show the progress and show incorectly rank.

**Comment by lucko** [comment]
I don't really understand what the issue here is.

The sounds like more of an issue with EzRanksPro than with LuckPerms?
