### ISSUE TITLE
[Sponge] Unsetting permissions with/without context flags

### ISSUE THREAD

**Issue by Rasgnarok** [lucko/LuckPerms#935]
**Issue:** when unsetting a permission node with a context, if you unset without specifying said context it will always return positive (meaning it will always say it successfully unset), even though it cannot unset it because of the missing context. **Only seems to happen with JSON storage, can't reproduce on a default Luckperms installation.**
Example: 
![image](https://user-images.githubusercontent.com/18584380/39256952-3f2b4ca2-487e-11e8-8fed-4cb5784cdc76.png)

**Comment by lucko** [comment]
The screenshot you posted looks fine to me?

Can you highlight where the issue is?

**Comment by Rasgnarok** [comment]
There, updated the ticket with the right screenshot. Unsetting a node under global, when it's been cached, results into a false positive when the node had been set under a context.

**Comment by lucko** [comment]
I can't reproduce using the latest version.

```
> lp creategroup test
[17:36:41] [pool-6-thread-1/INFO]: [LP] test was successfully created.
> lp group test permission set test.permission true testserver
[17:37:00] [pool-6-thread-1/INFO]: [LP] Set test.permission to true for test in context server=testserver.
> lp group test permission unset test.permission
[17:37:16] [pool-6-thread-1/INFO]: [LP] test does not have test.permission set in context global.
>
```

**Comment by lucko** [comment]
Please try to reproduce this using the latest dev release - if it's still an issue feel free to reopen this ticket.
