### ISSUE TITLE
Bungeecord MySQL error?

### ISSUE THREAD

**Issue by Julianvb97** [lucko/LuckPerms#936]
I already searched all over the internet to fix this but cannot solve it still.

this is the error: 
luckperms - Failed to validate connection me.lucko.luckperms.lib.mysql.jdbc.JDBC4Connection@5da79bc4 (No operations allowed after connection closed.)

I hope someone can help me
The credentials are correct, I changed the wait_timeout to 1800 already so I'm clueless now.

**Comment by ICEconchy** [comment]
What are you hosting and controlling your server with (e.g. multicraft/vps etc)

**Comment by Julianvb97** [comment]
I host it on a Contabo VPS and I use pterodactyl as panel. Also I use MariaDB for Mysql driver

**Comment by ICEconchy** [comment]
Only bungee.

**Comment by BrainStone** [comment]
Try this: https://github.com/lucko/LuckPerms/wiki/Storage-system-errors

**Comment by Julianvb97** [comment]
@BrainStone Did that already sorry...

**Comment by Julianvb97** [comment]
@ICEconchy  The bungeecord error has been resolved now my spigot server has this error: 
(Connection.setNetworkTimeout cannot be called on a closed connection)

It is just weird that only luckperms has issues with the MySQL/MariaDB and the other plugins are working just fine....

**Comment by lucko** [comment]
Brainstone was correct - please read the details on this page. This isn't a LP issue.

https://github.com/lucko/LuckPerms/wiki/Storage-system-errors#mysql-no-operations-allowed-after-connection-closed-error

**Comment by Julianvb97** [comment]
Alright so could you tell me why no other plugin on that server has problems with MariaDB and luckperms is the only one with this error?

**Comment by lucko** [comment]
Probably because the other plugins you have don't use a connection pool like LuckPerms does.

**Comment by Julianvb97** [comment]
I looked at this link: https://github.com/lucko/LuckPerms/wiki/Storage-system-errors#mysql-no-operations-allowed-after-connection-closed-error

My error isnt stated there, I got this error in my console: luckperms - Failed to validate connection me.lucko.luckperms.lib.mariadb.MariaDbConnection@6eb81946 (Connection.setNetworkTimeout cannot be called on a closed connection)

**Comment by lucko** [comment]
Yes it is - you error *is* stated there.

> me.lucko.luckperms.lib.hikari.pool.PoolBase - luckperms - Failed to validate connection me.lucko.luckperms.lib.mariadb.MariaDbConnection@xxxxxxx (xxx cannot be called on a closed connection)
