### ISSUE TITLE
[Nukkit] Nemisys & Synapse support

### ISSUE THREAD

**Issue by Creeperface01** [lucko/LuckPerms#937]
Hi, I would like to suggest if you could add support for Nemisys. It's basically proxy like bungeecord (just based on different principle). Nemisys is separate software and SynapseAPI is plugin for Nukkit. Both are located in https://github.com/NukkitX. Nemisys and synapse have support for plugin messaging and in the latest version I added permission support to the proxy. If you decided to add support and found any problem, let me know and I can try to add/fix it.

**Comment by lucko** [comment]
I don't think this is in scope for the main LuckPerms project at this time.

If such a time comes when Nemisys is used by a significant number of people, then perhaps this can be reconsidered.

I hope you understand. :)

**Comment by Creeperface01** [comment]
Or I already tried to do that, so there is a chance you will accept my PR I can do it :)

**Comment by lucko** [comment]
No, I think this is better off remaining separate from the main project.

**Comment by Creeperface01** [comment]
Ok nemisys module could be, but at least messaging have to be implemented directly into the nukkit module doesn't it?

**Comment by lucko** [comment]
Nope, it can be added in a standalone plugin via the API.

**Comment by Creeperface01** [comment]
OK thanks :) I'll do my best
