### ISSUE TITLE
LuckPerms does not handle group meta inheritance properly, it seems

### ISSUE THREAD

**Issue by ryall** [lucko/LuckPerms#94]
- LuckPerms v2.16.31
- Sponge
- Minecraft 1.10.2

I seem to be having problems with meta inheritance when it comes to groups. Specifically, I am trying to set more homes for a donator with the [home-count meta tag](http://nucleuspowered.org/docs/modules/home.html) from Nucleus.

Perms are as follows:

**default**:
- meta.home-count.2

**donator**:
- group.default
- meta.home-count.5

With the **donator** rank, the meta value 2 is returned incorrectly. The perms are definitely set correctly. Also, setting the meta tag directly on the user works, just not through group inheritance.

This is a consistent issue I'm finding across all meta tags I'm using within Nucleus. Above is just one example.

**Comment by lucko** [comment]
Are the donator users also a member of default?

**Comment by ryall** [comment]
Yes, they are

**Comment by lucko** [comment]
Added the following command:

`/lp group <group> setweight <weight>`

Should fix your issue. :)

**Comment by ryall** [comment]
Amazing, thanks Lucko!
