### ISSUE TITLE
Api Question..

### ISSUE THREAD

**Issue by Diserix** [lucko/LuckPerms#940]
Hello, I want to do their api in my plugin, but somehow this does not work the way I want. It's about a chat prefix plugin, which should be queried about the groups, PermissionEx is a light query like this: `if(PermissionsEx.getUser(p).inGroup("Owner")) {
			e.setFormat("§7[§4Owner§7] §4"+ p.getName() + " §8» §7" + Message);`

My question is now how can I do that with LuckPerms?

**Comment by lucko** [comment]
Use `p.hasPermission("group.owner")`
