### ISSUE TITLE
Cant Figure out why my Prefixes/Suffixs wont work

### ISSUE THREAD

**Issue by Bradman12312** [lucko/LuckPerms#941]
Hello!
first off, i want to say i love LuckPerms. it's made my life so much easier on managing my sponge Server. 

Recently found an issue though. I've been doing some updating, and suddenly all my suffixes are gone. I've installed the VaultChatformatter like it says on the Wiki, and I'm pretty sure i have the correct version of everything on my sponge server (1.12.2) , but something isn't adding up. 

I run the commands like normal, and LP shows it accepts the command, but then nothing after. 

My Current versions are as follows:

Luckperms version:  **LuckPerms-sponge-4.1.73**
VaultChatFormatter version:  most recent one from their website
Vault: **1.6.6**
Sponge-forge version: **spongeforge-1.12.2-2611-7.1.0-BETA-3002.jar**

As well, here is a paste-bin of the start up of my server, in case that information is important:

https://pastebin.com/euxU8vXi

Please let me know if you need any more information, or what i need to do to fix this issue. 

Thank you for your time :)

**Comment by lucko** [comment]
Vault and VaultChatFormatter are Bukkit plugins and won't run on Sponge.

I suggest using Nucleus.

**Comment by Bradman12312** [comment]
Is there anything else I'll need ot install besides Nucleus to get the prefixes to work? I want to make sure i do this right. :)

**Comment by Bradman12312** [comment]
Sweet :)
