### ISSUE TITLE
Cant figure out how to give world perms

### ISSUE THREAD

**Issue by Bradman12312** [lucko/LuckPerms#942]
Hello,

So my players cant seem to get to the Nether or The End. I researched how to allow it but cant find it in the wiki's

Can you tell me what the command would be to set perms to go to the nether, or the end world?

Our nether name is DIM-1

**Comment by Bradman12312** [comment]
They get the error "you do not have permission to travel to DIM-1" for reference

**Comment by Bradman12312** [comment]
Is there a way to fix this?

**Comment by lucko** [comment]
I'm not sure of the answer, the requirement is being enforced by another plugin.

You can work it out using the verbose command
https://github.com/lucko/LuckPerms/wiki/Verbose
