### ISSUE TITLE
Suggestions : A new perm value and register your plugin in aquifer (paper)'s ressources

### ISSUE THREAD

**Issue by aeyu** [lucko/LuckPerms#948]
Hi !
I suggest you add on your plugin a new value for perms. 
I mean currently perms are enabled (true) or disabled (false). 
You should add a value "undefined" that act the same as if you didn't set that perm.

I also suggest you add LuckPerms on Aquifer's Resources's page :  https://aquifermc.org/resources/ 
Aquifer is a fork of Spigot.

Thanks for your hardwork, anyway !

**Comment by lucko** [comment]
> You should add a value "undefined" that act the same as if you didn't set that perm.

This exists already internally. The Bukkit permissions API expects a boolean response, so `undefined` is convered to `false` when a check is made. (or to `true` if the player is opped)

I don't really see the benefit of posting it on Aquifer, LP doesn't have any special functionality which works with Paper only, and it's not a Paper specific plugin. It would just be another place I've got to post updates to.
