### ISSUE TITLE
Do not show weight and display name in perm list

### ISSUE THREAD

**Issue by voodootje0** [lucko/LuckPerms#949]
I recommend to not show weight and display name in perm list in `/lp group <group> perm list`

**Comment by Andre601** [comment]
weight and displayname are just permissions that tell LuckPerms what weight and displayname the group has.
It wouldn't make sense, to just add something, to ignore those permissions.

**Comment by lucko** [comment]
These aren't special "meta" permissions like `group.<group>` and `prefix.<data>` - by that I mean, they don't have any special handling internally - they're just permissions.

So yeah, I agree with Andre, I think it's best that they remain included.
