### ISSUE TITLE
LuckPerms not understanding editor command

### ISSUE THREAD

**Issue by PrincessRTFM** [lucko/LuckPerms#953]
I just installed LuckPerms and got my old permissions migrated (from GroupManager), and I wanted to launch the web editor interface. However, upon using `/lp editor` and it's variants, I only see LuckPerms listing its version and subcommands, as if I had only run `/lp` without an argument. I am using v4.0.18 on a Spigot 1.12.2 server, hosted on MelonCube and installed through their online plugin manager. It doesn't matter whether I run the command from the console or in game, the result is always the same.

**Comment by Andre601** [comment]
First: Update LuckPerms. The version you provided (4.0.18) is WAY too old. LuckPerms version on Spigot is 4.1.25
Next: You need the permission luckperms.editor to use the command. If you only get the Plugin name and its version as a response, then it does mean, that you don't have permission.

**Comment by PrincessRTFM** [comment]
Ah, okay. I used an "auto installer" thing on my server host, I'll grab the latest file. Thanks!
