### ISSUE TITLE
Feature request: Add a gui with permissions

### ISSUE THREAD

**Issue by Nik2143** [lucko/LuckPerms#955]
I think it would be very useful to add a gui that based on the permissions declared in the plugin.yml of the various plugins in the server allows you to add or remove permissions from a group through the use of a gui

**Comment by Andre601** [comment]
Luck already got that request and answered it (#619)

It wouldn't be useful for LuckPerms to have a GUI. Especially, if it already has a Web-Editor, which gives way more possibilities.

**Comment by Nik2143** [comment]
OK, thanks
