### ISSUE TITLE
Apparent Symlink issue

### ISSUE THREAD

**Issue by oddare** [lucko/LuckPerms#956]
# PRESET INFO

Names not accurate
All users (read: servers), this scenario (HUB) is connected to one root user (ROOT) through symlinks
All users share the same group (MC) to have full read-write permissions
Used command is `sudo ln -s /home/ROOT/plugins/LuckPerms/yaml-storage /home/HUB/plugins/LuckPerms/yaml-storage`: Fake folder at HUB location on entry sends to ROOT
Setup works without issues on 4.0.98
Configurations for 4.1.83 has been wiped and updated properly - Works when NOT symlinked breaks upon symlink of "yaml-storage"

As noted in preset, I'm using symlinks between my servers so as to assimilate MySQL but with the perks of YAML which I rely on relatively often, ontop of the perks of the web-editor and ingame changes.
Upon updating it appears as if the plugin can no longer access the database, regardless of my attempts.

Paste: https://paste.md-5.net/luvurelili.avrasm

**Comment by lucko** [comment]
Symbolic links should be followed, but LP doesn't implement any specific handling for it. It's all handled by Java's filesystem APIs

**Comment by oddare** [comment]
Has there been any major changes in how it's handled/stored since then though? I've attempted various things but it appears that 4.1.83 just doesn't like symlinks.

**Comment by lucko** [comment]
Yes, I've switched a lot of things from using the [`File`](https://docs.oracle.com/javase/8/docs/api/java/io/File.html) API to the [`Path`s](https://docs.oracle.com/javase/8/docs/api/java/nio/file/Path.html) API.

**Comment by oddare** [comment]
Bungee bootup and shutdown paste: https://paste.md-5.net/tafaqeweka.avrasm

**Comment by lucko** [comment]
> So, whatever you did for v4.1.86 fixes the issue with symlinks. ¯\_(ツ)_/¯


yay
