### ISSUE TITLE
Groups

### ISSUE THREAD

**Issue by ZeLFaDore** [lucko/LuckPerms#958]
Please Please CAN you make this plugin more simpler to use ? 
it is sooooooooooo complicated to create a group just make a group file to edit groups permissions prefix thanks

**Comment by lucko** [comment]
> it is sooooooooooo complicated to create a group

It's literally just one command? `/lp creategroup <group>` - I don't know how I can make that any simpler? Do you have any suggestions?

> just make a group file to edit groups permissions prefix

This already exists, but you need to enable YAML storage in the config file. As Brainstone said, we generally recommend using the web editor if you're struggling to remember commands.

There's also a basic usage guide here which I recommend you read.

https://github.com/lucko/LuckPerms/wiki/Usage

**Comment by ZeLFaDore** [comment]
thanks alot you really work hard at this plugin i will give it one more go :)
