### ISSUE TITLE
Bug (LuckPerm with YAML Storage)

### ISSUE THREAD

**Issue by samysilva** [lucko/LuckPerms#959]
Good evening,

I'm trying to use LuckPerm with YAML Storage.

I changed the configuration file, as the documentation explains, I stopped and started the server again.

On the first boot the plugin creates the "yaml-storage" folder with its files. And everything works normally.

However, after stopping the server, and attempting to start again, an error occurs when initializing the permissions.

I've tested the other Storages based on files, and they also present problems.

With H2 is Ok

======================

```
\plugins\LuckPerms\config.yml

# - If you want to edit data manually in "traditional" storage files, we suggest using YAML.

storage-method: yaml
```

======================

```
[20:58:14 INFO]: [LP] Loading configuration...
[20:58:14 INFO]: [LP] Loading storage provider... [YAML]
[20:58:14 INFO]: [LuckPerms] [ERROR] Failed to init storage dao
[20:58:14 WARN]: java.nio.file.FileAlreadyExistsException: C:\Users\Samy\Desktop\Minecraft\Minecraft\plugins\LuckPerms\yaml-storage\users
```

**Comment by lucko** [comment]
Which version of LP are you using?

**Comment by samysilva** [comment]
Hi, im using the version 4.1.69

Here are a screenshot of the loading.

https://www.spigotmc.org/threads/luckperms-an-advanced-permissions-plugin.174259/page-103#post-2983419

**Comment by lucko** [comment]
I believe this is fixed already on the latest version.

https://luckperms.github.io/

**Comment by samysilva** [comment]
Thank you Lucko.

I tested again with version 97, which worked perfectly. I had searched for new versions on Google, which forwarded me to version 69. I wrote here the address luckperms.github.io to search for new versions.

Thank you very much :-)
