### ISSUE TITLE
Setting a permission to undefined does not remove contexts

### ISSUE THREAD

**Issue by bloodmc** [lucko/LuckPerms#96]
Tested removal of permissions using latest LuckPerms using json storage and the following remained

      {
        "gp_claim": "f3044dc5-f0b2-4d0a-9f1c-4f4c33cca59b",
        "gp_source": "pixelmon:occupiedpokeball"
      },
      {}

As you can see, there are no permissions but the contexts still exist.

Also after this occurs, it will continue to return the last known value until server restarts. I edited the json manually and did a '/lp sync' but it had no effect. After restarting, it started to work normally.

**Comment by lucko** [comment]
As far as I know, this should have no effect on permission calculation.

What do you mean by "it will continue to return the last known value"?
