### ISSUE TITLE
Error in BungeeCord console

### ISSUE THREAD

**Issue by meandpiggy** [lucko/LuckPerms#965]
I placed this plugin into my BungeeCord plugins folder. it gave me this error message:

![image](https://user-images.githubusercontent.com/38956062/39587558-05998370-4eb7-11e8-9e07-8d7cbd907398.png)

Pleas help

**Comment by Andre601** [comment]
I saw better jokes than that. Please choose another GitHub-repo, to make your stupid jokes.
