### ISSUE TITLE
BungeeCord console problem

### ISSUE THREAD

**Issue by meandpiggy** [lucko/LuckPerms#966]
I placed this plugin into my BungeeCord plugins folder. it gave me this error message:

at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0<PluginClassloader.java:34>
at net.md_5.bungee.api.plugin.PluginClassloader..loadClass<PluginClassloader.java:27>
at java.lang.ClassLoader.loadClass<.Unknown Source>

Please help

**Comment by lucko** [comment]
I need to see the full error message (or the full log if you have it?)

**Comment by meandpiggy** [comment]
Where do I get the bungeecord console log?

**Comment by lucko** [comment]
Usually in the `proxy.log` file, or in the `logs` folder.

Post it to pastebin and then send the link here :)

**Comment by meandpiggy** [comment]
The full error code:

09:47:23 [INFO] Loaded plugin cmd_find version git:cmd_find:1.12-SNAPSHOT:79cd077:1309 by SpigotMC
09:47:23 [INFO] Loaded plugin AdvancedBan version 2.0.6 by Leoko
09:47:23 [INFO] Loaded plugin BungeeChat version 2.1.6.855 by shawn_ian, BrainStone
09:47:23 [INFO] Loaded plugin cmd_server version git:cmd_server:1.12-SNAPSHOT:79cd077:1309 by SpigotMC
09:47:23 [INFO] Loaded plugin cmd_alert version git:cmd_alert:1.12-SNAPSHOT:79cd077:1309 by SpigotMC
09:47:23 [INFO] Loaded plugin cmd_send version git:cmd_send:1.12-SNAPSHOT:79cd077:1309 by SpigotMC
09:47:23 [INFO] Loaded plugin cmd_list version git:cmd_list:1.12-SNAPSHOT:79cd077:1309 by SpigotMC
09:47:23 [WARNING] Forced host server pvp is not defined
09:47:23 [INFO] Enabled plugin reconnect_yaml version git:reconnect_yaml:1.12-SNAPSHOT:79cd077:1309 by SpigotMC
09:47:23 [INFO] Enabled plugin cmd_find version git:cmd_find:1.12-SNAPSHOT:79cd077:1309 by SpigotMC
09:47:24 [INFO] 
 
[]=====[Enabling AdvancedBan]=====[]
| Information:
|   Name: AdvancedBan
|   Developer: Leoko
|   Version: 2.0.6
|   MySQL: false
| Support:
|   Skype: Leoko33
|   Mail: Leoko4433@gmail.com
| Update:
|   There is a new version available! [2.1.3-RELEASE]
[]================================[]
 
09:47:24 [INFO] Enabled plugin AdvancedBan version 2.0.6 by Leoko
09:47:25 [INFO] [BungeeChat] §6---------------- §bBungee Chat§6 ----------------
09:47:25 [INFO] [BungeeChat] §eAuthors: §ashawn_ian & The_BrainStone
09:47:25 [INFO] [BungeeChat] §eVersion: §aVersion(input=2.1.6.855, component=ListComponent([NumberComponent(2), NumberComponent(1), NumberComponent(6), NumberComponent(855)]))
09:47:25 [INFO] [BungeeChat] §eModules: §aAlert§f, §aAntiAdvertising§f, §aAntiDuplication§f, §aAntiSwear§f, §aChatLock§f, §aChatLogging§f, §aClearChat§f, §aJoinMessage§f, §aLeaveMessage§f, §aLocalChat§f, §aMessenger§f, §aStaffChat§f, §aTabCompletion§f, §aVanish§f, §aVersionChecker§f, §aWelcomeMessage
09:47:26 [INFO] [BungeeChat] §6---------------------------------------------
09:47:26 [INFO] Enabled plugin BungeeChat version 2.1.6.855 by shawn_ian, BrainStone
09:47:26 [INFO] Enabled plugin cmd_server version git:cmd_server:1.12-SNAPSHOT:79cd077:1309 by SpigotMC
09:47:26 [INFO] Enabled plugin cmd_alert version git:cmd_alert:1.12-SNAPSHOT:79cd077:1309 by SpigotMC
09:47:26 [INFO] Enabled plugin cmd_send version git:cmd_send:1.12-SNAPSHOT:79cd077:1309 by SpigotMC
09:47:26 [INFO] Enabled plugin cmd_list version git:cmd_list:1.12-SNAPSHOT:79cd077:1309 by SpigotMC
09:47:28 [INFO] Listening on /192.168.3.22:25565
09:49:14 [INFO] Using standard Java JCE cipher.
09:49:14 [INFO] Using standard Java compressor.
09:49:14 [INFO] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.12-SNAPSHOT:79cd077:1309
09:49:14 [INFO] Discovered module: ModuleSpec(name=cmd_alert, file=modules\cmd_alert.jar, provider=JenkinsModuleSource())
09:49:14 [INFO] Discovered module: ModuleSpec(name=cmd_find, file=modules\cmd_find.jar, provider=JenkinsModuleSource())
09:49:14 [INFO] Discovered module: ModuleSpec(name=cmd_list, file=modules\cmd_list.jar, provider=JenkinsModuleSource())
09:49:14 [INFO] Discovered module: ModuleSpec(name=cmd_send, file=modules\cmd_send.jar, provider=JenkinsModuleSource())
09:49:14 [INFO] Discovered module: ModuleSpec(name=cmd_server, file=modules\cmd_server.jar, provider=JenkinsModuleSource())
09:49:14 [INFO] Discovered module: ModuleSpec(name=reconnect_yaml, file=modules\reconnect_yaml.jar, provider=JenkinsModuleSource())
09:49:14 [INFO] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.12-SNAPSHOT:79cd077:1309 by SpigotMC
09:49:14 [WARNING] Error enabling plugin LuckPerms
java.lang.NoClassDefFoundError: org/bukkit/plugin/java/JavaPlugin
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:34)
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:27)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:304)
	at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:212)
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:268)
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:56)
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: java.lang.ClassNotFoundException: org.bukkit.plugin.java.JavaPlugin
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:53)
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:27)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 18 more

**Comment by Andre601** [comment]
> Post it to **pastebin** and then send the link here :)

Reading messages is a good thing.

**Comment by meandpiggy** [comment]
lucko Where can I find that?

**Comment by meandpiggy** [comment]
Oh... Nevermind. I found the link you posted! :D

**Comment by lucko** [comment]
At the link I provided

**Comment by meandpiggy** [comment]
Can you please close this now? IDK how to. I'm new to GitHub.

**Comment by meandpiggy** [comment]
Wait nvm. I know how to now.
