### ISSUE TITLE
BotAttack - LuckPerms (Process Login)

### ISSUE THREAD

**Issue by Gasha666** [lucko/LuckPerms#967]
I'm using AntiBotDeluxeEx which blocking joining of bots, but LuckPerms still process login, an add bot into database, i few days ago i had ultra strong bot attack 635.000 bots, filled everything..LuckPerms breaked completely, i remove all old data, and everything was fine until today, again bot attack and again luckperms login proces and create huge lag, kick all players from server because processing login of bots that never really entered the server

https://pastebin.com/Rxk9etzm

Server version Latest PaperSpigot (1.12.2)

**Comment by BrainStone** [comment]
Simplest solution is running the server in online mode. Or if it is behind a bungee, enabling the bungee mode in Spigot and IP-Forwarding on the Bungee, while also using a firewall

**Comment by lucko** [comment]
Just going to repeat what I've already said to you on Spigot:

> Your antibot plugin should be cancelling the connection before it is handled by LuckPerms.
LP is doing the correct thing here.

Permissions data has to be loaded during the pre-login event - this is the only asynchronous login event available.

Anti-bot plugins should be dropping the connection at a protocol level via netty before it is even handled by the Minecraft server's implementation. If the pre-login event is being called, your anti-bot plugin isn't working properly.
