### ISSUE TITLE
perms don't inherit on sponge/forge

### ISSUE THREAD

**Issue by Ironic8b498** [lucko/LuckPerms#968]
I am running LuckPerms-Sponge-4.1.93, on spongeforge-1.12.2-2611-7.1.0-BETA-2961. if I give the perm to a group as long as player is in that group works fine, when they rank up they lose all perms from parent group.

**Comment by meandpiggy** [comment]
Make sure that that the parent group inherits the lower group. use this command:

/lp group <Higher Group> parent add <Lower Group>

**Comment by BrainStone** [comment]
The issue at hand, as far as I can tell, seems to happen if the inheritance is very deep. Another user is experiencing a very similar issue and also has inheritance that goes very deep (5+ steps). 

As the other user complains, the permissions stop working randomly. So I’m guessing that entries of groups are dropped from the cache when they shouldn’t. It might be the case that the cache is too small as both also have a very large number of permissions.

**Comment by Ironic8b498** [comment]
[May04.txt](https://github.com/lucko/LuckPerms/files/1974146/May04.txt)
here is my export of my perms. I'm having trouble with the groups in the forge track, which are used on my Sponge server the rest are on Spigot servers

**Comment by lucko** [comment]
I need reproducible steps, ideally 😃 

The number of permissions / depth of inheritance shouldn't have an effect.

**Comment by Ironic8b498** [comment]
I gave you my luckperms.conf off the sponge/forge server, and a export of my perms, without users. If players are in same group perms are assigned to perms work, if they have to inherit the perm get message saying I don't have permission to use that command.

**Comment by lucko** [comment]
Could you give me a specific example?

I don't have time to analyse your setup for you, you need to show me exactly where the issue is, and I'll do my best to help.

**Comment by Ironic8b498** [comment]
works now must of been something in config I couldn't see since I deleted config and had plugin make new one and it works fine now
