### ISSUE TITLE
LagSpikes with GriefPrevention

### ISSUE THREAD

**Issue by Slind14** [lucko/LuckPerms#97]
https://gist.githubusercontent.com/Slind14/baf559256e8ae02c58ac57e5adde1af7/raw/0ef2ffa9d0528dc5e4ded7b08ed44ea35e30c890/gistfile1.txt

Version: 2.16.48
GP Build: 199

**Comment by lucko** [comment]
Need more info - that log doesn't really give me much to work from. :/

**Comment by Slind14** [comment]
What kind of information do you need. I don't know what better than a thread dump I could give you.

**Comment by lucko** [comment]
Looks like a circular inheritance issue.

It's querying an inheritance loop 27 times. I'll look into it later - LuckPerms should prevent it.

**Comment by Slind14** [comment]
I just made sure that there are no inheritance loops. But there are inheritances of +30 groups, which I asked you about on the sponge forums if you remember ;)

```
default
	member

jrmod
	default

mod
	jrmod

srmod 
	mod

jradmin
	perms_admin
	srmod

admin
	perms_admin
	jradmin

manager
	perms_admin
	admin

director
	perms_admin

founder
	perms_admin

fakeco-admin
	mod

fakeadmin
	fakeco-admin



tier1
	default

tier2
	tier1

tier3
	tier2

tier4
	tier3

tier5
	tier4


player02
	default

player03
	player02

player04
	player03

[...]
```

**Comment by lucko** [comment]
Woops.

I made a mistake with my inheritance caching system. It was using up lots of memory and not actually caching anything. 😢 

This also explains the issues with memory footprint.
