### ISSUE TITLE
Groups n' stuff [SUGGESTION]

### ISSUE THREAD

**Issue by meandpiggy** [lucko/LuckPerms#970]
Hey, I was wondering if you could add a feature in which when you move a user to a group, they get a message like this in chat:

---------------------------------------------------
---------------------------------------------------
You have been moved to {GROUP}
---------------------------------------------------
---------------------------------------------------
Kind of like on Hypixel. Is it already added? If it is, can you please tell me how to activate it?

**Comment by Andre601** [comment]
I'm pretty sure Luck won't add that.
It doesn't really add anything that would improve LP in a positive way.

**Comment by meandpiggy** [comment]
@Andre601 That's negative, very negative. I just want a feature like on Hypixel! Does LuckPerms do this? Someone, please, tell me.

**Comment by Andre601** [comment]
> Does LuckPerms do this? 

No. It doesn't
And like I mentioned earlier
> It doesn't really add anything that would improve LP in a positive way.

Only because Hypixel has that doesn't mean LuckPerms need that.

**Comment by BrainStone** [comment]
LuckPerms provides an API, you could simply write a plugin that shows these messages. But I agree, this does not belong in a permission plugin.

**Comment by lucko** [comment]
These sort of messages are out-of-scope for the plugin in my opinion, but as Brainstone said, this is possible to add using the API.

**Comment by Andre601** [comment]
On the wiki.

**Comment by lucko** [comment]
These are the events you need

https://github.com/lucko/LuckPerms/tree/master/api/src/main/java/me/lucko/luckperms/api/event/node
https://github.com/lucko/LuckPerms/tree/master/api/src/main/java/me/lucko/luckperms/api/event/user/track
