### ISSUE TITLE
All list/search commands are broken

### ISSUE THREAD

**Issue by voodootje0** [lucko/LuckPerms#972]
LP version: 4.1.100

`/lp group owner listmembers` error
https://haste.jartexnetwork.com/curunetonu.sql

`/lp search group.owner` error
https://haste.jartexnetwork.com/awahuwujes.sql

Using mysql 5.7.21, and query ``SELECT * FROM `luckperms_user_permissions` WHERE `permission` LIKE 'group.owner'`` just works in command line.

**Comment by BrainStone** [comment]
I can confirm.

Shouldn’t that be prepared statements? To prevent against SQL injection etc

**Comment by lucko** [comment]
Yes they should.
