### ISSUE TITLE
Luckperms Web Editor Down

### ISSUE THREAD

**Issue by CDAGaming** [lucko/LuckPerms#973]
Each link to go to the editor, come back as 404 error

**Comment by Andre601** [comment]
[The editor is fine...](https://luckperms.github.io/editor/)
What version of LP are you using?

**Comment by CDAGaming** [comment]
https://ci.lucko.me/job/LuckPerms/652/
This build

**Comment by CDAGaming** [comment]
nvm now its working, guess i cant open one from console

**Comment by Andre601** [comment]
If you're using multicraft for managing servers, then it's their issue.
Because multicraft does for no reason remove the `?` in the link. And that messes stuff up.

**Comment by CDAGaming** [comment]
Ah, yea, that would be why xD

**Comment by CDAGaming** [comment]
Thay count that as a "special character", same as You cant do I'll bc the comma is also a "special character"
