### ISSUE TITLE
Add username set to migration

### ISSUE THREAD

**Issue by voodootje0** [lucko/LuckPerms#974]
Currently, I'm transferring, migration and importing lots of different servers from group manager into one global luckperms database. For this 9/10 times I'm using phpmyadmin to bulk edit lots of wrong permissions, rename groups, set server names etc. However I'm missing one thing that I cannot do myself, and that is also transferring the uuid <-> username data
![image](https://user-images.githubusercontent.com/6852308/39668453-6e7f7750-50ce-11e8-8a42-e14dd9977911.png)
after an migration being done, the listmembers will almost be filled with uuids only. It would be really nice if there will be an migration option/command available where the username will be set on migration import. 

The `use-server-uuid-cache` won't work for me since I am dealing with offline uuids, so the mojang lookup won't work. 

If you have any other idea how to fix this, maybe even without any modify towards the plugin, that would be really amazing.

**Comment by lucko** [comment]
https://github.com/lucko/LuckPerms/blob/d3dded879150420374c86b283403b7ebaf0dd358/bukkit/src/main/java/me/lucko/luckperms/bukkit/migration/MigrationGroupManager.java#L172-L175

https://github.com/lucko/LuckPerms/blob/d3dded879150420374c86b283403b7ebaf0dd358/bukkit/src/main/java/me/lucko/luckperms/bukkit/migration/MigrationGroupManager.java#L238


LP will migrate the username if it is known by GroupManager - not much I can do beyond that.

**Comment by voodootje0** [comment]
Sorry, I don't mean migration. Migration works perfectly with usernames and GroupManager. I meant exporting so that an export will also contain the username and not only use the uuid.

**Comment by lucko** [comment]
Oh right, yeah it's not easily possible for that data to be included in the imports/exports, as there is no command to initialise a new user with a uuid/username.
