### ISSUE TITLE
I guess problems with inherited groups

### ISSUE THREAD

**Issue by RubenStryker** [lucko/LuckPerms#975]
I have a problem that persists, I have created 3 groups:
Users, Veterans and hunters.

Permissions for users:
towny_maxplots.6

Permissions for veterans:
towny_maxplots.10
towny_maxplots.6 (false)
group.users

Permissions for hunters:
towny_maxplots.13
towny_maxplots.10 (false)
group.veteran

The fact is that veterans can not have more than 6 plots and hunters are alerted that they can not have 6 or 10 plots (the latter is random)

In the verbose, I do not see the node towny_maxplots

**Comment by lucko** [comment]
If you don't see the node in verbose, then Towny isn't actually checking for it.
