### ISSUE TITLE
LP isn't able to connect to Redis

### ISSUE THREAD

**Issue by LuconianCraft** [lucko/LuckPerms#976]
I tried to set up Redis with LuckPerms on Spigot (v4.1.102) and getting this error:
https://hastebin.com/jayejapoku.pl

Something similar happens with LuckPerms on BungeeCord (v4.1.102):
https://hastebin.com/leheberaqi.vbs

Any possibility to fix this?

**Comment by lucko** [comment]
Fixed in d3dded879150420374c86b283403b7ebaf0dd358
