### ISSUE TITLE
Latest LuckPerms is refusing to start

### ISSUE THREAD

**Issue by Foorack** [lucko/LuckPerms#977]
![ekrankopio de 2018-05-06 15-49-12](https://user-images.githubusercontent.com/5008081/39674356-d19b7f56-514a-11e8-92d7-82ecb288d946.png)

**Comment by Foorack** [comment]
Actually, looks like it's related to https://github.com/lucko/LuckPerms/issues/977

**Comment by Andre601** [comment]
> Actually, looks like it's related to #977

referring to your own issue?

**Comment by voodootje0** [comment]
#976

**Comment by Foorack** [comment]
@Andre601 I meant https://github.com/lucko/LuckPerms/issues/976 lol

**Comment by lucko** [comment]
Fixed in d3dded879150420374c86b283403b7ebaf0dd358
