### ISSUE TITLE
Cant do anything, luckperms.* doesnt work

### ISSUE THREAD

**Issue by turtleisaac1** [lucko/LuckPerms#979]
I am setting up my server and i added this plugin to control permissions, and in my console i am typing in the commands for giving me permissions and everything, and none of them work. i cant do anything and it is very annoying. please help

**Comment by turtleisaac1** [comment]
i only have luckperms installed. i used /lp user turtleisaac permission set luckperms.*  , and every video i watch says to do that, but it doesnt work

**Comment by BrainStone** [comment]
Doesn't work means what exactly? What happens when you execute the command?

**Comment by merjilin** [comment]
You to be sure, if you're running a sponge server please use `/lp user turtleisaac permission set luckperms true`.

By default `.*` does nothing on sponge without enabling wildcard support in the luckperms config.

**Comment by Andre601** [comment]
Also, run that command in the console.
If you don't have permission for the command, then obviously you can't use it, to ser the required perms.
