### ISSUE TITLE
"Similar to" constraint with web editor.

### ISSUE THREAD

**Issue by andrewkm** [lucko/LuckPerms#981]
Not sure if this is possible or not.
I've read the documentation on the wiki and don't believe so, but do correct me if I am wrong.

I am looking for a way to use the "similar to" constraint with the web editor? Have about  a hundred groups, with 40-50 being named "main_<group>" and would like the editor to target all groups starting with "main".

Perhaps:
`/lp group "group ~~ main%" editor`

Unsure how this would work if even considered, or if it's something that's already possible.

Cheers for any help :)

**Comment by BrainStone** [comment]
You can just use `/lp editor`. That'll let you edit all groups

**Comment by andrewkm** [comment]
@BrainStone that has nothing to do with this ticket.

**Comment by BrainStone** [comment]
Just wanted to point that out. ;)
