### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by kuzbear** [lucko/LuckPerms#984]
Hey man love the plugin, straight forward and a great replacement for pex.

something I'm new to is the MySQL database stuff for plugins and dont quite understand how to get it working, I have bungeecord, I have 3 servers(skyblock, hub, test). Atm im getting them ready to host, now I would like staff perms to be handled by hub so that they are global and i dont have to add them on each server. for some reason on my test server its not getting the global perms or prefix's. 

I have hub set as global, skyblock set as global(for now because with this issue my friends that are building that server weren't able to get the perms) and test set to test. sometimes the perms work depending but the prefix doesnt.

sorry about the messy explanation.

**Comment by lucko** [comment]
Is everything connected up to the same database?

**Comment by kuzbear** [comment]
Yes it is.

**Comment by kuzbear** [comment]
Okay so this morning I jumped on when i woke up, and jumped on the test server and look at the permissions of the group on that server, its coming up with all the perms of the group so it is loading that by the looks, its just not loading the prefix's

**Comment by lucko** [comment]
Sorry for the delay in replying, I've had quite a busy week, and this just slipped by me :)

It's unlikely that prefix data in particular would be skipped. It's all stored in exactly the same section of the MySQL database, and is all loaded at the same time.

Are you sure the data is actually there? Any errors in console?
