### ISSUE TITLE
LuckPerms API?

### ISSUE THREAD

**Issue by meandpiggy** [lucko/LuckPerms#985]
I was recently told by lucko himself that the plugin has an API, I was told that with this API, I could add group join/leave messages. Please tell me how to add them and give me a little bit more info on it! Thanks!

**Comment by lucko** [comment]
The API is documented here: https://github.com/lucko/LuckPerms/wiki/Developer-API

To use it, you need to be able to develop your own Bukkit plugin to make use of it. I suggest perhaps trying to find someone on the Spigot services forum who might be able to do it for you, if you don't know how to program yourself.
