### ISSUE TITLE
What is this: different uuid

### ISSUE THREAD

**Issue by LapizSeller** [lucko/LuckPerms#988]
I'm just migration from Zpermission to Luckperms 4.2.2
When some players login to Hub (with Authme), it show something like this:
i'm sure  ip-forwarding: true in bungeecord
and bungeecord: true in spigot
> [13:28:29] [User Authenticator #7355/INFO]: [WARN] LuckPerms already has data for player 'Gcafe' - but this data is stored under a different uuid.
[13:28:29] [User Authenticator #7355/INFO]: [WARN] 'Gcafe' has previously used the unique ids [b59ad395-4771-3196-b7ef-df2a71875fe3] but is now connecting with '1933c20d-daf3-3b17-abdc-2453005ab0e4'
[13:28:29] [User Authenticator #7355/INFO]: [WARN] This is usually because the server is not authenticating correctly. If you're using BungeeCord, please ensure that IP-Forwarding is setup correctly!
[13:28:29] [User Authenticator #7355/INFO]: UUID of player Gcafe is 1933c20d-daf3-3b17-abdc-2453005ab0e4

What is it? how to fix it? is it can cause any seriously problems?

**Comment by merjilin** [comment]
Like the message states, you have not configured IP-forwarding correctly. This can cause serious damage to your server, as data stored in plugins that use UUIDs will no longer function as intended.

To rectify this, enable ip-forwarding in your bungeecord config and enable bungeecord in your spigot.yml.

**Comment by LapizSeller** [comment]
@merjilin
 i'm sure  ip-forwarding: true in bungeecord
and bungeecord: true in spigot

**Comment by merjilin** [comment]
To me, this seems more like an AuthMe issue. Their offline UUIDs (what AuthMe provides LuckPerms) should match is Author is doing it's job correctly.

**Comment by lucko** [comment]
> [13:28:29] [User Authenticator #7355/INFO]: [WARN] 'Gcafe' has previously used the unique ids [b59ad395-4771-3196-b7ef-df2a71875fe3] but is now connecting with '1933c20d-daf3-3b17-abdc-2453005ab0e4'

Neither of those uuids are "valid" according to https://namemc.com/

This isn't an LP problem, rather an issue with your IP forwarding settings and/or any "premium" login plugins, such as FastLogin, etc
