### ISSUE TITLE
Command execution problem

### ISSUE THREAD

**Issue by hohserg1** [lucko/LuckPerms#989]
When I try to use /lp command:
https://pastebin.com/UyGVCNAL

I use guava-17.0

Thanks in advance.

**Comment by merjilin** [comment]
Can you please update to the latest bukkit build from here: https://luckperms.github.io/ and tell us if the issue is still there please :)

**Comment by lucko** [comment]
Try with the legacy version   
https://ci.lucko.me/job/LuckPermsLegacy/

Your server implementation seems to be screwing around with the way dependencies are loaded, so if the legacy build doesn't work, I suggest reporting it to them.

**Comment by hohserg1** [comment]
I have forgotten to specify - version 1.7.10
