### ISSUE TITLE
Issue with perma all permissions

### ISSUE THREAD

**Issue by sekwah41** [lucko/LuckPerms#991]
The function removeAttachment doesnt seem to function properly (works in other permissions such as PermissionsEx) and the player is stuck with full permissions from the below code at least.

I am currently working on a recode however this code from the old builds should still be valid and I am pretty sure it is also how commandsigns does this too so it is a larger issue possibly.

Example of code that triggers the problem
`try {
    permissionAttachment = player.addAttachment(plugin, "*", true);
    player.chat("/" + command);
} finally {
    player.removeAttachment(permissionAttachment);
 }`

One of my users was having trouble with this and using LuckPerms as the permission manager

**Comment by Phoenix616** [comment]
Can confirm that this is happening on the latest development build. The permission stays only attached until the next logout. (so it's not added to the LuckPerms permissions, just looks like the removal is either broken or doesn't like that it happens in the same tick)

**Comment by sekwah41** [comment]
Is this an issue specifically with * being removed or any permissions being removed after the permission node has been added?

**Comment by Phoenix616** [comment]
Seems to be happening with any permission.

**Comment by lucko** [comment]
The latter, should be fixed now

**Comment by Phoenix616** [comment]
Looks good, thanks!
