### ISSUE TITLE
Luckperms maximum-lifetime and Mysql wait-timeout

### ISSUE THREAD

**Issue by LapizSeller** [lucko/LuckPerms#992]
Today my server crash by luckperms with this error:
https://paste.ubuntu.com/p/HDW7RPShTT/
i'm search and found this page
https://github.com/lucko/LuckPerms/wiki/Storage-system-errors
On my server, Luckperms (Ver 4.2.2) maximum-lifetime is default (30 minutes) and Mysql wait-timeout is 43200 (12 hours) as you can see in here
mysqld --verbose --help: https://paste.ubuntu.com/p/gNf3ZXqPWV/
 i'm config correctly  why error still happen? 
i have 6 servers run Luckperms connect to same database, but only 1 server happen this issue. Don't know why.

**Comment by lucko** [comment]
I'm not sure, although the error you linked wasn't the cause of the server crashing, it might be *because of* it crashing?

**Comment by LapizSeller** [comment]
Yes, it's not crash, just disconnect all players and make players can't play.
Is `connect-timeout                                            5` related to this issue?

**Comment by LapizSeller** [comment]
today it happen again, don't know why only this server facing this issue, other (5 servers, same config) don't  has this issue.

**Comment by lucko** [comment]
As I said, 

> the error you linked wasn't the cause of the server crashing, it might be because of it crashing

Most likely another plugin lagging the server, causing connections to be dropped, and the LP database pool to report a lapse in system time

I'm pretty sure this is unrelated to LuckPerms
