### ISSUE TITLE
Website Editor Not Support Chinese Words

### ISSUE THREAD

**Issue by coco0325** [lucko/LuckPerms#994]
Chinese words will become garbled in website editor.
Please fix this.
Thanks~

**Comment by lucko** [comment]
Everything is encoded with UTF-8, so I don't know why that would be a problem.

**Comment by lucko** [comment]
Can you show an example?

**Comment by coco0325** [comment]
[https://cdn.discordapp.com/attachments/399093265468489757/445949720578490380/unknown.png](url)

**Comment by coco0325** [comment]
name: admin
permissions:
- holograms.*
- multiverse.teleport.self.*
- skillapi.*
- quests.*
- worldguard.*
- worldedit.*
- citizens.*
- shopkeeper.*
- libsdisguises.disguise.*
- fmb.bypass
- griefprevention.eavesdrop
- griefprevention.ignoreclaims
- Kycraft.kyc
- mythicmobs.admin
- weight.5
parents:
- default
- staff
prefixes:
- '&d✿&7【行政】&b':
    priority: 5
meta:
- default:
    value: 'false'

**Comment by lucko** [comment]
Working for me 😕 

![](https://luck.sh/BhETRSSclyX3A1wck9le6Ss95mI=)
![](https://luck.sh/32hj_MPSagKLsu_5SXOdBwJXvT4=)

https://luckperms.github.io/editor/?A0RDCGGXmd

**Comment by coco0325** [comment]
Maybe I can try it more and then tell you✅

**Comment by lucko** [comment]
Let me know how it goes :)

**Comment by lucko** [comment]
Windows, Java 8

**Comment by 8MiYile** [comment]
修改数据库编码为UTF-8即可解决此问题
Fix this by changing the database encoding to utf-8

**Comment by lucko** [comment]
This is already the case.
