### ISSUE TITLE
PermissionsEx-Sponge-LPConvert.jar unable to migrate.

### ISSUE THREAD

**Issue by TheTechBandit** [lucko/LuckPerms#996]
I am trying to migrate from PermissionsEx to LuckPerms since PEX no longer seems to work in 1.12.2.
Versions:
Forge:  forge-1.10.2-12.18.3.2511-universal
Sponge: spongeforge-1.10.2-2281-5.2.0-BETA-2578
LuckPerms: LuckPerms-Sponge-4.2.2
PermissionsEx: PermissionsEx v2.0-SNAPSHOT-b147
PermissionsEx-Sponge-LPConvert: PermissionsEx v2.0-SNAPSHOT-b146
Nucleus: Nucleus-1.1.0-S5.1-MC1.10.2-plugin

Loading the server with both the converter and our regular version of PEX causes the server to crash because it sees them as "duplicate mods." However, the server is fine if I have them installed individually. The same thing will happen when either regular PEX or the converter is installed: Both PEX and  LP seem to load correctly, and commands from both plugins work, as shown below. However, the /lp migration command will not see any plugins to migrate from.

![stuff](https://user-images.githubusercontent.com/32079837/39961635-a5ddfbba-5608-11e8-95d1-c4a16518a877.PNG)

It should also be noted that LP clearly recognizes in the log that PEX is loaded.

![stuff2](https://user-images.githubusercontent.com/32079837/39961696-ccd97c52-5609-11e8-8376-960450989565.PNG)

I can send the log/fml-log if needed.

**Comment by TheTechBandit** [comment]
Fixed! I just simply had to change to  an earlier version of LP. I used LuckPerms-Sponge-3.4.17 and it worked.

**Comment by lucko** [comment]
It was intentionally removed in newer versions
