### ISSUE TITLE
Permission Migration

### ISSUE THREAD

**Issue by Vendittii** [lucko/LuckPerms#997]
So I have the MySQL tables already set up, I'm adding a new server to my network (Factions), I want to migrate the permissions from PEX to LP. I need to make it so all the migrated permissions on Factions Server are only on the factions server, how would I go about doing this?

**Comment by Vendittii** [comment]
Edit - The group names are the same, I need the ranks to transfer server wide.

**Comment by Andre601** [comment]
One way to do it is to export the data you have into a file (`/lp export [filename]`) and edit it, by adding `server=<server>` at the end of the permissions, that should be added per server.
I hope that makes sense.

**Comment by merjilin** [comment]
The quickest and more efficient way would be the following:
1) Have the migration occur on a dev server which is not connected to your other servers 
2) Use bulkupdate to change the context from global to the server you wish. Command would be this ` /lp bulkupdate all update server <factions name> "server == global"` and must be done in console.

**Comment by Vendittii** [comment]
For future reference ( Thanks again) 


/lp export permissions grab the file it generates and put it on the factions server and run /lp import permissions
