### ISSUE TITLE
Error creating tracks with MySQL storage

### ISSUE THREAD

**Issue by alexstaeding** [lucko/LuckPerms#998]
~~Using LuckPerms-Sponge-4.1.7.jar~~ **Edit: Issue persists with latest version: v4.2.6**

Hi, I'm currently in the process of migrating my server from YAML storage to MySQL storage and everything seems to be working fine. I created a backup of the YAML data using `/lp export initialBackup` and this worked fine.

However, on import, the following error appears in the console:

    [16:36:39] [pool-3-thread-41/INFO]: [LP] (Import) ------------> Showing Error #120 <------------
    [16:36:39] [pool-3-thread-41/INFO]: [LP] (Import) Whilst executing: Command #120
    [16:36:39] [pool-3-thread-41/INFO]: [LP] (Import) Command: createtrack default
    [16:36:39] [pool-3-thread-41/INFO]: [LP] (Import) Type: FAILURE
    [16:36:39] [pool-3-thread-41/INFO]: [LP] (Import) Output:
    [16:36:39] [pool-3-thread-41/INFO]: [LP] (Import) <------------------------------------------>

This causes a bunch of errors later in the import because the track could not be found, and hence the groups can not be appended to them.

I tried running `/lp createtrack default` to fix the issue, but the following error comes up:

    [16:37:07] [Server thread/INFO] [nucleus]: Server ran the command: /lp createtrack default
    [16:37:07] [pool-4-thread-1/INFO] [STDERR]: 
    [me.lucko.luckperms.common.command.CommandManager:execute:206]: 
    java.util.concurrent.CompletionException: 
    me.lucko.luckperms.lib.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in 
    your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax 
    to use near 'groups FROM luckperms_tracks WHERE name='default'' at line 1

The full error is [here](https://pastebin.com/v1ibZHDg)

**Comment by merjilin** [comment]
Could you update to the latest sponge build here please and try the import again https://luckperms.github.io/

Make sure to erase your previous data as the import command simply imports the permissions again on top of the existing data

**Comment by lucko** [comment]
Looks like an invalid schema of some sort

You could try recreating the table, using the schema defined here:
https://github.com/lucko/LuckPerms/blob/20f992110d1d8bff8bdf252bc159e918d9788ef4/common/src/main/resources/me/lucko/luckperms/schema/mysql.sql#L56-L60

or updating your MySQL server instance to the latest version.

Aside from that, I'm not sure what to suggest. I don't think it's being caused by a bug in LP.

**Comment by lucko** [comment]
Yes, tested and working fine.

The code uses PreparedStataments, it's up to the driver to convert that into queries to send to the server.

**Comment by alexstaeding** [comment]
I came across [this](https://github.com/lucko/LuckPerms/issues/877) which seems to be the exact issue I had.

As per the suggestion, I installed MariaDB and have managed to get it all working :)

I guess the solution was to not use MySQL but MariaDB instead.
