### ISSUE TITLE
Incorrect group config saving after upgrade from LuckPerms Sponge 4.1.54 to 4.2.2

### ISSUE THREAD

**Issue by braunly** [lucko/LuckPerms#999]
I am using JSON storage type.
All meta keys have `null` values
Only for group, that i edited with `/lp group <group> permission set` command after upgrade
Config was saved on 4.1.54 version and edited on 4.2.2
Config file was
```
{
  "name": "moderators",
  "permissions": [
    "some.perm.*",
  ],
  "parents": [
    "helpers"
  ],
  "meta": [
    {
      "prefix": {
        "value": "&d"
      }
    },
    {
      "suffix": {
        "value": " &f[Moder]"
      }
    }
  ]
}
```

And now it looks like
```
{
  "name": "moderators",
  "permissions": [
    {
      "permission": "some.perm.*"
    }
  ],
  "parents": [
    {
      "group": "helpers"
    }
  ],
  "meta": [
    {
      "key": "prefix"
    },
    {
      "key": "suffix"
    }
  ]
}
```
SpongeForge 1.12.2-2655-7.1.0-BETA-3058

**Comment by lucko** [comment]
Thanks for reporting, this is resolved in the latest version :)

https://luckperms.github.io/
